Repository metabase/metabase, pull requests merged in 2018-04, with the labels that each got.

#6855 Add latest and earliest to datetime fingerprints
  frontend/test/__runner__/test_db_fixture.db.h2.db
  frontend/test/services/__snapshots__/MetabaseApi.integ.spec.js.snap
  src/metabase/sync/analyze/fingerprint.clj
  src/metabase/sync/analyze/fingerprint/datetime.clj
  src/metabase/sync/interface.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/query_processor/expand_resolve_test.clj
  test/metabase/query_processor_test.clj
  test/metabase/sync/analyze/fingerprint/datetime_test.clj
  test/metabase/sync/analyze/fingerprint_test.clj
Labels: Metadata/Sync

#7237 Hide deleted columns
  src/metabase/models/table.clj
  test/metabase/sync/sync_metadata/fields_test.clj
Labels: CLA/Signed

#7382 Docs for 0.29 (WIP)
  docs/administration-guide/03-metadata-editing.md
  docs/administration-guide/images/filter-options.png
  docs/users-guide/05-visualizing-results.md
  docs/users-guide/08-dashboard-filters.md
  docs/users-guide/10-pulses.md
  docs/users-guide/14-x-rays.md
  docs/users-guide/images/dashboard-filters/autocomplete.png
  docs/users-guide/images/dashboard-filters/dashboard-filters.png
  docs/users-guide/images/dashboard-filters/list.png
  docs/users-guide/images/dashboard-filters/multi-select.png
  docs/users-guide/images/dashboard-filters/search-options.png
  docs/users-guide/images/pulses/table.png
  docs/users-guide/images/visualizations/row.png
  docs/users-guide/images/x-rays/data-reference.png
  docs/users-guide/images/x-rays/drill-through.png
  docs/users-guide/images/x-rays/example.png
  docs/users-guide/images/x-rays/suggestions.png
Labels: Documentation
