Repository metabase/metabase, pull requests merged in 2019-12, with the labels that each got.

#11407 Log handle nil status
  src/metabase/middleware/log.clj
  test/metabase/middleware/log_test.clj
Labels: .Backend, Type:Bug

#11423 Warn when asking radio's to underline with no value
  frontend/src/metabase/components/Radio.jsx
Labels: .Frontend

#11051 fixed small error
  README.md
Labels: .CLA Signed

#11539 Whack a React warning
  frontend/src/metabase/nav/containers/Navbar.jsx
Labels: .Frontend

#11540 Update docs for 0.34
  docs/users-guide/05-visualizing-results.md
  docs/users-guide/13-sql-parameters.md
  docs/users-guide/images/SQL-filter-widget.png
  docs/users-guide/images/SQLInterface.png
  docs/users-guide/writing-sql.md
Labels: .Documentation
