Repository metabase/metabase, pull requests merged in 2019-01, with the labels that each got.

#9054 Docs for customizing drill-through
  docs/README.md
  docs/administration-guide/06-collections.md
  docs/administration-guide/10-single-sign-on.md
  docs/administration-guide/14-caching.md
  docs/administration-guide/15-whitelabeling.md
  docs/administration-guide/16-authenticating-with-saml.md
  docs/administration-guide/17-data-sandboxes.md
  docs/administration-guide/18-authenticating-with-jwt.md
  docs/administration-guide/start.md
  docs/enterprise-guide/authenticating-with-jwt.md
  docs/enterprise-guide/authenticating-with-saml.md
  docs/enterprise-guide/customizing-drill-through.md
  docs/enterprise-guide/data-sandboxes.md
  docs/enterprise-guide/images/JWT-auth-form.png
  docs/enterprise-guide/images/customizing-drill-through/chart-link-template.png
  docs/enterprise-guide/images/customizing-drill-through/column-settings.png
  docs/enterprise-guide/images/customizing-drill-through/dashboard-link-template.png
  docs/enterprise-guide/images/customizing-drill-through/detail-dashboard.png
  docs/enterprise-guide/images/customizing-drill-through/example-charts.png
  docs/enterprise-guide/images/customizing-drill-through/link-option.png
  docs/enterprise-guide/images/customizing-drill-through/table-options-filled.png
  docs/enterprise-guide/images/saml-form.png
  docs/enterprise-guide/images/sandboxing/advanced-example-1-filtering-question.png
  docs/enterprise-guide/images/sandboxing/advanced-example-1-people-table.png
  docs/enterprise-guide/images/sandboxing/advanced-example-1-results.png
  docs/enterprise-guide/images/sandboxing/advanced-example-1-sandbox-modal.png
  docs/enterprise-guide/images/sandboxing/advanced-example-2-filtering-question.png
  docs/enterprise-guide/images/sandboxing/advanced-example-2-orders-table.png
  docs/enterprise-guide/images/sandboxing/advanced-example-2-results.png
  docs/enterprise-guide/images/sandboxing/advanced-example-2-sandboxing-options.png
  docs/enterprise-guide/images/sandboxing/advanced-example-2-user-attributes.png
  docs/enterprise-guide/images/sandboxing/change-access-confirm-modal.png
  docs/enterprise-guide/images/sandboxing/edit-sandboxed-access.png
  docs/enterprise-guide/images/sandboxing/edit-user-details.png
  docs/enterprise-guide/images/sandboxing/filtered-pie-chart.png
  docs/enterprise-guide/images/sandboxing/filtered-table.png
  docs/enterprise-guide/images/sandboxing/grant-sandboxed-access.png
  docs/enterprise-guide/images/sandboxing/select-user-attribute.png
  docs/enterprise-guide/start.md
  docs/enterprise-guide/whitelabeling.md
  docs/users-guide/15-alerts.md
Labels: Documentation

#9211 Add apple touch icons
  resources/frontend_client/app/assets/img/android-chrome-192x192.png
  resources/frontend_client/app/assets/img/android-chrome-256x256.png
  resources/frontend_client/app/assets/img/apple-touch-icon.png
  resources/frontend_client/app/assets/img/browserconfig.xml
  resources/frontend_client/app/assets/img/favicon-16x16.png
  resources/frontend_client/app/assets/img/favicon-32x32.png
  resources/frontend_client/app/assets/img/favicon.ico
  resources/frontend_client/app/assets/img/mstile-150x150.png
  resources/frontend_client/app/assets/img/safari-pinned-tab.svg
  resources/frontend_client/app/assets/img/site.webmanifest
  resources/frontend_client/index_template.html
Labels: CLA/Signed

#9092 xray i18n fixes
  resources/automagic_dashboards/comparison/Country.yaml
  resources/automagic_dashboards/comparison/FK.yaml
  resources/automagic_dashboards/comparison/GenericField.yaml
  resources/automagic_dashboards/comparison/State.yaml
  resources/automagic_dashboards/field/Country.yaml
  resources/automagic_dashboards/field/DateTime.yaml
  resources/automagic_dashboards/field/GenericField.yaml
  resources/automagic_dashboards/field/State.yaml
  resources/automagic_dashboards/metric/GenericMetric.yaml
  resources/automagic_dashboards/question/GenericQuestion.yaml
  resources/automagic_dashboards/table/GenericTable.yaml
  resources/automagic_dashboards/table/GenericTable/Correlations.yaml
  resources/automagic_dashboards/table/GoogleAnalyticsTable.yaml
  resources/automagic_dashboards/table/TransactionTable.yaml
  resources/automagic_dashboards/table/TransactionTable/ByCountry.yaml
  resources/automagic_dashboards/table/TransactionTable/ByProduct.yaml
  resources/automagic_dashboards/table/TransactionTable/BySource.yaml
  resources/automagic_dashboards/table/TransactionTable/ByState.yaml
  resources/automagic_dashboards/table/TransactionTable/Seasonality.yaml
  resources/automagic_dashboards/table/UserTable.yaml
  src/metabase/automagic_dashboards/core.clj
Labels: X-Rays, i18n
