Repository metabase/metabase, pull requests merged in 2020-09, with the labels that each got.

#13256 Fix failing smoke test related to admin's ability to manage sub-collections
  frontend/test/metabase-smoketest/admin_setup.cy.spec.js
Labels: .CI & Tests

#13265 Migrate `EntityMenuItem` test from enzyme to react-testing-library
  frontend/test/metabase/components/EntityMenuItem.unit.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13264 Migrate `EntityMenuTrigger` test from enzyme to react-testing-library
  frontend/test/metabase/components/EntityMenuTrigger.unit.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13260 Add --keep-existing flag to dump-to-h2 command
  src/metabase/cmd.clj
  src/metabase/cmd/dump_to_h2.clj
Labels: .Enhancement, Operation/H2

#13276 Migrate `Button` test from enzyme to react-testing-library
  frontend/test/metabase/components/Button.unit.spec.js
  frontend/test/metabase/components/__snapshots__/Button.unit.spec.js.snap
Labels: .CI & Tests, .Tech Debt or Refactoring

#13269 Update and use consistent references to the issues in test reproductions
  frontend/src/metabase/components/Popover.css
  frontend/src/metabase/css/core/inputs.css
  frontend/test/__support__/cypress.js
  frontend/test/metabase-smoketest/admin.cy.spec.js
  frontend/test/metabase-smoketest/admin_setup.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/field.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/spinner.cy.spec.js
  frontend/test/metabase/scenarios/alert/email_alert.cy.spec.js
  frontend/test/metabase/scenarios/auth/search.cy.spec.js
  frontend/test/metabase/scenarios/auth/signin.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/text-box.cy.spec.js
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
  frontend/test/metabase/scenarios/question/new.cy.spec.js
  frontend/test/metabase/scenarios/question/trendline.cy.spec.js
  frontend/test/metabase/scenarios/question/view.cy.spec.js
  modules/drivers/bigquery/test/metabase/driver/bigquery/query_processor_test.clj
  modules/drivers/oracle/src/metabase/driver/oracle.clj
  src/metabase/api/user.clj
  src/metabase/util.clj
  test/metabase/task/send_pulses_test.clj
Labels: .CI & Tests, .Tech Debt or Refactoring, support/Repro

#13252 Repro for issue #13241
  frontend/test/__support__/cypress.js
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
Labels: .Already Fixed, .CI & Tests, support/Repro

#13286 Repro for #12762
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
Labels: .CI & Tests, support/Repro

#13296 Add e2e test for adding/connecting PostgreSQL database
  frontend/test/metabase-db/postgres/add.cy.spec.js
Labels: .CI & Tests, Database/Postgres

#13300 Repro for #13289
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
Labels: .CI & Tests, support/Repro

#13303 Add repro for #13263
  frontend/test/metabase-db/postgres/add.cy.spec.js
  frontend/test/snapshot-creators/default.cy.snap.js
Labels: .CI & Tests, Database/Postgres, support/Repro

#13308 Repro for #13022
  frontend/test/metabase/scenarios/admin/datamodel/metrics.cy.spec.js
Labels: .Already Fixed, .CI & Tests, support/Repro

#13312 Fix `snippet` Cypress error
  frontend/test/metabase/scenarios/question/snippets.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13323 Fix "editor-sorting-columns" Cypress error
  frontend/test/metabase/scenarios/admin/datamodel/editor.cy.spec.js
Labels: .CI & Tests

#13320 Add repro for #13306
  frontend/test/metabase/scenarios/question/new.cy.spec.js
Labels: .CI & Tests, support/Repro

#13322 Fix unix timestamp filter Cypress error
  frontend/test/metabase/scenarios/dashboard/parameters.cy.spec.js
Labels: .CI & Tests

#13307 Repro for #13000
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
Labels: .Already Fixed, .CI & Tests, support/Repro
