Repository metabase/metabase, pull requests merged in 2020-10, with the labels that each got.

#13339 Add repro for #13332
  frontend/test/metabase/scenarios/question/native.cy.spec.js
Labels: .CI & Tests, support/Repro

#13311 Feature/postgres cypress tests
  .circleci/config.yml
  frontend/test/metabase-db/postgres/add.cy.spec.js
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
  frontend/test/snapshot-creators/default.cy.snap.js
Labels: .CI & Tests, Database/Postgres

#13363 Add repro for #13069
  frontend/test/metabase/scenarios/admin/datamodel/metrics.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/segments.cy.spec.js
Labels: .CI & Tests, support/Repro

#13343 Upgrade Cypress to v5.3.0
  frontend/test/cypress.json
  frontend/test/metabase-smoketest/admin.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/metrics.cy.spec.js
  frontend/test/metabase/scenarios/setup/setup.cy.spec.js
  package.json
  yarn.lock
Labels: .CI & Tests, .Tech Debt or Refactoring

#13393 Fix Cypress CI Timeouts
  frontend/test/cypress.json
Labels: .CI & Tests, .Tech Debt or Refactoring

#13398 Revert Cypress upgrade (v5.3.0. -> v3.8.2)
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
  package.json
  yarn.lock
Labels: .CI & Tests, .Tech Debt or Refactoring

#13401 Remove Selenium and Karma
  .circleci/config.yml
  docs/developers-guide.md
  frontend/test/karma.conf.js
  frontend/test/legacy-karma/lib/dom.spec.js
  frontend/test/legacy-selenium/auth/login.spec.js
  frontend/test/metabase/lib/dom.unit.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
  jest.e2e.conf.json
  jest.integ.conf.json
  jest.tz.unit.conf.json
  jest.unit.conf.json
  package.json
  yarn.lock
Labels: .CI & Tests, .Tech Debt or Refactoring

#13021 E2e to cy/port/visualization
  frontend/test/metabase/scenarios/dashboard/text-box.cy.spec.js
  frontend/test/metabase/visualizations/components/Visualization.e2e.spec.js
Labels: .Tech Debt or Refactoring, support/Repro

#13013 E2e to cy/port/dashboard
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/parameters-embedded.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/parameters.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#12969 E2e to cy/port/alert
  frontend/test/__support__/cypress.js
  frontend/test/metabase/alert/alert.e2e.spec.js
  frontend/test/metabase/scenarios/alert/alert.cy.spec.js
  frontend/test/metabase/scenarios/alert/alert_auth.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13421 Fix Cypress flakes
  frontend/test/metabase-db/mongo/query.cy.spec.js
  frontend/test/metabase/scenarios/public/public.cy.spec.js
  frontend/test/metabase/scenarios/question/native.cy.spec.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
  frontend/test/metabase/scenarios/question/snippets.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13317 Repro for #11452
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
Labels: .CI & Tests, support/Repro

#13439 Add repro for #10829
  frontend/test/metabase/scenarios/dashboard/parameters.cy.spec.js
Labels: .CI & Tests, support/Repro

#13438 Attempt to fix flake in public.cy.spec.js
  frontend/test/metabase/scenarios/public/public.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13445 Fix "typing" flake for `admin > settings.spec.cy`
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13418 Convert e2e tests to Cypress
  .circleci/config.yml
  docs/developers-guide.md
  frontend/test/__runner__/run_e2e_tests.js
  frontend/test/__support__/cypress.js
  frontend/test/__support__/e2e.js
  frontend/test/metabase/admin/settings/SettingsAuthenticationOptions.e2e.spec.js
  frontend/test/metabase/alert/alert.e2e.spec.js
  frontend/test/metabase/collection/initial_collection.e2e.spec.js
  frontend/test/metabase/modes/components/drill/PivotByCategoryDrill.e2e.spec.js
  frontend/test/metabase/reference/segments.e2e.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/metadata.cy.spec.js
  frontend/test/metabase/scenarios/alert/alert.cy.spec.js
  frontend/test/metabase/scenarios/alert/alert_auth.cy.spec.js
  frontend/test/metabase/scenarios/collection_defaults.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/parameters-embedded.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/parameters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/text-box.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
  frontend/test/metabase/selectors/metadata.e2e.spec.js
  frontend/test/metabase/visualizations/components/Visualization.e2e.spec.js
  frontend/test/metabase/visualizations/drillthroughs.e2e.spec.js
  jest.e2e.conf.json
  package.json
Labels: .CI & Tests, .Tech Debt or Refactoring

#13497 Add Cypress metadata test for custom remapping
  frontend/test/metabase/scenarios/admin/datamodel/field.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/metadata.cy.spec.js
Labels: .CI & Tests

#13459 Add repro for #4506
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
Labels: .CI & Tests, support/Repro

#13506 Add repro for #13470
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
Labels: .CI & Tests, support/Repro

#13499 Add repro for #13469
  frontend/test/metabase/scenarios/question/new.cy.spec.js
Labels: .CI & Tests, support/Repro

#12219 Repro/dashboard searchbox permissions
  frontend/test/__support__/cypress.js
  frontend/test/metabase/scenarios/dashboard/dashboard_data_permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#12647 Repro for #12585
  frontend/test/metabase/scenarios/question/nulls.cy.spec.js
Labels: support/Repro

#12343 Cypress test for hidden tables
  frontend/test/metabase/scenarios/admin/datamodel/hide_tables.cy.spec.js
Labels: support/Repro

#12497 Cypress test for chart drill with date types
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
Labels: support/Repro

#12572 Repros #12568/#9802: Nested questions
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
Labels: support/Repro

#13517 Repro for #13504: Drill-through on Filtered Aggregated Results [ci skip]
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
Labels: .CI & Tests, support/Repro

#13555 Repro for #13534: Filter joined table on "Is not"/"Does not contain"
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#13557 Repro for #12649: Joins and custom column duplicate results
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
Labels: .CI & Tests, support/Repro

#13446 Docs - added first day of week option to localization docs page
  docs/administration-guide/localization.md
Labels: .Documentation

#13567 update language list
  docs/faq/general/what-languages-can-be-used-with-metabase.md
Labels: .Documentation

#13576 Repro for #13175: Arithmetic in Notebook
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
Labels: .CI & Tests, support/Repro

#13580 Repro for #13062: Multiple dashboard filter values not parsed on drill-through (numeric values)
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
Labels: .CI & Tests, support/Repro

#13589 Repro for #11007: Link dashboard filters to custom questions with filtered aggregate data
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, support/Repro

#13591 Repro for #13571: Display rows whose value is `null`
  frontend/test/metabase/scenarios/question/nulls.cy.spec.js
Labels: .CI & Tests, support/Repro

#13612 Fix failing Cypress test in `dashboard-drill` spec file
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13616 Fix Cypress flake in `admin/settings/settings` spec file
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13617 Update obsolete repro for #12985
  frontend/src/metabase/icon_paths.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13621 Fix Cypress flake in `admin/datamodel/metrics` spec file
  frontend/test/metabase/scenarios/admin/datamodel/metrics.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13637 Repro for #13098: Summarized distinct datetime column granularity [ci skip]
  frontend/test/metabase/scenarios/question/new.cy.spec.js
Labels: .CI & Tests, support/Repro

#13631 Repro for #12872: `Between Dates` filter (in)consistency
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro
