Repository metabase/metabase, pull requests merged in 2020-12, with the labels that each got.

#13895 Fix #13894: Always use "Previous results" for subsequent joins
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
Labels: .Frontend, .Tech Debt or Refactoring, Querying/GUI, support/Repro

#13945 Quarantine `public.cy.spec.js`
  frontend/test/metabase/scenarios/public/public.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13948 #13857 Repro: Cannot use custom expression after aggregation
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
Labels: .CI & Tests, support/Repro

#13952 Cypress `table` helper functions improvements
  frontend/test/__support__/cypress.js
  frontend/test/metabase/scenarios/admin/datamodel/metadata.cy.spec.js
  frontend/test/metabase/scenarios/alert/alert.cy.spec.js
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/new.cy.spec.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13953 #13641 Repro: Drill-through on implicit join tables withsandboxes
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, support/Repro

#13962 #13097 Repro: Same result for distinct count on multiple columns for MongoDB
  frontend/test/metabase-db/mongo/query.cy.spec.js
Labels: .CI & Tests, support/Repro

#13943 Consolidate sandboxing reproduction tests
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
  frontend/test/__support__/cypress.js
  frontend/test/snapshot-creators/default.cy.snap.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13967 #13927 Repro: URL click through doesn't include fields from hidden table
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
Labels: .CI & Tests, support/Repro

#13969 #13642 Repro: Drill-through not working on questions with joins with sandboxed target table, and target fields cannot be filtered
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, support/Repro

#13973 Start each test in `parameters.cy.spec.js` in isolation
  frontend/test/metabase/scenarios/dashboard/parameters.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13971 Refactor and unskip repro for #10829
  frontend/test/metabase/scenarios/dashboard/parameters.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13964 Revert #13895
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
Labels: .Tech Debt or Refactoring

#13993 Change back to manual navigation in smoke tests [ci skip]
  frontend/test/metabase-smoketest/admin.cy.spec.js
  frontend/test/metabase-smoketest/user.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13987 #13457 Repro: Drill-through combined cards with different amount of series
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
Labels: .CI & Tests, support/Repro

#13990 #12625 Repro: Remove sorted metric leads to "No results" page
  frontend/test/metabase/scenarios/question/new.cy.spec.js
Labels: .CI & Tests, support/Repro

#13994 Extract sample dataset metadata in Cypress
  .gitignore
  frontend/test/__support__/cypress_sample_dataset.js
  frontend/test/metabase/scenarios/admin/settings/localization.cy.spec.js
  frontend/test/snapshot-creators/default.cy.snap.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14004 Update Cypress tests with new metadata retrieval method
  enterprise/frontend/test/metabase-enterprise/audit/auditing.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/editor.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/field.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/metrics.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/segments.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/chained-filters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/parameters-embedded.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/permissions.cy.spec.js
  frontend/test/metabase/scenarios/public/public.cy.spec.js
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
  frontend/test/metabase/scenarios/question/native.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/new.cy.spec.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
  frontend/test/metabase/scenarios/question/nulls.cy.spec.js
  frontend/test/metabase/scenarios/question/view.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14011 Update repro for #13990 with new metadata method
  frontend/test/metabase/scenarios/question/new.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14015 Add metadata sync for external DBs
  frontend/test/__support__/cypress.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14019 #12445 Repro: Substring in custom column returns empty value
  frontend/test/metabase-db/mysql/custom-column.cy.spec.js
Labels: .CI & Tests, support/Repro

#14025 #13960 Repro: Should clear default filter value and preserve "state" on reload
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#14036 #13961 Repro: Should clear the default filter value for native questions
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#14043 #13112 Repro: X-rays should work on questions with explicit joins
  frontend/test/metabase/scenarios/dashboard/x-rays.cy.spec.js
Labels: .CI & Tests, support/Repro

#14041 Fix `user.cy.spec.js` smoke test
  frontend/test/metabase-smoketest/user.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14053 Merge Cypress metadata extraction method from `release-x.37.x`
  .gitignore
  enterprise/frontend/test/metabase-enterprise/audit/auditing.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
  frontend/test/__support__/cypress.js
  frontend/test/__support__/cypress_sample_dataset.js
  frontend/test/metabase/scenarios/admin/datamodel/editor.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/field.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/metrics.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/segments.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/localization.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/chained-filters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/parameters-embedded.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/permissions.cy.spec.js
  frontend/test/metabase/scenarios/public/public.cy.spec.js
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
  frontend/test/metabase/scenarios/question/native.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/new.cy.spec.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
  frontend/test/metabase/scenarios/question/nulls.cy.spec.js
  frontend/test/metabase/scenarios/question/view.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
  frontend/test/snapshot-creators/default.cy.snap.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14051 Add initial Cypress tests for pivot table (ref: #14049)
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
Labels: .CI & Tests

#14066 Repro for metabase#13868 - embedded dashboard with chained filters
  frontend/test/metabase/scenarios/dashboard/chained-filters.cy.spec.js
Labels: .CI & Tests, support/Repro

#14082 #13817 Repro: "Save question" modal wrong state applied to "Save" button
  frontend/test/metabase/scenarios/question/saved.cy.spec.js
Labels: .CI & Tests, support/Repro

#14085 #14080 Repro: "Input to aggregation-name does not match schema"
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
Labels: .CI & Tests, support/Repro

#14088 Improve assertion in repro for #14080 [ci skip]
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14102 #11907 Repro: Tooltip should display correct value for unaggregated data [ci skip]
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
Labels: .CI & Tests, support/Repro

#14103 #11957 Repro: Changing filters shouldn't drop aggregated filter [ci skip]
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#14120 #13187 Repro: FE should respect (BE) settings for `auto_run_queries`
  frontend/test/metabase/scenarios/admin/databases/edit.cy.spec.js
Labels: .CI & Tests, support/Repro

#14129 Remove unused New User Onboarding Modal
  frontend/src/metabase/components/StepIndicators.jsx
  frontend/src/metabase/home/components/NewUserOnboardingModal.jsx
  frontend/src/metabase/home/containers/HomepageApp.jsx
  frontend/test/metabase/components/StepIndicators.unit.spec.js
  frontend/test/metabase/home/NewUserOnboardingModal.unit.spec.js
Labels: .Tech Debt or Refactoring

#14073 #14114 Repro: Cannot save to child collection when access has been revoked to its parent
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#14121 Fix #13187: FE should respect settings for `auto_run_queries` on page load
  frontend/src/metabase/components/form/widgets/FormToggleWidget.jsx
  frontend/src/metabase/entities/databases/forms.js
  frontend/test/metabase/scenarios/admin/databases/edit.cy.spec.js
Labels: Admin Panel & Setup

#14142 #13415 Repro: Visualization type should be respected when entering a question from a dashboard
  frontend/test/metabase/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
Labels: .CI & Tests, support/Repro

#14137 #14114 Repro: Cannot see child collection in collection sidebar when access has been revoked to its parent
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#14134 Fix #13299: Misconfigured "Port" label and input fields
  frontend/src/metabase/components/form/widgets/FormNumericInputWidget.jsx
  frontend/test/metabase-db/mongo/add.cy.spec.js
  frontend/test/metabase-db/mysql/add.cy.spec.js
  frontend/test/metabase-db/postgres/add.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring, Type:UX

#14143 #14122 Repro: Sub-collections under Personal collection should be available in save/move modals
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#14164 #14148 Repro: Switch visualization to pivot table in Postgres [ci skip]
  frontend/test/metabase-db/postgres/query.cy.spec.js
Labels: .CI & Tests, support/Repro

#14161 #14136 Repro: Use binned numeric dimension as a grouping in a pivot table
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
Labels: .CI & Tests, support/Repro

#14167 #14124 Repro: Date is included when binned "by hour of day"
  frontend/test/metabase/scenarios/admin/datamodel/metadata.cy.spec.js
Labels: .CI & Tests, support/Repro

#14197 #14193 Repro: Custom column is dropped after removing filter (that comes after aggregation)
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
Labels: .CI & Tests, support/Repro

#14170 #14117 Repro: Dashboard subscriptions don't persist attachments
  frontend/test/metabase/scenarios/dashboard/subscriptions.cy.spec.js
Labels: .CI & Tests, support/Repro

#14163 Closes #14090 & #14074
  docs/users-guide/05-visualizing-results.md
  docs/users-guide/images/visualizations/histogram.png
  docs/users-guide/images/visualizations/pivot-table-notebook.png
  docs/users-guide/images/visualizations/pivot-table-options.png
  docs/users-guide/images/visualizations/waterfall-chart.png
Labels: .Documentation

#14174 Convert integration tests to Cypress
  .circleci/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  docs/developers-guide.md
  enterprise/frontend/test/metabase-enterprise/audit/containers/AuditTable.integ.spec.jsx
  frontend/test/metabase/admin/people/containers/EditUserModal.integ.spec.js
  frontend/test/metabase/admin/people/containers/GroupDetailApp.integ.spec.js
  frontend/test/metabase/admin/people/containers/GroupsListingApp.integ.spec.js
  frontend/test/metabase/admin/people/containers/NewUserModal.integ.spec.js
  frontend/test/metabase/admin/people/containers/PeopleListingApp.integ.spec.js
  frontend/test/metabase/admin/people/containers/UserActivationModal.integ.spec.js
  frontend/test/metabase/admin/people/containers/UserPasswordResetModal.integ.spec.js
  frontend/test/metabase/scenarios/admin/people/people.cy.spec.js
  frontend/test/metabase/scenarios/setup/user_settings.cy.spec.js
  frontend/test/metabase/user/UserSettings.integ.spec.js
  jest.integ.conf.json
  package.json
Labels: .CI & Tests, .Tech Debt or Refactoring
