Repository metabase/metabase, pull requests merged in 2020-11, with the labels that each got.

#13647 Fix old MBQL syntax in tests
  frontend/test/metabase/scenarios/admin/settings/localization.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/nulls.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13658 Fix recent Cypress flakes
  frontend/test/metabase/scenarios/admin/datamodel/editor.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
  frontend/test/metabase/scenarios/public/public.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13663 Repro for #13634: create CC after aggregation w/ Cumulative Sum/Count [ci skip]
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
Labels: .CI & Tests, support/Repro

#13668 Add Cypress repro PR template [ci skip]
  .github/PULL_REQUEST_TEMPLATE/cypress_repro.md
Labels: .Documentation

#13667 Repro for #13235: Filter with remapped values [ci skip]
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#13673 Repro for #13626: Pie chart shows spinner for `0` or `null` [ci skip]
  frontend/test/metabase/scenarios/question/nulls.cy.spec.js
Labels: .CI & Tests, support/Repro

#13689 Repro for #12928: Join saved questions already containing joins [ci skip]
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
Labels: .CI & Tests, support/Repro

#12775 Add a circleci workflow that runs a set of Cypress smoketests
  .circleci/config.yml
  frontend/test/metabase-smoketest/admin.cy.spec.js
  frontend/test/metabase-smoketest/admin_setup.cy.spec.js
  frontend/test/metabase-smoketest/user.cy.spec.js
  package.json
Labels: Support/Improvement

#13701 Fix `settings/settings.cy.spec.js` flakes
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13648 MBQL: correctly alias duplicate col names in breakouts (#10511)
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  src/metabase/driver/sql/query_processor.clj
  test/metabase/query_processor_test/nested_queries_test.clj
Labels: support/Repro

#13703 Fix Cypress flakes in `dashboard/dashboard.cy.spec.js` file
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13709 Fix `metrics.cy.spec.js` flakes (#13682)
  frontend/test/metabase/scenarios/admin/datamodel/metrics.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13674 Upgrade Cypress to v5.5.0
  .circleci/config.yml
  package.json
  yarn.lock
Labels: .CI & Tests, .Tech Debt or Refactoring

#13718 Fix `segments.cy.spec.js` flakes
  frontend/test/metabase/scenarios/admin/datamodel/segments.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13727 Unquarantine `scenarios/pulse/pulse.cy.spec.js`
  frontend/test/metabase/scenarios/pulse/pulse.cy.spec.js
Labels: .CI & Tests

#13732 Unset `DISPLAY` ENV in smoketests CI group
  .circleci/config.yml
Labels: .CI & Tests, .Tech Debt or Refactoring

#13734 Unquarantine enterprise `custom_drill_through/drill_through.cy.spec.js`
  enterprise/frontend/test/metabase-enterprise/custom_drill_through/drill_through.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13733 Unquarantine `question/nested.cy.spec.js`
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13738 Repro for #13604: Wrong day names on X-axis
  frontend/test/metabase/scenarios/admin/settings/localization.cy.spec.js
Labels: .CI & Tests, support/Repro

#13743 Port Cypress fixes/updates from `master` into `release-x.37.x`
  .circleci/config.yml
  frontend/test/metabase-smoketest/admin.cy.spec.js
  frontend/test/metabase-smoketest/admin_setup.cy.spec.js
  frontend/test/metabase-smoketest/user.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/editor.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/metrics.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/segments.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
  package.json
  yarn.lock
Labels: .Tech Debt or Refactoring

#13430 File download testing
  frontend/test/cypress-plugins.js
  frontend/test/metabase/scenarios/question/downloads.cy.spec.js
  package.json
  yarn.lock
Labels: .CI & Tests, support/Repro

#13749 Improve Cypress helper functions with log messages
  frontend/test/__support__/cypress.js
Labels: .CI & Tests

#13750 Repro for #13744: Join saved question with sorted metrics
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
Labels: .CI & Tests, support/Repro

#13747 Disable video uploads for successful Cypress tests
  frontend/test/cypress.json
Labels: .CI & Tests

#13745 Reproduce datetime downloads
  frontend/test/metabase/scenarios/question/downloads.cy.spec.js
Labels: .CI & Tests, support/Repro

#13759 Add docstrings to chain filter endpoints
  src/metabase/api/public.clj
Labels: .Backend, .Documentation

#13753 Repro for #13710: Trend visualization blank screen
  frontend/test/metabase/scenarios/question/new.cy.spec.js
Labels: .CI & Tests, support/Repro

#13756 Enable enterprise cypress tests
  .circleci/config.yml
  enterprise/frontend/test/metabase-enterprise/audit/auditing.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/custom_drill_through/drill_through.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/formatting/whitelabel.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/snippets/snippet-permissions.cy.spec.js
  frontend/test/__runner__/backend.js
  frontend/test/__runner__/run_cypress_tests.js
Labels: .CI & Tests, support/Repro

#13768 Add repro for #13597 [ci skip]
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, support/Repro

#13774 #13717 Repro: Properly choose between 'Object detail' and 'Table' views
  frontend/test/metabase/scenarios/question/new.cy.spec.js
Labels: .CI & Tests, support/Repro

#13779 #13764 Repro: Granularity of aggregated fields in nested question
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
Labels: .CI & Tests, support/Repro

#13782 #11439 Repro: Can't select date granularity when summarizing from saved question
  frontend/test/metabase/scenarios/question/new.cy.spec.js
Labels: .CI & Tests, support/Repro

#13790 Fix `unused var` linter error on a release branch
  frontend/test/metabase/scenarios/question/new.cy.spec.js
Labels: .Tech Debt or Refactoring

#13784 Repro for #12839: Can't use filter based on CE from aggregated results
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#13789 Refactor Cypress repro for #13000
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13811 #13801 Repro: Dashboard should handle cards with null values
  frontend/test/metabase/scenarios/question/nulls.cy.spec.js
Labels: .CI & Tests, support/Repro

#13813 #13649 Repro: Custom column from joined questions
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
Labels: .CI & Tests, support/Repro

#13823 Remove object count from log output
  src/metabase/cmd/dump_to_h2.clj
Labels: .Backend, Operation/Database Migrations

#13831 #13186 Repro: Missing dashboard filter columns for nested questions
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
Labels: .CI & Tests, support/Repro

#13816 #12507 Repro: Nested queries using metric
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
Labels: .CI & Tests, support/Repro

#13841 Fix admin settings `auth` cypress test
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13843 Fix `snippet` Cypress test for CI
  frontend/test/metabase/scenarios/question/snippets.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13839 Order fields to dump by ID
  src/metabase/cmd/dump_to_h2.clj
Labels: Database/Mongo, Operation/Database Migrations, Type:Bug

#13827 MySQL cypress test
  .circleci/config.yml
  frontend/test/metabase-db/mysql/add.cy.spec.js
  frontend/test/metabase-db/mysql/query.cy.spec.js
Labels: .CI & Tests

#13865 #13751 Repro: Custom column based filter should allow strings
  frontend/test/__support__/cypress.js
  frontend/test/metabase-db/postgres/add.cy.spec.js
  frontend/test/metabase-db/postgres/custom-column.cy.spec.js
  frontend/test/metabase-db/postgres/query.cy.spec.js
Labels: .CI & Tests, support/Repro

#13852 Fix `dash_drill.cy.spec.js`
  frontend/test/metabase/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13887 Cherry-pick `dash_drill.cy.spec.js` fix from master
  frontend/test/metabase/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13885 Repro for `EE#548`: Sanboxed questions with custom column containing `case`
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, support/Repro

#13896 Quarantine `field.cy.spec.js`
  frontend/test/metabase/scenarios/admin/datamodel/field.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13888 Repro for `EE#154`: Sanboxed table should allow joins to it
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, support/Repro

#13897 Fix smoke tests
  frontend/test/metabase-smoketest/user.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#13898 Upstream cypress improvements
  frontend/test/__support__/cypress.js
  frontend/test/cypress-plugins.js
  frontend/test/cypress.json
  frontend/test/metabase-smoketest/user.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/field.cy.spec.js
  frontend/test/metabase/scenarios/question/downloads.cy.spec.js
  package.json
  yarn.lock
Labels: .CI & Tests, .Tech Debt or Refactoring

#13900 Remove Enzyme 2
  package.json
  yarn.lock
Labels: .Tech Debt or Refactoring

#13902 Repro for `EE#524`: Advanced sandboxing (saved question with joins) prevents the use of joins for SB user
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, support/Repro

#13906 Improve yarn test scripts
  package.json
Labels: .CI & Tests, .Tech Debt or Refactoring

#13903 Repro for `EE#520`: Advanced sanboxing ignores object details and/or FK
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, support/Repro

#13915 Fix MySQL Cypress tests in `master`
  .circleci/config.yml
  frontend/test/__support__/cypress.js
  frontend/test/metabase-db/mongo/add.cy.spec.js
  frontend/test/metabase-db/mongo/query.cy.spec.js
  frontend/test/metabase-db/mysql/add.cy.spec.js
  frontend/test/metabase-db/mysql/query.cy.spec.js
  frontend/test/metabase-db/postgres/add.cy.spec.js
  frontend/test/metabase-db/postgres/custom-column.cy.spec.js
  frontend/test/metabase-db/postgres/query.cy.spec.js
  package.json
Labels: .CI & Tests, .Tech Debt or Refactoring
