Repository metabase/metabase, pull requests merged in 2020-07, with the labels that each got.

#12820 Docs: Update environment variables
  docs/operations-guide/environment-variables.md
Labels: Support/Improvement

#12852 Repro/filter without permissions
  frontend/test/metabase/scenarios/question/view.cy.spec.js
Labels: support/Repro

#12835 Repro/Email alert toggle
  frontend/test/__support__/cypress.js
  frontend/test/metabase-smoketest/admin_setup.cy.spec.js
  frontend/test/metabase/scenarios/README.md
  frontend/test/metabase/scenarios/alert/email_alert.cy.spec.js
Labels: support/Repro

#12833 Repro/Column confusion
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
Labels: support/Repro

#12811 Feature/trendline w many outputs
  frontend/test/metabase/scenarios/question/trendline.cy.spec.js
Labels: support/Repro

#12911 Repro for #12899
  frontend/test/metabase/scenarios/question/new.cy.spec.js
Labels: support/Repro

#12919 Repro for #12651
  frontend/test/metabase/scenarios/question/new.cy.spec.js
Labels: support/Repro

#12914 repro/Dash w text box cards
  frontend/test/metabase/scenarios/dashboard/text-box.cy.spec.js
Labels: support/Repro

#12943 Docs ee snippets
  docs/enterprise-guide/images/sql-snippets/change-permissions.png
  docs/enterprise-guide/images/sql-snippets/create-new-folder-modal.png
  docs/enterprise-guide/images/sql-snippets/enterprise-add-snippet.png
  docs/enterprise-guide/images/sql-snippets/snippet-folder.png
  docs/enterprise-guide/sql-snippets.md
  docs/users-guide/images/sql-snippets/highlight_and_save_as_snippet.gif
  docs/users-guide/images/sql-snippets/snippet_sidebar_and_insertion.gif
  docs/users-guide/sql-snippets.md
Labels: .Documentation

#12957 Repro/universal search
  frontend/test/metabase/scenarios/auth/search.cy.spec.js
Labels: support/Repro
