Repository metabase/metabase, pull requests merged in 2021-01, with the labels that each got.

#14267 #14255 Repro: CC and table column same name [REGRESSION]
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
Labels: .CI & Tests, support/Repro

#14272 Update year in copyright notice
  README.md
  docs/developers-guide.md
  enterprise/README.md
Labels: .Documentation

#14286 #14280 Repro: Moved collection isn't shown in sidebar
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#14292 #14285 Repro: Rows collapse when last value is 0
  frontend/test/metabase/scenarios/visualizations/rows.cy.spec.js
Labels: .CI & Tests, support/Repro

#14304 #14302 Repro: Native question with filter - dirty state without changes
  frontend/test/metabase/scenarios/question/native.cy.spec.js
Labels: .CI & Tests, support/Repro

#14269 Remove useless and/or unused CSS animations
  frontend/src/metabase/css/components/icons.css
  frontend/src/metabase/css/core/base.css
  frontend/src/metabase/css/dashboard.css
  frontend/src/metabase/dashboard/components/DashCard.jsx
Labels: .CSS, .Tech Debt or Refactoring

#14094 Remove Enzyme
  enterprise/frontend/test/metabase-enterprise/auth/LoginApp.unit.spec.js
  enterprise/frontend/test/metabase-enterprise/auth/sso.cy.spec.js
  frontend/src/metabase/components/BodyComponent.jsx
  frontend/src/metabase/components/Modal.jsx
  frontend/src/metabase/components/Tooltip.jsx
  frontend/src/metabase/containers/QuestionLoader.jsx
  frontend/src/metabase/internal/components/QuestionApp.jsx
  frontend/src/metabase/visualizations/visualizations/Table.jsx
  frontend/test/__support__/cypress.js
  frontend/test/__support__/enzyme.js
  frontend/test/__support__/integration.js
  frontend/test/__support__/mocks.js
  frontend/test/enzyme-setup.js
  frontend/test/metabase/admin/tasks/containers/Logs.unit.spec.js
  frontend/test/metabase/auth/containers/LoginApp.unit.spec.js
  frontend/test/metabase/components/AccordionList.unit.spec.js
  frontend/test/metabase/components/Calendar.unit.spec.js
  frontend/test/metabase/components/FieldValuesWidget.unit.spec.js
  frontend/test/metabase/components/LoadingAndErrorWrapper.unit.spec.js
  frontend/test/metabase/components/TokenField.unit.spec.js
  frontend/test/metabase/containers/AdHocQuestionLoader.unit.spec.js
  frontend/test/metabase/containers/Overworld.unit.spec.js
  frontend/test/metabase/containers/QuestionAndResultLoader.unit.spec.js
  frontend/test/metabase/containers/QuestionLoader.unit.spec.js
  frontend/test/metabase/containers/QuestionResultLoader.unit.spec.js
  frontend/test/metabase/containers/SaveQuestionModal.unit.spec.js
  frontend/test/metabase/containers/SavedQuestionLoader.unit.spec.js
  frontend/test/metabase/dashboard/DashCard.unit.spec.js
  frontend/test/metabase/entities/containers/EntityListLoader.unit.spec.js
  frontend/test/metabase/hoc/Background.unit.spec.js
  frontend/test/metabase/modes/TimeseriesFilterWidget.unit.spec.js
  frontend/test/metabase/modes/TimeseriesMode.unit.spec.js
  frontend/test/metabase/modes/components/drill/PivotByDrill.unit.spec.js
  frontend/test/metabase/nav/ProfileLink.unit.spec.js
  frontend/test/metabase/parameters/components/widgets/DateRangeWidget.unit.spec.js
  frontend/test/metabase/pulse/pulse.unit.spec.js
  frontend/test/metabase/query_builder/components/GuiQueryEditor.unit.spec.js
  frontend/test/metabase/query_builder/components/filters/FilterPopover.unit.spec.js
  frontend/test/metabase/query_builder/components/filters/pickers/DatePicker.unit.spec.js
  frontend/test/metabase/scenarios/auth/sso.cy.spec.js
  frontend/test/metabase/scenarios/internal/question.cy.spec.js
  frontend/test/metabase/visualizations/components/LegendVertical.unit.spec.js
  frontend/test/metabase/visualizations/components/ObjectDetail.unit.spec.js
  frontend/test/metabase/visualizations/components/settings/ChartNestedSettingsSeries.unit.spec.js
  frontend/test/metabase/visualizations/components/settings/ChartSettingOrderedColumns.unit.spec.js
  jest.tz.unit.conf.json
  jest.unit.conf.json
  package.json
  yarn.lock
Labels: .CI & Tests, .Tech Debt or Refactoring

#14308 #14254 Repro: Map visualization not suggested when first column type is number
  frontend/test/metabase/scenarios/visualizations/maps.cy.spec.js
Labels: .CI & Tests, support/Repro

#14279 Move web server related code into metabase.server
  .dir-locals.el
  dev/src/dev.clj
  enterprise/backend/src/metabase_enterprise/sandbox/api/routes.clj
  enterprise/backend/src/metabase_enterprise/sandbox/models/group_table_access_policy.clj
  enterprise/backend/src/metabase_enterprise/sso/api/routes.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/jwt.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/saml.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/gtap_test.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/saml_test.clj
  project.clj
  resources/frontend_client/index_template.html
  src/metabase/api/routes.clj
  src/metabase/api/session.clj
  src/metabase/api/setup.clj
  src/metabase/async/api_response.clj
  src/metabase/core.clj
  src/metabase/handler.clj
  src/metabase/models/card.clj
  src/metabase/models/session.clj
  src/metabase/pulse.clj
  src/metabase/query_processor/streaming/xlsx.clj
  src/metabase/server.clj
  src/metabase/server/README.md
  src/metabase/server/handler.clj
  src/metabase/server/middleware/auth.clj
  src/metabase/server/middleware/exceptions.clj
  src/metabase/server/middleware/json.clj
  src/metabase/server/middleware/log.clj
  src/metabase/server/middleware/misc.clj
  src/metabase/server/middleware/security.clj
  src/metabase/server/middleware/session.clj
  src/metabase/server/middleware/ssl.clj
  src/metabase/server/middleware/util.clj
  src/metabase/server/routes.clj
  src/metabase/server/routes/index.clj
  test/metabase/api/alert_test.clj
  test/metabase/api/card_test.clj
  test/metabase/api/common_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/geojson_test.clj
  test/metabase/api/metric_test.clj
  test/metabase/api/notify_test.clj
  test/metabase/api/pulse_test.clj
  test/metabase/api/segment_test.clj
  test/metabase/api/table_test.clj
  test/metabase/api/user_test.clj
  test/metabase/http_client.clj
  test/metabase/models/database_test.clj
  test/metabase/models/session_test.clj
  test/metabase/server/middleware/auth_test.clj
  test/metabase/server/middleware/json_test.clj
  test/metabase/server/middleware/log_test.clj
  test/metabase/server/middleware/misc_test.clj
  test/metabase/server/middleware/security_test.clj
  test/metabase/server/middleware/session_test.clj
  test/metabase/server/middleware/ssl_test.clj
  test/metabase/server/middleware/util_test.clj
  test/metabase/server/routes/index_test.clj
  test/metabase/test/data/users.clj
  test/metabase/test/initialize/web_server.clj
Labels: .Proposal

#14330 #14294 Repro: Native questions don't respect Start of the week
  frontend/test/metabase/scenarios/admin/settings/localization.cy.spec.js
Labels: .CI & Tests, support/Repro

#14335 #14287 Repro: Should suggest questions saved in collections with colon in their name
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#14344 #14341 Repro: Custom expression filter doesn't display options [REGRESSION]
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#14340 Refactor sandboxes
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14356 #14327 Repro: Cannot add date filter when calendar is collapsed
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#14346 Refactor whitelabel Cypress tests
  enterprise/frontend/test/metabase-enterprise/custom_drill_through/drill_through.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/formatting/whitelabel.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/snippets/snippet-permissions.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14355 Default databases with auto_run_queries to true
  frontend/src/metabase/admin/databases/database.js
  frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js
Labels: support/Repro

#14362 Refactor auditing Cypress tests
  enterprise/frontend/test/metabase-enterprise/audit/auditing.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14339 Run Cypress EE tests in isolation
  enterprise/frontend/test/metabase-enterprise/audit/ad-hoc.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/audit/auditing.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/custom_drill_through/drill_through.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/formatting/whitelabel.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/snippets/snippet-permissions.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14378 Fix `auditing` test failure on `master`
  enterprise/frontend/test/metabase-enterprise/audit/auditing.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14377 Merge `Run Cypress EE tests in isolation` PR from `release-x.37.x` branch (#14339)
  enterprise/frontend/test/metabase-enterprise/audit/ad-hoc.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/audit/auditing.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/custom_drill_through/drill_through.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/formatting/whitelabel.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/snippets/snippet-permissions.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14274 docs - saved question page - closes #14198
  docs/users-guide/08-dashboard-filters.md
  docs/users-guide/13-sql-parameters.md
  docs/users-guide/images/saved-questions/example-notebook.png
  docs/users-guide/images/saved-questions/variable-sidebar.png
  docs/users-guide/interactive-dashboards.md
  docs/users-guide/referencing-saved-questions-in-queries.md
  docs/users-guide/sql-snippets.md
  docs/users-guide/start.md
Labels: .Documentation

#14390 Remove jasmine
  frontend/test/.eslintrc
  frontend/test/metabase/lib/data_grid.unit.spec.js
  frontend/test/metabase/lib/redux.unit.spec.js
  frontend/test/metabase/query_builder/components/DataSelector.unit.spec.js
  package.json
  yarn.lock
Labels: .CI & Tests, .Tech Debt or Refactoring

#14380 Refactor `snippets` Cypress tests to run in isolation
  frontend/test/metabase/scenarios/question/snippets.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14372 Run Cypress OSS tests in isolation
  frontend/test/metabase-db/postgres/custom-column.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/edit.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/list.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/hide_tables.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/metrics.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/segments.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/table.cy.spec.js
  frontend/test/metabase/scenarios/admin/permissions/permissions.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/spinner.cy.spec.js
  frontend/test/metabase/scenarios/alert/alert.cy.spec.js
  frontend/test/metabase/scenarios/auth/search.cy.spec.js
  frontend/test/metabase/scenarios/auth/signin.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard_data_permissions.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/embed.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/nested-cards.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/parameters-embedded.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/permissions.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/text-box.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/title-drill.cy.spec.js
  frontend/test/metabase/scenarios/home/activity-page.cy.spec.js
  frontend/test/metabase/scenarios/home/overworld.cy.spec.js
  frontend/test/metabase/scenarios/permissions.cy.spec.js
  frontend/test/metabase/scenarios/pulse/pulse.cy.spec.js
  frontend/test/metabase/scenarios/question/data_ref.cy.spec.js
  frontend/test/metabase/scenarios/question/downloads.cy.spec.js
  frontend/test/metabase/scenarios/question/loading.cy.spec.js
  frontend/test/metabase/scenarios/question/native_subquery.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/operators.cy.spec.js
  frontend/test/metabase/scenarios/question/settings.cy.spec.js
  frontend/test/metabase/scenarios/question/snippets.cy.spec.js
  frontend/test/metabase/scenarios/question/trendline.cy.spec.js
  frontend/test/metabase/scenarios/question/view.cy.spec.js
  frontend/test/metabase/scenarios/reference/databases.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14383 Refactor `collections` Cypress tests to run in isolation
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14394 Merge `Run Cypress OSS tests in isolation` PR from `release-x.37.x` branch (#14372)
  frontend/test/metabase-db/postgres/custom-column.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/edit.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/list.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/hide_tables.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/metrics.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/segments.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/table.cy.spec.js
  frontend/test/metabase/scenarios/admin/permissions/permissions.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/spinner.cy.spec.js
  frontend/test/metabase/scenarios/alert/alert.cy.spec.js
  frontend/test/metabase/scenarios/auth/search.cy.spec.js
  frontend/test/metabase/scenarios/auth/signin.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard_data_permissions.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/embed.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/nested-cards.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/parameters-embedded.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/permissions.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/text-box.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/title-drill.cy.spec.js
  frontend/test/metabase/scenarios/home/activity-page.cy.spec.js
  frontend/test/metabase/scenarios/home/overworld.cy.spec.js
  frontend/test/metabase/scenarios/permissions.cy.spec.js
  frontend/test/metabase/scenarios/pulse/pulse.cy.spec.js
  frontend/test/metabase/scenarios/question/data_ref.cy.spec.js
  frontend/test/metabase/scenarios/question/downloads.cy.spec.js
  frontend/test/metabase/scenarios/question/loading.cy.spec.js
  frontend/test/metabase/scenarios/question/native_subquery.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/operators.cy.spec.js
  frontend/test/metabase/scenarios/question/settings.cy.spec.js
  frontend/test/metabase/scenarios/question/snippets.cy.spec.js
  frontend/test/metabase/scenarios/question/trendline.cy.spec.js
  frontend/test/metabase/scenarios/question/view.cy.spec.js
  frontend/test/metabase/scenarios/reference/databases.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14418 Pivot tables public/embed Cypress coverage and repro for #14447
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
Labels: .CI & Tests, support/Repro

#14449 #14426 Repro: Admin localization tab showing excessive options
  frontend/test/metabase/scenarios/admin/settings/localization.cy.spec.js
Labels: .CI & Tests, support/Repro

#14460 #11183 Repro: Missing Time series filter and granularity widgets
  frontend/test/metabase/scenarios/question/new.cy.spec.js
Labels: .CI & Tests, support/Repro

#14468 Update repro for #12928 [ci skip]
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14483 #14482 Repro: UI should update when a collection changes parent
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#14498 #14405 Repro: Dashboard subscription should not display "null" day of the week
  frontend/test/metabase/scenarios/dashboard/subscriptions.cy.spec.js
Labels: .CI & Tests, support/Repro

#14492 Fix #14327: Collapsed calendar prevented adding a date filter
  frontend/src/metabase/components/ExpandingContent.jsx
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: Type:UX

#14501 #12581 Repro: Revision history restore shows wrong query and misconfigured UI
  frontend/test/metabase/scenarios/question/native.cy.spec.js
Labels: .CI & Tests, support/Repro

#14510 #14495 Repro: Cannot drill-through when question is joined with SQL (if user has SQL restrictions)
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
Labels: .CI & Tests, support/Repro

#14530 #14517 Repro: Regex escaped characters shouldn't be ignored
  frontend/test/metabase-db/postgres/custom-column.cy.spec.js
Labels: .CI & Tests, support/Repro

#14526 Sanitize URL substring used for determining if the instance is hosted
  frontend/src/metabase/lib/settings.js
Labels: .Tech Debt or Refactoring

#14520 Add Cypress coverage for the Cloud CTA in admin panel
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
Labels: .CI & Tests

#14536 #14473 Repro: Click behavior with cross-filter does not list columns
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, support/Repro

#14544 #14494 Repro: "Done" button should be disabled prior to selecting Slack channel
  frontend/test/metabase/scenarios/dashboard/subscriptions.cy.spec.js
Labels: .CI & Tests, support/Repro

#14557 #12720 Repro: Dashboard filter connected to a card without data-permissions blocking QB question
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, support/Repro

#14571 #13832 Repro: Filters should use cached results after the first DB call
  frontend/test/__support__/cypress.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, support/Repro

#14570 docs - update pivot table image and text
  docs/users-guide/05-visualizing-results.md
  docs/users-guide/images/visualizations/pivot-table-options.png
Labels: .Documentation

#14587 #8055 Repro: Dashboard drill-through on a FK fails
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
Labels: .CI & Tests, support/Repro

#14589 Update `cypress_repro.md` template
  .github/PULL_REQUEST_TEMPLATE/cypress_repro.md
Labels: .CI & Tests, .Tech Debt or Refactoring
