Repository metabase/metabase, pull requests merged in 2021-08, with the labels that each got.

#17269 Update yarn build scripts
  package.json
Labels: .Tech Debt or Refactoring

#17280 #17268 Repro: Snippet folder permissions applied to root
  frontend/test/metabase/scenarios/native/snippets/snippet-permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#17261 Fix Elastic Beanstalk deployment in v40
  bin/release/src/release/elastic_beanstalk.clj
  bin/release/src/release/elastic_beanstalk/.ebextensions/01_metabase.config
  bin/release/src/release/elastic_beanstalk/.ebextensions/metabase_config/metabase-setup.sh
  bin/release/src/release/elastic_beanstalk/.ebextensions/metabase_config/nginx/log_x_real_ip.conf
  bin/release/src/release/elastic_beanstalk/.platform/confighooks/postdeploy/config_nginx.sh
  bin/release/src/release/elastic_beanstalk/.platform/hooks/postdeploy/config_nginx.sh
  bin/release/src/release/elastic_beanstalk/.platform/nginx/nginx-ssl.conf
  bin/release/src/release/elastic_beanstalk/.platform/nginx/nginx.conf
Labels: Operation/Elastic Beanstalk, backport

#17291 Update lein references in scripts
  package.json
Labels: .Tech Debt or Refactoring

#17279 Handle mutation of vizSetting column when syncing columns in a native question
  frontend/src/metabase-lib/lib/Question.js
  frontend/test/metabase-lib/lib/Question.unit.spec.js
Labels: backport

#17284 Fix incorrect props are passed to CollectionPermissionModal when used for snippets folders
  enterprise/frontend/src/metabase-enterprise/snippets/index.js
  frontend/test/metabase/scenarios/native/snippets/snippet-permissions.cy.spec.js
Labels: backport

#17182 Prepare Jest config for FE code coverage
  jest.unit.conf.json
Labels: .CI & Tests

#17180 Upgrade `@cypress/webpack-preprocessor`
  package.json
  yarn.lock
Labels: .Tech Debt or Refactoring

#17292 Use `jest-dom/extend-expect` library globally
  frontend/src/metabase/collections/components/CollectionHeader/CollectionHeader.unit.spec.js
  frontend/src/metabase/collections/containers/CollectionSidebar/CollectionSidebarFooter/CollectionSidebarFooter.unit.spec.js
  frontend/src/metabase/query_builder/components/SavedQuestionHeaderButton/SavedQuestionHeaderButton.unit.spec.js
  frontend/test/metabase/collections/BaseItemsTable.unit.spec.js
  frontend/test/metabase/components/AccordionList.unit.spec.js
  frontend/test/metabase/components/AddDatabaseHelpCard.unit.spec.js
  frontend/test/metabase/components/Button.unit.spec.js
  frontend/test/metabase/components/ClampedText.unit.spec.js
  frontend/test/metabase/components/DateTime.unit.spec.js
  frontend/test/metabase/components/EntityMenuItem.unit.spec.js
  frontend/test/metabase/components/Icon.unit.spec.js
  frontend/test/metabase/components/LastEditInfoLabel.unit.spec.js
  frontend/test/metabase/components/PaginationControls.unit.spec.js
  frontend/test/metabase/components/Tree.unit.spec.js
  frontend/test/metabase/containers/Overworld.unit.spec.js
  frontend/test/metabase/query_builder/components/ClampedDescription.unit.spec.js
  frontend/test/metabase/query_builder/components/QuestionActionButtons.unit.spec.js
  frontend/test/metabase/query_builder/components/QuestionActivityTimeline.unit.spec.jsx
  frontend/test/metabase/visualizations/components/ChartSettings.unit.spec.js
  frontend/test/metabase/visualizations/components/settings/ChartNestedSettingsSeries.unit.spec.js
  jest.unit.conf.json
Labels: .CI & Tests, .Tech Debt or Refactoring

#17283 Make the field search do limits (whacks #17228)
  frontend/src/metabase/dashboard/components/add-card-sidebar/QuestionList.jsx
  frontend/src/metabase/nav/components/SearchBar.jsx
  frontend/src/metabase/query_builder/components/data-search/SearchResults.jsx
  src/metabase/api/field.clj
  test/metabase/api/field_test.clj
  test/metabase/api/search_test.clj
Labels: backport

#17294 Update `project.clj` references
  .circleci/config.yml
  .github/workflows/percy-issue-comment.yml
  .github/workflows/percy.yml
  bin/build-for-test
Labels: .Tech Debt or Refactoring

#17310 Update strings for 0.40.2
  locales/bg.po
  locales/ca.po
  locales/cs.po
  locales/de.po
  locales/es.po
  locales/fa.po
  locales/fr.po
  locales/it.po
  locales/ja.po
  locales/metabase.pot
  locales/nb.po
  locales/nl.po
  locales/pl.po
  locales/pt-BR.po
  locales/ru.po
  locales/sk.po
  locales/sr.po
  locales/sv.po
  locales/tr.po
  locales/uk.po
  locales/vi.po
  locales/zh-HK.po
  locales/zh-TW.po
  locales/zh.po
Labels: Customization/i18n, backport

#15919 Fix location of share icon
  docs/administration-guide/12-public-links.md
Labels: .Documentation, backport

#17304 docs - troubleshooting logs
  docs/operations-guide/log-configuration.md
  docs/troubleshooting-guide/index.md
  docs/troubleshooting-guide/server-logs.md
Labels: .Documentation, backport

#17308 e2e test for "About Metabase" modal (partial repro for #15656)
  frontend/test/metabase/scenarios/onboarding/about.cy.spec.js
Labels: .CI & Tests, support/Repro

#17344 Repro for #17339: collection tree should expand/collapse on parent collection name click
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#17343 #17212 Repro: Not possible to apply dashboard ID filter to a nested QB question
  frontend/test/__support__/e2e/commands/api/composite/createQuestionAndDashboard.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/17212.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#17296 Regularizing titles of troubleshooting guides
  docs/troubleshooting-guide/application-database.md
  docs/troubleshooting-guide/datawarehouse.md
  docs/troubleshooting-guide/docker.md
  docs/troubleshooting-guide/email.md
  docs/troubleshooting-guide/ldap.md
  docs/troubleshooting-guide/loading-from-h2.md
  docs/troubleshooting-guide/loggingin.md
  docs/troubleshooting-guide/performance.md
  docs/troubleshooting-guide/proxies.md
  docs/troubleshooting-guide/running.md
  docs/troubleshooting-guide/sandboxing.md
  docs/troubleshooting-guide/sync-fingerprint-scan.md
  docs/troubleshooting-guide/timezones.md
Labels: .Documentation

#17352 Backport #17140
  frontend/test/__support__/e2e/helpers/e2e-dashboard-helpers.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/17139.cy.spec.js
Labels: .Tech Debt or Refactoring

#17353 Backport #17173
  frontend/test/__support__/e2e/helpers/e2e-dashboard-helpers.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-date.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/helpers/e2e-dashboard-filter-data-objects.js
Labels: .Tech Debt or Refactoring, .CI & Tests

#17364 #17211 Repro: No matching dashboard filter found when it clearly has been found
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/17211.cy.spec.js
Labels: .CI & Tests, support/Repro

#17361 #17060 Repro: Duplication of the displayed table columns
  frontend/test/metabase/scenarios/native/reproductions/17060.cy.spec.js
Labels: .CI & Tests, support/Repro

#17378 Fix wrong link in dashboard-filters user documentation
  docs/users-guide/08-dashboard-filters.md
Labels: .Tech Debt or Refactoring, .Documentation

#17382 [Dashboard filters coverage] Add initial set of tests for dashboard SQL text/category filters
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-sql.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/helpers/e2e-dashboard-filter-data-objects.js
Labels: .CI & Tests

#17392 Missing last letters in troubleshooting guide titles
  docs/troubleshooting-guide/sync-fingerprint-scan.md
Labels: backport

#17395 [Dashboard filters coverage] Add initial set of tests for dashboard SQL number filters
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-sql-number.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/helpers/e2e-dashboard-filter-data-objects.js
Labels: .CI & Tests

#17444 Prevent infinite re-rendering when the scroll bar appears/disappears
  frontend/src/metabase/dashboard/components/DashboardGrid.jsx
Labels: backport

#17449 Update Snowflake documentation
  docs/administration-guide/databases/snowflake.md
Labels: backport

#17470 Update documentation metadata types
  docs/administration-guide/03-metadata-editing.md
Labels: backport

#17464 Fix propType warning for `RawMaybeLink`
  frontend/src/metabase/components/Badge.styled.jsx
Labels: .Tech Debt or Refactoring

#17423 [Dashboard filters coverage] Add initial set of tests for dashboard SQL location filters
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-sql-location.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/helpers/e2e-dashboard-filter-data-objects.js
Labels: .CI & Tests

#17447 Make DB name in c3p0 name more robust
  src/metabase/driver/sql_jdbc/connection.clj
  test/metabase/driver/sql_jdbc/connection_test.clj
Labels: backport

#17481 Add "moderation" folder to e2e CI groups
  .circleci/config.yml
  frontend/test/metabase/scenarios/moderation/question-moderation.cy.spec.js
Labels: .CI & Tests

#17476 #17450 Repro: New databases with "This is a large database ..." still uses the default sync+scan settings
  frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js
Labels: .CI & Tests, support/Repro

#17489 docs - links to dashboard subscriptions
  docs/users-guide/07-dashboards.md
Labels: .Documentation, backport

#17459 Refine create question custom commands
  frontend/test/__support__/e2e/commands/api/question.js
  frontend/test/metabase/scenarios/binning/sql.cy.spec.js
  frontend/test/metabase/scenarios/question/new.cy.spec.js
Labels: .Tech Debt or Refactoring

#17483 [Dashboard filters coverage] Add initial set of tests for dashboard SQL date filters
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-sql-date.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/helpers/e2e-dashboard-filter-data-objects.js
Labels: .CI & Tests

#17492 docs - README headings
  docs/README.md
Labels: .Documentation, backport

#17493 Add `editDashboardCard` Cypress custom command
  frontend/test/__support__/e2e/commands.js
  frontend/test/__support__/e2e/commands/api/dashboardCard.js
Labels: .CI & Tests

#17508 fix ModalRoute close removes last segment instead of navigating to the parent path
  frontend/src/metabase/hoc/ModalRoute.jsx
Labels: backport

#17521 Edit Cypress custom command `cy.createDashboard()`
  frontend/test/__support__/e2e/commands/api/composite/createNativeQuestionAndDashboard.js
  frontend/test/__support__/e2e/commands/api/composite/createQuestionAndDashboard.js
  frontend/test/__support__/e2e/commands/api/dashboard.js
  frontend/test/metabase/scenarios/admin/audit/auditing.cy.spec.js
  frontend/test/metabase/scenarios/collections/collection-items-listing.cy.spec.js
  frontend/test/metabase/scenarios/collections/collection-types.cy.spec.js
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/parameters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/chained-filters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/click-behavior.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard_local-only.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/permissions.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/text-box.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/15163.cy.spec.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/nulls.cy.spec.js
  frontend/test/metabase/scenarios/question/view.cy.spec.js
  frontend/test/metabase/scenarios/sharing/subscriptions.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/line_chart.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/scalar.cy.spec.js
  frontend/test/snapshot-creators/default.cy.snap.js
Labels: .Tech Debt or Refactoring, .CI & Tests, backport

#17388 Fix serialization P2 issues
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/src/metabase_enterprise/serialization/load.clj
  enterprise/backend/src/metabase_enterprise/serialization/upsert.clj
  enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/load_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/serialize_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/test_util.clj
  src/metabase/cmd.clj
  src/metabase/models/card.clj
  src/metabase/models/metric.clj
  src/metabase/models/permissions_group.clj
  test/metabase/db/schema_migrations_test/impl.clj
Labels: backport

#17535 #13468 Repro: Question with joins causes re-run overlay after first save
  frontend/test/metabase/scenarios/question/reproductions/13468.cy.spec.js
Labels: .CI & Tests, support/Repro

#17534 #17514 Repros: Run-overlay not going away on GUI question
  frontend/test/metabase/scenarios/question/reproductions/17514-ui-overlay.cy.spec.js
Labels: .CI & Tests, support/Repro

#17553 Unifying all troubleshooting guides so far
  docs/faq/setup/what-is-h2.md
  docs/faq/setup/when-should-i-migrate-h2.md
  docs/faq/using-metabase/how-do-i-answer-questions-with-joins.md
  docs/faq/using-metabase/i-am-not-getting-email-notifications.md
  docs/troubleshooting-guide/cant-see-tables.md
  docs/troubleshooting-guide/cant-send-email.md
  docs/troubleshooting-guide/datawarehouse.md
  docs/troubleshooting-guide/email.md
  docs/troubleshooting-guide/filters.md
  docs/troubleshooting-guide/index.md
  docs/troubleshooting-guide/linked-filters.md
  docs/troubleshooting-guide/my-dashboard-is-slow.md
  docs/troubleshooting-guide/performance.md
  docs/troubleshooting-guide/sandboxing.md
  docs/troubleshooting-guide/sync-fingerprint-scan.md
  docs/troubleshooting-guide/times-appear-incorrect.md
  docs/troubleshooting-guide/timezones.md
Labels: .Documentation, backport

#17557 #17551 Repro: Dashboard date filter "Include today" does not work for relative "Next"
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/17551.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/helpers/e2e-date-filter-helpers.js
Labels: .CI & Tests, support/Repro

#17560 Refactor `cy.editDashbardCard` Cypress custom command
  frontend/test/__support__/e2e/commands/api/dashboardCard.js
  frontend/test/metabase-visual/dashboard/parameters-widget.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/17551.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/17514-ui-overlay.cy.spec.js
Labels: .Tech Debt or Refactoring, .CI & Tests

#17563 #17547 Repro: Editing an alert causes it to be deleted in some circumstances
  frontend/test/metabase/scenarios/sharing/reproductions/17547.cy.spec.js
Labels: .CI & Tests, support/Repro

#17574 Revert Mongo QA Docker image update back to the version 4.0
  .circleci/config.yml
  frontend/test/metabase-db/mongo/query.cy.spec.js
Labels: .Tech Debt or Refactoring

#17565 #17524 Reproductions: Visualization type is not always respected, when filters are applied
  frontend/test/metabase/scenarios/visualizations/reproductions/17524.cy.spec.js
Labels: .CI & Tests, support/Repro

#17576 #17512 Repro: Custom Expression case is using wrong field reference when nested query
  frontend/test/metabase/scenarios/question/reproductions/17512.cy.spec.js
Labels: .CI & Tests, support/Repro

#17589 Fix references to the possessive form of 'its'
  frontend/src/metabase/admin/permissions/pages/CollectionPermissionsPage/CollectionPermissionsPage.jsx
  frontend/src/metabase/admin/permissions/pages/GroupDataPermissionsPage/GroupsPermissionsPage.jsx
  frontend/test/metabase/scenarios/admin/permissions/permissions.cy.spec.js
Labels: .Tech Debt or Refactoring, Customization/i18n

#17650 [Dashboard filters coverage] Add test for dashboard filter applied to the explicitly joined field
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-explicit-join.cy.spec.js
Labels: .CI & Tests

#17661 Consolidate dashboard sql filters
  .circleci/config.yml
  frontend/test/metabase/scenarios/dashboard-filters-sql/dashboard-filters-sql-date.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters-sql/dashboard-filters-sql-id.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters-sql/dashboard-filters-sql-location.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters-sql/dashboard-filters-sql-number.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters-sql/dashboard-filters-sql-required-field-filter.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters-sql/dashboard-filters-sql-required-simple-filter.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters-sql/dashboard-filters-sql-text-category.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters-sql/helpers/e2e-dashboard-filter-sql-data-objects.js
  frontend/test/metabase/scenarios/dashboard-filters/helpers/e2e-dashboard-filter-data-objects.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/12614-nested-show-fields.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/12720-no-data-permissions-connected-filter.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/13150-additional-card-queries-for-all-filters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/15119-nodata-should-not-use-dash-filters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/15279-gracefully-deal-with-corrupted-filter.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/15689-allow-multiple-selections.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/15695-do-not-limit-number-of-results.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/16103-additional-requests-dropdown.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/17139-do-not-reset-filters-on-edit.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/17211-false-no-matching-filter-alert.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/17212-nested-id-filter.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/17551-include-today-in-all-time-next-filter.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/6660-sub-day-resolutions-relative-date.cy.spec.js
Labels: .CI & Tests

#17552 Vertical legend fixes for LineAreaBarChart
  frontend/src/metabase/query_builder/components/VisualizationResult.jsx
  frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx
  frontend/src/metabase/visualizations/components/LineAreaBarChart.styled.jsx
  frontend/src/metabase/visualizations/components/Visualization.jsx
  frontend/src/metabase/visualizations/components/legend/Legend.styled.jsx
  frontend/src/metabase/visualizations/components/legend/LegendCaption.jsx
  frontend/src/metabase/visualizations/components/legend/LegendItem.jsx
  frontend/src/metabase/visualizations/components/legend/LegendLayout.jsx
  frontend/src/metabase/visualizations/components/legend/LegendLayout.styled.jsx
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
Labels: .bugbash

#17666 #17657 Repro: Subscriptions are enabled without the recipient, which leads to an error
  frontend/test/metabase/scenarios/sharing/subscriptions.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#17668 Fix #17657: No recipients causes error resulting in blank screen
  frontend/src/metabase/lib/pulse.js
  frontend/src/metabase/sharing/components/PulsesListSidebar.jsx
  frontend/test/metabase/pulse/pulse.unit.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/17657.cy.spec.js
  frontend/test/metabase/scenarios/sharing/subscriptions.cy.spec.js
Labels: backport

#17670 Don't throw exception when archiving a dashboard in non-root collection
  src/metabase/models/pulse.clj
  test/metabase/models/pulse_test.clj
Labels: backport

#17699 #17658 Repro: Not possible to delete dashboard subscription unless dashboard is in root collection
  frontend/test/metabase/scenarios/sharing/reproductions/17658.cy.spec.js
Labels: .CI & Tests, support/Repro
