Repository metabase/metabase, pull requests merged in 2021-09, with the labels that each got.

#17707 Fix failing geolocation test :wrench:
  test/metabase/api/login_history_test.clj
  test/metabase/server/request/util_test.clj
Labels: backport

#17697 Fix #17673: Rounded buttons have excessive white background
  frontend/src/metabase/components/SchedulePicker.jsx
Labels: .Tech Debt or Refactoring, .CSS

#17715 Remove Cypress from yarn `resolutions`
  package.json
  yarn.lock
Labels: .Tech Debt or Refactoring, .CI & Tests

#17680 Collection sidebar: expand/collapse children when clicking on parent collection name
  frontend/src/metabase/collections/containers/CollectionSidebar/Collections/CollectionsList/CollectionsList.jsx
  frontend/src/metabase/collections/containers/CollectionSidebar/Collections/CollectionsList/CollectionsList.unit.spec.js
Labels: .bugbash

#17678 Only delete alert for card with multiple breakouts when a goal is defined
  frontend/test/metabase/scenarios/sharing/reproductions/17547.cy.spec.js
  src/metabase/api/card.clj
  test/metabase/api/card_test.clj
Labels: backport

#17708 Fix joins with incomplete conditions are removed on query run
  frontend/src/metabase-lib/lib/queries/StructuredQuery.js
  frontend/src/metabase-lib/lib/queries/structured/Join.js
  frontend/src/metabase/query_builder/components/notebook/NotebookStep.jsx
  frontend/test/metabase-lib/lib/queries/StructuredQuery-clean.unit.spec.js
  frontend/test/metabase-lib/lib/queries/structured/Join.unit.spec.js
  frontend/test/metabase/scenarios/question/reproductions/17710-notebook-incomplete-joins-removed.cy.spec.js
Labels: .CI & Tests, support/Repro

#17706 Fix chain filter search against FieldValues that contains nil
  src/metabase/models/params/chain_filter.clj
  test/metabase/models/params/chain_filter_test.clj
Labels: backport

#17747 Run Percy (sanity check) visual tests in CircleCI
  .circleci/config.yml
  docs/developers-guide/images/visual-tests/percy-healthcheck-step.png
  docs/developers-guide/index.md
  docs/developers-guide/visual-tests.md
Labels: .Tech Debt or Refactoring, .CI & Tests

#17760 #17751 Repro: Filter with a single long value hides the remove-button
  frontend/test/metabase/scenarios/native-filters/reproductions/17751-long-filter-name-hides-close-icon.cy.spec.js
Labels: .CI & Tests, support/Repro

#17742 #17738 Repro: "Native query editing" permission selector is inconsistent between "No self service" and "Block" permissions
  frontend/test/metabase/scenarios/admin/permissions/permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#17746 Fix field filter no longer responding after selecting "None"
  frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.jsx
  frontend/test/metabase/scenarios/native-filters/sql-field-filter-none.cy.spec.js
Labels: backport

#17776 #17768 Repro: If Entity Key fields are fingerprinted, then they show binning options in GUI
  frontend/test/metabase/scenarios/admin/datamodel/reproductions/17768-entity-key-showing-binning-options.cy.spec.js
Labels: .CI & Tests, support/Repro

#17778 New `permissions` E2E CI group
  .circleci/config.yml
  frontend/test/metabase/scenarios/permissions/admin-permissions.cy.spec.js
  frontend/test/metabase/scenarios/permissions/sandboxes.cy.spec.js
Labels: .Tech Debt or Refactoring, .CI & Tests, backport

#17780 #17775 Repro: Dashboard filter on a custom column doesn't work
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/17775-filter-custom-column-date.cy.spec.js
Labels: .CI & Tests, support/Repro

#17735 Fixing a missing link in Markdown
  docs/troubleshooting-guide/linked-filters.md
Labels: .Documentation

#17786 #16785 Repro: Search shows hidden tables
  frontend/test/metabase/scenarios/onboarding/search/reproductions/16785-do-not-display-hidden-tables.cy.spec.js
Labels: .CI & Tests, support/Repro

#17779 #17777 Repro: Hiding all tables in data model removes them from the permissions page
  frontend/test/metabase/scenarios/permissions/reproductions/17777-hidden-tables-not-available.cy.spec.js
Labels: .CI & Tests, support/Repro

#17787 #17763 Repro: Trying to set "Granular" permissions after "Block" is broken
  frontend/test/metabase/scenarios/permissions/reproductions/17763-cannot-edit-granular-after-block.cy.spec.js
Labels: .CI & Tests, support/Repro

#17774 Fix unable to click "Learn more" on custom expression
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield.jsx
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
Labels: backport

#17785 Fix SAML login with OpenAM
  src/metabase/util.clj
  test/metabase/util_test.clj
Labels: backport

#17794 Move `notifications` spec to the `onboarding` folder
  frontend/test/metabase/scenarios/onboarding/notifications.cy.spec.js
Labels: .Tech Debt or Refactoring

#17842 docs - dev guide links
  docs/README.md
  docs/developers-guide.md
  docs/developers-guide/build.md
  docs/developers-guide/frontend.md
  docs/developers-guide/start.md
Labels: .Documentation

#17835 Filling in missing text in login troubleshooting guide
  docs/troubleshooting-guide/cant-log-in.md
Labels: .Documentation

#17823 Fix dashboard subscriptions sidebar for sandboxed users
  frontend/src/metabase/sharing/components/PulsesListSidebar.jsx
  frontend/src/metabase/sharing/components/SharingSidebar.jsx
Labels: support/Repro

#17684 Update 05-visualizing-results.md
  docs/users-guide/05-visualizing-results.md
Labels: .Documentation

#17727 Fix removing a notebook section can remove other sections
  frontend/src/metabase-lib/lib/queries/structured/Join.js
  frontend/src/metabase/query_builder/components/notebook/NotebookStep.jsx
  frontend/src/metabase/query_builder/components/notebook/lib/steps.js
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx
  frontend/test/metabase-lib/lib/queries/StructuredQuery-clean.unit.spec.js
  frontend/test/metabase-lib/lib/queries/structured/Join.unit.spec.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/17712-notebook-extra-sections-removed.cy.spec.js
Labels: .CI & Tests, support/Repro

#17799 i18n: do not remove empty plural from translation
  bin/i18n/src/i18n/common.clj
  bin/i18n/test/i18n/create_artifacts/frontend_test.clj
  bin/i18n/test/i18n/create_artifacts/test_common.clj
Labels: backport

#17925 Fix data points formatting for multi-series
  frontend/src/metabase/visualizations/lib/apply_axis.js
  frontend/src/metabase/visualizations/lib/chart_values.js
  frontend/test/metabase/scenarios/visualizations/line_chart.cy.spec.js
Labels: backport

#17929 Show error messages when rendering card fails
  frontend/src/metabase/visualizations/components/CardRenderer.jsx
  frontend/src/metabase/visualizations/components/LeafletChoropleth.jsx
  frontend/src/metabase/visualizations/lib/LineAreaBarPostRender.js
  frontend/test/metabase/scenarios/visualizations/line_chart.cy.spec.js
Labels: backport

#17969 Fix grid map tooltips without metric column
  frontend/src/metabase/visualizations/components/ChartTooltip.jsx
  frontend/test/metabase/scenarios/visualizations/maps.cy.spec.js
Labels: backport

#17980 Add repro for #17975: Saved Question field change removes sorting
  frontend/test/metabase/scenarios/binning/binning-reproductions.cy.spec.js
Labels: .CI & Tests, support/Repro

#17976 Fix incorrect table names on join dimensions
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx
  frontend/test/metabase/scenarios/question/joins.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/17968-notebook-join-table-names.cy.spec.js
Labels: .CI & Tests, support/Repro

#18026 docs - restore original file name
  docs/operations-guide/handling-timezones.md
  docs/troubleshooting-guide/index.md
  docs/troubleshooting-guide/timezones.md
Labels: .Documentation

#18029 #6239 Repro: Not possible to sort by Custom Expression fields
  frontend/test/metabase/scenarios/question/reproductions/6239.cy.spec.js
Labels: .CI & Tests, support/Repro

#17994 docs - update api doc gen code
  docs/api-documentation.md
  src/metabase/cmd/endpoint_dox.clj
  test/metabase/cmd/endpoint_dox_test.clj
Labels: .Documentation

#18033 #18028 Repro: X-ray dashboards crash on first opening immediately after they are saved
  frontend/test/metabase/scenarios/dashboard/x-rays.cy.spec.js
Labels: .CI & Tests, support/Repro

#18014 #18009 Repro: Nodata user can create dashboard subscription, but receives an error
  frontend/test/metabase/scenarios/sharing/reproductions/18009-nodata-creates-subscription-receives-error.cy.spec.js
Labels: .CI & Tests, support/Repro

#18037 docs - update link in troubleshooting article
  docs/troubleshooting-guide/sandboxing.md
Labels: .Documentation

#18073 #18061 Repro(s): Pin map only containing null location results crashes the frontend
  frontend/test/metabase/scenarios/visualizations/reproductions/18061-maps-only-nulls-crash-frontend.cy.spec.js
Labels: .CI & Tests, support/Repro

#18071 Git ignore `clj-kondo` cache
  .gitignore
Labels: .Tech Debt or Refactoring

#18057 Add initial E2E coverage for "Tools to fix question errors"
  frontend/test/metabase/scenarios/admin/tools/erroring-questions.cy.spec.js
Labels: .CI & Tests, support/Repro

#18076 #9027 Repro: New questions do not appear in 'Saved Questions' until you refresh the browser
  frontend/test/metabase/scenarios/question/reproductions/9027-new-questions-not-in-saved-questions-immediately.cy.spec.js
Labels: .CI & Tests, support/Repro

#17669 Troubleshooting the app database
  docs/operations-guide/migrating-from-h2.md
  docs/operations-guide/running-metabase-on-heroku.md
  docs/troubleshooting-guide/application-database.md
  docs/troubleshooting-guide/index.md
  docs/troubleshooting-guide/loading-from-h2.md
Labels: .Documentation

#18080 #18021 Repro: "Recents" list in search should display the Verified badge
  frontend/test/metabase/scenarios/moderation/reproductions/18021-verified-badge-not-visible-in-recents.cy.spec.js
Labels: .CI & Tests, support/Repro

#17861 docs - revise activation guide
  docs/enterprise-guide/activating-the-enterprise-edition.md
Labels: .Documentation

#18127 Remove special cases in tests for Snowflake
  enterprise/backend/test/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions_test.clj
  test/metabase/query_processor_test/nested_queries_test.clj
Labels: backport

#18116 Wait qa db metadata load
  frontend/test/__support__/e2e/helpers/e2e-qa-databases-helpers.js
Labels: .Tech Debt or Refactoring, .CI & Tests

#17948 docs - multi-column joins
  docs/users-guide/custom-questions.md
  docs/users-guide/images/notebook/join-a-b-c.png
  docs/users-guide/images/notebook/joining-on-multiple-columns.png
  docs/users-guide/images/notebook/notebook-ui.png
Labels: .Documentation, backport

#17926 docs - question details sidebar
  docs/users-guide/03-basic-exploration.md
  docs/users-guide/04-asking-questions.md
  docs/users-guide/05-visualizing-results.md
  docs/users-guide/06-sharing-answers.md
  docs/users-guide/collections.md
  docs/users-guide/images/basic-exploration/search-results.gif
  docs/users-guide/images/basic-exploration/search-results.png
  docs/users-guide/images/collections/official-collection.png
  docs/users-guide/images/collections/our-analytics-page.png
  docs/users-guide/images/collections/pinned-items.png
  docs/users-guide/images/collections/question-checkbox.png
  docs/users-guide/images/download-button.png
  docs/users-guide/images/notebook/duplicate-question.png
  docs/users-guide/images/sharing-answers/question-details-sidebar.png
  docs/users-guide/images/sharing-answers/verified-icon.png
Labels: .Documentation, backport

#18129 Run all QA DB docker images at once in CI
  .circleci/config.yml
Labels: .Tech Debt or Refactoring, .CI & Tests

#17882 docs - updated permissions
  docs/administration-guide/05-setting-permissions.md
  docs/administration-guide/06-collections.md
  docs/administration-guide/data-permissions.md
  docs/administration-guide/images/change-access.png
  docs/administration-guide/images/permissions.png
  docs/administration-guide/images/table-permissions.png
  docs/enterprise-guide/data-sandboxes.md
  docs/enterprise-guide/images/sandboxing/advanced-example-2-filtering-question.png
  docs/enterprise-guide/images/sandboxing/advanced-example-2-sandboxing-options.png
  docs/enterprise-guide/images/sandboxing/change-access-confirm-modal.png
  docs/enterprise-guide/images/sandboxing/edit-sandboxed-access.png
  docs/enterprise-guide/images/sandboxing/edit-user-details.png
  docs/enterprise-guide/images/sandboxing/grant-sandboxed-access.png
  docs/enterprise-guide/images/sandboxing/select-user-attribute.png
Labels: .Documentation, backport

#18138 Do not emit view logs when there's no card id for query viewlogs (fixes #18136)
  src/metabase/query_processor/middleware/process_userland_query.clj
  test/metabase/query_processor/middleware/process_userland_query_test.clj
Labels: backport

#18106 Cypress E2E postgres snapshot
  .circleci/config.yml
  frontend/test/__runner__/cypress-runner-run-tests.js
  frontend/test/metabase-db/postgres/custom-column.cy.spec.js
  frontend/test/metabase-db/postgres/native.cy.spec.js
  frontend/test/metabase-db/postgres/permissions.cy.spec.js
  frontend/test/metabase-db/postgres/query.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/add-external.cy.spec.js
  frontend/test/metabase/scenarios/permissions/reproductions/13347-cannot-select-saved-question-in-database-without-data-permissions.cy.spec.js
  frontend/test/metabase/scenarios/permissions/reproductions/14873-regextract-in-sandboxed-table.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/13263-postgres-show-row-details-on-pk-click.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/13751-cc-allow-strings-in-filter.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/14517-cc-do-not-remove-regex-escape-chars.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/14957-unable-to-save-question-before-query-executed.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/15714-ce-percentile-accepts-two-params.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/14148-pivot-table-postgres.cy.spec.js
  frontend/test/snapshot-creators/default.cy.snap.js
Labels: .Tech Debt or Refactoring, .CI & Tests

#18170 Translate Whitelabel color options
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/ColorSchemeWidget.jsx
Labels: Customization/i18n, backport

#18055 Fix errors from disallowed characters in BigQuery custom expression names
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj
  modules/drivers/bigquery/src/metabase/driver/bigquery/query_processor.clj
  src/metabase/driver/sql/query_processor.clj
  test/metabase/query_processor_test/expressions_test.clj
Labels: backport
