Repository metabase/metabase, pull requests merged in 2021-07, with the labels that each got.

#16846 Add Cypress helper function `openNativeEditor`
  frontend/test/__support__/e2e/cypress.js
  frontend/test/metabase/scenarios/admin/audit/ad-hoc.cy.spec.js
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/parameters.cy.spec.js
  frontend/test/metabase/scenarios/filters/sql-filters.cy.spec.js
  frontend/test/metabase/scenarios/native/native.cy.spec.js
  frontend/test/metabase/scenarios/native/snippets/snippets.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/maps.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/waterfall.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16852 [SQL filters coverage] Add initial set of e2e tests around SQL field filter type of Number
  frontend/test/metabase/scenarios/filters/sql-field-filter-number.cy.spec.js
Labels: .CI & Tests

#16851 [SQL filters coverage] Add initial set of e2e tests around SQL field filter type of String
  frontend/test/metabase/scenarios/filters/sql-field-filter-string.cy.spec.js
Labels: .CI & Tests

#16853 Fix random collection is suggested when saving a new dashboard
  frontend/src/metabase/entities/collections.js
  frontend/src/metabase/lib/urls.js
  frontend/test/metabase/lib/urls.unit.spec.js
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#16868 Move stray folders into existing CI e2e groups
  frontend/test/metabase/scenarios/onboarding/home/browse.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/search/search-pagination.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/search/search-typehead.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/search/search.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16882 [Cypress Helpers] Add `filterWidget` helper function
  frontend/test/__support__/e2e/cypress.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard_local-only.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/title-drill.cy.spec.js
  frontend/test/metabase/scenarios/filters/sql-filters.cy.spec.js
  frontend/test/metabase/scenarios/native/native.cy.spec.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16854 [SQL filters coverage] Add initial set of e2e tests around SQL field filter type of Date
  frontend/test/metabase/scenarios/filters/sql-field-filter-date.cy.spec.js
Labels: .CI & Tests

#16884 [Cypress Helpers] Extract functions into separate files
  frontend/test/__support__/e2e/cypress.js
  frontend/test/__support__/e2e/helpers/e2e-ad-hoc-question-helpers.js
  frontend/test/__support__/e2e/helpers/e2e-assertion-helpers.js
  frontend/test/__support__/e2e/helpers/e2e-dashboard-helpers.js
  frontend/test/__support__/e2e/helpers/e2e-data-model-helpers.js
  frontend/test/__support__/e2e/helpers/e2e-database-metadata-helpers.js
  frontend/test/__support__/e2e/helpers/e2e-deprecated-helpers.js
  frontend/test/__support__/e2e/helpers/e2e-enterprise-helpers.js
  frontend/test/__support__/e2e/helpers/e2e-misc-helpers.js
  frontend/test/__support__/e2e/helpers/e2e-mock-app-settings-helpers.js
  frontend/test/__support__/e2e/helpers/e2e-open-table-helpers.js
  frontend/test/__support__/e2e/helpers/e2e-qa-databases-helpers.js
  frontend/test/__support__/e2e/helpers/e2e-setup-helpers.js
  frontend/test/__support__/e2e/helpers/e2e-ui-elements-helpers.js
  frontend/test/metabase/scenarios/admin/people/people.cy.spec.js
  frontend/test/metabase/scenarios/question/public/question.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16887 [SQL filters coverage] Extract and apply basic SQL filter helpers
  frontend/test/metabase/scenarios/filters/helpers/e2e-sql-filter-helpers.js
  frontend/test/metabase/scenarios/filters/sql-field-filter-date.cy.spec.js
  frontend/test/metabase/scenarios/filters/sql-field-filter-number.cy.spec.js
  frontend/test/metabase/scenarios/filters/sql-field-filter-string.cy.spec.js
  frontend/test/metabase/scenarios/filters/sql-filters.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16891 [SQL filters coverage] Extract and apply SQL field filter helpers
  frontend/test/metabase/scenarios/filters/helpers/e2e-field-filter-helpers.js
  frontend/test/metabase/scenarios/filters/sql-field-filter-date.cy.spec.js
  frontend/test/metabase/scenarios/filters/sql-field-filter-number.cy.spec.js
  frontend/test/metabase/scenarios/filters/sql-field-filter-string.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16892 [SQL filters coverage] Extract and apply date filter helpers
  frontend/test/metabase/scenarios/filters/helpers/e2e-date-filter-helpers.js
  frontend/test/metabase/scenarios/filters/sql-field-filter-date.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16895 [SQL filters coverage] Simplify `openEntryForm` function
  frontend/test/metabase/scenarios/filters/helpers/e2e-field-filter-helpers.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16893 [SQL filters coverage] Extract and apply SQL field filter data
  frontend/test/metabase/scenarios/filters/helpers/e2e-field-filter-data-objects.js
  frontend/test/metabase/scenarios/filters/sql-field-filter-date.cy.spec.js
  frontend/test/metabase/scenarios/filters/sql-field-filter-number.cy.spec.js
  frontend/test/metabase/scenarios/filters/sql-field-filter-string.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16898 [SQL filters coverage] Group reproductions
  frontend/test/metabase/scenarios/filters/reproductions/11480.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/11580.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/12228.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/12581.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/13961.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/14145.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/14302.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/15163.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/15444.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/15460.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/15700.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/15981.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/16739.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/9357.cy.spec.js
  frontend/test/metabase/scenarios/native/native.cy.spec.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
  frontend/test/metabase/scenarios/question/public/question.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16902 #16886 Repro: "Run selected text" removes everything but the selected text from the query
  frontend/test/metabase/scenarios/native/reproductions/16886.cy.spec.js
Labels: .CI & Tests, support/Repro

#16905 docs - update links
  docs/administration-guide/01-managing-databases.md
  docs/operations-guide/running-metabase-on-azure.md
Labels: .Documentation

#16341 docs - connecting to dbs with ssl certificates
  docs/administration-guide/secure-database-connections-with-ssl-certificates.md
  docs/administration-guide/start.md
Labels: .Documentation

#16903 #16855 Repro: Search does not work for users without data access
  frontend/test/metabase/scenarios/onboarding/search/search.cy.spec.js
Labels: .CI & Tests, support/Repro

#16896 Test collection sidebar responsiveness
  frontend/test/metabase/scenarios/collections/collections-sidebar.cy.spec.js
Labels: .CI & Tests, support/Repro

#14206 Docs sso tutorial auth0 14185
  docs/enterprise-guide/authenticating-with-saml.md
  docs/enterprise-guide/images/saml-auth0/auth0callbackurl.png
  docs/enterprise-guide/images/saml-auth0/auth0createapp.png
  docs/enterprise-guide/images/saml-auth0/auth0regularapp.png
  docs/enterprise-guide/images/saml-auth0/auth0saml2addon.png
  docs/enterprise-guide/images/saml-auth0/auth0samlmappings.png
  docs/enterprise-guide/images/saml-auth0/auth0samlusage.png
  docs/enterprise-guide/saml-auth0.md
Labels: .Documentation

#16829 Remove `recompose`
  frontend/src/metabase/admin/settings/components/widgets/CustomGeoJSONWidget.jsx
  frontend/src/metabase/components/List.jsx
  frontend/src/metabase/components/ListItem.jsx
  frontend/src/metabase/components/QueryButton.jsx
  frontend/src/metabase/components/SidebarItem.jsx
  frontend/src/metabase/components/TitleAndDescription.jsx
  frontend/src/metabase/components/TooltipPopover.jsx
  frontend/src/metabase/reference/components/Detail.jsx
  frontend/src/metabase/reference/components/EditHeader.jsx
  frontend/src/metabase/reference/components/EditableReferenceHeader.jsx
  frontend/src/metabase/reference/components/Field.jsx
  frontend/src/metabase/reference/components/FieldToGroupBy.jsx
  frontend/src/metabase/reference/components/FieldTypeDetail.jsx
  frontend/src/metabase/reference/components/ReferenceHeader.jsx
  frontend/src/metabase/reference/components/UsefulQuestions.jsx
  frontend/src/metabase/reference/databases/DatabaseSidebar.jsx
  frontend/src/metabase/reference/databases/FieldSidebar.jsx
  frontend/src/metabase/reference/databases/TableSidebar.jsx
  frontend/src/metabase/reference/guide/BaseSidebar.jsx
  frontend/src/metabase/reference/metrics/MetricSidebar.jsx
  frontend/src/metabase/reference/segments/SegmentFieldSidebar.jsx
  frontend/src/metabase/reference/segments/SegmentSidebar.jsx
  frontend/src/metabase/selectors/metadata.js
  frontend/src/metabase/selectors/shallowEqual.js
  package.json
  yarn.lock
Labels: .Tech Debt or Refactoring

#16915 Mark "Every field is hidden right now" string for translation
  frontend/src/metabase/visualizations/visualizations/Table.jsx
Labels: .Tech Debt or Refactoring, Customization/i18n

#16959 docs - fix pulse link [closes #16953]
  docs/faq/general/what-languages-can-be-used-with-metabase.md
  docs/users-guide/07-dashboards.md
  frontend/src/metabase/pulse/components/PulseEdit.jsx
Labels: .Documentation

#16964 Add `addFilterToDashboard` Cypress custom command
  frontend/test/__support__/e2e/commands.js
  frontend/test/__support__/e2e/commands/api/dashboardFilters.js
  frontend/test/metabase/scenarios/dashboard/parameters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/title-drill.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/15163.cy.spec.js
Labels: .CI & Tests

#16928 [SQL filters coverage] Add initial set of e2e tests around SQL field filter type of "None"
  frontend/test/metabase/scenarios/filters/sql-field-filter-none.cy.spec.js
Labels: .CI & Tests, support/Repro

#16921 #16918 Repro: Pulse fails when question has date field with "Month of Year"
  frontend/test/metabase/scenarios/sharing/reproductions/16918.cy.spec.js
Labels: .CI & Tests, support/Repro

#16926 [SQL filters coverage] Add initial set of e2e tests around SQL field filter type of ID
  frontend/test/metabase/scenarios/filters/sql-field-filter-id.cy.spec.js
Labels: .CI & Tests

#17006 [Cypress runner] Set `HAS_ENTERPRISE_TOKEN` using Configuration API
  frontend/test/__runner__/run_cypress_tests.js
  frontend/test/__support__/e2e/cypress-plugins.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#17015 [Cypress runner] Get version
  frontend/test/__runner__/cypress-runner-get-version.js
  frontend/test/__runner__/cypress-runner-utils.js
  frontend/test/__runner__/run_cypress_tests.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#17024 #17019 Repro: Question filters don't for for embed/public scenarios
  frontend/test/metabase/scenarios/filters/reproductions/17019.cy.spec.js
Labels: .CI & Tests, support/Repro

#17009 Fix native question looses visualisation settings if query fails
  frontend/src/metabase-lib/lib/Question.js
  frontend/src/metabase/query_builder/components/view/ViewFooter.jsx
  frontend/src/metabase/visualizations/visualizations/Table.jsx
  frontend/test/__support__/e2e/helpers/e2e-misc-helpers.js
  frontend/test/metabase/scenarios/native/reproductions/16914.cy.spec.js
Labels: .CI & Tests, support/Repro

#17041 #17033 Repro: An error occurs when opening a public question with filters having default parameters
  frontend/test/metabase/scenarios/question/public/question.cy.spec.js
Labels: .CI & Tests, support/Repro

#17010 [Cypress runner] Use Cypress' Module API to generate Cypress snapshots
  frontend/test/__runner__/generate-cypress-snapshots.js
  frontend/test/__runner__/run_cypress_tests.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16970 Add `createNativeQuestionAndDashboard` Cypress custom command
  frontend/test/__support__/e2e/commands.js
  frontend/test/__support__/e2e/commands/api/composite/createNativeQuestionAndDashboard.js
  frontend/test/metabase/scenarios/dashboard/title-drill.cy.spec.js
Labels: .CI & Tests

#17066 Rename CI group `filters` -> `native-filters`
  .circleci/config.yml
  frontend/test/metabase/scenarios/native-filters/helpers/e2e-date-filter-helpers.js
  frontend/test/metabase/scenarios/native-filters/helpers/e2e-field-filter-data-objects.js
  frontend/test/metabase/scenarios/native-filters/helpers/e2e-field-filter-helpers.js
  frontend/test/metabase/scenarios/native-filters/helpers/e2e-sql-filter-helpers.js
  frontend/test/metabase/scenarios/native-filters/reproductions/11480.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/11580.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/12228.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/12581.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/13961.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/14145.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/14302.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/15163.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/15444.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/15460.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/15700.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/15981.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/16739.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/17019.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/9357.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/sql-field-filter-date.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/sql-field-filter-id.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/sql-field-filter-none.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/sql-field-filter-number.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/sql-field-filter-string.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/sql-filters.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#17068 Adjust affected repros by waiting for the metadata to load
  frontend/test/metabase/scenarios/binning/binning-reproductions.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#17079 [Dashboard filters] Create initial infrastructure and group repros
  .circleci/config.yml
  frontend/test/metabase/scenarios/dashboard-filters/old-parameters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/parameters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/12614.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/12720.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/13150.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/15119.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/15279.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/15689.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/15695.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/16103.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/6660.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests

#17099 [Cypress runner] Run Cypress
  .circleci/config.yml
  frontend/test/__runner__/cypress-runner-generate-snapshots.js
  frontend/test/__runner__/cypress-runner-run-tests.js
  frontend/test/__runner__/run_cypress_tests.js
  frontend/test/__support__/e2e/cypress-plugins.js
  frontend/test/metabase-db/README.md
  frontend/test/metabase/scenarios/smoketest/README.md
  package.json
  yarn.lock
Labels: .CI & Tests

#17112 #17043 Repro: With Whitelabel custom name, Metabase name is still shown multiple places in Admin Panel
  frontend/test/metabase/scenarios/admin/settings/whitelabel.cy.spec.js
Labels: .CI & Tests, support/Repro

#17104 Run Cypress workflows in CircleCI as a matrix
  .circleci/config.yml
Labels: .CI & Tests, .Tech Debt or Refactoring

#17140 #17139 Repro: Clicking on cancel edit dashboard without any changes removes the dashboard filter
  frontend/test/__support__/e2e/helpers/e2e-dashboard-helpers.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/17139.cy.spec.js
Labels: .CI & Tests, support/Repro

#17159 Remove `image diff`
  bin/compare-screenshots
  package.json
  yarn.lock
Labels: .Tech Debt or Refactoring

#16930 Add and enable `cypress-grep` library
  frontend/test/__support__/e2e/cypress-plugins.js
  frontend/test/__support__/e2e/cypress.js
  package.json
  yarn.lock
Labels: .CI & Tests

#17181 Upgrade `xlsx` library
  package.json
  yarn.lock
Labels: .CI & Tests

#17173 [Dashboard filters coverage] Add initial set of tests for dashboard date filters
  frontend/test/__support__/e2e/helpers/e2e-dashboard-helpers.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-date.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/helpers/e2e-dashboard-filter-data-objects.js
Labels: .CI & Tests

#17190 [Dashboard filters coverage] Add initial set of tests for dashboard ID filter
  frontend/test/__support__/e2e/helpers/e2e-dashboard-helpers.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-id.cy.spec.js
Labels: .CI & Tests

#17188 [Dashboard filters coverage] Add initial set of tests for dashboard number filters
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-date.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-number.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/helpers/e2e-dashboard-filter-data-objects.js
Labels: .CI & Tests

#17191 [Dashboard filters coverage] Add initial set of tests for dashboard location filters
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-location.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/helpers/e2e-dashboard-filter-data-objects.js
Labels: .CI & Tests

#17192 [Dashboard filters coverage] Add initial set of tests for dashboard text/category filters
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-text-category.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/helpers/e2e-dashboard-filter-data-objects.js
Labels: .CI & Tests

#17202 #17200 Repro: Only the first 50 user groups are displayed
  frontend/test/metabase/scenarios/admin/people/people.cy.spec.js
Labels: .CI & Tests, support/Repro

#17201 Repro for #15342: The order of join-type causes query fail
  frontend/test/metabase-db/mysql/reproductions/15342.cy.spec.js
Labels: .CI & Tests, support/Repro

#17203 #17186 Repro: People search dropdown goes outside of the screen
  frontend/test/metabase/scenarios/sharing/subscriptions.cy.spec.js
Labels: .CI & Tests, support/Repro

#17153 Editing FAQ.
  docs/faq/general/can-i-request-a-new-feature.md
  docs/faq/general/do-we-need-a-data-processing-agreement.md
  docs/faq/general/does-metabase-do-x.md
  docs/faq/general/does-metabase-have-access-to-my-companys-data.md
  docs/faq/general/how-do-i-ask-for-help.md
  docs/faq/general/is-metabase-508-compliant.md
  docs/faq/general/supported-browsers.md
  docs/faq/general/what-if-i-find-a-bug.md
  docs/faq/general/what-languages-can-be-used-with-metabase.md
  docs/faq/setup/how-do-i-integrate-with-sso.md
  docs/faq/setup/i-am-having-trouble-running-metabase.md
  docs/faq/setup/what-is-h2.md
  docs/faq/setup/when-should-i-migrate-h2.md
  docs/faq/setup/which-databases-does-metabase-support.md
  docs/faq/start.md
  docs/faq/using-metabase/cant-access-data-i-need.md
  docs/faq/using-metabase/how-do-i-answer-questions-when-data-is-in-multiple-databases.md
  docs/faq/using-metabase/how-do-i-answer-questions-with-joins.md
  docs/faq/using-metabase/how-do-i-ask-questions.md
  docs/faq/using-metabase/how-do-i-reset-my-password.md
  docs/faq/using-metabase/i-am-not-getting-email-notifications.md
Labels: .Documentation

#17209 docs - troubleshooting guide: load from h2
  docs/operations-guide/migrating-from-h2.md
  docs/troubleshooting-guide/application-database.md
  docs/troubleshooting-guide/datawarehouse.md
  docs/troubleshooting-guide/loading-from-h2.md
  docs/users-guide/writing-sql.md
Labels: .Documentation

#17174 Performance troubleshooting guide
  docs/troubleshooting-guide/index.md
  docs/troubleshooting-guide/performance.md
Labels: .Documentation

#17221 Minor fixes to performance troubleshooting guide
  docs/troubleshooting-guide/performance.md
Labels: .Documentation

#17207 Troubleshooting guide for sandboxing
  docs/troubleshooting-guide/sandboxing.md
Labels: .Documentation

#17236 docs - troubleshooting section
  docs/troubleshooting-guide/application-database.md
  docs/troubleshooting-guide/index.md
  docs/troubleshooting-guide/ldap.md
  docs/troubleshooting-guide/performance.md
Labels: .Documentation

#17255 Troubleshooting sync/fingerprint/scan
  docs/troubleshooting-guide/index.md
  docs/troubleshooting-guide/sync-fingerprint-scan.md
Labels: .Documentation
