Repository metabase/metabase, pull requests merged in 2021-02, with the labels that each got.

#14606 Update values and fix failing Cypress tests on `master`
  frontend/test/metabase/scenarios/admin/datamodel/metrics.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/segments.cy.spec.js
  frontend/test/metabase/scenarios/question/new.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14593 #13785 Repro: Clicking on a bar graph that represents a date range chooses only the start of the range
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
Labels: .CI & Tests, support/Repro

#14611 Remove Cypress test for EE_524 issue
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14615 CI: include sample-dataset.db.mv.db in frontend checksums
  .circleci/config.yml
Labels: .CI & Tests

#14619 #14052 Repro: Cannot save to sub-collection when access to its parent is revoked
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#14631 #14629 Repro: Sandboxing should work on tables with remapped FK display values
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, support/Repro

#14633 docs - image and link fixes
  docs/enterprise-guide/full-app-embedding.md
  docs/users-guide/03-basic-exploration.md
  docs/users-guide/05-visualizing-results.md
  docs/users-guide/07-dashboards.md
  docs/users-guide/10-pulses.md
  docs/users-guide/images/search-results.png
  docs/users-guide/images/sharing-answers/share-icon.png
Labels: .Documentation

#14638 #10474 Repro: Cannot use Saved Question with remapped "Display values"="Use foreign key"
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
Labels: .CI & Tests, support/Repro

#14618 #14604 Repro: Custom columns break pivot tables
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
Labels: .CI & Tests, support/Repro

#14643 Skip repro for EE_520
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14641 #14636 Repro: Troubleshooting tasks pagination not working
  frontend/test/metabase/scenarios/admin/troubleshooting/tasks.cy.spec.js
Labels: .CI & Tests, support/Repro

#14661 Add an alternative QB-version of the repro for EE_520
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, support/Repro

#14659 Merge nested settings between question and dashcard
  frontend/src/metabase/dashboard/components/DashCard.jsx
  frontend/src/metabase/visualizations/lib/settings.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
  frontend/test/metabase/visualizations/lib/settings.unit.spec.js
Labels: support/Repro

#14665 #14650 Repro: Drill-through on a map results in a wrong filter value
  frontend/test/metabase/scenarios/visualizations/maps.cy.spec.js
Labels: .CI & Tests, support/Repro

#14674 Log complete token validation error only to debug log
  src/metabase/public_settings/metastore.clj
Labels: .Backend, Embedding/

#14690 #14612 Repro: Sandboxing limitations should have meaningful UI error message/feedback
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, support/Repro

#14698 Skip failing pivot tables Cypress tests
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14663 Split (SQL) repro for EE_520 in two versions
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, support/Repro

#14703 Merge `sandboxes.cy.spec.js` changes and improvements from `release-x.38.x` branch
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14723 #14649 Repro: Cannot add subsequent aggregation on a custom expresssion in notebook
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
Labels: .CI & Tests, support/Repro

#14725 #13150 Repro: Dashboard card sends a query for each filter defined
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, support/Repro

#14728 #14726 Repro: Custom filter expression does not show original editor on subsequent click
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
Labels: .CI & Tests, support/Repro

#14727 #14724 Repro: Cannot use saved question with joins as a base for new question
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
Labels: .CI & Tests, support/Repro

#14736 Export `remapDisplayValueToFK` function
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
  frontend/test/__support__/cypress.js
Labels: .CI & Tests

#14738 Add "remapped" version of the repro for #14724
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14752 #14724 Repro ("inception" version): Handle multi-level nesting
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
Labels: .CI & Tests, support/Repro

#14770 #14766 Repro: Cannot summarize columns from joined table based on a Saved Question
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, support/Repro

#14772 #12492 Repro: Custom expression filter with dates wrong display on subsequent click
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#14778 #14705 Repro: Cannot select all items in a collection using checkbox
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#14795 #14787 Repro: "Distribution" doesn't always work on joined saved question
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
Labels: .CI & Tests, support/Repro

#14796 #14793 Repro: X-rays fails on explicit joins, when metric is for the joined table
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
Labels: .CI & Tests, support/Repro

#14798 #14749 Repro: Email settings "Save changes" button enabled without any changes
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
Labels: .CI & Tests, support/Repro

#14816 Unskip repro for #11439
  frontend/test/metabase/scenarios/question/new.cy.spec.js
Labels: .CI & Tests

#14814 #14811 Repro: Questions with post-aggregation filter on joined table breaks
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#14815 Refine and upgrade repro for #12985
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring, support/Repro

#14646 docs - postgres ssl cert validation note for 0.38
  docs/operations-guide/configuring-application-database.md
Labels: .Documentation

#14821 #14775 Repro: Custom column not removed when a join is removed
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
Labels: .CI & Tests, support/Repro

#14827 #14776 Repro: Autocomplete results not correctly showing summary columns when full word entered
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#14831 #14753 repro: Collections without sub-collections have an "expand" arrow
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#14833 Fix check for disabled button in `add.cy.spec.js`
  frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14845 #14841 Repro: Cannot remove column via QB sidebar / settings
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, support/Repro

#14847 #14843 Repro: Filtering a Custom Column does not give correct results when using "Not equal to"
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#14857 #14854 Repro: Custom Expression using `case()` function fails when referencing the same column names
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
Labels: .CI & Tests, support/Repro

#14371 docs - clarify pivot tables only work with simple and custom questions
  docs/users-guide/05-visualizing-results.md
Labels: .Documentation

#14853 Fix documentation links for developers
  frontend/src/metabase/lib/settings.js
Labels: .Documentation, .Tech Debt or Refactoring

#14865 docs - add dash subs to user guide toc
  docs/users-guide/09-multi-series-charting.md
  docs/users-guide/dashboard-subscriptions.md
  docs/users-guide/start.md
Labels: .Documentation

#14875 #14872 Repro: Multi-level aggregations fails when filter is the last section
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#14881 Add Cypress custom commands
  enterprise/frontend/test/metabase-enterprise/audit/ad-hoc.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/audit/auditing.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/snippets/snippet-permissions.cy.spec.js
  frontend/test/__support__/commands.js
  frontend/test/__support__/cypress.js
  frontend/test/metabase-db/mongo/query.cy.spec.js
  frontend/test/metabase-db/postgres/custom-column.cy.spec.js
  frontend/test/metabase-smoketest/admin.cy.spec.js
  frontend/test/metabase-smoketest/admin_setup.cy.spec.js
  frontend/test/metabase-smoketest/user.cy.spec.js
  frontend/test/metabase/scenarios/admin/people/people.cy.spec.js
  frontend/test/metabase/scenarios/admin/permissions/permissions.cy.spec.js
  frontend/test/metabase/scenarios/admin/troubleshooting/tasks.cy.spec.js
  frontend/test/metabase/scenarios/alert/alert.cy.spec.js
  frontend/test/metabase/scenarios/alert/alert_auth.cy.spec.js
  frontend/test/metabase/scenarios/alert/email_alert.cy.spec.js
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/chained-filters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard_data_permissions.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/embed.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/nested-cards.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/parameters-embedded.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/parameters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/subscriptions.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/text-box.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/x-rays.cy.spec.js
  frontend/test/metabase/scenarios/permissions.cy.spec.js
  frontend/test/metabase/scenarios/public/public.cy.spec.js
  frontend/test/metabase/scenarios/pulse/pulse.cy.spec.js
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
  frontend/test/metabase/scenarios/question/data_ref.cy.spec.js
  frontend/test/metabase/scenarios/question/downloads.cy.spec.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
  frontend/test/metabase/scenarios/question/native.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
  frontend/test/metabase/scenarios/question/nulls.cy.spec.js
  frontend/test/metabase/scenarios/question/snippets.cy.spec.js
  frontend/test/metabase/scenarios/question/trendline.cy.spec.js
  frontend/test/metabase/scenarios/question/view.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/maps.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/waterfall.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14885 #14880 Repro: Negative filter can not be converted to custom expression
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#14899 #14757 Repro: New collection saved inside "My personal collection" not available in "New collection" modal
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#14901 Revert repro for #14757 (duplicate of #14122 )
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .Tech Debt or Refactoring

#14902 #14178 Repro: "Saved Questions" dialog doesn't respect nested collections structure
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#14903 #14900 Repro: Admin > Settings > General not working, when setup using environment variable `MB_SITE_URL`
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
Labels: .CI & Tests, support/Repro

#14920 #14919 Repro: "Reset to defaults" on dashboard card "Visualization settings" removes all "Click behavior"
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
Labels: .CI & Tests, support/Repro

#14922 #14907 Repro: Snippet folder is showing as part of collections
  enterprise/frontend/test/metabase-enterprise/snippets/snippet-permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#14925 #14873 Repro: `regexextract` breaks query on a sandboxed table
  frontend/test/metabase-db/postgres/sandboxes.cy.spec.js
Labels: .CI & Tests, support/Repro

#14942 Enable running a single spec in Cypress
  .circleci/config.yml
  frontend/test/__runner__/run_cypress_tests.js
  frontend/test/metabase-smoketest/README.md
  package.json
Labels: .CI & Tests, .Tech Debt or Refactoring

#14947 Enable running a single spec in Cypress in master branch (#14942)
  .circleci/config.yml
  frontend/test/__runner__/run_cypress_tests.js
  frontend/test/metabase-smoketest/README.md
  package.json
Labels: .CI & Tests

#14952 Fix #9357: Native question filter widget reordering via drag and drop
  frontend/src/metabase-lib/lib/queries/NativeQuery.js
  frontend/test/metabase/scenarios/question/native.cy.spec.js
Labels: .CI & Tests, Querying/Notebook, support/Repro

#14955 Upgrade `react-sortable-hoc` library to the latest version
  package.json
  yarn.lock
Labels: .Tech Debt or Refactoring

#14965 #14957 Repro: Saving a question before query has been executed can be slow with UI "hanging"
  frontend/test/metabase-db/postgres/native.cy.spec.js
Labels: .CI & Tests, support/Repro

#14963 #14959 Repro: Can not convert case-insensitive filter to custom expression
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#14967 #13455 Repro: Order of rearranged columns not preserved after column removal via sidebar
  frontend/test/metabase/scenarios/question/settings.cy.spec.js
Labels: .CI & Tests, support/Repro

#14968 #14515 Repro: Slack-based dashboard subscriptions should have a "Send to Slack now" button
  frontend/test/metabase/scenarios/dashboard/subscriptions.cy.spec.js
Labels: .CI & Tests, support/Repro

#14948 Add set of Cypress custom commands related to permissions API
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
  frontend/test/__support__/commands.js
  frontend/test/metabase-db/postgres/sandboxes.cy.spec.js
  frontend/test/snapshot-creators/default.cy.snap.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#14981 #14969 Repro: Pivot tables don't work for sandboxed users
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, support/Repro
