Repository metabase/metabase, pull requests merged in 2021-10, with the labels that each got.

#18179 Separate qa db snapshots
  .circleci/config.yml
  frontend/test/__support__/e2e/cypress-plugins.js
  frontend/test/snapshot-creators/default.cy.snap.js
  frontend/test/snapshot-creators/qa-db.cy.snap.js
Labels: .Tech Debt or Refactoring, .CI & Tests

#18184 Cypress E2E Mongo snapshot
  .circleci/config.yml
  frontend/test/__runner__/cypress-runner-run-tests.js
  frontend/test/metabase-db/mongo/add.cy.spec.js
  frontend/test/metabase-db/mongo/line.cy.spec.js
  frontend/test/metabase-db/mongo/native.cy.spec.js
  frontend/test/metabase-db/mongo/query.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/add-external.cy.spec.js
  frontend/test/metabase/scenarios/native/native-mongo.cy.spec.js
  frontend/test/metabase/scenarios/native/reproductions/15946-mongo-pre-select-table.cy.spec.js
  frontend/test/metabase/scenarios/question/mongo-query.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/13097-mongo-apply-distinct-count-multiple-columns.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/16170-line-mongo-replace-missing-values-with-zero.cy.spec.js
  frontend/test/snapshot-creators/qa-db.cy.snap.js
Labels: .Tech Debt or Refactoring, .CI & Tests

#18167 Convert deprecated k:mm time style to HH:mm on viz settings normalization
  shared/src/metabase/shared/models/visualization_settings.cljc
  shared/test/metabase/shared/models/visualization_settings_test.cljc
  src/metabase/query_processor/streaming/xlsx.clj
  test/metabase/query_processor/streaming/xlsx_test.clj
Labels: backport

#18193 Cypress E2E MySQL snapshot
  .circleci/config.yml
  frontend/test/__runner__/cypress-runner-run-tests.js
  frontend/test/__support__/e2e/cypress-plugins.js
  frontend/test/metabase-db/README.md
  frontend/test/metabase-db/mysql/add.cy.spec.js
  frontend/test/metabase-db/mysql/custom-column.cy.spec.js
  frontend/test/metabase/scenarios/README.md
  frontend/test/metabase/scenarios/admin/databases/add-external.cy.spec.js
  frontend/test/metabase/scenarios/native/native-mysql.cy.spec.js
  frontend/test/metabase/scenarios/question/mongo-query.cy.spec.js
  frontend/test/metabase/scenarios/question/query-external.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/12445-mysql-cc-apply-substring.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/15342-mysql-correct-joins-order.cy.spec.js
  frontend/test/snapshot-creators/qa-db.cy.snap.js
Labels: .Tech Debt or Refactoring, .CI & Tests, backport

#18171 Show permissions for hidden tables
  frontend/src/metabase/admin/permissions/components/PermissionsEditor/PermissionsEditor.jsx
  frontend/src/metabase/admin/permissions/components/PermissionsEditor/PermissionsEditorContent.jsx
  frontend/src/metabase/admin/permissions/components/PermissionsSelect/PermissionsSelect.jsx
  frontend/src/metabase/admin/permissions/components/PermissionsSidebar/PermissionsSidebar.jsx
  frontend/src/metabase/admin/permissions/components/PermissionsSidebar/PermissionsSidebarContent.jsx
  frontend/src/metabase/admin/permissions/pages/DataPermissionsPage/DataPermissionsPage.jsx
  frontend/src/metabase/admin/permissions/pages/DatabasePermissionsPage/DatabasesPermissionsPage.jsx
  frontend/src/metabase/admin/permissions/pages/GroupDataPermissionsPage/GroupsPermissionsPage.jsx
  frontend/src/metabase/admin/permissions/permissions.js
  frontend/src/metabase/admin/permissions/selectors/data-permissions.js
  frontend/src/metabase/admin/permissions/selectors/data-permissions.unit.spec.js
  frontend/src/metabase/admin/permissions/utils/data-entity-id.js
  frontend/src/metabase/selectors/metadata.js
  frontend/test/metabase-visual/admin/permissions.cy.spec.js
  frontend/test/metabase/scenarios/permissions/admin-permissions.cy.spec.js
Labels: backport

#18151 Fix /account authentication and session deletion behavior
  frontend/src/metabase/account/routes.jsx
  frontend/src/metabase/auth/auth.js
  frontend/src/metabase/lib/auth.js
  frontend/src/metabase/routes.jsx
  frontend/test/metabase/scenarios/onboarding/setup/user_settings.cy.spec.js
Labels: backport

#18205 Fix exports for queries with aggregations
  src/metabase/query_processor/streaming.clj
  test/metabase/query_processor/streaming_test.clj
Labels: backport

#18123 GET /api/database/:id/schemas should not return 'empty' schemas
  src/metabase/api/database.clj
  src/metabase/models/table.clj
  test/metabase/api/database_test.clj
Labels: backport

#18228 Fix DataSelector infinite loop
  frontend/src/metabase/query_builder/components/DataSelector.jsx
Labels: backport

#18227 Revert "Fix combined tooltip for charts"
  frontend/src/metabase/visualizations/lib/apply_tooltips.js
  frontend/test/metabase/scenarios/visualizations/line_chart.cy.spec.js
Labels: backport

#18195 Fix composite chart layout
  frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js
  frontend/test/metabase-visual/visualizations/line.cy.spec.js
Labels: backport

#18238 Make webpack output closer to webpack 4 and fix whitelabelling
  frontend/test/metabase/scenarios/onboarding/search/recently-viewed.cy.spec.js
  webpack.config.js
Labels: backport

#18188 Fix empty state in the Erroring questions page
  enterprise/frontend/src/metabase-enterprise/audit_app/components/AuditParameters.jsx
  enterprise/frontend/src/metabase-enterprise/tools/containers/ErrorOverview.jsx
  frontend/test/metabase/scenarios/admin/tools/erroring-questions.cy.spec.js
Labels: backport

#18186 Add missing categorical charts
  frontend/src/metabase/internal/pages/StaticVizPage.jsx
  frontend/src/metabase/static-viz/components/CategoricalAreaChart/CategoricalAreaChart.jsx
  frontend/src/metabase/static-viz/components/CategoricalAreaChart/index.js
  frontend/src/metabase/static-viz/components/CategoricalLineChart/CategoricalLineChart.jsx
  frontend/src/metabase/static-viz/components/CategoricalLineChart/index.js
  frontend/src/metabase/static-viz/containers/StaticChart/StaticChart.jsx
  frontend/src/metabase/static-viz/containers/StaticChart/StaticChart.unit.spec.js
Labels: backport

#18250 reduce data picker search results to 50 items
  frontend/src/metabase/dashboard/components/add-card-sidebar/QuestionList.jsx
  frontend/src/metabase/lib/constants.js
  frontend/src/metabase/nav/components/SearchResults.jsx
  frontend/src/metabase/query_builder/components/data-search/SearchResults.jsx
Labels: backport

#18230 Fix cache native queries not working (18160)
  src/metabase/api/card.clj
  test/metabase/api/card_test.clj
Labels: backport

#18134 Restyle the Verify button
  enterprise/frontend/src/metabase-enterprise/moderation/components/ModerationActions/ModerationActions.jsx
  enterprise/frontend/src/metabase-enterprise/moderation/components/ModerationActions/ModerationActions.styled.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionDetailsSidebarPanel.jsx
Labels: backport

#18237 Fix Dashboard Subscription email validation (second pass)
  enterprise/backend/test/metabase_enterprise/advanced_config/api/pulse_test.clj
  src/metabase/api/pulse.clj
  src/metabase/models/pulse_channel.clj
  test/metabase/api/pulse_test.clj
  test/metabase/models/pulse_channel_test.clj
Labels: backport

#18268 Pull in translations for 0.41
  locales/bg.po
  locales/ca.po
  locales/cs.po
  locales/de.po
  locales/es.po
  locales/fa.po
  locales/fr.po
  locales/it.po
  locales/ja.po
  locales/metabase.pot
  locales/nb.po
  locales/nl.po
  locales/pl.po
  locales/pt-BR.po
  locales/ru.po
  locales/sk.po
  locales/sr.po
  locales/sv.po
  locales/tr.po
  locales/uk.po
  locales/vi.po
  locales/zh-HK.po
  locales/zh-TW.po
  locales/zh.po
Labels: backport

#18190 Erroring question page nits
  enterprise/backend/src/metabase_enterprise/audit_app/pages/common.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/common/cards.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/queries.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/query_detail.clj
  enterprise/backend/test/metabase_enterprise/audit_app/pages/common_test.clj
  enterprise/frontend/src/metabase-enterprise/audit_app/containers/AuditTableVisualization.jsx
  enterprise/frontend/src/metabase-enterprise/audit_app/containers/QuestionLoadAndDisplay.jsx
  enterprise/frontend/src/metabase-enterprise/tools/containers/ErrorDetail.jsx
  enterprise/frontend/src/metabase-enterprise/tools/containers/ErrorOverview.jsx
  enterprise/frontend/src/metabase-enterprise/tools/containers/ToolsApp.jsx
  frontend/src/metabase/css/core/overflow.css
  frontend/test/metabase/scenarios/admin/audit/ad-hoc.cy.spec.js
  frontend/test/metabase/scenarios/admin/tools/erroring-questions.cy.spec.js
Labels: backport

#18247 Cypress email setup
  frontend/test/__support__/e2e/cypress.js
  frontend/test/__support__/e2e/helpers/e2e-deprecated-helpers.js
  frontend/test/__support__/e2e/helpers/e2e-email-helpers.js
  frontend/test/metabase/scenarios/admin/people/people.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/email.cy.spec.js
  frontend/test/metabase/scenarios/permissions/sandboxes.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/17658.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/18009-nodata-creates-subscription-receives-error.cy.spec.js
  frontend/test/metabase/scenarios/sharing/subscriptions.cy.spec.js
Labels: .Tech Debt or Refactoring, .CI & Tests, backport

#18266 docs - updates to auditing, landing page, and more
  docs/README.md
  docs/administration-guide/04-managing-users.md
  docs/enterprise-guide/audit.md
  docs/troubleshooting-guide/index.md
  docs/users-guide/01-what-is-metabase.md
  docs/users-guide/07-dashboards.md
  docs/users-guide/collections.md
  docs/users-guide/start.md
Labels: .Documentation, backport

#18265 #18114 Repro: Dashboard Textbox does not render links unless using Markdown
  frontend/test/metabase/scenarios/dashboard/text-box.cy.spec.js
Labels: .CI & Tests, support/Repro

#18217 Fix whitelabel issues with color function
  frontend/src/metabase/admin/people/components/group-members/AddMemberRow.jsx
  frontend/src/metabase/components/ProgressBar.jsx
  frontend/src/metabase/components/UserAvatar.jsx
  frontend/src/metabase/containers/ItemPicker.jsx
  frontend/src/metabase/nav/components/SearchBar.styled.jsx
  frontend/src/metabase/nav/constants.js
  frontend/src/metabase/nav/containers/Navbar.jsx
  frontend/src/metabase/query_builder/components/notebook/NotebookStep.jsx
  frontend/src/metabase/query_builder/components/view/ViewButton.jsx
  frontend/src/metabase/query_builder/components/view/ViewFooter.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting.jsx
  frontend/src/metabase/visualizations/visualizations/Gauge.jsx
  frontend/src/metabase/visualizations/visualizations/PivotTable.jsx
  frontend/src/metabase/visualizations/visualizations/WaterfallChart.jsx
Labels: backport

#18279 Static viz: allow rendering non-timeseries line charts
  resources/frontend_shared/static_viz_interface.js
  src/metabase/pulse/render.clj
  src/metabase/pulse/render/body.clj
  src/metabase/pulse/render/js_svg.clj
  test/metabase/pulse/render_test.clj
Labels: backport

#18295 Fix CSP issue for Google Analytics
  src/metabase/server/middleware/security.clj
Labels: backport

#18712 Skip sending dashboard subscription if dashboard is archived
  src/metabase/models/pulse.clj
  src/metabase/pulse.clj
  test/metabase/api/pulse_test.clj
  test/metabase/dashboard_subscription_test.clj
Labels: backport
