Repository metabase/metabase, pull requests merged in 2021-05, with the labels that each got.

#15887 Merge EE Cypress tests with the OSS ones
  enterprise/frontend/test/metabase-enterprise/auth/sso.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/custom_drill_through/drill_through.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/scenarios/admin/databases/add.cy.spec.js
  frontend/test/__support__/assets/logo.jpeg
  frontend/test/__support__/cypress.js
  frontend/test/metabase/home/HomepageApp.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js
  frontend/test/metabase/scenarios/admin/permissions/sandboxes.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/whitelabel.cy.spec.js
  frontend/test/metabase/scenarios/audit/ad-hoc.cy.spec.js
  frontend/test/metabase/scenarios/audit/auditing.cy.spec.js
  frontend/test/metabase/scenarios/auth/sso.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/subscriptions.cy.spec.js
  frontend/test/metabase/scenarios/snippets/snippet-permissions.cy.spec.js
  frontend/test/metabase/scenarios/snippets/snippets.cy.spec.js
  package.json
Labels: .CI & Tests, .Tech Debt or Refactoring

#15900 Refine CI checksum calculation - extract e2e files
  .circleci/config.yml
  frontend/test/__support__/e2e/assets/logo.jpeg
  frontend/test/metabase-db/postgres/query.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/whitelabel.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#15917 Allow multiple `--spec` arguments
  frontend/test/__runner__/run_cypress_tests.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#15924 Split e2e CI groups
  .circleci/config.yml
  frontend/test/metabase/scenarios/admin/audit/ad-hoc.cy.spec.js
  frontend/test/metabase/scenarios/admin/audit/auditing.cy.spec.js
  frontend/test/metabase/scenarios/collections/permissions-baseline.cy.spec.js
  frontend/test/metabase/scenarios/native/data_ref.cy.spec.js
  frontend/test/metabase/scenarios/native/native.cy.spec.js
  frontend/test/metabase/scenarios/native/native_subquery.cy.spec.js
  frontend/test/metabase/scenarios/native/snippets/snippet-permissions.cy.spec.js
  frontend/test/metabase/scenarios/native/snippets/snippets.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/auth/signin.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/auth/sso.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/home/activity-page.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/home/overworld.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/home/search.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/reference/databases.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/reference/metrics.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/search.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/setup/setup.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/setup/user_settings.cy.spec.js
  frontend/test/metabase/scenarios/question/internal/question.cy.spec.js
  frontend/test/metabase/scenarios/sharing/alert/alert.cy.spec.js
  frontend/test/metabase/scenarios/sharing/alert/alert_auth.cy.spec.js
  frontend/test/metabase/scenarios/sharing/alert/email_alert.cy.spec.js
  frontend/test/metabase/scenarios/sharing/embed.cy.spec.js
  frontend/test/metabase/scenarios/sharing/public.cy.spec.js
  frontend/test/metabase/scenarios/sharing/pulse.cy.spec.js
  frontend/test/metabase/scenarios/sharing/subscriptions.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/trendline.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#15932 Merge split e2e ci groups from release branch (cherry-pick from `release-x.39.x`)
  .circleci/config.yml
  frontend/test/__runner__/run_cypress_tests.js
  frontend/test/metabase/scenarios/admin/audit/ad-hoc.cy.spec.js
  frontend/test/metabase/scenarios/admin/audit/auditing.cy.spec.js
  frontend/test/metabase/scenarios/collections/permissions-baseline.cy.spec.js
  frontend/test/metabase/scenarios/native/data_ref.cy.spec.js
  frontend/test/metabase/scenarios/native/native.cy.spec.js
  frontend/test/metabase/scenarios/native/native_subquery.cy.spec.js
  frontend/test/metabase/scenarios/native/snippets/snippet-permissions.cy.spec.js
  frontend/test/metabase/scenarios/native/snippets/snippets.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/auth/signin.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/auth/sso.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/home/activity-page.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/home/overworld.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/home/search.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/reference/databases.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/reference/metrics.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/search.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/setup/setup.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/setup/user_settings.cy.spec.js
  frontend/test/metabase/scenarios/question/internal/question.cy.spec.js
  frontend/test/metabase/scenarios/sharing/alert/alert.cy.spec.js
  frontend/test/metabase/scenarios/sharing/alert/alert_auth.cy.spec.js
  frontend/test/metabase/scenarios/sharing/alert/email_alert.cy.spec.js
  frontend/test/metabase/scenarios/sharing/embed.cy.spec.js
  frontend/test/metabase/scenarios/sharing/public.cy.spec.js
  frontend/test/metabase/scenarios/sharing/pulse.cy.spec.js
  frontend/test/metabase/scenarios/sharing/subscriptions.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/trendline.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#15936 #15891 Repro: Don't show Custom Expression helper when input is not in focus
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
Labels: .CI & Tests, support/Repro

#15934 #15893 Repro: Cannot use numeric value before an operator in Custom Expression
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#15938 #15922 Repro: `isNull` function in Custom Columns does not work
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
Labels: .CI & Tests, support/Repro

#15933 Cherry pick fix for `build-for-test` script from the `release-x.39.x` branch
  bin/build-for-test
Labels: .CI & Tests, .Tech Debt or Refactoring

#15968 #15946 Repro: Converting mongo question to native query doesn't pre-select table
  frontend/test/metabase-db/mongo/native.cy.spec.js
Labels: .CI & Tests, support/Repro

#15985 #15981 Repro: Feature flag causes problems with Text and Number filters in Native query
  frontend/test/metabase/scenarios/native/native.cy.spec.js
Labels: .CI & Tests, support/Repro

#15987 Repro #15980: Gauge visualization causes re-render on hover when there are no labels
  frontend/src/metabase/visualizations/visualizations/Gauge.jsx
  frontend/test/metabase/scenarios/visualizations/gauge.cy.spec.js
Labels: .CI & Tests, support/Repro

#16003 #15998 Repro: Tooltip only shows first Y-axis value when X-axis is numeric and style is Ordinal/Histogram
  frontend/test/metabase/scenarios/visualizations/line_chart.cy.spec.js
Labels: .CI & Tests, support/Repro

#16001 Use GitHub Actions to run front-end tests (#15507)
  .circleci/config.yml
  .github/workflows/frontend.yml
Labels: .CI & Tests, .Tech Debt or Refactoring

#16011 Cherry pick Cypress custom command `cy.button()`
  frontend/test/__support__/e2e/commands.js
  frontend/test/metabase-db/mongo/query.cy.spec.js
  frontend/test/metabase-db/postgres/custom-column.cy.spec.js
  frontend/test/metabase-db/postgres/native.cy.spec.js
  frontend/test/metabase-smoketest/admin.cy.spec.js
  frontend/test/metabase-smoketest/admin_setup.cy.spec.js
  frontend/test/metabase-smoketest/user.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js
  frontend/test/metabase/scenarios/admin/permissions/sandboxes.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
  frontend/test/metabase/scenarios/collections/personal-collections.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
  frontend/test/metabase/scenarios/native/native.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/setup/user_settings.cy.spec.js
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
  frontend/test/metabase/scenarios/question/joins.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/new.cy.spec.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
  frontend/test/metabase/scenarios/question/saved.cy.spec.js
  frontend/test/metabase/scenarios/sharing/alert/alert.cy.spec.js
  frontend/test/metabase/scenarios/sharing/subscriptions.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/trendline.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/waterfall.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16019 Cypress run: guard against unspecified specs (#15969)
  frontend/test/__runner__/run_cypress_tests.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16033 Add `cypress-real-events` library
  frontend/test/__support__/e2e/cypress.js
  package.json
  yarn.lock
Labels: .CI & Tests, .Tech Debt or Refactoring

#16036 Add `cypress-real-events` library to the devDependencies (#16033)
  package.json
  yarn.lock
Labels: .CI & Tests, .Tech Debt or Refactoring

#16040 #15959 Repro: Adding cards to dashboard via search can cause the card to show spinner until browser refresh
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, support/Repro

#16022 Fix Whitelabel favicon not working in all browsers
  frontend/test/metabase/scenarios/admin/settings/whitelabel.cy.spec.js
  resources/frontend_client/index_template.html
  src/metabase/public_settings.clj
Labels: .Frontend, Administration/Whitelabel

#16128 #16103 Repro: Filter dropdown sends request for values every time widget is opened
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, support/Repro

#16133 #16108 Repro: Missing tooltip for sharing individual question
  frontend/test/metabase/scenarios/question/new.cy.spec.js
Labels: .CI & Tests, support/Repro

#16135 #16122 Repro: Normal login errors are not surfaced if SSO is also active
  frontend/test/metabase/scenarios/onboarding/auth/sso.cy.spec.js
Labels: .CI & Tests, support/Repro

#16142 #15974 / #11659 Repro: Google sign-in client ID setting fails to save on subsequent tries
  frontend/test/metabase/scenarios/admin/settings/sso.cy.spec.js
Labels: .CI & Tests, support/Repro

#16146 #15558 Repro: Login History tab not available for LDAP/Google logins
  frontend/test/__support__/e2e/cypress.js
  frontend/test/metabase/scenarios/onboarding/auth/sso.cy.spec.js
Labels: .CI & Tests, support/Repro

#16149 #15211 Repro: Pivot table don't show stand-alone values on the upper level grouping
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
Labels: .CI & Tests, support/Repro

#16192 Fix #16188 (React unsupported style property warning in `NewQueryOption`)
  frontend/src/metabase/new_query/components/NewQueryOption.jsx
Labels: .Tech Debt or Refactoring

#16204 #13313 Repro: It shouldn't be possible to save invalid (non-numeric) LDAP port
  frontend/test/metabase/scenarios/admin/settings/sso.cy.spec.js
Labels: .CI & Tests, support/Repro

#16209 #16198 Repro: Specific combination of filters can cause frontend reload or blank screen
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#16228 #16212 Repro: Questions used in SQL query aren't linked correctly from variables sidebar
  frontend/test/metabase/scenarios/native/native.cy.spec.js
Labels: .CI & Tests, support/Repro

#16205 #16173 Repro: LDAP setting should hit the correct endpoint
  frontend/test/metabase/scenarios/admin/settings/sso.cy.spec.js
Labels: .CI & Tests, support/Repro

#16215 Restore Custom Expression suggestion highlights
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions.jsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions.styled.jsx
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#16252 #16229 Repro: Drag functionality not working in dashboard visualization options modal
  frontend/src/metabase/visualizations/components/ChartSettings.jsx
  frontend/test/metabase/scenarios/dashboard/visualizaiton-options.cy.spec.js
Labels: .CI & Tests, support/Repro

#16263 #16249 Repro: Tooltip of combined dashboard cards does not show the correct column title
  frontend/test/metabase/scenarios/visualizations/line_chart.cy.spec.js
Labels: .CI & Tests, support/Repro

#16265 #16246 Repro: Incorrect values on data points for waterfall charts when one of the values is 0
  frontend/test/metabase/scenarios/visualizations/waterfall.cy.spec.js
Labels: .CI & Tests, support/Repro

#16280 #16273 Repro: Relative date filter applied to the custom column doesn't work
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
Labels: .CI & Tests, support/Repro

#16292 Revamp Cypress custom commands
  frontend/test/__support__/e2e/commands.js
  frontend/test/__support__/e2e/commands/api/dashboard.js
  frontend/test/__support__/e2e/commands/api/question.js
  frontend/test/__support__/e2e/commands/database/addH2SampleDataset.js
  frontend/test/__support__/e2e/commands/overwrites/log.js
  frontend/test/__support__/e2e/commands/permissions/sandboxTable.js
  frontend/test/__support__/e2e/commands/permissions/updatePermissions.js
  frontend/test/__support__/e2e/commands/ui/button.js
  frontend/test/__support__/e2e/commands/ui/icon.js
  frontend/test/__support__/e2e/commands/user/authentication.js
  frontend/test/__support__/e2e/commands/user/createUser.js
  frontend/test/__support__/e2e/commands/visibility/isRenderedWithinViewport.js
  frontend/test/__support__/e2e/commands/visibility/isVisibleInPopover.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16297 Unskip repro for #15119
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring
