Repository metabase/metabase, pull requests merged in 2021-03, with the labels that each got.

#14986 Add Cypress custom log command
  enterprise/frontend/test/metabase-enterprise/audit/ad-hoc.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/audit/auditing.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/formatting/whitelabel.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
  frontend/test/__support__/commands.js
  frontend/test/__support__/cypress.js
  frontend/test/metabase-db/mongo/query.cy.spec.js
  frontend/test/metabase-db/mysql/custom-column.cy.spec.js
  frontend/test/metabase-db/postgres/custom-column.cy.spec.js
  frontend/test/metabase-db/postgres/query.cy.spec.js
  frontend/test/metabase-db/postgres/sandboxes.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/edit.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/metadata.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/metrics.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/segments.cy.spec.js
  frontend/test/metabase/scenarios/admin/people/people.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/localization.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/parameters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/subscriptions.cy.spec.js
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
  frontend/test/metabase/scenarios/question/native.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/new.cy.spec.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
  frontend/test/metabase/scenarios/question/nulls.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/maps.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#15011 #14989 Repro: Pivot Table does not work for users without data permissions
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
Labels: .CI & Tests, support/Repro

#15021 Set `react` to the version `~16.14.0`
  package.json
  yarn.lock
Labels: .Tech Debt or Refactoring

#15004 Add Cypress custom command for creating the dashboard
  enterprise/frontend/test/metabase-enterprise/audit/auditing.cy.spec.js
  frontend/test/__support__/commands.js
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/chained-filters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/parameters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/permissions.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/subscriptions.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/text-box.cy.spec.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/nulls.cy.spec.js
  frontend/test/metabase/scenarios/question/view.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
  frontend/test/snapshot-creators/default.cy.snap.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#15005 Add Cypress custom command for creating the question
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
  frontend/test/__support__/commands.js
  frontend/test/metabase-db/mysql/custom-column.cy.spec.js
  frontend/test/metabase-db/postgres/sandboxes.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/metadata.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/localization.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/x-rays.cy.spec.js
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/new.cy.spec.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
  frontend/test/metabase/scenarios/question/nulls.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
  frontend/test/snapshot-creators/default.cy.snap.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#15035 #14990 Repro: Dashboard Subscription sidebar broken for Sandboxed users
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, support/Repro

#15037 Delete unused `metadata.js` file
  frontend/test/__support__/metadata.js
Labels: .Tech Debt or Refactoring

#15007 Add Cypress custom command for creating native questions
  enterprise/frontend/test/metabase-enterprise/audit/auditing.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
  frontend/test/__support__/commands.js
  frontend/test/metabase/scenarios/admin/settings/localization.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/chained-filters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/nested-cards.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/permissions.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/title-drill.cy.spec.js
  frontend/test/metabase/scenarios/public/public.cy.spec.js
  frontend/test/metabase/scenarios/question/downloads.cy.spec.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
  frontend/test/metabase/scenarios/question/native.cy.spec.js
  frontend/test/metabase/scenarios/question/native_subquery.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/nulls.cy.spec.js
  frontend/test/metabase/scenarios/question/view.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/maps.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/rows.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#15038 Add Cypress custom command for sandboxing tables
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
  frontend/test/__support__/commands.js
  frontend/test/metabase-db/postgres/sandboxes.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#15056 #14844 Repro: Sandboxed users cannot send Pulses to Slack
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, support/Repro

#15087 Unskip repro for #14294
  frontend/test/metabase/scenarios/admin/settings/localization.cy.spec.js
Labels: .CI & Tests

#15096 #15077 Repro: Dashboard sharing is not possible for dashboards with text cards only
  frontend/test/metabase/scenarios/dashboard/subscriptions.cy.spec.js
Labels: .CI & Tests, support/Repro

#15110 Fix `react/jsx-no-target-blank` error
  frontend/src/metabase/admin/datamodel/components/PartialQueryBuilder.jsx
  frontend/src/metabase/admin/settings/components/SettingsSingleSignOnForm.jsx
  frontend/src/metabase/admin/settings/components/SettingsSlackForm.jsx
  frontend/src/metabase/admin/settings/components/SettingsUpdatesForm.jsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingLegalese.jsx
  frontend/src/metabase/components/ExternalLink.jsx
  frontend/src/metabase/public/components/LogoBadge.jsx
  frontend/src/metabase/query_builder/components/template_tags/TagEditorHelp.jsx
Labels: .Frontend, .Tech Debt or Refactoring

#15111 Fix `react/no-unescaped-entities` error
  frontend/src/metabase/admin/datamodel/components/revisions/Revision.jsx
  frontend/src/metabase/admin/datamodel/components/revisions/RevisionHistory.jsx
  frontend/src/metabase/admin/datamodel/components/revisions/TextDiff.jsx
  frontend/src/metabase/admin/settings/components/SettingsSlackForm.jsx
  frontend/src/metabase/internal/pages/TypePage.jsx
  frontend/src/metabase/internal/pages/WelcomePage.jsx
Labels: .Frontend, .Tech Debt or Refactoring

#15122 Fix `react/no-children-prop` error
  frontend/src/metabase/components/Tooltip.jsx
  frontend/src/metabase/components/Triggerable.jsx
  frontend/src/metabase/containers/CollectionItemsLoader.jsx
  frontend/src/metabase/containers/QuestionLoader.jsx
  frontend/src/metabase/entities/containers/EntityListLoader.jsx
  frontend/src/metabase/entities/containers/EntityObjectLoader.jsx
  frontend/src/metabase/hoc/RenderPropToHOC.jsx
  frontend/src/metabase/query_builder/components/FilterList.jsx
  frontend/src/metabase/setup/containers/PostSetupApp.jsx
  frontend/test/metabase/containers/AdHocQuestionLoader.unit.spec.js
  frontend/test/metabase/containers/SavedQuestionLoader.unit.spec.js
Labels: .Frontend, .Tech Debt or Refactoring

#15135 Fix sandboxes test flake (in repro #14612)
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#15139 #15105 Repro: When Sandbox is granted to linked table column, but no access to the linked table, then "dirty" queries fail
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, support/Repro

#15158 #15152 Repro: Waterfall chart should not be enabled for question with more than 1 series
  frontend/test/metabase/scenarios/visualizations/waterfall.cy.spec.js
Labels: .CI & Tests, support/Repro

#15141 #15106 Repro: "Dirty" query fails when sandboxing on linked table column with multiple dimensions and remapping
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
Labels: .CI & Tests, support/Repro

#15138 #15119 Repro: User without data access should be able to use dashboard filters
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, support/Repro

#15162 Fix wording in 05-permissions doc
  docs/administration-guide/05-setting-permissions.md
Labels: .Documentation

#15177 #13347 Repro: Cannot select "Saved Questions", which belongs to database user doesn't have Data-permissions for
  frontend/test/metabase-db/postgres/permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#15169 #15163 Repro: Cannot view SQL question when accessing via dashboard with filters connected to modified card without SQL permissions
  frontend/test/metabase/scenarios/question/native.cy.spec.js
Labels: .CI & Tests, support/Repro

#15180 #15170 Repro: Cross-Filtering doesn't work for all field types
  frontend/test/metabase/scenarios/dashboard/chained-filters.cy.spec.js
Labels: .CI & Tests, support/Repro

#15198 #15080 Repro: Archived items not shown in archive
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#15200 Add `cypress-skip-test` library
  frontend/test/__support__/cypress.js
  package.json
  yarn.lock
Labels: .CI & Tests

#15236 Expand user roles for testing
  enterprise/frontend/test/metabase-enterprise/audit/auditing.cy.spec.js
  enterprise/frontend/test/metabase-enterprise/sandboxes/sandboxes.cy.spec.js
  frontend/test/__support__/cypress_data.js
  frontend/test/metabase-db/postgres/sandboxes.cy.spec.js
  frontend/test/metabase/scenarios/admin/people/people.cy.spec.js
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
  frontend/test/snapshot-creators/default.cy.snap.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#15213 Look at effective-type in the UI
  frontend/src/metabase-types/types/Field.js
  frontend/src/metabase/lib/schema_metadata.js
Labels: .Frontend

#15218 Fix typo in semantic migration
  resources/migrations/000_migrations.yaml
  test/metabase/db/schema_migrations_test.clj
Labels: Administration/Metadata & Sync, Operation/Database Migrations

#15238 #15237 Repro: User with sufficient permissions can't revert the dashboard
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#15202 #13229 Repro: User without permissions can see "Revert" buttons
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#15257 #15256 Repro: "Duplicate" dashboard modal says it "failed", when it actually did duplicate successfully
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#15262 #11719 Repro: Users with curate access can't edit question's metadata
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#15263 #15253 Repro: User with curate access can't unarchive question
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#15266 #15255 Repro: It's not possible to duplicate question from the collection root
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#15258 docs - fix hash links
  docs/operations-guide/advanced-topics-for-running-Metabase-in-AWS-ElasticBeanstalk.md
  docs/operations-guide/upgrading-metabase.md
Labels: .Documentation

#15282 #15281 Repro: Users with read permissions are offered to save new dashboard in collections they only have read access to
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#15299 #15289 Repro: Abandoning archive collection process should let you stay in the same collection
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#15301 #12489 Repro: Users can edit archived collections
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#15303 Expand "pin collection items" test
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#15290 docs - consolidated db lists [closes #14996]
  README.md
  docs/administration-guide/01-managing-databases.md
  docs/faq/setup/which-databases-does-metabase-support.md
Labels: .Documentation

#15305 Test question revert mechanism for users with curate permissions
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: .CI & Tests

#15308 Consolidate collection permissions tests
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#15321 #6884 Repro: Reverting the dashboard messes up the UI
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#15322 #1926 Repro: We shouldn't print revision history steps without description/diff
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#15344 Personal collections testing (with repro for #15343)
  frontend/test/metabase/scenarios/collections/personal-collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#15345 #8406 Repro: It shouldn't be possible to change permission levels on sub-collections inside personal collection
  frontend/test/metabase/scenarios/collections/personal-collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#15346 #15339 Repro: Admin can't see other users' personal sub-collections
  frontend/test/metabase/scenarios/collections/personal-collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#15348 #15338 Repro: Not possible to select pinned collection item using checkbox
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#15371 #15368 Repro: Click behavior leading to the dashboard without permissions causes a permission error
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, support/Repro

#15293 Check to see if `done` button is enabled whenever custom expr changes
  frontend/src/metabase/query_builder/components/ExpressionPopover.jsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield.jsx
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: Querying/Notebook

#15375 #15352 Repro: Different time filter query used in saved and nested question
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
Labels: .CI & Tests, support/Repro

#15378 #15333 Repro: Column filters not working for metrics
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#15380 #15331 Repro: Drill-through on PK/FK to the "object detail" when filtered by explicit joined column fails
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
Labels: .CI & Tests, support/Repro

#15381 #15324 Repro: Count of rows from drill-down on binned results doesn't match the number of records
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
Labels: .CI & Tests, support/Repro

#15384 #14145 Repro: Field id doesn't update when database source is changed
  frontend/test/metabase/scenarios/question/native.cy.spec.js
Labels: .CI & Tests, support/Repro

#15396 #15316 Repro: Custom Expression name containing brackets ([ or ]) can break the UI
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
Labels: .CI & Tests, support/Repro

#15398 #15279 Repro: Dashboard filters not working if one of them is corrupted
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, support/Repro

#15399 #15250 Repro: Click Behavior not parsing measure value for first row on Pie chart
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
Labels: .CI & Tests, support/Repro

#15406 #15397 Repro: Using aggregation functions on top of saved SQL question errors out
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
Labels: .CI & Tests, support/Repro

#15405 fix missing total on pie charts after the initial render
  frontend/src/metabase/visualizations/visualizations/PieChart.jsx
  frontend/test/metabase/scenarios/visualizations/pie_chart.cy.spec.js
Labels: support/Repro

#15421 docs - add duplicate question section
  docs/users-guide/04-asking-questions.md
  docs/users-guide/images/notebook/duplicate-question.png
  docs/users-guide/images/notebook/started-from-saved-question.png
Labels: .Documentation

#15419 docs - update search for 39
  docs/users-guide/01-what-is-metabase.md
  docs/users-guide/06-sharing-answers.md
  docs/users-guide/images/sharing-answers/search-results.gif
  docs/users-guide/images/sharing-answers/search-results.png
Labels: .Documentation
