Repository metabase/metabase, pull requests merged in 2021-11, with the labels that each got.

#18746 Abstract e2e downloads helpers
  frontend/test/__support__/e2e/cypress.js
  frontend/test/__support__/e2e/helpers/e2e-downloads-helpers.js
  frontend/test/metabase/scenarios/downloads/downloads.cy.spec.js
  frontend/test/metabase/scenarios/downloads/reproductions/10803-timestamp-formatting.cy.spec.js
  frontend/test/metabase/scenarios/downloads/reproductions/18219-temporal-units-not-formatted.cy.spec.js
  frontend/test/metabase/scenarios/downloads/reproductions/18382-old-syntax-missing-renamed-columns.cy.spec.js
  frontend/test/metabase/scenarios/downloads/reproductions/18440-remapped-display-value-dropped.cy.spec.js
Labels: .Tech Debt or Refactoring, .CI & Tests, backport

#18768 wrap moderation plugins in feature flag
  enterprise/frontend/src/metabase-enterprise/moderation/index.js
Labels: backport

#18792 #18729 Repro: XLSX export of "X of Y" (eg. Month of Year) is formatted as date column
  frontend/test/metabase/scenarios/downloads/reproductions/18729-date-formatting-x-of-y.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#18793 #18573 Repro: Remapped columns do not use renamed titles in exports
  frontend/test/metabase/scenarios/downloads/reproductions/18573-remapped-fields-not-renamed.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#18806 Fix markdown image link click area
  frontend/src/metabase/visualizations/visualizations/Text.css
Labels: backport

#18798 Add index to query_execution.card_id
  resources/migrations/000_migrations.yaml
Labels: backport

#18800 Do not bin numerical fields on join condition
  frontend/src/metabase-lib/lib/queries/structured/Join.js
  frontend/src/metabase/query_builder/components/DimensionList.jsx
  frontend/src/metabase/query_builder/components/FieldList.jsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx
  frontend/test/metabase/scenarios/question/reproductions/18589-numeric-binning-in-joins.cy.spec.js
Labels: backport

#18799 Add index to ModerationReview moderated_item_type + moderated_item_id
  bin/lint-migrations-file/README.md
  bin/lint-migrations-file/src/change/strict.clj
  resources/migrations/000_migrations.yaml
Labels: backport

#18836 docs - custom expressions
  docs/users-guide/expressions-list.md
  docs/users-guide/expressions.md
  docs/users-guide/start.md
Labels: .Documentation, backport

#18846 docs - compatibility ntoes
  docs/operations-guide/java-versions.md
  docs/users-guide/05-visualizing-results.md
Labels: .Documentation, backport

#18845 Fix notebook editor crash when joining on a custom column
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx
  frontend/test/metabase/scenarios/question/reproductions/18818-crash-when-joining-on-custom-column.cy.spec.js
Labels: backport

#18772 Don't qualify breakout field name for BigQuery when source is not from a table
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj
  src/metabase/driver/sql/query_processor.clj
Labels: backport

#18863 fix permissions page race condition
  frontend/src/metabase/admin/permissions/pages/DataPermissionsPage/DataPermissionsPage.jsx
Labels: backport

#18684 Add `instance-creation` setting for inclusion in Snowplow analytics
  src/metabase/public_settings.clj
  src/metabase/util/stats.clj
  test/metabase/public_settings_test.clj
  test/metabase/util/stats_test.clj
Labels: backport

#18858 Fix query->preprocessed when the query has cached results
  enterprise/backend/test/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions_test.clj
  src/metabase/query_processor.clj
  src/metabase/query_processor/middleware/cache_backend/db.clj
  test/metabase/query_processor_test.clj
Labels: backport

#18892 docs - remove outdated kubernetes page
  docs/operations-guide/installing-metabase.md
  docs/operations-guide/running-metabase-on-kubernetes.md
Labels: .Documentation, backport

#18896 Catch all exceptions when parsing strings as datetime values in XLSX exports
  src/metabase/query_processor/streaming/xlsx.clj
  test/metabase/query_processor/streaming/xlsx_test.clj
Labels: backport

#17693 Editing Google Analytics documentation
  docs/administration-guide/01-managing-databases.md
  docs/administration-guide/databases/google-analytics.md
  docs/administration-guide/images/google_analytics_add_database.png
Labels: .Documentation

#18843 Update new BigQuery driver to only use project-id in qualified names if it differs from credentials
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/common.clj
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj
Labels: backport

#18937 docs - update link
  docs/administration-guide/databases/google-analytics.md
Labels: .Documentation, backport

#18790 Fix clicking on a legend item in the query builder on unsaved question
  frontend/src/metabase/query_builder/actions.js
  frontend/test/metabase/scenarios/native/reproductions/12439-click-on-legend-breaks-ui.cy.spec.js
Labels: backport

#18934 docs - update sql parameter page
  docs/users-guide/13-sql-parameters.md
  docs/users-guide/images/sql-parameters/01-variables.png
  docs/users-guide/images/sql-parameters/02-widget.png
  docs/users-guide/images/sql-parameters/state-field-filter.png
Labels: .Documentation, backport

#18920 pass 'noEvent' api option to prevent unauthed event
  frontend/src/metabase/lib/entities.js
  frontend/src/metabase/visualizations/hoc/WithVizSettingsData.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: backport

#18965 Fix sending a test subscription with non-default parameters
  frontend/src/metabase/components/SendTestPulse.jsx
  frontend/src/metabase/lib/pulse.js
  frontend/src/metabase/sharing/components/AddEditSidebar.jsx
  frontend/src/metabase/sharing/components/SharingSidebar.jsx
  frontend/test/metabase/scenarios/sharing/reproductions/18669-test-email-with-parameters.cy.spec.js
Labels: backport

#19018 Docs – jar install page and getCallerClass error
  docs/operations-guide/running-the-metabase-jar-file.md
  docs/troubleshooting-guide/running.md
Labels: Type:Documentation, backport

#19030 fix funnels with zero initial step
  frontend/src/metabase/visualizations/components/FunnelNormal.jsx
  frontend/test/metabase-visual/visualizations/funnel.cy.spec.js
Labels: backport

#19072 docs - update links
  docs/administration-guide/01-managing-databases.md
  docs/users-guide/13-sql-parameters.md
Labels: backport

#19065 Add index on QueryExecution card_id + started_at
  bin/lint-migrations-file/src/change_set/common.clj
  bin/lint-migrations-file/test/lint_migrations_file_test.clj
  resources/migrations/000_migrations.yaml
Labels: backport

#19059 Harmonize Google dependency versions
  modules/drivers/bigquery/deps.edn
  modules/drivers/googleanalytics/deps.edn
Labels: backport

#19036 Validate suffix & strip whitespace from Google auth client id
  frontend/test/metabase/scenarios/admin/settings/sso/google.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/auth/sso.cy.spec.js
  src/metabase/integrations/google.clj
  test/metabase/api/session_test.clj
  test/metabase/api/user_test.clj
  test/metabase/integrations/google_test.clj
Labels: backport

#19089 Remove data types section and minor reorganization
  docs/users-guide/02-database-basics.md
Labels: Type:Documentation, backport

#19109 show trend previous value in full-screen mode
  frontend/src/metabase/visualizations/visualizations/SmartScalar.jsx
Labels: backport

#19116 Fix pivot tables with missing pivot columns
  frontend/src/metabase/visualizations/visualizations/Table.jsx
  frontend/test/metabase/scenarios/visualizations/reproductions/18976-pivot-table-columns.cy.spec.js
Labels: backport

#19066 Limit autocomplete results for tables and fields
  src/metabase/api/database.clj
  test/metabase/api/database_test.clj
Labels: backport

#19125 docs - remove errant redirect
  docs/troubleshooting-guide/loading-from-h2.md
Labels: Type:Documentation, backport

#19126 docs - new field types page; delete database basics
  docs/administration-guide/03-metadata-editing.md
  docs/users-guide/01-what-is-metabase.md
  docs/users-guide/02-database-basics.md
  docs/users-guide/field-types.md
  docs/users-guide/start.md
Labels: Type:Documentation, backport
