Repository metabase/metabase, pull requests merged in 2021-06, with the labels that each got.

#16294 Create composite Cypress custom command `cy.createQuestionAndDashboard`
  frontend/test/__support__/e2e/commands.js
  frontend/test/__support__/e2e/commands/api/composite/createQuestionAndDashboard.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/gauge.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16231 #12629 Repro: Human-readable number formatting not working properly
  frontend/test/metabase/scenarios/visualizations/scalar.cy.spec.js
Labels: .CI & Tests, support/Repro

#16306 Fix `nosql` user's email address
  frontend/test/__support__/e2e/cypress_data.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16321 Remove unit snapshots
  frontend/src/metabase/components/AccordionList.info.js
  frontend/src/metabase/components/Breadcrumbs.info.js
  frontend/src/metabase/components/Calendar.info.js
  frontend/src/metabase/components/Tooltip.info.js
  frontend/src/metabase/components/Visualization.info.js
  frontend/test/metabase/components/Calendar.unit.spec.js
  frontend/test/metabase/components/__snapshots__/Calendar.unit.spec.js.snap
  frontend/test/metabase/dashboard/DashCard.unit.spec.js
  frontend/test/metabase/dashboard/__snapshots__/DashCard.unit.spec.js.snap
  frontend/test/metabase/internal/__snapshots__/components.unit.spec.js.snap
  frontend/test/metabase/internal/components.unit.spec.js
  package.json
  yarn.lock
Labels: .Tech Debt or Refactoring

#16345 Filter nulls out of histograms
  frontend/src/metabase/visualizations/lib/renderer_utils.js
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/test/metabase/scenarios/visualizations/bar_chart.cy.spec.js
Labels: support/Repro

#16355 #16350 Repro: "Invite someone" button overlaps activate/deactivate radio buttons on small screen widths
  frontend/test/metabase/scenarios/admin/people/people.cy.spec.js
Labels: .CI & Tests, support/Repro

#16342 #15993 Repro: Click behavior with filter pass-thru does not show filters defined on question
  frontend/test/metabase/scenarios/dashboard/click-behavior.cy.spec.js
Labels: .CI & Tests, support/Repro

#16343 #16334 Repro: Click Behavior targeting a question with filter mapped causes the visualization type to change
  frontend/test/metabase/scenarios/dashboard/click-behavior.cy.spec.js
Labels: .CI & Tests, support/Repro

#16359 #16327 Repro: Double binning menu for date fields when using Saved Question (Native)
  frontend/test/metabase/scenarios/native/native.cy.spec.js
Labels: .CI & Tests, support/Repro

#16361 #16322 Repro: "Custom mapping" is only available, when "A list of all values" is set (and after a browser refresh)
  frontend/test/metabase/scenarios/admin/datamodel/metadata.cy.spec.js
Labels: .CI & Tests, .Reproduced

#16367 docs - fix hash link
  docs/administration-guide/databases/mongodb.md
Labels: .Documentation

#16364 #16226 Repro: LDAP/Email settings gets cleared if validation fails
  frontend/test/metabase/scenarios/admin/settings/email.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/sso.cy.spec.js
Labels: .CI & Tests, support/Repro

#16384 #16378 Repro: Cannot enable JWT authentication
  frontend/test/metabase/scenarios/admin/settings/sso.cy.spec.js
Labels: .CI & Tests, support/Repro

#16426 #12128 Repro: Can't change label on empty row value
  frontend/test/metabase/scenarios/visualizations/line_chart.cy.spec.js
Labels: .CI & Tests, support/Repro

#16390 Unskip merged repros
  frontend/test/metabase/scenarios/question/custom_column.cy.spec.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16501 Fix can't "Select All" collection items if all items are pinned
  frontend/src/metabase/collections/containers/CollectionContent.jsx
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#16500 Fix bulk archive broken
  frontend/src/metabase/collections/containers/CollectionContent.jsx
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#16514 Fix can't archive a question from the Question page
  frontend/src/metabase/query_builder/containers/ArchiveQuestionModal.jsx
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#16503 #16181 Repro: Dashboard Contains filter doesn't apply when clicking on Question title
  frontend/test/metabase/scenarios/dashboard/title-drill.cy.spec.js
Labels: .CI & Tests, support/Repro

#16513 Repro for missing value labels on combo charts
  frontend/test/metabase/scenarios/visualizations/combo.cy.spec.js
Labels: .CI & Tests, support/Repro

#16525 #16498 Repro: Should be possible to drag items to the root collection
  frontend/test/metabase/scenarios/collections/drag-and-drop.cy.spec.js
Labels: .CI & Tests, support/Repro

#16535 Unskip repro for #13751
  frontend/test/metabase-db/postgres/custom-column.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16537 Fix and unskip repro for #8333
  frontend/test/metabase/scenarios/dashboard/text-box.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16551 Unskip repro for #15695
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16552 Replace real TLDs with `.test` in frontend tests
  frontend/test/__support__/e2e/cypress_data.js
  frontend/test/metabase-smoketest/admin.cy.spec.js
  frontend/test/metabase-smoketest/admin_setup.cy.spec.js
  frontend/test/metabase/lib/formatting.unit.spec.js
  frontend/test/metabase/scenarios/admin/people/people.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/email.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/whitelabel.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/setup/setup.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/setup/user_settings.cy.spec.js
  frontend/test/metabase/visualizations/components/LineAreaBarChart.unit.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16495 #16386 Repro: Filtering on `boolean=true` column causes blank screen or "Something went wrong"
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
Labels: .CI & Tests, support/Repro

#16575 Merge `release-x.39.x` including ae6e9d9
  enterprise/backend/test/metabase_enterprise/serialization/load_test.clj
  frontend/src/metabase/admin/settings/components/SettingsBatchForm.jsx
  frontend/src/metabase/components/AccordionList.info.js
  frontend/src/metabase/components/Breadcrumbs.info.js
  frontend/src/metabase/components/Calendar.info.js
  frontend/src/metabase/components/Tooltip.info.js
  frontend/src/metabase/components/Visualization.info.js
  frontend/src/metabase/visualizations/components/ChartSettings.jsx
  frontend/src/metabase/visualizations/lib/chart_values.js
  frontend/src/metabase/visualizations/lib/renderer_utils.js
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/test/__support__/e2e/commands.js
  frontend/test/__support__/e2e/commands/api/composite/createQuestionAndDashboard.js
  frontend/test/__support__/e2e/commands/api/dashboard.js
  frontend/test/__support__/e2e/commands/api/question.js
  frontend/test/__support__/e2e/commands/database/addH2SampleDataset.js
  frontend/test/__support__/e2e/commands/overwrites/log.js
  frontend/test/__support__/e2e/commands/permissions/sandboxTable.js
  frontend/test/__support__/e2e/commands/permissions/updatePermissions.js
  frontend/test/__support__/e2e/commands/ui/button.js
  frontend/test/__support__/e2e/commands/ui/icon.js
  frontend/test/__support__/e2e/commands/user/authentication.js
  frontend/test/__support__/e2e/commands/user/createUser.js
  frontend/test/__support__/e2e/commands/visibility/isRenderedWithinViewport.js
  frontend/test/__support__/e2e/commands/visibility/isVisibleInPopover.js
  frontend/test/__support__/e2e/cypress_data.js
  frontend/test/metabase/components/Calendar.unit.spec.js
  frontend/test/metabase/components/__snapshots__/Calendar.unit.spec.js.snap
  frontend/test/metabase/dashboard/DashCard.unit.spec.js
  frontend/test/metabase/dashboard/__snapshots__/DashCard.unit.spec.js.snap
  frontend/test/metabase/internal/__snapshots__/components.unit.spec.js.snap
  frontend/test/metabase/internal/components.unit.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/metadata.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/email.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/sso.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/click-behavior.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
  frontend/test/metabase/scenarios/native/native.cy.spec.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
  frontend/test/metabase/scenarios/question/settings.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/bar_chart.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/gauge.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/line_chart.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/scalar.cy.spec.js
  modules/drivers/oracle/test/metabase/driver/oracle_test.clj
  package.json
  src/metabase/driver/sql/query_processor.clj
  test/metabase/driver/sql/query_processor_test.clj
  test/metabase/query_processor_test/explicit_joins_test.clj
  yarn.lock
Labels: .Tech Debt or Refactoring

#16585 Repros for #12782 and #4995: Problems with the labels when showing only one row in the results
  frontend/test/metabase/scenarios/visualizations/line_chart.cy.spec.js
Labels: .CI & Tests, support/Repro

#16592 Refactor and unskip the repro for #15279
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16620 Fix broken smoke test
  frontend/test/metabase-smoketest/admin_setup.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16623 Fix flake in repro for #14114
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16624 #16555 Repro: Collections appear in items list for user with revoked access to collections
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#16622 [Binning e2e coverage] Binning options
  .circleci/config.yml
  frontend/test/metabase/scenarios/binning/binning-options.cy.spec.js
Labels: .CI & Tests

#16618 Add repro for #16617: archive page shows error for users with collection curate permissions and no data permissions
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#16608 Fix drilldown on multi-series chart
  frontend/src/metabase/visualizations/components/Visualization.jsx
  frontend/src/metabase/visualizations/lib/apply_tooltips.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
Labels: .CI & Tests, support/Repro

#16627 #11503 Repros: Filters from dashboard not used in question
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
Labels: .CI & Tests, support/Repro

#16629 [Binning e2e coverage] Group existing binning repros together
  frontend/test/metabase/scenarios/binning/binning-reproductions.cy.spec.js
  frontend/test/metabase/scenarios/native/native.cy.spec.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16633 #16379 Repro: Selecting bin count on intermediate data question fails
  frontend/test/metabase/scenarios/binning/binning-reproductions.cy.spec.js
Labels: .CI & Tests, support/Repro

#16660 [Binning e2e coverage] Asserting on the saved SQL question
  frontend/test/metabase/scenarios/binning/sql.cy.spec.js
Labels: .CI & Tests

#16662 [Binning e2e coverage] Asserting on the bins from the saved QB question using implicit joins
  frontend/test/metabase/scenarios/binning/qb-implicit-joins.cy.spec.js
Labels: .CI & Tests

#16661 [Binning e2e coverage] Asserting on the saved QB question with explicit joins
  frontend/test/metabase/scenarios/binning/qb-explicit-joins.cy.spec.js
Labels: .CI & Tests

#16698 #16674 Repro: UI inconsistencies for bucket display on tables from implicitly joined tables
  frontend/test/metabase/scenarios/binning/binning-options.cy.spec.js
Labels: .CI & Tests, support/Repro

#16703 #16675 Repro: UI inconsistencies for bucket display on tables from explicitly joined tables
  frontend/test/metabase/scenarios/binning/binning-options.cy.spec.js
Labels: .CI & Tests, support/Repro

#16705 #16693 Repro: Binning from a column popover (distribution) on explicitly joined field renders incorrect title
  frontend/test/metabase/scenarios/binning/qb-explicit-joins.cy.spec.js
Labels: .CI & Tests, support/Repro

#16696 docs - 0.40
  docs/administration-guide/04-managing-users.md
  docs/administration-guide/05-setting-permissions.md
  docs/administration-guide/06-collections.md
  docs/administration-guide/images/AdminBar.png
  docs/administration-guide/images/ProfileDropdown.png
  docs/administration-guide/images/RemoveUser.png
  docs/enterprise-guide/audit.md
  docs/users-guide/05-visualizing-results.md
  docs/users-guide/07-dashboards.md
  docs/users-guide/images/dashboards/FirstDashboard.png
  docs/users-guide/images/sharing-answers/question-checkbox.png
Labels: .Documentation

#16664 Fix "Zoom in" and "View these X" drilldown actions for charts based on custom columns
  frontend/src/metabase/modes/components/drill/AutomaticDashboardDrill.jsx
  frontend/src/metabase/modes/components/drill/CompareToRestDrill.js
  frontend/src/metabase/modes/lib/drilldown.js
  frontend/src/metabase/visualizations/components/ChartClickActions.jsx
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
Labels: .CI & Tests, support/Repro

#16643 [Binning e2e coverage] Time Series Correctness
  frontend/test/metabase/scenarios/binning/correctness/time-series.cy.spec.js
Labels: .CI & Tests

#16630 [Binning e2e coverage] Longitude Correctness
  frontend/test/metabase/scenarios/binning/correctness/longitude.cy.spec.js
Labels: .CI & Tests

#16712 [Binning e2e coverage] Asserting on the bins from the regular QB table
  frontend/test/metabase/scenarios/binning/qb-regular-table.cy.spec.js
Labels: .CI & Tests

#16735 #16670 Repro: Auto-binning on number field is different for SQL than it is for QB
  frontend/test/metabase/scenarios/binning/binning-reproductions.cy.spec.js
Labels: .CI & Tests, support/Repro

#16737 #16671 Repro: Auto-binning on time series field is different for SQL than it is for QB
  frontend/test/metabase/scenarios/binning/binning-reproductions.cy.spec.js
Labels: .CI & Tests, support/Repro

#16738 #16672 Repro: Implicit binning on longitude from SQL question results in error
  frontend/test/metabase/scenarios/binning/binning-reproductions.cy.spec.js
Labels: .CI & Tests, support/Repro

#16742 Move smoke tests to the CircleCi
  .circleci/config.yml
  .github/workflows/uberjar.yml
  frontend/test/__runner__/run_cypress_tests.js
  frontend/test/metabase/scenarios/smoketest/README.md
  frontend/test/metabase/scenarios/smoketest/admin.cy.spec.js
  frontend/test/metabase/scenarios/smoketest/admin_setup.cy.spec.js
  frontend/test/metabase/scenarios/smoketest/user.cy.spec.js
  package.json
Labels: .CI & Tests, .Tech Debt or Refactoring

#16753 #16739 Repro: Filter feature flag causes Run-overlay of results in Native editor unless editor is expanded
  frontend/test/metabase/scenarios/native/native.cy.spec.js
Labels: .CI & Tests, support/Repro

#16733 fix linear interpolation of missing values
  frontend/src/metabase/visualizations/lib/fill_data.js
  frontend/src/metabase/visualizations/lib/renderer_utils.js
  frontend/test/metabase/scenarios/visualizations/line_chart.cy.spec.js
Labels: support/Repro

#16760 Unskip repro for #15397
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16757 docs - note on pivot table database support [closes #14876]
  docs/users-guide/05-visualizing-results.md
Labels: .Documentation

#16769 Unskip repro for #15974
  frontend/test/metabase/scenarios/admin/settings/sso.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16772 Divide SSO spec into separate files (for each of the providers)
  frontend/test/metabase/scenarios/admin/settings/sso.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/sso/google.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/sso/jwt.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/sso/ldap.cy.spec.js
Labels: .CI & Tests, .Tech Debt or Refactoring

#16777 #16770 Repro: Changing granularity/binning of a field, which is already used for sorting, will fail the query
  frontend/test/metabase/scenarios/binning/binning-reproductions.cy.spec.js
Labels: .CI & Tests, support/Repro

#16799 #16781 Repro: Error when setting column type to Number in data model settings
  frontend/test/metabase/scenarios/admin/datamodel/field-type.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/field.cy.spec.js
Labels: .CI & Tests, support/Repro

#16765 Refactor before fix: Retrieve multiple get params for Public Question
  frontend/src/metabase/dashboard/components/Dashboard.jsx
  frontend/src/metabase/dashboard/containers/AutomaticDashboardApp.jsx
  frontend/src/metabase/parameters/components/Parameters.jsx
  frontend/src/metabase/parameters/components/Parameters/Parameters.jsx
  frontend/src/metabase/parameters/components/Parameters/syncQueryParamsWithURL.js
  frontend/src/metabase/public/components/EmbedFrame.jsx
  frontend/src/metabase/public/components/widgets/AdvancedSettingsPane.jsx
  frontend/src/metabase/public/containers/PublicQuestion.jsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx
  frontend/src/metabase/query_builder/components/__mocks__/NativeQueryEditor.jsx
  frontend/test/metabase/parameters/components/Parameters/syncQueryParamsWithURL.unit.spec.js
Labels: .CI & Tests, support/Repro

#16795 Retrieve multiple get params for Public Question
  frontend/src/metabase/parameters/components/Parameters/syncQueryParamsWithURL.js
  frontend/test/__support__/e2e/cypress.js
  frontend/test/metabase/scenarios/question/public/question.cy.spec.js
Labels: .CI & Tests, support/Repro

#16806 #16784 Repro: The list of collections available on homepage "Our analytics" depends on the name of the first 50 objects
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, support/Repro

#16807 #16789 Repro: Clicking column name when dropdown menu is open should close menu
  frontend/test/metabase/scenarios/visualizations/table.cy.spec.js
Labels: .CI & Tests, support/Repro

#16813 [SQL filters coverage] Basic SQL filter types
  .circleci/config.yml
  frontend/test/metabase/scenarios/filters/sql-filters.cy.spec.js
Labels: .CI & Tests, support/Repro

#16833 docs - fix docs image
  docs/users-guide/images/visualizations/column-header-formatting.png
Labels: .Documentation
