Repository metabase/metabase, pull requests merged in 2021-12, with the labels that each got.

#19144 docs - small formatting changes
  docs/operations-guide/environment-variables.md
Labels: Type:Documentation, backport

#19183 Added test email steps; minor reorganizing
  docs/troubleshooting-guide/cant-send-email.md
Labels: Type:Documentation

#19176 Fix google-api-client version from google driver
  .circleci/config.yml
  modules/drivers/google/deps.edn
Labels: backport

#19185 Fix LDAP port validation and add LDAP API tests
  src/metabase/api/ldap.clj
  test/metabase/api/ldap_test.clj
  test/metabase/integrations/ldap_test.clj
  test/metabase/test/integrations/ldap.clj
Labels: backport

#19231 docs - update links
  docs/users-guide/06-sharing-answers.md
  docs/users-guide/13-sql-parameters.md
  docs/users-guide/field-types.md
Labels: Type:Documentation, backport

#19242 docs - update link
  docs/troubleshooting-guide/cant-log-in.md
Labels: Type:Documentation, backport

#19234 docs - created troubleshooting permissions
  docs/troubleshooting-guide/index.md
  docs/troubleshooting-guide/permissions.md
Labels: Type:Documentation, backport

#19251 docs - fixed links and replaced screenshots
  docs/administration-guide/06-collections.md
  docs/administration-guide/images/collections/admin-panel-collections.png
  docs/administration-guide/images/collections/collection-permissions.png
Labels: Type:Documentation, backport

#19254 docs - edit FAQ
  docs/faq/general/do-we-need-a-data-processing-agreement.md
Labels: Type:Documentation, backport

#18886 docs: typo MB_EMOJI_IN_LOGS
  docs/operations-guide/log-configuration.md
Labels: Type:Documentation

#19238 docs - JWT
  docs/enterprise-guide/authenticating-with-jwt.md
Labels: Type:Documentation, backport

#19272 docs - expanding description of LDAP features
  docs/administration-guide/10-single-sign-on.md
  docs/administration-guide/images/ldap-attributes.png
  docs/administration-guide/images/ldap-group-mapping.png
Labels: Type:Documentation

#19276 Site url validation fixes #14491
  src/metabase/util.clj
  test/metabase/util_test.clj
Labels: backport

#19313 Fix Presto JDBC test in CircleCI
  .circleci/config.yml
Labels: backport

#19361 docs - plans blockquotes
  docs/administration-guide/data-permissions.md
  docs/enterprise-guide/audit.md
  docs/enterprise-guide/authenticating-with-jwt.md
  docs/enterprise-guide/authenticating-with-saml-azure-ad.md
  docs/enterprise-guide/authenticating-with-saml.md
  docs/enterprise-guide/cache.md
  docs/enterprise-guide/dashboard-subscriptions.md
  docs/enterprise-guide/data-sandboxes.md
  docs/enterprise-guide/full-app-embedding.md
  docs/enterprise-guide/saml-auth0.md
  docs/enterprise-guide/serialization.md
  docs/enterprise-guide/sql-snippets.md
  docs/enterprise-guide/start.md
  docs/enterprise-guide/tools.md
  docs/enterprise-guide/whitelabeling.md
  docs/users-guide/06-sharing-answers.md
Labels: Type:Documentation, backport

#19370 Fix X-Ray/Automagic Dashboards when source query has a filter
  src/metabase/automagic_dashboards/core.clj
  src/metabase/automagic_dashboards/filters.clj
  src/metabase/sync/analyze.clj
  src/metabase/sync/analyze/fingerprint.clj
  test/metabase/automagic_dashboards/core_test.clj
  test/metabase/sync/analyze/fingerprint_test.clj
Labels: backport

#19421 Update log4j2 from 2.16.0 -> 2.17.0
  deps.edn
Labels: backport

#19433 docs - install & setup consolidation
  docs/README.md
  docs/getting-started.md
  docs/images/AccountSetup.png
  docs/images/AddDatabaseInfo.png
  docs/images/NewsletterSignup.png
  docs/images/UsageData.png
  docs/images/WelcomeScreen.png
  docs/operations-guide/installing-metabase.md
  docs/setting-up-metabase.md
Labels: Type:Documentation, backport

#19442 fix missing text wrapping
  frontend/src/metabase/admin/datamodel/components/database/MetadataSchemaList.jsx
  frontend/src/metabase/admin/datamodel/components/database/MetadataTableList.jsx
  frontend/src/metabase/css/core/text.css
Labels: backport

#19450 docs - clarify sql access in sandboxing
  docs/enterprise-guide/data-sandboxes.md
Labels: Type:Documentation, backport

#19458 Docs - note on disabling animations
  docs/users-guide/account-settings.md
Labels: Type:Documentation

#19462 docs - remove mentions of mac application
  docs/administration-guide/databases/oracle.md
  docs/administration-guide/databases/vertica.md
  docs/contributing.md
  docs/operations-guide/environment-variables.md
  docs/operations-guide/installing-metabase.md
  docs/operations-guide/running-the-metabase-mac-app.md
  docs/operations-guide/upgrading-metabase.md
  docs/troubleshooting-guide/cant-log-in.md
  src/metabase/analytics/stats.clj
Labels: Type:Documentation
