Repository metabase/metabase, pull requests merged in 2022-03, with the labels that each got.

#20775 E2E oss/ee versions helpers cleanup
  frontend/test/__support__/e2e/helpers/e2e-enterprise-helpers.js
  frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
  frontend/test/metabase/scenarios/embedding/embedding-smoketests.cy.spec.js
  frontend/test/metabase/scenarios/moderation/reproductions/18021-verified-badge-not-visible-in-recents.cy.spec.js
  frontend/test/metabase/scenarios/sharing/subscriptions.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#20777 Make conditional `describe` blocks more readable
  frontend/test/__support__/e2e/helpers/e2e-enterprise-helpers.js
  frontend/test/metabase/scenarios/admin/audit/ad-hoc.cy.spec.js
  frontend/test/metabase/scenarios/admin/audit/auditing.cy.spec.js
  frontend/test/metabase/scenarios/admin/audit/questions-audit.cy.spec.js
  frontend/test/metabase/scenarios/admin/audit/subscriptions.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/edit.cy.spec.js
  frontend/test/metabase/scenarios/admin/people/people.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/sso/jwt.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/whitelabel-color-theme.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/whitelabel.cy.spec.js
  frontend/test/metabase/scenarios/admin/tools/erroring-questions.cy.spec.js
  frontend/test/metabase/scenarios/admin/troubleshooting/help.cy.spec.js
  frontend/test/metabase/scenarios/collections/collection-types.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/caching.cy.spec.js
  frontend/test/metabase/scenarios/embedding/embedding-premium-token.cy.spec.js
  frontend/test/metabase/scenarios/moderation/question-moderation.cy.spec.js
  frontend/test/metabase/scenarios/native/snippets/snippet-permissions.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/auth/sso.cy.spec.js
  frontend/test/metabase/scenarios/permissions/admin-permissions.cy.spec.js
  frontend/test/metabase/scenarios/permissions/reproductions/14873-regextract-in-sandboxed-table.cy.spec.js
  frontend/test/metabase/scenarios/permissions/reproductions/17763-cannot-edit-granular-after-block.cy.spec.js
  frontend/test/metabase/scenarios/permissions/sandboxes.cy.spec.js
  frontend/test/metabase/scenarios/question/caching.cy.spec.js
  frontend/test/metabase/scenarios/sharing/approved-domains.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/18669-test-email-with-parameters.cy.spec.js
  frontend/test/metabase/scenarios/sharing/subscriptions.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#20785 docs - remove premium embedding, update screenshots
  docs/administration-guide/13-embedding.md
  docs/administration-guide/images/embedding/01-enabling.png
  docs/administration-guide/images/embedding/02-share-icon.png
  docs/administration-guide/images/embedding/03-enable-question.png
  docs/administration-guide/images/embedding/04-preview.png
  docs/administration-guide/images/embedding/05-code.png
  docs/administration-guide/images/embedding/06-locked.png
Labels: Type:Documentation, backport

#20788 docs - fix & update permissions links
  docs/README.md
  docs/administration-guide/05-setting-permissions.md
  docs/administration-guide/data-permissions.md
Labels: Type:Documentation, backport

#20767 Fix 'Compare to the rest' action styling
  frontend/src/metabase/visualizations/components/ChartClickActions.jsx
Labels: backport

#20793 Separate "auditing" e2e group from the "admin"
  .circleci/config.yml
  frontend/test/metabase/scenarios/auditing/ad-hoc.cy.spec.js
  frontend/test/metabase/scenarios/auditing/auditing.cy.spec.js
  frontend/test/metabase/scenarios/auditing/questions-audit.cy.spec.js
  frontend/test/metabase/scenarios/auditing/subscriptions.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#20801 Increase "randomness" for caching tests
  frontend/test/metabase/scenarios/admin/settings/cache.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#20819 Repro #20815: Models should not be embeddable
  frontend/test/metabase/scenarios/embedding/embedding-smoketests.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#20506 Fix and reproduce #20499: The term "SQL query" used in DBs that don't support SQL
  frontend/src/metabase-lib/lib/metadata/Database.ts
  frontend/src/metabase-lib/lib/metadata/Database.unit.spec.ts
  frontend/src/metabase/nav/containers/Navbar.jsx
  frontend/src/metabase/new_query/selectors.js
  frontend/test/metabase/scenarios/native/native-mongo.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#20852 Extract hard coded embedding key for e2e tests
  frontend/test/__support__/e2e/cypress_data.js
  frontend/test/snapshot-creators/default.cy.snap.js
Labels: .CI & Tests, support/Repro, backport

#20853 Add e2e embedding `jwt` helper
  frontend/test/__support__/e2e/cypress.js
  frontend/test/__support__/e2e/external/e2e-jwt-sign.js
  frontend/test/__support__/e2e/helpers/e2e-embedding-helpers.js
Labels: .CI & Tests, QA

#20849 Repro #20845: Embedding with Locked parameters does not allow numeric values
  frontend/test/metabase/scenarios/embedding/reproductions/20845-locked-numeric-param.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#20886 docs - fixing glossary links
  docs/administration-guide/data-permissions.md
  docs/setting-up-metabase.md
  docs/troubleshooting-guide/filters.md
  docs/troubleshooting-guide/linked-filters.md
  docs/troubleshooting-guide/sandboxing.md
  docs/troubleshooting-guide/sync-fingerprint-scan.md
  docs/users-guide/06-sharing-answers.md
Labels: Type:Documentation, backport

#20890 Doc - fix link
  docs/troubleshooting-guide/bigquery-drive.md
Labels: backport

#20800 Fix schemas not loading/showing immediately for a saved question
  frontend/src/metabase-lib/lib/queries/StructuredQuery.ts
  frontend/src/metabase/redux/metadata.js
  frontend/test/metabase-lib/lib/queries/StructuredQuery.unit.spec.js
Labels: backport

#20897 Disable `auditing` e2e CI group
  .circleci/config.yml
  frontend/test/metabase/scenarios/auditing/README.md
Labels: Type:Tech Debt, .CI & Tests, backport

#20483 Upgrade Cypress to the latest version (9.5.1)
  frontend/test/__support__/e2e/helpers/e2e-misc-helpers.js
  frontend/test/metabase-visual/onboarding/urls.cy.spec.js
  frontend/test/metabase/scenarios/admin/people/people.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/localization.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/maps.cy.spec.js
  frontend/test/metabase/scenarios/binning/qb-explicit-joins.cy.spec.js
  frontend/test/metabase/scenarios/collections/collection-pinned-overview.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
  frontend/test/metabase/scenarios/models/models.cy.spec.js
  frontend/test/metabase/scenarios/native/native.cy.spec.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
  frontend/test/metabase/scenarios/question/nulls.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/maps.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
  package.json
  yarn.lock
Labels: Type:Tech Debt, .CI & Tests, QA

#20855 fix ssl-key name typo
  src/metabase/driver/postgres.clj
  test/metabase/driver/postgres_test.clj
Labels: backport

#20908 Handle numeric values for :number parameters in JWTs
  src/metabase/api/embed.clj
  src/metabase/driver/common/parameters/values.clj
  test/metabase/api/embed_test.clj
  test/metabase/driver/common/parameters/values_test.clj
Labels: backport

#20914 Pass H2 options as connection properties; add LOCK_TIMEOUT (fix flaky tests)
  src/metabase/db/env.clj
Labels: backport

#20907 Fix BigQuery incorrectly quoting datetime-truncated field literal forms
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj
  modules/drivers/druid/src/metabase/driver/druid/execute.clj
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  src/metabase/util/honeysql_extensions.clj
Labels: backport

#20945 docs - remove GA version note; fix broken link
  docs/administration-guide/01-managing-databases.md
  docs/users-guide/13-sql-parameters.md
Labels: Type:Documentation, backport

#20978 Binning should not error for datasets with only a single row
  src/metabase/query_processor/middleware/binning.clj
  test/metabase/query_processor/middleware/binning_test.clj
  test/metabase/test/data/interface.clj
Labels: backport

#20984 Quarantine caching e2e tests
  frontend/test/metabase/scenarios/admin/settings/cache.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#20987 Reinforce admin `field-type` E2E tests
  frontend/test/metabase/scenarios/admin/datamodel/field-type.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#20998 docs - fixes broken links in 42 branch
  README.md
  docs/administration-guide/localization.md
  docs/users-guide/03-basic-exploration.md
Labels: Type:Documentation

#20976 Fix error in send-abandonment-emails task
  src/metabase/core.clj
  src/metabase/task/follow_up_emails.clj
  test/metabase/task/follow_up_emails_test.clj
Labels: backport

#21027 Skip failing visual test caused by #21026
  frontend/test/metabase-visual/admin/permissions.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#21019 Upgrade Cypress to the version `9.5.2`
  package.json
  yarn.lock
Labels: Type:Tech Debt, .CI & Tests

#21011 Upgrade `cypress-real-events` to the latest version `1.7.0`
  package.json
  yarn.lock
Labels: Type:Tech Debt, .CI & Tests, QA

#21016 Upgrade `@testing-library/cypress` to the latest version (`8.0.2`)
  frontend/test/metabase-visual/notebook/notebook.cy.spec.js
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
  frontend/test/metabase/scenarios/custom-column/custom-column.cy.spec.js
  frontend/test/metabase/scenarios/joins/joins.cy.spec.js
  frontend/test/metabase/scenarios/models/helpers/e2e-models-helpers.js
  frontend/test/metabase/scenarios/models/models.cy.spec.js
  frontend/test/metabase/scenarios/native/snippets/snippet-permissions.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/setup/setup.cy.spec.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
  package.json
  yarn.lock
Labels: Type:Tech Debt, .CI & Tests, QA

#20975 Fix `[:relative-datetime :current]` inside `:between` filter clause
  shared/src/metabase/mbql/util.cljc
  shared/test/metabase/mbql/util_test.cljc
  test/metabase/query_processor/middleware/desugar_test.clj
Labels: backport

#21004 Google Analytics: use service accounts for auth
  docs/administration-guide/databases/google-analytics.md
  frontend/src/metabase/entities/databases/forms.js
  frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js
  modules/drivers/google/src/metabase/driver/google.clj
  modules/drivers/googleanalytics/resources/metabase-plugin.yaml
  test/metabase/test/initialize/plugins.clj
Labels: backport

#20970 SQL editor: explicit trigger of autocomplete
  frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx
  frontend/test/metabase/scenarios/native/reproductions/20625-prefix-match.cy.spec.js
Labels: backport

#21052 Increase E2E QA DBs timeout
  frontend/test/__support__/e2e/helpers/e2e-qa-databases-helpers.js
  frontend/test/snapshot-creators/qa-db.cy.snap.js
Labels: Type:Tech Debt, .CI & Tests, QA

#21029 Upgrade `cypress-grep` to the latest version (`2.13.1`)
  package.json
  yarn.lock
Labels: Type:Tech Debt, .CI & Tests, QA

#21066 Fix E2E binning sidebar flakes
  frontend/test/__support__/e2e/helpers/e2e-bi-basics-helpers.js
Labels: Type:Tech Debt, .CI & Tests, QA

#21033 docs - update sql editor page
  docs/users-guide/images/SQL-filter-widget.png
  docs/users-guide/images/SQLInterface.png
  docs/users-guide/images/writing-sql/SQL-filter-widget.png
  docs/users-guide/images/writing-sql/SQLInterface.png
  docs/users-guide/writing-sql.md
Labels: Type:Documentation, backport

#21039 Add autolink support and better email link handling to backend Markdown parsing
  deps.edn
  src/metabase/pulse/markdown.clj
  test/metabase/pulse/markdown_test.clj
Labels: backport

#21051 Fix regression from fixing #20954
  frontend/src/metabase/components/DebouncedFrame.jsx
Labels: backport

#21025 Make models not embeddable
  frontend/src/metabase/query_builder/containers/QuestionEmbedWidget.jsx
  frontend/test/metabase/scenarios/embedding/embedding-smoketests.cy.spec.js
Labels: backport

#21085 Fix question E2E flakes
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
  frontend/test/metabase/scenarios/question/view.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, QA

#21067 Upgrade `@cypress/webpack-preprocessor` to the latest version (`5.11.1`)
  package.json
  yarn.lock
Labels: Type:Tech Debt, .CI & Tests, QA

#21091 docs - remove enterprise refs
  docs/administration-guide/06-collections.md
  docs/administration-guide/10-single-sign-on.md
  docs/administration-guide/sso.md
  docs/enterprise-guide/authenticating-with-saml-azure-ad.md
  docs/enterprise-guide/authenticating-with-saml.md
  docs/enterprise-guide/cache.md
  docs/enterprise-guide/dashboard-subscriptions.md
  docs/enterprise-guide/data-sandboxes.md
  docs/enterprise-guide/full-app-embedding.md
  docs/enterprise-guide/sql-snippets.md
  docs/operations-guide/environment-variables.md
  docs/troubleshooting-guide/loading-from-h2.md
  docs/troubleshooting-guide/permissions.md
  docs/users-guide/dashboard-subscriptions.md
  docs/users-guide/interactive-dashboards.md
  docs/users-guide/sql-snippets.md
Labels: Type:Documentation, backport

#21077 docs update - backport
  docs/api-documentation.md
  docs/developers-guide-drivers.md
  docs/developers-guide/clojure.md
  docs/developers-guide/devenv.md
  docs/developers-guide/driver-changelog.md
  docs/developers-guide/drivers/basics.md
  docs/developers-guide/drivers/driver-tests.md
  docs/developers-guide/drivers/multimethods.md
  docs/developers-guide/drivers/plugins.md
  docs/developers-guide/drivers/start.md
  docs/developers-guide/emacs.md
  docs/developers-guide/frontend.md
  docs/developers-guide/start.md
  docs/developers-guide/visual-studio-code.md
  docs/metabase-product-screenshot.png
  docs/operations-guide/configuring-application-database.md
  docs/operations-guide/encrypting-database-details-at-rest.md
  docs/operations-guide/environment-variables.md
Labels: Type:Documentation

#21094 Skip repro for 8406 due to #21026
  frontend/test/metabase/scenarios/collections/personal-collections.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, QA

#21092 [E2E] Fix `permissions` flakes
  frontend/test/metabase/scenarios/permissions/sandboxes.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, QA

#21010 Upgrade `percy` to the latest version `3.1.1`
  package.json
  yarn.lock
Labels: Type:Tech Debt, .CI & Tests, QA

#21099 [E2E] Add `question` CI group to GitHub Actions
  .github/workflows/e2e-tests.yml
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/new.cy.spec.js
  frontend/test/metabase/scenarios/question/query-external.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/17514-ui-overlay.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, QA

#21127 [E2E] Robustify visit question by applying `visitQuestion` helper
  frontend/test/metabase/scenarios/admin/datamodel/table.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/localization.cy.spec.js
  frontend/test/metabase/scenarios/auditing/auditing.cy.spec.js
  frontend/test/metabase/scenarios/binning/qb-implicit-joins.cy.spec.js
  frontend/test/metabase/scenarios/collections/items-metadata.cy.spec.js
  frontend/test/metabase/scenarios/collections/permissions-baseline.cy.spec.js
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
  frontend/test/metabase/scenarios/embedding/reproductions/20634-locked-parameters-in-embedded-question.cy.spec.js
  frontend/test/metabase/scenarios/models/models-revision-history.cy.spec.js
  frontend/test/metabase/scenarios/models/models.cy.spec.js
  frontend/test/metabase/scenarios/moderation/question-moderation.cy.spec.js
  frontend/test/metabase/scenarios/moderation/reproductions/18021-verified-badge-not-visible-in-recents.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/search/recently-viewed.cy.spec.js
  frontend/test/metabase/scenarios/permissions/admin-permissions.cy.spec.js
  frontend/test/metabase/scenarios/question/caching.cy.spec.js
  frontend/test/metabase/scenarios/question/new.cy.spec.js
  frontend/test/metabase/scenarios/question/saved.cy.spec.js
  frontend/test/metabase/scenarios/question/summarization.cy.spec.js
  frontend/test/metabase/scenarios/question/timelines.cy.spec.js
  frontend/test/metabase/scenarios/question/view.cy.spec.js
  frontend/test/metabase/scenarios/sharing/approved-domains.cy.spec.js
  frontend/test/metabase/scenarios/smoketest/admin_setup.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, QA

#21048 Don't format non-temporal columns as datetimes in XLSX exports
  src/metabase/query_processor/streaming/xlsx.clj
  test/metabase/query_processor/streaming/xlsx_test.clj
Labels: backport

#21122 [E2E] Add a few more query-related CI groups to GitHub Actions
  .github/workflows/e2e-tests.yml
Labels: Type:Tech Debt, .CI & Tests, QA

#21143 docs - link maintenance
  docs/administration-guide/start.md
  docs/developers-guide-drivers.md
  docs/developers-guide/drivers/basics.md
  docs/developers-guide/drivers/driver-tests.md
  docs/developers-guide/drivers/multimethods.md
Labels: Type:Documentation, backport

#21139 Repro #21135: CC with the same names as the existing columns causes confusion in the expression editor
  frontend/test/metabase/scenarios/custom-column/reproductions/21135-cc-same-name-as-existing-column.cy.spec.js
Labels: .CI & Tests, support/Repro

#21090 Manual backport: (Issue: #19710, PR: #20874, #20915) No visual feedback when setting column properties in Admin
  frontend/src/metabase/admin/datamodel/components/database/MetadataTable.jsx
  frontend/src/metabase/admin/datamodel/containers/FieldApp.jsx
  frontend/src/metabase/admin/datamodel/containers/MetadataEditorApp.jsx
  frontend/src/metabase/entities/fields.js
  frontend/src/metabase/entities/tables.js
Labels: auto-backported

#20909 Add initial test coverage for native questions embedding
  frontend/test/metabase/scenarios/embedding/embedding-native.cy.spec.js
Labels: .CI & Tests, QA

#21146 remove explicit z-index on DateOperatorSelector
  frontend/src/metabase/query_builder/components/filters/DateOperatorSelector.jsx
Labels: backport

#21195 Unskip repro for #20845
  frontend/test/metabase/scenarios/embedding/reproductions/20845-locked-numeric-param.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#21194 Unskip repro for #18729
  frontend/test/metabase/scenarios/downloads/reproductions/18729-date-formatting-x-of-y.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#21205 Support quarters in Dashboard filters
  src/metabase/driver/common/parameters/dates.clj
  test/metabase/driver/common/parameters/dates_test.clj
  test/metabase/driver/sql/parameters/substitute_test.clj
Labels: backport

#21207 Make `mt/with-everything-store` parallel capable and mark more tests as parallel
  src/metabase/query_processor/store.clj
  test/metabase/driver/sql/parameters/substitute_test.clj
  test/metabase/query_processor/test_util.clj
Labels: Type:Tech Debt, .Performance, .CI & Tests, .Backend

#21189 Display Custom Parameter Fields on Mobile
  frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/VisibilityToggler/VisibilityToggler.jsx
  frontend/src/metabase/query_builder/components/view/View.jsx
  frontend/test/metabase/query_builder/components/VisibilityToggler.unit.spec.js
  frontend/test/metabase/scenarios/native-filters/sql-filters.cy.spec.js
Labels: backport

#21220 Remove ScratchApp
  frontend/src/metabase/internal/components/ScratchApp.jsx
Labels: backport

#21224 Ignore Empty Conditional Formatting Queries
  frontend/src/metabase/visualizations/lib/table_format.js
  frontend/test/metabase/visualizations/lib/table_format.unit.spec.js
Labels: backport

#21204 Fix `:postgres` filtering by current quarter; remove a few unneeded casts in PG SQL output
  frontend/test/metabase/scenarios/question/reproductions/20683-postgres-current-quarter.cy.spec.js
  modules/drivers/sparksql/src/metabase/driver/hive_like.clj
  src/metabase/driver/postgres.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/query_processor_test/date_bucketing_test.clj
Labels: backport

#21232 Upgrade `@types/webpack-dev-server` to the latest version `4.7.2`
  package.json
  yarn.lock
Labels: Type:Tech Debt

#21178 Fix moved model's collection isn't displayed until page refresh
  frontend/src/metabase/entities/questions.js
  frontend/src/metabase/entities/schemas.js
  frontend/test/metabase/entities/schemas.unit.spec.js
  frontend/test/metabase/scenarios/models/reproductions/19737-data-picker-not-showing-moved-model.cy.spec.js
Labels: backport

#21252 handle long schema names
  frontend/src/metabase/browse/containers/SchemaBrowser.jsx
  frontend/src/metabase/browse/containers/SchemaBrowser.styled.tsx
Labels: backport

#21263 Remove extra decimals in small x-axis scales
  frontend/src/metabase/visualizations/lib/apply_axis.js
Labels: backport

#21255 Add new `valid-path-format?` predicate for schema validation to fix downgrading issues generically
  src/metabase/models/permissions.clj
  test/metabase/models/permissions_test.clj
Labels: backport

#21292 [E2E] Refactor `parameters-embedded` spec into `embedding-dashboard`
  frontend/test/__support__/e2e/helpers/e2e-embedding-helpers.js
  frontend/test/metabase/scenarios/embedding/embedding-dashboard.cy.spec.js
  frontend/test/metabase/scenarios/embedding/embedding-dashboard.js
  frontend/test/metabase/scenarios/embedding/parameters-embedded.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, QA

#21304 Fix Loading the SSL root certificate into a TrustManager
  src/metabase/models/secret.clj
  test/metabase/models/secret_test.clj
Labels: backport

#21301 Repro #21034: Autocomplete flicker in SQL Editor
  frontend/test/metabase/scenarios/native/reproductions/21034-autocomplete-flicker.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#21333 [e2e] use maildev version 1.1.0
  .circleci/config.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/percy-issue-comment.yml
  .github/workflows/percy.yml
  frontend/test/__support__/e2e/helpers/e2e-email-helpers.js
  frontend/test/metabase/scenarios/README.md
Labels: backport

#21279 Make "Invite someone" button not overlapping with other elements
  frontend/src/metabase/components/AdminPaneLayout.jsx
  frontend/src/metabase/components/AdminPaneLayout.styled.jsx
  frontend/test/metabase/scenarios/admin/people/people.cy.spec.js
Labels: backport

#21295 [E2E] Add `embedding` group to GitHub Actions
  .github/workflows/e2e-tests.yml
Labels: Type:Tech Debt, .CI & Tests, QA

#21323 Fix Time Series Fill When Grouping by Minute
  frontend/src/metabase/visualizations/lib/timeseries.js
  frontend/test/metabase/visualizations/lib/timeseries.unit.spec.js
Labels: backport

#21302 Remove flicker in SQL editing autocomplete
  frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx
  frontend/test/metabase/scenarios/native/reproductions/21034-autocomplete-flicker.cy.spec.js
Labels: backport

#21356 docs - update links
  docs/administration-guide/start.md
  docs/enterprise-guide/sql-snippets.md
Labels: Type:Documentation, backport

#21360 [E2E] Log output to file and store it as an artifact
  .github/workflows/e2e-tests.yml
  frontend/test/__runner__/log4j2.xml
Labels: Type:Tech Debt, .CI & Tests, QA

#21331 Docs - fix broken link
  docs/administration-guide/01-managing-databases.md
Labels: backport

#21368 Fix a flake in `models`
  frontend/test/metabase/scenarios/models/models.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#21373 Revert "Bump executor (#21036)"
  .circleci/config.yml
Labels: Type:Tech Debt, .CI & Tests

#21387 Fix flakes in native filters spec
  frontend/test/metabase/scenarios/native-filters/helpers/e2e-field-filter-helpers.js
Labels: Type:Tech Debt, .CI & Tests, QA

#21389 [E2E] Fix xrays flake
  frontend/test/metabase/scenarios/dashboard/x-rays.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, QA

#21376 Turn `modifyObstructiveCode` off in Cypress settings
  frontend/test/__support__/e2e/cypress-snapshots.json
  frontend/test/__support__/e2e/cypress.json
Labels: .CI & Tests, QA

#21394 [E2E] Reinforce repro for #17514
  frontend/test/metabase/scenarios/question/reproductions/17514-ui-overlay.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, QA

#21397 [E2E] Fix flaky sidebar tests
  frontend/test/metabase/scenarios/collections/collections-sidebar.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, QA
