Repository metabase/metabase, pull requests merged in 2022-12, with the labels that each got.

#26706 Make sure the new datetime functions work with literal
  modules/drivers/vertica/src/metabase/driver/vertica.clj
  src/metabase/query_processor/middleware/wrap_value_literals.clj
  src/metabase/util/honeysql_extensions.clj
  test/metabase/query_processor_test/date_time_zone_functions_test.clj
  test/metabase/util/honeysql_extensions_test.clj
Labels: backport

#26654 Fixes "Add series" modal when an instance has corrupted questions
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase-lib/queries/InternalQuery.ts
  frontend/src/metabase-lib/queries/NativeQuery.ts
  frontend/src/metabase-lib/queries/StructuredQuery.ts
Labels: backport

#26633 Convert-timezone for bigquery, snowflake, redshift
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/params_test.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
  modules/drivers/snowflake/test/metabase/test/data/snowflake.clj
  test/metabase/driver/sql/parameters/substitute_test.clj
  test/metabase/query_processor_test/alternative_date_test.clj
  test/metabase/query_processor_test/date_time_zone_functions_test.clj
Labels: backport

#26857 Fix sticky filters in embed mode
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.styled.jsx
Labels: backport

#26828 Extract sample DB to plugins directory on startup
  .clj-kondo/config.edn
  src/metabase/plugins.clj
  src/metabase/sample_data.clj
  src/metabase/util/files.clj
  test/metabase/sample_data_test.clj
Labels: backport

#26593 Fix Input and dropdown fields have different styles
  frontend/src/metabase/components/InputBlurChange.styled.tsx
  frontend/src/metabase/core/components/SelectButton/SelectButton.styled.tsx
  frontend/src/metabase/core/style/input.ts
  frontend/src/metabase/visualizations/components/settings/ChartSettingInput.styled.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingInputNumeric.styled.tsx
Labels: backport

#26845 Fixes remapped columns support for the row chart type
  frontend/src/metabase-types/api/dataset.ts
  frontend/src/metabase/static-viz/components/RowChart/RowChart.tsx
  frontend/src/metabase/static-viz/lib/format.ts
  frontend/src/metabase/visualizations/index.js
  frontend/src/metabase/visualizations/lib/graph/columns.ts
  frontend/src/metabase/visualizations/shared/types/data.ts
  frontend/src/metabase/visualizations/visualizations/RowChart/RowChart.tsx
Labels: backport

#26879 Remove `is_write` card property on the FE
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase/entities/questions.js
  frontend/src/metabase/entities/questions/forms.js
  frontend/src/metabase/query_builder/components/QuestionActions.tsx
Labels: backport

#26797 Respect chart orders in static viz
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase/static-viz/components/FunnelChart/FunnelChart.tsx
  frontend/src/metabase/static-viz/components/FunnelChart/types.ts
  frontend/src/metabase/static-viz/components/FunnelChart/utils/funnel.ts
  frontend/src/metabase/static-viz/components/FunnelChart/utils/funnel.unit.spec.ts
  frontend/src/metabase/static-viz/components/LineAreaBarChart/LineAreaBarChart.tsx
  frontend/src/metabase/static-viz/components/LineAreaBarChart/utils/series.tsx
  frontend/src/metabase/static-viz/components/LineAreaBarChart/utils/series.unit.spec.ts
  frontend/src/metabase/static-viz/components/LineAreaBarChart/utils/settings.unit.spec.ts
  frontend/src/metabase/static-viz/components/XYChart/XYChart.tsx
  frontend/src/metabase/static-viz/components/XYChart/types.ts
  frontend/src/metabase/visualizations/lib/settings.js
  frontend/src/metabase/visualizations/lib/settings/graph.js
  src/metabase/pulse/render/body.clj
  test/metabase/pulse/render/body_test.clj
  test/metabase/pulse/render/js_svg_test.clj
Labels: backport, visual

#26908 fix audit dashboards click behavior
  enterprise/frontend/src/metabase-enterprise/audit_app/lib/mode.js
  enterprise/frontend/src/metabase-enterprise/tools/mode.js
  frontend/src/metabase/visualizations/visualizations/RowChart/RowChart.tsx
Labels: backport

#26921 docs - note on dashboard deep copy
  docs/dashboards/introduction.md
Labels: Type:Documentation, backport

#26878 Bump SSHd => 2.9.2
  deps.edn
Labels: backport

#26926 docs - api update 45
  docs/api-documentation.md
  docs/api/action.md
  docs/api/app.md
  docs/api/card.md
  docs/api/dashboard.md
  docs/api/emitter.md
  docs/api/google.md
  docs/api/ldap.md
  docs/api/permissions.md
Labels: Type:Documentation

#26685 docs - convertTimezone, datetimeAdd, datetimeSubtract, and datetimeDiff
  docs/questions/query-builder/expressions-list.md
  docs/questions/query-builder/expressions/converttimezone.md
  docs/questions/query-builder/expressions/datetimeadd.md
  docs/questions/query-builder/expressions/datetimediff.md
  docs/questions/query-builder/expressions/datetimesubtract.md
  frontend/src/metabase-lib/expressions/helper-text-strings.ts
Labels: Type:Documentation, backport

#26841 Fix `has-user-setup` Setting not being cached correctly
  src/metabase/setup.clj
  test/metabase/setup_test.clj
Labels: backport

#26880 Fixes remapped columns support for the row chart type (#26845)
  frontend/src/metabase-types/api/dataset.ts
  frontend/src/metabase/static-viz/components/RowChart/RowChart.tsx
  frontend/src/metabase/static-viz/lib/format.ts
  frontend/src/metabase/visualizations/index.js
  frontend/src/metabase/visualizations/lib/graph/columns.ts
  frontend/src/metabase/visualizations/shared/types/data.ts
  frontend/src/metabase/visualizations/visualizations/RowChart/RowChart.tsx
Labels: auto-backported

#26941 Last-minute translations for x.45
  locales/ar.po
  locales/bg.po
  locales/ca.po
  locales/cs.po
  locales/de.po
  locales/es.po
  locales/fa.po
  locales/fr.po
  locales/id.po
  locales/it.po
  locales/ja.po
  locales/metabase.pot
  locales/nb.po
  locales/nl.po
  locales/pl.po
  locales/pt-BR.po
  locales/ru.po
  locales/sk.po
  locales/sr.po
  locales/sv.po
  locales/tr.po
  locales/uk.po
  locales/vi.po
  locales/zh-HK.po
  locales/zh-TW.po
  locales/zh.po
Labels: backport

#26965 Fix snowflake tests
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
Labels: backport

#26934 Serdes v2: Fix flaky e2e test
  src/metabase/models/field.clj
Labels: backport

#26978 docs - update datetimediff
  docs/questions/query-builder/expressions/datetimediff.md
Labels: Type:Documentation, backport

#26815 Fix incorrect datetime-diff results for bigquery on leap years
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj
  test/metabase/query_processor_test/date_time_zone_functions_test.clj
Labels: backport

#26993 add data.xml to deps.edn
  deps.edn
Labels: backport

#26963 docs - add limitations, formatting
  docs/questions/query-builder/expressions/converttimezone.md
  docs/questions/query-builder/expressions/datetimeadd.md
  docs/questions/query-builder/expressions/datetimediff.md
Labels: Type:Documentation, backport

#26966 docs - update api docs
  docs/api-documentation.md
  docs/api/action.md
  docs/api/app.md
  docs/api/card.md
  docs/api/dashboard.md
  docs/api/emitter.md
  docs/api/google.md
  docs/api/ldap.md
  docs/api/permissions.md
Labels: Type:Documentation

#26881 Serdes v2: Correctly (de)serialize references to segments and native snippets
  enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj
  src/metabase/models/card.clj
  src/metabase/models/serialization/util.clj
Labels: backport

#27010 Revert "Remove support for Heroku deployment (#25124) (#26298)"
  Procfile
  app.json
  bin/heroku/deploy
  bin/release/src/release.clj
  bin/release/src/release/common.clj
  bin/release/src/release/heroku.clj
  bin/start
  docs/installation-and-operation/installing-metabase.md
  docs/installation-and-operation/running-metabase-on-heroku.md
  docs/installation-and-operation/start.md
  docs/installation-and-operation/upgrading-metabase.md
  docs/troubleshooting-guide/timeout.md
Labels: Type:Tech Debt

#27018 [Docs] Fix external broken link
  .mlc_config.json
  docs/developers-guide/e2e-tests.md
Labels: Type:Tech Debt, backport

#26821 Change hasBreakout check
  frontend/src/metabase/query_builder/components/view/sidebars/ChartSettingsSidebar.jsx
  frontend/src/metabase/visualizations/components/ChartSettings.jsx
Labels: backport

#27011 Add `clojure -M:ee:drivers:check` to CI
  .github/workflows/backend.yml
  deps.edn
Labels: backport

#27021 🍒 Backport (pre) release script
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
Labels: Type:Tech Debt, .CI & Tests, auto-backported

#26761 fix core/Input component, deduplicate input components
  enterprise/frontend/src/metabase-enterprise/audit_app/components/AuditParameters.jsx
  enterprise/frontend/src/metabase-enterprise/audit_app/components/AuditParameters.styled.jsx
  enterprise/frontend/src/metabase-enterprise/auth/components/SessionTimeoutSetting/SessionTimeoutSetting.styled.tsx
  enterprise/frontend/src/metabase-enterprise/auth/components/SessionTimeoutSetting/SessionTimeoutSetting.tsx
  frontend/src/metabase/admin/datamodel/components/database/MetadataTable/MetadataTable.styled.tsx
  frontend/src/metabase/admin/people/components/SearchInput.jsx
  frontend/src/metabase/admin/people/containers/PeopleListingApp.jsx
  frontend/src/metabase/admin/permissions/components/FilterableTree/FilterableTree.tsx
  frontend/src/metabase/admin/permissions/components/PermissionsEditor/PermissionsEditorContent.jsx
  frontend/src/metabase/admin/settings/components/LicenseInput/LicenseInput.styled.tsx
  frontend/src/metabase/admin/settings/components/LicenseInput/LicenseInput.tsx
  frontend/src/metabase/components/FieldValuesWidget.jsx
  frontend/src/metabase/components/InputBlurChange.styled.tsx
  frontend/src/metabase/components/ListField/ListField.styled.tsx
  frontend/src/metabase/components/ListField/ListField.tsx
  frontend/src/metabase/components/ListSearchField.jsx
  frontend/src/metabase/components/SingleSelectListField/SingleSelectListField.styled.tsx
  frontend/src/metabase/components/SingleSelectListField/SingleSelectListField.tsx
  frontend/src/metabase/components/TextInput/TextInput.styled.tsx
  frontend/src/metabase/components/TextInput/TextInput.tsx
  frontend/src/metabase/components/TextInput/index.js
  frontend/src/metabase/core/components/AccordionList/AccordionListCell.jsx
  frontend/src/metabase/core/components/AccordionList/AccordionListCell.styled.tsx
  frontend/src/metabase/core/components/AutocompleteInput/AutocompleteInput.tsx
  frontend/src/metabase/core/components/AutocompleteInput/AutocompleteInput.unit.spec.tsx
  frontend/src/metabase/core/components/ExternalLink/ExternalLink.styled.tsx
  frontend/src/metabase/core/components/Input/Input.stories.tsx
  frontend/src/metabase/core/components/Input/Input.styled.tsx
  frontend/src/metabase/core/components/Input/Input.tsx
  frontend/src/metabase/core/components/Link/Link.styled.tsx
  frontend/src/metabase/core/components/Tab/Tab.styled.tsx
  frontend/src/metabase/core/components/Toggle/Toggle.styled.tsx
  frontend/src/metabase/core/style/input.ts
  frontend/src/metabase/dashboard/components/AddSeriesModal/QuestionList.jsx
  frontend/src/metabase/dashboard/components/AddSeriesModal/QuestionList.styled.jsx
  frontend/src/metabase/dashboard/components/add-card-sidebar/QuestionPicker.jsx
  frontend/src/metabase/dashboard/components/add-card-sidebar/QuestionPicker.styled.jsx
  frontend/src/metabase/lib/colors/palette.ts
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.styled.jsx
  frontend/src/metabase/query_builder/components/filters/pickers/SelectPicker.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/DimensionList/DimensionList.jsx
  frontend/src/metabase/timelines/collections/components/TimelineDetailsModal/TimelineDetailsModal.styled.tsx
  frontend/src/metabase/timelines/collections/components/TimelineDetailsModal/TimelineDetailsModal.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingInputNumeric.styled.tsx
  frontend/test/metabase/scenarios/question/new.cy.spec.js
Labels: Type:Tech Debt, visual

#27026 docs - athena notes
  docs/databases/connecting.md
  docs/databases/connections/athena.md
Labels: Type:Documentation, backport

#27016 Athena Driver: change auth method description and helper text
  modules/drivers/athena/resources/metabase-plugin.yaml
Labels: backport

#27017 docs - update custom destinations
  docs/dashboards/interactive.md
Labels: Type:Documentation, backport

#27022 docs - update public links
  docs/configuring-metabase/appearance.md
  docs/embedding/signed-embedding-parameters.md
  docs/questions/sharing/public-links.md
  docs/questions/start.md
Labels: Type:Documentation, backport

#27050 Fix flaky `remap-human-readable-string-column-test`
  test/metabase/test/util.clj
Labels: backport, flaky-test-fix

#26816 datetime-diff function for vertica
  modules/drivers/vertica/src/metabase/driver/vertica.clj
Labels: backport

#26758 datetime-diff function for redshift
  modules/drivers/redshift/src/metabase/driver/redshift.clj
Labels: backport

#27002 datetime-diff function for SQL Server
  modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj
  test/metabase/query_processor_test/date_time_zone_functions_test.clj
Labels: backport

#27027 Remove unused import
  frontend/src/metabase/static-viz/lib/numbers.ts
Labels: Type:Tech Debt, .Frontend, backport

#27065 Fix flaky tests `field-values-test.sync-recreate-field-values-test `
  test/metabase/sync/field_values_test.clj
Labels: flaky-test-fix

#27051 CI for release: verify that the downloaded Uberjar is a valid JAR file
  .github/workflows/release.yml
Labels: backport

#27081 Unskip repro for #25031
  frontend/test/metabase/scenarios/embedding/reproductions/20845-25031-locked-numeric-param.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#27048 Disable Athena driver IAM role-based auth in Cloud
  modules/drivers/athena/src/metabase/driver/athena.clj
  modules/drivers/athena/test/metabase/driver/athena_test.clj
Labels: .Backend, backport, Database/Athena

#27091 docs - update can't view or edit
  docs/troubleshooting-guide/cant-view-or-edit.md
Labels: Type:Documentation, backport

#27092 docs - update permissions troubleshooting
  docs/troubleshooting-guide/data-permissions.md
  docs/troubleshooting-guide/sync-fingerprint-scan.md
Labels: Type:Documentation, backport

#27071 Migrate MySQL latest driver test to GitHub Actions
  .circleci/config.yml
  .github/workflows/drivers.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#27078 Do not run driver tests when PR is in a draft mode
  .github/workflows/drivers.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#27136 Remove screen.debugs from tests
  frontend/src/metabase/components/DateSingleWidget/DateSingleWidget.unit.spec.tsx
  frontend/src/metabase/components/TokenField/TokenField.unit.spec.js
Labels: .CI & Tests

#26726 Release script: remove the container build & push
  bin/release/src/release.clj
  bin/release/src/release/docker.clj
Labels: backport

#27153 CI for release: use up-to-date actions/download-artifact@v3
  .github/workflows/release.yml
Labels: backport

#27148 Migrate Vertica driver test to GitHub Actions
  .circleci/config.yml
  .github/workflows/drivers.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#27103 Migrate Snowflake driver test to GitHub Actions
  .circleci/config.yml
  .github/workflows/drivers.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#27090 Update token check URL, using the current one as the fallback
  src/metabase/public_settings/premium_features.clj
  test/metabase/public_settings/premium_features_test.clj
Labels: backport

#27168 🍒 Backport Additional drivers to GitHub Actions
  .circleci/config.yml
  .github/workflows/drivers.yml
Labels: auto-backported

#27015 Support "quarter" unit for datetimeDiff
  docs/questions/query-builder/expressions/datetimediff.md
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj
  modules/drivers/vertica/src/metabase/driver/vertica.clj
  shared/src/metabase/mbql/schema.cljc
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  test/metabase/query_processor_test/date_time_zone_functions_test.clj
Labels: backport

#26806 Add app colors example
  docs/configuring-metabase/environment-variables.md
Labels: backport

#27108 docs - approved domains
  docs/configuring-metabase/email.md
  docs/configuring-metabase/settings.md
Labels: Type:Documentation, backport

#27147 Migrate Mongo 4.0 and 5.0 driver tests to GitHub Actions
  .circleci/config.yml
  .github/workflows/drivers.yml
Labels: Type:Tech Debt, .CI & Tests

#27203 🍒 Migrate Mongo 4.0 and 5.0 driver tests to GitHub Actions (#27147)
  .circleci/config.yml
  .github/workflows/drivers.yml
Labels: auto-backported

#27194 Try `dorny/test-reporter`
  .github/actions/test-driver/action.yml
  .github/workflows/backend.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#26468 Suppress console log when using `with-log-messages-for-level`
  test/metabase/logger_test.clj
  test/metabase/test/util/log.clj
Labels: backport

#27223 [CI] Add `concurrency` to the `drivers` workflow
  .github/workflows/drivers.yml
Labels: Type:Tech Debt, .CI & Tests

#27224 Fix datetimeDiff helper text
  frontend/src/metabase-lib/expressions/helper-text-strings.ts
Labels: backport

#27225 Improve datetimeDiff type error message
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj
  modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj
  modules/drivers/vertica/src/metabase/driver/vertica.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  test/metabase/query_processor_test/date_time_zone_functions_test.clj
Labels: backport

#27192 Relieve db pressure on api/health check
  src/metabase/db/connection_pool_setup.clj
  src/metabase/server/routes.clj
  test/metabase/db/connection_pool_setup_test.clj
Labels: backport

#27247 docs - make version history easier to find
  docs/README.md
  docs/dashboards/introduction.md
  docs/data-modeling/models.md
  docs/exploration-and-organization/history.md
  docs/exploration-and-organization/start.md
  docs/questions/native-editor/writing-sql.md
  docs/questions/query-builder/introduction.md
Labels: Type:Documentation, backport

#27193 docs - update general settings, localization, and timezones
  docs/configuring-metabase/appearance.md
  docs/configuring-metabase/localization.md
  docs/configuring-metabase/settings.md
  docs/configuring-metabase/timezones.md
  docs/questions/query-builder/expressions/converttimezone.md
  docs/troubleshooting-guide/timezones.md
Labels: Type:Documentation, backport

#27163 Add dedicated docs pages for some expressions
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/helper-text-strings.ts
Labels: backport

#27149 Migrate Oracle driver test to GitHub Actions
  .circleci/config.yml
  .github/workflows/drivers.yml
Labels: Type:Tech Debt, .CI & Tests

#27264 Revert default behavior on 45 for embedding `top_nav`
  frontend/src/metabase/redux/embed.js
  frontend/test/metabase/scenarios/embedding/embedding-full-app.cy.spec.js
Labels: auto-backported

#27269 [CI] Add new drivers to the skipped-checks
  .github/workflows/drivers-skipped-checks.yml
Labels: Type:Tech Debt, .CI & Tests

#27271 🍒 [CI] Add new drivers to the skipped-checks (#27269)
  .github/workflows/drivers-skipped-checks.yml
Labels: Type:Tech Debt, .CI & Tests, auto-backported

#27097 Open absolute urls not relatively to a metabase instance
  frontend/src/metabase/lib/dom.js
Labels: backport

#27294 docs - fix link
  docs/troubleshooting-guide/models.md
Labels: Type:Documentation, backport

#27324 Repro #27257: Number filter with 0 (zero) as default value shows as empty in the widget
  frontend/test/metabase/scenarios/native-filters/reproductions/27257.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#27330 Reproductions #27020 and #27105: static-viz failing for certain date formatting options
  frontend/test/metabase/scenarios/dashboard/reproductions/27020-27105-static-viz-date-formatting-failures.cy.spec.js
Labels: .CI & Tests, support/Repro

#27333 Repro #27279: Changing sorting does not apply for X-axis anymore
  frontend/test/metabase/scenarios/visualizations/reproductions/27279-sorting-does-not-apply-to-x-axis.cy.spec.js
Labels: .CI & Tests, support/Repro

#27336 🍒 Backport reproductions for 2022-12-19
  frontend/test/metabase/scenarios/dashboard/reproductions/27020-27105-static-viz-date-formatting-failures.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/27257.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/27279-sorting-does-not-apply-to-x-axis.cy.spec.js
Labels: auto-backported

#27351 Error when user attribute is null for sandboxing
  enterprise/backend/src/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions.clj
  enterprise/backend/test/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions_test.clj
Labels: backport

#27043 bump redux
  enterprise/frontend/src/metabase-enterprise/auth/containers/JwtAuthCard/JwtAuthCard.tsx
  enterprise/frontend/src/metabase-enterprise/auth/containers/SamlAuthCard/SamlAuthCard.tsx
  enterprise/frontend/src/metabase-enterprise/caching/components/DatabaseCacheTTLField/DatabaseCacheTTLField.unit.spec.js
  frontend/src/metabase-types/api/dashboard.ts
  frontend/src/metabase-types/api/mocks/dashboard.ts
  frontend/src/metabase-types/store/state.ts
  frontend/src/metabase/admin/settings/components/SettingsBatchForm.jsx
  frontend/src/metabase/admin/settings/components/SettingsEmailForm.jsx
  frontend/src/metabase/components/EntityMenu.jsx
  frontend/src/metabase/components/Popover/Popover.jsx
  frontend/src/metabase/components/Triggerable.jsx
  frontend/src/metabase/query_builder/components/ExtendedOptions.jsx
  frontend/src/metabase/query_builder/components/SelectionModule.jsx
  frontend/src/metabase/query_builder/components/filters/FilterWidget.tsx
  frontend/src/metabase/query_builder/components/view/ConvertQueryModal/ConvertQueryModal.tsx
  frontend/src/metabase/query_builder/components/view/PreviewQueryModal/PreviewQueryModal.tsx
  frontend/src/metabase/query_builder/components/view/QuestionAlertWidget.jsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx
  package.json
  yarn.lock
Labels: visual

#27357 Ensuring _raw prop is present on transformed series in line/area/bar …
  frontend/src/metabase-types/api/mocks/card.ts
  frontend/src/metabase-types/api/mocks/dataset.ts
  frontend/src/metabase-types/api/mocks/series.ts
  frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx
  frontend/src/metabase/visualizations/lib/series.ts
  frontend/src/metabase/visualizations/lib/series.unit.spec.ts
  frontend/test/metabase/scenarios/visualizations/reproductions/27279-sorting-does-not-apply-to-x-axis.cy.spec.js
Labels: backport

#27342 Fix Zero Filters not loading URL Parameters
  frontend/src/metabase/components/TextWidget/TextWidget.stories.tsx
  frontend/src/metabase/components/TextWidget/TextWidget.tsx
  frontend/src/metabase/components/TextWidget/TextWidget.unit.spec.tsx
  frontend/test/metabase/scenarios/native-filters/reproductions/27257.cy.spec.js
Labels: backport

#27339 Fixes to static-viz datetime formatter, in particular, issues #27020 and #27105
  frontend/test/metabase/scenarios/dashboard/reproductions/27020-27105-static-viz-date-formatting-failures.cy.spec.js
  src/metabase/pulse/render/datetime.clj
  test/metabase/pulse/render/body_test.clj
  test/metabase/pulse/render/datetime_test.clj
Labels: backport

#27381 Repro #25374: Comma-separated dashboard filter values not passed down to the question
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/25374-comma-separated-values-not-passed-to-question.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#27378 Fixes to static-viz datetime formatter, in particular, issues #27020 …
  frontend/test/metabase/scenarios/dashboard/reproductions/27020-27105-static-viz-date-formatting-failures.cy.spec.js
  src/metabase/pulse/render/datetime.clj
  test/metabase/pulse/render/body_test.clj
  test/metabase/pulse/render/datetime_test.clj
Labels: auto-backported

#27388 Repro #25927: Column filters not working on questions with custom columns
  frontend/test/metabase/scenarios/filters/reproductions/25927-column-filters-not-working-after-cc.cy.spec.js
Labels: .CI & Tests, support/Repro

#27389 Repro #27123: Exclude filter always ends up showing "Days of the week"
  frontend/test/metabase/scenarios/filters/reproductions/27123-exclude-always-shows-days-of-week.cy.spec.js
Labels: .CI & Tests, support/Repro

#27390 Repro #27380: Doing "Zoom in" from dashboard drops fields from joined tables
  frontend/test/metabase/scenarios/joins/reproductions/27380-dashboard-drops-joined-fields-on-zoom-in.cy.spec.js
Labels: .CI & Tests, support/Repro

#27397 🍒 Backport repros created on 2022-12-22
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/25374-comma-separated-values-not-passed-to-question.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/25927-column-filters-not-working-after-cc.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/27123-exclude-always-shows-days-of-week.cy.spec.js
  frontend/test/metabase/scenarios/joins/reproductions/27380-dashboard-drops-joined-fields-on-zoom-in.cy.spec.js
Labels: auto-backported

#27396 Repro #24839: Can't aggregate if source is the aggregated question
  frontend/test/metabase/scenarios/question/reproductions/24839-summarize-source-question-with-summarization.cy.spec.js
Labels: .CI & Tests, support/Repro

#27400 Repro #26861: "Exclude" field filter breaks native query
  frontend/test/metabase/scenarios/filters/reproductions/26861-exclude-breaks-native.cy.spec.js
Labels: .CI & Tests, support/Repro

#27404 Repro #25994: Between specific dates filter fails after aggregation
  frontend/test/metabase/scenarios/filters/reproductions/25994-between-after-summarize-not-working.cy.spec.js
Labels: .CI & Tests, support/Repro

#27412 docs - small updates
  docs/README.md
  docs/embedding/introduction.md
  docs/people-and-groups/managing.md
Labels: Type:Documentation, backport

#27409 [CI] Upgrade `deploysentinel` to the latest `v0.7.0`
  package.json
  yarn.lock
Labels: Type:Tech Debt, .CI & Tests, backport

#27411 🍒 Backport reproductions from 2022-12-23
  frontend/test/metabase/scenarios/filters/reproductions/25994-between-after-summarize-not-working.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/26861-exclude-breaks-native.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/24839-summarize-source-question-with-summarization.cy.spec.js
Labels: auto-backported

#27407 Upgrade `percy/cli` to the latest version
  package.json
  yarn.lock
Labels: Type:Tech Debt, .CI & Tests, backport

#27417 [Chore] Upgrade `concurrently` to the latest version
  package.json
  yarn.lock
Labels: Type:Tech Debt

#27235 [CI] Add concurrency to BE and FE workflows
  .github/workflows/backend.yml
  .github/workflows/drivers.yml
  .github/workflows/frontend.yml
Labels: Type:Tech Debt, .CI & Tests

#27345 [CI] Do not run FE and BE tests when PRs are in a draft mode
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
Labels: .CI & Tests

#27426 [CI] Fix flag type in `codecov` workflow
  codecov.yml
Labels: Type:Tech Debt, .CI & Tests

#27428 Repro #27356: Moving between dashboards with/without filter triggers an error
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/27356-navigation-between-two-dashboards.cy.spec.js
Labels: .CI & Tests, support/Repro

#27429 Repro #25378: Relative date filter on breakout after aggregation
  frontend/test/metabase/scenarios/filters/reproductions/25378-relative-date-on-breakout.cy.spec.js
Labels: .CI & Tests, support/Repro

#27433 🍒 Backport repros 2022-12-27
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/27356-navigation-between-two-dashboards.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/25378-relative-date-on-breakout.cy.spec.js
Labels: auto-backported

#27432 🍒 Backport CI updates
  .github/workflows/backend.yml
  .github/workflows/drivers.yml
  .github/workflows/frontend.yml
  codecov.yml
Labels: auto-backported

#27248 Fix BigQuery parsing of `bigdecimal` results
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/params_test.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj
Labels: backport

#27182 Use gvenzl/oracle-xe docker images to test Oracle
  .github/workflows/drivers-skipped-checks.yml
  .github/workflows/drivers.yml
  modules/drivers/oracle/src/metabase/driver/oracle.clj
  modules/drivers/oracle/test/metabase/driver/oracle_test.clj
  modules/drivers/oracle/test/metabase/test/data/oracle.clj
  src/metabase/driver/sql_jdbc/connection.clj
  test/metabase/test/data/impl.clj
  test_resources/ssl/oracle/README.md
  test_resources/ssl/oracle/keystore.p12
  test_resources/ssl/oracle/truststore.p12
Labels: Type:Tech Debt, .CI & Tests

#27450 Revert "[CI] Add concurrency to BE and FE workflows (#27235)"
  .github/workflows/backend.yml
  .github/workflows/drivers.yml
  .github/workflows/frontend.yml
Labels: Type:Tech Debt, .CI & Tests

#27451 Revert conditional `concurrency` attempt
  .github/workflows/backend.yml
  .github/workflows/drivers.yml
  .github/workflows/frontend.yml
Labels: Type:Tech Debt

#27457 Repro #19373: Pivot table returns wrong (distinct) row totals
  frontend/test/metabase/scenarios/visualizations/reproductions/19373-pivot-wrong-distinct-value-totals.cy.spec.js
Labels: .CI & Tests, support/Repro

#27459 Repro #18770: Post-aggregation filter disrupts drill-through
  frontend/test/metabase/scenarios/filters/reproductions/18770-post-aggregation-filter-disrupts-drillthrough.cy.spec.js
Labels: .CI & Tests, support/Repro

#27460 Repro #25250: Pivot Table doesn't show stand-alone values on collapsed sub-level grouping
  frontend/test/metabase/scenarios/visualizations/reproductions/25250-pivot-no-standalone-values-when-collapsed.cy.spec.js
Labels: .CI & Tests, support/Repro

#27461 🍒 Backport reproductions from 2022-12-28 and 2022-12-29
  frontend/test/metabase/scenarios/filters/reproductions/18770-post-aggregation-filter-disrupts-drillthrough.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/19373-pivot-wrong-distinct-value-totals.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/25250-pivot-no-standalone-values-when-collapsed.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/27427-static-viz-divide-by-zero.cy.spec.js
Labels: auto-backported

#27465 Fix flaky metabase.api.notify-test/post-db-id-test
  src/metabase/api/notify.clj
  test/metabase/api/notify_test.clj
Labels: flaky-test-fix
