Repository metabase/metabase, pull requests merged in 2022-09, with the labels that each got.

#25160 [E2E] Skip test that manually adds H2 database
  frontend/test/metabase/scenarios/question/new.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#25140 Fix how weeks are displayed in tooltips for native questions
  frontend/src/metabase/visualizations/lib/apply_axis.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/25007-week-tooltip-native.cy.spec.js
Labels: support/Repro, backport

#25159 docs - public link update
  docs/README.md
  docs/questions/images/enable-links.png
  docs/questions/images/public-export.png
  docs/questions/sharing/public-links.md
Labels: Type:Documentation, backport

#25164 Fix incorrect bubble size for multi-series
  frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js
Labels: backport

#25163 Really use the alternate names for the release container
  .github/workflows/release.yml
Labels: backport

#25009 Pie chart labels
  frontend/src/metabase/lib/colors/index.ts
  frontend/src/metabase/lib/colors/palette.ts
  frontend/src/metabase/visualizations/components/ChartWithLegend.css
  frontend/src/metabase/visualizations/visualizations/PieChart/PieArc.styled.tsx
  frontend/src/metabase/visualizations/visualizations/PieChart/PieArc.tsx
  frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.css
  frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.jsx
  frontend/src/metabase/visualizations/visualizations/PieChart/index.ts
  frontend/src/metabase/visualizations/visualizations/PieChart/utils.ts
  frontend/test/metabase-visual/visualizations/pie.cy.spec.js
Labels: visual

#25182 Add a preferred colors for cancelled
  frontend/src/metabase/lib/colors/groups.ts
Labels: backport

#25184 🍒 [E2E] Skip test that manually adds H2 database (#25160)
  frontend/test/metabase/scenarios/question/new.cy.spec.js
Labels: auto-backported

#25179 [E2E] Handle #17450 failures
  frontend/test/metabase/scenarios/admin/databases/add-external.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#25193 [E2E] Refactor repro for #21597
  frontend/test/metabase/scenarios/native/reproductions/21597-query-build-card-save-modal.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#25199 Really use the alternate names for the release container
  .github/workflows/release.yml
Labels: auto-backported

#25211 Upstream the compressed images from the docs
  docs/configuring-metabase/images/AccountSetup.png
  docs/configuring-metabase/images/AddDatabase.png
  docs/configuring-metabase/images/AddDatabaseInfo.png
  docs/configuring-metabase/images/EmailCredentials.png
  docs/configuring-metabase/images/MapSettings.png
  docs/configuring-metabase/images/NewsletterSignup.png
  docs/configuring-metabase/images/chart-colors.png
  docs/configuring-metabase/images/metabot.png
  docs/configuring-metabase/images/user-interface-colors.png
  docs/questions/images/enable-links.png
  docs/questions/images/public-export.png
Labels: Type:Documentation, backport

#25067 Handle env settings in batch form
  frontend/src/metabase/admin/settings/components/SettingsBatchForm.jsx
  frontend/src/metabase/admin/settings/components/SettingsSetting.jsx
  frontend/src/metabase/admin/settings/components/SettingsSetting.styled.tsx
  src/metabase/api/email.clj
  test/metabase/api/email_test.clj
Labels: backport

#25207 Fix loading the saved questions db for the first question
  frontend/src/metabase/query_builder/actions/core/core.js
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx
  frontend/test/metabase/scenarios/question/reproductions/25144-saved-questions-first-question.cy.spec.js
Labels: support/Repro, backport

#25230 [Manual backport] Fix loading the saved questions virtual db
  frontend/src/metabase/query_builder/actions/core/core.js
  frontend/src/metabase/query_builder/components/DataSelector.jsx
  frontend/test/metabase/scenarios/question/reproductions/25144-saved-questions-first-question.cy.spec.js
Labels: auto-backported

#25229 [Manual backport] Fix env settings in email form
  frontend/src/metabase/admin/settings/components/SettingsBatchForm.jsx
  frontend/src/metabase/admin/settings/components/SettingsSetting.jsx
  frontend/src/metabase/admin/settings/components/SettingsSetting.styled.tsx
  src/metabase/api/email.clj
  test/metabase/api/email_test.clj
Labels: auto-backported

#24991 Removed redundant check on searchable parameter fields
  frontend/src/metabase/components/FieldValuesWidget.jsx
  frontend/test/metabase/components/FieldValuesWidget.unit.spec.js
Labels: backport

#25170 Fix boolean fields for public questions
  frontend/src/metabase/public/containers/PublicQuestion.jsx
Labels: backport

#25167 Revert "Fix data selector trigger wrapping"
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx
Labels: backport

#25242 [Manual backport] Fix updating filters in the filter header
  frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.tsx
  frontend/test/metabase/scenarios/filters/reproductions/24994-update-filters.cy.spec.js
Labels: auto-backported

#25177 docs - readme structure
  docs/README.md
  docs/api/premium-features.md
Labels: Type:Documentation, backport

#25216 Fix condtional to properly render multi-line charts in static-viz
  src/metabase/pulse/render.clj
  test/metabase/pulse/render_test.clj
Labels: visual

#25259 Fix filters not working for columns in multi-stage queries
  frontend/src/metabase-lib/lib/Dimension.ts
  frontend/src/metabase-lib/lib/queries/StructuredQuery.ts
  frontend/src/metabase/modes/components/drill/ColumnFilterDrill.jsx
  frontend/src/metabase/visualizations/lib/table.js
  frontend/test/metabase/scenarios/question/reproductions/25016-column-filter-multi-stage-query.cy.spec.js
Labels: backport

#25290 docs - readme titles
  docs/README.md
  docs/configuring-metabase/email.md
  docs/configuring-metabase/slack.md
  docs/configuring-metabase/start.md
  docs/configuring-metabase/timezones.md
  docs/data-modeling/field-types.md
  docs/data-modeling/formatting.md
  docs/data-modeling/metadata-editing.md
  docs/data-modeling/segments-and-metrics.md
  docs/data-modeling/start.md
  docs/databases/encrypting-details-at-rest.md
  docs/databases/ssh-tunnel.md
  docs/databases/ssl-certificates.md
  docs/embedding/full-app-embedding.md
  docs/embedding/introduction.md
  docs/exploration-and-organization/exploration.md
  docs/exploration-and-organization/start.md
  docs/installation-and-operation/java-versions.md
  docs/installation-and-operation/migrating-from-h2.md
  docs/installation-and-operation/serialization.md
  docs/installation-and-operation/start.md
  docs/people-and-groups/authenticating-with-saml.md
  docs/people-and-groups/changing-password-complexity.md
  docs/people-and-groups/changing-session-expiration.md
  docs/people-and-groups/google-and-ldap.md
  docs/people-and-groups/saml-auth0.md
  docs/people-and-groups/saml-azure.md
  docs/people-and-groups/saml-google.md
  docs/people-and-groups/saml-keycloak.md
  docs/people-and-groups/saml-okta.md
  docs/people-and-groups/start.md
  docs/permissions/introduction.md
  docs/permissions/snippets.md
  docs/permissions/start.md
  docs/questions/native-editor/referencing-saved-questions-in-queries.md
  docs/questions/native-editor/sql-parameters.md
  docs/questions/query-builder/expressions.md
  docs/questions/sharing/alerts.md
  docs/questions/sharing/public-links.md
  docs/questions/sharing/visualizing-results.md
  docs/questions/start.md
  docs/troubleshooting-guide/cant-view-or-edit.md
  docs/troubleshooting-guide/index.md
  docs/usage-and-performance-tools/audit.md
  docs/usage-and-performance-tools/start.md
Labels: Type:Documentation, backport

#25285 Fix Chinese weekdays localization
  frontend/src/metabase/components/Calendar.tsx
  locales/zh.po
Labels: backport

#25298 docs - update references to jar files
  docs/databases/connections/postgresql.md
  docs/databases/ssl-certificates.md
  docs/installation-and-operation/configuring-application-database.md
  docs/installation-and-operation/running-the-metabase-jar-file.md
  docs/installation-and-operation/upgrading-metabase.md
  docs/paid-features/activating-the-enterprise-edition.md
Labels: Type:Documentation, backport

#25311 docs - fix links
  docs/installation-and-operation/upgrading-metabase.md
Labels: Type:Documentation, backport

#25198 [Apps] Allow extra parameters to be passed to action execution
  src/metabase/actions/execution.clj
  src/metabase/api/dashboard.clj
  test/metabase/actions/test_util.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/emitter_test.clj
Labels: .Backend, Actions/

#25296 [Apps] Hide is_write cards from collection items
  src/metabase/api/collection.clj
  test/metabase/api/collection_test.clj
Labels: .Backend, Actions/

#25313 docs - matching titles
  docs/README.md
  docs/api-documentation.md
  docs/installation-and-operation/backing-up-metabase-application-data.md
  docs/people-and-groups/saml-okta.md
Labels: Type:Documentation, backport

#25314 [Apps] Prototype backend app scaffolding
  src/metabase/api/app.clj
  src/metabase/api/card.clj
  test/metabase/api/app_test.clj
Labels: .Backend, Actions/

#25316 docs - add frontmatter to API doc page
  src/metabase/cmd/resources/api-intro.md
Labels: Type:Documentation, backport

#25332 docs - update docker quick starts
  docs/installation-and-operation/running-metabase-on-docker.md
Labels: Type:Documentation, backport

#25299 Fix issues with postgres PKCS-12 SSL connections
  src/metabase/driver/postgres.clj
  src/metabase/models/secret.clj
  test/metabase/driver/postgres_test.clj
Labels: backport

#25339 docs - timezones
  docs/configuring-metabase/timezones.md
Labels: Type:Documentation, backport

#25325 Add data point values E2E tests
  frontend/src/metabase/static-viz/components/XYChart/Values/Values.tsx
  frontend/test/metabase-visual/static-visualizations/line-area-bar-combo.cy.spec.js
Labels: visual

#25353 Add a description for slack channel form field
  frontend/src/metabase/admin/settings/slack/components/SlackStatusForm/SlackStatusForm.tsx
  frontend/src/metabase/admin/settings/slack/components/SlackStatusForm/types.ts
Labels: backport

#25355 Fix parameter mapping for multi-series cards
  frontend/src/metabase/dashboard/selectors.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/25355-multi-series-parameter-mapping.cy.spec.js
Labels: support/Repro, backport

#25358 docs - fix links
  docs/configuring-metabase/appearance.md
  docs/configuring-metabase/fonts.md
  docs/troubleshooting-guide/my-dashboard-is-slow.md
Labels: Type:Documentation, backport

#25360 [Manual backport] Add a description for slack channel form field
  frontend/src/metabase/admin/settings/slack/components/SlackStatusForm/SlackStatusForm.tsx
  frontend/src/metabase/admin/settings/slack/components/SlackStatusForm/types.ts
Labels: auto-backported

#25367 [Apps] exclude is_write cards from virtual tables
  src/metabase/api/database.clj
  test/metabase/api/database_test.clj
Labels: .Backend, Actions/

#25387 docs - update expressions-list.md
  docs/questions/query-builder/expressions-list.md
Labels: Type:Documentation, backport

#25369 H2 disallow `INIT=...` option using connection string
  src/metabase/driver/h2.clj
Labels: backport

#25342 docs - update api/dataset comment
  docs/developers-guide/docs.md
  src/metabase/api/dataset.clj
Labels: backport

#25396 docs - update README.md
  docs/README.md
Labels: Type:Documentation, backport

#25343 [Apps] Add scaffolded pages to existing apps
  frontend/src/metabase-types/api/click-behavior.ts
  frontend/src/metabase/containers/DataAppPagePicker.jsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/LinkOptions/LinkOptions.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/LinkOptions/LinkedEntityPicker.tsx
  frontend/src/metabase/lib/click-behavior.js
  frontend/src/metabase/modes/components/drill/DashboardClickDrill.jsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorFieldPicker/DataSelectorFieldPicker.unit.spec.tsx
  frontend/src/metabase/visualizations/hoc/WithVizSettingsData.js
  src/metabase/api/app.clj
  test/metabase/api/app_test.clj
Labels: .Backend, Actions/

#25386 Handle the session storage error when saving a location state
  frontend/src/metabase/query_builder/actions/navigation.js
Labels: backport

#24696 Coerce all the static viz charts that could be a combo to be a combo
  src/metabase/pulse/render.clj
  src/metabase/pulse/render/body.clj
  src/metabase/pulse/render/js_svg.clj
  src/metabase/pulse/render/sparkline.clj
  test/metabase/pulse/render/body_test.clj
  test/metabase/pulse/render/js_svg_test.clj
  test/metabase/pulse/render/sparkline_test.clj
Labels: visual

#25435 docs - community drivers
  docs/developers-guide/partner-and-community-drivers.md
Labels: Type:Documentation, backport

#25440 remove unused static chart types
  frontend/src/metabase/internal/pages/StaticVizPage.jsx
  frontend/src/metabase/static-viz/components/CategoricalAreaChart/CategoricalAreaChart.jsx
  frontend/src/metabase/static-viz/components/CategoricalAreaChart/constants.ts
  frontend/src/metabase/static-viz/components/CategoricalAreaChart/index.js
  frontend/src/metabase/static-viz/components/CategoricalBarChart/CategoricalBarChart.jsx
  frontend/src/metabase/static-viz/components/CategoricalBarChart/constants.ts
  frontend/src/metabase/static-viz/components/CategoricalBarChart/index.js
  frontend/src/metabase/static-viz/components/CategoricalLineChart/CategoricalLineChart.jsx
  frontend/src/metabase/static-viz/components/CategoricalLineChart/constants.ts
  frontend/src/metabase/static-viz/components/CategoricalLineChart/index.js
  frontend/src/metabase/static-viz/components/TimeSeriesAreaChart/TimeSeriesAreaChart.jsx
  frontend/src/metabase/static-viz/components/TimeSeriesAreaChart/constants.ts
  frontend/src/metabase/static-viz/components/TimeSeriesAreaChart/index.js
  frontend/src/metabase/static-viz/components/TimeSeriesBarChart/TimeSeriesBarChart.jsx
  frontend/src/metabase/static-viz/components/TimeSeriesBarChart/constants.ts
  frontend/src/metabase/static-viz/components/TimeSeriesBarChart/index.js
  frontend/src/metabase/static-viz/components/TimeSeriesLineChart/TimeSeriesLineChart.jsx
  frontend/src/metabase/static-viz/components/TimeSeriesLineChart/constants.ts
  frontend/src/metabase/static-viz/components/TimeSeriesLineChart/index.js
  frontend/src/metabase/static-viz/containers/StaticChart/StaticChart.tsx
  frontend/src/metabase/static-viz/containers/StaticChart/StaticChart.unit.spec.js
  frontend/src/metabase/static-viz/containers/StaticChart/constants.ts
  frontend/test/metabase-visual/static-visualizations/line-area-bar-combo.cy.spec.js
  resources/frontend_shared/static_viz_interface.js
Labels: visual

#25444 docs - update "manage database" permission
  docs/permissions/data.md
Labels: Type:Documentation, backport

#25466 docs - remove tables of contents
  docs/configuring-metabase/email.md
  docs/configuring-metabase/slack.md
  docs/databases/connecting.md
  docs/databases/encrypting-details-at-rest.md
  docs/databases/ssh-tunnel.md
  docs/installation-and-operation/running-metabase-on-azure.md
  docs/installation-and-operation/running-metabase-on-docker.md
  docs/installation-and-operation/running-the-metabase-jar-file.md
  docs/people-and-groups/account-settings.md
  docs/people-and-groups/saml-azure.md
  docs/people-and-groups/saml-okta.md
  docs/permissions/application.md
  docs/troubleshooting-guide/datawarehouse.md
  docs/troubleshooting-guide/docker.md
  docs/troubleshooting-guide/error-message.md
  docs/troubleshooting-guide/known-issues.md
  docs/troubleshooting-guide/ldap.md
  docs/troubleshooting-guide/models.md
  docs/troubleshooting-guide/proxies.md
  docs/troubleshooting-guide/running.md
  docs/troubleshooting-guide/sync-fingerprint-scan.md
Labels: Type:Documentation, backport

#25426 docs - update full-app embedding
  docs/embedding/full-app-embedding.md
  docs/embedding/images/01-enabling.png
  docs/embedding/images/action-menu.png
  docs/embedding/introduction.md
  docs/embedding/signed-embedding-parameters.md
  docs/embedding/signed-embedding.md
  docs/embedding/start.md
Labels: Type:Documentation, backport

#25470 docs - manual backport to remove artisanal tocs
  docs/configuring-metabase/email.md
  docs/configuring-metabase/slack.md
  docs/databases/connecting.md
  docs/databases/encrypting-details-at-rest.md
  docs/databases/ssh-tunnel.md
  docs/installation-and-operation/running-metabase-on-azure.md
  docs/installation-and-operation/running-metabase-on-docker.md
  docs/installation-and-operation/running-the-metabase-jar-file.md
  docs/people-and-groups/account-settings.md
  docs/people-and-groups/saml-azure.md
  docs/people-and-groups/saml-okta.md
  docs/permissions/application.md
  docs/troubleshooting-guide/datawarehouse.md
  docs/troubleshooting-guide/docker.md
  docs/troubleshooting-guide/error-message.md
  docs/troubleshooting-guide/known-issues.md
  docs/troubleshooting-guide/ldap.md
  docs/troubleshooting-guide/models.md
  docs/troubleshooting-guide/proxies.md
  docs/troubleshooting-guide/running.md
  docs/troubleshooting-guide/sync-fingerprint-scan.md
Labels: Type:Documentation

#25489 [E2E] Fix flaking models metadata test
  frontend/test/metabase/scenarios/models/models-metadata.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#25504 Manual backport for #25161
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/App.tsx
  frontend/src/metabase/components/AppBanner.jsx
  frontend/src/metabase/lib/settings.ts
  frontend/src/metabase/selectors/app.ts
  frontend/test/metabase/scenarios/admin/subscription/payment-failure.cy.spec.js
  src/metabase/api/premium_features.clj
  src/metabase/public_settings/premium_features.clj
  test/metabase/public_settings/premium_features_test.clj
Labels: auto-backported

#25180 🍒 [E2E] Consolidate `question` (#24733)
  frontend/test/metabase/scenarios/onboarding/home/browse.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/navbar/new-menu.cy.spec.js
  frontend/test/metabase/scenarios/question/loading.cy.spec.js
  frontend/test/metabase/scenarios/question/new.cy.spec.js
  frontend/test/metabase/scenarios/question/saved.cy.spec.js
  frontend/test/metabase/scenarios/question/summarization.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/16108-missing-tooltip.cy.spec.js
Labels: auto-backported

#25513 docs - remove generated api doc tables of contents
  docs/api-documentation.md
  docs/api/action.md
  docs/api/activity.md
  docs/api/alert.md
  docs/api/app.md
  docs/api/automagic-dashboards.md
  docs/api/bookmark.md
  docs/api/card.md
  docs/api/collection.md
  docs/api/dashboard.md
  docs/api/database.md
  docs/api/dataset.md
  docs/api/ee/advanced-permissions-application.md
  docs/api/ee/audit-app-user.md
  docs/api/ee/content-management-review.md
  docs/api/ee/sandbox-gtap.md
  docs/api/ee/sandbox-table.md
  docs/api/ee/sandbox-user.md
  docs/api/ee/sso.md
  docs/api/email.md
  docs/api/embed.md
  docs/api/emitter.md
  docs/api/field.md
  docs/api/geojson.md
  docs/api/ldap.md
  docs/api/login-history.md
  docs/api/metric.md
  docs/api/native-query-snippet.md
  docs/api/notify.md
  docs/api/permissions.md
  docs/api/persist.md
  docs/api/premium-features.md
  docs/api/preview-embed.md
  docs/api/public.md
  docs/api/pulse.md
  docs/api/revision.md
  docs/api/search.md
  docs/api/segment.md
  docs/api/session.md
  docs/api/setting.md
  docs/api/setup.md
  docs/api/slack.md
  docs/api/table.md
  docs/api/task.md
  docs/api/tiles.md
  docs/api/timeline-event.md
  docs/api/timeline.md
  docs/api/transform.md
  docs/api/user.md
  docs/api/util.md
  src/metabase/cmd/endpoint_dox.clj
  src/metabase/cmd/resources/api-intro.md
  test/metabase/cmd/endpoint_dox_test.clj
Labels: Type:Documentation

#25522 docs - manual backport of api docs
  docs/api-documentation.md
  docs/api/activity.md
  docs/api/alert.md
  docs/api/automagic-dashboards.md
  docs/api/bookmark.md
  docs/api/card.md
  docs/api/collection.md
  docs/api/dashboard.md
  docs/api/database.md
  docs/api/dataset.md
  docs/api/ee/advanced-permissions-application.md
  docs/api/ee/audit-app-user.md
  docs/api/ee/content-management-review.md
  docs/api/ee/sandbox-gtap.md
  docs/api/ee/sandbox-table.md
  docs/api/ee/sandbox-user.md
  docs/api/ee/sso.md
  docs/api/email.md
  docs/api/embed.md
  docs/api/field.md
  docs/api/geojson.md
  docs/api/ldap.md
  docs/api/login-history.md
  docs/api/metric.md
  docs/api/native-query-snippet.md
  docs/api/notify.md
  docs/api/permissions.md
  docs/api/persist.md
  docs/api/premium-features.md
  docs/api/preview-embed.md
  docs/api/public.md
  docs/api/pulse.md
  docs/api/revision.md
  docs/api/search.md
  docs/api/segment.md
  docs/api/session.md
  docs/api/setting.md
  docs/api/setup.md
  docs/api/slack.md
  docs/api/table.md
  docs/api/task.md
  docs/api/tiles.md
  docs/api/timeline-event.md
  docs/api/timeline.md
  docs/api/transform.md
  docs/api/user.md
  docs/api/util.md
  src/metabase/cmd/endpoint_dox.clj
  src/metabase/cmd/resources/api-intro.md
  test/metabase/cmd/endpoint_dox_test.clj
Labels: Type:Documentation

#25527 docs - update api-intro.md
  src/metabase/cmd/resources/api-intro.md
Labels: Type:Documentation

#25518 [E2E] Unskip quarantined test due to #24900
  frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#25541 [E2E] Unskip repro for #12489
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#25545 Fix models picker not working for non-english locale
  frontend/src/metabase/lib/saved-questions/saved-questions.js
  frontend/src/metabase/query_builder/components/DataSelector/saved-question-picker/SavedQuestionPicker.jsx
  frontend/test/metabase/scenarios/models/reproductions/25537-model-picker-locale.cy.spec.js
Labels: support/Repro, backport

#25520 docs - troubleshooting visualizations
  docs/configuring-metabase/custom-maps.md
  docs/dashboards/introduction.md
  docs/troubleshooting-guide/cant-see-tables.md
  docs/troubleshooting-guide/cant-view-or-edit.md
  docs/troubleshooting-guide/index.md
  docs/troubleshooting-guide/my-dashboard-is-slow.md
  docs/troubleshooting-guide/visualization.md
Labels: Type:Documentation, backport

#25549 [Apps] Update scaffold after FE change
  src/metabase/api/app.clj
Labels: .Backend, Actions/

#25558 docs - update README.md
  docs/README.md
Labels: Type:Documentation, backport

#25553 docs - update locked parameters
  docs/embedding/signed-embedding-parameters.md
Labels: Type:Documentation, backport

#25568 Fix popover offset in dashboards
  frontend/src/metabase/parameters/components/ParameterValueWidget.jsx
Labels: backport

#25548 Bump Apache Mina SSHD and Postgres driver
  deps.edn
Labels: backport

#25561 Allow disabling custom GeoJSON via env var
  docs/configuring-metabase/environment-variables.md
  src/metabase/api/geojson.clj
  test/metabase/api/geojson_test.clj
Labels: backport

#25427 Handle bigint and boolean casts in mysql json unwrapping
  src/metabase/driver/mysql.clj
  test/metabase/driver/mysql_test.clj
Labels: backport

#25195 [E2E] Cross-version initial dataset
  frontend/test/metabase/scenarios/cross-version/source/00-setup.cy.spec.js
  frontend/test/metabase/scenarios/cross-version/source/01-generate-metadata.cy.spec.js
  frontend/test/metabase/scenarios/cross-version/source/02-datamodel.cy.spec.js
  frontend/test/metabase/scenarios/cross-version/source/03-questions.cy.spec.js
  frontend/test/metabase/scenarios/cross-version/target/smoke.cy.spec.js
Labels: .CI & Tests

#25569 Fix native editor parameters layout for desktop
  frontend/src/metabase/query_builder/components/ResponsiveParametersList.styled.tsx
  frontend/src/metabase/query_builder/components/ResponsiveParametersList.tsx
Labels: backport

#25540 Fix FieldValuesWidget not showing spinner when loading list values
  frontend/src/metabase/components/FieldValuesWidget.jsx
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/25322-loading-list-values.cy.spec.js
Labels: support/Repro, backport

#25483 Fix inconsistent left y-axis padding
  frontend/src/metabase/static-viz/components/LineAreaBarChart/LineAreaBarChart.tsx
  frontend/src/metabase/static-viz/components/XYChart/XYChart.tsx
  frontend/src/metabase/static-viz/components/XYChart/constants.ts
  frontend/src/metabase/static-viz/components/XYChart/utils/margin.ts
  frontend/src/metabase/static-viz/components/XYChart/utils/ticks.ts
Labels: visual

#25596 [Manual backport] Fix FieldValuesWidget not showing spinner when loading list values
  frontend/src/metabase/components/FieldValuesWidget.jsx
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/25322-loading-list-values.cy.spec.js
Labels: auto-backported

#25591 docs - database troubles
  docs/databases/connecting.md
  docs/databases/connections/bigquery.md
  docs/databases/connections/mongodb.md
  docs/troubleshooting-guide/bigquery-drive.md
  docs/troubleshooting-guide/cant-see-tables.md
  docs/troubleshooting-guide/db-connection.md
  docs/troubleshooting-guide/db-performance.md
  docs/troubleshooting-guide/error-message.md
  docs/troubleshooting-guide/index.md
  docs/troubleshooting-guide/my-dashboard-is-slow.md
  docs/troubleshooting-guide/sync-fingerprint-scan.md
  docs/troubleshooting-guide/timeout.md
Labels: Type:Documentation, backport

#25604 docs - correction
  docs/databases/connecting.md
  docs/troubleshooting-guide/db-performance.md
Labels: Type:Documentation, backport

#25608 docs - google sign-in
  docs/people-and-groups/google-and-ldap.md
Labels: Type:Documentation, backport

#25607 Change the copy about not supporting PKCS-12 officially
  docs/databases/connections/postgresql.md
  frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js
  src/metabase/driver/postgres.clj
Labels: backport

#25620 docs - update headings and links
  README.md
  docs/README.md
  docs/api-documentation.md
  docs/configuring-metabase/start.md
  docs/configuring-metabase/timezones.md
  docs/databases/connecting.md
  docs/installation-and-operation/privacy.md
  docs/installation-and-operation/running-metabase-on-docker.md
  docs/installation-and-operation/running-the-metabase-jar-file.md
  docs/paid-features/activating-the-enterprise-edition.md
  docs/paid-features/overview.md
  docs/people-and-groups/managing.md
  docs/troubleshooting-guide/cant-log-in.md
  src/metabase/cmd/resources/api-intro.md
Labels: Type:Documentation, backport

#25623 docs - backport readme headings
  README.md
  docs/README.md
  docs/api-documentation.md
  docs/configuring-metabase/start.md
  docs/configuring-metabase/timezones.md
  docs/databases/connecting.md
  docs/installation-and-operation/running-metabase-on-docker.md
  docs/installation-and-operation/running-the-metabase-jar-file.md
  docs/installation-and-operation/start.md
  docs/paid-features/overview.md
  docs/people-and-groups/managing.md
  docs/troubleshooting-guide/cant-log-in.md
  src/metabase/cmd/resources/api-intro.md
Labels: Type:Documentation

#25626 update anchor link
  docs/permissions/data.md
Labels: Type:Documentation, backport

#25542 Do not allow to enter an empty relative time interval
  frontend/src/metabase/lib/time.ts
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/RelativeDatePicker.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/RelativeDatePicker.unit.spec.tsx
  frontend/test/metabase/lib/time.unit.spec.js
Labels: backport

#25634 docs - remove extra slash
  docs/configuring-metabase/timezones.md
  docs/people-and-groups/managing.md
  docs/troubleshooting-guide/cant-log-in.md
Labels: Type:Documentation

#25632 Remove unneeded and unused import
  enterprise/frontend/src/metabase-enterprise/application_permissions/api.js
Labels: Type:Tech Debt, .Frontend

#25560 Waterfall data point values
  frontend/src/metabase/internal/pages/StaticVizPage.jsx
  frontend/src/metabase/static-viz/components/CategoricalWaterfallChart/CategoricalWaterfallChart.jsx
  frontend/src/metabase/static-viz/components/CategoricalWaterfallChart/constants.ts
  frontend/src/metabase/static-viz/components/CategoricalWaterfallChart/index.js
  frontend/src/metabase/static-viz/components/TimeSeriesWaterfallChart/TimeSeriesWaterfallChart.jsx
  frontend/src/metabase/static-viz/components/TimeSeriesWaterfallChart/constants.ts
  frontend/src/metabase/static-viz/components/TimeSeriesWaterfallChart/index.js
  frontend/src/metabase/static-viz/components/Values/Values.tsx
  frontend/src/metabase/static-viz/components/Values/index.ts
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.jsx
  frontend/src/metabase/static-viz/components/WaterfallChart/constants.ts
  frontend/src/metabase/static-viz/components/WaterfallChart/index.js
  frontend/src/metabase/static-viz/components/WaterfallChart/types.ts
  frontend/src/metabase/static-viz/components/XYChart/XYChart.tsx
  frontend/src/metabase/static-viz/components/XYChart/types.ts
  frontend/src/metabase/static-viz/components/XYChart/utils/scales.ts
  frontend/src/metabase/static-viz/components/XYChart/utils/series.ts
  frontend/src/metabase/static-viz/components/XYChart/utils/ticks.ts
  frontend/src/metabase/static-viz/containers/StaticChart/StaticChart.tsx
  frontend/src/metabase/static-viz/containers/StaticChart/constants.ts
  frontend/src/metabase/static-viz/lib/axes.js
  frontend/src/metabase/static-viz/lib/axes.unit.spec.js
  frontend/src/metabase/static-viz/lib/waterfall.js
  frontend/test/metabase-visual/static-visualizations/waterfall.cy.spec.js
  resources/frontend_shared/static_viz_interface.js
  src/metabase/pulse/render/body.clj
  src/metabase/pulse/render/js_svg.clj
  test/metabase/pulse/render/js_svg_test.clj
Labels: visual

#25642 docs - remove trailing slashes from links
  LICENSE-MCL.txt
  LICENSE.txt
  README.md
  docs/configuring-metabase/setting-up-metabase.md
  docs/developers-guide/partner-and-community-drivers.md
  docs/people-and-groups/managing.md
  docs/people-and-groups/start.md
  docs/usage-and-performance-tools/start.md
  enterprise/LICENSE.txt
  enterprise/README.md
Labels: Type:Documentation, backport

#25639 docs - concat
  docs/questions/query-builder/expressions-list.md
  docs/questions/query-builder/expressions/case.md
  docs/questions/query-builder/expressions/coalesce.md
  docs/questions/query-builder/expressions/concat.md
  docs/questions/query-builder/expressions/isempty.md
  docs/questions/query-builder/expressions/isnull.md
Labels: Type:Documentation, backport

#25671 Fix validation for the saml form
  enterprise/frontend/src/metabase-enterprise/auth/components/SettingsSAMLForm.jsx
Labels: backport

#25630 [E2E] Add `@external` tag to tests that depend on Docker images
  docs/developers-guide/e2e-tests.md
  frontend/test/metabase-visual/static-visualizations/funnel.cy.spec.js
  frontend/test/metabase-visual/static-visualizations/line-area-bar-combo.cy.spec.js
  frontend/test/metabase-visual/static-visualizations/progress-bar.cy.spec.js
  frontend/test/metabase-visual/static-visualizations/waterfall.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/add-external.cy.spec.js
  frontend/test/metabase/scenarios/admin/people/people.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/cache.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/email.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/sso/ldap.cy.spec.js
  frontend/test/metabase/scenarios/auditing/approved-domains.cy.spec.js
  frontend/test/metabase/scenarios/custom-column/reproductions/12445-cc-mysql-apply-substring.cy.spec.js
  frontend/test/metabase/scenarios/custom-column/reproductions/13751-cc-allow-strings-in-filter.cy.spec.js
  frontend/test/metabase/scenarios/custom-column/reproductions/14517-cc-do-not-remove-regex-escape-chars.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/20683-postgres-current-quarter.cy.spec.js
  frontend/test/metabase/scenarios/joins/reproductions/15342-mysql-correct-joins-order.cy.spec.js
  frontend/test/metabase/scenarios/native/native-mongo.cy.spec.js
  frontend/test/metabase/scenarios/native/native-mysql.cy.spec.js
  frontend/test/metabase/scenarios/native/reproductions/15946-mongo-pre-select-table.cy.spec.js
  frontend/test/metabase/scenarios/native/reproductions/21597-query-build-card-save-modal.cy.spec.js
  frontend/test/metabase/scenarios/native/reproductions/22822-explore-results-unsupported-databases.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/auth/forgot_password.cy.spec.js
  frontend/test/metabase/scenarios/permissions/reproductions/13347-cannot-select-saved-question-in-database-without-data-permissions.cy.spec.js
  frontend/test/metabase/scenarios/permissions/reproductions/14873-regextract-in-sandboxed-table.cy.spec.js
  frontend/test/metabase/scenarios/permissions/sandboxes.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/13097-mongo-apply-distinct-count-multiple-columns.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/13263-postgres-show-row-details-on-pk-click.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/14957-unable-to-save-question-before-query-executed.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/15714-cc-postgres-percentile-accepts-two-params.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/15876-postgres-cast-time.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/17963-mongo-filter-expression-compare-two-fields.cy.spec.js
  frontend/test/metabase/scenarios/sharing/alert/alert-permissions.cy.spec.js
  frontend/test/metabase/scenarios/sharing/alert/alert-types.cy.spec.js
  frontend/test/metabase/scenarios/sharing/alert/alert.cy.spec.js
  frontend/test/metabase/scenarios/sharing/alert/email-alert.cy.spec.js
  frontend/test/metabase/scenarios/sharing/approved-domains.cy.spec.js
  frontend/test/metabase/scenarios/sharing/pulse.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/17658.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/18009-nodata-creates-subscription-receives-error.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/18344-subscription-shows-original-question-name.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/18352-subscription-int64-value-card.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/18669-test-email-with-parameters.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/21559-subscription-bar-sent-as-scalar.cy.spec.js
  frontend/test/metabase/scenarios/sharing/subscriptions.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/11727-cancel-native-query-shortcut.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/14148-pivot-table-postgres.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/16170-line-mongo-replace-missing-values.cy.spec.js
  frontend/test/snapshot-creators/qa-db.cy.snap.js
Labels: Type:Tech Debt, .CI & Tests, backport

#25619 Manual backport #24896
  src/metabase/query_processor/middleware/annotate.clj
  src/metabase/query_processor/util.clj
  test/metabase/query_processor/middleware/annotate_test.clj
  test/metabase/query_processor_test/nested_queries_test.clj
Labels: auto-backported

#25676 docs - add metabase expert links
  README.md
  docs/README.md
  docs/configuring-metabase/setting-up-metabase.md
  docs/installation-and-operation/upgrading-metabase.md
  docs/troubleshooting-guide/db-connection.md
Labels: backport

#25677 docs - manual backport of add expert links
  README.md
  docs/README.md
  docs/configuring-metabase/setting-up-metabase.md
  docs/installation-and-operation/upgrading-metabase.md
  docs/troubleshooting-guide/db-connection.md
Labels: Type:Documentation

#25673 Fix login form when ldap is enabled but password login is disabled
  enterprise/frontend/src/metabase-enterprise/auth/index.js
Labels: auto-backported

#25668 Remove website update from the release script (#25647)
  bin/release/src/release.clj
  bin/release/src/release/update_website.clj
Labels: auto-backported

#25683 docs - more expert links
  docs/README.md
  docs/installation-and-operation/installing-metabase.md
  docs/installation-and-operation/start.md
Labels: Type:Documentation, backport

#25686 update README.md
  README.md
  docs/installation-and-operation/installing-metabase.md
  docs/installation-and-operation/start.md
  docs/installation-and-operation/upgrading-metabase.md
Labels: Type:Documentation, backport

#25665 Upgrade Cypress to `v10.9.0`
  frontend/test/__runner__/cypress-runner-generate-snapshots.js
  frontend/test/__runner__/cypress-runner-run-tests.js
  frontend/test/__support__/e2e/config.js
  frontend/test/__support__/e2e/cypress-plugins.js
  frontend/test/__support__/e2e/cypress-snapshots.config.js
  frontend/test/__support__/e2e/cypress-snapshots.json
  frontend/test/__support__/e2e/cypress.config.js
  frontend/test/__support__/e2e/cypress.json
  package.json
  yarn.lock
Labels: Type:Tech Debt, .CI & Tests

#25667 docs - substring
  docs/questions/query-builder/expressions-list.md
  docs/questions/query-builder/expressions/substring.md
Labels: Type:Documentation, backport

#25688 docs - update api docs
  docs/api-documentation.md
  docs/api/google.md
  docs/api/permissions.md
Labels: Type:Documentation

#25690 docs - readme link update
  README.md
  docs/installation-and-operation/installing-metabase.md
  docs/installation-and-operation/start.md
  docs/installation-and-operation/upgrading-metabase.md
Labels: Type:Documentation

#25678 [E2E] Upgrade Cypress-related libraries
  package.json
  yarn.lock
Labels: Type:Tech Debt, .CI & Tests

#25573 Handle metric filters in drilldowns
  frontend/src/metabase-lib/lib/Question.ts
  frontend/src/metabase-lib/lib/metadata/Metadata.ts
  frontend/src/metabase-lib/lib/metadata/Metric.ts
  frontend/src/metabase-lib/lib/queries/structured/Aggregation.ts
  frontend/src/metabase/modes/components/drill/UnderlyingRecordsDrill.jsx
  frontend/src/metabase/modes/lib/actions.js
  frontend/test/__support__/sample_database_fixture.js
  frontend/test/__support__/sample_database_fixture.json
  frontend/test/metabase-lib/lib/Question.unit.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/6010-metric-filter-drill.cy.spec.js
Labels: support/Repro, backport

#25663 docs - add instructions to convert key to der
  docs/databases/connections/postgresql.md
Labels: Type:Documentation, backport

#25674 Fix login form when ldap is enabled but password login is disabled
  enterprise/frontend/src/metabase-enterprise/auth/index.js
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/people/containers/UserSuccessModal.jsx
  frontend/src/metabase/auth/components/PasswordButton/PasswordButton.tsx
  frontend/src/metabase/auth/components/PasswordButton/PasswordButton.unit.spec.tsx
  frontend/src/metabase/auth/containers/ForgotPasswordApp/ForgotPasswordApp.tsx
  frontend/src/metabase/auth/containers/PasswordButton/PasswordButton.tsx
  frontend/src/metabase/auth/containers/PasswordButton/index.ts
  frontend/src/metabase/entities/users/forms.js
  frontend/src/metabase/lib/settings.ts
  frontend/src/metabase/plugins/builtin/auth/password.js
  frontend/test/metabase/scenarios/admin/settings/sso/ldap.cy.spec.js
Labels: support/Repro

#25695 [Manual backport] Handle metric filters in drilldowns (#25573)
  frontend/src/metabase-lib/lib/Question.ts
  frontend/src/metabase-lib/lib/metadata/Metadata.ts
  frontend/src/metabase-lib/lib/metadata/Metric.ts
  frontend/src/metabase-lib/lib/queries/structured/Aggregation.ts
  frontend/src/metabase/modes/components/drill/UnderlyingRecordsDrill.jsx
  frontend/src/metabase/modes/lib/actions.js
  frontend/test/__support__/sample_database_fixture.js
  frontend/test/__support__/sample_database_fixture.json
  frontend/test/metabase-lib/lib/Question.unit.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/6010-metric-filter-drill.cy.spec.js
Labels: auto-backported

#25692 docs - add dev guide to readme sidebar section
  docs/README.md
  docs/developers-guide/start.md
Labels: Type:Documentation, backport

#25701 docs - update README
  README.md
Labels: Type:Documentation

#25710 Mysql persistence
  src/metabase/driver/mysql/ddl.clj
  test/metabase/analytics/prometheus_test.clj
  test/metabase/task/persist_refresh_test.clj
Labels: backport

#24751 Enable Kondo for tests part 3: enable deprecated var linter and fix warnings.
  .clj-kondo/config.edn
  enterprise/backend/test/metabase_enterprise/enhancements/api/collection_test.clj
  enterprise/backend/test/metabase_enterprise/enhancements/api/native_query_snippet_test.clj
  enterprise/backend/test/metabase_enterprise/enhancements/integrations/ldap_test.clj
  enterprise/backend/test/metabase_enterprise/pulse_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/card_test.clj
  enterprise/backend/test/metabase_enterprise/search/scoring_test.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj
  modules/drivers/druid/test/metabase/driver/druid/client_test.clj
  modules/drivers/oracle/test/metabase/driver/oracle_test.clj
  modules/drivers/presto-jdbc/test/metabase/driver/presto_jdbc_test.clj
  modules/drivers/presto/test/metabase/driver/presto_test.clj
  modules/drivers/sqlite/test/metabase/driver/sqlite_test.clj
  modules/drivers/vertica/test/metabase/driver/vertica_test.clj
  src/metabase/driver.clj
  src/metabase/driver/common.clj
  src/metabase/driver/sql_jdbc.clj
  src/metabase/driver/sql_jdbc/execute.clj
  src/metabase/driver/sql_jdbc/execute/old_impl.clj
  src/metabase/driver/sql_jdbc/sync/interface.clj
  src/metabase/query_processor/util.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/dataset_test.clj
  test/metabase/api/embed_test.clj
  test/metabase/api/field_test.clj
  test/metabase/api/native_query_snippet_test.clj
  test/metabase/api/preview_embed_test.clj
  test/metabase/api/table_test.clj
  test/metabase/async/streaming_response_test.clj
  test/metabase/driver/h2_test.clj
  test/metabase/driver/mysql_test.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/driver/sql_jdbc/native_test.clj
  test/metabase/driver/sql_jdbc_test.clj
  test/metabase/http_client.clj
  test/metabase/integrations/ldap_test.clj
  test/metabase/public_settings_test.clj
  test/metabase/query_processor/middleware/catch_exceptions_test.clj
  test/metabase/query_processor/middleware/permissions_test.clj
  test/metabase/query_processor/middleware/results_metadata_test.clj
  test/metabase/query_processor/util_test.clj
  test/metabase/query_processor_test/breakout_test.clj
  test/metabase/query_processor_test/filter_test.clj
  test/metabase/search/scoring_test.clj
  test/metabase/server/routes/index_test.clj
  test/metabase/sync/analyze/query_results_test.clj
  test/metabase/sync/analyze_test.clj
  test/metabase/test.clj
  test/metabase/test/data/impl.clj
  test/metabase/test/data/sql_jdbc/load_data.clj
  test/metabase/test/data/users.clj
  test/metabase/test/mock/util.clj
  test/metabase/test/sync.clj
  test/metabase/test/util.clj
  test/metabase/test/util/log.clj
Labels: backport

#25711 [E2E] Upgrade cross-version Cypress configs to v10 format
  .github/workflows/e2e-cross-version.yml
  frontend/test/__support__/e2e/config.js
  frontend/test/metabase/scenarios/cross-version/source/cross-version-source.config.js
  frontend/test/metabase/scenarios/cross-version/source/cypress.json
  frontend/test/metabase/scenarios/cross-version/target/cross-version-target.config.js
  frontend/test/metabase/scenarios/cross-version/target/cypress.json
Labels: Type:Tech Debt, .CI & Tests

#25709 [FE] Remove unused `underscore` imports
  enterprise/frontend/src/metabase-enterprise/license/index.js
  frontend/src/metabase/admin/people/components/GroupDetail.jsx
  frontend/src/metabase/admin/people/components/MembershipSelect/MembershipSelect.tsx
  frontend/src/metabase/admin/people/components/PeopleListRow.jsx
  frontend/src/metabase/admin/people/selectors.js
  frontend/src/metabase/admin/permissions/selectors/data-permissions/breadcrumbs.ts
  frontend/src/metabase/admin/permissions/selectors/data-permissions/data-sidebar.ts
  frontend/src/metabase/admin/permissions/selectors/data-permissions/fields.ts
  frontend/src/metabase/admin/permissions/selectors/data-permissions/group-sidebar.ts
  frontend/src/metabase/admin/permissions/selectors/data-permissions/schemas.ts
  frontend/src/metabase/admin/permissions/selectors/data-permissions/tables.ts
  frontend/src/metabase/admin/permissions/utils/graph/permissions-diff.ts
  frontend/src/metabase/collections/components/PinnedItemCard/PinnedItemCard.stories.tsx
  frontend/src/metabase/components/DateAllOptionsWidget/DateAllOptionsWidget.tsx
  frontend/src/metabase/core/components/Select/Select.stories.tsx
  frontend/src/metabase/dashboard/actions/revisions.js
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/LinkOptions/ValuesYouCanReference.jsx
  frontend/src/metabase/hoc/Favicon.jsx
  frontend/src/metabase/lib/card.js
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/SidebarCollectionLink.tsx
  frontend/src/metabase/query_builder/actions/core/core.js
  frontend/src/metabase/query_builder/actions/core/initializeQB.ts
  frontend/src/metabase/query_builder/actions/core/initializeQB.unit.spec.ts
  frontend/src/metabase/query_builder/actions/core/updateQuestion.unit.spec.ts
  frontend/src/metabase/query_builder/actions/models.js
  frontend/src/metabase/query_builder/actions/native.js
  frontend/src/metabase/query_builder/actions/querying.js
  frontend/src/metabase/query_builder/actions/ui.js
  frontend/src/metabase/query_builder/actions/visualization-settings.js
  frontend/src/metabase/query_builder/components/DataSelector/saved-question-picker/SavedQuestionList.jsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetFieldMetadataSidebar/MappedFieldPicker/MappedFieldPicker.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/DatePickerFooter.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/DatePickerShortcuts.tsx
  frontend/src/metabase/reducers-main.js
  frontend/src/metabase/visualizations/components/List/ListCell.tsx
  frontend/src/metabase/visualizations/components/TableSimple/TableCell.jsx
  frontend/src/metabase/visualizations/lib/apply_tooltips.js
  frontend/test/metabase-lib/lib/Dimension.unit.spec.js
  frontend/test/metabase-visual/notebook/notebook.cy.spec.js
  frontend/test/metabase/scenarios/admin/people/group-managers.cy.spec.js
  frontend/test/metabase/scenarios/filters/relative-datetime.cy.spec.js
Labels: Type:Tech Debt, .Frontend

#25675 Do not autorun ad-hoc native queries
  frontend/src/metabase/query_builder/actions/core/initializeQB.ts
  frontend/src/metabase/query_builder/actions/core/initializeQB.unit.spec.ts
  frontend/test/__support__/e2e/helpers/e2e-ad-hoc-question-helpers.js
  frontend/test/__support__/e2e/helpers/e2e-misc-helpers.js
  frontend/test/metabase/scenarios/native/native.cy.spec.js
  frontend/test/metabase/scenarios/permissions/permissions-baseline.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/11727-cancel-native-query-shortcut.cy.spec.js
Labels: Type:Tech Debt, backport
