Repository metabase/metabase, pull requests merged in 2022-02, with the labels that each got.

#20076 docs - updates to reflect new db advanced settings UI
  docs/administration-guide/01-managing-databases.md
  docs/administration-guide/databases/google-analytics.md
  docs/administration-guide/databases/mongodb.md
  docs/administration-guide/databases/mysql.md
Labels: Type:Documentation, backport

#20067 Joins E2E tests: ensure that the schema is completely loaded
  frontend/test/metabase/scenarios/joins/reproductions/18502-cannot-join-two-saved-questions-same-table.cy.spec.js
  frontend/test/metabase/scenarios/joins/reproductions/18512-cannot-join-two-saved-questions-with-same-implicit-explicit-grouped-field.cy.spec.js
Labels: backport

#20014 Enable quick filter drills on aggregated, custom columns and native query results
  frontend/src/metabase-lib/lib/metadata/Field.ts
  frontend/src/metabase-types/types/Dataset.ts
  frontend/src/metabase-types/types/mocks/dataset.ts
  frontend/src/metabase/modes/components/drill/QuickFilterDrill.jsx
  frontend/src/metabase/visualizations/components/ChartClickActions.jsx
  frontend/test/metabase/modes/components/drill/QuickFilterDrill.unit.spec.js
Labels: backport

#20100 Fix missing item descriptions in search results
  frontend/src/metabase/query_builder/components/data-search/SearchResults.jsx
  frontend/src/metabase/search/components/SearchResult.jsx
Labels: backport

#20074 Remove the empty pinned section banner
  frontend/src/metabase/collections/components/PinDropZone/PinDropZone.styled.tsx
  frontend/src/metabase/collections/components/PinDropZone/PinDropZone.tsx
  frontend/src/metabase/collections/components/PinnedItemOverview/PinnedItemOverview.tsx
  frontend/src/metabase/collections/components/PinnedItemOverview/PinnedItemOverview.unit.spec.js
Labels: backport

#20106 docs - fix docker dev branch instructions
  docs/developers-guide/dev-branch-docker.md
Labels: Type:Documentation, backport

#20006 fix crowded ordinal ticks
  frontend/src/metabase/internal/pages/StaticVizPage.jsx
  frontend/src/metabase/static-viz/components/LineAreaBarChart/LineAreaBarChart.tsx
  frontend/src/metabase/static-viz/components/LineAreaBarChart/types.ts
  frontend/src/metabase/static-viz/components/LineAreaBarChart/utils/settings.ts
  frontend/src/metabase/static-viz/components/LineAreaBarChart/utils/settings.unit.spec.ts
  frontend/src/metabase/static-viz/components/XYChart/XYChart.tsx
  frontend/src/metabase/static-viz/components/XYChart/utils/scales.ts
  frontend/src/metabase/static-viz/components/XYChart/utils/ticks.ts
Labels: backport

#20112 docs - update new Slack setup instructions
  docs/administration-guide/09-setting-up-slack.md
Labels: Type:Documentation, backport

#20111 Fix passing treat-before-posting on the FE
  frontend/src/metabase/entities/databases/forms.js
Labels: backport

#20117 docs - assorted screenshots and minor UI text updates
  docs/administration-guide/07-segments-and-metrics.md
  docs/administration-guide/images/AddMetric.png
  docs/administration-guide/images/AddSegment.png
  docs/administration-guide/images/CreateMetric.png
  docs/administration-guide/images/CreateSegment.png
  docs/administration-guide/images/FinishedSegment.png
  docs/administration-guide/images/re-scan-options.png
  docs/enterprise-guide/activating-the-enterprise-edition.md
  docs/enterprise-guide/images/sandboxing/advanced-example-1-sandbox-modal.png
  docs/users-guide/images/asking-questions/notebook-editor.png
  docs/users-guide/images/collection-detail.png
  docs/users-guide/images/collections/pinned-items.png
  docs/users-guide/images/notebook/started-from-saved-question.png
  docs/users-guide/images/notebook/summarize-step.png
Labels: Type:Documentation, backport

#20119 Fix creation type (for 0.42)
  frontend/src/metabase/nav/containers/Navbar.jsx
  frontend/src/metabase/new_query/containers/NewQueryOptions.jsx
Labels: backport

#20126 include type defs to tsc-files
  package.json
Labels: backport

#20013 BE for stacked area viz for #20004 (#18676)
  src/metabase/pulse/render/body.clj
  test/metabase/pulse/render/body_test.clj
  test/metabase/pulse/render/test_util.clj
Labels: backport

#20146 Fix models e2e typing flake pt2
  frontend/test/__support__/e2e/commands/api/question.js
  frontend/test/metabase/scenarios/models/models-query-editor.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#19901 Disable remapping when syncing Field values. Handle human readable values in `GET /api/field/:id/values`
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
  src/metabase/api/field.clj
  src/metabase/db/metadata_queries.clj
  src/metabase/models/field_values.clj
  src/metabase/query_processor/middleware/add_dimension_projections.clj
  test/metabase/api/field_test.clj
  test/metabase/models/field_values_test.clj
Labels: backport

#20138 Repro #19776: New data picker shows blank after archiving a model
  frontend/test/metabase/scenarios/models/reproductions/19776-data-picker-not-displayed-after-archiving-model.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#20149 Repro #20042: Blank screen when accessing Models with no-data user
  frontend/test/metabase/scenarios/models/reproductions/20042-nodata-user-blank-screen.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#20160 Fix native query editor resizing gets stuck
  frontend/src/metabase/query_builder/components/DataSelector.jsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx
Labels: backport

#20145 Fix "source cannot be null" error in MongoDB
  modules/drivers/mongo/src/metabase/driver/mongo/util.clj
Labels: backport

#20091 Remove trailing slash from /api/tiles call on frontend
  frontend/src/metabase/visualizations/components/LeafletTilePinMap.jsx
Labels: backport

#20166 Fix data selector crashes and closes after hiding a table
  frontend/src/metabase/query_builder/components/DataSelector.jsx
  frontend/test/metabase/scenarios/question/reproductions/19742-data-picker-closes-after-hiding-table.cy.spec.js
Labels: backport

#20029 increase font weight on selected AM/PM in filter
  frontend/src/metabase/query_builder/components/filters/pickers/HoursMinutesInput.jsx
Labels: backport

#20136 let user add missing options to ListField widget
  frontend/src/metabase/components/ListField/ListField.tsx
  frontend/test/metabase/scenarios/question/view.cy.spec.js
Labels: backport

#20032 Crop pngs to their content width after rendering to remove extra whitespace
  dev/src/dev/render_png.clj
  src/metabase/pulse.clj
  src/metabase/pulse/render/png.clj
  test/metabase/pulse/render/png_test.clj
Labels: backport

#20164 Repro #20045: Rerunning a saved Model causes it to add queryhash
  frontend/test/metabase/scenarios/models/reproductions/20045-rerun-model-adds-hash.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#20137 Repro #19737: New question picker doesn't show moved model's collection until page refresh
  frontend/test/metabase/scenarios/models/reproductions/19737-data-picker-not-showing-moved-model.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#20003 Handle NULL value for integer fingerprints
  frontend/src/metabase/components/MetadataInfo/FieldFingerprintInfo/FieldFingerprintInfo.jsx
  frontend/src/metabase/components/MetadataInfo/FieldFingerprintInfo/FieldFingerprintInfo.unit.spec.js
Labels: backport

#20175 Simplify models query e2e tests
  frontend/test/metabase/scenarios/models/models-query-editor.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#20161 Fix no-data user can't open a model
  frontend/src/metabase/query_builder/selectors.js
  frontend/test/metabase/scenarios/models/reproductions/20042-nodata-user-blank-screen.cy.spec.js
Labels: backport

#20195 Maps E2E test: ensure that the map data is received
  frontend/test/metabase/scenarios/visualizations/maps.cy.spec.js
Labels: backport

#20156 Circle CI: Build with Java 8
  .circleci/config.yml
Labels: backport

#20198 Repro #20018: Descriptions missing in search results
  frontend/test/metabase/scenarios/onboarding/search/search.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#20183 Fix URL hash appended to model URLs
  frontend/src/metabase/query_builder/actions.js
  frontend/test/metabase/scenarios/models/models-query-editor.cy.spec.js
  frontend/test/metabase/scenarios/models/reproductions/20045-rerun-model-adds-hash.cy.spec.js
Labels: backport

#20056 Fix native model editor initial height
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/constants.ts
  frontend/src/metabase/query_builder/components/NativeQueryEditor/utils.ts
Labels: backport

#20197 Repro #20044: "Explore results" shown for no-data users
  frontend/test/metabase/scenarios/native/reproductions/20044-no-data-sees-explore-results.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#20177 Fix display of horizontal lines in dashboard text cards
  frontend/src/metabase/visualizations/visualizations/Text.css
  src/metabase/pulse/markdown.clj
  test/metabase/pulse/markdown_test.clj
Labels: backport

#20217 Repro #20043: Don't show pins or helper on view-only collections
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: .CI & Tests, support/Repro, auto-backported

#20172 Update style for code in dashboard dark mode
  frontend/src/metabase/css/dashboard.css
Labels: backport

#20227 Fix pin map lat/lon column selection when query uses :breakout
  src/metabase/api/tiles.clj
  test/metabase/api/tiles_test.clj
Labels: backport

#20194 Update filename of sample DB
  bin/build-for-test
  frontend/test/__support__/e2e/commands/database/addH2SampleDatabase.js
  frontend/test/__support__/sample_database_fixture.json
  frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/edit.cy.spec.js
  frontend/test/metabase/scenarios/question/new.cy.spec.js
  frontend/test/snapshot-creators/default.cy.snap.js
  resources/sample-database.db.mv.db
  src/metabase/sample_data.clj
Labels: backport

#20139 Fix ambiguous run-query-for-dashcard endpoints
  docs/api-documentation.md
  frontend/src/metabase-lib/lib/Question.ts
  frontend/src/metabase/dashboard/actions.js
  frontend/src/metabase/lib/card.js
  frontend/src/metabase/parameters/utils/dashboards.js
  frontend/src/metabase/parameters/utils/dashboards.unit.spec.js
  frontend/src/metabase/query_builder/actions.js
  frontend/src/metabase/services.js
  frontend/test/metabase-lib/lib/Question.unit.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/12720-no-data-permissions-connected-filter.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/13150-additional-card-queries-for-all-filters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/13960-do-not-preserve-cleared-default-filter-on-refresh.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/17212-nested-id-filter.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/19494-wrong-default-value-multiple-cards-same-question.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/click-behavior.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/reproductions/18454-card-description.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/title-drill.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/17514-ui-overlay.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/gauge.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/18061-maps-only-nulls-crash-frontend.cy.spec.js
  src/metabase/api/dashboard.clj
  src/metabase/api/embed.clj
  src/metabase/api/public.clj
  src/metabase/pulse.clj
  src/metabase/query_processor/dashboard.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/public_test.clj
  test/metabase/query_processor/dashboard_test.clj
Labels: backport

#20237 Simplify time-series binning e2e test
  frontend/test/metabase/scenarios/binning/correctness/constants.js
  frontend/test/metabase/scenarios/binning/correctness/longitude.cy.spec.js
  frontend/test/metabase/scenarios/binning/correctness/time-series.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#20242 Repro #20229: Custom columns not appearing in result set when selecting subset of fields
  frontend/test/metabase/scenarios/custom-column/reproductions/20229-cc-missing-if-all-columns-not-selected.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#20225 Fix revision message timestamp color
  frontend/src/metabase/components/Timeline.styled.jsx
Labels: backport

#20239 Fix deselecting a column removes all custom expressions from query
  frontend/src/metabase/query_builder/components/notebook/steps/DataStep.jsx
  frontend/test/metabase/scenarios/custom-column/reproductions/20229-cc-missing-if-all-columns-not-selected.cy.spec.js
Labels: backport

#20249 Fix table column titles get cut-off when switching to model metadata editor
  frontend/src/metabase/visualizations/components/TableInteractive.jsx
  frontend/test/metabase/visualizations/components/Visualization-table.unit.spec.js
Labels: backport

#19732 Update serialization documentation
  docs/enterprise-guide/serialization.md
Labels: Type:Documentation

#20267 disable leaflet pointer-events in collection visualizations
  frontend/src/metabase/collections/components/CollectionCardVisualization/CollectionCardVisualization.styled.jsx
Labels: backport

#20272 Hide pin action button when user can't pin
  frontend/src/metabase/components/EntityItem.jsx
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: backport

#20238 Ignore hidden/archived tables cards and dashboards in recent list
  src/metabase/api/activity.clj
  test/metabase/api/activity_test.clj
Labels: backport

#20199 Retain property file path when revisiting database edit page
  src/metabase/api/database.clj
  src/metabase/models/database.clj
  src/metabase/models/secret.clj
  test/metabase/api/database_test.clj
  test/metabase/models/database_test.clj
Labels: backport

#20240 Prevent flaky tests based on contents of TaskHistory
  test/metabase/task/task_history_cleanup_test.clj
Labels: backport

#20270 Changing circleCI resource to handle be-tests-sparksql-ee faster
  .circleci/config.yml
Labels: .CI & Tests

#20284 Reinforce time-series binning e2e test
  frontend/test/metabase/scenarios/binning/correctness/time-series.cy.spec.js
Labels: .CI & Tests, support/Repro

#20271 Remove "Filtering on this field" form field for models
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetFieldMetadataSidebar/DatasetFieldMetadataSidebar.jsx
Labels: backport

#20191 Disable model editor's "Save changes" button when there are no changes
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx
  frontend/src/metabase/query_builder/reducers.js
  frontend/src/metabase/query_builder/selectors.js
  frontend/test/metabase/scenarios/models/models-query-editor.cy.spec.js
Labels: backport

#20118 Docs - postgres, truststore, and keystore
  docs/administration-guide/01-managing-databases.md
  docs/administration-guide/databases/oracle.md
  docs/administration-guide/databases/postgresql.md
  docs/administration-guide/images/oracle_jdbc_download.png
  docs/administration-guide/secure-database-connections-with-ssl-certificates.md
Labels: Type:Documentation, backport

#20294 docs - remove filtering on this field
  docs/users-guide/models.md
Labels: Type:Documentation

#20009 Rework how the remappings middleware matches remapped to/from columns for explicit external (FK) remaps
  dev/src/dev/debug_qp.clj
  enterprise/backend/test/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions_test.clj
  shared/src/metabase/mbql/schema.cljc
  shared/src/metabase/mbql/util.cljc
  shared/test/metabase/mbql/util_test.cljc
  src/metabase/query_processor/middleware/add_dimension_projections.clj
  src/metabase/query_processor/middleware/add_implicit_joins.clj
  src/metabase/query_processor/middleware/annotate.clj
  src/metabase/query_processor/middleware/resolve_joins.clj
  src/metabase/query_processor/util/add_alias_info.clj
  test/metabase/api/table_test.clj
  test/metabase/http_client.clj
  test/metabase/query_processor/middleware/add_dimension_projections_test.clj
  test/metabase/query_processor/middleware/add_implicit_joins_test.clj
  test/metabase/query_processor/streaming_test.clj
  test/metabase/query_processor_test/breakout_test.clj
  test/metabase/query_processor_test/remapping_test.clj
  test/metabase/test.clj
  test/metabase/test/data.clj
  test/metabase/test/util.clj
  test/metabase/test_runner.clj
  test/metabase/test_runner/assert_exprs.clj
  test/metabase/test_runner/assert_exprs_test.clj
Labels: backport

#20288 Disallow moving items to a collection it's already in via drag-n-drop
  frontend/src/metabase/containers/dnd/CollectionDropTarget.jsx
Labels: backport

#20295 Make Ad hoc question e2e helper automatically wait for the query results
  frontend/test/__support__/e2e/helpers/e2e-ad-hoc-question-helpers.js
  frontend/test/metabase-visual/visualizations/bar.cy.spec.js
  frontend/test/metabase-visual/visualizations/funnel.cy.spec.js
  frontend/test/metabase-visual/visualizations/line.cy.spec.js
  frontend/test/metabase-visual/visualizations/row.cy.spec.js
  frontend/test/metabase-visual/visualizations/scatter.cy.spec.js
  frontend/test/metabase-visual/visualizations/waterfall.cy.spec.js
  frontend/test/metabase/scenarios/binning/binning-options.cy.spec.js
  frontend/test/metabase/scenarios/binning/binning-reproductions.cy.spec.js
  frontend/test/metabase/scenarios/custom-column/custom-column.cy.spec.js
  frontend/test/metabase/scenarios/downloads/reproductions/18382-old-syntax-missing-renamed-columns.cy.spec.js
  frontend/test/metabase/scenarios/downloads/reproductions/18440-remapped-display-value-dropped.cy.spec.js
  frontend/test/metabase/scenarios/downloads/reproductions/18573-remapped-fields-not-renamed.cy.spec.js
  frontend/test/metabase/scenarios/downloads/reproductions/18729-date-formatting-x-of-y.cy.spec.js
  frontend/test/metabase/scenarios/joins/joins-2.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/15460.cy.spec.js
  frontend/test/metabase/scenarios/native/reproductions/12439-click-on-legend-breaks-ui.cy.spec.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/bar_chart.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/line_chart.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/maps.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/pie_chart.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/14148-pivot-table-postgres.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/18976-pivot-table-columns.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/scatter.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/waterfall.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#20273 Fix model metadata propagation
  frontend/src/metabase-lib/lib/Dimension.ts
  frontend/src/metabase/parameters/utils/dashboards.unit.spec.js
  frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js
  frontend/src/metabase/query_builder/actions.js
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.jsx
  frontend/src/metabase/query_builder/reducers.js
  frontend/src/metabase/query_builder/selectors.js
  frontend/test/metabase-lib/lib/Dimension.unit.spec.js
Labels: backport

#20304 Rewrite open table helper
  frontend/test/__support__/e2e/cypress.js
  frontend/test/__support__/e2e/helpers/e2e-ad-hoc-question-helpers.js
  frontend/test/__support__/e2e/helpers/e2e-open-table-helpers.js
  frontend/test/metabase-visual/visualizations/table.cy.spec.js
  frontend/test/metabase/scenarios/binning/binning-options.cy.spec.js
  frontend/test/metabase/scenarios/permissions/sandboxes.cy.spec.js
  frontend/test/metabase/scenarios/question/new.cy.spec.js
  frontend/test/metabase/scenarios/question/nulls.cy.spec.js
  frontend/test/metabase/scenarios/question/saved.cy.spec.js
  frontend/test/metabase/scenarios/question/view.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/table.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/trendline.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#20324 Remove accidental `.debug()` from a test
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#20336 Improve spacing above unpinned items table
  frontend/src/metabase/collections/components/BaseItemsTable.styled.jsx
  frontend/src/metabase/collections/components/PinnedItemOverview/PinnedItemOverview.styled.tsx
Labels: backport

#20334 Set default waterfall colors static viz
  src/metabase/pulse/render/body.clj
Labels: backport

#20154 Fix QP remapping middleware not recursing into joins or source queries of source queries
  frontend/test/metabase/scenarios/joins/joins.cy.spec.js
  src/metabase/models/params/chain_filter.clj
  src/metabase/query_processor/middleware/add_dimension_projections.clj
  test/metabase/query_processor/middleware/add_dimension_projections_test.clj
  test/metabase/query_processor_test/remapping_test.clj
Labels: backport

#20345 localStorage can't be used in Chrome Incognito
  docs/enterprise-guide/full-app-embedding.md
Labels: backport

#20342 Remove unused dep on aleph (and thus unused transient dep on Netty)
  deps.edn
Labels: backport

#20373 Replace the old bigquery e2e test with the Presto deprecation warning
  frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js
Labels: .CI & Tests

#20375 docs - update links
  docs/administration-guide/databases/postgresql.md
  docs/developers-guide/dev-branch-docker.md
  docs/operations-guide/installing-metabase.md
Labels: Type:Documentation, backport

#20347 Collection permissions E2E: wait for the complete collection data
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: backport

#20370 workaround people pagination flakes
  frontend/test/metabase/scenarios/admin/people/people.cy.spec.js
Labels: backport

#20395 Bi-basics e2e helpers
  frontend/test/__support__/e2e/cypress.js
  frontend/test/__support__/e2e/helpers/e2e-bi-basics-helpers.js
  frontend/test/metabase/scenarios/admin/datamodel/metadata.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/metrics.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/reproductions/17768-entity-key-showing-binning-options.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/table.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/whitelabel.cy.spec.js
  frontend/test/metabase/scenarios/binning/binning-options.cy.spec.js
  frontend/test/metabase/scenarios/binning/binning-reproductions.cy.spec.js
  frontend/test/metabase/scenarios/binning/correctness/longitude.cy.spec.js
  frontend/test/metabase/scenarios/binning/correctness/time-series.cy.spec.js
  frontend/test/metabase/scenarios/binning/qb-explicit-joins.cy.spec.js
  frontend/test/metabase/scenarios/binning/qb-implicit-joins.cy.spec.js
  frontend/test/metabase/scenarios/binning/qb-regular-table.cy.spec.js
  frontend/test/metabase/scenarios/binning/sql.cy.spec.js
  frontend/test/metabase/scenarios/custom-column/cc-data-type.cy.spec.js
  frontend/test/metabase/scenarios/custom-column/custom-column.cy.spec.js
  frontend/test/metabase/scenarios/custom-column/reproductions/13289-cc-post-aggregation-zoom-in.cy.spec.js
  frontend/test/metabase/scenarios/custom-column/reproductions/14843-cc-apply-filter-not-equal-to.cy.spec.js
  frontend/test/metabase/scenarios/custom-column/reproductions/18069-cc-sum-aggregation-dimension-type.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/x-rays.cy.spec.js
  frontend/test/metabase/scenarios/joins/joins-2.cy.spec.js
  frontend/test/metabase/scenarios/joins/joins.cy.spec.js
  frontend/test/metabase/scenarios/joins/reproductions/18589-numeric-binning-in-joins.cy.spec.js
  frontend/test/metabase/scenarios/models/models-query-editor.cy.spec.js
  frontend/test/metabase/scenarios/models/models-revision-history.cy.spec.js
  frontend/test/metabase/scenarios/models/models.cy.spec.js
  frontend/test/metabase/scenarios/native/native.cy.spec.js
  frontend/test/metabase/scenarios/permissions/sandboxes.cy.spec.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/new.cy.spec.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
  frontend/test/metabase/scenarios/question/nulls.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/17512.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/6239-sort-using-cust-exp.cy.spec.js
  frontend/test/metabase/scenarios/question/saved.cy.spec.js
  frontend/test/metabase/scenarios/question/summarization.cy.spec.js
  frontend/test/metabase/scenarios/question/view.cy.spec.js
  frontend/test/metabase/scenarios/smoketest/admin.cy.spec.js
  frontend/test/metabase/scenarios/smoketest/user.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/16170-line-mongo-replace-missing-values-with-zero.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/17524.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/table.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/waterfall.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#20422 Docs questions
  docs/README.md
  docs/users-guide/04-asking-questions.md
  docs/users-guide/05-visualizing-results.md
  docs/users-guide/start.md
Labels: Type:Documentation, backport

#20394 Handle scenario where query props are undefined on a StructuredQuery
  frontend/src/metabase-lib/lib/queries/StructuredQuery.ts
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/20393-public-dashboard-nested-card-with-parameters.cy.spec.js
Labels: support/Repro, backport

#20417 Fix revision history display
  frontend/src/metabase/lib/revisions/components.jsx
  frontend/src/metabase/lib/revisions/components.unit.spec.js
  frontend/src/metabase/lib/revisions/revisions.js
Labels: backport

#20445 Creating reproduction for 16621
  frontend/test/metabase/scenarios/question/reproductions/16621-create-multiple-filters-with-same-value.cy.spec.js
Labels: .CI & Tests, support/Repro

#20435 use column settings instead of display_name for pivot table value header
  frontend/src/metabase/lib/data_grid.js
Labels: backport

#20448 Ensure PNG cropping doesn't clip table content
  src/metabase/pulse/render/png.clj
  test/metabase/pulse/render/png_test.clj
Labels: backport

#20462 Clear google auth client ID setting if empty string is saved
  src/metabase/integrations/google.clj
  test/metabase/integrations/google_test.clj
Labels: backport

#20434 BigQuery should qualify columns from source query with `source` in the `SELECT` clause
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj
  test/metabase/query_processor_test/explicit_joins_test.clj
Labels: backport

#20474 Fix source aliases for Fields from joins not being properly escaped
  src/metabase/query_processor/util/add_alias_info.clj
  test/metabase/api/session_test.clj
  test/metabase/query_processor/util/add_alias_info_test.clj
  test/metabase/query_processor_test/explicit_joins_test.clj
  test/metabase/test.clj
Labels: backport

#20441 Simplify tests by improving custom `cy.createQuestion` command
  frontend/test/__support__/e2e/commands/api/question.js
  frontend/test/metabase/scenarios/admin/datamodel/metadata.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/localization.cy.spec.js
  frontend/test/metabase/scenarios/custom-column/custom-column.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/x-rays.cy.spec.js
  frontend/test/metabase/scenarios/downloads/reproductions/10803-timestamp-formatting.cy.spec.js
  frontend/test/metabase/scenarios/downloads/reproductions/19889-native-query-export-column-order.cy.spec.js
  frontend/test/metabase/scenarios/joins/joins-2.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/12228.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/12581.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/13961.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/14145.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/14302.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/sql-field-filter-category.cy.spec.js
  frontend/test/metabase/scenarios/native/reproductions/19451.cy.spec.js
  frontend/test/metabase/scenarios/native/snippets/snippets.cy.spec.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/maps.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/rows.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#20475 Include (new) site UUID in EE token check request
  src/metabase/public_settings.clj
  src/metabase/public_settings/premium_features.clj
  test/metabase/public_settings/premium_features_test.clj
Labels: backport

#20492 Repro #20488: Trend visualization percentage rounding decimals
  frontend/test/metabase/scenarios/visualizations/smartscalar-trend.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#19659 Add logic to truncate and uniquely-suffix column alias identifiers
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj
  modules/drivers/oracle/src/metabase/driver/oracle.clj
  modules/drivers/oracle/test/metabase/driver/oracle_test.clj
  shared/src/metabase/mbql/util.cljc
  src/metabase/driver.clj
  src/metabase/driver/common.clj
  src/metabase/driver/impl.clj
  src/metabase/query_processor.clj
  src/metabase/query_processor/middleware/add_implicit_joins.clj
  src/metabase/query_processor/middleware/escape_join_aliases.clj
  src/metabase/query_processor/middleware/resolve_joins.clj
  src/metabase/query_processor/util/add_alias_info.clj
  test/metabase/driver/common_test.clj
  test/metabase/driver/impl_test.clj
  test/metabase/query_processor/middleware/escape_join_aliases_test.clj
  test/metabase/query_processor/middleware/resolve_joins_test.clj
  test/metabase/query_processor_test.clj
  test/metabase/query_processor_test/explicit_joins_test.clj
  test/metabase/query_processor_test/implicit_joins_test.clj
  test/metabase/test/util.clj
Labels: backport

#20504 Repro #20436:Restricting and unrestricting access to a table results in the DB-level permission still being "Granular"
  frontend/test/metabase/scenarios/permissions/reproductions/20436-incorrect-display-of-database-permissions-level.cy.spec.js
Labels: .CI & Tests, support/Repro

#20317 Fix nested query controls for no-data users
  frontend/src/metabase-lib/lib/queries/NativeQuery.ts
  frontend/src/metabase-lib/lib/queries/StructuredQuery.ts
  frontend/src/metabase/internal/components/QuestionApp.jsx
  frontend/src/metabase/new_query/selectors.js
  frontend/src/metabase/query_builder/components/view/HeaderBreadcrumbs/HeaderBreadcrumbs.jsx
  frontend/src/metabase/query_builder/components/view/QuestionDataSource.jsx
  frontend/src/metabase/query_builder/components/view/QuestionDataSource.unit.spec.js
  frontend/src/metabase/query_builder/components/view/ViewFooter.jsx
  frontend/src/metabase/query_builder/components/view/ViewHeader.unit.spec.js
  frontend/src/metabase/visualizations/components/TableInteractive.jsx
  frontend/test/metabase-lib/lib/Question.unit.spec.js
  frontend/test/metabase-lib/lib/queries/StructuredQuery.unit.spec.js
  frontend/test/metabase/scenarios/question/reproductions/18978-18977-nested-question-nodata-user.cy.spec.js
Labels: backport

#20521 Repro #20519: Summarizing with implicit join does not allow subsequent joins and nested query
  frontend/test/metabase/scenarios/joins/reproductions/20519-cannot-join-on-aggregation-with-implicit-joins-and-nested-query.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#20512 Embed query endpoints should handle operator filters with a single arg
  src/metabase/api/embed.clj
  src/metabase/query_processor/dashboard.clj
  test/metabase/api/embed_test.clj
  test/metabase/api/preview_embed_test.clj
Labels: backport

#20523 Ensure token_features and created_at are included in backend Snowplow events
  src/metabase/analytics/snowplow.clj
  test/metabase/analytics/snowplow_test.clj
Labels: backport

#20503 Dashboard QP endpoints should ignore :default values and treat them as no value and compile Field filters to `1 = 1`
  frontend/test/metabase/scenarios/dashboard-filters-sql/dashboard-filters-sql-text-category.cy.spec.js
  src/metabase/driver/common/parameters/operators.clj
  src/metabase/driver/sql/parameters/substitute.clj
  src/metabase/query_processor/card.clj
  src/metabase/query_processor/dashboard.clj
  src/metabase/query_processor/middleware/parameters.clj
  test/metabase/driver/sql/parameters/substitute_test.clj
  test/metabase/query_processor/dashboard_test.clj
Labels: backport

#20553 Adding encryption algo's to docs
  docs/operations-guide/encrypting-database-details-at-rest.md
Labels: Type:Documentation, backport

#20557 docs - expanding google drive instructions in bigquery docs
  docs/administration-guide/databases/bigquery.md
  docs/troubleshooting-guide/bigquery-drive.md
Labels: Type:Documentation, backport

#20561 use includes instead of startsWith to filter options in ListField
  frontend/src/metabase/components/ListField/ListField.tsx
Labels: backport

#20581 Repro #20551: Filter dropdown only allows filtering on "starts with"
  frontend/test/metabase/scenarios/question/reproductions/20551-filter-starts-with.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#20536 Repro #20438: Embed dashboard Field Filter cannot work when choosing single option
  frontend/test/metabase/scenarios/sharing/reproductions/20438.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#20569 Dashboard Subscriptions *should* use `:default` param values.
  src/metabase/pulse.clj
  src/metabase/query_processor/dashboard.clj
  test/metabase/dashboard_subscription_test.clj
  test/metabase/query_processor/dashboard_test.clj
Labels: backport

#20583 Upgrade webpack-dev-server
  package.json
  webpack.config.js
  yarn.lock
Labels: backport

#20590 docs - typo
  docs/enterprise-guide/start.md
Labels: Type:Documentation, backport

#20533 Custom expression editor: do not always suggest an open parenthesis
  frontend/src/metabase/lib/expressions/suggest.js
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield.jsx
  frontend/test/metabase/lib/expressions/suggest.unit.spec.js
Labels: backport

#20509 Make date widget respect date/time format settings
  frontend/src/metabase/lib/time.js
  frontend/src/metabase/query_builder/components/filters/pickers/HoursMinutesInput.jsx
  frontend/src/metabase/query_builder/components/filters/pickers/SpecificDatePicker.jsx
  frontend/test/metabase/scenarios/admin/settings/localization.cy.spec.js
Labels: support/Repro

#20587 Repro #20548: Changing Y-axis order can cause duplicate legends when modifying metrics after
  frontend/test/metabase/scenarios/visualizations/reproductions/20548-bar-duplicate-y-axis-after-changing-metrics.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#20589 Repro #20517: Removing or adding column descriptions to metadata of Models results in "failed save"
  frontend/test/metabase/scenarios/models/reproductions/20517-edit-metadata-empty-description.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#20630 E2E Helper `visitQuestion`: Ensure that the query loaded before moving forward with the test
  frontend/test/__support__/e2e/helpers/e2e-misc-helpers.js
  frontend/test/metabase/scenarios/sharing/alert/alert-permissions.cy.spec.js
  frontend/test/metabase/scenarios/sharing/alert/alert.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#20631 Repro #20627: Nested queries with long Data Model names causes failing query with incorrect aliasing
  frontend/test/metabase/scenarios/question/reproductions/20627-nested-long-names-wrong-aliases.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#20662 Repro #20656: Dashboard with filter connected to a card that a user doesn't have permissions to view breaks
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/20656-dashboard-breaks-for-user-without-card-permissions.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#20663 Repro #20624: Model metadata not overriding question column settings
  frontend/test/metabase/scenarios/models/reproductions/20624-model-metadata-should-override-column-settings.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#20667 Repro 20638: Creating a new dashboard from the New button in a collection should take me to that dashboard
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#20672 Repro #15353: Pivot Table: Cannot change name of fields used for "values"
  frontend/test/metabase/scenarios/visualizations/reproductions/15353-pivot-settings-change-name-values.cy.spec.js
Labels: .CI & Tests, support/Repro

#20673 Repro #18814: Frontend crashes when using a custom column on a nested query
  frontend/test/metabase/scenarios/custom-column/reproductions/18814-cc-used-in-aggregation-for-nested-query.cy.spec.js
Labels: .CI & Tests, support/Repro

#20676 Repro #20471: Ugly error state in Admin > Databases
  frontend/test/metabase/scenarios/admin/databases/list.cy.spec.js
Labels: .CI & Tests, support/Repro

#20675 Repro #20469: Main page loading spinner spins forever on API error
  frontend/test/metabase/scenarios/onboarding/home/homepage.cy.spec.js
Labels: .CI & Tests, support/Repro

#20635 Fix locked parameters in embedded questions
  frontend/src/metabase/query_builder/containers/QuestionEmbedWidget.jsx
  frontend/test/metabase/scenarios/sharing/reproductions/20634-locked-parameters-in-embedded-question.cy.spec.js
Labels: support/Repro, backport

#20695 Repro #20683: Error when filtering date by current quarter in Postgres
  frontend/test/metabase/scenarios/question/reproductions/20683-postgres-current-quarter.cy.spec.js
Labels: .CI & Tests, support/Repro

#20684 Don't consider `:field` `:join-alias` when escaping aliases
  frontend/test/metabase/scenarios/question/reproductions/20627-nested-long-names-wrong-aliases.cy.spec.js
  src/metabase/driver.clj
  src/metabase/query_processor/middleware/escape_join_aliases.clj
  test/metabase/query_processor_test/nested_queries_test.clj
Labels: backport

#20691 E2E admin l10n tests: wait for table header to be visible first
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#20671 Apply `visitQuestion` helper to the related tests
  frontend/test/__support__/e2e/helpers/e2e-misc-helpers.js
  frontend/test/metabase/scenarios/admin/audit/questions-audit.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters-sql/dashboard-filters-sql-date.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters-sql/dashboard-filters-sql-id.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters-sql/dashboard-filters-sql-location.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters-sql/dashboard-filters-sql-number.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters-sql/dashboard-filters-sql-text-category.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/parameters-embedded.cy.spec.js
  frontend/test/metabase/scenarios/downloads/reproductions/18219-temporal-units-not-formatted.cy.spec.js
  frontend/test/metabase/scenarios/downloads/reproductions/18440-remapped-display-value-dropped.cy.spec.js
  frontend/test/metabase/scenarios/downloads/reproductions/19889-native-query-export-column-order.cy.spec.js
  frontend/test/metabase/scenarios/joins/joins-2.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/16739.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/17019.cy.spec.js
  frontend/test/metabase/scenarios/native/native_subquery.cy.spec.js
  frontend/test/metabase/scenarios/native/reproductions/20044-no-data-sees-explore-results.cy.spec.js
  frontend/test/metabase/scenarios/permissions/reproductions/14873-regextract-in-sandboxed-table.cy.spec.js
  frontend/test/metabase/scenarios/permissions/sandboxes.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/public/question.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/18978-18977-nested-question-nodata-user.cy.spec.js
  frontend/test/metabase/scenarios/sharing/alert/alert-permissions.cy.spec.js
  frontend/test/metabase/scenarios/sharing/alert/alert-types.cy.spec.js
  frontend/test/metabase/scenarios/sharing/alert/email-alert.cy.spec.js
  frontend/test/metabase/scenarios/sharing/public.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/17547.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/18352-subscription-int64-value-card.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#20687 Always show database sync buttons
  frontend/src/metabase/admin/databases/components/DatabaseEditApp/Sidebar/Sidebar.jsx
  frontend/src/metabase/admin/databases/components/DatabaseEditApp/Sidebar/Sidebar.unit.spec.js
Labels: backport

#20680 Handle nulls in ListField filter
  frontend/src/metabase/components/ListField/ListField.tsx
Labels: backport

#20696 Repro #19744: Custom Column after aggregation causes dashboard filtering to be very limited
  frontend/test/metabase/scenarios/custom-column/reproductions/19744-cc-after-aggregation-limited-filters.cy.spec.js
Labels: .CI & Tests, support/Repro

#20721 Embedding e2e group
  .circleci/config.yml
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
  frontend/test/metabase/scenarios/embedding/admin-embedding-settings.cy.spec.js
  frontend/test/metabase/scenarios/embedding/embedding-dashboard.cy.spec.js
  frontend/test/metabase/scenarios/embedding/parameters-embedded.cy.spec.js
  frontend/test/metabase/scenarios/embedding/reproductions/20393-public-dashboard-nested-card-with-parameters.cy.spec.js
  frontend/test/metabase/scenarios/embedding/reproductions/20438-dashboard-filter-single-value.cy.spec.js
  frontend/test/metabase/scenarios/embedding/reproductions/20634-locked-parameters-in-embedded-question.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#20678 Handle missing `dataset_query` when trying to map parameter targets to fields
  frontend/src/metabase/parameters/utils/dashboards.js
  frontend/src/metabase/parameters/utils/dashboards.unit.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/20656-dashboard-breaks-for-user-without-card-permissions.cy.spec.js
Labels: backport

#20726 Export and use `SAMPLE_DB_ID` for snapshot generation
  frontend/test/__support__/e2e/cypress_data.js
  frontend/test/snapshot-creators/default.cy.snap.js
Labels: Type:Tech Debt, .CI & Tests

#20707 Run unadded additional dashcard series using card query endpoint
  frontend/src/metabase/dashboard/actions.js
  frontend/src/metabase/dashboard/components/DashCard.jsx
  frontend/test/metabase/scenarios/dashboard/reproductions/20637-add-series-to-dashcard.cy.spec.js
Labels: support/Repro, backport

#20729 Replace hard coded ids in E2E custom commands and helpers
  frontend/test/__support__/e2e/commands/api/question.js
  frontend/test/__support__/e2e/commands/permissions/sandboxTable.js
  frontend/test/__support__/e2e/commands/permissions/updatePermissions.js
  frontend/test/__support__/e2e/helpers/e2e-ad-hoc-question-helpers.js
Labels: Type:Tech Debt, .CI & Tests

#20738 Fix a flake where Cypress cannot click "Exit admin"
  frontend/test/metabase/scenarios/smoketest/admin_setup.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#20741 Global E2E Config: Solve circular dependency issue in helpers
  frontend/test/__support__/e2e/commands/permissions/sandboxTable.js
  frontend/test/__support__/e2e/cypress_data.js
  frontend/test/__support__/e2e/helpers/e2e-ad-hoc-question-helpers.js
  frontend/test/__support__/e2e/helpers/e2e-database-metadata-helpers.js
  frontend/test/snapshot-creators/default.cy.snap.js
Labels: Type:Tech Debt, .CI & Tests

#20734 Replace hard coded sample database id in ALL e2e tests
  frontend/test/metabase-visual/static-visualizations/funnel.cy.spec.js
  frontend/test/metabase-visual/static-visualizations/line-area-bar-combo.cy.spec.js
  frontend/test/metabase-visual/static-visualizations/progress-bar.cy.spec.js
  frontend/test/metabase-visual/static-visualizations/waterfall.cy.spec.js
  frontend/test/metabase-visual/visualizations/bar.cy.spec.js
  frontend/test/metabase-visual/visualizations/funnel.cy.spec.js
  frontend/test/metabase-visual/visualizations/line.cy.spec.js
  frontend/test/metabase-visual/visualizations/row.cy.spec.js
  frontend/test/metabase-visual/visualizations/scatter.cy.spec.js
  frontend/test/metabase-visual/visualizations/waterfall.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/editor.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/localization.cy.spec.js
  frontend/test/metabase/scenarios/binning/binning-options.cy.spec.js
  frontend/test/metabase/scenarios/binning/binning-reproductions.cy.spec.js
  frontend/test/metabase/scenarios/custom-column/custom-column.cy.spec.js
  frontend/test/metabase/scenarios/custom-column/reproductions/19744-cc-after-aggregation-limited-filters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/permissions.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/x-rays.cy.spec.js
  frontend/test/metabase/scenarios/downloads/reproductions/18382-old-syntax-missing-renamed-columns.cy.spec.js
  frontend/test/metabase/scenarios/downloads/reproductions/18440-remapped-display-value-dropped.cy.spec.js
  frontend/test/metabase/scenarios/downloads/reproductions/18573-remapped-fields-not-renamed.cy.spec.js
  frontend/test/metabase/scenarios/downloads/reproductions/18729-date-formatting-x-of-y.cy.spec.js
  frontend/test/metabase/scenarios/embedding/parameters-embedded.cy.spec.js
  frontend/test/metabase/scenarios/joins/joins-2.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/15460.cy.spec.js
  frontend/test/metabase/scenarios/native/reproductions/12439-click-on-legend-breaks-ui.cy.spec.js
  frontend/test/metabase/scenarios/permissions/sandboxes.cy.spec.js
  frontend/test/metabase/scenarios/question/filter.cy.spec.js
  frontend/test/metabase/scenarios/question/internal/question.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
  frontend/test/metabase/scenarios/question/settings.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/18669-test-email-with-parameters.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/bar_chart.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/combo.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/line_chart.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/maps.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/pie_chart.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/18976-pivot-table-columns.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/scalar.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/scatter.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/waterfall.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#20746 Remove legacy EE hard coded version info
  frontend/test/__support__/e2e/cypress.js
  frontend/test/metabase/scenarios/embedding/admin-embedding-settings.cy.spec.js
  version.json
Labels: Type:Tech Debt, .CI & Tests

#20753 Embedding cleanup: Enable premium embedding token tests
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/text-box.cy.spec.js
  frontend/test/metabase/scenarios/embedding/admin-embedding-settings.cy.spec.js
  frontend/test/metabase/scenarios/embedding/embedding-dashboard.cy.spec.js
  frontend/test/metabase/scenarios/embedding/embedding-premium-token.cy.spec.js
  frontend/test/metabase/scenarios/embedding/embedding-snippets.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#20761 Add embedding smoke tests when embedding is disabled
  frontend/test/metabase/scenarios/embedding/embedding-smoketests.cy.spec.js
Labels: .CI & Tests

#20751 Handle legacy Field filter template tags that did not specify `:widget-type`
  shared/src/metabase/mbql/normalize.cljc
  shared/test/metabase/mbql/normalize_test.cljc
  test/metabase/query_processor_test/parameters_test.clj
Labels: backport

#20764 Add embedding smoke tests when embedding is enabled
  frontend/test/metabase/scenarios/embedding/embedding-smoketests.cy.spec.js
Labels: .CI & Tests
