Repository metabase/metabase, pull requests merged in 2022-05, with the labels that each got.

#22278 Hide navbar in fullscreen dashboard
  frontend/src/metabase/dashboard/hoc/DashboardControls.jsx
Labels: backport

#22274 Fix FK drills for native models overwriting metadata
  frontend/src/metabase-lib/lib/Question.ts
  frontend/src/metabase/dashboard/actions.js
  frontend/src/metabase/modes/components/drill/ObjectDetailDrill.jsx
  frontend/src/metabase/query_builder/actions.js
  frontend/src/metabase/redux/metadata.js
  frontend/src/metabase/redux/metadata.unit.spec.js
  frontend/test/__support__/e2e/commands/api/dashboard.js
  frontend/test/metabase-lib/lib/Question.unit.spec.js
  frontend/test/metabase/modes/components/drill/ObjectDetailDrill.unit.spec.js
  frontend/test/metabase/scenarios/models/helpers/e2e-models-metadata-helpers.js
  frontend/test/metabase/scenarios/models/models-metadata.cy.spec.js
Labels: backport

#22320 Unskip repro for #20517
  frontend/test/metabase/scenarios/models/reproductions/20517-edit-metadata-empty-description.cy.spec.js
Labels: backport

#22298 docs - adds note on deleting databases
  docs/administration-guide/data-permissions.md
Labels: Type:Documentation, backport

#22286 docs - minor edits
  docs/accessibility.md
  docs/administration-guide/06-collections.md
  docs/administration-guide/10-single-sign-on.md
  docs/administration-guide/application-permissions.md
  docs/administration-guide/secure-database-connections-with-ssl-certificates.md
  docs/administration-guide/ssh-tunnel-for-database-connections.md
  docs/code-reviews.md
  docs/contributing.md
  docs/developers-guide/driver-changelog.md
  docs/developers-guide/drivers/plugins.md
  docs/developers-guide/e2e-tests.md
  docs/developers-guide/frontend.md
  docs/enterprise-guide/data-sandboxes.md
  docs/enterprise-guide/saml-auth0.md
  docs/operations-guide/handling-timezones.md
  docs/operations-guide/running-metabase-on-azure.md
  docs/operations-guide/running-metabase-on-debian.md
  docs/troubleshooting-guide/cant-see-tables.md
  docs/troubleshooting-guide/permissions.md
  docs/troubleshooting-guide/saml.md
  docs/troubleshooting-guide/sandboxing.md
  docs/troubleshooting-guide/timezones.md
  docs/users-guide/03-basic-exploration.md
  docs/users-guide/05-visualizing-results.md
  docs/users-guide/14-x-rays.md
  docs/users-guide/account-settings.md
  docs/users-guide/events-and-timelines.md
  docs/users-guide/models.md
  docs/users-guide/referencing-saved-questions-in-queries.md
  docs/users-guide/sql-snippets.md
Labels: Type:Documentation, backport

#22269 Hide "Add another series" button when there are no series to add
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/test/metabase/scenarios/visualizations/reproductions/11249-add-more-series-no-columns.cy.spec.js
Labels: support/Repro, backport

#22327 Fix data selector drops list of database schemas
  frontend/src/metabase/selectors/metadata.js
  frontend/test/metabase/scenarios/question/reproductions/22285-schema-picker.cy.spec.js
Labels: support/Repro, backport

#22321 Fix several bugs in relative datetime filters
  frontend/src/metabase/lib/query_time.js
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/DateUnitSelector.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/RelativeDatePicker.tsx
  frontend/test/metabase/scenarios/filters/relative-datetime.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/helpers/e2e-date-filter-helpers.js
Labels: support/Repro, backport

#22311 Repro #22293: Non-admin database manager can delete database using the API
  frontend/test/metabase/scenarios/permissions/database-details-permissions.cy.spec.js
  frontend/test/metabase/scenarios/permissions/details-permissions.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#22308 Complete the support for "All Time" in the time-series filter
  frontend/src/metabase/modes/components/TimeseriesFilterWidget.jsx
  frontend/src/metabase/query_builder/components/filters/pickers/LegacyDatePicker/DatePicker.jsx
  frontend/test/metabase/scenarios/question/reproductions/22247-timeseries-filter-all-time.cy.spec.js
Labels: support/Repro

#22335 Backport: Don't hard-code timeout in Druid driver
  modules/drivers/druid/src/metabase/driver/druid.clj
  modules/drivers/druid/src/metabase/driver/druid/query_processor.clj
  modules/drivers/druid/test/metabase/driver/druid/client_test.clj
  modules/drivers/druid/test/metabase/driver/druid/query_processor_test.clj
Labels: auto-backported

#22323 Fix relative datetime filter colors
  frontend/src/metabase/query_builder/components/filters/FilterPopover.styled.tsx
  frontend/src/metabase/query_builder/components/filters/FilterPopover.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/ExcludeDatePicker.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/RelativeDatePicker.styled.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/RelativeDatePicker.tsx
Labels: backport

#22264 Wrapping Radio Group in ChartSettings
  frontend/src/metabase/core/components/Radio/Radio.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetFieldMetadataSidebar/DatasetFieldMetadataSidebar.styled.jsx
  frontend/src/metabase/visualizations/components/ChartSettings.jsx
  frontend/src/metabase/visualizations/components/ChartSettings.styled.tsx
Labels: backport

#22342 Revert "Fix changing column order/visibility via sidebar is inconsistent"
  frontend/src/metabase/query_builder/selectors.js
  frontend/src/metabase/visualizations/components/settings/ChartSettingOrderedColumns.jsx
  frontend/src/metabase/visualizations/visualizations/Table.jsx
  frontend/test/metabase/scenarios/question/settings.cy.spec.js
Labels: backport

#22346 Hover states in relative datetime filtering are inconsistent in sidebar
  frontend/src/metabase/components/Calendar.css
  frontend/src/metabase/components/Calendar.styled.tsx
  frontend/src/metabase/components/Calendar.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/DatePicker.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/DatePickerHeader.styled.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/DatePickerShortcuts.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/RangeDatePicker.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/SingleDatePicker.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/SpecificDatePicker.tsx
Labels: backport

#22294 docs - update login troubleshooting
  docs/administration-guide/04-managing-users.md
  docs/troubleshooting-guide/cant-log-in.md
  docs/troubleshooting-guide/ldap.md
Labels: Type:Documentation, backport

#22304 When MB_ENABLE_EMBEDDING is set show correct embedding settings UI
  frontend/src/metabase/admin/settings/components/SettingsSetting.jsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingLegalese.jsx
  frontend/src/metabase/admin/settings/components/widgets/SettingToggle.jsx
  frontend/src/metabase/admin/settings/containers/SettingsEditorApp.jsx
  frontend/src/metabase/admin/settings/selectors.js
Labels: backport

#22358 [E2E] Simplify download permissions tests
  frontend/test/metabase/scenarios/permissions/download-permissions.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#22367 Fix removing the field type in data reference
  frontend/src/metabase/reference/components/Field.jsx
  frontend/test/metabase/scenarios/onboarding/reference/reproductions/5276-remove-field-type.cy.spec.js
Labels: support/Repro, backport

#22363 fix **User filter** field
  docs/administration-guide/10-single-sign-on.md
Labels: Type:Documentation, backport

#22326 Adding Trivy code scanner
  .github/workflows/uberjar.yml
Labels: .CI & Tests

#22385 Fix relative filters for non-english locale
  frontend/src/metabase/lib/query_time.js
Labels: support/Repro, backport

#22349 Reproduce issue 22206
  frontend/test/metabase/scenarios/visualizations/reproductions/22206-add-remove-column.cy.spec.js
Labels: support/Repro

#22393 [E2E] Experiment running `custom-column` test group as PR check
  .github/workflows/e2e-tests.yml
Labels: .CI & Tests, QA

#22392 docs - update api docs
  docs/api-documentation.md
Labels: Type:Documentation, backport

#22410 E2E] Remove `joins` check from CCI
  .circleci/config.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#22366 Handle not available Notifications API
  frontend/src/metabase/dashboard/containers/DashboardApp.jsx
  frontend/src/metabase/hooks/use-web-notification.ts
  frontend/src/metabase/query_builder/containers/QueryBuilder.jsx
Labels: backport

#22415 Fix cancelling the native query via shortcut
  frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx
  frontend/test/metabase/scenarios/visualizations/reproductions/11727-cancel-native-query-shortcut.cy.spec.js
Labels: support/Repro, backport

#22383 XLSX formatting for temporal breakout fields
  src/metabase/query_processor/streaming/xlsx.clj
  test/metabase/query_processor/streaming/xlsx_test.clj
Labels: backport

#22424 updates docstring to correct formatting
  src/metabase/api/collection.clj
Labels: backport

#22435 Repro #22408: Block permissions obstructing download permissions set to "No"
  frontend/test/metabase/scenarios/permissions/download-permissions.cy.spec.js
Labels: .CI & Tests, support/Repro

#22405 [E2E] Experiment running `dashboard` test group as PR check
  .github/workflows/e2e-tests.yml
Labels: .CI & Tests, QA

#22436 remove misleading permissions tooltip
  enterprise/frontend/src/metabase-enterprise/feature_level_permissions/permission-management/download-permission.ts
Labels: backport

#22419 Add a delay for showing tooltips for relative date filters
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/RelativeDatePicker.tsx
Labels: backport

#22433 Fix visualization and settings buttons are visible for questions that use blocked db
  frontend/src/metabase/query_builder/components/view/ViewFooter.jsx
  frontend/test/metabase/scenarios/permissions/admin-permissions.cy.spec.js
Labels: backport

#22452 Repros #22447, #22449, #22450: illogical UI elements for nodata user
  frontend/test/metabase/scenarios/permissions/reproductions/22447-illogical-UI-elements-for-nodata.cy.spec.js
Labels: .CI & Tests, support/Repro

#22289 fix issue with missing parameter options in cloned, targeted dashboard
  frontend/src/metabase/dashboard/components/ClickMappings.jsx
  frontend/src/metabase/lib/click-behavior.js
  frontend/test/metabase/lib/click-behavior.unit.spec.js
Labels: backport

#22475 docs - link fix
  docs/users-guide/writing-sql.md
Labels: Type:Documentation, backport

#22468 [E2E] Add download permission tests for native questions
  frontend/test/metabase/scenarios/permissions/download-permissions.cy.spec.js
Labels: .CI & Tests, backport

#22422 Fix visualization settings for raw tables
  frontend/src/metabase/query_builder/selectors.js
  frontend/test/metabase/scenarios/visualizations/reproductions/22359-raw-tables-vis-settings.cy.spec.js
Labels: support/Repro, backport

#22456 Make it possible to convert relative filters to expressions
  frontend/src/metabase/lib/expressions/config.js
  frontend/src/metabase/lib/expressions/helper_text_strings.js
  frontend/test/metabase/lib/expressions/suggest.unit.spec.js
Labels: backport

#22167 Fix :Postgres :day-of-week extracts coming back as 0..6 instead of 1..7
  modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj
  src/metabase/driver.clj
  src/metabase/driver/common.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql/query_processor.clj
  test/metabase/query_processor_test/date_bucketing_test.clj
Labels: backport

#22479 extends ring.protocols/StreamableResponseBody to keywords (#22025)
  src/metabase/async/api_response.clj
Labels: auto-backported

#22426 Clear download perms when setting block perms
  enterprise/backend/src/metabase_enterprise/advanced_permissions/models/permissions.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/models/permissions_test.clj
  frontend/test/metabase/scenarios/permissions/download-permissions.cy.spec.js
  src/metabase/models/permissions.clj
Labels: backport

#22470 Fix permission bugs
  frontend/src/metabase/collections/components/NewCollectionItemMenu.jsx
  frontend/src/metabase/collections/containers/CollectionContent.jsx
  frontend/src/metabase/collections/containers/CollectionHeader.tsx
  frontend/src/metabase/components/Tooltip/Tooltip.tsx
  frontend/src/metabase/core/components/Link/Link.tsx
  frontend/src/metabase/lib/errors.ts
  frontend/src/metabase/query_builder/components/view/ViewHeader.jsx
  frontend/test/metabase/scenarios/permissions/reproductions/22447-illogical-UI-elements-for-nodata.cy.spec.js
Labels: backport

#22471 Pass parameter value to disabled TextWidget
  frontend/src/metabase/parameters/components/ParameterValueWidget.jsx
Labels: backport

#22472 Add moderated_status icon to recents list
  frontend/src/metabase/nav/components/RecentsList.jsx
Labels: backport

#22334 Fix unneeded query nesting when removing all expressions
  frontend/src/metabase-lib/lib/queries/StructuredQuery.ts
  frontend/test/__support__/e2e/helpers/e2e-notebook-helpers.js
  frontend/test/metabase/scenarios/custom-column/reproductions/19745-cc-nested-query-remove-expressions.cy.spec.js
Labels: support/Repro

#22368 Fix LDAP requires `uid` to do group sync
  enterprise/backend/test/metabase_enterprise/enhancements/integrations/ldap_test.clj
  src/metabase/integrations/ldap/default_implementation.clj
  test/metabase/api/session_test.clj
  test/metabase/integrations/ldap_test.clj
  test_resources/ldap.ldif
Labels: backport

#22526 Backport "Fix LDAP requires uid to do group sync
  enterprise/backend/test/metabase_enterprise/enhancements/integrations/ldap_test.clj
  src/metabase/integrations/ldap/default_implementation.clj
  test/metabase/api/session_test.clj
  test/metabase/integrations/ldap_test.clj
  test_resources/ldap.ldif
Labels: auto-backported

#22499 Better logs for rotate encryption key + better command error messages…
  src/metabase/cmd.clj
  src/metabase/cmd/rotate_encryption_key.clj
  test/metabase/cmd_test.clj
Labels: auto-backported

#22481 Fix automagic dashboards for queries with source queries
  frontend/test/metabase/scenarios/dashboard/x-rays.cy.spec.js
  src/metabase/api/automagic_dashboards.clj
  src/metabase/automagic_dashboards/core.clj
  src/metabase/automagic_dashboards/filters.clj
  src/metabase/sync/analyze/classifiers/name.clj
  test/metabase/api/automagic_dashboards_test.clj
Labels: backport

#22523 Fully specify identifier in Postgres JSON describe nested field column query (#22448)
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
  test/metabase/driver/postgres_test.clj
Labels: backport

#22440 [E2E] Remove `custom-column` check from CCI
  .circleci/config.yml
Labels: .CI & Tests, QA

#22596 Round date values when filtering relative dates
  frontend/src/metabase/lib/query_time.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/22482-round-relative-ranges.cy.spec.js
Labels: support/Repro, backport

#22607 turn on logging in quartz to watch for connection allocation
  resources/log4j2.xml
Labels: backport

#22635 Fix embedded dashboard is not being updated after changing params
  frontend/src/metabase/dashboard/utils.js
  frontend/test/metabase/scenarios/sharing/reproductions/22524-public-dashboard-updates-after-changing-parameters.cy.spec.js
Labels: support/Repro, backport

#22605 Fix a typo in the component name
  frontend/src/metabase/components/form/FormField.jsx
  frontend/src/metabase/components/form/FormFieldDescription.tsx
Labels: backport

#22618 Add test for embedding Metabase with locale parameter
  frontend/test/metabase/scenarios/embedding/embedding-questions.cy.spec.js
Labels: .CI & Tests

#22649 Start task scheduler at end of startup.
  src/metabase/core.clj
  src/metabase/task.clj
Labels: backport

#22664 Upgrade Cypress to `v9.6.1`
  package.json
  yarn.lock
Labels: .CI & Tests, backport

#22506 do not show restore sample database button to non-admins
  frontend/src/metabase/admin/databases/components/DatabaseList/DatabaseList.jsx
  frontend/src/metabase/admin/databases/components/DatabaseList/DatabaseList.unit.spec.jsx
  frontend/src/metabase/admin/databases/components/DatabaseList/index.ts
  frontend/src/metabase/admin/databases/containers/DatabaseListApp.jsx
  frontend/src/metabase/entities/databases.js
Labels: backport

#22662 Stopgap to fix #22636 until full implementation
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
Labels: backport

#22622 No open redirects for enterprise SSO's
  enterprise/backend/src/metabase_enterprise/sso/api/sso.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/jwt.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/saml.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/sso_utils.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/saml_test.clj
Labels: backport

#22674 do not show restore sample database button to non-admins (#22506)
  frontend/src/metabase/admin/databases/components/DatabaseList/DatabaseList.jsx
  frontend/src/metabase/admin/databases/components/DatabaseList/DatabaseList.unit.spec.jsx
  frontend/src/metabase/admin/databases/components/DatabaseList/index.ts
  frontend/src/metabase/admin/databases/containers/DatabaseListApp.jsx
  frontend/src/metabase/entities/databases.js
Labels: auto-backported

#22680 Don't reschedule syncs on startup
  src/metabase/api/database.clj
  src/metabase/sync/schedules.clj
  src/metabase/task/sync_databases.clj
  test/metabase/models/database_test.clj
  test/metabase/task/sync_databases_test.clj
Labels: backport

#22703 Manual Backport of PR E2E Checks
  .github/workflows/e2e-tests.yml
Labels: .CI & Tests, QA

#22707 Record startup times
  dev/src/dev.clj
  src/metabase/analytics/stats.clj
  src/metabase/core.clj
  src/metabase/public_settings.clj
  test/metabase/analytics/stats_test.clj
Labels: backport

#22708 Don't reschedule syncs on startup (#22680)
  src/metabase/api/database.clj
  src/metabase/sync/schedules.clj
  src/metabase/task/sync_databases.clj
  test/metabase/models/database_test.clj
  test/metabase/task/sync_databases_test.clj
Labels: auto-backported

#22710 docs - updates api docs
  docs/api-documentation.md
  docs/api/activity.md
  docs/api/alert.md
  docs/api/automagic-dashboards.md
  docs/api/bookmark.md
  docs/api/card.md
  docs/api/collection.md
  docs/api/dashboard.md
  docs/api/database.md
  docs/api/dataset.md
  docs/api/ee/advanced-permissions-application.md
  docs/api/ee/audit-app-user.md
  docs/api/ee/content-management-review.md
  docs/api/ee/sandbox-gtap.md
  docs/api/ee/sandbox-table.md
  docs/api/ee/sandbox-user.md
  docs/api/ee/sso.md
  docs/api/email.md
  docs/api/embed.md
  docs/api/field.md
  docs/api/geojson.md
  docs/api/ldap.md
  docs/api/login-history.md
  docs/api/metric.md
  docs/api/native-query-snippet.md
  docs/api/notify.md
  docs/api/permissions.md
  docs/api/premium-features.md
  docs/api/preview-embed.md
  docs/api/public.md
  docs/api/pulse.md
  docs/api/revision.md
  docs/api/search.md
  docs/api/segment.md
  docs/api/session.md
  docs/api/setting.md
  docs/api/setup.md
  docs/api/slack.md
  docs/api/table.md
  docs/api/task.md
  docs/api/tiles.md
  docs/api/timeline-event.md
  docs/api/timeline.md
  docs/api/transform.md
  docs/api/user.md
  docs/api/util.md
  src/metabase/api/common/internal.clj
  src/metabase/cmd/endpoint_dox.clj
  src/metabase/cmd/resources/api-intro.md
  test/metabase/cmd/endpoint_dox_test.clj
  test/metabase/util/schema_test.clj
Labels: Type:Documentation, auto-backported

#22713 Repro #22700: Custom expression aggregation does not work in metrics
  frontend/test/metabase/scenarios/admin/datamodel/metrics.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#22719 Repro #22527: Negative Y axis points not rendered on scatter plot
  frontend/test/metabase/scenarios/visualizations/reproductions/22527-scatter-negative-values-not-rendered.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#22724 Translations for x.43.1
  locales/bg.po
  locales/ca.po
  locales/cs.po
  locales/de.po
  locales/es.po
  locales/fa.po
  locales/fr.po
  locales/id.po
  locales/it.po
  locales/ja.po
  locales/metabase.pot
  locales/nb.po
  locales/nl.po
  locales/pl.po
  locales/pt-BR.po
  locales/ru.po
  locales/sk.po
  locales/sr.po
  locales/sv.po
  locales/tr.po
  locales/uk.po
  locales/vi.po
  locales/zh-HK.po
  locales/zh-TW.po
  locales/zh.po
Labels: Customization/i18n, backport

#22743 Fix inability to save to sub-collections when having no access to the parent (#22663)
  frontend/src/metabase-types/api/collection.ts
  frontend/src/metabase/containers/ItemPicker.jsx
  frontend/src/metabase/dashboard/components/add-card-sidebar/QuestionPicker.jsx
  frontend/src/metabase/entities/collections/collections.js
  frontend/src/metabase/lib/collections.ts
  frontend/src/metabase/lib/collections.unit.spec.ts
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
  package.json
  yarn.lock
Labels: auto-backported

#22734 URIDecode exported question filenames
  frontend/src/metabase/components/DownloadButton.jsx
Labels: backport

#22763 fix click behavior permission error
  frontend/src/metabase-lib/lib/Question.ts
  frontend/test/metabase/scenarios/dashboard/click-behavior.cy.spec.js
Labels: backport

#22813 docs - small update
  docs/api-documentation.md
  docs/api/card.md
  docs/api/database.md
  docs/api/ee/sandbox-gtap.md
  docs/api/ee/sandbox-table.md
  docs/api/geojson.md
  docs/api/ldap.md
  docs/api/persist.md
  docs/api/table.md
  docs/enterprise-guide/start.md
  src/metabase/cmd/endpoint_dox.clj
  test/metabase/cmd/endpoint_dox_test.clj
Labels: Type:Documentation, backport

#22817 docs - small docs update
  docs/api-documentation.md
  docs/api/ee/sandbox-gtap.md
  docs/api/geojson.md
  docs/api/ldap.md
  docs/enterprise-guide/start.md
  src/metabase/cmd/endpoint_dox.clj
  test/metabase/cmd/endpoint_dox_test.clj
Labels: Type:Documentation

#22821 docs-user-guides
  docs/users-guide/12-data-model-reference.md
  docs/users-guide/writing-sql.md
Labels: Type:Documentation, backport

#22818 docs - typo
  test/metabase/cmd/endpoint_dox_test.clj
Labels: Type:Documentation

#22840 Ensure Groups element is Visible on Admin
  frontend/test/metabase/scenarios/admin/people/group-managers.cy.spec.js
Labels: .CI & Tests, QA

#22866 fix usage of invalid value for scatter bubbles
  frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js
  frontend/test/metabase-visual/visualizations/scatter.cy.spec.js
Labels: backport, visual

#22779 Handle `nil` cache during initial cache population
  src/metabase/models/setting.clj
  src/metabase/models/setting/cache.clj
Labels: backport

#22894 Repro #22768: Cannot view Object Detail of non-numeric IDs
  frontend/test/metabase/scenarios/visualizations/object_detail.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#22898 Repro #22872: Pivot Table cannot sort by metric
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#22900 Add M1 section to the dev guide
  docs/developers-guide/build.md
Labels: Type:Documentation

#22895 Allow Google Platform Library authentication
  frontend/src/metabase/lib/auth.js
Labels: backport

#22907 [E2E] Remove `dashboard` group from checks on CCI
  .circleci/config.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#22911 [E2E] Experiment running models test group as PR check
  .github/workflows/e2e-tests.yml
Labels: .CI & Tests, QA

#22802 Improve parameter's date widget components (a few of them)
  frontend/src/metabase/components/Calendar.stories.tsx
  frontend/src/metabase/components/DateAllOptionsWidget/DateAllOptionsWidget.tsx
  frontend/src/metabase/components/DateAllOptionsWidget/DateWidget.styled.tsx
  frontend/src/metabase/components/DateAllOptionsWidget/index.ts
  frontend/src/metabase/components/DateRangeWidget/DateRangeWidget.tsx
  frontend/src/metabase/components/DateRangeWidget/DateRangeWidget.unit.spec.js
  frontend/src/metabase/components/DateRangeWidget/index.ts
  frontend/src/metabase/components/DateSingleWidget/DateSingleWidget.tsx
  frontend/src/metabase/components/DateSingleWidget/DateSingleWidget.unit.spec.tsx
  frontend/src/metabase/components/DateSingleWidget/index.ts
  frontend/src/metabase/parameters/components/ParameterValueWidget.jsx
Labels: visual

#22875 fix updating field name and description in data model
  frontend/src/metabase/admin/datamodel/containers/FieldApp.jsx
Labels: backport

#22874 hide back button on the relative date time picker when open from a table column header
  frontend/src/metabase/query_builder/components/filters/FilterPopover.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/DatePicker.tsx
  frontend/test/metabase/scenarios/filters/relative-datetime.cy.spec.js
Labels: backport

#22930 Fix ordering in the dev guide documentation on how to build Metabase
  docs/developers-guide/build.md
Labels: Type:Documentation

#22764 Remove field-specific code from ParameterValueWidget
  frontend/src/metabase/parameters/components/ParameterValueWidget.jsx
  frontend/src/metabase/parameters/components/WidgetStatusIcon/WidgetStatusIcon.tsx
  frontend/src/metabase/parameters/components/WidgetStatusIcon/index.ts
  frontend/src/metabase/parameters/utils/fields.js
  frontend/src/metabase/parameters/utils/fields.unit.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/parameters.cy.spec.js
Labels: visual

#22922 Repros #22859: Multi-level nested questions with joins incorrect column aliasing
  frontend/test/metabase/scenarios/joins/reproductions/22859-multi-nested-joins-wrong-aliasing.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#22927 Repro #22715: Model's column identifier is not respected
  frontend/test/metabase/scenarios/models/reproductions/22715-remapped-values-override-column-identifier.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#22945 Repro #22929: Circle size not respected on a scatter chart
  frontend/test/metabase/scenarios/visualizations/scatter.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#22948 Repro #22822: Do not offer "Explore results" unless the database supports it
  frontend/test/metabase/scenarios/native/reproductions/22822-explore-results-unsupported-databases.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#22956 Fix typo fitler -> filter
  frontend/src/metabase/query_builder/actions/ui.js
  frontend/src/metabase/visualizations/lib/graph/brush.js
Labels: Type:Tech Debt

#22955 Expand repro for #22715 with additional scenario
  frontend/test/metabase/scenarios/models/reproductions/22715-remapped-values-override-column-identifier.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#22986 Do not run E2E tests using CircleCI on `master`
  .circleci/config.yml
Labels: Type:Tech Debt, .CI & Tests

#22975 [E2E] Simplify and fix failing repro for #22247
  frontend/test/metabase/scenarios/question/reproductions/22247-timeseries-filter-all-time.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#22769 Limit of length of row for json parsing (fixes #22636 for most cases)
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
  test/metabase/driver/sql_jdbc/sync/describe_table_test.clj
Labels: backport

#22893 [E2E] Remove `models` check from CCI
  .circleci/config.yml
Labels: .CI & Tests, backport, QA

#23009 [E2E] Run OSS-specific tests on PR
  .github/workflows/e2e-tests.yml
  frontend/test/metabase/scenarios/admin/databases/list.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
  frontend/test/metabase/scenarios/admin/troubleshooting/help.cy.spec.js
  frontend/test/metabase/scenarios/embedding/embedding-premium-token.cy.spec.js
  frontend/test/metabase/scenarios/embedding/embedding-smoketests.cy.spec.js
  frontend/test/metabase/scenarios/organization/moderation-collection.cy.spec.js
  frontend/test/metabase/scenarios/permissions/admin-permissions.cy.spec.js
  frontend/test/metabase/scenarios/sharing/subscriptions.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#23012 Increase E2E job timeout on PRs
  .github/workflows/e2e-tests.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#23014 [E2E] Remove `embedding` group from checks on CCI
  .circleci/config.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#23015 [E2E] Experiment running `sharing` test group as PR check
  .github/workflows/e2e-tests.yml
Labels: Type:Tech Debt, .CI & Tests

#23020 🍒 Manual backport E2E changes
  .circleci/config.yml
  .github/workflows/e2e-tests.yml
  frontend/test/metabase/scenarios/admin/databases/list.cy.spec.js
  frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js
  frontend/test/metabase/scenarios/admin/troubleshooting/help.cy.spec.js
  frontend/test/metabase/scenarios/embedding/embedding-premium-token.cy.spec.js
  frontend/test/metabase/scenarios/embedding/embedding-smoketests.cy.spec.js
  frontend/test/metabase/scenarios/organization/moderation-collection.cy.spec.js
  frontend/test/metabase/scenarios/permissions/admin-permissions.cy.spec.js
  frontend/test/metabase/scenarios/sharing/subscriptions.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, auto-backported

#22998 manual backport of #22769 onto 43
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
  test/metabase/driver/sql_jdbc/sync/describe_table_test.clj
Labels: auto-backported

#23010 fix permissions diff shows saved questions
  frontend/src/metabase/admin/permissions/selectors/data-permissions/diff.ts
Labels: backport

#23038 Skip flaky FE unit test
  frontend/src/metabase/parameters/utils/mbql.unit.spec.js
Labels: Type:Tech Debt, .CI & Tests

#23036 [E2E] Fix line-toolbar-toolips flake
  frontend/test/metabase/scenarios/visualizations/line-bar-tooltips.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#23042 [E2E] Experiment running `question` test group as PR check
  .github/workflows/e2e-tests.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#22954 docs - update saml & sso
  docs/README.md
  docs/administration-guide/10-single-sign-on.md
  docs/administration-guide/sso.md
  docs/enterprise-guide/authenticating-with-saml.md
  docs/enterprise-guide/saml-auth0.md
  docs/enterprise-guide/saml-google.md
  docs/enterprise-guide/saml-keycloak.md
  docs/enterprise-guide/start.md
Labels: Type:Documentation, backport

#22981 Fix deadlock in pivot table connection management
  .dir-locals.el
  src/metabase/query_processor/context/default.clj
  src/metabase/query_processor/pivot.clj
Labels: backport

#23043 fix dashboard parameters tablet layout
  frontend/src/metabase/parameters/components/ParameterWidget.css
Labels: backport

#23046 fix login form mobile layout
  frontend/src/metabase/auth/components/AuthLayout/AuthLayout.styled.tsx
Labels: backport

#22962 Include field annotations for native queries too
  src/metabase/query_processor/middleware/annotate.clj
  src/metabase/query_processor/middleware/resolve_fields.clj
Labels: .Backend, Actions/

#23069 Bump transitive com.google.code.gson/gson
  modules/drivers/bigquery-cloud-sdk/deps.edn
  modules/drivers/googleanalytics/deps.edn
Labels: backport
