Repository metabase/metabase, pull requests merged in 2022-06, with the labels that each got.

#23067 Add :entity_id property and use it on all models with entity_id fields
  deps.edn
  src/metabase/models/card.clj
  src/metabase/models/collection.clj
  src/metabase/models/dashboard.clj
  src/metabase/models/dashboard_card.clj
  src/metabase/models/dimension.clj
  src/metabase/models/interface.clj
  src/metabase/models/metric.clj
  src/metabase/models/native_query_snippet.clj
  src/metabase/models/pulse.clj
  src/metabase/models/segment.clj
  src/metabase/models/timeline.clj
  src/metabase/util.clj
  test/metabase/api/alert_test.clj
  test/metabase/api/card_test.clj
  test/metabase/api/collection_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/field_test.clj
  test/metabase/api/metric_test.clj
  test/metabase/api/pulse_test.clj
  test/metabase/api/segment_test.clj
  test/metabase/api/table_test.clj
  test/metabase/events/revision_test.clj
  test/metabase/models/collection_test.clj
  test/metabase/models/metric_test.clj
  test/metabase/models/pulse_test.clj
  test/metabase/models/segment_test.clj
  test/metabase/test/util.clj
Labels: Operation/Serialization

#23068 fix column settings ignored
  frontend/src/metabase-lib/lib/queries/StructuredQuery.ts
  frontend/src/metabase/visualizations/components/TableInteractive.jsx
  frontend/test/metabase/scenarios/question/reproductions/23023-preview-shows-hidden-columns.cy.spec.js
Labels: support/Repro, backport

#23106 Fix print layout
  frontend/src/metabase/App.styled.tsx
  frontend/src/metabase/nav/containers/AppBar.styled.tsx
Labels: backport

#23116 allow equal or greater starting from units only
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/RelativeDatePicker.tsx
  frontend/test/metabase/scenarios/filters/relative-datetime.cy.spec.js
Labels: backport

#23123 [E2E] Simplify CircleCI Cypress workflow
  .circleci/config.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#23081 Add a test to check that all exported models have a portable unique name
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
Labels: Operation/Serialization

#23144 [E2E] Fix permissions pin flake
  frontend/test/metabase/scenarios/collections/permissions.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#23141 allow equal or greater starting from units (#23116)
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/RelativeDatePicker.tsx
  frontend/test/metabase/scenarios/filters/relative-datetime.cy.spec.js
Labels: auto-backported

#23149 Repro #22518: Changing model definition will not show changes until after browser refresh
  frontend/test/metabase/scenarios/models/reproductions/22518.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#23164 [E2E] Remove `question` group from checks on CCI
  .circleci/config.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#23165 Bump google oauth version
  modules/drivers/bigquery-cloud-sdk/deps.edn
  modules/drivers/googleanalytics/deps.edn
Labels: backport

#23169 [E2E] Experiment running `collections` test group as PR check
  .github/workflows/e2e-tests.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#23179 Upgrade Percy CLI to the latest `v1.2.1`
  package.json
  yarn.lock
Labels: Type:Tech Debt, .CI & Tests, backport

#23184 [E2E] Fix dashboard flake
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#23178 Run Percy on `master` using the default GH runners
  .github/workflows/percy.yml
Labels: Type:Tech Debt, .CI & Tests

#23166 [E2E] Rename the main workflow
  .github/workflows/e2e-main.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#21299 Record Cypress test runs only on master branch
  .github/workflows/e2e-main.yml
Labels: .CI & Tests, backport

#23196 Fix FE linter error
  frontend/test/metabase/scenarios/models/reproductions/22518.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#23193 Run E2E tests on the release branch (on push)
  .github/workflows/e2e-main.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#23203 Add Warnings component unit tests
  frontend/test/metabase/components/Warnings.unit.spec.js
Labels: .CI & Tests

#23185 do not offer expore results when a query db does not support nested queries
  frontend/src/metabase-lib/lib/queries/AtomicQuery.ts
  frontend/src/metabase-lib/lib/queries/StructuredQuery.ts
  frontend/src/metabase/query_builder/components/view/ViewHeader.jsx
  frontend/test/metabase/scenarios/native/reproductions/22822-explore-results-unsupported-databases.cy.spec.js
Labels: backport, visual

#23136 Do trivial identity for passthrough of symbols for nested field column instead of default processing
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
  test/metabase/driver/postgres_test.clj
Labels: backport

#23128 Include :features whether or not db is initialized
  src/metabase/models/database.clj
Labels: backport

#23211 [E2E] Fix group-admin flake
  frontend/test/metabase/scenarios/admin/people/group-managers.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#23209 Do not run E2E tests on release branch in CCI
  .circleci/config.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#23198 Handle time types in render code
  src/metabase/pulse/render/datetime.clj
  test/metabase/pulse/render/datetime_test.clj
Labels: backport

#23224 Adding the Starburst driver repo to docs
  docs/developers-guide-drivers.md
Labels: Type:Documentation, backport

#23233 Save query executions for cached queries (#23228)
  src/metabase/query_processor/middleware/process_userland_query.clj
  test/metabase/query_processor/middleware/cache_test.clj
Labels: auto-backported

#23237 fix custom url click behavior with the same dashboard url
  frontend/src/metabase/lib/dom.js
  frontend/src/metabase/lib/urls/questions.ts
  frontend/src/metabase/modes/components/drill/DashboardClickDrill.jsx
  frontend/src/metabase/visualizations/lib/action.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
Labels: backport

#23253 Force slack channel cache refresh when new token is saved
  src/metabase/api/slack.clj
  src/metabase/integrations/slack.clj
  test/metabase/api/slack_test.clj
  test/metabase/integrations/slack_test.clj
Labels: backport

#23260 Manual backport of #23253
  src/metabase/api/slack.clj
  src/metabase/integrations/slack.clj
  test/metabase/api/slack_test.clj
  test/metabase/integrations/slack_test.clj
Labels: auto-backported

#23263 Fix mysql humanize error
  modules/drivers/mongo/src/metabase/driver/mongo.clj
  modules/drivers/presto/src/metabase/driver/presto.clj
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  src/metabase/driver/h2.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
Labels: backport

#23151 Truncate long columns
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.css
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.styled.tsx
  frontend/src/metabase/visualizations/components/TableInteractive/index.ts
  frontend/src/metabase/visualizations/visualizations/PivotTable.jsx
  frontend/src/metabase/visualizations/visualizations/Table.jsx
  frontend/test/metabase-visual/visualizations/table.cy.spec.js
Labels: visual

#23221 Use big types when we have big JSON contents (whacks #22732)
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/driver/sql_jdbc/sync/describe_table_test.clj
Labels: backport

#23256 fix custom url click behavior with the same dashboard url (#23237)
  frontend/src/metabase/lib/dom.js
  frontend/src/metabase/lib/urls/questions.ts
  frontend/src/metabase/modes/components/drill/DashboardClickDrill.jsx
  frontend/src/metabase/visualizations/lib/action.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
Labels: auto-backported

#23249 Backport #22997 and #23136 at once
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
  test/metabase/driver/postgres_test.clj
Labels: auto-backported

#23279 fix first row object detail
  frontend/src/metabase/query_builder/selectors.js
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx
  frontend/test/metabase/scenarios/visualizations/object_detail.cy.spec.js
Labels: backport

#23287 Validate common passwords in user account settings
  frontend/src/metabase/account/password/actions.js
  frontend/src/metabase/account/password/components/UserPasswordForm/UserPasswordForm.jsx
  frontend/test/metabase/scenarios/onboarding/setup/user_settings.cy.spec.js
Labels: backport

#23304 🍒 [E2E] Fix group-admin flake (#23211)
  frontend/test/metabase/scenarios/admin/people/group-managers.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#23307 [E2E] Remove `organization` and `permissions` checks from CCI
  .circleci/config.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#23309 [E2E] Experiment running `native` test group as PR check
  .github/workflows/e2e-tests.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#23308 [E2E] Remove `collections` group from checks on CCI
  .circleci/config.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#23314 Render empty string for null boolean column results
  frontend/src/metabase/lib/formatting.js
Labels: backport

#23316 Backport password validation
  frontend/src/metabase/account/password/actions.js
  frontend/src/metabase/account/password/components/UserPasswordForm/UserPasswordForm.jsx
  frontend/test/metabase/scenarios/onboarding/setup/user_settings.cy.spec.js
Labels: auto-backported

#23321 Unbounce the checkbox
  frontend/src/metabase/core/components/CheckBox/CheckBox.styled.tsx
Labels: backport

#23320 Backport: Make Dashboard header responsive to NavBar being open
  frontend/src/metabase/components/Header.jsx
  frontend/src/metabase/components/Header.styled.tsx
  frontend/src/metabase/dashboard/containers/DashboardHeader.jsx
Labels: auto-backported

#23319 Backport: Render empty string for null boolean column results
  frontend/src/metabase/lib/formatting.js
Labels: auto-backported

#23333 docs - update sync record count
  docs/troubleshooting-guide/sync-fingerprint-scan.md
Labels: Type:Documentation

#23326 Backport #22732 fix to 43
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/driver/sql_jdbc/sync/describe_table_test.clj
Labels: auto-backported

#23342 docs - backport titles
  docs/README.md
  docs/administration-guide/02-setting-up-email.md
  docs/administration-guide/07-segments-and-metrics.md
  docs/administration-guide/11-getting-started-guide.md
  docs/administration-guide/20-custom-maps.md
  docs/administration-guide/databases/aws-rds.md
  docs/administration-guide/start.md
  docs/code-reviews.md
  docs/developers-guide/driver-changelog.md
  docs/developers-guide/e2e-tests.md
  docs/developers-guide/start.md
  docs/developers-guide/visual-studio-code.md
  docs/enterprise-guide/activating-the-enterprise-edition.md
  docs/enterprise-guide/authenticating-with-saml-azure-ad.md
  docs/enterprise-guide/authenticating-with-saml.md
  docs/enterprise-guide/full-app-embedding.md
  docs/enterprise-guide/start.md
  docs/enterprise-guide/whitelabeling.md
  docs/information-collection.md
  docs/operations-guide/configuring-application-database.md
  docs/operations-guide/enable-jmx.md
  docs/troubleshooting-guide/error-message.md
  docs/troubleshooting-guide/filters.md
  docs/troubleshooting-guide/loading-from-h2.md
  docs/troubleshooting-guide/my-dashboard-is-slow.md
  docs/troubleshooting-guide/sync-fingerprint-scan.md
  docs/users-guide/08-dashboard-filters.md
  docs/users-guide/13-sql-parameters.md
  docs/users-guide/14-x-rays.md
  docs/users-guide/dashboard-subscriptions.md
  docs/users-guide/sql-snippets.md
  docs/users-guide/start.md
Labels: Type:Documentation

#23348 Fix e2e test after introducing #23338
  frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js
Labels: .CI & Tests

#23337 Upgrade Percy CLI to the latest `v1.3.0`
  package.json
  yarn.lock
Labels: Type:Tech Debt, .CI & Tests, backport

#23329 fix getXValues fails on empty results
  frontend/src/metabase/visualizations/lib/renderer_utils.js
  frontend/test/metabase/visualizations/lib/renderer_utils.unit.spec.js
Labels: backport

#23361 [E2E] Fix native filter revision history flake
  frontend/test/metabase/scenarios/native-filters/reproductions/12581.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#23364 [E2E] Experiment running `native-filters` test group as PR check
  .github/workflows/e2e-tests.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#23363 🍒 [E2E] Fix native filter revision history flake
  frontend/test/metabase/scenarios/native-filters/reproductions/12581.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#23362 Backport ensure error on query errors
  src/metabase/query_processor/middleware/catch_exceptions.clj
  test/metabase/query_processor/middleware/catch_exceptions_test.clj
Labels: auto-backported

#23278 JSON query in postgres now walks identifier tree if one encountered (fixes #22967)
  src/metabase/driver/postgres.clj
  test/metabase/driver/postgres_test.clj
Labels: backport

#23327 Make first name and last name optional in user forms
  frontend/src/metabase-types/api/user.ts
  frontend/src/metabase/entities/users/forms.js
  frontend/src/metabase/home/homepage/components/HomeGreeting/HomeGreeting.tsx
  frontend/test/metabase/scenarios/admin/people/people.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/setup/user_settings.cy.spec.js
  frontend/test/metabase/scenarios/smoketest/admin.cy.spec.js
Labels: .CI & Tests

#23384 Manual backport for #23278
  src/metabase/driver/postgres.clj
  test/metabase/driver/postgres_test.clj
Labels: auto-backported

#23398 Fix time filter
  frontend/src/metabase/query_builder/components/filters/FilterPopover.tsx
  frontend/src/metabase/query_builder/components/filters/FilterPopoverFooter.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/LegacyDatePicker/HoursMinutesInput.jsx
  frontend/src/metabase/query_builder/components/filters/pickers/TimePicker/TimePicker.jsx
  frontend/src/metabase/query_builder/components/filters/pickers/TimePicker/TimePicker.styled.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/TimePicker/index.ts
  frontend/test/metabase/scenarios/filters/reproductions/22730-table-column-time-filter.cy.spec.js
Labels: backport

#23389 docs - update maps
  docs/users-guide/05-visualizing-results.md
Labels: Type:Documentation, backport

#23388 docs - update encryption
  docs/operations-guide/encrypting-database-details-at-rest.md
Labels: Type:Documentation, backport

#23426 [E2E] Remove `native-filters` group from checks on CCI
  .circleci/config.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#23425 Do not run backend tests on unrelated changes
  .github/workflows/backend.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#23434 Revert "Do not run backend tests on unrelated changes (#23425)"
  .github/workflows/backend.yml
Labels: Type:Tech Debt, .CI & Tests

#23430 [E2E] Remove basic admin setup flow from smoke tests
  frontend/test/metabase/scenarios/smoketest/admin_setup.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#23438 [E2E] Experiment running `onboarding` test group as PR check
  .github/workflows/e2e-tests.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#23416 Fix flakes in repro for 22227
  frontend/test/metabase/scenarios/filters/relative-datetime.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#23440 [E2E] Fix `filters` flakes
  frontend/test/metabase/scenarios/filters/filter.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/22730-table-column-time-filter.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#23442 [E2E] Experiment running `filters` test group as PR check
  .github/workflows/e2e-tests.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#23446 🍒 Backport `filters` fixes and changes
  .github/workflows/e2e-tests.yml
  frontend/test/metabase/scenarios/filters/filter.cy.spec.js
  frontend/test/metabase/scenarios/filters/relative-datetime.cy.spec.js
  frontend/test/metabase/scenarios/filters/reproductions/22730-table-column-time-filter.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, auto-backported

#23332 Prevent SSO users from editing their info
  enterprise/frontend/src/metabase-enterprise/auth/index.js
  frontend/src/metabase/account/app/components/AccountHeader/AccountHeader.jsx
  frontend/src/metabase/account/app/components/AccountHeader/AccountHeader.styled.jsx
  frontend/src/metabase/account/app/components/AccountHeader/AccountHeader.unit.spec.js
  frontend/src/metabase/admin/people/components/GroupMembersTable/GroupMembersTable.tsx
  frontend/src/metabase/admin/people/components/PeopleListRow.jsx
  frontend/src/metabase/collections/components/BaseTableItem.jsx
  frontend/src/metabase/components/LastEditInfoLabel.js
  frontend/src/metabase/entities/users/forms.js
  frontend/src/metabase/lib/user.ts
  frontend/src/metabase/plugins/builtin/auth/google.js
  frontend/src/metabase/plugins/builtin/auth/ldap.js
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/redux/user.js
  frontend/test/metabase/lib/user.unit.spec.ts
  frontend/test/metabase/scenarios/onboarding/setup/user_settings.cy.spec.js
Labels: .CI & Tests

#23370 fixes flaky visual tests
  frontend/src/metabase/visualizations/components/FunnelNormal.jsx
  frontend/test/__support__/e2e/cypress.js
  frontend/test/__support__/e2e/helpers/e2e-visual-tests-helpers.js
  frontend/test/metabase-visual/dashboard/parameters-widget.cy.spec.js
  frontend/test/metabase-visual/models/editor.cy.spec.js
  frontend/test/metabase-visual/notebook/notebook.cy.spec.js
  frontend/test/metabase-visual/onboarding/urls.cy.spec.js
  frontend/test/metabase-visual/visualizations/bar.cy.spec.js
  frontend/test/metabase-visual/visualizations/funnel.cy.spec.js
  frontend/test/metabase-visual/visualizations/line.cy.spec.js
  frontend/test/metabase-visual/visualizations/row.cy.spec.js
  frontend/test/metabase-visual/visualizations/scatter.cy.spec.js
  frontend/test/metabase-visual/visualizations/waterfall.cy.spec.js
Labels: visual

#23463 [E2E] Remove `admin` spec from smoke tests
  frontend/test/metabase/scenarios/onboarding/setup/setup.cy.spec.js
  frontend/test/metabase/scenarios/smoketest/admin.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#23458 [E2E] Remove `admin_setup` spec from smoke tests
  frontend/test/metabase/scenarios/admin/datamodel/hide_tables.cy.spec.js
  frontend/test/metabase/scenarios/smoketest/admin_setup.cy.spec.js
  frontend/test/metabase/scenarios/smoketest/hello.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#23471 🍒 Backport smoketest removal
  .circleci/config.yml
  frontend/test/metabase/scenarios/admin/datamodel/hide_tables.cy.spec.js
  frontend/test/metabase/scenarios/smoketest/README.md
  frontend/test/metabase/scenarios/smoketest/admin.cy.spec.js
  frontend/test/metabase/scenarios/smoketest/admin_setup.cy.spec.js
  frontend/test/metabase/scenarios/smoketest/user.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, auto-backported

#23006 docs - update jar link
  docs/operations-guide/running-the-metabase-jar-file.md
  docs/operations-guide/upgrading-metabase.md
Labels: Type:Documentation, backport

#23473 Writeback add http action
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  frontend/src/metabase/entities/actions.js
  src/metabase/api/action.clj
  src/metabase/api/card.clj
  src/metabase/api/routes.clj
  src/metabase/models.clj
  src/metabase/models/action.clj
  src/metabase/models/card.clj
  src/metabase/query_processor/writeback.clj
  test/metabase/api/action_test.clj
  test/metabase/api/card_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/emitter_test.clj
  test/metabase/cmd/copy_test.clj
Labels: .Backend, Actions/

#23475 fix tooltip overflow
  frontend/src/metabase/components/Tooltip/Tooltip.tsx
  frontend/src/metabase/visualizations/components/ChartTooltip/ChartTooltip.tsx
Labels: backport

#23522 docs - known issues
  docs/troubleshooting-guide/bugs.md
  docs/troubleshooting-guide/cant-log-in.md
  docs/troubleshooting-guide/index.md
  docs/troubleshooting-guide/known-issues.md
  docs/troubleshooting-guide/ldap.md
  docs/troubleshooting-guide/requesting-new-features.md
  docs/troubleshooting-guide/sql.md
Labels: Type:Documentation, backport

#23523 Fix alerts and subscriptions bugs
  frontend/src/metabase-types/api/index.ts
  frontend/src/metabase-types/api/notifications.ts
  frontend/src/metabase/components/PopoverWithTrigger/ControlledPopoverWithTrigger.tsx
  frontend/src/metabase/components/SelectList/BaseSelectListItem.jsx
  frontend/src/metabase/components/SelectList/SelectList.tsx
  frontend/src/metabase/components/SelectList/SelectListItem.jsx
  frontend/src/metabase/components/SelectList/SelectListItem.styled.jsx
  frontend/src/metabase/components/SelectList/index.js
  frontend/src/metabase/components/TextInput/TextInput.tsx
  frontend/src/metabase/components/select-list/SelectList.jsx
  frontend/src/metabase/components/select-list/index.js
  frontend/src/metabase/core/components/AutocompleteInput/AutocompleteInput.stories.tsx
  frontend/src/metabase/core/components/AutocompleteInput/AutocompleteInput.styled.tsx
  frontend/src/metabase/core/components/AutocompleteInput/AutocompleteInput.tsx
  frontend/src/metabase/core/components/AutocompleteInput/AutocompleteInput.unit.spec.tsx
  frontend/src/metabase/core/components/AutocompleteInput/index.ts
  frontend/src/metabase/dashboard/components/add-card-sidebar/QuestionList.jsx
  frontend/src/metabase/dashboard/components/add-card-sidebar/QuestionList.styled.jsx
  frontend/src/metabase/dashboard/components/add-card-sidebar/QuestionPicker.jsx
  frontend/src/metabase/lib/compose-event-handlers.ts
  frontend/src/metabase/pulse/components/PulseEditChannels.jsx
  frontend/src/metabase/pulse/components/RecipientPicker.jsx
  frontend/src/metabase/query_builder/components/DataSelector.styled.jsx
  frontend/src/metabase/query_builder/components/saved-question-picker/SavedQuestionList.styled.jsx
  frontend/src/metabase/sharing/components/AddEditSidebar/AddEditEmailSidebar.jsx
  frontend/src/metabase/sharing/components/AddEditSidebar/AddEditSlackSidebar.jsx
  frontend/src/metabase/sharing/components/AddEditSidebar/ChannelFields.jsx
  frontend/src/metabase/sharing/components/PulsesListSidebar.jsx
  frontend/src/metabase/sharing/components/SlackChannelField/SlackChannelField.tsx
  frontend/src/metabase/sharing/components/SlackChannelField/index.ts
  frontend/test/metabase/scenarios/sharing/subscriptions.cy.spec.js
Labels: visual

#23536 Removing Uberjar workflow cancel on concurrency
  .github/workflows/uberjar.yml
Labels: .CI & Tests

#23544 docs - troubleshooting models
  docs/troubleshooting-guide/index.md
  docs/troubleshooting-guide/models.md
  docs/users-guide/models.md
Labels: Type:Documentation, backport

#23542 Join slack channels with slack-id (#23495)
  src/metabase/api/pulse.clj
  src/metabase/integrations/slack.clj
  src/metabase/task/refresh_slack_channel_user_cache.clj
  test/metabase/api/pulse_test.clj
  test/metabase/api/slack_test.clj
  test/metabase/integrations/slack_test.clj
Labels: auto-backported

#23480 Run Percy inside E2E main workflow
  .github/workflows/e2e-main.yml
  .github/workflows/percy.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#23551 Remove diff logic from Percy job on `master`
  .github/workflows/e2e-main.yml
Labels: Type:Tech Debt, .CI & Tests

#23550 Ignore all unit tests in E2E workflows
  .github/workflows/e2e-main.yml
  .github/workflows/e2e-tests.yml
Labels: Type:Tech Debt, .CI & Tests

#23552 🍒 Manual backport of E2E/Percy related changes
  .circleci/config.yml
  .github/workflows/e2e-main.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/percy.yml
Labels: Type:Tech Debt, .CI & Tests, auto-backported

#23558 [CI] Increase `be-tests-java` timeout
  .github/workflows/backend.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#23562 Repro #23421: `visualization_settings` can break UI
  frontend/test/metabase/scenarios/models/reproductions/23421-visualization-settins-breaks-ui.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#23564 🍒 Manual backport of #23562
  frontend/test/__support__/e2e/helpers/e2e-ui-elements-helpers.js
  frontend/test/metabase/scenarios/models/reproductions/23421-visualization-settins-breaks-ui.cy.spec.js
Labels: .CI & Tests, auto-backported

#23553 Remove all remaining E2E and frontend bits from CCI
  .circleci/config.yml
  .github/workflows/e2e-tests.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#23567 Bring back `static-viz` to CircleCI
  .circleci/config.yml
Labels: Type:Tech Debt, .CI & Tests

#23561 Hide download button visibility toggle on Pro/EE dashboard sharing
  frontend/src/metabase/public/components/widgets/AdvancedSettingsPane.jsx
  frontend/src/metabase/public/components/widgets/DisplayOptionsPane.jsx
  frontend/test/metabase/scenarios/embedding/embedding-snippets.cy.spec.js
  frontend/test/metabase/scenarios/embedding/embedding-snippets.js
Labels: .CI & Tests

#23587 [E2E] Replace hard coded field IDs in visual tests
  frontend/test/metabase-visual/admin/colors.cy.spec.js
  frontend/test/metabase-visual/visualizations/line.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#23593 Repro #20809: Wrong aliasing in nesting based on question with filter to implicit/explicit table
  frontend/test/metabase/scenarios/question/reproductions/20809-nesting-explicit-implicit-filter.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#23579 docs - troubleshooting data sources
  docs/administration-guide/01-managing-databases.md
  docs/troubleshooting-guide/cant-see-tables.md
  docs/troubleshooting-guide/datawarehouse.md
  docs/troubleshooting-guide/error-message.md
  docs/troubleshooting-guide/index.md
  docs/troubleshooting-guide/my-dashboard-is-slow.md
  docs/troubleshooting-guide/timeout.md
Labels: Type:Documentation, backport

#23615 Unskip repro for #18021 and consolidate `recently-viewed` spec
  frontend/test/metabase/scenarios/onboarding/search/recently-viewed.cy.spec.js
  frontend/test/metabase/scenarios/organization/reproductions/18021-verified-badge-not-visible-in-recents.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#23634 🍒 Unskip repro for #18021 and consolidate `recently-viewed` spec (#23615)
  frontend/test/metabase/scenarios/onboarding/search/recently-viewed.cy.spec.js
  frontend/test/metabase/scenarios/organization/reproductions/18021-verified-badge-not-visible-in-recents.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, auto-backported

#23603 Add `mochawesome` report to Cypress
  .github/workflows/e2e-main.yml
  .github/workflows/e2e-tests.yml
  frontend/test/__runner__/cypress-runner-run-tests.js
  frontend/test/__support__/e2e/cypress.js
  frontend/test/__support__/e2e/cypress.json
  frontend/test/__support__/e2e/integration/visit-dashboard.cy.spec.js
  package.json
  yarn.lock
Labels: QA
