Repository metabase/metabase, pull requests merged in 2022-08, with the labels that each got.

#24439 Fix Table Names Not Appearing in Dimension Option Lists
  frontend/src/metabase-lib/lib/Dimension.ts
  frontend/src/metabase-lib/lib/DimensionOptions/DimensionOptions.ts
Labels: backport

#24367 Dont tokenize single input values
  frontend/src/metabase/components/TokenField/TokenField.tsx
  frontend/src/metabase/components/TokenField/TokenField.unit.spec.js
  frontend/src/metabase/parameters/components/widgets/StringInputWidget/StringInputWidget.unit.spec.tsx
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterItem/BulkFilterItem.unit.spec.tsx
  frontend/test/metabase/scenarios/filters/reproductions/9339-clipboard-numeric-filter.cy.spec.js
Labels: backport

#24473 [E2E] Fix failing dashboard test
  frontend/test/metabase/scenarios/dashboard/text-parameters.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#24436 Properly format date-time property for snowplow events
  snowplow/iglu-client-embedded/schemas/com.metabase/task/jsonschema/1-0-0
  src/metabase/analytics/snowplow.clj
  src/metabase/models/task_history.clj
  src/metabase/util/date_2.clj
  test/metabase/analytics/snowplow_test.clj
  test/metabase/models/task_history_test.clj
Labels: backport

#24442 Hide Popover suggestions on item removal
  frontend/src/metabase/components/TokenField/TokenField.tsx
Labels: backport

#24485 Update package.json deps
  yarn.lock
Labels: backport

#24482 Bump jetty-server to 9.4.48.v20220622
  deps.edn
Labels: backport

#24493 Bulk Filter Modal: Side Nav
  frontend/src/metabase/core/components/Tab/Tab.styled.tsx
  frontend/src/metabase/core/components/TabList/TabList.stories.tsx
  frontend/src/metabase/core/components/TabList/TabList.styled.tsx
  frontend/src/metabase/core/components/TabList/TabList.tsx
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterModal.styled.tsx
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterModal.tsx
Labels: backport

#24492 Bulk Filter Modal: New Field Layout
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterItem/BulkFilterItem.tsx
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterList/BulkFilterList.styled.tsx
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterList/BulkFilterList.tsx
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterModal.styled.tsx
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterSelect/BulkFilterSelect.styled.tsx
  frontend/src/metabase/query_builder/components/filters/modals/InlineCategoryPicker/InlineCategoryPicker.styled.tsx
  frontend/src/metabase/query_builder/components/filters/modals/InlineCategoryPicker/InlineCategoryPicker.tsx
  frontend/src/metabase/query_builder/components/filters/modals/InlineCategoryPicker/InlineCategoryPicker.unit.spec.tsx
  frontend/src/metabase/query_builder/components/filters/modals/InlineCategoryPicker/LargeCategoryFilterPicker.tsx
  frontend/src/metabase/query_builder/components/filters/modals/InlineCategoryPicker/SimpleCategoryFilterPicker.tsx
  frontend/src/metabase/query_builder/components/filters/modals/InlineCategoryPicker/constants.ts
  frontend/src/metabase/query_builder/components/filters/modals/InlineDatePicker/InlineDatePicker.styled.ts
  frontend/src/metabase/query_builder/components/filters/modals/InlineOperatorSelector/InlineOperatorSelector.styled.ts
  frontend/src/metabase/query_builder/components/filters/modals/InlineOperatorSelector/InlineOperatorSelector.tsx
  frontend/src/metabase/query_builder/components/filters/modals/InlineValuePicker/InlineValuePicker.styled.ts
  frontend/src/metabase/query_builder/components/filters/modals/InlineValuePicker/InlineValuePicker.tsx
  frontend/src/metabase/query_builder/components/filters/modals/InlineValuePicker/utils.ts
  frontend/test/__support__/e2e/helpers/e2e-bi-basics-helpers.js
  frontend/test/metabase/scenarios/filters/filter-bulk.cy.spec.js
  frontend/test/metabase/scenarios/filters/filter.cy.spec.js
Labels: backport

#24487 Show "Starting from" filters only when expressions are supported
  frontend/src/metabase-lib/lib/metadata/Database.ts
  frontend/src/metabase/components/DateAllOptionsWidget/DateAllOptionsWidget.tsx
  frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/DatePicker.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/RelativeDatePicker.tsx
  frontend/src/metabase/query_builder/components/notebook/lib/steps.js
Labels: backport

#24470 🍒 Backport light input borders
  frontend/src/metabase/admin/datamodel/components/database/ColumnItem/ColumnItem.styled.tsx
  frontend/src/metabase/components/InputBlurChange.styled.tsx
  frontend/src/metabase/components/TextInput/TextInput.styled.tsx
  frontend/src/metabase/components/TokenField/TokenField.styled.tsx
  frontend/src/metabase/core/components/Input/Input.styled.tsx
  frontend/src/metabase/core/components/SelectButton/SelectButton.styled.tsx
  frontend/src/metabase/css/components/form.css
  frontend/src/metabase/css/core/colors.css
  frontend/src/metabase/css/core/inputs.css
  frontend/src/metabase/dashboard/containers/DashboardHeader.styled.jsx
  frontend/src/metabase/lib/colors/palette.ts
  frontend/src/metabase/query_builder/components/QuestionActions.styled.tsx
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterSelect/BulkFilterSelect.styled.tsx
Labels: backport

#24457 [E2E] Consolidate dashboard filters on nested questions
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-nested.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/parameters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/12614-nested-show-fields.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/13186-nested-all-filter-options.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/17212-nested-id-filter.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#24496 reverts the ability to connect public dashboards and questions in the click behavior
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar.jsx
  frontend/src/metabase/modes/components/drill/DashboardClickDrill.jsx
  frontend/test/metabase/scenarios/dashboard/reproductions/17160-click-behavior-multiple-options.cy.spec.js
Labels: backport

#24503 Fix column duplication when adding a new breakout
  frontend/src/metabase-lib/lib/Question.ts
  frontend/test/metabase/scenarios/binning/binning-reproductions.cy.spec.js
Labels: backport

#24509 Fix certain dashboard header button icons not centered
  frontend/src/metabase/core/components/Button/Button.tsx
  frontend/src/metabase/dashboard/components/DashboardActions.jsx
  frontend/src/metabase/dashboard/components/RefreshWidget.jsx
Labels: backport

#24494 Enforce bigint for all int fields derived from JSON instead of doing more complete refactor
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
  test/metabase/driver/mysql_test.clj
  test/metabase/driver/postgres_test.clj
Labels: backport

#24507 exclude archived collections from navbar api call
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer.tsx
Labels: backport

#24491 Optional blocks in Markdown cards
  shared/src/metabase/shared/parameters/parameters.cljc
  shared/test/metabase/shared/parameters/parameters_test.cljc
Labels: backport

#24489 open urls with the site-url origin in the same tab
  enterprise/frontend/src/metabase-enterprise/auth/middleware/session-middleware.js
  frontend/src/metabase/lib/dom.js
Labels: backport

#24511 docs - revert gcp docs
  docs/administration-guide/databases/postgresql.md
Labels: Type:Documentation, backport

#24475 exception for none and block
  enterprise/frontend/src/metabase-enterprise/feature_level_permissions/permission-management/data-model-permission.unit.spec.ts
  frontend/src/metabase/admin/permissions/selectors/confirmations.ts
Labels: backport

#24513 [Manual backport] Fix certain dashboard header button icons not centered
  frontend/src/metabase/core/components/Button/Button.tsx
  frontend/src/metabase/dashboard/components/DashboardActions.jsx
  frontend/src/metabase/dashboard/components/RefreshWidget.jsx
Labels: auto-backported

#24521 Even tighter bulk filter spacing
  frontend/src/metabase/components/TokenField/TokenField.styled.tsx
  frontend/src/metabase/components/TokenFieldItem/TokenFieldItem.styled.ts
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterList/BulkFilterList.styled.tsx
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterModal.styled.tsx
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterSelect/BulkFilterSelect.styled.tsx
  frontend/src/metabase/query_builder/components/filters/modals/InlineDatePicker/InlineDatePicker.styled.ts
  frontend/src/metabase/query_builder/components/filters/modals/InlineOperatorSelector/InlineOperatorSelector.styled.ts
  frontend/src/metabase/query_builder/components/filters/modals/InlineValuePicker/InlineValuePicker.styled.ts
  frontend/src/metabase/query_builder/components/filters/pickers/BooleanPicker/BooleanPicker.styled.tsx
Labels: backport

#24517 Fixing null error when value is null and isCustom is true
  frontend/src/metabase/admin/settings/components/widgets/ModelCachingScheduleWidget/ModelCachingScheduleWidget.jsx
Labels: backport

#24526 Bulk filter Modal: Make search visible
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterFieldSearch.tsx
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterModal.styled.tsx
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterModal.tsx
Labels: backport

#24531 Change model cache on/off button copy
  enterprise/frontend/src/metabase-enterprise/model_persistence/index.ts
Labels: backport

#24472 [E2E] Consolidate `dashboard-filters` tests
  frontend/test/__support__/e2e/helpers/e2e-dashboard-helpers.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-date.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-date.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-sql-date.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-sql-date.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-text-category.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/parameters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/12720-no-data-permissions-connected-filter.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/12985-dropdown-search.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/13150-additional-card-queries-for-all-filters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/13960-do-not-preserve-cleared-default-filter-on-refresh.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/15119-nodata-should-not-use-dash-filters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/15689-allow-multiple-selections.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/15695-do-not-limit-number-of-results.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/16103-additional-requests-dropdown.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/16112-nodata-should-use-dashboard-filters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/17139-do-not-reset-filters-on-edit.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/6660-sub-day-resolutions-relative-date.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, support/Repro

#24480 bump snowflake
  modules/drivers/snowflake/deps.edn
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
Labels: backport

#24539 🤦‍♀️
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterModal.tsx
Labels: backport

#24431 Migrate bg-brand-dark-hover to JS colors
  frontend/src/metabase/css/core/colors.css
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar.jsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar.styled.tsx
Labels: visual

#24540 docs - 44 updates
  docs/users-guide/04-asking-questions.md
  docs/users-guide/07-dashboards.md
  docs/users-guide/images/asking-questions/bulk-filter-modal.png
Labels: Type:Documentation, backport

#24502 Repro #24500: Corrupted dashboard filter makes it impossible to view the question
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/24500-gracefully-deal-with-corrupted-filter.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#24558 🍒 Backport E2E dashboard filters optimization
  frontend/test/__support__/e2e/helpers/e2e-dashboard-helpers.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-date.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-date.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-location.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-location.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-nested.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-number.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-number.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-sql-date.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-sql-date.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-sql-location.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-sql-location.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-sql-number.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-sql-number.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-sql-text-category.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-sql-text-category.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-text-category.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-text-category.js
  frontend/test/metabase/scenarios/dashboard-filters/helpers/e2e-dashboard-filter-data-objects.js
  frontend/test/metabase/scenarios/dashboard-filters/helpers/e2e-dashboard-filter-sql-data-objects.js
  frontend/test/metabase/scenarios/dashboard-filters/parameters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/12614-nested-show-fields.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/12720-no-data-permissions-connected-filter.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/12985-dropdown-search.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/13150-additional-card-queries-for-all-filters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/13186-nested-all-filter-options.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/13960-do-not-preserve-cleared-default-filter-on-refresh.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/15119-nodata-should-not-use-dash-filters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/15689-allow-multiple-selections.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/15695-do-not-limit-number-of-results.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/16103-additional-requests-dropdown.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/16112-nodata-should-use-dashboard-filters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/17139-do-not-reset-filters-on-edit.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/17212-nested-id-filter.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/6660-sub-day-resolutions-relative-date.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/8030-reload-card-without-change.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#24542 bump apache hive 3.1.3
  modules/drivers/sparksql/deps.edn
Labels: backport

#24559 Avoid using lookaround in regex during optional block parsing
  shared/src/metabase/shared/parameters/parameters.cljc
Labels: backport

#24564 update api docs
  docs/api/dashboard.md
  docs/api/ee/content-management-review.md
  docs/api/ee/sandbox-gtap.md
  docs/api/ee/sandbox-table.md
  docs/api/ee/sandbox-user.md
  docs/api/ee/sso.md
  docs/api/native-query-snippet.md
Labels: Type:Documentation

#24560 docs - model caching
  docs/administration-guide/05-setting-permissions.md
  docs/enterprise-guide/authenticating-with-saml.md
  docs/enterprise-guide/tools.md
  docs/troubleshooting-guide/loading-from-h2.md
  docs/users-guide/expressions/coalesce.md
  docs/users-guide/images/models/model-caching-custom.png
  docs/users-guide/models.md
Labels: Type:Documentation, backport

#24551 Fix ExplicitSize for printing
  frontend/src/metabase/components/ExplicitSize.jsx
  frontend/src/metabase/css/dashboard.css
Labels: backport

#24545 22831 fix (group-by time bucketing on replacements for json aliases)
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql/query_processor.clj
  test/metabase/driver/postgres_test.clj
Labels: backport

#24573 docs - cache update
  docs/users-guide/models.md
Labels: Type:Documentation, backport

#24574 Use `linux/amd64` as platform for Temurin images
  bin/docker/Dockerfile
Labels: .CI & Tests, backport

#24579 Set `CookieSpecs/STANDARD` on HttpClient for Snowplow
  src/metabase/analytics/snowplow.clj
Labels: backport

#24444 docs - case
  docs/users-guide/expressions-list.md
  docs/users-guide/expressions/case.md
  docs/users-guide/expressions/coalesce.md
Labels: Type:Documentation, backport

#24586 Fix incorrect log when creating a card
  src/metabase/api/card.clj
Labels: backport

#24580 Ensure to use original query not persisted query when converting
  src/metabase/api/dataset.clj
Labels: backport

#24591 use leading debounce for visualizations
  frontend/src/metabase/visualizations/components/Visualization.jsx
Labels: backport

#24588 Support click behavior in Gauge and Progress visualizations
  frontend/src/metabase/visualizations/visualizations/Gauge.jsx
  frontend/src/metabase/visualizations/visualizations/Gauge.styled.tsx
  frontend/src/metabase/visualizations/visualizations/Progress.jsx
  frontend/test/metabase/scenarios/dashboard/click-behavior.cy.spec.js
Labels: support/Repro, backport

#24599 docs - update ssl
  docs/administration-guide/secure-database-connections-with-ssl-certificates.md
Labels: Type:Documentation, backport

#24483 Fix failing migrations
  resources/migrations/000_migrations.yaml
Labels: backport

#24582 Add Support for Case-insensitive `contains` dashboard filters
  frontend/src/metabase/meta/Card.js
  src/metabase/driver/common/parameters/operators.clj
Labels: backport

#24581 Fix multi-level nested queries with joins
  frontend/test/metabase/scenarios/joins/reproductions/22859-multi-nested-joins-wrong-aliasing.cy.spec.js
  src/metabase/query_processor/util/add_alias_info.clj
  test/metabase/query_processor_test/nested_queries_test.clj
Labels: backport

#24404 Recursively nest expressions
  frontend/test/metabase/scenarios/custom-column/reproductions/23862-cc-group-by-nested.cy.spec.js
  src/metabase/query_processor/util/nest_query.clj
  test/metabase/driver/sql/query_processor_test.clj
  test/metabase/query_processor/util/nest_query_test.clj
  test/metabase/query_processor_test/nested_queries_test.clj
Labels: backport

#24613 Backport a block of Serdes v2 changes, fixing embedded MBQL
  enterprise/backend/test/metabase_enterprise/serialization/v2/extract_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj
  src/metabase/models/card.clj
  src/metabase/models/dashboard_card.clj
  src/metabase/models/metric.clj
  src/metabase/models/segment.clj
  src/metabase/models/serialization/util.clj
  test/metabase/test/generate.clj
Labels: backport

#24247 Set timezone when truncating dates
  frontend/test/metabase/scenarios/visualizations/reproductions/16170-line-mongo-replace-missing-values.cy.spec.js
  modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj
  modules/drivers/mongo/test/metabase/driver/mongo/query_processor_test.clj
Labels: backport

#24615 docs - update "can't view or edit" guide
  docs/troubleshooting-guide/cant-view-or-edit.md
Labels: Type:Documentation, backport

#24554 Setting timeout to missing step on Build workflow
  .github/workflows/build-scripts.yml
Labels: .CI & Tests, backport

#24623 docs - update models
  docs/users-guide/models.md
Labels: Type:Documentation, backport

#24418 [Actions] Add generic with-action for action tests
  .clj-kondo/config.edn
  test/metabase/actions/test_util.clj
  test/metabase/api/action_test.clj
  test/metabase/api/emitter_test.clj
  test/metabase/models/action_test.clj
  test/metabase/models/emitter_test.clj
Labels: .Backend, Actions/

#24632 show browse data button when iframed
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarView.tsx
Labels: backport

#24643 Bump Mariadb driver to 2.7.6
  deps.edn
Labels: backport

#24644 Bump postgres to 42.3.6
  deps.edn
Labels: backport

#24587 Fix can't drilldown on null date dimension record
  frontend/src/metabase/modes/lib/actions.js
Labels: backport

#24658 docs - params
  docs/enterprise-guide/full-app-embedding.md
Labels: Type:Documentation, backport

#24661 Updating Structured Query BreakoutOptions to use dimensions rather th…
  frontend/src/metabase-lib/lib/queries/StructuredQuery.ts
  frontend/test/metabase-lib/lib/queries/StructuredQuery.unit.spec.js
Labels: auto-backported

#24667 Fix spelling of :notification-retry-randomization-factor setting
  src/metabase/pulse.clj
Labels: backport

#24669 fixing dashboard sticky params when embedded
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.styled.jsx
  frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.js
  frontend/src/metabase/dashboard/containers/DashboardApp.jsx
Labels: backport

#24676 Allow decimal settings values
  frontend/src/metabase/admin/settings/components/widgets/SettingInput.jsx
  frontend/src/metabase/admin/settings/components/widgets/SettingInput.tsx
  frontend/src/metabase/admin/settings/components/widgets/SettingInput.unit.spec.tsx
  frontend/src/metabase/components/InputBlurChange.styled.tsx
Labels: backport

#24677 fix editing filter updates wrong filter
  frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.tsx
  frontend/test/metabase/scenarios/filters/reproductions/24664-multiple-filters-editing.cy.spec.js
Labels: support/Repro, backport

#24622 Fix Column Filters for remapped model columns
  frontend/src/metabase/modes/components/drill/ColumnFilterDrill.jsx
Labels: backport

#24684 docs - link updates
  docs/administration-guide/sso.md
  docs/data-modeling/field-types.md
  docs/data-modeling/metadata-editing.md
  docs/databases/connections/google-analytics.md
  docs/developers-guide-drivers.md
  docs/enterprise-guide/authenticating-with-saml.md
  docs/troubleshooting-guide/bigquery-drive.md
  docs/troubleshooting-guide/data-permissions.md
  docs/troubleshooting-guide/sync-fingerprint-scan.md
  docs/users-guide/05-visualizing-results.md
  docs/users-guide/13-sql-parameters.md
Labels: Type:Documentation, backport

#24685 Properly Display Remapped Categories in Bulk Filter Modal
  frontend/src/metabase/query_builder/components/filters/modals/InlineCategoryPicker/InlineCategoryPicker.tsx
  frontend/src/metabase/query_builder/components/filters/modals/InlineCategoryPicker/InlineCategoryPicker.unit.spec.tsx
  frontend/src/metabase/query_builder/components/filters/modals/InlineCategoryPicker/SimpleCategoryFilterPicker.tsx
Labels: backport

#24267 updating question parameters on mobile
  frontend/src/metabase-types/types/Parameter.ts
  frontend/src/metabase/parameters/components/ParameterWidget.css
  frontend/src/metabase/parameters/components/SyncedParametersList/index.js
  frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx
  frontend/src/metabase/query_builder/components/ResponsiveParametersList.styled.tsx
  frontend/src/metabase/query_builder/components/ResponsiveParametersList.tsx
  frontend/src/metabase/query_builder/components/view/View.styled.tsx
  frontend/test/metabase/scenarios/native-filters/sql-filters.cy.spec.js
Labels: backport

#24691 [E2E] Fix a flake in 17160
  frontend/test/metabase/scenarios/dashboard/reproductions/17160-click-behavior-multiple-options.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#24702 docs - embed restructure
  docs/administration-guide/15-whitelabeling.md
  docs/administration-guide/application-permissions.md
  docs/dashboards/start.md
  docs/embedding/customize-embeds.md
  docs/embedding/fonts.md
  docs/embedding/full-app-embedding.md
  docs/embedding/images/01-enabling.png
  docs/embedding/images/02-share-icon.png
  docs/embedding/images/03-enable-question.png
  docs/embedding/images/04-preview.png
  docs/embedding/images/05-code.png
  docs/embedding/images/06-locked.png
  docs/embedding/images/Untitled.png
  docs/embedding/images/action-buttons.png
  docs/embedding/images/action-menu.png
  docs/embedding/images/additional-info.png
  docs/embedding/images/chart-colors.png
  docs/embedding/images/dashboard-sharing-icon.png
  docs/embedding/images/font-and-download.png
  docs/embedding/images/metabot.png
  docs/embedding/images/no-top-no-side.png
  docs/embedding/images/powered-by-metabase.png
  docs/embedding/images/side-nav.png
  docs/embedding/images/top-nav.png
  docs/embedding/images/user-interface-colors.png
  docs/embedding/introduction.md
  docs/embedding/start.md
  docs/embedding/whitelabeling.md
  docs/users-guide/04-asking-questions.md
Labels: Type:Documentation, backport

#24688 fixing button variant mapping for dashcard parameter filters
  frontend/src/metabase/dashboard/components/DashCardCardParameterMapper.jsx
Labels: backport

#24704 bump postgres to 42.4.1
  deps.edn
Labels: backport

#24707 [E2E] consolidate joins
  frontend/test/metabase/scenarios/joins/joins-2.cy.spec.js
  frontend/test/metabase/scenarios/joins/joins.cy.spec.js
  frontend/test/metabase/scenarios/joins/reproductions/13468-ui-overlay-after-save.cy.spec.js
  frontend/test/metabase/scenarios/question/new.cy.spec.js
  frontend/test/metabase/scenarios/question/summarization.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#24693 Sql autocomplete options
  frontend/src/metabase/admin/settings/selectors.js
  frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.jsx
  frontend/src/metabase/query_builder/selectors.js
  frontend/src/metabase/services.js
  frontend/test/metabase/scenarios/native/reproductions/20625-prefix-match.cy.spec.js
  src/metabase/api/database.clj
  test/metabase/api/database_test.clj
Labels: backport

#24570 [Actions] Simplify emitter schema model
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  resources/migrations/000_migrations.yaml
  src/metabase/api/emitter.clj
  src/metabase/models.clj
  src/metabase/models/action.clj
  src/metabase/models/emitter.clj
  test/metabase/actions/test_util.clj
  test/metabase/api/card_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/cmd/copy_test.clj
Labels: .Backend, Actions/

#24717 [E2E] Fix segments/metrics failures that started after #24682
  frontend/test/metabase/scenarios/admin/datamodel/metrics.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/segments.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#24723 remove autocomplete match style setting ui
  frontend/src/metabase/admin/settings/selectors.js
Labels: backport

#24728 Enable clj-kondo for driver namespaces
  .clj-kondo/config.edn
  .github/workflows/backend.yml
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/params.clj
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj
  modules/drivers/druid/src/metabase/driver/druid/execute.clj
  modules/drivers/druid/src/metabase/driver/druid/query_processor.clj
  modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/client.clj
  modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/query_processor.clj
  modules/drivers/mongo/src/metabase/driver/mongo.clj
  modules/drivers/mongo/src/metabase/driver/mongo/parameters.clj
  modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj
  modules/drivers/mongo/src/metabase/driver/mongo/util.clj
  modules/drivers/oracle/src/metabase/driver/oracle.clj
  modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj
  modules/drivers/presto/src/metabase/driver/presto.clj
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/sqlite/src/metabase/driver/sqlite.clj
  modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj
  src/metabase/api/search.clj
  src/metabase/models/params/chain_filter/dedupe_joins.clj
  src/metabase/pulse/render/body.clj
  src/metabase/query_processor/middleware/add_dimension_projections.clj
Labels: backport

#24730 Apply main args from bootstrap
  src/metabase/bootstrap.clj
Labels: backport

#24640 [Actions] Add emitter-usages hydration
  src/metabase/api/action.clj
  src/metabase/api/card.clj
  src/metabase/models/emitter.clj
  test/metabase/actions/test_util.clj
  test/metabase/models/emitter_test.clj
Labels: .Backend, Actions/

#24731 fix reset password flow
  frontend/src/metabase/auth/components/ForgotPassword/ForgotPassword.styled.tsx
  frontend/src/metabase/auth/components/ForgotPassword/ForgotPassword.tsx
  frontend/src/metabase/auth/components/ResetPassword/ResetPassword.styled.tsx
  frontend/src/metabase/auth/components/ResetPassword/ResetPassword.tsx
  frontend/src/metabase/auth/components/ResetPassword/ResetPassword.unit.spec.tsx
  frontend/src/metabase/auth/containers/ResetPasswordApp/ResetPasswordApp.tsx
  frontend/src/metabase/core/components/Button/Button.tsx
  frontend/test/metabase/scenarios/onboarding/auth/forgot_password.cy.spec.js
Labels: backport

#24745 Fix reset password flow
  frontend/src/metabase/auth/components/ForgotPassword/ForgotPassword.styled.tsx
  frontend/src/metabase/auth/components/ForgotPassword/ForgotPassword.tsx
  frontend/src/metabase/auth/components/ResetPassword/ResetPassword.styled.tsx
  frontend/src/metabase/auth/components/ResetPassword/ResetPassword.tsx
  frontend/src/metabase/auth/components/ResetPassword/ResetPassword.unit.spec.tsx
  frontend/src/metabase/auth/containers/ResetPasswordApp/ResetPasswordApp.tsx
  frontend/src/metabase/core/components/Button/Button.tsx
  frontend/test/metabase/scenarios/onboarding/auth/forgot_password.cy.spec.js
Labels: auto-backported

#24760 Revert "Fix #23689: Sandboxed group managers can't see other users in the People tab"
  enterprise/backend/test/metabase_enterprise/sandbox/api/user_test.clj
  frontend/test/metabase/scenarios/admin/people/reproductions/23689-sandboxed-group-manager.cy.spec.js
  frontend/test/metabase/scenarios/permissions/sandboxes.cy.spec.js
  src/metabase/api/user.clj
Labels: backport

#24747 docs - isnull and isempty
  docs/users-guide/expressions-list.md
  docs/users-guide/expressions/isempty.md
  docs/users-guide/expressions/isnull.md
Labels: Type:Documentation, backport

#24740 Fix incorrect hash for Advanced fieldvalues
  enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj
  enterprise/backend/test/metabase_enterprise/sandbox/models/params/field_values_test.clj
  src/metabase/api/dashboard.clj
Labels: backport

#24739 Remove chart rendering throttle with the app sidebar animation
  frontend/src/metabase/App.styled.tsx
  frontend/src/metabase/App.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.jsx
  frontend/src/metabase/dashboard/components/DashboardGrid.styled.tsx
  frontend/src/metabase/lib/resize-observer.ts
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbar.styled.tsx
  frontend/src/metabase/visualizations/components/CardRenderer.jsx
  frontend/src/metabase/visualizations/components/Visualization.jsx
  package.json
  yarn.lock
Labels: backport

#24754 Preserve metadata visibility-type
  src/metabase/query_processor/middleware/results_metadata.clj
  src/metabase/query_processor/util.clj
  test/metabase/api/card_test.clj
  test/metabase/query_processor/middleware/results_metadata_test.clj
Labels: backport

#24828 Flamber: Docs update envvars
  docs/operations-guide/environment-variables.md
Labels: Type:Documentation, backport

#24833 [E2E] Replace hard coded sample database IDs
  frontend/test/metabase-visual/admin/permissions.cy.spec.js
  frontend/test/metabase-visual/onboarding/urls.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/edit.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/list.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/editor.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/field-type.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/field.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/hide_tables.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/metadata.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/reproductions/17768-entity-key-showing-binning-options.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/reproductions/18384-field-settings-breaks-ui.cy.spec.js
  frontend/test/metabase/scenarios/admin/datamodel/table.cy.spec.js
  frontend/test/metabase/scenarios/admin/people/people.cy.spec.js
  frontend/test/metabase/scenarios/admin/troubleshooting/tasks.cy.spec.js
  frontend/test/metabase/scenarios/custom-column/reproductions/14843-cc-apply-filter-not-equal-to.cy.spec.js
  frontend/test/metabase/scenarios/custom-column/reproductions/21135-cc-same-name-as-existing-column.cy.spec.js
  frontend/test/metabase/scenarios/filters/filter.cy.spec.js
  frontend/test/metabase/scenarios/joins/reproductions/18502-cannot-join-two-saved-questions-same-table.cy.spec.js
  frontend/test/metabase/scenarios/joins/reproductions/20519-cannot-join-on-aggregation-with-implicit-joins-and-nested-query.cy.spec.js
  frontend/test/metabase/scenarios/models/models.cy.spec.js
  frontend/test/metabase/scenarios/permissions/admin-permissions.cy.spec.js
  frontend/test/metabase/scenarios/permissions/data-model-permissions.cy.spec.js
  frontend/test/metabase/scenarios/permissions/database-details-permissions.cy.spec.js
  frontend/test/metabase/scenarios/permissions/reproductions/17763-cannot-edit-granular-after-block.cy.spec.js
  frontend/test/metabase/scenarios/permissions/reproductions/17777-hidden-tables-not-available.cy.spec.js
  frontend/test/metabase/scenarios/permissions/sandboxes.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#24829 docs - google saml
  docs/enterprise-guide/saml-google.md
Labels: Type:Documentation, backport

#24847 [E2E] Merge repros 12693 and 21521 into a single test
  frontend/test/metabase/scenarios/admin/people/people.cy.spec.js
  frontend/test/metabase/scenarios/admin/people/reproductions/12693-group-count.cy.spec.js
  frontend/test/metabase/scenarios/admin/people/reproductions/21521-group-add-remove-users.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#24733 [E2E] Consolidate `question` group (assorted tweaks)
  frontend/test/metabase/scenarios/onboarding/home/browse.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/navbar/new-menu.cy.spec.js
  frontend/test/metabase/scenarios/question/loading.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/new.cy.spec.js
  frontend/test/metabase/scenarios/question/saved.cy.spec.js
  frontend/test/metabase/scenarios/question/summarization.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/16108-missing-tooltip.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#24848 Display the original field name when editing model column metadata
  frontend/src/metabase/components/form/widgets/FormInputWidget.jsx
  frontend/src/metabase/core/components/Input/Input.styled.tsx
  frontend/src/metabase/core/components/Input/Input.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetFieldMetadataSidebar/DatasetFieldMetadataSidebar.jsx
  frontend/src/metabase/styled-components/theme/index.ts
  frontend/src/metabase/styled-components/theme/typography.ts
Labels: backport

#24818 static viz measure text
  frontend/src/metabase/static-viz/constants/char-sizes.ts
  frontend/src/metabase/static-viz/lib/axes.unit.spec.js
  frontend/src/metabase/static-viz/lib/text.ts
  frontend/src/metabase/static-viz/lib/text.unit.spec.js
  package.json
  yarn.lock
Labels: visual

#24852 fix static viz waterfall colors
  frontend/src/metabase/static-viz/components/CategoricalAreaChart/CategoricalAreaChart.jsx
  frontend/src/metabase/static-viz/components/CategoricalBarChart/CategoricalBarChart.jsx
  frontend/src/metabase/static-viz/components/CategoricalLineChart/CategoricalLineChart.jsx
  frontend/src/metabase/static-viz/components/CategoricalWaterfallChart/CategoricalWaterfallChart.jsx
  frontend/src/metabase/static-viz/components/TimeSeriesAreaChart/TimeSeriesAreaChart.jsx
  frontend/src/metabase/static-viz/components/TimeSeriesBarChart/TimeSeriesBarChart.jsx
  frontend/src/metabase/static-viz/components/TimeSeriesLineChart/TimeSeriesLineChart.jsx
  frontend/src/metabase/static-viz/components/TimeSeriesWaterfallChart/TimeSeriesWaterfallChart.jsx
  frontend/src/metabase/static-viz/containers/StaticChart/StaticChart.tsx
  frontend/src/metabase/static-viz/containers/StaticChart/types.ts
  frontend/src/metabase/static-viz/lib/axes.js
  frontend/src/metabase/static-viz/lib/colors.ts
  resources/frontend_shared/static_viz_interface.js
  src/metabase/pulse/render/body.clj
  src/metabase/pulse/render/js_svg.clj
  test/metabase/pulse/render/js_svg_test.clj
Labels: visual

#24826 Set default engine in admin database forms to postgres
  frontend/src/metabase/admin/databases/database.js
  frontend/src/metabase/lib/engine.js
Labels: backport

#24901 doc - overhaul cleanup
  docs/permissions/application.md
  docs/permissions/data-sandboxes.md
  docs/usage-and-performance-tools/start.md
  docs/usage-and-performance-tools/tools.md
Labels: Type:Documentation, backport

#24863 Fix exclude filter with all selected options
  frontend/src/metabase/parameters/utils/date-formatting.ts
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/24235-exlude-all-date-options.cy.spec.js
Labels: support/Repro, backport

#24907 docs - fix redirect
  docs/installation-and-operation/running-metabase-on-debian.md
Labels: Type:Documentation, backport

#24762 Fix click behavior for links
  frontend/src/metabase/dashboard/actions.js
  frontend/src/metabase/dashboard/reducers.js
  frontend/src/metabase/lib/dom.js
  frontend/src/metabase/visualizations/lib/action.js
  frontend/test/metabase/scenarios/embedding/embedding-full-app.cy.spec.js
Labels: support/Repro

#24923 [E2E] Fix flakes in 22700
  frontend/test/metabase/scenarios/admin/datamodel/metrics.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#24925 [Manual backport] Fix click behavior for links
  frontend/src/metabase/dashboard/actions.js
  frontend/src/metabase/dashboard/reducers.js
  frontend/src/metabase/lib/dom.js
  frontend/src/metabase/visualizations/lib/action.js
  frontend/test/metabase/scenarios/embedding/embedding-full-app.cy.spec.js
Labels: auto-backported

#24888 Consolidate E2E tests with nested questions
  frontend/test/metabase/scenarios/native/reproductions/18364-cannot-save-nested.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/16938-nested-native-query-pk-drill.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#24926 🍒 Backport - [E2E] Fix flakes in 22700 (#24923)
  frontend/test/metabase/scenarios/admin/datamodel/metrics.cy.spec.js
Labels: .CI & Tests, auto-backported

#24881 [Apps] Data apps initial migration and endpoints
  resources/migrations/000_migrations.yaml
  src/metabase/api/app.clj
  src/metabase/api/routes.clj
  src/metabase/cmd/copy.clj
  src/metabase/models.clj
  src/metabase/models/app.clj
  test/metabase/api/app_test.clj
Labels: .Backend

#24927 🍒 Backport: Consolidate E2E tests with nested questions (#24888)
  frontend/test/metabase/scenarios/native/reproductions/18364-cannot-save-nested.cy.spec.js
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/16938-nested-native-query-pk-drill.cy.spec.js
Labels: auto-backported

#24931 [E2E] Replace non-existing ENV `ENTERPRISE_TOKEN`
  .github/workflows/e2e-main.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/percy-issue-comment.yml
  .github/workflows/percy-visual-label.yml
  frontend/test/__runner__/cypress-runner-backend.js
  frontend/test/__support__/e2e/cypress-plugins.js
Labels: Type:Tech Debt, .CI & Tests, backport

#24928 fix backport shows generic error when conflicts
  .github/workflows/auto-backport.yml
Labels: backport

#24929 [E2E] Fix/update `createNestedQuestion` helper
  frontend/test/metabase/scenarios/question/nested.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#24885 Use alternative image names for released container
  .github/workflows/release.yml
Labels: backport

#24959 [E2E] Obtain the current user rather than hard coding it
  frontend/test/metabase/scenarios/onboarding/setup/user_settings.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#24945 Fix click-and-drag filtering in dashboards for firefox
  frontend/src/metabase/visualizations/lib/graph/brush.js
Labels: backport

#24939 Fix segments in case custom expressions
  frontend/src/metabase/lib/expressions/recursive-parser.js
  frontend/test/metabase/scenarios/custom-column/reproductions/24922-cc-case-segment.cy.spec.js
Labels: support/Repro, backport

#24962 [E2E] Replace occurrences of hard coded user names in tests
  frontend/test/__support__/e2e/helpers/e2e-users-helpers.js
  frontend/test/__support__/e2e/helpers/index.js
  frontend/test/metabase/scenarios/admin/people/group-managers.cy.spec.js
  frontend/test/metabase/scenarios/admin/people/people.cy.spec.js
  frontend/test/metabase/scenarios/auditing/subscriptions.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/home/activity-page.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/setup/user_settings.cy.spec.js
  frontend/test/metabase/scenarios/onboarding/urls.cy.spec.js
  frontend/test/metabase/scenarios/organization/moderation-question.cy.spec.js
  frontend/test/metabase/scenarios/organization/timelines-collection.cy.spec.js
  frontend/test/metabase/scenarios/permissions/application-permissions.cy.spec.js
  frontend/test/metabase/scenarios/permissions/reproductions/22726-readonly-collection-duplicate-question.cy.spec.js
  frontend/test/metabase/scenarios/permissions/reproductions/23981-root-collection-breadcrumbs.cy.spec.js
  frontend/test/metabase/scenarios/sharing/alert/alert-permissions.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/17658.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#24933 Fix radio hover color
  frontend/src/metabase/core/components/Radio/Radio.styled.tsx
Labels: backport

#24983 docs - closes #24982
  docs/installation-and-operation/serialization.md
Labels: Type:Documentation, backport

#24985 docs - api doc update
  docs/api/bookmark.md
  docs/api/collection.md
  docs/api/database.md
  docs/api/ee/advanced-permissions-application.md
  docs/api/ee/sso.md
  docs/api/embed.md
  docs/api/preview-embed.md
  docs/api/util.md
  src/metabase/cmd/endpoint_dox.clj
Labels: Type:Documentation

#24989 docs- fix link
  docs/developers-guide/start.md
Labels: Type:Documentation, backport

#24617 [E2E] PoC for cross-version testing
  .github/workflows/e2e-cross-version.yml
  frontend/test/__support__/e2e/cypress-plugins.js
  frontend/test/metabase/scenarios/cross-version/source/cross-version-source-helpers.js
  frontend/test/metabase/scenarios/cross-version/source/cypress.json
  frontend/test/metabase/scenarios/cross-version/source/setup.cy.spec.js
  frontend/test/metabase/scenarios/cross-version/target/cross-version-target-helpers.js
  frontend/test/metabase/scenarios/cross-version/target/cypress.json
  frontend/test/metabase/scenarios/cross-version/target/smoke.cy.spec.js
Labels: .CI & Tests

#24979 🍒 [E2E] Replace non-existing ENV `ENTERPRISE_TOKEN` (#24931)
  .github/workflows/e2e-main.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/percy-issue-comment.yml
  .github/workflows/percy-visual-label.yml
  frontend/test/__runner__/cypress-runner-backend.js
  frontend/test/__support__/e2e/cypress-plugins.js
Labels: auto-backported

#25001 [App] Add action_id to dashcard and endpoint for execution
  resources/migrations/000_migrations.yaml
  src/metabase/actions.clj
  src/metabase/actions/execution.clj
  src/metabase/api/dashboard.clj
  src/metabase/models/dashboard_card.clj
  src/metabase/query_processor/writeback.clj
  test/metabase/api/dashboard_test.clj
Labels: .Backend, Actions/

#25023 docs - update models
  docs/data-modeling/models.md
Labels: Type:Documentation, backport

#25044 docs - correct frontmatter
  docs/configuring-metabase/email.md
Labels: Type:Documentation, backport

#25032 Repro #25031: Embedding Dashboard with Locked parameters does not allow numeric values
  frontend/test/metabase/scenarios/embedding/reproductions/20845-25031-locked-numeric-param.cy.spec.js
  frontend/test/metabase/scenarios/embedding/reproductions/20845-locked-numeric-param.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#25012 Make sandboxing middleware recursive
  enterprise/backend/src/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions.clj
  frontend/test/metabase/scenarios/permissions/sandboxes.cy.spec.js
  src/metabase/models/permissions.clj
  src/metabase/query_processor.clj
Labels: backport

#25043 [App] Raise card visualization_settings onto actions
  src/metabase/models/action.clj
  test/metabase/actions/test_util.clj
  test/metabase/api/action_test.clj
Labels: .Backend, Actions/

#25069 Update dev guide for e2e tests running on M1
  docs/developers-guide/e2e-tests.md
Labels: Type:Documentation, .CI & Tests, backport

#25063 docs -markdown linter
  .github/workflows/doc-md-links.yml
  .mlc_config.json
  docs/dashboards/filters.md
  docs/dashboards/interactive.md
  docs/dashboards/introduction.md
  docs/dashboards/multiple-series.md
  docs/dashboards/subscriptions.md
  docs/developers-guide/docs.md
  docs/developers-guide/start.md
  docs/embedding/whitelabeling.md
  docs/installation-and-operation/serialization.md
  docs/permissions/start.md
  docs/questions/query-builder/expressions-list.md
  package.json
  yarn.lock
Labels: Type:Documentation, backport

#25047 docs - database syncs and scans
  README.md
  docs/databases/connecting.md
  docs/databases/connections/google-analytics.md
  docs/databases/images/DatabaseDeleteButton.png
  docs/developers-guide/drivers/multimethods.md
  docs/developers-guide/drivers/start.md
  docs/developers-guide/partner-and-community-drivers.md
  docs/questions/sharing/visualizing-results.md
  docs/troubleshooting-guide/sync-fingerprint-scan.md
Labels: Type:Documentation, backport

#25072 [E2E] Cross-version individual artifacts
  .github/workflows/e2e-cross-version.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#25098 docs - update link
  docs/databases/connecting.md
Labels: Type:Documentation, backport

#25100 docs - update link to package.json
  docs/developers-guide/docs.md
Labels: backport

#25075 [Apps] Hydrate action_id on is_write Card
  src/metabase/api/card.clj
  src/metabase/models/action.clj
  test/metabase/api/card_test.clj
Labels: .Backend, Actions/

#25110 [Apps] Hydrate action on dashcards
  src/metabase/api/dashboard.clj
  src/metabase/models/action.clj
  test/metabase/api/dashboard_test.clj
Labels: .Backend, Actions/

#25114 Expand dev docs for E2E tests running against EE version
  docs/developers-guide/e2e-tests.md
Labels: Type:Documentation, backport

#24967 Fix incorrectness issue for advanced FieldValues when sandboxing use native question
  enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/field_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/models/params/field_values_test.clj
  frontend/test/metabase/scenarios/permissions/reproductions/24966-saved-native-q-field-values.cy.spec.js
Labels: support/Repro, backport

#25131 Fix data selector trigger wrapping
  frontend/src/metabase/query_builder/components/DataSelector.jsx
Labels: backport

#25134 Run 24966 repro on EE only
  frontend/test/metabase/scenarios/permissions/reproductions/24966-saved-native-q-field-values.cy.spec.js
Labels: backport

#25127 Use alternative image names for released container
  .github/workflows/release.yml
Labels: auto-backported

#25137 fix backports auto-approve
  .github/workflows/auto-backport.yml
Labels: backport

#25135 Fixed a misslink redirection for `Alerts` documentation
  docs/questions/sharing/alerts.md
Labels: Type:Documentation, backport

#25150 [E2E] Skip adding another H2 database to avoid failures in CI
  frontend/test/__support__/e2e/commands/database/addH2SampleDatabase.js
Labels: Type:Tech Debt, .CI & Tests, backport
