Repository metabase/metabase, pull requests merged in 2022-10, with the labels that each got.

#25755 docs - remove interactive
  docs/embedding/start.md
Labels: Type:Documentation, backport

#25763 Open `e2e` tests by default in Cypress open mode
  package.json
Labels: Type:Tech Debt, .CI & Tests, backport

#25787 docs - update section name to match sidebar
  docs/README.md
  docs/exploration-and-organization/start.md
Labels: Type:Documentation, backport

#25795 [GHA] Do not use `buildjet` for timezone tests
  .github/workflows/frontend.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#25783 Include new site UUID in version check requests
  src/metabase/public_settings.clj
  src/metabase/task/upgrade_checks.clj
  test/metabase/task/upgrade_checks_test.clj
Labels: backport

#25818 docs - update full-app embedding
  docs/embedding/full-app-embedding.md
Labels: Type:Documentation, backport

#25816 Refactor GeoJSON URL fetching logic
  src/metabase/api/geojson.clj
Labels: backport

#25819 Refactor password reset login for SSO users
  src/metabase/api/session.clj
  src/metabase/email/messages.clj
  src/metabase/email/password_reset.mustache
  test/metabase/email/messages_test.clj
  test/metabase/email_test.clj
Labels: backport

#25808 [E2E] Consolidate admin > database tests
  frontend/test/metabase/scenarios/admin/databases/add-external.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/add.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#25836 docs - heading
  docs/people-and-groups/google-and-ldap.md
Labels: Type:Documentation, backport

#25868 #25543 Repro: Collection list fails to display if there's an invalid parameter in a question
  frontend/test/metabase/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#25867 docs - models update
  docs/data-modeling/models.md
Labels: Type:Documentation

#25829 Static row chart
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase-types/api/dataset.ts
  frontend/src/metabase-types/api/mocks/dataset.ts
  frontend/src/metabase/lib/formatting/types.ts
  frontend/src/metabase/lib/measure-text.ts
  frontend/src/metabase/static-viz/components/RowChart/RowChart.tsx
  frontend/src/metabase/static-viz/components/RowChart/constants.ts
  frontend/src/metabase/static-viz/components/RowChart/index.ts
  frontend/src/metabase/static-viz/components/RowChart/theme.ts
  frontend/src/metabase/static-viz/components/RowChart/utils/format.ts
  frontend/src/metabase/static-viz/components/RowChart/utils/labels.ts
  frontend/src/metabase/static-viz/components/XYChart/types.ts
  frontend/src/metabase/static-viz/components/XYChart/utils/bounds.ts
  frontend/src/metabase/static-viz/components/XYChart/utils/scales.ts
  frontend/src/metabase/static-viz/components/XYChart/utils/ticks.ts
  frontend/src/metabase/static-viz/containers/StaticChart/StaticChart.tsx
  frontend/src/metabase/static-viz/containers/StaticChart/constants.ts
  frontend/src/metabase/visualizations/components/ScalarValue/utils.ts
  frontend/src/metabase/visualizations/components/ScalarValue/utils.unit.spec.ts
  frontend/src/metabase/visualizations/lib/graph/columns.ts
  frontend/src/metabase/visualizations/lib/settings/goal.ts
  frontend/src/metabase/visualizations/lib/settings/stacking.ts
  frontend/src/metabase/visualizations/shared/components/RowChart/RowChart.stories.tsx
  frontend/src/metabase/visualizations/shared/components/RowChart/RowChart.tsx
  frontend/src/metabase/visualizations/shared/components/RowChart/constants.ts
  frontend/src/metabase/visualizations/shared/components/RowChart/index.ts
  frontend/src/metabase/visualizations/shared/components/RowChart/types.ts
  frontend/src/metabase/visualizations/shared/components/RowChart/utils/domain.ts
  frontend/src/metabase/visualizations/shared/components/RowChart/utils/layout.ts
  frontend/src/metabase/visualizations/shared/components/RowChart/utils/scale.ts
  frontend/src/metabase/visualizations/shared/components/RowChart/utils/ticks.ts
  frontend/src/metabase/visualizations/shared/components/RowChartView/RowChartView.tsx
  frontend/src/metabase/visualizations/shared/components/RowChartView/index.ts
  frontend/src/metabase/visualizations/shared/components/VerticalGoalLine/VerticalGoalLine.tsx
  frontend/src/metabase/visualizations/shared/components/VerticalGoalLine/index.ts
  frontend/src/metabase/visualizations/shared/types/data.ts
  frontend/src/metabase/visualizations/shared/types/events.ts
  frontend/src/metabase/visualizations/shared/types/format.ts
  frontend/src/metabase/visualizations/shared/types/layout.ts
  frontend/src/metabase/visualizations/shared/types/measure-text.ts
  frontend/src/metabase/visualizations/shared/types/scale.ts
  frontend/src/metabase/visualizations/shared/types/settings.ts
  frontend/src/metabase/visualizations/shared/types/style.ts
  frontend/src/metabase/visualizations/shared/utils/colors.ts
  frontend/src/metabase/visualizations/shared/utils/data.ts
  frontend/src/metabase/visualizations/shared/utils/data.unit.spec.ts
  frontend/src/metabase/visualizations/shared/utils/series.ts
  frontend/test/metabase-visual/static-visualizations/row.cy.spec.js
  jest.tz.unit.conf.json
  jest.unit.conf.json
  package.json
  resources/frontend_shared/static_viz_interface.js
  src/metabase/pulse/render.clj
  src/metabase/pulse/render/body.clj
  src/metabase/pulse/render/js_svg.clj
  webpack.static-viz.config.js
  yarn.lock
Labels: visual

#25815 [Apps] Scaffold implicit actions
  src/metabase/api/app.clj
  test/metabase/api/app_test.clj
Labels: .Backend, Actions/

#25805 [Apps] Scaffolding cleanup
  src/metabase/api/app.clj
Labels: .Backend, Actions/

#25888 [E2E] Guard workflow against the missing recording key
  .github/workflows/e2e-main.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#25887 docs - date expressions
  docs/questions/query-builder/expressions-list.md
Labels: Type:Documentation

#25883 [Apps] Small scaffolding bug fixes
  src/metabase/api/app.clj
Labels: .Backend, Actions/

#25902 Clean up Slack error logging
  src/metabase/integrations/slack.clj
Labels: backport

#25911 🍒 [E2E] Guard workflow against the missing recording key (#25888)
  .github/workflows/e2e-main.yml
Labels: auto-backported

#25919 Repro #24660: Saved Questions data selector lists all questions for collections with the same name
  frontend/test/metabase/scenarios/collections/reproductions/24660-same-name-parent-collections.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#25945 Automatically set initial sync status of crufty tables to `complete`
  src/metabase/sync/sync_metadata/tables.clj
  test/metabase/sync/sync_metadata/tables_test.clj
Labels: backport

#25941 Refactor validation when executing a dashcard query
  src/metabase/query_processor/dashboard.clj
  test/metabase/api/embed_test.clj
  test/metabase/query_processor/dashboard_test.clj
Labels: backport

#25952 Use NodeJS `http` module for Cypress backend
  frontend/test/__runner__/cypress-runner-backend.js
Labels: Type:Tech Debt, .CI & Tests, backport

#25925 untie `getColumnKey` function from code not usable in static viz rendering environment
  frontend/src/metabase-lib/lib/Dimension.ts
  frontend/src/metabase-lib/lib/Question.ts
  frontend/src/metabase-lib/lib/parameters/utils/mbql.js
  frontend/src/metabase-lib/lib/queries/NativeQuery.ts
  frontend/src/metabase-lib/lib/queries/utils/dataset.js
  frontend/src/metabase-lib/lib/queries/utils/get-column-key.ts
  frontend/src/metabase-lib/lib/queries/utils/get-column-key.unit.spec.js
  frontend/src/metabase-lib/lib/references.ts
  frontend/src/metabase-lib/lib/references.unit.spec.ts
  frontend/src/metabase-types/api/dataset.ts
  frontend/src/metabase-types/api/query.ts
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/ClickBehaviorSidebar.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/ClickBehaviorSidebarContent.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/ClickBehaviorSidebarHeader/ClickBehaviorSidebarHeader.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/TableClickBehaviorView/TableClickBehaviorView.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/utils.ts
  frontend/src/metabase/modes/components/drill/FormatAction.jsx
  frontend/src/metabase/query_builder/components/filters/pickers/DefaultPicker.jsx
  frontend/src/metabase/static-viz/components/RowChart/utils/format.ts
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldPicker.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingOrderedColumns.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingsListColumns/ChartSettingsListColumns.tsx
  frontend/src/metabase/visualizations/lib/settings/column.js
  frontend/test/metabase-lib/lib/Dimension.unit.spec.js
  frontend/test/metabase/lib/dataset.unit.spec.js
Labels: visual

#25837 Replacing isomorphic-fetch for plain XMLHttpRequest
  bin/i18n/import-po-from-poeditor
  package.json
  yarn.lock
Labels: Type:Tech Debt

#25965 [E2E] Fix cache ttl test (flake)
  frontend/test/metabase/scenarios/admin/databases/edit.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#25973 docs - update links
  docs/api-documentation.md
  docs/api/action.md
  docs/api/app.md
  docs/api/dashboard.md
  docs/api/ee/serialization-serialize.md
  docs/api/model-action.md
  docs/api/notify.md
  docs/api/search.md
  docs/troubleshooting-guide/sandboxing.md
  src/metabase/api/notify.clj
Labels: Type:Documentation

#25975 docs - update redirect
  docs/configuring-metabase/email.md
Labels: Type:Documentation, backport

#25979 Repro #25908: Using filter Contains on dashboard is case-insensitive, but on drill-through to question becomes case-sensitive
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/25908-contains-filter-case-sensitivity.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#25991 Handle parameter parsing exceptions when loading collections
  src/metabase/api/collection.clj
  test/metabase/api/collection_test.clj
Labels: backport

#25944 docs - restore sample db
  docs/databases/connecting.md
  docs/databases/images/DatabaseManualSync.png
Labels: Type:Documentation, backport

#25982 [Apps] Disable data-apps prior to release
  src/metabase/actions.clj
  src/metabase/api/action.clj
  src/metabase/api/app.clj
  src/metabase/api/dashboard.clj
  src/metabase/api/model_action.clj
  src/metabase/api/permissions.clj
  src/metabase/models/action.clj
  src/metabase/models/app.clj
  test/metabase/test.clj
Labels: .Backend, Actions/

#25999 [Apps] Remove emitters
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  resources/migrations/000_migrations.yaml
  src/metabase/api/action.clj
  src/metabase/api/card.clj
  src/metabase/api/dashboard.clj
  src/metabase/api/emitter.clj
  src/metabase/api/routes.clj
  src/metabase/cmd/copy.clj
  src/metabase/models.clj
  src/metabase/models/action.clj
  src/metabase/models/emitter.clj
  test/metabase/actions/test_util.clj
  test/metabase/actions_test.clj
  test/metabase/api/action_test.clj
  test/metabase/api/card_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/emitter_test.clj
  test/metabase/cmd/copy_test.clj
  test/metabase/driver/sql_jdbc/actions_test.clj
  test/metabase/models/action_test.clj
  test/metabase/models/emitter_test.clj
Labels: .Backend, Actions/

#26028 Properly check if api/*current-user* is bound
  src/metabase/actions.clj
Labels: .Backend

#26022 Fix detection of backend files when generating i18n EDN
  bin/i18n/src/i18n/create_artifacts/backend.clj
  bin/i18n/test/i18n/create_artifacts/backend_test.clj
  bin/i18n/test/i18n/create_artifacts/test_common.clj
  src/metabase/api/table.clj
  test/metabase/util/i18n_test.clj
Labels: backport

#26036 [E2E] Try `deploysentinel` for Cypress runs analytics
  .github/workflows/e2e-main.yml
  frontend/test/__support__/e2e/config.js
  frontend/test/__support__/e2e/cypress.js
  package.json
  yarn.lock
Labels: .CI & Tests

#26037 Manual backport of #26022
  bin/i18n/src/i18n/create_artifacts/backend.clj
  bin/i18n/test/i18n/create_artifacts/backend_test.clj
  bin/i18n/test/i18n/create_artifacts/test_common.clj
  src/metabase/api/table.clj
Labels: auto-backported

#26034 docs - update signed embedding
  docs/embedding/signed-embedding-parameters.md
  docs/embedding/signed-embedding.md
Labels: Type:Documentation, backport

#26015 Fetch static viz code changes while running in the dev mode
  package.json
  src/metabase/pulse/render/js_svg.clj
  test/metabase/pulse/render/js_svg_test.clj
  webpack.static-viz.config.js
Labels: Type:Tech Debt, .Acceleration

#25811 Ensure static visualizations with multiple cards are rendered
  frontend/test/metabase/scenarios/sharing/reproductions/21559-subscription-bar-sent-as-scalar.cy.spec.js
  src/metabase/pulse/render.clj
  src/metabase/pulse/render/body.clj
  src/metabase/pulse/render/common.clj
  src/metabase/pulse/render/js_svg.clj
  test/metabase/pulse/render_test.clj
Labels: Visualization/Static

#26042 docs - update aws elastic beanstalk
  docs/installation-and-operation/running-metabase-on-elastic-beanstalk.md
Labels: Type:Documentation, backport

#26070 docs - update anchor links
  docs/embedding/signed-embedding.md
  docs/troubleshooting-guide/my-dashboard-is-slow.md
Labels: Type:Documentation, backport

#26044 [E2E] Tweak `deploysentinel` config
  .github/workflows/e2e-main.yml
  frontend/test/__support__/e2e/config.js
  frontend/test/__support__/e2e/cypress.js
  package.json
  yarn.lock
Labels: .CI & Tests

#26081 docs - fix table link
  docs/embedding/introduction.md
Labels: Type:Documentation, backport

#25262 Static pie chart labels
  frontend/src/metabase/static-viz/components/CategoricalDonutChart/CategoricalDonutChart.jsx
  frontend/src/metabase/static-viz/components/CategoricalDonutChart/CategoricalDonutChart.unit.spec.jsx
  frontend/src/metabase/static-viz/containers/StaticChart/StaticChart.unit.spec.js
  frontend/test/metabase-visual/static-visualizations/pie.cy.spec.js
  resources/frontend_shared/static_viz_interface.js
  src/metabase/pulse/render/body.clj
  src/metabase/pulse/render/js_svg.clj
  test/metabase/pulse/render/body_test.clj
  test/metabase/pulse/render/js_svg_test.clj
Labels: visual

#26101 [CI] Redo the release script and trigger it manually
  .github/workflows/release.yml
Labels: .Building & Releasing, .CI & Tests

#26119 Fix BulkFilterModal breaking "between" custom expressions
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/utils.ts
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/utils.unit.spec.ts
Labels: backport

#26107 static chart legend
  frontend/src/metabase/static-viz/components/Legend/Legend.tsx
  frontend/src/metabase/static-viz/components/Legend/constants.ts
  frontend/src/metabase/static-viz/components/Legend/index.ts
  frontend/src/metabase/static-viz/components/Legend/types.ts
  frontend/src/metabase/static-viz/components/Legend/utils.ts
  frontend/src/metabase/static-viz/components/LineAreaBarChart/LineAreaBarChart.tsx
  frontend/src/metabase/static-viz/components/XYChart/Legend/Legend.tsx
  frontend/src/metabase/static-viz/components/XYChart/Legend/LegendItem.tsx
  frontend/src/metabase/static-viz/components/XYChart/XYChart.tsx
  frontend/src/metabase/static-viz/components/XYChart/constants.ts
  frontend/src/metabase/static-viz/components/XYChart/types.ts
  frontend/src/metabase/static-viz/components/XYChart/utils/index.ts
  frontend/src/metabase/static-viz/components/XYChart/utils/legend.ts
  frontend/src/metabase/static-viz/components/XYChart/utils/legend.unit.spec.ts
  frontend/src/metabase/static-viz/components/XYChart/utils/margin.ts
Labels: visual

#26097 Don't throw an error when a partial permissions graph revision has no new changes
  src/metabase/models/permissions.clj
  test/metabase/models/permissions_test.clj
Labels: backport

#26120 [Apps] Handle type errors more cleanly
  src/metabase/actions/execution.clj
  test/metabase/actions/test_util.clj
  test/metabase/api/dashboard_test.clj
Labels: .Backend, Actions/

#26146 Static Row Chart formatting and legend
  frontend/src/metabase-lib/queries/utils/actions.js
  frontend/src/metabase-lib/queries/utils/dataset.js
  frontend/src/metabase-lib/queries/utils/range-for-value.ts
  frontend/src/metabase-types/api/dataset.ts
  frontend/src/metabase/entities/users.js
  frontend/src/metabase/lib/formatting/strings.ts
  frontend/src/metabase/lib/formatting/time.ts
  frontend/src/metabase/lib/formatting/value.tsx
  frontend/src/metabase/lib/security.js
  frontend/src/metabase/lib/security.unit.spec.js
  frontend/src/metabase/lib/settings.ts
  frontend/src/metabase/lib/utils.js
  frontend/src/metabase/static-viz/components/Legend/Legend.tsx
  frontend/src/metabase/static-viz/components/RowChart/RowChart.tsx
  frontend/src/metabase/static-viz/components/RowChart/constants.ts
  frontend/src/metabase/static-viz/components/RowChart/utils/format.ts
  frontend/src/metabase/static-viz/lib/format-static-value.ts
  frontend/src/metabase/visualizations/components/LeafletGridHeatMap.jsx
  frontend/src/metabase/visualizations/shared/utils/data.ts
  frontend/src/metabase/visualizations/shared/utils/format.ts
  frontend/src/metabase/visualizations/visualizations/RowChart/RowChart.tsx
  frontend/test/metabase/lib/utils.unit.spec.js
Labels: visual

#26144 docs - history
  docs/README.md
  docs/exploration-and-organization/collections.md
  docs/exploration-and-organization/exploration.md
  docs/exploration-and-organization/history.md
  docs/exploration-and-organization/images/verified-icon.png
  docs/exploration-and-organization/start.md
  docs/paid-features/overview.md
  docs/questions/query-builder/introduction.md
  docs/questions/sharing/answers.md
  docs/questions/sharing/public-links.md
Labels: Type:Documentation, backport
