Repository metabase/metabase, pull requests merged in 2023-10, with the labels that each got.

#34244 Search Milestone 2: Organize `created_by` components for future use
  enterprise/frontend/src/metabase-enterprise/content_verification/VerifiedFilter/VerifiedFilter.tsx
  frontend/src/metabase/search/components/DropdownSidebarFilter/DropdownSidebarFilter.styled.tsx
  frontend/src/metabase/search/components/DropdownSidebarFilter/DropdownSidebarFilter.tsx
  frontend/src/metabase/search/components/DropdownSidebarFilter/DropdownSidebarFilter.unit.spec.tsx
  frontend/src/metabase/search/components/DropdownSidebarFilter/index.ts
  frontend/src/metabase/search/components/SearchFilterPopoverWrapper/SearchFilterPopoverWrapper.styled.tsx
  frontend/src/metabase/search/components/SearchFilterPopoverWrapper/SearchFilterPopoverWrapper.tsx
  frontend/src/metabase/search/components/SearchFilterPopoverWrapper/SearchFilterPopoverWrapper.unit.spec.tsx
  frontend/src/metabase/search/components/SearchFilterPopoverWrapper/index.ts
  frontend/src/metabase/search/components/SearchSidebar/SearchSidebar.tsx
  frontend/src/metabase/search/components/SearchSidebar/index.ts
  frontend/src/metabase/search/components/SearchSidebar/tests/setup.tsx
  frontend/src/metabase/search/components/SearchUserPicker/SearchUserPicker.styled.tsx
  frontend/src/metabase/search/components/SearchUserPicker/SearchUserPicker.tsx
  frontend/src/metabase/search/components/SearchUserPicker/SearchUserPicker.unit.spec.tsx
  frontend/src/metabase/search/components/SearchUserPicker/index.ts
  frontend/src/metabase/search/components/ToggleSidebarFilter/ToggleSidebarFilter.tsx
  frontend/src/metabase/search/components/ToggleSidebarFilter/ToggleSidebarFilter.unit.spec.tsx
  frontend/src/metabase/search/components/ToggleSidebarFilter/index.ts
  frontend/src/metabase/search/components/UserListElement/index.ts
  frontend/src/metabase/search/components/UserNameDisplay/UserNameDisplay.tsx
  frontend/src/metabase/search/components/UserNameDisplay/UserNameDisplay.unit.spec.tsx
  frontend/src/metabase/search/components/UserNameDisplay/index.ts
  frontend/src/metabase/search/components/filters/CreatedByFilter/CreatedByContent/CreatedByContent.tsx
  frontend/src/metabase/search/components/filters/CreatedByFilter/CreatedByContent/index.ts
  frontend/src/metabase/search/components/filters/CreatedByFilter/CreatedByDisplay/CreatedByDisplay.tsx
  frontend/src/metabase/search/components/filters/CreatedByFilter/CreatedByDisplay/CreatedByDisplay.unit.spec.tsx
  frontend/src/metabase/search/components/filters/CreatedByFilter/CreatedByDisplay/index.ts
  frontend/src/metabase/search/components/filters/CreatedByFilter/CreatedByFilter.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilter.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilter.unit.spec.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterContent.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterDisplay.tsx
  frontend/src/metabase/search/containers/SearchApp.jsx
  frontend/src/metabase/search/types.ts
  frontend/src/metabase/search/utils/enabled-search-type/enabled-search-type.ts
  frontend/src/metabase/search/utils/enabled-search-type/enabled-search-type.unit.spec.ts
  frontend/src/metabase/search/utils/enabled-search-type/index.ts
  frontend/src/metabase/search/utils/index.ts
  frontend/src/metabase/search/utils/user-search-params/index.ts
  frontend/src/metabase/search/utils/user-search-params/user-search-params.ts
  frontend/src/metabase/search/utils/user-search-params/user-search-params.unit.spec.ts
Labels: .Team/42 :milky_way:

#33525 Global search: last edited by, last edited at
  enterprise/backend/test/metabase_enterprise/audit_db_test.clj
  resources/migrations/000_migrations.yaml
  src/metabase/api/collection.clj
  src/metabase/api/search.clj
  src/metabase/models/metric.clj
  src/metabase/models/revision.clj
  src/metabase/models/revision/last_edit.clj
  src/metabase/search/config.clj
  src/metabase/search/filter.clj
  test/metabase/api/card_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/revision_test.clj
  test/metabase/api/search_test.clj
  test/metabase/db/custom_migrations_test.clj
  test/metabase/db/schema_migrations_test.clj
  test/metabase/models/revision_test.clj
  test/metabase/search/filter_test.clj
Labels: .Team/42 :milky_way:

#34256 Migrate notebook's data step to MLv2
  frontend/src/metabase-lib/metadata.ts
  frontend/src/metabase-lib/query.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/query_builder/components/notebook/FieldsPickerIcon.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/DataStep/DataStep.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/DataStep/DataStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/DataStep/DataStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.jsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.styled.tsx
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#34157 [MLv2] Allow any type of arguments to :concat expressions
  src/metabase/lib/schema/expression/string.cljc
  test/metabase/lib/expression_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:, no-backport

#34084 Add custom warning message when leaving editing an existing SQL question
  frontend/src/metabase/actions/containers/ActionCreator/ActionCreator.tsx
  frontend/src/metabase/components/LeaveConfirmationModal/LeaveConfirmationModal.tsx
  frontend/src/metabase/containers/SaveQuestionModal.tsx
  frontend/src/metabase/hooks/use-callback-effect/index.ts
  frontend/src/metabase/hooks/use-callback-effect/use-callback-effect.ts
  frontend/src/metabase/hooks/use-callback-effect/use-callback-effect.unit.spec.tsx
  frontend/src/metabase/query_builder/actions/core/core.js
  frontend/src/metabase/query_builder/containers/QueryBuilder.jsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.unit.spec.tsx
  frontend/src/metabase/query_builder/selectors.js
  frontend/test/__support__/server-mocks/card.ts
Labels: .Team/42 :milky_way:, no-backport

#34217 Fix tests wtih unmocked http requests
  frontend/src/metabase/admin/databases/components/DatabaseEditApp/Sidebar/Sidebar.unit.spec.tsx
  frontend/src/metabase/admin/datamodel/components/MetricForm/MetricForm.unit.spec.tsx
  frontend/src/metabase/admin/datamodel/components/SegmentForm/SegmentForm.unit.spec.tsx
  frontend/src/metabase/auth/components/PasswordPanel/PasswordPanel.unit.spec.tsx
  frontend/src/metabase/common/hooks/use-dashboard-query/use-dashboard-query.unit.spec.tsx
  frontend/src/metabase/components/MetadataInfo/FieldFingerprintInfo/CategoryFingerprint.unit.spec.js
  frontend/src/metabase/containers/QuestionResultLoader.unit.spec.js
  frontend/src/metabase/dashboard/actions/save.js
  frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.unit.spec.tsx
  frontend/src/metabase/entities/containers/EntityName.unit.spec.tsx
  frontend/src/metabase/nav/components/WhatsNewNotification/WhatsNewNotification.unit.spec.tsx
  frontend/src/metabase/parameters/components/ValuesSourceSettings/ValuesSourceSettings.unit.spec.tsx
  frontend/src/metabase/pulse/components/RecipientPicker.unit.spec.js
  frontend/src/metabase/query_builder/components/filters/modals/InlineCategoryPicker/InlineCategoryPicker.unit.spec.tsx
  frontend/src/metabase/query_builder/components/filters/modals/InlineValuePicker/InlineValuePicker.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/QuestionDataSource.unit.spec.js
  frontend/src/metabase/query_builder/containers/QueryBuilder.unit.spec.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization-object.unit.spec.tsx
  frontend/test/__support__/server-mocks/card.ts
  frontend/test/__support__/server-mocks/dashboard.ts
  frontend/test/__support__/server-mocks/database.ts
  frontend/test/__support__/server-mocks/field.ts
Labels: visual, .Team/42 :milky_way:, no-backport

#34253 Clean up join E2E tests
  e2e/support/helpers/e2e-bi-basics-helpers.js
  e2e/support/helpers/e2e-dashboard-helpers.js
  e2e/support/helpers/e2e-misc-helpers.js
  e2e/support/helpers/e2e-notebook-helpers.js
  e2e/test/scenarios/joins/joins.cy.spec.js
  e2e/test/scenarios/joins/reproductions/12928-joining-questions-with-joins.cy.spec.js
  e2e/test/scenarios/joins/reproductions/14793-xrays-joins.cy.spec.js
  e2e/test/scenarios/joins/reproductions/15578-remapped-values-joins.cy.spec.js
  e2e/test/scenarios/joins/reproductions/17968-notebook-join-table-names.cy.spec.js
  e2e/test/scenarios/visualizations/reproductions/30058-32075-map-visualizations.cy.spec.js
  frontend/src/metabase/dashboard/components/DashboardGrid.jsx
  frontend/src/metabase/dashboard/containers/AutomaticDashboardApp.jsx
  frontend/src/metabase/query_builder/components/notebook/NotebookStep/NotebookStep.tsx
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#34270 Handle mismatching date parameters in dashboard -> native question drills
  e2e/test/scenarios/native-filters/reproductions/34129.cy.spec.js
  frontend/src/metabase/parameters/utils/date-formatting.ts
  frontend/src/metabase/parameters/utils/formatting.unit.spec.ts
  frontend/src/metabase/query_builder/actions/core/initializeQB.ts
Labels: backport, .Team/42 :milky_way:

#34181 docs - note experimental feature
  docs/api/metabot.md
  src/metabase/api/metabot.clj
Labels: Type:Documentation, backport

#34267 Filters API polish
  frontend/src/metabase-lib/constants.ts
  frontend/src/metabase-lib/filter.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/common/components/FilterPicker/BooleanFilterPicker.tsx
Labels: .Team/42 :milky_way:, no-backport

#34167 [jest] Move builtin plugins to specific specs
  .github/workflows/frontend.yml
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/password-login.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/sso-google.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/sso-ldap.unit.spec.tsx
  frontend/src/metabase/auth/components/Login/tests/common.unit.spec.tsx
  frontend/src/metabase/auth/components/Login/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/auth/components/PasswordPanel/PasswordPanel.unit.spec.tsx
  frontend/test/register-visualizations.js
Labels: visual, .Team/42 :milky_way:, no-backport

#34230 Update instance analytics graph for admins to "read"
  src/metabase/models/collection/graph.clj
  test/metabase/models/collection/graph_test.clj
Labels: .Team/PixelPolice :police_officer:

#34216 Remove extra driver/execute-write-query! sql-jdbc implementation
  src/metabase/driver/sql_jdbc/actions.clj
  src/metabase/driver/sql_jdbc/execute.clj
Labels: backport, .Team/42 :milky_way:

#33851 Drop unused typings
  package.json
  yarn.lock
Labels: .Team/42 :milky_way:, no-backport

#34007 Enable ClojureScript REPL and hot reloading of CLJS code
  deps.edn
  frontend/test/global-setup.js
  jest.config.json
  jest.tz.unit.conf.json
  package.json
  shadow-cljs.edn
  src/metabase/server/middleware/security.clj
  src/metabase/util/devtools.cljc
  tsconfig.json
  webpack.config.js
  webpack.static-viz.config.js
  yarn.lock
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33938 Automated Releases from CI 🚀
  .github/workflows/build-for-release.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  release/.env-template
  release/.gitignore
  release/README.md
  release/babel.config.json
  release/jest.config.cjs
  release/package.json
  release/src/github.ts
  release/src/index.ts
  release/src/release-notes.ts
  release/src/release-notes.unit.spec.ts
  release/src/types.ts
  release/src/version-helpers.ts
  release/src/version-helpers.unit.spec.ts
  release/src/version-info.ts
  release/src/version-info.unit.spec.ts
  release/tsconfig.json
  release/yarn.lock
Labels: .Building & Releasing, .CI & Tests, .Team/PixelPolice :police_officer:, no-backport

#34295 fix Arabic translations
  locales/ar-SA.po
  locales/ar.po
Labels: backport, .Team/PixelPolice :police_officer:

#34239 Remove unused collection `color` column
  dev/test/dev/model_tracking_test.clj
  e2e/snapshot-creators/default.cy.snap.js
  e2e/support/commands/api/collection.js
  e2e/test/scenarios/collections/collections.cy.spec.js
  e2e/test/scenarios/collections/personal-collections.cy.spec.js
  e2e/test/scenarios/collections/uploads.cy.spec.js
  e2e/test/scenarios/dashboard/permissions.cy.spec.js
  e2e/test/scenarios/native/snippets/snippet-permissions.cy.spec.js
  e2e/test/scenarios/onboarding/home/homepage.cy.spec.js
  e2e/test/scenarios/organization/official-collections.cy.spec.js
  e2e/test/scenarios/question/new.cy.spec.js
  enterprise/backend/test/metabase_enterprise/content_management/api/collection_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/seed_entity_ids_test.clj
  enterprise/frontend/src/metabase-enterprise/snippets/components/SnippetCollectionForm.tsx
  frontend/src/metabase-types/api/collection.ts
  frontend/src/metabase/containers/SaveQuestionModal.unit.spec.tsx
  resources/migrations/000_migrations.yaml
  src/metabase/api/collection.clj
  src/metabase/automagic_dashboards/populate.clj
  src/metabase/models/collection.clj
  src/metabase/models/dashboard.clj
  src/metabase/transforms/materialize.clj
  test/metabase/api/collection_test.clj
  test/metabase/db/schema_migrations_test.clj
  test/metabase/models/collection_test.clj
  test/metabase/test/generate.clj
  test/metabase/test/util.clj
  test_resources/instance_analytics_skip/collections/Lq6nt9JfsdTZXXz6cj1mX_a_a_a_a_a_a_s_personal_collection/Lq6nt9JfsdTZXXz6cj1mX_a_a_a_a_a_a_s_personal_collection.yaml
  test_resources/instance_analytics_skip/collections/tYhkn_-pFTWcCTSwhgCBP_instance_analytics/tYhkn_-pFTWcCTSwhgCBP_instance_analytics.yaml
Labels: Type:Tech Debt, Misc/API, no-backport

#34220 Fix action parameter types not saving correctly
  e2e/test/scenarios/actions/actions-on-dashboards.cy.spec.js
  frontend/src/metabase/actions/containers/ActionCreator/ActionContext/QueryActionContextProvider/QueryActionContextProvider.tsx
Labels: backport, .Team/42 :milky_way:

#34291 [MLv2] Update Boolean Picker Operator Options
  frontend/src/metabase/common/components/FilterPicker/BooleanFilterPicker.tsx
Labels: .Team/PixelPolice :police_officer:

#34302 Global search: created by and edited by support multiple ids
  src/metabase/api/search.clj
  src/metabase/search/config.clj
  src/metabase/search/filter.clj
  test/metabase/api/search_test.clj
  test/metabase/search/filter_test.clj
Labels: .Team/42 :milky_way:

#34272 Add custom warning message when leaving creating/editing a DB connection
  frontend/src/metabase/actions/containers/ActionCreatorModal/ActionCreatorModal.unit.spec.tsx
  frontend/src/metabase/admin/databases/containers/DatabaseEditApp.tsx
  frontend/src/metabase/admin/databases/containers/DatabaseEditApp.unit.spec.js
  frontend/src/metabase/admin/databases/containers/DatabaseEditApp.unit.spec.tsx
  frontend/src/metabase/admin/databases/database.js
  frontend/src/metabase/query_builder/containers/QueryBuilder.unit.spec.tsx
  frontend/test/__support__/server-mocks/database.ts
Labels: .Team/42 :milky_way:, no-backport

#34252 Add more E2E tests around joins
  e2e/test/scenarios/joins/joins.cy.spec.js
  e2e/test/scenarios/question/notebook.cy.spec.js
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33846 Add color to `ExpandButton` when moving collection
  frontend/src/metabase/containers/ItemPicker/Item.styled.tsx
Labels: backport

#34282 Fix adding filters in nested queries
  e2e/test/scenarios/filters/reproductions/34279-filters-nested-query.cy.spec.js
  frontend/src/metabase-lib/Dimension.ts
Labels: .Team/42 :milky_way:

#34310 Use HTTPS when getting version-info
  src/metabase/config.clj
  test/metabase/task/upgrade_checks_test.clj
Labels: backport, .Team/42 :milky_way:

#34314 [Manual backport] Handle mismatching date parameters in dashboard -> native question drills
  e2e/test/scenarios/native-filters/reproductions/34129.cy.spec.js
  frontend/src/metabase/parameters/utils/date-formatting.ts
  frontend/src/metabase/parameters/utils/formatting.unit.spec.ts
  frontend/src/metabase/query_builder/actions/core/initializeQB.ts
Labels: was-backported, .Blocker, .Team/42 :milky_way:, no-backport

#34315 Manual backport - Hardly visible expand icon on collection hover (#33846)
  frontend/src/metabase/containers/ItemPicker/Item.styled.tsx
Labels: was-backported, no-backport

#34319 Fix `yarn dev-ee` with new CLJS setup
  package.json
Labels: .Building & Releasing, .Team/QueryProcessor :hammer_and_wrench:, no-backport

#34328 Fix download bucket variable in release notes generation
  .github/workflows/release.yml
Labels: .Building & Releasing, .Team/PixelPolice :police_officer:, no-backport

#34263 [docs] Update expressions-list.md added another rounding example
  docs/questions/query-builder/expressions-list.md
Labels: Type:Documentation, backport

#34338 Simplify filters API
  frontend/src/metabase-lib/constants.ts
  frontend/src/metabase-lib/filter.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/common/components/FilterPicker/BooleanFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/BooleanFilterPicker/BooleanFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/BooleanFilterPicker/constants.ts
  frontend/src/metabase/common/components/FilterPicker/BooleanFilterPicker/types.ts
  frontend/src/metabase/common/components/FilterPicker/BooleanFilterPicker/utils.ts
Labels: .Team/42 :milky_way:

#34231 Misc drill thru fixes :wrench:
  enterprise/backend/test/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions_test.clj
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/drill_thru.cljc
  src/metabase/query_processor/middleware/annotate.clj
  test/metabase/api/card_test.clj
  test/metabase/lib/aggregation_test.cljc
  test/metabase/lib/drill_thru_test.cljc
  test/metabase/query_processor/middleware/annotate_test.clj
  test/metabase/query_processor_test/aggregation_test.clj
  test/metabase/query_processor_test/expression_aggregations_test.clj
  test/metabase/query_processor_test/nested_queries_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#34329 [E2E] Fix segment flake
  e2e/test/scenarios/admin/datamodel/metrics.cy.spec.js
  e2e/test/scenarios/admin/datamodel/segments.cy.spec.js
Labels: .CI & Tests, backport, flaky-test-fix

#34306 Remove unused and deprecated `delete-file!` function
  bin/build/src/metabuild_common/core.clj
  bin/build/src/metabuild_common/files.clj
Labels: Type:Tech Debt, .Backend, no-backport

#34307 Do not run frontend workflolw when label is added or removed
  .github/workflows/chromatic.yml
  .github/workflows/frontend.yml
Labels: backport, .Team/42 :milky_way:, chromatic

#34357 Fix broken metrics test
  e2e/test/scenarios/admin/datamodel/metrics.cy.spec.js
Labels: .CI & Tests

#34136 Mantine Textarea
  frontend/src/metabase/ui/components/inputs/Textarea/Textarea.stories.mdx
  frontend/src/metabase/ui/components/inputs/Textarea/Textarea.styled.tsx
  frontend/src/metabase/ui/components/inputs/Textarea/index.ts
  frontend/src/metabase/ui/components/inputs/index.ts
  frontend/src/metabase/ui/theme.ts
Labels: .Team/42 :milky_way:, no-backport

#34214 Search Milestone 2: Add `last_edited_by` search filter
  e2e/test/scenarios/onboarding/search/search.cy.spec.js
  frontend/src/metabase/search/components/DropdownSidebarFilter/DropdownSidebarFilter.styled.tsx
  frontend/src/metabase/search/components/DropdownSidebarFilter/DropdownSidebarFilter.tsx
  frontend/src/metabase/search/components/SearchSidebar/SearchSidebar.tsx
  frontend/src/metabase/search/components/SearchUserPicker/SearchUserPicker.tsx
  frontend/src/metabase/search/components/filters/CreatedByFilter/CreatedByFilter.tsx
  frontend/src/metabase/search/components/filters/LastEditedByFilter.tsx
  frontend/src/metabase/search/constants.ts
  frontend/src/metabase/search/types.ts
  frontend/src/metabase/search/utils/user-search-params/index.ts
  frontend/src/metabase/search/utils/user-search-params/user-search-params.ts
  frontend/src/metabase/search/utils/user-search-params/user-search-params.unit.spec.ts
Labels: visual, .Team/42 :milky_way:

#34365 Fix Select CSP errors
  frontend/src/metabase/ui/components/inputs/Select/Select.styled.tsx
Labels: .Team/42 :milky_way:, no-backport

#34373 New `instance_analytics.zip`
  resources/instance_analytics.zip
Labels: .Team/PixelPolice :police_officer:

#34347 Consider drill thru `:dimensions` when calculating `available-drill-thrus`
  src/metabase/lib/drill_thru.cljc
  src/metabase/lib/equality.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/schema/drill_thru.cljc
  test/metabase/lib/drill_thru_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#34352 `drill-thru-method` for sort drill thrus should handle string directions
  src/metabase/lib/drill_thru/sort.cljc
  test/metabase/lib/drill_thru/sort_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#34171 fix: Correct cache control for static js/css files
  src/metabase/server/request/util.clj
Labels: .Team/42 :milky_way:

#33865 Implement #33646
  src/metabase/driver/sql_jdbc/connection.clj
  test/metabase/driver/sql_jdbc/connection_test.clj
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#34296 [MLv2] NumberFilterPicker
  frontend/src/metabase-lib/filter.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/common/components/FilterPicker/FilterOperatorPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/FilterPicker.styled.tsx
  frontend/src/metabase/common/components/FilterPicker/FilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/NumberFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/NumberFilterPicker/NumberFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/NumberFilterPicker/constants.ts
  frontend/src/metabase/common/components/FilterPicker/NumberFilterPicker/index.ts
  frontend/src/metabase/common/components/FilterPicker/NumberFilterPicker/types.ts
  frontend/src/metabase/common/components/FilterPicker/NumberFilterPicker/utils.ts
  frontend/src/metabase/common/components/FilterPicker/StringFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/StringFilterPicker/StringFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/StringFilterPicker/constants.ts
  frontend/src/metabase/common/components/FilterPicker/StringFilterPicker/index.ts
  frontend/src/metabase/common/components/FilterPicker/StringFilterPicker/types.ts
  frontend/src/metabase/common/components/FilterPicker/StringFilterPicker/utils.ts
  frontend/src/metabase/query_builder/components/notebook/steps/FilterStep/FilterStep.tsx
Labels: visual, .Team/PixelPolice :police_officer:

#34292 Memoize audit collection id and hide custom reports with feature flag
  enterprise/backend/src/metabase_enterprise/audit_app/permissions.clj
  enterprise/backend/src/metabase_enterprise/audit_db.clj
  enterprise/backend/test/metabase_enterprise/audit_app/permissions_test.clj
  src/metabase/api/collection.clj
  src/metabase/models/collection.clj
  src/metabase/models/collection/graph.clj
  src/metabase/models/permissions.clj
  test/metabase/models/collection/graph_test.clj
  test/metabase/models/collection_test.clj
Labels: .Team/PixelPolice :police_officer:

#34376 Fix recent_views ordering on MySQL
  src/metabase/api/collection.clj
  src/metabase/models/recent_views.clj
Labels: .Team/PixelPolice :police_officer:

#34262 Enable expression dashboard filters
  e2e/test/scenarios/dashboard-filters/reproductions/17775-filter-custom-column-date.cy.spec.js
  e2e/test/scenarios/native-filters/helpers/e2e-date-filter-helpers.js
  src/metabase/driver/common/parameters/dates.clj
  src/metabase/models/params.clj
  src/metabase/query_processor/middleware/parameters/mbql.clj
  test/metabase/query_processor/middleware/parameters/mbql_test.clj
  test/metabase/query_processor/middleware/parameters_test.clj
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#34335 Read the latest version of the secret from the DB
  src/metabase/models/secret.clj
  test/metabase/models/secret_test.clj
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#34311 Fix corrupted dashboard parameters to have "unnamed" names and slugs
  e2e/test/scenarios/dashboard-filters/reproductions/24500-gracefully-deal-with-corrupted-filter.cy.spec.js
  src/metabase/models/dashboard.clj
  test/metabase/models/dashboard_test.clj
Labels: backport, .Team/42 :milky_way:

#34186 Convert collection permissions to typescript and add unit tests
  frontend/src/metabase-types/api/permissions.ts
  frontend/src/metabase-types/store/admin.ts
  frontend/src/metabase-types/store/collection.ts
  frontend/src/metabase-types/store/index.ts
  frontend/src/metabase-types/store/mocks/admin.ts
  frontend/src/metabase/admin/permissions/components/PermissionsSidebar/PermissionsSidebar.tsx
  frontend/src/metabase/admin/permissions/components/PermissionsSidebar/PermissionsSidebarContent.tsx
  frontend/src/metabase/admin/permissions/components/PermissionsTable/PermissionsTable.jsx
  frontend/src/metabase/admin/permissions/pages/CollectionPermissionsPage/CollectionPermissionsPage.tsx
  frontend/src/metabase/admin/permissions/pages/CollectionPermissionsPage/CollectionPermissionsPage.unit.spec.tsx
  frontend/src/metabase/admin/permissions/routes.jsx
  frontend/src/metabase/admin/permissions/selectors/collection-permissions.ts
  frontend/src/metabase/entities/collections/utils.ts
  frontend/test/__support__/server-mocks/permissions.ts
Labels: .Team/PixelPolice :police_officer:, no-backport

#34154 Update liquibase 4.21.1
  deps.edn
  src/metabase/db/liquibase.clj
Labels: visual, .Team/QueryProcessor :hammer_and_wrench:

#33891 Update Liquibase
  deps.edn
  resources/migrations/000_migrations.yaml
  src/metabase/db/custom_migrations.clj
  src/metabase/db/liquibase.clj
  src/metabase/util/files.clj
  test/metabase/db/schema_migrations_test.clj
  test/metabase/db/schema_migrations_test/impl.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#34416 Remove dependent joins from subsequent stages too
  src/metabase/lib/remove_replace.cljc
  src/metabase/lib/util.cljc
  test/metabase/lib/remove_replace_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#34312 Global search: adding creator name and last editor name to search results
  src/metabase/api/search.clj
  src/metabase/search/config.clj
  src/metabase/search/filter.clj
  test/metabase/api/search_test.clj
Labels: .Team/42 :milky_way:

#34277 [jest] Add global catch for unmocked http requests
  frontend/src/metabase/containers/SaveQuestionModal.unit.spec.tsx
  frontend/src/metabase/models/containers/ModelDetailPage/ModelDetailPage.tsx
  frontend/test/jest-setup-env.js
Labels: backport, visual, .Team/42 :milky_way:

#34398 Add custom warning message when leaving changing Data Model (segments and metrics)
  frontend/src/metabase-types/api/mocks/table.ts
  frontend/src/metabase/admin/datamodel/components/FormLabel/FormLabel.tsx
  frontend/src/metabase/admin/datamodel/components/MetricForm/MetricForm.tsx
  frontend/src/metabase/admin/datamodel/components/MetricForm/MetricForm.unit.spec.tsx
  frontend/src/metabase/admin/datamodel/components/SegmentForm/SegmentForm.tsx
  frontend/src/metabase/admin/datamodel/components/SegmentForm/SegmentForm.unit.spec.tsx
  frontend/src/metabase/admin/datamodel/containers/MetricApp.jsx
  frontend/src/metabase/admin/datamodel/containers/MetricApp.unit.spec.tsx
  frontend/src/metabase/admin/datamodel/containers/SegmentApp.jsx
  frontend/src/metabase/admin/datamodel/containers/SegmentApp.unit.spec.tsx
  frontend/src/metabase/status/components/StatusListing/StatusListing.tsx
  frontend/test/__support__/server-mocks/metric.ts
  frontend/test/__support__/server-mocks/segment.ts
Labels: .Team/42 :milky_way:, no-backport

#34405 Show custom warning message when leaving editing dashboard via Cancel button
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/question/settings.cy.spec.js
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.unit.spec.tsx
  frontend/src/metabase/dashboard/containers/DashboardHeader.jsx
Labels: .Team/42 :milky_way:, no-backport

#34364 Remove and disallow H2 from E2E tests
  e2e/support/commands.js
  e2e/support/commands/database/addH2SampleDatabase.js
  e2e/support/commands/database/addSQLiteDatabase.js
  e2e/test/scenarios/admin/databases/database-prompt-banner.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/14145.cy.spec.js
  e2e/test/scenarios/native/reproductions/18148-save-button-before-it-is-possible-to-save.cy.spec.js
  e2e/test/scenarios/onboarding/home/homepage.cy.spec.js
  e2e/test/scenarios/onboarding/reference/databases.cy.spec.js
  e2e/test/scenarios/question/new.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#34436 Minor updates to the developer's guide
  docs/developers-guide/devenv.md
Labels: .Team/42 :milky_way:, no-backport

#34431 Parameterize E2E matrix
  .github/actions/build-e2e-matrix/action.yml
  .github/workflows/e2e-tests.yml
Labels: .CI & Tests, backport

#34371 [MLv2] Support invisible columns with expression-parts
  src/metabase/lib/fe_util.cljc
  test/metabase/lib/fe_util_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:, no-backport

#34331 [MLv2] Fix boolean operators for Category typed fields
  src/metabase/lib/filter/operator.cljc
  test/metabase/lib/filter_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:, no-backport

#34381 Hack to fix webpack serving stale CLJS on browser refresh
  src/metabase/util/devtools.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#34389 Sort drill thrus should come back for aggregate columns
  src/metabase/lib/drill_thru/distribution.cljc
  src/metabase/lib/drill_thru/sort.cljc
  test/metabase/lib/drill_thru/distribution_test.cljc
  test/metabase/lib/drill_thru/sort_test.cljc
  test/metabase/lib/drill_thru_test.cljc
  test/metabase/lib/test_metadata/graph_provider.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#34377 Manual backport #33865 to 47
  src/metabase/driver/sql_jdbc/connection.clj
  test/metabase/driver/sql_jdbc/connection_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#34005 Mantine Switch
  frontend/src/metabase/ui/components/inputs/Switch/Switch.stories.mdx
  frontend/src/metabase/ui/components/inputs/Switch/Switch.styled.tsx
  frontend/src/metabase/ui/components/inputs/Switch/index.ts
  frontend/src/metabase/ui/components/inputs/index.ts
  frontend/src/metabase/ui/theme.ts
Labels: .Team/PixelPolice :police_officer:, .Team/42 :milky_way:, no-backport

#34444 Improve E2E matrix generation and simplify job conditionals
  .github/actions/build-e2e-matrix/action.yml
  .github/workflows/e2e-tests.yml
Labels: .CI & Tests, no-backport

#34442 improve table-column-settings test performance
  e2e/test/scenarios/visualizations/table-column-settings.cy.spec.js
Labels: backport, flaky-test-fix, .Team/PixelPolice :police_officer:

#34418 Exclude audit v2 content from audit v1 queries
  e2e/test/scenarios/admin/datamodel/table.cy.spec.js
  enterprise/backend/src/metabase_enterprise/audit_app/pages/common/dashboards.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/dashboard_detail.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/dashboards.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/databases.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/downloads.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/queries.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/schemas.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/tables.clj
Labels: .Team/PixelPolice :police_officer:

#34401 Mantine Tabs
  frontend/src/metabase/ui/components/index.ts
  frontend/src/metabase/ui/components/navigation/Tabs/Tabs.stories.mdx
  frontend/src/metabase/ui/components/navigation/Tabs/Tabs.styled.tsx
  frontend/src/metabase/ui/components/navigation/Tabs/index.ts
  frontend/src/metabase/ui/components/navigation/index.ts
  frontend/src/metabase/ui/theme.ts
Labels: .Team/42 :milky_way:, no-backport

#34392 Mantine Divider
  frontend/src/metabase/ui/Intro.stories.mdx
  frontend/src/metabase/ui/components/buttons/Button/Button.stories.mdx
  frontend/src/metabase/ui/components/data-display/Card/Card.stories.mdx
  frontend/src/metabase/ui/components/feedback/Loader/Loader.stories.mdx
  frontend/src/metabase/ui/components/index.ts
  frontend/src/metabase/ui/components/inputs/Checkbox/Checkbox.stories.mdx
  frontend/src/metabase/ui/components/inputs/FileInput/FileInput.stories.mdx
  frontend/src/metabase/ui/components/inputs/NumberInput/NumberInput.stories.mdx
  frontend/src/metabase/ui/components/inputs/Radio/Radio.stories.mdx
  frontend/src/metabase/ui/components/inputs/Select/Select.stories.mdx
  frontend/src/metabase/ui/components/inputs/TextInput/TextInput.stories.mdx
  frontend/src/metabase/ui/components/inputs/Textarea/Textarea.stories.mdx
  frontend/src/metabase/ui/components/navigation/Tabs/Tabs.stories.mdx
  frontend/src/metabase/ui/components/navigation/Tabs/Tabs.styled.tsx
  frontend/src/metabase/ui/components/navigation/Tabs/index.ts
  frontend/src/metabase/ui/components/navigation/index.ts
  frontend/src/metabase/ui/components/overlays/Menu/Menu.stories.mdx
  frontend/src/metabase/ui/components/typography/Anchor/Anchor.stories.mdx
  frontend/src/metabase/ui/components/typography/Text/Text.stories.mdx
  frontend/src/metabase/ui/components/typography/Title/Title.stories.mdx
  frontend/src/metabase/ui/components/utils/Divider/Divider.stories.mdx
  frontend/src/metabase/ui/components/utils/Divider/Divider.styled.tsx
  frontend/src/metabase/ui/components/utils/Divider/index.ts
  frontend/src/metabase/ui/components/utils/Paper/Paper.stories.mdx
  frontend/src/metabase/ui/components/utils/index.ts
  frontend/src/metabase/ui/theme.ts
Labels: .Team/42 :milky_way:, no-backport

#34412 Add missing models to `copy` command
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  src/metabase/cmd/copy.clj
  src/metabase/util/jvm.clj
  test/metabase/cmd/copy/h2_test.clj
  test/metabase/cmd/copy_test.clj
  test/metabase/cmd/load_and_dump_test.clj
  test/metabase/models/revision_test.clj
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#34434 Bump Mongo used in driver tests to `v4.4`
  .github/workflows/drivers.yml
Labels: .CI & Tests, backport

#34465 Modify SearchResult to fit new search payload
  frontend/src/metabase-types/api/mocks/search.ts
  frontend/src/metabase-types/api/search.ts
Labels: .Team/42 :milky_way:

#34475 🍒 Backport segment and metric E2E flake fixes
  e2e/test/scenarios/admin/datamodel/metrics.cy.spec.js
  e2e/test/scenarios/admin/datamodel/segments.cy.spec.js
Labels: was-backported

#34478 🍒 Remove and disallow H2 from E2E tests (#34364)
  e2e/support/commands.js
  e2e/support/commands/database/addH2SampleDatabase.js
  e2e/support/commands/database/addSQLiteDatabase.js
  e2e/test/scenarios/admin/databases/database-prompt-banner.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/14145.cy.spec.js
  e2e/test/scenarios/native/reproductions/18148-save-button-before-it-is-possible-to-save.cy.spec.js
  e2e/test/scenarios/onboarding/home/homepage.cy.spec.js
  e2e/test/scenarios/onboarding/reference/databases.cy.spec.js
  e2e/test/scenarios/question/new.cy.spec.js
Labels: was-backported

#34485 add Alexander Solovyov to the team.json
  .github/team.json
Labels: .Team/42 :milky_way:

#34476 🍒 Backport E2E matrix improvements
  .github/actions/build-e2e-matrix/action.yml
  .github/workflows/e2e-tests.yml
Labels: was-backported

#34484 Refactor confirmation modal assertions
  frontend/src/metabase/actions/containers/ActionCreatorModal/ActionCreatorModal.unit.spec.tsx
  frontend/src/metabase/admin/databases/containers/DatabaseEditApp.unit.spec.tsx
  frontend/src/metabase/admin/datamodel/containers/MetricApp.unit.spec.tsx
  frontend/src/metabase/admin/datamodel/containers/SegmentApp.unit.spec.tsx
  frontend/src/metabase/components/ConfirmContent/ConfirmContent.tsx
  frontend/src/metabase/components/LeaveConfirmationModal/LeaveConfirmationModal.tsx
  frontend/src/metabase/components/LeaveConfirmationModal/LeaveConfirmationModalContent.tsx
  frontend/src/metabase/components/LeaveConfirmationModal/index.ts
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.unit.spec.tsx
  frontend/src/metabase/dashboard/containers/DashboardHeader.jsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.unit.spec.tsx
Labels: .Team/42 :milky_way:, no-backport

#34477 🍒 Bump Mongo used in driver tests to `v4.4` (#34434)
  .github/workflows/drivers.yml
Labels: was-backported

#34488 Exclude `team.json` from CI triggers in file paths
  .github/file-paths.yaml
Labels: .CI & Tests, no-backport

#34356 Search Milestone 3: Native Query Search Toggle
  e2e/test/scenarios/onboarding/search/search.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/content_verification/VerifiedFilter/VerifiedFilter.tsx
  frontend/src/metabase/search/components/DropdownSidebarFilter/DropdownSidebarFilter.tsx
  frontend/src/metabase/search/components/DropdownSidebarFilter/DropdownSidebarFilter.unit.spec.tsx
  frontend/src/metabase/search/components/SearchSidebar/SearchSidebar.tsx
  frontend/src/metabase/search/components/ToggleSidebarFilter/ToggleSidebarFilter.tsx
  frontend/src/metabase/search/components/ToggleSidebarFilter/ToggleSidebarFilter.unit.spec.tsx
  frontend/src/metabase/search/components/filters/CreatedByFilter/CreatedByFilter.tsx
  frontend/src/metabase/search/components/filters/NativeQueryFilter/NativeQueryFilter.tsx
  frontend/src/metabase/search/components/filters/NativeQueryFilter/NativeQueryLabel.tsx
  frontend/src/metabase/search/components/filters/NativeQueryFilter/index.ts
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilter.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterDisplay.tsx
  frontend/src/metabase/search/constants.ts
  frontend/src/metabase/search/containers/SearchApp.styled.tsx
  frontend/src/metabase/search/types.ts
Labels: .Team/42 :milky_way:

#34399 [Dashboard] Do not lose filters state on navigating back from Question
  e2e/test/scenarios/dashboard/reproductions/34382-dashboard-back-navigation-preserve-filters.cy.spec.js
  frontend/src/metabase/dashboard/actions/data-fetching.js
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.jsx
  frontend/src/metabase/dashboard/hoc/DashboardData.jsx
  frontend/src/metabase/dashboard/reducers.js
  frontend/src/metabase/dashboard/reducers.unit.spec.js
  frontend/src/metabase/dashboard/selectors/selectors.js
  frontend/src/metabase/parameters/components/FilterApplyButton/FilterApplyButton.tsx
  frontend/src/metabase/parameters/components/FilterApplyButton/index.ts
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.tsx
Labels: backport, .Team/42 :milky_way:

#34473 Fix 25638 spinners change color
  webpack.config.js
Labels: backport

#34397 Persist search filters across searches
  e2e/test/scenarios/onboarding/search/search.cy.spec.js
  frontend/src/metabase/nav/components/search/SearchBar/SearchBar.tsx
  frontend/src/metabase/nav/components/search/SearchBar/SearchBar.unit.spec.tsx
  frontend/src/metabase/search/utils/search-location/search-location.ts
  frontend/src/metabase/search/utils/search-location/search-location.unit.spec.ts
Labels: .Team/42 :milky_way:

#34493 Manual backport: [Dashboard] Do not lose filters state on navigating back from Question
  e2e/test/scenarios/dashboard/reproductions/34382-dashboard-back-navigation-preserve-filters.cy.spec.js
  frontend/src/metabase/dashboard/actions/data-fetching.js
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.jsx
  frontend/src/metabase/dashboard/hoc/DashboardData.jsx
  frontend/src/metabase/dashboard/reducers.js
  frontend/src/metabase/dashboard/reducers.unit.spec.js
  frontend/src/metabase/dashboard/selectors/selectors.js
  frontend/src/metabase/parameters/components/FilterApplyButton/FilterApplyButton.tsx
  frontend/src/metabase/parameters/components/FilterApplyButton/index.ts
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.tsx
Labels: .Team/42 :milky_way:

#34452 Make broken branch notification less obnoxious
  .github/workflows/rerun-workflows.yml
Labels: .CI & Tests, backport, .Team/PixelPolice :police_officer:

#34489 Bump clj-kondo to 2023.09.07
  .github/workflows/backend.yml
  test/metabase/cmd/dump_to_h2_test.clj
  test/metabase/cmd/rotate_encryption_key_test.clj
Labels: backport, .Team/42 :milky_way:

#34388 [auditv2] Fix more e2e tests
  e2e/support/cypress_data.js
  e2e/test/scenarios/admin-2/auditing/questions-audit.cy.spec.js
  e2e/test/scenarios/admin/datamodel/table.cy.spec.js
  e2e/test/scenarios/admin/settings/localization.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/joins/reproductions/15578-remapped-values-joins.cy.spec.js
  e2e/test/scenarios/models/models.cy.spec.js
  e2e/test/scenarios/models/reproductions/19776-data-picker-not-displayed-after-archiving-model.cy.spec.js
  e2e/test/scenarios/models/reproductions/29378-actions-search-crash.cy.spec.js
  e2e/test/scenarios/models/reproductions/29517-native-remapped-model-drill-through-click-behavior.cy.spec.js
  e2e/test/scenarios/organization/moderation-question.cy.spec.js
  e2e/test/scenarios/organization/timelines-question.cy.spec.js
  e2e/test/scenarios/question/new.cy.spec.js
  e2e/test/scenarios/question/reproductions/25144-saved-questions-first-question.cy.spec.js
  e2e/test/scenarios/sharing/alert/alert.cy.spec.js
  e2e/test/scenarios/sharing/subscriptions.cy.spec.js
  e2e/test/scenarios/visualizations/table-column-settings.cy.spec.js
  enterprise/backend/src/metabase_enterprise/audit_app/pages/common/dashboards.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/dashboard_detail.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/dashboards.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/databases.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/downloads.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/queries.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/schemas.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/tables.clj
Labels: .CI & Tests, .Team/PixelPolice :police_officer:

#34358 Prevent empty dashboard parameter labels
  e2e/test/scenarios/dashboard-filters/parameters.cy.spec.js
  frontend/src/metabase/parameters/components/ParameterSettings/ParameterSettings.tsx
  frontend/src/metabase/parameters/components/ParameterSettings/ParameterSettings.unit.spec.tsx
  frontend/src/metabase/parameters/utils/dashboards.ts
  frontend/src/metabase/parameters/utils/dashboards.unit.spec.js
Labels: .Team/42 :milky_way:, no-backport

#33334 Remove most of MLv1 joins code
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/src/metabase-lib/queries/structured/Join.ts
  frontend/src/metabase-lib/queries/utils/join.js
  frontend/src/metabase-lib/queries/utils/query.js
  frontend/test/metabase-lib/lib/queries/StructuredQuery-clean.unit.spec.js
  frontend/test/metabase-lib/lib/queries/StructuredQuery-joins.unit.spec.js
  frontend/test/metabase-lib/lib/queries/structured/Join.unit.spec.js
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#34407 Revert `openSteps` notebook hack for MLv2 joins
  frontend/src/metabase/query_builder/components/notebook/NotebookSteps/NotebookSteps.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.tsx
  frontend/src/metabase/query_builder/components/notebook/types.ts
Labels: .Team/QueryProcessor :hammer_and_wrench:

#34448 [MLv2] Coordinate Filter Picker
  frontend/src/metabase-lib/filter.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/common/components/FilterPicker/CoordinateFilterPicker/CoordinateColumnSelect.tsx
  frontend/src/metabase/common/components/FilterPicker/CoordinateFilterPicker/CoordinateFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/CoordinateFilterPicker/constants.ts
  frontend/src/metabase/common/components/FilterPicker/CoordinateFilterPicker/index.ts
  frontend/src/metabase/common/components/FilterPicker/CoordinateFilterPicker/types.ts
  frontend/src/metabase/common/components/FilterPicker/CoordinateFilterPicker/utils.ts
  frontend/src/metabase/common/components/FilterPicker/FilterPicker.tsx
Labels: .Team/PixelPolice :police_officer:

#34501 MLv2 Joins — Disable RHS table changes
  frontend/src/metabase/query_builder/components/notebook/NotebookCell/NotebookCell.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/NotebookCell/NotebookCell.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTablePicker/JoinTablePicker.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTablePicker/JoinTablePicker.tsx
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#34500 Add basic specific date filters
  frontend/src/metabase/common/components/DatePicker/DatePicker.tsx
  frontend/src/metabase/common/components/DatePicker/DateShortcutPicker/constants.ts
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/RelativeDatePicker.tsx
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePicker.tsx
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/DateRangePicker/index.ts
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/SingleDatePicker/SingleDatePicker.tsx
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/SingleDatePicker/index.ts
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/SpecificDatePicker.styled.tsx
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/SpecificDatePicker.tsx
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/constants.ts
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/index.ts
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/types.ts
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/utils.ts
  frontend/src/metabase/common/components/DatePicker/types.ts
  frontend/src/metabase/common/components/FilterPicker/DateFilterPicker/utils.ts
  frontend/src/metabase/ui/components/dates/DatePicker/index.ts
  frontend/src/metabase/ui/components/dates/index.ts
  frontend/src/metabase/ui/components/index.ts
  frontend/src/metabase/ui/components/navigation/Tabs/Tabs.styled.tsx
  package.json
  yarn.lock
Labels: .Team/42 :milky_way:, no-backport

#34380 Add relative date filters UI
  frontend/src/metabase/common/components/DatePicker/BackButton/BackButton.tsx
  frontend/src/metabase/common/components/DatePicker/BackButton/index.ts
  frontend/src/metabase/common/components/DatePicker/DatePicker.tsx
  frontend/src/metabase/common/components/DatePicker/DateShortcutPicker/constants.ts
  frontend/src/metabase/common/components/DatePicker/ExcludeDatePicker/ExcludeDatePicker.tsx
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/CurrentDatePicker/CurrentDatePicker.tsx
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/CurrentDatePicker/constants.ts
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/CurrentDatePicker/index.ts
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/DateIntervalPicker/DateIntervalPicker.tsx
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/DateIntervalPicker/index.ts
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/DateIntervalPicker/utils.ts
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/DateOffsetIntervalPicker/DateOffsetIntervalPicker.styled.tsx
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/DateOffsetIntervalPicker/DateOffsetIntervalPicker.tsx
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/DateOffsetIntervalPicker/index.ts
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/DateOffsetIntervalPicker/utils.ts
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/RelativeDatePicker.styled.tsx
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/RelativeDatePicker.tsx
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/constants.ts
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/index.ts
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/types.ts
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/utils.ts
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePicker.tsx
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/DateRangePicker/index.ts
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/SingleDatePicker/SingleDatePicker.tsx
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/SingleDatePicker/index.ts
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/SpecificDatePicker.styled.tsx
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/SpecificDatePicker.tsx
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/constants.ts
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/index.ts
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/types.ts
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/utils.ts
  frontend/src/metabase/common/components/DatePicker/types.ts
  frontend/src/metabase/common/components/FilterPicker/DateFilterPicker/DateFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/DateFilterPicker/utils.ts
  frontend/src/metabase/ui/components/dates/DatePicker/index.ts
  frontend/src/metabase/ui/components/dates/index.ts
  frontend/src/metabase/ui/components/index.ts
  frontend/src/metabase/ui/components/inputs/FileInput/FileInput.styled.tsx
  frontend/src/metabase/ui/components/inputs/NumberInput/NumberInput.styled.tsx
  frontend/src/metabase/ui/components/inputs/Select/Select.styled.tsx
  frontend/src/metabase/ui/components/inputs/TextInput/TextInput.styled.tsx
  frontend/src/metabase/ui/components/inputs/Textarea/Textarea.styled.tsx
  frontend/src/metabase/ui/components/navigation/Tabs/Tabs.styled.tsx
  package.json
  yarn.lock
Labels: .Team/42 :milky_way:, no-backport

#34513 defendpoint without redefine routes
  src/metabase/api/common.clj
Labels: .Team/42 :milky_way:, no-backport

#34512 Updates hawk to include supports `#hawk/malli` reader within `=?`
  deps.edn
  enterprise/backend/test/metabase_enterprise/sandbox/api/gtap_test.clj
  test/metabase/api/automagic_dashboards_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/search_test.clj
  test/metabase/models/dashboard_test.clj
Labels: .Team/42 :milky_way:, no-backport

#34466 Split `SearchResult` components into separate files
  frontend/src/metabase/nav/components/search/RecentsList/RecentsList.jsx
  frontend/src/metabase/nav/components/search/SearchResults/SearchResults.tsx
  frontend/src/metabase/search/components/SearchResult/SearchResult.styled.tsx
  frontend/src/metabase/search/components/SearchResult/SearchResult.tsx
  frontend/src/metabase/search/components/SearchResult/SearchResult.unit.spec.tsx
  frontend/src/metabase/search/components/SearchResult/components/CollectionIcon.tsx
  frontend/src/metabase/search/components/SearchResult/components/Context.styled.tsx
  frontend/src/metabase/search/components/SearchResult/components/Context.tsx
  frontend/src/metabase/search/components/SearchResult/components/DefaultIcon.tsx
  frontend/src/metabase/search/components/SearchResult/components/ItemIcon.styled.tsx
  frontend/src/metabase/search/components/SearchResult/components/ItemIcon.tsx
  frontend/src/metabase/search/components/SearchResult/components/Score.tsx
  frontend/src/metabase/search/components/SearchResult/components/constants.ts
  frontend/src/metabase/search/components/SearchResult/components/index.ts
  frontend/src/metabase/search/components/SearchResult/index.ts
  frontend/src/metabase/search/containers/SearchApp.jsx
  frontend/src/metabase/search/containers/SearchResultSection.tsx
Labels: .Team/42 :milky_way:, no-backport

#34424 BE: Remove linked filters from dashboard if values source type is not "From connected fields"
  src/metabase/models/dashboard.clj
  test/metabase/models/dashboard_test.clj
Labels: .Team/42 :milky_way:, no-backport

#34518 Manual backport: Combine linting fe jobs into one
  .github/workflows/frontend.yml
  package.json
Labels: .Team/42 :milky_way:

#34317 Global search: option to search native queries
  e2e/test/scenarios/onboarding/search/search.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/content_verification/VerifiedFilter/VerifiedFilter.tsx
  frontend/src/metabase/search/components/DropdownSidebarFilter/DropdownSidebarFilter.tsx
  frontend/src/metabase/search/components/DropdownSidebarFilter/DropdownSidebarFilter.unit.spec.tsx
  frontend/src/metabase/search/components/SearchSidebar/SearchSidebar.tsx
  frontend/src/metabase/search/components/SearchSidebar/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/search/components/SearchSidebar/tests/premium.unit.spec.tsx
  frontend/src/metabase/search/components/SearchSidebar/tests/setup.tsx
  frontend/src/metabase/search/components/ToggleSidebarFilter/ToggleSidebarFilter.tsx
  frontend/src/metabase/search/components/ToggleSidebarFilter/ToggleSidebarFilter.unit.spec.tsx
  frontend/src/metabase/search/components/filters/CreatedByFilter/CreatedByFilter.tsx
  frontend/src/metabase/search/components/filters/LastEditedByFilter.tsx
  frontend/src/metabase/search/components/filters/NativeQueryFilter/NativeQueryFilter.tsx
  frontend/src/metabase/search/components/filters/NativeQueryFilter/NativeQueryLabel.tsx
  frontend/src/metabase/search/components/filters/NativeQueryFilter/index.ts
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilter.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterDisplay.tsx
  frontend/src/metabase/search/constants.ts
  frontend/src/metabase/search/containers/SearchApp.styled.tsx
  frontend/src/metabase/search/types.ts
  src/metabase/api/search.clj
  src/metabase/search/config.clj
  src/metabase/search/filter.clj
  src/metabase/search/scoring.clj
  test/metabase/api/search_test.clj
  test/metabase/search/filter_test.clj
  test/metabase/search/scoring_test.clj
Labels: .Team/42 :milky_way:

#34507 Add `johnswanson` to the team roster :tada:
  .github/team.json
Labels: .Team/PixelPolice :police_officer:, no-backport

#34487 Show custom warning message when leaving editing model via Cancel button
  e2e/test/scenarios/models/models-metadata.cy.spec.js
  e2e/test/scenarios/models/models-query-editor.cy.spec.js
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.unit.spec.tsx
Labels: visual, .Team/42 :milky_way:, no-backport

#34494 Refactor - reduce duplication in QueryBuilder unit tests
  frontend/src/metabase/query_builder/containers/QueryBuilder.unit.spec.tsx
Labels: .Team/42 :milky_way:, no-backport

#34423 E2E isolate mongo
  .github/actions/build-e2e-matrix/action.yml
  .github/workflows/e2e-tests.yml
  e2e/snapshot-creators/qa-db.cy.snap.js
  e2e/support/helpers/e2e-setup-helpers.js
  e2e/test/scenarios/admin/databases/add-new-database.cy.spec.js
  e2e/test/scenarios/native/native-mongo.cy.spec.js
  e2e/test/scenarios/native/reproductions/15946-mongo-pre-select-table.cy.spec.js
  e2e/test/scenarios/native/reproductions/32121-sql-source-query-can-explore-results.cy.spec.js
  e2e/test/scenarios/question/reproductions/13097-mongo-apply-distinct-count-multiple-columns.cy.spec.js
  e2e/test/scenarios/question/reproductions/17963-mongo-filter-expression-compare-two-fields.cy.spec.js
  e2e/test/scenarios/visualizations/reproductions/16170-line-mongo-replace-missing-values.cy.spec.js
Labels: .CI & Tests, backport

#34502 add repro test for #26467 which has been already fixed with #28945
  e2e/test/scenarios/visualizations/pivot_tables.cy.spec.js
Labels: backport, .Team/42 :milky_way:

#34369 Prevent dashboard parameter labels with identical slugs
  frontend/src/metabase/parameters/components/ParameterSettings/ParameterSettings.tsx
  frontend/src/metabase/parameters/components/ParameterSettings/ParameterSettings.unit.spec.tsx
  frontend/src/metabase/parameters/components/ParameterSidebar/ParameterSidebar.tsx
  frontend/src/metabase/parameters/components/ParameterSidebar/ParameterSidebar.unit.spec.tsx
Labels: .Team/42 :milky_way:, no-backport

#34454 Move some pre-release checks to build job from test job
  .github/workflows/build-for-release.yml
  .github/workflows/pre-release.yml
Labels: .Building & Releasing, .Team/PixelPolice :police_officer:, no-backport

#34536 Fix `load-from-h2` logic to loads entire system before running from uberjar
  src/metabase/cmd/copy.clj
  src/metabase/util/jvm.clj
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#34532 Manual backport of 34473
  webpack.config.js
Labels: was-backported

#34533 Manual backport of #34412
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  src/metabase/cmd/copy.clj
  src/metabase/util/jvm.clj
  test/metabase/cmd/copy/h2_test.clj
  test/metabase/cmd/copy_test.clj
  test/metabase/cmd/load_and_dump_test.clj
  test/metabase/models/revision_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#34546 Manual backport of #34536
  src/metabase/cmd/copy.clj
  src/metabase/util/jvm.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#34420 Add field selection to SmartScalar
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.jsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.unit.spec.js
Labels: visual, .Team/PixelPolice :police_officer:, no-backport

#34470 Run be tests on Java 21, and skip 17 and 19 altogether
  .github/workflows/backend.yml
Labels: no-backport

#34552 Use private ReplayIO API key
  .github/workflows/e2e-tests.yml
Labels: .CI & Tests, backport

#34555 Increase E2E tests running on Replayio frequency
  .github/workflows/e2e-tests.yml
Labels: no-backport

#34535 🍒 E2E isolate mongo (#34423)
  .github/actions/build-e2e-matrix/action.yml
  .github/workflows/e2e-tests.yml
  e2e/snapshot-creators/qa-db.cy.snap.js
  e2e/support/helpers/e2e-setup-helpers.js
  e2e/test/scenarios/admin/databases/add-new-database.cy.spec.js
  e2e/test/scenarios/native/native-mongo.cy.spec.js
  e2e/test/scenarios/native/reproductions/15946-mongo-pre-select-table.cy.spec.js
  e2e/test/scenarios/native/reproductions/32121-sql-source-query-can-explore-results.cy.spec.js
  e2e/test/scenarios/question/reproductions/13097-mongo-apply-distinct-count-multiple-columns.cy.spec.js
  e2e/test/scenarios/question/reproductions/17963-mongo-filter-expression-compare-two-fields.cy.spec.js
  e2e/test/scenarios/visualizations/reproductions/16170-line-mongo-replace-missing-values.cy.spec.js
Labels: was-backported

#34553 Clean up yarn scripts
  package.json
Labels: Type:Tech Debt, backport

#34558 🍒 Clean up yarn scripts (#34553)
  package.json
Labels: was-backported

#34560 Install dependencies before `dev` and `dev-ee`
  package.json
Labels: backport

#34561 🍒 Backport follow up yarn script changes
  package.json
Labels: was-backported

#34543 Remove line added by mistake from `webpack.config.js`
  webpack.config.js
Labels: no-backport

#34539 Update Apache POI
  deps.edn
  test/metabase/query_processor/streaming/xlsx_test.clj
Labels: backport

#34516 Invalid params reporting
  src/metabase/api/common.clj
  test/metabase/api/common/internal_test.clj
Labels: no-backport

#34504 Add lbrdnk into qpd team
  .github/team.json
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#34285 re-initialize qb when navigating back
  e2e/test/scenarios/native/native.cy.spec.js
  frontend/src/metabase/query_builder/actions/navigation.js
Labels: backport, .Team/PixelPolice :police_officer:, .Team/42 :milky_way:

#34538 Don't suggest joining something by its implicitly joinable columns
  src/metabase/lib/join.cljc
  test/metabase/lib/join_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#34575 [Manual Backport] re-initialize qb when navigating back (#34285)
  e2e/test/scenarios/native/native.cy.spec.js
  frontend/src/metabase/query_builder/actions/navigation.js
Labels: was-backported, .Team/PixelPolice :police_officer:

#34585 Add AuditLog and RecentViews to `metabase.cmd.copy`
  src/metabase/cmd/copy.clj
Labels: .Team/PixelPolice :police_officer:

#34456 Exclude summarize-column-by-time drill-thru for aggregate columns
  src/metabase/lib/drill_thru/summarize_column_by_time.cljc
  test/metabase/lib/drill_thru/summarize_column_by_time_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#34588 Revert "Clean up yarn scripts"
  package.json
Labels: backport

#34568 Make implicit fields coming from source query expressions use string id
  src/metabase/query_processor/middleware/add_implicit_clauses.clj
  test/metabase/query_processor/middleware/add_implicit_clauses_test.clj
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#34567 Sort scripts in package.json alphabetically
  frontend/src/metabase/common/hooks/use-entity-list-query/use-entity-list-query.unit.spec.tsx
  package.json
  release/package.json
Labels: backport, .Team/42 :milky_way:

#34590 🍒 Revert "Clean up yarn scripts" (#34588)
  package.json
Labels: was-backported

#33738 run with-temp in a transaction
  .clj-kondo/config.edn
  .clj-kondo/hooks/clojure/test.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/api/group_manager_test.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/pages/alerts_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/pages/dashboard_subscriptions_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/pages_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/models/params/field_values_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/test_util.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/seed_entity_ids_test.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/saml_test.clj
  src/metabase/moderation.clj
  test/metabase/actions/execution_test.clj
  test/metabase/actions/test_util.clj
  test/metabase/api/action_test.clj
  test/metabase/api/collection_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/embed_test.clj
  test/metabase/api/public_test.clj
  test/metabase/api/user_test.clj
  test/metabase/async/streaming_response_test.clj
  test/metabase/integrations/common_test.clj
  test/metabase/models/login_history_test.clj
  test/metabase/models/user_test.clj
  test/metabase/sync/sync_metadata/fields/sync_instances_test.clj
  test/metabase/task/sync_databases_test.clj
  test/metabase/test.clj
  test/metabase/test/redefs.clj
  test/metabase/test/util.clj
Labels: .Team/42 :milky_way:, no-backport

#33078 MLv2 — Migrate notebook's join step to MLv2
  e2e/test/scenarios/binning/binning-reproductions.cy.spec.js
  e2e/test/scenarios/joins/joins.cy.spec.js
  e2e/test/scenarios/joins/reproductions/12928-joining-questions-with-joins.cy.spec.js
  e2e/test/scenarios/joins/reproductions/15342-mysql-correct-joins-order.cy.spec.js
  e2e/test/scenarios/joins/reproductions/15578-remapped-values-joins.cy.spec.js
  e2e/test/scenarios/joins/reproductions/17710-notebook-incomplete-joins-removed.cy.spec.js
  e2e/test/scenarios/joins/reproductions/17712-notebook-extra-sections-removed.cy.spec.js
  e2e/test/scenarios/joins/reproductions/17968-notebook-join-table-names.cy.spec.js
  e2e/test/scenarios/joins/reproductions/31769-mlv2-join-dropped.cy.spec.js
  e2e/test/scenarios/question/notebook.cy.spec.js
  frontend/src/metabase-lib/expression.ts
  frontend/src/metabase-lib/join.ts
  frontend/src/metabase-lib/metadata.ts
  frontend/src/metabase-lib/metadata/Metadata.ts
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/src/metabase-lib/queries/structured/Join.ts
  frontend/src/metabase-lib/queries/utils/field-ref.js
  frontend/src/metabase-lib/queries/utils/join.js
  frontend/src/metabase-lib/queries/utils/query.js
  frontend/src/metabase-lib/query.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/common/components/FieldPicker/FieldPicker.tsx
  frontend/src/metabase/common/components/QueryColumnPicker/QueryColumnPicker.tsx
  frontend/src/metabase/common/components/QueryColumnPicker/index.ts
  frontend/src/metabase/components/PopoverWithTrigger/TippyPopoverWithTrigger.tsx
  frontend/src/metabase/query_builder/components/notebook/NotebookCell/NotebookCell.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/NotebookCell/NotebookCell.tsx
  frontend/src/metabase/query_builder/components/notebook/NotebookStep/steps.ts
  frontend/src/metabase/query_builder/components/notebook/NotebookSteps/NotebookSteps.tsx
  frontend/src/metabase/query_builder/components/notebook/lib/steps.ts
  frontend/src/metabase/query_builder/components/notebook/steps/DataStep/DataStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionColumnPicker/JoinConditionColumnPicker.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionColumnPicker/JoinConditionColumnPicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionColumnPicker/index.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionOperatorPicker/JoinConditionOperatorPicker.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionOperatorPicker/JoinConditionOperatorPicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionOperatorPicker/index.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.jsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStrategyPicker/JoinStrategyPicker.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStrategyPicker/JoinStrategyPicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStrategyPicker/index.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTablePicker/JoinTablePicker.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTablePicker/JoinTablePicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTablePicker/index.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/use-join-condition.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/use-join.ts
  frontend/test/metabase-lib/lib/queries/StructuredQuery-clean.unit.spec.js
  frontend/test/metabase-lib/lib/queries/StructuredQuery-joins.unit.spec.js
  frontend/test/metabase-lib/lib/queries/structured/Join.unit.spec.js
  src/metabase/lib/join.cljc
  src/metabase/lib/js.cljs
  test/metabase/lib/join_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:, no-backport

#34591 Manual backport - Sort scripts in package.json alphabetically (#34567)
  frontend/src/metabase/common/hooks/use-entity-list-query/use-entity-list-query.unit.spec.tsx
  package.json
Labels: was-backported

#34173 Add PKs to CSVs
  src/metabase/driver.clj
  src/metabase/driver/h2.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql_jdbc.clj
  src/metabase/upload.clj
  test/metabase/upload_test.clj
Labels: .Team/42 :milky_way:, no-backport

#34597 Fix `FilterPicker` for numeric PK and FK columns
  frontend/src/metabase/common/components/FilterPicker/FilterPicker.tsx
Labels: .Team/QueryProcessor :hammer_and_wrench:

#34594 🍒 Manual Backport: Make implicit fields coming from source query expressions use string id
  src/metabase/query_processor/middleware/add_implicit_clauses.clj
  test/metabase/query_processor/middleware/add_implicit_clauses_test.clj
Labels: was-backported

#34579 Prune deleted in-memory databases on startup (in dev)
  dev/src/dev.clj
Labels: .Team/PixelPolice, no-backport

#34569 Intersect filter widget and column operators
  frontend/src/metabase-lib/filter.ts
  frontend/src/metabase/common/components/FilterPicker/BooleanFilterPicker/BooleanFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/BooleanFilterPicker/types.ts
  frontend/src/metabase/common/components/FilterPicker/BooleanFilterPicker/utils.ts
  frontend/src/metabase/common/components/FilterPicker/CoordinateFilterPicker/CoordinateColumnSelect.tsx
  frontend/src/metabase/common/components/FilterPicker/CoordinateFilterPicker/CoordinateFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/CoordinateFilterPicker/constants.ts
  frontend/src/metabase/common/components/FilterPicker/CoordinateFilterPicker/types.ts
  frontend/src/metabase/common/components/FilterPicker/CoordinateFilterPicker/utils.ts
  frontend/src/metabase/common/components/FilterPicker/FilterOperatorPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/NumberFilterPicker/NumberFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/NumberFilterPicker/constants.ts
  frontend/src/metabase/common/components/FilterPicker/NumberFilterPicker/types.ts
  frontend/src/metabase/common/components/FilterPicker/NumberFilterPicker/utils.ts
  frontend/src/metabase/common/components/FilterPicker/StringFilterPicker/StringFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/StringFilterPicker/constants.ts
  frontend/src/metabase/common/components/FilterPicker/StringFilterPicker/types.ts
  frontend/src/metabase/common/components/FilterPicker/StringFilterPicker/utils.ts
  frontend/src/metabase/common/components/FilterPicker/types.ts
  frontend/src/metabase/common/components/FilterPicker/utils.ts
Labels: .Team/QueryProcessor

#34508 Automatically manage milestones in releases
  .github/workflows/release.yml
  release/src/github.ts
  release/src/version-helpers.ts
  release/src/version-helpers.unit.spec.ts
Labels: .Building & Releasing, .Team/PixelPolice, no-backport

#34599 Update test `expression-with-only-field-in-source-query-test`
  test/metabase/query_processor/middleware/add_implicit_clauses_test.clj
Labels: .Team/QueryProcessor, no-backport

#34534 Remove db dependant extensions
  frontend/src/metabase/lib/engine.js
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx
  frontend/test/__support__/mocks.js
Labels: backport, .Team/42

#34451 add collection.type to search results
  src/metabase/api/search.clj
  src/metabase/cmd/copy.clj
  src/metabase/search/config.clj
  src/metabase/search/scoring.clj
  test/metabase/api/search_test.clj
Labels: .Team/PixelPolice

#34586 Let them eat cake
  docs/api/timeline-event.md
  docs/api/timeline.md
  e2e/test/scenarios/organization/timelines-collection.cy.spec.js
  frontend/src/metabase/core/components/Icon/icons/index.ts
  frontend/src/metabase/lib/timelines.ts
  src/metabase/models/timeline.clj
Labels: backport
