Repository metabase/metabase, pull requests merged in 2023-06, with the labels that each got.

#31198 Manual backport - Fix - Cannot run native queries against MongoDB unless explicitly selecting the table (#31111)
  e2e/test/scenarios/native/reproductions/15946-mongo-pre-select-table.cy.spec.js
  frontend/src/metabase-types/api/query.ts
  frontend/src/metabase/query_builder/components/view/ConvertQueryModal/ConvertQueryModal.tsx
  frontend/src/metabase/query_builder/components/view/ConvertQueryModal/utils.ts
Labels: was-backported

#31196 [E2E] Chain the custom `button` command
  e2e/support/commands/ui/button.js
  e2e/test/scenarios/collections/collections.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/19745-cc-nested-query-remove-expressions.cy.spec.js
  e2e/test/scenarios/models/reproductions/28971-filters-model-new-model.cy.spec.js
  e2e/test/scenarios/organization/timelines-collection.cy.spec.js
Labels: .CI & Tests, backport

#31199 [E2E] Fix ReplayIO missing metadata
  .github/workflows/e2e-tests.yml
  e2e/support/config.js
  e2e/support/cypress.js
Labels: .CI & Tests

#31208 [E2E] Fix ReplayIO recordings upload
  .github/workflows/e2e-tests.yml
Labels: .CI & Tests

#31239 🍒 [E2E] Chain the custom `button` command (#31196)
  e2e/support/commands/ui/button.js
  e2e/test/scenarios/collections/collections.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/19745-cc-nested-query-remove-expressions.cy.spec.js
  e2e/test/scenarios/models/reproductions/28971-filters-model-new-model.cy.spec.js
  e2e/test/scenarios/organization/timelines-collection.cy.spec.js
Labels: was-backported

#31120 Make tooltip consistent for each icon
  frontend/src/metabase/query_builder/components/QuestionActions.tsx
  frontend/src/metabase/query_builder/components/QuestionActions.unit.spec.tsx
  frontend/src/metabase/query_builder/components/RunButtonWithTooltip.jsx
  frontend/src/metabase/query_builder/components/view/ConvertQueryButton/ConvertQueryButton.tsx
  frontend/src/metabase/query_builder/components/view/QuestionNotebookButton.jsx
  frontend/src/metabase/query_builder/components/view/ViewHeader.jsx
  frontend/src/metabase/query_builder/components/view/ViewHeader.unit.spec.js
Labels: .Team/42 :milky_way:

#30898 Dashboard tab revision
  src/metabase/api/dashboard.clj
  src/metabase/events/revision.clj
  src/metabase/models/dashboard.clj
  src/metabase/models/dashboard_tab.clj
  src/metabase/util.cljc
  test/metabase/api/dashboard_test.clj
  test/metabase/api/revision_test.clj
  test/metabase/events/revision_test.clj
  test/metabase/models/dashboard_test.clj
  test/metabase/util_test.cljc
Labels: .Team/42 :milky_way:

#30558 Make "Save" Modal Context Aware
  e2e/test/scenarios/models/create.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
  e2e/test/scenarios/question/new.cy.spec.js
  frontend/src/metabase/components/NewItemMenu/NewItemMenu.tsx
  frontend/src/metabase/lib/card.js
  frontend/src/metabase/models/containers/NewModelOptions/NewModelOptions.jsx
  frontend/src/metabase/models/containers/NewModelOptions/NewModelOptions.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx
  frontend/src/metabase/query_builder/components/notebook/steps/DataStep.tsx
Labels: .Team/42 :milky_way:

#31247 🍒 Fixup Chromatic storybook build timeout (#30798)
  .github/workflows/frontend.yml
Labels: was-backported

#31165 [MLv2] Keep order-by in sync when replacing breakouts
  src/metabase/lib/remove_replace.cljc
  test/metabase/lib/remove_replace_test.cljc
Labels: Type:Bug, .Backend, .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#31164 fixed typo in CustomHomePageModal
  frontend/src/metabase/home/components/Modals/CustomHomePageModal/CustomHomePageModal.tsx
Labels: .Team/PixelPolice :police_officer:

#31213 Migrate home to redux toolkit and unify jest tests
  frontend/src/metabase-types/api/user.ts
  frontend/src/metabase/common/hooks/use-entity-list-query/use-entity-list-query.ts
  frontend/src/metabase/home/components/CustomHomePageModal/CustomHomePageModal.tsx
  frontend/src/metabase/home/components/CustomHomePageModal/index.ts
  frontend/src/metabase/home/components/HomeCaption/HomeCaption.tsx
  frontend/src/metabase/home/components/HomeCaption/HomeCaption.unit.spec.tsx
  frontend/src/metabase/home/components/HomeCaption/index.ts
  frontend/src/metabase/home/components/HomeCard/HomeCard.tsx
  frontend/src/metabase/home/components/HomeCard/HomeCard.unit.spec.tsx
  frontend/src/metabase/home/components/HomeCard/index.ts
  frontend/src/metabase/home/components/HomeContent/HomeContent.tsx
  frontend/src/metabase/home/components/HomeContent/HomeContent.unit.spec.tsx
  frontend/src/metabase/home/components/HomeContent/index.ts
  frontend/src/metabase/home/components/HomeGreeting/HomeGreeting.tsx
  frontend/src/metabase/home/components/HomeGreeting/HomeGreeting.unit.spec.tsx
  frontend/src/metabase/home/components/HomeGreeting/index.ts
  frontend/src/metabase/home/components/HomeHelpCard/HomeHelpCard.tsx
  frontend/src/metabase/home/components/HomeHelpCard/HomeHelpCard.unit.spec.tsx
  frontend/src/metabase/home/components/HomeHelpCard/index.ts
  frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
  frontend/src/metabase/home/components/HomeLayout/HomeLayout.unit.spec.tsx
  frontend/src/metabase/home/components/HomeLayout/index.ts
  frontend/src/metabase/home/components/HomeModelCard/HomeModelCard.tsx
  frontend/src/metabase/home/components/HomeModelCard/HomeModelCard.unit.spec.tsx
  frontend/src/metabase/home/components/HomeModelCard/index.ts
  frontend/src/metabase/home/components/HomePage/HomePage.tsx
  frontend/src/metabase/home/components/HomePage/HomePage.unit.spec.tsx
  frontend/src/metabase/home/components/HomePage/index.ts
  frontend/src/metabase/home/components/HomePopularSection/HomePopularSection.tsx
  frontend/src/metabase/home/components/HomePopularSection/HomePopularSection.unit.spec.tsx
  frontend/src/metabase/home/components/HomePopularSection/index.ts
  frontend/src/metabase/home/components/HomeRecentSection/HomeRecentSection.tsx
  frontend/src/metabase/home/components/HomeRecentSection/HomeRecentSection.unit.spec.tsx
  frontend/src/metabase/home/components/HomeRecentSection/index.ts
  frontend/src/metabase/home/components/HomeXrayCard/HomeXrayCard.tsx
  frontend/src/metabase/home/components/HomeXrayCard/HomeXrayCard.unit.spec.tsx
  frontend/src/metabase/home/components/HomeXrayCard/index.ts
  frontend/src/metabase/home/components/HomeXraySection/HomeXraySection.tsx
  frontend/src/metabase/home/components/HomeXraySection/HomeXraySection.unit.spec.tsx
  frontend/src/metabase/home/components/HomeXraySection/index.ts
  frontend/src/metabase/home/containers/HomeContent/HomeContent.tsx
  frontend/src/metabase/home/containers/HomeContent/index.ts
  frontend/src/metabase/home/containers/HomePageApp/HomePageApp.tsx
  frontend/src/metabase/home/containers/HomePageApp/HomePageApp.unit.spec.tsx
  frontend/src/metabase/home/containers/HomePageApp/index.ts
  frontend/src/metabase/home/containers/HomeXraySection/HomeXraySection.tsx
  frontend/src/metabase/home/containers/HomeXraySection/index.ts
  frontend/src/metabase/home/selectors.ts
  frontend/src/metabase/routes.jsx
  frontend/src/metabase/selectors/user.ts
Labels: .Team/42 :milky_way:

#31237 Implement `fieldable-columns`; fix visible columns for joins with `:fields`
  frontend/src/metabase-lib/fields.ts
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/card.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/equality.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/metadata.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/stage.cljc
  src/metabase/lib/table.cljc
  src/metabase/lib/util.cljc
  test/metabase/lib/breakout_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/metadata/calculation_test.cljc
  test/metabase/lib/order_by_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30833 allow reordering dashboard tabs
  frontend/src/metabase/core/components/Sortable/Sortable.styled.tsx
  frontend/src/metabase/core/components/Sortable/Sortable.tsx
  frontend/src/metabase/core/components/Sortable/index.ts
  frontend/src/metabase/core/components/TabRow/TabRow.stories.tsx
  frontend/src/metabase/core/components/TabRow/TabRow.styled.tsx
  frontend/src/metabase/core/components/TabRow/TabRow.tsx
  frontend/src/metabase/dashboard/actions/tabs.ts
  frontend/src/metabase/dashboard/actions/tabs.unit.spec.ts
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/test-utils.ts
  frontend/src/metabase/dashboard/components/DashboardTabs/useDashboardTabs.ts
  package.json
  yarn.lock
Labels: .Team/PixelPolice :police_officer:

#31226 Functions for gettings columns & operators for join conditions
  frontend/src/metabase-lib/join.ts
  frontend/src/metabase-lib/types.ts
  src/metabase/lib/core.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/metadata.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/stage.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/metadata_test.cljc
  test/metabase/lib/test_metadata.cljc
  test/metabase/lib/test_util.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31231 MLv2: fix cached metadata provider accidentally returning tombstone `::nil` for objects that don't exist
  src/metabase/lib/metadata/cached_provider.cljc
  test/metabase/lib/metadata/jvm_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31094 [Model Indexes] Fix cache invalidation issue
  e2e/test/scenarios/models/model-indexes.cy.spec.js
  frontend/src/metabase/entities/model-indexes/actions.ts
  frontend/src/metabase/entities/model-indexes/actions.unit.spec.ts
  frontend/src/metabase/entities/model-indexes/model-indexes.ts
Labels: .Team/PixelPolice :police_officer:

#31220 Auditv2 - Frontend for instance analytics questions + models
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase/collections/utils.ts
  frontend/src/metabase/entities/collections/utils.ts
  frontend/src/metabase/entities/collections/utils.unit.spec.ts
  frontend/src/metabase/entities/questions.js
  frontend/src/metabase/query_builder/components/SavedQuestionHeaderButton/CollectionIcon.tsx
  frontend/src/metabase/query_builder/components/SavedQuestionHeaderButton/SavedQuestionHeaderButton.jsx
  frontend/src/metabase/query_builder/components/SavedQuestionHeaderButton/SavedQuestionHeaderButton.unit.spec.js
Labels: .Team/PixelPolice :police_officer:

#31271 Fix display name for cumulative count without column
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/core.cljc
  test/metabase/lib/aggregation_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31272 [MLv2] Change expressions map into a vector of expressions
  src/metabase/lib/convert.cljc
  src/metabase/lib/dev.cljc
  src/metabase/lib/expression.cljc
  src/metabase/lib/remove_replace.cljc
  src/metabase/lib/schema.cljc
  src/metabase/lib/schema/expression.cljc
  src/metabase/lib/util.cljc
  test/metabase/lib/aggregation_test.cljc
  test/metabase/lib/convert_test.cljc
  test/metabase/lib/expression_test.cljc
  test/metabase/lib/remove_replace_test.cljc
  test/metabase/lib/schema/expression/conditional_test.cljc
  test/metabase/lib/schema_test.cljc
  test/metabase/lib/stage_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#31181 Implement functions for manipulating join strategies
  frontend/src/metabase-lib/join.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase-lib/v2.ts
  src/metabase/lib/core.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/metadata.cljc
  src/metabase/lib/schema/join.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/metadata_test.cljc
  test/metabase/lib/test_metadata.cljc
  test/metabase/lib/test_util.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31244 Fix MLv1-MLv2 validation for aggregations and expressions
  frontend/src/metabase-lib/Dimension.ts
  frontend/src/metabase-lib/queries/structured/Aggregation.ts
  frontend/test/metabase-lib/lib/Dimension.unit.spec.js
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30942 Replaces MultipleValues/CommaSeparatedNumbers with vectors
  modules/drivers/mongo/src/metabase/driver/mongo/parameters.clj
  modules/drivers/mongo/test/metabase/driver/mongo/parameters_test.clj
  src/metabase/driver/common/parameters.clj
  src/metabase/driver/common/parameters/values.clj
  src/metabase/driver/sql/parameters/substitution.clj
  src/metabase/util.cljc
  test/metabase/driver/common/parameters/values_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31048 [Model Indexes] Use model metadata to determine indexability
  e2e/test/scenarios/models/model-indexes.cy.spec.js
  frontend/src/metabase/entities/model-indexes/actions.ts
  frontend/src/metabase/entities/model-indexes/actions.unit.spec.ts
  frontend/src/metabase/entities/model-indexes/model-indexes.ts
  frontend/src/metabase/entities/model-indexes/utils.ts
  frontend/src/metabase/entities/model-indexes/utils.unit.spec.ts
  frontend/src/metabase/query_builder/actions/core/core.js
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetFieldMetadataSidebar/DatasetFieldMetadataSidebar.jsx
Labels: .Team/PixelPolice :police_officer:

#31298 Fix Expression Dimension Test
  frontend/test/metabase-lib/lib/Dimension.unit.spec.js
Labels: .Team/42 :milky_way:

#31296 Pre-build the specific version and edition of MB
  .github/workflows/pre-release.yml
Labels: .Building & Releasing, .CI & Tests

#31270 docs - feedback
  docs/dashboards/images/select-dashboard-subscription.png
  docs/dashboards/subscriptions.md
  docs/exploration-and-organization/collections.md
  docs/exploration-and-organization/data-model-reference.md
  docs/questions/native-editor/sql-parameters.md
  docs/questions/query-builder/expressions/regexextract.md
Labels: Type:Documentation, backport

#29583 Use MLv2 for metadata calculation in QP (part 1); make column name calculation consistent with QP
  enterprise/backend/test/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions_test.clj
  modules/drivers/druid/src/metabase/driver/druid/query_processor.clj
  modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj
  modules/drivers/mongo/test/metabase/test/data/mongo.clj
  shared/src/metabase/mbql/normalize.cljc
  shared/test/metabase/mbql/normalize_test.cljc
  src/metabase/driver/sql/query_processor.clj
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/equality.cljc
  src/metabase/lib/expression.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/metadata/cached_provider.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/metadata/composed_provider.cljc
  src/metabase/lib/metadata/protocols.cljc
  src/metabase/query_processor/middleware/annotate.clj
  src/metabase/query_processor/middleware/pre_alias_aggregations.clj
  src/metabase/query_processor/middleware/resolve_joins.clj
  src/metabase/query_processor/store.clj
  src/metabase/query_processor/store/metadata_provider.clj
  src/metabase/query_processor/util/nest_query.clj
  test/metabase/api/card_test.clj
  test/metabase/api/embed_test.clj
  test/metabase/driver/sql/query_processor_test.clj
  test/metabase/lib/aggregation_test.cljc
  test/metabase/lib/expression_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/metadata/composed_provider_test.cljc
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/remove_replace_test.cljc
  test/metabase/lib/stage_test.cljc
  test/metabase/lib/test_util.cljc
  test/metabase/query_processor/middleware/add_source_metadata_test.clj
  test/metabase/query_processor/middleware/annotate_test.clj
  test/metabase/query_processor/middleware/pre_alias_aggregations_test.clj
  test/metabase/query_processor/pivot_test.clj
  test/metabase/query_processor/util/add_alias_info_test.clj
  test/metabase/query_processor/util/nest_query_test.clj
  test/metabase/query_processor_test/aggregation_test.clj
  test/metabase/query_processor_test/filter_test.clj
  test/metabase/query_processor_test/nested_queries_test.clj
  test/metabase/server/middleware/session_test.clj
  test/metabase/test/data.clj
  test/metabase/test/data/h2.clj
  test/metabase/test/data/interface.clj
  test/metabase/test/data/sql.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31305 Backport pre release improvements 2nd part
  .github/workflows/pre-release.yml
Labels: was-backported

#31304 [MLv2] Add expressionable-columns
  src/metabase/lib/core.cljc
  src/metabase/lib/expression.cljc
  src/metabase/lib/js.cljs
  test/metabase/lib/expression_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#31162 Keep the metadata from the tables list for questions
  src/metabase/lib/join.cljc
  src/metabase/lib/js/metadata.cljs
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31312 Fix long display name source question breakout
  src/metabase/automagic_dashboards/core.clj
  src/metabase/lib/core.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/util.cljc
  test/metabase/lib/breakout_test.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/metadata/jvm_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31307 use d3-selection api for adding timeline events icons
  frontend/src/metabase/visualizations/lib/timelines.js
Labels: visual, .Team/PixelPolice :police_officer:

#31315 CI: Run clj-kondo from its prebuilt binary
  .github/workflows/backend.yml
Labels: .CI & Tests

#31311 Update fallback for `interactive?` check
  bin/build/src/metabuild_common/input.clj
Labels: .CI & Tests

#31142 Fix - Native editor buttons are incorrectly rendering on top of model metadata screen
  e2e/test/scenarios/native/reproductions/30680-native-editor-buttons.cy.spec.js
  frontend/src/metabase/models/containers/NewModelOptions/NewModelOptions.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetQueryEditor.jsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetQueryEditor.unit.spec.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditorSidebar/NativeQueryEditorSidebar.jsx
  frontend/test/__support__/server-mocks/index.ts
  frontend/test/__support__/server-mocks/native-query-snippet.ts
Labels: backport, .Team/42 :milky_way:

#31211 [CSV] Parse negative numbers surrounded by parens
  src/metabase/upload.clj
  test/metabase/upload_test.clj
Labels: .Team/42 :milky_way:

#31292 Set primary key of implicit_action table to action_id
  resources/migrations/000_migrations.yaml
Labels: .Team/42 :milky_way:

#31316 Undo renaming `AddJoinAliasToVisualizationSettingsFieldRefs` migration
  resources/migrations/000_migrations.yaml
  src/metabase/db/custom_migrations.clj
  test/metabase/db/custom_migrations_test.clj
Labels: .Team/42 :milky_way:

#31323 Add tests for `SummarizeSidebar`, minor a11y fixes
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/AddAggregationButton/AddAggregationButton.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/AggregationItem/AggregationItem.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/AggregationItem/AggregationItem.styled.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/DimensionList/DimensionListItem/DimensionListItem.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeSidebar.unit.spec.tsx
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31317 Fix flaky test `revert-dashboard-with-tabs-basic-test` on mysql and mariadb
  test/metabase/models/dashboard_test.clj
Labels: .Team/42 :milky_way:

#31306 Remove styled-system
  docs/developers-guide/frontend.md
  enterprise/frontend/src/metabase-enterprise/caching/components/CacheSection/CacheSection.tsx
  frontend/src/metabase/account/login-history/components/LoginHistory/LoginHistory.jsx
  frontend/src/metabase/admin/people/components/PeopleList.jsx
  frontend/src/metabase/admin/people/containers/UserActivationModal.jsx
  frontend/src/metabase/admin/people/containers/UserPasswordResetModal.jsx
  frontend/src/metabase/admin/settings/components/SettingsBatchForm.jsx
  frontend/src/metabase/admin/settings/components/SettingsEmailForm.jsx
  frontend/src/metabase/admin/settings/components/SettingsSlackForm.jsx
  frontend/src/metabase/admin/tasks/containers/TasksApp.jsx
  frontend/src/metabase/archive/containers/ArchiveApp.jsx
  frontend/src/metabase/browse/containers/DatabaseBrowser.jsx
  frontend/src/metabase/browse/containers/SchemaBrowser.jsx
  frontend/src/metabase/components/BrowserCrumbs/BrowserCrumbs.jsx
  frontend/src/metabase/components/Card/Card.tsx
  frontend/src/metabase/components/ConfirmContent/ConfirmContent.tsx
  frontend/src/metabase/components/IconWrapper/IconWrapper.jsx
  frontend/src/metabase/components/type/Label.jsx
  frontend/src/metabase/components/type/Text.jsx
  frontend/src/metabase/containers/UserCollectionList.jsx
  frontend/src/metabase/core/components/Button/Button.tsx
  frontend/src/metabase/core/components/Link/Link.styled.tsx
  frontend/src/metabase/css/core/colors.css
  frontend/src/metabase/dashboard/components/DashboardMoveModal.jsx
  frontend/src/metabase/dashboard/containers/AutomaticDashboardApp.jsx
  frontend/src/metabase/nav/components/CollectionBreadcrumbs/CollectionBreadcrumbs.styled.tsx
  frontend/src/metabase/pulse/components/PulseEdit.jsx
  frontend/src/metabase/query_builder/components/DataSelector/data-search/SearchResults.jsx
  frontend/src/metabase/query_builder/components/QueryVisualization.jsx
  frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.tsx
  frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverFooter.tsx
  frontend/src/metabase/query_builder/components/notebook/NotebookStep/ActionButton.tsx
  frontend/src/metabase/query_builder/components/notebook/NotebookStep/NotebookStep.tsx
  frontend/src/metabase/query_builder/components/view/QuestionLastUpdated.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/AddAggregationButton/AddAggregationButton.jsx
  frontend/src/metabase/search/containers/SearchApp.jsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar.jsx
  frontend/src/types/styled-system.d.ts
  package.json
  yarn.lock
Labels: visual

#31334 Use ex-data instead of .getData to avoid reflection warnings
  test/metabase/api/card_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31293 [MLv2] Include `selected: true` with available binning/bucketing
  src/metabase/lib/binning.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/stage.cljc
  src/metabase/lib/temporal_bucket.cljc
  test/metabase/lib/field_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#31275 API that allows admins remove the suggested list of users from subscriptions and alerts
  frontend/src/metabase/services.js
  src/metabase/api/user.clj
  test/metabase/api/user_test.clj
Labels: .Team/PixelPolice :police_officer:

#30690 Activity, LoginHistory, ViewLog, TaskHistory, PersistedInfo to toucan2
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  src/metabase/api/task.clj
  src/metabase/models/activity.clj
  src/metabase/models/login_history.clj
  src/metabase/models/persisted_info.clj
  src/metabase/models/task_history.clj
  src/metabase/models/view_log.clj
  test/metabase/api/login_history_test.clj
Labels: .Team/42 :milky_way:

#31118 Fix missing revisions for dashboard
  src/metabase/api/dashboard.clj
  src/metabase/models/card.clj
  src/metabase/models/dashboard.clj
  src/metabase/models/dashboard_card.clj
  src/metabase/models/revision/diff.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/revision_test.clj
  test/metabase/events/revision_test.clj
  test/metabase/models/card_test.clj
  test/metabase/models/dashboard_card_test.clj
  test/metabase/models/dashboard_test.clj
Labels: .Team/42 :milky_way:

#31332 Fix error loading dashboards when app db has encrypted settings
  src/metabase/models/action.clj
  test/metabase/api/dashboard_test.clj
Labels: .Team/42 :milky_way:

#31351 Skip failing Cypress test while it's investigated
  e2e/test/scenarios/dashboard/x-rays.cy.spec.js
Labels: .Team/42 :milky_way:

#30813 Dashboard tabs on public/embedding
  e2e/support/helpers/e2e-dashboard-helpers.js
  e2e/test/scenarios/admin/settings/public-sharing.cy.spec.js
  e2e/test/scenarios/dashboard/tabs.cy.spec.js
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx
  frontend/src/metabase/dashboard/components/DashboardGrid.jsx
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.tsx
  frontend/src/metabase/public/containers/PublicDashboard.jsx
  frontend/src/metabase/public/containers/PublicDashboard.styled.tsx
  src/metabase/api/public.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/embed_test.clj
  test/metabase/api/public_test.clj
Labels: .Team/PixelPolice :police_officer:, .Team/42 :milky_way:

#31370 Backport Fix mongo nested queries handling (#30877)
  modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj
  modules/drivers/mongo/test/metabase/driver/mongo_test.clj
  src/metabase/query_processor/middleware/fetch_source_query.clj
  test/metabase/query_processor/middleware/fetch_source_query_test.clj
  test/metabase/query_processor_test/nested_queries_test.clj
Labels: was-backported

#31359 fix visual issues on dashboard tabs
  frontend/src/metabase/core/components/TabButton/TabButton.styled.tsx
  frontend/src/metabase/core/components/TabButton/TabButton.tsx
  frontend/src/metabase/core/components/TabRow/TabRow.styled.tsx
  frontend/src/metabase/dashboard/actions/tabs.ts
  frontend/src/metabase/dashboard/components/DashboardHeaderView.styled.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.styled.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.tsx
Labels: .Team/PixelPolice :police_officer:

#31376 add empty state for dashboard tabs
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx
  frontend/src/metabase/dashboard/components/Dashboard/DashboardEmptyState/DashboardEmptyState.jsx
  frontend/src/metabase/dashboard/components/Dashboard/DashboardEmptyState/DashboardEmptyState.styled.tsx
  frontend/src/metabase/dashboard/components/Dashboard/DashboardEmptyState/DashboardEmptyState.tsx
  frontend/src/metabase/dashboard/components/Dashboard/DashboardEmptyState/DashboardEmptyState.unit.spec.tsx
Labels: .Team/PixelPolice :police_officer:

#31379 Fix `validate-github-release` step
  bin/build/src/release/common/github.clj
Labels: backport

#31372 Move expression editor suggest logic to metabase-lib
  frontend/src/metabase-lib/expressions/__support__/expressions.js
  frontend/src/metabase-lib/expressions/__support__/shared.js
  frontend/src/metabase-lib/expressions/helper-text-strings.ts
  frontend/src/metabase-lib/expressions/helper-text-strings.unit.spec.ts
  frontend/src/metabase-lib/expressions/suggest.ts
  frontend/src/metabase-lib/expressions/suggest.unit.spec.ts
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorHelpText.stories.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorHelpText.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorHelpText.unit.spec.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx
  frontend/test/metabase/lib/expressions/formatter.unit.spec.js
Labels: .Team/42 :milky_way:

#31225 FE: Show a checkbox near parameters in Action Editor Form
  frontend/src/metabase/actions/components/ActionFormFieldWidget/ActionFormFieldWidget.tsx
  frontend/src/metabase/actions/containers/ActionCreator/ActionContext/ImplicitActionContextProvider/ImplicitActionContextProvider.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FormFieldEditor/FormFieldEditor.tsx
  frontend/src/metabase/actions/containers/ActionCreator/tests/ActionCreator-Common.unit.spec.tsx
  frontend/src/metabase/actions/hooks/use-action-form/use-action-form.ts
  frontend/src/metabase/actions/hooks/use-action-form/utils.ts
  frontend/src/metabase/actions/hooks/use-action-form/utils.unit.spec.ts
  frontend/src/metabase/actions/utils.ts
  frontend/src/metabase/core/components/Input/Input.styled.tsx
Labels: .Team/42 :milky_way:

#31352 Fix revision failed to fetch and returns null pointer
  src/metabase/models/revision.clj
  test/metabase/api/revision_test.clj
  test/metabase/models/card_test.clj
  test/metabase/models/revision_test.clj
Labels: .Team/42 :milky_way:

#31389 Remove Currents.dev project ID
  e2e/support/config.js
Labels: .CI & Tests

#30892 Change email notification url to allow for non-Metabase users to unsubscribe from alerts
  enterprise/backend/test/metabase_enterprise/sandbox/pulse_test.clj
  src/metabase/api/session.clj
  src/metabase/email/messages.clj
  src/metabase/email/pulse.mustache
  src/metabase/pulse.clj
  src/metabase/util/urls.clj
  test/metabase/api/session_test.clj
  test/metabase/email/messages_test.clj
  test/metabase/pulse_test.clj
Labels: .Team/PixelPolice :police_officer:

#31320 FE: pass nothing instead of null during action execution at Dashboard
  e2e/test/scenarios/dashboard/actions-on-dashboards.cy.spec.js
  frontend/src/metabase/actions/hooks/use-action-form/use-action-form.unit.spec.ts
  frontend/src/metabase/actions/hooks/use-action-form/utils.ts
  frontend/src/metabase/actions/hooks/use-action-form/utils.unit.spec.ts
Labels: .Team/42 :milky_way:

#31354 FE: show a banner for public action with hidden required field
  frontend/src/metabase-types/api/mocks/actions.ts
  frontend/src/metabase/actions/containers/ActionCreator/ActionCreatorView.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FormCreator.styled.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FormCreator.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FormCreator.unit.spec.tsx
  frontend/src/metabase/actions/containers/ActionCreator/InlineActionSettings.tsx
  frontend/src/metabase/actions/utils.ts
Labels: .Team/42 :milky_way:

#31357 Updates Snowflake driver to decode uploaded private key file
  modules/drivers/snowflake/resources/metabase-plugin.yaml
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  src/metabase/driver/util.clj
  test/metabase/driver/util_test.clj
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#31343 Add test for #31256
  test/metabase/lib/breakout_test.cljc
  test/metabase/lib/join_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31106 Question URL methods to functions
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase-lib/queries/drills/automatic-insights-drill.ts
  frontend/src/metabase-lib/queries/drills/dashboard-click-drill.js
  frontend/src/metabase-lib/urls.ts
  frontend/src/metabase/browse/containers/TableBrowser/TableBrowser.jsx
  frontend/src/metabase/components/MetadataInfo/TableInfo/ConnectedTables.tsx
  frontend/src/metabase/containers/AdHocQuestionLoader.unit.spec.js
  frontend/src/metabase/dashboard/actions/navigation.js
  frontend/src/metabase/lib/urls/questions.ts
  frontend/src/metabase/models/components/ModelDetailPage/ModelInfoSidePanel/ModelInfoSidePanel.tsx
  frontend/src/metabase/models/components/ModelDetailPage/ModelInfoSidePanel/ModelRelationships.tsx
  frontend/src/metabase/models/components/ModelDetailPage/ModelUsageDetails/ModelUsageDetails.tsx
  frontend/src/metabase/models/containers/ModelDetailPage/ModelDetailPage.unit.spec.tsx
  frontend/src/metabase/modes/components/drill/AutomaticInsightsDrill.tsx
  frontend/src/metabase/modes/components/drill/ObjectDetailDrill.unit.spec.ts
  frontend/src/metabase/nav/components/QuestionLineage/QuestionLineage.tsx
  frontend/src/metabase/query_builder/components/dataref/QuestionPane/QuestionPane.tsx
  frontend/src/metabase/query_builder/components/view/QuestionDataSource.jsx
  frontend/src/metabase/query_builder/components/view/QuestionDataSource.unit.spec.js
  frontend/src/metabase/query_builder/components/view/ViewHeader.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar.unit.spec.js
  frontend/test/metabase-lib/lib/Question.unit.spec.js
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#31387 [Toucan2] replace hydrate and with-temp-defaults
  .clj-kondo/config.edn
  enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj
  enterprise/backend/test/metabase_enterprise/advanced_config/models/pulse_channel_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/test_util.clj
  modules/drivers/sqlite/test/metabase/driver/sqlite_test.clj
  src/metabase/actions/execution.clj
  src/metabase/api/action.clj
  src/metabase/api/activity.clj
  src/metabase/api/alert.clj
  src/metabase/api/card.clj
  src/metabase/api/collection.clj
  src/metabase/api/dashboard.clj
  src/metabase/api/database.clj
  src/metabase/api/field.clj
  src/metabase/api/metric.clj
  src/metabase/api/native_query_snippet.clj
  src/metabase/api/permissions.clj
  src/metabase/api/persist.clj
  src/metabase/api/public.clj
  src/metabase/api/pulse.clj
  src/metabase/api/segment.clj
  src/metabase/api/table.clj
  src/metabase/api/timeline.clj
  src/metabase/api/user.clj
  src/metabase/models/collection.clj
  src/metabase/models/dashboard.clj
  src/metabase/models/dashboard_card.clj
  src/metabase/models/field.clj
  src/metabase/models/params.clj
  src/metabase/models/pulse.clj
  src/metabase/models/revision.clj
  src/metabase/models/serialization.clj
  src/metabase/models/timeline.clj
  src/metabase/models/timeline_event.clj
  src/metabase/moderation.clj
  src/metabase/query_processor/middleware/add_dimension_projections.clj
  src/metabase/task/persist_refresh.clj
  test/metabase/api/card_test.clj
  test/metabase/api/database_test.clj
  test/metabase/api/field_test.clj
  test/metabase/api/user_test.clj
  test/metabase/domain_entities/core_test.clj
  test/metabase/driver/mysql_test.clj
  test/metabase/models/action_test.clj
  test/metabase/models/card_test.clj
  test/metabase/models/collection/graph_test.clj
  test/metabase/models/collection_test.clj
  test/metabase/models/dashboard_test.clj
  test/metabase/models/params_test.clj
  test/metabase/models/pulse_channel_test.clj
  test/metabase/models/pulse_test.clj
  test/metabase/models/user_test.clj
  test/metabase/sample_data_test.clj
  test/metabase/sync/sync_dynamic_test.clj
  test/metabase/sync/sync_metadata/fields_test.clj
  test/metabase/sync/sync_metadata/metabase_metadata_test.clj
  test/metabase/test.clj
Labels: .Team/42 :milky_way:

#31281 🍒 Manual Backport #30558
  e2e/test/scenarios/models/create.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
  e2e/test/scenarios/question/new.cy.spec.js
  frontend/src/metabase/components/NewItemMenu/NewItemMenu.tsx
  frontend/src/metabase/lib/card.js
  frontend/src/metabase/models/containers/NewModelOptions/NewModelOptions.jsx
  frontend/src/metabase/models/containers/NewModelOptions/NewModelOptions.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx
  frontend/src/metabase/query_builder/components/notebook/steps/DataStep.jsx
Labels: was-backported, .Team/42 :milky_way:

#31322 Change `Export as PDF` button name for dashboards with multiple tabs
  e2e/test/scenarios/admin/settings/public-sharing.cy.spec.js
  e2e/test/scenarios/dashboard/tabs.cy.spec.js
  frontend/src/metabase/dashboard/actions/tabs.ts
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/test-utils.ts
  frontend/src/metabase/dashboard/containers/DashboardHeader.jsx
  frontend/src/metabase/dashboard/containers/DashboardHeader.unit.spec.jsx
Labels: .Team/42 :milky_way:

#31420 Adds audit v2 view migrations to liquibase
  resources/migrations/000_migrations.yaml
Labels: .Team/PixelPolice :police_officer:

#31414 Fix join alias display name calculation with legacy metadata
  src/metabase/lib/field.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/stage.cljc
  test/metabase/lib/breakout_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/metadata/jvm_test.clj
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/stage_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31426 Use Box to style components in the app
  .storybook/preview.tsx
  babel.config.json
  frontend/src/metabase/auth/components/Login/Login.styled.tsx
  frontend/src/metabase/auth/components/Login/Login.tsx
  frontend/src/metabase/ui/components/index.ts
  frontend/src/metabase/ui/components/inputs/Radio/index.ts
  frontend/src/metabase/ui/components/inputs/index.ts
  frontend/src/metabase/ui/components/layout/Box/index.ts
  frontend/src/metabase/ui/components/layout/Center/index.ts
  frontend/src/metabase/ui/components/layout/Flex/index.ts
  frontend/src/metabase/ui/components/layout/Grid/index.ts
  frontend/src/metabase/ui/components/layout/Group/index.ts
  frontend/src/metabase/ui/components/layout/Stack/index.ts
  frontend/src/metabase/ui/components/layout/index.ts
  frontend/src/metabase/ui/components/theme/ThemeProvider/ThemeProvider.tsx
  frontend/src/metabase/ui/components/theme/ThemeProvider/index.ts
  frontend/src/metabase/ui/components/theme/index.ts
  frontend/src/metabase/ui/components/typography/Text/index.ts
  frontend/src/metabase/ui/components/typography/index.ts
  frontend/src/metabase/ui/index.ts
  frontend/test/__support__/ui.tsx
Labels: .Team/42 :milky_way:

#31431 Upgrade Deploysentinel to `0.8.1`
  package.json
  yarn.lock
Labels: .CI & Tests

#31345 Make CSV Discovery Easier
  frontend/src/metabase/collections/components/CollectionHeader/CollectionHeader.styled.tsx
  frontend/src/metabase/collections/components/CollectionHeader/CollectionHeader.tsx
  frontend/src/metabase/collections/components/CollectionHeader/CollectionHeader.unit.spec.tsx
  frontend/src/metabase/collections/components/CollectionHeader/CollectionUpload.styled.tsx
  frontend/src/metabase/collections/components/CollectionHeader/CollectionUpload.tsx
  frontend/src/metabase/collections/components/CollectionHeader/CollectionUploadInfoModal.tsx
  frontend/src/metabase/collections/containers/CollectionContent.jsx
  frontend/src/metabase/status/components/FileUploadStatus/FileUploadStatus.unit.spec.tsx
Labels: .Team/PixelPolice :police_officer:

#31276 FE: ellipsify column title in details modal to prevent text overflow
  frontend/src/metabase/core/components/Ellipsified/Ellipsified.stories.tsx
  frontend/src/metabase/core/components/Ellipsified/Ellipsified.styled.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailsTable.tsx
Labels: visual, .Team/PixelPolice :police_officer:

#31432 [E2E] Extract `actions` E2E tests to their own group
  .github/workflows/e2e-tests.yml
  e2e/test/scenarios/actions/actions-on-dashboards.cy.spec.js
  e2e/test/scenarios/actions/model-actions.cy.spec.js
Labels: .CI & Tests

#31380 CSV upload loading messages
  frontend/src/metabase/status/components/FileUploadStatus/FileUploadStatus.unit.spec.tsx
  frontend/src/metabase/status/components/FileUploadStatusLarge/FileUploadStatusLarge.tsx
Labels: .Team/PixelPolice :police_officer:

#30804 New Dashboard Primitive - Headings
  e2e/support/helpers/e2e-dashboard-helpers.js
  e2e/test/scenarios/dashboard/text-box.cy.spec.js
  e2e/test/scenarios/dashboard/text-dashcards.cy.spec.js
  e2e/test/scenarios/dashboard/text-parameters.cy.spec.js
  e2e/test/scenarios/sharing/subscriptions.cy.spec.js
  frontend/src/metabase/components/EntityMenu/EntityMenu.jsx
  frontend/src/metabase/css/dashboard.css
  frontend/src/metabase/dashboard/actions/cards.js
  frontend/src/metabase/dashboard/components/DashCard/DashCard.styled.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionButtons/ChartSettingsButton.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionButtons/DashCardActionButtons.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.jsx
  frontend/src/metabase/dashboard/components/TextOptions/TextOptionsButton.styled.tsx
  frontend/src/metabase/dashboard/components/TextOptions/TextOptionsButton.tsx
  frontend/src/metabase/dashboard/containers/DashboardHeader.jsx
  frontend/src/metabase/sharing/components/SharingSidebar.jsx
  frontend/src/metabase/visualizations/register.js
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.styled.tsx
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.tsx
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.unit.spec.tsx
  frontend/src/metabase/visualizations/visualizations/Heading/index.ts
  frontend/src/metabase/visualizations/visualizations/Text/Text.css
  frontend/src/metabase/visualizations/visualizations/Text/Text.jsx
  frontend/src/metabase/visualizations/visualizations/Text/Text.styled.jsx
  frontend/src/metabase/visualizations/visualizations/Text/Text.unit.spec.tsx
  frontend/src/metabase/visualizations/visualizations/Text/index.ts
Labels: visual, .Team/PixelPolice :police_officer:

#31465 Add test for question title overflow
  e2e/test/scenarios/question/saved.cy.spec.js
Labels: .Team/42 :milky_way:

#31458 🍒 [E2E] Extract `actions` E2E tests to their own group (#31432)
  .github/workflows/e2e-tests.yml
  e2e/test/scenarios/actions/actions-on-dashboards.cy.spec.js
  e2e/test/scenarios/actions/model-actions.cy.spec.js
Labels: was-backported

#31453 🍒 [CI] Increase timeout in multiple workflows (#31449)
  .github/workflows/backend.yml
  .github/workflows/drivers.yml
  .github/workflows/e2e-tests.yml
Labels: was-backported

#31283 Add analytics
  e2e/test/scenarios/admin/databases/database-prompt-banner.cy.spec.js
  frontend/src/metabase/nav/analytics.ts
  frontend/src/metabase/nav/components/DatabasePromptBanner/DatabasePromptBanner.tsx
  snowplow/iglu-client-embedded/schemas/com.metabase/account/jsonschema/1-0-1
Labels: .Team/42 :milky_way:

#31438 Add instrumentation for "Turn into model" option on saved questions
  e2e/test/scenarios/question/question-management.cy.spec.js
  frontend/src/metabase/query_builder/analytics.js
  frontend/src/metabase/query_builder/components/QuestionActions.tsx
  snowplow/iglu-client-embedded/schemas/com.metabase/metabot/jsonschema/1-0-1
  snowplow/iglu-client-embedded/schemas/com.metabase/question/jsonschema/1-0-2
Labels: .Team/42 :milky_way:

#31377 Exclude SSO group mappings settings from cache
  enterprise/backend/src/metabase_enterprise/sso/integrations/sso_settings.clj
  src/metabase/integrations/ldap.clj
Labels: backport, .Team/PixelPolice :police_officer:

#31409 Allow upload table prefixes on dbs with schema
  frontend/src/metabase/admin/settings/components/UploadSettings/UploadSettings.tsx
  frontend/src/metabase/admin/settings/components/UploadSettings/UploadSettings.unit.spec.tsx
Labels: .Team/PixelPolice :police_officer:

#31443 Remove dont-bin pseudo binning strategy
  src/metabase/lib/binning.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#31441 Fix matching breakout columns with binning
  src/metabase/lib/breakout.cljc
  test/metabase/lib/breakout_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#31337 Hydrate root-collection on card and dashboard
  src/metabase/api/card.clj
  src/metabase/api/dashboard.clj
  src/metabase/api/timeline.clj
  src/metabase/models/collection.clj
  src/metabase/models/collection/root.clj
  src/metabase/models/timeline.clj
Labels: .Team/PixelPolice :police_officer:

#31454 Ensure download perms are properly enforced on dashcards
  src/metabase/api/dashboard.clj
  test/metabase/query_processor/streaming_test.clj
Labels: backport, .Team/PixelPolice :police_officer:

#31483 Make sure plurals get included properly when generating POT file
  bin/build/src/i18n/enumerate.clj
Labels: .Team/PixelPolice :police_officer:

#31487 MLv2: Fix matching of field literals to field integer IDs
  shared/src/metabase/mbql/util.cljc
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/breakout.cljc
  src/metabase/lib/equality.cljc
  src/metabase/lib/field.cljc
  test/metabase/lib/breakout_test.cljc
  test/metabase/lib/equality_test.cljc
  test/metabase/lib/field_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31019 Dashboard grid from 18 to 24
  e2e/snapshot-creators/default.cy.snap.js
  e2e/support/commands/api/composite/createNativeQuestionAndDashboard.js
  e2e/support/commands/api/composite/createQuestionAndAddToDashboard.js
  e2e/support/commands/api/composite/createQuestionAndDashboard.js
  e2e/support/helpers/e2e-dashboard-helpers.js
  e2e/support/integration/visit-dashboard.js
  e2e/test/scenarios/custom-column/reproductions/18747-cc-connected-to-dashboard-parameter.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/19744-cc-after-aggregation-limited-filters.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-auto-apply.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-explicit-join.cy.spec.js
  e2e/test/scenarios/dashboard-filters/old-parameters.cy.spec.js
  e2e/test/scenarios/dashboard-filters/parameters.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/12720-no-data-permissions-connected-filter.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/12985-dropdown-search.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/16112-nodata-should-use-dashboard-filters.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/17211-false-no-matching-filter-alert.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/17775-filter-custom-column-date.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/19494-wrong-default-value-multiple-cards-same-question.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/20656-dashboard-breaks-for-user-without-card-permissions.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/22788-flter-cc-dropped-on-second-edit.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/24235-exlude-all-date-options.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/24500-gracefully-deal-with-corrupted-filter.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/25355-multi-series-parameter-mapping.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/25374-comma-separated-values-not-passed-to-question.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/25908-contains-filter-case-sensitivity.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/29347-remapped-field-values.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/8030-reload-card-without-change.cy.spec.js
  e2e/test/scenarios/dashboard/chained-filters.cy.spec.js
  e2e/test/scenarios/dashboard/click-behavior.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard-back-navigation.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard-drill.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/dashboard/permissions.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/17160-click-behavior-multiple-options.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/20637-add-series-to-dashcard.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/26230-dashboard-sticky-filter-incorrectly-positioned.cy.spec.js
  e2e/test/scenarios/dashboard/text-parameters.cy.spec.js
  e2e/test/scenarios/dashboard/title-drill.cy.spec.js
  e2e/test/scenarios/embedding/reproductions/15860-locked-filters-same-source-table.cy.spec.js
  e2e/test/scenarios/embedding/reproductions/20438-dashboard-filter-single-value.cy.spec.js
  e2e/test/scenarios/embedding/reproductions/20845-25031-locked-numeric-param.cy.spec.js
  e2e/test/scenarios/embedding/shared/embedding-dashboard.js
  e2e/test/scenarios/embedding/shared/embedding-linked-filters.js
  e2e/test/scenarios/models/models-metadata.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/15163.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/24966-saved-native-q-field-values.cy.spec.js
  e2e/test/scenarios/question/nulls.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/25473-dashboard-text-filter-asking-for-number.cy.spec.js
  e2e/test/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  e2e/test/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
  e2e/test/scenarios/visualizations/gauge.cy.spec.js
  e2e/test/scenarios/visualizations/line-bar-tooltips.cy.spec.js
  e2e/test/scenarios/visualizations/line_chart.cy.spec.js
  e2e/test/scenarios/visualizations/pivot_tables.cy.spec.js
  e2e/test/scenarios/visualizations/scalar.cy.spec.js
  frontend/src/metabase/lib/dashboard_grid.js
  resources/migrations/000_migrations.yaml
  src/metabase/db/custom_migrations.clj
  test/metabase/db/custom_migrations_test.clj
  test/metabase/db/schema_migrations_test.clj
Labels: .Team/42 :milky_way:

#31491 Document how to improve code reviews
  docs/developers-guide/code-reviews.md
Labels: Type:Documentation

#31485 Remove infinite recursion when resolving fields by name
  src/metabase/lib/field.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/stage.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31486 [E2E] Fix joins flakes
  e2e/support/helpers/e2e-notebook-helpers.js
  e2e/test/scenarios/joins/joins.cy.spec.js
  e2e/test/scenarios/joins/reproductions/17767-cannot-join-on-aggregation-with-implicit-joins.cy.spec.js
  e2e/test/scenarios/joins/reproductions/18502-cannot-join-two-saved-questions-same-table.cy.spec.js
  e2e/test/scenarios/joins/reproductions/18512-cannot-join-two-saved-questions-with-same-implicit-explicit-grouped-field.cy.spec.js
Labels: flaky-test-fix

#31506 Remove dead link in docs
  docs/configuring-metabase/fonts.md
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31489 [CI] Bump timeout in stress-test workflow
  .github/workflows/e2e-stress-test-flake-fix.yml
Labels: .CI & Tests

#31467 Add snowplow tracking for search queries
  snowplow/iglu-client-embedded/schemas/com.metabase/search/jsonschema/1-0-0
  src/metabase/analytics/snowplow.clj
  src/metabase/api/search.clj
  test/metabase/api/search_test.clj
Labels: .Team/42 :milky_way:

#31504 Fix notification issue with quotes in the title
  .github/workflows/escalation-slack-notification.yml
Labels: .CI & Tests

#31329 FE: Mark Fields as hidden in parameter mapping
  frontend/src/metabase/actions/components/ActionViz/ActionDashcardSettings.tsx
  frontend/src/metabase/actions/components/ActionViz/ActionDashcardSettings.unit.spec.tsx
  frontend/src/metabase/actions/components/ActionViz/ActionParameterMapper.styled.tsx
  frontend/src/metabase/actions/components/ActionViz/ActionParameterMapper.tsx
  frontend/src/metabase/actions/components/ActionViz/utils.ts
  frontend/src/metabase/actions/containers/ActionParametersInputForm/ActionParametersInputForm.tsx
Labels: .Team/42 :milky_way:

#31099 Generically typed item picker
  frontend/src/metabase/collections/containers/FormCollectionPicker/FormCollectionPicker.tsx
  frontend/src/metabase/components/DashboardSelector/DashboardSelector.tsx
  frontend/src/metabase/containers/DashboardPicker.tsx
  frontend/src/metabase/containers/ItemPicker/Item.tsx
  frontend/src/metabase/containers/ItemPicker/ItemPicker.tsx
  frontend/src/metabase/containers/ItemPicker/ItemPickerView.tsx
  frontend/src/metabase/containers/ItemPicker/types.ts
  frontend/src/metabase/home/components/CustomHomePageModal/CustomHomePageModal.tsx
  frontend/src/metabase/models/containers/FormModelPicker/FormModelPicker.tsx
Labels: .Team/PixelPolice :police_officer:

#31512 Fix warnings about passing wrong attributes to DOM node
  frontend/src/metabase/core/components/SelectButton/SelectButton.styled.tsx
Labels: .Team/42 :milky_way:

#31210 Encourage admin users to connect to a database
  e2e/test/scenarios/admin/databases/database-prompt-banner.cy.spec.js
  e2e/test/scenarios/admin/datamodel/editor.cy.spec.js
  e2e/test/scenarios/custom-column/cc-help-text.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/26230-dashboard-sticky-filter-incorrectly-positioned.cy.spec.js
  e2e/test/scenarios/embedding/embedding-full-app.cy.spec.js
  e2e/test/scenarios/visualizations/line-bar-tooltips.cy.spec.js
  frontend/src/metabase/App.tsx
  frontend/src/metabase/components/AppBanner/AppBanner.jsx
  frontend/src/metabase/components/AppBanner/AppBanner.tsx
  frontend/src/metabase/components/AppBanner/AppBanner.unit.spec.tsx
  frontend/src/metabase/components/AppBanner/index.jsx
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.styled.jsx
  frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.js
  frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.unit.spec.js
  frontend/src/metabase/nav/components/DatabasePromptBanner/DatabasePromptBanner.styled.ts
  frontend/src/metabase/nav/components/DatabasePromptBanner/DatabasePromptBanner.tsx
  frontend/src/metabase/nav/components/DatabasePromptBanner/DatabasePromptBanner.unit.spec.tsx
  frontend/src/metabase/nav/components/DatabasePromptBanner/index.ts
  frontend/src/metabase/nav/components/PaymentBanner/PaymentBanner.tsx
  frontend/src/metabase/nav/components/PaymentBanner/PaymentBanner.unit.spec.tsx
  frontend/src/metabase/selectors/selectors.unit.spec.ts
  frontend/src/metabase/selectors/settings.ts
Labels: .Team/42 :milky_way:

#31269 docs - 46.3 api update
  docs/api-documentation.md
  docs/api/activity.md
  docs/api/card.md
  docs/configuring-metabase/fonts.md
  src/metabase/api/card.clj
Labels: Type:Documentation

#31514 Fix object detail view appearing up on every arrow key
  e2e/test/scenarios/question/nulls.cy.spec.js
  e2e/test/scenarios/visualizations/reproductions/30039-object-detail-navigation.cy.spec.js
  frontend/src/metabase/App.tsx
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterFieldSearch.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader.jsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.jsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx
Labels: backport, visual, .Team/42 :milky_way:

#31522 Upgrade ReplayIO to `v1.0.1`
  package.json
  yarn.lock
Labels: .CI & Tests

#31523 yarn upgrade ace-builds
  yarn.lock
Labels: .Team/PixelPolice :police_officer:

#31364 Fix: Inconsistent icon position in pinned dashboard item loading state
  frontend/src/metabase/collections/components/PinnedQuestionCard/PinnedQuestionCard.tsx
  frontend/src/metabase/visualizations/components/skeletons/AreaSkeleton/AreaSkeleton.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/AreaSkeleton/AreaSkeleton.tsx
  frontend/src/metabase/visualizations/components/skeletons/BarSkeleton/BarSkeleton.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/BarSkeleton/BarSkeleton.tsx
  frontend/src/metabase/visualizations/components/skeletons/ChartSkeleton/ChartSkeleton.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/ChartSkeleton/ChartSkeleton.tsx
  frontend/src/metabase/visualizations/components/skeletons/ChartSkeleton/ChartSkeleton.unit.spec.tsx
  frontend/src/metabase/visualizations/components/skeletons/EmptySkeleton/EmptySkeleton.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/EmptySkeleton/EmptySkeleton.tsx
  frontend/src/metabase/visualizations/components/skeletons/EmptySkeleton/index.ts
  frontend/src/metabase/visualizations/components/skeletons/FunnelSkeleton/FunnelSkeleton.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/FunnelSkeleton/FunnelSkeleton.tsx
  frontend/src/metabase/visualizations/components/skeletons/GaugeSkeleton/GaugeSkeleton.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/GaugeSkeleton/GaugeSkeleton.tsx
  frontend/src/metabase/visualizations/components/skeletons/LineSkeleton/LineSkeleton.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/LineSkeleton/LineSkeleton.tsx
  frontend/src/metabase/visualizations/components/skeletons/MapSkeleton/MapSkeleton.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/MapSkeleton/MapSkeleton.tsx
  frontend/src/metabase/visualizations/components/skeletons/PieSkeleton/PieSkeleton.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/PieSkeleton/PieSkeleton.tsx
  frontend/src/metabase/visualizations/components/skeletons/ProgressSkeleton/ProgressSkeleton.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/ProgressSkeleton/ProgressSkeleton.tsx
  frontend/src/metabase/visualizations/components/skeletons/RowSkeleton/RowSkeleton.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/RowSkeleton/RowSkeleton.tsx
  frontend/src/metabase/visualizations/components/skeletons/ScalarSkeleton/ScalarSkeleton.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/ScalarSkeleton/ScalarSkeleton.tsx
  frontend/src/metabase/visualizations/components/skeletons/ScalarSkeleton/index.ts
  frontend/src/metabase/visualizations/components/skeletons/ScatterSkeleton/ScatterSkeleton.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/ScatterSkeleton/ScatterSkeleton.tsx
  frontend/src/metabase/visualizations/components/skeletons/Skeleton/index.ts
  frontend/src/metabase/visualizations/components/skeletons/SkeletonCaption/SkeletonCaption.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/SkeletonCaption/SkeletonCaption.tsx
  frontend/src/metabase/visualizations/components/skeletons/SmartScalarSkeleton/SmartScalarSkeleton.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/SmartScalarSkeleton/SmartScalarSkeleton.tsx
  frontend/src/metabase/visualizations/components/skeletons/SmartScalarSkeleton/index.ts
  frontend/src/metabase/visualizations/components/skeletons/TableSkeleton/TableSkeleton.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/TableSkeleton/TableSkeleton.tsx
  frontend/src/metabase/visualizations/components/skeletons/VisualizationSkeleton/VisualizationSkeleton.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/VisualizationSkeleton/VisualizationSkeleton.tsx
  frontend/src/metabase/visualizations/components/skeletons/WaterfallSkeleton/WaterfallSkeleton.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/WaterfallSkeleton/WaterfallSkeleton.tsx
Labels: visual, .Team/42 :milky_way:

#31470 Add analytics
  e2e/test/scenarios/admin/databases/database-prompt-banner.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/24235-exlude-all-date-options.cy.spec.js
  frontend/src/metabase/nav/analytics.ts
  frontend/src/metabase/nav/components/DatabasePromptBanner/DatabasePromptBanner.tsx
  snowplow/iglu-client-embedded/schemas/com.metabase/account/jsonschema/1-0-1
Labels: visual, .Team/42 :milky_way:

#31541 Fix failed to dismiss spinner when db has no tables
  src/metabase/api/database.clj
  test/metabase/api/database_test.clj
Labels: .Team/42 :milky_way:

#31471 Prevent rendering the database prompt banner when white labeling
  e2e/test/scenarios/admin/databases/database-prompt-banner.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/settings/selectors.js
  enterprise/frontend/src/metabase-enterprise/settings/selectors.ts
  enterprise/frontend/src/metabase-enterprise/settings/selectors.unit.spec.ts
  enterprise/frontend/src/metabase-enterprise/settings/types.ts
  enterprise/frontend/src/metabase-enterprise/whitelabel/index.js
  frontend/src/metabase-types/store/mocks/settings.ts
  frontend/src/metabase-types/store/mocks/state.ts
  frontend/src/metabase/nav/components/DatabasePromptBanner/DatabasePromptBanner.tsx
  frontend/src/metabase/nav/components/DatabasePromptBanner/DatabasePromptBanner.unit.spec.tsx
  frontend/src/metabase/plugins/index.ts
Labels: .Team/42 :milky_way:

#31508 Fix sandbox table migrations for invalid perms table
  resources/migrations/000_migrations.yaml
  test/metabase/db/schema_migrations_test.clj
Labels: backport, .Team/PixelPolice :police_officer:

#31548 [E2E] Fix 18630 repro flake
  e2e/test/scenarios/joins/reproductions/18630-field-literals-in-joins.cy.spec.js
Labels: backport, flaky-test-fix

#31464 Update mapping modal state after inline change of the action
  e2e/test/scenarios/dashboard/actions-on-dashboards.cy.spec.js
  frontend/src/metabase/actions/components/ActionViz/ActionDashcardSettings.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FormFieldEditor/FormFieldEditor.tsx
  frontend/src/metabase/actions/containers/ActionPicker/ActionPicker.tsx
  frontend/src/metabase/actions/containers/ActionPicker/index.ts
Labels: .Team/42 :milky_way:

#31543 Remove POST api/database/:id/sync endpoint
  src/metabase/api/database.clj
  src/metabase/events/sync_database.clj
  test/metabase/sync/analyze_test.clj
Labels: .Team/42 :milky_way:

#31552 Manual backport of #31508
  resources/migrations/000_migrations.yaml
  test/metabase/db/schema_migrations_test.clj
Labels: was-backported

#31550 [Manual backport] Fix object detail view appearing up on every arrow key
  e2e/test/scenarios/question/nulls.cy.spec.js
  e2e/test/scenarios/visualizations/reproductions/30039-object-detail-navigation.cy.spec.js
  frontend/src/metabase/App.tsx
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterFieldSearch.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader.jsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.jsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx
Labels: was-backported

#31549 Manual backport - Respect alphabetical order of collections in "Move" modal (#31355)
  frontend/src/metabase/entities/collections/collections.ts
  frontend/src/metabase/entities/snippet-collections.js
Labels: was-backported

#31160 fix the question description icon placement in the collection view (#…
  e2e/support/helpers/e2e-collection-helpers.js
  e2e/test/scenarios/collections/reproductions/23515-pinned-question-pagination.cy.spec.js
  frontend/src/metabase/collections/components/PinnedQuestionCard/PinnedQuestionCard.styled.tsx
  frontend/src/metabase/collections/components/PinnedQuestionCard/PinnedQuestionCard.tsx
  frontend/src/metabase/components/EntityItem.jsx
  frontend/src/metabase/components/EntityMenu.jsx
  frontend/src/metabase/visualizations/components/legend/LegendCaption.styled.jsx
Labels: was-backported, .Team/PixelPolice :police_officer:

#31554 🍒 [E2E] Fix 18630 repro flake (#31548)
  e2e/test/scenarios/joins/reproductions/18630-field-literals-in-joins.cy.spec.js
Labels: was-backported

#31537 Wider Uploads settings container
  frontend/src/metabase/admin/settings/components/UploadSettings/UploadSetting.styled.tsx
  frontend/src/metabase/admin/settings/components/UploadSettings/UploadSettings.tsx
Labels: .Team/PixelPolice :police_officer:

#31407 Add snowplow event tracking for csv uploads
  snowplow/iglu-client-embedded/schemas/com.metabase/csvupload/jsonschema/1-0-0
  src/metabase/analytics/snowplow.clj
  src/metabase/api/card.clj
  src/metabase/upload.clj
  test/metabase/api/card_test.clj
Labels: .Team/42 :milky_way:

#31571 Fix the migration to increase grid of cards in revision table
  src/metabase/db/custom_migrations.clj
  test/metabase/db/custom_migrations_test.clj
Labels: .Team/42 :milky_way:

#31559 Mark table sync status as complete after syncing
  src/metabase/sync.clj
  test/metabase/sync_test.clj
Labels: .Team/42 :milky_way:

#31455 Refactor E2E tests in the `sharing` folder
  .github/workflows/e2e-tests.yml
  e2e/test/scenarios/sharing/downloads/downloads.cy.spec.js
  e2e/test/scenarios/sharing/downloads/reproductions/10803-timestamp-formatting.cy.spec.js
  e2e/test/scenarios/sharing/downloads/reproductions/18219-temporal-units-not-formatted.cy.spec.js
  e2e/test/scenarios/sharing/downloads/reproductions/18382-old-syntax-missing-renamed-columns.cy.spec.js
  e2e/test/scenarios/sharing/downloads/reproductions/18440-remapped-display-value-dropped.cy.spec.js
  e2e/test/scenarios/sharing/downloads/reproductions/18573-remapped-fields-not-renamed.cy.spec.js
  e2e/test/scenarios/sharing/downloads/reproductions/18729-date-formatting-x-of-y.cy.spec.js
  e2e/test/scenarios/sharing/downloads/reproductions/19889-native-query-export-column-order.cy.spec.js
  e2e/test/scenarios/sharing/public-dashboard.cy.spec.js
  e2e/test/scenarios/sharing/public-question.cy.spec.js
  e2e/test/scenarios/sharing/public-sharing.cy.spec.js
  e2e/test/scenarios/sharing/public.cy.spec.js
Labels: .CI & Tests, backport

#31563 Auditv2 modify views: add v_audit_log + update v_content
  resources/migrations/000_migrations.yaml
Labels: .Team/PixelPolice :police_officer:

#31576 [E2E] Do not hardcode admin id
  e2e/snapshot-creators/default.cy.snap.js
Labels: .CI & Tests, backport

#31457 fix frontend dev for safari
  src/metabase/server/middleware/security.clj
Labels: .Team/PixelPolice :police_officer:

#31583 Bump Honey SQL 2 version [46]
  deps.edn
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31589 update audit log view migration
  resources/migrations/000_migrations.yaml
Labels: .Team/PixelPolice :police_officer:

#31556 [CSV] Avoid expensive call to fetch DB metadata
  src/metabase/api/card.clj
  test/metabase/api/card_test.clj
Labels: .Team/42 :milky_way:

#31476 Add join alias to dashboard card visualization_settings.column_settings field refs
  resources/migrations/000_migrations.yaml
  src/metabase/db/custom_migrations.clj
  test/metabase/db/custom_migrations_test.clj
Labels: .Team/42 :milky_way:

#31545 4/x Follow up reviews and tests
  frontend/src/metabase/components/AppBanner/AppBanner.tsx
  frontend/src/metabase/components/AppBanner/AppBanner.unit.spec.tsx
  frontend/src/metabase/nav/components/DatabasePromptBanner/DatabasePromptBanner.tsx
  frontend/src/metabase/nav/components/DatabasePromptBanner/DatabasePromptBanner.unit.spec.tsx
  frontend/src/metabase/nav/components/PaymentBanner/PaymentBanner.unit.spec.tsx
  frontend/src/metabase/nav/hooks.ts
  frontend/src/metabase/nav/hooks.unit.spec.tsx
Labels: .Team/42 :milky_way:

#31557 5/x Add embedding tests
  e2e/support/commands/database/addH2SampleDatabase.js
  e2e/test/scenarios/admin/databases/database-prompt-banner.cy.spec.js
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase-types/api/dataset.ts
  frontend/src/metabase-types/api/mocks/card.ts
  frontend/src/metabase-types/api/mocks/dataset.ts
  frontend/src/metabase-types/api/query.ts
  frontend/src/metabase/home/components/HomeHelpCard/HomeHelpCard.tsx
  frontend/src/metabase/public/containers/PublicQuestion/PublicQuestion.jsx
  frontend/src/metabase/public/containers/PublicQuestion/PublicQuestion.unit.spec.tsx
  frontend/src/metabase/public/containers/PublicQuestion/index.js
  frontend/src/metabase/routes-embed.jsx
  frontend/src/metabase/routes-public.jsx
  frontend/src/metabase/routes.jsx
  frontend/src/metabase/selectors/embed.ts
  frontend/test/__support__/server-mocks/public.ts
Labels: .Team/42 :milky_way:

#31595 Merge #3166 to master too
  src/metabase/lib/aggregation.cljc
  test/metabase/lib/aggregation_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31618 Allow generating metadata for tables with nil columns
  src/metabase/lib/table.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31593 Fix Snowflake sync with uploaded private key
  modules/drivers/snowflake/resources/metabase-plugin.yaml
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  src/metabase/driver/util.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31594 Disable slow test to prevent flakiness
  test/metabase/query_processor_test/explicit_joins_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31385 Rest of models to toucan2 🎉
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  src/metabase/db/data_migrations.clj
  src/metabase/lib/metadata/jvm.clj
  src/metabase/models/interface.clj
  src/metabase/models/metric.clj
  src/metabase/models/metric_important_field.clj
  src/metabase/models/native_query_snippet.clj
  src/metabase/models/parameter_card.clj
  src/metabase/models/pulse.clj
  src/metabase/models/pulse_card.clj
  src/metabase/models/pulse_channel.clj
  src/metabase/models/pulse_channel_recipient.clj
  src/metabase/models/query.clj
  src/metabase/models/query_cache.clj
  src/metabase/models/query_execution.clj
  src/metabase/models/segment.clj
  src/metabase/models/user.clj
  test/metabase/models/revision_test.clj
  test/metabase/models/user_test.clj
  test/metabase/test/util.clj
Labels: .Team/42 :milky_way:

#31598 Do not record public info in revisions
  src/metabase/models/card.clj
  src/metabase/models/dashboard.clj
  test/metabase/events/revision_test.clj
  test/metabase/models/dashboard_test.clj
Labels: .Team/42 :milky_way:

#31398 custom homepage modal
  e2e/support/cypress_sample_instance_data.json
  e2e/test/scenarios/onboarding/home/homepage.cy.spec.js
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase-types/store/auth.ts
  frontend/src/metabase-types/store/index.ts
  frontend/src/metabase-types/store/mocks/auth.ts
  frontend/src/metabase-types/store/mocks/index.ts
  frontend/src/metabase-types/store/mocks/settings.ts
  frontend/src/metabase-types/store/mocks/state.ts
  frontend/src/metabase-types/store/settings.ts
  frontend/src/metabase-types/store/state.ts
  frontend/src/metabase/admin/settings/containers/SettingsEditorApp.jsx
  frontend/src/metabase/admin/settings/selectors.js
  frontend/src/metabase/containers/UndoListing.jsx
  frontend/src/metabase/home/components/CustomHomePageModal/CustomHomePageModal.tsx
  frontend/src/metabase/home/components/HomePage/HomePage.tsx
  frontend/src/metabase/reducers-common.js
  frontend/src/metabase/redux/auth.ts
  frontend/src/metabase/redux/settings.js
  frontend/src/metabase/redux/settings.ts
  frontend/src/metabase/redux/undo.js
  frontend/src/metabase/route-guards.jsx
  frontend/src/metabase/selectors/settings.ts
  src/metabase/api/setting.clj
  src/metabase/api/user.clj
  src/metabase/events/view_log.clj
  src/metabase/models/setting.clj
  test/metabase/api/setting_test.clj
  test/metabase/events/view_log_test.clj
Labels: .Team/PixelPolice :police_officer:

#31547 Fix issue reference in E2E test title
  e2e/test/scenarios/joins/reproductions/18818-crash-when-joining-on-custom-column.cy.spec.js
Labels: Type:Tech Debt

#31641 🍒 [E2E] Add `actions` to stubbed skipped job (#31640)
  .github/workflows/e2e-tests.yml
Labels: was-backported

#31605 Always create a transient dataset for BigQuery tests
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/test/data/bigquery_cloud_sdk.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31516 Docs - updates some apostrophes
  docs/installation-and-operation/running-metabase-on-docker.md
Labels: Type:Documentation, backport

#31526 docs - update data reference
  docs/exploration-and-organization/data-model-reference.md
  docs/exploration-and-organization/images/DataReference.png
  docs/exploration-and-organization/images/connections.png
  docs/exploration-and-organization/images/data-reference-page.png
Labels: Type:Documentation

#31633 Add test after speculative fix
  test/metabase/lib/table_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31546 Update default and min size constraints for dashboard cards
  e2e/support/helpers/e2e-dashboard-helpers.js
  e2e/test/scenarios/dashboard/dashboard-card-resizing.cy.spec.js
  frontend/src/metabase/actions/components/ActionViz/ActionViz.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.jsx
  frontend/src/metabase/visualizations/components/ChoroplethMap.jsx
  frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx
  frontend/src/metabase/visualizations/shared/utils/sizes.ts
  frontend/src/metabase/visualizations/visualizations/AreaChart.jsx
  frontend/src/metabase/visualizations/visualizations/BarChart.jsx
  frontend/src/metabase/visualizations/visualizations/ComboChart.jsx
  frontend/src/metabase/visualizations/visualizations/Funnel.jsx
  frontend/src/metabase/visualizations/visualizations/Gauge/Gauge.jsx
  frontend/src/metabase/visualizations/visualizations/Heading/index.ts
  frontend/src/metabase/visualizations/visualizations/LineChart.jsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkVizSettings.ts
  frontend/src/metabase/visualizations/visualizations/Map.jsx
  frontend/src/metabase/visualizations/visualizations/ObjectDetail.jsx
  frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.jsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.tsx
  frontend/src/metabase/visualizations/visualizations/Progress/Progress.jsx
  frontend/src/metabase/visualizations/visualizations/RowChart/RowChart.tsx
  frontend/src/metabase/visualizations/visualizations/Scalar.jsx
  frontend/src/metabase/visualizations/visualizations/ScatterPlot.jsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar.jsx
  frontend/src/metabase/visualizations/visualizations/Table.jsx
  frontend/src/metabase/visualizations/visualizations/Text/index.ts
  frontend/src/metabase/visualizations/visualizations/WaterfallChart.jsx
Labels: visual, .Team/42 :milky_way:

#31644 Solve OOM failures for `be-cloverage` job
  deps.edn
Labels: .CI & Tests, backport

#31629 docs - csv uploads
  docs/README.md
  docs/configuring-metabase/start.md
  docs/databases/images/upload-icon.png
  docs/databases/start.md
  docs/databases/uploads.md
  docs/exploration-and-organization/collections.md
  docs/exploration-and-organization/images/our-analytics-page.png
  frontend/src/metabase/admin/settings/components/UploadSettings/UploadSettings.tsx
  frontend/src/metabase/admin/settings/components/UploadSettings/UploadSettings.unit.spec.tsx
Labels: Type:Documentation

#31667 Fix some typos in the api/user logic
  src/metabase/api/user.clj
  test/metabase/api/user_test.clj
Labels: .Team/PixelPolice :police_officer:

#31568 Ensure an alias is set when creating a join
  deps.edn
  src/metabase/lib/join.cljc
  test/metabase/lib/join_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:
