Repository metabase/metabase, pull requests merged in 2023-05, with the labels that each got.

#30424 Make bucketing options opaque
  src/metabase/lib/core.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/schema/temporal_bucketing.cljc
  src/metabase/lib/temporal_bucket.cljc
  test/metabase/lib/field_test.cljc
Labels: .Backend, .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30444 Normalize away nil aggregation reference options
  shared/src/metabase/mbql/normalize.cljc
  shared/test/metabase/mbql/normalize_test.cljc
  test/metabase/query_processor_test/test_mlv2.clj
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30427 :cherries: Manual-Backport 30337: SmartScalars should compactify like Scalars
  frontend/src/metabase/visualizations/lib/scalar_utils.ts
  frontend/src/metabase/visualizations/lib/scalar_utils.unit.spec.ts
  frontend/src/metabase/visualizations/visualizations/Scalar.jsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar.jsx
  frontend/test/metabase/visualizations/components/SmartScalar.unit.spec.js
Labels: Type:Bug, Priority:P3, Client:Mobile Web, .Frontend, Visualization/Scalars, was-backported

#30422 Fix metadata handling during implicit joins resolution (#29053)
  src/metabase/query_processor/middleware/add_implicit_joins.clj
  test/metabase/query_processor/middleware/add_implicit_joins_test.clj
Labels: .Backend

#30439 Use keyword as datetime-diff units
  src/metabase/lib/schema/expression/temporal.cljc
  test/metabase/query_processor_test/date_time_zone_functions_test.clj
  test/metabase/query_processor_test/test_mlv2.clj
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30399 Allow Object Detail to show out-of-range detail items
  e2e/test/scenarios/visualizations/object_detail.cy.spec.js
  frontend/src/metabase/components/ErrorDetails/types.ts
  frontend/src/metabase/containers/ErrorPages.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.styled.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/utils.ts
  frontend/src/metabase/visualizations/components/ObjectDetail/utils.unit.spec.ts
Labels: visual, .Team/Viz :bar_chart:

#30398 Render markdown in card and dashboard descriptions
  src/metabase/email/pulse.mustache
  src/metabase/pulse.clj
  src/metabase/pulse/render.clj
  test/metabase/pulse/render_test.clj
  test/metabase/pulse_test.clj
Labels: visual

#30387 [RFC] Add entity loader hooks
  frontend/src/metabase-types/api/database.ts
  frontend/src/metabase-types/api/table.ts
  frontend/src/metabase/common/hooks/use-database-id-field-list-query/index.ts
  frontend/src/metabase/common/hooks/use-database-id-field-list-query/use-database-id-field-list-query.ts
  frontend/src/metabase/common/hooks/use-database-list-query/index.ts
  frontend/src/metabase/common/hooks/use-database-list-query/use-database-list-query.ts
  frontend/src/metabase/common/hooks/use-database-list-query/use-database-list-query.unit.spec.tsx
  frontend/src/metabase/common/hooks/use-entity-list-query/index.ts
  frontend/src/metabase/common/hooks/use-entity-list-query/use-entity-list-query.ts
  frontend/src/metabase/common/hooks/use-entity-query/index.ts
  frontend/src/metabase/common/hooks/use-entity-query/use-entity-query.ts
  frontend/src/metabase/common/hooks/use-table-list-query/index.ts
  frontend/src/metabase/common/hooks/use-table-list-query/use-table-list-query.ts
  frontend/src/metabase/common/hooks/use-table-list-query/use-table-list-query.unit.spec.tsx
  frontend/src/metabase/common/hooks/use-table-query/index.ts
  frontend/src/metabase/common/hooks/use-table-query/use-table-query.ts
  frontend/src/metabase/common/hooks/use-table-query/use-table-query.unit.spec.tsx
Labels: .Team/QueryBuilder :abacus:

#30404 Reusable Common Link Variants
  frontend/src/metabase/account/notifications/components/HelpModal/HelpModal.jsx
  frontend/src/metabase/account/notifications/components/HelpModal/HelpModal.styled.jsx
  frontend/src/metabase/account/notifications/components/NotificationCard/NotificationCard.jsx
  frontend/src/metabase/account/notifications/components/NotificationCard/NotificationCard.styled.jsx
  frontend/src/metabase/admin/app/components/DeprecationNotice/DeprecationNotice.styled.tsx
  frontend/src/metabase/admin/app/components/DeprecationNotice/DeprecationNotice.tsx
  frontend/src/metabase/admin/tasks/containers/ModelCacheRefreshJobs/ModelCacheRefreshJobs.styled.tsx
  frontend/src/metabase/admin/tasks/containers/ModelCacheRefreshJobs/ModelCacheRefreshJobs.tsx
  frontend/src/metabase/core/components/Link/Link.stories.tsx
  frontend/src/metabase/core/components/Link/Link.styled.tsx
  frontend/src/metabase/core/components/Link/Link.tsx
  frontend/src/metabase/core/components/Link/index.ts
  frontend/src/metabase/core/components/Link/types.ts
  frontend/src/metabase/dashboard/components/Dashboard/DashboardEmptyState/DashboardEmptyState.jsx
  frontend/src/metabase/dashboard/components/Dashboard/DashboardEmptyState/DashboardEmptyState.styled.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar.styled.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar.tsx
Labels: Type:Tech Debt, .Team/Viz :bar_chart:

#30378 Don't crash with null collection search result
  frontend/src/metabase/collections/utils.ts
  frontend/src/metabase/collections/utils.unit.spec.js
  frontend/src/metabase/collections/utils.unit.spec.ts
Labels: .Team/Viz :bar_chart:

#29861 Dashboard tabs CRUD
  .clj-kondo/config.edn
  enterprise/backend/test/metabase_enterprise/sandbox/api/dashboard_test.clj
  src/metabase/api/dashboard.clj
  src/metabase/models/dashboard_card.clj
  src/metabase/util/malli/schema.clj
  test/metabase/api/dashboard_test.clj
Labels: .Team/Backend :pancakes:

#30396 [MLv2] Add wrappers for column type checks, add `getColumnIcon` helper
  frontend/src/metabase-lib/breakout.unit.spec.ts
  frontend/src/metabase-lib/column_types.ts
  frontend/src/metabase-lib/metadata/utils/fields.ts
  frontend/src/metabase-lib/order_by.unit.spec.ts
  frontend/src/metabase-lib/test-helpers.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase-lib/v2.ts
  frontend/src/metabase/common/components/QueryColumnPicker/QueryColumnPicker.tsx
  frontend/src/metabase/common/utils/columns.ts
  frontend/src/metabase/common/utils/columns.unit.spec.ts
  frontend/test/__support__/sample_database_fixture.json
  frontend/test/metabase-lib/lib/Dimension.unit.spec.js
  shadow-cljs.edn
Labels: .metabase-lib

#30460 Migrate field refs in visualization_settings.column_settings from legacy format
  resources/migrations/000_migrations.yaml
  src/metabase/db/custom_migrations.clj
  test/metabase/db/custom_migrations_test.clj
Labels: .Team/Backend :pancakes:

#30462 Take an optional length instead of end for :substring
  src/metabase/lib/schema/expression/string.cljc
  test/metabase/query_processor_test/test_mlv2.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30467 Add date and time extract sugar functions to MLv2
  src/metabase/lib/schema/expression/temporal.cljc
  test/metabase/query_processor_test/test_mlv2.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30426 20911 include subcollections permissions
  e2e/support/helpers/e2e-permissions-helpers.js
  e2e/test/scenarios/collections/reproductions/20911-include-subcollections-permissions.cy.spec.js
  frontend/src/metabase/admin/permissions/components/CollectionPermissionsModal/CollectionPermissionsModal.jsx
  frontend/src/metabase/admin/permissions/components/PermissionsSelect/PermissionsSelect.jsx
  frontend/src/metabase/admin/permissions/selectors/collection-permissions.js
Labels: .Team/QueryBuilder :abacus:

#30463 Fix v1 dump command errors when logging entities
  enterprise/backend/src/metabase_enterprise/serialization/names.clj
  enterprise/backend/test/metabase_enterprise/serialization/names_test.clj
Labels: backport

#30496 Specify baseUrl for e2e tests
  e2e/tsconfig.json
Labels: .Team/QueryBuilder :abacus:

#30356 Use display name from model for implicit actions
  e2e/test/scenarios/dashboard/actions-on-dashboards.cy.spec.js
  e2e/test/scenarios/models/model-actions.cy.spec.js
  frontend/src/metabase-types/api/mocks/actions.ts
  frontend/src/metabase/actions/components/ActionViz/Action.unit.spec.tsx
  frontend/src/metabase/actions/containers/ActionParametersInputForm/ActionParametersInputForm.unit.spec.tsx
  frontend/src/metabase/actions/hooks/use-action-form/utils.ts
  frontend/src/metabase/actions/hooks/use-action-form/utils.unit.spec.ts
  frontend/src/metabase/public/containers/PublicAction/PublicAction.unit.spec.tsx
  src/metabase/models/action.clj
  test/metabase/models/action_test.clj
Labels: backport, .Team/Backend :pancakes:

#30483 Add database and schema entity hooks
  frontend/src/metabase-types/api/database.ts
  frontend/src/metabase-types/api/table.ts
  frontend/src/metabase/common/hooks/index.ts
  frontend/src/metabase/common/hooks/use-database-query/index.ts
  frontend/src/metabase/common/hooks/use-database-query/use-database-query.ts
  frontend/src/metabase/common/hooks/use-database-query/use-database-query.unit.spec.tsx
  frontend/src/metabase/common/hooks/use-schema-list-query/index.ts
  frontend/src/metabase/common/hooks/use-schema-list-query/use-schema-list-query.ts
  frontend/src/metabase/common/hooks/use-schema-list-query/use-schema-list-query.unit.spec.tsx
Labels: .Team/QueryBuilder :abacus:

#30503 Add correct types to the entities state
  frontend/src/metabase-types/api/collection.ts
  frontend/src/metabase-types/api/index.ts
  frontend/src/metabase-types/api/schema.ts
  frontend/src/metabase-types/store/entities.ts
  frontend/src/metabase/dashboard/containers/CreateDashboardModal.unit.spec.tsx
  frontend/src/metabase/entities/containers/EntityName.unit.spec.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbar.unit.spec.tsx
  frontend/test/__support__/sample_database_fixture.ts
Labels: .Team/QueryBuilder :abacus:

#30493 Remove CircleCi integration
  .circleci/config.yml
  deps.edn
  docs/developers-guide/drivers/driver-tests.md
Labels: .CI & Tests, backport

#30505 Properly quote token in master test failure notification script
  .github/workflows/rerun-workflows.yml
Labels: .CI & Tests, .Team/Viz :bar_chart:

#30530 Fix types in permissions selectors
  frontend/src/metabase/admin/permissions/pages/DataPermissionsPage/DataPermissionsPage.jsx
  frontend/src/metabase/admin/permissions/selectors/data-permissions/diff.ts
  frontend/src/metabase/admin/permissions/utils/graph/permissions-diff.ts
  frontend/src/metabase/entities/databases.js
Labels: .Team/QueryBuilder :abacus:

#30531 Fix #30494: fix subcollection apply logic
  e2e/support/helpers/e2e-permissions-helpers.js
  e2e/test/scenarios/collections/reproductions/20911-include-subcollections-permissions.cy.spec.js
  e2e/test/scenarios/permissions/admin-permissions.cy.spec.js
  frontend/src/metabase/admin/permissions/components/PermissionsSelect/PermissionsSelect.jsx
  frontend/src/metabase/admin/permissions/selectors/collection-permissions.js
Labels: .Team/QueryBuilder :abacus:

#30537 Escape schema and table names in Snowflake JDBC metadata calls
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#30410 use the new endpoint to fetch compatible cards in the add series modal
  frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.jsx
  frontend/src/metabase/dashboard/components/AddSeriesModal/QuestionList.jsx
  frontend/src/metabase/dashboard/components/AddSeriesModal/QuestionList.styled.jsx
  frontend/src/metabase/dashboard/components/AddSeriesModal/QuestionList.tsx
  frontend/src/metabase/dashboard/components/AddSeriesModal/QuestionListItem.jsx
  frontend/src/metabase/dashboard/components/AddSeriesModal/QuestionListItem.styled.tsx
  frontend/src/metabase/dashboard/components/AddSeriesModal/QuestionListItem.tsx
  frontend/src/metabase/services.js
Labels: .Team/Viz :bar_chart:

#30423 Make editing field settings not rely on the full database metadata
  e2e/test/scenarios/admin/datamodel/editor.cy.spec.js
  e2e/test/scenarios/admin/datamodel/field-type.cy.spec.js
  frontend/src/metabase-lib/metadata/Database.ts
  frontend/src/metabase-lib/metadata/Field.ts
  frontend/src/metabase-types/api/field.ts
  frontend/src/metabase-types/api/mocks/field.ts
  frontend/src/metabase-types/entities/database.ts
  frontend/src/metabase/admin/datamodel/components/SelectSeparator.jsx
  frontend/src/metabase/admin/datamodel/components/database/ColumnItem/ColumnItem.jsx
  frontend/src/metabase/admin/datamodel/components/database/ColumnItem/index.ts
  frontend/src/metabase/admin/datamodel/containers/FieldApp.jsx
  frontend/src/metabase/admin/datamodel/containers/FieldApp.styled.tsx
  frontend/src/metabase/admin/datamodel/metadata/actions.ts
  frontend/src/metabase/admin/datamodel/metadata/components/FieldFormattingSettings/FieldFormattingSettings.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/FieldFormattingSettings/index.ts
  frontend/src/metabase/admin/datamodel/metadata/components/FieldGeneralSettings/FieldGeneralSettings.styled.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/FieldGeneralSettings/FieldGeneralSettings.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/FieldGeneralSettings/index.ts
  frontend/src/metabase/admin/datamodel/metadata/components/FieldRemappingSettings/FieldRemappingSettings.jsx
  frontend/src/metabase/admin/datamodel/metadata/components/FieldRemappingSettings/FieldRemappingSettings.styled.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/FieldRemappingSettings/index.ts
  frontend/src/metabase/admin/datamodel/metadata/components/FieldSeparator/FieldSeparator.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/FieldSeparator/index.ts
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataFieldSettings/MetadataFieldSettings.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataFieldSettings/index.ts
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataTable/MetadataTable.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataTableColumn/MetadataTableColumn.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataTableSettings/MetadataTableSettings.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/SemanticTypeAndTargetPicker/SemanticTypeAndTargetPicker.tsx
  frontend/src/metabase/admin/routes.jsx
  frontend/src/metabase/entities/containers/EntityObjectLoader.jsx
  frontend/src/metabase/entities/databases.js
  frontend/src/metabase/entities/fields.js
  frontend/src/metabase/entities/tables.js
  frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceTypeModal.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetFieldMetadataSidebar/SemanticTypePicker/FKTargetPicker.tsx
  frontend/src/metabase/schema.js
Labels: .Team/QueryBuilder :abacus:

#30506 Clean up metadata selectors
  frontend/src/metabase-lib/metadata/Field.ts
  frontend/src/metabase-lib/metadata/Metadata.ts
  frontend/src/metabase-lib/metadata/Metric.ts
  frontend/src/metabase-lib/metadata/Schema.ts
  frontend/src/metabase-lib/metadata/Segment.ts
  frontend/src/metabase-types/api/field.ts
  frontend/src/metabase/dashboard/containers/DashboardApp.jsx
  frontend/src/metabase/entities/databases.js
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterSelect/BulkFilterSelect.tsx
  frontend/src/metabase/selectors/metadata.js
  frontend/src/metabase/selectors/metadata.ts
  frontend/src/metabase/selectors/metadata.unit.spec.js
  frontend/src/metabase/selectors/metadata.unit.spec.ts
  frontend/test/__support__/sample_database_fixture.ts
  frontend/test/__support__/store.ts
  frontend/test/__support__/ui.tsx
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30560 Reorg mock entity state helpers, add `createMockMetadata`
  frontend/src/metabase-types/store/mocks/entities.ts
  frontend/src/metabase-types/store/mocks/index.ts
  frontend/src/metabase-types/store/mocks/state.ts
  frontend/src/metabase/collections/components/ActionMenu/ActionMenu.unit.spec.tsx
  frontend/src/metabase/collections/containers/CreateCollectionForm.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.unit.spec.jsx
  frontend/src/metabase/dashboard/containers/CreateDashboardModal.unit.spec.tsx
  frontend/src/metabase/entities/containers/EntityName.unit.spec.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbar.unit.spec.tsx
  frontend/src/metabase/query_builder/components/QueryDownloadWidget/QueryDownloadWidget.unit.spec.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/ReadOnlyNotebook.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/ExpressionStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.unit.spec.tsx
  frontend/src/metabase/query_builder/containers/QueryViewer.unit.spec.tsx
  frontend/src/metabase/selectors/metadata.ts
  frontend/src/metabase/selectors/metadata.unit.spec.ts
  frontend/src/metabase/services.unit.spec.ts
  frontend/test/__support__/metadata.ts
  frontend/test/__support__/store.ts
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30525 Extend `addUndo` API for auto-apply filters toast
  e2e/test/scenarios/dashboard-filters/old-parameters.cy.spec.js
  frontend/src/metabase/containers/UndoListing.jsx
  frontend/src/metabase/dashboard/components/AutoApplyFilterToast/index.ts
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.jsx
  frontend/src/metabase/dashboard/hooks/useAutoApplyFiltersToast.tsx
  frontend/src/metabase/lib/redux/utils.js
  frontend/src/metabase/redux/undo.js
Labels: .Team/QueryBuilder :abacus:

#30484 Make editing field settings not rely on the full database metadata
  e2e/test/scenarios/admin/datamodel/editor.cy.spec.js
  e2e/test/scenarios/admin/datamodel/field-type.cy.spec.js
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  frontend/src/metabase-lib/metadata/Database.ts
  frontend/src/metabase-lib/metadata/Field.ts
  frontend/src/metabase-types/api/field.ts
  frontend/src/metabase-types/api/mocks/field.ts
  frontend/src/metabase-types/entities/database.ts
  frontend/src/metabase/admin/datamodel/components/SelectSeparator.jsx
  frontend/src/metabase/admin/datamodel/components/database/ColumnItem/ColumnItem.jsx
  frontend/src/metabase/admin/datamodel/components/database/ColumnItem/index.ts
  frontend/src/metabase/admin/datamodel/containers/FieldApp.jsx
  frontend/src/metabase/admin/datamodel/containers/FieldApp.styled.tsx
  frontend/src/metabase/admin/datamodel/metadata/actions.ts
  frontend/src/metabase/admin/datamodel/metadata/components/FieldFormattingSettings/FieldFormattingSettings.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/FieldFormattingSettings/index.ts
  frontend/src/metabase/admin/datamodel/metadata/components/FieldGeneralSettings/FieldGeneralSettings.styled.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/FieldGeneralSettings/FieldGeneralSettings.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/FieldGeneralSettings/index.ts
  frontend/src/metabase/admin/datamodel/metadata/components/FieldRemappingSettings/FieldRemappingSettings.jsx
  frontend/src/metabase/admin/datamodel/metadata/components/FieldRemappingSettings/FieldRemappingSettings.styled.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/FieldRemappingSettings/index.ts
  frontend/src/metabase/admin/datamodel/metadata/components/FieldSeparator/FieldSeparator.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/FieldSeparator/index.ts
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataFieldSettings/MetadataFieldSettings.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataFieldSettings/index.ts
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataTable/MetadataTable.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataTableColumn/MetadataTableColumn.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataTableSettings/MetadataTableSettings.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/SemanticTypeAndTargetPicker/SemanticTypeAndTargetPicker.tsx
  frontend/src/metabase/admin/routes.jsx
  frontend/src/metabase/entities/containers/EntityObjectLoader.jsx
  frontend/src/metabase/entities/databases.js
  frontend/src/metabase/entities/fields.js
  frontend/src/metabase/entities/tables.js
  frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceTypeModal.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetFieldMetadataSidebar/SemanticTypePicker/FKTargetPicker.tsx
  frontend/src/metabase/schema.js
  src/metabase/api/field.clj
  src/metabase/models/field.clj
  test/metabase/api/field_test.clj
Labels: .Team/Backend :pancakes:

#30417 Parse currency appropriately in CSVs
  src/metabase/upload.clj
  test/metabase/upload_test.clj
Labels: .Team/Backend :pancakes:

#30576 Address nits not merged with #30484
  src/metabase/api/field.clj
  test/metabase/api/field_test.clj
Labels: .Team/Backend :pancakes:

#29516 Tidy driver/database-supports? defmethods and remove usage of driver/supports?
  dev/src/dev.clj
  docs/developers-guide/driver-changelog.md
  enterprise/backend/test/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions_test.clj
  modules/drivers/athena/src/metabase/driver/athena.clj
  modules/drivers/athena/test/metabase/test/data/athena.clj
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/test/data/bigquery_cloud_sdk.clj
  modules/drivers/druid/src/metabase/driver/druid.clj
  modules/drivers/googleanalytics/src/metabase/driver/googleanalytics.clj
  modules/drivers/mongo/src/metabase/driver/mongo.clj
  modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj
  modules/drivers/mongo/test/metabase/driver/mongo/query_processor_test.clj
  modules/drivers/oracle/src/metabase/driver/oracle.clj
  modules/drivers/oracle/test/metabase/test/data/oracle.clj
  modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj
  modules/drivers/presto-jdbc/test/metabase/driver/presto_jdbc_test.clj
  modules/drivers/presto-jdbc/test/metabase/test/data/presto_jdbc.clj
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/sparksql/src/metabase/driver/hive_like.clj
  modules/drivers/sparksql/src/metabase/driver/sparksql.clj
  modules/drivers/sparksql/test/metabase/test/data/sparksql.clj
  modules/drivers/sqlite/src/metabase/driver/sqlite.clj
  modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj
  modules/drivers/sqlserver/test/metabase/driver/sqlserver_test.clj
  modules/drivers/vertica/src/metabase/driver/vertica.clj
  modules/drivers/vertica/test/metabase/test/data/vertica.clj
  src/metabase/api/database.clj
  src/metabase/api/table.clj
  src/metabase/automagic_dashboards/core.clj
  src/metabase/driver.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql.clj
  src/metabase/driver/sql_jdbc.clj
  src/metabase/query_processor/middleware/parameters/native.clj
  src/metabase/query_processor/middleware/results_metadata.clj
  src/metabase/query_processor/timezone.clj
  src/metabase/sync/fetch_metadata.clj
  test/metabase/api/database_test.clj
  test/metabase/db/metadata_queries_test.clj
  test/metabase/driver/sql/query_processor_test.clj
  test/metabase/driver_test.clj
  test/metabase/query_processor/middleware/add_timezone_info_test.clj
  test/metabase/query_processor/middleware/format_rows_test.clj
  test/metabase/query_processor/middleware/optimize_temporal_filters_test.clj
  test/metabase/query_processor/middleware/parameters/mbql_test.clj
  test/metabase/query_processor/middleware/parameters/native_test.clj
  test/metabase/query_processor/middleware/parameters_test.clj
  test/metabase/query_processor/middleware/wrap_value_literals_test.clj
  test/metabase/query_processor_test.clj
  test/metabase/query_processor_test/date_bucketing_test.clj
  test/metabase/query_processor_test/date_time_zone_functions_test.clj
  test/metabase/sync_test.clj
  test/metabase/test.clj
  test/metabase/test/data/interface.clj
  test/metabase/test/data/postgres.clj
  test/metabase/test/mock/moviedb.clj
  test/metabase/test/mock/toucanery.clj
Labels: .Team/Backend 🥞

#30473 Fancier Upload Settings
  e2e/test/scenarios/collections/uploads.cy.spec.js
  frontend/src/metabase-types/api/mocks/table.ts
  frontend/src/metabase/admin/settings/components/UploadSettings/UploadSetting.styled.tsx
  frontend/src/metabase/admin/settings/components/UploadSettings/UploadSettings.tsx
  frontend/src/metabase/admin/settings/components/UploadSettings/UploadSettings.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/UploadSettings/index.ts
  frontend/src/metabase/admin/settings/components/UploadSettings/utils.ts
  frontend/src/metabase/admin/settings/components/UploadSettings/utils.unit.spec.ts
  frontend/src/metabase/admin/settings/components/widgets/UploadSettingsWidget/UploadSettingsWidget.tsx
  frontend/src/metabase/admin/settings/components/widgets/UploadSettingsWidget/index.ts
  frontend/src/metabase/admin/settings/containers/SettingsEditorApp.jsx
  frontend/src/metabase/admin/settings/selectors.js
  frontend/src/metabase/components/ActionButton/ActionButton.jsx
  frontend/src/metabase/components/ActionButton/ActionButton.styled.tsx
  frontend/src/metabase/components/SaveStatus/SaveStatus.jsx
Labels: .Team/Viz :bar_chart:

#30582 docs - slack channel renaming note
  docs/configuring-metabase/slack.md
  docs/dashboards/subscriptions.md
  docs/questions/sharing/alerts.md
Labels: Type:Documentation, backport

#30528 Updating StringInputWidget to use underscore instead of lodash
  frontend/src/metabase/parameters/components/widgets/StringInputWidget/StringInputWidget.tsx
Labels: .Team/Viz :bar_chart:

#30591 Repro #30535: User session affects embedded question
  e2e/test/scenarios/embedding/reproductions/30535-session-sandboxing.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#30529 Add GET /api/database/{id}/syncable_schemas endpoint
  docs/developers-guide/driver-changelog.md
  src/metabase/api/database.clj
  src/metabase/driver.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql_jdbc.clj
  test/metabase/api/database_test.clj
  test/metabase/driver/h2_test.clj
  test/metabase/driver/mysql_test.clj
  test/metabase/driver/postgres_test.clj
Labels: .Team/Backend :pancakes:

#30554 Update connection impersonation warning
  enterprise/frontend/src/metabase-enterprise/advanced_permissions/components/RoleAccessWarning/RoleAccessWarning.styled.tsx
  enterprise/frontend/src/metabase-enterprise/advanced_permissions/components/RoleAccessWarning/RoleAccessWarning.tsx
  enterprise/frontend/src/metabase-enterprise/advanced_permissions/components/RoleAccessWarning/RoleAccessWarning.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/advanced_permissions/components/RoleAccessWarning/index.ts
  enterprise/frontend/src/metabase-enterprise/advanced_permissions/components/RoleAttributeMappingModal/RoleAttributeMappingModalView.styled.tsx
  enterprise/frontend/src/metabase-enterprise/advanced_permissions/components/RoleAttributeMappingModal/RoleAttributeMappingModalView.tsx
  frontend/src/metabase/admin/databases/containers/DatabaseEditApp.jsx
  frontend/src/metabase/databases/components/DatabaseDetailField/DatabaseDetailField.tsx
  frontend/src/metabase/databases/components/DatabaseForm/DatabaseForm.tsx
Labels: .Team/Viz :bar_chart:

#30586 Add tooltip to upload button
  frontend/src/metabase/collections/components/CollectionHeader/CollectionUpload.tsx
Labels: .Team/Viz :bar_chart:

#30477 Add warning message when leaving an edited, existing SQL question
  frontend/src/metabase/query_builder/components/__mocks__/NativeQueryEditor.jsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.jsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.unit.spec.tsx
Labels: .Team/QueryBuilder :abacus:

#30592 docs - update postgres
  docs/databases/connections/postgresql.md
Labels: Type:Documentation, backport

#30595 🍒 Repro #30535: User session affects embedded question (#30591)
  e2e/test/scenarios/embedding/reproductions/30535-session-sandboxing.cy.spec.js
Labels: was-backported

#30616 Fix mismatches in sample database mock
  frontend/src/metabase-types/api/mocks/presets/sample_database.ts
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30490 CI on fuzzing: make sure Clojure is available (due to CLJS)
  .github/workflows/fuzzing.yml
Labels: .CI & Tests

#30621 Ignore Twitter links in markdown link checker
  .mlc_config.json
Labels: .CI & Tests, backport

#30523 Add warning message when trying to navigate away from editing a model's query or metadata
  frontend/src/metabase-types/api/dataset.ts
  frontend/src/metabase-types/api/mocks/dataset.ts
  frontend/src/metabase-types/api/query.ts
  frontend/src/metabase/admin/permissions/pages/DataPermissionsPage/DataPermissionsPage.tsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.jsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.unit.spec.tsx
  frontend/src/metabase/static-viz/components/LineAreaBarChart/utils/series.unit.spec.ts
  frontend/src/metabase/visualizations/components/ChartCaption.unit.spec.tsx
Labels: visual, .Team/QueryBuilder :abacus:

#30617 Use `createMockMetadata` for MLv2 test helpers
  frontend/src/metabase-lib/order_by.unit.spec.ts
  frontend/src/metabase-lib/test-helpers.ts
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30633 Don't lint non-SSL links either
  .mlc_config.json
Labels: .Team/Backend :pancakes:

#30635 Expand the test coverage for `ListItem` component
  frontend/src/metabase/components/ListItem/ListItem.unit.spec.js
Labels: .CI & Tests, backport

#30640 Ignore provided metadata on new cards
  src/metabase/api/card.clj
  test/metabase/api/card_test.clj
Labels: Type:Bug, backport, .Team/QueryProcessor :hammer_and_wrench:, .Escalation

#30469 Omit :effective-type from legacy MBQL queries
  src/metabase/lib/convert.cljc
  test/metabase/lib/convert_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30499 Fix wrong test
  test/metabase/api/card_test.clj
  test/metabase/query_processor_test/test_mlv2.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30644 Prevent fields hiding joined fields
  src/metabase/lib/stage.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/stage_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30628 Don't sandbox embedded queries
  e2e/test/scenarios/embedding/reproductions/30535-session-sandboxing.cy.spec.js
  enterprise/backend/src/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions.clj
  enterprise/backend/test/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions_test.clj
  src/metabase/api/public.clj
  src/metabase/server/middleware/session.clj
  test/metabase/server/middleware/session_test.clj
Labels: backport, .Team/FunPolice :police_officer:

#30654 Revert "Prevent fields hiding joined fields (#30644)"
  src/metabase/lib/stage.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/stage_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30584 Add back button to return to the active dashboard
  e2e/test/scenarios/dashboard/dashboard-drill.cy.spec.js
  frontend/src/metabase/dashboard/actions/navigation.js
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.tsx
  frontend/src/metabase/dashboard/selectors.js
  frontend/src/metabase/query_builder/actions/ui.js
  frontend/src/metabase/query_builder/components/view/ViewHeader.jsx
  frontend/src/metabase/query_builder/components/view/ViewHeader.styled.jsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.jsx
  frontend/src/metabase/query_builder/reducers.js
  frontend/src/metabase/query_builder/selectors.js
Labels: .Team/QueryBuilder :abacus:

#30606 Update upload button tooltip
  frontend/src/metabase/collections/components/CollectionHeader/CollectionHeader.tsx
  frontend/src/metabase/collections/components/CollectionHeader/CollectionUpload.tsx
  frontend/src/metabase/core/components/Tooltip/Tooltip.styled.tsx
  frontend/src/metabase/core/components/Tooltip/index.ts
  frontend/src/metabase/redux/uploads.ts
  frontend/src/metabase/redux/uploads.unit.spec.js
Labels: .Team/Viz :bar_chart:

#30587 Add some error boundaries to collections
  frontend/src/metabase/collections/containers/CollectionContent.jsx
Labels: .Team/Viz :bar_chart:

#30613 Fix issues in auto apply button
  e2e/support/commands/api/dashboard.js
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-auto-apply.cy.spec.js
  e2e/test/scenarios/dashboard-filters/old-parameters.cy.spec.js
  frontend/src/metabase/components/ExplicitSize.jsx
  frontend/src/metabase/containers/UndoListing.jsx
  frontend/src/metabase/dashboard/actions/data-fetching.js
  frontend/src/metabase/dashboard/actions/parameters.js
  frontend/src/metabase/dashboard/actions/ui.js
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.jsx
  frontend/src/metabase/dashboard/hooks/useAutoApplyFiltersToast.tsx
  frontend/src/metabase/dashboard/reducers.js
  frontend/src/metabase/dashboard/reducers.unit.spec.js
  frontend/src/metabase/dashboard/selectors.js
  frontend/src/metabase/parameters/components/FilterApplyButton/FilterApplyButton.styled.ts
  frontend/src/metabase/parameters/components/FilterApplyButton/FilterApplyButton.tsx
  frontend/src/metabase/redux/undo.js
Labels: .Team/QueryBuilder :abacus:

#30620 Add optional message to error boundaries
  frontend/src/metabase/ErrorBoundary.tsx
Labels: .Frontend, .Team/Viz :bar_chart:

#30624 Add styling to dropzone overlay
  frontend/src/metabase/collections/components/UploadOverlay/UploadOverlay.styled.tsx
  frontend/src/metabase/collections/components/UploadOverlay/UploadOverlay.tsx
  frontend/src/metabase/collections/containers/CollectionContent.jsx
  frontend/src/metabase/collections/containers/CollectionContent.styled.tsx
  frontend/src/metabase/lib/colors/palette.ts
Labels: .Team/Viz :bar_chart:

#30675 Alternative GEOJSON.io fix
  test/metabase/api/login_history_test.clj
  test/metabase/api/session_test.clj
  test/metabase/server/request/util_test.clj
Labels: backport, .Team/Backend :pancakes:

#30445 docs - update data sandboxing
  docs/people-and-groups/managing.md
  docs/permissions/data-sandbox-examples.md
  docs/permissions/data-sandboxes.md
Labels: Type:Documentation, backport

#30217 Fix custom mapping doesn't work on dashboard
  e2e/test/scenarios/dashboard-filters/reproductions/29347-remapped-field-values.cy.spec.js
  enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/dashboard_test.clj
  src/metabase/api/dashboard.clj
  src/metabase/api/public.clj
  src/metabase/models/params.clj
  src/metabase/models/params/field_values.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/embed_test.clj
  test/metabase/api/public_test.clj
Labels: .Team/Backend :pancakes:

#30068 report_* models to toucan2
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/upsert_test.clj
  src/metabase/api/dashboard.clj
  src/metabase/db/util.clj
  src/metabase/models/dashboard.clj
  src/metabase/models/dashboard_card.clj
  src/metabase/models/dashboard_card_series.clj
  src/metabase/models/params.clj
  src/metabase/models/serialization.clj
  test/metabase/api/public_test.clj
  test/metabase/models/card_test.clj
  test/metabase/test/util.clj
Labels: .Team/Backend :pancakes:

#30536 Add `schemas` driver feature
  docs/developers-guide/driver-changelog.md
  modules/drivers/mongo/src/metabase/driver/mongo.clj
  modules/drivers/sqlite/src/metabase/driver/sqlite.clj
  src/metabase/driver.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  test/metabase/driver_test.clj
Labels: .Team/Backend :pancakes:

#30659 Parallelize three tests with typos
  test/metabase/driver/sql/parameters/substitute_test.clj
  test/metabase/driver/sql/parameters/substitution_test.clj
  test/metabase/driver/sql/query_processor_test.clj
Labels: .Team/Backend :pancakes:

#30569 Milestone 2 of [Epic] Prevent auto-apply filters in slow dashboards #29267
  e2e/support/commands/api/dashboard.js
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-auto-apply.cy.spec.js
  e2e/test/scenarios/dashboard-filters/old-parameters.cy.spec.js
  frontend/src/metabase/components/ExplicitSize.jsx
  frontend/src/metabase/containers/UndoListing.jsx
  frontend/src/metabase/dashboard/actions/data-fetching.js
  frontend/src/metabase/dashboard/actions/parameters.js
  frontend/src/metabase/dashboard/actions/save.js
  frontend/src/metabase/dashboard/actions/ui.js
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx
  frontend/src/metabase/dashboard/components/DashboardInfoSidebar.tsx
  frontend/src/metabase/dashboard/constants.js
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.jsx
  frontend/src/metabase/dashboard/containers/DashboardApp/index.js
  frontend/src/metabase/dashboard/containers/DashboardHeader.jsx
  frontend/src/metabase/dashboard/reducers.js
  frontend/src/metabase/dashboard/reducers.unit.spec.js
  frontend/src/metabase/dashboard/selectors.js
  frontend/src/metabase/hoc/TitleWithLoadingTime.jsx
  frontend/src/metabase/lib/redux/utils.js
  frontend/src/metabase/parameters/components/FilterApplyButton/FilterApplyButton.styled.ts
  frontend/src/metabase/parameters/components/FilterApplyButton/FilterApplyButton.tsx
  frontend/src/metabase/query_builder/components/VisualizationError.jsx
  frontend/src/metabase/query_builder/constants.ts
  frontend/src/metabase/query_builder/containers/QueryBuilder.jsx
  frontend/src/metabase/redux/undo.js
Labels: .Team/QueryBuilder :abacus:

#30661 Fix wrongly used `Database` and `Table` types from `metabase-types/api`
  frontend/src/metabase-lib/metadata/Database.ts
  frontend/src/metabase-types/api/database.ts
  frontend/src/metabase/admin/app/containers/DeprecationNotice/DeprecationNotice.tsx
  frontend/src/metabase/admin/app/selectors.ts
  frontend/src/metabase/admin/databases/components/DatabaseEditApp/Sidebar/Sidebar.tsx
  frontend/src/metabase/admin/permissions/selectors/data-permissions/permission-editor.ts
  frontend/src/metabase/admin/settings/components/UploadSettings/UploadSettings.tsx
  frontend/src/metabase/admin/settings/components/UploadSettings/UploadSettings.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/UploadSettings/utils.ts
  frontend/src/metabase/admin/settings/components/UploadSettings/utils.unit.spec.ts
  frontend/src/metabase/containers/DataPicker/DataPickerContainer.tsx
  frontend/src/metabase/containers/NewItemMenu/NewItemMenu.tsx
  frontend/src/metabase/databases/containers/DatabaseSyncModal/DatabaseSyncModal.tsx
  frontend/src/metabase/home/homepage/components/HomeContent/HomeContent.tsx
  frontend/src/metabase/home/homepage/components/HomeContent/HomeContent.unit.spec.tsx
  frontend/src/metabase/home/homepage/components/HomeXraySection/HomeXraySection.tsx
  frontend/src/metabase/home/homepage/components/HomeXraySection/HomeXraySection.unit.spec.tsx
  frontend/src/metabase/home/homepage/containers/HomeXraySection/HomeXraySection.tsx
  frontend/src/metabase/lib/urls/browse.ts
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarContainer.tsx
  frontend/src/metabase/selectors/data.ts
  frontend/src/metabase/selectors/data.unit.spec.ts
  frontend/src/metabase/status/components/DatabaseStatus/DatabaseStatus.tsx
  frontend/src/metabase/status/components/DatabaseStatus/DatabaseStatus.unit.spec.tsx
  frontend/src/metabase/status/components/DatabaseStatusLarge/DatabaseStatusLarge.stories.tsx
  frontend/src/metabase/status/components/DatabaseStatusLarge/DatabaseStatusLarge.tsx
  frontend/src/metabase/status/components/DatabaseStatusLarge/DatabaseStatusLarge.unit.spec.tsx
  frontend/src/metabase/status/components/DatabaseStatusSmall/DatabaseStatusSmall.stories.tsx
  frontend/src/metabase/status/components/DatabaseStatusSmall/DatabaseStatusSmall.tsx
  frontend/src/metabase/status/components/DatabaseStatusSmall/DatabaseStatusSmall.unit.spec.tsx
  frontend/src/metabase/status/containers/DatabaseStatus/DatabaseStatus.tsx
Labels: .Team/QueryBuilder :abacus:

#30687 Handle api errors in entity hooks
  frontend/src/metabase/common/hooks/use-database-query/use-database-query.unit.spec.tsx
  frontend/src/metabase/common/hooks/use-entity-list-query/use-entity-list-query.ts
  frontend/src/metabase/common/hooks/use-entity-query/use-entity-query.ts
  frontend/src/metabase/common/hooks/use-schema-list-query/use-schema-list-query.unit.spec.tsx
  frontend/test/__support__/server-mocks/database.ts
  frontend/test/__support__/server-mocks/index.ts
Labels: .Team/QueryBuilder :abacus:

#30655 Add field values to sample database mock preset
  frontend/src/metabase-types/api/mocks/presets/sample_database.ts
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30678 Remove non-existent database key
  frontend/src/metabase/reference/databases/DatabaseList.jsx
Labels: Type:Tech Debt

#30650 Refactor `ListItem` component
  frontend/src/metabase/components/ListItem/ListItem.jsx
  frontend/src/metabase/components/ListItem/ListItem.unit.spec.js
  frontend/src/metabase/reference/databases/DatabaseList.jsx
  frontend/src/metabase/reference/databases/TableList.jsx
  frontend/src/metabase/reference/databases/TableQuestions.jsx
  frontend/src/metabase/reference/metrics/MetricList.jsx
  frontend/src/metabase/reference/metrics/MetricQuestions.jsx
  frontend/src/metabase/reference/segments/SegmentList.jsx
  frontend/src/metabase/reference/segments/SegmentQuestions.jsx
Labels: Type:Tech Debt, Organization/Data Reference

#30639 Improve FE sources glob pattern to exclude unit tests
  .github/file-paths.yaml
Labels: .CI & Tests, backport

#30694 Cleanup `Schema` entity - fix types, get rid off Base
  frontend/src/metabase-lib/metadata/Schema.ts
  frontend/src/metabase-lib/metadata/Schema.unit.spec.ts
  frontend/src/metabase/admin/permissions/utils/data-entity-id.ts
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDatabaseSchemaPicker/DataSelectorDatabaseSchemaPicker.tsx
  frontend/src/metabase/selectors/metadata.ts
Labels: .Team/QueryBuilder :abacus:

#30656 Add bucketing to sample database mock preset
  frontend/src/metabase-types/api/field.ts
  frontend/src/metabase-types/api/mocks/presets/sample_database.ts
  frontend/src/metabase-types/api/table.ts
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30662 Prevent fields hiding joined fields
  src/metabase/lib/join.cljc
  src/metabase/lib/stage.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/metadata/jvm_test.clj
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/stage_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30395 Support expression options and fields only case and coalasce exprs
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/convert.cljc
  src/metabase/lib/schema/expression/conditional.cljc
  test/metabase/lib/convert_test.cljc
  test/metabase/lib/schema/expression/conditional_test.cljc
  test/metabase/query_processor_test/test_mlv2.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30660 Fix syntax error in slack notifications script
  .github/workflows/rerun-workflows.yml
Labels: .Team/Viz :bar_chart:

#30299 [MLv2] Add `metabase.lib.binning` and add binning support for fields
  shared/src/metabase/shared/util/i18n.cljs
  shared/test/metabase/shared/i18n_test.cljc
  src/metabase/api/table.clj
  src/metabase/lib/binning.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/options.cljc
  src/metabase/lib/schema/binning.cljc
  src/metabase/util.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/util_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30566 Return dashboard in GET "/most_recently_viewed_dashboard" response
  src/metabase/api/activity.clj
  test/metabase/api/activity_test.clj
Labels: .Team/Backend :pancakes:

#30733 docs - update data sandboxes
  docs/README.md
  docs/permissions/data-sandbox-examples.md
  docs/permissions/data-sandboxes.md
Labels: Type:Documentation, backport

#30738 docs - update sandboxes some more
  docs/permissions/data-sandboxes.md
Labels: Type:Documentation, backport

#30734 🍒 Manual Backport: [CI] Fix syntax error in slack notifications script (#30660)
  .github/workflows/rerun-workflows.yml
Labels: was-backported

#30305 Add app db as audit db on app startup
  enterprise/backend/src/metabase_enterprise/audit_db.clj
  enterprise/backend/test/metabase_enterprise/audit_db_test.clj
  resources/migrations/000_migrations.yaml
  src/metabase/api/database.clj
  src/metabase/core.clj
  src/metabase/db/env.clj
  src/metabase/driver/sql_jdbc/connection.clj
  src/metabase/query_processor/store.clj
  test/metabase/api/table_test.clj
Labels: .Team/FunPolice :police_officer:

#30742 docs - pro links
  docs/README.md
  docs/paid-features/start.md
Labels: Type:Documentation, backport

#30737 Hides malli's instrumentation messages
  dev/src/dev.clj
  src/metabase/util/malli.cljc
Labels: backport, .Team/Backend :pancakes:

#30701 Use database features from API to determine whether a DB supports schema
  frontend/src/metabase-types/api/database.ts
  frontend/src/metabase/admin/settings/components/UploadSettings/UploadSettings.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/UploadSettings/utils.ts
  frontend/src/metabase/admin/settings/components/UploadSettings/utils.unit.spec.ts
Labels: .Team/Viz :bar_chart:

#30611 change collections menu tooltip placement to bottom
  frontend/src/metabase/collections/components/CollectionHeader/CollectionBookmark.tsx
  frontend/src/metabase/collections/components/CollectionHeader/CollectionMenu.tsx
  frontend/src/metabase/collections/components/CollectionHeader/CollectionTimeline.tsx
  frontend/src/metabase/collections/components/CollectionHeader/CollectionUpload.tsx
  frontend/src/metabase/components/EntityMenu/EntityMenu.jsx
  frontend/src/metabase/components/EntityMenuTrigger/EntityMenuTrigger.tsx
  frontend/src/metabase/core/components/BookmarkToggle/BookmarkToggle.tsx
Labels: .Team/Viz :bar_chart:

#30698 Implement MLv1 compatible display names for bucketed fields
  e2e/test/scenarios/binning/binning-reproductions.cy.spec.js
  src/metabase/lib/field.cljc
  test/metabase/lib/breakout_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/temporal_bucket_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30739 Cleanup Metric metabase-lib type
  frontend/src/metabase-lib/metadata/Metric.ts
  frontend/src/metabase-types/api/metric.ts
  frontend/src/metabase/admin/datamodel/components/MetricItem.jsx
  frontend/src/metabase/admin/datamodel/containers/MetricListApp.jsx
  frontend/src/metabase/common/hooks/index.ts
  frontend/src/metabase/common/hooks/use-database-id-field-list-query/use-database-id-field-list-query.ts
  frontend/src/metabase/common/hooks/use-database-id-field-list-query/use-database-id-field-list-query.unit.spec.tsx
  frontend/src/metabase/common/hooks/use-metric-list-query/index.ts
  frontend/src/metabase/common/hooks/use-metric-list-query/use-metric-list-query.ts
  frontend/src/metabase/common/hooks/use-metric-list-query/use-metric-list-query.unit.spec.tsx
  frontend/src/metabase/common/hooks/use-metric-query/index.ts
  frontend/src/metabase/common/hooks/use-metric-query/use-metric-query.ts
  frontend/src/metabase/common/hooks/use-metric-query/use-metric-query.unit.spec.tsx
  frontend/test/__support__/server-mocks/database.ts
  frontend/test/__support__/server-mocks/index.ts
  frontend/test/__support__/server-mocks/metric.ts
Labels: .Team/QueryBuilder :abacus:

#30753 Update broken link to google standard sql
  docs/databases/connections/bigquery.md
Labels: .Team/QueryBuilder :abacus:

#30728 Cleanup Segment metabase-lib type
  frontend/src/metabase-lib/metadata/Metric.ts
  frontend/src/metabase-lib/metadata/Schema.ts
  frontend/src/metabase-lib/metadata/Segment.ts
  frontend/src/metabase-lib/metadata/Segment.unit.spec.ts
  frontend/src/metabase-types/api/metric.ts
  frontend/src/metabase-types/api/mocks/segment.ts
  frontend/src/metabase-types/api/segment.ts
  frontend/src/metabase/admin/datamodel/components/MetricItem.jsx
  frontend/src/metabase/admin/datamodel/components/SegmentItem.jsx
  frontend/src/metabase/admin/datamodel/containers/MetricListApp.jsx
  frontend/src/metabase/admin/datamodel/containers/SegmentListApp.jsx
  frontend/src/metabase/admin/permissions/utils/graph/data-permissions.ts
  frontend/src/metabase/common/hooks/index.ts
  frontend/src/metabase/common/hooks/use-database-id-field-list-query/use-database-id-field-list-query.ts
  frontend/src/metabase/common/hooks/use-database-id-field-list-query/use-database-id-field-list-query.unit.spec.tsx
  frontend/src/metabase/common/hooks/use-entity-list-query/use-entity-list-query.ts
  frontend/src/metabase/common/hooks/use-entity-query/use-entity-query.ts
  frontend/src/metabase/common/hooks/use-metric-list-query/index.ts
  frontend/src/metabase/common/hooks/use-metric-list-query/use-metric-list-query.ts
  frontend/src/metabase/common/hooks/use-metric-list-query/use-metric-list-query.unit.spec.tsx
  frontend/src/metabase/common/hooks/use-metric-query/index.ts
  frontend/src/metabase/common/hooks/use-metric-query/use-metric-query.ts
  frontend/src/metabase/common/hooks/use-metric-query/use-metric-query.unit.spec.tsx
  frontend/src/metabase/common/hooks/use-segment-list-query/index.ts
  frontend/src/metabase/common/hooks/use-segment-list-query/use-segment-list-query.ts
  frontend/src/metabase/common/hooks/use-segment-list-query/use-segment-list-query.unit.spec.tsx
  frontend/src/metabase/common/hooks/use-segment-query/index.ts
  frontend/src/metabase/common/hooks/use-segment-query/use-segment-query.ts
  frontend/src/metabase/common/hooks/use-segment-query/use-segment-query.unit.spec.tsx
  frontend/src/metabase/query_builder/components/dataref/SchemaPane.tsx
  frontend/test/__support__/server-mocks/database.ts
  frontend/test/__support__/server-mocks/index.ts
  frontend/test/__support__/server-mocks/metric.ts
  frontend/test/__support__/server-mocks/segment.ts
Labels: .Team/QueryBuilder :abacus:

#30752 Exclude yarn >=2 from engines in package.json
  package.json
Labels: .Team/QueryBuilder :abacus:

#30729 Use questions instead of cards in entity loaders
  frontend/src/metabase-lib/parameters/utils/click-behavior.js
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase/actions/containers/ActionCreator/ActionCreator.tsx
  frontend/src/metabase/actions/containers/ActionCreatorModal/ActionCreatorModal.tsx
  frontend/src/metabase/collections/components/PinnedItemOverview/PinnedItemOverview.tsx
  frontend/src/metabase/collections/components/PinnedQuestionCard/PinnedQuestionCard.tsx
  frontend/src/metabase/collections/components/PinnedQuestionCard/PinnedQuestionLoader.tsx
  frontend/src/metabase/collections/containers/CollectionContent.jsx
  frontend/src/metabase/common/hooks/index.ts
  frontend/src/metabase/common/hooks/use-question-list-query/index.ts
  frontend/src/metabase/common/hooks/use-question-list-query/use-question-list-query.ts
  frontend/src/metabase/common/hooks/use-question-list-query/use-question-list-query.unit.spec.tsx
  frontend/src/metabase/common/hooks/use-question-query/index.ts
  frontend/src/metabase/common/hooks/use-question-query/use-question-query.ts
  frontend/src/metabase/common/hooks/use-question-query/use-question-query.unit.spec.tsx
  frontend/src/metabase/containers/SavedQuestionLoader.jsx
  frontend/src/metabase/dashboard/actions/cards.js
  frontend/src/metabase/dashboard/actions/metadata.js
  frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.jsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/LinkOptions/LinkedEntityPicker.tsx
  frontend/src/metabase/dashboard/components/ClickMappings.jsx
  frontend/src/metabase/dashboard/hoc/WithVizSettingsData.js
  frontend/src/metabase/entities/questions.js
  frontend/src/metabase/lib/card.js
  frontend/src/metabase/lib/entities.js
  frontend/src/metabase/metabot/components/MetabotWidget/MetabotWidget.tsx
  frontend/src/metabase/metabot/containers/ModelMetabotApp/ModelMetabotApp.tsx
  frontend/src/metabase/models/components/ModelDetailPage/ModelUsageDetails/ModelUsageDetails.tsx
  frontend/src/metabase/models/containers/ModelDetailPage/ModelDetailPage.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbar.tsx
  frontend/src/metabase/nav/containers/MainNavbar/getSelectedItems.ts
  frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceCardModal.tsx
  frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceTypeModal.tsx
  frontend/src/metabase/query_builder/components/dataref/QuestionPane/QuestionPane.tsx
  frontend/src/metabase/query_builder/components/notebook/Notebook.tsx
  frontend/src/metabase/query_builder/components/view/QuestionDataSource.jsx
  frontend/test/metabase/lib/click-behavior.unit.spec.js
Labels: .Team/QueryBuilder :abacus:

#30757 [CI, E2E] Fix revision history flake
  e2e/test/scenarios/collections/revision-history.cy.spec.js
Labels: .CI & Tests, backport, flaky-test-fix

#30747 Keep original join-aliases in expected columns
  src/metabase/query_processor.clj
  test/metabase/query_processor/util/add_alias_info_test.clj
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#30748 update team.json
  .github/team.json
  .github/workflows/auto-assign.yml
Labels: .Team/PixelPolice :police_officer:

#30754 Fix metabase-lib/metadata/Database type
  frontend/src/metabase-lib/actions/utils.unit.spec.ts
  frontend/src/metabase-lib/metadata/Database.ts
  frontend/src/metabase-lib/metadata/Database.unit.spec.ts
  frontend/src/metabase-lib/parameters/utils/targets.unit.spec.ts
  frontend/src/metabase-lib/queries/utils/native-query-table.ts
  frontend/src/metabase/admin/databases/components/DatabaseEditApp/Sidebar/Sidebar.unit.spec.tsx
  frontend/src/metabase/admin/permissions/selectors/confirmations.ts
  frontend/src/metabase/metabot/components/Metabot/Metabot.unit.spec.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDatabaseSchemaPicker/DataSelectorDatabaseSchemaPicker.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDatabaseSchemaPicker/DataSelectorDatabaseSchemaPicker.unit.spec.js
  frontend/src/metabase/query_builder/components/dataref/DatabaseSchemasPane.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorHelpText.stories.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorHelpText.unit.spec.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/helper-text-strings.unit.spec.ts
  frontend/src/metabase/selectors/metadata.ts
  frontend/test/__support__/sample_database_fixture.ts
  frontend/test/metabase-lib/lib/queries/StructuredQuery-clean.unit.spec.js
Labels: .Team/QuestionMasters

#30761 Fix metabase-lib/metadata/Table type
  frontend/src/metabase-lib/metadata/Metric.ts
  frontend/src/metabase-lib/metadata/Table.ts
  frontend/src/metabase-lib/metadata/Table.unit.spec.ts
  frontend/src/metabase-lib/queries/utils/native-query-table.unit.spec.ts
  frontend/src/metabase-lib/queries/utils/nested-card-query-table.ts
  frontend/src/metabase-lib/queries/utils/structured-query-table.ts
  frontend/src/metabase-lib/queries/utils/structured-query-table.unit.spec.ts
  frontend/src/metabase-lib/queries/utils/virtual-table.ts
  frontend/src/metabase-lib/queries/utils/virtual-table.unit.spec.ts
  frontend/src/metabase-types/api/field.ts
  frontend/src/metabase-types/api/foreign-key.ts
  frontend/src/metabase-types/api/index.ts
  frontend/src/metabase-types/api/mocks/table.ts
  frontend/src/metabase-types/api/table.ts
  frontend/src/metabase/components/MetadataInfo/TableInfo/ColumnCount.unit.spec.tsx
  frontend/src/metabase/components/MetadataInfo/TableInfo/ConnectedTables.unit.spec.tsx
  frontend/src/metabase/components/MetadataInfo/TableInfo/TableInfo.unit.spec.tsx
  frontend/src/metabase/components/MetadataInfo/TableLabel/TableLabel.unit.spec.tsx
  frontend/src/metabase/query_builder/actions/core/updateQuestion.unit.spec.ts
  frontend/src/metabase/query_builder/components/dataref/TablePane.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.unit.spec.tsx
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/utils.unit.spec.ts
  frontend/src/metabase/query_builder/components/notebook/steps/ExpressionStep.unit.spec.tsx
  frontend/src/metabase/selectors/metadata.ts
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectRelationships.tsx
  frontend/test/__support__/sample_database_fixture.ts
Labels: visual, .Team/QuestionMasters

#30745 Migrate default temporal bucket logic from Field.ts to ML
  shared/src/metabase/shared/util/internal/time.clj
  shared/src/metabase/shared/util/internal/time.cljs
  shared/src/metabase/shared/util/time.cljc
  src/metabase/lib/field.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/metadata/jvm_test.clj
  test/metabase/lib/temporal_bucket_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30653 fix selecting pinned items in collections
  e2e/support/helpers/e2e-collection-helpers.js
  e2e/test/scenarios/collections/collection-pinned-overview.cy.spec.js
  e2e/test/scenarios/collections/collections.cy.spec.js
  frontend/src/metabase/collections/containers/CollectionContent.jsx
Labels: .Team/PixelPolice :police_officer:

#30774 🍒 fix selecting pinned items in collections (#30653)
  e2e/support/helpers/e2e-collection-helpers.js
  e2e/test/scenarios/collections/collection-pinned-overview.cy.spec.js
  e2e/test/scenarios/collections/collections.cy.spec.js
  frontend/src/metabase/collections/components/BulkActions.jsx
  frontend/src/metabase/collections/containers/CollectionContent.jsx
Labels: .Team/PixelPolice :police_officer:

#30249 Serdes for dashboardtab
  enterprise/backend/src/metabase_enterprise/serialization/v2/models.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj
  src/metabase/models/dashboard.clj
  src/metabase/models/dashboard_card.clj
  src/metabase/models/dashboard_tab.clj
  src/metabase/models/serialization.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:, .Team/QuestionMasters

#30755 Repro #30743: Sorting on the breakout column in joined questions crashes
  e2e/test/scenarios/joins/reproductions/30743-sort-on-breakout-column-crashes.cy.spec.js
Labels: .CI & Tests, support/Repro

#30781 Upgrade `xlsx`
  package.json
  yarn.lock
Labels: backport

#30749 Remove millisecond unit from datetimeDiff docs
  docs/questions/query-builder/expressions/datetimediff.md
Labels: .Team/QuestionMasters

#30581 Preselect most recently viewed dashboard in DashboardPicker
  docs/developers-guide/frontend.md
  frontend/src/metabase/common/hooks/index.ts
  frontend/src/metabase/common/hooks/use-collection-query/index.ts
  frontend/src/metabase/common/hooks/use-collection-query/use-collection-query.ts
  frontend/src/metabase/common/hooks/use-collection-query/use-collection-query.unit.spec.tsx
  frontend/src/metabase/common/hooks/use-most-recently-viewed-dashboard/index.ts
  frontend/src/metabase/common/hooks/use-most-recently-viewed-dashboard/use-most-recently-viewed-dashboard.ts
  frontend/src/metabase/containers/AddToDashSelectDashModal.tsx
  frontend/src/metabase/containers/AddToDashSelectDashModal.unit.spec.tsx
  frontend/src/metabase/containers/DashboardPicker.tsx
  frontend/src/metabase/containers/ItemPicker/ItemPicker.tsx
  frontend/src/metabase/containers/ItemPicker/ItemPicker.unit.spec.js
  frontend/src/metabase/nav/components/CollectionBreadcrumbs/CollectionBreadcrumbs.tsx
  frontend/src/metabase/services.js
  frontend/test/__support__/server-mocks/activity.ts
  frontend/test/__support__/server-mocks/collection.ts
Labels: .Team/QuestionMasters

#30786 🍒 Repro #30743: Sorting on the breakout column in joined questions crashes
  e2e/test/scenarios/joins/reproductions/30743-sort-on-breakout-column-crashes.cy.spec.js
Labels: was-backported

#30768 Fix type warning in loop
  src/metabase/lib/util.cljc
Labels: .Team/QuestionMasters

#30769 Add normalized data mock helpers
  frontend/src/metabase-types/api/field.ts
  frontend/src/metabase-types/api/mocks/field.ts
  frontend/src/metabase-types/api/mocks/index.ts
  frontend/src/metabase-types/api/mocks/schema.ts
  frontend/src/metabase-types/api/table.ts
  frontend/src/metabase-types/store/mocks/entities.ts
  frontend/src/metabase-types/store/mocks/index.ts
  frontend/src/metabase-types/store/mocks/state.ts
  frontend/src/metabase/common/hooks/index.ts
  frontend/src/metabase/common/hooks/use-table-metadata-query/index.ts
  frontend/src/metabase/common/hooks/use-table-metadata-query/use-table-metadata-query.ts
  frontend/src/metabase/common/hooks/use-table-metadata-query/use-table-metadata-query.unit.spec.tsx
  frontend/test/__support__/store.ts
Labels: .Team/QuestionMasters

#30464 fix default card position on tabbed dashboards
  frontend/src/metabase/dashboard/actions/cards.js
Labels: .Team/PixelPolice :police_officer:

#30540 fix width for tabs with long names
  frontend/src/metabase/core/components/TabButton/TabButton.styled.tsx
  frontend/src/metabase/core/components/TabButton/TabButton.tsx
Labels: .Team/PixelPolice :police_officer:

#30497 allow undoing tab deletion
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/dashboard/tabs.cy.spec.js
  frontend/src/metabase-types/store/dashboard.ts
  frontend/src/metabase-types/store/mocks/dashboard.ts
  frontend/src/metabase/dashboard/actions/save.js
  frontend/src/metabase/dashboard/actions/tabs.ts
  frontend/src/metabase/dashboard/components/DashboardSidebars.jsx
  frontend/src/metabase/dashboard/components/DashboardTabs/useDashboardTabs.ts
  frontend/src/metabase/dashboard/constants.ts
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.jsx
  frontend/src/metabase/dashboard/reducers.js
  frontend/src/metabase/dashboard/reducers.unit.spec.js
  frontend/src/metabase/dashboard/selectors/index.ts
  frontend/src/metabase/dashboard/selectors/selectors.js
  frontend/src/metabase/dashboard/selectors/selectors_typed.ts
Labels: .Team/PixelPolice :police_officer:

#30756 [CSV Upload] Speed up Postgres inserts
  src/metabase/driver/postgres.clj
  src/metabase/upload.clj
  test/metabase/upload_test.clj
Labels: .Team/QuestionMasters

#30812 Adds encoding to field props for database inputs
  frontend/src/metabase/databases/components/DatabaseDetailField/DatabaseDetailField.tsx
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#30815 Remove `withSampleDatabase` from `renderWithProviders`
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.unit.spec.js
  frontend/test/__support__/ui.tsx
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30808 Fix metabase-lib/metadata/Metadata type
  frontend/src/metabase-lib/metadata/Field.ts
  frontend/src/metabase-lib/metadata/Metadata.ts
  frontend/src/metabase-lib/metadata/Metadata.unit.spec.ts
  frontend/src/metabase-lib/metadata/utils/fields.ts
  frontend/src/metabase-types/api/mocks/schema.ts
  frontend/src/metabase-types/api/schema.ts
  frontend/src/metabase/admin/permissions/selectors/data-permissions/data-sidebar.ts
  frontend/src/metabase/admin/permissions/utils/metadata.ts
  frontend/src/metabase/selectors/metadata.ts
Labels: .Team/42 :milky_way:

#30741 Includes data model with selective serialization, adds --no-settings
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/models.clj
  enterprise/backend/test/metabase_enterprise/serialization/api/serialize_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/extract_test.clj
  src/metabase/cmd.clj
  test/metabase/cmd_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30811 Cleanup server-mocks
  frontend/src/metabase/containers/AddToDashSelectDashModal.unit.spec.tsx
  frontend/src/metabase/containers/ItemPicker/ItemPicker.tsx
  frontend/src/metabase/containers/ItemPicker/ItemPicker.unit.spec.js
  frontend/src/metabase/containers/ItemPicker/ItemPickerView.tsx
  frontend/test/__support__/server-mocks/collection.ts
Labels: .Team/42 :milky_way:

#30827 Migrate QuestionDataSource tests from the sample db fixture
  frontend/src/metabase/query_builder/components/view/QuestionDataSource.unit.spec.js
Labels: .Team/42 :milky_way:

#30829 Migrate order_by test from the sample db fixture
  frontend/src/metabase-lib/order_by.unit.spec.ts
Labels: .Team/42 :milky_way:

#30828 Remove `metabase-lib/mocks`
  frontend/src/metabase-lib/mocks.ts
  frontend/src/metabase-types/api/mocks/card.ts
  frontend/src/metabase-types/api/mocks/presets/sample_cards.ts
  frontend/src/metabase-types/api/query.ts
  frontend/src/metabase/actions/containers/ActionCreator/ActionContext/utils.ts
  frontend/src/metabase/models/containers/ModelDetailPage/ModelDetailPage.unit.spec.tsx
  frontend/src/metabase/modes/components/drill/NativeDrillFallback/NativeDrillFallback.unit.spec.tsx
  frontend/src/metabase/query_builder/actions/core/initializeQB.unit.spec.ts
  frontend/src/metabase/query_builder/actions/core/updateQuestion.unit.spec.ts
  frontend/src/metabase/query_builder/components/notebook/steps/BreakoutStep/BreakoutStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/test-utils.ts
  frontend/src/metabase/query_builder/components/view/QuestionRowCount/QuestionRowCount.unit.spec.tsx
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30835 Remove sample database fixture
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.unit.spec.js
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/suggest.unit.spec.ts
  frontend/test/__support__/sample_database_fixture.json
  frontend/test/__support__/sample_database_fixture.ts
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30685 Actions to toucan2
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  src/metabase/models/action.clj
  test/metabase/models_test.clj
Labels: .Team/42 :milky_way:

#30689 Dimension and FieldValues to toucan2
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  src/metabase/models/dimension.clj
  src/metabase/models/field_values.clj
  src/metabase/models/interface.clj
  src/metabase/models/params.clj
  test/metabase/test/util.clj
Labels: .Team/42 :milky_way:

#30688 Timeline and bookmark to toucan2
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  src/metabase/models/bookmark.clj
  src/metabase/models/timeline.clj
  src/metabase/models/timeline_event.clj
Labels: .Team/42 :milky_way:

#30787 Migrate field refs in result_metadata from legacy format
  resources/migrations/000_migrations.yaml
  src/metabase/db/custom_migrations.clj
  test/metabase/db/custom_migrations_test.clj
Labels: .Team/42 :milky_way:

#30692 ModerationReview, Revision, Secret, Session, Setting to toucan2
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  src/metabase/models/interface.clj
  src/metabase/models/moderation_review.clj
  src/metabase/models/revision.clj
  src/metabase/models/secret.clj
  src/metabase/models/session.clj
  src/metabase/models/setting.clj
  test/metabase/models/revision_test.clj
Labels: .Team/42 :milky_way:

#30775 [MLv2] remove replace aggregation and expressions
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/dev.cljc
  src/metabase/lib/expression.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/order_by.cljc
  src/metabase/lib/remove_replace.cljc
  src/metabase/lib/stage.cljc
  src/metabase/lib/util.cljc
  src/metabase/util/malli.cljc
  test/metabase/lib/aggregation_test.cljc
  test/metabase/lib/expression_test.cljc
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/remove_replace_test.cljc
  test/metabase/lib/stage_test.cljc
Labels: .Backend, .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30846 [MLv2] Add JS wrappers for temporal bucketing. Rework `temporal-bucket`.
  src/metabase/lib/core.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/temporal_bucket.cljc
  test/metabase/lib/field_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30850 Unskip repro for #30743; it was fixed by #30755
  e2e/test/scenarios/joins/reproductions/30743-sort-on-breakout-column-crashes.cy.spec.js
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30465 allow renaming tabs by double clicking name
  frontend/src/metabase/core/components/TabButton/TabButton.styled.tsx
  frontend/src/metabase/core/components/TabButton/TabButton.tsx
  frontend/src/metabase/core/components/TabButton/TabButton.unit.spec.tsx
  frontend/src/metabase/core/components/TabButton/TabButtonMenu.tsx
  frontend/src/metabase/core/components/TabButton/index.ts
  frontend/src/metabase/core/components/TabRow/TabRow.stories.tsx
  frontend/src/metabase/core/components/TabRow/TabRow.styled.tsx
  frontend/src/metabase/core/components/TabRow/TabRow.tsx
  frontend/src/metabase/core/components/TabRow/TabRow.unit.spec.tsx
  frontend/src/metabase/core/components/TabRow/index.ts
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.styled.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.unit.spec.tsx
  frontend/src/metabase/models/components/ModelDetailPage/ModelDetailPage.styled.tsx
Labels: .Team/PixelPolice :police_officer:

#30824 Fixes SQL formatting of BigQuery native queries
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj
  src/metabase/db/query.clj
Labels: Database/BigQuery, backport, .Team/QueryProcessor :hammer_and_wrench:

#30861 🤞 reduce revision history flakes 🤞
  e2e/test/scenarios/collections/revision-history.cy.spec.js
Labels: backport, flaky-test-fix, .Team/PixelPolice :police_officer:

#30855 add Shaun to team.json
  .github/team.json
Labels: .Team/PixelPolice :police_officer:

#30632 Warn users before they lose new changes
  e2e/support/helpers/e2e-dashboard-helpers.js
  frontend/src/metabase-types/api/dataset.ts
  frontend/src/metabase-types/api/mocks/dataset.ts
  frontend/src/metabase-types/api/mocks/group.ts
  frontend/src/metabase-types/api/mocks/permissions.ts
  frontend/src/metabase-types/api/permissions.ts
  frontend/src/metabase-types/store/admin.ts
  frontend/src/metabase/actions/containers/ActionCreator/ActionContext/ActionContext.ts
  frontend/src/metabase/actions/containers/ActionCreator/ActionContext/ImplicitActionContextProvider/ImplicitActionContextProvider.tsx
  frontend/src/metabase/actions/containers/ActionCreator/ActionContext/QueryActionContextProvider/QueryActionContextProvider.tsx
  frontend/src/metabase/actions/containers/ActionCreator/ActionCreator.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FormCreator.styled.tsx
  frontend/src/metabase/actions/containers/ActionCreator/tests/ActionCreator-Common.unit.spec.tsx
  frontend/src/metabase/admin/databases/containers/DatabaseEditApp.jsx
  frontend/src/metabase/admin/databases/containers/DatabaseEditApp.tsx
  frontend/src/metabase/admin/databases/containers/DatabaseEditApp.unit.spec.js
  frontend/src/metabase/admin/databases/database.js
  frontend/src/metabase/admin/datamodel/components/FormInput/FormInput.tsx
  frontend/src/metabase/admin/datamodel/components/MetricForm/MetricForm.tsx
  frontend/src/metabase/admin/datamodel/components/MetricForm/MetricForm.unit.spec.tsx
  frontend/src/metabase/admin/datamodel/components/PartialQueryBuilder.jsx
  frontend/src/metabase/admin/datamodel/components/SegmentForm/SegmentForm.tsx
  frontend/src/metabase/admin/datamodel/components/SegmentForm/SegmentForm.unit.spec.tsx
  frontend/src/metabase/admin/permissions/components/PermissionsPageLayout/PermissionsPageLayout.tsx
  frontend/src/metabase/admin/permissions/components/ToolbarUpsell/ToolbarUpsell.tsx
  frontend/src/metabase/admin/permissions/pages/DataPermissionsPage/DataPermissionsPage.tsx
  frontend/src/metabase/admin/permissions/test/DatabasesPermissionsPage/DatabasesPermissionsPage.unit.spec.tsx
  frontend/src/metabase/admin/permissions/test/GroupsPermissionsPage/GroupsPermissionsPage.unit.spec.tsx
  frontend/src/metabase/containers/AddToDashSelectDashModal.unit.spec.tsx
  frontend/src/metabase/containers/ItemPicker/ItemPicker.unit.spec.js
  frontend/src/metabase/dashboard/actions/parameters.js
  frontend/src/metabase/dashboard/containers/DashboardApp.unit.spec.jsx
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.jsx
  frontend/src/metabase/dashboard/containers/DashboardHeader.jsx
  frontend/src/metabase/dashboard/containers/selectors.jsx
  frontend/src/metabase/databases/components/DatabaseForm/DatabaseForm.tsx
  frontend/src/metabase/hooks/use-before-unload/index.ts
  frontend/src/metabase/hooks/use-before-unload/use-before-unload.ts
  frontend/src/metabase/query_builder/components/__mocks__/NativeQueryEditor.jsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.jsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ChartCaption.unit.spec.tsx
  frontend/test/__support__/server-mocks/collection.ts
  frontend/test/__support__/server-mocks/group.ts
  frontend/test/__support__/server-mocks/permissions.ts
Labels: visual

#30832 Properly hydrate foreign keys for a table
  frontend/src/metabase-lib/metadata/ForeignKey.ts
  frontend/src/metabase-lib/metadata/Table.ts
  frontend/src/metabase-lib/metadata/Table.unit.spec.ts
  frontend/src/metabase-lib/queries/utils/structured-query-table.unit.spec.ts
  frontend/src/metabase-lib/queries/utils/virtual-table.ts
  frontend/src/metabase-lib/queries/utils/virtual-table.unit.spec.ts
  frontend/src/metabase-types/api/mocks/schema.ts
  frontend/src/metabase-types/api/mocks/table.ts
  frontend/src/metabase-types/api/schema.ts
  frontend/src/metabase-types/api/table.ts
  frontend/src/metabase/components/MetadataInfo/TableInfo/ConnectedTables.unit.spec.tsx
  frontend/src/metabase/components/MetadataInfo/TableInfo/TableInfo.tsx
  frontend/src/metabase/components/MetadataInfo/TableInfo/TableInfo.unit.spec.tsx
  frontend/src/metabase/query_builder/components/dataref/TableInfoLoader.tsx
  frontend/src/metabase/query_builder/selectors.js
  frontend/src/metabase/schema.js
  frontend/src/metabase/selectors/metadata.ts
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectRelationships.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectRelationships.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/types.ts
  frontend/test/__support__/testForeignKeys.js
Labels: visual, .Team/42 :milky_way:

#30478 Subscription for dashboard tabs
  src/metabase/email/messages.clj
  src/metabase/email/pulse.mustache
  src/metabase/models/dashboard.clj
  src/metabase/models/dashboard_tab.clj
  src/metabase/models/pulse.clj
  src/metabase/pulse.clj
  test/metabase/dashboard_subscription_test.clj
  test/metabase/email/messages_test.clj
  test/metabase/models/dashboard_tab_test.clj
  test/metabase/pulse/test_util.clj
Labels: .Team/42 :milky_way:

#30871 Fix sample database not appearing in Database Browser without page refresh
  e2e/test/scenarios/admin/databases/default-sample-database.cy.spec.js
  frontend/src/metabase/admin/databases/components/DatabaseList/DatabaseList.jsx
  frontend/src/metabase/admin/databases/database.js
  frontend/src/metabase/browse/containers/DatabaseBrowser.jsx
  frontend/src/metabase/nav/components/AdminNavbar/AdminNavbar.tsx
Labels: backport, .Team/42 :milky_way:

#30875 Use sentence case for temporal bucket names
  e2e/test/scenarios/binning/binning-options.cy.spec.js
  e2e/test/scenarios/binning/binning-reproductions.cy.spec.js
  e2e/test/scenarios/binning/correctness/shared/constants.js
  e2e/test/scenarios/binning/correctness/time-series.cy.spec.js
  e2e/test/scenarios/custom-column/custom-column.cy.spec.js
  e2e/test/scenarios/question/summarization.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/16918.cy.spec.js
  frontend/src/metabase-lib/Dimension.ts
  frontend/src/metabase-types/api/mocks/presets/sample_database.ts
  src/metabase/api/table.clj
  src/metabase/pulse/render/datetime.clj
Labels: visual, .Team/QueryProcessor :hammer_and_wrench:

#30879 Handle rubbish in mongodb versionArray
  modules/drivers/mongo/src/metabase/driver/mongo.clj
  modules/drivers/mongo/test/metabase/driver/mongo_test.clj
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#30830 Exclude :starburst from two-of-the-same-aggregations-test
  test/metabase/query_processor_test/nested_queries_test.clj
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#30630 hide dashcard when empty setting
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  frontend/src/metabase-types/api/dataset.ts
  frontend/src/metabase-types/api/mocks/series.ts
  frontend/src/metabase-types/api/query.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.jsx
  frontend/src/metabase/dashboard/utils.js
  frontend/src/metabase/dashboard/utils.ts
  frontend/src/metabase/dashboard/utils.unit.spec.js
  frontend/src/metabase/dashboard/utils.unit.spec.ts
  frontend/src/metabase/visualizations/components/ChartCaption.unit.spec.tsx
  frontend/src/metabase/visualizations/lib/settings/visualization.js
Labels: visual, .Team/PixelPolice :police_officer:

#30884 Add aggregation operator specific properties to display-info schema
  src/metabase/lib/metadata/calculation.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30784 Stack cards vertically for dashboard with tabs on downgrade
  resources/migrations/000_migrations.yaml
  src/metabase/db/custom_migrations.clj
  test/metabase/db/custom_migrations_test.clj
Labels: .Team/42 :milky_way:

#30870 BE: Create and delete visualization_settings.fields for implicit actions as parameters change
  src/metabase/models/action.clj
  test/metabase/models/action_test.clj
Labels: .Team/42 :milky_way:
