Repository metabase/metabase, pull requests merged in 2023-04, with the labels that each got.

#29711 Metadata/refs overhaul. RIP `field_ref`
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/breakout.cljc
  src/metabase/lib/common.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/dev.cljc
  src/metabase/lib/expression.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/metadata.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/normalize.cljc
  src/metabase/lib/options.cljc
  src/metabase/lib/order_by.cljc
  src/metabase/lib/query.cljc
  src/metabase/lib/ref.cljc
  src/metabase/lib/schema/ref.cljc
  src/metabase/lib/stage.cljc
  src/metabase/lib/temporal_bucket.cljc
  src/metabase/lib/util.cljc
  test/metabase/lib/aggregation_test.cljc
  test/metabase/lib/dev_test.cljc
  test/metabase/lib/expression_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/filter_test.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/metadata_test.cljc
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/stage_test.cljc
  test/metabase/lib/test_metadata.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29737 MLv2: return expressions in default fields
  src/metabase/lib/dev.cljc
  src/metabase/lib/expression.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/metadata.cljc
  src/metabase/lib/stage.cljc
  src/metabase/lib/table.cljc
  test/metabase/lib/expression_test.cljc
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/stage_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29613 Adapt unique schema logic in CI from Snowflake to Redshift
  modules/drivers/redshift/test/metabase/driver/redshift_test.clj
  modules/drivers/redshift/test/metabase/test/data/redshift.clj
  modules/drivers/snowflake/test/metabase/test/data/snowflake.clj
  test/metabase/driver/sql/test_util/unique_prefix.clj
  test/metabase/driver/sql_jdbc/sync/describe_database_test.clj
Labels: backport, flaky-test-fix

#29738 Fix semantics of group mapping query
  src/metabase/integrations/common.clj
  test/metabase/integrations/common_test.clj
Labels: backport

#29755 Manual backport of #29738
  src/metabase/integrations/common.clj
  test/metabase/integrations/common_test.clj
Labels: was-backported

#29336 Added pretty? option to POST api/dataset/native route
  frontend/src/metabase/query_builder/components/view/PreviewQueryModal/PreviewQueryModal.tsx
  frontend/src/metabase/query_builder/selectors.js
  src/metabase/api/dataset.clj
  src/metabase/db/query.clj
  test/metabase/api/dataset_test.clj
  test/metabase/db/query_test.clj
  test_resources/metabase/db/mongodbquery.json
Labels: .Team/Backend :pancakes:

#29741 Manual backport persistent schema cache info table
  src/metabase/driver/ddl/interface.clj
  src/metabase/driver/mysql/ddl.clj
  src/metabase/driver/postgres/ddl.clj
  test/metabase/query_processor/persistence_test.clj
Labels: was-backported

#27505 Clean cache after branch closes
  .github/workflows/clean-cache.yml
Labels: .CI & Tests, backport

#29793 🍒 [CI] Bump the timeout for backend workflows (#29789)
  .github/workflows/backend.yml
  .github/workflows/drivers.yml
Labels: .CI & Tests, was-backported

#29696 [MLv2] Disallow duplicate UUIDs in a query
  src/metabase/lib/schema.cljc
  src/metabase/lib/schema/util.cljc
  test/metabase/lib/schema/expression/conditional_test.cljc
  test/metabase/lib/schema/util_test.cljc
  test/metabase/lib/schema_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29767 Fix metric & segment description logic when definitions don't have `:source-table`
  src/metabase/models/metric.clj
  src/metabase/models/segment.clj
  test/metabase/models/metric_test.clj
  test/metabase/models/segment_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29811 docs - add Albanian and Korean
  docs/configuring-metabase/localization.md
Labels: Type:Documentation, backport

#29536 docs - update list of included artifacts
  docs/installation-and-operation/serialization.md
Labels: Type:Documentation, backport

#29768 MLv2: add `:temporal-extract` to schema
  src/metabase/lib/schema/expression/temporal.cljc
  test/metabase/lib/expression_test.cljc
  test/metabase/lib/schema/expression/temporal_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29814 docs - update localization
  docs/configuring-metabase/localization.md
Labels: Type:Documentation, backport

#29773 MLv2 multimethods should use custom hierarchies
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/common.cljc
  src/metabase/lib/convert.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/equality.cljc
  src/metabase/lib/expression.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/hierarchy.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/js/metadata.cljs
  src/metabase/lib/metadata.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/metric.cljc
  src/metabase/lib/normalize.cljc
  src/metabase/lib/options.cljc
  src/metabase/lib/order_by.cljc
  src/metabase/lib/query.cljc
  src/metabase/lib/schema/aggregation.cljc
  src/metabase/lib/schema/expression.cljc
  src/metabase/lib/schema/expression/arithmetic.cljc
  src/metabase/lib/schema/expression/string.cljc
  src/metabase/lib/schema/expression/temporal.cljc
  src/metabase/lib/schema/order_by.cljc
  src/metabase/lib/schema/temporal_bucketing.cljc
  src/metabase/lib/segment.cljc
  src/metabase/lib/temporal_bucket.cljc
  test/metabase/lib/aggregation_test.cljc
  test/metabase/lib/convert_test.cljc
  test/metabase/lib/expression_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/metric_test.cljc
  test/metabase/lib/schema/expression/string_test.cljc
  test/metabase/lib/schema/literal/jvm_test.clj
  test/metabase/lib/test_metadata.cljc
  test/metabase/query_processor/middleware/annotate_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29804 🍒 Remove text coverage reporter from jest
  jest.unit.conf.json
Labels: was-backported

#29418 [CI] Optimize `admin > databases` E2E tests
  e2e/test/scenarios/admin/databases/actions.cy.spec.js
  e2e/test/scenarios/admin/databases/add-new-database.cy.spec.js
  e2e/test/scenarios/admin/databases/add.cy.spec.js
  e2e/test/scenarios/admin/databases/database-exceptions.cy.spec.js
  e2e/test/scenarios/admin/databases/default-sample-database.cy.spec.js
  e2e/test/scenarios/admin/databases/edit.cy.spec.js
  e2e/test/scenarios/admin/databases/helpers/e2e-database-helpers.js
  e2e/test/scenarios/admin/databases/list.cy.spec.js
  e2e/test/scenarios/admin/settings/spinner.cy.spec.js
Labels: .CI & Tests, backport

#29809 fix drill-through on legend for stacked charts
  e2e/test/scenarios/visualizations/bar_chart.cy.spec.js
  frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx
  frontend/src/metabase/visualizations/components/legend/Legend.jsx
  frontend/src/metabase/visualizations/components/legend/LegendItem.jsx
Labels: backport, .Team/Viz :bar_chart:

#29803 [MLv2] Add direction arg to orderByClause
  frontend/src/metabase-lib/order_by.ts
  frontend/src/metabase-lib/order_by.unit.spec.ts
  frontend/src/metabase-lib/query.ts
  src/metabase/lib/js.cljs
  src/metabase/lib/order_by.cljc
  test/metabase/lib/order_by_test.cljc
Labels: Type:Tech Debt, .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#29758 Fix not being able to open a card from a dashboard with sandboxing
  e2e/test/scenarios/dashboard/reproductions/29076-dashboard-card-drill-sandbox.cy.spec.js
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase/dashboard/actions/metadata.js
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/dashboard/hoc/WithVizSettingsData.js
  frontend/src/metabase/lib/click-behavior.js
  frontend/src/metabase/visualizations/hoc/WithVizSettingsData.js
Labels: support/Repro, backport, .Team/QueryBuilder :abacus:

#29838 🍒 Manual backport - fix drill-through on legend for stacked charts (#…
  e2e/test/scenarios/visualizations/bar_chart.cy.spec.js
  frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx
  frontend/src/metabase/visualizations/components/legend/Legend.jsx
  frontend/src/metabase/visualizations/components/legend/LegendItem.jsx
Labels: was-backported

#29754 Detect types for empty CSV files appropriately
  src/metabase/csv.clj
  test/metabase/csv_test.clj
Labels: .Team/Backend :pancakes:

#29845 docs - update notification permissions
  docs/configuring-metabase/settings.md
  docs/dashboards/subscriptions.md
  docs/permissions/notifications.md
  docs/questions/sharing/alerts.md
  docs/usage-and-performance-tools/audit.md
Labels: Type:Documentation, backport

#29860 Backport "Fix not being able to open a card from a dashboard with sandboxing"
  e2e/test/scenarios/dashboard/reproductions/29076-dashboard-card-drill-sandbox.cy.spec.js
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase/dashboard/actions/metadata.js
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/dashboard/hoc/WithVizSettingsData.js
  frontend/src/metabase/lib/click-behavior.js
  frontend/src/metabase/visualizations/hoc/WithVizSettingsData.js
Labels: was-backported

#29818 MLv2 display-info method
  frontend/src/metabase-lib/metadata.ts
  frontend/src/metabase-lib/order_by.ts
  frontend/src/metabase-lib/order_by.unit.spec.ts
  frontend/src/metabase-lib/types.ts
  src/metabase/lib/core.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/order_by.cljc
  src/metabase/lib/schema/common.cljc
  src/metabase/lib/table.cljc
  test/metabase/lib/order_by_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29874 orderable-columns should not return columns that are already in order-bys
  src/metabase/lib/expression.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/order_by.cljc
  src/metabase/lib/table.cljc
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/table_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29732 Fix missing JS metadata for Saved Question/Model source query
  frontend/src/metabase-lib/order_by.unit.spec.ts
  src/metabase/lib/card.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/js/metadata.cljs
  src/metabase/lib/metadata.cljc
  src/metabase/lib/schema/id.cljc
  src/metabase/lib/stage.cljc
  src/metabase/lib/table.cljc
  src/metabase/lib/util.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/stage_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#29824 MLv2: Column metadata include `:lib/source-column-alias` and `:lib/desired-column-alias`
  frontend/src/metabase-lib/order_by.unit.spec.ts
  frontend/test/jest-setup.js
  package.json
  src/metabase/driver/impl.clj
  src/metabase/lib/field.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/metadata.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/metadata/jvm.clj
  src/metabase/lib/query.cljc
  src/metabase/lib/stage.cljc
  src/metabase/lib/util.cljc
  test/metabase/api/metric_test.clj
  test/metabase/api/segment_test.clj
  test/metabase/driver/impl_test.clj
  test/metabase/lib/aggregation_test.cljc
  test/metabase/lib/expression_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/metadata/jvm_test.clj
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/stage_test.cljc
  test/metabase/lib/util_test.cljc
  test/metabase/models/metric_test.clj
  test/metabase/models/segment_test.clj
  test/metabase/query_processor_test/explicit_joins_test.clj
  yarn.lock
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29879 Fix can't join a table with another native question based on the same table
  e2e/test/scenarios/joins/reproductions/29795-native-query-join-question-misses-metadata.cy.spec.js
  frontend/src/metabase/query_builder/components/DimensionList.jsx
Labels: backport

#29844 Add metabot raw data toggle
  e2e/test/scenarios/onboarding/metabot.cy.spec.js
  frontend/src/metabase-types/store/metabot.ts
  frontend/src/metabase-types/store/mocks/metabot.ts
  frontend/src/metabase/metabot/actions.ts
  frontend/src/metabase/metabot/components/MetabotDisplayToggle/MetabotDisplayToggle.tsx
  frontend/src/metabase/metabot/components/MetabotDisplayToggle/index.ts
  frontend/src/metabase/metabot/components/MetabotFeedback/MetabotFeedback.styled.tsx
  frontend/src/metabase/metabot/components/MetabotFeedback/MetabotFeedback.tsx
  frontend/src/metabase/metabot/components/MetabotQueryBuilder/MetabotQueryBuilder.styled.tsx
  frontend/src/metabase/metabot/components/MetabotQueryBuilder/MetabotQueryBuilder.tsx
  frontend/src/metabase/metabot/components/MetabotVisualization/MetabotVisualization.tsx
  frontend/src/metabase/metabot/constants.ts
  frontend/src/metabase/metabot/reducers.js
  frontend/src/metabase/metabot/selectors.ts
  frontend/src/metabase/query_builder/components/view/QuestionDisplayToggle/QuestionDisplayToggle.styled.tsx
  frontend/src/metabase/query_builder/components/view/QuestionDisplayToggle/QuestionDisplayToggle.tsx
  frontend/src/metabase/query_builder/components/view/QuestionDisplayToggle/index.ts
  frontend/src/metabase/query_builder/components/view/ViewFooter.jsx
Labels: .Team/QueryBuilder :abacus:

#29883 Temporarily skip convert-timezone tests for redshift
  test/metabase/query_processor_test/date_time_zone_functions_test.clj
Labels: backport

#29906 MLv2: Add sample-dataset test metadata
  test/metabase/lib/test_metadata.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29923 Fixes convert-timezone tests for redshift
  test/metabase/query_processor_test/date_time_zone_functions_test.clj
Labels: backport

#29930 Return internal operator representation in resolve-expression
  src/metabase/lib/expression.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/schema/expression.cljc
  test/metabase/lib/expression_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29530 Improve typesafety for `useDispatch`
  frontend/src/metabase/lib/redux/hooks.ts
  frontend/src/metabase/lib/redux/hooks.unit.spec.tsx
  frontend/src/metabase/lib/redux/index.ts
  frontend/src/metabase/lib/redux/utils.js
  frontend/src/metabase/lib/redux/utils.unit.spec.js
  frontend/test/__support__/ui.tsx
Labels: Type:Tech Debt, .Frontend, .Team/Viz :bar_chart:

#29903 MLv2: Fix metadata inference for `:field` clauses with string names that come from joins
  src/metabase/lib/card.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/metadata.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/stage.cljc
  test/metabase/lib/card_test.cljc
  test/metabase/lib/convert_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/join_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29841 [MLv2] filter to filters and condition to conditions
  modules/drivers/mongo/test/metabase/driver/mongo/query_processor_test.clj
  src/metabase/lib/convert.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/filter.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/schema.cljc
  src/metabase/lib/schema/filter.cljc
  src/metabase/lib/schema/join.cljc
  src/metabase/lib/stage.cljc
  src/metabase/lib/util.cljc
  src/metabase/models/segment.clj
  test/metabase/lib/convert_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/filter_test.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/normalize_test.cljc
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/stage_test.cljc
  test/metabase/lib/table_test.cljc
  test/metabase/lib/util_test.cljc
Labels: Type:Tech Debt, .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#29954 [MLv2] Fix tests where condition moved to conditions
  test/metabase/lib/field_test.cljc
  test/metabase/lib/join_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#29920 Fix flaky migrate-field-database-type-test
  test/metabase/db/schema_migrations_test.clj
Labels: flaky-test-fix

#29975 Rename metabase.csv -> metabase.upload
  bin/build/src/release/elastic_beanstalk.clj
  bin/build/src/release/uberjar.clj
  src/metabase/api/card.clj
  src/metabase/driver.clj
  src/metabase/driver/postgres.clj
  src/metabase/upload.clj
  test/metabase/api/card_test.clj
  test/metabase/upload_test.clj
Labels: .Team/Backend :pancakes:

#29985 Handle uploads to the root collection
  src/metabase/api/card.clj
Labels: .Team/Backend :pancakes:

#29987 Allow the uploads schema to be nil (for MySQL, etc.)
  src/metabase/api/card.clj
  test/metabase/api/card_test.clj
Labels: .Team/Backend :pancakes:

#29878 Fix typo in managing-people-groups doc
  docs/people-and-groups/managing.md
Labels: Type:Documentation

#29957 Unify pMBQL interrogation function return values
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/breakout.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/expression.cljc
  src/metabase/lib/filter.cljc
  src/metabase/lib/order_by.cljc
  test/metabase/lib/filter_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29777 [MLv2] remove & replace breakout clause
  src/metabase/lib/breakout.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/query.cljc
  src/metabase/lib/remove_replace.cljc
  src/metabase/lib/util.cljc
  test/metabase/lib/breakout_test.cljc
  test/metabase/lib/query_test.cljc
  test/metabase/lib/remove_replace_test.cljc
Labels: Type:Tech Debt, .Backend, .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#29961 Add MLv2 schema and functions for `:var`
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/schema/aggregation.cljc
  test/metabase/lib/aggregation_test.cljc
  test/metabase/query_processor_test/test_mlv2.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30009 Reload collection data after CSV upload
  frontend/src/metabase/redux/uploads.ts
Labels: .Team/Viz :bar_chart:

#29962 Fix MLv2 `:absolute-datetime` schema
  src/metabase/lib/schema/expression/temporal.cljc
  src/metabase/lib/schema/literal.cljc
  test/metabase/lib/schema/expression/temporal_test.cljc
  test/metabase/lib/schema/literal_test.cljc
  test/metabase/query_processor_test/test_mlv2.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29956 MLv2 metadata calculation validation
  e2e/test/scenarios/question/saved.cy.spec.js
  src/metabase/lib/field.cljc
  src/metabase/lib/stage.cljc
  src/metabase/query_processor.clj
  test/metabase/lib/metadata/calculation_test.cljc
  test/metabase/query_processor_test/nested_queries_test.clj
  test/metabase/query_processor_test/remapping_test.clj
  test/metabase/query_processor_test/test_mlv2.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30026 Fix MLv2 order-by FE tests
  frontend/src/metabase-lib/order_by.unit.spec.ts
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30018 MLv2 Column grouping utilities
  frontend/src/metabase-lib/metadata.ts
  frontend/src/metabase-lib/types.ts
  shadow-cljs.edn
  src/metabase/lib/column_group.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/stage.cljc
  test/metabase/lib/card_test.cljc
  test/metabase/lib/column_group_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/test_util.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30019 MLv2: fix :relative-datetime schema
  src/metabase/lib/schema/expression/temporal.cljc
  test/metabase/lib/schema/expression/temporal_test.cljc
  test/metabase/query_processor_test/test_mlv2.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30017 docs - note on mongo scans
  docs/databases/connections/mongodb.md
Labels: Type:Documentation, backport

#30002 [MLv2] Remove and replace clause for filters
  src/metabase/lib/remove_replace.cljc
  test/metabase/lib/remove_replace_test.cljc
Labels: Type:Tech Debt, .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30022 MLv2: Fix `:percentile` column name
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/schema/aggregation.cljc
  test/metabase/lib/aggregation_test.cljc
  test/metabase/lib/schema/aggregation_test.cljc
  test/metabase/query_processor_test/test_mlv2.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30021 MLv2: Fix join `:fields` conversion
  src/metabase/lib/card.cljc
  src/metabase/lib/convert.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/order_by.cljc
  src/metabase/lib/remove_replace.cljc
  src/metabase/lib/stage.cljc
  src/metabase/lib/table.cljc
  src/metabase/lib/util.cljc
  test/metabase/lib/card_test.cljc
  test/metabase/lib/convert_test.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/stage_test.cljc
  test/metabase/lib/util_test.cljc
  test/metabase/query_processor_test/explicit_joins_test.clj
  test/metabase/query_processor_test/test_mlv2.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30029 Fix not being able to use field filters in databases without schema
  e2e/test/scenarios/native-filters/reproductions/29786.cy.spec.js
  frontend/src/metabase-lib/metadata/Schema.ts
Labels: support/Repro, backport

#30005 CSV upload e2e tests
  e2e/support/assets/dog_breeds.csv
  e2e/support/assets/star_wars_characters.csv
  e2e/test/scenarios/collections/uploads.cy.spec.js
  frontend/src/metabase/collections/containers/CollectionContent.jsx
Labels: .Team/Viz :bar_chart:

#30061 docs - update api docs
  docs/api-documentation.md
  docs/api/action.md
  docs/api/activity.md
  docs/api/collection.md
  docs/api/database.md
  docs/api/dataset.md
  docs/api/ee/advanced-config-logs.md
  docs/api/ee/sandbox-gtap.md
  docs/api/ee/sandbox-user.md
  docs/api/field.md
  docs/api/metabot.md
  docs/api/metric.md
  docs/api/permissions.md
  docs/api/pulse.md
  docs/api/search.md
  docs/api/segment.md
  docs/api/setting.md
  docs/api/table.md
Labels: Type:Documentation

#30049 docs - note on invitations
  docs/people-and-groups/managing.md
Labels: Type:Documentation, backport

#29227 Add/remove nested fields when enabling/disabling unfolded JSON
  src/metabase/api/field.clj
  test/metabase/api/field_test.clj
Labels: .Team/Backend :pancakes:

#30013 Delete old persistence schemas in redshift
  modules/drivers/redshift/test/metabase/test/data/redshift.clj
Labels: .Team/Backend :pancakes:

#30074 [MLv2] Remove and replace fields clause
  src/metabase/lib/core.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/remove_replace.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/remove_replace_test.cljc
  test/metabase/lib/stage_test.cljc
Labels: Type:Tech Debt, .Backend, .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#29846 docs - update saml
  docs/people-and-groups/authenticating-with-jwt.md
  docs/people-and-groups/authenticating-with-saml.md
  docs/people-and-groups/google-and-ldap.md
Labels: Type:Documentation, backport

#30085 docs - update full-app embedding
  docs/embedding/full-app-embedding.md
Labels: Type:Documentation, backport

#30063 MLv2: remove `:type :pipeline`
  src/metabase/lib/metadata.cljc
  src/metabase/lib/query.cljc
  src/metabase/lib/schema.cljc
  src/metabase/lib/util.cljc
  src/metabase/query_processor/middleware/normalize_query.clj
  test/metabase/lib/aggregation_test.cljc
  test/metabase/lib/breakout_test.cljc
  test/metabase/lib/card_test.cljc
  test/metabase/lib/convert_test.cljc
  test/metabase/lib/dev_test.cljc
  test/metabase/lib/expression_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/filter_test.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/normalize_test.cljc
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/query_test.cljc
  test/metabase/lib/schema/expression/conditional_test.cljc
  test/metabase/lib/schema/util_test.cljc
  test/metabase/lib/stage_test.cljc
  test/metabase/lib/test_util.cljc
  test/metabase/lib/util_test.cljc
  test/metabase/query_processor_test/pipeline_queries_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30065 MLv2: make sure Model source query includes implicitly joinable columns
  src/metabase/lib/card.cljc
  src/metabase/lib/js/metadata.cljs
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/util.cljc
  test/metabase/lib/card_test.cljc
  test/metabase/lib/convert_test.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/query_test.cljc
  test/metabase/lib/stage_test.cljc
  test/metabase/lib/test_metadata.cljc
  test/metabase/lib/test_metadata/graph_provider.cljc
  test/metabase/lib/test_util.cljc
  test/metabase/lib/util_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30064 fix specs in embedding-full-app.cy.spec.js
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/dashboard/dashboard-management.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/embedding/embedding-full-app.cy.spec.js
  e2e/test/scenarios/question/saved.cy.spec.js
  frontend/src/metabase/nav/components/AdminNavbar/AdminNavbar.tsx
  frontend/src/metabase/nav/components/AppBar/AppBar.tsx
Labels: backport, .Team/Viz :bar_chart:

#29411 Convert TagEditorParam-related logic to TypeScript and add tests
  e2e/test/scenarios/admin/datamodel/metrics.cy.spec.js
  e2e/test/scenarios/auditing/ad-hoc.cy.spec.js
  e2e/test/scenarios/models/reproductions/29378-actions-search-crash.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/11580.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/22473-cannot-unsubscribe-from-notifications-without-collection-perms.cy.spec.js
  e2e/test/scenarios/question/reproductions/15714-cc-postgres-percentile-accepts-two-params.cy.spec.js
  e2e/test/scenarios/question/reproductions/18207-string-min-max.cy.spec.js
  e2e/test/scenarios/question/summarization.cy.spec.js
  frontend/src/metabase-lib/metadata/utils/models.ts
  frontend/src/metabase-lib/parameters/constants.ts
  frontend/src/metabase-lib/parameters/utils/template-tag-options.ts
  frontend/src/metabase-lib/parameters/utils/template-tag-options.unit.spec.js
  frontend/src/metabase-lib/parameters/utils/template-tags.ts
  frontend/src/metabase-lib/queries/NativeQuery.ts
  frontend/src/metabase-lib/variables/TemplateTagVariable/TemplateTagVariable.ts
  frontend/src/metabase-lib/variables/TemplateTagVariable/constants.ts
  frontend/src/metabase-types/api/dataset.ts
  frontend/src/metabase-types/api/field.ts
  frontend/src/metabase-types/api/mocks/dataset.ts
  frontend/src/metabase-types/api/mocks/field.ts
  frontend/src/metabase-types/api/mocks/presets/sample_database.ts
  frontend/src/metabase-types/api/mocks/table.ts
  frontend/src/metabase-types/api/query.ts
  frontend/src/metabase-types/api/table.ts
  frontend/src/metabase-types/types/Query.ts
  frontend/src/metabase/actions/containers/ActionCreator/ActionContext/QueryActionContextProvider/utils.ts
  frontend/src/metabase/actions/containers/ActionCreator/ActionContext/QueryActionContextProvider/utils.unit.spec.ts
  frontend/src/metabase/parameters/utils/template-tag-options.js
  frontend/src/metabase/query_builder/actions/core/initializeQB.unit.spec.ts
  frontend/src/metabase/query_builder/actions/core/updateQuestion.unit.spec.ts
  frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.jsx
  frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.styled.tsx
  frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.unit.spec.jsx
  frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.unit.spec.tsx
Labels: .Team/QueryBuilder :abacus:

#30105 Fix row limit not set properly for notebook preview queries
  e2e/test/scenarios/question/notebook.cy.spec.js
  frontend/src/metabase/query_builder/components/notebook/NotebookStepPreview.jsx
Labels: support/Repro, .Team/QueryProcessor :hammer_and_wrench:

#29641 Refactor editing dashboard's cards
  e2e/support/commands/api/composite/createNativeQuestionAndDashboard.js
  e2e/support/commands/api/composite/createQuestionAndAddToDashboard.js
  e2e/support/commands/api/composite/createQuestionAndDashboard.js
  e2e/support/helpers/e2e-dashboard-helpers.js
  e2e/support/integration/visit-dashboard.js
  e2e/test/scenarios/custom-column/reproductions/19744-cc-after-aggregation-limited-filters.cy.spec.js
  e2e/test/scenarios/dashboard-filters/parameters.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/12720-no-data-permissions-connected-filter.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/19494-wrong-default-value-multiple-cards-same-question.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/25322-loading-list-values.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/8030-reload-card-without-change.cy.spec.js
  e2e/test/scenarios/dashboard/chained-filters.cy.spec.js
  e2e/test/scenarios/dashboard/click-behavior.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard-drill.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard_local-only.cy.spec.js
  e2e/test/scenarios/dashboard/permissions.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/17160-click-behavior-multiple-options.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/26230-dashboard-sticky-filter-incorrectly-positioned.cy.spec.js
  e2e/test/scenarios/embedding/reproductions/15860-locked-filters-same-source-table.cy.spec.js
  e2e/test/scenarios/filters/view.cy.spec.js
  e2e/test/scenarios/models/models-metadata.cy.spec.js
  e2e/test/scenarios/models/reproductions/23024-cannot-apply-dash-filter-native-model.cy.spec.js
  e2e/test/scenarios/question/nulls.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/20393-public-dashboard-nested-card-with-parameters.cy.spec.js
  e2e/test/scenarios/sharing/subscriptions.cy.spec.js
  e2e/test/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  e2e/test/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
  e2e/test/scenarios/visualizations/line-bar-tooltips.cy.spec.js
  e2e/test/scenarios/visualizations/line_chart.cy.spec.js
  e2e/test/scenarios/visualizations/pivot_tables.cy.spec.js
  e2e/test/scenarios/visualizations/scalar.cy.spec.js
  enterprise/backend/test/metabase_enterprise/sandbox/api/dashboard_test.clj
  frontend/src/metabase/dashboard/actions/cards.js
  frontend/src/metabase/dashboard/actions/core.js
  frontend/src/metabase/dashboard/actions/data-fetching.js
  frontend/src/metabase/dashboard/actions/save.js
  frontend/src/metabase/dashboard/reducers.js
  frontend/src/metabase/lib/revisions/revisions.js
  frontend/src/metabase/lib/revisions/revisions.unit.spec.js
  frontend/src/metabase/services.js
  src/metabase/api/dashboard.clj
  src/metabase/models/dashboard.clj
  src/metabase/models/dashboard_card.clj
  src/metabase/util/malli/schema.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/http_client.clj
  test/metabase/models/dashboard_card_test.clj
  test/metabase/models/dashboard_test.clj
  test/metabase/models/on_demand_test.clj
Labels: .Team/Viz :bar_chart:, .Team/Backend :pancakes:

#30120 [MLv2] New `fk_reference_name` for implicitly joinable column group
  src/metabase/lib/column_group.cljc
  src/metabase/lib/util.cljc
  test/metabase/lib/column_group_test.cljc
  test/metabase/lib/util_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30096 [MLv2] Clean query to remove any parts that fail schema validation
  src/metabase/lib/convert.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/metric.cljc
  test/metabase/lib/convert_test.cljc
  test/metabase/lib/metric_test.cljc
Labels: Type:Tech Debt, .Backend, .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30124 Create an empty display_name for MBQL stages
  src/metabase/lib/column_group.cljc
  src/metabase/lib/metadata/calculation.cljc
  test/metabase/lib/column_group_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30106 Remove `ExtendedOptions` component
  frontend/src/metabase/query_builder/components/ExtendedOptions.jsx
  frontend/src/metabase/query_builder/components/GuiQueryEditor.jsx
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30107 Clean up notebook `BreakoutStep` component
  frontend/src/metabase/query_builder/components/notebook/steps/BreakoutStep/BreakoutStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/BreakoutStep/BreakoutStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/BreakoutStep/index.ts
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30135 [DOCS] Update editing user account instructions
  docs/people-and-groups/managing.md
Labels: Type:Documentation, backport

#30095 MLv2: fix aggregation reference generation
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/metadata/calculation.cljc
  test/metabase/lib/aggregation_test.cljc
  test/metabase/lib/order_by_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29885 Use string/contains for new high cardinality string field filters
  e2e/test/scenarios/native-filters/sql-filters-source.cy.spec.js
  frontend/src/metabase-lib/parameters/utils/template-tag-options.ts
  frontend/src/metabase-types/api/field.ts
  frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.unit.spec.tsx
Labels: .Team/QueryBuilder :abacus:

#30129 docs - break out charts into individual pages
  docs/configuring-metabase/appearance.md
  docs/questions/images/VisualizeChoices.png
  docs/questions/images/trend-settings.png
  docs/questions/images/viz-options.png
  docs/questions/images/waterfall-chart.png
  docs/questions/sharing/visualizations/combo-chart.md
  docs/questions/sharing/visualizations/detail.md
  docs/questions/sharing/visualizations/funnel.md
  docs/questions/sharing/visualizations/gauge.md
  docs/questions/sharing/visualizations/line-bar-and-area-charts.md
  docs/questions/sharing/visualizations/map.md
  docs/questions/sharing/visualizations/numbers.md
  docs/questions/sharing/visualizations/pie-or-donut-chart.md
  docs/questions/sharing/visualizations/pivot-table.md
  docs/questions/sharing/visualizations/progress-bar.md
  docs/questions/sharing/visualizations/scatterplot-or-bubble-chart.md
  docs/questions/sharing/visualizations/table.md
  docs/questions/sharing/visualizations/trend.md
  docs/questions/sharing/visualizations/waterfall-chart.md
  docs/questions/sharing/visualizing-results.md
Labels: Type:Documentation, backport

#30147 [MLv2] Make expression and aggregation options survive conversion
  src/metabase/lib/convert.cljc
  test/metabase/lib/convert_test.cljc
Labels: Type:Tech Debt, .Backend, .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30098 MLv2 schema: validate references
  src/metabase/lib/field.cljc
  src/metabase/lib/schema.cljc
  src/metabase/lib/stage.cljc
  test/metabase/automagic_dashboards/core_test.clj
  test/metabase/lib/field_test.cljc
  test/metabase/lib/schema_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30175 [TEMP] Disable the failing percy spec
  e2e/test/visual/models/editor.cy.spec.js
Labels: .CI & Tests

#30176 Increase the request timeout for Percy model editor spec
  e2e/test/visual/models/editor.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#30153 [CI] Remove matrix strategy from the `percy` job
  .github/workflows/e2e-tests.yml
Labels: .CI & Tests, backport

#30151 Removes :result_metadata from non-model card serialization
  src/metabase/models/card.clj
  test/metabase/models/card_test.clj
Labels: Operation/Serialization, backport

#30155 [MLv2] Drop `:effective-type` when converting to legacy MBQL
  src/metabase/lib/convert.cljc
  test/metabase/lib/convert_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30179 Upgrade Percy CLI to `v1.23.0`
  package.json
  yarn.lock
Labels: Type:Tech Debt, .CI & Tests

#30187 Revert "[MLv2] Drop `:effective-type` when converting to legacy MBQL"
  src/metabase/lib/convert.cljc
  test/metabase/lib/convert_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30188 docs - update session expiration and google sign-in
  docs/configuring-metabase/environment-variables.md
  docs/people-and-groups/changing-session-expiration.md
  docs/people-and-groups/google-and-ldap.md
Labels: Type:Documentation, backport

#30126 Include checklist task to migrate off h2
  frontend/src/metabase-types/api/index.ts
  frontend/src/metabase-types/api/mocks/index.ts
  frontend/src/metabase-types/api/mocks/setup.ts
  frontend/src/metabase-types/api/setup.ts
  frontend/src/metabase/admin/settings/selectors.js
  frontend/src/metabase/admin/settings/setup/components/SetupCheckList/SetupCheckList.jsx
  frontend/src/metabase/admin/settings/setup/components/SetupCheckList/SetupCheckList.styled.tsx
  frontend/src/metabase/admin/settings/setup/components/SetupCheckList/SetupCheckList.unit.spec.tsx
  frontend/src/metabase/admin/settings/setup/components/SetupCheckList/index.ts
  frontend/test/__support__/server-mocks/index.ts
  frontend/test/__support__/server-mocks/setup.ts
  src/metabase/api/setup.clj
  test/metabase/api/setup_test.clj
Labels: backport

#30194 Wait for db delete request to resolve before closing modal
  frontend/src/metabase/admin/databases/components/DeleteDatabaseModel/DeleteDatabaseModal.tsx
  frontend/src/metabase/admin/databases/database.js
Labels: .Team/Viz :bar_chart:

#30173 MLv2: finish temporal bucketing
  src/metabase/lib/core.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/schema/temporal_bucketing.cljc
  src/metabase/lib/stage.cljc
  src/metabase/lib/temporal_bucket.cljc
  test/metabase/lib/breakout_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/schema/expression/temporal_test.cljc
  test/metabase/lib/schema/filter_test.cljc
  test/metabase/lib/stage_test.cljc
  test/metabase/lib/test_metadata.cljc
  test/metabase/lib/test_util.cljc
  test/metabase/lib/util_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30225 [DOCS] Fix typo in premium features overview
  docs/paid-features/overview.md
Labels: Type:Documentation

#30192 🍒 Backport Percy fixes and changes
  .github/workflows/e2e-tests.yml
  e2e/test/visual/models/editor.cy.spec.js
  package.json
  yarn.lock
Labels: was-backported

#30212 fix metabot error state is not cleared
  frontend/src/metabase/metabot/components/Metabot/Metabot.unit.spec.tsx
  frontend/src/metabase/metabot/reducers.js
  frontend/test/__support__/server-mocks/dataset.ts
  frontend/test/__support__/server-mocks/metabot.ts
Labels: .Team/Viz :bar_chart:

#30191 [MLv2] Change how `TemplateTag.widget-type` works for field filters
  frontend/src/metabase-lib/parameters/utils/template-tag-options.ts
  frontend/src/metabase-lib/parameters/utils/template-tags.ts
  frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.jsx
  shared/src/metabase/mbql/schema.cljc
  src/metabase/models/card.clj
  src/metabase/query_processor/card.clj
  src/metabase/query_processor/dashboard.clj
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30203 docs - update filter troubleshooting
  docs/data-modeling/metadata-editing.md
  docs/troubleshooting-guide/filters.md
Labels: Type:Documentation, backport

#30215 docs - update "can't see tables"
  docs/troubleshooting-guide/cant-see-tables.md
Labels: Type:Documentation, backport

#30231 docs - update official collection info
  docs/exploration-and-organization/collections.md
  docs/exploration-and-organization/images/official-collection.png
  docs/exploration-and-organization/images/verified-icon.png
Labels: Type:Documentation, backport

#30163 MLv2: Implement support for `:value` clause
  dev/src/user.clj
  src/metabase/config.clj
  src/metabase/lib/convert.cljc
  src/metabase/lib/normalize.cljc
  src/metabase/lib/schema/common.cljc
  src/metabase/lib/schema/expression.cljc
  src/metabase/lib/schema/literal.cljc
  src/metabase/lib/util.cljc
  src/metabase/query_processor.clj
  test/metabase/lib/convert_test.cljc
  test/metabase/lib/schema/literal_test.cljc
  test/metabase/query_processor_test/test_mlv2.clj
  test/metabase/test/core.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29842 Use metabase-lib v2 to manage order-bys in the notebook editor
  e2e/test/scenarios/binning/binning-reproductions.cy.spec.js
  frontend/src/metabase-lib/metadata.ts
  frontend/src/metabase-lib/order_by.ts
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/src/metabase-lib/queries/structured/OrderBy.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/common/components/QueryColumnPicker/QueryColumnPicker.tsx
  frontend/src/metabase/common/components/QueryColumnPicker/QueryColumnPicker.unit.spec.tsx
  frontend/src/metabase/common/components/QueryColumnPicker/index.ts
  frontend/src/metabase/query_builder/components/SortWidget.jsx
  frontend/src/metabase/query_builder/components/notebook/lib/steps.ts
  frontend/src/metabase/query_builder/components/notebook/steps/SortStep/SortStep.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/SortStep/SortStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/SortStep/SortStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/QuestionRowCount/QuestionRowCount.unit.spec.tsx
  frontend/src/metabase/query_builder/selectors.unit.spec.js
  frontend/test/metabase-lib/lib/queries/StructuredQuery-clean.unit.spec.js
  frontend/test/metabase-lib/lib/queries/StructuredQuery.unit.spec.js
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30227 Mark MLv1 limit methods as deprecated
  frontend/src/metabase-lib/queries/StructuredQuery.ts
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30258 docs - update note on plans in environment variables
  docs/configuring-metabase/environment-variables.md
Labels: Type:Documentation, backport

#30252 [E2E] Fix question moderation flake
  e2e/test/scenarios/organization/moderation-question.cy.spec.js
Labels: .CI & Tests, backport, flaky-test-fix

#30271 Fix #29862: Metric tooltip description gets cut
  frontend/src/metabase/core/components/Tooltip/Tooltip.tsx
Labels: Type:Bug, Priority:P2, Administration/Metrics & Segments, .Frontend, backport

#30257 Move question's `apiGetResults` method from metabase-lib
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase-types/api/database.ts
  frontend/src/metabase-types/api/mocks/database.ts
  frontend/src/metabase/containers/QuestionResultLoader.jsx
  frontend/src/metabase/metabot/actions.ts
  frontend/src/metabase/query_builder/actions/querying.js
  frontend/src/metabase/services.js
  frontend/src/metabase/services.unit.spec.ts
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30276 docs - fix anchor link
  docs/configuring-metabase/appearance.md
Labels: Type:Documentation, backport

#30265 Fix inlined number params in native queries
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  src/metabase/driver/sql/parameters/substitution.clj
  src/metabase/driver/sql/query_processor.clj
  src/metabase/driver/sql/util.clj
  src/metabase/driver/sql_jdbc.clj
  src/metabase/driver/sql_jdbc/actions.clj
  src/metabase/driver/sql_jdbc/sync/describe_database.clj
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
  test/metabase/driver/sql/query_processor_test.clj
  test/metabase/query_processor_test/date_bucketing_test.clj
  test/metabase/query_processor_test/parameters_test.clj
  test/metabase/query_processor_test/timezones_test.clj
  test/metabase/test/data/sql/ddl.clj
  test/metabase/test/data/sql_jdbc/load_data.clj
Labels: backport

#30293 [MLv2] JS wrappers for breakout fns
  frontend/src/metabase-lib/breakout.ts
  frontend/src/metabase-lib/breakout.unit.spec.ts
  frontend/src/metabase-lib/query.ts
  frontend/src/metabase-lib/v2.ts
  src/metabase/lib/breakout.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/order_by.cljc
  src/metabase/lib/stage.cljc
  test/metabase/lib/breakout_test.cljc
  test/metabase/lib/remove_replace_test.cljc
Labels: .Backend, .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30298 docs - updates docs home image
  docs/README.md
  docs/images/metabase-product-screenshot.png
Labels: Type:Documentation, backport

#30146 Hide column types and migrate JS functions working with them
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/metadata/jvm.clj
  src/metabase/lib/types/constants.cljc
  src/metabase/lib/types/isa.cljc
  test/metabase/lib/types/isa_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#26377 Add Netsuite SuiteAnalytics Connect community driver link to documentation
  docs/developers-guide/partner-and-community-drivers.md
Labels: Type:Documentation, backport

#30281 Add metabot tracking
  e2e/test/scenarios/onboarding/metabot.cy.spec.js
  frontend/src/metabase/metabot/actions.ts
  frontend/src/metabase/metabot/analytics.ts
  frontend/src/metabase/metabot/components/MetabotFeedback/MetabotFeedback.tsx
  snowplow/iglu-client-embedded/schemas/com.metabase/metabot/jsonschema/1-0-1
Labels: .Team/Viz :bar_chart:

#30309 Add notification on escalation label
  .github/workflows/escalation-slack-notification.yml
Labels: .CI & Tests

#30310 Rename escalation label
  .github/workflows/escalation-slack-notification.yml
Labels: .CI & Tests

#30320 🍒 Manual Backport #30194
  frontend/src/metabase/admin/databases/components/DeleteDatabaseModel/DeleteDatabaseModal.tsx
  frontend/src/metabase/admin/databases/database.js
Labels: was-backported

#29751 Toggle JSON unfolding by field (again)
  e2e/test/scenarios/admin/datamodel/field.cy.spec.js
  frontend/src/metabase/admin/datamodel/containers/FieldApp.jsx
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
  modules/drivers/sqlite/test/metabase/driver/sqlite_test.clj
  resources/migrations/000_migrations.yaml
  src/metabase/api/field.clj
  src/metabase/db/custom_migrations.clj
  src/metabase/driver/common.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
  src/metabase/models/database.clj
  src/metabase/sync/interface.clj
  src/metabase/sync/sync_metadata/fields/fetch_metadata.clj
  src/metabase/sync/sync_metadata/fields/sync_instances.clj
  test/metabase/api/field_test.clj
  test/metabase/cmd/dump_to_h2_test.clj
  test/metabase/cmd/rotate_encryption_key_test.clj
  test/metabase/driver/common_test.clj
  test/metabase/driver/mysql_test.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/driver/sql_jdbc/sync/describe_table_test.clj
  test/metabase/driver/sql_jdbc_test.clj
  test/metabase/sync/sync_dynamic_test.clj
  test/metabase/sync/sync_metadata/fields/fetch_metadata_test.clj
  test/metabase/sync/sync_metadata/fields/sync_metadata_test.clj
  test/metabase/sync_test.clj
  test/metabase/test/mock/toucanery.clj
  test/metabase/test/mock/util.clj
Labels: .Team/Backend :pancakes:

#30300 [MLv2] Remove invalid query parts when summarizing
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/breakout.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/util.cljc
  test/metabase/lib/aggregation_test.cljc
  test/metabase/lib/breakout_test.cljc
Labels: .Backend, .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30336 bump snowflake to 3.13.30
  modules/drivers/snowflake/deps.edn
Labels: backport

#30316 breakoutable columns
  e2e/test/scenarios/admin/datamodel/field.cy.spec.js
  frontend/src/metabase-lib/breakout.ts
  src/metabase/lib/breakout.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/dev.cljc
  src/metabase/lib/expression.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/metadata.cljc
  test/metabase/lib/breakout_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30162 [MLv2] Fix inner native query key
  src/metabase/lib/convert.cljc
  test/metabase/lib/convert_test.cljc
  test/metabase/query_processor_test/test_mlv2.clj
Labels: Type:Bug, .Backend, .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#30341 docs - update env vars doc
  docs/configuring-metabase/environment-variables.md
Labels: Type:Documentation, backport

#30094 Check CSV Upload permissions on the frontend
  frontend/src/metabase/App.tsx
  frontend/src/metabase/admin/settings/components/widgets/UploadSettingsWidget/UploadSettingsWidget.tsx
  frontend/src/metabase/collections/components/CollectionHeader/CollectionHeader.tsx
  frontend/src/metabase/collections/components/CollectionHeader/CollectionHeader.unit.spec.tsx
  frontend/src/metabase/collections/components/CollectionHeader/CollectionUpload.tsx
  frontend/src/metabase/collections/containers/CollectionContent.jsx
  frontend/src/metabase/lib/uploads.ts
  frontend/src/metabase/status/components/FileUploadStatus/FileUploadStatus.tsx
  frontend/src/metabase/status/components/FileUploadStatus/FileUploadStatus.unit.spec.tsx
  frontend/src/metabase/status/components/FileUploadStatusLarge/FileUploadStatusLarge.tsx
  frontend/src/metabase/status/components/StatusLarge/StatusLarge.tsx
  frontend/src/metabase/status/components/StatusListing/StatusListing.tsx
  frontend/src/metabase/status/components/StatusListing/StatusListing.unit.spec.tsx
  frontend/src/metabase/status/containers/StatusListing/StatusListing.tsx
  frontend/src/metabase/status/containers/StatusListing/index.ts
  src/metabase/public_settings.clj
Labels: .Team/Viz :bar_chart:

#30358 docs - add week to list of units for datetimediff
  docs/questions/query-builder/expressions/datetimediff.md
Labels: Type:Documentation, backport

#30244 Notify slack of failing CI on master or release branches
  .github/workflows/rerun-workflows.yml
Labels: .CI & Tests

#30205 docs - add db privileges, update db connection troubleshooting
  docs/README.md
  docs/actions/introduction.md
  docs/databases/connecting.md
  docs/databases/connections/mysql.md
  docs/databases/connections/oracle.md
  docs/databases/connections/postgresql.md
  docs/databases/connections/presto.md
  docs/databases/connections/redshift.md
  docs/databases/connections/snowflake.md
  docs/databases/connections/sparksql.md
  docs/databases/connections/sql-server.md
  docs/databases/users-roles-privileges.md
  docs/troubleshooting-guide/data-permissions.md
  docs/troubleshooting-guide/db-connection.md
  docs/troubleshooting-guide/sync-fingerprint-scan.md
Labels: Type:Documentation, backport

#30082 Entity Search + Indexing
  e2e/test/scenarios/models/model-indexes.cy.spec.js
  frontend/src/metabase-lib/types/constants.js
  frontend/src/metabase-lib/types/utils/isa.js
  frontend/src/metabase-lib/types/utils/isa.unit.spec.js
  frontend/src/metabase-types/api/field.ts
  frontend/src/metabase-types/api/index.ts
  frontend/src/metabase-types/api/mocks/index.ts
  frontend/src/metabase-types/api/mocks/modelIndexes.ts
  frontend/src/metabase-types/api/modelIndexes.ts
  frontend/src/metabase-types/api/search.ts
  frontend/src/metabase-types/store/entities.ts
  frontend/src/metabase-types/store/mocks/entities.ts
  frontend/src/metabase/components/EditBar/EditBar.tsx
  frontend/src/metabase/entities/index.js
  frontend/src/metabase/entities/indexed-entities/index.ts
  frontend/src/metabase/entities/indexed-entities/indexed-entities.ts
  frontend/src/metabase/entities/model-indexes/actions.ts
  frontend/src/metabase/entities/model-indexes/actions.unit.spec.ts
  frontend/src/metabase/entities/model-indexes/index.ts
  frontend/src/metabase/entities/model-indexes/model-indexes.ts
  frontend/src/metabase/entities/model-indexes/utils.ts
  frontend/src/metabase/lib/schema/schema.js
  frontend/src/metabase/lib/urls/index.ts
  frontend/src/metabase/lib/urls/indexed-entities.ts
  frontend/src/metabase/nav/components/AppBar/AppBar.tsx
  frontend/src/metabase/query_builder/actions/core/core.js
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetFieldMetadataSidebar/DatasetFieldMetadataSidebar.jsx
  frontend/src/metabase/schema.js
  frontend/src/metabase/search/components/InfoText.jsx
  frontend/src/metabase/services.js
  frontend/test/__support__/server-mocks/model-indexes.ts
Labels: .Team/Viz :bar_chart:

#30326 Look for options at the last position in MBQL clauses
  src/metabase/lib/convert.cljc
  src/metabase/lib/schema/expression/conditional.cljc
  test/metabase/lib/convert_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30172 MLv2: port time interval description code
  frontend/src/metabase-lib/Dimension.ts
  frontend/src/metabase-lib/metadata.ts
  frontend/src/metabase-lib/queries/utils/query-time.js
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/CurrentPicker/CurrentPicker.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/DateUnitSelector.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar.jsx
  src/metabase/lib/core.cljc
  src/metabase/lib/filter.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/temporal_bucket.cljc
  test/metabase/lib/temporal_bucket_test.cljc
Labels: visual, .Team/QueryProcessor :hammer_and_wrench:

#30219 Csv/misc bugfixes
  resources/migrations/000_migrations.yaml
  src/metabase/api/card.clj
  src/metabase/driver.clj
  src/metabase/driver/h2.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql_jdbc.clj
  src/metabase/upload.clj
  test/metabase/api/card_test.clj
  test/metabase/upload_test.clj
Labels: .Team/Backend :pancakes:

#30388 🍒 Fix typo in password reset email template (#30348)
  e2e/support/commands/api/question.js
  e2e/support/helpers/e2e-misc-helpers.js
  src/metabase/email/password_reset.mustache
Labels: was-backported

#30352 Add tests for schema endpoints
  enterprise/backend/src/metabase_enterprise/advanced_permissions/common.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  src/metabase/api/database.clj
  test/metabase/api/database_test.clj
Labels: .Team/Backend :pancakes:

#30405 docs - note on column visibility
  docs/data-modeling/metadata-editing.md
Labels: Type:Documentation, backport

#30394 Add include_hidden parameter to GET "api/database/:id/schemas"
  src/metabase/api/database.clj
  test/metabase/api/database_test.clj
Labels: .Team/Backend :pancakes:

#29053 Fix metadata handling during implicit joins resolution
  src/metabase/query_processor/middleware/add_implicit_joins.clj
  test/metabase/query_processor/middleware/add_implicit_joins_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#30337 Fix #25637: SmartScalars should compactify like Scalars
  frontend/src/metabase/visualizations/lib/scalar_utils.ts
  frontend/src/metabase/visualizations/lib/scalar_utils.unit.spec.ts
  frontend/src/metabase/visualizations/visualizations/Scalar.jsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar.jsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar.unit.spec.js
Labels: Type:Bug, Priority:P3, Client:Mobile Web, .Frontend, Visualization/Scalars, backport, visual

#30330 fix database info banner link
  frontend/src/metabase/databases/components/DatabaseInfoField/DatabaseInfoField.styled.tsx
  frontend/src/metabase/databases/components/DatabaseInfoField/DatabaseInfoField.unit.spec.tsx
Labels: backport, .Team/Viz :bar_chart:

#30392 Handle BOMs in uploaded CSVs
  deps.edn
  src/metabase/upload.clj
  test/metabase/upload_test.clj
Labels: .Team/Backend :pancakes:

#30421 Make CSV "Start Exploring" Link Actually Start Exploring
  e2e/test/scenarios/collections/uploads.cy.spec.js
  frontend/src/metabase/redux/uploads.ts
  frontend/src/metabase/redux/uploads.unit.spec.js
  frontend/src/metabase/status/components/FileUploadStatus/FileUploadStatus.unit.spec.tsx
  frontend/src/metabase/status/components/FileUploadStatusLarge/FileUploadStatusLarge.tsx
  frontend/src/metabase/status/components/StatusLarge/StatusLarge.tsx
  src/metabase/api/card.clj
Labels: .Team/Viz :bar_chart:, .Team/Backend :pancakes:

#30432 docs - fix links
  docs/troubleshooting-guide/db-connection.md
  docs/troubleshooting-guide/sync-fingerprint-scan.md
Labels: Type:Documentation, backport

#30443 Update filters.md > fix doc itemization
  docs/dashboards/filters.md
Labels: Type:Documentation, backport

#30408 Fix #28973: Disable drag for single fields
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPicker.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingOrderedItems.tsx
Labels: Type:Bug, Priority:P3, Visualization/Chart Settings, backport, visual

#30449 docs - fix link
  docs/troubleshooting-guide/data-permissions.md
Labels: Type:Documentation, backport

#30451 docs - remove file
  docs/start.md
Labels: Type:Documentation, backport

#30373 [MLv2] remove replace join conditions and fields
  src/metabase/lib/core.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/remove_replace.cljc
  src/metabase/lib/schema/join.cljc
  src/metabase/lib/util.cljc
  test/metabase/lib/remove_replace_test.cljc
Labels: .Backend, .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:
