Repository metabase/metabase, pull requests merged in 2023-07, with the labels that each got.

#31999 Enable eftest slow test warnings for tests that take longer than 1.5s
  test/metabase/test_runner.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32076 🍒 to 46: Fix Snowflake sync with uploaded private key (#31593)
  modules/drivers/snowflake/resources/metabase-plugin.yaml
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  src/metabase/driver/util.clj
Labels: was-backported

#32057 Update row chart measuring function
  e2e/test/scenarios/visualizations/rows.cy.spec.js
  frontend/src/metabase/static-viz/components/RowChart/RowChart.tsx
  frontend/src/metabase/visualizations/shared/components/RowChart/RowChart.stories.tsx
  frontend/src/metabase/visualizations/shared/components/RowChart/RowChart.tsx
  frontend/src/metabase/visualizations/shared/components/RowChart/RowChart.unit.spec.tsx
Labels: backport, visual, .Blocker, .Team/PixelPolice :police_officer:

#31982 handleSelectSeries uses ordered series
  e2e/test/scenarios/visualizations/bar_chart.cy.spec.js
  frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx
Labels: backport, visual, .Team/PixelPolice :police_officer:

#31484 moving instance analytics logic to enterprise
  enterprise/frontend/src/metabase-enterprise/collections/components/CollectionInstanceAnalyticsIcon.tsx
  enterprise/frontend/src/metabase-enterprise/collections/components/CollectionInstanceAnalyticsIcon.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/collections/constants.ts
  enterprise/frontend/src/metabase-enterprise/collections/index.ts
  enterprise/frontend/src/metabase-enterprise/collections/utils.ts
  enterprise/frontend/src/metabase-enterprise/collections/utils.unit.spec.ts
  frontend/src/metabase-types/api/collection.ts
  frontend/src/metabase-types/api/mocks/collection.ts
  frontend/src/metabase/collections/components/CollectionHeader/CollectionCaption.tsx
  frontend/src/metabase/collections/components/CollectionHeader/CollectionHeader.unit.spec.tsx
  frontend/src/metabase/collections/utils.ts
  frontend/src/metabase/dashboard/components/DashboardHeaderView.tsx
  frontend/src/metabase/dashboard/containers/DashboardHeader.unit.spec.jsx
  frontend/src/metabase/dashboard/containers/DashboardHeader.unit.spec.tsx
  frontend/src/metabase/entities/collections/utils.ts
  frontend/src/metabase/entities/collections/utils.unit.spec.ts
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/query_builder/components/SavedQuestionHeaderButton/CollectionIcon.tsx
  frontend/src/metabase/search/components/InfoText.jsx
Labels: .Team/PixelPolice :police_officer:

#32025 impersonatied FE fixes
  e2e/support/helpers/e2e-permissions-helpers.js
  e2e/test/scenarios/permissions/impersonated.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/advanced_permissions/index.js
  enterprise/frontend/src/metabase-enterprise/feature_level_permissions/permission-management/download-permission.ts
  frontend/src/metabase/admin/permissions/permissions.js
  frontend/src/metabase/admin/permissions/selectors/confirmations.ts
  frontend/src/metabase/admin/permissions/selectors/data-permissions/schemas.ts
  frontend/src/metabase/admin/permissions/utils/graph/data-permissions.ts
  frontend/src/metabase/plugins/index.ts
Labels: backport, .Blocker, .Team/PixelPolice :police_officer:

#32008 moving dashboard events 1-0-2 to 1-1-2
  frontend/src/metabase/dashboard/analytics.ts
  snowplow/iglu-client-embedded/schemas/com.metabase/dashboard/jsonschema/1-1-2
Labels: backport, .Team/PixelPolice :police_officer:

#32091 Fix cronjob frequency for ReplayIO E2E tests
  .github/workflows/e2e-tests.yml
Labels: .CI & Tests, backport

#32095 Fix cronjob frequency for ReplayIO E2E tests (#32091)
  .github/workflows/e2e-tests.yml
Labels: was-backported

#32067 Implement filter-operator
  frontend/src/metabase-lib/filter.ts
  src/metabase/lib/core.cljc
  src/metabase/lib/filter.cljc
  src/metabase/lib/js.cljs
  test/metabase/lib/filter_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32089 Fix metabase.lib.js/available-join-strategies
  src/metabase/lib/js.cljs
  test/metabase/lib/js_test.cljs
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31965 Fix Heading card input and Text card content clipping
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.styled.tsx
  frontend/src/metabase/visualizations/visualizations/Text/Text.css
  frontend/src/metabase/visualizations/visualizations/Text/Text.jsx
  frontend/src/metabase/visualizations/visualizations/Text/Text.styled.tsx
  frontend/src/metabase/visualizations/visualizations/Text/Text.unit.spec.tsx
Labels: Reporting/Dashboards, .Frontend, backport, .Regression/master, visual, .Team/PixelPolice :police_officer:

#31930 unskip testing actions when impersonated
  e2e/support/db_tasks.js
  e2e/support/helpers/e2e-qa-databases-helpers.js
  e2e/support/test_roles.js
  e2e/test/scenarios/actions/model-actions.cy.spec.js
Labels: backport, .Team/PixelPolice :police_officer:

#32077 Apply draft parameters when turning on dashboard auto-apply filters
  e2e/test/scenarios/dashboard-filters/dashboard-filters-auto-apply.cy.spec.js
  frontend/src/metabase/dashboard/actions/parameters.js
Labels: backport, .Team/42 :milky_way:

#31747 Let users create a new collection when saving or moving things
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/question/new.cy.spec.js
  e2e/test/scenarios/question/question-management.cy.spec.js
  frontend/src/metabase/collections/components/BulkActions.jsx
  frontend/src/metabase/collections/components/MoveCollectionModal/MoveCollectionModal.tsx
  frontend/src/metabase/collections/containers/FormCollectionPicker/FormCollectionPicker.styled.tsx
  frontend/src/metabase/collections/containers/FormCollectionPicker/FormCollectionPicker.tsx
  frontend/src/metabase/containers/CollectionMoveModal.jsx
  frontend/src/metabase/containers/CollectionMoveModal.tsx
  frontend/src/metabase/containers/ItemPicker/ItemPicker.tsx
  frontend/src/metabase/containers/ItemPicker/ItemPicker.unit.spec.js
  frontend/src/metabase/containers/ItemPicker/ItemPickerView.tsx
  frontend/src/metabase/containers/ItemPicker/test-utils.js
  frontend/src/metabase/containers/SaveQuestionModal.tsx
  frontend/src/metabase/containers/SaveQuestionModal.unit.spec.tsx
  frontend/src/metabase/core/components/Button/Button.styled.tsx
  frontend/src/metabase/core/components/Button/Button.tsx
  frontend/src/metabase/dashboard/components/DashboardMoveModal.jsx
  frontend/src/metabase/dashboard/containers/CreateDashboardForm.tsx
  frontend/src/metabase/dashboard/containers/CreateDashboardModal.tsx
  frontend/src/metabase/dashboard/containers/CreateDashboardModal.unit.spec.tsx
  frontend/src/metabase/models/components/ModelDetailPage/ModelDetailHeader/ModelDetailHeader.tsx
  frontend/src/metabase/query_builder/components/QueryModals.tsx
  frontend/test/__support__/server-mocks/collection.ts
Labels: .Team/PixelPolice :police_officer:

#32116 Fix failing geocode test
  test/metabase/server/request/util_test.clj
Labels: backport, .Team/42 :milky_way:

#31978 Backport sunset snowplow tracking for task history to 45
  enterprise/frontend/src/metabase-enterprise/audit_app/containers/AuditTableVisualization.jsx
  frontend/test/metabase/scenarios/onboarding/setup/setup.cy.spec.js
  src/metabase/models/task_history.clj
  test/metabase/models/task_history_test.clj
  test/metabase/sync/analyze_test.clj
Labels: was-backported, .Team/42 :milky_way:

#32061 [MLv2] Allow replacing clauses with metrics
  src/metabase/lib/common.cljc
  test/metabase/lib/remove_replace_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#31957 Clean and rebuild the CLJS on a `yarn dev`
  package.json
Labels: .Building & Releasing, .Team/QueryProcessor :hammer_and_wrench:

#32098 Revert "Removes :googleanalytics driver and related code (#31670)"
  .clj-kondo/config.edn
  .github/workflows/backend.yml
  .github/workflows/drivers.yml
  bin/build/src/i18n/enumerate.clj
  deps.edn
  docs/databases/connections/google-analytics.md
  docs/developers-guide/drivers/multimethods.md
  docs/questions/query-builder/expressions/converttimezone.md
  docs/questions/query-builder/expressions/datetimediff.md
  docs/questions/query-builder/introduction.md
  docs/questions/sharing/visualizations/pivot-table.md
  docs/questions/start.md
  e2e/test/scenarios/admin/databases/add-new-database.cy.spec.js
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase-lib/metadata/Database.ts
  frontend/src/metabase-lib/metadata/Metric.ts
  frontend/src/metabase-lib/metadata/Table.ts
  frontend/src/metabase-lib/metadata/utils/ga-metadata.js
  frontend/src/metabase-lib/metadata/utils/tables.js
  frontend/src/metabase-lib/queries/Query.ts
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/src/metabase-lib/queries/utils/segments.js
  frontend/src/metabase/databases/constants.tsx
  frontend/src/metabase/lib/engine.js
  frontend/src/metabase/query_builder/actions/core/updateQuestion.ts
  frontend/src/metabase/query_builder/components/view/QuestionDataSelector.jsx
  frontend/test/metabase-lib/lib/metadata/Metric.unit.spec.js
  jest.tz.unit.conf.json
  jest.unit.conf.json
  modules/drivers/deps.edn
  modules/drivers/googleanalytics/deps.edn
  modules/drivers/googleanalytics/resources/metabase-plugin.yaml
  modules/drivers/googleanalytics/src/metabase/driver/google.clj
  modules/drivers/googleanalytics/src/metabase/driver/googleanalytics.clj
  modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/client.clj
  modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/execute.clj
  modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/metadata.clj
  modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/query_processor.clj
  modules/drivers/googleanalytics/test/metabase/driver/google_test.clj
  modules/drivers/googleanalytics/test/metabase/driver/googleanalytics/execute_test.clj
  modules/drivers/googleanalytics/test/metabase/driver/googleanalytics/query_processor_test.clj
  modules/drivers/googleanalytics/test/metabase/driver/googleanalytics_test.clj
  resources/automagic_dashboards/table/GoogleAnalyticsTable.yaml
  shared/src/metabase/mbql/schema.cljc
  shared/src/metabase/types.cljc
  src/metabase/automagic_dashboards/core.clj
  src/metabase/driver/util.clj
  src/metabase/sync/analyze/classifiers/name.clj
  src/metabase/sync/analyze/fingerprint.clj
  test/metabase/automagic_dashboards/core_test.clj
  test/metabase/automagic_dashboards/rules_test.clj
  test/metabase/driver_test.clj
  test/metabase/lib/metric_test.cljc
  test/metabase/query_processor/middleware/expand_macros_test.clj
  test/metabase/query_processor_test.clj
  test/metabase/sync/analyze/fingerprint_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32064 MLv2: add filter operator short display name
  src/metabase/lib/filter.cljc
  src/metabase/lib/filter/operator.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/schema/filter.cljc
  test/metabase/lib/filter_test.cljc
  test/metabase/lib/join_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32110 Implement replace-join and support joins in (remove/replace)-clause
  src/metabase/lib/core.cljc
  src/metabase/lib/remove_replace.cljc
  src/metabase/lib/util.cljc
  test/metabase/lib/remove_replace_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31646 Adding filter of summarized field grouped by latitude and longitude on a map changes visualization type
  e2e/support/helpers/e2e-notebook-helpers.js
  e2e/test/scenarios/visualizations/reproductions/30058-32075-map-visualizations.cy.spec.js
  e2e/test/scenarios/visualizations/reproductions/30058-map-crash.cy.spec.js
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase/query_builder/actions/querying.js
  frontend/test/metabase-lib/lib/Question.unit.spec.js
Labels: support/Repro, backport, .Team/42 :milky_way:

#32119 Fix - Filter box in table has horizontal scroll
  e2e/test/scenarios/visualizations/table.cy.spec.js
  frontend/src/metabase/query_builder/components/filters/pickers/DefaultPicker.jsx
  frontend/src/metabase/query_builder/components/filters/pickers/DefaultPicker.styled.tsx
Labels: support/Repro, backport, .Team/42 :milky_way:

#32080 Migrate MetabaseSettings.isEnterprise to getIsPaidPlan selector
  frontend/src/metabase/admin/settings/components/SettingsEmailForm.jsx
  frontend/src/metabase/admin/settings/components/SettingsUpdatesForm/SettingsUpdatesForm.unit.spec.js
  frontend/src/metabase/admin/settings/components/SettingsUpdatesForm/VersionUpdateNotice/VersionUpdateNotice.jsx
  frontend/src/metabase/admin/settings/setup/components/SetupCheckList/SetupCheckList.jsx
Labels: backport, .Team/42 :milky_way:

#32078 Migrate MetabaseSettings.isPaidPlan to getIsPaidPlan selector
  frontend/src/metabase/admin/routes.jsx
  frontend/src/metabase/admin/tasks/components/Help/Help.styled.tsx
  frontend/src/metabase/admin/tasks/components/Help/Help.tsx
  frontend/src/metabase/admin/tasks/components/Help/index.ts
  frontend/src/metabase/admin/tasks/containers/Help.jsx
  frontend/src/metabase/lib/settings.ts
  frontend/src/metabase/nav/components/AdminNavbar/AdminNavbar.tsx
  frontend/src/metabase/nav/components/ProfileLink.jsx
Labels: Type:Tech Debt, backport, .Team/42 :milky_way:

#32104 🍒 Manual Backport (#32098) restores :googleanalytics driver
  .clj-kondo/config.edn
  .github/workflows/backend.yml
  .github/workflows/drivers.yml
  bin/build/src/i18n/enumerate.clj
  deps.edn
  docs/databases/connections/google-analytics.md
  docs/developers-guide/drivers/multimethods.md
  docs/questions/query-builder/expressions/converttimezone.md
  docs/questions/query-builder/expressions/datetimediff.md
  docs/questions/query-builder/introduction.md
  docs/questions/sharing/visualizations/pivot-table.md
  docs/questions/start.md
  e2e/test/scenarios/admin/databases/add-new-database.cy.spec.js
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase-lib/metadata/Database.ts
  frontend/src/metabase-lib/metadata/Metric.ts
  frontend/src/metabase-lib/metadata/Table.ts
  frontend/src/metabase-lib/metadata/utils/ga-metadata.js
  frontend/src/metabase-lib/metadata/utils/tables.js
  frontend/src/metabase-lib/queries/Query.ts
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/src/metabase-lib/queries/utils/segments.js
  frontend/src/metabase/databases/constants.tsx
  frontend/src/metabase/lib/engine.js
  frontend/src/metabase/query_builder/actions/core/updateQuestion.ts
  frontend/src/metabase/query_builder/components/view/QuestionDataSelector.jsx
  frontend/test/metabase-lib/lib/metadata/Metric.unit.spec.js
  jest.tz.unit.conf.json
  jest.unit.conf.json
  modules/drivers/deps.edn
  modules/drivers/googleanalytics/deps.edn
  modules/drivers/googleanalytics/resources/metabase-plugin.yaml
  modules/drivers/googleanalytics/src/metabase/driver/google.clj
  modules/drivers/googleanalytics/src/metabase/driver/googleanalytics.clj
  modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/client.clj
  modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/execute.clj
  modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/metadata.clj
  modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/query_processor.clj
  modules/drivers/googleanalytics/test/metabase/driver/google_test.clj
  modules/drivers/googleanalytics/test/metabase/driver/googleanalytics/execute_test.clj
  modules/drivers/googleanalytics/test/metabase/driver/googleanalytics/query_processor_test.clj
  modules/drivers/googleanalytics/test/metabase/driver/googleanalytics_test.clj
  resources/automagic_dashboards/table/GoogleAnalyticsTable.yaml
  shared/src/metabase/mbql/schema.cljc
  shared/src/metabase/types.cljc
  src/metabase/automagic_dashboards/core.clj
  src/metabase/driver/util.clj
  src/metabase/sync/analyze/classifiers/name.clj
  src/metabase/sync/analyze/fingerprint.clj
  test/metabase/automagic_dashboards/core_test.clj
  test/metabase/automagic_dashboards/rules_test.clj
  test/metabase/driver_test.clj
  test/metabase/query_processor/middleware/expand_macros_test.clj
  test/metabase/query_processor_test.clj
  test/metabase/sync/analyze/fingerprint_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31564 Migrate QB summarization sidebar to MLv2
  .vscode/settings.json
  e2e/test/scenarios/question/summarization.cy.spec.js
  frontend/src/metabase-lib/breakout.ts
  frontend/src/metabase-lib/buckets.ts
  frontend/src/metabase-lib/v2.ts
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.tsx
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.unit.spec.tsx
  frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.tsx
  frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BucketPickerPopover.tsx
  frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/types.ts
  frontend/src/metabase/query_builder/components/view/View.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/AddAggregationButton/AddAggregationButton.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/AddAggregationButton/AddAggregationButton.styled.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/AddAggregationButton/AddAggregationButton.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/AddAggregationButton/index.ts
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/AggregationItem/AggregationItem.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/AggregationItem/AggregationItem.styled.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/AggregationItem/AggregationItem.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/AggregationItem/index.ts
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/BreakoutColumnList/BreakoutColumnList.styled.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/BreakoutColumnList/BreakoutColumnList.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/BreakoutColumnList/BreakoutColumnListItem/BreakoutColumnListItem.styled.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/BreakoutColumnList/BreakoutColumnListItem/BreakoutColumnListItem.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/BreakoutColumnList/BreakoutColumnListItem/index.ts
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/BreakoutColumnList/index.ts
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/DimensionList/DimensionList.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/DimensionList/DimensionListItem/DimensionListItem.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/DimensionList/DimensionListItem/DimensionListItem.styled.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/DimensionList/DimensionListItem/DimensionListItem.unit.spec.js
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/DimensionList/DimensionListItem/index.js
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/DimensionList/index.js
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/DimensionList/utils.js
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeSidebar.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeSidebar.styled.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeSidebar.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeSidebar.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/index.ts
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#32086 Make text measurement function naming more consistent
  frontend/src/metabase/lib/measure-text.ts
  frontend/src/metabase/static-viz/components/FunnelChart/utils/margin.ts
  frontend/src/metabase/static-viz/components/Gauge/utils.tsx
  frontend/src/metabase/static-viz/components/Legend/utils.ts
  frontend/src/metabase/static-viz/components/ProgressBar/utils.ts
  frontend/src/metabase/static-viz/components/RowChart/RowChart.tsx
  frontend/src/metabase/static-viz/components/XYChart/XYChart.tsx
  frontend/src/metabase/static-viz/components/XYChart/utils/ticks.ts
  frontend/src/metabase/static-viz/components/XYChart/utils/values.ts
  frontend/src/metabase/static-viz/lib/axes.js
  frontend/src/metabase/static-viz/lib/text.ts
  frontend/src/metabase/static-viz/lib/text.unit.spec.js
  frontend/src/metabase/visualizations/shared/components/RowChart/RowChart.stories.tsx
  frontend/src/metabase/visualizations/shared/components/RowChart/RowChart.tsx
  frontend/src/metabase/visualizations/shared/components/RowChart/RowChart.unit.spec.tsx
  frontend/src/metabase/visualizations/shared/components/RowChart/utils/layout.ts
  frontend/src/metabase/visualizations/shared/components/RowChart/utils/scale.ts
  frontend/src/metabase/visualizations/shared/components/RowChart/utils/ticks.ts
  frontend/src/metabase/visualizations/visualizations/RowChart/RowChart.tsx
Labels: backport, visual, .Team/PixelPolice :police_officer:

#32071 🍒 to 47: Fix release workflow latest Docker tag adjustment (#32041)
  .github/workflows/release.yml
Labels: was-backported

#32072 🍒 to 46: Fix release workflow latest Docker tag adjustment (#32041)
  .github/workflows/release.yml
Labels: was-backported

#32051 [MLv2] Native query functions for changing db and collection-name
  modules/drivers/mongo/src/metabase/driver/mongo.clj
  modules/drivers/mongo/test/metabase/driver/mongo_test.clj
  src/metabase/driver.clj
  src/metabase/lib/core.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/native.cljc
  test/metabase/lib/native_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#32111 sync snowplow dashboard schemas
  frontend/src/metabase/dashboard/analytics.ts
  snowplow/iglu-client-embedded/schemas/com.metabase/dashboard/jsonschema/1-1-1
  snowplow/iglu-client-embedded/schemas/com.metabase/dashboard/jsonschema/1-1-2
Labels: backport, .Team/PixelPolice :police_officer:

#32150 refactor `useDashboardTabs` and `useSyncURLSlug` to not nullify `selectedTabId` on unmount
  e2e/test/scenarios/sharing/public-dashboard.cy.spec.js
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/use-dashboard-tabs.ts
  frontend/src/metabase/dashboard/components/DashboardTabs/use-sync-url-slug.ts
Labels: .Team/PixelPolice :police_officer:

#32157 Bump @replayio/cypress to 1.0.5
  package.json
  yarn.lock
Labels: .CI & Tests, backport

#31687 Make sure models keep their original question when duplicating
  e2e/test/scenarios/models/reproductions/31309-duplicating-a-model-must-duplicate-question.cy.spec.js
  frontend/src/metabase/query_builder/components/QueryModals.tsx
  frontend/src/metabase/query_builder/selectors.js
Labels: .Team/42 :milky_way:

#32079 Move hosting plugin code to EE
  enterprise/frontend/src/metabase-enterprise/hosting/components/SettingsCloudStoreLink/SettingsCloudStoreLink.styled.tsx
  enterprise/frontend/src/metabase-enterprise/hosting/components/SettingsCloudStoreLink/SettingsCloudStoreLink.tsx
  enterprise/frontend/src/metabase-enterprise/hosting/components/SettingsCloudStoreLink/index.ts
  enterprise/frontend/src/metabase-enterprise/hosting/index.js
  enterprise/frontend/src/metabase-enterprise/plugins.js
  frontend/src/metabase/lib/settings.ts
  frontend/src/metabase/plugins/builtin.js
  frontend/src/metabase/plugins/components/SettingsCloudStoreLink/index.js
  frontend/src/metabase/selectors/settings.ts
Labels: Type:Tech Debt, .Team/42 :milky_way:

#32139 Fix - Search results has a box with scrollbars
  e2e/support/helpers/e2e-scrollbar-helpers.js
  e2e/support/helpers/index.js
  e2e/test/scenarios/onboarding/search/reproductions/28788-search-results-overflow.cy.spec.js
  e2e/test/scenarios/visualizations/table.cy.spec.js
  frontend/src/metabase/nav/components/SearchBar.tsx
  frontend/src/metabase/search/components/SearchResult.styled.tsx
Labels: support/Repro, backport, .Team/42 :milky_way:

#32146 Don't allow mapping a model FK to another model
  e2e/test/scenarios/models/reproductions/31663-no-model-fks.cy.spec.js
  frontend/src/metabase-lib/metadata/Metadata.ts
  frontend/src/metabase/entities/databases.js
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetFieldMetadataSidebar/SemanticTypePicker/FKTargetPicker.tsx
Labels: support/Repro, .Team/QueryProcessor :hammer_and_wrench:

#32144 Fix missing `slack_colorized` icon
  frontend/src/metabase/core/components/Icon/icons/index.ts
  frontend/src/metabase/sharing/components/NewPulseSidebar.tsx
  frontend/src/metabase/sharing/components/SharingSidebar.jsx
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#32152 BE: Make card and dashboard granular cache_ttl respect feature flagging
  enterprise/backend/src/metabase_enterprise/advanced_config/caching.clj
  enterprise/backend/test/metabase_enterprise/advanced_config/caching_test.clj
  src/metabase/query_processor/card.clj
  test/metabase/query_processor/card_test.clj
Labels: .Team/42 :milky_way:

#32142 Preserve filters during navigating back to dashboard
  e2e/test/scenarios/dashboard/dashboard-back-navigation.cy.spec.js
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.jsx
  frontend/src/metabase/dashboard/reducers.js
  frontend/src/metabase/hooks/use-web-notification.ts
  frontend/src/metabase/query_builder/containers/QueryBuilder.jsx
Labels: .Team/42 :milky_way:

#32162 Change "Author" to "Created By" in model details
  frontend/src/metabase/models/components/ModelDetailPage/ModelInfoSidePanel/ModelInfoSidePanel.tsx
  frontend/src/metabase/models/containers/ModelDetailPage/ModelDetailPage.unit.spec.tsx
Labels: backport

#32167 Make the warn param logs to log the full API URI
  src/metabase/api/common.clj
Labels: .Team/42 :milky_way:

#32100 Fix several backend feature flag checks and remove `:any` flag from `defenterprise`
  enterprise/backend/src/metabase_enterprise/enhancements/integrations/ldap.clj
  enterprise/backend/src/metabase_enterprise/enhancements/models/native_query_snippet/permissions.clj
  enterprise/backend/src/metabase_enterprise/pulse.clj
  enterprise/backend/src/metabase_enterprise/search/scoring.clj
  enterprise/backend/test/metabase_enterprise/enhancements/api/native_query_snippet_test.clj
  enterprise/backend/test/metabase_enterprise/enhancements/integrations/ldap_test.clj
  enterprise/backend/test/metabase_enterprise/enhancements/models/native_query_snippet/permissions_test.clj
  enterprise/backend/test/metabase_enterprise/pulse_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/test_util.clj
  enterprise/backend/test/metabase_enterprise/search/scoring_test.clj
  enterprise/backend/test/metabase_enterprise/util_test.clj
  src/metabase/public_settings/premium_features.clj
  src/metabase/search/scoring.clj
  test/metabase/integrations/ldap_test.clj
  test/metabase/public_settings/premium_features_test.clj
Labels: backport, .Team/PixelPolice :police_officer:

#32147 Restore tab during navigating back to the dashboard
  e2e/test/scenarios/dashboard/dashboard-back-navigation.cy.spec.js
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.unit.spec.tsx
Labels: .Team/42 :milky_way:

#32188 Add mb to upload limit tooltip
  frontend/src/metabase/collections/components/CollectionHeader/CollectionUpload.tsx
  frontend/src/metabase/redux/uploads.ts
  frontend/src/metabase/redux/uploads.unit.spec.js
Labels: backport, .Team/PixelPolice :police_officer:

#32166 Manual backport of "sync snowplow dashboard schemas"
  frontend/src/metabase/dashboard/analytics.ts
  snowplow/iglu-client-embedded/schemas/com.metabase/dashboard/jsonschema/1-0-2
  snowplow/iglu-client-embedded/schemas/com.metabase/dashboard/jsonschema/1-1-1
Labels: was-backported, .Team/PixelPolice :police_officer:

#31751 Upgrade jsdom
  enterprise/frontend/src/metabase-enterprise/auth/actions.ts
  enterprise/frontend/src/metabase-enterprise/auth/components/SsoButton/SsoButton.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/auth/middleware/session-middleware.unit.spec.js
  frontend/src/metabase/auth/actions.ts
  frontend/src/metabase/auth/components/Logout/Logout.unit.spec.tsx
  frontend/src/metabase/lib/dom.js
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx
  frontend/test/metabase/lib/expressions/fuzz.recursive-parser.unit.spec.js
  frontend/test/metabase/lib/expressions/fuzz.tokenizer.unit.spec.js
  package.json
  yarn.lock
Labels: visual, .Team/42 :milky_way:

#32106 Make the `fieldValuesWidget` a functional component
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.jsx
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.unit.spec.js
  frontend/src/metabase/components/FieldValuesWidget/testMocks.js
  frontend/src/metabase/components/FieldValuesWidget/utils.js
  frontend/src/metabase/components/FieldValuesWidget/utils.unit.spec.js
Labels: .Team/PixelPolice :police_officer:

#32164 add separate test setup file path to file-paths
  .github/file-paths.yaml
Labels: backport, .Blocker, .Team/PixelPolice :police_officer:

#32185 Sort dashboard cards for mobile
  frontend/src/metabase/dashboard/components/grid/utils.js
  frontend/src/metabase/dashboard/components/grid/utils.unit.spec.js
Labels: backport, .Blocker, .Team/PixelPolice :police_officer:

#31986 Fix no warning when leaving edited native questions
  frontend/src/metabase/containers/SaveQuestionModal.tsx
  frontend/src/metabase/containers/SaveQuestionModal.unit.spec.tsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.jsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.unit.spec.tsx
  frontend/src/metabase/query_builder/selectors.js
  frontend/src/metabase/query_builder/utils.ts
  frontend/src/metabase/selectors/app.ts
Labels: backport, .Team/42 :milky_way:

#32214 Fix webpack warning from #31564
  frontend/src/metabase/query_builder/components/view/QuestionSummaries.jsx
Labels: backport, .Team/42 :milky_way:

#32177 Fix quick filter drill for custom expressions
  e2e/test/scenarios/custom-column/reproductions/32032-cc-quick-filter-drill.cy.spec.js
  frontend/src/metabase-lib/queries/drills/quick-filter-drill.ts
Labels: support/Repro, backport, .Team/QueryProcessor :hammer_and_wrench:

#32196 Fix places causing warnings in dev console and tests
  frontend/src/metabase/components/LastEditInfoLabel/LastEditInfoLabel.jsx
  frontend/src/metabase/components/tree/TreeNode.styled.tsx
  frontend/src/metabase/core/components/BookmarkToggle/BookmarkToggle.styled.tsx
  frontend/src/metabase/nav/components/AppBar/AppBarToggle.styled.tsx
  frontend/src/metabase/nav/components/SearchBar.styled.tsx
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/SidebarItems.styled.tsx
Labels: .Team/42 :milky_way:

#32103 :cherries: Manual Backport #31965 (heading input and text card clipping)
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.styled.tsx
  frontend/src/metabase/visualizations/visualizations/Text/Text.css
  frontend/src/metabase/visualizations/visualizations/Text/Text.jsx
  frontend/src/metabase/visualizations/visualizations/Text/Text.styled.jsx
  frontend/src/metabase/visualizations/visualizations/Text/Text.styled.tsx
  frontend/src/metabase/visualizations/visualizations/Text/Text.unit.spec.tsx
Labels: was-backported, visual, .Team/PixelPolice :police_officer:

#32223 Fix `fetch-mock` behavior with hanging requests
  frontend/test/jest-setup-env.js
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32192 Fix back to dashboard to select correct tab and preserve filters
  e2e/test/scenarios/dashboard/dashboard-back-navigation.cy.spec.js
  e2e/test/scenarios/models/reproductions/29951-model-editor-results-metadata.cy.spec.js
  frontend/src/metabase/components/LastEditInfoLabel/LastEditInfoLabel.jsx
  frontend/src/metabase/components/tree/TreeNode.styled.tsx
  frontend/src/metabase/core/components/BookmarkToggle/BookmarkToggle.styled.tsx
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.unit.spec.tsx
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.jsx
  frontend/src/metabase/dashboard/reducers.js
  frontend/src/metabase/hooks/use-web-notification.ts
  frontend/src/metabase/nav/components/AppBar/AppBarToggle.styled.tsx
  frontend/src/metabase/nav/components/SearchBar.styled.tsx
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/SidebarItems.styled.tsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.jsx
Labels: backport, .Team/42 :milky_way:

#31880 Fix styling for heading cards in dashboard subscriptions
  shared/src/metabase/shared/parameters/parameters.cljc
  src/metabase/pulse.clj
  test/metabase/dashboard_subscription_test.clj
Labels: visual, .Team/PixelPolice :police_officer:

#32066 Fix Filter Pill display names for dates
  e2e/test/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  e2e/test/scenarios/visualizations/reproductions/25007-week-tooltip-native.cy.spec.js
  frontend/src/metabase-lib/queries/structured/Filter.ts
  frontend/src/metabase/lib/formatting/date.tsx
  frontend/src/metabase/lib/formatting/date.unit.spec.tsx
  frontend/src/metabase/lib/formatting/types.ts
  frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.unit.spec.js
  frontend/test/metabase-lib/lib/queries/structured/Filter.unit.spec.js
Labels: visual, .Team/PixelPolice :police_officer:

#32138 Fix embedding plugins init
  enterprise/frontend/src/metabase-enterprise/embedding/components/EmbeddingAppOriginDescription/EmbeddingAppOriginDescription.tsx
  enterprise/frontend/src/metabase-enterprise/embedding/components/EmbeddingAppOriginDescription/index.ts
  enterprise/frontend/src/metabase-enterprise/embedding/index.js
  frontend/src/metabase/admin/routes.jsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/SettingsEditor.jsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/index.ts
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/common.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/premium.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/setup.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingCustomizationInfo/EmbeddingCustomizationInfo.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingCustomizationInfo/index.ts
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingCustomizationWidget/EmbeddingCustomizationWidget.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingCustomizationWidget/EmbeddingCustomizationWidget.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingCustomizationWidget/index.ts
  frontend/src/metabase/admin/settings/components/widgets/FullAppEmbeddingLinkWidget/FullAppEmbeddingLinkWidget.tsx
  frontend/src/metabase/admin/settings/components/widgets/FullAppEmbeddingLinkWidget/FullAppEmbeddingLinkWidget.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/FullAppEmbeddingLinkWidget/index.ts
  frontend/src/metabase/admin/settings/selectors.js
  frontend/src/metabase/plugins/index.ts
  frontend/test/__support__/enterprise.js
Labels: backport, .Team/42 :milky_way:

#32235 Adds logic and test for default SSH tunnel port
  src/metabase/util/ssh.clj
  test/metabase/util/ssh_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32254 [E2E] Fix `models` 29951 flake
  e2e/test/scenarios/models/reproductions/29951-model-editor-results-metadata.cy.spec.js
Labels: .CI & Tests, backport, flaky-test-fix

#32172 Redundant separator displayed in table filter popup
  frontend/src/metabase/components/Popover/Popover.css
  frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.styled.tsx
  frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.tsx
  frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx
  frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverHeader.tsx
Labels: .Team/42 :milky_way:

#32202 Convert FieldValuesWidget to Typescript
  frontend/src/metabase-lib/metadata/Field.ts
  frontend/src/metabase-types/api/field.ts
  frontend/src/metabase-types/api/mocks/field.ts
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.tsx
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.unit.spec.tsx
  frontend/src/metabase/components/FieldValuesWidget/index.jsx
  frontend/src/metabase/components/FieldValuesWidget/index.ts
  frontend/src/metabase/components/FieldValuesWidget/testMocks.ts
  frontend/src/metabase/components/FieldValuesWidget/types.ts
  frontend/src/metabase/components/FieldValuesWidget/utils.ts
Labels: .Team/PixelPolice :police_officer:

#32101 Updates v1 load to resolve Dashboard filter source card IDs
  enterprise/backend/src/metabase_enterprise/serialization/load.clj
  enterprise/backend/test/metabase_enterprise/serialization/load_test.clj
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#32276 Fix flake in `impersonated` E2E spec
  e2e/test/scenarios/permissions/impersonated.cy.spec.js
Labels: .CI & Tests, flaky-test-fix

#32212 fix broken audit
  .github/workflows/e2e-tests.yml
  e2e/test/scenarios/auditing/ad-hoc.cy.spec.js
  e2e/test/scenarios/auditing/approved-domains.cy.spec.js
  e2e/test/scenarios/auditing/auditing.cy.spec.js
  e2e/test/scenarios/auditing/questions-audit.cy.spec.js
  e2e/test/scenarios/dashboard/x-rays.cy.spec.js
  frontend/src/metabase/dashboard/actions/data-fetching.js
  frontend/src/metabase/dashboard/actions/tabs.ts
  frontend/src/metabase/dashboard/utils.ts
  frontend/src/metabase/dashboard/utils.unit.spec.ts
Labels: backport, .Blocker, .Team/PixelPolice :police_officer:

#32232 fade headings in parameter mapping mode
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase-types/api/dashboard.ts
  frontend/src/metabase-types/api/mocks/dashboard.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/dashboard/components/DashCard/Dashcard.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashCard/utils.ts
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.styled.tsx
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.tsx
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.unit.spec.tsx
  frontend/src/metabase/visualizations/visualizations/Text/Text.styled.tsx
Labels: backport, visual, .Team/PixelPolice :police_officer:

#32250 Expose new feature flags
  enterprise/backend/test/metabase_enterprise/api/session_test.clj
  enterprise/backend/test/metabase_enterprise/api/session_test.lcj
  src/metabase/public_settings.clj
  src/metabase/public_settings/premium_features.clj
  test/metabase/api/session_test.clj
Labels: backport, .Team/42 :milky_way:

#32251 Allow downloading native query results even after the query has changed
  e2e/test/scenarios/sharing/downloads/reproductions/28834-modified-native-question.cy.spec.js
  frontend/src/metabase/query_builder/components/QueryDownloadWidget/QueryDownloadWidget.tsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.unit.spec.tsx
Labels: backport, .Team/42 :milky_way:

#32281 Manual backport "Fix dashboard scroll jank when there are no filters"
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx
  frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.js
  frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.unit.spec.js
Labels: was-backported, .Team/PixelPolice :police_officer:

#32240 Mechanism for internal use of premium features
  enterprise/backend/src/metabase_enterprise/audit_db.clj
  src/metabase/public_settings/premium_features.clj
  test/metabase/public_settings/premium_features_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32307 Revert "Mechanism for internal use of premium features"
  enterprise/backend/src/metabase_enterprise/audit_db.clj
  src/metabase/public_settings/premium_features.clj
  test/metabase/public_settings/premium_features_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32313 restrict mantine v6 specific api
  .eslintrc
  frontend/src/metabase/.eslintrc
Labels: backport, .Team/PixelPolice :police_officer:

#32238 Use default role for connection impersonation when acquiring a connection via JDBC spec
  enterprise/backend/src/metabase_enterprise/advanced_permissions/driver/impersonation.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/driver/impersonation_test.clj
  src/metabase/driver/sql_jdbc/execute.clj
Labels: backport, .Team/PixelPolice :police_officer:

#32315 Rework back to dashboard e2e test to make it more real world and less flaky
  e2e/test/scenarios/dashboard/dashboard-back-navigation.cy.spec.js
Labels: .Team/42 :milky_way:

#32239 🍒 Fix back to dashboard to select correct tab and preserve filters
  e2e/test/scenarios/dashboard/dashboard-back-navigation.cy.spec.js
  frontend/src/metabase/components/LastEditInfoLabel/LastEditInfoLabel.jsx
  frontend/src/metabase/components/tree/TreeNode.styled.tsx
  frontend/src/metabase/core/components/BookmarkToggle/BookmarkToggle.styled.tsx
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.unit.spec.tsx
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.jsx
  frontend/src/metabase/dashboard/reducers.js
  frontend/src/metabase/hooks/use-web-notification.ts
  frontend/src/metabase/nav/components/AppBar/AppBarToggle.styled.tsx
  frontend/src/metabase/nav/components/SearchBar.styled.tsx
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/SidebarItems.styled.tsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.jsx
Labels: was-backported, .Team/42 :milky_way:

#32292 🍒 Backport E2E impersonated fix
  e2e/test/scenarios/permissions/impersonated.cy.spec.js
Labels: was-backported, flaky-test-fix

#32326 Fix - "A negative value is not valid" for height and width
  frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.jsx
  frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.unit.spec.js
Labels: support/Repro, backport, visual, .Team/42 :milky_way:

#32343 [E2E] Fix public dashboard flake
  e2e/test/scenarios/sharing/public-dashboard.cy.spec.js
Labels: backport, flaky-test-fix

#32347 🍒 Manual Backport #31986
  frontend/src/metabase/containers/SaveQuestionModal.tsx
  frontend/src/metabase/containers/SaveQuestionModal.unit.spec.tsx
  frontend/src/metabase/query_builder/components/QueryModals.tsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.jsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.unit.spec.tsx
  frontend/src/metabase/query_builder/selectors.js
  frontend/src/metabase/query_builder/utils.ts
  frontend/src/metabase/selectors/app.ts
Labels: was-backported

#32253 Fix enable/disable password login plugin init
  enterprise/frontend/src/metabase-enterprise/auth/index.js
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/common.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/password-login.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/premium.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/setup.tsx
Labels: .Team/42 :milky_way:

#32324 Adding toast when setting custom homepage
  e2e/test/scenarios/onboarding/home/homepage.cy.spec.js
  frontend/src/metabase/home/components/CustomHomePageModal/CustomHomePageModal.tsx
Labels: backport, .Team/PixelPolice :police_officer:

#32353 Convert search namespace to use Malli
  src/metabase/api/search.clj
  src/metabase/models/permissions.clj
  src/metabase/search/util.clj
  test/metabase/search/util_test.clj
Labels: .Team/42 :milky_way:

#32274 Fade Link Cards When Mapping Parameters
  frontend/src/metabase-types/api/mocks/dashboard.ts
  frontend/src/metabase/dashboard/components/DashCard/Dashcard.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashCard/utils.ts
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.styled.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.tsx
Labels: backport, visual, .Team/PixelPolice :police_officer:

#32338 Respect schema perms for CSV uploads
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  src/metabase/api/card.clj
Labels: backport, .Team/42 :milky_way:

#32193 Fix :has_question_and_dashboard
  src/metabase/api/user.clj
  test/metabase/api/user_test.clj
Labels: .Team/PixelPolice :police_officer:

#32154 Tweak behavior of `enabled?` fn on settings and add `:feature` option
  src/metabase/models/setting.clj
  test/metabase/models/setting_test.clj
Labels: .Team/PixelPolice :police_officer:

#32099 docs - 47 bits and bobs
  docs/databases/uploads.md
  docs/exploration-and-organization/collections.md
  docs/paid-features/overview.md
  docs/permissions/data.md
  docs/questions/images/bulk-filter-modal.png
  docs/questions/images/filter-badge.png
  docs/questions/images/filter-step.png
  docs/questions/query-builder/introduction.md
Labels: Type:Documentation, backport

#32336 Mantine Checkbox
  frontend/src/metabase/ui/components/inputs/Checkbox/Checkbox.stories.mdx
  frontend/src/metabase/ui/components/inputs/Checkbox/CheckboxIcon.tsx
  frontend/src/metabase/ui/components/inputs/Checkbox/index.ts
  frontend/src/metabase/ui/components/inputs/index.ts
  frontend/src/metabase/ui/theme.ts
Labels: .Team/42 :milky_way:

#32375 Potentially fix StackOverflow in flaky tests
  src/metabase/models/permissions_group.clj
  src/metabase/models/user.clj
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#32173 Fix - Clicking Saved Questions option in data selector when instance have no questions leads to Raw Data option instead
  frontend/src/metabase/containers/DataPicker/DataPickerContainer.tsx
  frontend/src/metabase/containers/DataPicker/DataPickerView.tsx
  frontend/src/metabase/containers/DataPicker/DataTypePicker/DataTypePicker.tsx
  frontend/src/metabase/containers/DataPicker/constants.ts
  frontend/src/metabase/containers/DataPicker/constants.tsx
  frontend/src/metabase/containers/DataPicker/index.ts
  frontend/src/metabase/containers/DataPicker/tests/common.tsx
  frontend/src/metabase/containers/DataPicker/types.ts
  frontend/src/metabase/containers/DataPicker/useDataPickerValue.ts
  frontend/src/metabase/containers/DataPicker/utils.ts
  frontend/src/metabase/containers/DataPicker/utils.unit.spec.ts
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.unit.spec.js
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDataBucketPicker/DataSelectorDataBucketPicker.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDataBucketPicker/DataSelectorDataBucketPicker.unit.spec.tsx
  frontend/src/metabase/query_builder/components/DataSelector/constants.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.jsx
Labels: support/Repro, backport, .Team/42 :milky_way:

#32141 Add focus trap to modals to prevent background keyboard navigation
  e2e/test/scenarios/admin/databases/add-new-database.cy.spec.js
  e2e/test/scenarios/permissions/impersonated.cy.spec.js
  frontend/src/metabase/components/Modal/WindowModal.tsx
  frontend/src/metabase/components/Modal/WindowModal.unit.spec.tsx
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterFieldSearch.tsx
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterModal.tsx
  frontend/src/metabase/timelines/common/components/NewEventModal/NewEventModal.tsx
  frontend/src/metabase/timelines/common/components/NewTimelineModal/NewTimelineModal.tsx
  frontend/src/metabase/ui/components/index.ts
  frontend/src/metabase/ui/components/util/FocusTrap/index.ts
  frontend/src/metabase/ui/components/util/index.ts
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.styled.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailWrapper.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailWrapper.unit.spec.tsx
  frontend/test/__support__/testDataset.js
  frontend/test/__support__/testDataset.ts
Labels: visual, .Team/42 :milky_way:

#32267 adjusting minimum size for scalar (number) cards
  e2e/test/scenarios/dashboard/dashboard-card-resizing.cy.spec.js
  frontend/src/metabase/visualizations/shared/utils/sizes.ts
Labels: backport, visual, .Team/PixelPolice :police_officer:

#32330 Use some more granular feature flags for premium features
  docs/configuring-metabase/environment-variables.md
  enterprise/backend/README.md
  enterprise/backend/src/metabase_enterprise/advanced_config/caching.clj
  enterprise/backend/src/metabase_enterprise/advanced_config/file.clj
  enterprise/backend/src/metabase_enterprise/api/routes.clj
  enterprise/backend/src/metabase_enterprise/content_management/api/routes.clj
  enterprise/backend/src/metabase_enterprise/content_verification/api/review.clj
  enterprise/backend/src/metabase_enterprise/content_verification/api/routes.clj
  enterprise/backend/src/metabase_enterprise/enhancements/models/native_query_snippet/permissions.clj
  enterprise/backend/test/metabase_enterprise/advanced_config/caching_test.clj
  enterprise/backend/test/metabase_enterprise/advanced_config/file/databases_test.clj
  enterprise/backend/test/metabase_enterprise/advanced_config/file/settings_test.clj
  enterprise/backend/test/metabase_enterprise/advanced_config/file/users_test.clj
  enterprise/backend/test/metabase_enterprise/advanced_config/file_test.clj
  enterprise/backend/test/metabase_enterprise/api/session_test.clj
  enterprise/backend/test/metabase_enterprise/content_verification/api/review_test.clj
  enterprise/backend/test/metabase_enterprise/enhancements/api/native_query_snippet_test.clj
  enterprise/backend/test/metabase_enterprise/enhancements/models/native_query_snippet/permissions_test.clj
  src/metabase/api/common/internal.clj
  src/metabase/api/database.clj
  src/metabase/models/moderation_review.clj
  src/metabase/public_settings.clj
  src/metabase/public_settings/premium_features.clj
  test/metabase/api/database_test.clj
Labels: .Team/42 :milky_way:

#32189 Use `:database` to check for a Mongo native query
  e2e/test/scenarios/native/reproductions/32121-sql-source-query-can-explore-results.cy.spec.js
  src/metabase/query_processor/middleware/fetch_source_query.clj
  test/metabase/query_processor/middleware/fetch_source_query_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32382 Fix `with-temporary-setting-values` incorrectly identify whether it's in a parallel test
  test/metabase/server/request/util_test.clj
  test/metabase/test/util.clj
Labels: .Team/42 :milky_way:

#32381 BE: Guard enable password login setting to respect feature flag
  enterprise/backend/test/metabase_enterprise/api/session_test.lcj
  enterprise/backend/test/metabase_enterprise/public_settings_test.clj
  src/metabase/models/setting.clj
  src/metabase/public_settings.clj
  test/metabase/api/session_test.clj
  test/metabase/models/user_test.clj
  test/metabase/server/request/util_test.clj
  test/metabase/test/util.clj
Labels: .Team/42 :milky_way:

#32153 BE: Make Approved Domains for Notifications setting respect feature flagging
  enterprise/backend/src/metabase_enterprise/advanced_config/models/pulse_channel.clj
  enterprise/backend/test/metabase_enterprise/advanced_config/api/pulse_test.clj
  enterprise/backend/test/metabase_enterprise/advanced_config/models/pulse_channel_test.clj
  src/metabase/public_settings/premium_features.clj
Labels: .Team/42 :milky_way:

#32404 docs - update image and clarify text
  docs/dashboards/images/dashboard-with-link-cards.png
  docs/dashboards/introduction.md
Labels: Type:Documentation, backport

#32378 Fix infinite loop when logging error when fetching `site-locale`
  src/metabase/models/setting.clj
  src/metabase/public_settings.clj
  src/metabase/util/i18n/impl.clj
  test/metabase/cmd/dump_to_h2_test.clj
  test/metabase/cmd/load_and_dump_test.clj
  test/metabase/public_settings_test.clj
  test/metabase/util/i18n/impl_test.clj
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#32406 docs - update releases
  docs/releases.md
Labels: Type:Documentation, backport

#32422 Have Kondo enforce usage of `clojure.core/random-uuid`
  .clj-kondo/config.edn
  enterprise/backend/src/metabase_enterprise/serialization/load.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/saml.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/sso_utils.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/api/setting_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj
  modules/drivers/druid/src/metabase/driver/druid/query_processor.clj
  src/metabase/api/action.clj
  src/metabase/api/card.clj
  src/metabase/api/dashboard.clj
  src/metabase/api/session.clj
  src/metabase/api/setup.clj
  src/metabase/config.clj
  src/metabase/lib/native.cljc
  src/metabase/models/user.clj
  src/metabase/public_settings.clj
  src/metabase/server/middleware/browser_cookie.clj
  src/metabase/setup.clj
  src/metabase/sync/util.clj
  test/metabase/actions/test_util.clj
  test/metabase/api/action_test.clj
  test/metabase/api/card_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/login_history_test.clj
  test/metabase/api/public_test.clj
  test/metabase/api/session_test.clj
  test/metabase/api/user_test.clj
  test/metabase/db/schema_migrations_test.clj
  test/metabase/driver/common/parameters/values_test.clj
  test/metabase/events/activity_feed_test.clj
  test/metabase/lib/native_test.cljc
  test/metabase/models/card_test.clj
  test/metabase/models/dashboard_test.clj
  test/metabase/models/login_history_test.clj
  test/metabase/models/user_test.clj
  test/metabase/query_processor/streaming_test.clj
  test/metabase/server/middleware/auth_test.clj
  test/metabase/server/middleware/session_test.clj
  test/metabase/util/password_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32134 Fix broken force migration
  src/metabase/db/custom_migrations.clj
  src/metabase/db/liquibase.clj
  src/metabase/db/setup.clj
  test/metabase/db/force_migration_test.clj
  test/metabase/db/liquibase_test.clj
  test_resources/force-migration.yaml
Labels: backport, .Team/42 :milky_way:

#32113 BE: Guard Official Collection requires EE token
  e2e/test/scenarios/organization/official-collections.cy.spec.js
  enterprise/backend/test/metabase_enterprise/content_management/api/collection_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/gtap_test.clj
  src/metabase/api/collection.clj
  src/metabase/api/permissions.clj
  src/metabase/models/collection.clj
  src/metabase/public_settings/premium_features.clj
  src/metabase/util/malli.cljc
  test/metabase/api/collection_test.clj
  test/metabase/api/permissions_test.clj
  test/metabase/db/custom_migrations_test.clj
  test/metabase/server/middleware/security_test.clj
Labels: backport, .Team/42 :milky_way:

#32261 Do not show edit model menu options without write permissions
  enterprise/frontend/src/metabase-enterprise/moderation/index.js
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/query_builder/components/QuestionActions.tsx
  frontend/src/metabase/query_builder/components/QuestionActions.unit.spec.tsx
Labels: backport, .Team/42 :milky_way:

#32367 Use correct feature flags for content verification and caching
  enterprise/frontend/src/metabase-enterprise/advanced_permissions/components/ImpersonationModal/ImpersonationModal.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/caching/index.js
  enterprise/frontend/src/metabase-enterprise/moderation/index.js
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/databases/containers/DatabaseEditApp.styled.tsx
  frontend/src/metabase/admin/databases/containers/DatabaseEditApp.tsx
  frontend/src/metabase/admin/permissions/test/DatabasesPermissionsPage/DatabasesPermissionsPage.unit.spec.tsx
  frontend/src/metabase/admin/permissions/test/GroupsPermissionsPage/GroupsPermissionsPage.unit.spec.tsx
  frontend/src/metabase/common/hooks/use-revision-list-query/use-revision-list-query.unit.spec.tsx
  frontend/src/metabase/common/hooks/use-user-list-query/use-user-list-query.unit.spec.tsx
  frontend/src/metabase/databases/components/DatabaseForm/DatabaseForm.stories.tsx
  frontend/src/metabase/databases/components/DatabaseForm/DatabaseForm.tsx
  frontend/src/metabase/databases/components/DatabaseForm/index.ts
  frontend/src/metabase/databases/components/DatabaseForm/tests/cache-granular-controls.unit.spec.tsx
  frontend/src/metabase/databases/components/DatabaseForm/tests/common.unit.spec.tsx
  frontend/src/metabase/databases/components/DatabaseForm/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/databases/components/DatabaseForm/tests/setup.tsx
  frontend/src/metabase/databases/components/DatabaseHelpCard/DatabaseHelpCard.stories.tsx
  frontend/src/metabase/databases/components/DatabaseHelpCard/DatabaseHelpCard.tsx
  frontend/src/metabase/databases/components/DatabaseHelpCard/index.ts
  frontend/src/metabase/databases/containers/DatabaseForm/DatabaseForm.tsx
  frontend/src/metabase/databases/containers/DatabaseForm/index.ts
  frontend/src/metabase/databases/containers/DatabaseHelpCard/DatabaseHelpCard.tsx
  frontend/src/metabase/databases/containers/DatabaseHelpCard/index.ts
  frontend/src/metabase/databases/selectors.ts
  frontend/src/metabase/entities/model-indexes/actions.unit.spec.ts
  frontend/src/metabase/lib/settings.ts
  frontend/src/metabase/metabot/components/Metabot/Metabot.unit.spec.tsx
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/public/containers/PublicQuestion/PublicQuestion.unit.spec.tsx
  frontend/src/metabase/query_builder/components/QuestionActivityTimeline.unit.spec.js
  frontend/src/metabase/query_builder/components/notebook/ReadOnlyNotebook.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar.unit.spec.js
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/QuestionInfoSidebar.styled.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/QuestionInfoSidebar.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/index.ts
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/tests/cache-granular-controls.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/tests/common.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/tests/content-verification.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/tests/setup.tsx
  frontend/src/metabase/query_builder/containers/QueryViewer.unit.spec.tsx
  frontend/src/metabase/selectors/settings.ts
  frontend/src/metabase/setup/components/DatabaseHelp/DatabaseHelp.tsx
  frontend/src/metabase/setup/components/DatabaseStep/DatabaseStep.tsx
  frontend/test/__support__/server-mocks/index.ts
  frontend/test/__support__/server-mocks/user.ts
Labels: .Team/42 :milky_way:

#32419 Joins should have `:fields` `:all` by default
  src/metabase/lib/join.cljc
  test/metabase/lib/join_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32417 Fix setup alert right after question creation
  e2e/test/scenarios/sharing/alert/email-alert.cy.spec.js
  frontend/src/metabase/query_builder/components/AlertModals.jsx
Labels: .Team/42 :milky_way:

#32420 MLv2: Add `join-lhs-display-name`
  frontend/src/metabase-lib/join.ts
  src/metabase/lib/core.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/util.cljc
  test/metabase/lib/breakout_test.cljc
  test/metabase/lib/card_test.cljc
  test/metabase/lib/column_group_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/js_test.cljs
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/remove_replace_test.cljc
  test/metabase/lib/stage_test.cljc
  test/metabase/lib/test_metadata.cljc
  test/metabase/lib/test_util.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32431 Add more e2e tests for drill options
  e2e/test/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  e2e/test/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
  e2e/test/scenarios/visualizations/drillthroughs/table_drills.cy.spec.js
  frontend/src/metabase/modes/components/modes/TimeseriesMode.jsx
Labels: .Team/42 :milky_way:

#32394 Don't display spinners next to schema in query database selector
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDatabaseSchemaPicker/DataSelectorDatabaseSchemaPicker.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDatabaseSchemaPicker/DataSelectorDatabaseSchemaPicker.unit.spec.js
Labels: backport, .Team/42 :milky_way:

#32428 Expose new granular feature flags
  e2e/test/scenarios/admin/people/people.cy.spec.js
  e2e/test/scenarios/admin/settings/sso/ldap.cy.spec.js
  enterprise/backend/test/metabase_enterprise/api/session_test.clj
  enterprise/backend/test/metabase_enterprise/content_management/api/collection_test.clj
  src/metabase/public_settings.clj
  src/metabase/public_settings/premium_features.clj
Labels: .Team/42 :milky_way:

#31333 Add a prometheus metric for emails sent
  src/metabase/analytics/prometheus.clj
  src/metabase/api/util.clj
  src/metabase/email.clj
  src/metabase/troubleshooting.clj
  test/metabase/analytics/prometheus_test.clj
  test/metabase/email_test.clj
Labels: backport

#32418 47 revert annotate changes
  src/metabase/query_processor/middleware/annotate.clj
  test/metabase/query_processor/middleware/add_source_metadata_test.clj
  test/metabase/query_processor/middleware/annotate_test.clj
  test/metabase/query_processor/util/nest_query_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32447 Update `assert-has-feature` docstring, message and localization
  enterprise/backend/test/metabase_enterprise/content_management/api/collection_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/gtap_test.clj
  src/metabase/api/collection.clj
  src/metabase/api/permissions.clj
  src/metabase/public_settings/premium_features.clj
  test/metabase/api/permissions_test.clj
Labels: .Team/42 :milky_way:

#32198 Return snippets as a flat list on OSS & EE without content-management flag
  enterprise/backend/src/metabase_enterprise/snippet_collections/api/native_query_snippet.clj
  enterprise/backend/src/metabase_enterprise/snippet_collections/models/native_query_snippet/permissions.clj
  enterprise/backend/test/metabase_enterprise/snippet_collections/api/native_query_snippet_test.clj
  enterprise/backend/test/metabase_enterprise/snippet_collections/models/native_query_snippet/permissions_test.clj
  src/metabase/api/collection.clj
  src/metabase/models/native_query_snippet/permissions.clj
  test/metabase/api/collection_test.clj
Labels: .Team/PixelPolice :police_officer:

#32331 Add actions dropdown to object detail modal
  frontend/src/metabase-types/api/actions.ts
  frontend/src/metabase/common/hooks/index.ts
  frontend/src/metabase/common/hooks/use-action-list-query/index.ts
  frontend/src/metabase/common/hooks/use-action-list-query/use-action-list-query.ts
  frontend/src/metabase/common/hooks/use-action-list-query/use-action-list-query.unit.spec.tsx
  frontend/src/metabase/components/EntityMenu/EntityMenu.jsx
  frontend/src/metabase/models/components/ModelDetailPage/ModelActionDetails/ModelActionDetails.tsx
  frontend/src/metabase/models/components/ModelDetailPage/ModelDetailPage.tsx
  frontend/src/metabase/models/containers/ModelDetailPage/ModelDetailPage.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/types.ts
  frontend/src/metabase/visualizations/components/ObjectDetail/utils.ts
  frontend/src/metabase/visualizations/components/ObjectDetail/utils.unit.spec.ts
Labels: visual, .Team/42 :milky_way:

#32436 Remove color-brand-light and text-accent2-hover CSS colors
  frontend/src/metabase/browse/containers/SchemaBrowser.jsx
  frontend/src/metabase/browse/containers/SchemaBrowser.styled.tsx
  frontend/src/metabase/components/Sidebar.css
  frontend/src/metabase/css/core/colors.css
  frontend/src/metabase/query_builder/components/NativeQueryEditor.css
  frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor.styled.tsx
  frontend/src/metabase/styled-components/components/GlobalStyles/GlobalStyles.tsx
Labels: .Team/42 :milky_way:

#32468 Allow clearing dashboard description
  frontend/src/metabase/dashboard/components/DashboardInfoSidebar/DashboardInfoSidebar.styled.tsx
  frontend/src/metabase/dashboard/components/DashboardInfoSidebar/DashboardInfoSidebar.tsx
  frontend/src/metabase/dashboard/components/DashboardInfoSidebar/DashboardInfoSidebar.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardInfoSidebar/index.ts
Labels: backport, .Team/42 :milky_way:

#32398 fix error when archiving custom homepage dashboard
  e2e/test/scenarios/onboarding/home/homepage.cy.spec.js
  frontend/src/metabase-types/api/dashboard.ts
  frontend/src/metabase-types/api/mocks/dashboard.ts
  frontend/src/metabase/dashboard/components/DashboardTabs/test-utils.ts
  frontend/src/metabase/home/components/HomePage/HomePage.tsx
  frontend/src/metabase/home/components/HomePage/HomePage.unit.spec.tsx
Labels: backport, .Team/PixelPolice :police_officer:

#32460 joinable-columns should return a JS array
  src/metabase/lib/js.cljs
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32463 Drop unused computation_job table
  resources/migrations/000_migrations.yaml
Labels: .Team/42 :milky_way:

#32357 Fix edit dashboard calls more APIs than needed
  e2e/test/scenarios/dashboard-filters/dashboard-filters-auto-apply.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  frontend/src/metabase/dashboard/actions/actions.unit.spec.js
  frontend/src/metabase/dashboard/actions/parameters.js
  frontend/src/metabase/dashboard/actions/save.js
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/index.ts
  frontend/src/metabase/dashboard/components/DashboardInfoSidebar/DashboardInfoSidebar.tsx
  frontend/src/metabase/dashboard/components/DashboardInfoSidebar/DashboardInfoSidebar.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardSidebars.jsx
  frontend/src/metabase/dashboard/containers/DashboardHeader.jsx
  frontend/src/metabase/dashboard/containers/DashboardHeader.unit.spec.jsx
  frontend/src/metabase/parameters/reducers.ts
Labels: backport, .Team/42 :milky_way:

#32472 Make setting/getting JWT and SAML settings respect feature flag
  enterprise/backend/src/metabase_enterprise/sso/api/saml.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/sso_settings.clj
  enterprise/backend/test/metabase_enterprise/public_settings_test.clj
  enterprise/backend/test/metabase_enterprise/sso/api/saml_test.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/saml_test.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/sso_settings_test.clj
Labels: .Team/42 :milky_way:

#32479 Add css nonce to emotion
  frontend/src/metabase/app.js
  frontend/src/metabase/lib/dom.js
  package.json
  src/metabase/server/middleware/security.clj
  webpack.config.js
  yarn.lock
Labels: .Team/42 :milky_way:

#32478 Remove CSS re-writing with whitelabel
  enterprise/frontend/src/metabase-enterprise/whitelabel/lib/whitelabel.js
Labels: .Team/42 :milky_way:

#32477 Migrate bg-brand to emotion
  frontend/src/metabase/admin/people/components/AddMemberRow.jsx
  frontend/src/metabase/admin/people/components/AddMemberRow.styled.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/SettingsEditor.jsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/SettingsEditor.styled.tsx
  frontend/src/metabase/admin/settings/components/SettingsUpdatesForm/VersionUpdateNotice/VersionUpdateNotice.jsx
  frontend/src/metabase/admin/settings/components/SettingsUpdatesForm/VersionUpdateNotice/VersionUpdateNotice.styled.tsx
  frontend/src/metabase/components/DateMonthYearWidget/DateMonthYearWidget.styled.tsx
  frontend/src/metabase/components/DateMonthYearWidget/DateMonthYearWidget.tsx
  frontend/src/metabase/components/HeaderModal/HeaderModal.jsx
  frontend/src/metabase/components/HeaderModal/index.jsx
  frontend/src/metabase/css/core/colors.css
  frontend/src/metabase/dashboard/components/DashboardHeaderView.tsx
  frontend/src/metabase/parameters/components/ParameterWidget.css
  frontend/src/metabase/parameters/components/ParameterWidget.jsx
  frontend/src/metabase/parameters/components/ParameterWidget.styled.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions.jsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions.styled.tsx
Labels: .Team/42 :milky_way:

#32500 Use token status to determine whether it's a paid plan
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/databases/containers/DatabaseEditApp.unit.spec.js
  frontend/src/metabase/admin/settings/components/SettingsUpdatesForm/SettingsUpdatesForm.unit.spec.js
  frontend/src/metabase/components/AppBanner/AppBanner.unit.spec.tsx
  frontend/src/metabase/nav/components/DatabasePromptBanner/DatabasePromptBanner.unit.spec.tsx
  frontend/src/metabase/nav/hooks.ts
  frontend/src/metabase/nav/hooks.unit.spec.tsx
  frontend/src/metabase/selectors/selectors.unit.spec.ts
  frontend/src/metabase/selectors/settings.ts
Labels: .Team/42 :milky_way:

#32459 `join-condition-lhs-columns`: remove cols from current/subsequent joins
  frontend/src/metabase-lib/join.ts
  src/metabase/lib/join.cljc
  src/metabase/lib/js.cljs
  test/metabase/lib/join_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32317 Enforce authentication feature flags on EE build
  enterprise/frontend/src/metabase-enterprise/auth/index.js
  enterprise/frontend/src/metabase-enterprise/settings/index.js
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/people/components/GroupDetail.jsx
  frontend/src/metabase/admin/people/containers/AdminPeopleApp.unit.spec.tsx
  frontend/src/metabase/admin/people/selectors.js
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/auth.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/session-timeout-config.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/setup.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/sso-google.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/sso-jwt.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/sso-ldap.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/sso-saml.unit.spec.tsx
  frontend/src/metabase/admin/settings/auth/containers/GoogleAuthForm/GoogleAuthForm.tsx
  frontend/src/metabase/common/utils/plan.ts
  frontend/src/metabase/common/utils/plan.unit.spec.ts
  frontend/src/metabase/selectors/selectors.unit.spec.ts
  frontend/src/metabase/selectors/settings.ts
  webpack.static-viz.config.js
Labels: backport, .Blocker, .Team/PixelPolice :police_officer:

#32272 hiding Card Parameter Mapper header on small cards
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.jsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.styled.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.unit.spec.jsx
  frontend/src/metabase/dashboard/components/DashboardGrid.jsx
  frontend/src/metabase/dashboard/components/grid/utils.js
  frontend/src/metabase/visualizations/shared/utils/sizes.ts
Labels: backport, visual, .Team/PixelPolice :police_officer:

#32491 `with-join-fields` should add join alias to field refs
  src/metabase/lib/field.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/schema.cljc
  src/metabase/lib/schema/join.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/test_util.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32464 BE guard setting embedding-app-origin
  enterprise/backend/test/metabase_enterprise/public_settings_test.clj
  src/metabase/public_settings.clj
  test/metabase/server/middleware/security_test.clj
Labels: .Team/42 :milky_way:

#32486 ordering users by first name in API responses
  e2e/support/cypress_sample_instance_data.js
  e2e/test/scenarios/onboarding/urls.cy.spec.js
  e2e/test/scenarios/permissions/sandboxes.cy.spec.js
  src/metabase/api/user.clj
  test/metabase/api/user_test.clj
Labels: backport, .Team/PixelPolice :police_officer:

#32508 Migrate addCssRule to emotion
  frontend/src/metabase/admin/routes.jsx
  frontend/src/metabase/admin/tasks/components/Logs/Logs.jsx
  frontend/src/metabase/admin/tasks/components/Logs/Logs.styled.tsx
  frontend/src/metabase/admin/tasks/components/Logs/Logs.unit.spec.js
  frontend/src/metabase/admin/tasks/components/Logs/index.ts
  frontend/src/metabase/lib/dom.js
  frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx
  frontend/src/metabase/visualizations/components/LineAreaBarChart.styled.tsx
Labels: visual, .Team/42 :milky_way:

#32522 Centralize EE endpoints error message
  enterprise/backend/src/metabase_enterprise/api/routes.clj
  enterprise/backend/src/metabase_enterprise/api/routes/common.clj
  enterprise/backend/src/metabase_enterprise/content_verification/api/routes.clj
  enterprise/backend/src/metabase_enterprise/sandbox/api/routes.clj
  enterprise/backend/test/metabase_enterprise/advanced_config/api/logs_test.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/api/application_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/api/user_test.clj
  enterprise/backend/test/metabase_enterprise/content_management/api/collection_test.clj
  enterprise/backend/test/metabase_enterprise/content_verification/api/review_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/gtap_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/user_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/api/serialize_test.clj
Labels: .Team/42 :milky_way:

#32524 Guard dashboard subscription filters respect the new feature flag name
  .clj-kondo/config.edn
  enterprise/backend/src/metabase_enterprise/dashboard_subscription_filters/pulse.clj
  enterprise/backend/test/metabase_enterprise/dashboard_subscription_filters/pulse_test.clj
  enterprise/backend/test/metabase_enterprise/pulse_test.clj
  src/metabase/pulse/parameters.clj
  test/metabase/pulse/parameters_test.clj
Labels: visual, .Team/42 :milky_way:

#32465 Fetch-values for implicit actions save QueryExecution in action context
  resources/migrations/000_migrations.yaml
  shared/src/metabase/mbql/schema.cljc
  src/metabase/actions/execution.clj
  src/metabase/api/dashboard.clj
  src/metabase/api/public.clj
  src/metabase/models/action.clj
  src/metabase/models/dashboard_card.clj
  src/metabase/query_processor/middleware/process_userland_query.clj
  test/metabase/actions/execution_test.clj
  test/metabase/api/dataset_test.clj
  test/metabase/api/public_test.clj
  test/metabase/query_processor/middleware/process_userland_query_test.clj
Labels: .Team/42 :milky_way:

#32523 Manual backport 32486
  e2e/support/cypress_sample_instance_data.js
  e2e/test/scenarios/onboarding/urls.cy.spec.js
  e2e/test/scenarios/permissions/sandboxes.cy.spec.js
  src/metabase/api/user.clj
  test/metabase/api/user_test.clj
Labels: was-backported

#32527 Fix passing invalid props to Icon and Link
  frontend/src/metabase/components/Badge/Badge.jsx
  frontend/src/metabase/components/Badge/Badge.styled.tsx
  frontend/src/metabase/components/tree/TreeNode.styled.tsx
  frontend/src/metabase/core/components/BookmarkToggle/BookmarkToggle.styled.tsx
  frontend/src/metabase/core/components/Icon/Icon.tsx
  frontend/src/metabase/core/components/Link/Link.styled.tsx
  frontend/src/metabase/lib/styling/emotion.ts
  frontend/src/metabase/nav/components/AppBar/AppBarToggle.styled.tsx
  frontend/src/metabase/nav/components/SearchBar.styled.tsx
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/SidebarItems.styled.tsx
  package.json
Labels: visual, .Team/42 :milky_way:

#32466 Endpoint to fetch implicit actions param values
  src/metabase/actions.clj
  src/metabase/api/action.clj
  test/metabase/api/action_test.clj
Labels: .Team/42 :milky_way:

#32507 Do not count empty lines and duplicates in action option editor
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.unit.spec.tsx
Labels: .Team/42 :milky_way:

#32197 Add check premium token has :serialization feature in import/export
  enterprise/backend/src/metabase_enterprise/audit_db.clj
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/load_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32519 MLv2: add `databaseID(query)`
  frontend/src/metabase-lib/database.ts
  frontend/src/metabase-lib/v2.ts
  src/metabase/lib/core.cljc
  src/metabase/lib/database.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/metadata.cljc
  test/metabase/lib/breakout_test.cljc
  test/metabase/lib/card_test.cljc
  test/metabase/lib/column_group_test.cljc
  test/metabase/lib/database_test.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/stage_test.cljc
  test/metabase/lib/test_util.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32521 Misc kondo linter improvements & code cleanup
  .clj-kondo/config.edn
  .clj-kondo/hooks/clojure/test.clj
  deps.edn
  test/metabase/lib/aggregation_test.cljc
  test/metabase/lib/breakout_test.cljc
  test/metabase/lib/column_group_test.cljc
  test/metabase/lib/expression_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/filter_test.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/js_test.cljs
  test/metabase/lib/limit_test.cljc
  test/metabase/lib/metadata/calculation_test.cljc
  test/metabase/lib/metric_test.cljc
  test/metabase/lib/native_test.cljc
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/query_test.cljc
  test/metabase/lib/remove_replace_test.cljc
  test/metabase/lib/stage_test.cljc
  test/metabase/lib/table_test.cljc
  test/metabase/lib/temporal_bucket_test.cljc
  test/metabase/lib/types/isa_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32062 gate snippet folders and their permissions behind `snippet_collections` premium feature
  e2e/test/scenarios/native/snippets/snippet-permissions.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/snippets/components/CollectionOptionsButton.jsx
  enterprise/frontend/src/metabase-enterprise/snippets/index.js
  frontend/src/metabase-types/api/collection.ts
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/search.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.unit.spec.jsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx
  frontend/src/metabase/query_builder/components/template_tags/SnippetSidebar/SnippetSidebar.jsx
  frontend/src/metabase/query_builder/components/template_tags/SnippetSidebar/index.ts
  frontend/src/metabase/query_builder/components/template_tags/SnippetSidebar/tests/common.unit.spec.tsx
  frontend/src/metabase/query_builder/components/template_tags/SnippetSidebar/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/query_builder/components/template_tags/SnippetSidebar/tests/premium.unit.spec.tsx
  frontend/src/metabase/query_builder/components/template_tags/SnippetSidebar/tests/setup.tsx
  frontend/src/metabase/query_builder/components/view/View.jsx
  frontend/test/__support__/server-mocks/collection.ts
  frontend/test/__support__/server-mocks/native-query-snippet.ts
Labels: .Team/PixelPolice :police_officer:

#32379 Let non-users unsubscribe from alerts and subscriptions
  e2e/support/helpers/e2e-email-helpers.js
  e2e/test/scenarios/sharing/subscriptions.cy.spec.js
  frontend/src/metabase/containers/ErrorPages.tsx
  frontend/src/metabase/containers/Unsubscribe.styled.tsx
  frontend/src/metabase/containers/Unsubscribe.tsx
  frontend/src/metabase/dashboard/components/DashboardActions.jsx
  frontend/src/metabase/dashboard/components/Sidebar.jsx
  frontend/src/metabase/routes.jsx
  frontend/src/metabase/services.js
  frontend/src/metabase/sharing/components/PulsesListSidebar.jsx
Labels: Reporting/Pulses, backport, visual, .Team/PixelPolice :police_officer:
