Repository metabase/metabase, pull requests merged in 2023-12, with the labels that each got.

#36265 Migrate test support files to TS
  frontend/src/metabase-lib/expressions/__support__/expressions.ts
  frontend/src/metabase-lib/expressions/__support__/shared.ts
  frontend/src/metabase-lib/expressions/suggest.unit.spec.ts
  frontend/src/metabase-types/api/database.ts
  frontend/test/metabase/lib/expressions/formatter.unit.spec.js
Labels: .Team/QueryingComponents

#36238 [Auditv2] Don't show broken move and archive buttons for analytics collections
  e2e/test/scenarios/collections/instance-analytics.cy.spec.js
  frontend/src/metabase/collections/components/ActionMenu/ActionMenu.unit.spec.tsx
  frontend/src/metabase/collections/utils.ts
  frontend/src/metabase/collections/utils.unit.spec.ts
Labels: no-backport, .Team/AdminWebapp

#36249 Rework auto-generated PKs for CSV uploads
  src/metabase/driver/h2.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  src/metabase/upload.clj
  src/metabase/upload/parsing.clj
  test/metabase/api/card_test.clj
  test/metabase/upload_test.clj
Labels: no-backport, .Team/BackendComponents

#36276 Restrict available-segments to the first stage
  src/metabase/lib/segment.cljc
  test/metabase/lib/segment_test.cljc
Labels: .Team/QueryProcessor, no-backport

#36245 Document and test adding `results_metadata` to qp middleware for static viz
  .clj-kondo/config.edn
  deps.edn
  dev/src/dev/render_png.clj
  enterprise/backend/test/metabase_enterprise/sandbox/pulse_test.clj
  src/metabase/pulse.clj
  src/metabase/pulse/render/body.clj
  test/metabase/pulse/pulse_integration_test.clj
  test/metabase/pulse/render_test.clj
  test/metabase/query_processor/middleware/results_metadata_test.clj
Labels: visual, no-backport, .Team/DashViz

#36281 [MLv2] Implement `drillThru()` for pivot drills; add BE unit tests
  src/metabase/lib/drill_thru/pivot.cljc
  test/metabase/lib/drill_thru/pivot_test.cljc
  test/metabase/lib/drill_thru/test_util.cljc
Labels: no-backport

#36314 Update visitDashboard e2e helper to be tabs-aware
  e2e/support/helpers/e2e-misc-helpers.js
  e2e/test/scenarios/dashboard/tabs.cy.spec.js
Labels: .CI & Tests, backport, .Team/AdminWebapp

#36223 store query_execution.cache_hash
  enterprise/backend/test/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions_test.clj
  resources/migrations/001_update_migrations.yaml
  src/metabase/query_processor/middleware/cache.clj
  src/metabase/query_processor/middleware/process_userland_query.clj
  test/metabase/api/dataset_test.clj
  test/metabase/query_processor/middleware/cache_test.clj
  test/metabase/query_processor/middleware/process_userland_query_test.clj
  test/metabase/query_processor/streaming_test.clj
  test/metabase/query_processor_test.clj
Labels: .Team/QueryProcessor, no-backport, .Team/BackendComponents

#36339 Fix failed E2E from 61f2b28dd62938ae4f66434b1678e227bb0c8d0d
  frontend/src/metabase/entities/containers/EntityForm.jsx
Labels: flaky-test-fix, no-backport, .Team/Embedding

#36333 Make sure the app DB is initialized
  enterprise/backend/test/metabase_enterprise/audit_app/permissions_test.clj
Labels: flaky-test-fix, .Team/QueryProcessor, no-backport

#36340 [Storybook] Build cljs with NODE_ENV=development to override default settings
  package.json
Labels: no-backport, chromatic, .Team/QueryingComponents

#36109 Migrate suggestions to MLv2
  e2e/test/scenarios/admin/datamodel/metrics.cy.spec.js
  frontend/src/metabase-lib/expressions/__support__/expressions.js
  frontend/src/metabase-lib/expressions/__support__/expressions.ts
  frontend/src/metabase-lib/expressions/__support__/shared.ts
  frontend/src/metabase-lib/expressions/index.js
  frontend/src/metabase-lib/expressions/suggest.ts
  frontend/src/metabase-lib/expressions/suggest.unit.spec.ts
  frontend/src/metabase-lib/metadata.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase-types/api/database.ts
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.tsx
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.unit.spec.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/NotebookStep/NotebookStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/AggregateStep/AggregateStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/BreakoutStep/BreakoutStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/DataStep/DataStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/ExpressionStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/ExpressionStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/LimitStep/LimitStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/SortStep/SortStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/types.ts
  frontend/test/metabase/lib/expressions/formatter.unit.spec.js
Labels: .Team/QueryingComponents

#36335 [webpack] Always write to disk
  package.json
  webpack.config.js
  yarn.lock
Labels: no-backport, .Team/QueryingComponents

#36269 Fix all unused arg errors
  .eslintrc
  frontend/src/metabase-lib/Dimension.ts
  frontend/src/metabase-lib/expressions/pratt/compiler.ts
  frontend/src/metabase-lib/queries/Query.ts
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/src/metabase-lib/queries/structured/Filter.ts
  frontend/src/metabase-lib/queries/structured/MBQLClause.ts
  frontend/src/metabase/admin/settings/containers/PremiumEmbeddingLicensePage/PremiumEmbeddingLicensePage.unit.spec.tsx
  frontend/src/metabase/collections/components/CollectionHeader/CollectionHeader.tsx
  frontend/src/metabase/collections/components/CollectionHeader/tests/setup.tsx
  frontend/src/metabase/components/Calendar/Calendar.unit.spec.tsx
  frontend/src/metabase/components/SingleSelectListField/SingleSelectListField.tsx
  frontend/src/metabase/containers/ItemPicker/Item.tsx
  frontend/src/metabase/containers/ItemPicker/ItemPickerView.tsx
  frontend/src/metabase/core/components/EditableText/EditableText.tsx
  frontend/src/metabase/entities/collections/collections.ts
  frontend/src/metabase/entities/model-indexes/model-indexes.ts
  frontend/src/metabase/lib/formatting/image.tsx
  frontend/src/metabase/lib/formatting/value.unit.spec.tsx
  frontend/src/metabase/lib/promise.ts
  frontend/src/metabase/lib/redux/hooks.unit.spec.tsx
  frontend/src/metabase/nav/components/DatabasePromptBanner/DatabasePromptBanner.tsx
  frontend/src/metabase/plugins/components/PluginPlaceholder/PluginPlaceholder.tsx
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/query_builder/actions/core/initializeQB.unit.spec.ts
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorTablePicker/DataSelectorTablePicker.styled.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetFieldMetadataSidebar/SemanticTypePicker/FKTargetPicker.tsx
  frontend/src/metabase/query_builder/components/QueryDownloadWidget/QueryDownloadWidget.tsx
  frontend/src/metabase/query_builder/components/QueryValidationError/ErrorActionButton.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorHelpText.stories.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorHelpText.tsx
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterFieldSearch.tsx
  frontend/src/metabase/query_builder/components/notebook/lib/steps.ts
  frontend/src/metabase/query_builder/components/view/ViewFooter.jsx
  frontend/src/metabase/redux/uploads.ts
  frontend/src/metabase/search/containers/SearchApp.unit.spec.tsx
  frontend/src/metabase/static-viz/components/LineAreaBarChart/utils/series.tsx
  frontend/src/metabase/static-viz/components/Values/Values.tsx
  frontend/src/metabase/static-viz/components/XYChart/shapes/AreaSeries.tsx
  frontend/src/metabase/static-viz/components/XYChart/shapes/AreaSeriesStacked.tsx
  frontend/src/metabase/static-viz/components/XYChart/shapes/LineSeries.tsx
  frontend/src/metabase/status/components/FileUploadStatus/FileUploadStatus.unit.spec.tsx
  frontend/src/metabase/timelines/questions/containers/EditEventModal/EditEventModal.tsx
  frontend/src/metabase/ui/components/inputs/Checkbox/Checkbox.styled.tsx
  frontend/src/metabase/ui/components/inputs/Radio/Radio.styled.tsx
  frontend/src/metabase/ui/components/overlays/Popover/Popover.styled.tsx
  frontend/src/metabase/ui/components/utils/Paper/Paper.styled.tsx
  frontend/src/metabase/visualizations/components/ClickActions/ClickActionsPopover.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ClickActions/ClickActionsView.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/utils.ts
  frontend/src/metabase/visualizations/index.ts
Labels: backport, visual, .Team/Embedding

#36312 Fix broken auto-wiring when adding a new card to a dashboard
  e2e/test/scenarios/dashboard-filters/parameters.cy.spec.js
  frontend/src/metabase/dashboard/actions/auto-wire-parameters/actions.ts
  frontend/src/metabase/dashboard/actions/cards.js
Labels: no-backport, .Team/Embedding

#36329 Ensure collections are loaded before showing entity copy form
  frontend/src/metabase/entities/containers/EntityCopyModal.tsx
Labels: .CI & Tests, Administration/Audit, backport, .Team/AdminWebapp

#36094 Enable auto commit
  src/metabase/driver/sql_jdbc/execute.clj
Labels: backport, .Team/QueryProcessor

#36244 Allow toggling of the dashboard subscription sidebar from the icon
  e2e/support/helpers/e2e-email-helpers.js
  e2e/test/scenarios/sharing/subscriptions.cy.spec.js
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx
Labels: no-backport

#36356 [docs] Update collections.md
  docs/exploration-and-organization/collections.md
Labels: Type:Documentation, backport

#36355 Manually backport "Enable auto commit (#36094)"
  src/metabase/driver/sql_jdbc/execute.clj
Labels: was-backported, .Team/QueryProcessor

#36218 Test for #35319
  test/metabase/api/card_test.clj
Labels: .metabase-lib, .Team/QueryProcessor, no-backport

#36380 fix backport comment command
  .github/actions/verify-membership/action.yml
  .github/actions/verify-membership/verify_membership.sh
  .github/workflows/auto-assign.yml
  .github/workflows/auto-backport.yml
  .github/workflows/backport.yml
  .github/workflows/percy-issue-comment.yml
  .github/workflows/require-percy-tests.yml
Labels: no-backport, .Team/DashViz

#36318 [MLv2] Underlying records: use card name as label for nested queries
  src/metabase/lib/drill_thru/underlying_records.cljc
  test/metabase/lib/drill_thru/underlying_records_test.cljc
Labels: .Team/QueryProcessor, no-backport

#36257 MB_CLOUD_GATEWAY_IPS is settable from env var
  e2e/test/scenarios/filters/filter-types.cy.spec.js
  src/metabase/public_settings.clj
  test/metabase/driver/common_test.clj
  test/metabase/public_settings_test.clj
Labels: backport, .Team/AdminWebapp

#36357 Ensure Metadata is Propagated for Standalone Pulse Cards
  src/metabase/pulse/util.clj
  test/metabase/pulse/pulse_integration_test.clj
Labels: visual, no-backport, .Team/DashViz

#36121 Sync dynamic tables for snowflake
  docs/developers-guide/driver-changelog.md
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
  modules/drivers/snowflake/test/metabase/test/data/snowflake.clj
  modules/drivers/sqlite/src/metabase/driver/sqlite.clj
  src/metabase/driver/sql_jdbc/sync.clj
  src/metabase/driver/sql_jdbc/sync/describe_database.clj
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
  src/metabase/driver/sql_jdbc/sync/interface.clj
Labels: backport, .Team/BackendComponents

#35481 Use `malli=?` instead of `#hawk/malli` etc
  deps.edn
  enterprise/backend/test/metabase_enterprise/sandbox/api/gtap_test.clj
  test/metabase/api/automagic_dashboards_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/search_test.clj
  test/metabase/models/dashboard_test.clj
  test/metabase/test.clj
Labels: no-backport, .Team/BackendComponents

#36394 Task ns cleanup: use malli and remove log translation
  src/metabase/task.clj
  src/metabase/task/send_anonymous_stats.clj
  src/metabase/task/send_pulses.clj
  src/metabase/task/sync_databases.clj
  src/metabase/task/task_history_cleanup.clj
  src/metabase/task/truncate_audit_tables.clj
  src/metabase/task/upgrade_checks.clj
Labels: no-backport, .Team/BackendComponents

#36361 Uploads: Make the display name for the _mb_row_id column "_mb_row_id"
  src/metabase/api/card.clj
  src/metabase/upload.clj
  test/metabase/api/card_test.clj
Labels: backport, .Team/BackendComponents

#36401 dashboard_tab.entity_id is nullable now, makes drop-entity-ids work
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/entity_ids_test.clj
  resources/migrations/001_update_migrations.yaml
Labels: backport, .Team/BackendComponents

#36217 Add column-name and table-name to fk-filter drill's display-info
  frontend/src/metabase-lib/drills.unit.spec.ts
  frontend/src/metabase-lib/tests/drills-fk-filter.unit.spec.ts
  frontend/src/metabase-lib/types.ts
  src/metabase/lib/drill_thru/fk_filter.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/schema/drill_thru.cljc
  test/metabase/lib/drill_thru/fk_filter_test.cljc
Labels: .Team/QueryProcessor, no-backport

#36385 Do not return zoom/pk/fk-details drills for null cell values
  src/metabase/lib/drill_thru/object_details.cljc
  test/metabase/lib/drill_thru/fk_details_test.cljc
  test/metabase/lib/drill_thru/pk_test.cljc
  test/metabase/lib/drill_thru/zoom_test.cljc
Labels: .Team/QueryProcessor, no-backport

#36031 Expressions in AggregationPicker without legacy query
  e2e/test/scenarios/admin/datamodel/metrics.cy.spec.js
  e2e/test/scenarios/filters/filter.cy.spec.js
  e2e/test/scenarios/joins/reproductions/20519-cannot-join-on-aggregation-with-implicit-joins-and-nested-query.cy.spec.js
  e2e/test/scenarios/models/reproductions/28193-cannot-use-custom-column.cy.spec.js
  e2e/test/scenarios/question/notebook.cy.spec.js
  e2e/test/scenarios/question/reproductions/15714-cc-postgres-percentile-accepts-two-params.cy.spec.js
  e2e/test/scenarios/question/reproductions/17512.cy.spec.js
  e2e/test/scenarios/question/reproductions/18207-string-min-max.cy.spec.js
  e2e/test/scenarios/question/reproductions/6239-sort-using-cust-exp.cy.spec.js
  e2e/test/scenarios/question/summarization.cy.spec.js
  frontend/src/metabase-lib/aggregation.ts
  frontend/src/metabase-lib/expression.ts
  frontend/src/metabase-lib/expressions/process.js
  frontend/src/metabase-lib/metadata.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.tsx
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.unit.spec.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/AggregateStep/AggregateStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/AggregateStep/AggregateStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/ExpressionStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/AddAggregationButton/AddAggregationButton.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/AggregationItem/AggregationItem.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeSidebar.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeSidebar.unit.spec.tsx
Labels: no-backport, .Team/QueryingComponents

#36402 Add Metabase version argument to Dockerfile
  Dockerfile
Labels: backport

#36378 Handle Release Notes for Release Candidates
  .github/workflows/release.yml
  release/README.md
  release/release-offline.ts
  release/src/github.ts
  release/src/release-notes.ts
Labels: .Building & Releasing, .CI & Tests, no-backport, .Team/AdminWebapp

#36206 Fix card filter connected to a field not causing an update
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.jsx
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeaderView.tsx
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.unit.spec.tsx
Labels: backport, .Team/QueryingComponents

#36255 Adding pagination to All Personal Collections page
  e2e/test/scenarios/collections/personal-collections.cy.spec.js
  e2e/test/scenarios/onboarding/urls.cy.spec.js
  frontend/src/metabase-types/api/mocks/user.ts
  frontend/src/metabase-types/api/user.ts
  frontend/src/metabase/common/hooks/use-user-list-query/use-user-list-query.ts
  frontend/src/metabase/common/hooks/use-user-list-query/use-user-list-query.unit.spec.tsx
  frontend/src/metabase/components/BrowserCrumbs/BrowserCrumbs.jsx
  frontend/src/metabase/containers/UserCollectionList.jsx
  frontend/src/metabase/containers/UserCollectionList.styled.tsx
  frontend/src/metabase/containers/UserCollectionList.tsx
  frontend/src/metabase/containers/UserCollectionList.unit.spec.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarView.tsx
  frontend/src/metabase/routes.jsx
Labels: no-backport, .Team/AdminWebapp

#36319 [MLv2] Underlying records: show drills on clicks with no `:column`
  src/metabase/lib/drill_thru/underlying_records.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/schema/drill_thru.cljc
  test/metabase/lib/drill_thru/underlying_records_test.cljc
Labels: .Team/QueryProcessor, no-backport

#36152 Filter values leaked in API request on Embedding
  .clj-kondo/config.edn
  enterprise/backend/test/metabase_enterprise/dashboard_subscription_filters/pulse_test.clj
  src/metabase/api/embed.clj
  src/metabase/email/messages.clj
  src/metabase/models/params.clj
  src/metabase/pulse.clj
  test/metabase/api/embed_test.clj
  test/metabase/models/params_test.clj
  test/metabase/pulse/parameters_test.clj
Labels: backport, .Team/AdminWebapp

#36360 Adding markdown support to search result descriptions
  e2e/test/scenarios/onboarding/search/search.cy.spec.js
  frontend/src/metabase/search/components/SearchResult/SearchResult.styled.tsx
  frontend/src/metabase/search/components/SearchResult/SearchResult.tsx
Labels: backport, .Team/AdminWebapp

#36427 docs - hide when empty
  docs/dashboards/introduction.md
Labels: Type:Documentation, backport

#35184 Update Trend chart copy for special cases (on frontend)
  e2e/test/scenarios/visualizations-tabular/smartscalar-trend.cy.spec.js
  frontend/src/metabase/css/dashboard.css
  frontend/src/metabase/lib/formatting/date.tsx
  frontend/src/metabase/lib/formatting/date.unit.spec.tsx
  frontend/src/metabase/lib/formatting/types.ts
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.jsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.styled.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.unit.spec.js
  frontend/src/metabase/visualizations/visualizations/SmartScalar/compute.js
  frontend/src/metabase/visualizations/visualizations/SmartScalar/compute.unit.spec.js
  frontend/src/metabase/visualizations/visualizations/SmartScalar/utils.ts
Labels: visual, no-backport, .Team/DashViz

#36431 Updating default `number-formatter` for percents
  src/metabase/pulse/render/common.clj
  test/metabase/pulse/pulse_integration_test.clj
  test/metabase/pulse/render/common_test.clj
  test/metabase/pulse/render_test.clj
Labels: visual, no-backport, .Team/DashViz

#36375 Fix scrolling in filter picker
  frontend/src/metabase/querying/components/FilterPicker/FilterColumnPicker/FilterColumnPicker.tsx
Labels: no-backport, .Team/QueryingComponents

#36440 Return `:pk` drills for non-PK values in rows with multiple PKs
  src/metabase/lib/drill_thru/common.cljc
  src/metabase/lib/drill_thru/fk_details.cljc
  src/metabase/lib/drill_thru/object_details.cljc
  src/metabase/lib/drill_thru/pk.cljc
  src/metabase/lib/drill_thru/zoom.cljc
  src/metabase/lib/schema/drill_thru.cljc
  test/metabase/lib/drill_thru/pk_test.cljc
  test/metabase/lib/drill_thru/underlying_records_test.cljc
  test/metabase/lib/drill_thru/zoom_test.cljc
Labels: .Team/QueryProcessor, no-backport

#36389 Return row count: 2 instead of negative row count
  src/metabase/lib/drill_thru/underlying_records.cljc
  test/metabase/lib/drill_thru/underlying_records_test.cljc
Labels: .Team/QueryProcessor, no-backport

#36407 FE: Things to do after pulses are removed
  frontend/src/metabase/collections/components/BaseTableItem.jsx
Labels: .Team/BackendComponents

#35975 Fix click behavior link to dashboards/questions not using client router
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  frontend/src/metabase/lib/dom.js
  frontend/src/metabase/visualizations/lib/action.js
  frontend/src/metabase/visualizations/lib/action.unit.spec.ts
Labels: backport, visual, .Team/Embedding

#36434 team: add levex to BEC
  .github/team.json
Labels: no-backport

#36410 Backport: dashboard_tab.entity_id is nullable now, makes drop-entity-ids work
  enterprise/backend/test/metabase_enterprise/serialization/v2/entity_ids_test.clj
  resources/migrations/000_migrations.yaml
Labels: was-backported

#36396 Expressions in FilterPicker without legacy query
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.unit.spec.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/FilterStep/FilterStep.tsx
  frontend/src/metabase/query_builder/components/view/QuestionFilters/QuestionFilters.tsx
  frontend/src/metabase/querying/components/FilterPicker/FilterPicker.tsx
  frontend/src/metabase/querying/components/FilterPicker/FilterPicker.unit.spec.tsx
Labels: no-backport, .Team/QueryingComponents

#36349 add Snyk workflow to run on master/release commits
  .github/scripts/write-poms.sh
  .github/workflows/snyk.yml
Labels: no-backport, .Team/BackendComponents

#36460 put reaction on the comment ASAP when reacting to backport command
  .github/workflows/backport.yml
Labels: no-backport, .Team/BackendComponents

#36404 Move upload-csv! to metabase.upload
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  enterprise/backend/test/metabase_enterprise/upload_test.clj
  src/metabase/api/card.clj
  src/metabase/api/database.clj
  src/metabase/driver/h2.clj
  src/metabase/upload.clj
  test/metabase/api/card_test.clj
  test/metabase/upload_test.clj
Labels: backport, .Team/BackendComponents

#35118 add dominant-baseline workaround for echarts
  frontend/src/metabase/static-viz/lib/svg.ts
  frontend/src/metabase/static-viz/lib/svg.unit.spec.ts
  jest.config.js
  package.json
  yarn.lock
Labels: visual, .Team/PixelPolice (DEPRECATED), .Team/DashViz

#34820 create unified BE path for isomorphic visualizations
  dev/src/dev/render_png.clj
  frontend/src/metabase/static-viz/containers/IsomorphicStaticChart/IsomorphicStaticChart.tsx
  frontend/src/metabase/static-viz/containers/IsomorphicStaticChart/index.ts
  frontend/src/metabase/static-viz/containers/IsomorphicStaticChart/types.ts
  frontend/src/metabase/static-viz/containers/StaticChart/StaticChart.tsx
  frontend/src/metabase/static-viz/lib/settings.ts
  resources/frontend_shared/static_viz_interface.js
  src/metabase/pulse/render.clj
  src/metabase/pulse/render/body.clj
  src/metabase/pulse/render/js_svg.clj
  src/metabase/pulse/util.clj
  test/metabase/pulse/render/body_test.clj
  test/metabase/pulse/render/js_svg_test.clj
  test/metabase/pulse/render_test.clj
Labels: visual, .Team/DashViz

#35297 update cartesian chart columns utils and types
  frontend/src/metabase/static-viz/components/RowChart/utils/labels.ts
  frontend/src/metabase/static-viz/lib/format.ts
  frontend/src/metabase/visualizations/lib/graph/columns.ts
  frontend/src/metabase/visualizations/shared/utils/data.ts
  frontend/src/metabase/visualizations/shared/utils/series.ts
  frontend/src/metabase/visualizations/visualizations/RowChart/RowChart.tsx
  frontend/src/metabase/visualizations/visualizations/RowChart/utils/events.ts
  frontend/src/metabase/visualizations/visualizations/RowChart/utils/format.ts
  frontend/src/metabase/visualizations/visualizations/RowChart/utils/warnings.ts
Labels: visual, .Team/DashViz

#35300 add basic static combo chart built with echarts
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.tsx
  frontend/src/metabase/static-viz/components/ComboChart/index.ts
  frontend/src/metabase/static-viz/components/ComboChart/settings.ts
  frontend/src/metabase/static-viz/containers/IsomorphicStaticChart/IsomorphicStaticChart.tsx
  frontend/src/metabase/static-viz/containers/IsomorphicStaticChart/types.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.unit.spec.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/types.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/lib/series.ts
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/src/metabase/visualizations/lib/settings/series.js
  frontend/src/metabase/visualizations/shared/settings/cartesian-chart.ts
  frontend/src/metabase/visualizations/shared/settings/series.ts
  frontend/src/metabase/visualizations/shared/utils/data.ts
  frontend/src/metabase/visualizations/types/visualization.ts
  frontend/src/metabase/visualizations/visualizations/RowChart/utils/events.ts
Labels: visual, .Team/DashViz

#35301 apply breakout series sorting
  frontend/src/metabase/static-viz/components/ComboChart/settings.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
Labels: visual, .Team/DashViz

#35307 Support Y-axis split
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/stories-data.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.unit.spec.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
Labels: visual, .Team/DashViz

#35321 add legend to the static combo chart
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.tsx
  frontend/src/metabase/static-viz/components/ComboChart/settings.ts
  frontend/src/metabase/static-viz/components/Legend/Legend.tsx
  frontend/src/metabase/static-viz/components/Legend/constants.ts
  frontend/src/metabase/static-viz/components/Legend/utils.ts
  frontend/src/metabase/static-viz/components/RowChart/RowChart.tsx
  frontend/src/metabase/static-viz/components/XYChart/XYChart.tsx
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.unit.spec.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/legend.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/types.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/lib/series.ts
  frontend/src/metabase/visualizations/lib/settings/series.js
  frontend/src/metabase/visualizations/shared/settings/series.ts
Labels: visual, .Team/DashViz

#35395 support custom y-axis range
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/types.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/axis.ts
Labels: visual, .Team/DashViz

#35573 Align combo chart ticks, axes names
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.tsx
  frontend/src/metabase/static-viz/components/ComboChart/settings.ts
  frontend/src/metabase/static-viz/components/ComboChart/stories-data.ts
  frontend/src/metabase/static-viz/components/Legend/utils.ts
  frontend/src/metabase/static-viz/constants/char-sizes.ts
  frontend/src/metabase/static-viz/containers/StaticChart/StaticChart.tsx
  frontend/src/metabase/static-viz/index.js
  frontend/src/metabase/static-viz/lib/text.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/types.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/format.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/grid.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/style.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/types.ts
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/src/metabase/visualizations/shared/settings/cartesian-chart.ts
Labels: visual, .Team/DashViz

#35922 Support histogram X-axis, improve X-axis type inferrence
  frontend/src/metabase/static-viz/components/ComboChart/settings.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/format.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/src/metabase/visualizations/shared/settings/cartesian-chart.ts
Labels: visual, .Team/DashViz

#35923 fix charts broken when there is right y-axis only
  frontend/src/metabase/visualizations/echarts/cartesian/option/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
Labels: visual, .Team/DashViz

#36013 Fix combined cards with dimensions that have different units
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.unit.spec.ts
Labels: visual, .Team/DashViz

#35345 combo chart goal line
  frontend/src/metabase/visualizations/echarts/cartesian/option/goal-line.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
Labels: visual, .Team/PixelPolice (DEPRECATED), .Team/DashViz

#35997 combo chart trend line
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase-types/api/dataset.ts
  frontend/src/metabase-types/api/insight.ts
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/stories-data.ts
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/auto-y-split.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/messed-up-axis.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/trend-combo-log.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/trend-combo-power.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/trend-combo.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/trend-multi-series-area.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/trend-multi-series-bar.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/trend-multi-series-line.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/trend-multi-series-normalized-stacked-area.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/trend-multi-series-normalized-stacked-bar.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/trend-multi-series-stacked-area.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/trend-multi-series-stacked-bar.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/trend-single-series-area.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/trend-single-series-bar.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/trend-single-series-line.json
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/types.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/trend-line.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/utils.ts
Labels: visual, .Team/DashViz

#36486 remove duplicate function
  frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts
Labels: visual, .Team/DashViz

#36446 Ensure that admin perms override group manager in GET /api/user
  src/metabase/api/user.clj
  test/metabase/api/user_test.clj
Labels: backport, .Team/AdminWebapp

#36445 Misc zoom-in-bins drill fixes
  src/metabase/lib/binning.cljc
  src/metabase/lib/binning/util.cljc
  src/metabase/lib/drill_thru.cljc
  src/metabase/lib/drill_thru/underlying_records.cljc
  src/metabase/lib/drill_thru/zoom_in_bins.cljc
  src/metabase/lib/field.cljc
  src/metabase/util.cljc
  test/metabase/lib/binning_test.cljc
  test/metabase/lib/drill_thru/sort_test.cljc
  test/metabase/lib/drill_thru/zoom_in_bins_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/metadata/calculation_test.cljc
Labels: .Team/QueryProcessor, no-backport

#36449 quick-filter drill should return contains and does-not-contain for text columns
  frontend/src/metabase-lib/tests/drills-quick-filter.unit.spec.ts
  src/metabase/lib/drill_thru/quick_filter.cljc
  src/metabase/lib/metadata/calculation.cljc
  test/metabase/lib/drill_thru/pk_test.cljc
  test/metabase/lib/drill_thru/quick_filter_test.cljc
  test/metabase/lib/drill_thru_test.cljc
Labels: .Team/QueryProcessor, no-backport

#36448 Misc `zoom-in-geographic` drill fixes
  frontend/src/metabase-lib/tests/drills-zoom-in-binning.unit.spec.ts
  frontend/src/metabase-lib/tests/drills-zoom-in-geographic.unit.spec.ts
  frontend/src/metabase-types/api/dataset.ts
  src/metabase/lib/convert.cljc
  src/metabase/lib/drill_thru.cljc
  src/metabase/lib/drill_thru/zoom_in_geographic.cljc
  test/metabase/lib/drill_thru/zoom_in_geographic_test.cljc
Labels: .Team/QueryProcessor, no-backport

#36443 [MLv2] Implement `automatic-insights` drill
  src/metabase/lib/drill_thru.cljc
  src/metabase/lib/drill_thru/automatic_insights.cljc
  src/metabase/lib/drill_thru/quick_filter.cljc
  src/metabase/lib/drill_thru/underlying_records.cljc
  src/metabase/lib/js/metadata.cljs
  src/metabase/lib/metadata.cljc
  src/metabase/lib/schema/drill_thru.cljc
  test/metabase/lib/drill_thru/automatic_insights_test.cljc
  test/metabase/lib/drill_thru_test.cljc
  test/metabase/lib/test_metadata.cljc
Labels: .Team/QueryProcessor, no-backport

#36505 Misc zoom-in-timeseries drill fixes
  frontend/src/metabase-lib/tests/drills-zoom-in-timeseries.unit.spec.ts
  src/metabase/lib/drill_thru/zoom_in_timeseries.cljc
  test/metabase/lib/drill_thru/zoom_in_timeseries_test.cljc
Labels: .Team/QueryProcessor, no-backport

#36387 Fix erroring migration and add test to exercise MB_DB_AUTOMIGRATE=false option
  resources/migrations/001_update_migrations.yaml
  test/metabase/db/setup_test.clj
  test_resources/error-migration.yaml
Labels: backport, .Team/AdminWebapp

#36480 [Help-link] test: remove e2e for a the single setting scenario
  e2e/test/scenarios/admin-2/whitelabel.cy.spec.js
Labels: .Team/Embedding

#36478 [Help link] set error to null when typing
  e2e/test/scenarios/admin-2/whitelabel.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/HelpLinkSettings/HelpLinkSettings.tsx
Labels: .Team/Embedding

#36479 add target branch name to backporting branch for less conflicts
  .github/workflows/backport.yml
Labels: no-backport, .Team/BackendComponents

#36453 🍒 Manual backported "Fix click behavior link to dashboards/questions not using client router"
  e2e/support/commands/api/dashboard.js
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  frontend/src/metabase/lib/dom.js
  frontend/src/metabase/visualizations/lib/action.js
  frontend/src/metabase/visualizations/lib/action.unit.spec.ts
  frontend/src/metabase/visualizations/types.ts
Labels: was-backported, visual

#36501 Tweak code block in doc
  docs/installation-and-operation/running-the-metabase-jar-file.md
Labels: Type:Documentation, no-backport

#36483 Fix dashboard filter width in edit mode
  frontend/src/metabase/parameters/components/ParameterWidget/ParameterWidget.jsx
  frontend/src/metabase/parameters/components/ParameterWidget/ParameterWidget.styled.ts
Labels: backport, .Team/DashViz

#36522 test: add e2e case to handle the oss/no-whitelabel enabled case
  e2e/test/scenarios/admin-2/whitelabel.cy.spec.js
Labels: .Team/Embedding

#36526 fix linting issues on the help link feature branch
  frontend/src/metabase/nav/components/AppBar/AppBarLarge.tsx
  frontend/src/metabase/nav/components/AppBar/AppBarSmall.tsx
Labels: .Team/Embedding

#36328 BE settings for whitelabeled help link
  src/metabase/analytics/stats.clj
  src/metabase/public_settings.clj
  test/metabase/analytics/stats_test.clj
  test/metabase/public_settings_test.clj
Labels: .Team/AdminWebapp

#36493 Enabling converting simple value expressions from pMBQL to legacy
  src/metabase/lib/expression.cljc
  src/metabase/lib/js.cljs
  test/metabase/lib/expression_test.cljc
  test/metabase/lib/js_test.cljs
Labels: backport, .metabase-lib, .Team/QueryProcessor

#36529 [MLv2] Unskip FE integration tests for automatic-insights drills
  frontend/src/metabase-lib/tests/drills-automatic-insights.unit.spec.ts
Labels: .Team/QueryProcessor, no-backport

#36484 Apply column formatting to CSV exports
  e2e/test/scenarios/sharing/downloads/reproductions/10803-timestamp-formatting.cy.spec.js
  src/metabase/email/messages.clj
  src/metabase/pulse/render/body.clj
  src/metabase/pulse/render/common.clj
  src/metabase/pulse/render/datetime.clj
  src/metabase/query_processor/streaming/csv.clj
  test/metabase/pulse/pulse_integration_test.clj
  test/metabase/pulse/render/body_test.clj
  test/metabase/pulse/render/common_test.clj
  test/metabase/pulse/render/datetime_test.clj
  test/metabase/query_processor/streaming/csv_test.clj
  test/metabase/query_processor/streaming_test.clj
Labels: visual, no-backport, .Team/DashViz

#36500 [MLv2] drop-stage-if-empty
  src/metabase/lib/core.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/stage.cljc
  test/metabase/lib/stage_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor, no-backport

#36172 [Help link] feature branch
  e2e/test/scenarios/admin-2/whitelabel.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/HelpLinkSettings/HelpLinkSettings.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/HelpLinkSettings/index.ts
  enterprise/frontend/src/metabase-enterprise/whitelabel/index.js
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/nav/components/AppBar/AppBarLarge.tsx
  frontend/src/metabase/nav/components/AppBar/AppBarSmall.tsx
  frontend/src/metabase/nav/components/ProfileLink.unit.spec.js
  frontend/src/metabase/nav/components/ProfileLink/ProfileLink.jsx
  frontend/src/metabase/nav/components/ProfileLink/ProfileLink.unit.spec.tsx
  frontend/src/metabase/nav/components/ProfileLink/index.ts
  frontend/src/metabase/nav/components/ProfileLink/useHelpLink.ts
  src/metabase/analytics/stats.clj
  src/metabase/public_settings.clj
  test/metabase/analytics/stats_test.clj
  test/metabase/public_settings_test.clj
Labels: no-backport, .Team/Embedding

#36189 Fix settings jwt
  enterprise/frontend/src/metabase-enterprise/auth/components/SettingsJWTForm/SettingsJWTForm.tsx
  enterprise/frontend/src/metabase-enterprise/auth/components/SettingsJWTForm/SettingsJWTForm.unit.spec.tsx
Labels: no-backport, .Team/AdminWebapp

#36534 Revert "Fix card filter connected to a field not causing an update"
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.jsx
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeaderView.tsx
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.unit.spec.tsx
Labels: backport, .Team/DashViz

#36518 Upgrade @testing-library/jest-dom to address security issue with its dependency
  jest.config.js
  package.json
  yarn.lock
Labels: backport, .Team/QueryingComponents

#36546 Add "refresh_downstream" icon
  frontend/src/metabase/core/components/Icon/icons/index.ts
  frontend/src/metabase/core/components/Icon/icons/refresh_downstream.svg
Labels: no-backport, .Team/DashViz

#36547 Add icon search to Storybook
  frontend/src/metabase/core/components/Icon/Icon.stories.tsx
Labels: no-backport, .Team/DashViz

#36503 Use stretch variant on switch
  frontend/src/metabase/search/components/ToggleSidebarFilter/ToggleSidebarFilter.styled.tsx
  frontend/src/metabase/search/components/ToggleSidebarFilter/ToggleSidebarFilter.tsx
Labels: backport, .Team/AdminWebapp

#36528 Update server side relative datetime generation honeysql
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  modules/drivers/redshift/test/metabase/driver/redshift_test.clj
Labels: .Team/QueryProcessor, no-backport

#36490 Refactoring formatting code for common utility
  .clj-kondo/config.edn
  src/metabase/formatter.clj
  src/metabase/formatter/datetime.clj
  src/metabase/pulse/render.clj
  src/metabase/pulse/render/body.clj
  src/metabase/pulse/render/color.clj
  src/metabase/pulse/render/png.clj
  src/metabase/pulse/render/table.clj
  src/metabase/query_processor/streaming/csv.clj
  test/metabase/formatter/datetime_test.clj
  test/metabase/formatter_test.clj
  test/metabase/pulse/render/body_test.clj
  test/metabase/pulse/render/table_test.clj
  test/metabase/pulse/render/test_util.clj
  test/metabase/pulse/render_test.clj
Labels: visual, no-backport, .Team/DashViz

#36475 Fix BE flake: metabase-enterprise.advanced-permissions.common-test/upload-csv-test
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  src/metabase/upload.clj
  test/metabase/upload_test.clj
Labels: backport, .Team/BackendComponents

#36405 Convert expression parsing related files to typescript
  frontend/src/metabase-lib/expressions/config.ts
  frontend/src/metabase-lib/expressions/diagnostics.ts
  frontend/src/metabase-lib/expressions/index.ts
  frontend/src/metabase-lib/expressions/pratt/types.ts
  frontend/src/metabase-lib/expressions/resolver.js
  frontend/src/metabase-lib/expressions/suggest.ts
  frontend/src/metabase-lib/expressions/tokenizer.js
  frontend/src/metabase-lib/expressions/types.ts
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx
  frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.tsx
  frontend/test/metabase/lib/expressions/diagnostics.unit.spec.js
Labels: .Team/QueryingComponents

#36567 Temporarily skip server-side-relative-datetime-honeysql-form
  modules/drivers/redshift/test/metabase/driver/redshift_test.clj
Labels: no-backport, .Team/BackendComponents

#36054 Migrate SettingsLdapForm to formik
  e2e/test/scenarios/admin-2/sso/ldap.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/auth/index.js
  frontend/src/metabase/admin/settings/components/SettingsLdapForm.jsx
  frontend/src/metabase/admin/settings/components/SettingsLdapForm.styled.tsx
  frontend/src/metabase/admin/settings/components/SettingsLdapForm.tsx
  frontend/src/metabase/admin/settings/components/SettingsLdapForm.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/GroupMappingsWidget/GroupMappingsWidget.jsx
  frontend/src/metabase/plugins/builtin/auth/ldap.js
Labels: no-backport, .Team/AdminWebapp

#36572 [MLv2] Only mark selected columns for aggregations with columns
  src/metabase/lib/aggregation.cljc
  test/metabase/lib/aggregation_test.cljc
Labels: backport, .Team/QueryProcessor

#36541 [MLv2] Fix warning in CLJS build
  src/metabase/lib/js/metadata.cljs
Labels: .Team/QueryProcessor, no-backport

#36353 convert user reducer to RTK and typescript
  frontend/src/metabase/admin/admin.js
  frontend/src/metabase/admin/app/actions.ts
  frontend/src/metabase/admin/app/reducers.ts
  frontend/src/metabase/admin/app/selectors.ts
  frontend/src/metabase/redux/user.js
  frontend/src/metabase/redux/user.ts
Labels: no-backport, .Team/DashViz

#36580 Unskip one and skip another relative datetime test
  modules/drivers/redshift/test/metabase/driver/redshift_test.clj
Labels: backport, .Team/QueryProcessor

#36523 Add title to funnel chart that became a bar chart
  frontend/src/metabase/visualizations/visualizations/Funnel.jsx
  frontend/src/metabase/visualizations/visualizations/Funnel.unit.spec.jsx
Labels: backport, visual

#36578 Workaround for an H2 bug
  src/metabase/api/testing.clj
  test/metabase/api/testing_test.clj
Labels: backport, .Team/AdminWebapp

#36597 fix some questions with problems re: models
  resources/instance_analytics/collections/vG58R8k-QddHWA7_47umn_metabase_analytics/cards/DnNyT6EtIn-Zx8bHRFHbV_questions_created_last_week.yaml
  resources/instance_analytics/collections/vG58R8k-QddHWA7_47umn_metabase_analytics/cards/G7fFejjb7cgwYlUXSvf3K_dashboards_created_last_week.yaml
  resources/instance_analytics/collections/vG58R8k-QddHWA7_47umn_metabase_analytics/cards/JPERH6xYVcj3m2Zw0YVY1_active_alerts.yaml
  resources/instance_analytics/collections/vG58R8k-QddHWA7_47umn_metabase_analytics/cards/MOAq881VSlM2BhVUv5e_K_last_activity_on_question.yaml
  resources/instance_analytics/collections/vG58R8k-QddHWA7_47umn_metabase_analytics/cards/p-z74CSp1IOs1rXwAcwcS_most_active_creators.yaml
  resources/instance_analytics/collections/vG58R8k-QddHWA7_47umn_metabase_analytics/cards/xrgv7nzXe_v8ORWIbq839_recent_activity_on_dashboard.yaml
  resources/instance_analytics/collections/vG58R8k-QddHWA7_47umn_metabase_analytics/cards/ybsNZp-876qEMoA1U51dc_alerts_and_subscriptions_created_last_week.yaml
  resources/instance_analytics/collections/vG58R8k-QddHWA7_47umn_metabase_analytics/dashboards/DHMhMa1FYxiyIgM7_xdgR_person_overview.yaml
  resources/instance_analytics/collections/vG58R8k-QddHWA7_47umn_metabase_analytics/dashboards/bJEYb0o5CXlfWFcIztDwJ_dashboard_overview.yaml
  resources/instance_analytics/collections/vG58R8k-QddHWA7_47umn_metabase_analytics/dashboards/jm7KgY6IuS6pQjkBZ7WUI_question_overview.yaml
  resources/instance_analytics/collections/vG58R8k-QddHWA7_47umn_metabase_analytics/dashboards/vFnGZMNN2K_KW1I0B52bq_metabase_metrics.yaml
  resources/instance_analytics/collections/vG58R8k-QddHWA7_47umn_metabase_analytics/okNLSZKdSxaoG58JSQY54_custom_reports/okNLSZKdSxaoG58JSQY54_custom_reports.yaml
  resources/instance_analytics/collections/vG58R8k-QddHWA7_47umn_metabase_analytics/vG58R8k-QddHWA7_47umn_metabase_analytics.yaml
  resources/instance_analytics/databases/Internal Metabase Database/schemas/public/tables/v_content/fields/creator_id.yaml
  resources/instance_analytics/databases/Internal Metabase Database/schemas/public/tables/v_content/fields/made_public_by_user.yaml
  resources/instance_analytics/databases/Internal Metabase Database/schemas/public/tables/v_group_members/fields/user_id.yaml
  resources/instance_analytics/databases/Internal Metabase Database/schemas/public/tables/v_tasks/fields/details.yaml
Labels: backport

#36606 Pretty print #>> and != as operators when possible
  src/metabase/driver/sql/util.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/driver/sql/util_test.clj
Labels: backport, .Team/QueryProcessor

#36511 Copy drills dox from #36253
  src/metabase/lib/drill_thru/column_filter.cljc
  src/metabase/lib/drill_thru/distribution.cljc
  src/metabase/lib/drill_thru/fk_details.cljc
  src/metabase/lib/drill_thru/fk_filter.cljc
  src/metabase/lib/drill_thru/pivot.cljc
  src/metabase/lib/drill_thru/pk.cljc
  src/metabase/lib/drill_thru/quick_filter.cljc
  src/metabase/lib/drill_thru/sort.cljc
  src/metabase/lib/drill_thru/summarize_column.cljc
  src/metabase/lib/drill_thru/summarize_column_by_time.cljc
  src/metabase/lib/drill_thru/underlying_records.cljc
  src/metabase/lib/drill_thru/zoom.cljc
  src/metabase/lib/drill_thru/zoom_in_bins.cljc
  src/metabase/lib/drill_thru/zoom_in_geographic.cljc
  src/metabase/lib/drill_thru/zoom_in_timeseries.cljc
  src/metabase/lib/schema/drill_thru.cljc
Labels: .Team/QueryProcessor, no-backport

#36617 Use `sorted-set` for `locales.clj` so order doesn't change every time we add a new language
  bin/build/src/i18n/common.clj
  resources/locales.clj
Labels: .Team/QueryProcessor, no-backport

#36589 Extract dashboard `QuestionPicker` from `AddCardSidebar`
  frontend/src/metabase/dashboard/components/AddCardSidebar/AddCardSidebar.jsx
  frontend/src/metabase/dashboard/components/AddCardSidebar/AddCardSidebar.unit.spec.tsx
  frontend/src/metabase/dashboard/components/AddCardSidebar/index.ts
  frontend/src/metabase/dashboard/components/DashboardSidebars.jsx
  frontend/src/metabase/dashboard/components/QuestionPicker/QuestionList.styled.tsx
  frontend/src/metabase/dashboard/components/QuestionPicker/QuestionList.tsx
  frontend/src/metabase/dashboard/components/QuestionPicker/QuestionPicker.jsx
  frontend/src/metabase/dashboard/components/QuestionPicker/QuestionPicker.styled.tsx
  frontend/src/metabase/dashboard/components/QuestionPicker/index.ts
Labels: no-backport, .Team/DashViz

#36611 Fix underlying-records drill with nil binned value
  src/metabase/lib/drill_thru/underlying_records.cljc
  test/metabase/lib/drill_thru/underlying_records_test.cljc
Labels: .Team/QueryProcessor, no-backport

#36535 understandable error when export target directory is not writable
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/src/metabase_enterprise/serialization/dump.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/storage.clj
  enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/test_util.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/storage_test.clj
Labels: backport, .Team/BackendComponents

#36627 Add junit.xml to .gitignore
  .gitignore
Labels: .CI & Tests, backport, .Team/QueryingComponents

#36551 Handle latest release check correctly for s3
  .github/workflows/release.yml
  release/release-offline.ts
Labels: .Building & Releasing, backport, .Team/AdminWebapp

#36635 fix sending backport error message
  .github/actions/notify-pull-request/action.yml
Labels: no-backport, .Team/BackendComponents

#36485 CSV appends: Merge 1, Milestone 0: add endpoint to append to table (part one)
  src/metabase/api/card.clj
  src/metabase/api/database.clj
  src/metabase/api/table.clj
  src/metabase/upload.clj
  test/metabase/api/table_test.clj
  test/metabase/upload_test.clj
Labels: no-backport, .Team/BackendComponents

#36462 Sync index info
  docs/developers-guide/driver-changelog.md
  resources/migrations/001_update_migrations.yaml
  src/metabase/driver.clj
  src/metabase/driver/h2.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql_jdbc.clj
  src/metabase/driver/sql_jdbc/sync.clj
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
  src/metabase/sync/fetch_metadata.clj
  src/metabase/sync/sync_metadata.clj
  src/metabase/sync/sync_metadata/fields.clj
  src/metabase/sync/sync_metadata/indexes.clj
  test/metabase/api/database_test.clj
  test/metabase/api/field_test.clj
  test/metabase/api/table_test.clj
  test/metabase/driver/sql_jdbc/sync/describe_table_test.clj
  test/metabase/sync/sync_metadata/indexes_test.clj
  test/metabase/test/data/interface.clj
  test/metabase/test/data/mysql.clj
  test/metabase/test/data/sql.clj
  test/metabase/test/data/sql/ddl.clj
Labels: no-backport, .Team/BackendComponents

#36558 Support changing the expression when the type and the name don't change
  src/metabase/lib/remove_replace.cljc
  src/metabase/types.cljc
  test/metabase/lib/expression_test.cljc
  test/metabase/lib/remove_replace_test.cljc
  test/metabase/lib/schema/expression/arithmetic_test.cljc
  test/metabase/lib/schema/expression/conditional_test.cljc
  test/metabase/types_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor, no-backport

#36652 docs - basic action limitations
  docs/actions/basic.md
Labels: Type:Documentation, backport

#36605 Metabase analytics everywhere
  enterprise/frontend/src/metabase-enterprise/collections/components/CollectionInstanceAnalyticsIcon.tsx
  enterprise/frontend/src/metabase-enterprise/collections/components/CollectionInstanceAnalyticsIcon.unit.spec.tsx
  frontend/src/metabase/collections/components/CollectionHeader/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/entities/collections/utils.unit.spec.ts
Labels: Administration/Audit, backport, .Team/AdminWebapp

#36660 [MLv2] `fk-filter` drills should not appear on native queries
  src/metabase/lib/drill_thru/fk_filter.cljc
  test/metabase/lib/drill_thru/fk_filter_test.cljc
Labels: .Team/QueryProcessor, no-backport

#36613 Underlying records drills: preserve the temporal bucket on a breakout column in the previous stage
  src/metabase/lib/drill_thru/underlying_records.cljc
  src/metabase/lib/underlying.cljc
  test/metabase/lib/drill_thru/underlying_records_test.cljc
Labels: .Team/QueryProcessor, no-backport

#36543 adding perm-graph filtering on db or group id
  .clj-kondo/config.edn
  dev/src/dev/model_tracking.clj
  src/metabase/api/permissions.clj
  src/metabase/models/permissions.clj
  test/metabase/api/permissions_test.clj
  test/metabase/api/permissions_test_util.clj
  test/metabase/models/permissions_group_test.clj
Labels: no-backport, .Team/AdminWebapp

#36650 Make replace-clause use custom expression name if set
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/util.cljc
  test/metabase/lib/remove_replace_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor, no-backport

#36392 Task to send emails warn user about pulse removal
  src/metabase/email.clj
  src/metabase/email/warn_deprecate_pulse.mustache
  src/metabase/task/email_remove_legacy_pulse.clj
  src/metabase/task/send_pulses.clj
  src/metabase/util/urls.clj
  test/metabase/email_test.clj
  test/metabase/task/email_remove_legacy_pulse_test.clj
Labels: backport, .Team/BackendComponents

#36616 Generate sane queries for native query models with renamed columns
  src/metabase/lib/card.cljc
  test/metabase/lib/drill_thru/column_filter_test.cljc
Labels: .Team/QueryProcessor, no-backport

#36527 [#35961 M2] Split Link Panel from Popover
  e2e/test/scenarios/sharing/public-sharing-embed-button-behavior.cy.spec.js
  frontend/src/metabase/dashboard/components/PublicLinkPopover/DashboardPublicLinkPopover.unit.spec.tsx
  frontend/src/metabase/dashboard/components/PublicLinkPopover/PublicLinkCopyPanel.styled.tsx
  frontend/src/metabase/dashboard/components/PublicLinkPopover/PublicLinkCopyPanel.tsx
  frontend/src/metabase/dashboard/components/PublicLinkPopover/PublicLinkPopover.tsx
  frontend/src/metabase/dashboard/components/PublicLinkPopover/PublicLinkPopover.unit.spec.tsx
  frontend/src/metabase/dashboard/components/PublicLinkPopover/QuestionPublicLinkPopover.unit.spec.tsx
  frontend/src/metabase/public/components/widgets/SharingPane.styled.tsx
Labels: .Team/Embedding

#36032 Fix whitelabeled application name replaces Metabase in admin settings
  enterprise/frontend/src/metabase-enterprise/settings/selectors.ts
  enterprise/frontend/src/metabase-enterprise/whitelabel/index.js
  enterprise/frontend/src/metabase-enterprise/whitelabel/lib/whitelabel.js
  enterprise/frontend/src/metabase-enterprise/whitelabel/overrides.js
  frontend/src/metabase-lib/expressions/helper-text-strings.ts
  frontend/src/metabase/account/notifications/components/HelpModal/HelpModal.jsx
  frontend/src/metabase/account/notifications/components/HelpModal/HelpModal.unit.spec.js
  frontend/src/metabase/admin/settings/components/SettingsSlackForm.jsx
  frontend/src/metabase/auth/components/ForgotPasswordForm/ForgotPasswordForm.tsx
  frontend/src/metabase/auth/components/Login/Login.tsx
  frontend/src/metabase/collections/components/CollectionHeader/CollectionUploadInfoModal.tsx
  frontend/src/metabase/components/SchedulePicker/SchedulePicker.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/ClickBehaviorSidebarMainView/ClickBehaviorSidebarMainView.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/TypeSelector/TypeSelector.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/hooks.ts
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/utils.ts
  frontend/src/metabase/home/components/CustomHomePageModal/CustomHomePageModal.tsx
  frontend/src/metabase/home/components/HomeHelpCard/HomeHelpCard.tsx
  frontend/src/metabase/home/components/HomeHelpCard/HomeHelpCard.unit.spec.tsx
  frontend/src/metabase/home/components/HomeXraySection/HomeXraySection.tsx
  frontend/src/metabase/models/containers/NewModelOptions/NewModelOptions.tsx
  frontend/src/metabase/nav/components/ProfileLink/ProfileLink.jsx
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/public/components/EmbedFrame/LogoBadge.tsx
  frontend/src/metabase/public/components/widgets/SharingPane.tsx
  frontend/src/metabase/pulse/components/WhatsAPulse.jsx
  frontend/src/metabase/reference/databases/DatabaseList.jsx
  frontend/src/metabase/reference/databases/NoDatabasesEmptyState.jsx
  frontend/src/metabase/routes-public.jsx
  frontend/src/metabase/routes.jsx
  frontend/src/metabase/selectors/whitelabel/index.ts
  frontend/src/metabase/selectors/whitelabel/tests/common.unit.spec.ts
  frontend/src/metabase/selectors/whitelabel/tests/enterprise.unit.spec.ts
  frontend/src/metabase/selectors/whitelabel/tests/premium.unit.spec.ts
  frontend/src/metabase/sharing/components/NewPulseSidebar.tsx
  frontend/src/metabase/sharing/components/SlackChannelField/SlackChannelField.tsx
  frontend/src/metabase/timelines/collections/components/TimelineDetailsModal/TimelineDetailsModal.unit.spec.tsx
  frontend/src/metabase/timelines/collections/components/TimelineEmptyState/TimelineEmptyState.tsx
  frontend/src/metabase/timelines/collections/components/TimelineEmptyState/TimelineEmptyState.unit.spec.tsx
  frontend/src/metabase/timelines/collections/components/TimelineListModal/TimelineListModal.unit.spec.tsx
  frontend/src/metabase/timelines/questions/components/TimelineEmptyState/TimelineEmptyState.tsx
  frontend/src/metabase/timelines/questions/components/TimelineEmptyState/TimelineEmptyState.unit.spec.tsx
  frontend/src/metabase/timelines/questions/components/TimelinePanel/TimelinePanel.unit.spec.tsx
Labels: backport, .Team/Embedding

#36638 Backport: understandable error when export target directory is not writable
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/src/metabase_enterprise/serialization/dump.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/storage.clj
  enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/test_util.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/storage_test.clj
Labels: was-backported

#36695 HK in API client: move reversal of exponential delay list where it be…
  frontend/src/metabase/lib/api.js
Labels: no-backport, :broom:, .Team/QueryingComponents

#36474 Cypress TypeScript PoC
  e2e/.eslintrc
  e2e/support/commands/ui/button.js
  e2e/support/commands/ui/button.ts
  e2e/support/commands/ui/icon.js
  e2e/support/commands/ui/icon.ts
  e2e/support/helpers/e2e-data-model-helpers.js
  e2e/support/helpers/e2e-data-model-helpers.ts
  e2e/support/helpers/e2e-notebook-helpers.js
  e2e/support/helpers/e2e-notebook-helpers.ts
Labels: .CI & Tests, no-backport

#36673 Remove dead FE code after migrating drills
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase-lib/queries/utils/actions.js
  frontend/src/metabase-lib/queries/utils/actions.unit.spec.js
  frontend/src/metabase-lib/queries/utils/drilldown.js
  frontend/src/metabase-lib/queries/utils/drilldown.unit.spec.js
  frontend/test/metabase-lib/lib/Question.unit.spec.js
Labels: no-backport, .Team/QueryingComponents

#36700 [MLv2] Reorder column filter and distribution drills
  src/metabase/lib/drill_thru.cljc
  test/metabase/lib/drill_thru_test.cljc
Labels: .Team/QueryProcessor, no-backport

#36703 Rerun workflows only once on important branches
  .github/workflows/rerun-workflows.yml
Labels: .CI & Tests, no-backport

#36704 Retry failed Cypress tests only once
  e2e/support/config.js
Labels: .CI & Tests, backport

#36663 Prevent release artifacts colliding with test artifacts
  .github/workflows/build-for-release.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
Labels: .Building & Releasing, backport, .Team/AdminWebapp

#36645 docs - add Finnish to list of languages
  docs/configuring-metabase/localization.md
Labels: Type:Documentation, backport

#36599 docs - add percentage to list of field types
  docs/data-modeling/field-types.md
Labels: backport

#36568 Migrate functions used in ExpressionEditorTextfield to MLv2 query
  e2e/test/scenarios/custom-column/custom-column.cy.spec.js
  e2e/test/scenarios/visualizations-charts/waterfall.cy.spec.js
  frontend/src/metabase-lib/expression.ts
  frontend/src/metabase-lib/expressions/config.ts
  frontend/src/metabase-lib/expressions/diagnostics.ts
  frontend/src/metabase-lib/expressions/format.js
  frontend/src/metabase-lib/expressions/format.ts
  frontend/src/metabase-lib/expressions/index.ts
  frontend/src/metabase-lib/expressions/process.ts
  frontend/src/metabase-lib/fields.ts
  frontend/src/metabase-lib/metadata.ts
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/ExpressionStep.unit.spec.tsx
  frontend/src/metabase/querying/components/FilterPicker/FilterPicker.tsx
  frontend/src/metabase/querying/components/FilterPicker/FilterPicker.unit.spec.tsx
Labels: visual, .Team/QueryingComponents

#36641 Fix uploading CSV columns with boolean and integer values
  src/metabase/upload.clj
  src/metabase/upload/parsing.clj
  test/metabase/upload_test.clj
Labels: backport, .Team/BackendComponents

#36702 Revert all server side generated timestamps commits
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  modules/drivers/redshift/test/metabase/driver/redshift_test.clj
Labels: .Team/QueryProcessor, no-backport

#36603 docs - linked filters limit
  docs/troubleshooting-guide/linked-filters.md
Labels: Type:Documentation, backport

#36697 Fixes for audit DB permission checks & defaults
  enterprise/backend/src/metabase_enterprise/audit_app/permissions.clj
  enterprise/backend/src/metabase_enterprise/audit_db.clj
  enterprise/backend/test/metabase_enterprise/audit_app/permissions_test.clj
  enterprise/backend/test/metabase_enterprise/audit_db_test.clj
Labels: backport, .Team/AdminWebapp

#36418 docs - max retention
  docs/configuring-metabase/environment-variables.md
Labels: Type:Documentation, backport

#35841 Migration to remove the legacy pulses
  e2e/test/scenarios/permissions/permissions-baseline.cy.spec.js
  e2e/test/scenarios/permissions/sandboxes.cy.spec.js
  e2e/test/scenarios/sharing/pulse.cy.spec.js
  e2e/test/scenarios/sharing/reproductions.cy.spec.js
  e2e/test/scenarios/sharing/subscriptions.cy.spec.js
  frontend/src/metabase/collections/components/BaseTableItem.jsx
  frontend/src/metabase/lib/urls/pulses.ts
  frontend/src/metabase/pulse/components/PulseCardPreview.jsx
  frontend/src/metabase/pulse/components/PulseCardPreview.styled.tsx
  frontend/src/metabase/pulse/components/PulseEdit.jsx
  frontend/src/metabase/pulse/components/PulseEdit.styled.tsx
  frontend/src/metabase/pulse/components/PulseEditCards.jsx
  frontend/src/metabase/pulse/components/PulseEditCards.styled.tsx
  frontend/src/metabase/pulse/components/PulseEditCollection.jsx
  frontend/src/metabase/pulse/components/PulseEditCollection.styled.tsx
  frontend/src/metabase/pulse/components/PulseEditName.jsx
  frontend/src/metabase/pulse/components/PulseEditSkip.jsx
  frontend/src/metabase/pulse/components/WhatsAPulse.jsx
  frontend/src/metabase/pulse/components/WhatsAPulse.styled.tsx
  frontend/src/metabase/pulse/containers/PulseEditApp.jsx
  frontend/src/metabase/routes.jsx
  resources/migrations/001_update_migrations.yaml
  test/metabase/db/schema_migrations_test.clj
Labels: no-backport, .Team/BackendComponents

#36571 Use driver/database-supports? instead of supports-schema?
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  test/metabase/upload_test.clj
Labels: no-backport, .Team/BackendComponents

#36694 test(whats-new-notification): add test case for white labeling scenario
  frontend/src/metabase/nav/components/WhatsNewNotification/WhatsNewNotification.unit.spec.tsx
Labels: backport, .Team/Embedding
