Repository metabase/metabase, pull requests merged in 2023-03, with the labels that each got.

#28764 Upgrade babel-loader to 9.1.2
  package.json
  yarn.lock
Labels: backport

#28778 Fix exclusion of CLJS devtools from release builds
  shadow-cljs.edn
  src/metabase/util/devtools.cljc
  src/metabase/util/devtools.cljs
Labels: backport

#28753 docs - update caching
  docs/configuring-metabase/caching.md
Labels: Type:Documentation, backport

#28789 Fix dead link
  docs/developers-guide/drivers/plugins.md
Labels: Type:Tech Debt, .CI & Tests

#28803 Release script fix
  .dir-locals.el
  bin/build/src/release/common.clj
  bin/build/src/release/elastic_beanstalk.clj
  bin/build/test/release/elastic_beanstalk_test.clj
Labels: backport

#28560 Add /api/logs/query_execution endpoint for downloading logs.
  enterprise/backend/src/metabase_enterprise/advanced_config/api/logs.clj
  enterprise/backend/src/metabase_enterprise/api/routes.clj
  enterprise/backend/test/metabase_enterprise/advanced_config/api/logs_test.clj
Labels: backport

#28818 [CI] Upgrade `codecov` action to v3
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
Labels: .CI & Tests, backport

#28738 Add utm_media, utm_source, and utm_users to upgrade urls
  e2e/test/scenarios/embedding/embedding-premium-token.cy.spec.js
  e2e/test/scenarios/embedding/embedding-smoketests.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/license/components/LicenseAndBillingSettings/LicenseAndBillingSettings.tsx
  frontend/src/metabase-types/api/index.ts
  frontend/src/metabase-types/api/mocks/index.ts
  frontend/src/metabase-types/api/mocks/store.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase-types/api/store.ts
  frontend/src/metabase/admin/permissions/components/ToolbarUpsell/ToolbarUpsell.tsx
  frontend/src/metabase/admin/permissions/components/ToolbarUpsell/ToolbarUpsell.unit.spec.tsx
  frontend/src/metabase/admin/permissions/components/ToolbarUpsell/index.ts
  frontend/src/metabase/admin/permissions/pages/DataPermissionsPage/DataPermissionsPage.jsx
  frontend/src/metabase/admin/settings/components/SettingsLicense/SettingsLicense.tsx
  frontend/src/metabase/admin/settings/components/SettingsLicense/SettingsLicense.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingCustomizationInfo.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingCustomizationInfo/EmbeddingCustomizationInfo.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingCustomizationInfo/EmbeddingCustomizationInfo.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingCustomizationInfo/index.ts
  frontend/src/metabase/admin/settings/components/widgets/FullAppEmbeddingLinkWidget/FullAppEmbeddingLinkWidget.tsx
  frontend/src/metabase/admin/settings/components/widgets/FullAppEmbeddingLinkWidget/FullAppEmbeddingLinkWidget.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/FullAppEmbeddingLinkWidget/index.ts
  frontend/src/metabase/admin/settings/components/widgets/PremiumEmbeddingLinkWidget/index.ts
  frontend/src/metabase/admin/settings/containers/PremiumEmbeddingLicensePage/PremiumEmbeddingLicensePage.tsx
  frontend/src/metabase/admin/settings/containers/PremiumEmbeddingLicensePage/PremiumEmbeddingLicensePage.unit.spec.tsx
  frontend/src/metabase/admin/settings/selectors.js
  frontend/src/metabase/lib/settings.ts
  frontend/src/metabase/selectors/selectors.unit.spec.ts
  frontend/src/metabase/selectors/settings.ts
  frontend/test/__support__/server-mocks/index.ts
  frontend/test/__support__/server-mocks/session.ts
  frontend/test/__support__/server-mocks/settings.ts
  frontend/test/__support__/server-mocks/store.ts
Labels: backport

#28499 docs - Google Analytics deprecation updates
  docs/databases/connecting.md
  docs/databases/connections/google-analytics.md
Labels: Type:Documentation, backport

#28815 Updating Close Icon
  frontend/src/metabase/icon_paths.ts
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldPicker.jsx
Labels: backport

#28823 Stacked tooltip fixes
  frontend/src/metabase/visualizations/components/ChartTooltip/StackedDataTooltip/StackedDataTooltip.styled.tsx
  frontend/src/metabase/visualizations/components/ChartTooltip/StackedDataTooltip/StackedDataTooltip.tsx
  frontend/src/metabase/visualizations/components/ChartTooltip/StackedDataTooltip/StackedDataTooltip.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ChartTooltip/StackedDataTooltip/utils.ts
Labels: backport

#28844 docs - update api docs
  docs/api-documentation.md
  docs/api/collection.md
  docs/api/ee/advanced-config-logs.md
  docs/api/ee/sandbox-user.md
Labels: Type:Documentation

#28855 docs - backport ga deprecation
  docs/databases/connecting.md
  docs/databases/connections/google-analytics.md
Labels: Type:Documentation

#28825 fix gauge png saving
  frontend/src/metabase/visualizations/visualizations/Gauge.jsx
Labels: backport

#28786 [CI] Use GitHub basic runners for `druid` and `sparksql` tests
  .github/workflows/drivers.yml
Labels: .CI & Tests, backport

#28861 [CI] Do not mark JUnit reports as failed checks
  .github/actions/test-driver/action.yml
  .github/workflows/backend.yml
Labels: .CI & Tests, backport

#28866 [CI] CodeQL optimization
  .github/codeql/codeql-config.yml
  .github/file-paths.yaml
  .github/workflows/codeql.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#28870 [E2E] Fix Cypress grep pre-filtering
  e2e/support/config.js
Labels: Type:Tech Debt, .CI & Tests, backport

#28886 fix flaky `update-user-attributes-test`
  enterprise/backend/test/metabase_enterprise/sandbox/api/user_test.clj
Labels: backport, flaky-test-fix

#28885 Fix flaky `metabase.dashboard-subscription-test/actions-are-skipped-test`
  test/metabase/dashboard_subscription_test.clj
Labels: flaky-test-fix

#28892 [E2E] Fix embedding flake in repro #20634
  e2e/test/scenarios/embedding/reproductions/20634-locked-parameters-in-embedded-question.cy.spec.js
Labels: .CI & Tests, flaky-test-fix

#28873 docs - clarify basic actions based on changes to how they work
  docs/actions/basic.md
  docs/actions/custom.md
  docs/actions/introduction.md
Labels: Type:Documentation, backport

#28847 Include Google Sign-in when querying users for the audit app
  enterprise/backend/src/metabase_enterprise/audit_app/pages/users.clj
  enterprise/backend/test/metabase_enterprise/audit_app/pages_test.clj
Labels: backport

#28813 Hide dashcard parameter mappings for action dashboard cards
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.jsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.unit.spec.jsx
Labels: backport

#28793 (1/n) update `BaseItemsTable` for new collections bulk actions UI
  e2e/test/scenarios/collections/collections.cy.spec.js
  frontend/src/metabase/collections/components/BaseItemsTable.jsx
  frontend/src/metabase/collections/components/BaseItemsTable.styled.tsx
  frontend/src/metabase/collections/components/BaseTableItem.jsx
  frontend/src/metabase/collections/containers/CollectionContent.jsx
  frontend/test/metabase/collections/BaseItemsTable.unit.spec.js
Labels: .Frontend

#28905 docs - clarify alert actions based on role
  docs/questions/images/recipients.png
  docs/questions/sharing/alerts.md
Labels: Type:Documentation, backport

#28903 22788 fix custom column filter lose their settings when editing dashboards a second time
  e2e/test/scenarios/dashboard-filters/reproductions/22788-flter-cc-dropped-on-second-edit.cy.spec.js
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.jsx
  frontend/src/metabase/dashboard/selectors.js
Labels: backport

#28797 (2/n) update `BulkActions` for new bulk collection actions UI
  e2e/test/scenarios/collections/collections.cy.spec.js
  frontend/src/metabase/collections/components/BulkActions.jsx
  frontend/src/metabase/collections/components/BulkActions.styled.tsx
  frontend/src/metabase/collections/containers/CollectionContent.jsx
  frontend/src/metabase/components/BulkActionBar.styled.tsx
  frontend/src/metabase/components/BulkActionBar.tsx
Labels: .Frontend

#28878 Better hover state for link cards
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.styled.tsx
Labels: backport

#28627 Test Time Fields in Action Forms
  .github/workflows/e2e-tests.yml
  e2e/support/test_tables.js
  e2e/support/test_tables_data.js
  e2e/test/scenarios/dashboard/actions-on-dashboards.cy.spec.js
  frontend/src/metabase/actions/containers/ActionParametersInputForm/utils.ts
  package.json
Labels: backport

#28915 docs - png export
  docs/dashboards/actions.md
  docs/questions/sharing/answers.md
Labels: Type:Documentation, backport

#28913 manual backport 22788
  e2e/test/scenarios/dashboard-filters/reproductions/22788-flter-cc-dropped-on-second-edit.cy.spec.js
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.jsx
  frontend/src/metabase/dashboard/selectors.js
Labels: auto-backported

#28708 docs - update appearance
  docs/configuring-metabase/appearance.md
  docs/questions/sharing/visualizing-results.md
Labels: Type:Documentation, backport

#28877 fix x-rays visible when disabled
  e2e/test/scenarios/dashboard/x-rays.cy.spec.js
  frontend/src/metabase/home/homepage/components/HomeContent/HomeContent.tsx
  frontend/src/metabase/home/homepage/components/HomeContent/HomeContent.unit.spec.tsx
  frontend/src/metabase/home/homepage/containers/HomeContent/HomeContent.tsx
Labels: backport

#28858 Standardize chart settings icon buttons
  e2e/test/scenarios/binning/binning-reproductions.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
  e2e/test/scenarios/native/reproductions/16914.cy.spec.js
  e2e/test/scenarios/question/reproductions/17514-ui-overlay.cy.spec.js
  e2e/test/scenarios/question/settings.cy.spec.js
  e2e/test/scenarios/visualizations/pivot_tables.cy.spec.js
  e2e/test/scenarios/visualizations/reproductions/15353-pivot-settings-change-name-values.cy.spec.js
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldPicker.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldPicker.styled.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingSelect.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingSelect.styled.tsx
  frontend/src/metabase/visualizations/components/settings/ColumnItem.jsx
  frontend/src/metabase/visualizations/components/settings/ColumnItem.styled.tsx
  frontend/test/metabase/visualizations/components/settings/ChartSettingFieldsPicker.unit.spec.js
Labels: backport

#28807 (3/n) update `UndoListing` to match new design for bulk collection actions
  e2e/test/scenarios/collections/collections.cy.spec.js
  frontend/src/metabase/App.tsx
  frontend/src/metabase/containers/UndoListing.jsx
  frontend/src/metabase/containers/UndoListing.styled.tsx
  frontend/src/metabase/selectors/undo.js
Labels: .Frontend

#28811 Centering tab labels
  frontend/src/metabase/core/components/Radio/Radio.tsx
  frontend/src/metabase/visualizations/components/ChartSettingsWidgetPopover.styled.tsx
  frontend/test/metabase/visualizations/components/ChartSettingsWidgetPopover.unit.spec.jsx
Labels: backport

#28799 Cannot use filter relative interval on breakout fields
  e2e/test/scenarios/filters/reproductions/25378-relative-date-on-breakout.cy.spec.js
  src/metabase/query_processor/middleware/optimize_temporal_filters.clj
  test/metabase/query_processor/middleware/optimize_temporal_filters_test.clj
Labels: backport

#28820 Handle Interval values coming from Redshift
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  modules/drivers/redshift/test/metabase/driver/redshift_test.clj
Labels: backport

#28943 Fix flaky switch project id test for bigquery
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj
Labels: flaky-test-fix

#28862 Elevate field type in the action editor
  e2e/test/scenarios/models/model-actions.cy.spec.js
  frontend/src/metabase/actions/components/ActionForm/ActionForm.styled.tsx
  frontend/src/metabase/actions/components/ActionForm/ActionForm.tsx
  frontend/src/metabase/actions/components/ActionForm/FormFieldEditor.styled.tsx
  frontend/src/metabase/actions/components/ActionForm/FormFieldEditor.tsx
  frontend/src/metabase/actions/components/ActionForm/FormFieldEditor.unit.spec.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FieldSettingsPopover.styled.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FieldSettingsPopover.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FieldSettingsPopover.unit.spec.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FormCreator.styled.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx
  frontend/src/metabase/actions/containers/ActionCreator/tests/ActionCreator-ImplicitActions.unit.spec.ts
  frontend/src/metabase/actions/containers/ActionCreator/tests/ActionCreator-QueryActions.unit.spec.ts
  frontend/src/metabase/core/components/FormField/FormField.tsx
Labels: backport

#28945 Fixes notebook editor not working for pivot questions until results are loaded
  e2e/test/scenarios/question/reproductions/28874-notebook-pivot.cy.spec.js
  frontend/src/metabase/query_builder/actions/core/updateQuestion.ts
Labels: support/Repro, backport

#28968 Handle database permissions in the model detail page
  frontend/src/metabase-lib/actions/utils.ts
  frontend/src/metabase-lib/actions/utils.unit.spec.ts
  frontend/src/metabase-types/api/mocks/actions.ts
  frontend/src/metabase/models/components/ModelDetailPage/ModelActionDetails/ModelActionDetails.tsx
  frontend/src/metabase/models/components/ModelDetailPage/ModelActionDetails/ModelActionListItem.tsx
  frontend/src/metabase/models/containers/ModelDetailPage/ModelDetailPage.tsx
  frontend/src/metabase/models/containers/ModelDetailPage/ModelDetailPage.unit.spec.tsx
Labels: backport

#28757 Fix flaky test and test for a new case
  deps.edn
  src/metabase/api/geojson.clj
  test/metabase/api/geojson_test.clj
Labels: backport, flaky-test-fix

#28984 Prevent flakes in GroupMappingsWidget e2e tests
  e2e/test/scenarios/admin/settings/sso/group-mappings-widget.js
  e2e/test/scenarios/admin/settings/sso/jwt.cy.spec.js
  e2e/test/scenarios/admin/settings/sso/ldap.cy.spec.js
  e2e/test/scenarios/admin/settings/sso/saml.cy.spec.js
Labels: flaky-test-fix

#28961 Bind *card-id* when executing a dashboard subscription to fix perm checks
  e2e/test/scenarios/sharing/reproductions/18009-nodata-creates-subscription-receives-error.cy.spec.js
  src/metabase/pulse.clj
  src/metabase/query_processor/card.clj
  test/metabase/dashboard_subscription_test.clj
  test/metabase/models/permissions_test.clj
Labels: backport

#28963 Fix dashboard filter values coercion for actions
  e2e/support/helpers/e2e-dragndrop-helpers.js
  e2e/support/helpers/index.js
  e2e/test/scenarios/dashboard/actions-on-dashboards.cy.spec.js
  e2e/test/scenarios/visualizations/pivot_tables.cy.spec.js
  frontend/src/metabase/actions/components/ActionViz/Action.tsx
  frontend/src/metabase/actions/components/ActionViz/Action.unit.spec.tsx
Labels: backport

#29022 Hide model detail new question link without data permissions
  frontend/src/metabase/models/components/ModelDetailPage/ModelDetailPage.tsx
  frontend/src/metabase/models/components/ModelDetailPage/ModelUsageDetails/ModelUsageDetails.tsx
  frontend/src/metabase/models/containers/ModelDetailPage/ModelDetailPage.unit.spec.tsx
Labels: backport

#28994 Fix actions behavior on the archive page
  e2e/test/scenarios/models/model-actions.cy.spec.js
  frontend/src/metabase/components/ArchivedItem.jsx
  frontend/src/metabase/containers/UndoListing.jsx
  frontend/src/metabase/entities/search.js
  frontend/src/metabase/schema.js
Labels: backport

#29001 docs - update public sharing
  docs/questions/images/public-link-custom-destination.png
  docs/questions/sharing/public-links.md
Labels: Type:Documentation, backport

#29002 Improved datetime handling in Action Forms 🥴
  frontend/src/metabase/actions/containers/ActionParametersInputForm/utils.ts
  frontend/src/metabase/actions/containers/ActionParametersInputForm/utils.unit.spec.ts
Labels: backport

#29045 Mention changes to building drivers in Metabase 0.46.0 dox
  docs/developers-guide/driver-changelog.md
Labels: backport

#29034 Fix copy-pasting sql into the action editor
  frontend/src/metabase/actions/containers/ActionCreator/ActionCreator.tsx
Labels: backport

#29032 Adding classname prop to ObjectDetail
  e2e/test/scenarios/visualizations/object_detail.cy.spec.js
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/types.ts
Labels: backport

#29024 add explicit method param for saved and unsaved questions
  frontend/src/metabase/query_builder/components/QueryDownloadWidget/utils.ts
  frontend/src/metabase/query_builder/components/QueryDownloadWidget/utils.unit.spec.ts
Labels: backport

#29028 Do not show parameters for non-variable template tags in the action editor
  e2e/support/helpers/e2e-action-helpers.js
  e2e/test/scenarios/models/model-actions.cy.spec.js
  frontend/src/metabase/actions/containers/ActionCreator/utils.ts
Labels: backport

#29037 Remove unnecessary `retrieve-dashboard-card` call on every update to a dashcard
  src/metabase/models/dashboard_card.clj
  test/metabase/models/dashboard_card_test.clj
Labels: backport

#29078 Delete implicit actions when models are changed to saved questions
  src/metabase/models/card.clj
  test/metabase/models/action_test.clj
Labels: backport

#28879 Remove personal collections from collection detail page
  e2e/test/scenarios/collections/collection-items-listing.cy.spec.js
  e2e/test/scenarios/collections/collections.cy.spec.js
  src/metabase/models/collection.clj
  test/metabase/api/collection_test.clj
Labels: backport

#28942 Adds `metabase_field.database_auto_incremented`
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
  modules/drivers/sqlite/test/metabase/driver/sqlite_test.clj
  resources/migrations/000_migrations.yaml
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
  src/metabase/models/field.clj
  src/metabase/sync/interface.clj
  src/metabase/sync/sync_metadata/fields/fetch_metadata.clj
  src/metabase/sync/sync_metadata/fields/sync_instances.clj
  src/metabase/sync/sync_metadata/fields/sync_metadata.clj
  test/metabase/api/database_test.clj
  test/metabase/api/field_test.clj
  test/metabase/api/table_test.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/driver/sql_jdbc/sync/describe_table_test.clj
  test/metabase/driver/sql_jdbc_test.clj
  test/metabase/sync/sync_dynamic_test.clj
  test/metabase/sync/sync_metadata/fields/fetch_metadata_test.clj
  test/metabase/sync/sync_metadata/fields/sync_metadata_test.clj
  test/metabase/sync_test.clj
  test/metabase/test/mock/toucanery.clj
  test/metabase/test/mock/util.clj
Labels: backport

#28937 pulling out column title logic and sharing with settings
  e2e/test/scenarios/binning/binning-reproductions.cy.spec.js
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingOrderedColumns.jsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.tsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/settings.ts
  frontend/src/metabase/visualizations/visualizations/Table.jsx
  frontend/test/metabase/visualizations/components/settings/ChartSettingOrderedColumns.unit.spec.js
  frontend/test/metabase/visualizations/visualizations/PivotTable.unit.spec.js
  frontend/test/metabase/visualizations/visualizations/Table.unit.spec.js
Labels: backport

#29000 Better handle numeric action parameters with "select" and "radio" types
  frontend/src/metabase-types/api/actions.ts
  frontend/src/metabase/actions/components/ActionForm/ActionForm.unit.spec.tsx
  frontend/src/metabase/actions/components/ActionForm/FormFieldEditor.tsx
  frontend/src/metabase/actions/components/ActionForm/FormFieldEditor.unit.spec.tsx
  frontend/src/metabase/actions/components/ActionForm/utils.ts
  frontend/src/metabase/actions/components/ActionViz/Action.tsx
  frontend/src/metabase/actions/components/ActionViz/Action.unit.spec.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FieldSettingsButtons.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.styled.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.unit.spec.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/constants.ts
Labels: backport

#29021 Disable implicit actions if update query to include clauses
  enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  src/metabase/api/action.clj
  src/metabase/models/card.clj
  test/metabase/api/action_test.clj
  test/metabase/models/action_test.clj
  test/metabase/models/card_test.clj
  test/metabase/test/generate.clj
Labels: backport, .Blocker

#29054 docs - dash actions
  docs/actions/basic.md
  docs/actions/custom.md
  docs/actions/images/dashboard-action.gif
  docs/actions/images/dropdown.png
  docs/actions/images/form.png
  docs/actions/start.md
  docs/dashboards/actions.md
  docs/dashboards/images/filter-to-action-button.png
  docs/dashboards/images/id-value.png
  docs/permissions/data.md
  docs/questions/sharing/answers.md
Labels: Type:Documentation, backport

#29014 Handle models with joins
  src/metabase/models/persisted_info.clj
  src/metabase/query_processor/util/persisted_cache.clj
  test/metabase/driver/common/parameters/values_test.clj
  test/metabase/query_processor/persistence_test.clj
Labels: backport

#29120 docs - actions backport
  docs/actions/basic.md
  docs/actions/custom.md
  docs/actions/images/dashboard-action.gif
  docs/actions/images/dropdown.png
  docs/actions/images/form.png
  docs/actions/start.md
  docs/dashboards/actions.md
  docs/dashboards/images/filter-to-action-button.png
  docs/dashboards/images/id-value.png
  docs/permissions/data.md
  docs/questions/sharing/answers.md
Labels: Type:Documentation

#29128 docs - add examples
  docs/actions/custom.md
Labels: Type:Documentation, backport

#29055 List actions endpoint
  e2e/test/scenarios/dashboard/actions-on-dashboards.cy.spec.js
  frontend/src/metabase/actions/components/ActionViz/ActionDashcardSettings.unit.spec.tsx
  frontend/src/metabase/actions/containers/ActionCreatorModal/ActionCreatorModal.unit.spec.tsx
  frontend/src/metabase/actions/containers/ActionPicker/ActionPicker.tsx
  frontend/src/metabase/actions/containers/ActionPicker/types.ts
  frontend/src/metabase/actions/containers/ActionPicker/utils.ts
  frontend/src/metabase/actions/containers/ActionPicker/utils.unit.spec.ts
  frontend/src/metabase/models/containers/ModelDetailPage/ModelDetailPage.unit.spec.tsx
  frontend/test/__support__/server-mocks/action.ts
  src/metabase/api/action.clj
  test/metabase/api/action_test.clj
Labels: backport, .Blocker

#29129 fix collection selector is out of the screen
  e2e/test/scenarios/collections/collections.cy.spec.js
  frontend/src/metabase/collections/containers/FormCollectionPicker/FormCollectionPicker.tsx
Labels: backport

#29104 docs - countif
  docs/questions/query-builder/expressions-list.md
  docs/questions/query-builder/expressions/countif.md
  docs/questions/query-builder/expressions/sumif.md
Labels: Type:Documentation, backport

#28295 Improving axes grouping/splitting in static viz.
  src/metabase/pulse/render/body.clj
  test/metabase/pulse/render/body_test.clj
  test/metabase/pulse/render/test_util.clj
Labels: backport

#29112 fix flaky fetch-logs-test
  enterprise/backend/test/metabase_enterprise/advanced_config/api/logs_test.clj
  test/metabase/dashboard_subscription_test.clj
  test/metabase/test/data.clj
Labels: backport, flaky-test-fix

#28998 Delete the abandonment email task
  .clj-kondo/config.edn
  resources/migrations/000_migrations.yaml
  src/metabase/db/custom_migrations.clj
  test/metabase/db/custom_migrations_test.clj
Labels: backport

#29049 [Blocker] Fix optional parameter handling in action forms
  frontend/src/metabase/actions/components/ActionForm/ActionForm.tsx
  frontend/src/metabase/actions/components/ActionForm/ActionForm.unit.spec.tsx
  frontend/src/metabase/actions/components/ActionForm/ActionFormFieldWidget.tsx
  frontend/src/metabase/actions/components/ActionForm/FormFieldEditor.tsx
  frontend/src/metabase/actions/components/ActionForm/FormFieldEditor.unit.spec.tsx
  frontend/src/metabase/actions/components/ActionForm/utils.ts
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FieldSettingsPopover.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FieldSettingsPopover.unit.spec.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/utils.ts
  frontend/src/metabase/public/containers/PublicAction/PublicAction.unit.spec.tsx
  src/metabase/actions/execution.clj
  test/metabase/api/action_test.clj
Labels: backport, .Blocker

#29141 Unskipping Test
  e2e/test/scenarios/question/settings.cy.spec.js
Labels: backport

#29062 Object detail edge case tests
  e2e/support/helpers/e2e-qa-databases-helpers.js
  e2e/support/test_tables.js
  e2e/test/scenarios/dashboard/actions-on-dashboards.cy.spec.js
  e2e/test/scenarios/visualizations/object_detail.cy.spec.js
Labels: backport

#29173 docs - action cast
  docs/actions/custom.md
  docs/actions/introduction.md
Labels: Type:Documentation, backport

#29101 Only save changed dashboards
  e2e/support/helpers/e2e-dashboard-helpers.js
  e2e/test/scenarios/dashboard-filters/reproductions/22788-flter-cc-dropped-on-second-edit.cy.spec.js
  frontend/src/metabase/dashboard/actions/actions.unit.spec.js
  frontend/src/metabase/dashboard/actions/save.js
  frontend/src/metabase/dashboard/actions/utils.ts
  frontend/src/metabase/dashboard/actions/utils.unit.spec.ts
Labels: backport

#29185 docs - note for action endpoint
  docs/api/action.md
Labels: Type:Documentation

#29182 docs - now
  docs/questions/query-builder/expressions-list.md
  docs/questions/query-builder/expressions/converttimezone.md
  docs/questions/query-builder/expressions/datetimeadd.md
  docs/questions/query-builder/expressions/datetimediff.md
  docs/questions/query-builder/expressions/datetimesubtract.md
  docs/questions/query-builder/expressions/now.md
Labels: Type:Documentation, backport

#29150 fix exclude date filter serialization
  e2e/support/helpers/e2e-dashboard-helpers.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-date.cy.spec.js
  frontend/src/metabase-lib/queries/utils/query-time.js
  frontend/src/metabase/parameters/utils/date-formatting.ts
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/DatePicker.unit.spec.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/ExcludeDatePicker.tsx
Labels: backport

#29194 fix + api test
  src/metabase/api/permission_graph.clj
  src/metabase/api/permissions.clj
  src/metabase/models/permissions.clj
  test/metabase/api/permissions_test.clj
Labels: backport

#29160 adding hasMultipleDimensions check to hasLegend clause
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/visualizations/line_chart.cy.spec.js
  frontend/src/metabase/query_builder/components/view/View.jsx
  frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx
Labels: backport

#29092 Handle data permission error for dashboard actions
  frontend/src/metabase/actions/components/ActionViz/Action.tsx
  frontend/src/metabase/actions/components/ActionViz/Action.unit.spec.tsx
  frontend/test/__support__/server-mocks/database.ts
Labels: backport

#29088 Users can run actions if they have access to the database
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  src/metabase/query_processor/middleware/permissions.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/query_processor/middleware/permissions_test.clj
Labels: backport

#29197 Add Recent Item Links to link cards
  frontend/src/metabase-types/api/activity.ts
  frontend/src/metabase-types/api/mocks/activity.ts
  frontend/src/metabase/nav/components/RecentsList.jsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.styled.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/utils.ts
  frontend/test/__support__/server-mocks/activity.ts
  frontend/test/__support__/server-mocks/index.ts
Labels: backport

#29174 manual backport #29112
  enterprise/backend/test/metabase_enterprise/advanced_config/api/logs_test.clj
  test/metabase/test/data.clj
Labels: auto-backported

#29165 Tweak boolean fields in basic action forms
  frontend/src/metabase/core/components/FormCheckBox/FormCheckBox.stories.tsx
  frontend/src/metabase/core/components/FormDateInput/FormDateInput.stories.tsx
  frontend/src/metabase/core/components/FormField/FormField.styled.tsx
  frontend/src/metabase/core/components/FormField/FormField.tsx
  frontend/src/metabase/core/components/FormFileInput/FormFileInput.stores.tsx
  frontend/src/metabase/core/components/FormInput/FormInput.stories.tsx
  frontend/src/metabase/core/components/FormNumericInput/FormNumericInput.stories.tsx
  frontend/src/metabase/core/components/FormRadio/FormRadio.stories.tsx
  frontend/src/metabase/core/components/FormSelect/FormSelect.stories.tsx
  frontend/src/metabase/core/components/FormTextArea/FormTextArea.stories.tsx
  frontend/src/metabase/core/components/FormToggle/FormToggle.stories.tsx
  frontend/src/metabase/dashboard/components/ActionSidebar/ActionSidebar.tsx
Labels: backport

#29190 Fix quick filter drill with nulls
  e2e/test/scenarios/question/reproductions/29082-quick-filter-null.cy.spec.js
  frontend/src/metabase-lib/queries/drills/quick-filter-drill.js
  frontend/src/metabase/modes/components/drill/QuickFilterDrill.tsx
  frontend/test/metabase/modes/components/drill/QuickFilterDrill.unit.spec.js
Labels: backport

#29241 docs - add detail as viz
  docs/questions/images/detail.png
  docs/questions/sharing/visualizing-results.md
Labels: Type:Documentation, backport

#29239 [CI] Start using `was-backported` label
  .github/workflows/auto-backport.yml
  .github/workflows/backport.yml
Labels: .CI & Tests, backport

#29039 Fix action database picker state without available databases
  e2e/support/helpers/e2e-action-helpers.js
  e2e/test/scenarios/admin/settings/public-sharing.cy.spec.js
  e2e/test/scenarios/models/model-actions.cy.spec.js
  frontend/src/metabase/actions/containers/ActionCreator/QueryActionEditor.tsx
  frontend/src/metabase/actions/utils.ts
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDatabasePicker/DataSelectorDatabasePicker.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/DataSourceSelectors/DataSourceSelectors.jsx
Labels: backport

#29272 [Chore] Updgrade `percy/cli` to the latest version
  package.json
  yarn.lock
Labels: Type:Tech Debt, .CI & Tests, backport

#29244 docs - update disabling password logins
  docs/people-and-groups/authenticating-with-jwt.md
  docs/people-and-groups/authenticating-with-saml.md
  docs/people-and-groups/google-and-ldap.md
Labels: Type:Documentation, backport

#29278 Fix filtering not working for newly created models in the QB
  e2e/test/scenarios/models/reproductions/28971-filters-model-new-model.cy.spec.js
  frontend/src/metabase/query_builder/actions/core/core.js
Labels: support/Repro, backport

#29288 Change action menu to drill-through menu
  e2e/test/scenarios/collections/permissions.cy.spec.js
  e2e/test/scenarios/visualizations/maps.cy.spec.js
  e2e/test/scenarios/visualizations/pivot_tables.cy.spec.js
  frontend/src/metabase-lib/parameters/utils/click-behavior.js
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/TableClickBehaviorView/TableClickBehaviorView.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/utils.ts
  frontend/src/metabase/lib/click-behavior.js
Labels: backport

#29228 Ensure we use the ssh tunnel on action execution
  src/metabase/driver/sql_jdbc/actions.clj
  src/metabase/driver/sql_jdbc/execute.clj
  test/metabase/actions_test.clj
Labels: backport

#29189 Updating graph.metrics when column is removed
  e2e/test/scenarios/visualizations/reproductions/20548-bar-duplicate-y-axis-after-changing-metrics.cy.spec.js
  frontend/src/metabase-lib/Question.ts
  frontend/test/metabase/lib/dataset.unit.spec.js
Labels: backport

#29305 Unskip repro for #25543
  e2e/test/scenarios/collections/collections.cy.spec.js
Labels: .CI & Tests

#29307 [CI] Do not run `i18n` workflow on spec changes
  .github/file-paths.yaml
  .github/workflows/i18n.yml
Labels: .CI & Tests, backport

#29314 Removing Repro for 20488
  e2e/test/scenarios/visualizations/smartscalar-trend.cy.spec.js
Labels: backport

#29271 [E2E] Allow custom browser for Cypress database snapshot generation
  e2e/runner/cypress-runner-generate-snapshots.js
  e2e/runner/cypress-runner-run-tests.js
  e2e/runner/cypress-runner-utils.js
Labels: .CI & Tests, backport

#29233 Properly return parameters for card in public and embedding endpoints
  e2e/test/scenarios/native-filters/sql-filters-source.cy.spec.js
  src/metabase/api/embed.clj
  src/metabase/api/public.clj
  test/metabase/api/embed_test.clj
  test/metabase/api/preview_embed_test.clj
  test/metabase/api/public_test.clj
Labels: backport, .Blocker

#29330 REAL launch lag fix :wrench:
  deps.edn
  src/metabase/db/connection.clj
Labels: backport

#29334 fix how isCustomWidgetCheck detects if widgets are react components
  e2e/test/scenarios/models/models-metadata.cy.spec.js
  frontend/src/metabase-types/guards/forms.ts
  frontend/src/metabase-types/guards/react.ts
Labels: backport

#29320 Manual backport: Optimize DB calls of dashboard card updates some more - 2
  src/metabase/api/dashboard.clj
  src/metabase/models/dashboard_card.clj
  src/metabase/models/interface.clj
  test/metabase/models/dashboard_card_test.clj
Labels: was-backported

#29356 [CI] Increase FE timezones tests timeout
  .github/workflows/frontend.yml
Labels: .CI & Tests, backport

#29295 Actions/e2e model actions tests
  e2e/support/helpers/e2e-qa-databases-helpers.js
  e2e/test/scenarios/dashboard/actions-on-dashboards.cy.spec.js
  e2e/test/scenarios/models/model-actions.cy.spec.js
Labels: .CI & Tests, backport

#29230 fix missing group by columns from joined tables
  e2e/test/scenarios/joins/reproductions/27873-missing-joined-group-by.cy.spec.js
  e2e/test/scenarios/question/summarization.cy.spec.js
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/DimensionList/DimensionList.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/DimensionList/utils.js
Labels: backport

#29333 Make object detail viz work for non-logged-in users
  e2e/test/scenarios/visualizations/object_detail.cy.spec.js
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/types.ts
  frontend/src/metabase/visualizations/components/ObjectDetail/utils.ts
  frontend/src/metabase/visualizations/components/TableSimple/TableFooter.tsx
Labels: backport

#29397 Clear Slack token if saved with a non-existant files channel
  src/metabase/api/slack.clj
  src/metabase/integrations/slack.clj
  test/metabase/api/slack_test.clj
Labels: backport

#29392 Backport - Keep NFC root fields in nested queries (#29184) (#29321)
  src/metabase/query_processor/util/nest_query.clj
  test/metabase/query_processor_test/nested_queries_test.clj
Labels: was-backported

#29353 Resolve `nth-check` and `json5` dependabot alerts
  package.json
  yarn.lock
Labels: .Security related, backport, .Blocker

#29373 docs - drill through menu
  docs/dashboards/interactive.md
  docs/databases/connections/athena.md
  docs/databases/connections/bigquery.md
  docs/databases/connections/druid.md
  docs/databases/connections/h2.md
  docs/databases/connections/mysql.md
  docs/databases/connections/postgresql.md
  docs/databases/connections/presto.md
  docs/databases/connections/redshift.md
  docs/databases/connections/snowflake.md
  docs/databases/connections/sparksql.md
  docs/databases/connections/sql-server.md
  docs/databases/connections/sqlite.md
  docs/embedding/introduction.md
  docs/exploration-and-organization/exploration.md
  docs/exploration-and-organization/x-rays.md
  docs/troubleshooting-guide/timeout.md
Labels: Type:Documentation, backport

#29214 Show all subscriptions on /account/notifications page
  e2e/test/scenarios/permissions/reproductions/22473-cannot-unsubscribe-from-notifications-without-collection-perms.cy.spec.js
  frontend/src/metabase/account/notifications/containers/NotificationsApp/NotificationsApp.jsx
  frontend/src/metabase/lib/notifications.js
  src/metabase/api/pulse.clj
  src/metabase/models/pulse.clj
  test/metabase/api/pulse_test.clj
  test/metabase/models/pulse_test.clj
Labels: backport

#29436 docs - backport drill-through
  docs/dashboards/interactive.md
  docs/databases/connections/athena.md
  docs/databases/connections/bigquery.md
  docs/databases/connections/druid.md
  docs/databases/connections/h2.md
  docs/databases/connections/mysql.md
  docs/databases/connections/postgresql.md
  docs/databases/connections/presto.md
  docs/databases/connections/redshift.md
  docs/databases/connections/snowflake.md
  docs/databases/connections/sparksql.md
  docs/databases/connections/sql-server.md
  docs/databases/connections/sqlite.md
  docs/embedding/introduction.md
  docs/exploration-and-organization/exploration.md
  docs/exploration-and-organization/x-rays.md
  docs/troubleshooting-guide/timeout.md
Labels: Type:Documentation

#29451 docs - note on comparing data from multiple databases
  docs/dashboards/multiple-series.md
Labels: Type:Documentation, backport

#29377 🍒 Manual Backport #29295 Action/Model-Actions Tests
  e2e/support/helpers/e2e-qa-databases-helpers.js
  e2e/test/scenarios/dashboard/actions-on-dashboards.cy.spec.js
  e2e/test/scenarios/models/model-actions.cy.spec.js
Labels: was-backported

#29259 Improvement of recent_views endpoint query
  src/metabase/api/activity.clj
Labels: backport

#29401 docs - update caching
  docs/configuring-metabase/caching.md
  docs/configuring-metabase/images/caching.png
  docs/dashboards/introduction.md
  docs/questions/sharing/answers.md
Labels: Type:Documentation, backport

#29448 [E2E] Remove `addFilterToDashboard` custom Cypress command
  e2e/support/commands.js
  e2e/support/commands/api/dashboardFilters.js
  e2e/test/scenarios/dashboard-filters/old-parameters.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/12720-no-data-permissions-connected-filter.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/17211-false-no-matching-filter-alert.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/20656-dashboard-breaks-for-user-without-card-permissions.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/24235-exlude-all-date-options.cy.spec.js
  e2e/test/scenarios/dashboard/title-drill.cy.spec.js
  e2e/test/scenarios/embedding/reproductions/20438-dashboard-filter-single-value.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/15163.cy.spec.js
  e2e/test/visual/dashboard/fullscreen.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#29465 Remove support for nested-field-columns feature for redshift
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  test/metabase/api/permissions_test.clj
Labels: .Team/Backend :pancakes:

#29493 docs - update datetime custom expressions
  docs/questions/query-builder/expressions/datetimeadd.md
  docs/questions/query-builder/expressions/datetimediff.md
  docs/questions/query-builder/expressions/datetimesubtract.md
Labels: Type:Documentation, backport

#29423 Separate date from datetime binning options
  src/metabase/api/table.clj
  test/metabase/api/table_test.clj
Labels: backport

#29457 Reproduce broken audit log #29456
  e2e/test/scenarios/auditing/ad-hoc.cy.spec.js
Labels: support/Repro

#29505 docs - update full-app embedding
  docs/embedding/full-app-embedding.md
Labels: Type:Documentation, backport

#28992 [MLv2] Lay foundations and port display locking logic to CLJC
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase-lib/metadata/Table.ts
  frontend/src/metabase/components/MetadataInfo/TableInfo/ConnectedTables.unit.spec.tsx
  frontend/test/metabase-lib/lib/Question.unit.spec.js
  frontend/test/metabase/query_builder/components/view/sidebars/ChartTypeSidebar.unit.spec.js
  package.json
  shadow-cljs.edn
  src/metabase/domain_entities/card.cljc
  src/metabase/domain_entities/converters.cljs
  src/metabase/lib/convert.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/query.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29459 docs - notes on actions
  docs/actions/introduction.md
Labels: Type:Documentation, backport

#29534 docs - note on metabase versioning
  docs/developers-guide/versioning.md
Labels: Type:Documentation, backport

#29283 keep standalone values when collapsing column
  e2e/test/scenarios/visualizations/pivot_tables.cy.spec.js
  e2e/test/scenarios/visualizations/reproductions/25250-pivot-no-standalone-values-when-collapsed.cy.spec.js
  frontend/src/metabase/lib/data_grid.js
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.unit.spec.tsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTableCell.tsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/RowToggleIcon.tsx
  frontend/test/metabase/lib/data_grid.unit.spec.js
Labels: backport

#29543 "Sync" instead of "Scan" in database settings
  frontend/src/metabase/databases/components/DatabaseSyncScheduleField/DatabaseSyncScheduleField.tsx
Labels: backport, .Team/Viz :bar_chart:

#29524 docs - update sync/scan
  docs/README.md
  docs/configuring-metabase/settings.md
  docs/data-modeling/metadata-editing.md
  docs/databases/connecting.md
  docs/databases/connections/athena.md
  docs/databases/connections/bigquery.md
  docs/databases/connections/druid.md
  docs/databases/connections/h2.md
  docs/databases/connections/mysql.md
  docs/databases/connections/postgresql.md
  docs/databases/connections/presto.md
  docs/databases/connections/redshift.md
  docs/databases/connections/snowflake.md
  docs/databases/connections/sparksql.md
  docs/databases/connections/sql-server.md
  docs/databases/connections/sqlite.md
  docs/databases/images/re-scan-options.png
  docs/databases/images/scanning-options.png
  docs/databases/sync-scan.md
  docs/developers-guide/drivers/multimethods.md
  docs/permissions/data.md
  docs/troubleshooting-guide/db-performance.md
  docs/troubleshooting-guide/filters.md
  docs/troubleshooting-guide/sync-fingerprint-scan.md
Labels: Type:Documentation, backport

#29532 Add Ocient as a partner driver
  src/metabase/driver/util.clj
Labels: backport

#29576 docs - notes on actions
  docs/actions/custom.md
  docs/actions/images/appearance.png
  docs/actions/introduction.md
  docs/developers-guide/start.md
Labels: Type:Documentation, backport

#29580 Implement MLv2 `orderable-columns`
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/breakout.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/expression.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/metadata.cljc
  src/metabase/lib/order_by.cljc
  src/metabase/lib/schema/expression.cljc
  src/metabase/lib/schema/join.cljc
  src/metabase/lib/stage.cljc
  src/metabase/lib/util.cljc
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/test_metadata.cljc
  test/metabase/lib/test_util.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29578 Put db-level cache_ttl behind enterprise feature flag
  enterprise/backend/src/metabase_enterprise/advanced_config/caching.clj
  enterprise/backend/test/metabase_enterprise/advanced_config/caching_test.clj
  src/metabase/api/database.clj
  src/metabase/query_processor/card.clj
  test/metabase/api/database_test.clj
  test/metabase/query_processor/card_test.clj
Labels: backport

#29565 MLv2 new expression syntax
  src/metabase/lib/common.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/dispatch.cljc
  src/metabase/lib/expression.cljc
  src/metabase/lib/filter.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/schema/common.cljc
  test/metabase/lib/aggregation_test.cljc
  test/metabase/lib/expression_test.cljc
  test/metabase/lib/filter_test.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/query_test.cljc
  test/metabase/lib/util_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29497 Add a reproduction for dashboard sticky filter incorrectly positioned when moving between dashboards
  e2e/test/scenarios/dashboard/reproductions/26230-dashboard-sticky-filter-incorrectly-positioned.cy.spec.js
Labels: Reporting/Dashboards, support/Repro, backport

#29594 🍒 Update to Cypress 12 (#29396)
  e2e/support/helpers/e2e-misc-helpers.js
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/admin/settings/localization.cy.spec.js
  e2e/test/scenarios/admin/settings/sso/group-mappings-widget.js
  e2e/test/scenarios/custom-column/reproductions/21135-cc-same-name-as-existing-column.cy.spec.js
  e2e/test/scenarios/dashboard/actions-on-dashboards.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard_data_permissions.cy.spec.js
  e2e/test/scenarios/filters/operators.cy.spec.js
  e2e/test/scenarios/models/models.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
  e2e/test/scenarios/native/snippets/snippet-permissions.cy.spec.js
  e2e/test/scenarios/onboarding/setup/user_settings.cy.spec.js
  e2e/test/scenarios/organization/moderation-collection.cy.spec.js
  e2e/test/scenarios/organization/timelines-question.cy.spec.js
  e2e/test/scenarios/question/nested.cy.spec.js
  e2e/test/scenarios/question/notebook.cy.spec.js
  e2e/test/scenarios/question/nulls.cy.spec.js
  e2e/test/scenarios/question/reproductions/18207-string-min-max.cy.spec.js
  e2e/test/scenarios/question/reproductions/18978-18977-nested-question-nodata-user.cy.spec.js
  e2e/test/scenarios/question/summarization.cy.spec.js
  e2e/test/scenarios/sharing/alert/alert-types.cy.spec.js
  e2e/test/scenarios/visualizations/pivot_tables.cy.spec.js
  e2e/test/scenarios/visualizations/trendline.cy.spec.js
  e2e/test/scenarios/visualizations/waterfall.cy.spec.js
  frontend/src/metabase/core/components/AccordionList/AccordionList.jsx
  frontend/src/metabase/core/components/Select/Select.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx
  frontend/src/metabase/query_builder/components/filters/OperatorSelector.jsx
  frontend/src/metabase/query_builder/components/notebook/NotebookStepPreview.jsx
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx
  package.json
  yarn.lock
Labels: .CI & Tests, was-backported

#29603 Add Ocient as a partner driver on docs
  docs/developers-guide/partner-and-community-drivers.md
Labels: Type:Documentation, backport

#29539 Add a reproduction for unable to properly filter on an aggregation
  e2e/test/scenarios/question/reproductions/22230-query-builder-aggregation-filtering.cy.spec.js
Labels: Querying/GUI, support/Repro, backport, .Team/QueryBuilder :abacus:

#29599 [MLv2] Add `metabase.lib.js/legacy-query` for converting queries to JS
  src/metabase/lib/js.cljs
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#29609 docs - action menu
  docs/databases/connections/athena.md
  docs/databases/connections/bigquery.md
  docs/databases/connections/druid.md
  docs/databases/connections/h2.md
  docs/databases/connections/mysql.md
  docs/databases/connections/postgresql.md
  docs/databases/connections/presto.md
  docs/databases/connections/redshift.md
  docs/databases/connections/snowflake.md
  docs/databases/connections/sparksql.md
  docs/databases/connections/sql-server.md
  docs/databases/connections/sqlite.md
Labels: Type:Documentation, backport

#29507 MLv2: Finish porting query description generation
  .clj-kondo/config.edn
  bin/kondo.sh
  frontend/src/metabase-lib/queries/utils/description.js
  frontend/src/metabase-lib/queries/utils/description.styled.tsx
  frontend/src/metabase/admin/datamodel/components/MetricItem.jsx
  frontend/src/metabase/admin/datamodel/components/SegmentItem.jsx
  shared/src/metabase/mbql/util.cljc
  src/metabase/api/metric.clj
  src/metabase/api/query_description.clj
  src/metabase/api/segment.clj
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/breakout.cljc
  src/metabase/lib/convert.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/filter.cljc
  src/metabase/lib/js/metadata.cljs
  src/metabase/lib/limit.cljc
  src/metabase/lib/metadata.cljc
  src/metabase/lib/metadata/cached_provider.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/metadata/graph_provider.cljc
  src/metabase/lib/metadata/jvm.clj
  src/metabase/lib/metadata/protocols.cljc
  src/metabase/lib/metric.cljc
  src/metabase/lib/order_by.cljc
  src/metabase/lib/query.cljc
  src/metabase/lib/segment.cljc
  src/metabase/lib/stage.cljc
  src/metabase/lib/table.cljc
  src/metabase/models/metric.clj
  src/metabase/models/segment.clj
  test/metabase/api/metric_test.clj
  test/metabase/api/query_description_test.clj
  test/metabase/api/segment_test.clj
  test/metabase/lib/breakout_test.cljc
  test/metabase/lib/metadata/cached_provider_test.cljc
  test/metabase/lib/test_metadata.cljc
  test/metabase/models/metric_test.clj
  test/metabase/models/segment_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29614 docs - trend line
  docs/questions/sharing/visualizing-results.md
Labels: Type:Documentation, backport

#29619 docs - update bigquery
  docs/databases/connections/bigquery.md
Labels: Type:Documentation, backport

#29625 [MLv2] Append and drop final stage
  src/metabase/lib/core.cljc
  src/metabase/lib/order_by.cljc
  src/metabase/lib/stage.cljc
  test/metabase/lib/stage_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#29616 docs - remove specific version option from migrate down command
  docs/installation-and-operation/upgrading-metabase.md
Labels: Type:Documentation, backport

#29608 Remove duplicate reproductions for #22230
  e2e/test/scenarios/filters/reproductions/22230-filter-on-aggregation-max-of.cy.spec.js
  e2e/test/scenarios/question/reproductions/22230-query-builder-aggregation-filtering.cy.spec.js
Labels: Querying/GUI, support/Repro, backport, .Team/QueryBuilder :abacus:

#29605 Fix implicit actions not created in a deterministic order
  e2e/test/scenarios/models/model-actions.cy.spec.js
  frontend/src/metabase/entities/actions/actions.ts
  package.json
Labels: backport, Querying/Actions, .Team/QueryBuilder :abacus:
