Repository metabase/metabase, pull requests merged in 2023-01, with the labels that each got.

#27510 docs - update api docs
  docs/api-documentation.md
  docs/api/action.md
  docs/api/app.md
  docs/api/card.md
  docs/api/collection.md
  docs/api/dashboard.md
  docs/api/google.md
  docs/api/ldap.md
  docs/api/model-action.md
  docs/api/notify.md
  docs/api/permissions.md
  docs/api/public.md
Labels: Type:Documentation

#27515 Notify api key not set hints
  src/metabase/api/routes.clj
  src/metabase/api/routes/common.clj
  src/metabase/models/setting.clj
  src/metabase/server/middleware/auth.clj
  test/metabase/api/notify_test.clj
  test/metabase/models/setting_test.clj
  test/metabase/public_settings_test.clj
  test/metabase/server/middleware/auth_test.clj
  test/metabase/test/util.clj
Labels: backport

#27509 Cache and deps fixes
  .github/actions/prepare-backend/action.yml
  Dockerfile
Labels: backport

#26736 Show server timezone info in `now` custom expression helper text
  frontend/src/metabase-lib/expressions/types.ts
  frontend/src/metabase-types/api/database.ts
  frontend/src/metabase-types/api/index.ts
  frontend/src/metabase-types/api/mocks/database.ts
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.jsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/helper-text-strings.ts
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/helper-text-strings.unit.spec.ts
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/suggest.js
  frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.jsx
  frontend/src/metabase/query_builder/components/notebook/NotebookStep.jsx
  frontend/src/metabase/query_builder/components/notebook/NotebookSteps.jsx
  frontend/src/metabase/query_builder/components/notebook/steps/ExpressionStep.jsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.jsx
  src/metabase/driver.clj
Labels: backport

#27559 Fix cannot select fields for double aggregations
  frontend/src/metabase-lib/queries/utils/structured-query-table.ts
  frontend/src/metabase/core/components/AccordionList/AccordionListCell.jsx
  frontend/src/metabase/query_builder/components/notebook/NotebookStep.jsx
  frontend/test/metabase/scenarios/question/reproductions/27462-no-field-options-for-double-aggregations.cy.spec.js
Labels: .CI & Tests, support/Repro

#27480 Restoring active item colors
  frontend/src/metabase/components/SelectList/SelectListItem.styled.jsx
Labels: backport

#27425 27356 switch dashboards filters
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/27356-navigation-between-two-dashboards.cy.spec.js
Labels: backport

#27436 Parse comma-separated list of numbers as URL filter params
  frontend/src/metabase/parameters/utils/parameter-values.js
  frontend/src/metabase/parameters/utils/parameter-values.unit.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/25374-comma-separated-values-not-passed-to-question.cy.spec.js
Labels: backport

#27585 Use Oxford comma for formatting parameter values in text cards with more than 2 items
  shared/src/metabase/shared/parameters/parameters.cljc
  shared/test/metabase/shared/parameters/parameters_test.cljc
  test/metabase/pulse/parameters_test.clj
Labels: backport

#27557 Add processing step to the date format string so that we get Day of Month
  src/metabase/pulse/render/datetime.clj
Labels: backport

#27392 Remove panning logic from map boundary calculation
  frontend/src/metabase/admin/settings/components/SettingsSetting.jsx
  frontend/src/metabase/admin/settings/components/widgets/CustomGeoJSONWidget.jsx
  frontend/src/metabase/visualizations/components/LeafletChoropleth.jsx
  frontend/src/metabase/visualizations/lib/mapping.js
  frontend/test/metabase-visual/visualizations/map.cy.spec.js
Labels: backport, visual

#27590 docs - update subscription chart caveat
  docs/dashboards/images/example-email.png
  docs/dashboards/subscriptions.md
  frontend/src/metabase/sharing/components/AddEditSidebar/CaveatMessage.jsx
Labels: Type:Documentation

#27419 Remove forced `yarn` resolutions
  package.json
  yarn.lock
Labels: Type:Tech Debt

#27630 docs - remove sql server page and redirect
  docs/databases/connecting.md
  docs/databases/connections/sql-server.md
Labels: Type:Documentation, backport

#27632 docs - update mongo version support
  docs/databases/connecting.md
  docs/databases/connections/mongodb.md
  docs/databases/images/mongo_3.png
Labels: Type:Documentation

#27637 restore aliases before annotating
  shared/src/metabase/mbql/schema.cljc
  src/metabase/query_processor/middleware/annotate.clj
  src/metabase/query_processor/middleware/escape_join_aliases.clj
  test/metabase/query_processor/middleware/annotate_test.clj
  test/metabase/query_processor/middleware/escape_join_aliases_test.clj
  test/metabase/query_processor_test.clj
Labels: backport

#27670 [CI] Fix Trivy scans timing out
  .github/workflows/uberjar.yml
Labels: .CI & Tests, backport

#27614 Fixed regex for latitude name type matching
  src/metabase/sync/analyze/classifiers/name.clj
  test/metabase/sync/analyze/classifiers/name_test.clj
Labels: backport

#27655 FieldValues skipping but not updating last used at
  src/metabase/models/field_values.clj
  test/metabase/models/field_values_test.clj
Labels: Type:Bug

#27687 Fix navigating from dashboard to card with string filters
  frontend/src/metabase-lib/parameters/utils/mbql.js
  frontend/src/metabase-lib/parameters/utils/mbql.unit.spec.js
  frontend/test/metabase-lib/lib/Question.unit.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/25908-contains-filter-case-sensitivity.cy.spec.js
Labels: backport

#27542 Cherry pick notify api message
  src/metabase/api/routes.clj
  src/metabase/api/routes/common.clj
  src/metabase/models/setting.clj
  src/metabase/server/middleware/auth.clj
  test/metabase/api/notify_test.clj
  test/metabase/models/setting_test.clj
  test/metabase/public_settings_test.clj
  test/metabase/server/middleware/auth_test.clj
  test/metabase/test/util.clj
Labels: auto-backported

#27712 docs - update "can't see tables"
  docs/troubleshooting-guide/cant-see-tables.md
Labels: Type:Documentation, backport

#27662 docs - add section to dashboard subscriptions on permissions
  docs/dashboards/subscriptions.md
Labels: Type:Documentation, backport

#27648 docs - admin data model
  docs/README.md
  docs/data-modeling/images/column-reorder.gif
  docs/data-modeling/images/custom-mapping.png
  docs/data-modeling/images/filter-options.png
  docs/data-modeling/images/fk-mapping.png
  docs/data-modeling/images/form.png
  docs/data-modeling/images/hide-unhide-tables.gif
  docs/data-modeling/images/learn-about-your-data-sql-editor.png
  docs/data-modeling/metadata-editing.md
  docs/data-modeling/start.md
Labels: Type:Documentation, backport

#27726 docs - note on breadcrumbs
  docs/embedding/full-app-embedding.md
Labels: Type:Documentation, backport

#27679 Upgrading storybook to 6.5.15
  package.json
  yarn.lock
Labels: backport

#27771 docs - notes on allowed domains
  docs/configuring-metabase/settings.md
  docs/paid-features/overview.md
Labels: Type:Documentation, backport

#27755 docs - update jwt
  docs/people-and-groups/authenticating-with-jwt.md
Labels: Type:Documentation, backport

#27798 Repro #25189: CC referencing a base column dropped in nested question
  frontend/test/metabase/scenarios/custom-column/reproductions/25189-cc-column-reference-only.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#27805 Repro #26826: Dashboard alien card
  frontend/test/metabase/scenarios/dashboard/reproductions/26826-dashboard-alien-card.cy.spec.js
Labels: .CI & Tests, support/Repro

#27796 Fix "Powered by Metabase" badge partially invisible with transparent theme
  frontend/src/metabase/public/components/EmbedFrame.jsx
Labels: backport

#27801 Repro #24330: Admin gets all users' personal collections on home page
  frontend/test/metabase/scenarios/collections/personal-collections.cy.spec.js
Labels: .CI & Tests, support/Repro, backport

#27825 Fix exclude filter not working with other date time units
  frontend/src/metabase-lib/queries/utils/date-filters.ts
  frontend/test/metabase/scenarios/filters/reproductions/27123-exclude-always-shows-days-of-week.cy.spec.js
Labels: backport

#27826 Fix and unskip the test for "Not possible to connect dashboard filters to a Model based on SQL"
  frontend/test/metabase/scenarios/models/reproductions/23024-cannot-apply-dash-filter-native-model.cy.spec.js
Labels: backport

#27837 Fix failing bigquery test
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj
Labels: backport, flaky-test-fix

#27811 Release workflow: handle the auto-adjustment of latest tag on Docker Hub
  .github/workflows/release.yml
Labels: .CI & Tests, backport

#27848 Release workflow: handle the auto-adjustment of latest tag on Docker Hub
  .github/workflows/release.yml
Labels: auto-backported

#27787 docs - sumif
  docs/questions/query-builder/expressions-list.md
  docs/questions/query-builder/expressions/case.md
  docs/questions/query-builder/expressions/datetimediff.md
  docs/questions/query-builder/expressions/sumif.md
Labels: Type:Documentation, backport

#27870 docs - update timezones
  docs/configuring-metabase/timezones.md
Labels: Type:Documentation, backport

#27875 manual backport for "docs - sumif"
  docs/questions/query-builder/expressions-list.md
  docs/questions/query-builder/expressions/case.md
  docs/questions/query-builder/expressions/datetimediff.md
  docs/questions/query-builder/expressions/sumif.md
Labels: Type:Documentation

#27872 Triggers docs update upon a release (#27028)
  .github/workflows/release.yml
Labels: auto-backported

#27886 Remap and update QA databases ports in Cypress tests
  .github/workflows/e2e-main.yml
  .github/workflows/e2e-tests.yml
  frontend/test/__support__/e2e/cypress_data.js
  frontend/test/__support__/e2e/helpers/e2e-qa-databases-helpers.js
  frontend/test/metabase/scenarios/admin/databases/add-external.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#27892 docs - note on migrate down command
  docs/installation-and-operation/upgrading-metabase.md
Labels: Type:Documentation, backport

#27909 docs - can't view or edit
  docs/troubleshooting-guide/cant-view-or-edit.md
Labels: Type:Documentation, backport

#27925 docs - dash sub update
  docs/README.md
  docs/configuring-metabase/email.md
  docs/configuring-metabase/slack.md
  docs/dashboards/subscriptions.md
  docs/databases/connecting.md
  docs/people-and-groups/account-settings.md
  docs/permissions/notifications.md
  docs/permissions/start.md
  docs/questions/sharing/alerts.md
  docs/usage-and-performance-tools/audit.md
Labels: Type:Documentation, backport

#27928 Subscription perms fixes
  enterprise/backend/test/metabase_enterprise/advanced_permissions/api/subscription_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/pulse_test.clj
  frontend/src/metabase/account/notifications/containers/NotificationsApp/NotificationsApp.jsx
  frontend/src/metabase/sharing/components/AddEditSidebar/AddEditEmailSidebar.jsx
  frontend/src/metabase/sharing/components/AddEditSidebar/AddEditSlackSidebar.jsx
  frontend/src/metabase/sharing/components/AddEditSidebar/CaveatMessage.jsx
  frontend/src/metabase/sharing/components/AddEditSidebar/CaveatMessage.styled.tsx
  src/metabase/api/pulse.clj
  src/metabase/models/pulse.clj
  test/metabase/api/pulse_test.clj
  test/metabase/models/pulse_channel_test.clj
  test/metabase/models/pulse_test.clj
Labels: backport

#27939 Manual backport of #27928 to 45 release branch
  enterprise/backend/test/metabase_enterprise/advanced_permissions/api/subscription_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/pulse_test.clj
  frontend/src/metabase/account/notifications/containers/NotificationsApp/NotificationsApp.jsx
  frontend/src/metabase/sharing/components/AddEditSidebar/AddEditEmailSidebar.jsx
  frontend/src/metabase/sharing/components/AddEditSidebar/AddEditSlackSidebar.jsx
  frontend/src/metabase/sharing/components/AddEditSidebar/CaveatMessage.jsx
  frontend/src/metabase/sharing/components/AddEditSidebar/CaveatMessage.styled.tsx
  src/metabase/api/pulse.clj
  src/metabase/models/pulse.clj
  test/metabase/api/pulse_test.clj
  test/metabase/models/pulse_channel_test.clj
  test/metabase/models/pulse_test.clj
Labels: auto-backported

#27895 [Chore] Update copyright year to the current one
  README.md
Labels: Type:Documentation

#27930 docs - update converttimezone
  docs/questions/query-builder/expressions/converttimezone.md
Labels: Type:Documentation, backport

#27948 docs - update links
  docs/permissions/notifications.md
  docs/usage-and-performance-tools/audit.md
Labels: Type:Documentation, backport

#27750 Drop BE defaults for dashcard's size_x, size_y, row, and col
  frontend/test/__support__/e2e/commands/api/composite/createNativeQuestionAndDashboard.js
  frontend/test/__support__/e2e/commands/api/composite/createQuestionAndAddToDashboard.js
  frontend/test/__support__/e2e/commands/api/composite/createQuestionAndDashboard.js
  frontend/test/metabase/scenarios/custom-column/reproductions/19744-cc-after-aggregation-limited-filters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/old-parameters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/parameters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/12720-no-data-permissions-connected-filter.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/19494-wrong-default-value-multiple-cards-same-question.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/25322-loading-list-values.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/reproductions/25355-multi-series-parameter-mapping.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/chained-filters.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/click-behavior.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard-drill.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/dashboard_local-only.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/permissions.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/reproductions/17160-click-behavior-multiple-options.cy.spec.js
  frontend/test/metabase/scenarios/embedding/reproductions/15860-locked-filters-same-source-table.cy.spec.js
  frontend/test/metabase/scenarios/filters/view.cy.spec.js
  frontend/test/metabase/scenarios/models/models-metadata.cy.spec.js
  frontend/test/metabase/scenarios/models/reproductions/23024-cannot-apply-dash-filter-native-model.cy.spec.js
  frontend/test/metabase/scenarios/native-filters/reproductions/15163.cy.spec.js
  frontend/test/metabase/scenarios/question/nulls.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/20393-public-dashboard-nested-card-with-parameters.cy.spec.js
  frontend/test/metabase/scenarios/sharing/subscriptions.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/line-bar-tooltips.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/line_chart.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/scalar.cy.spec.js
  resources/migrations/000_migrations.yaml
  src/metabase/api/dashboard.clj
  src/metabase/models/dashboard_card.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/public_test.clj
  test/metabase/api/revision_test.clj
  test/metabase/models/card_test.clj
  test/metabase/models/dashboard_test.clj
  test/metabase/models/on_demand_test.clj
  test/metabase/test/util.clj
Labels: .Release notes mention

#27971 Fix filtering parameters toggle not working
  frontend/src/metabase/parameters/components/ParameterLinkedFilters/ParameterLinkedFilters.tsx
  frontend/src/metabase/parameters/components/ParameterLinkedFilters/ParameterLinkedFilters.unit.spec.tsx
  frontend/test/metabase/scenarios/dashboard-filters/parameters.cy.spec.js
Labels: support/Repro

#27964 docs - update sql and error troubleshooting
  docs/troubleshooting-guide/error-message.md
  docs/troubleshooting-guide/filters.md
  docs/troubleshooting-guide/images/sample-error-sql.png
  docs/troubleshooting-guide/sql.md
Labels: Type:Documentation, backport

#27981 docs - add logo param
  docs/embedding/full-app-embedding.md
Labels: Type:Documentation
