Repository metabase/metabase, pull requests merged in 2023-11, with the labels that each got.

#34887 Search option to return only or exclude items in personal collections
  src/metabase/api/search.clj
  src/metabase/search/config.clj
  test/metabase/api/search_test.clj
Labels: .Team/42, no-backport

#35239 Fix migration added in #35134
  resources/migrations/000_migrations.yaml
Labels: .Team/42, no-backport

#35276 Fix flaky test because of the current date
  e2e/test/scenarios/native-filters/reproductions/16756.cy.spec.js
Labels: backport, .Team/42

#35264 docs - fix anchor links
  docs/dashboards/subscriptions.md
  docs/questions/sharing/alerts.md
Labels: Type:Documentation, backport

#35065 Stop publishing `:event/card-upate` on card (un)archive
  src/metabase/api/card.clj
Labels: .Team/PixelPolice, no-backport

#35289 docs - model index
  docs/data-modeling/field-types.md
  docs/data-modeling/models.md
Labels: Type:Documentation, backport

#35270 Correct added version for `prettify-native-form`
  docs/developers-guide/driver-changelog.md
  src/metabase/driver.clj
Labels: .Team/QueryProcessor, no-backport

#34947 Optimize revision recording, speed up update dashboard API by 25% 🚀
  src/metabase/api/alert.clj
  src/metabase/api/automagic_dashboards.clj
  src/metabase/api/card.clj
  src/metabase/api/dashboard.clj
  src/metabase/api/database.clj
  src/metabase/api/dataset.clj
  src/metabase/api/metric.clj
  src/metabase/api/pulse.clj
  src/metabase/api/revision.clj
  src/metabase/api/segment.clj
  src/metabase/api/setup.clj
  src/metabase/events.clj
  src/metabase/events/activity_feed.clj
  src/metabase/events/driver_notifications.clj
  src/metabase/events/last_login.clj
  src/metabase/events/persisted_info.clj
  src/metabase/events/revision.clj
  src/metabase/events/schema.clj
  src/metabase/events/sync_database.clj
  src/metabase/events/view_log.clj
  src/metabase/models/activity.clj
  src/metabase/models/dashboard.clj
  src/metabase/models/dashboard_card.clj
  src/metabase/models/pulse.clj
  src/metabase/models/revision.clj
  src/metabase/models/revision/diff.clj
  src/metabase/query_processor/middleware/process_userland_query.clj
  test/metabase/api/activity_test.clj
  test/metabase/api/card_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/revision_test.clj
  test/metabase/api/search_test.clj
  test/metabase/api/setup_test.clj
  test/metabase/events/activity_feed_test.clj
  test/metabase/events/persisted_info_test.clj
  test/metabase/events/revision_test.clj
  test/metabase/events/view_log_test.clj
  test/metabase/models/card_test.clj
  test/metabase/models/dashboard_test.clj
  test/metabase/models/revision_test.clj
  test/metabase/query_processor/middleware/process_userland_query_test.clj
Labels: .Team/42, no-backport

#35141 Add dashboard picker tests
  frontend/src/metabase-types/api/mocks/collection.ts
  frontend/src/metabase/containers/AddToDashSelectDashModal/AddToDashSelectDashModal.unit.spec.tsx
  frontend/src/metabase/dashboard/components/add-card-sidebar/AddCardSidebar/AddCardSidebar.jsx
  frontend/src/metabase/dashboard/components/add-card-sidebar/AddCardSidebar/index.ts
Labels: .Team/42

#35135 [milestone 1] Prevent users from adding questions in personal collections to dashboards in public collections
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/question/new.cy.spec.js
  e2e/test/scenarios/question/question-management.cy.spec.js
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase-types/api/collection.ts
  frontend/src/metabase-types/api/dashboard.ts
  frontend/src/metabase-types/api/mocks/card.ts
  frontend/src/metabase-types/api/mocks/collection.ts
  frontend/src/metabase/collections/selectors.js
  frontend/src/metabase/collections/selectors.ts
  frontend/src/metabase/common/hooks/index.ts
  frontend/src/metabase/common/hooks/use-most-recently-viewed-dashboard/index.ts
  frontend/src/metabase/containers/AddToDashSelectDashModal.unit.spec.tsx
  frontend/src/metabase/containers/AddToDashSelectDashModal/AddToDashSelectDashModal.styled.tsx
  frontend/src/metabase/containers/AddToDashSelectDashModal/AddToDashSelectDashModal.tsx
  frontend/src/metabase/containers/AddToDashSelectDashModal/AddToDashSelectDashModal.unit.spec.tsx
  frontend/src/metabase/containers/AddToDashSelectDashModal/hooks.ts
  frontend/src/metabase/containers/AddToDashSelectDashModal/index.ts
  frontend/src/metabase/containers/AddToDashSelectDashModal/utils.ts
  frontend/src/metabase/containers/DashboardPicker.tsx
  frontend/src/metabase/containers/ItemPicker/ItemPicker.tsx
  frontend/src/metabase/dashboard/components/DashboardSidebars.jsx
  frontend/src/metabase/dashboard/components/add-card-sidebar/AddCardSidebar/AddCardSidebar.jsx
  frontend/src/metabase/dashboard/components/add-card-sidebar/AddCardSidebar/AddCardSidebar.unit.spec.tsx
  frontend/src/metabase/dashboard/components/add-card-sidebar/AddCardSidebar/index.ts
  frontend/src/metabase/dashboard/components/add-card-sidebar/QuestionList.jsx
  frontend/src/metabase/dashboard/components/add-card-sidebar/QuestionPicker.jsx
  frontend/src/metabase/dashboard/reducers.js
  frontend/src/metabase/entities/collections/constants.ts
  frontend/src/metabase/entities/collections/getExpandedCollectionsById.js
  frontend/src/metabase/nav/components/NewItemButton/NewItemButton.tsx
  frontend/src/metabase/query_builder/components/QueryModals.tsx
Labels: .Team/42, no-backport

#35286 🍒 Manual backport - fix arabic number inconsistency (#34633)
  frontend/src/metabase/lib/formatting/date.tsx
  frontend/src/metabase/lib/i18n.js
  frontend/src/metabase/lib/i18n.unit.spec.ts
Labels: was-backported, .Team/PixelPolice

#35315 [MLv2] Filters — Update `TimeFilterPicker` tests
  frontend/src/metabase/common/components/FilterPicker/TimeFilterPicker/TimeFilterPicker.unit.spec.tsx
Labels: .Team/QueryProcessor

#35208 Fix click actions perf issue with charts
  enterprise/frontend/src/metabase-enterprise/audit_app/components/AuditTableVisualization/AuditTableVisualization.jsx
  frontend/src/metabase/visualizations/components/ChoroplethMap.jsx
  frontend/src/metabase/visualizations/components/FunnelNormal.jsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailsTable.tsx
  frontend/src/metabase/visualizations/visualizations/Gauge/Gauge.jsx
  frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.jsx
  frontend/src/metabase/visualizations/visualizations/Progress/Progress.jsx
  frontend/src/metabase/visualizations/visualizations/Scalar/Scalar.jsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.jsx
Labels: visual, .Blocker, .Team/42, no-backport

#35267 Preserve join aliases in dashcard queries (fixes 25278 & 32557)
  src/metabase/automagic_dashboards/core.clj
  test/metabase/automagic_dashboards/core_test.clj
Labels: no-backport

#35229 Add tests for date filters
  frontend/src/metabase/common/components/DatePicker/DatePicker.unit.spec.tsx
  frontend/src/metabase/common/components/DatePicker/DateShortcutPicker/DateShortcutPicker.unit.spec.tsx
  frontend/src/metabase/common/components/DatePicker/ExcludeDatePicker/ExcludeDatePicker.unit.spec.tsx
  frontend/src/metabase/common/components/DatePicker/ExcludeDatePicker/utils.ts
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/CurrentDatePicker/CurrentDatePicker.unit.spec.tsx
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/DateIntervalPicker/DateIntervalPicker.unit.spec.tsx
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/DateIntervalPicker/utils.ts
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/DateOffsetIntervalPicker/DateOffsetIntervalPicker.unit.spec.tsx
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/DateOffsetIntervalPicker/utils.ts
  frontend/src/metabase/common/components/DatePicker/RelativeDatePicker/RelativeDatePicker.unit.spec.tsx
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePicker.tsx
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePicker.unit.spec.tsx
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/SingleDatePicker/SingleDatePicker.tsx
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/SingleDatePicker/SingleDatePicker.unit.spec.tsx
  frontend/src/metabase/common/components/DatePicker/SpecificDatePicker/SpecificDatePicker.unit.spec.tsx
  frontend/src/metabase/common/components/DatePicker/types.ts
  frontend/src/metabase/common/components/FilterPicker/DateFilterPicker/DateFilterPicker.unit.spec.tsx
  frontend/src/metabase/common/components/FilterPicker/DateFilterPicker/utils.ts
Labels: .Team/42

#34087 Add remove columns panel
  e2e/test/scenarios/joins/reproductions/23293-drill-through-implicit-join-add-remove-column.cy.spec.js
  e2e/test/scenarios/models/reproductions/23421-visualization-settins-breaks-ui.cy.spec.js
  e2e/test/scenarios/permissions/sandboxes.cy.spec.js
  e2e/test/scenarios/question/settings.cy.spec.js
  e2e/test/scenarios/visualizations/pie_chart.cy.spec.js
  e2e/test/scenarios/visualizations/reproductions/22206-add-remove-column.cy.spec.js
  e2e/test/scenarios/visualizations/table-column-settings.cy.spec.js
  e2e/test/scenarios/visualizations/table.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/license/components/LicenseAndBillingSettings/LicenseAndBillingSettings.tsx
  frontend/src/metabase-lib/metadata.ts
  frontend/src/metabase-types/api/mocks/presets/sample_database.ts
  frontend/src/metabase/components/StackedCheckBox/StackedCheckBox.tsx
  frontend/src/metabase/query_builder/selectors.js
  frontend/src/metabase/visualizations/click-actions/actions/ColumnFormattingAction/ColumnFormattingAction.tsx
  frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx
  frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/index.ts
  frontend/src/metabase/visualizations/click-actions/modes/DefaultMode.ts
  frontend/src/metabase/visualizations/components/ChartSettings.jsx
  frontend/src/metabase/visualizations/components/ChartSettings.styled.tsx
  frontend/src/metabase/visualizations/components/ClickActions/ClickActionControl.tsx
  frontend/src/metabase/visualizations/components/ClickActions/ClickActionsPopover.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ClickActions/utils.ts
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingAddRemoveColumns/ChartSettingAddRemoveColumns.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingAddRemoveColumns/ChartSettingAddRemoveColumns.unit.spec.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingOrderedItems/ChartSettingOrderedItems.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/ChartSettingTableColumns.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/DatasetColumnSelector.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/DatasetColumnSelector.unit.spec.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/QueryColumnSelector.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/QueryColumnSelector.unit.spec.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/TableColumnSelector.styled.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/TableColumnSelector.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/types.ts
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/utils.ts
  frontend/src/metabase/visualizations/components/settings/ColumnItem/ColumnItem.styled.tsx
  frontend/src/metabase/visualizations/components/settings/ColumnItem/ColumnItem.tsx
  frontend/src/metabase/visualizations/lib/settings/column.js
  frontend/src/metabase/visualizations/visualizations/Table.unit.spec.js
  src/metabase/lib/js.cljs
  src/metabase/lib/metadata/calculation.cljc
  yarn.lock
Labels: visual, .Team/PixelPolice, no-backport

#35236 Skip archived or deleted cards on revert dashboard
  src/metabase/models/dashboard.clj
  src/metabase/models/dashboard_card.clj
  test/metabase/models/dashboard_test.clj
Labels: backport, .Team/42

#35308 refactor: remove wild cy.in in test file
  e2e/test/scenarios/dashboard/tabs.cy.spec.js
Labels: backport, .Team/42

#35211 Convert click-behavior utils to TypeScript
  frontend/src/metabase-lib/.eslintrc
  frontend/src/metabase-lib/Dimension.ts
  frontend/src/metabase-lib/parameters/utils/click-behavior.js
  frontend/src/metabase-lib/parameters/utils/click-behavior.ts
  frontend/src/metabase-lib/parameters/utils/click-behavior.unit.spec.ts
  frontend/src/metabase-lib/queries/Query.ts
  frontend/src/metabase-lib/types/constants.ts
  frontend/src/metabase-lib/variables/Variable/Variable.ts
  frontend/src/metabase-types/api/click-behavior.ts
  frontend/src/metabase-types/api/dataset.ts
  frontend/src/metabase-types/api/parameters.ts
  frontend/src/metabase-types/api/user.ts
  frontend/src/metabase-types/guards/click-behavior.ts
  frontend/src/metabase-types/guards/index.ts
  frontend/src/metabase/actions/utils.ts
  frontend/src/metabase/dashboard/components/ClickMappings.jsx
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/lib/formatting/date.tsx
  frontend/src/metabase/lib/formatting/link.ts
  frontend/src/metabase/selectors/user.ts
Labels: .Team/42, no-backport

#35314 [MLv2] Filters — Add tests for `BooleanFilterPicker`
  frontend/src/metabase/common/components/FilterPicker/BooleanFilterPicker/BooleanFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/BooleanFilterPicker/BooleanFilterPicker.unit.spec.tsx
Labels: .Team/QueryProcessor, no-backport

#35318 Mantine number input fix
  frontend/src/metabase/ui/components/inputs/NumberInput/NumberInput.stories.mdx
  frontend/src/metabase/ui/components/inputs/NumberInput/NumberInput.styled.tsx
  frontend/src/metabase/ui/components/inputs/NumberInput/NumberInput.tsx
  frontend/src/metabase/ui/components/inputs/NumberInput/NumberInput.unit.spec.tsx
  frontend/src/metabase/ui/components/inputs/NumberInput/index.ts
  frontend/src/metabase/ui/components/inputs/TimeInput/TimeInput.tsx
  frontend/src/metabase/ui/theme.ts
Labels: .Team/42, no-backport

#35313 [MLv2] Filters — Add tests for `NumberFilterPicker`
  frontend/src/metabase/common/components/FilterPicker/NumberFilterPicker/NumberFilterPicker.unit.spec.tsx
Labels: .Team/QueryProcessor

#35325 [MLv2] Filters — Add tests for `CoordinateFilterPicker`
  frontend/src/metabase/common/components/FilterPicker/CoordinateFilterPicker/CoordinateFilterPicker.unit.spec.tsx
Labels: .Team/QueryProcessor

#35323 Fix nested column filter issue
  e2e/test/scenarios/filters/filter-sources.cy.spec.js
  frontend/src/metabase-lib/fields.ts
  frontend/src/metabase-lib/queries/structured/Filter.ts
  frontend/src/metabase/common/components/FilterPicker/ColumnValuesWidget/ColumnValuesWidget.tsx
  src/metabase/lib/core.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/js.cljs
  test/metabase/lib/field_test.cljc
Labels: .Team/42

#35326 [MLv2] Filters — Add tests for `StringFilterPicker`
  frontend/src/metabase/common/components/FilterPicker/StringFilterPicker/StringFilterPicker.unit.spec.tsx
Labels: .Team/QueryProcessor

#35283 Fix missing indexed entity x-ray button
  e2e/support/helpers/e2e-model-index-helper.js
  e2e/test/scenarios/models/model-indexes.cy.spec.js
  e2e/test/scenarios/onboarding/search/search.cy.spec.js
  frontend/src/metabase-types/api/search.ts
  frontend/src/metabase/common/utils/model-names.ts
  frontend/src/metabase/common/utils/model-names.unit.spec.ts
  frontend/src/metabase/nav/components/search/SearchResultsDropdown/SearchResultsDropdown.unit.spec.tsx
  frontend/src/metabase/search/components/InfoText/get-info-text.tsx
  frontend/src/metabase/search/components/SearchResult/SearchResult.styled.tsx
  frontend/src/metabase/search/components/SearchResult/SearchResult.tsx
  frontend/src/metabase/search/components/SearchResult/tests/SearchResult.unit.spec.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterContent.unit.spec.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterDisplay.unit.spec.tsx
  frontend/src/metabase/search/constants.ts
  frontend/src/metabase/search/containers/SearchApp.unit.spec.tsx
Labels: .Team/42, no-backport

#33855 Fix - Custom expression that has a name consisting only of whitespace breaks the question
  frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.unit.spec.tsx
Labels: .Team/42

#35332 [MLv2] Filters — Extract test helpers, add more `FilterPicker` tests
  frontend/src/metabase/common/components/FilterPicker/BooleanFilterPicker/BooleanFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/BooleanFilterPicker/BooleanFilterPicker.unit.spec.tsx
  frontend/src/metabase/common/components/FilterPicker/CoordinateFilterPicker/CoordinateFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/CoordinateFilterPicker/CoordinateFilterPicker.unit.spec.tsx
  frontend/src/metabase/common/components/FilterPicker/DateFilterPicker/DateFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/DateFilterPicker/DateFilterPicker.unit.spec.tsx
  frontend/src/metabase/common/components/FilterPicker/FilterPicker.unit.spec.tsx
  frontend/src/metabase/common/components/FilterPicker/NumberFilterPicker/NumberFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/NumberFilterPicker/NumberFilterPicker.unit.spec.tsx
  frontend/src/metabase/common/components/FilterPicker/StringFilterPicker/StringFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/StringFilterPicker/StringFilterPicker.unit.spec.tsx
  frontend/src/metabase/common/components/FilterPicker/TimeFilterPicker/TimeFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/TimeFilterPicker/TimeFilterPicker.unit.spec.tsx
  frontend/src/metabase/common/components/FilterPicker/test-utils.ts
Labels: .Team/QueryProcessor

#35350 Replace getByLabelText with getIcon
  frontend/src/metabase/search/components/SearchResult/tests/SearchResult.unit.spec.tsx
Labels: .Team/42, no-backport

#35328 Fix date parsing in filter wrappers
  frontend/src/metabase-lib/filter.ts
  frontend/src/metabase-lib/filter.unit.spec.ts
Labels: .Team/42, no-backport

#35327 left align dashcard actions on small cards
  e2e/test/scenarios/dashboard/tabs.cy.spec.js
  frontend/src/metabase/dashboard/components/DashCard/DashCard.styled.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  package.json
  yarn.lock
Labels: .Team/42

#35359 Fix join filter names
  e2e/test/scenarios/filters/filter-sources.cy.spec.js
Labels: .Team/42

#35346 Fix calling API more than necessary
  frontend/src/metabase/collections/components/PinnedQuestionCard/PinnedQuestionCard.unit.spec.tsx
  frontend/src/metabase/collections/components/PinnedQuestionCard/PinnedQuestionLoader.tsx
Labels: backport, .Team/42

#35329 Increasing scroll count for flakey table columns test
  e2e/test/scenarios/visualizations/table-column-settings.cy.spec.js
Labels: .Team/PixelPolice, no-backport

#35284 Reorganize and add new audit views
  bin/lint-migrations-file/src/change/strict.clj
  bin/lint-migrations-file/src/change_set/strict.clj
  enterprise/backend/src/metabase_enterprise/audit_app/permissions.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/entity_ids.clj
  resources/instance_analytics_views/audit_log.sql
  resources/instance_analytics_views/dashboardcard.sql
  resources/instance_analytics_views/mysql-audit_log.sql
  resources/instance_analytics_views/subscriptions.sql
  resources/liquibase.yaml
  resources/migrations/000_migrations.yaml
  resources/migrations/instance_analytics_views/alerts/v1/h2-alerts.sql
  resources/migrations/instance_analytics_views/alerts/v1/mysql-alerts.sql
  resources/migrations/instance_analytics_views/alerts/v1/postgres-alerts.sql
  resources/migrations/instance_analytics_views/audit_log/v1/h2-audit_log.sql
  resources/migrations/instance_analytics_views/audit_log/v1/mysql-audit_log.sql
  resources/migrations/instance_analytics_views/audit_log/v1/postgres-audit_log.sql
  resources/migrations/instance_analytics_views/content/v1/h2-content.sql
  resources/migrations/instance_analytics_views/content/v1/mysql-content.sql
  resources/migrations/instance_analytics_views/content/v1/postgres-content.sql
  resources/migrations/instance_analytics_views/dashboardcard/v1/dashboardcard.sql
  resources/migrations/instance_analytics_views/databases/v1/databases.sql
  resources/migrations/instance_analytics_views/fields/v1/h2-fields.sql
  resources/migrations/instance_analytics_views/fields/v1/mysql-fields.sql
  resources/migrations/instance_analytics_views/fields/v1/postgres-fields.sql
  resources/migrations/instance_analytics_views/group_members/v1/group_members.sql
  resources/migrations/instance_analytics_views/mysql-indexes.sql
  resources/migrations/instance_analytics_views/postgres-indexes.sql
  resources/migrations/instance_analytics_views/query_log/v1/h2-query_log.sql
  resources/migrations/instance_analytics_views/query_log/v1/mysql-query_log.sql
  resources/migrations/instance_analytics_views/query_log/v1/postgres-query_log.sql
  resources/migrations/instance_analytics_views/subscriptions/v1/h2-subscriptions.sql
  resources/migrations/instance_analytics_views/subscriptions/v1/mysql-subscriptions.sql
  resources/migrations/instance_analytics_views/subscriptions/v1/postgres-subscriptions.sql
  resources/migrations/instance_analytics_views/tables/v1/h2-tables.sql
  resources/migrations/instance_analytics_views/tables/v1/mysql-tables.sql
  resources/migrations/instance_analytics_views/tables/v1/postgres-tables.sql
  resources/migrations/instance_analytics_views/users/v1/h2-users.sql
  resources/migrations/instance_analytics_views/users/v1/mysql-users.sql
  resources/migrations/instance_analytics_views/users/v1/postgres-users.sql
  resources/migrations/instance_analytics_views/view_log/v1/h2-view_log.sql
  resources/migrations/instance_analytics_views/view_log/v1/mysql-view_log.sql
  resources/migrations/instance_analytics_views/view_log/v1/postgres-view_log.sql
  test/metabase/db/custom_migrations_test.clj
  test/metabase/db/schema_migrations_test/impl.clj
Labels: .Team/PixelPolice

#35146 Snowplow: Add new event for search results filtered
  e2e/test/scenarios/onboarding/search/search.cy.spec.js
  frontend/src/metabase/nav/components/search/SearchBar/SearchBar.tsx
  frontend/src/metabase/nav/components/search/SearchResults/SearchResults.tsx
  frontend/src/metabase/nav/components/search/SearchResultsDropdown/SearchResultsDropdown.tsx
  frontend/src/metabase/search/constants.ts
  frontend/src/metabase/search/containers/SearchApp.jsx
  snowplow/iglu-client-embedded/schemas/com.metabase/search/jsonschema/1-0-1
  src/metabase/analytics/snowplow.clj
  src/metabase/api/search.clj
  test/metabase/api/search_test.clj
Labels: visual, .Team/42, no-backport

#35336 Fixing x-rays with custom columns (#16680)
  e2e/test/scenarios/custom-column/custom-column.cy.spec.js
  frontend/src/metabase-lib/queries/drills/automatic-insights-drill.ts
  src/metabase/automagic_dashboards/core.clj
  src/metabase/automagic_dashboards/names.clj
  src/metabase/automagic_dashboards/util.clj
  test/metabase/automagic_dashboards/core_test.clj
  test/metabase/automagic_dashboards/names_test.clj
Labels: no-backport

#35380 Moving x-ray checks to backend for 15655 to reduce flakes
  e2e/test/scenarios/dashboard/x-rays.cy.spec.js
  test/metabase/automagic_dashboards/core_test.clj
Labels: no-backport

#35268 Disable auto-commit (enable transactions) for read-only connections
  src/metabase/driver/sql_jdbc/execute.clj
  src/metabase/driver/sql_jdbc/sync/describe_database.clj
Labels: backport, .Team/QueryProcessor

#35372 Fix wrongly mocked collection item key
  frontend/src/metabase/collections/components/PinnedQuestionCard/PinnedQuestionCard.unit.spec.tsx
Labels: .Team/42 (DEPRECATED), no-backport

#35223 BE prep for using PUT /api/dashboard/:id to update dashcards and tabs
  frontend/src/metabase/dashboard/actions/save.js
  src/metabase/api/dashboard.clj
  test/metabase/api/dashboard_test.clj
Labels: .Team/42 (DEPRECATED), no-backport

#35397 Update teams in team.json (Nov 2023 reorg)
  .github/team.json
Labels: no-backport

#35407 fix flaky relative time test `filter-datetime-by-date-in-timezone-relative-to-days-since-test`
  test/metabase/query_processor_test/timezones_test.clj
Labels: backport, flaky-test-fix, .Team/BackendComponents

#35269 Backport 34991 prettify native form
  docs/developers-guide/driver-changelog.md
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj
  modules/drivers/oracle/src/metabase/driver/oracle.clj
  modules/drivers/oracle/test/metabase/driver/oracle_test.clj
  modules/drivers/oracle/test/metabase/test/data/oracle.clj
  modules/drivers/redshift/test/metabase/driver/redshift_test.clj
  modules/drivers/sparksql/test/metabase/driver/sparksql_test.clj
  modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj
  modules/drivers/vertica/test/metabase/driver/vertica_test.clj
  src/metabase/api/dataset.clj
  src/metabase/db/query.clj
  src/metabase/driver.clj
  src/metabase/driver/sql.clj
  src/metabase/driver/sql/util.clj
  src/metabase/driver/sql_jdbc/execute.clj
  test/metabase/db/query_test.clj
  test/metabase/driver/mysql_test.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/driver/sql/parameters/substitute_test.clj
  test/metabase/driver/sql/query_processor_test.clj
  test/metabase/driver/sql/query_processor_test_util.clj
  test/metabase/driver/sql/util_test.clj
  test/metabase/driver_test.clj
  test/metabase/query_processor_test/nested_queries_test.clj
Labels: was-backported, .Team/QueryProcessor

#35412 Fix E2E failure due to the DST
  e2e/test/scenarios/visualizations/table.cy.spec.js
Labels: Type:Tech Debt, backport, flaky-test-fix

#35333 [Dashboard] Simplify filters stickiness calculation
  frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.js
  frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.unit.spec.js
Labels: backport, .Team/42 (DEPRECATED)

#35399 Manual backport of "Disable auto-commit for read-only connections"
  src/metabase/driver/sql_jdbc/execute.clj
  src/metabase/driver/sql_jdbc/sync/describe_database.clj
Labels: was-backported, .Team/QueryProcessor

#35168 [MLv2] Make `find-matching-column` correctly match implicit joins
  src/metabase/lib/equality.cljc
  src/metabase/lib/js/metadata.cljs
  test/metabase/lib/equality_test.cljc
Labels: .Team/QueryProcessor, no-backport

#35265 [MLv2] Add card-or-table-id
  src/metabase/lib/core.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/js.cljs
  test/metabase/lib/field_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor, no-backport

#35334 docs - x-ray and action notes
  docs/actions/basic.md
  docs/actions/images/update-record.png
  docs/data-modeling/field-types.md
  docs/exploration-and-organization/exploration.md
  docs/exploration-and-organization/images/automatic-insights.png
  docs/exploration-and-organization/images/drill-through.png
  docs/exploration-and-organization/images/x-ray-compare-popover.png
  docs/exploration-and-organization/x-rays.md
Labels: no-backport

#35130 QP enterprise middleware should use `defenterprise`
  deps.edn
  enterprise/backend/src/metabase_enterprise/advanced_permissions/query_processor/middleware/permissions.clj
  enterprise/backend/src/metabase_enterprise/audit_app/query_processor/middleware/handle_audit_queries.clj
  enterprise/backend/src/metabase_enterprise/sandbox/query_processor/middleware/column_level_perms_check.clj
  enterprise/backend/src/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/models/permissions/block_permissions_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/api/user_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/pages/alerts_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/pages/common_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/pages/dashboard_subscriptions_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/query_processor/middleware/handle_audit_queries_test.clj
  src/metabase/public_settings/premium_features.clj
  src/metabase/query_processor.clj
  src/metabase/query_processor/middleware/enterprise.clj
Labels: Type:Tech Debt, Querying/Processor, .Team/QueryProcessor, no-backport

#35253 [MLv2] Format brush filter display names
  shared/src/metabase/shared/util/internal/time.clj
  shared/src/metabase/shared/util/internal/time.cljs
  shared/src/metabase/shared/util/internal/time_common.cljc
  shared/src/metabase/shared/util/time.cljc
  shared/test/metabase/shared/util/time_test.cljc
  src/metabase/lib/filter.cljc
  src/metabase/lib/schema/expression/temporal.cljc
  src/metabase/lib/schema/literal.cljc
  test/metabase/lib/filter_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor, no-backport

#35058 Use recipients API instead of useUserListQuery
  e2e/test/scenarios/onboarding/search/search.cy.spec.js
  frontend/src/metabase/containers/DataPicker/tests/common.tsx
  frontend/src/metabase/nav/components/search/SearchBar/SearchBar.unit.spec.tsx
  frontend/src/metabase/nav/components/search/SearchResults/SearchResults.unit.spec.tsx
  frontend/src/metabase/nav/components/search/SearchResultsDropdown/SearchResultsDropdown.unit.spec.tsx
  frontend/src/metabase/search/components/InfoText/InfoText.unit.spec.tsx
  frontend/src/metabase/search/components/InfoText/InfoTextAssetLink.tsx
  frontend/src/metabase/search/components/InfoText/InfoTextEditedInfo.tsx
  frontend/src/metabase/search/components/SearchResult/tests/SearchResult-Collections.unit.spec.tsx
  frontend/src/metabase/search/components/SearchUserPicker/SearchUserPicker.tsx
  frontend/src/metabase/search/components/SearchUserPicker/SearchUserPicker.unit.spec.tsx
  frontend/src/metabase/search/components/UserNameDisplay/UserNameDisplay.tsx
  frontend/src/metabase/search/components/UserNameDisplay/UserNameDisplay.unit.spec.tsx
  frontend/src/metabase/search/containers/SearchApp.unit.spec.tsx
  frontend/src/metabase/sharing/components/SharingSidebar/tests/setup.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx
  frontend/test/__support__/server-mocks/user.ts
Labels: visual, .Team/42 (DEPRECATED), no-backport

#35427 Fix E2E "move dashcards to tabs" flake
  e2e/support/helpers/e2e-dashboard-helpers.js
Labels: flaky-test-fix, no-backport

#35445 Add Data Test ID for sidebar
  frontend/src/metabase/dashboard/components/Sidebar.jsx
  frontend/src/metabase/dashboard/components/add-card-sidebar/AddCardSidebar/AddCardSidebar.jsx
Labels: no-backport, .Team/Embedding

#35349 Fix - Text weirdly wrapped in column dropdown in Polish language
  frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.styled.tsx
  frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.tsx
  frontend/src/metabase/core/components/AccordionList/AccordionListCell.jsx
  frontend/src/metabase/core/components/AccordionList/AccordionListCell.styled.tsx
Labels: backport, .Team/Query

#35215 Handle search in dashboard and question picker
  e2e/test/scenarios/onboarding/home/homepage.cy.spec.js
  frontend/src/metabase-types/api/search.ts
  frontend/src/metabase-types/entities/common.ts
  frontend/src/metabase-types/entities/index.ts
  frontend/src/metabase/containers/AddToDashSelectDashModal/AddToDashSelectDashModal.unit.spec.tsx
  frontend/src/metabase/containers/ItemPicker/ItemPicker.tsx
  frontend/src/metabase/containers/ItemPicker/ItemPickerView.tsx
  frontend/src/metabase/containers/ItemPicker/types.ts
  frontend/src/metabase/dashboard/components/add-card-sidebar/AddCardSidebar/AddCardSidebar.unit.spec.tsx
  frontend/src/metabase/dashboard/components/add-card-sidebar/QuestionList.tsx
  frontend/src/metabase/dashboard/components/add-card-sidebar/QuestionPicker.jsx
Labels: .Team/42 (DEPRECATED), no-backport

#35417 Filter popover overflow issue
  frontend/src/metabase/ui/components/overlays/Popover/Popover.styled.tsx
  frontend/src/metabase/ui/components/overlays/Popover/use-floating-auto-update.ts
  frontend/src/metabase/ui/components/overlays/Popover/use-popover.ts
  webpack.config.js
Labels: no-backport

#35405 Update search api documentation to includes available filters
  src/metabase/api/search.clj
Labels: no-backport, .Team/BackendComponents

#35429 🍒 Manual backport of #34996
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/entity_ids.clj
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/entity_ids_test.clj
  src/metabase/cmd.clj
  test/metabase/cmd_test.clj
Labels: was-backported

#35413 Only create one revision per request to PUT /api/dashboard/:id
  src/metabase/api/dashboard.clj
  src/metabase/events/revision.clj
  src/metabase/events/schema.clj
  src/metabase/models/dashboard_tab.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/events/revision_test.clj
Labels: no-backport, .Team/BackendComponents

#35381 impoving spacing, centering checkbox labels
  e2e/test/scenarios/question/settings.cy.spec.js
  frontend/src/metabase/ui/components/inputs/Checkbox/Checkbox.styled.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingAddRemoveColumns/ChartSettingAddRemoveColumns.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/DatasetColumnSelector.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/QueryColumnSelector.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/TableColumnSelector.tsx
Labels: visual, no-backport, .Team/AdminWebapp

#35277 Hide elements in create new dashboard modal
  frontend/src/metabase/collections/components/CreateCollectionForm/CreateCollectionForm.tsx
  frontend/src/metabase/collections/containers/FormCollectionPicker/FormCollectionPicker.tsx
  frontend/src/metabase/containers/AddToDashSelectDashModal/AddToDashSelectDashModal.tsx
  frontend/src/metabase/containers/AddToDashSelectDashModal/AddToDashSelectDashModal.unit.spec.tsx
  frontend/src/metabase/containers/CreateCollectionOnTheGo.tsx
  frontend/src/metabase/dashboard/containers/CreateDashboardForm.tsx
Labels: .Team/42 (DEPRECATED), no-backport

#35385 [MLv2] Filters — Refactor widget layout, make column values widget take full width
  frontend/src/metabase/common/components/FilterPicker/BooleanFilterPicker/BooleanFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/ColumnValuesWidget/ColumnValuesWidget.tsx
  frontend/src/metabase/common/components/FilterPicker/CoordinateFilterPicker/CoordinateFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/FilterPicker.styled.tsx
  frontend/src/metabase/common/components/FilterPicker/FilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/Footer.tsx
  frontend/src/metabase/common/components/FilterPicker/Header.tsx
  frontend/src/metabase/common/components/FilterPicker/NumberFilterPicker/NumberFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/StringFilterPicker/StringFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/TimeFilterPicker/TimeFilterPicker.tsx
  frontend/src/metabase/common/components/FilterPicker/constants.ts
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.tsx
Labels: .Team/QueryProcessor

#34268 Run `clj-kondo` on `bin/` files
  .clj-kondo/config.edn
  .github/workflows/backend.yml
  bin/build/src/build.clj
  bin/build/src/build/licenses.clj
  bin/build/src/build/uberjar.clj
  bin/build/src/build/version_properties.clj
  bin/build/src/build_driver.clj
  bin/build/src/build_drivers.clj
  bin/build/src/build_drivers/build_driver.clj
  bin/build/src/build_drivers/common.clj
  bin/build/src/build_drivers/compile_source_files.clj
  bin/build/src/build_drivers/copy_source_files.clj
  bin/build/src/build_drivers/create_uberjar.clj
  bin/build/src/build_drivers/lint_manifest_file.clj
  bin/build/src/build_drivers/verify.clj
  bin/build/src/i18n/common.clj
  bin/build/src/i18n/create_artifacts.clj
  bin/build/src/i18n/create_artifacts/backend.clj
  bin/build/src/i18n/create_artifacts/frontend.clj
  bin/build/src/metabuild_common/aws.clj
  bin/build/src/metabuild_common/entrypoint.clj
  bin/build/src/metabuild_common/files.clj
  bin/build/src/metabuild_common/input.clj
  bin/build/src/metabuild_common/misc.clj
  bin/build/src/metabuild_common/output.clj
  bin/build/src/metabuild_common/steps.clj
  bin/build/src/release.clj
  bin/build/src/release/check_prereqs.clj
  bin/build/src/release/common.clj
  bin/build/src/release/common/github.clj
  bin/build/src/release/common/hash.clj
  bin/build/src/release/common/http.clj
  bin/build/src/release/draft_release.clj
  bin/build/src/release/git_tags.clj
  bin/build/src/release/set_build_options.clj
  bin/build/src/release/uberjar.clj
  bin/build/src/release/version_info.clj
  bin/build/src/verify_driver.clj
  bin/build/test/build/licenses_test.clj
  bin/build/test/build_drivers/build_driver_test.clj
  bin/build/test/i18n/create_artifacts/test_common.clj
  bin/build/test/release/version_info_test.clj
  bin/kondo.sh
  bin/lint-migrations-file/src/change_set/common.clj
  bin/lint-migrations-file/src/change_set/strict.clj
  bin/lint-migrations-file/src/column/common.clj
  bin/lint-migrations-file/src/column/strict.clj
  bin/lint-migrations-file/src/lint_migrations_file.clj
  bin/release-list/src/release_list/main.clj
  test/metabase/cmd/compare_h2_dbs.clj
Labels: .Team/QueryProcessor, no-backport

#35462 docs - update key
  docs/configuring-metabase/config-file.md
Labels: Type:Documentation, backport

#34935 [MLv2] Implement `zoom-in.binning` drill thru
  src/metabase/lib/binning/util.cljc
  src/metabase/lib/drill_thru.cljc
  src/metabase/lib/drill_thru/zoom_in_bins.cljc
  src/metabase/lib/schema/binning.cljc
  src/metabase/lib/schema/common.cljc
  src/metabase/lib/schema/drill_thru.cljc
  src/metabase/query_processor/middleware/binning.clj
  src/metabase/util.cljc
  test/metabase/driver/sql/query_processor_test.clj
  test/metabase/lib/binning/util_test.cljc
  test/metabase/lib/drill_thru/zoom_in_bins_test.cljc
  test/metabase/lib/test_metadata.cljc
  test/metabase/lib/test_metadata/graph_provider.cljc
  test/metabase/lib/test_util/metadata_providers/mock.cljc
  test/metabase/query_processor/middleware/add_source_metadata_test.clj
  test/metabase/query_processor/middleware/binning_test.clj
  test/metabase/util_test.cljc
Labels: .Team/QueryProcessor, no-backport

#35458 Add :marginalia/one alias to generate docs for a single file
  deps.edn
Labels: .Team/QueryProcessor, no-backport

#35342 [AuditV2] Add Audit deprecation banner
  e2e/test/scenarios/admin-2/auditing/auditing.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/audit_app/containers/AuditApp.jsx
  enterprise/frontend/src/metabase-enterprise/audit_app/containers/AuditApp.styled.jsx
Labels: Administration/Audit, .Team/PixelPolice (DEPRECATED)

#35471 Downgrade Cypress to 12.0.2 🤞
  package.json
  yarn.lock
Labels: .CI & Tests, backport, .Team/AdminWebapp

#35172 [Auditv2] Default copy save location
  e2e/test/scenarios/admin-2/auditing/auditing.cy.spec.js
  e2e/test/scenarios/collections/instance-analytics.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/audit_app/containers/AuditApp.jsx
  enterprise/frontend/src/metabase-enterprise/audit_app/containers/AuditApp.styled.jsx
  enterprise/frontend/src/metabase-enterprise/collections/constants.ts
  enterprise/frontend/src/metabase-enterprise/collections/index.ts
  enterprise/frontend/src/metabase-enterprise/collections/utils.ts
  frontend/src/metabase-types/api/collection.ts
  frontend/src/metabase/collections/components/CollectionHeader/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/collections/components/CollectionMenu/CollectionMenu.tsx
  frontend/src/metabase/collections/utils.ts
  frontend/src/metabase/containers/SaveQuestionModal.tsx
  frontend/src/metabase/entities/containers/EntityCopyModal.tsx
  frontend/src/metabase/entities/containers/EntityForm.jsx
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/query_builder/containers/QueryBuilder.unit.spec.tsx
Labels: .Team/PixelPolice (DEPRECATED)

#35435 Fix audit v2 merge conflicts with master and rework audit_log API
  bin/build/src/metabuild_common/files.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/sso_utils.clj
  enterprise/backend/test/metabase_enterprise/advanced_config/models/pulse_channel_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/pages/alerts_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/pages/dashboard_subscriptions_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/permissions_test.clj
  enterprise/backend/test/metabase_enterprise/email/messages_test.clj
  enterprise/backend/test/metabase_enterprise/public_settings_test.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/saml_test.clj
  resources/migrations/000_migrations.yaml
  resources/migrations/instance_analytics_views/alerts/v1/h2-alerts.sql
  resources/migrations/instance_analytics_views/subscriptions/v1/h2-subscriptions.sql
  src/metabase/api/alert.clj
  src/metabase/api/card.clj
  src/metabase/api/dashboard.clj
  src/metabase/api/database.clj
  src/metabase/api/dataset.clj
  src/metabase/api/session.clj
  src/metabase/api/setup.clj
  src/metabase/api/table.clj
  src/metabase/api/user.clj
  src/metabase/events.clj
  src/metabase/events/audit_log.clj
  src/metabase/events/recent_views.clj
  src/metabase/events/schema.clj
  src/metabase/events/view_log.clj
  src/metabase/models/activity.clj
  src/metabase/models/audit_log.clj
  src/metabase/models/pulse.clj
  src/metabase/models/recent_views.clj
  src/metabase/models/setting.clj
  src/metabase/models/user.clj
  test/metabase/api/activity_test.clj
  test/metabase/api/alert_test.clj
  test/metabase/api/database_test.clj
  test/metabase/api/session_test.clj
  test/metabase/api/setup_test.clj
  test/metabase/api/user_test.clj
  test/metabase/db/schema_migrations_test.clj
  test/metabase/events/audit_log_test.clj
  test/metabase/events/recent_views_test.clj
  test/metabase/events/revision_test.clj
  test/metabase/events/view_log_test.clj
  test/metabase/models/audit_log_test.clj
  test/metabase/models/pulse_channel_test.clj
  test/metabase/models/pulse_test.clj
  test/metabase/query_processor/middleware/process_userland_query_test.clj
Labels: .Team/AdminWebapp

#35366 refactor: remove renderDashCardActions in favor of a component
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionButtons/AddSeriesButton/index.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionButtons/DashCardActionButton/index.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionButtons/DashCardActionButtons.styled.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionButtons/index.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/ActionSettingsButton/ActionSettingsButton.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/ActionSettingsButton/index.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/AddSeriesButton/AddSeriesButton.styled.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/AddSeriesButton/AddSeriesButton.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/AddSeriesButton/index.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/ChartSettingsButton/ChartSettingsButton.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/ChartSettingsButton/index.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardActionButton/DashCardActionButton.styled.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardActionButton/DashCardActionButton.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardActionButton/index.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardActionsPanel.styled.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardActionsPanel.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardTabMenu/DashCardTabMenu.styled.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardTabMenu/DashCardTabMenu.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardTabMenu/DashCardTabMenu.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardTabMenu/index.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/LinkCardEditButton/LinkCardEditButton.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/LinkCardEditButton/index.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/index.ts
Labels: .Team/42 (DEPRECATED)

#35210 Add type safety to jest config
  jest.config.js
  jest.config.json
Labels: backport, .Team/42 (DEPRECATED)

#34715 How to upgrade beanstalk
  docs/installation-and-operation/running-metabase-on-elastic-beanstalk.md
Labels: backport

#34873 Add `align-temporal-unit-with-param-type` multimethod
  docs/developers-guide/driver-changelog.md
  src/metabase/driver/sql/parameters/substitution.clj
  test/metabase/driver/sql/parameters/substitution_test.clj
Labels: .Team/QueryProcessor

#35484 Unskip repro for #14775
  e2e/test/scenarios/custom-column/custom-column.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#35406 Use PUT /api/dashboard/:id to update dashcards and tabs
  e2e/support/commands/api/composite/createNativeQuestionAndDashboard.js
  e2e/support/commands/api/composite/createQuestionAndAddToDashboard.js
  e2e/support/commands/api/composite/createQuestionAndDashboard.js
  e2e/support/commands/api/dashboardCard.js
  e2e/support/helpers/e2e-dashboard-helpers.js
  e2e/test/scenarios/dashboard-cards/dashboard-card-resizing.cy.spec.js
  e2e/test/scenarios/dashboard-cards/dashboard-drill.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/17160-click-behavior-multiple-options.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/20637-add-series-to-dashcard.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/22265-broken-added-series-prevents-editing-card.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/32231-add-incompatible-series.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-chained-filters.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-auto-apply.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-sql-number.cy.spec.js
  e2e/test/scenarios/dashboard-filters/old-parameters.cy.spec.js
  e2e/test/scenarios/dashboard-filters/parameters.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/12985-dropdown-search.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/16112-nodata-should-use-dashboard-filters.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/17211-false-no-matching-filter-alert.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/20656-dashboard-breaks-for-user-without-card-permissions.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/22788-flter-cc-dropped-on-second-edit.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/24235-exlude-all-date-options.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/24500-gracefully-deal-with-corrupted-filter.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/25355-multi-series-parameter-mapping.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/25374-comma-separated-values-not-passed-to-question.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/25908-contains-filter-case-sensitivity.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/29347-remapped-field-values.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard-back-navigation.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/31274-dashcard-actions-overlap.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/34382-dashboard-back-navigation-preserve-filters.cy.spec.js
  e2e/test/scenarios/dashboard/tabs.cy.spec.js
  e2e/test/scenarios/dashboard/title-drill.cy.spec.js
  e2e/test/scenarios/embedding/embedding-full-app.cy.spec.js
  e2e/test/scenarios/embedding/reproductions/20438-dashboard-filter-single-value.cy.spec.js
  e2e/test/scenarios/embedding/reproductions/20845-25031-locked-numeric-param.cy.spec.js
  e2e/test/scenarios/embedding/shared/embedding-dashboard.js
  e2e/test/scenarios/embedding/shared/embedding-linked-filters.js
  e2e/test/scenarios/native-filters/reproductions/15163.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/24966-saved-native-q-field-values.cy.spec.js
  e2e/test/scenarios/sharing/public-dashboard.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/25473-dashboard-text-filter-asking-for-number.cy.spec.js
  e2e/test/scenarios/visualizations/gauge.cy.spec.js
  enterprise/backend/test/metabase_enterprise/sandbox/api/dashboard_test.clj
  frontend/src/metabase/dashboard/actions/save.js
  frontend/src/metabase/dashboard/actions/tabs.ts
  frontend/src/metabase/entities/collections/collections.ts
  frontend/src/metabase/entities/collections/getInitialCollectionId.ts
  frontend/src/metabase/entities/dashboards.js
  frontend/src/metabase/services.js
  test/metabase/api/common/internal_test.clj
  test/metabase/api/dashboard_test.clj
Labels: no-backport, .Team/BackendComponents

#35390 Remove recommendation for keeping user/pass enabled
  docs/people-and-groups/google-and-ldap.md
Labels: backport

#35389 docs - embedding updates
  docs/embedding/interactive-embedding.md
  docs/embedding/start.md
  docs/embedding/static-embedding-parameters.md
  docs/embedding/static-embedding.md
Labels: Type:Documentation, backport

#35473 update samesite docs
  docs/configuring-metabase/environment-variables.md
Labels: backport

#35468 [serdes] Bring back the big comments on the serdes process
  src/metabase/models/serialization.clj
Labels: .Team/QueryProcessor, no-backport

#35439 Fixing dropdown filter value GET #32126
  e2e/test/scenarios/dashboard-filters/dashboard-filters-nested.cy.spec.js
  src/metabase/api/dashboard.clj
  test/metabase/api/dashboard_test.clj
Labels: backport, .Team/DashViz

#35233 Copy `activity` table data to `audit_log`
  resources/migrations/000_migrations.yaml
  src/metabase/public_settings.clj
  test/metabase/db/schema_migrations_test.clj
Labels: .Team/PixelPolice (DEPRECATED), no-backport

#35500 🍒 Downgrade Cypress to 12.0.2 (backport to 47)
  package.json
  yarn.lock
Labels: .CI & Tests, was-backported

#35482 Manual backport: [Dashboard] Simplify filters stickiness calculation
  frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.js
  frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.unit.spec.js
Labels: was-backported

#34994 Update running-the-metabase-jar-file.md
  docs/README.md
  docs/developers-guide/build.md
  docs/installation-and-operation/java-versions.md
  docs/installation-and-operation/running-the-metabase-jar-file.md
  docs/installation-and-operation/start.md
  docs/troubleshooting-guide/running.md
Labels: Type:Documentation, backport

#35392 Create Admin Setting for MB_SESSION_COOKIE_SAMESITE
  e2e/test/scenarios/embedding/embedding-smoketests.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/embedding/components/EmbeddingAppSameSiteCookieDescription/EmbeddingAppSameSiteCookieDescription.styled.tsx
  enterprise/frontend/src/metabase-enterprise/embedding/components/EmbeddingAppSameSiteCookieDescription/EmbeddingAppSameSiteCookieDescription.tsx
  enterprise/frontend/src/metabase-enterprise/embedding/components/EmbeddingAppSameSiteCookieDescription/SameSiteSelectWidget.tsx
  enterprise/frontend/src/metabase-enterprise/embedding/components/EmbeddingAppSameSiteCookieDescription/index.ts
  enterprise/frontend/src/metabase-enterprise/embedding/index.js
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/common.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/enterprise.unit.spec.tsx
Labels: Administration/Settings, .Team/PixelPolice (DEPRECATED), no-backport, .Team/Embedding, .Team/DashViz

#35510 Fix flake in JWT test
  enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj
Labels: no-backport, .Team/AdminWebapp

#35512 [MLv2] Test for #31384 available aggregators updates from join
  test/metabase/lib/aggregation_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor, no-backport

#35507 [MLv2] Tests #12625 removing sorted aggregations
  test/metabase/lib/remove_replace_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor, no-backport

#35418 [MLv2] Refactor `display-info`; add caching
  src/metabase/lib/cache.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/util.cljc
  test/metabase/lib/column_group_test.cljc
  test/metabase/lib/fe_util_test.cljc
Labels: .Team/QueryProcessor, no-backport

#35322 Milestone Reminder Github Action
  .github/workflows/check-milestone.yml
Labels: .Team/PixelPolice (DEPRECATED), no-backport

#35378 feat: use name of card in undo toast message
  e2e/test/scenarios/dashboard/tabs.cy.spec.js
  frontend/src/metabase/containers/UndoListing.jsx
  frontend/src/metabase/containers/UndoListing.styled.tsx
  frontend/src/metabase/dashboard/actions/tabs.ts
  frontend/src/metabase/dashboard/actions/utils.ts
  frontend/src/metabase/dashboard/actions/utils.unit.spec.ts
  frontend/src/metabase/dashboard/selectors/selectors-typed.ts
  frontend/src/metabase/dashboard/selectors/selectors.js
Labels: .Team/42 (DEPRECATED)

#35479 Manual backport - Fix - Text weirdly wrapped in column dropdown in Polish language (#35349)
  frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.styled.tsx
  frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.tsx
  frontend/src/metabase/core/components/AccordionList/AccordionListCell.jsx
  frontend/src/metabase/core/components/AccordionList/AccordionListCell.styled.tsx
Labels: was-backported, .Team/Query

#35527 Refine CI triggers for `snowplow` workflow
  .github/file-paths.yaml
Labels: Type:Tech Debt, .CI & Tests, no-backport

#35496 Remove a retired field's FK target references during sync
  src/metabase/models/field.clj
  test/metabase/sync/sync_metadata/fields_test.clj
Labels: backport, .Team/BackendComponents

#35448 Adding Stacked Checkbox component
  .storybook/preview.tsx
  frontend/src/metabase/ui/components/inputs/Checkbox/Checkbox.stories.mdx
  frontend/src/metabase/ui/components/inputs/Checkbox/Checkbox.styled.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingAddRemoveColumns/ChartSettingAddRemoveColumns.tsx
Labels: visual, no-backport, .Team/AdminWebapp

#35498 Optimistic Database Sync in e2e tests
  e2e/runner/cypress-runner-backend.js
  e2e/support/config.js
  e2e/support/helpers/e2e-qa-databases-helpers.js
Labels: .CI & Tests, backport, .Team/AdminWebapp

#35542 Fix possibility of e2e-update-cards-only-test failure
  test/metabase/api/dashboard_test.clj
Labels: no-backport, .Team/BackendComponents

#35177 Separate SMTP Connection Setup from Other Email Settings
  e2e/test/scenarios/admin/settings/email.cy.spec.js
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/SettingsSection.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/allowed-domains.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/common.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/user-visibility.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/Email/SMTPConnectionCard.tsx
  frontend/src/metabase/admin/settings/components/Email/SMTPConnectionForm.tsx
  frontend/src/metabase/admin/settings/components/Email/SettingsEmailForm.tsx
  frontend/src/metabase/admin/settings/components/SettingsBatchForm.jsx
  frontend/src/metabase/admin/settings/components/SettingsEmailForm.jsx
  frontend/src/metabase/admin/settings/components/SettingsEmailForm.styled.tsx
  frontend/src/metabase/admin/settings/selectors.js
  frontend/src/metabase/components/Breadcrumbs/Breadcrumbs.jsx
Labels: .Team/PixelPolice (DEPRECATED), no-backport, .Team/DashViz

#35515 [MLv2] Test for 27323
  test/metabase/lib/card_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor, no-backport

#35537 Re-assign dashboard filters on Audit
  resources/instance_analytics/collections/vG58R8k-QddHWA7_47umn_metabase_analytics/cards/MOAq881VSlM2BhVUv5e_K_last_activity_on_question.yaml
  resources/instance_analytics/collections/vG58R8k-QddHWA7_47umn_metabase_analytics/dashboards/DHMhMa1FYxiyIgM7_xdgR_person_overview.yaml
  resources/instance_analytics/collections/vG58R8k-QddHWA7_47umn_metabase_analytics/dashboards/jm7KgY6IuS6pQjkBZ7WUI_question_overview.yaml
  resources/instance_analytics/collections/vG58R8k-QddHWA7_47umn_metabase_analytics/dashboards/vFnGZMNN2K_KW1I0B52bq_metabase_metrics.yaml
Labels: no-backport

#35520 Test for #11210
  src/metabase/lib/binning.cljc
  test/metabase/lib/drill_thru/zoom_in_geographic_test.cljc
Labels: .Team/QueryProcessor, no-backport

#35504 [MLv2] Test if a join is removed a custom column based on it is too
  test/metabase/lib/expression_test.cljc
Labels: .Team/QueryProcessor, no-backport

#35506 Add new indexes for audit v2
  resources/instance_analytics_views/collections.sql
  resources/instance_analytics_views/tasks.sql
  resources/migrations/000_migrations.yaml
  resources/migrations/instance_analytics_views/indexes/v1/h2-indexes.sql
  resources/migrations/instance_analytics_views/indexes/v1/mariadb-indexes.sql
  resources/migrations/instance_analytics_views/indexes/v1/mysql-indexes.sql
  resources/migrations/instance_analytics_views/indexes/v1/mysql-rollback.sql
  resources/migrations/instance_analytics_views/indexes/v1/postgres-indexes.sql
  resources/migrations/instance_analytics_views/mysql-indexes.sql
Labels: no-backport, .Team/AdminWebapp

#35387 Fix slow back button x-ray flakes
  e2e/test/scenarios/dashboard/dashboard-back-navigation.cy.spec.js
  src/metabase/api/automagic_dashboards.clj
  test/metabase/api/automagic_dashboards_test.clj
Labels: backport, .Team/DashViz

#35423 Split E2E `visualizations` group
  .github/actions/build-e2e-matrix/action.yml
  e2e/test/scenarios/native/reproductions/11727-cancel-native-query-shortcut.cy.spec.js
  e2e/test/scenarios/native/reproductions/21615-convert-to-sql.cy.spec.js
  e2e/test/scenarios/visualizations-charts/bar_chart.cy.spec.js
  e2e/test/scenarios/visualizations-charts/combo.cy.spec.js
  e2e/test/scenarios/visualizations-charts/funnel.cy.spec.js
  e2e/test/scenarios/visualizations-charts/gauge.cy.spec.js
  e2e/test/scenarios/visualizations-charts/line-bar-tooltips.cy.spec.js
  e2e/test/scenarios/visualizations-charts/line_chart.cy.spec.js
  e2e/test/scenarios/visualizations-charts/maps.cy.spec.js
  e2e/test/scenarios/visualizations-charts/pie_chart.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/13504-post-aggregation-drill.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/16170-line-mongo-replace-missing-values.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/17524.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/18061-maps-only-nulls-crash-frontend.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/18063-maps-null-location-wrong-tooltip.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/18776-timeseries-hidden-axis-freeze.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/20548-bar-duplicate-y-axis-after-changing-metrics.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/21452-xhr-on-every-char-for-rename.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/21504-pie-settings-formatting.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/21665-multi-series-frontend-reload.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/22527-scatter-negative-values-not-rendered.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/25007-week-tooltip-native.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/25156-invalid-x-axis-series.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/27279-sorting-does-not-apply-to-x-axis.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/27427-static-viz-divide-by-zero.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/29030-bar-area-stacking.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/30058-32075-map-visualizations.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/33208-auto-chart-type-after-save.cy.spec.js
  e2e/test/scenarios/visualizations-charts/rows.cy.spec.js
  e2e/test/scenarios/visualizations-charts/scatter.cy.spec.js
  e2e/test/scenarios/visualizations-charts/trendline.cy.spec.js
  e2e/test/scenarios/visualizations-charts/waterfall.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/14148-pivot-table-postgres.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/25415-custom-column-drill-through.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/drillthroughs/chart_drill.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/drillthroughs/dash_drill.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/drillthroughs/table_drills.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/object_detail.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/pivot_tables.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/11249-add-more-series-no-columns.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/11435-time-tooltip-native.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/15353-pivot-settings-change-name-values.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/18976-pivot-table-columns.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/18996-table-image-pagination.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/19373-pivot-wrong-distinct-value-totals.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/21392-chart-many-columns-freeze.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/22206-add-remove-column.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/23076.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/28304-table-columns-unknown.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/28311-sorting-table-columns.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/30039-object-detail-navigation.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/6010-metric-filter-drill.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/scalar.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/smartscalar-trend.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/table-column-settings.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/table.cy.spec.js
Labels: .CI & Tests, backport

#35548 :cherries: Manual Backport [#35478]
  e2e/support/cypress_sample_instance_data.js
  e2e/support/helpers/e2e-email-helpers.js
  e2e/test/scenarios/sharing/subscriptions.cy.spec.js
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/settings/components/Email/BccToggleWidget.tsx
  frontend/src/metabase/admin/settings/selectors.js
Labels: was-backported, .Team/DashViz, .Team/AdminWebapp

#35185 Make Pre-Release checks trigger on workflow_dispatch
  .github/workflows/build-for-release.yml
  .github/workflows/pre-release.yml
Labels: .Building & Releasing, .Team/PixelPolice (DEPRECATED), no-backport

#35441 Update some pivot QP code to use MLv2 (bug fix)
  src/metabase/lib/equality.cljc
  src/metabase/query_processor/pivot.clj
  test/metabase/lib/equality_test.cljc
  test/metabase/query_processor/pivot_test.clj
Labels: backport, .Team/QueryProcessor

#35386 Handle audit v2 downgrade case
  resources/migrations/000_migrations.yaml
  test/metabase/db/schema_migrations_test.clj
Labels: .Team/PixelPolice (DEPRECATED), no-backport

#35523 Generate sane SQL for a DATE[TIME] expression = DATE literal filter
  shared/src/metabase/mbql/schema.cljc
  src/metabase/lib/metadata/cached_provider.cljc
  src/metabase/lib/metadata/composed_provider.cljc
  src/metabase/lib/metadata/jvm.clj
  src/metabase/query_processor/middleware/optimize_temporal_filters.clj
  src/metabase/query_processor/middleware/wrap_value_literals.clj
  test/metabase/lib/metadata/cached_provider_test.cljc
  test/metabase/lib/metadata/composed_provider_test.cljc
  test/metabase/lib/metadata/jvm_test.clj
  test/metabase/lib/test_metadata/graph_provider.cljc
  test/metabase/lib/test_util/metadata_providers/mock.cljc
  test/metabase/query_processor/middleware/optimize_temporal_filters_test.clj
  test/metabase/query_processor/middleware/wrap_value_literals_test.clj
  test/metabase/query_processor_test/filter_test.clj
Labels: .Team/QueryProcessor, no-backport

#35442 No more `schema=`
  .clj-kondo/config.edn
  .clj-kondo/hooks/clojure/test.clj
  dev/src/user.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/models/permissions/block_permissions_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/pages_test.clj
  enterprise/backend/test/metabase_enterprise/enhancements/integrations/ldap_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/dashboard_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/gtap_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/extract_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj
  modules/drivers/mongo/test/metabase/driver/mongo/query_processor_test.clj
  test/metabase/actions_test.clj
  test/metabase/analytics/stats_test.clj
  test/metabase/api/automagic_dashboards_test.clj
  test/metabase/api/card_test.clj
  test/metabase/api/collection_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/database_test.clj
  test/metabase/api/embed_test.clj
  test/metabase/api/geojson_test.clj
  test/metabase/api/native_query_snippet_test.clj
  test/metabase/api/preview_embed_test.clj
  test/metabase/api/public_test.clj
  test/metabase/api/pulse_test.clj
  test/metabase/api/session_test.clj
  test/metabase/api/setting_test.clj
  test/metabase/api/setup_test.clj
  test/metabase/api/task_test.clj
  test/metabase/api/tiles_test.clj
  test/metabase/api/user_test.clj
  test/metabase/automagic_dashboards/core_test.clj
  test/metabase/dashboard_subscription_test.clj
  test/metabase/driver/common/parameters/operators_test.clj
  test/metabase/integrations/slack_test.clj
  test/metabase/models/card_test.clj
  test/metabase/models/collection/graph_test.clj
  test/metabase/models/dashboard_test.clj
  test/metabase/models/database_test.clj
  test/metabase/models/interface_test.clj
  test/metabase/models/pulse_test.clj
  test/metabase/models/setting_test.clj
  test/metabase/pulse/render/body_test.clj
  test/metabase/pulse/render/style_test.clj
  test/metabase/pulse_test.clj
  test/metabase/query_processor/card_test.clj
  test/metabase/query_processor/middleware/add_implicit_joins_test.clj
  test/metabase/query_processor/middleware/cache_test.clj
  test/metabase/query_processor/middleware/catch_exceptions_test.clj
  test/metabase/query_processor/middleware/results_metadata_test.clj
  test/metabase/query_processor/pivot_test.clj
  test/metabase/query_processor_test.clj
  test/metabase/query_processor_test/nested_queries_test.clj
  test/metabase/query_processor_test/order_by_test.clj
  test/metabase/server/request/util_test.clj
  test/metabase/test/automagic_dashboards.clj
  test/metabase/test/fixtures.clj
  test/metabase/test_runner.clj
  test/metabase/test_runner/assert_exprs.clj
  test/metabase/transforms/specs_test.clj
Labels: .Team/QueryProcessor, no-backport

#34892 Refine CI triggers for E2E workflow
  .github/file-paths.yaml
Labels: Type:Tech Debt, .CI & Tests, no-backport

#35485 Stable order of serialization keys
  enterprise/backend/src/metabase_enterprise/serialization/dump.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/storage_test.clj
  resources/serialization-order.edn
  src/metabase/util.cljc
  src/metabase/util/yaml.clj
  test/metabase/util_test.cljc
Labels: backport, .Team/BackendComponents

#35533 Refine CI triggers for `i18n` workflow
  .github/file-paths.yaml
  .github/workflows/i18n.yml
Labels: Type:Tech Debt, .CI & Tests, no-backport

#35499 Deprecate PUT /api/dashboard/:id/cards endpoint
  src/metabase/api/dashboard.clj
Labels: .Release notes mention, no-backport, .Team/BackendComponents

#35480 Manual backport: Fix field Values search for PKs (#33006)
  src/metabase/api/field.clj
  test/metabase/api/field_test.clj
  test/metabase/test/util.clj
Labels: was-backported

#35501 🍒 Downgrade Cypress to 12.0.2 (backport to 46)
  .github/workflows/fuzzing.yml
  package.json
  yarn.lock
Labels: .CI & Tests, was-backported

#35490 Respect "enable nested queries" setting and database's "nested queries" feature
  frontend/src/metabase-lib/metadata/Database.ts
  frontend/src/metabase/models/components/ModelDetailPage/ModelDetailPage.tsx
  frontend/src/metabase/models/containers/ModelDetailPage/ModelDetailPage.tsx
  frontend/src/metabase/models/containers/ModelDetailPage/ModelDetailPage.unit.spec.tsx
Labels: backport, .Team/Query

#35526 Editing existing click behavior after target dashboard tab has been removed
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  frontend/src/metabase-lib/parameters/utils/click-behavior.ts
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/ClickBehaviorSidebar.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/LinkOptions/LinkedEntityPicker.tsx
Labels: no-backport, .Team/Query

#35443 Daily task to delete old inactive tables
  docs/configuring-metabase/environment-variables.md
  src/metabase/models/table.clj
  src/metabase/task/delete_inactive_tables.clj
  test/metabase/models/table_test.clj
  test/metabase/task/delete_inactive_tables_test.clj
Labels: no-backport, .Team/BackendComponents

#35403 Includes dbms_version for database_connection_successful snoplow event
  snowplow/iglu-client-embedded/schemas/com.metabase/database/jsonschema/1-0-1
  src/metabase/analytics/snowplow.clj
  src/metabase/api/database.clj
  src/metabase/api/setup.clj
  test/metabase/analytics/snowplow_test.clj
  test/metabase/api/database_test.clj
  test/metabase/api/setup_test.clj
Labels: no-backport, .Team/BackendComponents

#35317 Hide personal collections and items when configuring click behavior
  frontend/src/metabase-lib/parameters/utils/click-behavior.ts
  frontend/src/metabase-types/api/click-behavior.ts
  frontend/src/metabase/collections/components/CollectionHeader/CollectionCaption.tsx
  frontend/src/metabase/collections/components/CollectionMenu/CollectionMenu.tsx
  frontend/src/metabase/collections/components/CreateCollectionForm/CreateCollectionForm.tsx
  frontend/src/metabase/collections/containers/FormCollectionPicker/FormCollectionPicker.tsx
  frontend/src/metabase/collections/utils.ts
  frontend/src/metabase/collections/utils.unit.spec.ts
  frontend/src/metabase/containers/AddToDashSelectDashModal/AddToDashSelectDashModal.tsx
  frontend/src/metabase/containers/AddToDashSelectDashModal/utils.ts
  frontend/src/metabase/containers/CreateCollectionOnTheGo.tsx
  frontend/src/metabase/containers/DashboardPicker.tsx
  frontend/src/metabase/containers/DataPicker/CardPicker/utils.ts
  frontend/src/metabase/containers/ItemPicker/ItemPicker.tsx
  frontend/src/metabase/containers/ItemPicker/types.ts
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/LinkOptions/LinkOptions.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/LinkOptions/LinkedEntityPicker/LinkedEntityPicker.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/LinkOptions/LinkedEntityPicker/LinkedEntityPicker.unit.spec.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/LinkOptions/LinkedEntityPicker/index.ts
  frontend/src/metabase/dashboard/components/add-card-sidebar/QuestionPicker.jsx
  frontend/src/metabase/dashboard/containers/CreateDashboardForm.tsx
  frontend/src/metabase/dashboard/selectors/selectors.js
  frontend/src/metabase/entities/collections/utils.ts
  frontend/src/metabase/lib/urls/collections.ts
  frontend/src/metabase/query_builder/components/DataSelector/saved-question-picker/SavedQuestionPicker.jsx
Labels: .Team/42 (DEPRECATED), no-backport

#35411 Partial e2e tests - Visual glitches when joining same table and field multiple times
  e2e/test/scenarios/question/reproductions/19893-joining-same-table-and-field-multiple-times.cy.spec.js
Labels: backport, .Team/Query

#35280 Auto apply dashboard filters with the same field
  e2e/test/scenarios/dashboard-filters/parameters.cy.spec.js
  frontend/src/metabase-lib/parameters/utils/targets.ts
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase/dashboard/actions/auto-wire-parameters/actions.ts
  frontend/src/metabase/dashboard/actions/auto-wire-parameters/utils.ts
  frontend/src/metabase/dashboard/actions/cards.js
  frontend/src/metabase/dashboard/actions/parameters.js
  frontend/src/metabase/dashboard/actions/tabs.ts
  frontend/src/metabase/dashboard/actions/utils.ts
Labels: visual, .Team/42 (DEPRECATED), no-backport

#35539 Rename unparallelizable serdes functions to have exclamation marks
  enterprise/backend/src/metabase_enterprise/audit_db.clj
  enterprise/backend/src/metabase_enterprise/serialization/api/serialize.clj
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/src/metabase_enterprise/serialization/dump.clj
  enterprise/backend/src/metabase_enterprise/serialization/load.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/backfill_ids.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/storage.clj
  enterprise/backend/test/metabase_enterprise/serialization/load_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/backfill_ids_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj
  src/metabase/cmd.clj
  test/metabase/cmd_test.clj
Labels: no-backport, .Team/BackendComponents

#35530 remove dashcards not in serialization data when loading
  enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj
  src/metabase/models/dashboard.clj
Labels: backport, .Team/BackendComponents

#35593 load-metabase! now has an exclamation mark in the name
  enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj
Labels: no-backport, .Team/BackendComponents

#35579 Fix newly created E2E CSV flakes
  e2e/test/scenarios/collections/uploads.cy.spec.js
Labels: .CI & Tests, flaky-test-fix, no-backport

#35531 Add migration to remove FK target fields for previously inactive fields
  resources/migrations/000_migrations.yaml
  test/metabase/db/schema_migrations_test.clj
Labels: no-backport, .Team/BackendComponents

#35568 Fix Custom Label Line Height in Radio Component
  frontend/src/metabase/ui/components/inputs/Radio/Radio.styled.tsx
Labels: backport, .Team/DashViz, .Team/AdminWebapp

#35608 Give cljs tests 15 min
  .github/workflows/cljs.yml
Labels: backport, .Team/AdminWebapp

#35617 Refine default CI triggers
  .github/file-paths.yaml
Labels: .CI & Tests, no-backport

#35522 Speed up audit DB tests
  enterprise/backend/src/metabase_enterprise/audit_db.clj
  enterprise/backend/test/metabase_enterprise/audit_app/api/collection_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/api/database_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/permissions_test.clj
  enterprise/backend/test/metabase_enterprise/audit_db_test.clj
Labels: no-backport, .Team/AdminWebapp

#35580 Further optimize static-viz check for the backend workflow
  .github/workflows/backend.yml
Labels: .CI & Tests, no-backport

#35549 Add don't bin option for temporal bucketing
  e2e/test/scenarios/binning/binning-options.cy.spec.js
  frontend/src/metabase-lib/test-helpers.ts
  frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BucketPickerPopover.unit.spec.tsx
  frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/TemporalBucketPickerPopover.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/BreakoutStep/BreakoutStep.unit.spec.tsx
Labels: backport, .Team/Query

#35391 Audit log CRUD permission failures
  resources/migrations/000_migrations.yaml
  src/metabase/api/common.clj
  src/metabase/events/audit_log.clj
  src/metabase/events/schema.clj
  src/metabase/models/audit_log.clj
  src/metabase/models/dashboard.clj
  test/metabase/api/common_test.clj
Labels: no-backport, .Team/AdminWebapp

#35603 docs - update links
  docs/embedding/introduction.md
  docs/embedding/static-embedding.md
  docs/troubleshooting-guide/my-dashboard-is-slow.md
Labels: Type:Documentation, backport

#35602 Update Babel and MySQL2 Dependencies
  package.json
  yarn.lock
Labels: backport, dependencies, .Team/AdminWebapp

#35559 Add subscription-send and alert-send events
  enterprise/backend/test/metabase_enterprise/sandbox/pulse_test.clj
  src/metabase/events/audit_log.clj
  src/metabase/pulse.clj
  test/metabase/events/audit_log_test.clj
Labels: no-backport, .Team/AdminWebapp

#35612 Fixing flaky tests related to `inner-query-name-collisions-test` (#32355)
  test/metabase/metabot/metabot_util_test.clj
Labels: backport, flaky-test-fix, .Team/DashViz

#35624 Remove `auditv2-main` from uberjar workflow
  .github/workflows/uberjar.yml
Labels: no-backport, .Team/AdminWebapp

#35592 Revert "Generate sane SQL for a DATE[TIME] expression = ..." (#35523)
  shared/src/metabase/mbql/schema.cljc
  src/metabase/lib/metadata/cached_provider.cljc
  src/metabase/lib/metadata/composed_provider.cljc
  src/metabase/lib/metadata/jvm.clj
  src/metabase/query_processor/middleware/optimize_temporal_filters.clj
  src/metabase/query_processor/middleware/wrap_value_literals.clj
  test/metabase/lib/metadata/cached_provider_test.cljc
  test/metabase/lib/metadata/composed_provider_test.cljc
  test/metabase/lib/metadata/jvm_test.clj
  test/metabase/lib/test_metadata/graph_provider.cljc
  test/metabase/lib/test_util/metadata_providers/mock.cljc
  test/metabase/query_processor/middleware/optimize_temporal_filters_test.clj
  test/metabase/query_processor/middleware/wrap_value_literals_test.clj
  test/metabase/query_processor_test/filter_test.clj
Labels: .Team/QueryProcessor, no-backport

#35589 Fix "Create new pulse" E2E flake
  e2e/test/scenarios/sharing/pulse.cy.spec.js
Labels: .CI & Tests, backport, flaky-test-fix, .Team/AdminWebapp

#35616 Fix public link E2E flakes
  e2e/test/scenarios/sharing/reproductions/20393-public-dashboard-nested-card-with-parameters.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/22524-public-dashboard-updates-after-changing-parameters.cy.spec.js
Labels: .CI & Tests, flaky-test-fix, .Team/AdminWebapp

#35604 🍒 Update Babel and MySQL2 Dependencies (manual backport to 47)
  package.json
  yarn.lock
Labels: was-backported, dependencies

#35545 avoid calling fetchCardData in undoRemoveCardFromDashboard for virtual cards
  e2e/test/scenarios/dashboard/reproductions/12926-editing-dashboards-doesnt-cancel-running-queries.cy.spec.js
  frontend/src/metabase/dashboard/actions/cards.js
Labels: backport, .Team/Embedding

#35646 Include E2E workflow in file-path triggers
  .github/file-paths.yaml
Labels: Type:Tech Debt, .CI & Tests, no-backport
