Repository metabase/metabase, pull requests merged in 2023-08, with the labels that each got.

#32780 Upgrade Deploysentinel to `v0.8.8`
  package.json
  yarn.lock
Labels: .CI & Tests, backport

#31755 Migrate database.options to database.settings
  enterprise/backend/test/metabase_enterprise/advanced_config/caching_test.clj
  resources/migrations/000_migrations.yaml
  src/metabase/api/database.clj
  src/metabase/api/persist.clj
  src/metabase/db/custom_migrations.clj
  src/metabase/db/liquibase.clj
  src/metabase/db/setup.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql.clj
  src/metabase/events/persisted_info.clj
  src/metabase/models/database.clj
  src/metabase/models/interface.clj
  src/metabase/task/persist_refresh.clj
  test/metabase/api/card_test.clj
  test/metabase/api/database_test.clj
  test/metabase/api/persist_test.clj
  test/metabase/api/table_test.clj
  test/metabase/db/custom_migrations_test.clj
  test/metabase/events/persisted_info_test.clj
  test/metabase/task/persist_refresh_test.clj
Labels: .Team/42 :milky_way:

#32731 Handle absolute link for LinkCards on sub-path properly
  frontend/src/metabase/visualizations/register.js
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.styled.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/index.ts
Labels: visual, .Team/42 :milky_way:

#32711 indicate orphan dashboard parameters
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.jsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.styled.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.unit.spec.jsx
Labels: backport, .Team/PixelPolice :police_officer:

#32684 improve actions-on-dashboards e2e tests
  e2e/support/helpers/e2e-qa-databases-helpers.js
  e2e/test/scenarios/actions/actions-on-dashboards.cy.spec.js
Labels: backport, flaky-test-fix, .Team/PixelPolice :police_officer:

#32786 add npretto to team.json
  .github/team.json
Labels: .Team/42 :milky_way:

#32791 Add e2e tests for changing column list in the query in viz settings
  e2e/test/scenarios/visualizations/table-column-settings.cy.spec.js
  frontend/src/metabase/visualizations/components/settings/ChartSettingOrderedColumns.jsx
Labels: support/Repro, visual, .Team/42 :milky_way:

#32735 Ignore H2 databases in load-from-h2
  src/metabase/cmd/copy.clj
  test/metabase/cmd/copy_test.clj
  test/metabase/cmd/dump_to_h2_test.clj
  test/metabase/cmd/load_and_dump_test.clj
  test/metabase/cmd/load_from_h2_test.clj
  test/metabase/cmd/rotate_encryption_key_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32777 [Manual backport] Bump org.apache.sshd/sshd-core (#32762)
  deps.edn
  src/metabase/util/ssh.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32734 Disallow new H2 connections
  e2e/runner/cypress-runner-backend.js
  e2e/runner/cypress-runner-generate-snapshots.js
  e2e/runner/cypress-runner-run-tests.js
  e2e/test/scenarios/admin/databases/add-new-database.cy.spec.js
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.js
  e2e/test/scenarios/visualizations/reproductions/11435-time-tooltip-native.cy.spec.js
  enterprise/backend/test/metabase_enterprise/advanced_config/file/databases_test.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  frontend/src/metabase/admin/app/selectors.ts
  src/metabase/api/database.clj
  src/metabase/api/setup.clj
  src/metabase/api/table.clj
  src/metabase/driver/h2.clj
  src/metabase/driver/util.clj
  src/metabase/sync.clj
  test/metabase/api/database_test.clj
  test/metabase/api/setting_test.clj
  test/metabase/api/setup_test.clj
  test/metabase/driver/h2_test.clj
  test/metabase/driver/sql_jdbc/connection_test.clj
  test/metabase/driver/util_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32769 [MLv2] Fix join clause dispatches for card and table sources
  src/metabase/lib/join.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/test_metadata.cljc
  test/metabase/lib/test_util.cljc
Labels: Type:Bug, .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#32808 docs -update release list
  docs/releases.md
Labels: Type:Documentation, backport

#32809 docs - update list of releases manual backport
  docs/releases.md
Labels: Type:Documentation

#32763 Allow setting time for date filter at dashboard
  e2e/test/scenarios/dashboard-filters/dashboard-filters-date.cy.spec.js
  e2e/test/scenarios/native-filters/helpers/e2e-date-filter-helpers.js
  frontend/src/metabase/components/DateAllOptionsWidget/DateAllOptionsWidget.tsx
  frontend/src/metabase/components/DateAllOptionsWidget/index.ts
  frontend/src/metabase/components/DateRangeWidget/DateRangeWidget.tsx
  frontend/src/metabase/components/DateSingleWidget/DateSingleWidget.tsx
  frontend/src/metabase/parameters/components/ParameterValueWidget.jsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/HoursMinutesInput.tsx
Labels: .Team/42 :milky_way:

#32636 Backport of Create new collection when moving / saving things
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/question/new.cy.spec.js
  e2e/test/scenarios/question/question-management.cy.spec.js
  frontend/src/metabase/collections/components/BulkActions.jsx
  frontend/src/metabase/collections/components/MoveCollectionModal/MoveCollectionModal.tsx
  frontend/src/metabase/collections/containers/FormCollectionPicker/FormCollectionPicker.styled.tsx
  frontend/src/metabase/collections/containers/FormCollectionPicker/FormCollectionPicker.tsx
  frontend/src/metabase/containers/CollectionMoveModal.jsx
  frontend/src/metabase/containers/CollectionMoveModal.tsx
  frontend/src/metabase/containers/ItemPicker/ItemPicker.tsx
  frontend/src/metabase/containers/ItemPicker/ItemPicker.unit.spec.js
  frontend/src/metabase/containers/ItemPicker/ItemPickerView.tsx
  frontend/src/metabase/containers/ItemPicker/test-utils.js
  frontend/src/metabase/containers/SaveQuestionModal.tsx
  frontend/src/metabase/containers/SaveQuestionModal.unit.spec.tsx
  frontend/src/metabase/core/components/Button/Button.styled.tsx
  frontend/src/metabase/core/components/Button/Button.tsx
  frontend/src/metabase/dashboard/components/DashboardMoveModal.jsx
  frontend/src/metabase/dashboard/containers/CreateDashboardForm.tsx
  frontend/src/metabase/dashboard/containers/CreateDashboardModal.tsx
  frontend/src/metabase/dashboard/containers/CreateDashboardModal.unit.spec.tsx
  frontend/src/metabase/models/components/ModelDetailPage/ModelDetailHeader/ModelDetailHeader.tsx
  frontend/src/metabase/query_builder/components/QueryModals.tsx
  frontend/test/__support__/server-mocks/collection.ts
Labels: was-backported, .Team/PixelPolice :police_officer:

#32607 When embedded, force showing side nav when top nav is hidden
  e2e/test/scenarios/embedding/embedding-full-app.cy.spec.js
  frontend/src/metabase/nav/containers/Navbar.unit.spec.tsx
  frontend/src/metabase/redux/app.ts
  frontend/src/metabase/selectors/app.ts
Labels: backport, .Team/PixelPolice :police_officer:

#32800 Revert running E2E tests on Electron
  e2e/runner/cypress-runner-generate-snapshots.js
  e2e/runner/cypress-runner-run-tests.js
Labels: .CI & Tests

#32789 Upgrade Deploysentinel to `v0.8.8` (#32780)
  package.json
  yarn.lock
Labels: was-backported

#32752 Add `SearchFilterModal` to integration branch
  frontend/src/metabase/search/components/SearchFilterModal/SearchFilterModal.styled.tsx
  frontend/src/metabase/search/components/SearchFilterModal/SearchFilterModal.tsx
  frontend/src/metabase/search/components/SearchFilterModal/SearchFilterModal.unit.spec.tsx
  frontend/src/metabase/search/components/SearchFilterModal/SearchFilterModalFooter.styled.tsx
  frontend/src/metabase/search/components/SearchFilterModal/SearchFilterModalFooter.tsx
Labels: .Team/42 :milky_way:

#32662 Global search: filter by verified
  src/metabase/api/search.clj
  src/metabase/moderation.clj
  src/metabase/public_settings/premium_features.clj
  src/metabase/search/config.clj
  src/metabase/search/filter.clj
  test/metabase/api/search_test.clj
  test/metabase/search/filter_test.clj
  test/metabase/test.clj
  test/metabase/test/util.clj
Labels: .Team/42 :milky_way:

#32679 [MLv2] Add `lib.field/add-field` and `remove-field`
  src/metabase/lib/core.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/js.cljs
  test/metabase/lib/field_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32754 Fix long running queries possibly piling up via auto-refresh
  e2e/test/scenarios/dashboard/reproductions/12578-prevent-fetching-slow-cards-more-than-one-at-a-time-when-auto-refreshing.cy.spec.js
  frontend/src/metabase-types/store/dashboard.ts
  frontend/src/metabase-types/store/mocks/dashboard.ts
  frontend/src/metabase/dashboard/actions/data-fetching.js
  frontend/src/metabase/dashboard/components/RefreshWidget.jsx
  frontend/src/metabase/dashboard/constants.ts
  frontend/src/metabase/dashboard/hoc/DashboardControls.jsx
  frontend/src/metabase/dashboard/reducers.js
  frontend/src/metabase/dashboard/reducers.unit.spec.js
Labels: backport, .Team/42 :milky_way:

#32743 🍒 Backported "Fix UX for empty dashboard filter with multiple choices"
  e2e/test/scenarios/dashboard-filters/dashboard-filters-text-category.cy.spec.js
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.jsx
  frontend/src/metabase/components/ListField/ListField.tsx
  frontend/src/metabase/components/ListField/index.ts
  frontend/src/metabase/dashboard/actions/parameters.js
  frontend/src/metabase/modes/components/drill/common/ColumnFilterDrillPopover.tsx
  frontend/src/metabase/query_builder/components/GuiQueryEditor.jsx
  frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.tsx
  frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.unit.spec.tsx
  frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverFooter.tsx
  frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverHeader.tsx
  frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverPicker.tsx
  frontend/src/metabase/query_builder/components/filters/FilterPopover/index.tsx
  frontend/src/metabase/query_builder/components/filters/FilterWidget.tsx
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterSelect/BulkFilterSelect.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/FilterStep.tsx
  frontend/src/metabase/query_builder/components/view/QuestionFilters.jsx
Labels: .Team/42 :milky_way:

#32215 Get first and last rows when sampling json columns
  dev/src/dev.clj
  dev/src/dev/debug_qp.clj
  docs/developers-guide/driver-changelog.md
  modules/drivers/oracle/src/metabase/driver/oracle.clj
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
  src/metabase/util/honey_sql_1.clj
  src/metabase/util/honey_sql_2.clj
  src/metabase/util/honeysql_extensions.clj
  test/metabase/driver/mysql_test.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/driver/sql_jdbc/sync/describe_table_test.clj
  test/metabase/util/honey_sql_1_test.clj
  test/metabase/util/honey_sql_2_test.clj
Labels: backport, .Team/42 :milky_way:

#32470 [Epic] Allow basic deletes and updates on object detail views - Milestone 1
  e2e/test/scenarios/actions/actions-in-object-detail-view.cy.spec.js
  frontend/src/metabase-types/api/actions.ts
  frontend/src/metabase/actions/components/ActionForm/ActionForm.tsx
  frontend/src/metabase/actions/components/ActionViz/Action.tsx
  frontend/src/metabase/actions/components/ActionViz/ActionVizForm.tsx
  frontend/src/metabase/actions/components/ActionViz/utils.ts
  frontend/src/metabase/actions/containers/ActionExecuteModal/ActionExecuteModal.tsx
  frontend/src/metabase/actions/containers/ActionParametersInputForm/ActionParametersInputForm.tsx
  frontend/src/metabase/actions/containers/ActionParametersInputForm/ActionParametersInputForm.unit.spec.tsx
  frontend/src/metabase/actions/hooks/use-action-form/use-action-form.ts
  frontend/src/metabase/actions/hooks/use-action-form/use-action-form.unit.spec.ts
  frontend/src/metabase/actions/utils.ts
  frontend/src/metabase/common/hooks/index.ts
  frontend/src/metabase/common/hooks/use-action-list-query/index.ts
  frontend/src/metabase/common/hooks/use-action-list-query/use-action-list-query.ts
  frontend/src/metabase/common/hooks/use-action-list-query/use-action-list-query.unit.spec.tsx
  frontend/src/metabase/components/EntityMenu/EntityMenu.jsx
  frontend/src/metabase/components/ModalContent/ModalContent.tsx
  frontend/src/metabase/dashboard/actions/actions.ts
  frontend/src/metabase/models/components/ModelDetailPage/ModelActionDetails/ModelActionDetails.tsx
  frontend/src/metabase/models/components/ModelDetailPage/ModelDetailPage.tsx
  frontend/src/metabase/models/containers/ModelDetailPage/ModelDetailPage.tsx
  frontend/src/metabase/services.js
  frontend/src/metabase/visualizations/components/ObjectDetail/DeleteObjectModal.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailWrapper.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/types.ts
  frontend/src/metabase/visualizations/components/ObjectDetail/utils.ts
  frontend/src/metabase/visualizations/components/ObjectDetail/utils.unit.spec.ts
  frontend/test/__support__/utils.ts
  src/metabase/actions.clj
  src/metabase/api/action.clj
  test/metabase/api/action_test.clj
Labels: .Epic, visual, .Team/42 :milky_way:

#32702 [serdes] Add a missing dependency of dashcards on actions
  enterprise/backend/test/metabase_enterprise/serialization/v2/extract_test.clj
  src/metabase/models/dashboard.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32710 Remove unused `GET /api/database/db-ids-with-deprecated-drivers` endpoint
  frontend/src/metabase/services.js
  src/metabase/api/database.clj
  test/metabase/api/database_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#31935 Show all breakouts and metrics in tooltip when merging stacked bar charts
  frontend/src/metabase/visualizations/lib/apply_tooltips.js
  frontend/src/metabase/visualizations/lib/apply_tooltips.unit.spec.js
Labels: visual, .Team/PixelPolice :police_officer:

#32801 Fully prevent open redirects during JWT/SAML auth
  enterprise/backend/src/metabase_enterprise/sso/integrations/saml.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/sso_utils.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/saml_test.clj
Labels: backport, .Team/PixelPolice :police_officer:

#32859 Allow `w` and `h` props usage in eslint for Mantine
  .eslintrc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32871 fix resetting to default dashcard visualization settings
  frontend/src/metabase/visualizations/components/ChartSettings.jsx
  frontend/src/metabase/visualizations/components/ChartSettings.unit.spec.js
Labels: backport, visual, .Team/PixelPolice :police_officer:

#32462 Enable parameter mapping for heading dash-cards
  e2e/support/helpers/e2e-dashboard-helpers.js
  e2e/test/scenarios/dashboard/text-parameters.cy.spec.js
  frontend/src/metabase-lib/parameters/utils/targets.ts
  frontend/src/metabase-types/api/parameters.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.jsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.unit.spec.jsx
  frontend/src/metabase/dashboard/components/DashCard/Dashcard.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashCard/utils.ts
  frontend/src/metabase/parameters/utils/mapping-options.js
  frontend/src/metabase/visualizations/shared/utils/parameter-substitution.js
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.styled.tsx
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.tsx
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.unit.spec.tsx
  frontend/src/metabase/visualizations/visualizations/Text/Text.jsx
  shared/src/metabase/shared/parameters/parameters.cljc
  shared/test/metabase/shared/parameters/parameters_test.cljc
  src/metabase/pulse/parameters.clj
  test/metabase/dashboard_subscription_test.clj
Labels: Reporting/Dashboards, Reporting/Pulses, backport, visual, .Team/PixelPolice :police_officer:

#32805 `join-condition-lhs-display-name` should use join condition LHS
  frontend/src/metabase-lib/join.ts
  src/metabase/lib/join.cljc
  src/metabase/lib/js.cljs
  test/metabase/lib/join_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32874 Ldap group mapping slash issue
  src/metabase/integrations/ldap.clj
  test/metabase/integrations/ldap_test.clj
Labels: backport

#32878 Move random stuff in `metabase.test` to `metabase.test.util.misc`
  test/metabase/test.clj
  test/metabase/test/util/misc.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32873 Get rid of backfill query for user-recent-views
  src/metabase/events/view_log.clj
Labels: backport, .Team/PixelPolice :police_officer:

#32753 Add `SearchFunnelButton` and `SearchBar` to integration branch
  e2e/test/scenarios/embedding/embedding-full-app.cy.spec.js
  e2e/test/scenarios/question/notebook.cy.spec.js
  frontend/src/metabase/nav/components/SearchBar.styled.tsx
  frontend/src/metabase/nav/components/SearchBar.tsx
  frontend/src/metabase/nav/components/SearchBar.unit.spec.tsx
  frontend/src/metabase/nav/components/SearchResults.jsx
  frontend/src/metabase/query_builder/components/view/QuestionFilters.jsx
Labels: .Team/42 :milky_way:

#32825 Define a new persist-models-enabled setting for database.
  src/metabase/models/database.clj
  test/metabase/api/database_test.clj
Labels: .Team/42 :milky_way:

#32843 Fast `mu/defn`
  .clj-kondo/config.edn
  enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj
  src/metabase/cmd.clj
  src/metabase/lib/remove_replace.cljc
  src/metabase/util/malli.cljc
  src/metabase/util/malli/defmethod.clj
  src/metabase/util/malli/defn.clj
  src/metabase/util/malli/fn.clj
  src/metabase/util/malli/registry.cljc
  src/metabase/util/malli/schema.clj
  test/metabase/cmd_test.clj
  test/metabase/lib/metadata_test.cljc
  test/metabase/lib/table_test.cljc
  test/metabase/metabot/metabot_util_test.clj
  test/metabase/util/malli/defmethod_test.clj
  test/metabase/util/malli/defn_test.clj
  test/metabase/util/malli/describe_test.clj
  test/metabase/util/malli/fn_test.clj
  test/metabase/util/malli_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32490 Systematize date range formats in Filter name
  frontend/src/metabase-lib/queries/structured/Filter.ts
  frontend/src/metabase-lib/queries/utils/query-time.js
  frontend/src/metabase/lib/formatting/date.tsx
  frontend/src/metabase/lib/formatting/date.unit.spec.tsx
  frontend/src/metabase/lib/formatting/types.ts
  frontend/src/metabase/lib/time.ts
  frontend/src/metabase/query_builder/components/filters/modals/InlineDatePicker/InlineDatePicker.unit.spec.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DatePicker/DatePicker.tsx
  frontend/test/metabase-lib/lib/queries/structured/Filter.unit.spec.js
  frontend/test/metabase/lib/formatting/date.unit.spec.js
Labels: .Team/PixelPolice :police_officer:

#32923 [47] Prevent malicious H2 connection string properties (#32733)
  src/metabase/api/setup.clj
  src/metabase/driver/h2.clj
  src/metabase/setup.clj
  test/metabase/api/setup_test.clj
  test/metabase/driver/h2_test.clj
  test/metabase/setup_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32706 docs - restore reference to data reference section
  docs/exploration-and-organization/data-model-reference.md
Labels: Type:Documentation, backport

#32599 Change field values to have consistent shape in API responses
  enterprise/backend/test/metabase_enterprise/sandbox/api/card_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/dashboard_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/dataset_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/field_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/models/params/chain_filter_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/models/params/field_values_test.clj
  frontend/src/metabase-types/api/field.ts
  frontend/src/metabase-types/api/mocks/field.ts
  frontend/src/metabase-types/api/mocks/presets/sample_database.ts
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataFieldSettings/MetadataFieldSettings.unit.spec.tsx
  frontend/src/metabase/components/FieldValuesWidget/utils.ts
  frontend/src/metabase/parameters/actions.ts
  frontend/test/__support__/server-mocks/field.ts
  src/metabase/api/card.clj
  src/metabase/api/dashboard.clj
  src/metabase/api/dataset.clj
  src/metabase/api/field.clj
  src/metabase/db/metadata_queries.clj
  src/metabase/models/field_values.clj
  src/metabase/models/params/chain_filter.clj
  src/metabase/models/params/custom_values.clj
  src/metabase/models/params/field_values.clj
  src/metabase/util/malli/schema.clj
  test/metabase/api/card_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/dataset_test.clj
  test/metabase/api/embed_test.clj
  test/metabase/api/public_test.clj
  test/metabase/db/metadata_queries_test.clj
  test/metabase/models/field_values_test.clj
  test/metabase/models/params/chain_filter_test.clj
  test/metabase/models/params/custom_values_test.clj
Labels: .Team/42 :milky_way:

#32813 Fix nils in subscriptions for values in series
  src/metabase/pulse/render/body.clj
  test/metabase/pulse/render/body_test.clj
Labels: visual, .Team/PixelPolice :police_officer:

#32779 Fix info icon on scalar/trend dashboard cards
  frontend/src/metabase/core/components/Icon/icons/index.ts
  frontend/src/metabase/core/components/Icon/icons/info.svg
  frontend/src/metabase/core/components/Icon/icons/info_filled.svg
  frontend/src/metabase/visualizations/components/ScalarValue/ScalarValue.jsx
  frontend/src/metabase/visualizations/components/ScalarValue/ScalarValue.styled.tsx
  frontend/src/metabase/visualizations/visualizations/Scalar/Scalar.unit.spec.js
Labels: backport, visual

#32736 Prevent mismatches between engine and details
  src/metabase/driver.clj
  src/metabase/driver/sql_jdbc/connection.clj
  test/metabase/driver/h2_test.clj
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#32921 :cherries: Manual Backport #32462
  e2e/support/helpers/e2e-dashboard-helpers.js
  e2e/test/scenarios/dashboard/text-parameters.cy.spec.js
  frontend/src/metabase-lib/parameters/utils/targets.ts
  frontend/src/metabase-types/api/parameters.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.jsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.unit.spec.jsx
  frontend/src/metabase/dashboard/components/DashCard/Dashcard.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashCard/utils.ts
  frontend/src/metabase/parameters/utils/mapping-options.js
  frontend/src/metabase/visualizations/shared/utils/parameter-substitution.js
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.styled.tsx
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.tsx
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.unit.spec.tsx
  frontend/src/metabase/visualizations/visualizations/Text/Text.jsx
  shared/src/metabase/shared/parameters/parameters.cljc
  shared/test/metabase/shared/parameters/parameters_test.cljc
  src/metabase/pulse/parameters.clj
  test/metabase/dashboard_subscription_test.clj
Labels: was-backported, visual, .Team/PixelPolice :police_officer:

#32925 [47] Disallow H2 databases in load-from-h2 (#32735)
  src/metabase/cmd/copy.clj
  test/metabase/cmd/copy_test.clj
  test/metabase/cmd/dump_to_h2_test.clj
  test/metabase/cmd/load_and_dump_test.clj
  test/metabase/cmd/load_from_h2_test.clj
  test/metabase/cmd/rotate_encryption_key_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32817 The error message we show when Google SSO login fails had a bit of CS…
  frontend/src/metabase/auth/components/GoogleButton/GoogleButton.styled.tsx
Labels: backport

#32924 [47] Disallow new H2 connections (#32734)
  e2e/runner/cypress-runner-backend.js
  e2e/runner/cypress-runner-generate-snapshots.js
  e2e/runner/cypress-runner-run-tests.js
  e2e/test/scenarios/admin/databases/add-new-database.cy.spec.js
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.js
  e2e/test/scenarios/visualizations/reproductions/11435-time-tooltip-native.cy.spec.js
  enterprise/backend/test/metabase_enterprise/advanced_config/file/databases_test.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  frontend/src/metabase/admin/app/selectors.ts
  src/metabase/api/database.clj
  src/metabase/api/setup.clj
  src/metabase/api/table.clj
  src/metabase/driver/h2.clj
  src/metabase/driver/util.clj
  src/metabase/sync.clj
  test/metabase/api/database_test.clj
  test/metabase/api/setting_test.clj
  test/metabase/api/setup_test.clj
  test/metabase/driver/h2_test.clj
  test/metabase/driver/sql_jdbc/connection_test.clj
  test/metabase/driver/util_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32835 Add repro to undo move dashboard doesn't always work in v44
  e2e/support/helpers/e2e-dashboard-helpers.js
  e2e/test/scenarios/dashboard/reproductions/25705-undo-moving-dashboards.cy.spec.js
Labels: .CI & Tests, support/Repro, backport, .Team/42 :milky_way:

#32892 Install `terser-webpack-plugin`
  package.json
  yarn.lock
Labels: .Building & Releasing, .Frontend, backport

#32810 Added props to the FormFooter component to optionally add a border
  enterprise/frontend/src/metabase-enterprise/advanced_permissions/components/ImpersonationModal/ImpersonationModalView.tsx
  frontend/src/metabase/core/components/FormFooter/FormFooter.styled.tsx
Labels: backport

#32899 Add tests to showing most recent dashboard revisions
  e2e/support/helpers/e2e-dashboard-helpers.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-auto-apply.cy.spec.js
  e2e/test/scenarios/dashboard/caching.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/16559-show-recent-dashboard-revision.cy.spec.js
Labels: .CI & Tests, support/Repro, backport, .Team/42 :milky_way:

#32893 Make it easier to configure `QueryColumnPicker` color
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.styled.tsx
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.tsx
  frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.styled.tsx
  frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/BaseBucketPickerPopover.tsx
  frontend/src/metabase/common/components/QueryColumnPicker/BucketPickerPopover/types.ts
  frontend/src/metabase/common/components/QueryColumnPicker/QueryColumnPicker.styled.tsx
  frontend/src/metabase/common/components/QueryColumnPicker/QueryColumnPicker.tsx
  frontend/src/metabase/lib/colors/types.ts
  frontend/src/metabase/query_builder/components/notebook/steps/AggregateStep/AggregateStep.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/AggregateStep/AggregateStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/BreakoutStep/BreakoutStep.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/BreakoutStep/BreakoutStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/SortStep/SortStep.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/BreakoutColumnList/BreakoutColumnListItem/BreakoutColumnListItem.styled.tsx
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#32910 Add tests to dashboard should work if some cards are broken
  e2e/test/scenarios/dashboard/reproductions/13736-dashboard-should-work-if-some-cards-are-broken.cy.spec.js
Labels: .CI & Tests, support/Repro, backport, .Team/42 :milky_way:

#32946 Run Cypress using Chromium `111.0.5563.146`
  .github/workflows/e2e-tests.yml
Labels: .CI & Tests, backport

#32807 [MLv2] Add function to sync join-condition temporal bucketing options
  shared/src/metabase/mbql/util.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/schema.cljc
  test/metabase/lib/join_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:

#32951 Allow workflow to be cancelled via UI or by concurrent job
  .github/workflows/e2e-tests.yml
Labels: backport, .Team/42 :milky_way:

#32881 Backport dashboard performance fixes
  .github/file-paths.yaml
  .github/workflows/require-percy-tests.yml
  e2e/test/scenarios/dashboard/reproductions/26230-dashboard-sticky-filter-incorrectly-positioned.cy.spec.js
  e2e/test/visual/account/notifications.cy.spec.js
  e2e/test/visual/admin/colors.cy.spec.js
  e2e/test/visual/admin/fonts.cy.spec.js
  e2e/test/visual/admin/permissions.cy.spec.js
  e2e/test/visual/collections/bookmarks.cy.spec.js
  e2e/test/visual/collections/timelines.cy.spec.js
  e2e/test/visual/dashboard/dashboard-layout.cy.spec.js
  e2e/test/visual/dashboard/fullscreen.cy.spec.js
  e2e/test/visual/dashboard/parameters-widget.cy.spec.js
  e2e/test/visual/models/editor.cy.spec.js
  e2e/test/visual/notebook/notebook.cy.spec.js
  e2e/test/visual/onboarding/urls.cy.spec.js
  frontend/src/metabase/components/ExplicitSize.jsx
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.jsx
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.styled.jsx
  frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.js
  frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.unit.spec.js
  frontend/src/metabase/visualizations/components/CardRenderer.jsx
  package.json
  yarn.lock
Labels: was-backported, visual, .Team/PixelPolice :police_officer:

#32774 Change full-app embedding to interactive embedding in admin section
  e2e/test/scenarios/embedding/embedding-premium-token.cy.spec.js
  e2e/test/scenarios/embedding/embedding-smoketests.cy.spec.js
  e2e/test/scenarios/embedding/embedding-standalone.cy.spec.js
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/common.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/FullAppEmbeddingLinkWidget/FullAppEmbeddingLinkWidget.tsx
  frontend/src/metabase/admin/settings/selectors.js
Labels: backport

#32869 Manual backport of #32801 to 47
  enterprise/backend/src/metabase_enterprise/sso/integrations/saml.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/sso_utils.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/saml_test.clj
Labels: .Team/PixelPolice :police_officer:

#32954 🍒 Manual Backport #32193
  src/metabase/api/user.clj
  test/metabase/api/user_test.clj
Labels: was-backported

#32875 Fix x-axis default value in visualization settings
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/src/metabase/visualizations/lib/settings/graph.unit.spec.js
  frontend/src/metabase/visualizations/visualizations/RowChart/utils/settings-definitions.js
Labels: backport, visual, .Team/PixelPolice :police_officer:

#32955 🍒 Manual Backport #32458
  .clj-kondo/macros/metabase_enterprise/serialization/test_util.clj
  enterprise/backend/src/metabase_enterprise/serialization/load.clj
  enterprise/backend/test/metabase_enterprise/serialization/load_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/test_util.clj
Labels: was-backported

#32960 Fix load-from-h2 bugs with H2 databases
  src/metabase/cmd/copy.clj
  test/metabase/cmd/copy_test.clj
  test/metabase/cmd/dump_to_h2_test.clj
  test/metabase/cmd/load_and_dump_test.clj
  test/metabase/cmd/load_from_h2_test.clj
  test/metabase/cmd/rotate_encryption_key_test.clj
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#32798 Fully hydrate PUT-ed collections, which the FE depends on
  e2e/support/helpers/e2e-collection-helpers.js
  e2e/test/scenarios/collections/collections.cy.spec.js
  e2e/test/scenarios/collections/reproductions/30235-turn-official-after-move.cy.spec.js
  src/metabase/api/collection.clj
  test/metabase/api/collection_test.clj
Labels: backport, .Team/42 :milky_way:

#32972 Introduce a backport reminder CI workflow
  .github/workflows/backport-reminder.yml
Labels: no-backport

#32751 Modify `SearchApp` for integration branch
  frontend/src/metabase/search/components/SearchFilterModal/SearchFilterModal.tsx
  frontend/src/metabase/search/components/SearchResult.tsx
  frontend/src/metabase/search/components/TypeSearchSidebar/TypeSearchSidebar.tsx
  frontend/src/metabase/search/components/TypeSearchSidebar/TypeSearchSidebar.unit.spec.tsx
  frontend/src/metabase/search/components/TypeSearchSidebar/index.ts
  frontend/src/metabase/search/constants.ts
  frontend/src/metabase/search/containers/SearchApp.jsx
  frontend/src/metabase/search/containers/SearchApp.unit.spec.tsx
  frontend/src/metabase/search/containers/constants.ts
  frontend/src/metabase/search/types.ts
  frontend/src/metabase/search/utils/search-location/search-location.ts
  frontend/src/metabase/search/utils/search-location/search-location.unit.spec.ts
Labels: .Team/42 :milky_way:

#32952 Fix remaining CSP issues with styles
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FormCreator.tsx
  frontend/src/metabase/app.js
  frontend/src/metabase/components/Modal/WindowModal.tsx
  frontend/src/metabase/core/components/DragDropContext/DragDropContext.tsx
  frontend/src/metabase/core/components/DragDropContext/index.ts
  frontend/src/metabase/styled-components/components/EmotionCacheProvider/EmotionCacheProvider.tsx
  frontend/src/metabase/styled-components/components/EmotionCacheProvider/index.ts
  frontend/src/metabase/ui/components/theme/ThemeProvider/ThemeProvider.tsx
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.styled.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPicker.jsx
Labels: visual, .Team/42 :milky_way:

#32850 Fix errors when removing custom columns used by other clauses
  e2e/test/scenarios/question/reproductions/32625-removing-dependent-clauses.cy.spec.js
  frontend/src/metabase/query_builder/components/notebook/Notebook.tsx
Labels: support/Repro, backport, .Team/QueryProcessor :hammer_and_wrench:

#32976 Remove unused `getFieldTarget` function
  frontend/src/metabase-lib/queries/utils/field-ref.js
  frontend/test/metabase/lib/query.unit.spec.js
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#32965 Embiggen chart selection icons
  frontend/src/metabase/query_builder/components/view/sidebars/ChartTypeSidebar.tsx
Labels: backport

#32957 🍒 Manual Backport #32779
  frontend/src/metabase/core/components/Icon/icons/index.ts
  frontend/src/metabase/core/components/Icon/icons/info.svg
  frontend/src/metabase/core/components/Icon/icons/info_filled.svg
  frontend/src/metabase/visualizations/components/ScalarValue/ScalarValue.jsx
  frontend/src/metabase/visualizations/components/ScalarValue/ScalarValue.styled.tsx
  frontend/src/metabase/visualizations/visualizations/Scalar/Scalar.unit.spec.js
Labels: was-backported, visual

#32969 Remove redundant embedding-standalone E2E spec
  e2e/test/scenarios/embedding/embedding-standalone.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests

#32796 Fix stacking of dashcards
  e2e/test/scenarios/dashboard/reproductions/31274-dashcard-actions-overlap.cy.spec.js
  frontend/src/metabase/css/dashboard.css
  frontend/src/metabase/dashboard/components/DashCard/DashCard.styled.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.styled.tsx
Labels: backport, .Team/42 :milky_way:

#33000 Change log level for api.field/search-values to error
  src/metabase/api/field.clj
Labels: .Team/42 :milky_way:, no-backport

#32949 Fix - Cannot remove questions when combining questions to create multi-series charts
  frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx
  frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.unit.spec.tsx
  frontend/src/metabase/dashboard/components/AddSeriesModal/index.ts
  frontend/src/metabase/dashboard/components/DashboardGrid.jsx
  frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx
  frontend/src/metabase/visualizations/components/legend/Legend.jsx
  frontend/src/metabase/visualizations/components/legend/LegendLayout.jsx
Labels: backport, visual, .Team/42 :milky_way:

#33013 docs - add Latvian to list of languages
  docs/configuring-metabase/localization.md
Labels: Type:Documentation, backport

#33010 Manual backport - Fix - Cannot remove questions when combining questions to create multi-series charts
  frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx
  frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.unit.spec.tsx
  frontend/src/metabase/dashboard/components/AddSeriesModal/index.ts
  frontend/src/metabase/dashboard/components/DashboardGrid.jsx
  frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx
  frontend/src/metabase/visualizations/components/legend/Legend.jsx
  frontend/src/metabase/visualizations/components/legend/LegendLayout.jsx
  frontend/test/__support__/utils.ts
Labels: was-backported, visual

#33032 Fix flaky Login history test
  test/metabase/api/login_history_test.clj
Labels: backport, .Team/42 :milky_way:

#33035 Add missing translations
  enterprise/frontend/src/metabase-enterprise/application_permissions/selectors.ts
  enterprise/frontend/src/metabase-enterprise/sandboxes/components/LoginAttributesWidget.jsx
  enterprise/frontend/src/metabase-enterprise/sandboxes/index.js
  frontend/src/metabase/admin/permissions/components/DataPermissionsHelp/DataPermissionsHelp.tsx
  frontend/src/metabase/admin/permissions/selectors/data-permissions/groups.ts
  frontend/src/metabase/home/components/CustomHomePageModal/CustomHomePageModal.tsx
  frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
  frontend/src/metabase/nav/components/DatabasePromptBanner/DatabasePromptBanner.tsx
Labels: backport, .Team/42 :milky_way:

#33020 docs - update releases 46.7
  docs/releases.md
Labels: Type:Documentation, no-backport

#32867 [Manual backport] Remove references to missing expressions when converting to pMBQL (#32685)
  src/metabase/lib/convert.cljc
  src/metabase/lib/schema.cljc
  test/metabase/lib/convert_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#33005 Create new `dashboard-cards` E2E group
  .github/workflows/e2e-tests.yml
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  e2e/test/scenarios/dashboard-cards/dashboard-card-resizing.cy.spec.js
  e2e/test/scenarios/dashboard-cards/dashboard-drill.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/17160-click-behavior-multiple-options.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/18454-card-description.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/20637-add-series-to-dashcard.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/27020-27105-static-viz-date-formatting-failures.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/29304-scalar-first-render-size-change.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/31628-responsive-scalars.cy.spec.js
  e2e/test/scenarios/dashboard-cards/visualizaiton-options.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-chained-filters.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filter-data-permissions.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/26230-dashboard-sticky-filter-incorrectly-positioned.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/31662-between-filter-default-value.cy.spec.js
  e2e/test/scenarios/organization/bookmarks-dashboard.cy.spec.js
Labels: .CI & Tests, backport

#33011 Address dashboard visual glitches caused by css refactoring
  e2e/test/scenarios/dashboard/reproductions/31274-dashcard-actions-overlap.cy.spec.js
  frontend/src/metabase/dashboard/components/DashCard/DashCard.styled.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.styled.tsx
Labels: backport, .Team/42 :milky_way:

#32927 docs - rename embedding
  docs/README.md
  docs/configuring-metabase/environment-variables.md
  docs/configuring-metabase/fonts.md
  docs/embedding/interactive-embedding.md
  docs/embedding/introduction.md
  docs/embedding/start.md
  docs/embedding/static-embedding-parameters.md
  docs/embedding/static-embedding.md
  docs/paid-features/overview.md
  docs/questions/query-builder/expressions/regexextract.md
  docs/questions/sharing/public-links.md
  docs/troubleshooting-guide/my-dashboard-is-slow.md
  docs/troubleshooting-guide/sandboxing.md
Labels: Type:Documentation, backport

#32872 Reproduce failed breakout detection in multistage queries
  e2e/test/scenarios/question/settings.cy.spec.js
Labels: support/Repro, backport, .Team/PixelPolice :police_officer:

#32898 Add Text and Anchor Mantine Components
  enterprise/frontend/src/metabase-enterprise/license/components/LicenseAndBillingSettings/LicenseAndBillingSettings.tsx
  frontend/src/metabase/collections/components/CollectionEmptyState/CollectionEmptyState.styled.tsx
  frontend/src/metabase/collections/components/CollectionEmptyState/CollectionEmptyState.tsx
  frontend/src/metabase/ui/components/typography/Anchor/Anchor.stories.mdx
  frontend/src/metabase/ui/components/typography/Anchor/index.ts
  frontend/src/metabase/ui/components/typography/Text/Text.stories.mdx
  frontend/src/metabase/ui/components/typography/index.ts
  frontend/src/metabase/ui/theme.ts
Labels: .Team/42 :milky_way:, no-backport

#32980 Use a dynamic nonce for the style-src CSP header
  frontend/src/metabase/setup/components/CompletedStep/CompletedStep.tsx
  frontend/src/metabase/styled-components/components/EmotionCacheProvider/EmotionCacheProvider.tsx
  frontend/src/types/global.d.ts
  resources/frontend_client/index_template.html
  resources/frontend_client/inline_js/index_bootstrap.js
  src/metabase/server/middleware/security.clj
  src/metabase/server/routes/index.clj
  test/metabase/api/common_test.clj
  test/metabase/server/middleware/security_test.clj
Labels: .Team/42 :milky_way:, no-backport

#33047 Don't lock display for models
  e2e/test/scenarios/models/reproductions/32963-model-question-display-lock.cy.spec.js
  frontend/src/metabase/query_builder/actions/core/initializeQB.ts
  frontend/src/metabase/query_builder/actions/core/initializeQB.unit.spec.ts
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#32248 Make mongo query's `:case` expression realize during compilation
  modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj
  test/metabase/api/dataset_test.clj
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#32766 Remove slfj4 dependencies from org.apache.sshd
  deps.edn
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#32742 Search Filter Milestone 1 - Type Filters for Search
  e2e/test/scenarios/embedding/embedding-full-app.cy.spec.js
  e2e/test/scenarios/onboarding/search/search.cy.spec.js
  e2e/test/scenarios/question/notebook.cy.spec.js
  frontend/src/metabase/components/LoadingSpinner/LoadingSpinner.tsx
  frontend/src/metabase/nav/components/SearchBar.styled.tsx
  frontend/src/metabase/nav/components/SearchBar.tsx
  frontend/src/metabase/nav/components/SearchBar.unit.spec.tsx
  frontend/src/metabase/nav/components/SearchResults.jsx
  frontend/src/metabase/nav/utils/model-names.ts
  frontend/src/metabase/query_builder/components/view/QuestionFilters.jsx
  frontend/src/metabase/search/components/InfoText.tsx
  frontend/src/metabase/search/components/SearchFilterModal/SearchFilterModal.styled.tsx
  frontend/src/metabase/search/components/SearchFilterModal/SearchFilterModal.tsx
  frontend/src/metabase/search/components/SearchFilterModal/SearchFilterModal.unit.spec.tsx
  frontend/src/metabase/search/components/SearchFilterModal/SearchFilterModalFooter.styled.tsx
  frontend/src/metabase/search/components/SearchFilterModal/SearchFilterModalFooter.tsx
  frontend/src/metabase/search/components/SearchFilterModal/filters/SearchFilterView.tsx
  frontend/src/metabase/search/components/SearchFilterModal/filters/SearchFilterView.unit.spec.tsx
  frontend/src/metabase/search/components/SearchFilterModal/filters/TypeFilter.styled.tsx
  frontend/src/metabase/search/components/SearchFilterModal/filters/TypeFilter.tsx
  frontend/src/metabase/search/components/SearchFilterModal/filters/TypeFilter.unit.spec.tsx
  frontend/src/metabase/search/components/SearchResult.tsx
  frontend/src/metabase/search/components/SearchResult.unit.spec.tsx
  frontend/src/metabase/search/components/TypeSearchSidebar/TypeSearchSidebar.styled.tsx
  frontend/src/metabase/search/components/TypeSearchSidebar/TypeSearchSidebar.tsx
  frontend/src/metabase/search/components/TypeSearchSidebar/TypeSearchSidebar.unit.spec.tsx
  frontend/src/metabase/search/components/TypeSearchSidebar/index.ts
  frontend/src/metabase/search/components/types.ts
  frontend/src/metabase/search/constants.ts
  frontend/src/metabase/search/containers/SearchApp.jsx
  frontend/src/metabase/search/containers/SearchApp.styled.tsx
  frontend/src/metabase/search/containers/SearchApp.unit.spec.tsx
  frontend/src/metabase/search/containers/constants.ts
  frontend/src/metabase/search/types.ts
  frontend/src/metabase/search/utils/index.ts
  frontend/src/metabase/search/utils/search-location/index.ts
  frontend/src/metabase/search/utils/search-location/search-location.ts
  frontend/src/metabase/search/utils/search-location/search-location.unit.spec.ts
  frontend/test/__support__/server-mocks/search.ts
Labels: .Team/42 :milky_way:, no-backport

#33051 Fix styling of ParametersWidgetContainer
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.styled.tsx
Labels: backport, .Team/42 :milky_way:

#32992 fix funnel shows card title in the chart viewport in QB
  frontend/src/metabase/visualizations/visualizations/Funnel.jsx
  frontend/src/metabase/visualizations/visualizations/Funnel.unit.spec.jsx
Labels: backport, visual, .Team/PixelPolice :police_officer:

#32993 Generate correct reference for broken out expressions
  src/metabase/lib/expression.cljc
  src/metabase/lib/field.cljc
  test/metabase/lib/order_by_test.cljc
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#32882 [MLv2] Support segments
  frontend/src/metabase-lib/segments.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase-lib/v2.ts
  src/metabase/lib/core.cljc
  src/metabase/lib/filter.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/js/metadata.cljs
  src/metabase/lib/metadata.cljc
  src/metabase/lib/metadata/protocols.cljc
  src/metabase/lib/schema.cljc
  src/metabase/lib/schema/ref.cljc
  src/metabase/lib/segment.cljc
  test/metabase/lib/convert_test.cljc
  test/metabase/lib/filter_test.cljc
  test/metabase/lib/schema/filter_test.cljc
  test/metabase/lib/segment_test.cljc
  test/metabase/lib/test_util.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33004 Add an e2e test to reproduce issue 28756
  e2e/test/scenarios/dashboard/reproductions/28756-toast-to-enable-notifications-when-no-permissions.cy.spec.js
Labels: backport, .Team/42 :milky_way:

#32904 MLv2 Joins 2 — Suggested condition
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/use-join.ts
Labels: .Team/QueryProcessor :hammer_and_wrench:

#33055 Group `NativeQueryEditor` files in a single directory
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.css
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.jsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.styled.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditorPrompt/NativeQueryEditorPrompt.styled.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditorPrompt/NativeQueryEditorPrompt.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditorPrompt/index.ts
  frontend/src/metabase/query_builder/components/NativeQueryEditor/VisibilityToggler/VisibilityToggler.unit.spec.js
  frontend/src/metabase/query_builder/components/NativeQueryEditor/__mocks__/NativeQueryEditor.jsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/__mocks__/index.ts
  frontend/src/metabase/query_builder/components/NativeQueryEditor/index.ts
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33003 Provide ability to use Is dashboard filter as a variable also for mongo
  modules/drivers/mongo/src/metabase/driver/mongo/parameters.clj
  modules/drivers/mongo/test/metabase/driver/mongo/parameters_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#32446 Modify `:contains`, `:starts-with` and `:ends-with` so field or expression can be used as the second argument
  modules/drivers/druid/src/metabase/driver/druid/query_processor.clj
  modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj
  modules/drivers/mongo/test/metabase/driver/mongo/parameters_test.clj
  modules/drivers/mongo/test/metabase/driver/mongo/query_processor_test.clj
  src/metabase/driver/sql/query_processor.clj
  test/metabase/query_processor_test/filter_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32797 Convert DefaultPicker to typescript
  frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopoverPicker.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DefaultPicker/DefaultPicker.styled.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DefaultPicker/DefaultPicker.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DefaultPicker/DefaultPicker.unit.spec.tsx
  frontend/src/metabase/query_builder/components/filters/pickers/DefaultPicker/index.ts
  frontend/src/metabase/query_builder/components/filters/pickers/NumberPicker.jsx
  frontend/src/metabase/query_builder/components/filters/pickers/SelectPicker.jsx
  frontend/src/metabase/query_builder/components/filters/pickers/TextPicker.jsx
Labels: Querying/Parameters & Variables, .Team/PixelPolice :police_officer:, no-backport

#33021 [MLv2] Expose field_id mlv2 function
  frontend/src/metabase-lib/fields.ts
Labels: .Team/PixelPolice :police_officer:, no-backport

#33025 Dont crash with bad fieldValues options
  e2e/test/scenarios/filters/filter-reproductions.cy.spec.js
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.tsx
Labels: backport, .Blocker, .Team/PixelPolice :police_officer:

#32987 Fix alias of joined column LHS of standard join conditions
  src/metabase/lib/join.cljc
  src/metabase/lib/remove_replace.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/remove_replace_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#33009 Fix misc errors in currency metadata
  shared/src/metabase/shared/util/currency.cljc
Labels: .Team/PixelPolice :police_officer:, no-backport

#33092 Wink for GCP users
  docs/databases/connections/postgresql.md
Labels: Type:Documentation, backport

#33024 Wrap long column names in chart settings sidebar
  e2e/test/scenarios/question/reproductions/32964-long-column-name-in-visualization-settings.cy.spec.js
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldPicker.styled.tsx
  frontend/src/metabase/visualizations/components/settings/ColumnItem.styled.tsx
Labels: backport, visual, .Team/PixelPolice :police_officer:

#33031 Test metadata helper function consolidation
  src/metabase/lib/core.cljc
  src/metabase/lib/query.cljc
  test/metabase/lib/card_test.cljc
  test/metabase/lib/column_group_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/filter_test.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/metadata/jvm_test.clj
  test/metabase/lib/metadata_test.cljc
  test/metabase/lib/native_test.cljc
  test/metabase/lib/query_test.cljc
  test/metabase/lib/test_metadata.cljc
  test/metabase/lib/test_util.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33081 Fix a question suffix created when deep copying a dashboard with question
  src/metabase/api/dashboard.clj
  test/metabase/api/dashboard_test.clj
Labels: backport

#32905 MLv2 Joins 3 — Fields
  frontend/src/metabase-lib/join.ts
  frontend/src/metabase/common/components/FieldPicker/FieldPicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/DataStep/DataStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTablePicker/JoinTablePicker.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTablePicker/JoinTablePicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/use-join.ts
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32906 MLv2 Joins 4 — Multiple conditions
  frontend/src/metabase-lib/join.ts
  frontend/src/metabase/common/components/QueryColumnPicker/QueryColumnPicker.tsx
  frontend/src/metabase/query_builder/components/notebook/NotebookCell/NotebookCell.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/NotebookCell/NotebookCell.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/use-join-condition.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/use-join.ts
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32907 MLv2 Joins 5 — Update condition UI
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionColumnPicker/JoinConditionColumnPicker.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionColumnPicker/JoinConditionColumnPicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionOperatorPicker/JoinConditionOperatorPicker.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionOperatorPicker/JoinConditionOperatorPicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/use-join-condition.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/use-join.ts
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32908 MLv2 Joins 6 — Read-only mode
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionColumnPicker/JoinConditionColumnPicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStrategyPicker/JoinStrategyPicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTablePicker/JoinTablePicker.tsx
Labels: .Team/QueryProcessor :hammer_and_wrench:

#32868 Reduce number of tests stored in memory
  e2e/support/config.js
Labels: .CI & Tests, backport

#33122 Fix dynamic message id in translations
  e2e/test/scenarios/question/reproductions/33079-drill-underlying-records.cy.spec.js
  frontend/src/metabase/modes/components/drill/UnderlyingRecordsDrill.ts
Labels: backport, .Team/42 :milky_way:

#33019 docs - h2 update
  docs/actions/introduction.md
  docs/databases/connecting.md
  docs/databases/connections/h2.md
  docs/questions/query-builder/expressions/converttimezone.md
Labels: Type:Documentation, backport

#33135 docs - h2 update
  docs/actions/introduction.md
  docs/databases/connecting.md
  docs/databases/connections/h2.md
  docs/questions/query-builder/expressions/converttimezone.md
Labels: Type:Documentation, no-backport

#33038 available_models should not take models into account
  src/metabase/api/search.clj
  src/metabase/search/filter.clj
  test/metabase/api/search_test.clj
  test/metabase/search/filter_test.clj
Labels: .Team/42 :milky_way:

#32288 Improve Filter <> DatePicker compatibility
  e2e/test/scenarios/filters/reproductions/12496-drill-through-filter-date.cy.spec.js
Labels: visual, .Team/PixelPolice :police_officer:, no-backport

#32778 Creating a collection when saving a question/dashboard should return to the question/dashboard save modal with the new collection selected
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/question/new.cy.spec.js
  frontend/src/metabase/collections/containers/FormCollectionPicker/FormCollectionPicker.styled.tsx
  frontend/src/metabase/collections/containers/FormCollectionPicker/FormCollectionPicker.tsx
  frontend/src/metabase/containers/CreateCollectionOnTheGo.tsx
  frontend/src/metabase/containers/SaveQuestionModal.tsx
  frontend/src/metabase/containers/SaveQuestionModal.unit.spec.tsx
  frontend/src/metabase/dashboard/containers/CreateDashboardForm.tsx
  frontend/src/metabase/dashboard/containers/CreateDashboardModal.tsx
  frontend/src/metabase/dashboard/containers/CreateDashboardModal.unit.spec.tsx
Labels: backport, .Team/PixelPolice :police_officer:

#33034 Fix dashboard actions linked with filters don't work
  e2e/test/scenarios/actions/reproductions/32974-linked-parameter-via-url-does-not-work.cy.spec.js
  frontend/src/metabase/actions/components/ActionViz/ActionVizForm.tsx
Labels: .CI & Tests, support/Repro, backport, .Team/42 :milky_way:

#32982 Remove unsafe-eval from script-src
  package.json
  src/metabase/server/middleware/security.clj
  yarn.lock
Labels: .Team/42 :milky_way:, no-backport

#33133 Fix crash in admin settings in a non-default locale
  e2e/test/scenarios/admin/databases/reproductions/33035-group-translations.cy.spec.js
  frontend/src/metabase/admin/permissions/selectors/data-permissions/group-sidebar.ts
  frontend/src/metabase/admin/permissions/selectors/data-permissions/groups.ts
Labels: backport, .Team/42 :milky_way:

#33087 Fix - Can't subsequently run actions for different objects from dashboards
  e2e/test/scenarios/actions/actions-on-dashboards.cy.spec.js
  frontend/src/metabase/actions/hooks/use-action-initial-values.ts
Labels: .Team/42 :milky_way:, no-backport

#33076 Show new syncing tables as greyed out in data reference pane
  frontend/src/metabase/entities/tables.js
  frontend/src/metabase/query_builder/components/dataref/DatabaseTablesPane.tsx
  frontend/src/metabase/query_builder/components/dataref/DatabaseTablesPane.unit.spec.tsx
  frontend/src/metabase/query_builder/components/dataref/NodeList.styled.tsx
Labels: backport, .Team/42 :milky_way:

#33089 Search by table description
  e2e/test/scenarios/onboarding/search/search.cy.spec.js
  src/metabase/search/config.clj
  test/metabase/api/search_test.clj
Labels: .Team/42 :milky_way:, no-backport

#33154 Fix flaky reproduction for 15891
  e2e/test/scenarios/custom-column/cc-help-text.cy.spec.js
Labels: .CI & Tests, backport, flaky-test-fix

#33119 User friendly error message when combining series that cannot be visualized together
  e2e/test/scenarios/dashboard-cards/reproductions/32231-add-incompatible-series.cy.spec.js
  frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx
  frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.jsx
  frontend/src/metabase/visualizations/components/Visualization/ErrorView/ErrorView.tsx
  frontend/src/metabase/visualizations/components/Visualization/ErrorView/index.ts
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
Labels: backport, visual, .Team/42 :milky_way:

#33066 Add column rename via popover test
  e2e/test/scenarios/visualizations/table-column-settings.cy.spec.js
Labels: .CI & Tests, backport, .Team/PixelPolice :police_officer:

#33059 Extract styled components from `NativeQueryEditor`
  e2e/support/helpers/e2e-misc-helpers.js
  e2e/test/scenarios/models/models.cy.spec.js
  e2e/test/scenarios/models/reproductions/22517-add-remove-column-drops-metadata.cy.spec.js
  e2e/test/scenarios/native-filters/helpers/e2e-sql-filter-helpers.js
  e2e/test/scenarios/native-filters/reproductions/14145.cy.spec.js
  e2e/test/scenarios/native/native-mongo.cy.spec.js
  e2e/test/scenarios/native/native-mysql.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
  e2e/test/scenarios/native/reproductions/16886.cy.spec.js
  e2e/test/scenarios/native/reproductions/21597-query-build-card-save-modal.cy.spec.js
  e2e/test/scenarios/native/reproductions/32121-sql-source-query-can-explore-results.cy.spec.js
  e2e/test/scenarios/native/snippets/snippets.cy.spec.js
  e2e/test/scenarios/question/reproductions/9027-new-questions-not-in-saved-questions-immediately.cy.spec.js
  e2e/test/scenarios/visualizations/maps.cy.spec.js
  e2e/test/scenarios/visualizations/table.cy.spec.js
  e2e/test/scenarios/visualizations/waterfall.cy.spec.js
  frontend/src/metabase/css/query_builder.css
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.css
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.jsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.styled.tsx
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33164 Revert "Remove unsafe-eval from script-src"
  package.json
  src/metabase/server/middleware/security.clj
  yarn.lock
Labels: .Team/42 :milky_way:, no-backport

#33100 Fix redirect URI validation for relative paths
  enterprise/backend/src/metabase_enterprise/sso/integrations/sso_utils.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/sso_utils_test.clj
Labels: backport, .Team/PixelPolice :police_officer:

#33102 Migrate `NativeQueryEditor` to TypeScript
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditorPrompt/NativeQueryEditorPrompt.tsx
  frontend/src/types/ace-builds.d.ts
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33136 docs - remove user flag
  docs/installation-and-operation/serialization.md
Labels: Type:Documentation, backport

#33056 fix `ChartSettingInputNumeric` not accepting decimals on safari
  frontend/src/metabase/visualizations/components/settings/ChartSettingInputNumeric.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingInputNumeric.unit.spec.tsx
  frontend/src/metabase/visualizations/lib/settings.js
Labels: backport, visual, .Team/PixelPolice :police_officer:

#33099 Make changes to Checkbox based on Text component changes
  frontend/src/metabase/ui/components/inputs/Checkbox/Checkbox.stories.mdx
  frontend/src/metabase/ui/theme.ts
Labels: .Team/42 :milky_way:, no-backport

#32966 Improved `mu/defn` error messages
  shared/src/metabase/mbql/schema.cljc
  shared/test/metabase/mbql/schema_test.cljc
  src/metabase/util/malli/fn.clj
  src/metabase/util/malli/humanize.cljc
  test/metabase/lib/schema/join_test.cljc
  test/metabase/util/malli/humanize_test.cljc
  test/metabase/util/malli/registry_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33094 Manual backport of #32993
  src/metabase/lib/expression.cljc
  src/metabase/lib/field.cljc
  test/metabase/lib/order_by_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#33145 fixes x-ray loading order
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/dashboard/x-rays.cy.spec.js
  frontend/src/metabase/dashboard/components/grid/utils.js
  frontend/src/metabase/dashboard/components/grid/utils.unit.spec.js
  frontend/src/metabase/dashboard/selectors.unit.spec.js
  frontend/src/metabase/dashboard/selectors/selectors.js
Labels: backport, .Team/PixelPolice :police_officer:

#33103 Fix alias of LHS from join
  src/metabase/lib/join.cljc
  src/metabase/lib/remove_replace.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/remove_replace_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33090 🍒 Manual Backport 33025
  e2e/test/scenarios/filters/filter-reproductions.cy.spec.js
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.jsx
Labels: was-backported, .Blocker, .Team/PixelPolice :police_officer:

#33188 Remove unsafe-eval from script-src
  e2e/test/scenarios/visualizations/line_chart.cy.spec.js
  frontend/src/metabase/visualizations/lib/trends.js
  package.json
  src/metabase/server/middleware/security.clj
  yarn.lock
Labels: visual, .Team/42 :milky_way:, no-backport

#33159 Add docs about running tests with snowplow
  docs/developers-guide/e2e-tests.md
Labels: no-backport

#33160 Manual backport - User friendly error message when combining series that cannot be visualized together
  e2e/test/scenarios/dashboard/reproductions/32231-add-incompatible-series.cy.spec.js
  frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx
  frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.jsx
  frontend/src/metabase/visualizations/components/Visualization/ErrorView/ErrorView.tsx
  frontend/src/metabase/visualizations/components/Visualization/ErrorView/index.ts
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
Labels: was-backported, visual

#33191 Add emotion.d.ts
  frontend/src/metabase/search/components/SearchFilterModal/SearchFilterModal.styled.tsx
  frontend/src/types/emotion.d.ts
Labels: .Team/42 :milky_way:, no-backport

#33097 Mantine menu
  frontend/src/metabase/ui/components/buttons/Button/index.ts
  frontend/src/metabase/ui/components/buttons/index.ts
  frontend/src/metabase/ui/components/data-display/Accordion/Accordion.styled.tsx
  frontend/src/metabase/ui/components/data-display/Accordion/index.ts
  frontend/src/metabase/ui/components/index.ts
  frontend/src/metabase/ui/components/inputs/Checkbox/Checkbox.styled.tsx
  frontend/src/metabase/ui/components/inputs/Checkbox/index.ts
  frontend/src/metabase/ui/components/inputs/Radio/Radio.styled.tsx
  frontend/src/metabase/ui/components/inputs/Radio/index.ts
  frontend/src/metabase/ui/components/overlays/Menu/Menu.stories.mdx
  frontend/src/metabase/ui/components/overlays/Menu/Menu.styled.tsx
  frontend/src/metabase/ui/components/overlays/Menu/index.ts
  frontend/src/metabase/ui/components/overlays/index.ts
  frontend/src/metabase/ui/components/theme/ThemeProvider/ThemeProvider.tsx
  frontend/src/metabase/ui/components/typography/Anchor/Anchor.stories.mdx
  frontend/src/metabase/ui/components/typography/Anchor/Anchor.styled.tsx
  frontend/src/metabase/ui/components/typography/Anchor/index.ts
  frontend/src/metabase/ui/components/typography/Text/Text.styled.tsx
  frontend/src/metabase/ui/components/typography/Text/index.ts
  frontend/src/metabase/ui/theme.ts
Labels: .Team/42 :milky_way:, no-backport

#33073 Consolidate dashboard specs
  e2e/support/helpers/e2e-dashboard-helpers.js
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/dashboard-cards/visualization-options.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-auto-apply.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard-management.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/dashboard/duplicate.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/25705-undo-moving-dashboards.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/26826-dashboard-alien-card.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/31848-new-question-dashboard.cy.spec.js
  e2e/test/scenarios/onboarding/home/homepage.cy.spec.js
Labels: .CI & Tests, backport
