Repository metabase/metabase, pull requests merged in 2023-09, with the labels that each got.

#33415 Create a privilege table and update it on sync for postgres
  docs/developers-guide/driver-changelog.md
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  resources/migrations/000_migrations.yaml
  src/metabase/driver.clj
  src/metabase/driver/postgres.clj
  src/metabase/models.clj
  src/metabase/models/table_privileges.clj
  src/metabase/sync/sync_metadata.clj
  src/metabase/sync/sync_metadata/sync_table_privileges.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/sync/sync_metadata/sync_table_privileges_test.clj
Labels: .Team/42 :milky_way:, no-backport

#33572 Move drill thrus to their own namespaces & numerous bug fixes
  src/metabase/lib/core.cljc
  src/metabase/lib/drill_thru.cljc
  src/metabase/lib/drill_thru/automatic_insights.cljc
  src/metabase/lib/drill_thru/column_filter.cljc
  src/metabase/lib/drill_thru/common.cljc
  src/metabase/lib/drill_thru/distribution.cljc
  src/metabase/lib/drill_thru/foreign_key.cljc
  src/metabase/lib/drill_thru/object_details.cljc
  src/metabase/lib/drill_thru/pivot.cljc
  src/metabase/lib/drill_thru/progression.cljc
  src/metabase/lib/drill_thru/quick_filter.cljc
  src/metabase/lib/drill_thru/sort.cljc
  src/metabase/lib/drill_thru/summarize_column.cljc
  src/metabase/lib/drill_thru/summarize_column_by_time.cljc
  src/metabase/lib/drill_thru/underlying_records.cljc
  src/metabase/lib/drill_thru/zoom_in_timeseries.cljc
  src/metabase/lib/schema/drill_thru.cljc
  src/metabase/util/malli.cljc
  src/metabase/util/malli/fn.clj
  test/metabase/lib/drill_thru/sort_test.cljc
  test/metabase/lib/drill_thru/underlying_records_test.cljc
  test/metabase/lib/drill_thru_test.cljc
  test/metabase/util/malli_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33648 Use field ID as name if the field cannot be resolved
  src/metabase/lib/field.cljc
  test/metabase/lib/metadata/calculation_test.cljc
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#33677 Adding Snowflake to the list of DB's
  docs/questions/native-editor/referencing-saved-questions-in-queries.md
Labels: Type:Documentation, backport

#33067 docs - deprecate beanstalk
  docs/configuring-metabase/customizing-jetty-webserver.md
  docs/installation-and-operation/advanced-topics-for-running-Metabase-in-AWS-ElasticBeanstalk.md
  docs/installation-and-operation/creating-RDS-database-on-AWS.md
  docs/installation-and-operation/installing-metabase.md
  docs/installation-and-operation/migrating-from-h2.md
  docs/installation-and-operation/running-metabase-on-elastic-beanstalk.md
  docs/installation-and-operation/start.md
  docs/installation-and-operation/upgrading-metabase.md
  docs/troubleshooting-guide/bugs.md
  docs/troubleshooting-guide/docker.md
  docs/troubleshooting-guide/timeout.md
Labels: Type:Documentation, backport

#33630 48 cycle simple bumps
  bin/build/resources/overrides.edn
  deps.edn
  e2e/test/scenarios/embedding/embedding-smoketests.cy.spec.js
  modules/drivers/athena/deps.edn
  modules/drivers/bigquery-cloud-sdk/deps.edn
  modules/drivers/googleanalytics/deps.edn
  modules/drivers/presto-jdbc/deps.edn
  modules/drivers/redshift/deps.edn
  modules/drivers/snowflake/deps.edn
  modules/drivers/sqlite/deps.edn
  modules/drivers/sqlserver/deps.edn
  modules/drivers/vertica/deps.edn
  src/metabase/query_processor/middleware/cache/impl.clj
  test/metabase/api/common/internal_test.clj
  test/metabase/api/embed_test.clj
  test/metabase/api/geojson_test.clj
  test/metabase/api/preview_embed_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33673 What's new - adds white labeling check to logic
  frontend/src/metabase/nav/components/WhatsNewNotification/WhatsNewNotification.tsx
  frontend/src/metabase/nav/components/WhatsNewNotification/utils.ts
  frontend/src/metabase/nav/components/WhatsNewNotification/utils.unit.spec.ts
Labels: .Team/42 :milky_way:

#33674 Add Right Arrow Icon
  frontend/src/metabase/core/components/Icon/icons/index.ts
Labels: .Team/42 :milky_way:, no-backport

#33526 MLv2 Joins 9 — Remove `externalOp` usage
  frontend/src/metabase-lib/common.ts
  frontend/src/metabase-lib/join.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/use-join-condition.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/use-join.ts
Labels: .Team/QueryProcessor :hammer_and_wrench:

#33217 Modify GET /api/user endpoint to only work for admins/group managers
  e2e/test/scenarios/organization/content-verification.cy.spec.js
  e2e/test/scenarios/sharing/pulse.cy.spec.js
  enterprise/backend/test/metabase_enterprise/sandbox/api/user_test.clj
  frontend/src/metabase/pulse/containers/PulseEditApp.jsx
  src/metabase/api/user.clj
  test/metabase/api/user_test.clj
Labels: backport, .Team/PixelPolice :police_officer:

#33694 Refactor - Break ObjectDetail down
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailBody.styled.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailBody.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailBody.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailHeader.styled.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailHeader.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailHeader.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.styled.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailWrapper.styled.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailWrapper.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailsTable.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectRelationships.tsx
Labels: backport, visual, .Team/42 :milky_way:

#33433 Remove external op on the FE
  frontend/src/metabase-lib/common.ts
  frontend/src/metabase-lib/filter.ts
  frontend/src/metabase-lib/join.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase-lib/v2.ts
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33190 Download previously saved uberjar for E2E workflow
  .github/file-paths.yaml
  .github/workflows/e2e-tests.yml
Labels: .CI & Tests, backport

#33723 Nit: Remove the redundant assertion from `common_test.clj`
  bin/build/test/release/common_test.clj
Labels: .CI & Tests, backport

#33574 Implement timeseries zoom drill thru
  src/metabase/lib/drill_thru.cljc
  src/metabase/lib/drill_thru/common.cljc
  src/metabase/lib/drill_thru/zoom_in_timeseries.cljc
  src/metabase/lib/schema/drill_thru.cljc
  src/metabase/lib/temporal_bucket.cljc
  test/metabase/lib/drill_thru/zoom_in_timeseries_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33570 Parameterize collection and dashboard ids in e2e tests
  e2e/support/cypress_sample_instance_data.js
  e2e/test/scenarios/actions/reproductions/31587-bottom-corner-radius-action-buttons.cy.spec.js
  e2e/test/scenarios/admin-2/auditing/approved-domains.cy.spec.js
  e2e/test/scenarios/admin/databases/database-prompt-banner.cy.spec.js
  e2e/test/scenarios/collections/archive.cy.spec.js
  e2e/test/scenarios/collections/collection-pinned-overview.cy.spec.js
  e2e/test/scenarios/collections/collections.cy.spec.js
  e2e/test/scenarios/collections/personal-collections.cy.spec.js
  e2e/test/scenarios/collections/reproductions/20911-include-subcollections-permissions.cy.spec.js
  e2e/test/scenarios/collections/revision-history.cy.spec.js
  e2e/test/scenarios/dashboard-cards/dashboard-drill.cy.spec.js
  e2e/test/scenarios/dashboard-cards/visualization-options.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-chained-filters.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filter-data-permissions.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-date.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-id.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-location.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-number.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-text-category.cy.spec.js
  e2e/test/scenarios/dashboard-filters/parameters.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/12720-no-data-permissions-connected-filter.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/19494-wrong-default-value-multiple-cards-same-question.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/22482-round-relative-ranges.cy.spec.js
  e2e/test/scenarios/dashboard/caching.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard-back-navigation.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard-management.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/21830-slow-loading-card-viz-options-error.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/29076-dashboard-card-drill-sandbox.cy.spec.js
  e2e/test/scenarios/dashboard/tabs.cy.spec.js
  e2e/test/scenarios/dashboard/text-dashcards.cy.spec.js
  e2e/test/scenarios/embedding/embedding-full-app.cy.spec.js
  e2e/test/scenarios/embedding/embedding-smoketests.cy.spec.js
  e2e/test/scenarios/embedding/embedding-snippets.cy.spec.js
  e2e/test/scenarios/filters/view.cy.spec.js
  e2e/test/scenarios/models/create.cy.spec.js
  e2e/test/scenarios/models/reproductions/29517-native-remapped-model-drill-through-click-behavior.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
  e2e/test/scenarios/onboarding/home/homepage.cy.spec.js
  e2e/test/scenarios/onboarding/search/recently-viewed.cy.spec.js
  e2e/test/scenarios/onboarding/urls.cy.spec.js
  e2e/test/scenarios/organization/bookmarks-collection.cy.spec.js
  e2e/test/scenarios/organization/bookmarks-dashboard.cy.spec.js
  e2e/test/scenarios/organization/edit-history-metadata.cy.spec.js
  e2e/test/scenarios/permissions/admin-permissions.cy.spec.js
  e2e/test/scenarios/permissions/application-permissions.cy.spec.js
  e2e/test/scenarios/permissions/permissions-baseline.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/22473-cannot-unsubscribe-from-notifications-without-collection-perms.cy.spec.js
  e2e/test/scenarios/permissions/sandboxes.cy.spec.js
  e2e/test/scenarios/question/new.cy.spec.js
  e2e/test/scenarios/question/question-management.cy.spec.js
  e2e/test/scenarios/question/saved.cy.spec.js
  e2e/test/scenarios/sharing/approved-domains.cy.spec.js
  e2e/test/scenarios/sharing/downloads/downloads.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/17657.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/17658.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/18009-nodata-creates-subscription-receives-error.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/18344-subscription-shows-original-question-name.cy.spec.js
  e2e/test/scenarios/sharing/subscriptions.cy.spec.js
Labels: .CI & Tests, .Team/PixelPolice :police_officer:, no-backport

#33665 Move MLv2 metadata schemas into a `metabase.lib.schema` namespace
  src/metabase/lib/metadata.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/schema/metadata.cljc
  src/metabase/models/persisted_info.clj
  src/metabase/query_processor/util/persisted_cache.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#32070 `mt/user-http-request` to call the app handler directly
  enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/saml_test.clj
  src/metabase/api/dashboard.clj
  src/metabase/async/streaming_response.clj
  src/metabase/query_processor/streaming/interface.clj
  src/metabase/util/malli/schema.clj
  test/metabase/api/alert_test.clj
  test/metabase/api/card_test.clj
  test/metabase/api/collection_test.clj
  test/metabase/api/common/internal_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/database_test.clj
  test/metabase/api/dataset_test.clj
  test/metabase/api/embed_test.clj
  test/metabase/api/geojson_test.clj
  test/metabase/api/notify_test.clj
  test/metabase/api/permissions_test.clj
  test/metabase/api/preview_embed_test.clj
  test/metabase/api/public_test.clj
  test/metabase/api/pulse_test.clj
  test/metabase/api/session_test.clj
  test/metabase/api/setup_test.clj
  test/metabase/api/transform_test.clj
  test/metabase/http_client.clj
  test/metabase/http_client_test.clj
  test/metabase/query_processor/streaming/test_util.clj
  test/metabase/test.clj
  test/metabase/test/data/users.clj
Labels: .Team/42 :milky_way:, no-backport

#33505 Mantine Select
  frontend/src/metabase/ui/components/inputs/Checkbox/Checkbox.styled.tsx
  frontend/src/metabase/ui/components/inputs/Input/Input.styled.tsx
  frontend/src/metabase/ui/components/inputs/NumberInput/NumberInput.stories.mdx
  frontend/src/metabase/ui/components/inputs/Select/Select.stories.mdx
  frontend/src/metabase/ui/components/inputs/Select/Select.styled.tsx
  frontend/src/metabase/ui/components/inputs/Select/SelectItem.tsx
  frontend/src/metabase/ui/components/inputs/Select/index.ts
  frontend/src/metabase/ui/components/inputs/TextInput/TextInput.stories.mdx
  frontend/src/metabase/ui/components/inputs/index.ts
  frontend/src/metabase/ui/components/overlays/Menu/Menu.styled.tsx
  frontend/src/metabase/ui/theme.ts
Labels: .Team/42 :milky_way:, no-backport, chromatic

#33717 Manual backport - Refactor - Break ObjectDetail down
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.styled.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailBody.styled.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailBody.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailBody.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailHeader.styled.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailHeader.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailHeader.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.styled.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailWrapper.styled.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailWrapper.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailWrapper.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailsTable.styled.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailsTable.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectRelationships.styled.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectRelationships.tsx
Labels: was-backported, visual

#33710 Fix redundant network requests triggered in object detail modal
  e2e/test/scenarios/visualizations/object_detail.cy.spec.js
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.styled.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailWrapper.styled.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailsTable.styled.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailsTable.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectRelationships.styled.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectRelationships.tsx
Labels: backport, visual, .Team/42 :milky_way:

#33724 Manual backport of #33703 to 47
  enterprise/backend/src/metabase_enterprise/sso/integrations/sso_utils.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/sso_utils_test.clj
Labels: .Team/PixelPolice :police_officer:

#33745 Fix `download-uberjar` job logic
  .github/workflows/e2e-tests.yml
Labels: .CI & Tests, no-backport

#33746 🍒 Backport "Download previously saved uberjar for E2E workflow
  .github/file-paths.yaml
  .github/workflows/e2e-tests.yml
Labels: was-backported

#33720 Mantine button color
  frontend/src/metabase/ui/components/buttons/Button/Button.stories.mdx
  frontend/src/metabase/ui/components/buttons/Button/Button.styled.tsx
  frontend/src/metabase/ui/theme.ts
Labels: .Team/42 :milky_way:, no-backport

#33747 Fix unresolved var `lib.join/current-join-alias`
  src/metabase/lib/drill_thru/zoom_in_timeseries.cljc
Labels: no-backport

#33604 Switch pulse email sending to use bcc instead of sending a seperate email
  enterprise/backend/test/metabase_enterprise/sandbox/pulse_test.clj
  src/metabase/email.clj
  src/metabase/email/messages.clj
  src/metabase/pulse.clj
  test/metabase/api/pulse_test.clj
  test/metabase/dashboard_subscription_test.clj
  test/metabase/email_test.clj
  test/metabase/pulse_test.clj
  test/metabase/task/send_pulses_test.clj
Labels: backport, .Team/PixelPolice :police_officer:

#33124 [POC] Faster E2E tests in CI
  .github/workflows/e2e-tests.yml
  e2e/test/scenarios/dashboard-filters/dashboard-filters-auto-apply.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-source.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard-back-navigation.cy.spec.js
  e2e/test/scenarios/dashboard/x-rays.cy.spec.js
  e2e/test/scenarios/question/notebook.cy.spec.js
  e2e/test/scenarios/question/question-management.cy.spec.js
  e2e/test/scenarios/visualizations/object_detail.cy.spec.js
  e2e/test/scenarios/visualizations/pivot_tables.cy.spec.js
Labels: .CI & Tests, backport

#33743 Manual backport - Fix redundant network requests triggered in object detail modal
  e2e/test/scenarios/visualizations/object_detail.cy.spec.js
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.tsx
Labels: was-backported, visual

#33704 Add e2e test for issue 20049
  e2e/test/scenarios/dashboard-filters/reproductions/20049-change-question-parameter-type-affects-dashboard-filter.cy.spec.js
Labels: .CI & Tests, support/Repro, .Team/42 :milky_way:

#33761 Improve notebook editor performance
  deps.edn
  shared/src/metabase/mbql/util.cljc
  src/metabase/lib/equality.cljc
  src/metabase/util.cljc
  src/metabase/util/memoize.clj
  src/metabase/util/memoize.cljs
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#33656 Indexed Entity X-Rays
  .clj-kondo/config.edn
  .clj-kondo/hooks/metabase/api/automagic_dashboards_test.clj
  frontend/src/metabase-types/api/mocks/search.ts
  frontend/src/metabase-types/api/search.ts
  frontend/src/metabase/dashboard/containers/AutomaticDashboardApp.jsx
  frontend/src/metabase/dashboard/hoc/DashboardData.jsx
  frontend/src/metabase/search/components/SearchResult.styled.tsx
  frontend/src/metabase/search/components/SearchResult.tsx
  shared/src/metabase/mbql/normalize.cljc
  src/metabase/api/automagic_dashboards.clj
  src/metabase/api/model_index.clj
  src/metabase/api/search.clj
  src/metabase/automagic_dashboards/core.clj
  src/metabase/automagic_dashboards/filters.clj
  src/metabase/automagic_dashboards/populate.clj
  src/metabase/models/dashboard.clj
  src/metabase/models/interface.clj
  src/metabase/models/model_index.clj
  src/metabase/search/config.clj
  test/metabase/api/automagic_dashboards_test.clj
  test/metabase/api/search_test.clj
  test/metabase/automagic_dashboards/core_test.clj
  test/metabase/models/model_index_test.clj
Labels: no-backport

#33764 Fix failing Vertica test
  modules/drivers/vertica/test/metabase/driver/vertica_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33775 🍒 Consolidate E2E `dashboard` specs (#33073)
  e2e/support/helpers/e2e-dashboard-helpers.js
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/dashboard-cards/visualization-options.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-auto-apply.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard-management.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/dashboard/duplicate.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/25705-undo-moving-dashboards.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/26826-dashboard-alien-card.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/31848-new-question-dashboard.cy.spec.js
  e2e/test/scenarios/onboarding/home/homepage.cy.spec.js
Labels: was-backported

#33762 Don't delete a connection impersonation policy when non-data perms are updated
  enterprise/backend/src/metabase_enterprise/advanced_permissions/models/connection_impersonation.clj
  enterprise/backend/src/metabase_enterprise/sandbox/models/permissions/delete_sandboxes.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/api/impersonation_test.clj
Labels: backport, .Team/PixelPolice :police_officer:

#33777 Fix e2e skipped tests naming
  .github/workflows/e2e-tests.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#33768 Manual backport #33761
  deps.edn
  shared/src/metabase/mbql/util.cljc
  src/metabase/lib/equality.cljc
  src/metabase/util.cljc
  src/metabase/util/memoize.clj
  src/metabase/util/memoize.cljs
Labels: was-backported, .Blocker, .Team/QueryProcessor :hammer_and_wrench:

#33671 Fix compareversions
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/lib/utils.js
  frontend/src/metabase/lib/utils.unit.spec.ts
  frontend/src/metabase/nav/components/WhatsNewNotification/utils.ts
  frontend/src/metabase/nav/components/WhatsNewNotification/utils.unit.spec.ts
  frontend/test/metabase/lib/utils.unit.spec.js
Labels: .Team/42 :milky_way:

#33639 Add Type Filter to Search
  e2e/test/scenarios/onboarding/search/search.cy.spec.js
  frontend/src/metabase-types/api/search.ts
  frontend/src/metabase/components/FieldSet/FieldSet.jsx
  frontend/src/metabase/search/components/SearchFilterSidebar/SearchFilterSidebar.styled.tsx
  frontend/src/metabase/search/components/SearchFilterSidebar/SearchFilterSidebar.tsx
  frontend/src/metabase/search/components/SearchFilterSidebar/SearchFilterSidebar.unit.spec.tsx
  frontend/src/metabase/search/components/SearchFilterSidebar/filters/SearchFilterView.tsx
  frontend/src/metabase/search/components/SearchFilterSidebar/filters/SearchFilterView.unit.spec.tsx
  frontend/src/metabase/search/components/SearchFilterSidebar/filters/TypeFilter.styled.tsx
  frontend/src/metabase/search/components/SearchFilterSidebar/filters/TypeFilter.tsx
  frontend/src/metabase/search/components/SearchSidebar/SearchSidebar.tsx
  frontend/src/metabase/search/components/SearchSidebar/tests/common.unit.spec.tsx
  frontend/src/metabase/search/components/SearchSidebar/tests/setup.tsx
  frontend/src/metabase/search/components/SidebarFilter/SidebarFilter.styled.tsx
  frontend/src/metabase/search/components/SidebarFilter/SidebarFilter.tsx
  frontend/src/metabase/search/components/SidebarFilter/SidebarFilter.unit.spec.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilter.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterContent.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterContent.unit.spec.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterDisplay.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterDisplay.unit.spec.tsx
  frontend/src/metabase/search/constants.ts
  frontend/src/metabase/search/containers/SearchApp.jsx
  frontend/src/metabase/search/containers/SearchApp.styled.tsx
  frontend/src/metabase/search/containers/SearchApp.unit.spec.tsx
  frontend/src/metabase/search/types.ts
Labels: .Team/42 :milky_way:

#33785 Remove unused "No changes to permissions will be made." confirmation in PermissionsEditBar
  frontend/src/metabase/admin/permissions/components/PermissionsPageLayout/PermissionsEditBar.jsx
Labels: backport, .Team/42 :milky_way:

#33781 🍒 Backport faster E2E tests in CI
  .github/workflows/e2e-tests.yml
  e2e/test/scenarios/dashboard-filters/dashboard-filters-auto-apply.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-source.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard-back-navigation.cy.spec.js
  e2e/test/scenarios/dashboard/x-rays.cy.spec.js
  e2e/test/scenarios/question/notebook.cy.spec.js
  e2e/test/scenarios/question/question-management.cy.spec.js
  e2e/test/scenarios/visualizations/object_detail.cy.spec.js
  e2e/test/scenarios/visualizations/pivot_tables.cy.spec.js
Labels: .CI & Tests, was-backported

#33787 Fix test that's breaking pre-release workflow
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#33632 Fix fetching field values for remapped fields
  e2e/test/scenarios/dashboard-filters/reproductions/21528-dashboard-id-filter-map-to-a-wrong-field.cy.spec.js
  frontend/src/metabase-lib/parameters/utils/targets.ts
  frontend/src/metabase-lib/parameters/utils/targets.unit.spec.ts
  frontend/src/metabase/parameters/utils/dashboards.ts
  src/metabase/models/params/chain_filter.clj
  test/metabase/models/params/chain_filter_test.clj
Labels: backport, visual, .Team/42 :milky_way:

#33789 Update copy in the custom leave confirmation modal
  e2e/test/scenarios/permissions/admin-permissions.cy.spec.js
  e2e/test/scenarios/permissions/impersonated.cy.spec.js
  frontend/src/metabase/admin/permissions/hooks/use-leave-confirmation.jsx
Labels: .Team/42 :milky_way:, no-backport

#33697 Fix object detail crashing when a table from foreign key is hidden
  frontend/src/metabase-types/api/mocks/table.ts
  frontend/src/metabase-types/api/table.ts
  frontend/src/metabase/query_builder/selectors.js
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.unit.spec.tsx
  frontend/test/__support__/server-mocks/table.ts
  frontend/test/__support__/testDataset.ts
Labels: backport, visual, .Team/42 :milky_way:

#33660 Manual backport of #33620
  e2e/test/scenarios/visualizations/line-bar-tooltips.cy.spec.js
  e2e/test/scenarios/visualizations/reproductions/21452-xhr-on-every-char-for-rename.cy.spec.js
  src/metabase/query_processor/middleware/annotate.clj
  src/metabase/query_processor/middleware/cumulative_aggregations.clj
  test/metabase/query_processor/middleware/cumulative_aggregations_test.clj
  test/metabase/query_processor_test/aggregation_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:

#33804 Fix e2e skipped test naming 2
  .github/workflows/e2e-tests.yml
Labels: Type:Tech Debt, .CI & Tests, backport

#33712 Convert SearchResults.jsx to typescript
  frontend/src/metabase-types/api/collection.ts
  frontend/src/metabase/core/components/AutocompleteInput/AutocompleteInput.tsx
  frontend/src/metabase/hooks/use-list-keyboard-navigation/use-list-keyboard-navigation.ts
  frontend/src/metabase/nav/components/SearchBar.tsx
  frontend/src/metabase/nav/components/SearchResults.jsx
  frontend/src/metabase/nav/components/SearchResults.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx
Labels: visual, .Team/42 :milky_way:, no-backport

#33678 Manual backport of #33648
  src/metabase/lib/field.cljc
  test/metabase/lib/metadata/calculation_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:

#33638 disable "download results" and "edit question" from xray dashcards that have not been saved
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/dashboard/components/DashCard/Dashcard.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.jsx
  frontend/src/metabase/dashboard/containers/AutomaticDashboardApp.jsx
Labels: backport, .Team/42 :milky_way:

#33623 [MLv2] Column metadata to legacy-field-ref
  src/metabase/lib/js.cljs
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33799 Add a reminder note to pick either backport or no-backport label
  .github/PULL_REQUEST_TEMPLATE.md
Labels: no-backport

#33737 Fix broken drill thrus/make sure all drill thrus produce valid queries after application
  src/metabase/lib/binning.cljc
  src/metabase/lib/drill_thru.cljc
  src/metabase/lib/drill_thru/column_filter.cljc
  src/metabase/lib/drill_thru/distribution.cljc
  src/metabase/lib/drill_thru/fk_details.cljc
  src/metabase/lib/drill_thru/object_details.cljc
  src/metabase/lib/drill_thru/pk.cljc
  src/metabase/lib/drill_thru/quick_filter.cljc
  src/metabase/lib/drill_thru/summarize_column.cljc
  src/metabase/lib/drill_thru/summarize_column_by_time.cljc
  src/metabase/lib/drill_thru/zoom.cljc
  src/metabase/lib/equality.cljc
  src/metabase/lib/filter.cljc
  src/metabase/lib/schema.cljc
  src/metabase/lib/schema/drill_thru.cljc
  src/metabase/lib/schema/util.cljc
  src/metabase/lib/temporal_bucket.cljc
  test/metabase/lib/drill_thru_test.cljc
  test/metabase/lib/filter_test.cljc
  test/metabase/lib/schema/util_test.cljc
  test/metabase/lib/schema_test.cljc
  test/metabase/lib/temporal_bucket_test.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33758 Happy little entity ID parameterizations
  e2e/snapshot-creators/default.cy.snap.js
  e2e/support/commands/api/composite/createNativeQuestionAndDashboard.js
  e2e/support/cypress_sample_instance_data.js
  e2e/support/helpers/e2e-qa-databases-helpers.js
  e2e/test/scenarios/admin-2/auditing/auditing.cy.spec.js
  e2e/test/scenarios/admin-2/people/people.cy.spec.js
  e2e/test/scenarios/admin/databases/database-exceptions.cy.spec.js
  e2e/test/scenarios/admin/datamodel/reproductions.cy.spec.js
  e2e/test/scenarios/collections/collection-pinned-overview.cy.spec.js
  e2e/test/scenarios/collections/personal-collections.cy.spec.js
  e2e/test/scenarios/collections/reproductions/23515-pinned-question-pagination.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/27745-cc-numeric-missing-summarize.cy.spec.js
  e2e/test/scenarios/dashboard/tabs.cy.spec.js
  e2e/test/scenarios/models/models-revision-history.cy.spec.js
  e2e/test/scenarios/models/reproductions/20042-nodata-user-blank-screen.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
  e2e/test/scenarios/permissions/data-model-permissions.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/24966-saved-native-q-field-values.cy.spec.js
  e2e/test/scenarios/permissions/sandboxes.cy.spec.js
  e2e/test/scenarios/sharing/alert/alert-permissions.cy.spec.js
  e2e/test/scenarios/sharing/alert/alert.cy.spec.js
  e2e/test/scenarios/sharing/subscriptions.cy.spec.js
  e2e/test/scenarios/visualizations/reproductions/21665-multi-series-frontend-reload.cy.spec.js
  e2e/test/scenarios/visualizations/reproductions/23076.cy.spec.js
  frontend/src/metabase/home/components/HomeLayout/HomeLayout.tsx
Labels: .CI & Tests, no-backport

#33684 Stop making my eyes bleed!
  .clj-kondo/config.edn
  .clj-kondo/hooks/clojure/test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/extract_test.clj
  shared/test/metabase/shared/formatting/date_test.cljc
  test/metabase/api/dashboard_test.clj
  test/metabase/db/data_migrations_test.clj
  test/metabase/driver/sql/parameters/substitute_test.clj
  test/metabase/query_processor/streaming/xlsx_test.clj
  test/metabase/query_processor/util/nest_query_test.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33801 Refactor useLeaveConfirmation hook to a component
  frontend/src/metabase/admin/permissions/components/PermissionsPageLayout/PermissionsPageLayout.tsx
  frontend/src/metabase/components/LeaveConfirmationModal/LeaveConfirmationModal.tsx
  frontend/src/metabase/components/LeaveConfirmationModal/index.ts
Labels: backport, .Team/42 :milky_way:

#33362 Add the official build for release workflow
  .github/workflows/build-for-release.yml
  .github/workflows/pre-release.yml
Labels: .Building & Releasing, no-backport

#33805 🍒 Manual Backport Fix object detail crashing when a table from foreign key is hidden (#33697)
  frontend/src/metabase-types/api/mocks/table.ts
  frontend/src/metabase-types/api/table.ts
  frontend/src/metabase/query_builder/selectors.js
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetail.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailBody.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailWrapper.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailsTable.unit.spec.tsx
  frontend/test/__support__/server-mocks/table.ts
  frontend/test/__support__/testDataset.js
  frontend/test/__support__/testDataset.ts
  frontend/test/__support__/ui.tsx
Labels: was-backported, visual, .Team/42 :milky_way:

#33824 🍒 Manual Backport #33638
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/dashboard/components/DashCard/Dashcard.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.jsx
  frontend/src/metabase/dashboard/containers/AutomaticDashboardApp.jsx
Labels: was-backported

#33822 Manual backport - Refactor useLeaveConfirmation hook to a component (#33801)
  frontend/src/metabase/admin/permissions/components/PermissionsPageLayout/PermissionsPageLayout.tsx
  frontend/src/metabase/components/LeaveConfirmationModal/LeaveConfirmationModal.tsx
  frontend/src/metabase/components/LeaveConfirmationModal/index.ts
Labels: was-backported

#33823 Fix e2e skipped test naming 2 (#33804)
  .github/workflows/e2e-tests.yml
Labels: was-backported

#33806 [Dashboard] Make parameters widget container not sticky on small devices
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.styled.tsx
  frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.js
  frontend/src/metabase/dashboard/components/Dashboard/stickyParameters.unit.spec.js
Labels: backport, .Team/42 :milky_way:

#33834 docs - update list of releases
  docs/releases.md
Labels: Type:Documentation, backport

#33601 Refactor Archive App
  e2e/support/commands/api/dashboard.js
  e2e/support/commands/api/question.js
  e2e/test/scenarios/collections/archive.cy.spec.js
  frontend/src/metabase-types/api/collection.ts
  frontend/src/metabase-types/api/mocks/collection.ts
  frontend/src/metabase/archive/containers/ArchiveApp.jsx
  frontend/src/metabase/archive/containers/ArchiveApp.tsx
  frontend/src/metabase/common/components/FieldPicker/FieldPicker.tsx
  frontend/src/metabase/components/ArchivedItem/ArchivedItem.tsx
  frontend/src/metabase/components/ArchivedItem/index.jsx
  frontend/src/metabase/components/StackedCheckBox/StackedCheckBox.tsx
  frontend/src/metabase/components/StackedCheckBox/index.jsx
  frontend/src/metabase/components/StackedCheckBox/index.tsx
  frontend/src/metabase/core/components/CheckBox/types.ts
  frontend/src/metabase/entities/search.js
  frontend/src/metabase/hoc/ListSelect.jsx
  frontend/src/metabase/lib/schema/schema.js
  frontend/src/metabase/query_builder/components/notebook/steps/FieldsPicker.tsx
  frontend/src/metabase/redux/app.ts
  frontend/src/metabase/routes.jsx
  frontend/src/metabase/sharing/components/EmailAttachmentPicker.jsx
Labels: backport, .Team/PixelPolice :police_officer:

#33732 Automagic tests
  shared/src/metabase/mbql/normalize.cljc
  src/metabase/automagic_dashboards/core.clj
  test/metabase/automagic_dashboards/core_test.clj
Labels: no-backport

#33837 Fix parameter mappings on x-ray dashboards
  src/metabase/automagic_dashboards/filters.clj
  test/metabase/automagic_dashboards/core_test.clj
Labels: no-backport

#33845 Allow multiple implicitly joinables for a single target field
  src/metabase/lib/breakout.cljc
  src/metabase/lib/metadata/calculation.cljc
  test/metabase/lib/metadata/calculation_test.cljc
  test/metabase/lib/test_metadata.cljc
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33863 docs - note on connection impersonation
  docs/permissions/data.md
Labels: Type:Documentation, backport

#33359 Allow removing filter defaults on Subscriptions (EE)
  docs/developers-guide/e2e-tests.md
  e2e/support/helpers/e2e-email-helpers.js
  e2e/test/scenarios/sharing/reproductions/24223-remove-filter-defaults-on-subscriptions.cy.spec.js
  e2e/test/scenarios/sharing/subscriptions.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/sharing/components/MutableParametersSection.jsx
  frontend/src/metabase-lib/parameters/utils/parameter-values.js
  frontend/src/metabase-lib/parameters/utils/parameter-values.unit.spec.js
  frontend/src/metabase/dashboard/actions/parameters.js
  frontend/src/metabase/dashboard/selectors/selectors.js
  frontend/src/metabase/lib/pulse.ts
  frontend/src/metabase/sharing/components/AddEditSidebar/AddEditEmailSidebar.jsx
  frontend/src/metabase/sharing/components/AddEditSidebar/AddEditSidebar.jsx
  frontend/src/metabase/sharing/components/AddEditSidebar/AddEditSlackSidebar.jsx
  frontend/src/metabase/sharing/components/AddEditSidebar/DefaultParametersSection.jsx
  frontend/test/metabase/lib/pulse.unit.spec.js
  src/metabase/pulse/parameters.clj
  test/metabase/pulse/parameters_test.clj
Labels: visual, .Team/PixelPolice :police_officer:, no-backport

#33341 fix static bundle dev mode
  package.json
  webpack.static-viz.config.js
Labels: backport, .Team/PixelPolice :police_officer:

#33840 Remove unused d3 package
  package.json
  yarn.lock
Labels: backport, .Team/PixelPolice :police_officer:

#33831 Fix notebook performance issue
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase-lib/metadata/Field.ts
  frontend/src/metabase-lib/queries/Query.ts
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/src/metabase-lib/queries/structured/Aggregation.ts
  frontend/src/metabase-lib/queries/structured/Breakout.ts
  frontend/src/metabase/admin/databases/components/DatabaseEditApp/Sidebar/Sidebar.unit.spec.tsx
  frontend/src/metabase/components/Triggerable/Triggerable.jsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/query_builder/components/GuiQueryEditor.jsx
  frontend/src/metabase/query_builder/components/notebook/steps/AggregateStep/AggregateStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/BreakoutStep/BreakoutStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/SortStep/SortStep.tsx
  frontend/src/metabase/visualizations/components/TableSimple/TableCell.jsx
  frontend/test/metabase-lib/lib/Question.unit.spec.js
Labels: visual, .Team/42 :milky_way:, no-backport

#33363 Create pre-release Docker staging images that include Metabase version in the name
  .github/workflows/pre-release.yml
Labels: .Building & Releasing, no-backport

#33877 Prefer secret value to secret instance ID
  src/metabase/api/database.clj
  src/metabase/models/secret.clj
  test/metabase/models/secret_test.clj
Labels: backport, .Team/QueryProcessor :hammer_and_wrench:

#33766 [MLv2] Macro for testing against a number of similar shaped but differently built queries at once
  .clj-kondo/config.edn
  .clj-kondo/hooks/metabase/lib/test_util/macros.clj
  test/metabase/lib/remove_replace_test.cljc
  test/metabase/lib/test_util/macros.clj
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33899 [MLv2] Adds hasWritePermission for native queries
  src/metabase/lib/core.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/native.cljc
  test/metabase/lib/native_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33850 Drop unused packages
  frontend/test/metabase-bootstrap.js
  package.json
  yarn.lock
Labels: .Team/42 :milky_way:, no-backport

#33593 Whats new notification
  e2e/test/scenarios/onboarding/navbar/whats-new.cy.spec.js
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/lib/utils.js
  frontend/src/metabase/lib/utils.unit.spec.ts
  frontend/src/metabase/nav/components/WhatsNewNotification/WhatsNewNotification.styled.tsx
  frontend/src/metabase/nav/components/WhatsNewNotification/WhatsNewNotification.tsx
  frontend/src/metabase/nav/components/WhatsNewNotification/WhatsNewNotification.unit.spec.tsx
  frontend/src/metabase/nav/components/WhatsNewNotification/index.ts
  frontend/src/metabase/nav/components/WhatsNewNotification/sparkles.svg
  frontend/src/metabase/nav/components/WhatsNewNotification/utils.ts
  frontend/src/metabase/nav/components/WhatsNewNotification/utils.unit.spec.ts
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarView.tsx
  frontend/test/metabase/lib/utils.unit.spec.js
Labels: .Team/42 :milky_way:, no-backport

#33842 Scope test selectors in models metadata tests
  e2e/test/scenarios/models/models-metadata.cy.spec.js
  frontend/src/metabase/query_builder/components/view/sidebars/DatasetManagementSection/DatasetMetadataStrengthIndicator/DatasetMetadataStrengthIndicator.tsx
Labels: .CI & Tests, backport, flaky-test-fix, .Team/PixelPolice :police_officer:

#33828 Fix 'object' visualization not showing 'details-only' fields
  frontend/src/metabase/visualizations/components/Visualization/Visualization-object.unit.spec.tsx
  frontend/src/metabase/visualizations/lib/settings/column.js
  frontend/src/metabase/visualizations/visualizations/ObjectDetail.jsx
  frontend/src/metabase/visualizations/visualizations/Table.jsx
Labels: backport, visual, .Team/42 :milky_way:

#33856 Include subpath to the URL during downloading question results
  frontend/src/metabase/query_builder/actions/downloading.ts
  frontend/src/metabase/query_builder/containers/QueryBuilder.unit.spec.tsx
Labels: backport, .Blocker, .Team/42 :milky_way:

#33871 Update dir locals
  .dir-locals.el
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33929 Fix permissions-instance-analytics-audit-v2-test
  enterprise/backend/test/metabase_enterprise/audit_app/permissions_test.clj
Labels: .Team/PixelPolice :police_officer:

#33926 [MLv2] Don't discard extra variadic args to drill-thru
  src/metabase/lib/js.cljs
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport, Querying/Drill Thrus

#33940 Fix failures in `api.persist-test`
  test/metabase/api/persist_test.clj
Labels: .Team/PixelPolice :police_officer:, no-backport

#33941 Fix E2E archive/unarchive dashboard flaky test
  e2e/test/scenarios/collections/archive.cy.spec.js
Labels: flaky-test-fix, no-backport

#33392 Metabase event subsystem overhaul
  enterprise/backend/test/metabase_enterprise/advanced_permissions/api/subscription_test.clj
  src/metabase/api/activity.clj
  src/metabase/api/card.clj
  src/metabase/api/dashboard.clj
  src/metabase/api/database.clj
  src/metabase/api/dataset.clj
  src/metabase/api/metric.clj
  src/metabase/api/segment.clj
  src/metabase/api/session.clj
  src/metabase/api/setup.clj
  src/metabase/core.clj
  src/metabase/email/messages.clj
  src/metabase/events.clj
  src/metabase/events/activity_feed.clj
  src/metabase/events/driver_notifications.clj
  src/metabase/events/last_login.clj
  src/metabase/events/persisted_info.clj
  src/metabase/events/revision.clj
  src/metabase/events/sync_database.clj
  src/metabase/events/view_log.clj
  src/metabase/models/activity.clj
  src/metabase/models/dashboard.clj
  src/metabase/models/pulse.clj
  src/metabase/models/setting.clj
  src/metabase/query_processor/middleware/process_userland_query.clj
  src/metabase/server/middleware/session.clj
  src/metabase/sync/sync_metadata/fks.clj
  src/metabase/sync/util.clj
  src/metabase/util/methodical/null_cache.clj
  src/metabase/util/methodical/unsorted_dispatcher.clj
  test/metabase/api/activity_test.clj
  test/metabase/api/revision_test.clj
  test/metabase/api/setup_test.clj
  test/metabase/events/activity_feed_test.clj
  test/metabase/events/last_login_test.clj
  test/metabase/events/persisted_info_test.clj
  test/metabase/events/revision_test.clj
  test/metabase/events/view_log_test.clj
  test/metabase/events_test.clj
  test/metabase/query_processor/middleware/process_userland_query_test.clj
  test/metabase/sync/util_test.clj
  test/metabase/test/initialize.clj
  test/metabase/test/initialize/events.clj
Labels: .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33675 Add CTA to search dropdown
  frontend/src/metabase-types/api/mocks/search.ts
  frontend/src/metabase/nav/components/AppBar/AppBar.unit.spec.tsx
  frontend/src/metabase/nav/components/AppBar/AppBarLarge.tsx
  frontend/src/metabase/nav/components/AppBar/AppBarSmall.tsx
  frontend/src/metabase/nav/components/search/RecentsList/RecentsList.jsx
  frontend/src/metabase/nav/components/search/RecentsList/RecentsList.styled.tsx
  frontend/src/metabase/nav/components/search/RecentsList/RecentsList.unit.spec.js
  frontend/src/metabase/nav/components/search/RecentsList/index.ts
  frontend/src/metabase/nav/components/search/SearchBar/SearchBar.styled.tsx
  frontend/src/metabase/nav/components/search/SearchBar/SearchBar.tsx
  frontend/src/metabase/nav/components/search/SearchBar/SearchBar.unit.spec.tsx
  frontend/src/metabase/nav/components/search/SearchBar/index.ts
  frontend/src/metabase/nav/components/search/SearchResults/SearchResults.styled.tsx
  frontend/src/metabase/nav/components/search/SearchResults/SearchResults.tsx
  frontend/src/metabase/nav/components/search/SearchResults/SearchResults.unit.spec.tsx
  frontend/src/metabase/nav/components/search/SearchResults/index.ts
  frontend/src/metabase/nav/components/search/SearchResultsDropdown/SearchResultsDropdown.styled.tsx
  frontend/src/metabase/nav/components/search/SearchResultsDropdown/SearchResultsDropdown.tsx
  frontend/src/metabase/nav/components/search/SearchResultsDropdown/SearchResultsDropdown.unit.spec.tsx
  frontend/src/metabase/nav/components/search/SearchResultsDropdown/index.ts
  frontend/src/metabase/search/components/SearchResult.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.styled.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.tsx
Labels: visual, .Team/42 :milky_way:

#33954 docs - update list of releases
  docs/releases.md
Labels: Type:Documentation, backport

#33946 Fix compare versions vunknown
  frontend/src/metabase/lib/utils.js
  frontend/src/metabase/lib/utils.unit.spec.ts
  frontend/src/metabase/nav/components/WhatsNewNotification/utils.unit.spec.ts
Labels: .Team/42 :milky_way:, no-backport

#33965 Reduce the number of Cypress retries in run mode
  e2e/support/config.js
Labels: .CI & Tests, backport

#33916 Rework FieldValuesWidget to skip initialization of Fields entity
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.tsx
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.unit.spec.tsx
Labels: backport, .Team/42 :milky_way:

#33908 [PivotTable] Improve scrolling performance
  frontend/src/metabase/actions/components/ActionViz/ActionButtonView.tsx
  frontend/src/metabase/admin/permissions/components/PermissionsTable/PermissionsTable.jsx
  frontend/src/metabase/admin/settings/components/widgets/CustomGeoJSONWidget.jsx
  frontend/src/metabase/collections/components/BaseTableItem.jsx
  frontend/src/metabase/components/Breadcrumbs/Breadcrumbs.jsx
  frontend/src/metabase/components/CollectionItem/CollectionItem.jsx
  frontend/src/metabase/components/EntityItem/EntityItem.jsx
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.styled.tsx
  frontend/src/metabase/components/ListItem/ListItem.styled.tsx
  frontend/src/metabase/core/components/Ellipsified/Ellipsified.stories.tsx
  frontend/src/metabase/core/components/Ellipsified/Ellipsified.tsx
  frontend/src/metabase/core/components/Ellipsified/index.ts
  frontend/src/metabase/dashboard/components/ActionSidebar/ActionSidebar.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.jsx
  frontend/src/metabase/home/components/HomeModelCard/HomeModelCard.styled.tsx
  frontend/src/metabase/home/components/HomeXrayCard/HomeXrayCard.styled.tsx
  frontend/src/metabase/hooks/use-is-truncated.ts
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterModal.styled.tsx
  frontend/src/metabase/reference/components/EditableReferenceHeader.jsx
  frontend/src/metabase/reference/components/ReferenceHeader.jsx
  frontend/src/metabase/status/components/StatusLarge/StatusLarge.tsx
  frontend/src/metabase/timelines/common/components/ModalHeader/ModalHeader.styled.tsx
  frontend/src/metabase/timelines/questions/components/TimelineCard/TimelineCard.tsx
  frontend/src/metabase/visualizations/components/FunnelNormal.jsx
  frontend/src/metabase/visualizations/components/LegendItem.jsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailsTable.tsx
  frontend/src/metabase/visualizations/components/ScalarValue/ScalarValue.jsx
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx
  frontend/src/metabase/visualizations/components/TableSimple/TableSimple.jsx
  frontend/src/metabase/visualizations/components/legend/LegendCaption.jsx
  frontend/src/metabase/visualizations/components/legend/LegendItem.jsx
  frontend/src/metabase/visualizations/components/skeletons/SkeletonCaption/SkeletonCaption.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/StaticSkeleton/StaticSkeleton.styled.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/EntityDisplay.styled.tsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.tsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTableCell.tsx
  frontend/src/metabase/visualizations/visualizations/Scalar/Scalar.styled.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.styled.tsx
Labels: backport, visual, .Team/42 :milky_way:

#33308 Adding Model to Cypress Snapshot
  e2e/snapshot-creators/default.cy.snap.js
  e2e/support/commands/api/dashboard.js
  e2e/support/helpers/e2e-ad-hoc-question-helpers.js
  e2e/support/helpers/e2e-notebook-helpers.js
  e2e/test/scenarios/admin-2/auditing/auditing.cy.spec.js
  e2e/test/scenarios/admin-2/auditing/questions-audit.cy.spec.js
  e2e/test/scenarios/admin-2/auditing/subscriptions.cy.spec.js
  e2e/test/scenarios/admin/databases/default-sample-database.cy.spec.js
  e2e/test/scenarios/admin/datamodel/editor.cy.spec.js
  e2e/test/scenarios/admin/datamodel/hide_tables.cy.spec.js
  e2e/test/scenarios/binning/binning-reproductions.cy.spec.js
  e2e/test/scenarios/binning/sql.cy.spec.js
  e2e/test/scenarios/collections/collection-items-listing.cy.spec.js
  e2e/test/scenarios/collections/collections.cy.spec.js
  e2e/test/scenarios/collections/uploads.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/13751-cc-allow-strings-in-filter.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/27745-cc-numeric-missing-summarize.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/embedding/embedding-full-app.cy.spec.js
  e2e/test/scenarios/filters/operators.cy.spec.js
  e2e/test/scenarios/filters/reproductions/20683-postgres-current-quarter.cy.spec.js
  e2e/test/scenarios/filters/view.cy.spec.js
  e2e/test/scenarios/joins/joins.cy.spec.js
  e2e/test/scenarios/joins/reproductions/15342-mysql-correct-joins-order.cy.spec.js
  e2e/test/scenarios/joins/reproductions/22859-multi-nested-joins-wrong-aliasing.cy.spec.js
  e2e/test/scenarios/joins/reproductions/29795-native-query-join-question-misses-metadata.cy.spec.js
  e2e/test/scenarios/models/create.cy.spec.js
  e2e/test/scenarios/models/model-indexes.cy.spec.js
  e2e/test/scenarios/models/models.cy.spec.js
  e2e/test/scenarios/models/reproductions/19737-data-picker-not-showing-moved-model.cy.spec.js
  e2e/test/scenarios/models/reproductions/19776-data-picker-not-displayed-after-archiving-model.cy.spec.js
  e2e/test/scenarios/models/reproductions/28971-filters-model-new-model.cy.spec.js
  e2e/test/scenarios/models/reproductions/31663-no-model-fks.cy.spec.js
  e2e/test/scenarios/native/data_ref.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
  e2e/test/scenarios/native/native_subquery.cy.spec.js
  e2e/test/scenarios/native/reproductions/15946-mongo-pre-select-table.cy.spec.js
  e2e/test/scenarios/native/reproductions/32121-sql-source-query-can-explore-results.cy.spec.js
  e2e/test/scenarios/onboarding/reference/databases.cy.spec.js
  e2e/test/scenarios/question/new.cy.spec.js
  e2e/test/scenarios/question/notebook.cy.spec.js
  e2e/test/scenarios/question/query-external.cy.spec.js
  e2e/test/scenarios/question/reproductions/13263-postgres-show-row-details-on-pk-click.cy.spec.js
  e2e/test/scenarios/question/reproductions/15714-cc-postgres-percentile-accepts-two-params.cy.spec.js
  e2e/test/scenarios/question/reproductions/17963-mongo-filter-expression-compare-two-fields.cy.spec.js
  e2e/test/scenarios/question/reproductions/19742-data-picker-closes-after-hiding-table.cy.spec.js
  e2e/test/scenarios/question/reproductions/22285-schema-picker.cy.spec.js
  e2e/test/scenarios/question/reproductions/4482-temporal-min-max.cy.spec.js
  e2e/test/scenarios/sharing/alert/email-alert.cy.spec.js
Labels: .Team/PixelPolice :police_officer:, no-backport

#33935 fix `landing-page` setting causing frontend to break
  e2e/test/scenarios/admin/settings/settings.cy.spec.js
  frontend/src/metabase/routes.jsx
Labels: backport, .Team/PixelPolice :police_officer:

#33815 X-ray improvements for clarity and literacy
  .clj-kondo/config.edn
  .lsp/config.edn
  bin/i18n/update-translation-template
  deps.edn
  src/metabase/api/automagic_dashboards.clj
  src/metabase/automagic_dashboards/core.clj
  src/metabase/automagic_dashboards/dashboard_templates.clj
  test/metabase/automagic_dashboards/core_test.clj
  test/metabase/automagic_dashboards/dashboard_templates_test.clj
  test/metabase/automagic_dashboards/rules_test.clj
Labels: no-backport

#33772 Instance Analytics Collections Always at Bottom of Collections List
  e2e/support/commands/api/dashboard.js
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  src/metabase/api/collection.clj
  src/metabase/models/collection.clj
  test/metabase/api/collection_test.clj
Labels: .Team/PixelPolice :police_officer:

#33994 Fix E2E model actions CRUD flake
  e2e/test/scenarios/actions/model-actions.cy.spec.js
Labels: backport, flaky-test-fix

#33979 Backport #33908
  frontend/src/metabase/actions/components/ActionViz/ActionButtonView.tsx
  frontend/src/metabase/admin/permissions/components/PermissionsTable/PermissionsTable.jsx
  frontend/src/metabase/admin/settings/components/widgets/CustomGeoJSONWidget.jsx
  frontend/src/metabase/collections/components/BaseTableItem.jsx
  frontend/src/metabase/components/Breadcrumbs/Breadcrumbs.jsx
  frontend/src/metabase/components/CollectionItem/CollectionItem.jsx
  frontend/src/metabase/components/EntityItem/EntityItem.jsx
  frontend/src/metabase/components/ListItem/ListItem.styled.tsx
  frontend/src/metabase/core/components/Ellipsified/Ellipsified.stories.tsx
  frontend/src/metabase/core/components/Ellipsified/Ellipsified.tsx
  frontend/src/metabase/core/components/Ellipsified/index.ts
  frontend/src/metabase/dashboard/components/ActionSidebar/ActionSidebar.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.jsx
  frontend/src/metabase/home/components/HomeModelCard/HomeModelCard.styled.tsx
  frontend/src/metabase/home/components/HomeXrayCard/HomeXrayCard.styled.tsx
  frontend/src/metabase/hooks/use-is-truncated.ts
  frontend/src/metabase/query_builder/components/filters/modals/BulkFilterModal/BulkFilterModal.styled.tsx
  frontend/src/metabase/reference/components/EditableReferenceHeader.jsx
  frontend/src/metabase/reference/components/ReferenceHeader.jsx
  frontend/src/metabase/status/components/StatusLarge/StatusLarge.tsx
  frontend/src/metabase/timelines/common/components/ModalHeader/ModalHeader.styled.tsx
  frontend/src/metabase/timelines/questions/components/TimelineCard/TimelineCard.tsx
  frontend/src/metabase/visualizations/components/FunnelNormal.jsx
  frontend/src/metabase/visualizations/components/LegendItem.jsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailsTable.tsx
  frontend/src/metabase/visualizations/components/ScalarValue/ScalarValue.jsx
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx
  frontend/src/metabase/visualizations/components/TableSimple/TableSimple.jsx
  frontend/src/metabase/visualizations/components/legend/LegendCaption.jsx
  frontend/src/metabase/visualizations/components/legend/LegendItem.jsx
  frontend/src/metabase/visualizations/components/skeletons/SkeletonCaption/SkeletonCaption.styled.tsx
  frontend/src/metabase/visualizations/components/skeletons/StaticSkeleton/StaticSkeleton.styled.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/EntityDisplay.styled.tsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.tsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTableCell.tsx
  frontend/src/metabase/visualizations/visualizations/Scalar/Scalar.styled.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.styled.jsx
Labels: visual, .Team/42 :milky_way:

#33939 Audit v2 collections for admins should return false for can_write
  src/metabase/models/collection.clj
  test/metabase/models/collection_test.clj
Labels: .Team/PixelPolice :police_officer:

#33827 Add custom warning message when leaving editing dashboard with unsaved changes
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.jsx
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.unit.spec.tsx
Labels: .Team/42 :milky_way:, no-backport

#33966 Convert lib/utils.js to ts
  frontend/src/metabase-lib/queries/utils/card.js
  frontend/src/metabase-lib/queries/utils/index.js
  frontend/src/metabase/admin/settings/components/SettingsBatchForm.jsx
  frontend/src/metabase/admin/settings/components/SettingsSlackForm.jsx
  frontend/src/metabase/admin/settings/components/widgets/CustomGeoJSONWidget.jsx
  frontend/src/metabase/components/UserAvatar/UserAvatar.tsx
  frontend/src/metabase/components/UserPicker/UserPicker.jsx
  frontend/src/metabase/dashboard/actions/data-fetching.js
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/utils.ts
  frontend/src/metabase/lib/card.js
  frontend/src/metabase/lib/pulse.ts
  frontend/src/metabase/lib/settings.ts
  frontend/src/metabase/lib/utils.js
  frontend/src/metabase/lib/utils.ts
  frontend/src/metabase/lib/utils.unit.spec.ts
  frontend/src/metabase/lib/validate.js
  frontend/src/metabase/nav/components/WhatsNewNotification/utils.ts
  frontend/src/metabase/pulse/components/RecipientPicker.jsx
  frontend/src/metabase/query_builder/actions/core/core.js
  frontend/src/metabase/query_builder/actions/navigation.js
  frontend/src/metabase/query_builder/components/QueryVisualization.jsx
  frontend/src/metabase/query_builder/components/template_tags/TagEditorHelp.tsx
  frontend/src/metabase/query_builder/reducers.js
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
  frontend/test/metabase/lib/query.unit.spec.js
Labels: visual, .Team/42 :milky_way:, no-backport

#34021 Revert `metabase-enterprise.audit-app.permissions-test` to previous version
  enterprise/backend/test/metabase_enterprise/audit_app/permissions_test.clj
Labels: .Team/PixelPolice :police_officer:

#33931 Fix 33917: Increase max length of collection slugs
  resources/migrations/000_migrations.yaml
  src/metabase/models/collection.clj
  test/metabase/models/collection_test.clj
Labels: .Team/42 :milky_way:, no-backport

#34024 Random BE cleanup
  .clj-kondo/config.edn
  .dir-locals.el
  dev/src/dev.clj
Labels: .Team/42 :milky_way:, no-backport

#34025 Use the same Chrome version (111) for visual tests as well
  .github/workflows/e2e-tests.yml
Labels: .CI & Tests, backport

#33989 fix multi-color selection in `ColorRangeSelector`
  frontend/src/metabase/core/components/ColorRangeSelector/ColorRangePopover.tsx
  frontend/src/metabase/core/components/ColorRangeSelector/ColorRangeSelector.unit.spec.tsx
  frontend/src/metabase/core/components/ColorRangeSelector/ColorRangeToggle.styled.tsx
  frontend/src/metabase/core/components/ColorRangeSelector/ColorRangeToggle.tsx
Labels: backport, .Team/PixelPolice :police_officer:

#34038 Fix serialization test on auditv2 branch
  enterprise/backend/src/metabase_enterprise/audit_db.clj
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/test/metabase_enterprise/audit_db_test.clj
Labels: .Team/PixelPolice :police_officer:

#34043 change the way unzip computes its target files
  enterprise/backend/src/metabase_enterprise/audit_db.clj
  src/metabase/util/files.clj
Labels: .Team/PixelPolice :police_officer:

#34028 Update changelog to include report-timezone-id-if-supported change
  docs/developers-guide/driver-changelog.md
Labels: backport, .Team/42 :milky_way:

#34046 update release-glob
  .github/workflows/rerun-workflows.yml
Labels: .CI & Tests, backport, .Team/PixelPolice :police_officer:

#34048 Nit: Fix typo in conditional table formatting
  docs/questions/sharing/visualizations/table.md
Labels: Type:Documentation

#33990 Fix 33971: CSV uploads aren't possible when native query editing is disabled
  e2e/test/scenarios/collections/uploads.cy.spec.js
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  frontend/src/metabase-lib/metadata/Database.ts
  frontend/src/metabase-types/api/database.ts
  frontend/src/metabase-types/api/mocks/database.ts
  frontend/src/metabase/collections/containers/CollectionContent.jsx
  src/metabase/api/card.clj
  src/metabase/api/database.clj
  test/metabase/api/card_test.clj
  test/metabase/api/database_test.clj
Labels: backport, .Team/PixelPolice :police_officer:, .Team/42 :milky_way:

#34014 Remove extra search API call
  e2e/test/scenarios/onboarding/search/search.cy.spec.js
  frontend/src/metabase/nav/components/SearchResults.tsx
Labels: .Team/42 :milky_way:, no-backport

#34029 [Auditv2] Add Instance Analytics Icon
  enterprise/frontend/src/metabase-enterprise/collections/components/CollectionInstanceAnalyticsIcon.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/collections/constants.ts
  enterprise/frontend/src/metabase-enterprise/collections/utils.unit.spec.ts
  frontend/src/metabase/collections/components/CollectionHeader/CollectionHeader.unit.spec.tsx
  frontend/src/metabase/core/components/Icon/icons/audit.svg
  frontend/src/metabase/core/components/Icon/icons/index.ts
  frontend/src/metabase/dashboard/components/DashboardHeader/tests/enterprise.unit.spec.ts
  frontend/src/metabase/entities/collections/utils.unit.spec.ts
  frontend/src/metabase/query_builder/components/SavedQuestionHeaderButton/SavedQuestionHeaderButton.unit.spec.js
Labels: .Team/PixelPolice :police_officer:

#33970 Fix archived items tooltip that's missing the item type
  frontend/src/metabase-types/api/collection.ts
  frontend/src/metabase/archive/containers/ArchiveApp.tsx
  frontend/src/metabase/common/utils/model-names.ts
  frontend/src/metabase/common/utils/model-names.unit.spec.ts
  frontend/src/metabase/components/ArchivedItem/ArchivedItem.tsx
  frontend/src/metabase/nav/components/RecentsList.jsx
  frontend/src/metabase/nav/utils/index.js
  frontend/src/metabase/search/components/InfoText.tsx
  frontend/src/metabase/search/components/SearchFilterModal/filters/TypeFilter.tsx
Labels: backport

#34037 [InteractiveTable] Improve peformance during scrolling
  frontend/src/metabase/visualizations/click-actions/Mode/Mode.ts
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx
Labels: backport, visual, .Team/42 :milky_way:

#33985 Fix links in admin settings to work on subpath
  enterprise/frontend/src/metabase-enterprise/application_permissions/api.js
  frontend/src/metabase/admin/tasks/components/Help/Help.tsx
  frontend/src/metabase/services.js
Labels: backport, visual, .Team/42 :milky_way:

#33902 [MLv2] Fix template-tags snippet-id
  src/metabase/lib/core.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/native.cljc
  test/metabase/lib/js_test.cljs
  test/metabase/lib/native_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33942 [MLv2] Add function for database engine
  src/metabase/lib/core.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/native.cljc
  test/metabase/lib/native_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:, no-backport

#33814 [MLv2] Handle coalesce type after conversion
  e2e/test/scenarios/native/reproductions/21597-query-build-card-save-modal.cy.spec.js
  e2e/test/scenarios/visualizations/pivot_tables.cy.spec.js
  frontend/src/metabase/query_builder/components/notebook/lib/steps.unit.spec.js
  frontend/src/metabase/visualizations/click-actions/drills/UnderlyingRecordsDrill.unit.spec.js
  frontend/test/metabase-lib/lib/Question.unit.spec.js
  src/metabase/lib/convert.cljc
  src/metabase/lib/metadata.cljc
  src/metabase/lib/query.cljc
  src/metabase/lib/schema/expression.cljc
  src/metabase/lib/schema/filter.cljc
  test/metabase/lib/aggregation_test.cljc
  test/metabase/lib/schema/filter_test.cljc
Labels: visual, .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:, no-backport

#34062 ~~Bump h2~~ inline parameter to fix flaky test
  enterprise/backend/src/metabase_enterprise/audit_app/pages/dashboards.clj
Labels: no-backport

#33992 Migrate the remaining existing events to the new audit_log API & table
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  src/metabase/events/audit_log.clj
  src/metabase/events/revision.clj
  src/metabase/models/audit_log.clj
  src/metabase/models/metric.clj
  src/metabase/models/segment.clj
  src/metabase/models/table.clj
  test/metabase/api/setup_test.clj
  test/metabase/events/audit_log_test.clj
  test/metabase/events/revision_test.clj
  test/metabase/models/audit_log_test.clj
Labels: .Team/PixelPolice :police_officer:

#34040 [MLv2] Add query can-run function
  src/metabase/lib/core.cljc
  src/metabase/lib/native.cljc
  src/metabase/lib/query.cljc
  src/metabase/lib/schema/template_tag.cljc
  test/metabase/lib/native_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:, no-backport

#34031 🍒 [E2E] Fix "back to x-ray model dashboard" navigation flake (#34020)
  e2e/test/scenarios/dashboard/dashboard-back-navigation.cy.spec.js
Labels: was-backported

#33991 Do not offer to delete archived collections
  e2e/test/scenarios/collections/archive.cy.spec.js
  frontend/src/metabase/components/ArchivedItem/ArchivedItem.tsx
Labels: support/Repro, backport

#34041 Audit permissions should be read only for cards and dashboards with instance analytics root
  src/metabase/models/card.clj
  src/metabase/models/dashboard.clj
  test/metabase/models/collection_test.clj
Labels: .Team/PixelPolice :police_officer:

#34071 moves ia content to /plugins from zip or resoruces
  enterprise/backend/src/metabase_enterprise/audit_db.clj
  enterprise/backend/test/metabase_enterprise/audit_db_test.clj
  src/metabase/util/files.clj
Labels: .Team/PixelPolice :police_officer:

#33980 Add explicit font size for Search Bar
  frontend/src/metabase/nav/components/SearchBar.styled.tsx
Labels: backport, .Team/42 :milky_way:

#33886 show columns added after the dashcard has been created in the viz settings
  frontend/src/metabase/visualizations/lib/settings/column.js
  frontend/src/metabase/visualizations/lib/settings/column.unit.spec.js
Labels: backport, visual, .Team/42 :milky_way:

#33807 Set last_acknowledged_version automatically for new users
  e2e/test/scenarios/onboarding/navbar/whats-new.cy.spec.js
  src/metabase/models/user.clj
  src/metabase/server/middleware/session.clj
  test/metabase/models/user_test.clj
Labels: backport, .Team/42 :milky_way:

#33808 Search Milestone 2: Add `created_by` search filter
  e2e/support/commands/api/dashboard.js
  e2e/test/scenarios/onboarding/search/search.cy.spec.js
  frontend/src/metabase-types/api/mocks/user.ts
  frontend/src/metabase/components/EventSandbox/EventSandbox.tsx
  frontend/src/metabase/search/components/SearchSidebar/SearchSidebar.tsx
  frontend/src/metabase/search/components/SearchSidebar/tests/setup.tsx
  frontend/src/metabase/search/components/SidebarFilter/SearchFilterPopoverWrapper.styled.tsx
  frontend/src/metabase/search/components/SidebarFilter/SearchFilterPopoverWrapper.tsx
  frontend/src/metabase/search/components/SidebarFilter/SearchFilterPopoverWrapper.unit.spec.tsx
  frontend/src/metabase/search/components/SidebarFilter/SidebarFilter.styled.tsx
  frontend/src/metabase/search/components/SidebarFilter/SidebarFilter.tsx
  frontend/src/metabase/search/components/SidebarFilter/SidebarFilter.unit.spec.tsx
  frontend/src/metabase/search/components/filters/CreatedByFilter/CreatedByContent.styled.tsx
  frontend/src/metabase/search/components/filters/CreatedByFilter/CreatedByContent.tsx
  frontend/src/metabase/search/components/filters/CreatedByFilter/CreatedByContent.unit.spec.tsx
  frontend/src/metabase/search/components/filters/CreatedByFilter/CreatedByDisplay.tsx
  frontend/src/metabase/search/components/filters/CreatedByFilter/CreatedByDisplay.unit.spec.tsx
  frontend/src/metabase/search/components/filters/CreatedByFilter/CreatedByFilter.tsx
  frontend/src/metabase/search/components/filters/CreatedByFilter/CreatedByFilter.unit.spec.tsx
  frontend/src/metabase/search/components/filters/CreatedByFilter/UserListElement.styled.tsx
  frontend/src/metabase/search/components/filters/CreatedByFilter/UserListElement.tsx
  frontend/src/metabase/search/components/filters/CreatedByFilter/UserListElement.unit.spec.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilter.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilter.unit.spec.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterContent.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterContent.unit.spec.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterDisplay.tsx
  frontend/src/metabase/search/constants.ts
  frontend/src/metabase/search/containers/SearchApp.jsx
  frontend/src/metabase/search/containers/SearchApp.styled.tsx
  frontend/src/metabase/search/containers/SearchApp.unit.spec.tsx
  frontend/src/metabase/search/types.ts
  frontend/src/metabase/search/utils/enabled-search-type/enabled-search-type.ts
  frontend/src/metabase/search/utils/search-location/search-location.ts
Labels: .Team/42 :milky_way:

#34079 Run the backport CI job when pushing new commits
  .github/workflows/backport-reminder.yml
  src/metabase/models/user.clj
Labels: .Team/42 :milky_way:, no-backport

#34073 Add missing @external tag to test introduced by #33990
  e2e/test/scenarios/collections/uploads.cy.spec.js
Labels: .Team/42 :milky_way:

#34057 [backport] Update changelog to include report-timezone-id-if-supported change
  docs/developers-guide/driver-changelog.md
Labels: was-backported

#33533 Search Milestone 1.5 - Integration Branch
  e2e/test/scenarios/onboarding/search/search.cy.spec.js
  frontend/src/metabase-types/api/mocks/search.ts
  frontend/src/metabase-types/api/search.ts
  frontend/src/metabase/components/FieldSet/FieldSet.jsx
  frontend/src/metabase/nav/components/AppBar/AppBar.unit.spec.tsx
  frontend/src/metabase/nav/components/AppBar/AppBarLarge.tsx
  frontend/src/metabase/nav/components/AppBar/AppBarSmall.tsx
  frontend/src/metabase/nav/components/search/RecentsList/RecentsList.jsx
  frontend/src/metabase/nav/components/search/RecentsList/RecentsList.styled.tsx
  frontend/src/metabase/nav/components/search/RecentsList/RecentsList.unit.spec.js
  frontend/src/metabase/nav/components/search/RecentsList/index.ts
  frontend/src/metabase/nav/components/search/SearchBar/SearchBar.styled.tsx
  frontend/src/metabase/nav/components/search/SearchBar/SearchBar.tsx
  frontend/src/metabase/nav/components/search/SearchBar/SearchBar.unit.spec.tsx
  frontend/src/metabase/nav/components/search/SearchBar/index.ts
  frontend/src/metabase/nav/components/search/SearchResults/SearchResults.styled.tsx
  frontend/src/metabase/nav/components/search/SearchResults/SearchResults.tsx
  frontend/src/metabase/nav/components/search/SearchResults/SearchResults.unit.spec.tsx
  frontend/src/metabase/nav/components/search/SearchResults/index.ts
  frontend/src/metabase/nav/components/search/SearchResultsDropdown/SearchResultsDropdown.styled.tsx
  frontend/src/metabase/nav/components/search/SearchResultsDropdown/SearchResultsDropdown.tsx
  frontend/src/metabase/nav/components/search/SearchResultsDropdown/SearchResultsDropdown.unit.spec.tsx
  frontend/src/metabase/nav/components/search/SearchResultsDropdown/index.ts
  frontend/src/metabase/search/components/SearchFilterModal/SearchFilterModal.styled.tsx
  frontend/src/metabase/search/components/SearchFilterModal/SearchFilterModal.tsx
  frontend/src/metabase/search/components/SearchFilterModal/SearchFilterModal.unit.spec.tsx
  frontend/src/metabase/search/components/SearchFilterModal/SearchFilterModalFooter.styled.tsx
  frontend/src/metabase/search/components/SearchFilterModal/SearchFilterModalFooter.tsx
  frontend/src/metabase/search/components/SearchFilterModal/filters/SearchFilterView.tsx
  frontend/src/metabase/search/components/SearchFilterModal/filters/SearchFilterView.unit.spec.tsx
  frontend/src/metabase/search/components/SearchFilterModal/filters/TypeFilter.styled.tsx
  frontend/src/metabase/search/components/SearchFilterModal/filters/TypeFilter.tsx
  frontend/src/metabase/search/components/SearchResult.tsx
  frontend/src/metabase/search/components/SearchSidebar/SearchSidebar.tsx
  frontend/src/metabase/search/components/SearchSidebar/tests/common.unit.spec.tsx
  frontend/src/metabase/search/components/SearchSidebar/tests/setup.tsx
  frontend/src/metabase/search/components/SidebarFilter/SidebarFilter.styled.tsx
  frontend/src/metabase/search/components/SidebarFilter/SidebarFilter.tsx
  frontend/src/metabase/search/components/SidebarFilter/SidebarFilter.unit.spec.tsx
  frontend/src/metabase/search/components/TypeSearchSidebar/TypeSearchSidebar.styled.tsx
  frontend/src/metabase/search/components/TypeSearchSidebar/TypeSearchSidebar.tsx
  frontend/src/metabase/search/components/TypeSearchSidebar/TypeSearchSidebar.unit.spec.tsx
  frontend/src/metabase/search/components/TypeSearchSidebar/index.ts
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilter.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterContent.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterContent.unit.spec.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterDisplay.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterDisplay.unit.spec.tsx
  frontend/src/metabase/search/constants.ts
  frontend/src/metabase/search/containers/SearchApp.jsx
  frontend/src/metabase/search/containers/SearchApp.styled.tsx
  frontend/src/metabase/search/containers/SearchApp.unit.spec.tsx
  frontend/src/metabase/search/types.ts
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.styled.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.tsx
Labels: visual, .Team/42 :milky_way:, no-backport

#34083 Fix uploads-disabled-for-sandboxed-user-test test by using root collection
  enterprise/backend/test/metabase_enterprise/upload_test.clj
Labels: .Team/42 :milky_way:, no-backport

#33978 Lazy load EntityForm
  frontend/src/metabase/entities/containers/EntityForm.jsx
Labels: backport, .Team/42 :milky_way:

#34092 Fix typo in audit.md
  docs/usage-and-performance-tools/audit.md
Labels: Type:Documentation, backport, .Team/PixelPolice :police_officer:

#33977 [MLv2] Rebuild `lib.equality` for faster, more precise matching and simpler code
  e2e/test/scenarios/actions/model-actions.cy.spec.js
  e2e/test/scenarios/visualizations/table-column-settings.cy.spec.js
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/utils.ts
  src/metabase/lib/breakout.cljc
  src/metabase/lib/drill_thru/sort.cljc
  src/metabase/lib/equality.cljc
  src/metabase/lib/fe_util.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/filter.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/js/metadata.cljs
  src/metabase/lib/order_by.cljc
  src/metabase/query_processor/middleware/binning.clj
  test/metabase/lib/breakout_test.cljc
  test/metabase/lib/column_group_test.cljc
  test/metabase/lib/equality_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/metadata/calculation_test.cljc
  test/metabase/lib/test_util.cljc
Labels: visual, .metabase-lib, .Team/QueryProcessor :hammer_and_wrench:, no-backport

#34101 Auditv2 more content transfer fixes
  enterprise/backend/src/metabase_enterprise/audit_db.clj
  enterprise/backend/test/metabase_enterprise/audit_db_test.clj
Labels: .Team/PixelPolice :police_officer:

#33983 Cleanup unused action names to prevent circular deps problem
  frontend/src/metabase/common/hooks/use-entity-list-query/use-entity-list-query.unit.spec.tsx
  frontend/src/metabase/redux/metadata.js
Labels: backport, .Team/42 :milky_way:

#34085 🍒 Backport: Archived items fixes
  frontend/src/metabase-types/api/collection.ts
  frontend/src/metabase/archive/containers/ArchiveApp.jsx
  frontend/src/metabase/common/utils/model-names.ts
  frontend/src/metabase/common/utils/model-names.unit.spec.ts
  frontend/src/metabase/components/ArchivedItem/ArchivedItem.jsx
  frontend/src/metabase/nav/components/RecentsList.jsx
  frontend/src/metabase/nav/utils/index.js
  frontend/src/metabase/search/components/InfoText.tsx
Labels: was-backported

#34090 [auditv2] Fix collection type check
  frontend/src/metabase/collections/utils.ts
Labels: .Team/PixelPolice :police_officer:

#33833 Add tests to Title drill-through leads to different destinations depending on whether the question is nested or not
  e2e/test/scenarios/dashboard/title-drill.cy.spec.js
Labels: backport, .Team/42 :milky_way:

#34056 Assure that common_name is assoc'd on a User correctly
  src/metabase/models/user.clj
  test/metabase/models/user_test.clj
Labels: .Team/42 :milky_way:, no-backport

#34116 Revert "show columns added after the dashcard has been created in the viz settings"
  frontend/src/metabase/visualizations/lib/settings/column.js
  frontend/src/metabase/visualizations/lib/settings/column.unit.spec.js
Labels: visual, .Team/42 :milky_way:, no-backport

#34118 Use Bigints for CSV uploads
  src/metabase/driver/h2.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  test/metabase/upload_test.clj
Labels: .Team/42 :milky_way:, no-backport

#33598 Update table_privileges on sync for MySQL
  src/metabase/driver/mysql.clj
  test/metabase/api/field_test.clj
  test/metabase/driver/mysql_test.clj
  test/metabase/driver/sql_jdbc/sync/describe_table_test.clj
  test/metabase/models/action_test.clj
  test/metabase/sync/sync_metadata/sync_table_privileges_test.clj
Labels: .Team/42 :milky_way:, no-backport

#34026 X ray stage 1
  src/metabase/automagic_dashboards/core.clj
  src/metabase/automagic_dashboards/schema.clj
  test/metabase/automagic_dashboards/core_test.clj
Labels: no-backport
