Repository metabase/metabase, pull requests merged in 2023-02, with the labels that each got.

#27999 docs - db docs
  docs/configuring-metabase/timezones.md
  docs/databases/connecting.md
  docs/databases/connections/athena.md
  docs/databases/connections/aws-rds.md
  docs/databases/connections/bigquery.md
  docs/databases/connections/google-analytics.md
  docs/databases/connections/h2.md
  docs/databases/connections/mongodb.md
  docs/databases/connections/mysql.md
  docs/databases/connections/oracle.md
  docs/databases/connections/postgresql.md
  docs/databases/connections/redshift.md
  docs/databases/connections/snowflake.md
  docs/databases/ssl-certificates.md
  docs/databases/start.md
  docs/permissions/data.md
Labels: Type:Documentation

#27945 [Manual backport] Fix column filters for nested queries
  frontend/src/metabase/modes/components/drill/ColumnFilterDrill.jsx
  frontend/test/metabase/scenarios/filters/reproductions/25927-column-filters-not-working-after-cc.cy.spec.js
Labels: auto-backported

#28007 docs - fix typo
  docs/databases/connecting.md
Labels: Type:Documentation, backport

#28015 Include numThreadsAwaitingCheckoutDefaultUser in conn pool stats
  src/metabase/analytics/prometheus.clj
  src/metabase/troubleshooting.clj
Labels: backport

#28004 Update Orders.ID description in fixture
  frontend/test/__support__/sample_database_fixture.json
Labels: Type:Tech Debt

#27902 Make using the QA DBs easier in local development
  frontend/test/__support__/e2e/cypress_data.js
  frontend/test/__support__/e2e/helpers/e2e-qa-databases-helpers.js
  frontend/test/metabase/scenarios/README.md
  frontend/test/metabase/scenarios/docker-compose.yml
  package.json
Labels: .CI & Tests

#28041 Replace E2E repro for #22822 with the FE unit test
  frontend/src/metabase/query_builder/components/view/ViewHeader.unit.spec.js
  frontend/test/metabase/scenarios/native/reproductions/22822-explore-results-unsupported-databases.cy.spec.js
Labels: .CI & Tests

#28070 docs - api docs update for 45
  docs/api/collection.md
  docs/api/pulse.md
  src/metabase/api/collection.clj
Labels: Type:Documentation

#27889 Enable and fix broken "edit history metadata" E2E tests
  frontend/test/metabase/scenarios/organization/edit-history-metadata.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, backport

#28069 docs - update api docs
  docs/api/action.md
  docs/api/card.md
  docs/api/collection.md
  docs/api/dashboard.md
  docs/api/database.md
  docs/api/dataset.md
  docs/api/ee/sandbox-gtap.md
  docs/api/embed.md
  docs/api/notify.md
  docs/api/permissions.md
  docs/api/public.md
  docs/api/pulse.md
  docs/api/setting.md
  src/metabase/api/collection.clj
Labels: Type:Documentation

#28087 [E2E] Make sure we can add Mongo using its connection string
  frontend/test/metabase/scenarios/admin/databases/add-external.cy.spec.js
Labels: .CI & Tests, backport

#28138 Repro #25715: Blank admin panel page for `null` database details
  frontend/test/metabase/scenarios/admin/databases/list.cy.spec.js
Labels: .CI & Tests, support/Repro

#28130 Repro #26571: do not show xrays if feature is disabled
  frontend/test/metabase/scenarios/dashboard/x-rays.cy.spec.js
Labels: .CI & Tests, support/Repro

#28178 Rename `metabase.util.honey-sql-*-extensions` => `metabase.util.honey-sql-*`
  .clj-kondo/config.edn
  docs/developers-guide/driver-changelog.md
  enterprise/backend/src/metabase_enterprise/advanced_permissions/models/permissions/application_permissions.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/common.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/common/card_and_dashboard_detail.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/common/cards.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/common/dashboards.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/common/pulses.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/dashboards.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/databases.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/downloads.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/queries.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/schemas.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/tables.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/user_detail.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/users.clj
  enterprise/backend/test/metabase_enterprise/audit_app/pages/common_test.clj
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  src/metabase/analytics/stats.clj
  src/metabase/api/activity.clj
  src/metabase/api/collection.clj
  src/metabase/api/database.clj
  src/metabase/api/search.clj
  src/metabase/db/setup.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql/query_processor.clj
  src/metabase/driver/sql/util.clj
  src/metabase/models/bookmark.clj
  src/metabase/models/collection.clj
  src/metabase/models/collection/graph.clj
  src/metabase/models/permissions.clj
  src/metabase/models/query.clj
  src/metabase/models/setting/cache.clj
  src/metabase/models/timeline_event.clj
  src/metabase/util/honey_sql_1.clj
  src/metabase/util/honey_sql_2.clj
  src/metabase/util/honeysql_extensions.clj
  test/metabase/models/permissions_group_test.clj
  test/metabase/test/data/sql/ddl.clj
  test/metabase/test/data/sql_jdbc/load_data.clj
  test/metabase/util/honey_sql_1_test.clj
  test/metabase/util/honey_sql_2_test.clj
Labels: Type:Tech Debt

#28174 Removing / fixing warnings when updating a dashboard filter and with incorrect link templates
  frontend/src/metabase/lib/formatting/link.ts
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
Labels: backport

#28135 Repro #25988: Cannot reference nested question as native subquery
  frontend/test/__support__/e2e/helpers/e2e-ad-hoc-question-helpers.js
  frontend/test/metabase/scenarios/native/native_subquery.cy.spec.js
Labels: .CI & Tests, support/Repro

#28219 docs - migrate down command backport
  docs/installation-and-operation/upgrading-metabase.md
Labels: Type:Documentation

#28216 Add conditional concurrency to heavy-traffic workflows
  .github/workflows/backend.yml
  .github/workflows/drivers.yml
  .github/workflows/frontend.yml
Labels: .CI & Tests

#27891 Validate E2E test files names
  .github/workflows/e2e-cross-version.yml
  frontend/test/metabase/scenarios/binning/correctness/longitude.cy.spec.js
  frontend/test/metabase/scenarios/binning/correctness/shared/constants.js
  frontend/test/metabase/scenarios/binning/correctness/time-series.cy.spec.js
  frontend/test/metabase/scenarios/cross-version/source/00-setup.cy.spec.js
  frontend/test/metabase/scenarios/cross-version/source/helpers/cross-version-source-helpers.js
  frontend/test/metabase/scenarios/cross-version/source/shared/cross-version-source.config.js
  frontend/test/metabase/scenarios/cross-version/target/helpers/cross-version-target-helpers.js
  frontend/test/metabase/scenarios/cross-version/target/shared/cross-version-target.config.js
  frontend/test/metabase/scenarios/cross-version/target/smoke.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-date.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-location.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-number.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-sql-date.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-sql-location.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-sql-number.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-sql-text-category.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/dashboard-filters-text-category.cy.spec.js
  frontend/test/metabase/scenarios/dashboard-filters/shared/dashboard-filters-date.js
  frontend/test/metabase/scenarios/dashboard-filters/shared/dashboard-filters-location.js
  frontend/test/metabase/scenarios/dashboard-filters/shared/dashboard-filters-number.js
  frontend/test/metabase/scenarios/dashboard-filters/shared/dashboard-filters-sql-date.js
  frontend/test/metabase/scenarios/dashboard-filters/shared/dashboard-filters-sql-location.js
  frontend/test/metabase/scenarios/dashboard-filters/shared/dashboard-filters-sql-number.js
  frontend/test/metabase/scenarios/dashboard-filters/shared/dashboard-filters-sql-text-category.js
  frontend/test/metabase/scenarios/dashboard-filters/shared/dashboard-filters-text-category.js
  frontend/test/metabase/scenarios/embedding/embedding-dashboard.cy.spec.js
  frontend/test/metabase/scenarios/embedding/embedding-linked-filters.cy.spec.js
  frontend/test/metabase/scenarios/embedding/embedding-native.cy.spec.js
  frontend/test/metabase/scenarios/embedding/embedding-questions.cy.spec.js
  frontend/test/metabase/scenarios/embedding/embedding-snippets.cy.spec.js
  frontend/test/metabase/scenarios/embedding/shared/embedding-dashboard.js
  frontend/test/metabase/scenarios/embedding/shared/embedding-linked-filters.js
  frontend/test/metabase/scenarios/embedding/shared/embedding-native.js
  frontend/test/metabase/scenarios/embedding/shared/embedding-questions.js
  frontend/test/metabase/scenarios/embedding/shared/embedding-snippets.js
  frontend/test/validate-e2e-test-files.js
  package.json
Labels: .CI & Tests

#28097 Fix DataSelector not working in full app embedding
  frontend/src/metabase/containers/DataPicker/DataPickerContainer.tsx
  frontend/src/metabase/containers/NewItemMenu/NewItemMenu.tsx
  frontend/src/metabase/models/containers/NewModelOptions/NewModelOptions.jsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarContainer.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor.jsx
  frontend/src/metabase/selectors/data.ts
  frontend/src/metabase/selectors/data.unit.spec.ts
  frontend/test/metabase/scenarios/embedding/embedding-full-app.cy.spec.js
Labels: support/Repro, backport

#28223 docs - clickhouse partner
  docs/developers-guide/drivers/start.md
  docs/developers-guide/partner-and-community-drivers.md
Labels: Type:Documentation, backport

#28226 docs - migrate down docker
  docs/installation-and-operation/upgrading-metabase.md
Labels: Type:Documentation, backport

#28200 docs - update description and API docs
  docs/api/action.md
  docs/api/card.md
  docs/api/collection.md
  docs/api/dataset.md
  docs/api/public.md
  docs/api/setting.md
  src/metabase/util/malli/describe.cljc
  test/metabase/api/action_test.clj
  test/metabase/util/malli/describe_test.clj
Labels: Type:Documentation

#28232 docs - update field filters
  docs/questions/native-editor/sql-parameters.md
  docs/troubleshooting-guide/error-message.md
  docs/troubleshooting-guide/filters.md
  docs/troubleshooting-guide/sql.md
Labels: Type:Documentation, backport

#28222 Manual backport of various (blocked) Cypress changes
  .github/workflows/e2e-main.yml
  .github/workflows/e2e-tests.yml
  frontend/src/metabase/query_builder/components/view/ViewHeader.unit.spec.js
  frontend/test/__support__/e2e/cypress_data.js
  frontend/test/__support__/e2e/helpers/e2e-ad-hoc-question-helpers.js
  frontend/test/__support__/e2e/helpers/e2e-qa-databases-helpers.js
  frontend/test/metabase/scenarios/admin/databases/add-external.cy.spec.js
  frontend/test/metabase/scenarios/admin/databases/list.cy.spec.js
  frontend/test/metabase/scenarios/dashboard/x-rays.cy.spec.js
  frontend/test/metabase/scenarios/native/native_subquery.cy.spec.js
  frontend/test/metabase/scenarios/native/reproductions/22822-explore-results-unsupported-databases.cy.spec.js
Labels: .CI & Tests, auto-backported

#28243 no native drill fallback when embedded
  frontend/src/metabase/modes/components/drill/NativeDrillFallback/NativeDrillFallback.styled.tsx
  frontend/src/metabase/modes/components/drill/NativeDrillFallback/NativeDrillFallback.tsx
  frontend/src/metabase/modes/components/drill/NativeDrillFallback/NativeDrillFallback.unit.spec.tsx
Labels: backport

#28265 Repro #28218: Cannot reference native question with semicolon
  frontend/test/metabase/scenarios/native/native_subquery.cy.spec.js
Labels: .CI & Tests, support/Repro

#28260 Repro #25156: Handle invalid x-axis scale
  frontend/test/metabase/scenarios/visualizations/reproductions/25156-invalid-x-axis-series.cy.spec.js
Labels: .CI & Tests, support/Repro

#28262 Repro #27873: Missing group by column from the joined table
  frontend/test/metabase/scenarios/joins/reproductions/27873-missing-joined-group-by.cy.spec.js
Labels: .CI & Tests, support/Repro

#28253 [Chore] Upgrade `deploysentinel` to v0.7.8
  package.json
  yarn.lock
Labels: .CI & Tests, backport

#27983 Custom Table e2e Tests 1: Add basic querying for postgres and mysql
  frontend/test/__support__/e2e/config.js
  frontend/test/__support__/e2e/cypress_data.js
  frontend/test/__support__/e2e/db_tasks.js
  frontend/test/__support__/e2e/helpers/e2e-qa-databases-helpers.js
  package.json
  yarn.lock
Labels: .CI & Tests

#28276 docs - update embedding comparison
  docs/embedding/introduction.md
  docs/embedding/signed-embedding.md
Labels: Type:Documentation, backport

#28257 [CI] Add path filtering to the yaml linter workflow
  .github/file-paths.yaml
  .github/workflows/yaml.yml
Labels: .CI & Tests

#27984 Custom Table e2e Tests 2: Simple issue reproduction
  frontend/test/metabase/scenarios/custom-column/reproductions/27745-cc-numeric-missing-summarize.cy.spec.js
Labels: .CI & Tests, support/Repro

#28310 [CI] Start using the latest `maildev` (2.0.5) and adjust ports
  .github/workflows/e2e-main.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/percy-issue-comment.yml
  .github/workflows/percy-visual-label.yml
  frontend/test/__support__/e2e/cypress_data.js
  frontend/test/__support__/e2e/helpers/e2e-email-helpers.js
  frontend/test/metabase/scenarios/README.md
  frontend/test/metabase/scenarios/admin/settings/email.cy.spec.js
  frontend/test/metabase/scenarios/permissions/sandboxes.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/18009-nodata-creates-subscription-receives-error.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/18344-subscription-shows-original-question-name.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/18352-subscription-int64-value-card.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/21559-subscription-bar-sent-as-scalar.cy.spec.js
  frontend/test/metabase/scenarios/sharing/subscriptions.cy.spec.js
Labels: .CI & Tests, backport

#28323 Fix Percy static-viz failures on `master`
  frontend/test/__support__/e2e/helpers/e2e-email-helpers.js
Labels: Type:Tech Debt, .CI & Tests

#28330 Repro #28193: Cannot use custom column with models
  frontend/test/metabase/scenarios/models/reproductions/28193-cannot-use-custom-column.cy.spec.js
Labels: .CI & Tests, support/Repro

#28325 [CI] Improve path-filtering logic for `frontend_sources`
  .github/file-paths.yaml
Labels: Type:Tech Debt, .CI & Tests

#28339 docs - fix links
  docs/troubleshooting-guide/filters.md
Labels: Type:Documentation, backport

#27986 Custom Table e2e Tests 3: Create and add writable DBs
  frontend/test/__support__/e2e/cypress_data.js
  frontend/test/__support__/e2e/helpers/e2e-qa-databases-helpers.js
  frontend/test/metabase/scenarios/admin/databases/actions.cy.spec.js
  frontend/test/snapshot-creators/qa-db.cy.snap.js
Labels: .CI & Tests

#28317 docs - update signed embedding parameters
  docs/embedding/signed-embedding-parameters.md
Labels: Type:Documentation, backport

#28392 [CI] Optimize CodeQL so it doesn't run two times per commit
  .github/workflows/codeql.yml
Labels: .CI & Tests

#27946 Fix missing keys in Account settings > Login history
  frontend/src/metabase/account/login-history/components/LoginHistory/LoginHistory.jsx
Labels: Type:Tech Debt, .Frontend

#28395 [E2E] Fix `embedding-native` flake
  frontend/test/metabase/scenarios/embedding/embedding-native.cy.spec.js
  frontend/test/metabase/scenarios/embedding/shared/embedding-native.js
Labels: Type:Tech Debt, .CI & Tests

#28398 Backport E2E reproductions
  frontend/test/metabase/scenarios/joins/reproductions/27873-missing-joined-group-by.cy.spec.js
  frontend/test/metabase/scenarios/models/reproductions/28193-cannot-use-custom-column.cy.spec.js
  frontend/test/metabase/scenarios/native/native_subquery.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/25156-invalid-x-axis-series.cy.spec.js
Labels: auto-backported

#28400 Fix syntax in rerun workflows logic 🤦‍♂️
  .github/workflows/rerun-workflows.yml
Labels: Type:Tech Debt, .CI & Tests

#28401 [CI] Fix syntax in rerun workflows logic (#28400)
  .github/workflows/rerun-workflows.yml
Labels: auto-backported

#28399 🍒 Various CI fixes and improvements from `master`
  .github/workflows/codeql.yml
  .github/workflows/e2e-main.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/percy-issue-comment.yml
  .github/workflows/percy-visual-label.yml
  frontend/test/__support__/e2e/cypress_data.js
  frontend/test/__support__/e2e/helpers/e2e-email-helpers.js
  frontend/test/metabase/scenarios/README.md
  frontend/test/metabase/scenarios/admin/settings/email.cy.spec.js
  frontend/test/metabase/scenarios/embedding/embedding-native.cy.spec.js
  frontend/test/metabase/scenarios/embedding/embedding-native.js
  frontend/test/metabase/scenarios/permissions/sandboxes.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/18009-nodata-creates-subscription-receives-error.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/18344-subscription-shows-original-question-name.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/18352-subscription-int64-value-card.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/21559-subscription-bar-sent-as-scalar.cy.spec.js
  frontend/test/metabase/scenarios/sharing/subscriptions.cy.spec.js
Labels: auto-backported

#28363 [CI] Improve path-filtering logic for `ci`
  .github/file-paths.yaml
Labels: .CI & Tests

#28409 Add fallback stub for `be-checks`
  .github/workflows/backend.yml
Labels: Type:Tech Debt, .CI & Tests

#28410 [E2E] Fix native field filter related flakes
  frontend/src/metabase/components/Popover/Popover.jsx
  frontend/test/metabase/scenarios/native-filters/helpers/e2e-field-filter-helpers.js
Labels: Type:Tech Debt, .CI & Tests

#28421 🍒 Backport more flake fixes
  frontend/src/metabase/components/Popover/Popover.jsx
  frontend/test/metabase/scenarios/native-filters/helpers/e2e-field-filter-helpers.js
  frontend/test/metabase/scenarios/onboarding/notifications.cy.spec.js
Labels: auto-backported

#28412 [CI] Fix Google related drivers classpath test
  .github/workflows/drivers.yml
Labels: Type:Tech Debt, .CI & Tests

#28430 Upgrade `babel-loader` to 9.1.2
  package.json
  yarn.lock
Labels: Type:Tech Debt

#28429 🍒 [CI] Fix Google related drivers classpath test (#28412)
  .github/workflows/drivers.yml
Labels: auto-backported

#28434 [Chore] Upgrade `esbuild`
  package.json
  yarn.lock
Labels: Type:Tech Debt

#28432 [CI] Improve `codenotify` workflow
  .github/workflows/codenotify.yml
Labels: Type:Tech Debt, .CI & Tests

#28445 [E2E] Prevent app permission flakes
  frontend/test/metabase/scenarios/permissions/application-permissions.cy.spec.js
Labels: .CI & Tests, flaky-test-fix

#28431 [CI] Unify E2E tests workflows
  .github/workflows/e2e-main.yml
  .github/workflows/e2e-tests.yml
Labels: .CI & Tests

#28450 [E2E] Fix search flake
  frontend/test/metabase/scenarios/onboarding/search/search.cy.spec.js
Labels: .CI & Tests, flaky-test-fix

#27989 Custom Table e2e Tests 5: Simple actions testing
  docs/developers-guide/e2e-tests.md
  frontend/test/__support__/e2e/helpers/e2e-action-helpers.js
  frontend/test/__support__/e2e/helpers/e2e-qa-databases-helpers.js
  frontend/test/__support__/e2e/test_tables.js
  frontend/test/metabase/scenarios/dashboard/actions-on-dashboards.cy.spec.js
  frontend/test/metabase/scenarios/models/model-actions.cy.spec.js
Labels: .CI & Tests

#28463 Remove unused emoji script
  bin/update-emoji
Labels: Type:Tech Debt

#28475 Fix flaky test `metabase.server.middleware.offset-paging-test/paging-test`
  test/metabase/server/middleware/offset_paging_test.clj
Labels: backport

#28459 [E2E] Expand and fix repro for #25473
  frontend/test/metabase/scenarios/sharing/public.cy.spec.js
  frontend/test/metabase/scenarios/sharing/reproductions/25473-dashboard-text-filter-asking-for-number.cy.spec.js
Labels: Type:Tech Debt, .CI & Tests, flaky-test-fix

#28460 [Chore] Upgrade `lint-staged` to the latest version
  package.json
  yarn.lock
Labels: .CI & Tests

#28467 [E2E] Use Mongo 4.4 in tests
  .github/workflows/e2e-tests.yml
  frontend/test/__support__/e2e/helpers/e2e-qa-databases-helpers.js
Labels: .CI & Tests

#28482 Fix and expand verify doc links logic
  .github/workflows/docs.yml
  bin/verify-doc-links
  package.json
Labels: Type:Tech Debt, .CI & Tests

#28465 Drill-thru with binning should use `[and [>= ...] [< ...]`, not `[between ...]`
  frontend/src/metabase-lib/queries/utils/actions.js
  frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js
Labels: backport

#28458 Fix Missing type property on a card breaks the frontend on the Notebook view
  frontend/src/metabase-lib/Dimension.ts
  frontend/test/metabase/scenarios/question/reproductions/28221-missing-custom-field-metadata.cy.spec.js
Labels: backport

#28529 fix official questions title alignment
  frontend/src/metabase/visualizations/components/legend/LegendCaption.styled.jsx
Labels: .Blocker

#28452 Add `database_id` to implicit actions (except when it's persisted)
  src/metabase/models/action.clj
  test/metabase/api/action_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/models/action_test.clj
Labels: .Blocker

#28539 docs - dashboard filter selectable values
  docs/dashboards/filters.md
  docs/dashboards/images/add-filter.png
  docs/dashboards/images/filter-type.png
  docs/dashboards/images/filters.png
  docs/dashboards/images/selectable-values.png
  docs/dashboards/images/wiring-cards.png
Labels: Type:Documentation

#28508 docs - add link card to docs
  docs/dashboards/images/autorefresh.png
  docs/dashboards/images/dashboard-with-link-cards.png
  docs/dashboards/images/edit.png
  docs/dashboards/images/new-text-card.png
  docs/dashboards/images/pinning-dashboard.png
  docs/dashboards/images/share-icon.png
  docs/dashboards/images/text-card-button.png
  docs/dashboards/images/visualization-settings.png
  docs/dashboards/introduction.md
Labels: Type:Documentation

#28484 docs - remove note on joins
  docs/questions/query-builder/join.md
Labels: Type:Documentation

#28238 26890 viz picker behavior
  frontend/src/metabase/query_builder/components/view/ViewFooter.jsx
  frontend/src/metabase/query_builder/components/view/ViewFooter.styled.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/ChartSettingsSidebar.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/ChartTypeSidebar.styled.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/ChartTypeSidebar.tsx
  frontend/src/metabase/query_builder/reducers.js
  frontend/src/metabase/visualizations/components/ChartSettings.jsx
  frontend/src/metabase/visualizations/components/ChartSettings.styled.tsx
  frontend/src/metabase/visualizations/components/ChartSettingsWidgetPopover.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
  frontend/src/metabase/visualizations/shared/utils/data.ts
  frontend/test/metabase/query_builder/components/view/sidebars/ChartSettingsSidebar.unit.spec.js
  frontend/test/metabase/query_builder/components/view/sidebars/ChartTypeSidebar.unit.spec.js
  frontend/test/metabase/scenarios/binning/binning-reproductions.cy.spec.js
  frontend/test/metabase/scenarios/cross-version/source/03-questions.cy.spec.js
  frontend/test/metabase/scenarios/native/native.cy.spec.js
  frontend/test/metabase/scenarios/native/reproductions/12439-click-on-legend-breaks-ui.cy.spec.js
  frontend/test/metabase/scenarios/permissions/admin-permissions.cy.spec.js
  frontend/test/metabase/scenarios/permissions/reproductions/22447-illogical-UI-elements-for-nodata.cy.spec.js
  frontend/test/metabase/scenarios/permissions/sandboxes.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/18207-string-min-max.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/18978-18977-nested-question-nodata-user.cy.spec.js
  frontend/test/metabase/scenarios/question/settings.cy.spec.js
  frontend/test/metabase/scenarios/sharing/alert/alert-types.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/bar_chart.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/funnel.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/line_chart.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/maps.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/pivot_tables.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/11249-add-more-series-no-columns.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/21452-xhr-on-every-char-for-rename.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/21504-pie-settings-formatting.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/22206-add-remove-column.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/22527-scatter-negative-values-not-rendered.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/scalar.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/trendline.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/waterfall.cy.spec.js
Labels: .Blocker

#28527 fix sending test subscriptions on dashboards with actions
  frontend/src/metabase-types/api/mocks/dashboard.ts
  frontend/src/metabase/sharing/components/SharingSidebar.jsx
  frontend/src/metabase/sharing/components/SharingSidebar.unit.spec.js
Labels: .Blocker

#28548 [CI] Print useful summary in a re-run workflow
  .github/workflows/rerun-workflows.yml
Labels: .CI & Tests

#28533 Update outdated libs
  yarn.lock
Labels: .Blocker

#28570 docs - update api docs
  docs/api/action.md
  docs/api/card.md
  docs/api/dashboard.md
  docs/api/database.md
  docs/api/dataset.md
  docs/api/ee/sandbox-gtap.md
  docs/api/permissions.md
  docs/api/public.md
  docs/api/search.md
Labels: Type:Documentation

#28518 Set action.model_id to cascade on delete
  resources/migrations/000_migrations.yaml
  test/metabase/db/schema_migrations_test.clj
Labels: .Blocker

#28572 [E2E] Fix Percy flake `parameters-widget`
  frontend/test/__support__/e2e/helpers/e2e-dashboard-helpers.js
  frontend/test/metabase-visual/dashboard/parameters-widget.cy.spec.js
Labels: flaky-test-fix

#28576 [WIP] Do not load personal collections on home page
  frontend/src/metabase/collections/containers/CollectionContent.jsx
  frontend/src/metabase/containers/DataPicker/CardPicker/CardPickerContainer.tsx
  frontend/src/metabase/entities/questions.js
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarContainer.tsx
  frontend/src/metabase/query_builder/components/DataSelector/saved-question-picker/SavedQuestionPicker.jsx
Labels: .Blocker

#28578 [CI] Increase E2E tests timeout
  .github/workflows/e2e-tests.yml
Labels: .CI & Tests

#28473 docs - actions
  docs/README.md
  docs/actions/basic.md
  docs/actions/custom.md
  docs/actions/images/basic-actions.png
  docs/actions/images/custom-action.png
  docs/actions/images/dropdown.png
  docs/actions/images/example-action.png
  docs/actions/images/public-form.png
  docs/actions/introduction.md
  docs/actions/start.md
  docs/dashboards/actions.md
  docs/dashboards/images/button-form.png
  docs/dashboards/images/buttons.png
  docs/dashboards/images/dashboard-filter-action.png
  docs/dashboards/images/filter-to-action-button.png
  docs/dashboards/start.md
  docs/data-modeling/images/model-detail.png
  docs/data-modeling/models.md
  docs/questions/sharing/public-links.md
  docs/start.md
Labels: Type:Documentation

#28584 [CI] optimize JUnit report generation for backend tests
  .github/actions/test-driver/action.yml
  .github/workflows/backend.yml
Labels: .CI & Tests

#28592 [E2E] Fix flaky `native-filters` test (21246 repro)
  frontend/test/metabase/scenarios/native-filters/reproductions/21246.cy.spec.js
Labels: flaky-test-fix

#28512 Fallback to generating action form fields from parameters
  frontend/src/metabase/actions/components/ActionViz/Action.unit.spec.tsx
  frontend/src/metabase/actions/containers/ActionParametersInputForm/ActionParametersInputForm.unit.spec.tsx
  frontend/src/metabase/actions/utils.ts
  frontend/src/metabase/actions/utils.unit.spec.ts
  frontend/test/metabase/scenarios/dashboard/actions-on-dashboards.cy.spec.js
  frontend/test/metabase/scenarios/models/model-actions.cy.spec.js
Labels: .Blocker

#28591 [CI] Run Frontend and Drivers tests on Ubuntu 22.04
  .github/workflows/drivers.yml
  .github/workflows/frontend.yml
Labels: .CI & Tests

#28597 [E2E] Fix model-revision-history flake
  frontend/test/metabase/scenarios/models/models-revision-history.cy.spec.js
Labels: flaky-test-fix

#28604 [E2E] Fix x-ray flake
  frontend/test/metabase/scenarios/dashboard/x-rays.cy.spec.js
Labels: flaky-test-fix

#28605 [Ci] Fix rerun workflow
  .github/workflows/rerun-workflows.yml
Labels: Type:Tech Debt, .CI & Tests

#28606 [CI] Start running `backend` and `e2e` workflows on `ubuntu-22.04`
  .github/workflows/backend.yml
  .github/workflows/e2e-tests.yml
Labels: .CI & Tests

#28625 stack area chart with breakouts
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/src/metabase/visualizations/lib/settings/graph.unit.spec.js
  src/metabase/pulse/render/body.clj
Labels: visual

#28612 [CI] Remove unneeded step from drivers workflow
  .github/workflows/drivers.yml
Labels: Type:Tech Debt, .CI & Tests

#28657 Run workflows using `ubuntu-22.04` - batch 3
  .github/workflows/auto-backport.yml
  .github/workflows/backport.yml
  .github/workflows/percy-issue-comment.yml
  .github/workflows/rerun-workflows.yml
  .github/workflows/stale.yml
Labels: .CI & Tests

#28658 Run workflows using `ubuntu-22.04` - batch 4
  .github/workflows/e2e-cross-version.yml
  .github/workflows/fuzzing.yml
  .github/workflows/snowplow.yml
Labels: .CI & Tests

#28659 Run workflows using `ubuntu-22.04` - batch 5
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
Labels: .CI & Tests

#28615 Remove duplicate field entries for parameters in actions
  frontend/src/metabase-types/api/mocks/actions.ts
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FormCreator.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/utils.ts
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/utils.unit.spec.ts
  frontend/src/metabase/actions/containers/ActionCreator/tests/utils.unit.spec.ts
  frontend/src/metabase/actions/containers/ActionCreator/utils.ts
  frontend/src/metabase/actions/containers/ActionCreator/utils.unit.spec.ts
Labels: .Blocker

#28629 Revert the ports of number and date formatting to CLJC
  frontend/src/metabase/lib/formatting/currency.js
  frontend/src/metabase/lib/formatting/date.tsx
  frontend/src/metabase/lib/formatting/datetime-utils.ts
  frontend/src/metabase/lib/formatting/numbers.tsx
  frontend/src/metabase/lib/formatting/time.ts
  frontend/src/metabase/lib/formatting/types.ts
  frontend/src/metabase/lib/time.ts
  frontend/src/metabase/static-viz/components/ProgressBar/constants.ts
  frontend/src/metabase/static-viz/lib/numbers.unit.spec.js
  frontend/src/metabase/visualizations/lib/apply_tooltips.js
  frontend/src/metabase/visualizations/lib/chart_values.js
  frontend/src/metabase/visualizations/lib/settings/column.js
  frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.jsx
  frontend/src/metabase/visualizations/visualizations/RowChart/utils/format.ts
  frontend/test/metabase-visual/static-visualizations/gauge.cy.spec.js
  frontend/test/metabase/collections/BaseItemsTable.unit.spec.js
  frontend/test/metabase/components/DateTime.unit.spec.js
  frontend/test/metabase/lib/formatting.unit.spec.js
  frontend/test/metabase/scenarios/question/settings.cy.spec.js
Labels: .Blocker

#28204 Added `api/collection/{tree}` flag to remove other users' collections from results
  .cljfmt/indents.clj
  .pre-commit-config.yaml
  bin/cljfmt.sh
  frontend/src/metabase/collections/containers/CollectionContent.jsx
  frontend/src/metabase/containers/DataPicker/CardPicker/CardPickerContainer.tsx
  frontend/src/metabase/entities/questions.js
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarContainer.tsx
  frontend/src/metabase/query_builder/components/DataSelector/saved-question-picker/SavedQuestionPicker.jsx
  src/metabase/api/collection.clj
  test/metabase/api/collection_test.clj
Labels: .Blocker

#28671 Fix e2e flake in dashboard downloads test
  frontend/test/metabase/scenarios/downloads/downloads.cy.spec.js
Labels: flaky-test-fix

#28660 [CI] Refine and update code coverage rules and targets
  codecov.yml
  jest.unit.conf.json
Labels: .CI & Tests

#28656 Run workflows using `ubuntu-22.04` - batch 2
  .github/workflows/codenotify.yml
  .github/workflows/codeql.yml
  .github/workflows/doc-md-links.yml
  .github/workflows/whitespace.yml
  .github/workflows/yaml.yml
Labels: .CI & Tests

#28709 Revert column settings changes
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase-lib/queries/utils/dataset.js
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionButtons/ChartSettingsButton.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionButtons/DashCardActionButtons.tsx
  frontend/src/metabase/query_builder/components/view/ConvertQueryModal/ConvertQueryModal.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/ChartSettingsSidebar.jsx
  frontend/src/metabase/visualizations/components/ChartSettings.jsx
  frontend/src/metabase/visualizations/components/ChartSettings.styled.tsx
  frontend/src/metabase/visualizations/components/ChartSettingsWidget.styled.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingColumnEditor.styled.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingColumnEditor.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldPicker.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPicker.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingOrderedColumns.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingOrderedItems.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingOrderedSimple.styled.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingOrderedSimple.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingsListColumns/ChartSettingsListColumns.tsx
  frontend/src/metabase/visualizations/components/settings/ColumnItem.jsx
  frontend/src/metabase/visualizations/components/settings/ColumnItem.styled.tsx
  frontend/src/metabase/visualizations/lib/settings.js
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/src/metabase/visualizations/lib/settings/visualization.js
  frontend/src/metabase/visualizations/visualizations/ObjectDetail.jsx
  frontend/src/metabase/visualizations/visualizations/Table.jsx
  frontend/test/__support__/e2e/helpers/e2e-ui-elements-helpers.js
  frontend/test/metabase/scenarios/binning/binning-reproductions.cy.spec.js
  frontend/test/metabase/scenarios/native/native.cy.spec.js
  frontend/test/metabase/scenarios/native/reproductions/16914.cy.spec.js
  frontend/test/metabase/scenarios/permissions/sandboxes.cy.spec.js
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
  frontend/test/metabase/scenarios/question/reproductions/17514-ui-overlay.cy.spec.js
  frontend/test/metabase/scenarios/question/settings.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/22206-add-remove-column.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/28304-table-columns-unknown.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/reproductions/28311-sorting-table-columns.cy.spec.js
  frontend/test/metabase/scenarios/visualizations/table.cy.spec.js
  frontend/test/metabase/visualizations/components/settings/ChartSettingColumnEditor.unit.spec.js
  frontend/test/metabase/visualizations/components/settings/ChartSettingOrderedColumns.unit.spec.js
  frontend/test/metabase/visualizations/components/settings/ChartSettingOrderedSimple.unit.spec.js
Labels: .Blocker

#28728 Adding flex grow to card wrapper
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
  frontend/test/metabase/scenarios/question/notebook.cy.spec.js
Labels: support/Repro

#28748 Disable basic actions for unsupported models
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase/models/components/ModelDetailPage/ModelActionDetails/ModelActionDetails.tsx
  frontend/src/metabase/models/containers/ModelDetailPage/ModelDetailPage.unit.spec.tsx
  frontend/test/metabase-lib/lib/Question.unit.spec.js
Labels: .Blocker

#28730 [Docs] Fix typo in basic actions
  docs/actions/basic.md
Labels: Type:Documentation

#28595 Env var to control retention of `query_execution` data
  enterprise/backend/src/metabase_enterprise/task/truncate_audit_log.clj
  enterprise/backend/test/metabase_enterprise/task/truncate_audit_log_test.clj
  src/metabase/task/truncate_audit_log.clj
  src/metabase/task/truncate_audit_log/interface.clj
  test/metabase/task/truncate_audit_log_test.clj
Labels: backport
