Repository metabase/metabase, pull requests merged in 2024-03, with the labels that each got.

#39294 Revert "Fix missing result metadata (#39201)"
  frontend/src/metabase/query_builder/actions/core/core.js
  frontend/src/metabase/query_builder/actions/querying.js
Labels: no-backport, .Team/QueryingComponents

#39293 Revert "Fix missing result metadata (#39243)"
  frontend/src/metabase/query_builder/actions/core/core.js
  frontend/src/metabase/query_builder/actions/querying.js
Labels: no-backport, .Team/QueryingComponents

#39440 hide error when the user changes the token
  frontend/src/metabase/setup/components/LicenseTokenStep/LicenseTokenForm.tsx
  frontend/src/metabase/setup/tests/enterprise.unit.spec.tsx
Labels: .Team/Embedding

#39441 Optimize some parts of Notebook editor
  frontend/src/metabase/query_builder/components/notebook/NotebookSteps/NotebookSteps.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/use-join-condition.ts
  frontend/src/metabase/query_builder/components/view/View.jsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/ViewHeader.jsx
Labels: no-backport, .Team/QueryingComponents

#39443 keep token visible when going back
  frontend/src/metabase/setup/components/LicenseTokenStep/LicenseTokenForm.tsx
  frontend/src/metabase/setup/components/LicenseTokenStep/LicenseTokenStep.tsx
  frontend/src/metabase/setup/tests/enterprise.unit.spec.tsx
Labels: .Team/Embedding

#39359 Use `updateUserSetting` for user-local settings
  frontend/src/metabase/browse/components/ModelExplanationBanner.tsx
  frontend/src/metabase/home/components/HomePage/HomePage.tsx
Labels: no-backport, .Team/QueryingComponents

#39430 Notify slack on cross-version test failure
  .github/workflows/e2e-cross-version.yml
Labels: no-backport, .Team/AdminWebapp

#39418 Move jetty timeout default to metabase.config
  src/metabase/config.clj
  src/metabase/server.clj
Labels: no-backport, .Team/BackendComponents

#39422 Update various TODO comments
  src/metabase/email/messages.clj
  src/metabase/shared/parameters/parameters.cljc
  src/metabase/util/malli/schema.clj
Labels: no-backport, .Team/BackendComponents

#39311 Forcefully reload table/card metadata when there are no fields (yet)
  frontend/src/metabase/entities/tables.js
  frontend/src/metabase/lib/redux/utils.js
Labels: backport, .Team/QueryingComponents

#39263 Utilize diagnoseExpression to detect expression errors
  e2e/test/scenarios/custom-column/custom-column.cy.spec.js
  frontend/src/metabase-lib/expression.ts
  frontend/src/metabase-lib/expressions/diagnostics.ts
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx
Labels: backport, .Team/QueryingComponents

#39228 docs - updates to installation
  docs/installation-and-operation/installing-metabase.md
  docs/installation-and-operation/migrating-from-h2.md
  docs/installation-and-operation/running-the-metabase-jar-file.md
  docs/installation-and-operation/start.md
Labels: Type:Documentation, backport

#39445 Fix visual glitch when dragging a dashboard tab
  frontend/src/metabase/core/components/Sortable/Sortable.tsx
Labels: backport, .Team/DashViz

#39257 License activation step - integration branch PR
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.ts
  frontend/src/metabase-types/store/setup.ts
  frontend/src/metabase/selectors/settings.ts
  frontend/src/metabase/services.js
  frontend/src/metabase/setup/actions.ts
  frontend/src/metabase/setup/analytics.ts
  frontend/src/metabase/setup/components/CloudMigrationHelp/CloudMigrationHelp.tsx
  frontend/src/metabase/setup/components/DataUsageStep/DataUsageStep.tsx
  frontend/src/metabase/setup/components/DatabaseStep/DatabaseStep.tsx
  frontend/src/metabase/setup/components/LanguageStep/LanguageStep.tsx
  frontend/src/metabase/setup/components/LicenseTokenStep/LicenseTokenForm.tsx
  frontend/src/metabase/setup/components/LicenseTokenStep/LicenseTokenStep.tsx
  frontend/src/metabase/setup/components/LicenseTokenStep/index.ts
  frontend/src/metabase/setup/components/SettingsPage/SettingsPage.tsx
  frontend/src/metabase/setup/components/UsageQuestionStep/UsageQuestionStep.tsx
  frontend/src/metabase/setup/components/UserStep/UserStep.tsx
  frontend/src/metabase/setup/components/WelcomePage/WelcomePage.tsx
  frontend/src/metabase/setup/reducers.ts
  frontend/src/metabase/setup/selectors.ts
  frontend/src/metabase/setup/tests/common.unit.spec.tsx
  frontend/src/metabase/setup/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/setup/tests/premium.unit.spec.tsx
  frontend/src/metabase/setup/tests/setup.tsx
  frontend/src/metabase/setup/types.ts
  frontend/src/metabase/setup/useStep.ts
  frontend/test/__support__/server-mocks/setup.ts
  snowplow/iglu-client-embedded/schemas/com.metabase/setup/jsonschema/1-0-3
  src/metabase/api/setup.clj
  test/metabase/api/setup_test.clj
Labels: no-backport

#39444 Fix dashboard tabs drop animation
  e2e/test/scenarios/dashboard/tabs.cy.spec.js
  frontend/src/metabase/core/components/Sortable/Sortable.tsx
Labels: backport, .Team/DashViz

#39283 Fix snowflake ssh tunnel
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  src/metabase/util/ssh.clj
  test/metabase/driver/sql_jdbc/connection_test.clj
  test/metabase/util/ssh_test.clj
Labels: backport, .Team/QueryProcessor

#39456 Differentiate `UserSettings` type from the rest of the `Settings`
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/redux/settings.ts
Labels: no-backport, .Team/QueryingComponents

#39319 Fix click behavior when routing to a different tab on the same dashboard
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  frontend/src/metabase-lib/queries/drills/dashboard-click-drill.js
  frontend/src/metabase/visualizations/click-actions/actions/DashboardClickAction.tsx
Labels: backport, Reporting/Dashboards/Click Behavior, visual, .Team/DashViz

#39457 Generate unique user name in table-privileges-test
  modules/drivers/redshift/test/metabase/driver/redshift_test.clj
Labels: backport, .Team/QueryProcessor

#39170 DB prevents creating new data permission paths
  enterprise/backend/src/metabase_enterprise/advanced_permissions/models/permissions.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/models/permissions_test.clj
  resources/migrations/001_update_migrations.yaml
  resources/migrations/permissions/mariadb_enforce_no_data_permissions_on_create.sql
  resources/migrations/permissions/mysql_create_drop_constraint_if_exists_procedure.sql
  src/metabase/api/permissions.clj
  src/metabase/models/permissions.clj
  src/metabase/models/permissions/parse.clj
  src/metabase/permissions/util.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/db/schema_migrations_test.clj
  test/metabase/permissions/util_test.clj
Labels: .Team/AdminWebapp

#39365 fix viz breaking when switching to funnel
  frontend/src/metabase/visualizations/components/FunnelNormal.jsx
Labels: visual, .Team/DashViz

#39154 [FIX: #39152] Public links refer to `null` when question is new
  e2e/test/scenarios/sharing/public-sharing-embed-button-behavior.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/pivot_tables.cy.spec.js
  frontend/src/metabase/dashboard/components/DashboardEmbedHeaderButton/DashboardEmbedHeaderButton.tsx
  frontend/src/metabase/dashboard/components/DashboardEmbedHeaderButton/index.ts
  frontend/src/metabase/dashboard/components/EmbedMenu/AdminEmbedMenu.tsx
  frontend/src/metabase/dashboard/components/EmbedMenu/AdminEmbedMenu.unit.spec.tsx
  frontend/src/metabase/dashboard/components/EmbedMenu/NonAdminEmbedMenu.tsx
  frontend/src/metabase/public/components/ResourceEmbedButton/ResourceEmbedButton.tsx
  frontend/src/metabase/public/components/ResourceEmbedButton/ResourceEmbedButton.unit.spec.tsx
  frontend/src/metabase/public/components/ResourceEmbedButton/index.ts
  frontend/src/metabase/query_builder/components/QueryModals.tsx
  frontend/src/metabase/query_builder/components/view/ViewFooter.jsx
Labels: backport, .Team/Embedding

#39442 Repro #34688 and #34690 - Time series footer
  e2e/test/scenarios/binning/reproductions/34688-34690-time-series-footer.cy.spec.js
Labels: backport, .Team/QueryingComponents

#39464 Convert `dashboard/actions/core` to TypeScript
  frontend/src/metabase-types/api/dashboard.ts
  frontend/src/metabase-types/api/mocks/dashboard.ts
  frontend/src/metabase/dashboard/actions/actions.ts
  frontend/src/metabase/dashboard/actions/auto-wire-parameters/toasts.ts
  frontend/src/metabase/dashboard/actions/auto-wire-parameters/utils.ts
  frontend/src/metabase/dashboard/actions/core.ts
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx
Labels: backport, .Team/DashViz

#39472 Replace `dashboard.isEditing` state with `dashboard.editingDashboard`
  frontend/src/metabase-types/store/dashboard.ts
  frontend/src/metabase-types/store/mocks/dashboard.ts
  frontend/src/metabase/dashboard/actions/actions.ts
  frontend/src/metabase/dashboard/actions/actions.unit.spec.js
  frontend/src/metabase/dashboard/actions/cards.unit.spec.ts
  frontend/src/metabase/dashboard/actions/core.ts
  frontend/src/metabase/dashboard/actions/save.js
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.tsx
  frontend/src/metabase/dashboard/constants.ts
  frontend/src/metabase/dashboard/reducers.js
  frontend/src/metabase/dashboard/reducers.unit.spec.js
  frontend/src/metabase/dashboard/selectors.ts
Labels: backport, .Team/DashViz

#39505 Optimize data step in the notebook editor
  frontend/src/metabase/common/components/FieldPicker/FieldPicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/DataStep/DataStep.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/DataStep/DataStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTablePicker/JoinTablePicker.tsx
Labels: backport, .Team/QueryingComponents

#39500 Repro #30312 - Cannot filter directly from table column header when Question is Summarized
  e2e/test/scenarios/filters/reproductions/30312-drill-filter-on-aggregated-column.cy.spec.js
Labels: backport, .Team/QueryingComponents

#39512 Use arrow functions in e2e & unit tests definitions
  e2e/test/scenarios/collections/reproductions/30235-turn-official-after-move.cy.spec.js
  e2e/test/scenarios/filters/reproductions/31340-long-column-name-search-results.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/drillthroughs/table_drills.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/37726-pivot-table-add-column.cy.spec.js
  frontend/src/metabase/admin/permissions/components/DataPermissionsHelp/DataPermissionsHelp.unit.spec.tsx
  frontend/src/metabase/admin/permissions/test/DatabasesPermissionsPage/DatabasesPermissionsPage.unit.spec.tsx
  frontend/src/metabase/admin/permissions/test/GroupsPermissionsPage/GroupsPermissionsPage.unit.spec.tsx
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.unit.spec.tsx
Labels: no-backport, .Team/QueryingComponents

#39502 Repro #29094 - Notebook filter field allows non boolean custom expressions
  e2e/test/scenarios/filters/reproductions/29094-non-boolean-custom-expressions.cy.spec.js
Labels: no-backport, .Team/QueryingComponents

#39510 Repro #23851 - Drill-through on a timestamp column binned as XofY fails unless sematic type is defined
  e2e/test/scenarios/binning/reproductions/23851-drill-temporal-extraction.cy.spec.js
Labels: backport, .Team/QueryingComponents

#39517 Remove broken field ref comparison with QP columns
  frontend/src/metabase-lib/comparison.ts
  frontend/src/metabase-lib/comparison.unit.spec.ts
Labels: no-backport, .Team/QueryingComponents

#39010 [serdes-v1] can now dump/load entity_id
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/src/metabase_enterprise/serialization/serialize.clj
  enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj
  src/metabase/cmd.clj
Labels: backport, .Team/BackendComponents

#39255 [QP] Fix confusion of expressions with the same name as columns
  modules/drivers/sqlite/test/metabase/driver/sqlite_test.clj
  src/metabase/lib/expression.cljc
  src/metabase/query_processor/util/add_alias_info.clj
  src/metabase/query_processor/util/nest_query.clj
  test/metabase/driver/sql/query_processor_test.clj
  test/metabase/lib/expression_test.cljc
  test/metabase/query_processor/util/add_alias_info_test.clj
  test/metabase/query_processor/util/nest_query_test.clj
Labels: backport

#38959 Fix mongo password handling
  modules/drivers/mongo/src/metabase/driver/mongo/connection.clj
  modules/drivers/mongo/test/metabase/driver/mongo/connection_test.clj
Labels: Database/Mongo, backport, .Team/QueryProcessor

#39518 Prevent custom expressions from being removed from the query
  e2e/test/scenarios/visualizations-tabular/table-column-settings.cy.spec.js
  frontend/src/metabase/querying/components/FieldPanel/FieldPanel.unit.spec.tsx
  frontend/src/metabase/querying/components/FieldPanel/utils.ts
Labels: backport, .Team/QueryingComponents

#39522 Don't send release reminders on weekends
  .github/workflows/release-status.yml
Labels: no-backport, .Team/AdminWebapp

#39467 Add build start slack message
  .github/workflows/build-for-release.yml
  release/src/slack.ts
  release/src/version-helpers.ts
  release/src/version-helpers.unit.spec.ts
Labels: .Building & Releasing, no-backport, .Team/AdminWebapp

#39446 [QP] Use the alias for unfolded JSON columns from previous stages
  src/metabase/driver/postgres.clj
  test/metabase/driver/postgres_test.clj
Labels: backport, .Team/QueryProcessor

#39269 Do not return value if the database id used for `last-used-native-database-id` does not exist (anymore)
  src/metabase/models/user.clj
  test/metabase/models/user_test.clj
Labels: no-backport, .Team/QueryingComponents

#39425 Remove TODOs
  src/metabase/core.clj
  src/metabase/mbql/normalize.cljc
  src/metabase/mbql/schema.cljc
  src/metabase/mbql/util/match/impl.cljc
  src/metabase/pulse/util.clj
  src/metabase/util.cljc
Labels: visual, no-backport, .Team/BackendComponents

#39466 Additional X-Ray Documentation
  src/metabase/automagic_dashboards/core.clj
Labels: backport, .Team/DashViz

#39535 [backport] [serdes-v1] can now dump/load entity_id
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/src/metabase_enterprise/serialization/serialize.clj
  enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj
  src/metabase/cmd.clj
Labels: .Team/BackendComponents, was-backported

#39529 [MLv2] `joinable-columns` on a Join sets source and alias
  src/metabase/lib/join.cljc
  test/metabase/lib/join_test.cljc
Labels: backport, .Team/QueryProcessor

#38873 Add the ability to copy required checks from `master` to any existing branch
  release/README.md
  release/package.json
  release/src/required-checks.ts
Labels: no-backport, .Team/QueryingComponents

#39480 Enterprise api calls cleanup
  enterprise/frontend/src/metabase-enterprise/advanced_permissions/components/ImpersonationModal/ImpersonationModal.tsx
  enterprise/frontend/src/metabase-enterprise/audit_app/containers/UnsubscribeUserModal/UnsubscribeUserModal.jsx
  enterprise/frontend/src/metabase-enterprise/audit_app/lib/services.js
  enterprise/frontend/src/metabase-enterprise/audit_app/reducer.ts
  enterprise/frontend/src/metabase-enterprise/llm_autodescription/LLMSuggestQuestionInfo.tsx
  enterprise/frontend/src/metabase-enterprise/services.ts
Labels: Misc/API, no-backport, .Team/AdminWebapp

#39469 Move user-local settings to user model
  src/metabase/models/user.clj
  src/metabase/public_settings.clj
Labels: .Backend, no-backport, .Team/QueryingComponents

#39537 Fix query builder query string parsing
  frontend/src/metabase/query_builder/utils.ts
Labels: backport, .Team/DashViz

#39573 docs - add 48.8 to release list
  docs/releases.md
Labels: Type:Documentation, backport

#39563 Generate unique user name in table-privileges-test (#39457)
  modules/drivers/redshift/test/metabase/driver/redshift_test.clj
Labels: .Team/QueryProcessor

#39566 Fix cursor in notebook editor
  frontend/src/metabase/query_builder/components/notebook/NotebookCell/NotebookCell.styled.tsx
Labels: backport, .Team/QueryingComponents

#39235 No more Schema, only Malli (finish the migration)
  deps.edn
  enterprise/backend/src/metabase_enterprise/sso/integrations/saml.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/sso_settings.clj
  enterprise/backend/test/metabase_enterprise/advanced_config/file/settings_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/test_util.clj
  modules/drivers/druid/src/metabase/driver/druid/execute.clj
  modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/query_processor.clj
  src/metabase/api/public.clj
  src/metabase/api/session.clj
  src/metabase/automagic_dashboards/core.clj
  src/metabase/automagic_dashboards/dashboard_templates.clj
  src/metabase/automagic_dashboards/util.clj
  src/metabase/cmd/copy.clj
  src/metabase/db/connection_pool_setup.clj
  src/metabase/db/custom_migrations.clj
  src/metabase/domain_entities/core.clj
  src/metabase/domain_entities/specs.clj
  src/metabase/driver/common.clj
  src/metabase/driver/common/parameters/operators.clj
  src/metabase/driver/common/parameters/parse.clj
  src/metabase/driver/impl.clj
  src/metabase/driver/sql_jdbc/actions.clj
  src/metabase/formatter.clj
  src/metabase/mbql/schema.cljc
  src/metabase/models/card.clj
  src/metabase/models/dispatch.clj
  src/metabase/models/humanization.clj
  src/metabase/models/interface.clj
  src/metabase/models/moderation_review.clj
  src/metabase/models/pulse_channel.clj
  src/metabase/models/session.clj
  src/metabase/models/setting.clj
  src/metabase/plugins/initialize.clj
  src/metabase/pulse/render.clj
  src/metabase/pulse/render/body.clj
  src/metabase/pulse/render/color.clj
  src/metabase/pulse/render/png.clj
  src/metabase/query_processor/middleware/catch_exceptions.clj
  src/metabase/related.clj
  src/metabase/server/middleware/session.clj
  src/metabase/transforms/core.clj
  src/metabase/transforms/specs.clj
  src/metabase/util.cljc
  src/metabase/util/date_2/parse.clj
  src/metabase/util/i18n.clj
  src/metabase/util/schema.clj
  test/metabase/api/action_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/automagic_dashboards/dashboard_templates_test.clj
  test/metabase/domain_entities/specs_test.clj
  test/metabase/pulse/render/body_test.clj
  test/metabase/pulse/render/test_util.clj
  test/metabase/query_processor_test/expression_aggregations_test.clj
  test/metabase/sync/analyze/fingerprint/fingerprinters_test.clj
  test/metabase/test/data/users.clj
  test/metabase/test/domain_entities.clj
  test/metabase/test/transforms.clj
  test/metabase/test/util/log.clj
  test/metabase/transforms/specs_test.clj
Labels: .Team/QueryProcessor, no-backport

#39509 Optimize join step
  frontend/src/metabase/common/components/FieldPicker/FieldPicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTablePicker/JoinTablePicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/use-join.ts
Labels: backport, .Team/QueryingComponents

#39533 Update dashboard sections menu
  e2e/test/scenarios/dashboard-cards/dashboard-sections.cy.spec.js
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.styled.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/SectionLayoutPreview.tsx
Labels: backport, .Team/DashViz

#39539 HK: Translate parameter values to TS
  frontend/src/metabase/parameters/utils/parameter-values.ts
  frontend/src/metabase/query_builder/actions/core/parameterUtils.ts
Labels: no-backport, :broom:, .Team/QueryingComponents

#39552 backported "[QP] Fix confusion of expressions with the same name as columns"
  modules/drivers/sqlite/test/metabase/driver/sqlite_test.clj
  src/metabase/lib/expression.cljc
  src/metabase/query_processor/util/add_alias_info.clj
  src/metabase/query_processor/util/nest_query.clj
  test/metabase/driver/sql/query_processor_test.clj
  test/metabase/lib/expression_test.cljc
  test/metabase/query_processor/util/add_alias_info_test.clj
  test/metabase/query_processor/util/nest_query_test.clj
Labels: .Team/QueryProcessor, was-backported

#39623 Introduce describeWithSnowplowEE
  e2e/support/helpers/e2e-snowplow-helpers.js
  e2e/test/scenarios/onboarding/home/browse.cy.spec.js
Labels: no-backport, .Team/QueryingComponents

#39626 Backport #39623 - Introduce describeWithSnowplowEE
  e2e/support/helpers/e2e-snowplow-helpers.js
  e2e/test/scenarios/onboarding/home/browse.cy.spec.js
Labels: .Team/QueryingComponents, was-backported

#39636 include clj-memory-meter in :dev alias
  deps.edn
Labels: no-backport, .Team/BackendComponents

#39625 Update text for visualisation loading state
  frontend/src/metabase/visualizations/components/Visualization/LoadingView/LoadingView.tsx
  frontend/src/metabase/visualizations/components/Visualization/LoadingView/LoadingView.unit.spec.tsx
Labels: backport, visual, .Team/QueryingComponents

#39589 Dont alert slack on failing backport branches
  .github/workflows/rerun-workflows.yml
Labels: .CI & Tests, no-backport, .Team/AdminWebapp

#39473 Fix errors happening after canceling a new dashboard tab creation
  e2e/test/scenarios/dashboard/tabs.cy.spec.js
  frontend/src/metabase/dashboard/actions/core.ts
  frontend/src/metabase/dashboard/actions/tabs.ts
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.tsx
Labels: backport, .Team/DashViz

#39640 Don't provision SSO users before the instance has been setup
  src/metabase/models/user.clj
  src/metabase/setup.clj
  test/metabase/models/user_test.clj
Labels: backport, .Team/AdminWebapp

#39484 fix funnel bar breaking in app
  frontend/src/metabase/visualizations/visualizations/Funnel/funnel-bar-transform.ts
Labels: visual, .Team/DashViz

#39642 backport "[QP] Use the alias for unfolded JSON columns from previous stages (#39446)" to 48
  src/metabase/driver/postgres.clj
  test/metabase/driver/postgres_test.clj
Labels: .Team/QueryProcessor, was-backported

#39632 Deduplicate some packages
  frontend/src/metabase/core/components/Link/Link.styled.tsx
  frontend/src/metabase/search/components/SearchResult/SearchResult.styled.tsx
  yarn.lock
Labels: no-backport, .Team/QueryingComponents

#39647 fix stacking in app
  frontend/src/metabase/visualizations/lib/settings/graph.js
Labels: visual, .Team/DashViz

#39569 Fix click behavior not working for pivot table header cells and tables pivoted (pivoted column cells)
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  frontend/src/metabase/lib/data_grid.js
  frontend/src/metabase/visualizations/lib/table.js
Labels: Visualization/Tables, support/Repro, backport, Reporting/Dashboards/Click Behavior, visual, .Team/DashViz

#39630 Tighten updateable columns of sync classify step
  src/metabase/sync/analyze/classify.clj
Labels: no-backport, .Team/BackendComponents

#39673 Fix mistake in API changelog: type can be "question" not "query"
  docs/developers-guide/api-changelog.md
Labels: backport, .Team/BackendComponents

#39308 Table info hovercard
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/joins/reproductions/23293-drill-through-implicit-join-add-remove-column.cy.spec.js
  e2e/test/scenarios/question/new.cy.spec.js
  e2e/test/scenarios/question/notebook.cy.spec.js
  e2e/test/scenarios/question/saved.cy.spec.js
  e2e/test/scenarios/sharing/public-sharing-embed-button-behavior.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/table.cy.spec.js
  frontend/src/metabase/components/MetadataInfo/ColumnInfoIcon/ColumnInfoIcon.tsx
  frontend/src/metabase/components/MetadataInfo/ColumnInfoPopover/ColumnInfoPopover.tsx
  frontend/src/metabase/components/MetadataInfo/InfoIcon/InfoIcon.styled.tsx
  frontend/src/metabase/components/MetadataInfo/InfoIcon/index.tsx
  frontend/src/metabase/components/MetadataInfo/MetadataInfo.styled.tsx
  frontend/src/metabase/components/MetadataInfo/Popover/Popover.styled.tsx
  frontend/src/metabase/components/MetadataInfo/Popover/Popover.tsx
  frontend/src/metabase/components/MetadataInfo/Popover/index.tsx
  frontend/src/metabase/components/MetadataInfo/TableInfo/TableInfo.styled.tsx
  frontend/src/metabase/components/MetadataInfo/TableInfo/TableInfo.tsx
  frontend/src/metabase/components/MetadataInfo/TableInfo/index.ts
  frontend/src/metabase/components/MetadataInfo/TableInfoIcon/TableInfoIcon.tsx
  frontend/src/metabase/components/MetadataInfo/TableInfoIcon/TableInfoIcon.unit.spec.tsx
  frontend/src/metabase/components/MetadataInfo/TableInfoPopover/TableInfoPopover.styled.tsx
  frontend/src/metabase/components/MetadataInfo/TableInfoPopover/TableInfoPopover.tsx
  frontend/src/metabase/components/MetadataInfo/TableInfoPopover/index.ts
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorTablePicker/DataSelectorTablePicker.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorTablePicker/DataSelectorTablePicker.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/QuestionDataSource.jsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/QuestionDataSource.styled.tsx
Labels: .Team/QueryingComponents

#39633 Join performance issues
  e2e/test/scenarios/joins/joins.cy.spec.js
  frontend/src/metabase-lib/join.ts
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/Join/Join.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/Join/Join.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/Join/index.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinCondition/JoinCondition.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinCondition/JoinCondition.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinCondition/index.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionColumnPicker/JoinConditionColumnPicker.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionColumnPicker/JoinConditionColumnPicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionDraft/JoinConditionDraft.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionDraft/JoinConditionDraft.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionDraft/index.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionDraft/utils.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionOperatorPicker/JoinConditionOperatorPicker.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionOperatorPicker/JoinConditionOperatorPicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionRemoveButton/JoinConditionRemoveButton.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionRemoveButton/JoinConditionRemoveButton.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinConditionRemoveButton/index.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinDraft/JoinDraft.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinDraft/JoinDraft.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinDraft/index.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinDraft/utils.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStrategyPicker/JoinStrategyPicker.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStrategyPicker/JoinStrategyPicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTableColumnDraftPicker/JoinTableColumnDraftPicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTableColumnDraftPicker/index.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTableColumnPicker/JoinTableColumnPicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTableColumnPicker/index.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTablePicker/JoinTablePicker.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTablePicker/JoinTablePicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/use-join-condition.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/use-join.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/utils.ts
Labels: backport, .Team/QueryingComponents

#39675 Refactor `cy.updatePermissionsGraph`, `cy.updatePermissionsSchemas` & `cy.updateCollectionGraph` to TypeScript
  e2e/support/commands/permissions/updatePermissions.js
  e2e/support/commands/permissions/updatePermissions.ts
Labels: no-backport, .Team/QueryingComponents

#39659 Remove unused shallowEqual file
  frontend/src/metabase/selectors/shallowEqual.js
Labels: no-backport, .Team/QueryingComponents

#39648 Scroll dashboard tabs to the end when adding a tab
  frontend/src/metabase/core/components/TabRow/TabRow.tsx
Labels: backport, .Team/DashViz

#39678 Fix dev/pprint-sql
  dev/src/dev/debug_qp.clj
Labels: no-backport, .Team/BackendComponents

#39629 Repro #11994 - Clicking RawData-toggle on pivoted table makes the question dirty and shows Save-button
  e2e/test/scenarios/permissions/reproductions/11994-dirty-question.cy.spec.ts
Labels: backport, .Team/QueryingComponents

#39576 Fail number parsing if it is only a substring
  src/metabase/upload/parsing.clj
  test/metabase/upload_test.clj
Labels: backport, .Team/BackendComponents

#39652 Fix field-vales query to specify :full type
  src/metabase/models/table.clj
Labels: backport, .Team/BackendComponents

#39680 Add stylelint
  .stylelintrc.json
  enterprise/frontend/src/metabase-enterprise/llm_autodescription/loading.css
  frontend/src/metabase/components/Breadcrumbs/Breadcrumbs.module.css
  frontend/src/metabase/components/Calendar/Calendar.module.css
  frontend/src/metabase/components/List/List.module.css
  frontend/src/metabase/components/Popover/Popover.module.css
  frontend/src/metabase/components/Sidebar.module.css
  frontend/src/metabase/containers/SaveQuestionModal.module.css
  frontend/src/metabase/css/admin.module.css
  frontend/src/metabase/css/components/buttons.module.css
  frontend/src/metabase/css/components/form.module.css
  frontend/src/metabase/css/components/grabber.module.css
  frontend/src/metabase/css/components/list.module.css
  frontend/src/metabase/css/components/modal.module.css
  frontend/src/metabase/css/core/animation.module.css
  frontend/src/metabase/css/core/arrow.module.css
  frontend/src/metabase/css/core/base.module.css
  frontend/src/metabase/css/core/breakpoints.module.css
  frontend/src/metabase/css/core/clearfix.module.css
  frontend/src/metabase/css/core/colors.module.css
  frontend/src/metabase/css/core/float.module.css
  frontend/src/metabase/css/core/fonts.module.css
  frontend/src/metabase/css/core/grid.module.css
  frontend/src/metabase/css/core/headings.module.css
  frontend/src/metabase/css/core/hide.module.css
  frontend/src/metabase/css/core/layout.module.css
  frontend/src/metabase/css/core/scroll.module.css
  frontend/src/metabase/css/core/shadow.module.css
  frontend/src/metabase/css/core/spacing.module.css
  frontend/src/metabase/css/core/text.module.css
  frontend/src/metabase/css/dashboard.module.css
  frontend/src/metabase/css/index.module.css
  frontend/src/metabase/css/query_builder.module.css
  frontend/src/metabase/parameters/components/ParameterValueWidget.module.css
  frontend/src/metabase/reference/Reference.module.css
  frontend/src/metabase/reference/components/Formula.module.css
  frontend/src/metabase/visualizations/components/ChartWithLegend.module.css
  frontend/src/metabase/visualizations/components/LineAreaBarChart.module.css
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.module.css
  package.json
  yarn.lock
Labels: visual, no-backport, .Team/QueryingComponents

#39637 38092 metadata table columns dnd
  e2e/test/scenarios/admin/datamodel/editor.cy.spec.js
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataTableColumn/MetadataTableColumn.styled.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataTableColumnList/MetadataTableColumnList.tsx
  frontend/src/metabase/components/Grabber/Grabber.jsx
  frontend/src/metabase/core/components/Sortable/SortableList.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingOrderedItems/ChartSettingOrderedItems.tsx
Labels: backport, visual, .Team/AdminWebapp

#39716 remove mark from dashviz team
  .github/team.json
Labels: no-backport

#39718 update Admin Webapp team members
  .github/team.json
Labels: no-backport, .Team/AdminWebapp

#39661 Fix action button label cut off
  frontend/src/metabase/dashboard/components/DashCard/DashCard.styled.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
Labels: Reporting/Dashboards, backport, visual, .Team/DashViz

#39656 Fix text cutoff for error view and no results view on dash-cards
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
Labels: Reporting/Dashboards, backport, visual, .Team/DashViz

#39681 [HDS] Prep/cleanup steps for Highlighting the data source
  frontend/src/metabase/containers/DataPicker/constants.tsx
  frontend/src/metabase/containers/DataPicker/utils.ts
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityList.styled.tsx
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityList.tsx
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityPicker.jsx
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityPicker.styled.tsx
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityPicker.unit.spec.jsx
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/utils.js
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTablePicker/JoinTablePicker.tsx
Labels: .Team/QueryingComponents

#39651 Render CSV append errors as markdown
  src/metabase/upload.clj
  test/metabase/upload_test.clj
Labels: backport, .Team/BackendComponents

#39639 Remove Audit v1 Backend
  enterprise/backend/src/metabase_enterprise/audit_app/pages/alerts.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/common.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/common/card_and_dashboard_detail.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/common/cards.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/common/dashboards.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/common/pulses.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/dashboard_detail.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/dashboard_subscriptions.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/dashboards.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/database_detail.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/databases.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/downloads.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/queries.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/query_detail.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/question_detail.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/schemas.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/table_detail.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/tables.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/user_detail.clj
  enterprise/backend/src/metabase_enterprise/audit_app/pages/users.clj
  enterprise/backend/test/metabase_enterprise/audit_app/pages/alerts_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/pages/common_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/pages/dashboard_subscriptions_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/pages_test.clj
Labels: no-backport, .Team/AdminWebapp

#39559 docs - update basic exploration
  docs/exploration-and-organization/data-model-reference.md
  docs/exploration-and-organization/exploration.md
  docs/exploration-and-organization/images/browse-data.png
  docs/exploration-and-organization/images/collection-detail.png
  docs/exploration-and-organization/images/detail-view.png
  docs/exploration-and-organization/images/learn-about-our-data.png
  docs/exploration-and-organization/images/only-verified-models.png
  docs/exploration-and-organization/images/search-results.png
Labels: Type:Documentation, backport

#39712 Disable animation on NewItemMenu
  frontend/src/metabase/components/EntityMenu/EntityMenu.jsx
  frontend/src/metabase/components/NewItemMenu/NewItemMenu.tsx
  frontend/src/metabase/nav/components/ProfileLink/ProfileLink.jsx
Labels: no-backport, .Team/AdminWebapp

#39692 Repro #39508 - Query builder silently fails on duplicate custom column names
  frontend/src/metabase/query_builder/components/notebook/steps/ExpressionStep.unit.spec.tsx
Labels: backport, .Team/QueryingComponents

#39695 Cache can-run
  src/metabase/lib/js.cljs
Labels: backport, .Team/QueryingComponents

#39454 ParameterValuePicker: use in Native queries for single strings, numbers, and dates
  e2e/test/scenarios/native-filters/reproductions/31606.cy.spec.js
  e2e/test/scenarios/native-filters/sql-field-filter-date.cy.spec.js
  e2e/test/scenarios/native-filters/sql-field-filter-number.cy.spec.js
  e2e/test/scenarios/native-filters/sql-field-filter-string.cy.spec.js
  e2e/test/scenarios/native-filters/sql-field-filter.cy.spec.js
  e2e/test/scenarios/native-filters/sql-filters.cy.spec.js
  frontend/src/metabase-lib/parameters/utils/parameter-type.ts
  frontend/src/metabase-lib/parameters/utils/template-tags.ts
  frontend/src/metabase-types/api/dataset.ts
  frontend/src/metabase/components/DateMonthYearWidget/DateMonthYearWidget.stories.tsx
  frontend/src/metabase/components/DateMonthYearWidget/DateMonthYearWidget.tsx
  frontend/src/metabase/components/DateMonthYearWidget/DateMonthYearWidget.unit.spec.tsx
  frontend/src/metabase/components/DateMonthYearWidget/index.ts
  frontend/src/metabase/components/DateQuarterYearWidget/DateQuarterYearWidget.stories.tsx
  frontend/src/metabase/components/DateQuarterYearWidget/DateQuarterYearWidget.tsx
  frontend/src/metabase/components/DateQuarterYearWidget/DateQuarterYearWidget.unit.spec.tsx
  frontend/src/metabase/components/DateQuarterYearWidget/index.ts
  frontend/src/metabase/components/DateRelativeWidget/DateRelativeWidget.stories.tsx
  frontend/src/metabase/components/DateRelativeWidget/DateRelativeWidget.tsx
  frontend/src/metabase/components/DateRelativeWidget/DateRelativeWidget.unit.spec.tsx
  frontend/src/metabase/components/DateRelativeWidget/index.ts
  frontend/src/metabase/parameters/components/ParameterValuePicker/OwnDatePicker.tsx
  frontend/src/metabase/parameters/components/ParameterValuePicker/ParameterValuePicker.styled.tsx
  frontend/src/metabase/parameters/components/ParameterValuePicker/ParameterValuePicker.tsx
  frontend/src/metabase/parameters/components/ParameterValuePicker/PlainValueInput.tsx
  frontend/src/metabase/parameters/components/ParameterValuePicker/core.ts
  frontend/src/metabase/parameters/components/ParameterValuePicker/index.tsx
  frontend/src/metabase/parameters/components/ParameterValueWidget.jsx
  frontend/src/metabase/query_builder/actions/core/updateQuestion.ts
  frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.tsx
  frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.unit.spec.tsx
  frontend/src/metabase/query_builder/components/template_tags/TagEditorParamParts/DefaultRequiredValueControl.tsx
  frontend/src/metabase/query_builder/components/template_tags/TagEditorParamParts/FilterWidgetTypeSelect.tsx
  frontend/src/metabase/query_builder/components/template_tags/TagEditorParamParts/VariableTypeSelect.tsx
Labels: no-backport, .Team/QueryingComponents

#39682 Cache `fromLegacyQuery` calls
  frontend/src/metabase-lib/metadata.unit.spec.ts
  frontend/src/metabase-lib/query.ts
  frontend/src/metabase-lib/query.unit.spec.ts
  src/metabase/lib/cache.cljc
  src/metabase/lib/js.cljs
Labels: backport, .Team/QueryingComponents

#39755 Show "Bookmark" before "Archive" in entity menus
  frontend/src/metabase/components/EntityItem/EntityItem.jsx
Labels: backport, .Team/DashViz

#39757 Fix unresponsive dashboard header button
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.tsx
Labels: backport, .Team/DashViz

#39752 Fix invisible chart legend dots when printing
  frontend/src/metabase/visualizations/components/legend/LegendItem.styled.tsx
Labels: backport, visual, .Team/DashViz

#39729 Remove react-motion - Bulk Actions
  e2e/test/scenarios/collections/collections.cy.spec.js
  frontend/src/metabase/archive/containers/ArchiveApp.tsx
  frontend/src/metabase/collections/components/BulkActions.jsx
  frontend/src/metabase/collections/components/BulkActions.styled.tsx
  frontend/src/metabase/components/BulkActionBar/BulkActionBar.tsx
  frontend/src/metabase/components/BulkActionBar/index.tsx
  frontend/src/metabase/ui/components/utils/Transition/index.ts
  frontend/src/metabase/ui/components/utils/index.ts
Labels: backport, .Team/AdminWebapp

#39717 using CSS animations for notebook previews
  frontend/src/metabase/query_builder/components/notebook/NotebookStepPreview.jsx
Labels: backport, .Team/AdminWebapp

#39762 Make tabs e2e test stable again
  e2e/test/scenarios/dashboard/tabs.cy.spec.js
Labels: backport, .Team/QueryingComponents

#39734 Define PrivilegedSettings type
  frontend/src/metabase-types/api/settings.ts
Labels: no-backport, .Team/QueryingComponents

#39162 "Extract column" drill thru
  e2e/test/scenarios/visualizations-tabular/table.cy.spec.js
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/querying/utils/drills/column-extract-drill/column-extract-drill.tsx
  frontend/src/metabase/querying/utils/drills/column-extract-drill/index.ts
  frontend/src/metabase/querying/utils/drills/constants.ts
  frontend/src/metabase/ui/components/icons/Icon/icons/extract.svg
  frontend/src/metabase/ui/components/icons/Icon/icons/index.ts
  frontend/src/metabase/visualizations/components/ClickActions/ClickActionsViewSection.tsx
  frontend/src/metabase/visualizations/components/ClickActions/utils.ts
  frontend/src/metabase/visualizations/types/click-actions.ts
  src/metabase/lib/drill_thru.cljc
  src/metabase/lib/drill_thru/column_extract.cljc
  src/metabase/lib/drill_thru/column_filter.cljc
  src/metabase/lib/drill_thru/quick_filter.cljc
  src/metabase/lib/expression.cljc
  src/metabase/lib/schema/drill_thru.cljc
  src/metabase/shared/util/internal/time.clj
  src/metabase/shared/util/internal/time.cljs
  test/metabase/lib/drill_thru/column_extract_test.cljc
  test/metabase/lib/drill_thru/quick_filter_test.cljc
  test/metabase/lib/drill_thru_test.cljc
  test/metabase/test_runner/assert_exprs/approximately_equal_js.clj
Labels: visual, no-backport, .Team/QueryingComponents

#39792 Properly highlight models as the data source
  e2e/test/scenarios/question/reproductions/39699-notebook-data-source-models.cy.spec.js
  frontend/src/metabase/containers/DataPicker/constants.tsx
  frontend/src/metabase/containers/DataPicker/utils.ts
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityList.styled.tsx
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityList.tsx
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityPicker.jsx
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityPicker.styled.tsx
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityPicker.unit.spec.jsx
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/utils.js
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTablePicker/JoinTablePicker.tsx
Labels: backport, .Team/QueryingComponents

#39710 Dashboard width revision message should handle nil
  src/metabase/models/revision/diff.clj
  test/metabase/api/revision_test.clj
Labels: backport, .Team/DashViz

#39788 tweak default modal spacing
  frontend/src/metabase/ui/components/overlays/Modal/Modal.styled.tsx
Labels: no-backport

#39786 Remove `user-locale` from settings
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/lib/cron.ts
Labels: Type:Tech Debt, no-backport, .Team/QueryingComponents

#39785 Fix the `dismissed-custom-dashboard-toast` setting case
  frontend/src/metabase/admin/settings/selectors.js
  frontend/src/metabase/home/components/CustomHomePageModal/CustomHomePageModal.tsx
Labels: backport, .Team/QueryingComponents

#39782 Fix order of actions in question, dashboard and collection item menus
  frontend/src/metabase/components/EntityItem/EntityItem.jsx
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionActions/QuestionActions.tsx
Labels: backport, .Team/DashViz

#39806 docs - api formatting
  docs/api/action.md
  docs/api/alert.md
  docs/api/api-key.md
  docs/api/automagic-dashboards.md
  docs/api/bookmark.md
  docs/api/card.md
  docs/api/collection.md
  docs/api/dashboard.md
  docs/api/database.md
  docs/api/dataset.md
  docs/api/ee/advanced-config-logs.md
  docs/api/ee/advanced-permissions-impersonation.md
  docs/api/ee/audit-app-user.md
  docs/api/ee/content-verification-review.md
  docs/api/ee/sandbox-gtap.md
  docs/api/ee/sandbox-table.md
  docs/api/ee/sandbox-user.md
  docs/api/ee/serialization.md
  docs/api/ee/sso.md
  docs/api/email.md
  docs/api/embed.md
  docs/api/field.md
  docs/api/geojson.md
  docs/api/google.md
  docs/api/ldap.md
  docs/api/metabot.md
  docs/api/metric.md
  docs/api/model-index.md
  docs/api/native-query-snippet.md
  docs/api/notify.md
  docs/api/permissions.md
  docs/api/persist.md
  docs/api/preview-embed.md
  docs/api/public.md
  docs/api/pulse.md
  docs/api/revision.md
  docs/api/search.md
  docs/api/segment.md
  docs/api/session.md
  docs/api/setting.md
  docs/api/setup.md
  docs/api/slack.md
  docs/api/sso-saml.md
  docs/api/table.md
  docs/api/task.md
  docs/api/tiles.md
  docs/api/timeline-event.md
  docs/api/timeline.md
  docs/api/transform.md
  docs/api/user.md
  docs/api/util.md
Labels: Type:Documentation

#39796 Fix janky db refreshing
  frontend/src/metabase/browse/components/BrowseDatabases.tsx
Labels: backport, .Team/AdminWebapp

#39738 Adds property based test for `u/map-all`
  test/metabase/util_test.cljc
Labels: no-backport, .Team/AdminWebapp

#39728 Do not allow `undefined` when updating a user setting
  frontend/src/metabase/redux/settings.ts
Labels: no-backport, .Team/QueryingComponents

#39797 Remove deprecated and unused `searchTypeaheadEnabled` method
  frontend/src/metabase/lib/settings.ts
Labels: Organization/Search, .Frontend, Administration/Settings, no-backport, :broom:, .Team/QueryingComponents

#39780 Disclosure triangle and Fullpage modal transitions
  frontend/src/metabase/components/DisclosureTriangle/DisclosureTriangle.jsx
  frontend/src/metabase/components/Modal/FullPageModal.tsx
Labels: backport, .Team/AdminWebapp

#39705 Chart Settings Table Formatting DnD kit
  e2e/test/scenarios/visualizations-tabular/table.cy.spec.js
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting.unit.spec.js
  frontend/src/metabase/visualizations/visualizations/PivotTable/settings.ts
  frontend/src/metabase/visualizations/visualizations/Table.tsx
Labels: backport, visual, .Team/AdminWebapp

#39646 Cleanup css modules usage
  frontend/src/metabase/components/LabelIcon/LabelIcon.module.css
  frontend/src/metabase/components/List/List.module.css
  frontend/src/metabase/components/ListItem/ListItem.jsx
  frontend/src/metabase/components/Sidebar.module.css
  frontend/src/metabase/parameters/components/ParameterValueWidget.module.css
  frontend/src/metabase/reference/components/Detail.jsx
  frontend/src/metabase/reference/components/Field.module.css
  frontend/src/metabase/reference/components/ReferenceHeader.jsx
  frontend/src/metabase/reference/components/ReferenceHeader.module.css
  frontend/src/metabase/reference/databases/DatabaseSidebar.jsx
  frontend/src/metabase/reference/databases/FieldSidebar.jsx
  frontend/src/metabase/reference/databases/TableSidebar.jsx
  frontend/src/metabase/reference/guide/BaseSidebar.jsx
  frontend/src/metabase/reference/metrics/MetricSidebar.jsx
  frontend/src/metabase/reference/segments/SegmentFieldSidebar.jsx
  frontend/src/metabase/reference/segments/SegmentSidebar.jsx
  frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.module.css
Labels: visual, no-backport, .Team/QueryingComponents

#39766 Only return helpText for supported features
  frontend/src/metabase-lib/expressions/suggest.ts
  frontend/src/metabase-lib/expressions/suggest.unit.spec.ts
Labels: backport, .Team/QueryingComponents

#39798 Fix table columns remapped fields
  e2e/test/scenarios/question/reproductions/39795-reorder-column-field-mapping.cy.spec.js
  frontend/src/metabase-lib/Question.ts
Labels: backport, visual, .Team/QueryingComponents

#39679 Update existing foreign keys during metadata sync
  deps.edn
  modules/drivers/mongo/test/metabase/driver/mongo_test.clj
  src/metabase/sync/sync_metadata/fks.clj
  src/metabase/sync/util.clj
  test/metabase/actions/test_util.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/query_processor_test/timezones_test.clj
  test/metabase/sync/analyze_test.clj
  test/metabase/sync/sync_metadata/fields/sync_metadata_test.clj
  test/metabase/sync/sync_metadata/fields_test.clj
  test/metabase/sync_test.clj
Labels: backport, .Team/BackendComponents

#39791 Fix quick filter drill test name
  test/metabase/lib/drill_thru/quick_filter_test.cljc
Labels: no-backport, .Team/QueryingComponents

#39635 [chain filters] should not be using inactive fields for joins
  src/metabase/models/params/chain_filter.clj
  test/metabase/models/params/chain_filter_test.clj
Labels: backport, .Team/BackendComponents

#39787 Remove react motion - Undo component
  frontend/src/metabase/containers/UndoListing.jsx
Labels: backport, .Team/AdminWebapp

#39493 Convert column to float when appending floats to an integer column
  docs/developers-guide/driver-changelog.md
  src/metabase/driver.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql_jdbc.clj
  src/metabase/driver/sql_jdbc/sync.clj
  src/metabase/driver/sql_jdbc/sync/interface.clj
  src/metabase/upload.clj
  test/metabase/upload_test.clj
Labels: no-backport, .Team/BackendComponents

#39857 Bump clojure to 11.1.2
  deps.edn
Labels: backport, .Team/AdminWebapp

#39821 Publish audit logs for CSV uploads
  src/metabase/events/audit_log.clj
  src/metabase/upload.clj
  test/metabase/upload_test.clj
Labels: no-backport, .Team/BackendComponents

#39811 Adjust padding to hide scrollbars for single line text dash-cards
  frontend/src/metabase/visualizations/visualizations/Text/Text.styled.tsx
Labels: backport, visual, .Team/DashViz

#39819 Fix progress bar value display when progress card is minimum height
  frontend/src/metabase/visualizations/visualizations/Progress/Progress.jsx
Labels: Visualization/Scalars, backport, visual, .Team/DashViz

#39631 Specify GH project board per team
  .github/team.json
  .github/workflows/auto-assign.yml
Labels: backport, .Team/BackendComponents

#39278 fix missing placeholder series
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.tsx
  frontend/src/metabase/static-viz/components/ScatterPlot/ScatterPlot.tsx
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.tsx
  frontend/src/metabase/visualizations/echarts/cartesian/option/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/option/index.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/chart-definition.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-models-and-option.ts
Labels: visual, .Team/DashViz

#39669 fix waterfall series is missing on enormous datasets
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Custom_Colors.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Data_Labels.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Data_Labels_Column_Formatting.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Data_Labels_Mixed.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Data_Labels_Timeseries.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Enourmous_Dataset.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Log_Scale_With_Labels_Hour_Of_Day_X_Axis.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Mixed_Above_Zero.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Mixed_Below_Zero.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Native_Time_Series_Quarter.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Native_Time_Series_With_Gaps.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Negative_Only.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_No_Total_Ordinal.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_No_Total_Timeseries.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Ordinal_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Pow_Y_Scale.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Pow_Y_Scale_Mixed.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Pow_Y_Scale_Negative_Only.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Starts_Above_Zero_Crosses_Ends_Above.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Starts_Above_Zero_Ends_Below.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Starts_Below_Zero_Crosses_Ends_Below.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Starts_Below_Zero_Ends_Above.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Structured_Time_Series_Year.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Time_Series_Data_As_Ordinal_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Time_X_Scale_Two_Bars_Without_Total.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Timeseries_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Timeseries_X_Scale_Unsorted.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Unaggregated_Linear.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Unaggregated_Ordinal.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Unaggregated_Timeseries.png
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.stories.tsx
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/enormous-dataset.json
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/constants.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/option/index.ts
Labels: visual, .Team/DashViz

#39870 hide execution time from percy snapshots
  .percy.yml
Labels: visual, no-backport, .Team/DashViz

#39794 Using CSS transition and component for QB header
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/visualizations-tabular/table.cy.spec.js
  frontend/src/metabase/query_builder/components/view/View.jsx
Labels: backport, .Team/AdminWebapp

#39851 Fix - Description for calculated columns in model metadata editing page is incorrectly populated with description from other columns
  e2e/test/scenarios/models/reproductions/25884-34349-null-description-in-column-metadata.cy.spec.ts
  frontend/src/metabase/components/form/widgets/FormTextAreaWidget/FormTextAreaWidget.jsx
  frontend/src/metabase/query_builder/containers/test-utils.tsx
Labels: backport, .Team/QueryingComponents

#39763 Repro #35711 - Models broken with custom fields
  e2e/test/scenarios/models/reproductions/35711-metadata-in-models-with-custom-fields.cy.spec.ts
Labels: backport, .Team/QueryingComponents

#39862 Only copy active fields and tables with data/with-temp-copy-of-db
  test/metabase/test/data/impl.clj
Labels: backport, .Team/BackendComponents

#39703 Allow dropdown source for all string operators in dashboards
  e2e/test/scenarios/dashboard-filters/dashboard-filters-source.cy.spec.js
  frontend/src/metabase-lib/parameters/utils/parameter-source.ts
  frontend/src/metabase-lib/parameters/utils/parameter-source.unit.spec.ts
  frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget/ParameterFieldWidget.jsx
Labels: backport, .Team/QueryingComponents

#39664 Fix hanging cache refresh jobs
  enterprise/backend/src/metabase_enterprise/advanced_config/caching.clj
  src/metabase/models/persisted_info.clj
  test/metabase/task/persist_refresh_test.clj
Labels: no-backport, .Team/AdminWebapp

#39929 Make `update-card-with-type-and-dataset-test` not parallel
  test/metabase/api/card_test.clj
Labels: no-backport, .Team/BackendComponents

#39817 Diagnostic Information Modal
  .eslintrc
  e2e/support/commands.js
  e2e/support/commands/downloads/deleteDownloadsFolder.js
  e2e/support/commands/downloads/downloadUtils.js
  e2e/support/commands/ui/button.ts
  e2e/support/config.js
  e2e/support/cypress.js
  e2e/test/scenarios/admin-2/error-reporting.cy.spec.ts
  frontend/src/metabase-types/api/admin.ts
  frontend/src/metabase-types/api/index.ts
  frontend/src/metabase-types/api/util.ts
  frontend/src/metabase/App.tsx
  frontend/src/metabase/ErrorBoundary.tsx
  frontend/src/metabase/admin/databases/containers/DatabaseEditApp.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/SettingsEditor.jsx
  frontend/src/metabase/app.js
  frontend/src/metabase/components/ErrorPages/ErrorDiagnosticModal.tsx
  frontend/src/metabase/components/ErrorPages/ErrorDiagnosticModal.unit.spec.tsx
  frontend/src/metabase/components/ErrorPages/ErrorPages.styled.tsx
  frontend/src/metabase/components/ErrorPages/ErrorPages.tsx
  frontend/src/metabase/components/ErrorPages/index.ts
  frontend/src/metabase/components/ErrorPages/types.ts
  frontend/src/metabase/components/ErrorPages/use-error-info.ts
  frontend/src/metabase/components/ErrorPages/utils.ts
  frontend/src/metabase/components/LoadingAndGenericErrorWrapper/LoadingAndGenericErrorWrapper.jsx
  frontend/src/metabase/containers/NotFoundFallbackPage.tsx
  frontend/src/metabase/containers/Unsubscribe.tsx
  frontend/src/metabase/lib/errors/console.js
  frontend/src/metabase/lib/errors/console.unit.spec.js
  frontend/src/metabase/lib/errors/index.ts
  frontend/src/metabase/models/containers/ModelDetailPage/ModelDetailPage.tsx
  frontend/src/metabase/query_builder/containers/test-utils.tsx
  frontend/src/metabase/routes.jsx
  frontend/src/metabase/ui/components/inputs/Checkbox/Checkbox.styled.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.tsx
  package.json
  src/metabase/server/middleware/log.clj
  yarn.lock
Labels: visual, no-backport, .Team/AdminWebapp

#39853 Remove info icon on table
  e2e/test/scenarios/question/saved.cy.spec.js
  frontend/src/metabase/components/MetadataInfo/TableInfoIcon/TableInfoIcon.unit.spec.tsx
  frontend/src/metabase/components/MetadataInfo/TableInfoPopover/TableInfoPopover.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorTablePicker/DataSelectorTablePicker.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/QuestionDataSource.jsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/QuestionDataSource.unit.spec.js
Labels: no-backport, .Team/QueryingComponents

#39858 Fixes for LLM auto-description
  enterprise/backend/src/metabase_enterprise/llm/settings.clj
  enterprise/backend/test/metabase_enterprise/llm/settings_test.clj
  enterprise/frontend/src/metabase-enterprise/llm_autodescription/LLMSuggestQuestionInfo.tsx
  enterprise/frontend/src/metabase-enterprise/llm_autodescription/index.ts
  enterprise/frontend/src/metabase-enterprise/services.ts
  enterprise/frontend/src/metabase-enterprise/settings/types.ts
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/settings/selectors.js
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/plugins/types.ts
Labels: no-backport, .Team/DashViz

#39719 docs - add filter customization
  docs/questions/native-editor/sql-parameters.md
  docs/questions/native-editor/writing-sql.md
Labels: Type:Documentation, backport

#39952 do not blur timeline events when series hovered
  frontend/src/metabase/visualizations/echarts/cartesian/timeline-events/option.ts
Labels: visual, .Team/DashViz

#39876 fix multiple merged timeline events icon is not star
  frontend/src/metabase/visualizations/echarts/cartesian/timeline-events/option.ts
Labels: visual, .Team/DashViz

#39875 Clean up unused perms code
  enterprise/backend/src/metabase_enterprise/advanced_permissions/models/permissions.clj
  enterprise/backend/src/metabase_enterprise/advanced_permissions/models/permissions/application_permissions.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/models/permissions/block_permissions_test.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/models/permissions_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/permissions_test.clj
  src/metabase/api/permissions.clj
  src/metabase/models/collection/graph.clj
  src/metabase/models/data_permissions.clj
  src/metabase/models/permissions.clj
  src/metabase/models/permissions/parse.clj
  src/metabase/models/query/permissions.clj
  src/metabase/sync/sync_metadata/tables.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/native_query_snippet_test.clj
  test/metabase/models/dashboard_test.clj
  test/metabase/models/permissions/parse_test.clj
  test/metabase/models/permissions_test.clj
  test/metabase/query_processor_test/query_to_native_test.clj
  test/metabase/upload_test.clj
Labels: no-backport, .Team/AdminWebapp

#39960 remove hours of day waterfall story
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Log_Scale_With_Labels_Hour_Of_Day_X_Axis.png
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.stories.tsx
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/index.ts
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/log-scale-with-labels-hour-of-day-x-axis.json
Labels: .Team/DashViz

#39650 Update expression-parts to satisfy filter picker
  src/metabase/lib/fe_util.cljc
  src/metabase/shared/formatting/date.cljc
  src/metabase/shared/formatting/internal/date_formatters.cljc
  src/metabase/shared/util/internal/time.clj
  src/metabase/shared/util/time.cljc
  test/metabase/lib/fe_util_test.cljc
Labels: .Team/QueryProcessor, no-backport

#39816 fix combined cards drills
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/visualizations/components/ChartCaption.tsx
  frontend/src/metabase/visualizations/components/ChartTooltip/KeyValuePairChartTooltip/KeyValuePairChartTooltip.tsx
  frontend/src/metabase/visualizations/components/ChartTooltip/utils.ts
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts
  frontend/src/metabase/visualizations/types/hover.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/events.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-chart-events.ts
  frontend/src/metabase/visualizations/visualizations/Funnel/funnel-bar-transform.ts
  frontend/src/metabase/visualizations/visualizations/RowChart/RowChart.tsx
  frontend/src/metabase/visualizations/visualizations/Scalar/scalars-bar-transform.ts
Labels: visual, .Team/DashViz

#39913 Fix null ordinal value formatting
  .loki/reference/chrome_laptop_static_viz_ComboChart_Area_Fully_Null_Dimension_37902.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Fully_Null_Dimension_37902.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Line_Fully_Null_Dimension_37902.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Null_Category_Value_Formatting.png
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/null-category-value-formatting.json
  frontend/src/metabase/visualizations/echarts/cartesian/constants/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.ts
Labels: visual, .Team/DashViz

#39824 Convert QP to MLv2 Part 2
  .gitignore
  src/metabase/api/common.clj
  src/metabase/lib/card.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/limit.cljc
  src/metabase/lib/metadata.cljc
  src/metabase/lib/metadata/cached_provider.cljc
  src/metabase/lib/metadata/composed_provider.cljc
  src/metabase/lib/native.cljc
  src/metabase/lib/schema/binning.cljc
  src/metabase/lib/schema/common.cljc
  src/metabase/lib/schema/filter.cljc
  src/metabase/lib/schema/id.cljc
  src/metabase/lib/schema/metadata.cljc
  src/metabase/mbql/schema.cljc
  src/metabase/mbql/util.cljc
  src/metabase/models/data_permissions.clj
  src/metabase/models/params/chain_filter.clj
  src/metabase/models/user.clj
  src/metabase/query_processor/middleware/convert_to_legacy.clj
  src/metabase/query_processor/middleware/expand_macros.clj
  src/metabase/query_processor/middleware/fetch_source_query.clj
  src/metabase/query_processor/middleware/fetch_source_query_legacy.clj
  src/metabase/query_processor/middleware/normalize_query.clj
  src/metabase/query_processor/middleware/permissions.clj
  src/metabase/query_processor/middleware/resolve_fields.clj
  src/metabase/query_processor/middleware/resolve_referenced.clj
  src/metabase/query_processor/middleware/resolve_source_table.clj
  src/metabase/query_processor/preprocess.clj
  src/metabase/query_processor/store.clj
  src/metabase/query_processor/util/tag_referenced_cards.clj
  src/metabase/shared/util/i18n.clj
  test/metabase/lib/metadata_test.cljc
  test/metabase/lib/native_test.cljc
  test/metabase/query_processor/middleware/expand_macros_test.clj
  test/metabase/query_processor/middleware/permissions_test.clj
  test/metabase/query_processor/middleware/resolve_fields_test.clj
  test/metabase/query_processor/middleware/resolve_referenced_test.clj
  test/metabase/query_processor/middleware/resolve_source_table_test.clj
  test/metabase/query_processor/middleware/upgrade_field_literals_test.clj
  test/metabase/query_processor/util/tag_referenced_cards_test.clj
Labels: .Team/QueryProcessor, no-backport

#39955 [Metrics V2] query processor phase 1
  src/metabase/lib/schema.cljc
  src/metabase/lib/schema/metadata.cljc
  src/metabase/query_processor/middleware/metrics.clj
  src/metabase/query_processor/preprocess.clj
  test/metabase/query_processor/middleware/metrics_test.clj
  test/metabase/util/malli/humanize_test.cljc
Labels: .Team/QueryProcessor, no-backport
