Repository metabase/metabase, pull requests merged in 2024-04, with the labels that each got.

#40574 Convert `hide.modules.css` to CSS modules
  frontend/src/metabase/components/Popover/Popover.jsx
  frontend/src/metabase/components/form/FormikCustomForm/CustomFormSection.tsx
  frontend/src/metabase/containers/formUtils.js
  frontend/src/metabase/core/components/Button/Button.tsx
  frontend/src/metabase/css/core/hide.module.css
  frontend/src/metabase/dashboard/hoc/DashboardControls.jsx
  frontend/src/metabase/query_builder/components/template_tags/SnippetSidebar/SnippetSidebar.jsx
  frontend/src/metabase/query_builder/components/view/QuestionAlertWidget.jsx
  frontend/src/metabase/query_builder/components/view/ViewFooter.jsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/ViewHeader.jsx
  frontend/src/metabase/search/components/SearchResult/components/Score.tsx
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.module.css
  frontend/src/metabase/visualizations/visualizations/Gauge/Gauge.jsx
  frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.jsx
  frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.unit.spec.js
Labels: visual, no-backport, .Team/Embedding

#40836 Fix the missing query issue in 49
  frontend/src/metabase-lib/queries/StructuredQuery.ts
Labels: .Team/QueryingComponents

#40839 Migrate question entity to RTK
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase/api/api-key.ts
  frontend/src/metabase/api/card.ts
  frontend/src/metabase/api/database.ts
  frontend/src/metabase/api/field.ts
  frontend/src/metabase/api/index.ts
  frontend/src/metabase/api/table.ts
  frontend/src/metabase/api/tags.ts
  frontend/src/metabase/common/hooks/entity-framework/use-question-list-query/use-question-list-query.ts
  frontend/src/metabase/common/hooks/entity-framework/use-question-query/use-question-query.ts
  frontend/src/metabase/entities/questions.js
Labels: visual, .Team/QueryingComponents

#40700 Allow CollectionMover to display API errors
  frontend/src/metabase/collections/components/MoveCollectionModal/MoveCollectionModal.tsx
  frontend/src/metabase/common/components/CollectionPicker/components/CollectionPickerModal.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/ButtonBar.tsx
  frontend/src/metabase/containers/MoveModal.tsx
Labels: no-backport, .Team/AdminWebapp

#40822 Properly Handle Other Users' Personal Subcollections in CollectionPicker
  frontend/src/metabase/common/components/CollectionPicker/components/CollectionPicker.tsx
  frontend/src/metabase/common/components/CollectionPicker/utils.ts
  frontend/src/metabase/common/components/CollectionPicker/utils.unit.spec.ts
Labels: no-backport, .Team/AdminWebapp

#40840 Do not update Pie chart state unnecessary
  frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.jsx
Labels: backport, visual, .Team/QueryingComponents

#40832 Remove flakiness from ListPicker spec
  frontend/src/metabase/parameters/components/ParameterValuePicker/ListPicker/ListPicker.unit.spec.tsx
Labels: backport, .Team/QueryingComponents

#40844 Fix x-ray dashboards run some queries twice on load
  frontend/src/metabase/dashboard/hoc/DashboardData.jsx
Labels: backport, .Team/DashViz

#40849 Update query results download tooltip copy
  frontend/src/metabase/query_builder/components/QueryDownloadPopover/QueryDownloadPopover.tsx
Labels: backport, .Team/DashViz

#40855 Team json update
  .github/team.json
Labels: .CI & Tests, no-backport

#40861 Handle null value for field in CategoryFingerprint
  frontend/src/metabase/components/MetadataInfo/ColumnFingerprintInfo/CategoryFingerprint.jsx
  frontend/src/metabase/components/MetadataInfo/ColumnFingerprintInfo/CategoryFingerprint.unit.spec.js
Labels: backport, .Team/QueryingComponents

#40028 docs - updates api docs script to handle exception
  src/metabase/api/common/internal.clj
  src/metabase/cmd/endpoint_dox.clj
Labels: Type:Documentation, backport

#40780 Update Translations Strings for 49.3
  locales/ar-SA.po
  locales/ar.po
  locales/bg.po
  locales/ca.po
  locales/cs.po
  locales/de.po
  locales/es.po
  locales/fa.po
  locales/fi.po
  locales/fr.po
  locales/he.po
  locales/id.po
  locales/it.po
  locales/ja.po
  locales/ko.po
  locales/lv.po
  locales/metabase.pot
  locales/nb.po
  locales/nl.po
  locales/pl.po
  locales/pt-BR.po
  locales/ru.po
  locales/sk.po
  locales/sq.po
  locales/sr.po
  locales/sv.po
  locales/tr.po
  locales/uk.po
  locales/vi.po
  locales/zh-CN.po
  locales/zh-HK.po
  locales/zh-TW.po
  locales/zh.po
Labels: backport, .Team/AdminWebapp

#40847 Convert BrowserCrumbs to TS
  frontend/src/metabase/browse/components/SchemaBrowser.jsx
  frontend/src/metabase/browse/components/TableBrowser/TableBrowser.jsx
  frontend/src/metabase/components/BrowserCrumbs/BrowserCrumbs.tsx
  frontend/src/metabase/components/BrowserCrumbs/index.jsx
  frontend/src/metabase/components/BrowserCrumbs/index.tsx
  frontend/src/metabase/containers/UserCollectionList.tsx
Labels: no-backport, .Team/Embedding

#40858 docs - fix typo
  docs/dashboards/introduction.md
Labels: Type:Documentation, backport

#40873 Fixes code snippet typo with extra closing parenthesis in case expression documentation
  docs/questions/query-builder/expressions/case.md
Labels: backport

#40785 Migrate schema entity to RTK
  e2e/test/scenarios/models/models.cy.spec.js
  e2e/test/scenarios/native/native_subquery.cy.spec.js
  e2e/test/scenarios/question/notebook-native-preview-sidebar.cy.spec.ts
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase-types/api/database.ts
  frontend/src/metabase-types/api/segment.ts
  frontend/src/metabase/admin/databases/components/DatabaseEditApp/Sidebar/Sidebar.tsx
  frontend/src/metabase/admin/databases/components/DatabaseEditApp/Sidebar/Sidebar.unit.spec.tsx
  frontend/src/metabase/admin/databases/containers/DatabaseEditApp.tsx
  frontend/src/metabase/admin/databases/database.js
  frontend/src/metabase/api/api-key.ts
  frontend/src/metabase/api/card.ts
  frontend/src/metabase/api/database.ts
  frontend/src/metabase/api/field.ts
  frontend/src/metabase/api/index.ts
  frontend/src/metabase/api/query.ts
  frontend/src/metabase/api/segment.ts
  frontend/src/metabase/api/table.ts
  frontend/src/metabase/api/tags.ts
  frontend/src/metabase/common/hooks/entity-framework/use-question-list-query/use-question-list-query.ts
  frontend/src/metabase/common/hooks/entity-framework/use-question-query/use-question-query.ts
  frontend/src/metabase/dashboard/actions/cards.unit.spec.ts
  frontend/src/metabase/entities/questions.js
  frontend/src/metabase/entities/schemas.js
  frontend/src/metabase/entities/schemas.unit.spec.js
  frontend/src/metabase/entities/segments.js
  frontend/src/metabase/services.js
  frontend/test/__support__/server-mocks/database.ts
Labels: no-backport, .Team/QueryingComponents

#40772 Add a repro for 'GUI model joining native ones break with column not found error'
  e2e/test/scenarios/models/reproductions/40252-native-model-join-crashes.cy.spec.js
Labels: backport, .Team/QueryingComponents

#40784 Add repro for "Dashboard filters do not work with custom columns on saved questions used in models"
  e2e/test/scenarios/models/reproductions/32483-dashboard-filtes-custom-column.cy.spec.js
Labels: backport, .Team/QueryingComponents

#40887 Disable saving models without up-to-date result_metadata
  e2e/support/helpers/e2e-misc-helpers.js
  e2e/test/scenarios/models/create.cy.spec.js
  e2e/test/scenarios/models/reproductions/22518.cy.spec.js
  e2e/test/scenarios/models/reproductions/37009-stale-result-metadata.cy.spec.js
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx
Labels: support/Repro, no-backport, .Team/QueryingComponents

#40889 Show query execution time in the QB header for MBQL queries
  frontend/src/metabase/query_builder/components/view/ViewFooter.jsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.unit.spec.tsx
Labels: no-backport, .Team/QueryingComponents

#40730 Migrate frontend/src/metabase/components/Popover/Popover.module.css
  e2e/support/helpers/e2e-ui-elements-helpers.js
  frontend/src/metabase/admin/datamodel/components/FilterPopover/FilterPopover.styled.tsx
  frontend/src/metabase/admin/datamodel/components/FilterPopover/FilterPopoverFooter.tsx
  frontend/src/metabase/admin/datamodel/components/filters/pickers/DefaultPicker/DefaultPicker.tsx
  frontend/src/metabase/admin/datamodel/components/filters/pickers/LegacyDatePicker/DatePicker.jsx
  frontend/src/metabase/admin/datamodel/components/filters/pickers/SelectPicker.jsx
  frontend/src/metabase/components/Popover/Popover.jsx
  frontend/src/metabase/components/Popover/Popover.module.css
  frontend/src/metabase/ui/components/overlays/Popover/index.tsx
Labels: no-backport, .Team/Embedding

#40903 Add breakpoints to the Mantine theme overrides
  frontend/src/metabase/ui/theme.ts
Labels: backport, .Team/QueryingComponents

#40692 docs - notification perms
  docs/permissions/notifications.md
Labels: Type:Documentation, backport

#40880 Make generated_columns optional for csvupload events
  snowplow/iglu-client-embedded/schemas/com.metabase/csvupload/jsonschema/1-0-3
  src/metabase/analytics/snowplow.clj
Labels: backport, .Team/BackendComponents

#40900 Migrate metrics entity to RTK
  frontend/src/metabase-types/api/metric.ts
  frontend/src/metabase/api/index.ts
  frontend/src/metabase/api/metric.ts
  frontend/src/metabase/api/tags.ts
  frontend/src/metabase/entities/metrics.js
Labels: no-backport, .Team/QueryingComponents

#40851 Add repro test for a model that uses another model and both have custom column with the same name
  e2e/test/scenarios/models/reproductions/39150-model-with-same-custom-column-name.cy.spec.ts
Labels: backport, .Team/QueryingComponents

#40896 Replace Questions.loadList with RTK
  frontend/src/metabase/models/components/ModelDetailPage/ModelDetailPage.tsx
  frontend/src/metabase/models/components/ModelDetailPage/ModelUsageDetails/ModelUsageDetails.tsx
  frontend/src/metabase/models/components/ModelDetailPage/ModelUsageDetails/index.ts
Labels: no-backport, .Team/QueryingComponents

#40403 Use RTK Query instead of entity framework for DatabaseCandidates
  frontend/src/metabase/admin/databases/components/DatabaseList/DatabaseList.jsx
  frontend/src/metabase/api/api.ts
  frontend/src/metabase/api/database-candidates.ts
  frontend/src/metabase/api/index.ts
  frontend/src/metabase/common/hooks/entity-framework/index.ts
  frontend/src/metabase/common/hooks/entity-framework/use-database-candidate-list-query/index.ts
  frontend/src/metabase/common/hooks/entity-framework/use-database-candidate-list-query/use-database-candidate-list-query.ts
  frontend/src/metabase/common/hooks/entity-framework/use-database-candidate-list-query/use-database-candidate-list-query.unit.spec.tsx
  frontend/src/metabase/databases/components/DatabaseSyncModal/DatabaseSyncModal.tsx
  frontend/src/metabase/databases/components/DatabaseSyncModal/DatabaseSyncModal.unit.spec.tsx
  frontend/src/metabase/databases/components/DatabaseSyncModal/index.ts
  frontend/src/metabase/databases/containers/DatabaseSyncModal/DatabaseSyncModal.tsx
  frontend/src/metabase/databases/containers/DatabaseSyncModal/index.ts
  frontend/src/metabase/entities/database-candidates.js
  frontend/src/metabase/entities/index.js
  frontend/src/metabase/home/components/HomeXraySection/HomeXraySection.tsx
Labels: no-backport, .Team/AdminWebapp

#40859 Fix bumping minor version past 10
  release/src/version-helpers.ts
  release/src/version-helpers.unit.spec.ts
Labels: backport, .Team/BackendComponents

#36596 Fix "instace analytics" typo
  enterprise/frontend/src/metabase-enterprise/collections/constants.ts
Labels: backport

#40922 Creator sentiment emails iterate
  src/metabase/email/messages.clj
  src/metabase/task/creator_sentiment_emails.clj
  test/metabase/task/creator_sentiment_emails_test.clj
Labels: backport

#40928 Fix brushing not working
  frontend/src/metabase/visualizations/visualizations/CartesianChart/events.ts
Labels: visual, .Team/DashViz

#40879 enable text selection on non-brushable charts
  frontend/src/metabase/visualizations/components/EChartsRenderer/EChartsRenderer.styled.tsx
  frontend/src/metabase/visualizations/components/EChartsRenderer/EChartsRenderer.tsx
Labels: visual, .Team/DashViz

#37769 Fixes clicks, drills on the combined scalars and funnel bar charts
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.tsx
  frontend/src/metabase/static-viz/components/ComboChart/settings.ts
  frontend/src/metabase/static-viz/components/ScatterPlot/ScatterPlot.tsx
  frontend/src/metabase/visualizations/components/TransformedVisualization/TransformedVisualization.tsx
  frontend/src/metabase/visualizations/echarts/cartesian/model/legend.ts
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/src/metabase/visualizations/shared/settings/cartesian-chart.ts
  frontend/src/metabase/visualizations/types/visualization.ts
  frontend/src/metabase/visualizations/visualizations/AreaChart/AreaChart.tsx
  frontend/src/metabase/visualizations/visualizations/BarChart/BarChart.tsx
  frontend/src/metabase/visualizations/visualizations/CartesianChart/CartesianChart.tsx
  frontend/src/metabase/visualizations/visualizations/CartesianChart/events.ts
  frontend/src/metabase/visualizations/visualizations/Funnel/funnel-bar-transform.ts
  frontend/src/metabase/visualizations/visualizations/Scalar/scalars-bar-transform.ts
Labels: visual, .Team/DashViz

#40908 Remove unused CSS files
  frontend/src/metabase/components/sortable/index.js
  frontend/src/metabase/components/sortable/sortable.jsx
  frontend/src/metabase/components/sortable/sortable.module.css
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/DraggableSidebarLink.styled.tsx
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/DraggableSidebarLink.tsx
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/index.ts
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/sortable.module.css
  package.json
  yarn.lock
Labels: no-backport, .Team/Embedding

#40918 Migrate `dashboard.module.css`
  e2e/test/scenarios/dashboard-cards/reproductions/20637-add-series-to-dashcard.cy.spec.js
  e2e/test/scenarios/organization/official-collections.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/21559-subscription-bar-sent-as-scalar.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/18061-maps-only-nulls-crash-frontend.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/21665-multi-series-frontend-reload.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/30058-32075-map-visualizations.cy.spec.js
  frontend/src/metabase/css/dashboard.module.css
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardActionsPanel.styled.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.tsx
  frontend/src/metabase/visualizations/components/LegendHeader.jsx
  frontend/src/metabase/visualizations/components/PinMap.jsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
  frontend/src/metabase/visualizations/visualizations/Scalar/Scalar.jsx
Labels: visual, no-backport, .Team/Embedding

#40907 Create the internal user in a migration
  enterprise/backend/src/metabase_enterprise/audit_db.clj
  enterprise/backend/src/metabase_enterprise/internal_user.clj
  enterprise/backend/test/metabase_enterprise/internal_user_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj
  resources/migrations/001_update_migrations.yaml
  src/metabase/cmd/copy.clj
  src/metabase/db/custom_migrations.clj
  test/metabase/db/internal_user_test.clj
  test/metabase/db/schema_migrations_test.clj
  test/metabase/query_processor/middleware/metrics_test.clj
  test/metabase/setup_test.clj
Labels: no-backport, .Team/BackendComponents

#40681 [MS2] 1. Analytics
  docs/installation-and-operation/serialization.md
  enterprise/frontend/src/metabase-enterprise/settings/selectors.ts
  enterprise/frontend/src/metabase-enterprise/settings/types.ts
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/IllustrationWidget/IllustrationWidget.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/IllustrationWidget/IllustrationWidget.unit.spec.tsx
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/auth/selectors.ts
  frontend/src/metabase/home/selectors.ts
  src/metabase/analytics/stats.clj
  src/metabase/public_settings.clj
  test/metabase/analytics/stats_test.clj
Labels: no-backport, .Team/Embedding

#40901 Do not put js code into page title
  e2e/support/helpers/e2e-ad-hoc-question-helpers.js
  e2e/test/scenarios/question/document-title.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/whitelabel/index.js
  frontend/src/metabase/app.js
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/query_builder/actions/querying.js
  frontend/src/metabase/query_builder/components/QueryVisualization.jsx
  frontend/src/metabase/query_builder/components/QueryVisualization.unit.spec.tsx
  frontend/src/metabase/selectors/whitelabel/index.ts
  frontend/src/metabase/selectors/whitelabel/tests/common.unit.spec.ts
  frontend/src/metabase/selectors/whitelabel/tests/enterprise.unit.spec.ts
  frontend/src/metabase/selectors/whitelabel/tests/premium.unit.spec.ts
Labels: backport, .Team/QueryingComponents

#40921 docs - formatting exports
  docs/README.md
  docs/dashboards/subscriptions.md
  docs/data-modeling/formatting.md
  docs/questions/images/export-dashboard-as-pdf.png
  docs/questions/images/exporting-the-results-of-a-question.png
  docs/questions/sharing/exporting-results.md
  docs/questions/sharing/visualizations/table.md
  docs/questions/start.md
Labels: Type:Documentation, backport

#40609 Use MLv2 to determine whether a query can be previewed
  e2e/test/scenarios/question/notebook.cy.spec.js
  frontend/src/metabase/query_builder/components/notebook/NotebookStep/NotebookStep.tsx
Labels: support/Repro, backport, .Team/QueryingComponents

#40874 Fix row id mapping in object detail modal displaying
  e2e/test/scenarios/visualizations-tabular/object_detail.cy.spec.js
  frontend/src/metabase/query_builder/selectors.js
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx
Labels: backport, visual, .Team/QueryingComponents

#40943 docs - add 49.3 to list of releases
  docs/releases.md
Labels: Type:Documentation, backport

#40947 Deprecate MLv1 metadata
  frontend/src/metabase-lib/v1/metadata/Database.ts
  frontend/src/metabase-lib/v1/metadata/Field.ts
  frontend/src/metabase-lib/v1/metadata/ForeignKey.ts
  frontend/src/metabase-lib/v1/metadata/Metadata.ts
  frontend/src/metabase-lib/v1/metadata/Metric.ts
  frontend/src/metabase-lib/v1/metadata/Schema.ts
  frontend/src/metabase-lib/v1/metadata/Segment.ts
  frontend/src/metabase-lib/v1/metadata/Table.ts
Labels: no-backport, .Team/QueryingComponents

#40650 Command Palette UI adjustments
  e2e/test/scenarios/onboarding/command-palette.cy.spec.js
  frontend/src/metabase/admin/app/components/SettingsCommandPaletteActions.tsx
  frontend/src/metabase/palette/components/Palette.styled.tsx
  frontend/src/metabase/palette/components/Palette.tsx
  frontend/src/metabase/palette/components/PaletteFooter.tsx
  frontend/src/metabase/palette/components/PaletteResults.tsx
  frontend/src/metabase/palette/components/PaletteResults.unit.spec.tsx
  frontend/src/metabase/palette/hooks/useCommandPalette.tsx
  frontend/src/metabase/palette/hooks/useCommandPaletteBasicActions.tsx
  frontend/src/metabase/palette/utils.ts
  frontend/src/metabase/palette/utils.unit.spec.ts
Labels: no-backport, .Team/AdminWebapp

#40954 Clarify that backport/no-backport is an internal thing
  .github/PULL_REQUEST_TEMPLATE.md
Labels: backport

#40963 Temporarily comment out flaky caching test: min-ttl-test
  test/metabase/query_processor/middleware/cache_test.clj
Labels: no-backport, .Team/BackendComponents

#40841 Fix embedding
  e2e/support/helpers/e2e-embedding-helpers.js
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/embedding/interactive-embedding.cy.spec.js
  e2e/test/scenarios/embedding/reproductions/40660-overflow-when-embedding-long-dashboards.cy.spec.js
  frontend/src/metabase-types/api/mocks/dashboard.ts
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.styled.tsx
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx
  frontend/src/metabase/lib/embed.js
  frontend/src/metabase/nav/components/AppBar/AppBar.tsx
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.styled.tsx
Labels: backport, .Team/Embedding

#40962 Add analytics events for the native code preview in a notebook
  e2e/test/scenarios/question/notebook-native-preview-sidebar.cy.spec.ts
  frontend/src/metabase/query_builder/analytics.js
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/ToggleNativeQueryPreview/ToggleNativeQueryPreview.tsx
  snowplow/iglu-client-embedded/schemas/com.metabase/question/jsonschema/1-0-3
Labels: no-backport, .Team/QueryingComponents

#39234 Basic cache admin UI
  enterprise/frontend/src/metabase-enterprise/caching/components/GranularControlsExplanation.tsx
  enterprise/frontend/src/metabase-enterprise/caching/components/ResetButtonContainer.styled.tsx
  enterprise/frontend/src/metabase-enterprise/caching/components/ResetButtonContainer.tsx
  enterprise/frontend/src/metabase-enterprise/caching/components/StrategyEditorForDatabases.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/caching/components/StrategyFormLauncher.styled.tsx
  enterprise/frontend/src/metabase-enterprise/caching/components/StrategyFormLauncher.tsx
  enterprise/frontend/src/metabase-enterprise/caching/components/StrategyFormLauncherPanel.tsx
  enterprise/frontend/src/metabase-enterprise/caching/hooks/useResetToDefaultForm.tsx
  enterprise/frontend/src/metabase-enterprise/caching/index.tsx
  frontend/src/metabase-types/api/index.ts
  frontend/src/metabase-types/api/mocks/performance.ts
  frontend/src/metabase-types/api/performance.ts
  frontend/src/metabase-types/store/admin.ts
  frontend/src/metabase/admin/app/reducers.ts
  frontend/src/metabase/admin/performance/components/PerformanceApp.styled.tsx
  frontend/src/metabase/admin/performance/components/PerformanceApp.tsx
  frontend/src/metabase/admin/performance/components/StrategyEditorForDatabases.styled.tsx
  frontend/src/metabase/admin/performance/components/StrategyEditorForDatabases.tsx
  frontend/src/metabase/admin/performance/components/StrategyEditorForDatabases.unit.spec.tsx
  frontend/src/metabase/admin/performance/components/StrategyForm.tsx
  frontend/src/metabase/admin/performance/components/test-utils.tsx
  frontend/src/metabase/admin/performance/hooks/useCacheConfigs.tsx
  frontend/src/metabase/admin/performance/hooks/useConfirmOnRouteLeave.tsx
  frontend/src/metabase/admin/performance/hooks/useDelayedLoadingSpinner.tsx
  frontend/src/metabase/admin/performance/hooks/useRecentlyTrue.tsx
  frontend/src/metabase/admin/performance/hooks/useVerticallyOverflows.tsx
  frontend/src/metabase/admin/performance/strategies.ts
  frontend/src/metabase/admin/routes.jsx
  frontend/src/metabase/admin/settings/selectors.js
  frontend/src/metabase/core/components/FormSubmitButton/FormSubmitButton.tsx
  frontend/src/metabase/forms/components/FormProvider/FormProvider.tsx
  frontend/src/metabase/forms/components/FormSubmitButton/FormSubmitButton.tsx
  frontend/src/metabase/forms/contexts/FormContext/FormContext.tsx
  frontend/src/metabase/forms/hooks/use-form-context/use-form-context.ts
  frontend/src/metabase/forms/hooks/use-form-submit/use-form-submit.ts
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/schema.js
  frontend/src/metabase/services.js
  frontend/src/metabase/ui/components/buttons/Button/Button.styled.tsx
  frontend/src/metabase/ui/components/buttons/Button/index.ts
  frontend/src/metabase/ui/components/icons/Icon/Icon.tsx
  frontend/src/metabase/ui/index.ts
  frontend/test/__support__/server-mocks/performance.ts
Labels: no-backport

#40919 Make Noah the codeowner for permissions et al
  .github/CODEOWNERS
Labels: backport

#40821 Fix naming a filter offset or limit breaks dashboards
  src/metabase/server/middleware/offset_paging.clj
  test/metabase/server/middleware/offset_paging_test.clj
Labels: backport, .Team/AdminWebapp

#40931 fix timeline events render on top of series
  .loki/reference/chrome_laptop_static_viz_ComboChart_Goal_Between_Extent_And_Chart_Bound.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Goal_Line_Out_Of_Bounds_37848.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Goal_Line_Under_Series_38824.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Goal_Very_Small.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Number_Of_Insights_Error_39608.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Combo_Log.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Combo_Power.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Area.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Line.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Normalized_Stacked_Area.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Stacked_Area.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Goal_Line.png
  frontend/src/metabase/visualizations/echarts/cartesian/constants/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/constants/style.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/goal-line.ts
  frontend/src/metabase/visualizations/echarts/types.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-chart-events.ts
Labels: visual, .Team/DashViz

#40938 [docs] some format fixes
  docs/questions/native-editor/referencing-saved-questions-in-queries.md
  docs/questions/native-editor/sql-parameters.md
Labels: Type:Documentation, backport

#40933 [QP] Correctly find joined fields in the previous stage
  e2e/test/scenarios/models/reproductions/40252-native-model-join-crashes.cy.spec.js
  src/metabase/query_processor/util/add_alias_info.clj
  test/metabase/query_processor/util/add_alias_info_test.clj
Labels: backport, .Team/QueryProcessor

#41002 Fix question_id in question schema 1-0-3
  snowplow/iglu-client-embedded/schemas/com.metabase/question/jsonschema/1-0-3
Labels: no-backport, .Team/QueryingComponents

#40522 Convert `cursor.module.css` to CSS modules
  e2e/test/scenarios/visualizations-tabular/drillthroughs/chart_drill.cy.spec.js
  frontend/src/metabase/admin/datamodel/components/DimensionList/DimensionList.jsx
  frontend/src/metabase/admin/datamodel/components/ObjectActionSelect.jsx
  frontend/src/metabase/admin/datamodel/components/filters/pickers/DatePicker/HoursMinutesInput.tsx
  frontend/src/metabase/admin/datamodel/components/filters/pickers/LegacyDatePicker/HoursMinutesInput.jsx
  frontend/src/metabase/admin/people/components/AddMemberRow.jsx
  frontend/src/metabase/admin/people/components/GroupMembersTable/GroupMembersTable.tsx
  frontend/src/metabase/admin/settings/components/ApiKeys/ManageApiKeys.tsx
  frontend/src/metabase/admin/settings/components/widgets/CustomGeoJSONWidget.jsx
  frontend/src/metabase/components/Triggerable/Triggerable.jsx
  frontend/src/metabase/css/core/cursor.module.css
  frontend/src/metabase/dashboard/components/ClickMappings.jsx
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.tsx
  frontend/src/metabase/query_builder/components/DataSelector/TriggerComponents.tsx
  frontend/src/metabase/query_builder/components/notebook/NotebookStepPreview.jsx
  frontend/src/metabase/query_builder/components/view/QuestionAlertWidget.jsx
  frontend/src/metabase/sharing/components/PulsesListSidebar.jsx
  frontend/src/metabase/visualizations/components/FunnelNormal.jsx
  frontend/src/metabase/visualizations/components/LegacyChoropleth.jsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailsTable.tsx
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingGaugeSegments.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting.jsx
  frontend/src/metabase/visualizations/lib/LineAreaBarPostRender.js
  frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.jsx
Labels: visual, no-backport, .Team/Embedding

#40748 fix: padding not working on <Modal> component
  frontend/src/metabase/ui/components/overlays/Modal/Modal.styled.tsx
Labels: visual, no-backport, .Team/Embedding

#40966 Fix flaky test caused by unmounted HoverCard
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/admin-2/whitelabel.cy.spec.js
  frontend/src/metabase/components/MetadataInfo/Popover/Popover.tsx
  frontend/src/metabase/ui/components/overlays/Popover/index.tsx
Labels: no-backport, .Team/Embedding

#40741 Break out upload.types namespace
  src/metabase/upload.clj
  src/metabase/upload/parsing.clj
  src/metabase/upload/types.cljc
  test/metabase/upload/types_test.clj
  test/metabase/upload_test.clj
  test/metabase/util/ordered_hierarchy_test.clj
Labels: no-backport, .Team/BackendComponents

#40899 Testing parity for appending to and replacing uploads
  enterprise/backend/test/metabase_enterprise/upload_test.clj
  test/metabase/upload_test.clj
Labels: no-backport, .Team/BackendComponents

#40834 do not print stacktrace when client closes connection too early
  src/metabase/query_processor/streaming.clj
Labels: backport, .Team/BackendComponents

#40545 Clean up deprecated data permission types
  e2e/snapshot-creators/default.cy.snap.js
  e2e/support/commands/permissions/sandboxTable.js
  e2e/test/scenarios/actions/model-actions.cy.spec.js
  e2e/test/scenarios/collections/uploads.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/15163.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
  e2e/test/scenarios/permissions/admin-permissions.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/13347-cannot-select-saved-question-in-database-without-data-permissions.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/14873-regextract-in-sandboxed-table.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/17763-cannot-edit-granular-after-block.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/20436-incorrect-display-of-database-permissions-level.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/22447-illogical-UI-elements-for-nodata.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/22695-search-databases-no-permissions.cy.spec.js
  enterprise/backend/src/metabase_enterprise/advanced_permissions/models/connection_impersonation.clj
  enterprise/backend/src/metabase_enterprise/audit_app/permissions.clj
  enterprise/backend/src/metabase_enterprise/sandbox/api/table.clj
  enterprise/backend/src/metabase_enterprise/sandbox/models/group_table_access_policy.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/models/permissions/block_permissions_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/permissions_test.clj
  enterprise/backend/test/metabase_enterprise/audit_db_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/gtap_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/pulse_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/test_util.clj
  enterprise/backend/test/metabase_enterprise/snippet_collections/api/native_query_snippet_test.clj
  resources/migrations/001_update_migrations.yaml
  src/metabase/models/data_permissions.clj
  src/metabase/models/data_permissions/graph.clj
  src/metabase/models/database.clj
  src/metabase/models/native_query_snippet/permissions.clj
  src/metabase/models/permissions_group.clj
  src/metabase/models/query/permissions.clj
  src/metabase/models/table.clj
  test/metabase/api/dataset_test.clj
  test/metabase/api/permissions_test.clj
  test/metabase/dashboard_subscription_test.clj
  test/metabase/events/view_log_test.clj
  test/metabase/models/data_permissions/graph_test.clj
  test/metabase/models/data_permissions_test.clj
  test/metabase/models/database_test.clj
  test/metabase/models/permissions_group_test.clj
  test/metabase/models/table_test.clj
Labels: .Team/AdminWebapp

#40965 [MLv2] Handle nested "Zoom In" drills on binned columns
  src/metabase/lib/binning.cljc
  src/metabase/lib/drill_thru/zoom_in_bins.cljc
  test/metabase/lib/drill_thru/zoom_in_bins_test.cljc
Labels: .Team/QueryProcessor, no-backport

#40997 fix line charts broken due to stacking settings
  .loki/reference/chrome_laptop_static_viz_ComboChart_Area_Stack_All_Series_Without_Interpolation.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Area_Stack_Interpolate_Missing_Values.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Area_Stack_Linear_X_Axis.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Breakout_With_Line_Series_Stacked_Right_Axis_Only.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Histogram_Stacked.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Histogram_Stacked_Normalized.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Log_Y_Scale_Stacked.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Log_Y_Scale_Stacked_Negative.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Stack_Display_Overrides_Series_Displays.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Stack_Linear_X_Axis.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Stacked_Normalized_Empty_Space_37880.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Stacked_Pow_Y_Axis.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Stacked_Pow_Y_Axis_Negatives.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Stacked_Total_Formatted_Values.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Two_Axes_Stacked_With_Negative_Values.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Normalized_Stacked_Area.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Normalized_Stacked_Bar.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Stacked_Area.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Stacked_Bar.png
  .loki/reference/chrome_laptop_static_viz_FunnelBarChart_Default.png
  .loki/reference/chrome_laptop_static_viz_ScalarChart_Default.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Custom_Y_Axis_Range.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Default.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Goal_Line.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Histogram_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale_At_One.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Metric_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Ordinal_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale_Multi_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Timeseries_X_Scale.png
  frontend/src/metabase/visualizations/lib/settings/graph.js
Labels: visual, .Team/DashViz, loki-update

#41033 docs - mention of raw unformatted results
  docs/questions/sharing/exporting-results.md
  docs/questions/sharing/public-links.md
Labels: Type:Documentation, backport

#41027 Repro #23103 - Wrong number of distinct values in a native model
  e2e/test/scenarios/models/reproductions/23103-wrong-number-of-distinct-values.cy.spec.ts
Labels: no-backport, .Team/QueryingComponents

#40455 add new settings for embedding homepage
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.ts
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/home/components/EmbedHomepage/EmbedHomepage.tsx
  frontend/src/metabase/home/components/EmbedMinimalHomepage/EmbedMinimalHomepage.styled.tsx
  frontend/src/metabase/home/components/EmbedMinimalHomepage/EmbedMinimalHomepage.tsx
  frontend/src/metabase/home/components/EmbedMinimalHomepage/index.ts
  frontend/src/metabase/home/components/HomeContent/HomeContent.tsx
  frontend/src/metabase/home/components/HomeContent/HomeContent.unit.spec.tsx
  frontend/src/metabase/home/utils.ts
  frontend/src/metabase/setup/actions.ts
  frontend/src/metabase/setup/tests/common.unit.spec.tsx
  frontend/src/metabase/setup/tests/premium.unit.spec.tsx
  frontend/src/metabase/setup/tests/setup.tsx
  src/metabase/embed/settings.clj
Labels: .Team/Embedding

#41029 Revert "fix: padding not working on <Modal> component"
  frontend/src/metabase/ui/components/overlays/Modal/Modal.styled.tsx
Labels: no-backport, .Team/Embedding

#40528 connect settings to the embed homepage and show it
  frontend/src/metabase/home/components/EmbedHomepage/EmbedHomepage.stories.tsx
  frontend/src/metabase/home/components/EmbedHomepage/EmbedHomepage.tsx
  frontend/src/metabase/home/components/EmbedHomepage/EmbedHomepageView.tsx
  frontend/src/metabase/home/components/EmbedHomepage/InteractiveTabContent.tsx
  frontend/src/metabase/home/components/EmbedHomepage/StaticTabContent.tsx
  frontend/src/metabase/home/components/EmbedHomepage/tests/common.unit.spec.tsx
  frontend/src/metabase/home/components/EmbedHomepage/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/home/components/EmbedHomepage/tests/premium.unit.spec.tsx
  frontend/src/metabase/home/components/EmbedHomepage/tests/setup.tsx
  frontend/src/metabase/home/components/HomeContent/HomeContent.tsx
  frontend/src/metabase/home/components/HomeContent/HomeContent.unit.spec.tsx
Labels: .Team/Embedding

#40587 dismiss without feedback for the embedding homepage
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.ts
  frontend/src/metabase/home/components/EmbedHomepage/EmbedHomepage.tsx
  frontend/src/metabase/home/components/EmbedHomepage/EmbedHomepageView.tsx
  frontend/src/metabase/home/components/EmbedHomepage/tests/common.unit.spec.tsx
  frontend/src/metabase/home/components/EmbedHomepage/tests/setup.tsx
  frontend/src/metabase/home/components/EmbedHomepage/types.ts
Labels: .Team/Embedding

#40638 use List from metabase/ui
  frontend/src/metabase/home/components/EmbedHomepage/InteractiveTabContent.tsx
  frontend/src/metabase/home/components/EmbedHomepage/StaticTabContent.tsx
Labels: .Team/Embedding

#40813 set embedding-secret-key when embedding is enabled
  e2e/snapshot-creators/default.cy.snap.js
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.ts
  frontend/src/metabase/admin/settings/selectors.js
  src/metabase/embed/settings.clj
Labels: .Team/Embedding

#40957 Enable not emptyable arguments for is-empty and not-empty clauses
  e2e/test/scenarios/custom-column/custom-column.cy.spec.js
  modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj
  src/metabase/legacy_mbql/util.cljc
  src/metabase/lib/schema/filter.cljc
  src/metabase/query_processor/middleware/desugar.clj
  src/metabase/query_processor/middleware/wrap_value_literals.clj
  test/metabase/legacy_mbql/util_test.cljc
  test/metabase/query_processor/middleware/desugar_test.clj
  test/metabase/query_processor/middleware/validate_temporal_bucketing_test.clj
  test/metabase/query_processor/streaming/csv_test.clj
  test/metabase/query_processor_test/filter_test.clj
  test/metabase/test/data/dataset_definitions.clj
  test_resources/load-durations.edn
  test_resources/sync-durations.edn
Labels: backport, .Team/QueryProcessor

#40758 show warning for unaggregated dimension
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/types.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/index.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-models-and-option.ts
Labels: visual, .Team/DashViz

#40759 show null dimension value warning
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Custom_Y_Axis_Range.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Default.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Histogram_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale_At_One.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Metric_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Ordinal_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale_Multi_Series.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Linear_Null_Dimension.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Ordinal_Null_Dimension.png
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.stories.tsx
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/index.ts
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/linear-null-dimension.json
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/ordinal-null-dimension.json
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/index.ts
Labels: visual, .Team/DashViz

#40763 show invalid date warning
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/index.ts
Labels: visual, .Team/DashViz

#40764 show unexpected and multiple timezones warnings
  frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/utils/timeseries.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/index.ts
Labels: visual, .Team/DashViz

#41044 docs - update public sharing
  docs/questions/images/create-a-public-link.png
  docs/questions/images/dashboard-sharing.png
  docs/questions/images/enable-links.png
  docs/questions/images/public-embed.png
  docs/questions/images/public-export.png
  docs/questions/sharing/public-links.md
Labels: Type:Documentation, backport

#41048 Try using a separate canvas object for each cartesian chart
  frontend/src/metabase/lib/measure-text.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-models-and-option.ts
Labels: visual, .Team/DashViz

#41036 asynchronously load libraries for png and pdf exports
  frontend/src/metabase/visualizations/lib/save-chart-image.ts
  frontend/src/metabase/visualizations/lib/save-dashboard-pdf.ts
Labels: backport, visual, .Team/DashViz

#40828 Fix histogram and ordinal x-axis scales not respecting column formatting
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Ordinal_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Default.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Custom_Y_Axis_Range.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Default.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Goal_Line.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Histogram_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale_At_One.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Metric_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Ordinal_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale_Multi_Series.png
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.tsx
  frontend/src/metabase/components/TokenField/utils.ts
  frontend/src/metabase/components/TokenField/utils.unit.spec.ts
  frontend/src/metabase/lib/number.ts
  frontend/src/metabase/lib/number.unit.spec.ts
  frontend/src/metabase/parameters/components/widgets/NumberInputWidget/NumberInputWidget.tsx
  frontend/src/metabase/visualizations/echarts/cartesian/option/axis.ts
Labels: visual, .Team/DashViz, loki-update

#41055 Fix ordinal scale x-axis tick labels for numeric columns
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Relative_Datetime_Ordinal_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Goal_Line.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Ordinal_Null_Dimension.png
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/bar-relative-datetime-ordinal-scale.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/axis.ts
Labels: visual, .Team/DashViz, loki-update

#41001 fix relative date time x-axis ticks
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Two_Days_Of_Week.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Numeric_X_Axis_Includes_Zero_37082.png
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/bar-two-days-of-week.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/axis.ts
Labels: visual, .Team/DashViz

#40679 [MLv2] First pass of docs improvements in `metabase.lib.js`
  src/metabase/lib/filter/update.cljc
  src/metabase/lib/js.cljs
Labels: .Team/QueryProcessor, no-backport

#41069 Fix tests for ms1 after updating on master
  frontend/src/metabase/home/components/EmbedHomepage/tests/common.unit.spec.tsx
  frontend/src/metabase/setup/tests/premium.unit.spec.tsx
Labels: .Team/Embedding

#41049 docs - remove redirect
  docs/questions/sharing/public-links.md
Labels: Type:Documentation, backport

#41073 Fix `flaky onboarding/command-palette.cy.spec.js`
  e2e/support/helpers/e2e-command-palette-helpers.js
  e2e/test/scenarios/onboarding/command-palette.cy.spec.js
  frontend/src/metabase/palette/components/PaletteResults.tsx
Labels: no-backport, .Team/Embedding

#41066 Simple sync exceptions
  src/metabase/sync/util.clj
  test/metabase/test/data/impl/get_or_create.clj
Labels: no-backport, .Team/BackendComponents

#41018 Migrate `LineAreaBarChart.module.css`
  e2e/test/scenarios/dashboard-cards/reproductions/32231-add-incompatible-series.cy.spec.js
  e2e/test/scenarios/models/models-revision-history.cy.spec.js
  e2e/test/scenarios/models/models.cy.spec.js
  e2e/test/scenarios/visualizations-charts/line_chart.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/30058-32075-map-visualizations.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/drillthroughs/chart_drill.cy.spec.js
  frontend/src/metabase/css/dashboard.module.css
  frontend/src/metabase/visualizations/components/LineAreaBarChart.jsx
  frontend/src/metabase/visualizations/components/LineAreaBarChart.module.css
Labels: visual, no-backport, .Team/Embedding

#41030 Migrate `list.module.css`
  e2e/test/scenarios/admin-2/sso/shared/group-mappings-widget.js
  e2e/test/scenarios/admin/datamodel/metadata.cy.spec.js
  e2e/test/scenarios/admin/datamodel/reproductions.cy.spec.js
  e2e/test/scenarios/onboarding/reference/databases.cy.spec.js
  e2e/test/scenarios/permissions/sandboxes.cy.spec.js
  e2e/test/scenarios/question/notebook-data-source.cy.spec.ts
  e2e/test/scenarios/visualizations-charts/waterfall.cy.spec.js
  frontend/src/metabase/admin/datamodel/components/DimensionList/DimensionList.jsx
  frontend/src/metabase/admin/datamodel/components/DimensionPicker/DimensionPicker.jsx
  frontend/src/metabase/admin/datamodel/components/FilterPopover/FilterPopover.tsx
  frontend/src/metabase/core/components/AccordionList/AccordionListCell.jsx
  frontend/src/metabase/core/components/AccordionList/AccordionListCell.styled.tsx
  frontend/src/metabase/css/components/list.module.css
  frontend/src/metabase/css/query_builder.module.css
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.unit.spec.js
Labels: no-backport, .Team/Embedding

#41078 Fix question schema notebook
  frontend/src/metabase/query_builder/analytics.js
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/ToggleNativeQueryPreview/ToggleNativeQueryPreview.tsx
  snowplow/iglu-client-embedded/schemas/com.metabase/question/jsonschema/1-0-3
Labels: no-backport, .Team/QueryingComponents

#41075 Tighten metabase.upload interface
  src/metabase/upload.clj
Labels: no-backport, .Team/BackendComponents

#41074 Fix loading metadata for models
  frontend/src/metabase/query_builder/containers/test-utils.tsx
  frontend/src/metabase/questions/actions.ts
Labels: no-backport, .Team/QueryingComponents

#40996 No error message on preview api error
  frontend/src/metabase/query_builder/components/notebook/NotebookStepPreview.jsx
  frontend/src/metabase/query_builder/components/notebook/NotebookStepPreview.unit.spec.tsx
Labels: no-backport, .Team/QueryingComponents

#41093 fix ticks auto rotation
  frontend/src/metabase/visualizations/echarts/cartesian/chart-measurements/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/types.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/axis.ts
Labels: visual, .Team/DashViz

#40693 fix ordinal axis labels
  .loki/reference/chrome_laptop_static_viz_ComboChart_Area_Stack_Linear_X_Axis.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Ordinal_X_Scale_Auto_Rotated_Labels.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Stack_Linear_X_Axis.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Compact_X_Axis_Does_Not_Work_38917.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Default.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Goal_Between_Extent_And_Chart_Bound.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Goal_Line_Disabled.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Goal_Line_Out_Of_Bounds_37848.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Goal_Very_Small.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Line_Custom_Y_Axis_Range_Equals_Extents.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Line_Log_Y_Scale.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Line_Show_Dots_Auto.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Line_Show_Dots_Off.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Line_Show_Dots_On.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Log_Y_Scale_Custom_Y_Axis_Range.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Long_Dimension_Name_Cut_Off_37420.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Pow_Y_Scale_Custom_Y_Axis_Range.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Ticks_Native_Week_With_Gap_Long_Range.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Wrong_Y_Axis_Range_37306.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Custom_Y_Axis_Range.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Default.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Goal_Line.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Histogram_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale_At_One.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Metric_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Ordinal_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale_Multi_Series.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Data_Labels.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Data_Labels_Column_Formatting.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Data_Labels_Timeseries.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Enourmous_Dataset.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Log_Y_Scale.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Log_Y_Scale_Negative.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Negative_Only.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_No_Total_Ordinal.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Ordinal_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Pow_Y_Scale.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Pow_Y_Scale_Negative_Only.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Time_Series_Data_As_Ordinal_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Timeseries_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Timeseries_X_Scale_Unsorted.png
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/bar-ordinal-x-scale-auto-rotated-labels.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/chart-measurements/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/chart-measurements/types.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/types.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/axis.ts
Labels: visual, .Team/DashViz, loki-update

#40752 Use window functions for cumulative sum and cumulative count
  docs/developers-guide/driver-changelog.md
  e2e/test/scenarios/custom-column/custom-column.cy.spec.js
  modules/drivers/athena/src/metabase/driver/athena.clj
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj
  modules/drivers/mongo/test/metabase/driver/mongo/query_processor_test.clj
  modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/sparksql/src/metabase/driver/sparksql.clj
  modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj
  modules/drivers/vertica/src/metabase/driver/vertica.clj
  src/metabase/db.clj
  src/metabase/driver.clj
  src/metabase/driver/h2.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql.clj
  src/metabase/driver/sql/query_processor.clj
  src/metabase/driver/sql_jdbc/execute.clj
  src/metabase/legacy_mbql/util.cljc
  src/metabase/lib/aggregation.cljc
  src/metabase/query_processor/middleware/cumulative_aggregations.clj
  test/metabase/driver/sql/query_processor_test.clj
  test/metabase/legacy_mbql/util_test.cljc
  test/metabase/query_processor/middleware/add_implicit_clauses_test.clj
  test/metabase/query_processor/middleware/cumulative_aggregations_test.clj
  test/metabase/query_processor/util/add_alias_info_test.clj
  test/metabase/query_processor_test/aggregation_test.clj
  test/metabase/query_processor_test/cumulative_aggregation_test.clj
  test/metabase/query_processor_test/expression_aggregations_test.clj
  test/metabase/test/data/h2.clj
  test/metabase/test/data/interface.clj
Labels: .Team/QueryProcessor, no-backport

#40466 MLv2 normalization: add :lib/uuid automatically to options maps if missing
  src/metabase/lib/query.cljc
  src/metabase/lib/schema/common.cljc
  src/metabase/lib/util.cljc
  src/metabase/models/interface.clj
  src/metabase/query_processor/middleware/normalize_query.clj
  test/metabase/lib/normalize_test.cljc
  test/metabase/lib/query_test.cljc
Labels: .Team/QueryProcessor, no-backport

#41008 make qp.middleware.cache-test/min-ttl-test pass consistently
  test/metabase/query_processor/middleware/cache_test.clj
Labels: no-backport, .Team/BackendComponents

#40958 Remove lingering Joda Time references
  deps.edn
  docs/developers-guide/driver-changelog.md
  src/metabase/driver/common.clj
  src/metabase/task/send_pulses.clj
  test/metabase/driver/mysql_test.clj
Labels: no-backport, .Team/BackendComponents

#40956 Convert PublicError and PublicNotFound to TS
  frontend/src/metabase/public/components/PublicError.jsx
  frontend/src/metabase/public/components/PublicError.tsx
  frontend/src/metabase/public/components/PublicNotFound.tsx
  frontend/src/metabase/public/containers/PublicApp/PublicApp.tsx
  frontend/src/metabase/routes-embed.jsx
  frontend/src/metabase/routes-public.jsx
Labels: no-backport, .Team/Embedding

#40984 Make notebook native preview sidebar resizable
  e2e/test/scenarios/question/notebook-native-preview-sidebar.cy.spec.ts
  frontend/src/metabase/query_builder/components/view/NativeQueryPreviewSidebar/NativeQueryPreviewSidebar.tsx
  frontend/src/metabase/query_builder/components/view/View/NotebookContainer/NotebookContainer.module.css
  frontend/src/metabase/query_builder/components/view/View/NotebookContainer/NotebookContainer.tsx
Labels: no-backport, .Team/QueryingComponents

#41040 Migrate search to RTK
  frontend/src/metabase-types/api/collection.ts
  frontend/src/metabase-types/api/mocks/search.ts
  frontend/src/metabase-types/api/search.ts
  frontend/src/metabase/api/collection.ts
  frontend/src/metabase/api/dataset.ts
  frontend/src/metabase/api/index.ts
  frontend/src/metabase/api/search.ts
  frontend/src/metabase/api/tags.ts
  frontend/src/metabase/common/components/CollectionPicker/components/CollectionPicker.tsx
  frontend/src/metabase/common/components/CollectionPicker/types.ts
  frontend/src/metabase/common/components/CollectionPicker/utils.ts
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerSearch/EntityPickerSearch.tsx
  frontend/src/metabase/common/hooks/entity-framework/use-search-list-query/use-search-list-query.ts
  frontend/src/metabase/dashboard/components/QuestionPicker/QuestionList.tsx
  frontend/src/metabase/entities/search.js
  frontend/src/metabase/nav/components/search/SearchResults/SearchResults.tsx
  frontend/src/metabase/search/components/InfoText/InfoText.unit.spec.tsx
  frontend/src/metabase/search/constants.ts
  frontend/src/metabase/services.js
Labels: no-backport, .Team/QueryingComponents

#41117 Add endpoint to list uploaded tables
  src/metabase/api/table.clj
  test/metabase/api/table_test.clj
Labels: no-backport, .Team/BackendComponents

#41100 Remove unused argument passed around
  dev/src/dev.clj
  src/metabase/api/testing.clj
  src/metabase/cmd/migrate.clj
  src/metabase/db/liquibase.clj
  src/metabase/db/setup.clj
  test/metabase/cmd/load_from_h2_test.clj
  test/metabase/db/fix_mysql_utf8_test.clj
  test/metabase/db/force_migration_test.clj
  test/metabase/db/schema_migrations_test/impl.clj
Labels: no-backport, .Team/BackendComponents

#40774 cache invalidation
  .dir-locals.el
  enterprise/backend/src/metabase_enterprise/cache/strategies.clj
  enterprise/backend/test/metabase_enterprise/cache/cache_test.clj
  resources/migrations/001_update_migrations.yaml
  src/metabase/api/cache.clj
  src/metabase/api/common.clj
  src/metabase/api/common/openapi.clj
  src/metabase/models.clj
  src/metabase/models/cache_config.clj
  src/metabase/models/card.clj
  src/metabase/query_processor/card.clj
  src/metabase/query_processor/middleware/cache_backend/db.clj
  test/metabase/api/card_test.clj
  test/metabase/api/common/openapi_test.clj
Labels: no-backport, .Team/BackendComponents

#41052 [API] Ensure the `:schema` is returned as an empty string, not nil
  src/metabase/api/database.clj
  src/metabase/api/table.clj
  test/metabase/api/database_test.clj
  test/metabase/api/table_test.clj
Labels: .Team/QueryProcessor, no-backport

#41035 [MBQL lib] `suggestedJoinConditions` accepts a join position for edits
  src/metabase/lib/join.cljc
  src/metabase/lib/js.cljs
  test/metabase/lib/join_test.cljc
Labels: .Team/QueryProcessor, no-backport

#40008 Move search to toplevel in accordionlist
  frontend/src/metabase/admin/datamodel/metadata/components/SemanticTypeAndTargetPicker/SemanticTypeAndTargetPicker.tsx
  frontend/src/metabase/common/components/QueryColumnPicker/QueryColumnPicker.tsx
  frontend/src/metabase/core/components/AccordionList/AccordionList.jsx
  frontend/src/metabase/core/components/AccordionList/AccordionList.unit.spec.js
  frontend/src/metabase/core/components/AccordionList/AccordionListCell.jsx
  frontend/src/metabase/core/components/AccordionList/AccordionListCell.styled.tsx
  frontend/src/metabase/core/components/AccordionList/utils.ts
  frontend/src/metabase/core/components/AccordionList/utils.unit.spec.ts
  frontend/src/metabase/core/components/Select/Select.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorTablePicker/DataSelectorTablePicker.tsx
  frontend/src/metabase/querying/components/FilterPicker/FilterColumnPicker/FilterColumnPicker.tsx
Labels: no-backport, .Team/QueryingComponents

#41063 Quickfix heigth on row picker
  frontend/src/metabase/common/components/FieldPicker/FieldPicker.styled.tsx
  frontend/src/metabase/components/MetadataInfo/TableInfo/ConnectedTables.tsx
  frontend/src/metabase/components/MetadataInfo/TableInfo/ConnectedTables.unit.spec.tsx
Labels: no-backport, .Team/QueryingComponents

#40891 Allow to change RHS table in each join
  frontend/src/metabase-lib/join.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/Join/Join.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinComplete/JoinComplete.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinComplete/JoinComplete.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinComplete/index.ts
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinDraft/JoinDraft.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTablePicker/JoinTablePicker.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTablePicker/JoinTablePicker.tsx
Labels: no-backport, .Team/QueryingComponents

#39436 Refactor: move fingerprinting and classifier code from sync directory
  .clj-kondo/config.edn
  bin/build/src/i18n/enumerate.clj
  enterprise/backend/src/metabase_enterprise/llm/api.clj
  modules/drivers/googleanalytics/test/metabase/driver/googleanalytics_test.clj
  src/metabase/analyze/classifiers/category.clj
  src/metabase/analyze/classifiers/core.clj
  src/metabase/analyze/classifiers/name.clj
  src/metabase/analyze/classifiers/no_preview_display.clj
  src/metabase/analyze/classifiers/text_fingerprint.clj
  src/metabase/analyze/fingerprint/fingerprinters.clj
  src/metabase/analyze/fingerprint/insights.clj
  src/metabase/analyze/fingerprint/schema.clj
  src/metabase/analyze/query_results.clj
  src/metabase/analyze/schema.clj
  src/metabase/api/card.clj
  src/metabase/automagic_dashboards/core.clj
  src/metabase/automagic_dashboards/util.clj
  src/metabase/models/card.clj
  src/metabase/query_processor/middleware/annotate.clj
  src/metabase/query_processor/middleware/results_metadata.clj
  src/metabase/sync.clj
  src/metabase/sync/analyze.clj
  src/metabase/sync/analyze/classify.clj
  src/metabase/sync/analyze/fingerprint.clj
  src/metabase/sync/interface.clj
  src/metabase/types.cljc
  test/metabase/analyze/classifiers/category_test.clj
  test/metabase/analyze/classifiers/name_test.clj
  test/metabase/analyze/classifiers/no_preview_display_test.clj
  test/metabase/analyze/classifiers/text_fingerprint_test.clj
  test/metabase/analyze/classify_test.clj
  test/metabase/analyze/fingerprint/fingerprinters_test.clj
  test/metabase/analyze/fingerprint/insights_test.clj
  test/metabase/analyze/fingerprint_test.clj
  test/metabase/analyze/query_results_test.clj
  test/metabase/driver/mysql_test.clj
  test/metabase/query_processor/middleware/results_metadata_test.clj
  test/metabase/sync/analyze/classify_test.clj
  test/metabase/sync/analyze/fingerprint_test.clj
  test/metabase/sync/analyze_test.clj
Labels: backport, .Team/BackendComponents

#40655 Make Collection Picker child-aware
  e2e/test/scenarios/admin-2/whitelabel.cy.spec.js
  frontend/src/metabase-types/api/collection.ts
  frontend/src/metabase/common/components/CollectionPicker/components/CollectionPicker.tsx
  frontend/src/metabase/common/components/CollectionPicker/components/CollectionPicker.unit.spec.tsx
  frontend/src/metabase/common/components/CollectionPicker/components/CollectionPickerModal.tsx
  frontend/src/metabase/common/components/CollectionPicker/components/PersonalCollectionItemList.tsx
  frontend/src/metabase/common/components/CollectionPicker/components/RootItemList.tsx
  frontend/src/metabase/common/components/CollectionPicker/types.ts
  frontend/src/metabase/common/components/CollectionPicker/utils.ts
  frontend/src/metabase/common/components/CollectionPicker/utils.unit.spec.ts
  frontend/src/metabase/common/components/EntityPicker/components/ItemList/ItemList.tsx
  frontend/src/metabase/common/components/EntityPicker/components/NestedItemPicker/NestedItemPicker.tsx
  frontend/src/metabase/common/components/EntityPicker/components/NestedItemPicker/utils.ts
  frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.unit.spec.tsx
  frontend/src/metabase/dashboard/containers/CreateDashboardModal.unit.spec.tsx
Labels: no-backport, .Team/AdminWebapp

#41134 Fix bad spacing on notebook action buttons
  frontend/src/metabase/query_builder/components/notebook/NotebookStep/NotebookStep.tsx
Labels: no-backport, .Team/Embedding

#41064 Preserve notebook native preview user preferences
  .clj-kondo/hooks/metabase/models/setting.clj
  e2e/test/scenarios/question/notebook-native-preview-sidebar.cy.spec.ts
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase-types/store/mocks/qb.ts
  frontend/src/metabase-types/store/qb.ts
  frontend/src/metabase/query_builder/actions/core/initializeQB.ts
  frontend/src/metabase/query_builder/actions/ui.js
  frontend/src/metabase/query_builder/components/view/View/NotebookContainer/NotebookContainer.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/ToggleNativeQueryPreview/ToggleNativeQueryPreview.tsx
  frontend/src/metabase/query_builder/selectors.js
  src/metabase/models/user.clj
Labels: no-backport, .Team/QueryingComponents

#41102 docs - notes on events and timelines
  docs/exploration-and-organization/events-and-timelines.md
  docs/exploration-and-organization/history.md
  docs/exploration-and-organization/images/edit-an-event.png
  docs/exploration-and-organization/images/event-on-a-time-series.png
  docs/exploration-and-organization/images/timeline-sidebar.png
Labels: Type:Documentation, backport

#40657 Legacy MBQL documentation
  .clj-kondo/config.edn
  .dir-locals.el
  modules/drivers/druid/src/metabase/driver/druid/query_processor.clj
  modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj
  src/metabase/db/metadata_queries.clj
  src/metabase/driver/sql/query_processor.clj
  src/metabase/legacy_mbql/normalize.cljc
  src/metabase/legacy_mbql/predicates.cljc
  src/metabase/legacy_mbql/schema.cljc
  src/metabase/legacy_mbql/schema/helpers.cljc
  src/metabase/legacy_mbql/util.cljc
  src/metabase/lib/schema/binning.cljc
  src/metabase/lib/schema/common.cljc
  src/metabase/lib/schema/id.cljc
  src/metabase/lib/schema/literal.cljc
  src/metabase/pulse/markdown.clj
  src/metabase/query_processor/middleware/add_dimension_projections.clj
  src/metabase/query_processor/middleware/fetch_source_query_legacy.clj
  src/metabase/util/malli/doc.clj
  src/metabase/util/malli/registry.cljc
  test/metabase/legacy_mbql/js_test.cljs
  test/metabase/legacy_mbql/normalize_test.cljc
  test/metabase/legacy_mbql/schema_test.cljc
  test/metabase/legacy_mbql/util_test.cljc
  test/metabase/query_processor/middleware/results_metadata_test.clj
Labels: .Team/QueryProcessor, no-backport

#40982 Use window functions for cumulative sum and cumulative count [BigQuery]
  docs/developers-guide/driver-changelog.md
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/test/data/bigquery_cloud_sdk.clj
  src/metabase/driver/sql/query_processor.clj
  src/metabase/lib/convert.cljc
  src/metabase/lib/equality.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/schema/expression.cljc
  src/metabase/lib/stage.cljc
  src/metabase/lib/util.cljc
  src/metabase/lib/walk.cljc
  src/metabase/query_processor/middleware/add_dimension_projections.clj
  src/metabase/query_processor/middleware/auto_bucket_datetimes.clj
  src/metabase/query_processor/middleware/upgrade_field_literals.clj
  src/metabase/query_processor/pivot.clj
  src/metabase/query_processor/preprocess.clj
  src/metabase/query_processor/setup.clj
  src/metabase/query_processor/util/add_alias_info.clj
  src/metabase/query_processor/util/nest_query.clj
  src/metabase/query_processor/util/transformations/nest_breakouts.clj
  src/metabase/util/honey_sql_2.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/lib/convert_test.cljc
  test/metabase/lib/equality_test.cljc
  test/metabase/lib/walk_test.cljc
  test/metabase/query_processor/middleware/add_source_metadata_test.clj
  test/metabase/query_processor/middleware/upgrade_field_literals_test.clj
  test/metabase/query_processor/pivot_test.clj
  test/metabase/query_processor/util/add_alias_info_test.clj
  test/metabase/query_processor/util/nest_query_test.clj
  test/metabase/query_processor/util/transformations/nest_breakouts_test.clj
  test/metabase/query_processor_test/cumulative_aggregation_test.clj
  test/metabase/query_processor_test/nested_queries_test.clj
Labels: .Team/QueryProcessor, no-backport

#41143 Bugfix 38839 manually set axis position
  src/metabase/pulse/render/body.clj
  test/metabase/pulse/render/body_test.clj
Labels: backport, visual, .Team/DashViz

#41082 Rename native query preview sidebar component
  frontend/src/metabase/query_builder/components/notebook/NotebookNativePreview/NotebookNativePreview.tsx
  frontend/src/metabase/query_builder/components/notebook/NotebookNativePreview/index.ts
  frontend/src/metabase/query_builder/components/notebook/NotebookNativePreview/utils.ts
  frontend/src/metabase/query_builder/components/view/NativeQueryPreviewSidebar/index.ts
  frontend/src/metabase/query_builder/components/view/View/NotebookContainer/NotebookContainer.tsx
Labels: no-backport, :broom:, .Team/QueryingComponents

#41164 [backport] serialize result metadata for any card (#41131)
  src/metabase/models/card.clj
  test/metabase/models/card_test.clj
Labels: .Team/BackendComponents, was-backported

#41166 Bump Macaw (now with sanitization)
  deps.edn
Labels: no-backport, .Team/BackendComponents

#40509 Table Picker
  frontend/src/metabase-lib/v1/Question.ts
  frontend/src/metabase-lib/v1/metadata/Schema.ts
  frontend/src/metabase-types/api/schema.ts
  frontend/src/metabase-types/api/table.ts
  frontend/src/metabase/api/database.ts
  frontend/src/metabase/api/table.ts
  frontend/src/metabase/common/components/CollectionPicker/components/CollectionPickerModal.tsx
  frontend/src/metabase/common/components/CollectionPicker/types.ts
  frontend/src/metabase/common/components/DataPicker/components/DataPickerModal.tsx
  frontend/src/metabase/common/components/DataPicker/components/DatabaseList.tsx
  frontend/src/metabase/common/components/DataPicker/components/SchemaList.tsx
  frontend/src/metabase/common/components/DataPicker/components/TableList.tsx
  frontend/src/metabase/common/components/DataPicker/components/TablePicker.tsx
  frontend/src/metabase/common/components/DataPicker/components/index.ts
  frontend/src/metabase/common/components/DataPicker/hooks/index.ts
  frontend/src/metabase/common/components/DataPicker/hooks/useAutoSelectOnlyItem.ts
  frontend/src/metabase/common/components/DataPicker/index.ts
  frontend/src/metabase/common/components/DataPicker/types.ts
  frontend/src/metabase/common/components/DataPicker/utils.ts
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/EntityPickerModal.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/EntityPickerModal.unit.spec.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/TabsView.tsx
  frontend/src/metabase/common/components/EntityPicker/components/ItemList/ItemList.tsx
  frontend/src/metabase/common/components/EntityPicker/components/NestedItemPicker/index.ts
  frontend/src/metabase/containers/DataPicker/types.ts
  frontend/src/metabase/entities/schemas.js
  frontend/src/metabase/query_builder/components/notebook/steps/DataStep/DataStep.tsx
Labels: no-backport, .Team/QueryingComponents

#41080 Convert `ui` actions to TypeScript
  frontend/src/metabase/query_builder/actions/ui.ts
Labels: no-backport, :broom:, .Team/QueryingComponents

#41138 connect the example dashboard id setting to the embedding homepage
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/home/components/EmbedHomepage/EmbedHomepage.stories.tsx
  frontend/src/metabase/home/components/EmbedHomepage/EmbedHomepage.tsx
  frontend/src/metabase/home/components/EmbedHomepage/EmbedHomepageView.tsx
  frontend/src/metabase/home/components/EmbedHomepage/StaticTabContent.tsx
  frontend/src/metabase/home/components/EmbedHomepage/tests/common.unit.spec.tsx
  frontend/src/metabase/home/components/EmbedHomepage/tests/setup.tsx
Labels: .Team/Embedding

#41141 Improve the fetching logic in a notebook native preview
  e2e/test/scenarios/question/notebook-native-preview-sidebar.cy.spec.ts
  frontend/src/metabase/query_builder/components/notebook/NotebookNativePreview/NotebookNativePreview.tsx
Labels: no-backport, .Team/QueryingComponents

#41129 Fix tags for self-referencing entities
  frontend/src/metabase-types/api/activity.ts
  frontend/src/metabase-types/api/bookmark.ts
  frontend/src/metabase-types/api/collection.ts
  frontend/src/metabase-types/api/dashboard.ts
  frontend/src/metabase-types/api/metric.ts
  frontend/src/metabase-types/api/mocks/activity.ts
  frontend/src/metabase-types/api/search.ts
  frontend/src/metabase-types/api/segment.ts
  frontend/src/metabase/api/activity.ts
  frontend/src/metabase/api/api-key.ts
  frontend/src/metabase/api/automagic-dashboards.ts
  frontend/src/metabase/api/bookmark.ts
  frontend/src/metabase/api/card.ts
  frontend/src/metabase/api/collection.ts
  frontend/src/metabase/api/database.ts
  frontend/src/metabase/api/field.ts
  frontend/src/metabase/api/index.ts
  frontend/src/metabase/api/metric.ts
  frontend/src/metabase/api/search.ts
  frontend/src/metabase/api/segment.ts
  frontend/src/metabase/api/table.ts
  frontend/src/metabase/api/tags/constants.ts
  frontend/src/metabase/api/tags/index.ts
  frontend/src/metabase/api/tags/utils.ts
  frontend/src/metabase/api/timeline-event.ts
  frontend/src/metabase/api/timeline.ts
  frontend/src/metabase/common/components/CollectionPicker/components/CollectionPickerModal.tsx
  frontend/src/metabase/common/components/CollectionPicker/types.ts
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/EntityPickerModal.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerSearch/EntityPickerSearch.tsx
  frontend/src/metabase/common/hooks/entity-framework/use-search-list-query/use-search-list-query.unit.spec.tsx
  frontend/src/metabase/containers/DataPicker/DataPickerContainer.tsx
  frontend/src/metabase/containers/NewItemMenu/NewItemMenu.tsx
  frontend/src/metabase/entities/bookmarks.js
  frontend/src/metabase/entities/popular-items.js
  frontend/src/metabase/entities/recent-items.js
  frontend/src/metabase/home/components/HomePage/HomePage.tsx
  frontend/src/metabase/metabot/components/MetabotWidget/MetabotWidget.tsx
  frontend/src/metabase/nav/components/search/SearchResults/SearchResults.tsx
  frontend/src/metabase/palette/hooks/useCommandPaletteBasicActions.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx
  frontend/src/metabase/query_builder/components/dataref/DatabaseSchemasPane.tsx
  frontend/src/metabase/search/components/InfoText/InfoText.unit.spec.tsx
  frontend/src/metabase/search/components/SearchResult/components/ItemIcon.styled.tsx
  frontend/src/metabase/search/components/SearchResult/components/ItemIcon.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilter.unit.spec.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterContent.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterContent.unit.spec.tsx
  frontend/src/metabase/search/components/filters/TypeFilter/TypeFilterDisplay.unit.spec.tsx
  frontend/src/metabase/search/constants.ts
  frontend/src/metabase/search/containers/SearchApp.jsx
  frontend/src/metabase/search/containers/SearchApp.unit.spec.tsx
  frontend/src/metabase/search/types.ts
  frontend/src/metabase/search/utils/enabled-search-type/enabled-search-type.ts
  frontend/src/metabase/services.js
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.tsx
Labels: visual, no-backport, .Team/QueryingComponents

#41167 docs -Fix exporting results list
  docs/questions/sharing/exporting-results.md
Labels: Type:Documentation, backport

#41156 Minimize echarts shape transitions
  frontend/src/metabase/visualizations/echarts/cartesian/option/index.ts
Labels: visual, .Team/DashViz

#41091 Migrate `components/modal.module.css`
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/admin-2/tools/erroring-questions.cy.spec.js
  e2e/test/scenarios/admin/settings/cache.cy.spec.js
  e2e/test/scenarios/collections/permissions.cy.spec.js
  e2e/test/scenarios/collections/personal-collections.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/19744-cc-after-aggregation-limited-filters.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/25189-cc-column-reference-only.cy.spec.js
  e2e/test/scenarios/dashboard-cards/dashboard-drill.cy.spec.js
  e2e/test/scenarios/dashboard-cards/visualization-options.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard-management.cy.spec.js
  e2e/test/scenarios/joins/reproductions/23293-drill-through-implicit-join-add-remove-column.cy.spec.js
  e2e/test/scenarios/organization/timelines-collection.cy.spec.js
  e2e/test/scenarios/permissions/sandboxes.cy.spec.js
  e2e/test/scenarios/question/question-management.cy.spec.js
  e2e/test/scenarios/question/reproductions/17514-ui-overlay.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/18344-subscription-shows-original-question-name.cy.spec.js
  e2e/test/scenarios/visualizations-charts/line-bar-tooltips.cy.spec.js
  e2e/test/scenarios/visualizations-charts/line_chart.cy.spec.js
  frontend/src/metabase/admin/databases/components/DatabaseEditApp/Sidebar/Sidebar.unit.spec.tsx
  frontend/src/metabase/components/Modal/FullPageModal.tsx
  frontend/src/metabase/components/Modal/WindowModal.tsx
  frontend/src/metabase/components/Modal/utils.tsx
  frontend/src/metabase/components/QuestionSavedModal/QuestionSavedModal.tsx
  frontend/src/metabase/css/components/modal.module.css
  frontend/src/metabase/css/dashboard.module.css
  frontend/src/metabase/dashboard/components/DashboardGrid.tsx
  frontend/src/metabase/query_builder/components/SavedQuestionIntroModal.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailWrapper.tsx
Labels: visual, no-backport, .Team/Embedding

#41139 Fix coercing multiple columns from int to float in H2
  src/metabase/driver/h2.clj
  test/metabase/driver/sql_jdbc/sync/describe_database_test.clj
  test/metabase/upload_test.clj
Labels: backport, .Team/BackendComponents

#41137 Be more specific about which sections need a seperator
  frontend/src/metabase/core/components/AccordionList/AccordionListCell.jsx
  frontend/src/metabase/core/components/AccordionList/AccordionListCell.styled.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDatabaseSchemaPicker/DataSelectorDatabaseSchemaPicker.tsx
Labels: no-backport, .Team/QueryingComponents

#41147 [MBQL lib] Don't enforce expression types when converting from legacy
  src/metabase/lib/convert.cljc
  src/metabase/lib/filter.cljc
  src/metabase/lib/query.cljc
  src/metabase/lib/schema/expression.cljc
  src/metabase/lib/schema/filter.cljc
  test/metabase/lib/convert_test.cljc
  test/metabase/query_processor/middleware/annotate_test.clj
Labels: backport

#41205 docs - some minor revisions
  docs/exploration-and-organization/events-and-timelines.md
  docs/exploration-and-organization/history.md
Labels: Type:Documentation, backport

#40937 Fix e2e-tests-admin-ee
  e2e/test/scenarios/admin/settings/localization.cy.spec.js
  frontend/src/metabase/visualizations/components/EChartsRenderer/EChartsRenderer.tsx
Labels: visual, .Team/DashViz

#41213 🚀 🏎️ ⏩Driver tests now take 28 minutes instead of 90 🚀 🏎️ ⏩
  deps.edn
Labels: backport, .Team/QueryProcessor

#41109 fix data labels default settings computation for static viz
  .loki/reference/chrome_laptop_static_viz_ComboChart_Area_Stacked_Auto_Data_Labels.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bars_Breakout_Sorted_With_Negative_Values_Power_Y_Axis.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Line_Log_Y_Scale_Negative.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Custom_Y_Axis_Range.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Default.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Goal_Line.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Histogram_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale_At_One.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Metric_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Ordinal_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale_Multi_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Timeseries_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Data_Labels_Column_Formatting.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Data_Labels_Timeseries.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Log_Y_Scale.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Log_Y_Scale_Negative.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Pow_Y_Scale_Negative_Only.png
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/settings.ts
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/area-stacked-auto-data-labels.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/src/metabase/visualizations/shared/settings/cartesian-chart.ts
Labels: visual, .Team/DashViz

#41103 Use DelayedLoadingAndErrorWrapper component in Admin > Performance
  frontend/src/metabase/admin/performance/components/StrategyEditorForDatabases.tsx
  frontend/src/metabase/admin/performance/hooks/useDelayedLoadingSpinner.tsx
  frontend/src/metabase/components/LoadingAndErrorWrapper/DelayedLoadingAndErrorWrapper.tsx
Labels: no-backport, .Team/AdminWebapp

#40141 Improved pivot QP: use MLv2 and avoid recursive preprocessing (performance improvement)
  src/metabase/api/testing.clj
  src/metabase/driver/sql/query_processor.clj
  src/metabase/lib/breakout.cljc
  src/metabase/lib/core.cljc
  src/metabase/query_processor/middleware/annotate.clj
  src/metabase/query_processor/middleware/normalize_query.clj
  src/metabase/query_processor/pivot.clj
  test/metabase/api/dataset_test.clj
  test/metabase/query_processor/pivot_test.clj
Labels: .Team/QueryProcessor, no-backport

#36068 `<datetime expression> = <date literal string>` should do something sane
  src/metabase/driver/h2.clj
  src/metabase/legacy_mbql/schema.cljc
  src/metabase/lib/schema/expression/arithmetic.cljc
  src/metabase/query_processor/middleware/format_rows.clj
  src/metabase/query_processor/middleware/optimize_temporal_filters.clj
  src/metabase/query_processor/middleware/wrap_value_literals.clj
  test/metabase/driver/h2_test.clj
  test/metabase/driver/sql/parameters/substitute_test.clj
  test/metabase/driver/sql/query_processor_test.clj
  test/metabase/legacy_mbql/schema_test.cljc
  test/metabase/query_processor/middleware/optimize_temporal_filters_test.clj
  test/metabase/query_processor/middleware/wrap_value_literals_test.clj
  test/metabase/query_processor_test/date_bucketing_test.clj
  test/metabase/query_processor_test/date_time_zone_functions_test.clj
  test/metabase/query_processor_test/filter_test.clj
Labels: .Team/QueryProcessor, no-backport

#41210 Fix e2e-tests-custom-column-ee
  e2e/test/scenarios/custom-column/custom-column.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/13289-cc-post-aggregation-zoom-in.cy.spec.js
Labels: .Team/DashViz

#41191 Mitigate some redshift flakes
  enterprise/backend/test/metabase_enterprise/advanced_permissions/driver/impersonation_test.clj
  modules/drivers/redshift/test/metabase/driver/redshift_test.clj
Labels: backport, .Team/BackendComponents

#41231 Upgraded xlsx module
  package.json
  yarn.lock
Labels: backport

#41204 Restore tabs display for embedded dashboard without title
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.tsx
  frontend/src/metabase/public/containers/PublicDashboard/PublicDashboard.jsx
  frontend/src/metabase/public/containers/PublicDashboard/PublicDashboard.styled.tsx
  frontend/src/metabase/public/containers/PublicDashboard/PublicDashboard.unit.spec.tsx
  frontend/src/metabase/public/containers/PublicDashboard/index.ts
  frontend/src/metabase/routes-embed.jsx
  frontend/src/metabase/routes-public.jsx
  frontend/src/metabase/routes.jsx
  frontend/test/__support__/server-mocks/embed.ts
Labels: backport, .Team/Embedding

#40961 Convert PreviewPane to TS
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/PreviewPane/PreviewPane.styled.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/PreviewPane/PreviewPane.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/PreviewPane/PreviewPane.unit.spec.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/PreviewPane/index.ts
Labels: no-backport, .Team/Embedding

#41246 Migrate `base.module.css`
  frontend/src/metabase/admin/datamodel/components/DimensionList/DimensionList.jsx
  frontend/src/metabase/components/ActionButton/ActionButton.jsx
  frontend/src/metabase/containers/dnd/DropArea.jsx
  frontend/src/metabase/css/core/base.module.css
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/query_builder/components/AlertListPopoverContent.jsx
  frontend/src/metabase/query_builder/components/AlertModals/AlertModals.jsx
Labels: no-backport, .Team/Embedding

#41244 Comment out flaky rollback test for MySQL
  test/metabase/db/schema_migrations_test.clj
Labels: backport, .Team/BackendComponents

#41068 Faster driver/describe-database for redshift
  enterprise/backend/test/metabase_enterprise/advanced_permissions/driver/impersonation_test.clj
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  modules/drivers/redshift/test/metabase/driver/redshift_test.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql_jdbc/sync/describe_database.clj
  test/metabase/sync/sync_metadata/comments_test.clj
  test/metabase/sync/sync_metadata/sync_table_privileges_test.clj
Labels: no-backport, .Team/BackendComponents
