Repository metabase/metabase, pull requests merged in 2024-06, with the labels that each got.

#42985 Fix data labels too dense with large single series
  .github/actions/prepare-frontend/action.yml
  .loki/reference/chrome_laptop_static_viz_ComboChart_Area_Stacked_Auto_Data_Labels.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bars_Breakout_Sorted_With_Negative_Values_Power_Y_Axis.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Incorrect_Label_Y_Axis_Split_41285.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Auto_Y_Axis_Exclude_Zero_With_Goal.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Custom_Y_Axis_Range.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Default.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Goal_Line.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Histogram_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale_At_One.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Metric_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Ordinal_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale_Multi_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Timeseries_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Data_Labels_Column_Formatting.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Data_Labels_Timeseries.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Log_Y_Scale.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Log_Y_Scale_Negative.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Pow_Y_Scale_Negative_Only.png
  e2e/test/scenarios/visualizations-charts/combo.cy.spec.js
  e2e/test/scenarios/visualizations-charts/waterfall.cy.spec.js
  frontend/src/metabase/visualizations/echarts/cartesian/chart-measurements/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/types.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/goal-line.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/trend-line.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/utils.ts
  frontend/src/metabase/visualizations/echarts/cartesian/scatter/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/timeline-events/model.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/option/index.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/events.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-chart-debug.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-chart-events.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-models-and-option.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/utils.ts
  patches/echarts+5.5.0.patch
Labels: backport, .Team/DashViz

#43486 🤖 backported "Fix data labels too dense with large single series"
  .github/actions/prepare-frontend/action.yml
  .loki/reference/chrome_laptop_static_viz_ComboChart_Area_Stacked_Auto_Data_Labels.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bars_Breakout_Sorted_With_Negative_Values_Power_Y_Axis.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Incorrect_Label_Y_Axis_Split_41285.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Auto_Y_Axis_Exclude_Zero_With_Goal.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Custom_Y_Axis_Range.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Default.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Goal_Line.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Histogram_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale_At_One.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Metric_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Ordinal_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale_Multi_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Timeseries_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Data_Labels_Column_Formatting.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Data_Labels_Timeseries.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Log_Y_Scale.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Log_Y_Scale_Negative.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Pow_Y_Scale_Negative_Only.png
  e2e/test/scenarios/visualizations-charts/combo.cy.spec.js
  e2e/test/scenarios/visualizations-charts/waterfall.cy.spec.js
  frontend/src/metabase/visualizations/echarts/cartesian/chart-measurements/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/types.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/goal-line.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/trend-line.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/utils.ts
  frontend/src/metabase/visualizations/echarts/cartesian/scatter/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/timeline-events/model.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/option/index.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/events.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-chart-debug.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-chart-events.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-models-and-option.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/utils.ts
  patches/echarts+5.5.0.patch
Labels: was-backported

#43434 Fix mariadb failed to migrate due to having deep nested revision
  src/metabase/db/custom_migrations.clj
  test/metabase/db/custom_migrations_test.clj
Labels: backport, .Team/BackendComponents

#43448 🤖 backported "Fix unit tests running multiple times in watch mode"
  jest.config.js
Labels: was-backported

#43450 🤖 backported "Show the columns for the correct stage when using combine/extract in the presence of an aggregation"
  e2e/test/scenarios/custom-column/cc-shortcuts-combine.cy.spec.js
  e2e/test/scenarios/custom-column/cc-shortcuts-extract.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/column-shortcuts/column-shortcuts.cy.spec.ts
  e2e/test/scenarios/visualizations-tabular/column-shortcuts/combine-column-shortcut.cy.spec.ts
  frontend/src/metabase/query_builder/components/expressions/CombineColumns/CombineColumns.tsx
  frontend/src/metabase/query_builder/components/expressions/CombineColumns/index.tsx
  frontend/src/metabase/query_builder/components/expressions/CombineColumns/util.ts
  frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx
  frontend/src/metabase/query_builder/components/expressions/ExtractColumn/ExtractColumn.tsx
  frontend/src/metabase/query_builder/components/expressions/ExtractColumn/index.tsx
  frontend/src/metabase/query_builder/components/expressions/ExtractColumn/util.ts
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/combine-columns-drill.tsx
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/components/CombineColumnsDrill/CombineColumnsDrill.tsx
  frontend/src/metabase/visualizations/click-actions/actions/CombineColumnsAction/CombineColumnsAction.tsx
  frontend/src/metabase/visualizations/click-actions/actions/ExtractColumn/ExtractColumn.tsx
  src/metabase/lib/js.cljs
  test/metabase/lib/js_test.cljs
Labels: was-backported

#43492 Fix invalid input in the build for release action
  .github/workflows/build-for-release.yml
Labels: .CI & Tests, no-backport, .Team/QueryingComponents

#43499 Revert "Copy question link from dashboard (#42892)"
  e2e/support/commands/api/composite/createDashboardWithQuestions.js
  e2e/support/commands/api/composite/createQuestionAndDashboard.js
  e2e/test/scenarios/dashboard/title-drill.cy.spec.js
  frontend/src/metabase-lib/v1/Question.ts
  frontend/src/metabase-lib/v1/urls.ts
  frontend/src/metabase/css/dashboard.module.css
  frontend/src/metabase/dashboard/actions/getNewCardUrl.ts
  frontend/src/metabase/dashboard/actions/getNewCardUrl.unit.spec.ts
  frontend/src/metabase/dashboard/actions/navigation.js
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/dashboard/components/DashCard/Dashcard.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashCard/types.ts
  frontend/src/metabase/dashboard/components/DashboardGrid.tsx
  frontend/src/metabase/parameters/utils/dashboards.ts
  frontend/src/metabase/parameters/utils/dashboards.unit.spec.js
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboard.tsx
  frontend/src/metabase/visualizations/components/ChartCaption.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
  frontend/src/metabase/visualizations/components/legend/LegendCaption.jsx
  frontend/src/metabase/visualizations/components/legend/LegendCaption.styled.tsx
  frontend/src/metabase/visualizations/components/legend/LegendLabel.module.css
  frontend/src/metabase/visualizations/components/legend/LegendLabel.tsx
  frontend/src/metabase/visualizations/types/visualization.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/CartesianChart.tsx
  frontend/src/metabase/visualizations/visualizations/Funnel/Funnel.tsx
  frontend/src/metabase/visualizations/visualizations/RowChart/RowChart.tsx
Labels: no-backport, .Team/QueryingComponents

#43479 🤖 backported "Fix LDAP admin settings form not allowing modification if a custom port is set"
  frontend/src/metabase/admin/settings/components/SettingsLdapForm.tsx
Labels: was-backported

#43469 fix stacked data labels on ordinal charts
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Stacked_Series_Labels_And_Totals_Ordinal.png
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/bar-stacked-series-labels-and-totals-ordinal.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/chart-measurements/index.ts
Labels: backport, .Team/DashViz

#43487 🤖 backported "Fix mariadb failed to migrate due to having deep nested revision"
  src/metabase/db/custom_migrations.clj
  test/metabase/db/custom_migrations_test.clj
Labels: .Team/BackendComponents, was-backported

#43420 Tag slack users by github handle
  .github/github-slack-map.json
  release/src/slack.ts
Labels: no-backport, .Team/AdminWebapp

#43508 🤖 backported "fix stacked data labels on ordinal charts"
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Stacked_Series_Labels_And_Totals_Ordinal.png
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/bar-stacked-series-labels-and-totals-ordinal.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/chart-measurements/index.ts
Labels: was-backported

#43429 Catch exceptions from driver/database-supports? outside driver code
  .clj-kondo/config.edn
  enterprise/backend/src/metabase_enterprise/advanced_permissions/driver/impersonation.clj
  enterprise/backend/test/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions_test.clj
  src/metabase/actions.clj
  src/metabase/api/card.clj
  src/metabase/api/database.clj
  src/metabase/api/table.clj
  src/metabase/db/metadata_queries.clj
  src/metabase/driver/util.clj
  src/metabase/models/database.clj
  src/metabase/query_processor/middleware/add_implicit_joins.clj
  src/metabase/query_processor/middleware/check_features.clj
  src/metabase/query_processor/middleware/cumulative_aggregations.clj
  src/metabase/query_processor/middleware/parameters/native.clj
  src/metabase/query_processor/middleware/results_metadata.clj
  src/metabase/query_processor/timezone.clj
  src/metabase/sync/analyze/fingerprint.clj
  src/metabase/sync/fetch_metadata.clj
  src/metabase/sync/sync_metadata/fields.clj
  src/metabase/sync/sync_metadata/fks.clj
  src/metabase/sync/sync_metadata/indexes.clj
  src/metabase/sync/sync_metadata/sync_table_privileges.clj
  src/metabase/upload.clj
  src/metabase/xrays/automagic_dashboards/combination.clj
  test/metabase/driver/sql_jdbc/sync/describe_table_test.clj
  test/metabase/driver/util_test.clj
  test/metabase/models/database_test.clj
  test/metabase/models/model_index_test.clj
  test/metabase/query_processor/middleware/parameters/mbql_test.clj
  test/metabase/query_processor/test_util.clj
  test/metabase/query_processor_test/advanced_math_test.clj
  test/metabase/query_processor_test/date_bucketing_test.clj
  test/metabase/query_processor_test/date_time_zone_functions_test.clj
  test/metabase/query_processor_test/timezones_test.clj
  test/metabase/test/data/dataset_definition_test.clj
  test/metabase/upload_test.clj
Labels: backport, .Team/BackendComponents

#43425 Don't throw an exception when a non-existent setting is in the config file
  enterprise/backend/src/metabase_enterprise/advanced_config/file/settings.clj
  enterprise/backend/test/metabase_enterprise/advanced_config/file/settings_test.clj
  src/metabase/models/setting.clj
  src/metabase/public_settings.clj
Labels: backport, .Team/BackendComponents

#43477 measure auto compactness on correct values
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Stacked_Series_Labels_Normalized_Auto_Compactness.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bars_Breakout_Sorted_With_Negative_Values_Power_Y_Axis.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Auto_Y_Axis_Exclude_Zero_With_Goal.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Custom_Y_Axis_Range.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Default.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Goal_Line.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Histogram_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale_At_One.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Metric_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Ordinal_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale_Multi_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Timeseries_X_Scale.png
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/bar-stacked-series-labels-normalized-auto-compactness.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
Labels: backport, .Team/DashViz

#43521 🤖 backported "Don't throw an exception when a non-existent setting is in the config file"
  enterprise/backend/src/metabase_enterprise/advanced_config/file/settings.clj
  enterprise/backend/test/metabase_enterprise/advanced_config/file/settings_test.clj
  src/metabase/models/setting.clj
  src/metabase/public_settings.clj
Labels: was-backported

#43526 Use `actions/github-script@v7` everywhere
  .github/workflows/build-for-release.yml
  .github/workflows/loki-update.yml
Labels: .CI & Tests, no-backport, .Team/QueryingComponents

#43525 Use `actions/checkout@v4` everywhere
  .github/workflows/build-for-release.yml
  .github/workflows/loki-update.yml
  .github/workflows/loki.yml
Labels: .CI & Tests, no-backport, .Team/QueryingComponents

#43519 Combine tabular viz e2e specs
  e2e/test/scenarios/visualizations-tabular/14148-pivot-table-postgres.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/25415-custom-column-drill-through.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/column-shortcuts.cy.spec.ts
  e2e/test/scenarios/visualizations-tabular/column-shortcuts/combine-column-shortcut.cy.spec.ts
  e2e/test/scenarios/visualizations-tabular/reproductions/11249-add-more-series-no-columns.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/11435-time-tooltip-native.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/15353-pivot-settings-change-name-values.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/18976-pivot-table-columns.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/18996-table-image-pagination.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/19373-pivot-wrong-distinct-value-totals.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/21392-chart-many-columns-freeze.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/22206-add-remove-column.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/23076.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/28304-table-columns-unknown.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/28311-sorting-table-columns.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/30039-object-detail-navigation.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/37726-pivot-table-add-column.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/42049-wrong-columns-order.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/42697-pivot-new-breakout.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/6010-metric-filter-drill.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/visualizations-tabular-reproductions.cy.spec.js
Labels: .CI & Tests, no-backport, .Team/AdminWebapp

#43518 Fix bulk action delete button hover contrast
  frontend/src/metabase/collections/components/CollectionBulkActions/ArchivedBulkActions.tsx
  frontend/src/metabase/components/BulkActionBar/BulkActionBar.styled.tsx
Labels: no-backport, .Team/AdminWebapp

#43465 🤖 backported "Handle MySQL quotes when resolving analyzed fields"
  src/metabase/native_query_analyzer.clj
  test/metabase/native_query_analyzer_test.clj
Labels: .Team/BackendComponents, was-backported

#43528 🤖 backported "measure auto compactness on correct values"
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Stacked_Series_Labels_Normalized_Auto_Compactness.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bars_Breakout_Sorted_With_Negative_Values_Power_Y_Axis.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Auto_Y_Axis_Exclude_Zero_With_Goal.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Custom_Y_Axis_Range.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Default.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Goal_Line.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Histogram_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale_At_One.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Metric_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Ordinal_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale_Multi_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Timeseries_X_Scale.png
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/bar-stacked-series-labels-normalized-auto-compactness.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
Labels: was-backported

#43267 docs - druid jdbc and json unfolding
  docs/data-modeling/json-unfolding.md
  docs/databases/connections/druid.md
Labels: Type:Documentation, backport

#42975 docs - note on api change
  docs/developers-guide/api-changelog.md
Labels: Type:Documentation, backport

#42928 fix data labels under trend/goal lines
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Auto_Formatting_Compact.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Auto_Formatting_Full.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Correct_Width_When_Two_Y_Axes.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Data_Labels_Negatives.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Formatting_Full.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Stacked_Labels_Null_Vs_Zero.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bars_Breakout_Sorted_With_Negative_Values_Power_Y_Axis.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Data_Labels_Under_Trend_Goal_Lines_41280.png
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/bar-data-labels-negatives.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/bar-stacked-labels-null-vs-zero.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/data-labels-under-trend-goal-lines-41280.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/constants/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/constants/style.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/util.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/goal-line.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/trend-line.ts
  frontend/src/metabase/visualizations/echarts/cartesian/scatter/option/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/option/index.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-chart-events.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/utils.ts
Labels: backport, .Team/DashViz, loki-update

#43542 🤖 backported "Skip fingerprinting or scanning field values for fields with base_type=type/*"
  src/metabase/models/field_values.clj
  src/metabase/sync/analyze/fingerprint.clj
  test/metabase/models/field_values_test.clj
  test/metabase/sync/analyze/fingerprint_test.clj
Labels: was-backported

#43553 Amend stack values labels control copy
  frontend/src/metabase/visualizations/lib/settings/graph.js
Labels: backport, .Team/DashViz

#43313 [Browse] Unify breadcrumbs into one link
  frontend/src/metabase/browse/components/CollectionBreadcrumbsWithTooltip.styled.tsx
  frontend/src/metabase/browse/components/CollectionBreadcrumbsWithTooltip.tsx
  frontend/src/metabase/browse/components/Ellipsis.tsx
  frontend/src/metabase/browse/components/PathSeparator.tsx
  frontend/src/metabase/components/ResponsiveContainer/ResponsiveContainer.tsx
Labels: backport, .Team/AdminWebapp

#43284 [Browse] Don't show filter icon when no models have been verified
  e2e/test/scenarios/onboarding/home/browse.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/content_verification/ModelFilterControls.tsx
  frontend/src/metabase/browse/components/BrowseModels.tsx
  frontend/src/metabase/browse/components/ModelsTable.tsx
  frontend/src/metabase/components/EntityItem/EntityItem.tsx
Labels: backport, .Team/AdminWebapp

#43220 Previous period comparison shortcut in notebook mode
  enterprise/frontend/src/embedding-sdk/components/private/SdkContentWrapper.tsx
  frontend/src/metabase-lib/index.ts
  frontend/src/metabase-lib/offset.ts
  frontend/src/metabase-lib/temporal_bucket.ts
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.tsx
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.unit.spec.tsx
  frontend/src/metabase/query_builder/components/CompareAggregations/CompareAggregations.tsx
  frontend/src/metabase/query_builder/components/CompareAggregations/components/ColumnPicker/ColumnPicker.module.css
  frontend/src/metabase/query_builder/components/CompareAggregations/components/ColumnPicker/ColumnPicker.tsx
  frontend/src/metabase/query_builder/components/CompareAggregations/components/ColumnPicker/index.ts
  frontend/src/metabase/query_builder/components/CompareAggregations/components/OffsetInput/OffsetInput.module.css
  frontend/src/metabase/query_builder/components/CompareAggregations/components/OffsetInput/OffsetInput.tsx
  frontend/src/metabase/query_builder/components/CompareAggregations/components/OffsetInput/index.ts
  frontend/src/metabase/query_builder/components/CompareAggregations/components/OffsetInput/utils.ts
  frontend/src/metabase/query_builder/components/CompareAggregations/components/ReferenceAggregationPicker/ReferenceAggregationPicker.module.css
  frontend/src/metabase/query_builder/components/CompareAggregations/components/ReferenceAggregationPicker/ReferenceAggregationPicker.tsx
  frontend/src/metabase/query_builder/components/CompareAggregations/components/ReferenceAggregationPicker/index.ts
  frontend/src/metabase/query_builder/components/CompareAggregations/components/index.ts
  frontend/src/metabase/query_builder/components/CompareAggregations/index.ts
  frontend/src/metabase/query_builder/components/CompareAggregations/types.ts
  frontend/src/metabase/query_builder/components/CompareAggregations/utils.ts
  frontend/src/metabase/query_builder/components/notebook/steps/AggregateStep/AggregateStep.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/AddAggregationButton/AddAggregationButton.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/AggregationItem/AggregationItem.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeSidebar.tsx
  frontend/src/metabase/styled-components/containers/GlobalStyles/GlobalStyles.tsx
Labels: no-backport, .Team/QueryingComponents

#43495 refactor public/embed reducers and related code
  enterprise/frontend/src/embedding-sdk/store/index.ts
  frontend/src/metabase/app-embed.js
  frontend/src/metabase/app-main.js
  frontend/src/metabase/app-public.js
  frontend/src/metabase/dashboard/actions/cards.unit.spec.ts
  frontend/src/metabase/reducers-common.ts
  frontend/src/metabase/reducers-main.ts
  frontend/src/metabase/reducers-public.js
  frontend/src/metabase/reducers-public.ts
  frontend/test/__support__/storybook.tsx
  frontend/test/__support__/ui.tsx
Labels: backport, .Team/Embedding

#43573 Update dead jetty docs links
  docs/configuring-metabase/customizing-jetty-webserver.md
  docs/troubleshooting-guide/timeout.md
Labels: backport, .Team/QueryingComponents

#43493 Previous period comparison shortcut in chill mode - "+" button
  frontend/src/metabase/query_builder/components/CompareAggregations/utils.ts
  frontend/src/metabase/ui/components/icons/Icon/icons/index.ts
  frontend/src/metabase/ui/components/icons/Icon/icons/lines.svg
  frontend/src/metabase/visualizations/click-actions/actions/CompareAggregationsAction/CompareAggregationsAction.tsx
  frontend/src/metabase/visualizations/click-actions/actions/CompareAggregationsAction/index.ts
  frontend/src/metabase/visualizations/click-actions/actions/ExtractColumn/index.ts
  frontend/src/metabase/visualizations/click-actions/actions/ExtractColumnAction/ExtractColumnAction.tsx
  frontend/src/metabase/visualizations/click-actions/actions/ExtractColumnAction/index.ts
  frontend/src/metabase/visualizations/click-actions/modes/DefaultMode.ts
  frontend/src/metabase/visualizations/click-actions/modes/EmbeddingSdkMode.ts
Labels: no-backport, .Team/QueryingComponents

#43577 🤖 backported "Update dead jetty docs links"
  docs/configuring-metabase/customizing-jetty-webserver.md
  docs/troubleshooting-guide/timeout.md
Labels: was-backported

#43399 🤖 backported "Update macaw for qualified rename support"
  deps.edn
  src/metabase/models/card.clj
  src/metabase/native_query_analyzer.clj
  src/metabase/native_query_analyzer/replacement.clj
  src/metabase/util.cljc
  test/metabase/models/card_test.clj
  test/metabase/native_query_analyzer/replacement_test.clj
  test/metabase/native_query_analyzer_test.clj
Labels: .Team/BackendComponents, was-backported

#43524 temporarily removes the SameSite=None suggestion box
  enterprise/frontend/src/metabase-enterprise/embedding/components/EmbeddingAppSameSiteCookieDescription/EmbeddingAppSameSiteCookieDescription.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding.unit.spec.tsx
Labels: backport, .Team/Embedding

#43579 Backport "Update dead jetty docs links" to v48
  docs/configuring-metabase/customizing-jetty-webserver.md
  docs/troubleshooting-guide/timeout.md
Labels: .Team/QueryingComponents, was-backported

#43574 🤖 backported "refactor public/embed reducers and related code"
  enterprise/frontend/src/embedding-sdk/store/index.ts
  frontend/src/metabase/app-embed.js
  frontend/src/metabase/app-main.js
  frontend/src/metabase/app-public.js
  frontend/src/metabase/dashboard/actions/cards.unit.spec.ts
  frontend/src/metabase/reducers-common.ts
  frontend/src/metabase/reducers-main.ts
  frontend/src/metabase/reducers-public.js
  frontend/src/metabase/reducers-public.ts
  frontend/test/__support__/storybook.tsx
  frontend/test/__support__/ui.tsx
Labels: was-backported

#43514 Consolidate sharing e2e specs
  e2e/test/scenarios/sharing/approved-domains.cy.spec.js
  e2e/test/scenarios/sharing/downloads/reproductions/10803-timestamp-formatting.cy.spec.js
  e2e/test/scenarios/sharing/downloads/reproductions/18219-temporal-units-not-formatted.cy.spec.js
  e2e/test/scenarios/sharing/downloads/reproductions/18382-old-syntax-missing-renamed-columns.cy.spec.js
  e2e/test/scenarios/sharing/downloads/reproductions/18440-remapped-display-value-dropped.cy.spec.js
  e2e/test/scenarios/sharing/downloads/reproductions/18573-remapped-fields-not-renamed.cy.spec.js
  e2e/test/scenarios/sharing/downloads/reproductions/18729-date-formatting-x-of-y.cy.spec.js
  e2e/test/scenarios/sharing/downloads/reproductions/19889-native-query-export-column-order.cy.spec.js
  e2e/test/scenarios/sharing/downloads/reproductions/28834-modified-native-question.cy.spec.js
  e2e/test/scenarios/sharing/downloads/sharing-download-reproductions.cy.spec.js
  e2e/test/scenarios/sharing/public-sharing.cy.spec.js
  e2e/test/scenarios/sharing/reproductions.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/18009-nodata-creates-subscription-receives-error.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/18344-subscription-shows-original-question-name.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/18352-subscription-int64-value-card.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/18669-test-email-with-parameters.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/20393-public-dashboard-nested-card-with-parameters.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/21559-subscription-bar-sent-as-scalar.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/22524-public-dashboard-updates-after-changing-parameters.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/24223-remove-filter-defaults-on-subscriptions.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/25473-dashboard-text-filter-asking-for-number.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/26988-embedding-dynamic-settings.cy.spec.js
  e2e/test/scenarios/sharing/reproductions/30314-new-subscription-form-state.cy.spec.js
  e2e/test/scenarios/sharing/sharing-reproductions.cy.spec.js
Labels: .CI & Tests, no-backport, .Team/AdminWebapp

#43537 Add build requirements for v50
  release/src/version-helpers.ts
Labels: .Building & Releasing, no-backport, .Team/AdminWebapp

#43350 [Browse] Add brand-colored dot to filter icon when the filter is active
  enterprise/frontend/src/metabase-enterprise/content_verification/ModelFilterControls.tsx
Labels: backport, .Team/AdminWebapp

#43584 🤖 backported "temporarily removes the SameSite=None suggestion box"
  enterprise/frontend/src/metabase-enterprise/embedding/components/EmbeddingAppSameSiteCookieDescription/EmbeddingAppSameSiteCookieDescription.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding.unit.spec.tsx
Labels: was-backported

#43563 [backport] Skip fingerprinting or scanning field values for fields with base_type=type/*
  src/metabase/models/field_values.clj
  src/metabase/sync/analyze/fingerprint.clj
  test/metabase/models/field_values_test.clj
  test/metabase/sync/analyze/fingerprint_test.clj
Labels: .Team/BackendComponents

#43464 Add can_run_adhoc_query to Card hydration
  frontend/src/metabase-lib/v1/Question.ts
  frontend/src/metabase-lib/v1/urls.ts
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase-types/api/mocks/card.ts
  frontend/src/metabase/actions/containers/ActionCreator/ActionContext/QueryActionContextProvider/QueryActionContextProvider.tsx
  frontend/src/metabase/dashboard/actions/navigation.js
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.unit.spec.jsx
  frontend/src/metabase/models/components/ModelDetailPage/ModelInfoSidePanel/ModelInfoSidePanel.tsx
  src/metabase/api/card.clj
  src/metabase/api/dashboard.clj
  src/metabase/models/card.clj
  src/metabase/models/dashboard.clj
  src/metabase/models/interface.clj
  src/metabase/xrays/automagic_dashboards/populate.clj
  test/metabase/api/automagic_dashboards_test.clj
  test/metabase/api/card_test.clj
  test/metabase/models/card_test.clj
  test/metabase/models/interface_test.clj
Labels: backport, .Team/QueryProcessor

#43566 🤖 backported "Amend stack values labels control copy"
  frontend/src/metabase/visualizations/lib/settings/graph.js
Labels: was-backported

#43595 🤖 backported "Add can_run_adhoc_query to Card hydration"
  frontend/src/metabase-lib/v1/Question.ts
  frontend/src/metabase-lib/v1/urls.ts
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase-types/api/mocks/card.ts
  frontend/src/metabase/actions/containers/ActionCreator/ActionContext/QueryActionContextProvider/QueryActionContextProvider.tsx
  frontend/src/metabase/dashboard/actions/navigation.js
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.unit.spec.jsx
  frontend/src/metabase/models/components/ModelDetailPage/ModelInfoSidePanel/ModelInfoSidePanel.tsx
  src/metabase/api/card.clj
  src/metabase/api/dashboard.clj
  src/metabase/models/card.clj
  src/metabase/models/dashboard.clj
  src/metabase/models/interface.clj
  src/metabase/xrays/automagic_dashboards/populate.clj
  test/metabase/api/automagic_dashboards_test.clj
  test/metabase/api/card_test.clj
  test/metabase/models/card_test.clj
  test/metabase/models/interface_test.clj
Labels: was-backported

#42857 docs - caching updates
  docs/configuring-metabase/caching.md
  docs/configuring-metabase/images/data-caching-settings.png
  docs/data-modeling/images/model-caching-custom.png
  docs/data-modeling/models.md
  docs/paid-features/overview.md
  docs/questions/native-editor/writing-sql.md
  docs/questions/query-builder/introduction.md
  docs/troubleshooting-guide/timeout.md
Labels: Type:Documentation, backport

#43551 render static pie chart legend
  frontend/src/metabase/static-viz/components/PieChart/PieChart.tsx
  frontend/src/metabase/static-viz/components/PieChart/legend.tsx
Labels: .Team/DashViz

#43550 render static pie chart
  frontend/src/metabase/static-viz/components/PieChart/PieChart.tsx
  frontend/src/metabase/static-viz/components/PieChart/legend.tsx
  frontend/src/metabase/visualizations/echarts/pie/format.ts
  frontend/src/metabase/visualizations/echarts/pie/option/constants.ts
  frontend/src/metabase/visualizations/echarts/pie/option/index.ts
  package.json
  yarn.lock
Labels: .Team/DashViz

#43549 create chartModel for pie chart
  frontend/src/metabase/lib/arrays.ts
  frontend/src/metabase/static-viz/components/PieChart/PieChart.tsx
  frontend/src/metabase/static-viz/components/PieChart/legend.tsx
  frontend/src/metabase/visualizations/echarts/pie/constants.ts
  frontend/src/metabase/visualizations/echarts/pie/format.ts
  frontend/src/metabase/visualizations/echarts/pie/model/index.ts
  frontend/src/metabase/visualizations/echarts/pie/model/types.ts
  frontend/src/metabase/visualizations/echarts/pie/option/constants.ts
  frontend/src/metabase/visualizations/echarts/pie/option/index.ts
  frontend/src/metabase/visualizations/shared/constants.ts
  frontend/src/metabase/visualizations/shared/settings/pie.ts
  frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.jsx
  package.json
  yarn.lock
Labels: .Team/DashViz

#43548 compute viz settings for static pie chart
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase/lib/arrays.ts
  frontend/src/metabase/static-viz/components/ComboChart/settings.ts
  frontend/src/metabase/static-viz/components/PieChart/PieChart.tsx
  frontend/src/metabase/static-viz/components/PieChart/legend.tsx
  frontend/src/metabase/static-viz/components/PieChart/settings.ts
  frontend/src/metabase/static-viz/components/WaterfallChart/settings.ts
  frontend/src/metabase/static-viz/lib/settings.ts
  frontend/src/metabase/visualizations/echarts/pie/constants.ts
  frontend/src/metabase/visualizations/echarts/pie/format.ts
  frontend/src/metabase/visualizations/echarts/pie/model/index.ts
  frontend/src/metabase/visualizations/echarts/pie/model/types.ts
  frontend/src/metabase/visualizations/echarts/pie/option/constants.ts
  frontend/src/metabase/visualizations/echarts/pie/option/index.ts
  frontend/src/metabase/visualizations/shared/settings/pie.ts
  frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.jsx
  package.json
  yarn.lock
Labels: .Team/DashViz

#43607 loki CI improvements
  .github/file-paths.yaml
  .github/workflows/loki.yml
Labels: backport, .Team/DashViz

#43609 🤖 backported "loki CI improvements"
  .github/file-paths.yaml
  .github/workflows/loki.yml
Labels: was-backported

#43585 remove modified padding on ellipsifyed sidebar items
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/SidebarItems.styled.tsx
Labels: backport, .Team/AdminWebapp

#43264 feat(sdk): font size scaling and adjustment for visualizations
  .loki/reference/chrome_laptop_Visualizations_shared_RowChart_Default.png
  .loki/reference/chrome_laptop_Visualizations_shared_RowChart_Huge_Font.png
  .loki/reference/chrome_laptop_viz_BarChart_Default.png
  .loki/reference/chrome_laptop_viz_BarChart_Embedding_Huge_Font.png
  .loki/reference/chrome_laptop_viz_LineChart_Default.png
  .loki/reference/chrome_laptop_viz_LineChart_Embedding_Huge_Font.png
  enterprise/frontend/src/embedding-sdk/components/private/SdkContentWrapper.tsx
  enterprise/frontend/src/embedding-sdk/lib/theme/default-component-theme.ts
  enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.ts
  enterprise/frontend/src/embedding-sdk/types/theme/index.ts
  enterprise/frontend/src/embedding-sdk/types/theme/private.ts
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/FunnelBarChart/FunnelBarChart.stories.tsx
  frontend/src/metabase/static-viz/components/ScalarChart/ScalarChart.stories.tsx
  frontend/src/metabase/static-viz/components/ScatterPlot/ScatterPlot.stories.tsx
  frontend/src/metabase/static-viz/components/SmartScalar/SmartScalar.stories.tsx
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.stories.tsx
  frontend/src/metabase/static-viz/index.js
  frontend/src/metabase/ui/index.ts
  frontend/src/metabase/visualizations/components/FunnelNormal.styled.tsx
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.module.css
  frontend/src/metabase/visualizations/components/TableInteractive/table-theme-utils.ts
  frontend/src/metabase/visualizations/echarts/cartesian/chart-measurements/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/constants/style.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/series.unit.spec.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/goal-line.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/timeline-events/model.ts
  frontend/src/metabase/visualizations/echarts/cartesian/timeline-events/option.ts
  frontend/src/metabase/visualizations/hooks/use-browser-rendering-context.ts
  frontend/src/metabase/visualizations/shared/components/RowChart/RowChart.stories.tsx
  frontend/src/metabase/visualizations/shared/utils/size-in-px.ts
  frontend/src/metabase/visualizations/shared/utils/size-in-px.unit.spec.ts
  frontend/src/metabase/visualizations/shared/utils/theme.ts
  frontend/src/metabase/visualizations/types/visualization.ts
  frontend/src/metabase/visualizations/visualizations/BarChart/BarChart.stories.tsx
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-models-and-option.ts
  frontend/src/metabase/visualizations/visualizations/Funnel/Funnel.tsx
  frontend/src/metabase/visualizations/visualizations/Funnel/Funnel.unit.spec.jsx
  frontend/src/metabase/visualizations/visualizations/LineChart/LineChart.stories.tsx
  frontend/src/metabase/visualizations/visualizations/RowChart/RowChart.tsx
  frontend/src/metabase/visualizations/visualizations/RowChart/utils/theme.ts
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.stories.tsx
  loki.config.js
  webpack.static-viz.config.js
Labels: no-backport, .Team/Embedding

#43534 docs - license step
  docs/configuring-metabase/setting-up-metabase.md
Labels: Type:Documentation, backport

#43591 🤖 backported "[Browse] Add brand-colored dot to filter icon when the filter is active"
  enterprise/frontend/src/metabase-enterprise/content_verification/ModelFilterControls.tsx
Labels: was-backported

#43567 🤖 backported "[Browse] Unify breadcrumbs into one link"
  frontend/src/metabase/browse/components/CollectionBreadcrumbsWithTooltip.styled.tsx
  frontend/src/metabase/browse/components/CollectionBreadcrumbsWithTooltip.tsx
  frontend/src/metabase/browse/components/Ellipsis.tsx
  frontend/src/metabase/browse/components/PathSeparator.tsx
  frontend/src/metabase/components/ResponsiveContainer/ResponsiveContainer.tsx
Labels: was-backported

#43569 🤖 backported "[Browse] Don't show filter icon when no models have been verified"
  e2e/test/scenarios/onboarding/home/browse.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/content_verification/ModelFilterControls.tsx
  frontend/src/metabase/browse/components/BrowseModels.tsx
  frontend/src/metabase/browse/components/ModelsTable.tsx
  frontend/src/metabase/components/EntityItem/EntityItem.tsx
Labels: was-backported

#43545 Release from tagged test jars
  .github/actions/prepare-frontend/action.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/tag-for-release.yml
  release/src/version-helpers.ts
  release/src/version-helpers.unit.spec.ts
Labels: .Building & Releasing, backport, .Team/AdminWebapp

#43619 Consolidate chart viz e2e specs
  e2e/test/scenarios/visualizations-charts/reproductions/13504-post-aggregation-drill.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/16170-line-mongo-replace-missing-values.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/17524.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/18061-maps-only-nulls-crash-frontend.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/18063-maps-null-location-wrong-tooltip.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/18776-timeseries-hidden-axis-freeze.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/20548-bar-duplicate-y-axis-after-changing-metrics.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/21452-xhr-on-every-char-for-rename.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/21504-pie-settings-formatting.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/21665-multi-series-frontend-reload.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/22527-scatter-negative-values-not-rendered.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/25007-week-tooltip-native.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/25156-invalid-x-axis-series.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/27279-sorting-does-not-apply-to-x-axis.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/27427-static-viz-divide-by-zero.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/30058-32075-map-visualizations.cy.spec.js
  e2e/test/scenarios/visualizations-charts/reproductions/33208-auto-chart-type-after-save.cy.spec.js
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.js
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.ts
Labels: .CI & Tests, no-backport, .Team/AdminWebapp

#43613 Consolidate dashboard e2e specs
  e2e/test/scenarios/dashboard/caching.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard-reproductions.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard_local-only.cy.spec.js
  e2e/test/scenarios/dashboard/permissions.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/12578-prevent-fetching-slow-cards-more-than-one-at-a-time-when-auto-refreshing.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/12926-editing-dashboards-doesnt-cancel-running-queries.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/13736-dashboard-should-work-if-some-cards-are-broken.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/16559-show-recent-dashboard-revision.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/17879-date-parameter-mapping.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/21830-slow-loading-card-viz-options-error.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/28756-toast-to-enable-notifications-when-no-permissions.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/29076-dashboard-card-drill-sandbox.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/31274-dashcard-actions-overlap.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/31697-question-xray-segment.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/31766-corrupted-dashcards-after-save.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/34382-dashboard-back-navigation-preserve-filters.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/35037-recently-viewed-link-editing-dashboard-link-card.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/39863-redundant-queries-on-tab-change.cy.spec.js
  e2e/test/scenarios/dashboard/reproductions/40695-tab-dashcards-display.cy.spec.js
  e2e/test/scenarios/dashboard/text-cards.cy.spec.js
  e2e/test/scenarios/dashboard/text-dashcards.cy.spec.js
Labels: .CI & Tests, no-backport

#43527 Combine e2e native filter specs
  e2e/test/scenarios/native-filters/native-filters-reproductions.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/11480.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/11580.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/12228.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/12581.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/13961.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/14302.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/15163.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/15444.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/15460.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/15700.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/15981.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/16739.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/16756.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/17019.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/17490.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/21160.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/21246.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/27257.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/29786.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/31606.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/34129.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/40232-dragging-filters.cy.spec.js
  e2e/test/scenarios/native-filters/reproductions/9357.cy.spec.js
  e2e/test/scenarios/native-filters/sql-field-filter-date.cy.spec.js
  e2e/test/scenarios/native-filters/sql-field-filter-number.cy.spec.js
  e2e/test/scenarios/native-filters/sql-field-filter-string.cy.spec.js
  e2e/test/scenarios/native-filters/sql-field-filter-types.cy.spec.js
Labels: .CI & Tests, no-backport, .Team/AdminWebapp

#43616 Consolidate custom column e2e specs
  e2e/test/scenarios/custom-column/cc-data-type.cy.spec.js
  e2e/test/scenarios/custom-column/cc-error-feedback.cy.spec.js
  e2e/test/scenarios/custom-column/cc-expression-editor.cy.spec.js
  e2e/test/scenarios/custom-column/cc-help-text.cy.spec.js
  e2e/test/scenarios/custom-column/cc-shortcuts-combine.cy.spec.js
  e2e/test/scenarios/custom-column/cc-shortcuts-extract.cy.spec.js
  e2e/test/scenarios/custom-column/cc-shortcuts.cy.spec.js
  e2e/test/scenarios/custom-column/custom-column-reproductions.cy.spec.js
  e2e/test/scenarios/custom-column/custom-column.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/12445-cc-mysql-apply-substring.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/13289-cc-post-aggregation-zoom-in.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/13751-cc-allow-strings-in-filter.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/14517-cc-do-not-remove-regex-escape-chars.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/14843-cc-apply-filter-not-equal-to.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/18069-cc-sum-aggregation-dimension-type.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/18747-cc-connected-to-dashboard-parameter.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/18814-cc-used-in-aggregation-for-nested-query.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/19744-cc-after-aggregation-limited-filters.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/19745-cc-nested-query-remove-expressions.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/20229-cc-missing-if-all-columns-not-selected.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/21135-cc-same-name-as-existing-column.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/21513-cc-confusion-field-function.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/23862-cc-group-by-nested.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/24922-cc-case-segment.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/25189-cc-column-reference-only.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/27745-cc-numeric-missing-summarize.cy.spec.js
  e2e/test/scenarios/custom-column/reproductions/32032-cc-quick-filter-drill.cy.spec.js
Labels: no-backport, .Team/AdminWebapp

#43552 Consolidate permissions e2e specs
  e2e/test/scenarios/permissions/create-queries.cy.spec.js
  e2e/test/scenarios/permissions/create-queries/granular.cy.spec.js
  e2e/test/scenarios/permissions/create-queries/no.cy.spec.js
  e2e/test/scenarios/permissions/create-queries/query-builder-and-native.cy.spec.js
  e2e/test/scenarios/permissions/permissions-reproductions.cy.spec.js
  e2e/test/scenarios/permissions/permissions-reproductions.cy.spec.ts
  e2e/test/scenarios/permissions/reproductions/13347-cannot-select-saved-question-in-database-without-data-permissions.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/14873-regextract-in-sandboxed-table.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/17763-cannot-edit-granular-after-block.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/17777-hidden-tables-not-available.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/19603-archived-sub-collection-shows-up-in-permissions.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/20436-incorrect-display-of-database-permissions-level.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/22447-illogical-UI-elements-for-nodata.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/22473-cannot-unsubscribe-from-notifications-without-collection-perms.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/22695-search-databases-no-permissions.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/22726-readonly-collection-duplicate-question.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/22727-readonly-collection-offered-on-save.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/23981-root-collection-breadcrumbs.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/24966-saved-native-q-field-values.cy.spec.js
  e2e/test/scenarios/permissions/reproductions/39221-fetch-settings-only-if-admin.cy.spec.ts
  e2e/test/scenarios/permissions/view-data.cy.spec.js
  e2e/test/scenarios/permissions/view-data/blocked.cy.spec.js
  e2e/test/scenarios/permissions/view-data/granular.cy.spec.js
  e2e/test/scenarios/permissions/view-data/impersonated.cy.spec.js
  e2e/test/scenarios/permissions/view-data/legacy-no-self-service.cy.spec.js
  e2e/test/scenarios/permissions/view-data/sandboxed.cy.spec.ts
  e2e/test/scenarios/permissions/view-data/unrestricted.cy.spec.js
Labels: .CI & Tests, no-backport, .Team/AdminWebapp

#43612 docs - update env var docs
  docs/configuring-metabase/environment-variables.md
  src/metabase/cmd/resources/other-env-vars.md
Labels: Type:Documentation, no-backport

#43546 Fix new collection modal auto-focus moving
  frontend/src/metabase/collections/components/CreateCollectionForm/CreateCollectionForm.tsx
Labels: backport, .Team/AdminWebapp

#43624 🤖 backported "Release from tagged test jars"
  .github/actions/prepare-frontend/action.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/tag-for-release.yml
  release/src/version-helpers.ts
  release/src/version-helpers.unit.spec.ts
Labels: was-backported

#43635 Make Backports Automerge Again
  .github/workflows/auto-backport.yml
Labels: .CI & Tests, backport, .Team/AdminWebapp

#43636 🤖 backported "Make Backports Automerge Again"
  .github/workflows/auto-backport.yml
Labels: was-backported

#43522 [cache] config should be editable if entity is accessible
  enterprise/backend/test/metabase_enterprise/cache/cache_test.clj
  src/metabase/api/cache.clj
  test/metabase/api/cache_test.clj
Labels: backport, .Team/BackendComponents

#43639 🤖 backported "[cache] config should be editable if entity is accessible"
  enterprise/backend/test/metabase_enterprise/cache/cache_test.clj
  src/metabase/api/cache.clj
  test/metabase/api/cache_test.clj
Labels: was-backported

#43588 Fix flaky `interactive-embedding.cy.spec.js`
  e2e/support/config.js
  e2e/test/scenarios/embedding/interactive-embedding.cy.spec.js
Labels: backport, .Team/Embedding

#43570 Add inbox as testing context to debug flaky pulse tests
  test/metabase/pulse_test.clj
Labels: no-backport, .Team/BackendComponents

#43586 Convert Pagination Controls to TS
  enterprise/frontend/src/metabase-enterprise/audit_app/containers/AuditTable.jsx
  frontend/src/metabase/admin/people/components/GroupMembersTable/GroupMembersTable.tsx
  frontend/src/metabase/admin/people/components/PeopleList.jsx
  frontend/src/metabase/admin/tasks/containers/ModelCacheRefreshJobs/ModelCacheRefreshJobs.tsx
  frontend/src/metabase/admin/tasks/containers/TasksApp.tsx
  frontend/src/metabase/collections/components/CollectionContent/CollectionContentView.tsx
  frontend/src/metabase/components/PaginationControls/PaginationControls.jsx
  frontend/src/metabase/components/PaginationControls/PaginationControls.tsx
  frontend/src/metabase/components/PaginationControls/PaginationControls.unit.spec.tsx
  frontend/src/metabase/components/PaginationControls/index.jsx
  frontend/src/metabase/components/PaginationControls/index.tsx
  frontend/src/metabase/containers/UserCollectionList.tsx
  frontend/src/metabase/dashboard/components/QuestionPicker/QuestionList.tsx
  frontend/src/metabase/search/containers/SearchApp.jsx
Labels: no-backport, .Team/Embedding

#43642 Use a more obvious test error message
  enterprise/backend/test/metabase_enterprise/serialization/api_test.clj
Labels: Type:Tech Debt, backport, .Team/BackendComponents

#43634 Fix RowChart shrinks on hover
  e2e/test/scenarios/visualizations-charts/rows.cy.spec.js
  frontend/src/metabase/visualizations/shared/components/RowChart/RowChart.stories.tsx
  frontend/src/metabase/visualizations/visualizations/RowChart/RowChart.tsx
  frontend/src/metabase/visualizations/visualizations/RowChart/utils/theme.ts
Labels: no-backport

#43485 Set min bar height for non-zero bars
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Breakout_With_Line_Series_Stacked_Right_Axis_Only.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Data_Labels_Negatives.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Min_Height_Limit.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Stack_Linear_X_Axis.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Combo_Stacked_Bars_Areas.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Histogram_Ticks_45_Degrees.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Histogram_Ticks_90_Degrees.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Line_Log_Y_Scale.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Log_Y_Scale_Custom_Y_Axis_Range.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Pow_Y_Scale_Custom_Y_Axis_Range.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Combo.png
  .loki/reference/chrome_laptop_viz_LineChart_Default.png
  .loki/reference/chrome_laptop_viz_LineChart_Embedding_Huge_Font.png
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/bar-min-height-limit.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/scatter/model/index.ts
Labels: backport, .Team/DashViz

#43648 🤖 backported "Use a more obvious test error message"
  enterprise/backend/test/metabase_enterprise/serialization/api_test.clj
Labels: was-backported

#43212 Temporal unit parameters in dashboards
  e2e/test/scenarios/dashboard-filters/temporal-unit-parameters.cy.spec.js
  frontend/src/metabase-lib/temporal_bucket.ts
  frontend/src/metabase-lib/v1/Question.ts
  frontend/src/metabase-lib/v1/parameters/utils/click-behavior.ts
  frontend/src/metabase-lib/v1/parameters/utils/filters.js
  frontend/src/metabase-lib/v1/parameters/utils/mbql.js
  frontend/src/metabase-lib/v1/parameters/utils/mbql.unit.spec.js
  frontend/src/metabase-lib/v1/parameters/utils/operators.ts
  frontend/src/metabase-lib/v1/parameters/utils/parameter-type.ts
  frontend/src/metabase/dashboard/actions/auto-wire-parameters/actions.ts
  frontend/src/metabase/dashboard/actions/auto-wire-parameters/utils.ts
  frontend/src/metabase/dashboard/actions/parameters.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.tsx
  frontend/src/metabase/parameters/components/ParameterSettings/ParameterSettings.tsx
  frontend/src/metabase/parameters/components/ParameterSidebar/ParameterSidebar.tsx
  frontend/src/metabase/parameters/components/ParameterValueWidget.jsx
  frontend/src/metabase/parameters/components/widgets/TemporalUnitWidget/TemporalUnitWidget.tsx
  frontend/src/metabase/parameters/components/widgets/TemporalUnitWidget/index.ts
  frontend/src/metabase/parameters/utils/formatting.ts
  frontend/src/metabase/parameters/utils/mapping-options.ts
  frontend/src/metabase/parameters/utils/parameter-values.ts
  src/metabase/lib/core.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/temporal_bucket.cljc
Labels: no-backport, .Team/QueryingComponents

#43288 🤖 backported "Fix multiple origins support by handling invalid origins"
  src/metabase/server/middleware/security.clj
  test/metabase/server/middleware/security_test.clj
Labels: was-backported

#43632 🤖 backported "Fix new collection modal auto-focus moving"
  frontend/src/metabase/collections/components/CreateCollectionForm/CreateCollectionForm.tsx
Labels: was-backported

#43620 🤖 backported "docs - license step"
  docs/configuring-metabase/setting-up-metabase.md
Labels: was-backported

#43604 🤖 backported "docs - caching updates"
  docs/configuring-metabase/caching.md
  docs/configuring-metabase/images/data-caching-settings.png
  docs/data-modeling/images/model-caching-custom.png
  docs/data-modeling/models.md
  docs/paid-features/overview.md
  docs/questions/native-editor/writing-sql.md
  docs/questions/query-builder/introduction.md
  docs/troubleshooting-guide/timeout.md
Labels: was-backported

#43539 🤖 backported "docs - note on api change"
  docs/developers-guide/api-changelog.md
Labels: was-backported

#43623 Put New Tests in Flake Jail + Parole Well Behaved Tests
  e2e/test/scenarios/binning/qb-explicit-joins.cy.spec.js
  e2e/test/scenarios/collections/collection-items-listing.cy.spec.js
  e2e/test/scenarios/dashboard-cards/dashboard-drill.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-sql-text-category.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard-reproductions.cy.spec.js
  e2e/test/scenarios/filters-reproductions/dashboard-filters-reproductions.cy.spec.js
  e2e/test/scenarios/models/models-metadata.cy.spec.js
  e2e/test/scenarios/native/native_subquery.cy.spec.js
  e2e/test/scenarios/organization/bookmarks-question.cy.spec.js
  e2e/test/scenarios/permissions/sandboxes.cy.spec.js
  e2e/test/scenarios/question/notebook-native-preview-sidebar.cy.spec.ts
  e2e/test/scenarios/question/notebook.cy.spec.js
  e2e/test/scenarios/question/offset.cy.spec.ts
  e2e/test/scenarios/question/question-management.cy.spec.js
  e2e/test/scenarios/visualizations-charts/maps.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/pivot_tables.cy.spec.js
Labels: .CI & Tests, no-backport, .Team/AdminWebapp

#43640 🤖 backported "Fix flaky `interactive-embedding.cy.spec.js`"
  e2e/support/config.js
  e2e/test/scenarios/embedding/interactive-embedding.cy.spec.js
Labels: was-backported

#43535 🤖 backported "docs - druid jdbc and json unfolding"
  docs/data-modeling/json-unfolding.md
  docs/databases/connections/druid.md
Labels: was-backported

#43520 🤖 backported "Catch exceptions from driver/database-supports? outside driver code"
  .clj-kondo/config.edn
  enterprise/backend/src/metabase_enterprise/advanced_permissions/driver/impersonation.clj
  enterprise/backend/test/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions_test.clj
  src/metabase/actions.clj
  src/metabase/api/card.clj
  src/metabase/api/database.clj
  src/metabase/api/table.clj
  src/metabase/db/metadata_queries.clj
  src/metabase/driver/util.clj
  src/metabase/models/database.clj
  src/metabase/query_processor/middleware/add_implicit_joins.clj
  src/metabase/query_processor/middleware/check_features.clj
  src/metabase/query_processor/middleware/cumulative_aggregations.clj
  src/metabase/query_processor/middleware/parameters/native.clj
  src/metabase/query_processor/middleware/results_metadata.clj
  src/metabase/query_processor/timezone.clj
  src/metabase/sync/analyze/fingerprint.clj
  src/metabase/sync/fetch_metadata.clj
  src/metabase/sync/sync_metadata/fields.clj
  src/metabase/sync/sync_metadata/fks.clj
  src/metabase/sync/sync_metadata/indexes.clj
  src/metabase/sync/sync_metadata/sync_table_privileges.clj
  src/metabase/upload.clj
  src/metabase/xrays/automagic_dashboards/combination.clj
  test/metabase/driver/sql_jdbc/sync/describe_table_test.clj
  test/metabase/driver/util_test.clj
  test/metabase/models/database_test.clj
  test/metabase/models/model_index_test.clj
  test/metabase/query_processor/middleware/parameters/mbql_test.clj
  test/metabase/query_processor/test_util.clj
  test/metabase/query_processor_test/advanced_math_test.clj
  test/metabase/query_processor_test/date_bucketing_test.clj
  test/metabase/query_processor_test/date_time_zone_functions_test.clj
  test/metabase/query_processor_test/timezones_test.clj
  test/metabase/test/data/dataset_definition_test.clj
  test/metabase/upload_test.clj
Labels: .Team/BackendComponents, was-backported

#43482 🤖 backported "Only log views for cards in a dashboard if the user views the tab"
  e2e/test/scenarios/dashboard/tabs.cy.spec.js
  src/metabase/api/card.clj
  src/metabase/api/dashboard.clj
  src/metabase/api/embed.clj
  src/metabase/api/public.clj
  src/metabase/events/recent_views.clj
  src/metabase/events/schema.clj
  src/metabase/events/view_log.clj
  src/metabase/models/view_log.clj
  test/metabase/api/activity_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/embed_test.clj
  test/metabase/api/public_test.clj
  test/metabase/events/recent_views_test.clj
  test/metabase/events/view_log_test.clj
Labels: .Team/BackendComponents, was-backported

#43506 🤖 backported "Populate Macaw options based on database type"
  src/metabase/native_query_analyzer.clj
Labels: .Team/BackendComponents, was-backported

#43581 fix(sdk): Fix static dashboard API
  enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.tsx
  frontend/src/metabase/dashboard/hoc/DashboardControls.tsx
  frontend/src/metabase/dashboard/hooks/use-embed-display-options.ts
  frontend/src/metabase/dashboard/hooks/use-embed-font.ts
Labels: no-backport, .Team/Embedding

#43500 Previous period comparison shortcut in chill mode - column headers
  frontend/src/metabase-lib/drills.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.tsx
  frontend/src/metabase/query_builder/components/CompareAggregations/CompareAggregations.tsx
  frontend/src/metabase/querying/utils/drills/compare-aggregations-drill/compare-aggregations-drill.tsx
  frontend/src/metabase/querying/utils/drills/compare-aggregations-drill/index.ts
  frontend/src/metabase/querying/utils/drills/constants.ts
  frontend/src/metabase/visualizations/click-actions/actions/CompareAggregationsAction/CompareAggregationsAction.tsx
  frontend/src/metabase/visualizations/click-actions/modes/EmbeddingSdkMode.ts
  frontend/src/metabase/visualizations/components/ClickActions/utils.ts
  frontend/src/metabase/visualizations/types/click-actions.ts
  src/metabase/lib/drill_thru.cljc
  src/metabase/lib/drill_thru/compare_aggregations.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/schema/drill_thru.cljc
  test/metabase/lib/drill_thru_test.cljc
Labels: no-backport, .Team/QueryingComponents

#43496 Demonstrate nesting dynamic redefines
  test/metabase/test.clj
  test/metabase/test/util/dynamic_redefs.clj
  test/metabase/test/util_test.clj
Labels: backport, .Team/BackendComponents

#43580 More wiring and documentation around Macaw
  deps.edn
  src/metabase/native_query_analyzer.clj
  src/metabase/native_query_analyzer/impl.cljc
  src/metabase/native_query_analyzer/replacement.clj
  test/metabase/test/util_test.clj
Labels: backport, .Team/BackendComponents

#43670 🤖 backported "Demonstrate nesting dynamic redefines"
  test/metabase/test.clj
  test/metabase/test/util/dynamic_redefs.clj
  test/metabase/test/util_test.clj
Labels: was-backported

#43657 Expose `attached-dwh` token feature flag to frontend
  enterprise/backend/test/metabase_enterprise/api/session_test.clj
  src/metabase/public_settings.clj
  src/metabase/public_settings/premium_features.clj
Labels: backport

#43679 🤖 backported "docs - column heading options"
  docs/questions/images/column-header-formatting.png
  docs/questions/images/column-heading-options.png
  docs/questions/query-builder/introduction.md
  docs/questions/sharing/visualizations/map.md
  docs/questions/sharing/visualizations/scatterplot-or-bubble-chart.md
  docs/questions/sharing/visualizations/table.md
Labels: was-backported

#43394 Fix long field names handling for series names and in the model editor
  frontend/src/metabase/core/components/Input/Input.styled.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetFieldMetadataSidebar/DatasetFieldMetadataSidebar.jsx
Labels: backport, .Team/DashViz

#43680 🤖 backported "Performance fix for getUrlWithParameters when there are no parameters"
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/23137-click-behavior-not-working-for-gauge-and-progress.cy.spec.js
  frontend/src/metabase-lib/v1/Question.ts
  frontend/src/metabase-lib/v1/urls.ts
Labels: was-backported

#43682 🤖 backported "Fix long field names handling for series names and in the model editor"
  frontend/src/metabase/core/components/Input/Input.styled.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetFieldMetadataSidebar/DatasetFieldMetadataSidebar.jsx
Labels: was-backported

#43678 🤖 backported "Expose `attached-dwh` token feature flag to frontend"
  enterprise/backend/test/metabase_enterprise/api/session_test.clj
  src/metabase/public_settings.clj
  src/metabase/public_settings/premium_features.clj
Labels: was-backported

#43610 Add E2E reproduction for #39150
  e2e/test/scenarios/models/reproductions.cy.spec.ts
Labels: support/Repro, backport, .Team/QueryingComponents

#43668 Fix column scaling ("Multiply by a number") bugs
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Auto_Formatting_Compact.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Auto_Formatting_Full.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Formatting_Full.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Stacked_Total_Formatted_Values.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Custom_Y_Axis_Range_With_Column_Scaling.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Y_Axis_Compact_Without_Data_Labels.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Auto_Y_Axis_Exclude_Zero_With_Goal.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Custom_Y_Axis_Range.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Custom_Y_Axis_Range_With_Column_Scaling.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Default.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Goal_Line.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Histogram_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale_At_One.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Metric_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Ordinal_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale_Multi_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Timeseries_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Custom_Y_Axis_Range_With_Column_Scaling.png
  .loki/reference/chrome_laptop_static_viz_WaterfallChart_Data_Labels_Column_Formatting.png
  .loki/reference/chrome_laptop_viz_LineChart_Embedding_Huge_Font.png
  e2e/test/scenarios/visualizations-charts/bar_chart.cy.spec.js
  frontend/src/metabase/lib/formatting/types.ts
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/custom-y-axis-range-with-column-scaling.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/static-viz/components/RowChart/RowChart.tsx
  frontend/src/metabase/static-viz/components/ScatterPlot/ScatterPlot.stories.tsx
  frontend/src/metabase/static-viz/components/ScatterPlot/stories-data/custom-y-axis-range-with-column-scaling.json
  frontend/src/metabase/static-viz/components/ScatterPlot/stories-data/index.ts
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.stories.tsx
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/custom-y-axis-range-with-column-scaling.json
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/index.ts
  frontend/src/metabase/static-viz/lib/format.ts
  frontend/src/metabase/visualizations/components/ChartTooltip/KeyValuePairChartTooltip/KeyValuePairChartTooltip.tsx
  frontend/src/metabase/visualizations/components/ChartTooltip/utils.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/util.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/scatter/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/index.ts
  frontend/src/metabase/visualizations/lib/tooltip.ts
  frontend/src/metabase/visualizations/shared/utils/data.ts
  frontend/src/metabase/visualizations/shared/utils/data.unit.spec.ts
  frontend/src/metabase/visualizations/types/hover.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/events.ts
  frontend/src/metabase/visualizations/visualizations/RowChart/RowChart.tsx
  frontend/src/metabase/visualizations/visualizations/RowChart/utils/format.ts
Labels: backport, .Team/DashViz

#43692 move github-slack-map to fix release script build
  release/github-slack-map.json
  release/src/slack.ts
Labels: .Building & Releasing, no-backport, .Team/DevEx

#43272 Remove serdes support for legacy metrics
  docs/api-documentation.md
  docs/api/legacy-metric.md
  docs/developers-guide/api-changelog.md
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/src/metabase_enterprise/serialization/dump.clj
  enterprise/backend/src/metabase_enterprise/serialization/load.clj
  enterprise/backend/src/metabase_enterprise/serialization/names.clj
  enterprise/backend/src/metabase_enterprise/serialization/serialize.clj
  enterprise/backend/src/metabase_enterprise/serialization/upsert.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/models.clj
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/load_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/names_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/serialize_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/test_util.clj
  enterprise/backend/test/metabase_enterprise/serialization/upsert_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/extract_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj
  src/metabase/cmd/copy.clj
  src/metabase/models/legacy_metric.clj
  test/metabase/cmd/copy_test.clj
Labels: no-backport

#43401 🤖 backported "Remove Google Analytics driver"
  .clj-kondo/config.edn
  .github/workflows/drivers-stress-test.yml
  .github/workflows/drivers.yml
  bin/build/src/i18n/enumerate.clj
  deps.edn
  docs/databases/connections/google-analytics.md
  docs/developers-guide/drivers/multimethods.md
  docs/questions/query-builder/expressions/converttimezone.md
  docs/questions/query-builder/expressions/datetimediff.md
  docs/questions/sharing/visualizations/pivot-table.md
  docs/questions/start.md
  modules/drivers/deps.edn
  modules/drivers/druid/test/metabase/driver/druid/execute_test.clj
  modules/drivers/googleanalytics/deps.edn
  modules/drivers/googleanalytics/resources/metabase-plugin.yaml
  modules/drivers/googleanalytics/src/metabase/driver/google.clj
  modules/drivers/googleanalytics/src/metabase/driver/googleanalytics.clj
  modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/client.clj
  modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/execute.clj
  modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/metadata.clj
  modules/drivers/googleanalytics/src/metabase/driver/googleanalytics/query_processor.clj
  modules/drivers/googleanalytics/test/metabase/driver/google_test.clj
  modules/drivers/googleanalytics/test/metabase/driver/googleanalytics/execute_test.clj
  modules/drivers/googleanalytics/test/metabase/driver/googleanalytics/query_processor_test.clj
  modules/drivers/googleanalytics/test/metabase/driver/googleanalytics_test.clj
  resources/automagic_dashboards/table/GoogleAnalyticsTable.yaml
  src/metabase/analyze/classifiers/name.clj
  src/metabase/driver/util.clj
  src/metabase/legacy_mbql/util.cljc
  src/metabase/lib/schema.cljc
  src/metabase/types.cljc
  src/metabase/xrays/automagic_dashboards/core.clj
  src/metabase/xrays/automagic_dashboards/dashboard_templates.clj
  src/metabase/xrays/automagic_dashboards/interesting.clj
  src/metabase/xrays/automagic_dashboards/names.clj
  src/metabase/xrays/automagic_dashboards/util.clj
  test/metabase/legacy_mbql/normalize_test.cljc
  test/metabase/lib/convert_test.cljc
  test/metabase/lib/util/match_test.cljc
  test/metabase/query_processor/middleware/annotate_test.clj
  test/metabase/query_processor/middleware/expand_macros_test.clj
  test/metabase/query_processor/test_util.clj
  test/metabase/xrays/automagic_dashboards/dashboard_templates_test.clj
  test/metabase/xrays/automagic_dashboards/interesting_test.clj
Labels: was-backported

#43656 Followed-up tasks for changelog generation
  .github/workflows/release-embedding-sdk.yml
Labels: backport, .Team/Embedding

#43719 🤖 backported "Followed-up tasks for changelog generation"
  .github/workflows/release-embedding-sdk.yml
Labels: was-backported

#43653 Time-over-time comparison - Unit tests
  frontend/src/metabase-lib/test-helpers.ts
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.unit.spec.tsx
  frontend/src/metabase/query_builder/components/CompareAggregations/CompareAggregations.unit.spec.tsx
Labels: no-backport, .Team/QueryingComponents

#43673 🤖 backported "More wiring and documentation around Macaw"
  deps.edn
  src/metabase/native_query_analyzer.clj
  src/metabase/native_query_analyzer/impl.cljc
  src/metabase/native_query_analyzer/replacement.clj
  test/metabase/test/util_test.clj
Labels: was-backported

#43589 Analytic events for time-over-time comparison
  e2e/test/scenarios/question/column-compare.cy.spec.ts
  frontend/src/metabase-lib/extractions.ts
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.tsx
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.unit.spec.tsx
  frontend/src/metabase/query_builder/components/CompareAggregations/components/ColumnPicker/ColumnPicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/AggregateStep/AggregateStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeSidebar.unit.spec.tsx
  frontend/src/metabase/querying/analytics.ts
  frontend/src/metabase/querying/utils/drills/compare-aggregations-drill/compare-aggregations-drill.tsx
  frontend/src/metabase/visualizations/click-actions/actions/CompareAggregationsAction/CompareAggregationsAction.tsx
  snowplow/iglu-client-embedded/schemas/com.metabase/question/jsonschema/1-0-6
Labels: no-backport, .Team/QueryingComponents

#43675 Fetch ad-hoc query metadata on the BE
  enterprise/frontend/src/metabase-enterprise/sandboxes/components/AttributeMappingEditor/AttributeMappingEditor.tsx
  enterprise/frontend/src/metabase-enterprise/sandboxes/components/EditSandboxingModal/EditSandboxingModal.tsx
  enterprise/frontend/src/metabase-enterprise/sandboxes/components/EditSandboxingModal/EditSandboxingModal.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/sandboxes/utils.ts
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase-types/guards/card.ts
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataFieldSettings/MetadataFieldSettings.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataTable/MetadataTable.tsx
  frontend/src/metabase/api/automagic-dashboards.ts
  frontend/src/metabase/api/card.ts
  frontend/src/metabase/api/dashboard.ts
  frontend/src/metabase/api/dataset.ts
  frontend/src/metabase/api/tags/utils.ts
  frontend/src/metabase/entities/dashboards.js
  frontend/src/metabase/entities/questions.js
  frontend/src/metabase/entities/tables.js
  frontend/src/metabase/lib/entities.js
  frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceTypeModal.tsx
  frontend/src/metabase/query_builder/components/dataref/QuestionPane/QuestionPane.tsx
  frontend/src/metabase/query_builder/containers/test-utils.tsx
  frontend/src/metabase/questions/actions.ts
  frontend/src/metabase/redux/metadata.js
  frontend/src/metabase/redux/metadata.unit.spec.js
  frontend/test/__support__/server-mocks/dataset.ts
  src/metabase/api/dataset.clj
  src/metabase/api/query_metadata.clj
  test/metabase/api/dataset_test.clj
Labels: backport, .Team/QueryingComponents

#43727 Update README to reflect API changes in Static Dashboard
  enterprise/frontend/src/embedding-sdk/README.md
  enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.tsx
Labels: no-backport, .Team/Embedding

#43660 Fix OSS tests in CI
  e2e/support/helpers/e2e-enterprise-helpers.js
  e2e/support/helpers/e2e-misc-helpers.js
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/admin-2/tools/erroring-questions.cy.spec.js
  e2e/test/scenarios/admin/settings/settings.cy.spec.js
  e2e/test/scenarios/admin/troubleshooting/help.cy.spec.js
  e2e/test/scenarios/collections/instance-analytics.cy.spec.js
  e2e/test/scenarios/models/reproductions.cy.spec.js
  e2e/test/scenarios/native/snippets/snippet-permissions.cy.spec.js
  e2e/test/scenarios/permissions/admin-permissions.cy.spec.js
  e2e/test/scenarios/permissions/permissions-reproductions.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions-2.cy.spec.js
  e2e/test/scenarios/question/new.cy.spec.js
  e2e/test/scenarios/question/notebook-data-source.cy.spec.ts
  e2e/test/scenarios/sharing/subscriptions.cy.spec.js
Labels: .CI & Tests, backport, .Team/DevEx

#43637 Backport reminder bot
  .github/workflows/release-status.yml
  release/.eslintrc
  release/src/backports.ts
  release/src/index.ts
  release/src/release-notes.ts
  release/src/slack.ts
  release/src/types.ts
Labels: .CI & Tests, no-backport, .Team/DevEx

#43681 docs - models and caching
  docs/configuring-metabase/caching.md
  docs/data-modeling/images/cache-model-schema.png
  docs/data-modeling/model-persistence.md
  docs/data-modeling/models.md
  docs/paid-features/overview.md
  e2e/test/scenarios/admin/databases/reproductions/26470-model-cache-enable-button.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/caching/components/ModelPersistenceConfiguration.tsx
  enterprise/frontend/src/metabase-enterprise/model_persistence/index.ts
  frontend/src/metabase/admin/databases/components/DatabaseEditApp/Sidebar/ModelCachingControl/ModelCachingControl.tsx
  frontend/src/metabase/admin/databases/components/DatabaseEditApp/Sidebar/Sidebar.unit.spec.tsx
Labels: Type:Documentation, backport

#43723 [serdes] do not output exceptions used only for api tests
  enterprise/backend/src/metabase_enterprise/serialization/api.clj
  enterprise/backend/test/metabase_enterprise/serialization/api_test.clj
  src/metabase/logger.clj
Labels: backport, .Team/BackendComponents

#43731 add inbox as testing context for more pulse tests
  test/metabase/pulse_test.clj
Labels: no-backport, .Team/BackendComponents

#43735 Update SDK readme to reference newer RC version
  enterprise/frontend/src/embedding-sdk/README.md
Labels: no-backport, .Team/Embedding

#43733 🤖 backported "[serdes] do not output exceptions used only for api tests"
  enterprise/backend/src/metabase_enterprise/serialization/api.clj
  enterprise/backend/test/metabase_enterprise/serialization/api_test.clj
  src/metabase/logger.clj
Labels: was-backported

#43734 Update SDK version to 0.1.7
  enterprise/frontend/src/embedding-sdk/CHANGELOG.md
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: no-backport

#43625 Batch load card metadata
  enterprise/backend/src/metabase_enterprise/sandbox/api/table.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/table_test.clj
  src/metabase/api/card.clj
  src/metabase/api/dashboard.clj
  src/metabase/api/field.clj
  src/metabase/api/query_metadata.clj
  src/metabase/api/table.clj
  src/metabase/models/collection/root.clj
  src/metabase/models/revision/last_edit.clj
Labels: backport, .Team/QueryProcessor

#43472 make compact formatting consistent across all series
  .loki/reference/chrome_laptop_static_viz_ComboChart_Combo_Data_Labels_Auto_Compactness_Propagates_From_Line.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Combo_Data_Labels_Auto_Compactness_Propagates_From_Totals.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Auto_Y_Axis_Exclude_Zero_With_Goal.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Custom_Y_Axis_Range.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Custom_Y_Axis_Range_With_Column_Scaling.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Default.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Goal_Line.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Histogram_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale_At_One.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Metric_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Ordinal_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale_Multi_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Timeseries_X_Scale.png
  .loki/reference/chrome_laptop_viz_LineChart_Embedding_Huge_Font.png
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/settings.ts
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/combo-data-labels-auto-compactness-propagates-from-line.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/combo-data-labels-auto-compactness-propagates-from-totals.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/scatter/model/index.ts
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/src/metabase/visualizations/shared/settings/cartesian-chart.ts
Labels: backport, .Team/DashViz

#43286 [Browse] Show Browse models link in nav only when there are models
  frontend/src/metabase/browse/components/BrowseModels.tsx
  frontend/src/metabase/browse/test-utils.ts
  frontend/src/metabase/common/hooks/use-fetch-models.tsx
  frontend/src/metabase/common/hooks/use-has-models.tsx
  frontend/src/metabase/components/LoadingAndErrorWrapper/DelayedLoadingAndErrorWrapper.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbar.unit.spec.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/BrowseNavSection.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarView.tsx
  frontend/src/metabase/nav/containers/Navbar.unit.spec.tsx
Labels: backport, .Team/AdminWebapp

#43736 Upgrade to TypeScript v5.4
  .storybook/main.js
  enterprise/frontend/src/embedding-sdk/components/private/PublicComponentWrapper/withPublicComponentWrapper.tsx
  enterprise/frontend/src/embedding-sdk/hooks/private/use-init-data.ts
  frontend/src/metabase-lib/filter.ts
  frontend/src/metabase/admin/people/containers/AdminPeopleApp.tsx
  frontend/src/metabase/core/components/TabRow/TabRow.tsx
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/SidebarLink.tsx
  package.json
  tsconfig.base.json
  yarn.lock
Labels: dependencies, no-backport, .Team/AdminWebapp

#43750 use correct github api for CI
  release/src/backports.ts
Labels: no-backport, .Team/DevEx

#43754 [docs] update list of releases
  docs/releases.md
Labels: Type:Documentation, backport

#43757 🤖 backported "[docs] update list of releases"
  docs/releases.md
Labels: was-backported

#43745 🍒 Add E2E reproduction for #39150 to v50
  e2e/test/scenarios/models/reproductions/39150-model-with-same-custom-column-name.cy.spec.ts
Labels: .Team/QueryingComponents, was-backported

#43428 Multi Series Dashcards Render with Filters Applied To All Series
  src/metabase/lib/schema/info.cljc
  src/metabase/pulse.clj
  src/metabase/pulse/render/body.clj
  src/metabase/pulse/util.clj
  test/metabase/pulse/render/body_test.clj
  test/metabase/pulse/render/test_util.clj
Labels: backport, .Team/DashViz

#43747 Hydrate can_run_adhoc_query and address review comments
  src/metabase/api/query_metadata.clj
  src/metabase/models/revision/last_edit.clj
Labels: backport, .Team/QueryProcessor

#43716 Consolidate dashboard-card specs
  e2e/test/scenarios/dashboard-cards/dashboard-card-reproductions.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/15993-click-behavior-question-with-filter-causes-error.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/16334-click-behavior-question-with-filter-changes-viz-type.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/17160-click-behavior-multiple-options.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/18067-click-behavior-boolean-columns.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/18454-card-description.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/20637-add-series-to-dashcard.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/22265-broken-added-series-prevents-editing-card.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/23137-click-behavior-not-working-for-gauge-and-progress.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/27020-27105-static-viz-date-formatting-failures.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/29304-scalar-first-render-size-change.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/31628-responsive-scalars.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/32231-add-incompatible-series.cy.spec.js
Labels: .CI & Tests, no-backport, .Team/DevEx

#43717 Consolidate joins specs
  e2e/test/scenarios/joins/joins-reproductions.cy.spec.js
  e2e/test/scenarios/joins/reproductions/12928-joining-questions-with-joins.cy.spec.js
  e2e/test/scenarios/joins/reproductions/14793-xrays-joins.cy.spec.js
  e2e/test/scenarios/joins/reproductions/15342-mysql-correct-joins-order.cy.spec.js
  e2e/test/scenarios/joins/reproductions/15578-remapped-values-joins.cy.spec.js
  e2e/test/scenarios/joins/reproductions/17710-notebook-incomplete-joins-removed.cy.spec.js
  e2e/test/scenarios/joins/reproductions/17767-cannot-join-on-aggregation-with-implicit-joins.cy.spec.js
  e2e/test/scenarios/joins/reproductions/17968-notebook-join-table-names.cy.spec.js
  e2e/test/scenarios/joins/reproductions/18502-cannot-join-two-saved-questions-same-table.cy.spec.js
  e2e/test/scenarios/joins/reproductions/18512-cannot-join-two-saved-questions-with-same-implicit-explicit-grouped-field.cy.spec.js
  e2e/test/scenarios/joins/reproductions/18589-numeric-binning-in-joins.cy.spec.js
  e2e/test/scenarios/joins/reproductions/18630-field-literals-in-joins.cy.spec.js
  e2e/test/scenarios/joins/reproductions/18818-crash-when-joining-on-custom-column.cy.spec.js
  e2e/test/scenarios/joins/reproductions/20519-cannot-join-on-aggregation-with-implicit-joins-and-nested-query.cy.spec.js
  e2e/test/scenarios/joins/reproductions/22859-multi-nested-joins-wrong-aliasing.cy.spec.js
  e2e/test/scenarios/joins/reproductions/23293-drill-through-implicit-join-add-remove-column.cy.spec.js
  e2e/test/scenarios/joins/reproductions/27380-dashboard-drops-joined-fields-on-zoom-in.cy.spec.js
  e2e/test/scenarios/joins/reproductions/27873-missing-joined-group-by.cy.spec.js
  e2e/test/scenarios/joins/reproductions/29795-native-query-join-question-misses-metadata.cy.spec.js
  e2e/test/scenarios/joins/reproductions/30743-sort-on-breakout-column-crashes.cy.spec.js
  e2e/test/scenarios/joins/reproductions/31769-mlv2-join-dropped.cy.spec.js
Labels: no-backport, .Team/DevEx

#43760 🍒 Manual Backport #43754
  docs/releases.md
Labels: Type:Documentation, was-backported

#43602 Move database role to url parameters from connection properties on Snowflake
  modules/drivers/snowflake/resources/metabase-plugin.yaml
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
Labels: Database/Snowflake, .Backend, backport, .Team/QueryProcessor

#43755 Fix width of save button in cache sidebar (tiny PR)
  enterprise/frontend/src/metabase-enterprise/caching/components/SidebarCacheForm.styled.tsx
  enterprise/frontend/src/metabase-enterprise/caching/components/SidebarCacheForm.tsx
Labels: backport, .Team/AdminWebapp

#43603 Remove dead code: LastEdited
  frontend/src/metabase/browse/components/LastEdited.tsx
Labels: backport, .Team/AdminWebapp

#43718 Combine search e2e specs
  e2e/test/scenarios/search/reproductions/16785-do-not-display-hidden-tables.cy.spec.js
  e2e/test/scenarios/search/reproductions/28788-search-results-overflow.cy.spec.js
  e2e/test/scenarios/search/search.cy.spec.js
Labels: .CI & Tests, no-backport, .Team/DevEx

#43726 🤖 backported "Fetch ad-hoc query metadata on the BE"
  enterprise/frontend/src/metabase-enterprise/sandboxes/components/AttributeMappingEditor/AttributeMappingEditor.tsx
  enterprise/frontend/src/metabase-enterprise/sandboxes/components/EditSandboxingModal/EditSandboxingModal.tsx
  enterprise/frontend/src/metabase-enterprise/sandboxes/components/EditSandboxingModal/EditSandboxingModal.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/sandboxes/utils.ts
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataFieldSettings/MetadataFieldSettings.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataTable/MetadataTable.tsx
  frontend/src/metabase/api/automagic-dashboards.ts
  frontend/src/metabase/api/card.ts
  frontend/src/metabase/api/dashboard.ts
  frontend/src/metabase/api/dataset.ts
  frontend/src/metabase/api/tags/utils.ts
  frontend/src/metabase/entities/dashboards.js
  frontend/src/metabase/entities/questions.js
  frontend/src/metabase/entities/tables.js
  frontend/src/metabase/lib/entities.js
  frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceTypeModal.tsx
  frontend/src/metabase/query_builder/components/dataref/QuestionPane/QuestionPane.tsx
  frontend/src/metabase/query_builder/containers/test-utils.tsx
  frontend/src/metabase/questions/actions.ts
  frontend/src/metabase/redux/metadata.js
  frontend/src/metabase/redux/metadata.unit.spec.js
  frontend/test/__support__/server-mocks/dataset.ts
  src/metabase/api/dataset.clj
  src/metabase/api/query_metadata.clj
  test/metabase/api/dataset_test.clj
Labels: was-backported

#43739 🤖 backported "Batch load card metadata"
  enterprise/backend/src/metabase_enterprise/sandbox/api/table.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/table_test.clj
  src/metabase/api/card.clj
  src/metabase/api/dashboard.clj
  src/metabase/api/field.clj
  src/metabase/api/query_metadata.clj
  src/metabase/api/table.clj
  src/metabase/models/collection/root.clj
  src/metabase/models/revision/last_edit.clj
Labels: was-backported

#43728 Highlight the table cell data in dashboards when the cell is an ID column
  .loki/reference/chrome_laptop_visualizations_TableSimple_Default.png
  frontend/src/metabase/visualizations/components/TableSimple/TableCell.styled.tsx
  frontend/src/metabase/visualizations/components/TableSimple/TableCell.tsx
  frontend/src/metabase/visualizations/components/TableSimple/TableSimple.stories.tsx
  frontend/src/metabase/visualizations/components/TableSimple/stories-data/table-simple-orders-with-people.json
  loki.config.js
Labels: backport, visual, .Team/Embedding

#43749 Remove old repro for 39150
  e2e/test/scenarios/models/reproductions.cy.spec.ts
Labels: Type:Tech Debt, .CI & Tests, no-backport, .Team/QueryingComponents

#43296 Fix remaining `tinyint` booleans in MySQL
  resources/migrations/001_update_migrations.yaml
Labels: backport

#43752 Add `ts-pattern` library
  frontend/src/metabase/query_builder/components/dataref/QuestionPane/QuestionPane.tsx
  package.json
  yarn.lock
Labels: no-backport, .Team/AdminWebapp

#43744 🍒 Add E2E reproduction for #39150 to v49
  e2e/test/scenarios/models/reproductions/39150-model-with-same-custom-column-name.cy.spec.ts
Labels: .Team/QueryingComponents, was-backported

#43135 Add events to measure search performance
  e2e/support/helpers/e2e-snowplow-helpers.js
  e2e/test/scenarios/search/search-snowplow.cy.spec.js
  frontend/src/metabase-types/api/search.ts
  frontend/src/metabase/api/search.ts
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerSearch/EntityPickerSearch.tsx
  frontend/src/metabase/containers/AddToDashSelectDashModal/AddToDashSelectDashModal.unit.spec.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/LinkOptions/LinkedEntityPicker/LinkedEntityPicker.unit.spec.tsx
  frontend/src/metabase/nav/components/search/SearchResults/SearchResults.tsx
  frontend/src/metabase/palette/components/PaletteResultItem.tsx
  frontend/src/metabase/palette/components/PaletteResults.tsx
  frontend/src/metabase/palette/hooks/useCommandPalette.tsx
  frontend/src/metabase/search/analytics.ts
  frontend/src/metabase/search/components/SearchResult/SearchResult.tsx
  frontend/src/metabase/search/components/SearchResult/tests/SearchResult-Collections.unit.spec.tsx
  frontend/src/metabase/search/components/SearchResult/tests/SearchResult-Tables.unit.spec.tsx
  frontend/src/metabase/search/components/SearchResult/tests/SearchResult.unit.spec.tsx
  frontend/src/metabase/search/containers/SearchResultSection.tsx
  snowplow/iglu-client-embedded/schemas/com.metabase/search/jsonschema/2-0-0
  src/metabase/api/search.clj
  test/metabase/api/search_test.clj
Labels: backport, .Team/AdminWebapp

#43780 fix timeline events covers series
  frontend/src/metabase/visualizations/echarts/cartesian/constants/style.ts
Labels: backport, .Team/DashViz

#43761 Send more tests to flake jail
  e2e/test/scenarios/custom-column/cc-typing-suggestion.cy.spec.js
  e2e/test/scenarios/embedding/interactive-embedding.cy.spec.js
  e2e/test/scenarios/native-filters/native-filters-reproductions.cy.spec.js
  e2e/test/scenarios/visualizations-charts/line-bar-tooltips.cy.spec.js
Labels: backport, .Team/DevEx

#43730 🤖 backported "Fix OSS tests in CI"
  e2e/support/helpers/e2e-enterprise-helpers.js
  e2e/support/helpers/e2e-misc-helpers.js
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/admin-2/tools/erroring-questions.cy.spec.js
  e2e/test/scenarios/admin/settings/settings.cy.spec.js
  e2e/test/scenarios/admin/troubleshooting/help.cy.spec.js
  e2e/test/scenarios/collections/instance-analytics.cy.spec.js
  e2e/test/scenarios/models/reproductions/19776-data-picker-not-displayed-after-archiving-model.cy.spec.js
  e2e/test/scenarios/native/snippets/snippet-permissions.cy.spec.js
  e2e/test/scenarios/permissions/admin-permissions.cy.spec.js
  e2e/test/scenarios/question/new.cy.spec.js
  e2e/test/scenarios/question/notebook-data-source.cy.spec.ts
  e2e/test/scenarios/question/reproductions/25144-saved-questions-first-question.cy.spec.js
  e2e/test/scenarios/sharing/subscriptions.cy.spec.js
Labels: was-backported
