Repository metabase/metabase, pull requests merged in 2024-12, with the labels that each got.

#50453 Deprecate alert and pulse apis
  docs/developers-guide/api-changelog.md
  enterprise/backend/test/metabase_enterprise/advanced_permissions/api/subscription_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/pulse_test.clj
  src/metabase/api/alert.clj
  src/metabase/api/pulse.clj
  src/metabase/api/routes.clj
  test/metabase/api/pulse_test.clj
Labels: backport, .Team/Workflows

#50707 Fix Quartz rescheduling with multiple triggers
  src/metabase/search/appdb/index.clj
  src/metabase/task.clj
  src/metabase/task/sweep_query_analysis.clj
Labels: backport, .Team/Workflows

#38121 docs: fix log4j configurationFile arg path for docker command
  docs/configuring-metabase/log-configuration.md
Labels: Type:Documentation, backport

#50710 Partially fix flaky native e2e tests
  e2e/test/scenarios/native/native-reproductions.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
Labels: backport, .Team/Querying

#50601 docs: serialization clarification
  docs/installation-and-operation/serialization.md
Labels: Type:Documentation, backport

#50743 docs - update chart list
  docs/questions/sharing/visualizing-results.md
Labels: Type:Documentation, backport

#50754 🤖 backported "docs: serialization clarification"
  docs/installation-and-operation/serialization.md
Labels: was-backported

#50756 Add wzimrin to teams and github-slack-map
  .github/team.json
  release/github-slack-map.json
Labels: backport, .Team/Querying

#50757 🤖 backported "Add wzimrin to teams and github-slack-map"
  .github/team.json
  release/github-slack-map.json
Labels: was-backported

#50755 🤖 backported "docs - update chart list"
  docs/questions/sharing/visualizing-results.md
Labels: was-backported

#50761 Added nvoxland to team config files
  .github/team.json
  release/github-slack-map.json
Labels: no-backport, .Team/AdminWebapp

#50737 Make e2e tests of embedding and sql filters date-invariant
  e2e/test/scenarios/embedding/embedding-reproductions.cy.spec.js
  e2e/test/scenarios/native-filters/helpers/e2e-field-filter-data-objects.js
  e2e/test/scenarios/native-filters/sql-field-filter-types.cy.spec.js
Labels: backport, .Team/AdminWebapp

#50767 🤖 backported "Make e2e tests of embedding and sql filters date-invariant"
  e2e/test/scenarios/embedding/embedding-reproductions.cy.spec.js
  e2e/test/scenarios/native-filters/helpers/e2e-field-filter-data-objects.js
  e2e/test/scenarios/native-filters/sql-field-filter-types.cy.spec.js
Labels: was-backported

#44523 Implement new `EntityObjectLoaderRtkQuery` that uses RTK Query hooks
  frontend/src/metabase/api/collection.ts
  frontend/src/metabase/api/database.ts
  frontend/src/metabase/entities/containers/EntityObjectLoader.jsx
  frontend/src/metabase/entities/containers/index.js
  frontend/src/metabase/entities/containers/rtk-query/EntityObjectLoaderRtkQuery.tsx
  frontend/src/metabase/entities/containers/rtk-query/index.ts
  frontend/src/metabase/entities/containers/rtk-query/types/entities.ts
  frontend/src/metabase/entities/containers/rtk-query/types/index.ts
  frontend/src/metabase/entities/containers/rtk-query/types/rtk.ts
  frontend/src/metabase/entities/databases.js
  frontend/src/metabase/entities/tables.js
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-chart-events.ts
Labels: no-backport, .Team/Querying

#50513 Always show embed sharing option for admins
  e2e/test/scenarios/embedding/embedding-smoketests.cy.spec.js
  e2e/test/scenarios/sharing/public-sharing-embed-button-behavior.cy.spec.js
  frontend/src/metabase/sharing/components/SharingMenu/MenuItems/EmbedMenuItem.tsx
  frontend/src/metabase/sharing/components/SharingMenu/MenuItems/PublicLinkMenuItem.tsx
  frontend/src/metabase/sharing/components/SharingMenu/test/DashboardSharingMenu.unit.spec.tsx
  frontend/src/metabase/sharing/components/SharingMenu/test/QuestionSharingMenu.unit.spec.tsx
Labels: .Team/Embedding

#50709 🤖 backported "Cache static assets without hash length restriction"
  e2e/test/scenarios/embedding/embedding-reproductions.cy.spec.js
  src/metabase/server/request/util.clj
Labels: was-backported

#50590 🤖 backported "fix(sdk): entity picker theming fixes"
  frontend/src/metabase/ui/components/feedback/Skeleton/Skeleton.styled.tsx
  frontend/src/metabase/ui/components/inputs/SegmentedControl/SegmentedControl.styled.tsx
  frontend/src/metabase/ui/components/navigation/NavLink/NavLink.styled.tsx
Labels: was-backported

#50705 🤖 backported "feat(sdk): add withChartTypeSelector prop to InteractiveQuestion"
  docs/embedding/sdk/questions.md
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveAdHocQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult/InteractiveQuestionResult.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.unit.spec.tsx
Labels: was-backported

#50768 [Notification] Rename notification types
  enterprise/backend/test/metabase_enterprise/dashboard_subscription_filters/parameter_test.clj
  src/metabase/channel/impl/email.clj
  src/metabase/channel/impl/http.clj
  src/metabase/channel/impl/slack.clj
  src/metabase/models/notification.clj
  src/metabase/notification/payload/core.clj
  src/metabase/notification/payload/impl/card.clj
  src/metabase/notification/payload/impl/dashboard.clj
  src/metabase/notification/send.clj
  src/metabase/pulse/send.clj
  test/metabase/pulse/send_test.clj
Labels: no-backport, .Team/Workflows

#50729 🤖 backported "Fix Quartz rescheduling with multiple triggers"
  src/metabase/search/appdb/index.clj
  src/metabase/task.clj
  src/metabase/task/sweep_query_analysis.clj
Labels: was-backported

#50774 Fix a (native-ace-editor) flake 30039
  e2e/test/scenarios/visualizations-tabular/visualizations-tabular-reproductions.cy.spec.js
Labels: backport, flaky-test-fix

#50580 New Embed modal
  e2e/test/scenarios/embedding/embedding-smoketests.cy.spec.js
  e2e/test/scenarios/sharing/public-sharing-embed-button-behavior.cy.spec.js
  frontend/src/metabase/public/components/EmbedModal/EmbedModalContent/EmbedModalContent.unit.spec.tsx
  frontend/src/metabase/public/components/EmbedModal/EmbedModalContent/tests/EmbedModalContent.common.unit.spec.tsx
  frontend/src/metabase/public/components/EmbedModal/EmbedModalContent/tests/EmbedModalContent.enterprise.unit.spec.tsx
  frontend/src/metabase/public/components/EmbedModal/EmbedModalContent/tests/EmbedModalContent.premium.unit.spec.tsx
  frontend/src/metabase/public/components/EmbedModal/EmbedModalContent/tests/setup.tsx
  frontend/src/metabase/public/components/EmbedModal/SelectEmbedTypePane/SelectEmbedTypePane.tsx
  frontend/src/metabase/public/components/EmbedModal/SelectEmbedTypePane/SelectEmbedTypePane.unit.spec.tsx
  frontend/src/metabase/public/components/EmbedModal/SelectEmbedTypePane/SharingPaneButton/SharingPaneButton.module.css
  frontend/src/metabase/public/components/EmbedModal/SelectEmbedTypePane/SharingPaneButton/SharingPaneButton.tsx
  frontend/src/metabase/ui/components/typography/List/List.styled.tsx
  package.json
  yarn.lock
Labels: .Team/Embedding

#50672 Pivot Exports Can Handle `nil` in Breakout Col, and Multiple Cols of the Same Aggregation Type
  src/metabase/query_processor/pivot.clj
  src/metabase/query_processor/pivot/postprocess.clj
  src/metabase/query_processor/streaming/csv.clj
  test/metabase/api/downloads_exports_test.clj
Labels: backport, .Team/DashViz

#50723 Fix logging with conflict handlers
  bin/build/src/build/uberjar.clj
  bin/build/src/build_drivers/create_uberjar.clj
  deps.edn
Labels: no-backport

#50611 Address feedback on Sankey
  e2e/test/scenarios/visualizations-charts/sankey.cy.spec.js
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldPicker.jsx
  frontend/src/metabase/visualizations/echarts/graph/sankey/layout/index.ts
  frontend/src/metabase/visualizations/echarts/graph/sankey/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/graph/sankey/model/dataset.unit.spec.ts
  frontend/src/metabase/visualizations/echarts/graph/sankey/model/formatters.ts
  frontend/src/metabase/visualizations/echarts/graph/sankey/model/index.ts
  frontend/src/metabase/visualizations/echarts/graph/sankey/model/types.ts
  frontend/src/metabase/visualizations/echarts/graph/sankey/option/index.ts
  frontend/src/metabase/visualizations/echarts/graph/sankey/option/tooltip.tsx
  frontend/src/metabase/visualizations/echarts/types.ts
  frontend/src/metabase/visualizations/lib/settings/utils.js
  frontend/src/metabase/visualizations/types/visualization.ts
  frontend/src/metabase/visualizations/visualizations/SankeyChart/SankeyChart.tsx
  frontend/src/metabase/visualizations/visualizations/SankeyChart/chart-definition.ts
  frontend/src/metabase/visualizations/visualizations/SankeyChart/chart-definition.unit.spec.ts
  frontend/src/metabase/visualizations/visualizations/SankeyChart/events.ts
  frontend/src/metabase/visualizations/visualizations/SankeyChart/events.unit.spec.ts
Labels: backport, .Team/DashViz

#50780 🤖 backported "Pivot Exports Can Handle `nil` in Breakout Col, and Multiple Cols of the Same Aggregation Type"
  src/metabase/query_processor/pivot.clj
  src/metabase/query_processor/pivot/postprocess.clj
  src/metabase/query_processor/streaming/csv.clj
  test/metabase/api/downloads_exports_test.clj
Labels: was-backported

#50779 Remove memoization of active user counts setting
  src/metabase/public_settings/premium_features.clj
  src/metabase/troubleshooting.clj
  test/metabase/public_settings/premium_features_test.clj
Labels: backport, .Team/AdminWebapp

#50787 🤖 backported "Address feedback on Sankey"
  e2e/test/scenarios/visualizations-charts/sankey.cy.spec.js
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldPicker.jsx
  frontend/src/metabase/visualizations/echarts/graph/sankey/layout/index.ts
  frontend/src/metabase/visualizations/echarts/graph/sankey/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/graph/sankey/model/dataset.unit.spec.ts
  frontend/src/metabase/visualizations/echarts/graph/sankey/model/formatters.ts
  frontend/src/metabase/visualizations/echarts/graph/sankey/model/index.ts
  frontend/src/metabase/visualizations/echarts/graph/sankey/model/types.ts
  frontend/src/metabase/visualizations/echarts/graph/sankey/option/index.ts
  frontend/src/metabase/visualizations/echarts/graph/sankey/option/tooltip.tsx
  frontend/src/metabase/visualizations/echarts/types.ts
  frontend/src/metabase/visualizations/lib/settings/utils.js
  frontend/src/metabase/visualizations/types/visualization.ts
  frontend/src/metabase/visualizations/visualizations/SankeyChart/SankeyChart.tsx
  frontend/src/metabase/visualizations/visualizations/SankeyChart/chart-definition.ts
  frontend/src/metabase/visualizations/visualizations/SankeyChart/chart-definition.unit.spec.ts
  frontend/src/metabase/visualizations/visualizations/SankeyChart/events.ts
  frontend/src/metabase/visualizations/visualizations/SankeyChart/events.unit.spec.ts
Labels: was-backported

#50715 fix narrow ordinal line charts have no tooltip
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
Labels: backport, .Team/DashViz

#50466 fix(sdk): introduce `.mb-wrapper` to scope down our css
  .storybook/preview.tsx
  e2e/test-component/scenarios/embedding-sdk/styles-tests.cy.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/private/PublicComponentStylesWrapper.tsx
  frontend/src/metabase/css/core/box_sizing.module.css
  frontend/src/metabase/css/core/headings.module.css
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.module.css
  resources/frontend_client/index_template.html
Labels: backport, visual, .Team/Embedding

#50788 🤖 backported "Remove memoization of active user counts setting"
  src/metabase/public_settings/premium_features.clj
  src/metabase/troubleshooting.clj
  test/metabase/public_settings/premium_features_test.clj
Labels: was-backported

#50789 🤖 backported "fix narrow ordinal line charts have no tooltip"
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
Labels: was-backported

#50516 Introduce the non-admin Onboarding Checklist
  e2e/test/scenarios/onboarding/onboarding-checklist.cy.spec.ts
  frontend/src/metabase/home/components/Onboarding/Onboarding.tsx
  frontend/src/metabase/home/components/Onboarding/tests/common.unit.spec.tsx
  frontend/src/metabase/home/components/Onboarding/tests/setup.tsx
  frontend/src/metabase/home/selectors.ts
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarView.tsx
  frontend/src/metabase/nav/containers/MainNavbar/tests/common.unit.spec.tsx
  frontend/src/metabase/route-guards.tsx
  frontend/src/metabase/routes.jsx
Labels: backport, PR-Env

#50791 🤖 backported "fix(sdk): introduce `.mb-wrapper` to scope down our css"
  .storybook/preview.tsx
  e2e/test-component/scenarios/embedding-sdk/styles-tests.cy.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/private/PublicComponentStylesWrapper.tsx
  frontend/src/metabase/css/core/box_sizing.module.css
  frontend/src/metabase/css/core/headings.module.css
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.module.css
  resources/frontend_client/index_template.html
Labels: was-backported

#50775 🤖 backported "Fix a (native-ace-editor) flake 30039"
  e2e/test/scenarios/visualizations-tabular/visualizations-tabular-reproductions.cy.spec.js
Labels: was-backported

#50747 🤖 backported "Partially fix flaky native e2e tests"
  e2e/test/scenarios/native/native-reproductions.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
Labels: was-backported

#50795 Manual backport of: Make e2e tests of embedding and sql filters date-invariant (#50737)
  e2e/test/scenarios/native-filters/helpers/e2e-field-filter-data-objects.js
  e2e/test/scenarios/native-filters/sql-field-filter-types.cy.spec.js
Labels: .Team/AdminWebapp

#50799 🤖 backported "Update Translations for v52.1"
  locales/ar-SA.po
  locales/ar.po
  locales/bg.po
  locales/ca.po
  locales/cs.po
  locales/da.po
  locales/de.po
  locales/es.po
  locales/fa.po
  locales/fi.po
  locales/fr.po
  locales/he.po
  locales/hu.po
  locales/id.po
  locales/it.po
  locales/ja.po
  locales/ko.po
  locales/lv.po
  locales/metabase.pot
  locales/ms.po
  locales/nb.po
  locales/nl.po
  locales/pl.po
  locales/pt-BR.po
  locales/ru.po
  locales/sk.po
  locales/sq.po
  locales/sr.po
  locales/sv.po
  locales/tr.po
  locales/uk.po
  locales/vi.po
  locales/zh-CN.po
  locales/zh-HK.po
  locales/zh-TW.po
  locales/zh.po
Labels: was-backported

#50790 Manual backport of #50779 to 51
  src/metabase/public_settings/premium_features.clj
  src/metabase/troubleshooting.clj
  test/metabase/public_settings/premium_features_test.clj
Labels: .Team/AdminWebapp, was-backported

#50783 removing the 'can_write' requirement for selecting things via the question picker
  e2e/test/scenarios/dashboard-cards/dashboard-sections.cy.spec.js
  frontend/src/metabase/common/components/QuestionPicker/components/QuestionPickerModal.tsx
Labels: backport, .Team/AdminWebapp

#50760 [Clean up] Hide clean up UI in sample collections
  e2e/test/scenarios/collections/cleanup.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/clean_up/CollectionCleanupAlert/CollectionCleanupAlert.tsx
  enterprise/frontend/src/metabase-enterprise/clean_up/index.tsx
  enterprise/frontend/src/metabase-enterprise/clean_up/utils.ts
  enterprise/frontend/src/metabase-enterprise/clean_up/utils.unit.spec.ts
  frontend/src/metabase-types/api/collection.ts
  frontend/src/metabase/collections/components/CollectionMenu/CollectionMenu.tsx
  frontend/src/metabase/plugins/index.ts
Labels: backport, .Team/AdminWebapp

#50579 Onboarding checklist - misc. follow ups
  frontend/src/metabase/home/components/Onboarding/Onboarding.tsx
  frontend/src/metabase/home/components/Onboarding/tests/common.unit.spec.tsx
  frontend/src/metabase/home/components/Onboarding/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/home/components/Onboarding/tests/premium.unit.spec.tsx
  resources/frontend_client/app/assets/img/onboarding_data_diagram.png
  resources/frontend_client/app/assets/img/onboarding_data_diagram@2x.png
Labels: backport

#50750 docs - 52 api and env var
  docs/api-documentation.md
  docs/api/cache.md
  docs/api/card.md
  docs/api/collection.md
  docs/api/dashboard.md
  docs/api/dataset.md
  docs/api/ee/advanced-permissions-application.md
  docs/api/ee/content-verification-review.md
  docs/api/embed.md
  docs/api/notify.md
  docs/api/permissions.md
  docs/api/public.md
  docs/api/pulse.md
  docs/api/search.md
  docs/api/session.md
  docs/api/slack.md
  docs/api/user.md
  docs/configuring-metabase/environment-variables.md
Labels: Type:Documentation, no-backport

#50784 docs - commands
  docs/installation-and-operation/commands.md
  enterprise/frontend/src/embedding-sdk/README.md
Labels: Type:Documentation, backport

#50656 feat(sdk): rename prop names to be clear and explicit
  docs/embedding/sdk/dashboards.md
  docs/embedding/sdk/questions.md
  e2e/test-component/scenarios/embedding-sdk/interactive-question.cy.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/SdkSaveQuestionForm.stories.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/SdkSaveQuestionForm.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/ConnectedDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/EditableDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/StaticQuestion/StaticQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/public/StaticQuestion/StaticQuestion.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/hooks/private/use-load-static-question.ts
  enterprise/frontend/src/embedding-sdk/hooks/private/use-sdk-dashboard-params.ts
  enterprise/frontend/src/embedding-sdk/lib/load-static-question.ts
Labels: backport, .Team/Embedding, Embedding/SDK

#50812 🤖 backported "Onboarding checklist - misc. follow ups"
  frontend/src/metabase/home/components/Onboarding/Onboarding.tsx
  frontend/src/metabase/home/components/Onboarding/tests/common.unit.spec.tsx
  frontend/src/metabase/home/components/Onboarding/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/home/components/Onboarding/tests/premium.unit.spec.tsx
  resources/frontend_client/app/assets/img/onboarding_data_diagram.png
  resources/frontend_client/app/assets/img/onboarding_data_diagram@2x.png
Labels: was-backported

#50815 Manual backport of 50813
  src/metabase/public_settings/premium_features.clj
  test/metabase/public_settings/premium_features_test.clj
Labels: .Team/AdminWebapp

#50810 🤖 backported "[Clean up] Hide clean up UI in sample collections"
  e2e/test/scenarios/collections/cleanup.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/clean_up/CollectionCleanupAlert/CollectionCleanupAlert.tsx
  enterprise/frontend/src/metabase-enterprise/clean_up/index.tsx
  enterprise/frontend/src/metabase-enterprise/clean_up/utils.ts
  enterprise/frontend/src/metabase-enterprise/clean_up/utils.unit.spec.ts
  frontend/src/metabase-types/api/collection.ts
  frontend/src/metabase/collections/components/CollectionMenu/CollectionMenu.tsx
  frontend/src/metabase/plugins/index.ts
Labels: was-backported

#50817 🤖 backported "feat(sdk): rename prop names to be clear and explicit"
  docs/embedding/sdk/dashboards.md
  docs/embedding/sdk/questions.md
  e2e/test-component/scenarios/embedding-sdk/interactive-question.cy.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/SdkSaveQuestionForm.stories.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/SdkSaveQuestionForm.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/ConnectedDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/EditableDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/StaticQuestion/StaticQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/public/StaticQuestion/StaticQuestion.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/hooks/private/use-load-static-question.ts
  enterprise/frontend/src/embedding-sdk/hooks/private/use-sdk-dashboard-params.ts
  enterprise/frontend/src/embedding-sdk/lib/load-static-question.ts
Labels: was-backported

#50813 Ensure user count is fetched within token status memoization
  src/metabase/public_settings/premium_features.clj
  test/metabase/public_settings/premium_features_test.clj
Labels: backport, .Team/AdminWebapp

#50258 Split ACE editor into separate component
  e2e/support/helpers/e2e-action-helpers.js
  e2e/support/helpers/e2e-ad-hoc-question-helpers.js
  e2e/support/helpers/e2e-misc-helpers.js
  e2e/support/helpers/e2e-native-editor-helpers.ts
  e2e/support/helpers/index.ts
  e2e/test/scenarios/actions/actions-on-dashboards.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard-back-navigation.cy.spec.js
  e2e/test/scenarios/models/create.cy.spec.js
  e2e/test/scenarios/models/helpers/e2e-models-helpers.js
  e2e/test/scenarios/models/models-query-editor.cy.spec.js
  e2e/test/scenarios/models/models.cy.spec.js
  e2e/test/scenarios/models/reproductions.cy.spec.js
  e2e/test/scenarios/native-filters/native-filters-reproductions.cy.spec.js
  e2e/test/scenarios/native/native-database-source.cy.spec.js
  e2e/test/scenarios/native/native-reproductions.cy.spec.ts
  e2e/test/scenarios/native/native.cy.spec.js
  e2e/test/scenarios/native/native_subquery.cy.spec.js
  e2e/test/scenarios/native/snippets.cy.spec.js
  e2e/test/scenarios/onboarding/navbar/new-menu.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions-1.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions-2.cy.spec.js
  e2e/test/scenarios/question/notebook-native-preview-sidebar.cy.spec.ts
  e2e/test/scenarios/sharing/downloads/sharing-download-reproductions.cy.spec.js
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.js
  enterprise/frontend/src/embedding-sdk/components/private/PublicComponentStylesWrapper.tsx
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/actions/containers/ActionCreator/ActionContext/QueryActionContextProvider/QueryActionEditor.tsx
  frontend/src/metabase/css/core/colors.module.css
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetQueryEditor.unit.spec.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/AceEditor/AceEditor.module.css
  frontend/src/metabase/query_builder/components/NativeQueryEditor/AceEditor/AceEditor.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/AceEditor/constants.ts
  frontend/src/metabase/query_builder/components/NativeQueryEditor/AceEditor/index.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/AceEditor/selectors.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/AceEditor/types.ts
  frontend/src/metabase/query_builder/components/NativeQueryEditor/AceEditor/utils.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/Editor.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.module.css
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.styled.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/__mocks__/NativeQueryEditor.jsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/constants.ts
  frontend/src/metabase/query_builder/components/NativeQueryEditor/types.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/utils.ts
  frontend/src/metabase/query_builder/containers/QueryBuilder.tsx
  frontend/src/metabase/query_builder/selectors.js
  frontend/src/metabase/querying/notebook/components/NotebookNativePreview/NotebookNativePreview.tsx
  frontend/src/metabase/querying/notebook/components/NotebookNativePreview/utils.ts
  frontend/src/metabase/styled-components/containers/GlobalStyles/GlobalStyles.tsx
  frontend/src/types/ace-builds.d.ts
Labels: visual, no-backport, .Team/Querying, PR-Env

#50605 Properly handle other users personal collections in collection picker
  e2e/test/scenarios/organization/entity-picker.cy.spec.ts
  frontend/src/metabase/common/components/CollectionPicker/components/CollectionPicker.tsx
  frontend/src/metabase/common/components/CollectionPicker/utils.ts
  frontend/src/metabase/common/components/CollectionPicker/utils.unit.spec.ts
Labels: backport, .Team/AdminWebapp

#50713 Show /api/search errors in Browse models and Browse metrics
  e2e/test/scenarios/onboarding/home/browse.cy.spec.ts
  frontend/src/metabase/browse/metrics/BrowseMetrics.tsx
  frontend/src/metabase/browse/models/BrowseModels.tsx
Labels: backport, .Team/AdminWebapp

#50693 Update Interactive Embedding Admin Settings page
  enterprise/frontend/src/metabase-enterprise/embedding/components/InteractiveEmbeddingSettings.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/common.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/enterprise.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/premium.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/InteractiveEmbeddingOptionCard/InteractiveEmbeddingOptionCard.tsx
Labels: .Team/Embedding

#50730 backported "Fix Quartz rescheduling with multiple triggers" (#50707)
  src/metabase/task.clj
  src/metabase/task/sweep_query_analysis.clj
Labels: .Team/Workflows, was-backported

#50843 fix persist model error email
  src/metabase/email/persisted-model-error.hbs
Labels: backport, .Team/Workflows

#50849 🤖 backported "Add more logs for sending notification"
  src/metabase/notification/send.clj
Labels: was-backported

#50634 Port Questions to use new EntityObjectLoaderRtkQuery
  frontend/src/metabase/actions/containers/ActionCreatorModal/ActionCreatorModal.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataFieldSettings/MetadataFieldSettings.tsx
  frontend/src/metabase/containers/SavedQuestionLoader.jsx
  frontend/src/metabase/entities/containers/rtk-query/EntityObjectLoaderRtkQuery.tsx
  frontend/src/metabase/entities/questions.js
Labels: no-backport, .Team/Querying

#50845 Manual backport of 50703 to 51
  e2e/test/scenarios/embedding/embedding-reproductions.cy.spec.js
  src/metabase/server/request/util.clj
Labels: Embedding/Public, no-backport, .Team/Embedding

#50853 [WIP] Port Persisted Models to use new EntityObjectLoaderRtkQuery
  frontend/src/metabase/entities/persisted-models.js
Labels: do not merge, no-backport, .Team/Querying

#50851 🤖 backported "fix persist model error email"
  src/metabase/email/persisted-model-error.hbs
Labels: was-backported

#50786 [serdes] do not require prefix when passing entity ids to export
  enterprise/backend/src/metabase_enterprise/serialization/api.clj
  enterprise/backend/test/metabase_enterprise/serialization/api_test.clj
  src/metabase/cmd.clj
Labels: backport, .Team/Workflows

#50854 Port Schemas to use new EntityObjectLoaderRtkQuery
  frontend/src/metabase/entities/schemas.js
Labels: no-backport, .Team/Querying

#49344 Trial Banner
  .clj-kondo/src/hooks/metabase/models/setting.clj
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/components/AppBanner/AppBanner.tsx
  frontend/src/metabase/components/AppBanner/AppBanner.unit.spec.tsx
  frontend/src/metabase/components/AppBanner/index.ts
  frontend/src/metabase/components/AppBanner/utils.ts
  frontend/src/metabase/components/AppBanner/utils.unit.spec.ts
  frontend/src/metabase/nav/components/TrialBanner/TrialBanner.tsx
  frontend/src/metabase/nav/components/TrialBanner/TrialBanner.unit.spec.tsx
  frontend/src/metabase/nav/components/TrialBanner/index.ts
  src/metabase/models/user.clj
Labels: backport

#50857 [WIP] Port Timeline Events to use new EntityObjectLoaderRtkQuery
  frontend/src/metabase/entities/timeline-events.js
Labels: do not merge, no-backport, .Team/Querying

#50850 Replace experimental flag with engine choice
  src/metabase/api/search.clj
  src/metabase/public_settings.clj
  src/metabase/search/appdb/core.clj
  src/metabase/search/appdb/index.clj
  src/metabase/search/engine.clj
  src/metabase/search/impl.clj
  test/metabase/api/search_test.clj
  test/metabase/search/appdb/index_test.clj
  test/metabase/search/appdb/scoring_test.clj
  test/metabase/search/config_test.clj
  test/metabase/search/impl_test.clj
Labels: backport, .Team/Workflows

#50866 Port Users to use new EntityObjectLoaderRtkQuery
  frontend/src/metabase/entities/users.js
Labels: no-backport, .Team/Querying

#50872 🤖 backported "Replace experimental flag with engine choice"
  src/metabase/api/search.clj
  src/metabase/public_settings.clj
  src/metabase/search/appdb/core.clj
  src/metabase/search/appdb/index.clj
  src/metabase/search/engine.clj
  src/metabase/search/impl.clj
  test/metabase/api/search_test.clj
  test/metabase/search/appdb/index_test.clj
  test/metabase/search/appdb/scoring_test.clj
  test/metabase/search/config_test.clj
  test/metabase/search/impl_test.clj
Labels: was-backported

#50752 Move filter-parts to MBQL lib
  frontend/src/metabase-lib/constants.ts
  frontend/src/metabase-lib/filter.ts
  frontend/src/metabase-lib/filter.unit.spec.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateIntervalPicker/DateIntervalPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateIntervalPicker/SimpleDateIntervalPicker/SimpleDateIntervalPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateIntervalPicker/utils.ts
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/utils.ts
  frontend/src/metabase/querying/filters/components/DatePicker/types.ts
  frontend/src/metabase/querying/filters/components/FilterModal/BooleanFilterEditor/BooleanFilterEditor.tsx
  frontend/src/metabase/querying/filters/components/FilterModal/BooleanFilterEditor/BooleanFilterEditor.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/FilterModal/CoordinateFilterEditor/CoordinateFilterEditor.tsx
  frontend/src/metabase/querying/filters/components/FilterModal/CoordinateFilterEditor/CoordinateFilterEditor.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/FilterModal/DateFilterEditor/DateFilterEditor.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/FilterModal/NumberFilterEditor/NumberFilterEditor.tsx
  frontend/src/metabase/querying/filters/components/FilterModal/NumberFilterEditor/NumberFilterEditor.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/FilterModal/StringFilterEditor/StringFilterEditor.tsx
  frontend/src/metabase/querying/filters/components/FilterModal/StringFilterEditor/StringFilterEditor.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/CoordinateFilterPicker/CoordinateFilterPicker.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/DateFilterPicker/DateFilterPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/FilterPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/NumberFilterPicker/NumberFilterPicker.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/StringFilterPicker/StringFilterPicker.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/StringFilterPicker/StringFilterPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/test-utils.ts
  frontend/src/metabase/querying/filters/hooks/use-boolean-operator-filter/constants.ts
  frontend/src/metabase/querying/filters/hooks/use-boolean-operator-filter/types.ts
  frontend/src/metabase/querying/filters/hooks/use-boolean-operator-filter/use-boolean-operator-filter.ts
  frontend/src/metabase/querying/filters/hooks/use-boolean-operator-filter/use-boolean-operator-filter.unit.spec.ts
  frontend/src/metabase/querying/filters/hooks/use-boolean-operator-filter/utils.ts
  frontend/src/metabase/querying/filters/hooks/use-boolean-option-filter/types.ts
  frontend/src/metabase/querying/filters/hooks/use-coordinate-filter/constants.ts
  frontend/src/metabase/querying/filters/hooks/use-coordinate-filter/use-coordinate-filter.ts
  frontend/src/metabase/querying/filters/hooks/use-coordinate-filter/use-coordinate-filter.unit.spec.ts
  frontend/src/metabase/querying/filters/hooks/use-coordinate-filter/utils.ts
  frontend/src/metabase/querying/filters/hooks/use-date-filter/use-date-filter.unit.spec.ts
  frontend/src/metabase/querying/filters/hooks/use-date-filter/utils.ts
  frontend/src/metabase/querying/filters/hooks/use-number-filter/constants.ts
  frontend/src/metabase/querying/filters/hooks/use-number-filter/types.ts
  frontend/src/metabase/querying/filters/hooks/use-number-filter/use-number-filter.ts
  frontend/src/metabase/querying/filters/hooks/use-number-filter/use-number-filter.unit.spec.ts
  frontend/src/metabase/querying/filters/hooks/use-number-filter/utils.ts
  frontend/src/metabase/querying/filters/hooks/use-string-filter/constants.ts
  frontend/src/metabase/querying/filters/hooks/use-string-filter/types.ts
  frontend/src/metabase/querying/filters/hooks/use-string-filter/use-string-filter.ts
  frontend/src/metabase/querying/filters/hooks/use-string-filter/use-string-filter.unit.spec.ts
  frontend/src/metabase/querying/filters/hooks/use-string-filter/utils.ts
  src/metabase/lib/core.cljc
  src/metabase/lib/fe_util.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/schema/filter.cljc
  test/metabase/lib/fe_util_test.cljc
Labels: no-backport, .Team/Querying

#50852 Finish deprecating old search module namespace
  .clj-kondo/config.edn
  src/metabase/api/search.clj
  src/metabase/models/action.clj
  src/metabase/models/card.clj
  src/metabase/models/dashboard.clj
  src/metabase/models/model_index.clj
  src/metabase/models/segment.clj
  src/metabase/models/table.clj
  src/metabase/search.clj
  src/metabase/search/core.clj
Labels: backport, .Team/Workflows

#50880 🤖 backported "Finish deprecating old search module namespace"
  .clj-kondo/config.edn
  src/metabase/api/search.clj
  src/metabase/models/action.clj
  src/metabase/models/card.clj
  src/metabase/models/dashboard.clj
  src/metabase/models/model_index.clj
  src/metabase/models/segment.clj
  src/metabase/models/table.clj
  src/metabase/search.clj
  src/metabase/search/core.clj
Labels: was-backported

#50861 chore: drop unused CSS
  frontend/src/metabase/components/MetadataInfo/MetadataInfo.styled.tsx
  frontend/src/metabase/query_builder/components/QueryDownloadWidget/QueryDownloadWidget.styled.tsx
  frontend/src/metabase/query_builder/components/QuestionEmbedWidget/QuestionEmbedWidget.styled.tsx
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeList/ChartTypeList.styled.tsx
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeOption/ChartTypeOption.styled.tsx
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeSettings/ChartTypeSettings.styled.tsx
Labels: no-backport, .Team/Querying

#50881 sql-field-filter-types.cy.spec.js flakes
  e2e/test/scenarios/native-filters/helpers/e2e-sql-filter-helpers.js
  e2e/test/scenarios/native-filters/sql-field-filter-types.cy.spec.js
Labels: backport, .Team/Querying

#50860 feat(sdk): add style and className to static dashboards
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.tsx
  enterprise/frontend/src/embedding-sdk/hooks/private/use-sdk-dashboard-params.ts
Labels: backport, .Team/Embedding, Embedding/SDK

#50802 Applying the underlying records filter to a query with a join display…
  src/metabase/lib/drill_thru/underlying_records.cljc
  test/metabase/lib/drill_thru/underlying_records_test.cljc
Labels: backport, .Team/Querying

#50765 Move time filter parts to MBQL lib
  frontend/src/metabase-lib/constants.ts
  frontend/src/metabase-lib/filter.ts
  frontend/src/metabase-lib/filter.unit.spec.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/querying/filters/components/FilterModal/TimeFilterEditor/TimeFilterEditor.tsx
  frontend/src/metabase/querying/filters/components/FilterModal/TimeFilterEditor/TimeFilterEditor.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/TimeFilterPicker/TimeFilterPicker.tsx
  frontend/src/metabase/querying/filters/hooks/use-time-filter/constants.ts
  frontend/src/metabase/querying/filters/hooks/use-time-filter/types.ts
  frontend/src/metabase/querying/filters/hooks/use-time-filter/use-time-filter.ts
  frontend/src/metabase/querying/filters/hooks/use-time-filter/use-time-filter.unit.spec.ts
  frontend/src/metabase/querying/filters/hooks/use-time-filter/utils.ts
  src/metabase/lib/core.cljc
  src/metabase/lib/fe_util.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/schema/filter.cljc
  test/metabase/lib/fe_util_test.cljc
Labels: no-backport, .Team/Querying

#50884 🤖 backported "feat(sdk): add style and className to static dashboards"
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.tsx
  enterprise/frontend/src/embedding-sdk/hooks/private/use-sdk-dashboard-params.ts
Labels: was-backported

#50886 🤖 backported "Applying the underlying records filter to a query with a join display…"
  src/metabase/lib/drill_thru/underlying_records.cljc
  test/metabase/lib/drill_thru/underlying_records_test.cljc
Labels: was-backported

#50847 Manual backport 50663 to 51
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/types.ts
  enterprise/frontend/src/embedding-sdk/components/public/StaticQuestion/StaticQuestion.tsx
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase-types/api/entity-id.ts
Labels: Embedding/Public, no-backport, .Team/Embedding

#50885 docs - verified content
  docs/README.md
  docs/dashboards/introduction.md
  docs/data-modeling/metrics.md
  docs/data-modeling/models.md
  docs/exploration-and-organization/collections.md
  docs/exploration-and-organization/content-verification.md
  docs/exploration-and-organization/exploration.md
  docs/exploration-and-organization/history.md
  docs/exploration-and-organization/images/verified-only.png
  docs/exploration-and-organization/images/verify-this-dashboard.png
  docs/exploration-and-organization/start.md
  docs/paid-features/overview.md
Labels: Type:Documentation, backport

#50895 🤖 backported "docs - verified content"
  docs/README.md
  docs/dashboards/introduction.md
  docs/data-modeling/metrics.md
  docs/data-modeling/models.md
  docs/exploration-and-organization/collections.md
  docs/exploration-and-organization/content-verification.md
  docs/exploration-and-organization/exploration.md
  docs/exploration-and-organization/history.md
  docs/exploration-and-organization/images/verified-only.png
  docs/exploration-and-organization/images/verify-this-dashboard.png
  docs/exploration-and-organization/start.md
  docs/paid-features/overview.md
Labels: was-backported

#50807 Deserialize metrics as cards
  enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj
  src/metabase/models/serialization.clj
Labels: backport, .Team/Querying

#50236 test: syncing views against all drivers
  modules/drivers/bigquery-cloud-sdk/test/metabase/test/data/bigquery_cloud_sdk.clj
  modules/drivers/mongo/src/metabase/driver/mongo.clj
  modules/drivers/mongo/test/metabase/test/data/mongo.clj
  modules/drivers/oracle/test/metabase/test/data/oracle.clj
  modules/drivers/snowflake/test/metabase/test/data/snowflake.clj
  modules/drivers/sqlserver/test/metabase/test/data/sqlserver.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/driver/sql_jdbc/sync/describe_table_test.clj
  test/metabase/test/data/interface.clj
  test/metabase/test/data/sql.clj
  test/metabase/test/data/sql_jdbc.clj
Labels: backport, .Team/Drivers

#50870 🤖 backported "Trial Banner"
  .clj-kondo/src/hooks/metabase/models/setting.clj
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/components/AppBanner/AppBanner.tsx
  frontend/src/metabase/components/AppBanner/AppBanner.unit.spec.tsx
  frontend/src/metabase/components/AppBanner/index.ts
  frontend/src/metabase/components/AppBanner/utils.ts
  frontend/src/metabase/components/AppBanner/utils.unit.spec.ts
  frontend/src/metabase/nav/components/TrialBanner/TrialBanner.tsx
  frontend/src/metabase/nav/components/TrialBanner/TrialBanner.unit.spec.tsx
  frontend/src/metabase/nav/components/TrialBanner/index.ts
  src/metabase/models/user.clj
Labels: was-backported

#50899 Add v0.51.7 to the list of releases
  docs/releases.md
Labels: Type:Documentation, backport

#50904 🤖 backported "Add v0.51.7 to the list of releases"
  docs/releases.md
Labels: was-backported

#50896 🤖 backported "Deserialize metrics as cards"
  enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj
  src/metabase/models/serialization.clj
Labels: was-backported

#50906 Add v0.52.1 to the list of releases
  docs/releases.md
Labels: Type:Documentation, backport

#50908 🤖 backported "Add v0.52.1 to the list of releases"
  docs/releases.md
Labels: was-backported

#50900 fix: Qualify postgres enums outside public schema
  src/metabase/driver/postgres.clj
  test/metabase/driver/postgres_test.clj
Labels: backport, .Team/Drivers

#50910 🤖 backported "fix: Qualify postgres enums outside public schema"
  src/metabase/driver/postgres.clj
  test/metabase/driver/postgres_test.clj
Labels: was-backported

#50806 Loki flake: make delays configurable independently
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_List_Single_With_Value.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_List_With_Value.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_List_Single_With_Value.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_List_With_Value.png
  .storybook/preview.tsx
  frontend/src/metabase/components/ExplicitSize/ExplicitSize.tsx
  frontend/src/metabase/components/ListField/ListField.tsx
  frontend/src/metabase/components/SingleSelectListField/SingleSelectListField.tsx
  frontend/src/metabase/context/wait-time.ts
  frontend/src/metabase/lib/delay.ts
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardView-filters.stories.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardView.stories.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestionView.stories.tsx
Labels: backport, .Team/Querying

#50918 🤖 backported "Loki flake: make delays configurable independently"
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_List_Single_With_Value.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_List_With_Value.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_List_Single_With_Value.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_List_With_Value.png
  .storybook/preview.tsx
  frontend/src/metabase/components/ExplicitSize/ExplicitSize.tsx
  frontend/src/metabase/components/ListField/ListField.tsx
  frontend/src/metabase/components/SingleSelectListField/SingleSelectListField.tsx
  frontend/src/metabase/context/wait-time.ts
  frontend/src/metabase/lib/delay.ts
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardView-filters.stories.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardView.stories.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestionView.stories.tsx
Labels: was-backported

#50725 🤖 backported "Deprecate alert and pulse apis"
  docs/developers-guide/api-changelog.md
  enterprise/backend/test/metabase_enterprise/advanced_permissions/api/subscription_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/pulse_test.clj
  src/metabase/api/alert.clj
  src/metabase/api/pulse.clj
  src/metabase/api/routes.clj
  test/metabase/api/pulse_test.clj
Labels: was-backported

#50876 Keep support for the old search engine name
  src/metabase/search/appdb/core.clj
  test/metabase/api/search_test.clj
  test/metabase/search/impl_test.clj
Labels: backport, .Team/Workflows

#50922 🤖 backported "Keep support for the old search engine name"
  src/metabase/search/appdb/core.clj
  test/metabase/api/search_test.clj
  test/metabase/search/impl_test.clj
Labels: was-backported

#50869 Port Collections to use new EntityObjectLoaderRtkQuery
  frontend/src/metabase/collections/components/CollectionContent/CollectionContent.tsx
  frontend/src/metabase/collections/components/MoveCollectionModal/MoveCollectionModal.tsx
  frontend/src/metabase/common/components/CollectionPicker/components/CollectionPicker.tsx
  frontend/src/metabase/common/hooks/entity-framework/index.ts
  frontend/src/metabase/common/hooks/entity-framework/use-collection-query/index.ts
  frontend/src/metabase/common/hooks/entity-framework/use-collection-query/use-collection-query.ts
  frontend/src/metabase/common/hooks/entity-framework/use-collection-query/use-collection-query.unit.spec.tsx
  frontend/src/metabase/components/ArchiveCollectionModal/ArchiveCollectionModal.jsx
  frontend/src/metabase/containers/CollectionName.jsx
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.tsx
  frontend/src/metabase/dashboard/components/DashboardMoveModal.tsx
  frontend/src/metabase/dashboard/containers/ArchiveDashboardModal.jsx
  frontend/src/metabase/entities/collections/collections.ts
  frontend/src/metabase/entities/containers/rtk-query/types/entities.ts
  frontend/src/metabase/nav/containers/CollectionBreadcrumbs/CollectionBreadcrumbs.tsx
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityPicker.jsx
  frontend/src/metabase/questions/components/CollectionBadge.tsx
  frontend/src/metabase/status/components/FileUploadStatus/FileUploadStatus.tsx
Labels: no-backport, .Team/Querying

#50878 Migrate favicon logic to mantine hook
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.tsx
  frontend/src/metabase/dashboard/selectors.ts
  frontend/src/metabase/hoc/Favicon.jsx
  frontend/src/metabase/hooks/use-favicon.ts
  frontend/src/metabase/query_builder/containers/QueryBuilder.tsx
  frontend/src/metabase/query_builder/containers/test-utils.tsx
  frontend/src/metabase/query_builder/selectors.js
Labels: backport, .Team/Embedding

#50773 fix(sdk): remove Error.captureStackTrace as it errors on firefox
  enterprise/frontend/src/embedding-sdk/store/auth.ts
Labels: backport, .Team/Embedding

#50819 🤖 backported "Ensure user count is fetched within token status memoization"
  src/metabase/public_settings/premium_features.clj
  test/metabase/public_settings/premium_features_test.clj
Labels: was-backported

#50937 Fix edge cases in New Search around model filtering
  src/metabase/search/appdb/core.clj
  src/metabase/search/filter.clj
  test/metabase/search/filter_test.clj
Labels: backport, .Team/Workflows

#50939 🤖 backported "Fix edge cases in New Search around model filtering"
  src/metabase/search/appdb/core.clj
  src/metabase/search/filter.clj
  test/metabase/search/filter_test.clj
Labels: was-backported

#50170 [xlsx-export] Refactor postprocess namespace with perf/concat
  src/metabase/query_processor/pivot/postprocess.clj
  src/metabase/util/performance.clj
  test/metabase/util/performance_test.clj
Labels: backport

#50531 Add binning to display name
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  e2e/test/scenarios/question/multiple-column-breakouts.cy.spec.ts
  e2e/test/scenarios/question/native-query-drill.cy.spec.ts
  e2e/test/scenarios/visualizations-charts/maps.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/pivot_tables.cy.spec.js
  src/metabase/legacy_mbql/normalize.cljc
  src/metabase/lib/binning.cljc
  src/metabase/lib/expression.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/models/interface.clj
  src/metabase/query_processor/middleware/annotate.clj
  src/metabase/query_processor/middleware/results_metadata.clj
  test/metabase/lib/binning_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/query_processor/middleware/add_source_metadata_test.clj
  test/metabase/query_processor/middleware/annotate_test.clj
  test/metabase/query_processor_test/binning_test.clj
  test/metabase/query_processor_test/breakout_test.clj
Labels: backport, .Team/Querying

#50934 🤖 backported "fix(sdk): remove Error.captureStackTrace as it errors on firefox"
  enterprise/frontend/src/embedding-sdk/store/auth.ts
Labels: was-backported

#50793 sankey static viz integration test
  test/metabase/channel/render/body_test.clj
Labels: backport, .Team/DashViz

#50947 docs - update env var docs
  docs/configuring-metabase/environment-variables.md
  src/metabase/search/appdb/index.clj
Labels: Type:Documentation, no-backport

#50888 [FE] Move exclude date filter parts to MBQL lib
  frontend/src/metabase-lib/filter.ts
  frontend/src/metabase-lib/filter.unit.spec.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase-lib/v1/expressions/config.ts
  frontend/src/metabase/querying/filters/components/DatePicker/ExcludeDatePicker/ExcludeDatePicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/ExcludeDatePicker/utils.ts
  frontend/src/metabase/querying/filters/components/FilterModal/DateFilterEditor/DateFilterEditor.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/DateFilterPicker/DateFilterPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/test-utils.ts
  frontend/src/metabase/querying/filters/hooks/use-date-filter/use-date-filter.unit.spec.ts
  frontend/src/metabase/querying/filters/hooks/use-date-filter/utils.ts
  src/metabase/lib/core.cljc
  src/metabase/lib/fe_util.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/schema/filter.cljc
  test/metabase/lib/fe_util_test.cljc
Labels: no-backport, .Team/Querying

#50950 🤖 backported "sankey static viz integration test"
  test/metabase/channel/render/body_test.clj
Labels: was-backported

#50941 Include explicit require to c.t.build.tasks.uber
  bin/build/src/build_drivers/create_uberjar.clj
Labels: backport

#50835 Add v0.50.35 to the list of releases
  docs/questions/sharing/answers.md
  docs/releases.md
Labels: Type:Documentation, backport

#50914 Make postgres enums not error when using :is-empty/:not-empty
  src/metabase/types.cljc
  test/metabase/legacy_mbql/util_test.cljc
Labels: backport, .Team/Querying

#50829 New and improved Examples collection
  resources/migrations/001_update_migrations.yaml
  resources/sample-content.edn
  src/metabase/db/custom_migrations.clj
  test/metabase/db/custom_migrations_test.clj
  test/metabase/db/setup_test.clj
Labels: backport, .Team/AdminWebapp

#50963 docs - update env vars
  docs/configuring-metabase/environment-variables.md
  src/metabase/search/appdb/index.clj
Labels: Type:Documentation, no-backport

#50967 🤖 backported "Make postgres enums not error when using :is-empty/:not-empty"
  src/metabase/types.cljc
  test/metabase/legacy_mbql/util_test.cljc
Labels: was-backported

#50968 🤖 backported "New and improved Examples collection"
  resources/migrations/001_update_migrations.yaml
  resources/sample-content.edn
  src/metabase/db/custom_migrations.clj
  test/metabase/db/custom_migrations_test.clj
  test/metabase/db/setup_test.clj
Labels: was-backported

#50966 🤖 backported "Add v0.50.35 to the list of releases"
  docs/questions/sharing/answers.md
  docs/releases.md
Labels: was-backported

#50889 fix scatter chart tooltip
  e2e/test/scenarios/visualizations-charts/scatter.cy.spec.js
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/src/metabase/visualizations/lib/settings/graph.unit.spec.js
  frontend/src/metabase/visualizations/shared/settings/cartesian-chart.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/events.ts
Labels: backport, .Team/DashViz

#50969 🤖 backported "fix scatter chart tooltip"
  e2e/test/scenarios/visualizations-charts/scatter.cy.spec.js
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/src/metabase/visualizations/lib/settings/graph.unit.spec.js
  frontend/src/metabase/visualizations/shared/settings/cartesian-chart.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/events.ts
Labels: was-backported

#50912 chore: rework DataSelector to css modules
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.module.css
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.styled.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDataBucketPicker/DataSelectorDataBucketPicker.module.css
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDataBucketPicker/DataSelectorDataBucketPicker.styled.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDataBucketPicker/DataSelectorDataBucketPicker.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDatabasePicker/DataSelectorDatabasePicker.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorDatabaseSchemaPicker/DataSelectorDatabaseSchemaPicker.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorFieldPicker/DataSelectorFieldPicker.module.css
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorFieldPicker/DataSelectorFieldPicker.styled.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorFieldPicker/DataSelectorFieldPicker.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorLoading/DataSelectorLoading.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorSchemaPicker/DataSelectorSchemaPicker.styled.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorSchemaPicker/DataSelectorSchemaPicker.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorSectionHeader/DataSelectorSectionHeader.module.css
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorSectionHeader/DataSelectorSectionHeader.styled.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorSectionHeader/DataSelectorSectionHeader.tsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelectorTablePicker/DataSelectorTablePicker.tsx
  frontend/src/metabase/query_builder/components/DataSelector/RawDataBackButton.tsx
  frontend/src/metabase/query_builder/components/DataSelector/TriggerComponents.tsx
  frontend/src/metabase/query_builder/components/DataSelector/constants.ts
  frontend/src/metabase/query_builder/components/DataSelector/data-search/SearchResults.jsx
  frontend/src/metabase/query_builder/components/DataSelector/data-search/SearchResults.module.css
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityList.module.css
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityList.styled.tsx
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityList.tsx
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityPicker.jsx
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityPicker.module.css
Labels: no-backport, .Team/Querying, PR-Env

#50842 Streamline embed flow when embedding is off
  e2e/test/scenarios/embedding/embedding-smoketests.cy.spec.js
  e2e/test/scenarios/sharing/public-sharing-embed-button-behavior.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/embedding/components/InteractiveEmbeddingSettings.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/common.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/enterprise.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/premium.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/InteractiveEmbeddingOptionCard/InteractiveEmbeddingOptionCard.tsx
  frontend/src/metabase/public/components/EmbedModal/EmbedModalContent/EmbedModalContent.unit.spec.tsx
  frontend/src/metabase/public/components/EmbedModal/EmbedModalContent/tests/EmbedModalContent.common.unit.spec.tsx
  frontend/src/metabase/public/components/EmbedModal/EmbedModalContent/tests/EmbedModalContent.enterprise.unit.spec.tsx
  frontend/src/metabase/public/components/EmbedModal/EmbedModalContent/tests/EmbedModalContent.premium.unit.spec.tsx
  frontend/src/metabase/public/components/EmbedModal/EmbedModalContent/tests/setup.tsx
  frontend/src/metabase/public/components/EmbedModal/SelectEmbedTypePane/SelectEmbedTypePane.tsx
  frontend/src/metabase/public/components/EmbedModal/SelectEmbedTypePane/SelectEmbedTypePane.unit.spec.tsx
  frontend/src/metabase/public/components/EmbedModal/SelectEmbedTypePane/SharingPaneButton/SharingPaneButton.module.css
  frontend/src/metabase/public/components/EmbedModal/SelectEmbedTypePane/SharingPaneButton/SharingPaneButton.tsx
  frontend/src/metabase/sharing/components/SharingMenu/MenuItems/EmbedMenuItem.tsx
  frontend/src/metabase/sharing/components/SharingMenu/MenuItems/PublicLinkMenuItem.tsx
  frontend/src/metabase/sharing/components/SharingMenu/test/DashboardSharingMenu.unit.spec.tsx
  frontend/src/metabase/sharing/components/SharingMenu/test/QuestionSharingMenu.unit.spec.tsx
  frontend/src/metabase/ui/components/typography/List/List.styled.tsx
  package.json
  yarn.lock
Labels: backport, .Team/Embedding

#50979 🤖 backported "Streamline embed flow when embedding is off"
  e2e/test/scenarios/embedding/embedding-smoketests.cy.spec.js
  e2e/test/scenarios/sharing/public-sharing-embed-button-behavior.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/embedding/components/InteractiveEmbeddingSettings.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/common.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/enterprise.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/premium.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/InteractiveEmbeddingOptionCard/InteractiveEmbeddingOptionCard.tsx
  frontend/src/metabase/public/components/EmbedModal/EmbedModalContent/EmbedModalContent.unit.spec.tsx
  frontend/src/metabase/public/components/EmbedModal/EmbedModalContent/tests/EmbedModalContent.common.unit.spec.tsx
  frontend/src/metabase/public/components/EmbedModal/EmbedModalContent/tests/EmbedModalContent.enterprise.unit.spec.tsx
  frontend/src/metabase/public/components/EmbedModal/EmbedModalContent/tests/EmbedModalContent.premium.unit.spec.tsx
  frontend/src/metabase/public/components/EmbedModal/EmbedModalContent/tests/setup.tsx
  frontend/src/metabase/public/components/EmbedModal/SelectEmbedTypePane/SelectEmbedTypePane.tsx
  frontend/src/metabase/public/components/EmbedModal/SelectEmbedTypePane/SelectEmbedTypePane.unit.spec.tsx
  frontend/src/metabase/public/components/EmbedModal/SelectEmbedTypePane/SharingPaneButton/SharingPaneButton.module.css
  frontend/src/metabase/public/components/EmbedModal/SelectEmbedTypePane/SharingPaneButton/SharingPaneButton.tsx
  frontend/src/metabase/sharing/components/SharingMenu/MenuItems/EmbedMenuItem.tsx
  frontend/src/metabase/sharing/components/SharingMenu/MenuItems/PublicLinkMenuItem.tsx
  frontend/src/metabase/sharing/components/SharingMenu/test/DashboardSharingMenu.unit.spec.tsx
  frontend/src/metabase/sharing/components/SharingMenu/test/QuestionSharingMenu.unit.spec.tsx
  frontend/src/metabase/ui/components/typography/List/List.styled.tsx
  package.json
  yarn.lock
Labels: was-backported

#50980 Improve queue test and add more buffering
  src/metabase/util/queue.clj
  test/metabase/util/queue_test.clj
Labels: backport, .Team/Workflows

#50981 🤖 backported "Improve queue test and add more buffering"
  src/metabase/util/queue.clj
  test/metabase/util/queue_test.clj
Labels: was-backported

#50837 Render negative values on PieChart
  .loki/reference/chrome_laptop_static_viz_PieChart_All_Negative.png
  .loki/reference/chrome_laptop_static_viz_PieChart_All_Negative_With_Other.png
  e2e/test/scenarios/visualizations-charts/pie_chart.cy.spec.js
  frontend/src/metabase/static-viz/components/PieChart/PieChart.stories.tsx
  frontend/src/metabase/static-viz/components/PieChart/stories-data/all-negative-with-other.json
  frontend/src/metabase/static-viz/components/PieChart/stories-data/index.ts
  frontend/src/metabase/visualizations/echarts/pie/model/index.ts
  frontend/src/metabase/visualizations/echarts/pie/model/types.ts
  frontend/src/metabase/visualizations/echarts/pie/option.ts
  frontend/src/metabase/visualizations/visualizations/PieChart/use-chart-events.ts
Labels: backport, .Team/DashViz

#50989 🤖 backported "Render negative values on PieChart"
  .loki/reference/chrome_laptop_static_viz_PieChart_All_Negative.png
  .loki/reference/chrome_laptop_static_viz_PieChart_All_Negative_With_Other.png
  e2e/test/scenarios/visualizations-charts/pie_chart.cy.spec.js
  frontend/src/metabase/static-viz/components/PieChart/PieChart.stories.tsx
  frontend/src/metabase/static-viz/components/PieChart/stories-data/all-negative-with-other.json
  frontend/src/metabase/static-viz/components/PieChart/stories-data/index.ts
  frontend/src/metabase/visualizations/echarts/pie/model/index.ts
  frontend/src/metabase/visualizations/echarts/pie/model/types.ts
  frontend/src/metabase/visualizations/echarts/pie/option.ts
  frontend/src/metabase/visualizations/visualizations/PieChart/use-chart-events.ts
Labels: was-backported

#50982 Fix rollback to version 50 with null query_field values
  dev/src/dev/migrate.clj
  resources/migrations/001_update_migrations.yaml
Labels: backport, .Team/Workflows

#50938 Encapsulate default models to search
  src/metabase/api/search.clj
  src/metabase/search/core.clj
  src/metabase/search/impl.clj
Labels: backport, .Team/Workflows

#50990 Fix race between jobs accessing the search index
  src/metabase/search/appdb/index.clj
  src/metabase/task/search_index.clj
Labels: backport, .Team/Workflows

#50953 Move specific date filter parts to MBQL lib
  frontend/src/metabase-lib/constants.ts
  frontend/src/metabase-lib/filter.ts
  frontend/src/metabase-lib/filter.unit.spec.ts
  frontend/src/metabase-lib/types.ts
  src/metabase/lib/core.cljc
  src/metabase/lib/fe_util.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/schema/filter.cljc
  src/metabase/util/time.cljc
  src/metabase/util/time/impl.clj
  src/metabase/util/time/impl.cljs
  src/metabase/util/time/impl_common.cljc
  test/metabase/lib/fe_util_test.cljc
  test/metabase/util/time_test.cljc
Labels: no-backport, .Team/Querying

#50840 🤖 backported "Show /api/search errors in Browse models and Browse metrics"
  e2e/test/scenarios/onboarding/home/browse.cy.spec.ts
  frontend/src/metabase/browse/metrics/BrowseMetrics.tsx
  frontend/src/metabase/browse/models/BrowseModels.tsx
Labels: was-backported

#51007 Pin webhook tester to v1
  .github/actions/e2e-prepare-containers/action.yml
  e2e/test/scenarios/admin-2/settings.cy.spec.js
  e2e/test/scenarios/question/saved.cy.spec.js
Labels: .CI & Tests, backport, .Team/AdminWebapp

#50965 Support FE display functions for during function
  src/metabase/legacy_mbql/normalize.cljc
  src/metabase/lib/fe_util.cljc
  src/metabase/lib/filter.cljc
  src/metabase/lib/schema/filter.cljc
  test/metabase/lib/fe_util_test.cljc
  test/metabase/lib/filter_test.cljc
  test/metabase/lib/js_test.cljs
Labels: no-backport, .Team/Querying

#49982 feat: Introduce describe-indexes
  docs/developers-guide/driver-changelog.md
  src/metabase/driver.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql_jdbc.clj
  src/metabase/driver/sql_jdbc/sync.clj
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
  src/metabase/sync/interface.clj
  src/metabase/sync/sync_metadata/indexes.clj
  test/metabase/driver/sql_jdbc/sync/describe_table_test.clj
Labels: backport, .Team/Drivers

#51022 Bump Malli to 0.17.0
  deps.edn
Labels: backport

#50991 Make Loki's embedding scroll stories more resilient
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardView.stories.tsx
Labels: backport, .Team/Embedding

#50841 Fix embed loader not translated with #locale
  e2e/support/helpers/e2e-embedding-helpers.js
  e2e/test/scenarios/embedding/embedding-reproductions.cy.spec.js
  frontend/src/metabase/components/LoadingAndErrorWrapper/LoadingAndErrorWrapper.jsx
  frontend/src/metabase/components/LoadingAndErrorWrapper/LoadingAndErrorWrapper.unit.spec.js
  frontend/src/metabase/public/LocaleProvider.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboard.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion.tsx
Labels: backport, .Team/Embedding

#50998 Add story for QuestionSettings
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/QuestionSettings/QuestionSettings.stories.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/QuestionSettings/QuestionSettings.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/QuestionSettings/index.ts
Labels: backport, .Team/Embedding

#50867 feat(sdk): use public-facing question type in event handlers
  e2e/test-component/scenarios/embedding-sdk/interactive-question.cy.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/SdkSaveQuestionForm.stories.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/InteractiveQuestionProvider.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/types.ts
  enterprise/frontend/src/embedding-sdk/index.ts
  enterprise/frontend/src/embedding-sdk/lib/plugins.ts
  enterprise/frontend/src/embedding-sdk/lib/transform-question.ts
  enterprise/frontend/src/embedding-sdk/lib/transform-question.unit.spec.ts
  enterprise/frontend/src/embedding-sdk/types/public/question.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenuItems.tsx
Labels: backport, .Team/Embedding, Embedding/SDK

#50993 🤖 backported "Fix rollback to version 50 with null query_field values"
  dev/src/dev/migrate.clj
  resources/migrations/001_update_migrations.yaml
Labels: was-backported

#51009 🤖 backported "Pin webhook tester to v1"
  .github/actions/e2e-prepare-containers/action.yml
  e2e/test/scenarios/admin-2/settings.cy.spec.js
  e2e/test/scenarios/question/saved.cy.spec.js
Labels: .CI & Tests, was-backported

#50890 feat(sdk): detect if session.id is not a string
  enterprise/frontend/src/embedding-sdk/store/auth.ts
  enterprise/frontend/src/embedding-sdk/test/sdk-config-errors.unit.spec.tsx
Labels: backport, .Team/Embedding

#50728 feat(sdk): support sql parameters in interactive questions
  docs/embedding/sdk/questions.md
  e2e/test-component/scenarios/embedding-sdk/interactive-question-native.cy.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/InteractiveQuestionProvider.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/types.ts
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.tsx
  enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.ts
  enterprise/frontend/src/embedding-sdk/hooks/private/use-load-question.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/lib/interactive-question/run-question-on-load.ts
  enterprise/frontend/src/embedding-sdk/lib/interactive-question/update-question.ts
  enterprise/frontend/src/embedding-sdk/types/question.ts
  frontend/src/metabase-lib/v1/Question.ts
  frontend/src/metabase/query_builder/actions/core/updateQuestion.ts
Labels: backport, .Team/Embedding, Embedding/SDK

#50585 feat(sdk): move non-auth config options to provider
  docs/embedding/sdk/appearance.md
  docs/embedding/sdk/authentication.md
  docs/embedding/sdk/config.md
  docs/embedding/sdk/dashboards.md
  docs/embedding/sdk/next-js.md
  docs/embedding/sdk/questions.md
  docs/embedding/sdk/quickstart.md
  e2e/support/helpers/component-testing-sdk/component-embedding-sdk-helpers.tsx
  e2e/test-component/scenarios/embedding-sdk/locale-on-provider.cy.spec.tsx
  e2e/test-component/scenarios/embedding-sdk/styles-tests.cy.spec.tsx
  enterprise/frontend/src/embedding-sdk/cli/snippets/embedding-provider-snippet.ts
  enterprise/frontend/src/embedding-sdk/components/private/SdkUsageProblem/SdkUsageProblemDisplay.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/private/SdkUsageProblem/index.tsx
  enterprise/frontend/src/embedding-sdk/components/public/CollectionBrowser/CollectionBrowser.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/public/CreateDashboardModal/CreateDashboardModal.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/public/CreateDashboardModal/use-create-dashboard-api.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/EditableDashboard.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion-multiple-questions.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion-themed.stories.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.EditorButton.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/public/MetabaseProvider.tsx
  enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/public/StaticQuestion/StaticQuestion.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/public/index.ts
  enterprise/frontend/src/embedding-sdk/hooks/private/use-init-data.ts
  enterprise/frontend/src/embedding-sdk/hooks/private/use-init-data.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/hooks/private/use-sdk-usage-problem.ts
  enterprise/frontend/src/embedding-sdk/index.ts
  enterprise/frontend/src/embedding-sdk/lib/usage-problem.ts
  enterprise/frontend/src/embedding-sdk/store/auth.ts
  enterprise/frontend/src/embedding-sdk/store/types.ts
  enterprise/frontend/src/embedding-sdk/test/CommonSdkCorsStoryWrapper.tsx
  enterprise/frontend/src/embedding-sdk/test/CommonSdkStoryWrapper.tsx
  enterprise/frontend/src/embedding-sdk/test/auth-flow.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/test/mocks/config.ts
  enterprise/frontend/src/embedding-sdk/test/sdk-compatibility-warning.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/test/sdk-config-errors.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/tests/sdk-locale-support.stories.tsx
  enterprise/frontend/src/embedding-sdk/tests/styling-sdk-tests.stories.tsx
  enterprise/frontend/src/embedding-sdk/types/auth-config.ts
  enterprise/frontend/src/embedding-sdk/types/index.ts
  frontend/src/metabase/visualizations/components/ChartTooltip/EChartsTooltip/EChartsTooltip.stories.tsx
  frontend/test/__support__/ui.tsx
Labels: backport, .Team/Embedding, Embedding/SDK

#51027 Pass dashboard_id in FE->BE context
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.tsx
  frontend/src/metabase/dashboard/hooks/use-register-dashboard-metabot-context.ts
  frontend/src/metabase/query_builder/containers/QueryBuilder.tsx
  frontend/src/metabase/query_builder/containers/use-register-query-builder-metabot-context.ts
Labels: .Team/Querying

#50962 Nested joins ignore temporal units
  src/metabase/query_processor/util/nest_query.clj
  test/metabase/query_processor/util/nest_query_test.clj
Labels: backport, .Team/Querying

#50964 If multiple limit or offset arguments are passed, only use the 1st one
  src/metabase/server/middleware/offset_paging.clj
  test/metabase/query_processor_test/offset_test.clj
  test/metabase/server/middleware/offset_paging_test.clj
Labels: backport, .Team/AdminWebapp

#50862 feat(sdk): use metabase type prefix and re-export types
  docs/embedding/sdk/dashboards.md
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveAdHocQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/types.ts
  enterprise/frontend/src/embedding-sdk/components/public/CollectionBrowser/CollectionBrowser.tsx
  enterprise/frontend/src/embedding-sdk/components/public/CreateQuestion/CreateQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/ConnectedDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/EditableDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/context.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/index.ts
  enterprise/frontend/src/embedding-sdk/components/public/MetabaseProvider.tsx
  enterprise/frontend/src/embedding-sdk/components/public/index.ts
  enterprise/frontend/src/embedding-sdk/index.ts
  enterprise/frontend/src/embedding-sdk/lib/plugins.ts
  enterprise/frontend/src/embedding-sdk/lib/plugins/dashboard.ts
  enterprise/frontend/src/embedding-sdk/store/auth.ts
  enterprise/frontend/src/embedding-sdk/store/reducer.ts
  enterprise/frontend/src/embedding-sdk/store/types.ts
  enterprise/frontend/src/embedding-sdk/test/sdk-compatibility-warning.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/types/auth-config.ts
  enterprise/frontend/src/embedding-sdk/types/refresh-token.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenuItems.tsx
  frontend/src/metabase/visualizations/click-actions/Mode/Mode.ts
  frontend/src/metabase/visualizations/click-actions/lib/modes.ts
Labels: backport, .Team/Embedding, Embedding/SDK

#44444 docs - generate config file
  docs/configuring-metabase/config-file.md
  docs/configuring-metabase/config-template.md
  docs/installation-and-operation/commands.md
  src/metabase/cmd.clj
  src/metabase/cmd/config_file_gen.clj
  src/metabase/cmd/env_var_dox.clj
  src/metabase/cmd/resources/config-file-intro.md
  src/metabase/cmd/resources/config-file-outro.md
  src/metabase/cmd/resources/config-template.yaml
  src/metabase/public_settings.clj
  test/metabase/cmd/config_file_gen_test.clj
  test/metabase/cmd_test.clj
  test/metabase/public_settings_test.clj
Labels: backport

#51046 Fix browse models e2e tests
  e2e/test/scenarios/onboarding/home/browse.cy.spec.ts
Labels: no-backport, .Team/AdminWebapp
