Repository metabase/metabase, pull requests merged in 2024-09, with the labels that each got.

#47445 [serdes] a bit more valuable ns docstring
  enterprise/backend/src/metabase_enterprise/serialization/v2/models.clj
  src/metabase/models/serialization.clj
Labels: no-backport, .Team/BackendComponents

#47498 Upgrade Macaw to 0.2.10
  deps.edn
Labels: no-backport, .Team/BackendComponents

#46958 FE - e2e - Cover dashboard filters with tests
  e2e/test/scenarios/dashboard-filters/dashboard-filters-query-stages.cy.spec.ts
  enterprise/frontend/src/metabase-enterprise/sandboxes/components/EditSandboxingModal/EditSandboxingModal.unit.spec.tsx
  frontend/src/metabase-lib/v1/parameters/utils/targets.ts
  frontend/src/metabase/parameters/utils/mapping-options.ts
  frontend/src/metabase/parameters/utils/mapping-options.unit.spec.js
  frontend/src/metabase/querying/filters/hooks/use-filter-modal/use-filter-modal.ts
  frontend/src/metabase/querying/filters/hooks/use-filter-modal/utils/filters.ts
  src/metabase/legacy_mbql/util.cljc
  src/metabase/query_processor/card.clj
  src/metabase/query_processor/middleware/parameters/mbql.clj
  test/metabase/query_processor/middleware/parameters/mbql_test.clj
Labels: no-backport, .Team/Querying

#47499 [serdes] fix grammar mistakes in the doc
  src/metabase/models/serialization.clj
Labels: no-backport, .Team/BackendComponents

#47441 Indicate which column is used in reference validator sort test
  enterprise/backend/test/metabase_enterprise/query_reference_validation/api_test.clj
Labels: no-backport, .Team/BackendComponents

#47309 Maintain selected folder state in Entity Picker
  frontend/src/metabase/common/components/CollectionPicker/components/CollectionPickerModal.tsx
  frontend/src/metabase/common/components/DashboardPicker/components/DashboardPickerModal.tsx
  frontend/src/metabase/common/components/DataPicker/components/DataPickerModal.tsx
  frontend/src/metabase/common/components/DataPicker/components/DatabaseList.tsx
  frontend/src/metabase/common/components/DataPicker/components/SchemaList.tsx
  frontend/src/metabase/common/components/DataPicker/components/TableList.tsx
  frontend/src/metabase/common/components/DataPicker/components/TablePicker.tsx
  frontend/src/metabase/common/components/DataPicker/types.ts
  frontend/src/metabase/common/components/DataPicker/utils.ts
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/EntityPickerModal.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/EntityPickerModal.unit.spec.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/TabsView.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerSearch/EntityPickerSearch.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerSearch/utils.ts
  frontend/src/metabase/common/components/EntityPicker/constants.ts
  frontend/src/metabase/common/components/EntityPicker/hooks/use-log-recent-item.tsx
  frontend/src/metabase/common/components/EntityPicker/types.ts
  frontend/src/metabase/common/components/EntityPicker/utils.ts
  frontend/src/metabase/common/components/QuestionPicker/components/QuestionPickerModal.tsx
Labels: no-backport, .Team/Querying

#47229 feat(sdk): improve license, mock server and post-install for embedding cli
  enterprise/frontend/src/embedding-sdk/README.md
  enterprise/frontend/src/embedding-sdk/cli/constants/config.ts
  enterprise/frontend/src/embedding-sdk/cli/constants/messages.ts
  enterprise/frontend/src/embedding-sdk/cli/constants/mock-server-package-json.ts
  enterprise/frontend/src/embedding-sdk/cli/run.ts
  enterprise/frontend/src/embedding-sdk/cli/snippets/analytics-provider-snippet.ts
  enterprise/frontend/src/embedding-sdk/cli/snippets/express-server-snippet.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/ask-tenancy-columns.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/generate-component-files.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/generate-credentials.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/generate-express-server-file.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/index.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/setup-license.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/setup-permission.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/show-post-setup-steps.ts
  enterprise/frontend/src/embedding-sdk/cli/types/cli.ts
  enterprise/frontend/src/embedding-sdk/cli/utils/get-tenancy-isolation-sandboxes.ts
  enterprise/frontend/src/embedding-sdk/cli/utils/install-mock-server-deps.ts
  enterprise/frontend/src/embedding-sdk/cli/utils/sample-tenancy-column-values.ts
Labels: no-backport, .Team/Embedding, Embedding/SDK

#47469 Use function arguments rather than a dynamic var
  enterprise/backend/src/metabase_enterprise/serialization/load.clj
  src/metabase/models/database.clj
  src/metabase/models/field_values.clj
  src/metabase/models/serialization.clj
Labels: backport, .Team/BackendComponents

#47303 Use original display name for fields in uploaded tables
  src/metabase/upload.clj
  test/metabase/upload_test.clj
Labels: backport, .Team/BackendComponents

#47508 Update SDK version to 0.1.34
  enterprise/frontend/src/embedding-sdk/CHANGELOG.md
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: no-backport

#47504 🤖 backported "Use function arguments rather than a dynamic var"
  enterprise/backend/src/metabase_enterprise/serialization/load.clj
  src/metabase/models/field_values.clj
  src/metabase/models/serialization.clj
Labels: was-backported

#47400 Followup on "Fix crash when navigating between bookmarked dashboards"
  e2e/test/scenarios/dashboard/dashboard-reproductions.cy.spec.js
  frontend/src/metabase-types/guards/click-behavior.ts
  frontend/src/metabase-types/guards/common.ts
  frontend/src/metabase-types/guards/index.ts
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx
  frontend/src/metabase/dashboard/types/fetch-dashboard-result.ts
Labels: backport, .Team/DashViz

#47507 🤖 backported "Use original display name for fields in uploaded tables"
  src/metabase/upload.clj
  test/metabase/upload_test.clj
Labels: was-backported

#47484 Use table name in inactive table error if user has access to it
  src/metabase/models/data_permissions.clj
  src/metabase/query_processor/middleware/permissions.clj
  test/metabase/query_processor/middleware/permissions_test.clj
Labels: backport, .Team/AdminWebapp

#47481 Use consistent approach for disabling permission checks in QP to fix sandboxing error in downloads
  enterprise/backend/src/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/dataset_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/download_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/pulse_test.clj
  src/metabase/models/query/permissions.clj
  src/metabase/query_processor/middleware/add_source_metadata.clj
  src/metabase/query_processor/util/nest_query.clj
  test/metabase/api/card_test.clj
Labels: backport, .Team/AdminWebapp

#47511 backport "[serdes] a bit more valuable ns docstring"
  enterprise/backend/src/metabase_enterprise/serialization/v2/models.clj
  src/metabase/models/serialization.clj
Labels: .Team/BackendComponents, was-backported

#47489 Disallow duplicate order-by clauses in ::lib.schema.order-by/order-bys
  src/metabase/lib/order_by.cljc
  src/metabase/lib/schema/order_by.cljc
  src/metabase/lib/schema/util.cljc
  src/metabase/query_processor/util.clj
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/remove_replace_test.cljc
  test/metabase/lib/schema/order_by_test.cljc
  test/metabase/lib/schema/util_test.cljc
  test/metabase/lib/schema_test.cljc
  test/metabase/query_processor/middleware/normalize_query_test.clj
  test/metabase/query_processor_test/order_by_test.clj
Labels: backport, .Team/Querying

#47442 fix(sdk): Add toggle for saving questions
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult.tsx
  enterprise/frontend/src/embedding-sdk/components/private/QuestionEditor/QuestionEditor.tsx
  enterprise/frontend/src/embedding-sdk/components/public/CreateQuestion/CreateQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/public/ModifyQuestion/ModifyQuestion.tsx
Labels: no-backport, .Team/Embedding

#47210 feat(sdk): Use stable IDs in SDK components
  enterprise/frontend/src/embedding-sdk/README.md
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/InteractiveQuestionProvider.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/ConnectedDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/StaticQuestion/StaticQuestion.tsx
  enterprise/frontend/src/embedding-sdk/lib/interactive-question/run-question-on-load.ts
  enterprise/frontend/src/embedding-sdk/types/question.ts
  frontend/src/metabase-types/api/actions.ts
  frontend/src/metabase-types/api/alert.ts
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase-types/api/dashboard.ts
  frontend/src/metabase-types/api/entity-id.ts
  frontend/src/metabase-types/api/index.ts
  frontend/src/metabase-types/api/mocks/actions.ts
  frontend/src/metabase-types/api/mocks/alert.ts
  frontend/src/metabase-types/api/mocks/card.ts
  frontend/src/metabase-types/api/mocks/dashboard.ts
  frontend/src/metabase-types/api/mocks/entity-id.ts
  frontend/src/metabase-types/api/mocks/snippets.ts
  frontend/src/metabase-types/api/snippets.ts
  frontend/src/metabase-types/api/subscription.ts
  frontend/src/metabase/actions/containers/ActionCreator/ActionContext/QueryActionContextProvider/QueryActionContextProvider.tsx
  frontend/src/metabase/api/entity-id.ts
  frontend/src/metabase/api/index.ts
  frontend/src/metabase/dashboard/actions/tabs.ts
  frontend/src/metabase/dashboard/actions/utils.unit.spec.ts
  frontend/src/metabase/dashboard/components/DashboardTabs/test-utils.ts
  frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts
  frontend/src/metabase/lib/errors/messages.ts
  src/metabase/api/embed/common.clj
  test/metabase/api/embed_test.clj
  test/metabase/api/util_test.clj
Labels: no-backport, .Team/Embedding

#47213 Remove drilled props from ViewFooter components
  frontend/src/metabase/query_builder/components/view/QuestionTimelineWidget/QuestionTimelineWidget.tsx
  frontend/src/metabase/query_builder/components/view/View.jsx
  frontend/src/metabase/query_builder/components/view/ViewFooter/CenterViewFooterButtonGroup.tsx
  frontend/src/metabase/query_builder/components/view/ViewFooter/LeftViewFooterButtonGroup.tsx
  frontend/src/metabase/query_builder/components/view/ViewFooter/RightViewFooterButtonGroup.tsx
  frontend/src/metabase/query_builder/components/view/ViewFooter/ViewFooter.tsx
  frontend/src/metabase/query_builder/components/view/ViewFooter/ViewFooterDownloadWidget.tsx
Labels: no-backport, .Team/Embedding

#47530 🤖 backported "Use consistent approach for disabling permission checks in QP to fix sandboxing error in downloads"
  enterprise/backend/src/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/dataset_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/download_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/pulse_test.clj
  src/metabase/models/query/permissions.clj
  src/metabase/query_processor/middleware/add_source_metadata.clj
  src/metabase/query_processor/util/nest_query.clj
  test/metabase/api/card_test.clj
Labels: was-backported

#47532 🤖 backported "Disallow duplicate order-by clauses in ::lib.schema.order-by/order-bys"
  src/metabase/lib/order_by.cljc
  src/metabase/lib/schema/order_by.cljc
  src/metabase/lib/schema/util.cljc
  src/metabase/query_processor/util.clj
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/remove_replace_test.cljc
  test/metabase/lib/schema/order_by_test.cljc
  test/metabase/lib/schema/util_test.cljc
  test/metabase/lib/schema_test.cljc
  test/metabase/query_processor/middleware/normalize_query_test.clj
  test/metabase/query_processor_test/order_by_test.clj
Labels: was-backported

#47529 Implement a simple greedy approximation for dedupe-joins
  deps.edn
  src/metabase/models/params/chain_filter/dedupe_joins.clj
  test/metabase/models/params/chain_filter/dedupe_joins_test.clj
Labels: backport, .Team/Querying

#46586 Use app DB for query execution metrics
  src/metabase/analytics/stats.clj
  test/metabase/analytics/stats_test.clj
  test/metabase/db/test_util.clj
  test/metabase/test.clj
Labels: backport, .Team/BackendComponents

#47551 [serdes] reveal exception causes
  enterprise/backend/src/metabase_enterprise/serialization/api.clj
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj
  enterprise/backend/test/metabase_enterprise/serialization/api_test.clj
  src/metabase/cmd.clj
  src/metabase/models/serialization.clj
Labels: backport, .Team/BackendComponents

#47556 🤖 backported "[serdes] reveal exception causes"
  enterprise/backend/src/metabase_enterprise/serialization/api.clj
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj
  enterprise/backend/test/metabase_enterprise/serialization/api_test.clj
  src/metabase/cmd.clj
  src/metabase/models/serialization.clj
Labels: was-backported

#47512 Refine 'last' version logic
  release/src/milestones.ts
  release/src/version-helpers.ts
  release/src/version-helpers.unit.spec.ts
Labels: .Building & Releasing, no-backport, .Team/AdminWebapp

#47089 Toggle series visibility from chart legend (cartesian charts)
  e2e/support/helpers/e2e-visual-tests-helpers.js
  e2e/test/scenarios/visualizations-charts/bar_chart.cy.spec.js
  e2e/test/scenarios/visualizations-charts/legend.cy.spec.js
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/AddSeriesButton/AddSeriesButton.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/query_builder/components/VisualizationResult.jsx
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.tsx
  frontend/src/metabase/static-viz/components/ComboChart/settings.ts
  frontend/src/metabase/static-viz/components/ScatterPlot/ScatterPlot.tsx
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.tsx
  frontend/src/metabase/visualizations/components/ChartTooltip/EChartsTooltip/EChartsTooltip.tsx
  frontend/src/metabase/visualizations/components/legend/Legend.jsx
  frontend/src/metabase/visualizations/components/legend/Legend.styled.tsx
  frontend/src/metabase/visualizations/components/legend/LegendItem.jsx
  frontend/src/metabase/visualizations/components/legend/LegendItem.styled.tsx
  frontend/src/metabase/visualizations/components/legend/LegendItemDot.styled.tsx
  frontend/src/metabase/visualizations/components/legend/LegendItemDot.tsx
  frontend/src/metabase/visualizations/components/legend/LegendLayout.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingOrderedItems/ChartSettingOrderedItems.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingSeriesOrder.tsx
  frontend/src/metabase/visualizations/components/settings/ColumnItem/ColumnItem.tsx
  frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/legend.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/legend.unit.spec.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/series.unit.spec.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/trend-line.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/types.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/scatter/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/scatter/option/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/index.ts
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/src/metabase/visualizations/types/visualization.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/CartesianChart.tsx
  frontend/src/metabase/visualizations/visualizations/CartesianChart/events.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-models-and-option.ts
  frontend/test/__support__/echarts.ts
Labels: no-backport, .Team/DashViz

#47427 [MBQL lib] Allow temporal bucketing of Date(Time) expressions
  e2e/test/scenarios/custom-column/custom-column.cy.spec.js
  e2e/test/scenarios/dashboard-filters/temporal-unit-parameters.cy.spec.js
  e2e/test/scenarios/question/column-compare.cy.spec.ts
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.unit.spec.tsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.unit.spec.tsx
  src/metabase/lib/expression.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/schema/ref.cljc
  src/metabase/lib/temporal_bucket.cljc
  src/metabase/query_processor/middleware/annotate.clj
  src/metabase/query_processor/middleware/parameters/mbql.clj
  test/metabase/lib/temporal_bucket_test.cljc
Labels: backport, .Team/Querying

#47395 backported "Much better collection permission performance" (#47251)
  resources/migrations/001_update_migrations.yaml
  resources/migrations/permissions/collection-access-h2.sql
  resources/migrations/permissions/collection-access-mariadb.sql
  resources/migrations/permissions/collection-access.sql
  src/metabase/api/action.clj
  src/metabase/api/collection.clj
  src/metabase/api/database.clj
  src/metabase/api/search.clj
  src/metabase/api/timeline.clj
  src/metabase/api/user.clj
  src/metabase/config.clj
  src/metabase/models/collection.clj
  src/metabase/models/permissions.clj
  src/metabase/server/middleware/request_id.clj
  test/metabase/api/user_test.clj
  test/metabase/db/schema_migrations_test.clj
  test/metabase/models/collection_test.clj
  test/metabase/models/permissions_test.clj
Labels: .Team/AdminWebapp

#47456 🤖 backported "Check joins in lib.metadata/editable?"
  src/metabase/lib/metadata.cljc
  test/metabase/lib/metadata_test.cljc
Labels: was-backported

#47503 🤖 backported "Simplify finding metrics in Summarize"
  e2e/test/scenarios/admin/datamodel/metrics.cy.spec.js
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.tsx
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.unit.spec.tsx
  src/metabase/lib/legacy_metric.cljc
Labels: was-backported

#47572 Add v0.49.25 to the list of releases
  docs/releases.md
Labels: Type:Documentation, backport

#47573 🤖 backported "Add v0.49.25 to the list of releases"
  docs/releases.md
Labels: was-backported

#47577 docs - note on DuckDB
  docs/developers-guide/partner-and-community-drivers.md
Labels: Type:Documentation, backport

#47578 🤖 backported "docs - note on DuckDB"
  docs/developers-guide/partner-and-community-drivers.md
Labels: was-backported

#46776 [FE] Allow multiple breakouts for a column
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/question/multiple-column-breakouts.cy.spec.ts
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeSidebar.unit.spec.tsx
  frontend/src/metabase/querying/notebook/components/BreakoutStep/BreakoutStep.tsx
  frontend/src/metabase/querying/notebook/components/BreakoutStep/BreakoutStep.unit.spec.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.jsx
  src/metabase/lib/equality.cljc
  test/metabase/lib/equality_test.cljc
  test/metabase/lib/field_test.cljc
Labels: no-backport, .Team/Querying

#47574 Don't update updated_at when setting last_used_at on a card
  src/metabase/query_processor/middleware/results_metadata.clj
  src/metabase/query_processor/middleware/update_used_cards.clj
  test/metabase/query_processor/middleware/results_metadata_test.clj
  test/metabase/query_processor/middleware/update_used_cards_test.clj
Labels: backport, .Team/AdminWebapp

#47571 upgrade micromatch to address security issue
  release/yarn.lock
  yarn.lock
Labels: backport, .Team/Querying

#47548 🤖 backported "Implement a simple greedy approximation for dedupe-joins"
  deps.edn
  src/metabase/models/params/chain_filter/dedupe_joins.clj
  test/metabase/models/params/chain_filter/dedupe_joins_test.clj
Labels: was-backported

#47580 🤖 backported "Don't update updated_at when setting last_used_at on a card"
  src/metabase/query_processor/middleware/results_metadata.clj
  src/metabase/query_processor/middleware/update_used_cards.clj
  test/metabase/query_processor/middleware/results_metadata_test.clj
  test/metabase/query_processor/middleware/update_used_cards_test.clj
Labels: was-backported

#47516 🤖 backported "Use table name in inactive table error if user has access to it"
  src/metabase/models/data_permissions.clj
  src/metabase/query_processor/middleware/permissions.clj
  test/metabase/query_processor/middleware/permissions_test.clj
Labels: was-backported

#47583 🤖 backported "upgrade micromatch to address security issue"
  release/yarn.lock
  yarn.lock
Labels: was-backported

#47539 Remove phantom tooltips when there is no label on tooltip
  frontend/src/metabase/core/components/Input/Input.tsx
  frontend/src/metabase/core/components/Input/Input.unit.spec.tsx
Labels: no-backport, .Team/Embedding

#47538 fix(sdk): Add `onSave` behavior to `QuestionEditor`
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/SdkSaveQuestionForm.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/index.ts
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/InteractiveQuestionProvider.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/types.ts
  enterprise/frontend/src/embedding-sdk/components/private/QuestionEditor/QuestionEditor.tsx
  enterprise/frontend/src/embedding-sdk/components/public/CreateQuestion/CreateQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/public/ModifyQuestion/ModifyQuestion.tsx
Labels: no-backport, .Team/Embedding

#47568 🤖 backported "[MBQL lib] Allow temporal bucketing of Date(Time) expressions"
  e2e/test/scenarios/custom-column/custom-column.cy.spec.js
  frontend/src/metabase/query_builder/containers/QueryBuilder.unit.spec.tsx
  src/metabase/lib/expression.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/schema/ref.cljc
  src/metabase/lib/temporal_bucket.cljc
  src/metabase/query_processor/middleware/annotate.clj
  src/metabase/query_processor/middleware/parameters/mbql.clj
  test/metabase/lib/temporal_bucket_test.cljc
Labels: was-backported

#47593 docs: pro callout for subscriptions
  docs/dashboards/subscriptions.md
Labels: Type:Documentation, backport

#47594 🤖 backported "docs: pro callout for subscriptions"
  docs/dashboards/subscriptions.md
Labels: was-backported

#47591 Add v0.50.24 to the list of releases
  docs/releases.md
Labels: Type:Documentation, backport

#47598 🤖 backported "Add v0.50.24 to the list of releases"
  docs/releases.md
Labels: was-backported

#47585 upgrade webpack to address security issue
  package.json
  yarn.lock
Labels: backport, .Team/Querying

#47605 add more stuff to migrations doc
  resources/migrations/001_update_migrations.yaml
Labels: no-backport, .Team/BackendComponents

#47612 Manual backport — Followup on "Fix crash when navigating between bookmarked dashboards"
  e2e/test/scenarios/dashboard/dashboard-reproductions.cy.spec.js
  frontend/src/metabase-types/guards/click-behavior.ts
  frontend/src/metabase-types/guards/common.ts
  frontend/src/metabase-types/guards/index.ts
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx
  frontend/src/metabase/dashboard/types.ts
  yarn.lock
Labels: .Team/DashViz

#47607 Update default locked parameter value
  e2e/test/scenarios/embedding/embedding-dashboard.cy.spec.js
  e2e/test/scenarios/embedding/embedding-native.cy.spec.js
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/StaticEmbedSetupPane.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/tests/common.unit.spec.tsx
Labels: backport, .Team/Embedding

#47599 fix time series with data gaps stacked bar charts crash when enabling segments labels
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Stacked_All_Labels_Timeseries_With_Gap_45717.png
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/bar-stacked-all-labels-timeseries-with-gap-45717.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/chart-measurements/index.ts
Labels: backport, .Team/DashViz

#47519 Add embedding SDK admin settings tests
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/common.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/common.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/enterprise.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/premium.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/types.ts
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings.tsx
Labels: .Team/Embedding

#47453 Notifications Followup
  e2e/test/scenarios/admin-2/settings.cy.spec.js
  frontend/src/metabase/admin/settings/notifications/WebhookForm.tsx
  frontend/src/metabase/admin/settings/slack/components/SlackSettings/SlackSettings.tsx
Labels: no-backport, .Team/AdminWebapp

#47623 Pass string auto param to ee-extra
  .github/workflows/release.yml
Labels: .Building & Releasing, no-backport, .Team/AdminWebapp

#47618 Fix `:selected?` property of `visible-columns` (CLJS only)
  e2e/test/scenarios/question/multiple-column-breakouts.cy.spec.ts
  src/metabase/lib/js.cljs
Labels: no-backport, .Team/Querying

#47609 clean output folder to avoid bloating
  package.json
  yarn.lock
Labels: no-backport, .Team/Querying

#47625 🤖 backported "rename event -> simple_event and trackEvent -> trackSimpleEvent"
  frontend/src/metabase-types/analytics/schema.ts
  frontend/src/metabase/lib/analytics.ts
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/UploadCSV/analytics.ts
  snowplow/iglu-client-embedded/schemas/com.metabase/event/jsonschema/1-0-0
  snowplow/iglu-client-embedded/schemas/com.metabase/simple_event/jsonschema/1-0-0
Labels: was-backported

#47619 🤖 backported "fix time series with data gaps stacked bar charts crash when enabling segments labels"
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Stacked_All_Labels_Timeseries_With_Gap_45717.png
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/bar-stacked-all-labels-timeseries-with-gap-45717.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/chart-measurements/index.ts
Labels: was-backported

#47308 🤖 backported "Entity id translation service"
  src/metabase/api/common.clj
  src/metabase/api/embed/common.clj
  src/metabase/api/util.clj
  src/metabase/search/config.clj
  test/metabase/api/embed_test.clj
  test/metabase/api/util_test.clj
Labels: was-backported

#47544 fix: sqlserver handle uniqueidentifier uuids
  modules/drivers/athena/test/metabase/test/data/athena.clj
  modules/drivers/oracle/src/metabase/driver/oracle.clj
  modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj
  modules/drivers/sqlserver/test/metabase/test/data/sqlserver.clj
  src/metabase/driver/sql/query_processor.clj
  test/metabase/driver/sql_jdbc_test.clj
  test/metabase/test/data/h2.clj
Labels: backport, .Team/Drivers

#47432 Entity id translation analytics
  src/metabase/api/embed/common.clj
  test/metabase/api/embed/common_test.clj
  test/metabase/api/embed_test.clj
  test/metabase/api/util_test.clj
Labels: backport, .Team/AdminWebapp

#47545 docs: clarify cumulative aggregations
  docs/questions/images/cumulative-metric-plus-sort.png
  docs/questions/images/cumulative-metric-reverse.png
  docs/questions/images/cumulative-metric.png
  docs/questions/query-builder/expressions-list.md
  docs/questions/query-builder/expressions/cumulative.md
Labels: Type:Documentation, backport

#47645 🤖 backported "docs: clarify cumulative aggregations"
  docs/questions/images/cumulative-metric-plus-sort.png
  docs/questions/images/cumulative-metric-reverse.png
  docs/questions/images/cumulative-metric.png
  docs/questions/query-builder/expressions-list.md
  docs/questions/query-builder/expressions/cumulative.md
Labels: was-backported

#47418 Bump Kondo version to 2024.08.29
  deps.edn
  enterprise/backend/src/metabase_enterprise/airgap.clj
  src/metabase/api/activity.clj
  src/metabase/models/recent_views.clj
  src/metabase/public_settings/premium_features.clj
  src/metabase/search/impl.clj
Labels: no-backport, .Team/DevEx

#47589 Store ::nil markers in CachedMetadataProvider for failed lookups
  src/metabase/lib/metadata/cached_provider.cljc
  src/metabase/lib/metadata/protocols.cljc
  test/metabase/lib/metadata/cached_provider_test.cljc
Labels: backport, .Team/Querying

#47629 fix hidden pivot table scroll bar in QB
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Number.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Quarter_Year_Dropdown.png
  .loki/reference/chrome_laptop_viz_PivotTable_No_Outer_Horizontal_Scroll.png
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.stories.tsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.styled.tsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.tsx
Labels: backport, .Team/DashViz, loki-update

#47647 🤖 backported "fix hidden pivot table scroll bar in QB"
  .loki/reference/chrome_laptop_viz_PivotTable_No_Outer_Horizontal_Scroll.png
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.styled.tsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.tsx
Labels: was-backported

#47553 Rename 'Date Filter' to 'All Options' in field filters
  e2e/test/scenarios/dashboard-filters/dashboard-filters-date.cy.spec.js
  e2e/test/scenarios/dashboard-filters/parameters.cy.spec.js
  e2e/test/scenarios/native-filters/helpers/e2e-field-filter-data-objects.js
  e2e/test/scenarios/native-filters/sql-field-filter-types.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions-1.cy.spec.js
  frontend/src/metabase-lib/v1/parameters/constants.ts
Labels: no-backport, .Team/Querying

#47634 API endpoint dox generation should resolve schemas from the registry
  .clj-kondo/config.edn
  src/metabase/util/malli/describe.cljc
  src/metabase/util/malli/registry.cljc
  test/metabase/api/card_test.clj
  test/metabase/api/common/internal_test.clj
  test/metabase/util/malli/describe_test.cljc
  test/metabase/util/malli/registry_test.cljc
Labels: backport, .Team/DevEx

#47652 Use i18n-appropriate string interpolation for card copying
  src/metabase/api/card.clj
Labels: no-backport, .Team/BackendComponents

#47651 perf: Add more timeseries insights optimizations
  src/metabase/analyze/fingerprint/insights.clj
Labels: backport

#47653 [serdes] improve dir detection
  enterprise/backend/src/metabase_enterprise/serialization/api.clj
Labels: backport, .Team/BackendComponents

#47662 🤖 backported "perf: Add more timeseries insights optimizations"
  src/metabase/analyze/fingerprint/insights.clj
Labels: was-backported

#47611 Revert "Hide upload config when data warehouse is attached"
  e2e/test/scenarios/admin-2/settings.cy.spec.js
  frontend/src/metabase/admin/settings/selectors.js
  src/metabase/public_settings.clj
  test/metabase/api/setting_test.clj
Labels: backport

#47650 Dashboard subscriptions and alerts should exclude archived cards
  src/metabase/pulse/util.clj
  test/metabase/dashboard_subscription_test.clj
  test/metabase/pulse_test.clj
Labels: backport, .Team/BackendComponents

#47664 🤖 backported "[serdes] improve dir detection"
  enterprise/backend/src/metabase_enterprise/serialization/api.clj
Labels: was-backported

#47631 Fix query type and respect user parameters in search
  src/metabase/api/search.clj
  src/metabase/models/collection.clj
  src/metabase/search/config.clj
  src/metabase/search/impl.clj
  test/metabase/search/filter_test.clj
  test/metabase/search/impl_test.clj
Labels: backport, .Team/BackendComponents

#47410 newsletter-toggle-clicked event
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.ts
  frontend/src/metabase-types/analytics/event.ts
  frontend/src/metabase/setup/components/CompletedStep/CompletedStep.tsx
Labels: backport, .Team/Embedding

#47635 docs - embedding params edits
  docs/embedding/static-embedding-parameters.md
  docs/embedding/static-embedding.md
  docs/questions/sharing/public-links.md
Labels: Type:Documentation, backport

#47671 🤖 backported "docs - embedding params edits"
  docs/embedding/static-embedding-parameters.md
  docs/embedding/static-embedding.md
  docs/questions/sharing/public-links.md
Labels: was-backported

#47669 🤖 backported "newsletter-toggle-clicked event"
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.ts
  frontend/src/metabase-types/analytics/event.ts
  frontend/src/metabase/setup/components/CompletedStep/CompletedStep.tsx
Labels: was-backported

#47648 Add .swc to gitignore in the v50 release branch
  .gitignore
Labels: .Team/DashViz

#47665 [insights] Simplify args to simple-linear-regresion
  src/metabase/analyze/fingerprint/insights.clj
Labels: backport

#47643 Use `:description` instead of `:doc/message` for Malli docstrings
  src/metabase/legacy_mbql/schema.cljc
  src/metabase/legacy_mbql/schema/helpers.cljc
  src/metabase/lib/schema/common.cljc
  src/metabase/lib/schema/id.cljc
  src/metabase/util/malli/doc.clj
  src/metabase/util/malli/registry.cljc
Labels: no-backport, .Team/DevEx

#47622 Fix visualization with warnings doesn't work when embedding
  e2e/test/scenarios/embedding/embedding-reproductions.cy.spec.js
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
Labels: .Team/Embedding

#47678 🤖 backported "[insights] Simplify args to simple-linear-regresion"
  src/metabase/analyze/fingerprint/insights.clj
Labels: was-backported

#47659 fix(sdk): fix typescript type references to "embedding-sdk" not resolving
  bin/embedding-sdk/fixup-types-after-compilation.js
Labels: no-backport, .Team/Embedding

#47679 perf: Miscellaneous card rendering improvements
  src/metabase/driver/sql_jdbc/execute.clj
  src/metabase/util/date_2.clj
  src/metabase/util/performance.clj
Labels: backport

#47592 Support field remapping in pivot queries
  src/metabase/query_processor/pivot.clj
  test/metabase/api/dataset_test.clj
  test/metabase/query_processor/pivot_test.clj
  test/metabase/query_processor_test/remapping_test.clj
Labels: backport, .Team/Querying

#47680 Revert multiple inheritance with SnowflakeVariant
  src/metabase/types.cljc
Labels: backport, .Team/Querying

#47691 🤖 backported "perf: Miscellaneous card rendering improvements"
  src/metabase/driver/sql_jdbc/execute.clj
  src/metabase/util/date_2.clj
  src/metabase/util/performance.clj
Labels: was-backported

#47482 Catch Errors in Download process and only write error message
  src/metabase/async/streaming_response.clj
  src/metabase/query_processor/streaming.clj
  test/metabase/api/downloads_exports_test.clj
  test/metabase/query_processor/streaming/csv_test.clj
Labels: backport, .Team/DashViz

#47368 Metrics notebook step restrictions
  e2e/test/scenarios/metrics/metrics-editing.cy.spec.js
  e2e/test/scenarios/question/notebook-link-to-data-source.cy.spec.ts
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx
  frontend/src/metabase/query_builder/components/DatasetEditor/MetricEmptyState/MetricEmptyState.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/MetricEmptyState/MetricEmptyState.unit.spec.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/MetricEmptyState/index.ts
  frontend/src/metabase/querying/notebook/components/AggregateStep/AggregateStep.tsx
  frontend/src/metabase/querying/notebook/components/AggregateStep/AggregateStep.unit.spec.tsx
  frontend/src/metabase/querying/notebook/components/BreakoutStep/BreakoutStep.tsx
  frontend/src/metabase/querying/notebook/components/BreakoutStep/BreakoutStep.unit.spec.tsx
  frontend/src/metabase/querying/notebook/components/ClauseStep/ClauseStep.tsx
  frontend/src/metabase/querying/notebook/components/DataStep/DataStep.tsx
  frontend/src/metabase/querying/notebook/components/DataStep/DataStep.unit.spec.tsx
  frontend/src/metabase/querying/notebook/components/NotebookCell/NotebookCell.styled.tsx
  frontend/test/__support__/server-mocks/database.ts
  frontend/test/__support__/server-mocks/table.ts
Labels: no-backport, .Team/Querying

#47636 Add a quick test for perms on timeline API
  test/metabase/api/collection_test.clj
Labels: no-backport, .Team/AdminWebapp

#47626 New can-run/can-save restrictions for metrics
  src/metabase/lib/query.cljc
  test/metabase/lib/query_test.cljc
Labels: no-backport, .Team/Querying

#47703 docs - update api docs
  docs/api/card.md
  docs/api/field.md
Labels: Type:Documentation, no-backport

#47696 🤖 backported "Catch Errors in Download process and only write error message"
  src/metabase/async/streaming_response.clj
  src/metabase/query_processor/streaming.clj
  test/metabase/api/downloads_exports_test.clj
  test/metabase/query_processor/streaming/csv_test.clj
Labels: was-backported

#47543 Add CardDisplayType type to narrow values for charts
  enterprise/frontend/src/embedding-sdk/hooks/private/use-sdk-element-size.ts
  enterprise/frontend/src/embedding-sdk/lib/default-height.ts
  frontend/src/metabase-lib/v1/Question.ts
  frontend/src/metabase-types/api/activity.ts
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase-types/api/collection.ts
  frontend/src/metabase-types/api/dashboard.ts
  frontend/src/metabase-types/api/index.ts
  frontend/src/metabase-types/api/search.ts
  frontend/src/metabase-types/api/visualization.ts
  frontend/src/metabase/lib/icon.unit.spec.ts
  frontend/src/metabase/query_builder/components/view/sidebars/ChartTypeSidebar.tsx
  frontend/src/metabase/visualizations/components/skeletons/ChartSkeleton/ChartSkeleton.unit.spec.tsx
  frontend/src/metabase/visualizations/index.ts
  frontend/src/metabase/visualizations/shared/utils/sizes.ts
  frontend/src/metabase/visualizations/types/visualization.ts
Labels: no-backport, .Team/Embedding

#47708 clojure 1.12.0
  deps.edn
Labels: no-backport, .Team/BackendComponents

#47663 Always allow localhost:* on CORS
  src/metabase/server/middleware/security.clj
  test/metabase/server/middleware/security_test.clj
Labels: backport, .Team/Embedding

#47709 Fix missed spots still using dynamic user vars for search
  src/metabase/models/collection.clj
  src/metabase/search/impl.clj
Labels: no-backport, .Team/BackendComponents

#47666 🤖 backported "Revert "Hide upload config when data warehouse is attached""
  e2e/test/scenarios/admin-2/settings.cy.spec.js
  frontend/src/metabase/admin/settings/selectors.js
  src/metabase/public_settings.clj
  test/metabase/api/setting_test.clj
Labels: was-backported

#47658 perf: Optimize some query processor functions
  src/metabase/query_processor/middleware/large_int_id.clj
  src/metabase/query_processor/reducible.clj
  src/metabase/util/performance.clj
Labels: backport

#47677 Fix Transparent disabled state on mantine switch label
  frontend/src/metabase/ui/components/inputs/Switch/Switch.styled.tsx
Labels: backport, .Team/AdminWebapp

#47419 🤖 backported "Hide attached DWH database details"
  e2e/test/scenarios/admin/databases.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/advanced_permissions/components/ImpersonationModal/ImpersonationModalView.tsx
  enterprise/frontend/src/metabase-enterprise/advanced_permissions/components/ImpersonationWarning/ImpersonationWarning.tsx
  frontend/src/metabase-lib/v1/metadata/Field.ts
  frontend/src/metabase-types/api/database.ts
  frontend/src/metabase/admin/databases/containers/DatabaseEditApp.tsx
  frontend/src/metabase/admin/databases/database.js
  frontend/src/metabase/admin/databases/editParamsForUserControlledScheduling.js
  frontend/src/metabase/databases/components/DatabaseAuthCodeDescription/DatabaseAuthCodeDescription.tsx
  frontend/src/metabase/databases/components/DatabaseClientIdDescription/DatabaseClientIdDescription.tsx
  frontend/src/metabase/databases/utils/schema.ts
  resources/migrations/001_update_migrations.yaml
  resources/serialization-order.edn
  src/metabase/api/database.clj
  src/metabase/lib/schema/metadata.cljc
  src/metabase/models/database.clj
  test/metabase/api/table_test.clj
  test_resources/serialization_baseline/databases/My Database/My Database.yaml
  test_resources/serialization_baseline/databases/test-data (h2)/test-data (h2).yaml
  test_resources/serialization_baseline/databases/test-data/test-data.yaml
Labels: was-backported

#47676 [serdes] option to dump full stacktraces on errors
  enterprise/backend/src/metabase_enterprise/serialization/api.clj
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/ingest.clj
  enterprise/backend/test/metabase_enterprise/serialization/api_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj
  src/metabase/cmd.clj
  src/metabase/models/serialization.clj
  test/metabase/cmd_test.clj
Labels: backport, .Team/BackendComponents

#47718 🤖 backported "Fix Transparent disabled state on mantine switch label"
  frontend/src/metabase/ui/components/inputs/Switch/Switch.styled.tsx
Labels: was-backported

#47722 Reduce frequency of release status messages
  release/src/release-status.ts
Labels: .Building & Releasing, no-backport, .Team/AdminWebapp

#47716 🤖 backported "perf: Optimize some query processor functions"
  src/metabase/query_processor/middleware/large_int_id.clj
  src/metabase/query_processor/reducible.clj
  src/metabase/util/performance.clj
Labels: was-backported

#47712 fix(sdk): default font not working
  enterprise/frontend/src/embedding-sdk/components/private/SdkThemeProvider.tsx
  enterprise/frontend/src/embedding-sdk/store/index.ts
  frontend/src/metabase/styled-components/theme/css-variables.ts
Labels: no-backport, .Team/Embedding

#47141 🤖 backported "recents updates to better support metrics"
  src/metabase/models/recent_views.clj
  test/metabase/models/recent_views_test.clj
Labels: was-backported

#47638 🤖 backported "fix: sqlserver handle uniqueidentifier uuids"
  modules/drivers/athena/test/metabase/test/data/athena.clj
  modules/drivers/oracle/src/metabase/driver/oracle.clj
  modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj
  modules/drivers/sqlserver/test/metabase/test/data/sqlserver.clj
  src/metabase/driver/sql/query_processor.clj
  test/metabase/driver/sql_jdbc_test.clj
  test/metabase/test/data/h2.clj
Labels: was-backported

#47710 🤖 backported "Always allow localhost:* on CORS"
  src/metabase/server/middleware/security.clj
  test/metabase/server/middleware/security_test.clj
Labels: was-backported

#47695 🤖 backported "Revert multiple inheritance with SnowflakeVariant"
  src/metabase/types.cljc
Labels: was-backported

#47728 fix test: make sure there is a db and perm group
  src/metabase/models/data_permissions/graph.clj
  test/metabase/api/permissions_test_util.clj
  test/metabase/models/permissions_group_test.clj
Labels: no-backport, .Team/AdminWebapp

#47604 🤖 backported "upgrade webpack to address security issue"
  package.json
  yarn.lock
Labels: was-backported

#47702 Add docs url to the metric editor
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetNotebook/DatasetNotebook.jsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetNotebook/DatasetNotebook.unit.spec.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetNotebook/MetricSidebar/MetricSidebar.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetNotebook/MetricSidebar/index.ts
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetNotebook/MetricSidebar/tests/common.unit.spec.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetNotebook/MetricSidebar/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetNotebook/MetricSidebar/tests/setup.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetNotebook/MetricSidebar/tests/whitelabel.unit.spec.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetNotebook/index.ts
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetQueryEditor.jsx
  frontend/src/metabase/query_builder/components/DatasetEditor/ResizableNotebook/index.js
Labels: no-backport, .Team/Querying

#47430 🤖 backported "Static embed dashboard and question endpoints"
  src/metabase/api/embed.clj
  src/metabase/api/embed/common.clj
  src/metabase/models/setting.clj
  test/metabase/api/embed_test.clj
  test/metabase/api/util_test.clj
Labels: was-backported

#47448 fix(sdk): Use modal instead of hacky form for saving questions
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/SaveButton.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/InteractiveQuestionProvider.tsx
  enterprise/frontend/src/embedding-sdk/components/private/QuestionEditor/QuestionEditor.tsx
  frontend/src/metabase/components/SaveQuestionForm/SaveQuestionForm.tsx
  frontend/src/metabase/components/SaveQuestionForm/context.tsx
  frontend/src/metabase/components/SaveQuestionForm/types.ts
  frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.tsx
  frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.unit.spec.tsx
  frontend/src/metabase/forms/components/FormSubmitButton/FormSubmitButton.tsx
  frontend/src/metabase/query_builder/components/QueryModals/QueryModals.tsx
  frontend/src/metabase/ui/utils/colors.ts
Labels: no-backport, .Team/Embedding, Embedding/SDK

#47732 Hide temporal comparisons in the notebook editor for metrics
  e2e/test/scenarios/metrics/metrics-editing.cy.spec.js
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.tsx
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/View/NotebookContainer/NotebookContainer.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/AddAggregationButton/AddAggregationButton.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/AggregationItem/AggregationItem.tsx
  frontend/src/metabase/querying/notebook/components/AggregateStep/AggregateStep.tsx
  frontend/src/metabase/querying/notebook/components/AggregateStep/AggregateStep.unit.spec.tsx
Labels: no-backport, .Team/Querying

#47687 Simplify backend Snowplow API in preparation for migrating stats ping to Snowplow
  enterprise/backend/src/metabase_enterprise/llm/client.clj
  enterprise/backend/src/metabase_enterprise/serialization/api.clj
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/test/metabase_enterprise/serialization/test_util.clj
  src/metabase/actions/execution.clj
  src/metabase/analytics/snowplow.clj
  src/metabase/api/action.clj
  src/metabase/api/collection.clj
  src/metabase/api/dashboard.clj
  src/metabase/api/database.clj
  src/metabase/api/model_index.clj
  src/metabase/api/public.clj
  src/metabase/api/session.clj
  src/metabase/api/setup.clj
  src/metabase/api/timeline_event.clj
  src/metabase/api/user.clj
  src/metabase/embed/settings.clj
  src/metabase/metabot/feedback.clj
  src/metabase/upload.clj
  test/metabase/analytics/snowplow_test.clj
Labels: backport, .Team/AdminWebapp

#47100 Basic Sidesheet Components
  frontend/src/metabase/common/components/Sidesheet/Sidesheet.samples.tsx
  frontend/src/metabase/common/components/Sidesheet/Sidesheet.stories.mdx
  frontend/src/metabase/common/components/Sidesheet/Sidesheet.tsx
  frontend/src/metabase/common/components/Sidesheet/Sidesheet.unit.spec.tsx
  frontend/src/metabase/common/components/Sidesheet/SidesheetButton.tsx
  frontend/src/metabase/common/components/Sidesheet/SidesheetCard.tsx
  frontend/src/metabase/common/components/Sidesheet/SidesheetCardSection.tsx
  frontend/src/metabase/common/components/Sidesheet/SidesheetSubPage.tsx
  frontend/src/metabase/common/components/Sidesheet/SidesheetSubPage.unit.spec.tsx
  frontend/src/metabase/common/components/Sidesheet/SidesheetTabPanelContainer.tsx
  frontend/src/metabase/common/components/Sidesheet/index.ts
  frontend/src/metabase/common/components/Sidesheet/sidesheet.module.css
  frontend/src/metabase/ui/index.ts
Labels: no-backport, .Team/AdminWebapp

#47717 Fix admin override for public actions
  src/metabase/api/public.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/public_test.clj
  test/metabase/driver/sql_jdbc/actions_test.clj
  test/metabase/query_processor/card_test.clj
  test/metabase/query_processor/dashboard_test.clj
Labels: backport, .Team/AdminWebapp

#47699 Question Settings Sidesheet
  e2e/test/scenarios/admin/performance/helpers/e2e-strategy-form-helpers.ts
  e2e/test/scenarios/admin/performance/performance.cy.spec.ts
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/caching/utils.js
  enterprise/frontend/src/metabase-enterprise/caching/utils.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/model_persistence/components/ModelCacheControl/ModelCacheControl.tsx
  enterprise/frontend/src/metabase-enterprise/model_persistence/components/ModelCacheControl/index.ts
  enterprise/frontend/src/metabase-enterprise/model_persistence/index.ts
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase/api/card.ts
  frontend/src/metabase/home/components/HomePage/HomePage.tsx
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/query_builder/actions/ui.ts
  frontend/src/metabase/query_builder/components/view/View.jsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionActions/QuestionActions.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/ModelCacheManagementSection/ModelCacheManagementSection.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/ModelCacheManagementSection/ModelCacheManagementSection.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/ModelCacheManagementSection/index.ts
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/QuestionInfoSidebar.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/tests/cache-granular-controls.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionSettingsSidebar/QuestionSettingsSidebar.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionSettingsSidebar/index.ts
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionSettingsSidebar/tests/common.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionSettingsSidebar/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionSettingsSidebar/tests/setup.tsx
  frontend/src/metabase/query_builder/reducers.js
  frontend/test/__support__/server-mocks/persist.ts
Labels: no-backport, .Team/AdminWebapp

#47739 🤖 backported "Simplify backend Snowplow API in preparation for migrating stats ping to Snowplow"
  enterprise/backend/src/metabase_enterprise/llm/client.clj
  enterprise/backend/src/metabase_enterprise/serialization/api.clj
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/test/metabase_enterprise/serialization/test_util.clj
  src/metabase/actions/execution.clj
  src/metabase/analytics/snowplow.clj
  src/metabase/api/action.clj
  src/metabase/api/dashboard.clj
  src/metabase/api/database.clj
  src/metabase/api/model_index.clj
  src/metabase/api/public.clj
  src/metabase/api/session.clj
  src/metabase/api/setup.clj
  src/metabase/api/timeline_event.clj
  src/metabase/api/user.clj
  src/metabase/embed/settings.clj
  src/metabase/metabot/feedback.clj
  src/metabase/upload.clj
  test/metabase/analytics/snowplow_test.clj
Labels: was-backported

#47742 🤖 backported "Fix admin override for public actions"
  src/metabase/api/public.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/public_test.clj
  test/metabase/driver/sql_jdbc/actions_test.clj
  test/metabase/query_processor/card_test.clj
  test/metabase/query_processor/dashboard_test.clj
Labels: was-backported

#47737 Split ChartType components into files
  e2e/test/scenarios/visualizations-charts/maps.cy.spec.js
  enterprise/frontend/src/embedding-sdk/components/public/StaticQuestion/StaticQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/public/StaticQuestion/StaticQuestion.unit.spec.tsx
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeList/ChartTypeList.styled.tsx
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeList/ChartTypeList.tsx
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeList/ChartTypeList.unit.spec.tsx
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeList/index.ts
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeOption/ChartTypeOption.styled.tsx
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeOption/ChartTypeOption.tsx
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeOption/ChartTypeOption.unit.spec.tsx
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeOption/index.ts
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeSettings/ChartTypeSettings.styled.tsx
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeSettings/ChartTypeSettings.tsx
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeSettings/ChartTypeSettings.unit.spec.tsx
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeSettings/index.ts
  frontend/src/metabase/query_builder/components/chart-type-selector/index.ts
  frontend/src/metabase/query_builder/components/chart-type-selector/use-chart-type-visualizations.ts
  frontend/src/metabase/query_builder/components/chart-type-selector/viz-order.ts
  frontend/src/metabase/query_builder/components/view/View.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/ChartTypeSidebar.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/ChartTypeSidebar.unit.spec.js
  frontend/src/metabase/query_builder/components/view/sidebars/ChartTypeSidebar/ChartTypeSidebar.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/ChartTypeSidebar/index.ts
Labels: no-backport, .Team/Embedding

#47748 fix(sdk): Fix entity ID logic to use the correct status
  frontend/src/metabase/api/entity-id.ts
  frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts
Labels: backport, .Team/Embedding

#47505 Remove useMemo from tabs computation
  frontend/src/metabase/common/components/DataPicker/components/DataPickerModal.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/EntityPickerModal.tsx
Labels: no-backport, .Team/Querying

#47721 [serdes] api: better error when archive looks weird
  enterprise/backend/src/metabase_enterprise/serialization/api.clj
Labels: backport, .Team/BackendComponents

#47756 🤖 backported "[serdes] api: better error when archive looks weird"
  enterprise/backend/src/metabase_enterprise/serialization/api.clj
Labels: was-backported

#47348 feat(sdk): add the create question component demo to the cli
  enterprise/frontend/src/embedding-sdk/cli/snippets/analytics-dashboard-snippet.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/create-models-and-xrays.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/setup-permission.ts
  enterprise/frontend/src/embedding-sdk/cli/types/cli.ts
  enterprise/frontend/src/embedding-sdk/cli/utils/create-collection.ts
  enterprise/frontend/src/embedding-sdk/cli/utils/create-model-from-table.ts
  enterprise/frontend/src/embedding-sdk/cli/utils/get-sandboxed-collection-permissions.ts
  enterprise/frontend/src/embedding-sdk/cli/utils/permissions-graph.unit.spec.ts
Labels: no-backport, .Team/Embedding, Embedding/SDK

#47720 🤖 backported "[serdes] option to dump full stacktraces on errors"
  enterprise/backend/src/metabase_enterprise/serialization/api.clj
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/ingest.clj
  enterprise/backend/test/metabase_enterprise/serialization/api_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/extract_test.clj
  src/metabase/cmd.clj
  src/metabase/models/serialization.clj
  test/metabase/cmd_test.clj
Labels: was-backported

#47692 Recalculate "graph.metrics" and "graph.dimensions" if empty
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
  frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.unit.spec.tsx
  frontend/src/metabase/visualizations/lib/settings/graph.js
Labels: no-backport, .Team/DashViz

#47727 fix(sdk): remove usage of legacy query in static question
  frontend/src/metabase/visualizations/types/visualization.ts
  frontend/src/metabase/visualizations/visualizations/PivotTable/utils.ts
Labels: no-backport, .Team/Embedding

#47762 Update SDK version to 0.1.36
  enterprise/frontend/src/embedding-sdk/CHANGELOG.md
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: no-backport

#47686 Introduce `enable-embedding-sdk` toggle
  enterprise/backend/test/metabase_enterprise/api/session_test.clj
  enterprise/frontend/src/metabase-enterprise/embedding-sdk/index.js
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/common.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/enterprise.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/premium.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/setup.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSettings.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingOption.tsx
  src/metabase/embed/settings.clj
  src/metabase/public_settings.clj
  src/metabase/public_settings/premium_features.clj
  src/metabase/server/middleware/security.clj
  test/metabase/server/middleware/security_test.clj
Labels: no-backport, .Team/Embedding

#47640 🤖 backported "Entity id translation analytics"
  src/metabase/api/embed/common.clj
  test/metabase/api/embed/common_test.clj
  test/metabase/api/embed_test.clj
Labels: was-backported

#47590 fix: bigquery add null checks to result processing
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj
Labels: backport, .Team/Drivers

#47729 handle errors without crashing in SliceNameWidget
  frontend/src/metabase/visualizations/visualizations/PieChart/SliceNameWidget.tsx
  frontend/src/metabase/visualizations/visualizations/PieChart/SliceNameWidget.unit.spec.tsx
Labels: no-backport, .Team/DashViz

#47581 Toggle series visibility from chart legend (pie charts)
  e2e/test/scenarios/visualizations-charts/legend.cy.spec.js
  frontend/src/metabase/static-viz/components/PieChart/PieChart.tsx
  frontend/src/metabase/static-viz/components/PieChart/legend.tsx
  frontend/src/metabase/visualizations/components/ChartWithLegend.jsx
  frontend/src/metabase/visualizations/components/LegendHorizontal.jsx
  frontend/src/metabase/visualizations/components/LegendItem.jsx
  frontend/src/metabase/visualizations/components/LegendVertical.jsx
  frontend/src/metabase/visualizations/components/legend/LegendItemDot.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingSeriesOrder.tsx
  frontend/src/metabase/visualizations/echarts/pie/constants.ts
  frontend/src/metabase/visualizations/echarts/pie/model/index.ts
  frontend/src/metabase/visualizations/echarts/pie/model/types.ts
  frontend/src/metabase/visualizations/echarts/pie/option.ts
  frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.tsx
  frontend/src/metabase/visualizations/visualizations/PieChart/chart-definition.ts
  frontend/src/metabase/visualizations/visualizations/PieChart/use-chart-events.ts
Labels: no-backport, .Team/DashViz

#47740 Convey cancelation info when the client closes the connection
  src/metabase/query_processor/streaming.clj
  test/metabase/async/streaming_response_test.clj
Labels: backport, .Team/Querying

#47781 🤖 backported "Convey cancelation info when the client closes the connection"
  src/metabase/query_processor/streaming.clj
  test/metabase/async/streaming_response_test.clj
Labels: was-backported

#47157 Question Info + Settings Sidesheets
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/admin-2/api-keys.cy.spec.ts
  e2e/test/scenarios/admin/performance/helpers/e2e-strategy-form-helpers.ts
  e2e/test/scenarios/admin/performance/performance.cy.spec.ts
  e2e/test/scenarios/collections/revision-history.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/filters-reproductions/dashboard-filters-with-question-revert.cy.spec.js
  e2e/test/scenarios/models/models-metadata.cy.spec.js
  e2e/test/scenarios/models/models-revision-history.cy.spec.js
  e2e/test/scenarios/models/reproductions.cy.spec.ts
  e2e/test/scenarios/native-filters/native-filters-reproductions.cy.spec.js
  e2e/test/scenarios/organization/content-verification.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions-1.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
  e2e/test/scenarios/question/caching.cy.spec.js
  e2e/test/scenarios/question/saved.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/caching/components/SidebarCacheForm.styled.tsx
  enterprise/frontend/src/metabase-enterprise/caching/components/SidebarCacheForm.tsx
  enterprise/frontend/src/metabase-enterprise/caching/utils.js
  enterprise/frontend/src/metabase-enterprise/caching/utils.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/model_persistence/components/ModelCacheControl/ModelCacheControl.tsx
  enterprise/frontend/src/metabase-enterprise/model_persistence/components/ModelCacheControl/index.ts
  enterprise/frontend/src/metabase-enterprise/model_persistence/index.ts
  enterprise/frontend/src/metabase-enterprise/moderation/components/ModerationReviewBanner/ModerationReviewBanner.styled.tsx
  enterprise/frontend/src/metabase-enterprise/moderation/components/ModerationReviewBanner/ModerationReviewBanner.tsx
  enterprise/frontend/src/metabase-enterprise/moderation/components/ModerationReviewBanner/ModerationReviewBanner.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/moderation/components/ModerationReviewBanner/index.ts
  enterprise/frontend/src/metabase-enterprise/moderation/components/QuestionModerationSection/QuestionModerationSection.jsx
  enterprise/frontend/src/metabase-enterprise/moderation/index.js
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase/admin/performance/components/StrategyForm.styled.tsx
  frontend/src/metabase/admin/performance/components/StrategyForm.tsx
  frontend/src/metabase/api/card.ts
  frontend/src/metabase/common/components/Timeline/Timeline.styled.tsx
  frontend/src/metabase/hooks/use-confirmation.tsx
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/query_builder/actions/ui.ts
  frontend/src/metabase/query_builder/components/QuestionActivityTimeline.styled.tsx
  frontend/src/metabase/query_builder/components/QuestionActivityTimeline.tsx
  frontend/src/metabase/query_builder/components/view/View.jsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionActions/QuestionActions.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/ModelCacheManagementSection/ModelCacheManagementSection.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/ModelCacheManagementSection/ModelCacheManagementSection.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/ModelCacheManagementSection/index.ts
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/QuestionInfoSidebar.module.css
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/QuestionInfoSidebar.styled.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/QuestionInfoSidebar.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/tests/cache-granular-controls.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/tests/common.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/tests/content-verification.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionSettingsSidebar/QuestionSettingsSidebar.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionSettingsSidebar/index.ts
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionSettingsSidebar/tests/common.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionSettingsSidebar/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionSettingsSidebar/tests/setup.tsx
  frontend/src/metabase/query_builder/reducers.js
  frontend/test/__support__/server-mocks/persist.ts
Labels: no-backport, .Team/AdminWebapp

#47724 perf: Use more efficient query validation when the argument is valid
  src/metabase/legacy_mbql/util.cljc
  src/metabase/lib/schema.cljc
Labels: backport

#47587 [QP] Correctly handle `:lib/internal-remap` columns in `:result_metadata`
  src/metabase/lib/schema/metadata.cljc
  src/metabase/query_processor/middleware/add_dimension_projections.clj
  src/metabase/query_processor/middleware/add_source_metadata.clj
  src/metabase/query_processor/middleware/fetch_source_query.clj
  src/metabase/query_processor/middleware/fetch_source_query_legacy.clj
  src/metabase/query_processor/middleware/large_int_id.clj
  src/metabase/query_processor/middleware/results_metadata.clj
  test/metabase/query_processor/middleware/add_dimension_projections_test.clj
Labels: backport, .Team/Querying
