Repository metabase/metabase, pull requests merged in 2024-11, with the labels that each got.

#49418 🤖 backported "Fix dirty yarn.lock by resolving elliptic"
  package.json
Labels: was-backported

#49417 Revert "Avoid native editor autocomplete suggestions flicker"
  e2e/test/scenarios/native/native-reproductions.cy.spec.js
  e2e/test/scenarios/native/native_subquery.cy.spec.js
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx
Labels: backport, .Team/Querying

#49424 Follow up on dirty yarn.lock by resolving elliptic
  yarn.lock
Labels: backport, .Team/Querying

#49420 🤖 backported "Revert "Avoid native editor autocomplete suggestions flicker""
  e2e/test/scenarios/native/native-reproductions.cy.spec.js
  e2e/test/scenarios/native/native_subquery.cy.spec.js
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx
Labels: was-backported

#49411 🤖 backported "[QP] Update breakouts in `:order-by` when setting time granularity"
  src/metabase/query_processor/middleware/parameters/mbql.clj
  test/metabase/query_processor/middleware/parameters/mbql_test.clj
Labels: was-backported

#49361 fix: add UserAgentEntry to databricks connection
  modules/drivers/databricks/src/metabase/driver/databricks.clj
  modules/drivers/databricks/test/metabase/driver/databricks_test.clj
Labels: backport, .Team/Drivers

#47997 bump snowflake driver version
  modules/drivers/snowflake/deps.edn
Labels: backport

#49429 Address some review comments
  resources/migrations/001_update_migrations.yaml
  test/metabase/db/custom_migrations_test.clj
Labels: .Team/Querying

#49387 Give the command palette a higher z-index
  frontend/src/metabase/palette/components/Palette.tsx
Labels: backport, .Team/AdminWebapp

#49184 Remove dead code: FullPageModal
  frontend/src/metabase/components/Modal/FullPageModal.tsx
  frontend/src/metabase/components/Modal/Modal.tsx
  frontend/src/metabase/components/Modal/RoutelessFullPageModal.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailWrapper.tsx
Labels: no-backport, .Team/AdminWebapp

#48998 Simplify the "Edit segment"/"Retire segment" actions and modal
  frontend/src/metabase/admin/datamodel/components/SegmentActionSelect.jsx
  frontend/src/metabase/admin/datamodel/components/SegmentActionSelect.styled.tsx
  frontend/src/metabase/admin/datamodel/components/SegmentItem.jsx
  frontend/src/metabase/admin/datamodel/components/SegmentRetireModal.jsx
Labels: backport, .Team/AdminWebapp

#49436 🤖 backported "Simplify the "Edit segment"/"Retire segment" actions and modal"
  frontend/src/metabase/admin/datamodel/components/SegmentActionSelect.jsx
  frontend/src/metabase/admin/datamodel/components/SegmentActionSelect.styled.tsx
  frontend/src/metabase/admin/datamodel/components/SegmentItem.jsx
  frontend/src/metabase/admin/datamodel/components/SegmentRetireModal.jsx
Labels: was-backported

#49190 [MBQL lib] Relax schema to avoid spammy normalization warnings
  src/metabase/legacy_mbql/schema.cljc
  src/metabase/lib/convert.cljc
  src/metabase/lib/query.cljc
  src/metabase/lib/schema.cljc
  test/metabase/actions_test.clj
  test/metabase/lib/convert_test.cljc
  test/metabase/lib/schema/join_test.cljc
  test/metabase/lib/schema_test.cljc
Labels: no-backport, .Team/Querying

#49447 Docs: update custom expressions limitations
  docs/questions/query-builder/expressions-list.md
  docs/questions/query-builder/expressions/converttimezone.md
  docs/questions/query-builder/expressions/offset.md
Labels: Type:Documentation, backport

#49450 🤖 backported "Docs: update custom expressions limitations"
  docs/questions/query-builder/expressions-list.md
  docs/questions/query-builder/expressions/converttimezone.md
  docs/questions/query-builder/expressions/offset.md
Labels: was-backported

#49443 Make sure metrics migration populates all permissions fields
  src/metabase/db/custom_migrations/metrics_v2.clj
  test/metabase/db/custom_migrations/metrics_v2_test.clj
Labels: backport, .Team/AdminWebapp

#49323 Use list picker when searching a single value
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Number.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_Search.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_Search_With_Value.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Text.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Text_With_Value.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Month_Year.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Number.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_List_Single_With_Value.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_List_With_Value.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_Search.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_Search_With_Value.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Text.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Text_With_Value.png
  e2e/test/scenarios/dashboard-filters/dashboard-chained-filters.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-text-category.cy.spec.js
  e2e/test/scenarios/dashboard-filters/parameters.cy.spec.js
  e2e/test/scenarios/filters-reproductions/dashboard-filters-reproductions.cy.spec.js
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.tsx
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.unit.spec.tsx
Labels: backport, .Team/Querying, loki-update

#49453 🤖 backported "Make sure metrics migration populates all permissions fields"
  src/metabase/db/custom_migrations/metrics_v2.clj
  test/metabase/db/custom_migrations/metrics_v2_test.clj
Labels: was-backported

#48956 Dashboard verifications
  e2e/test/scenarios/models/models-revision-history.cy.spec.js
  e2e/test/scenarios/organization/content-verification.cy.spec.js
  enterprise/backend/src/metabase_enterprise/stale.clj
  enterprise/backend/test/metabase_enterprise/stale/api_test.clj
  enterprise/frontend/src/metabase-enterprise/moderation/components/EntityModerationIcon/EntityModerationIcon.tsx
  enterprise/frontend/src/metabase-enterprise/moderation/components/EntityModerationIcon/EntityModerationIcon.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/moderation/components/EntityModerationIcon/index.ts
  enterprise/frontend/src/metabase-enterprise/moderation/components/ModerationReviewBanner/ModerationReviewBanner.tsx
  enterprise/frontend/src/metabase-enterprise/moderation/components/ModerationReviewBanner/ModerationReviewBanner.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/moderation/components/ModerationReviewIcon/ModerationReviewIcon.tsx
  enterprise/frontend/src/metabase-enterprise/moderation/components/ModerationReviewIcon/ModerationReviewIcon.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/moderation/components/QuestionModerationButton/QuestionModerationButton.tsx
  enterprise/frontend/src/metabase-enterprise/moderation/components/QuestionModerationButton/QuestionModerationButton.unit.spec.js
  enterprise/frontend/src/metabase-enterprise/moderation/components/QuestionModerationButton/index.ts
  enterprise/frontend/src/metabase-enterprise/moderation/components/QuestionModerationIcon/QuestionModerationIcon.tsx
  enterprise/frontend/src/metabase-enterprise/moderation/components/QuestionModerationIcon/index.ts
  enterprise/frontend/src/metabase-enterprise/moderation/containers/ModerationReviewIcon/ModerationReviewIcon.tsx
  enterprise/frontend/src/metabase-enterprise/moderation/hooks/useMenuItems.tsx
  enterprise/frontend/src/metabase-enterprise/moderation/index.js
  enterprise/frontend/src/metabase-enterprise/moderation/service.ts
  enterprise/frontend/src/metabase-enterprise/moderation/service.unit.spec.ts
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase-types/api/dashboard.ts
  frontend/src/metabase-types/api/mocks/card.ts
  frontend/src/metabase-types/api/mocks/dashboard.ts
  frontend/src/metabase-types/api/moderation.ts
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeaderButtonRow/action-buttons.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeaderView.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/buttons/DashboardActionMenu.tsx
  frontend/src/metabase/dashboard/components/DashboardInfoSidebar/DashboardInfoSidebar.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/test-utils.ts
  frontend/src/metabase/dashboard/hooks/use-refresh-dashboard.ts
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/query_builder/components/QuestionActivityTimeline.tsx
  frontend/src/metabase/query_builder/components/SavedQuestionHeaderButton/CollectionIcon.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionActions/QuestionActions.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/QuestionInfoSidebar.tsx
  src/metabase/api/collection.clj
  src/metabase/api/dashboard.clj
  src/metabase/models/recent_views.clj
  src/metabase/moderation.clj
  src/metabase/search/legacy.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/models/recent_views_test.clj
Labels: no-backport, .Team/AdminWebapp

#49404 Adding moderated status to entity picker
  e2e/test/scenarios/collections/collections.cy.spec.js
  e2e/test/scenarios/models/models.cy.spec.js
  e2e/test/scenarios/onboarding/reference/databases.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/collections/utils.ts
  enterprise/frontend/src/metabase-enterprise/collections/utils.unit.spec.tsx
  frontend/src/metabase/collections/components/PinnedItemCard/PinnedItemCard-ee.unit.spec.tsx
  frontend/src/metabase/collections/components/PinnedItemCard/PinnedItemCard.tsx
  frontend/src/metabase/common/components/EntityPicker/components/ItemList/ItemList.tsx
  frontend/src/metabase/common/components/EntityPicker/components/ResultItem/ResultItem.tsx
  frontend/src/metabase/common/components/EntityPicker/components/ResultItem/ResultItem.unit.spec.tsx
  frontend/src/metabase/common/components/EntityPicker/types.ts
  frontend/src/metabase/common/components/QuestionPicker/components/QuestionPicker.unit.spec.tsx
  frontend/src/metabase/ui/components/icons/Icon/icons/verified_filled.svg
  yarn.lock
Labels: no-backport, .Team/AdminWebapp

#49426 🤖 backported "Follow up on dirty yarn.lock by resolving elliptic"
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Single.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Number.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_List_With_Value.png
  yarn.lock
Labels: was-backported, loki-update

#49463 Fix dirty yarn.lock
  yarn.lock
Labels: backport, .Team/Querying

#49409 🤖 backported "Fix flaky public links tests"
  e2e/test/scenarios/sharing/public-dashboard.cy.spec.js
  e2e/test/scenarios/sharing/public-question.cy.spec.js
Labels: was-backported

#49455 🤖 backported "Use list picker when searching a single value"
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Number.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_Search.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_Search_With_Value.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Text.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Text_With_Value.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Number.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_Search.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_Search_With_Value.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Text.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Text_With_Value.png
  e2e/test/scenarios/dashboard-filters/dashboard-chained-filters.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-text-category.cy.spec.js
  e2e/test/scenarios/dashboard-filters/parameters.cy.spec.js
  e2e/test/scenarios/filters-reproductions/dashboard-filters-reproductions.cy.spec.js
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.tsx
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.unit.spec.tsx
Labels: was-backported, loki-update

#49334 Move section logic to hook
  frontend/src/metabase/visualizations/components/ChartSettings/BaseChartSettings/BaseChartSettings.styled.tsx
  frontend/src/metabase/visualizations/components/ChartSettings/BaseChartSettings/BaseChartSettings.tsx
  frontend/src/metabase/visualizations/components/ChartSettings/BaseChartSettings/hooks.ts
Labels: backport, .Team/Embedding

#48914 🤖 backported "fix react warnings"
  frontend/src/metabase/components/Badge/Badge.styled.tsx
  frontend/src/metabase/components/MetadataInfo/InfoIcon/InfoIcon.styled.tsx
  frontend/src/metabase/components/tree/TreeNode.styled.tsx
  frontend/src/metabase/nav/components/AppBar/AppBarToggle.styled.tsx
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/SidebarItems.styled.tsx
  frontend/src/metabase/query_builder/components/view/View/NotebookContainer/NotebookContainer.tsx
Labels: was-backported

#49428 Assume question is dirty when edited from notebook
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
  frontend/src/metabase/query_builder/actions/navigation.js
Labels: backport, .Team/Querying

#49251 feat(sdk): ability to enforce the destination collection to save to and hide the collection picker
  docs/embedding/sdk/questions.md
  e2e/test/scenarios/embedding-sdk/helpers/save-interactive-question-e2e-helpers.ts
  e2e/test/scenarios/embedding-sdk/interactive-question.cy.spec.ts
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/SdkSaveQuestionForm.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/InteractiveQuestionProvider.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/types.ts
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult/InteractiveQuestionResult.tsx
  enterprise/frontend/src/embedding-sdk/components/private/QuestionEditor/QuestionEditor.tsx
  enterprise/frontend/src/embedding-sdk/components/public/CreateQuestion/CreateQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.stories.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/public/ModifyQuestion/ModifyQuestion.tsx
  frontend/src/metabase/components/SaveQuestionForm/SaveQuestionForm.tsx
  frontend/src/metabase/components/SaveQuestionForm/context.tsx
  frontend/src/metabase/components/SaveQuestionForm/types.ts
  frontend/src/metabase/components/SaveQuestionForm/util.ts
  frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.tsx
Labels: backport, .Team/Embedding, Embedding/SDK

#49470 Memoize useChartSettingsSections variables
  frontend/src/metabase/visualizations/components/ChartSettings/BaseChartSettings/hooks.ts
Labels: backport, .Team/Embedding

#49476 Fix flaky custom column test
  e2e/test/scenarios/custom-column/cc-boolean-functions.cy.spec.ts
Labels: .CI & Tests, backport, flaky-test-fix, .Team/Querying

#49483 🤖 backported "Fix flaky custom column test"
  e2e/test/scenarios/custom-column/cc-boolean-functions.cy.spec.ts
Labels: was-backported

#49490 docs: remove case workaround
  docs/questions/query-builder/expressions-list.md
Labels: Type:Documentation, backport

#49491 🤖 backported "docs: remove case workaround"
  docs/questions/query-builder/expressions-list.md
Labels: was-backported

#49413 [MBQL lib] Add breakouts to random query generators
  src/metabase/lib/breakout.cljc
  test/metabase/lib/breakout_test.cljc
  test/metabase/lib/test_util/generators.cljc
Labels: no-backport, .Team/Querying

#48633 Add release channel option to publish job
  .github/workflows/release-tag.yml
  .github/workflows/release.yml
Labels: .Building & Releasing, no-backport, .Team/AdminWebapp

#49367 Pivot Measures Order Used in Pivot Exports
  src/metabase/query_processor/pivot.clj
  src/metabase/query_processor/pivot/postprocess.clj
  src/metabase/query_processor/streaming/csv.clj
  src/metabase/query_processor/streaming/json.clj
  test/metabase/api/downloads_exports_test.clj
  test/metabase/query_processor/pivot_test.clj
Labels: backport, .Team/DashViz

#49505 add llm-payloads to gitignore
  .gitignore
Labels: .Team/DashViz

#49503 🤖 backported "Pivot Measures Order Used in Pivot Exports"
  src/metabase/query_processor/pivot.clj
  src/metabase/query_processor/pivot/postprocess.clj
  src/metabase/query_processor/streaming/csv.clj
  src/metabase/query_processor/streaming/json.clj
  test/metabase/api/downloads_exports_test.clj
  test/metabase/query_processor/pivot_test.clj
Labels: was-backported

#49093 Remove daisy-chaining from pre-release tests
  .github/workflows/build-for-release.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  .github/workflows/tag-for-release.yml
Labels: .Building & Releasing, no-backport, .Team/AdminWebapp

#49513 🤖 backported "Add v0.51.2 to the list of releases"
  docs/releases.md
Labels: was-backported

#49347 fix: tests for clickhouse development
  .clj-kondo/test/hooks/clojure/test_test.clj
  test/metabase/api/pivots.clj
  test/metabase/events/view_log_test.clj
Labels: backport, .Team/Drivers

#49432 🤖 backported "fix: add UserAgentEntry to databricks connection"
  modules/drivers/databricks/src/metabase/driver/databricks.clj
  modules/drivers/databricks/test/metabase/driver/databricks_test.clj
Labels: was-backported

#49406 🤖 backported "Adjust dependent dashboard cards"
  src/metabase/models/card.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/models/card_test.clj
Labels: was-backported

#49514 🤖 backported "fix: tests for clickhouse development"
  .clj-kondo/test/hooks/clojure/test_test.clj
  test/metabase/api/pivots.clj
  test/metabase/events/view_log_test.clj
Labels: was-backported

#49474 🤖 backported "In question sidesheet, improve the 'Based on' section"
  frontend/src/metabase/lib/icon.ts
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/utils.js
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/utils.unit.spec.ts
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/QuestionDetails.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/components/QuestionSources.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/components/QuestionSources.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/components/types.ts
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/components/utils.tsx
Labels: was-backported

#49472 Fix flaky #16559 repro
  e2e/support/helpers/e2e-dashboard-helpers.ts
  e2e/test/scenarios/dashboard/dashboard-reproductions.cy.spec.js
Labels: .CI & Tests, backport, flaky-test-fix, .Team/Querying

#49517 🤖 backported "Fix flaky #16559 repro"
  e2e/support/helpers/e2e-dashboard-helpers.ts
  e2e/test/scenarios/dashboard/dashboard-reproductions.cy.spec.js
Labels: was-backported

#49511 Flake fix: native editor selection range
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx
Labels: backport, .Team/Querying

#49489 Fix missing question type for metrics
  e2e/test/scenarios/native/native-reproductions.cy.spec.ts
  frontend/src/metabase/query_builder/components/NativeQueryEditor/utils.ts
Labels: no-backport, .Team/Querying

#49475 🤖 backported "Assume question is dirty when edited from notebook"
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
  frontend/src/metabase/query_builder/actions/navigation.js
Labels: was-backported

#49518 🤖 backported "Flake fix: native editor selection range"
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx
Labels: was-backported

#49479 🤖 backported "feat(sdk): ability to enforce the destination collection to save to and hide the collection picker"
  docs/embedding/sdk/questions.md
  e2e/test/scenarios/embedding-sdk/helpers/save-interactive-question-e2e-helpers.ts
  e2e/test/scenarios/embedding-sdk/interactive-question.cy.spec.ts
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/SdkSaveQuestionForm.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/InteractiveQuestionProvider.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/types.ts
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult/InteractiveQuestionResult.tsx
  enterprise/frontend/src/embedding-sdk/components/private/QuestionEditor/QuestionEditor.tsx
  enterprise/frontend/src/embedding-sdk/components/public/CreateQuestion/CreateQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.stories.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/public/ModifyQuestion/ModifyQuestion.tsx
  frontend/src/metabase/components/SaveQuestionForm/SaveQuestionForm.tsx
  frontend/src/metabase/components/SaveQuestionForm/context.tsx
  frontend/src/metabase/components/SaveQuestionForm/types.ts
  frontend/src/metabase/components/SaveQuestionForm/util.ts
  frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.tsx
Labels: was-backported

#49460 [streaming-response] Use HttpEndpoint.isOpen() instead of reading a byte from TCP socket
  src/metabase/async/streaming_response.clj
  test/metabase/async/streaming_response_test.clj
Labels: backport

#49524 🤖 backported "[streaming-response] Use HttpEndpoint.isOpen() instead of reading a byte from TCP socket"
  src/metabase/async/streaming_response.clj
  test/metabase/async/streaming_response_test.clj
Labels: was-backported

#49464 Fixed width filters
  e2e/test/scenarios/filters-reproductions/filters-reproductions.cy.spec.js
  frontend/src/metabase/querying/filters/components/FilterPicker/CoordinateFilterPicker/CoordinateFilterPicker.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/FilterColumnPicker/FilterColumnPicker.styled.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/NumberFilterPicker/NumberFilterPicker.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/StringFilterPicker/StringFilterPicker.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/TimeFilterPicker/TimeFilterPicker.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/constants.ts
Labels: backport, .Team/Querying

#49522 Update `saveDashboard` helper to wait for the GET `/api/dashboard/:id`
  e2e/support/helpers/e2e-dashboard-helpers.ts
  e2e/test/scenarios/custom-column/cc-boolean-functions.cy.spec.ts
Labels: .CI & Tests, backport, .Team/Querying

#49337 Update Macaw to 0.2.24 and set its run mode
  deps.edn
  src/metabase/query_analysis/native_query_analyzer/impl.cljc
Labels: no-backport, .Team/BackendComponents

#49527 🤖 backported "Fixed width filters"
  e2e/test/scenarios/filters-reproductions/filters-reproductions.cy.spec.js
  frontend/src/metabase/querying/filters/components/FilterPicker/CoordinateFilterPicker/CoordinateFilterPicker.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/FilterColumnPicker/FilterColumnPicker.styled.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/NumberFilterPicker/NumberFilterPicker.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/StringFilterPicker/StringFilterPicker.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/TimeFilterPicker/TimeFilterPicker.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/constants.ts
Labels: was-backported

#49481 🤖 backported "Memoize useChartSettingsSections variables"
  frontend/src/metabase/visualizations/components/ChartSettings/BaseChartSettings/hooks.ts
Labels: was-backported

#49521 Backport of "Flake fix: native editor selection range #49511"
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx
Labels: was-backported

#49528 🤖 backported "Update `saveDashboard` helper to wait for the GET `/api/dashboard/:id`"
  e2e/support/helpers/e2e-dashboard-helpers.ts
  e2e/test/scenarios/custom-column/cc-boolean-functions.cy.spec.ts
Labels: was-backported

#49495 Update api-changelog.md
  docs/developers-guide/api-changelog.md
Labels: Type:Documentation, no-backport

#49446 [MBQL lib] Match implicitly joined refs with multiple paths
  src/metabase/lib/equality.cljc
  test/metabase/lib/equality_test.cljc
Labels: no-backport, .Team/Querying

#49356 Add base color palette
  .eslintrc.js
  .stylelintrc.json
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/use-embedding-settings-icon-colors.tsx
  frontend/src/metabase/css/core/colors.module.css
  frontend/src/metabase/home/components/EmbedHomepage/Badge.ts
  frontend/src/metabase/ui/utils/colors.ts
Labels: backport, .Team/AdminWebapp

#49445 [util] Add `u.time/local-date`, `local-time` and `local-date-time`
  src/metabase/util/time.cljc
  src/metabase/util/time/impl.clj
  src/metabase/util/time/impl.cljs
  src/metabase/util/time/impl_common.cljc
  test/metabase/util/time_test.cljc
Labels: no-backport, .Team/Querying

#49535 🤖 backported "feat(sdk): Add `isOpen` prop to control CreateDashboardModal"
  enterprise/frontend/src/embedding-sdk/components/public/CreateDashboardModal/CreateDashboardModal.stories.tsx
  enterprise/frontend/src/embedding-sdk/components/public/CreateDashboardModal/CreateDashboardModal.tsx
  enterprise/frontend/src/embedding-sdk/components/public/CreateDashboardModal/CreateDashboardModal.unit.spec.tsx
Labels: was-backported

#49546 🤖 backported "Correct Azure SAML"
  docs/people-and-groups/saml-azure.md
Labels: was-backported

#49011 perf: Implement faster sync methods for mysql
  src/metabase/driver/mysql.clj
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
  test/metabase/driver/sql_jdbc/sync/describe_table_test.clj
  test/metabase/driver_test.clj
Labels: backport, .Team/Drivers

#49492 fix(49482): don't create a new store on each MetabaseProvider render
  enterprise/frontend/src/embedding-sdk/components/public/MetabaseProvider.tsx
  enterprise/frontend/src/embedding-sdk/test/auth-flow.unit.spec.tsx
Labels: .Team/Embedding

#49506 Check only :stages of the result of metric resolution in the QP
  src/metabase/query_processor/middleware/metrics.clj
  test/metabase/query_processor/middleware/metrics_test.clj
Labels: backport, .Team/Querying

#49561 🤖 backported "Check only :stages of the result of metric resolution in the QP"
  src/metabase/query_processor/middleware/metrics.clj
  test/metabase/query_processor/middleware/metrics_test.clj
Labels: was-backported

#49414 Use column names instead of field refs for pivot viz settings
  e2e/test/scenarios/collections/collection-pinned-overview.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/pivot_tables.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/visualizations-tabular-reproductions.cy.spec.js
  enterprise/backend/src/metabase_enterprise/serialization/load.clj
  enterprise/backend/test/metabase_enterprise/serialization/load_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/test_util.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj
  frontend/src/metabase-lib/v1/queries/utils/pivot.js
  frontend/src/metabase-lib/v1/queries/utils/pivot.ts
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase/lib/data_grid.js
  frontend/src/metabase/query_builder/actions/core/updateQuestion.unit.spec.ts
  frontend/src/metabase/querying/viz-settings/utils/sync-viz-settings.ts
  frontend/src/metabase/querying/viz-settings/utils/sync-viz-settings.unit.spec.tsx
  frontend/src/metabase/services.js
  frontend/src/metabase/services.unit.spec.ts
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.unit.spec.js
  frontend/src/metabase/visualizations/components/settings/ChartSettingsListColumns/ChartSettingsListColumns.styled.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingsListColumns/ChartSettingsListColumns.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingsListColumns/index.ts
  frontend/src/metabase/visualizations/lib/settings/typed-utils.unit.spec.ts
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.tsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.unit.spec.tsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/pivot-table-test-mocks.tsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/settings.ts
  frontend/src/metabase/visualizations/visualizations/PivotTable/stories-data.ts
  frontend/src/metabase/visualizations/visualizations/PivotTable/types.ts
  frontend/src/metabase/visualizations/visualizations/PivotTable/utils.ts
  frontend/src/metabase/visualizations/visualizations/PivotTable/utils.unit.spec.ts
  frontend/test/metabase/lib/data_grid.unit.spec.js
  src/metabase/query_processor/pivot.clj
  test/metabase/api/card_test.clj
  test/metabase/api/downloads_exports_test.clj
  test/metabase/api/pivots.clj
  test/metabase/models/interface_test.clj
  test/metabase/pulse/render/body_test.clj
  test/metabase/query_processor/pivot_test.clj
Labels: backport, .Team/Querying

#49563 🤖 backported "Use column names instead of field refs for pivot viz settings"
  e2e/test/scenarios/collections/collection-pinned-overview.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/pivot_tables.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/visualizations-tabular-reproductions.cy.spec.js
  enterprise/backend/src/metabase_enterprise/serialization/load.clj
  enterprise/backend/test/metabase_enterprise/serialization/load_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/test_util.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj
  frontend/src/metabase-lib/v1/queries/utils/pivot.js
  frontend/src/metabase-lib/v1/queries/utils/pivot.ts
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase/lib/data_grid.js
  frontend/src/metabase/query_builder/actions/core/updateQuestion.unit.spec.ts
  frontend/src/metabase/querying/viz-settings/utils/sync-viz-settings.ts
  frontend/src/metabase/querying/viz-settings/utils/sync-viz-settings.unit.spec.tsx
  frontend/src/metabase/services.js
  frontend/src/metabase/services.unit.spec.ts
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.unit.spec.js
  frontend/src/metabase/visualizations/components/settings/ChartSettingsListColumns/ChartSettingsListColumns.styled.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingsListColumns/ChartSettingsListColumns.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingsListColumns/index.ts
  frontend/src/metabase/visualizations/lib/settings/typed-utils.unit.spec.ts
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.tsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.unit.spec.tsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/pivot-table-test-mocks.tsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/settings.ts
  frontend/src/metabase/visualizations/visualizations/PivotTable/stories-data.ts
  frontend/src/metabase/visualizations/visualizations/PivotTable/types.ts
  frontend/src/metabase/visualizations/visualizations/PivotTable/utils.ts
  frontend/src/metabase/visualizations/visualizations/PivotTable/utils.unit.spec.ts
  frontend/test/metabase/lib/data_grid.unit.spec.js
  src/metabase/query_processor/pivot.clj
  test/metabase/api/card_test.clj
  test/metabase/api/downloads_exports_test.clj
  test/metabase/api/pivots.clj
  test/metabase/models/interface_test.clj
  test/metabase/pulse/render/body_test.clj
  test/metabase/query_processor/pivot_test.clj
Labels: was-backported

#49568 Add v0.50.32 to the list of releases
  docs/releases.md
Labels: Type:Documentation, backport

#49574 🤖 backported "Add v0.50.32 to the list of releases"
  docs/releases.md
Labels: was-backported

#49210 [Notification] Soft migrate dashsub and alert to notification
  dev/src/dev.clj
  dev/src/dev/render_png.clj
  enterprise/backend/src/metabase_enterprise/dashboard_subscription_filters/pulse.clj
  enterprise/backend/test/metabase_enterprise/dashboard_subscription_filters/pulse_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/pulse_test.clj
  src/metabase/api/pulse.clj
  src/metabase/channel/impl/email.clj
  src/metabase/channel/impl/http.clj
  src/metabase/channel/impl/slack.clj
  src/metabase/email/_dashsub_alert_header.mustache
  src/metabase/email/alert.mustache
  src/metabase/email/dashboard_subscription.mustache
  src/metabase/email/messages.clj
  src/metabase/email/pulse.mustache
  src/metabase/notification/core.clj
  src/metabase/notification/payload/core.clj
  src/metabase/notification/payload/execute.clj
  src/metabase/notification/payload/impl/alert.clj
  src/metabase/notification/payload/impl/dashboard_subscription.clj
  src/metabase/notification/send.clj
  src/metabase/pulse/parameters.clj
  src/metabase/pulse/preview.clj
  src/metabase/pulse/send.clj
  src/metabase/pulse/util.clj
  src/metabase/task/send_pulses.clj
  src/metabase/util/retry.clj
  test/metabase/api/pulse_test.clj
  test/metabase/channel/http_test.clj
  test/metabase/dashboard_subscription_test.clj
  test/metabase/email/messages_test.clj
  test/metabase/notification/payload/core_test.clj
  test/metabase/pulse/pulse_integration_test.clj
  test/metabase/pulse/render/body_test.clj
  test/metabase/pulse/send_test.clj
  test/metabase/pulse/test_util.clj
  test/metabase/query_processor/middleware/update_used_cards_test.clj
Labels: no-backport, .Team/BackendComponents

#49419 [Notification] Pulse clean up
  .clj-kondo/config.edn
  deps.edn
  dev/src/dev/render_png.clj
  enterprise/backend/src/metabase_enterprise/dashboard_subscription_filters/parameter.clj
  enterprise/backend/test/metabase_enterprise/dashboard_subscription_filters/parameter_test.clj
  src/metabase/api/embed/common.clj
  src/metabase/api/pulse.clj
  src/metabase/channel/impl/email.clj
  src/metabase/channel/impl/http.clj
  src/metabase/channel/impl/slack.clj
  src/metabase/channel/render/body.clj
  src/metabase/channel/render/color.clj
  src/metabase/channel/render/core.clj
  src/metabase/channel/render/image_bundle.clj
  src/metabase/channel/render/js_engine.clj
  src/metabase/channel/render/js_svg.clj
  src/metabase/channel/render/png.clj
  src/metabase/channel/render/preview.clj
  src/metabase/channel/render/style.clj
  src/metabase/channel/render/table.clj
  src/metabase/email/messages.clj
  src/metabase/models/params/shared.cljc
  src/metabase/notification/payload/core.clj
  src/metabase/notification/payload/execute.clj
  src/metabase/notification/payload/impl/alert.clj
  src/metabase/notification/payload/impl/dashboard_subscription.clj
  src/metabase/pulse/core.clj
  src/metabase/pulse/parameters.clj
  src/metabase/pulse/render/data.json
  src/metabase/pulse/util.clj
  src/metabase/util/urls.clj
  test/metabase/api/pulse_test.clj
  test/metabase/channel/render/body_test.clj
  test/metabase/channel/render/color_test.clj
  test/metabase/channel/render/core_test.clj
  test/metabase/channel/render/js_engine_test.clj
  test/metabase/channel/render/js_svg_test.clj
  test/metabase/channel/render/png_test.clj
  test/metabase/channel/render/style_test.clj
  test/metabase/channel/render/table_test.clj
  test/metabase/dashboard_subscription_test.clj
  test/metabase/models/params/shared_test.cljc
  test/metabase/pulse/parameters_test.clj
  test/metabase/pulse/render/test_util.clj
  test/metabase/pulse/send_test.clj
  test/metabase/util/urls_test.clj
Labels: no-backport, .Team/BackendComponents

#49214 feat(sdk): refactor the auth code to provide better error messages
  e2e/test/scenarios/embedding-sdk/metabase-sdk-styles-tests.cy.spec.ts
  e2e/test/scenarios/embedding-sdk/static-dashboard-cors.cy.spec.js
  enterprise/frontend/src/embedding-sdk/components/private/PublicComponentWrapper/PublicComponentWrapper.tsx
  enterprise/frontend/src/embedding-sdk/components/private/PublicComponentWrapper/PublicComponentWrapper.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/public/MetabaseProvider.tsx
  enterprise/frontend/src/embedding-sdk/hooks/private/index.ts
  enterprise/frontend/src/embedding-sdk/hooks/private/setup-sdk-auth.ts
  enterprise/frontend/src/embedding-sdk/hooks/private/setup-sdk-auth.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/hooks/private/use-init-data.ts
  enterprise/frontend/src/embedding-sdk/hooks/private/use-init-data.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/store/auth.ts
  enterprise/frontend/src/embedding-sdk/store/reducer.ts
  enterprise/frontend/src/embedding-sdk/store/refresh-token.ts
  enterprise/frontend/src/embedding-sdk/store/types.ts
  enterprise/frontend/src/embedding-sdk/test/auth-flow.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/test/sdk-config-errors.unit.spec.tsx
Labels: backport, .Team/Embedding

#49478 Convert Embedding icon hook to CSS and use semantic colors
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingOption.module.css
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingSdkOptionCard/SdkIcon.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/InteractiveEmbeddingOptionCard/InteractiveEmbeddingIcon.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/StaticEmbeddingOptionCard/StaticEmbeddingIcon.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/types.ts
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/use-embedding-settings-icon-colors.tsx
  frontend/src/metabase/css/core/colors.module.css
Labels: backport, .Team/Embedding

#49579 🤖 backported "feat(sdk): refactor the auth code to provide better error messages"
  e2e/test/scenarios/embedding-sdk/metabase-sdk-styles-tests.cy.spec.ts
  e2e/test/scenarios/embedding-sdk/static-dashboard-cors.cy.spec.js
  enterprise/frontend/src/embedding-sdk/components/private/PublicComponentWrapper/PublicComponentWrapper.tsx
  enterprise/frontend/src/embedding-sdk/components/private/PublicComponentWrapper/PublicComponentWrapper.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/public/MetabaseProvider.tsx
  enterprise/frontend/src/embedding-sdk/hooks/private/index.ts
  enterprise/frontend/src/embedding-sdk/hooks/private/setup-sdk-auth.ts
  enterprise/frontend/src/embedding-sdk/hooks/private/setup-sdk-auth.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/hooks/private/use-init-data.ts
  enterprise/frontend/src/embedding-sdk/hooks/private/use-init-data.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/store/auth.ts
  enterprise/frontend/src/embedding-sdk/store/reducer.ts
  enterprise/frontend/src/embedding-sdk/store/refresh-token.ts
  enterprise/frontend/src/embedding-sdk/store/types.ts
  enterprise/frontend/src/embedding-sdk/test/auth-flow.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/test/sdk-config-errors.unit.spec.tsx
Labels: was-backported

#48611 convert qb actions to ts
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  frontend/src/metabase-lib/v1/Question.ts
  frontend/src/metabase-types/store/qb.ts
  frontend/src/metabase/nav/components/search/SearchBar/SearchBar.tsx
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/query_builder/actions/core/core.ts
  frontend/src/metabase/query_builder/actions/core/types.ts
  frontend/src/metabase/query_builder/actions/models.js
  frontend/src/metabase/query_builder/actions/models.ts
  frontend/src/metabase/query_builder/actions/navigation.ts
  frontend/src/metabase/query_builder/actions/object-detail.ts
  frontend/src/metabase/query_builder/actions/querying.ts
  frontend/src/metabase/query_builder/actions/timelines.ts
  frontend/src/metabase/query_builder/components/QueryVisualization.unit.spec.tsx
  frontend/src/metabase/redux/app.ts
Labels: backport, .Team/Querying

#49589 🤖 backported "convert qb actions to ts"
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  frontend/src/metabase-lib/v1/Question.ts
  frontend/src/metabase-types/store/qb.ts
  frontend/src/metabase/nav/components/search/SearchBar/SearchBar.tsx
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/query_builder/actions/core/core.ts
  frontend/src/metabase/query_builder/actions/core/types.ts
  frontend/src/metabase/query_builder/actions/models.js
  frontend/src/metabase/query_builder/actions/models.ts
  frontend/src/metabase/query_builder/actions/navigation.ts
  frontend/src/metabase/query_builder/actions/object-detail.ts
  frontend/src/metabase/query_builder/actions/querying.ts
  frontend/src/metabase/query_builder/actions/timelines.ts
  frontend/src/metabase/query_builder/components/QueryVisualization.unit.spec.tsx
  frontend/src/metabase/redux/app.ts
Labels: was-backported

#49599 Update SDK version to 1.51.3
  enterprise/frontend/src/embedding-sdk/CHANGELOG.md
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: no-backport

#49448 [testing] Add filters to random query generators
  src/metabase/lib/filter.cljc
  src/metabase/lib/schema/filter.cljc
  src/metabase/lib/schema/temporal_bucketing.cljc
  test/metabase/lib/test_util/generators.cljc
  test/metabase/lib/test_util/generators/filters.cljc
  test/metabase/lib/test_util/generators/util.cljc
Labels: no-backport, .Team/Querying

#49580 🤖 backported "Convert Embedding icon hook to CSS and use semantic colors"
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingOption.module.css
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingSdkOptionCard/SdkIcon.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/InteractiveEmbeddingOptionCard/InteractiveEmbeddingIcon.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/StaticEmbeddingOptionCard/StaticEmbeddingIcon.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/types.ts
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/use-embedding-settings-icon-colors.tsx
  frontend/src/metabase/css/core/colors.module.css
Labels: was-backported

#49606 🤖 backported "docs - sdk edits"
  docs/embedding/sdk/appearance.md
  docs/embedding/sdk/authentication.md
  docs/embedding/sdk/collections.md
  docs/embedding/sdk/config.md
  docs/embedding/sdk/dashboards.md
  docs/embedding/sdk/introduction.md
  docs/embedding/sdk/next-js.md
  docs/embedding/sdk/plugins.md
  docs/embedding/sdk/questions.md
  docs/embedding/sdk/quickstart-cli.md
  docs/embedding/sdk/quickstart.md
  docs/embedding/sdk/version.md
  enterprise/frontend/src/embedding-sdk/README.md
Labels: was-backported

#49603 🤖 backported "fix type errors that appear on the mantine branch"
  enterprise/frontend/src/embedding-sdk/store/reducer.ts
Labels: was-backported

#49611 🤖 backported "Update static embedding iframe resizer"
  docs/embedding/static-embedding.md
Labels: was-backported

#49601 Fix flaky #31274 repro
  e2e/test/scenarios/dashboard/dashboard-reproductions.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, backport, flaky-test-fix, .Team/Querying

#49575 Fix :pivot-measures with column names
  e2e/test/scenarios/visualizations-tabular/pivot_tables.cy.spec.js
  src/metabase/query_processor/pivot.clj
  test/metabase/api/downloads_exports_test.clj
Labels: backport, .Team/Querying

#49610 [serdes] meaningful API status codes
  enterprise/backend/src/metabase_enterprise/serialization/api.clj
  enterprise/backend/test/metabase_enterprise/serialization/api_test.clj
Labels: backport, .Team/BackendComponents

#49613 🤖 backported "Fix flaky #31274 repro"
  e2e/test/scenarios/dashboard/dashboard-reproductions.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
Labels: was-backported

#49614 🤖 backported "Fix :pivot-measures with column names"
  e2e/test/scenarios/visualizations-tabular/pivot_tables.cy.spec.js
  src/metabase/query_processor/pivot.clj
  test/metabase/api/downloads_exports_test.clj
Labels: was-backported

#49591 feat(sdk): small usability improvements for embedding cli
  enterprise/frontend/src/embedding-sdk/cli/constants/config.ts
  enterprise/frontend/src/embedding-sdk/cli/constants/database.ts
  enterprise/frontend/src/embedding-sdk/cli/constants/messages.ts
  enterprise/frontend/src/embedding-sdk/cli/run.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/add-database-connection.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/ask-if-has-database.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/ask-tenancy-columns.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/generate-credentials.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/index.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/show-metabase-cli-title.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/show-post-setup-steps.ts
  enterprise/frontend/src/embedding-sdk/cli/types/cli.ts
Labels: backport, .Team/Embedding, Embedding/SDK

#49616 🤖 backported "[serdes] meaningful API status codes"
  enterprise/backend/src/metabase_enterprise/serialization/api.clj
  enterprise/backend/test/metabase_enterprise/serialization/api_test.clj
Labels: was-backported

#49554 Push metabot to stats
  .github/workflows/uberjar.yml
Labels: .CI & Tests, no-backport, .Team/AdminWebapp

#49626 Fix auto-release artifact name collision
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
Labels: .Building & Releasing, no-backport, .Team/AdminWebapp

#49509 Make sure a new table gets table-level block if any other tables have table-level block
  enterprise/backend/src/metabase_enterprise/advanced_permissions/common.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  src/metabase/models/data_permissions.clj
  src/metabase/models/table.clj
  test/metabase/models/data_permissions_test.clj
Labels: backport, .Team/AdminWebapp

#49512 Filter out Empty Rows from Pivot Exports
  src/metabase/query_processor/pivot/postprocess.clj
  test/metabase/api/downloads_exports_test.clj
Labels: backport, .Team/DashViz

#49638 🤖 backported "Filter out Empty Rows from Pivot Exports "
  src/metabase/query_processor/pivot/postprocess.clj
  test/metabase/api/downloads_exports_test.clj
Labels: was-backported

#49530 Fix - Values from the returned rows not present in the visualization are interpolable in the URL but don't have values
  e2e/test/scenarios/dashboard-cards/dashboard-card-reproductions.cy.spec.js
  frontend/src/metabase/visualizations/visualizations/RowChart/utils/events.ts
Labels: backport, .Team/Querying

#49612 🤖 backported "Fix flaky datamodel test"
  e2e/test/scenarios/admin/datamodel/datamodel.cy.spec.js
Labels: was-backported

#49654 🤖 backported "Fix - Values from the returned rows not present in the visualization are interpolable in the URL but don't have values"
  e2e/test/scenarios/dashboard-cards/dashboard-card-reproductions.cy.spec.js
  frontend/src/metabase/visualizations/visualizations/RowChart/utils/events.ts
Labels: was-backported

#49617 🤖 backported "feat(sdk): small usability improvements for embedding cli"
  enterprise/frontend/src/embedding-sdk/cli/constants/config.ts
  enterprise/frontend/src/embedding-sdk/cli/constants/database.ts
  enterprise/frontend/src/embedding-sdk/cli/constants/messages.ts
  enterprise/frontend/src/embedding-sdk/cli/run.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/add-database-connection.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/ask-if-has-database.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/ask-tenancy-columns.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/generate-credentials.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/index.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/show-metabase-cli-title.ts
  enterprise/frontend/src/embedding-sdk/cli/steps/show-post-setup-steps.ts
  enterprise/frontend/src/embedding-sdk/cli/types/cli.ts
Labels: was-backported

#49674 Update SDK version to 1.52.1
  enterprise/frontend/src/embedding-sdk/CHANGELOG.md
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: no-backport

#49669 🤖 backported "Email throttling config"
  src/metabase/email.clj
  test/metabase/email_test.clj
  test_resources/serialization_baseline/settings.yaml
Labels: was-backported

#49167 feat(sdk): Add chart settings to `InteractiveQuestion`
  docs/embedding/sdk/questions.md
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/QuestionSettings.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/index.ts
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.tsx
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase/visualizations/components/ChartSettings/index.ts
Labels: backport, .Team/Embedding

#49672 fix(sdk): Fix visualization default size
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/Visualization.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult/InteractiveQuestionResult.tsx
Labels: backport, .Team/Embedding

#49545 Re-introduce "Upload CSV" button for instances with DWH attached
  e2e/test/scenarios/models/reproductions.cy.spec.ts
  e2e/test/scenarios/onboarding/add-initial-data.cy.spec.ts
  frontend/src/metabase-types/analytics/event.ts
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbar.unit.spec.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarView.tsx
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/DwhUploadCSV/DwhUploadCSV.tsx
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/DwhUploadCSV/analytics.ts
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/DwhUploadCSV/index.ts
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/SidebarOnboardingSection/SidebarOnboardingSection.tsx
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/SidebarOnboardingSection/analytics.ts
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/SidebarOnboardingSection/index.ts
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/SidebarOnboardingSection/types.ts
  frontend/src/metabase/nav/containers/MainNavbar/analytics.ts
  frontend/src/metabase/nav/containers/MainNavbar/tests/common.unit.spec.tsx
  frontend/src/metabase/nav/containers/MainNavbar/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/nav/containers/MainNavbar/tests/premium.unit.spec.tsx
  frontend/src/metabase/nav/containers/MainNavbar/tests/setup.tsx
Labels: no-backport

#49555 docs: contact support to change cloud env var
  docs/dashboards/subscriptions.md
  src/metabase/cmd/resources/env-var-intro.md
Labels: Type:Documentation, backport

#49699 docs: remove nested queires admin setting
  docs/configuring-metabase/settings.md
  docs/troubleshooting-guide/models.md
Labels: Type:Documentation, backport

#49675 Note about apsaradb
  docs/installation-and-operation/configuring-application-database.md
Labels: backport

#49702 🤖 backported "docs: remove nested queires admin setting"
  docs/configuring-metabase/settings.md
  docs/troubleshooting-guide/models.md
Labels: was-backported

#49703 🤖 backported "Note about apsaradb"
  docs/installation-and-operation/configuring-application-database.md
Labels: was-backported

#49659 fix(sdk): put a bandage on the flashing error on static question in strict mode
  enterprise/frontend/src/embedding-sdk/hooks/private/use-load-static-question.ts
Labels: backport, .Team/Embedding

#49706 🤖 backported "docs - link fix"
  docs/embedding/sdk/quickstart.md
Labels: was-backported

#49137 Remove withFeatures from renderWithProviders
  frontend/src/metabase/collections/components/CollectionInfoSidebar/tests/premium.unit.spec.tsx
  frontend/src/metabase/collections/components/CollectionInfoSidebar/tests/setup.tsx
  frontend/src/metabase/dashboard/components/DashboardInfoSidebar/DashboardEntityIdCard/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardInfoSidebar/DashboardEntityIdCard/tests/premium.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardInfoSidebar/DashboardEntityIdCard/tests/setup.tsx
  frontend/test/__support__/ui.tsx
Labels: backport, .Team/AdminWebapp

#49637 Manual backport of #49509 to v50
  enterprise/backend/src/metabase_enterprise/advanced_permissions/common.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  src/metabase/models/data_permissions.clj
  src/metabase/models/table.clj
  test/metabase/models/data_permissions_test.clj
Labels: .Team/AdminWebapp

#49704 🤖 backported "fix(sdk): put a bandage on the flashing error on static question in strict mode"
  enterprise/frontend/src/embedding-sdk/hooks/private/use-load-static-question.ts
Labels: was-backported

#49631 Add `breakout_query` tool
  enterprise/backend/src/metabase_enterprise/metabot_v3/context.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/reactions.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/breakout-query.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/breakout_query.clj
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/index.ts
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/queries.ts
  frontend/src/metabase-types/api/metabot.ts
Labels: .Team/Querying

#49629 Add `limit_query` tool
  enterprise/backend/src/metabase_enterprise/metabot_v3/context.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/reactions.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/breakout-query.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/breakout_query.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/limit-query.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/limit_query.clj
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/index.ts
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/queries.ts
  frontend/src/metabase-types/api/metabot.ts
Labels: .Team/Querying

#49622 Add `aggregate_query` tool
  enterprise/backend/src/metabase_enterprise/metabot_v3/context.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/reactions.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/aggregate-query.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/aggregate_query.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/breakout-query.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/breakout_query.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/limit-query.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/limit_query.clj
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/index.ts
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/queries.ts
  frontend/src/metabase-types/api/metabot.ts
Labels: .Team/Querying

#49619 Add `sort_query` tool
  enterprise/backend/src/metabase_enterprise/metabot_v3/context.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/reactions.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/aggregate-query.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/aggregate_query.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/breakout-query.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/breakout_query.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/limit-query.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/limit_query.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/sort-query.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/sort_query.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/tools_test.clj
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/index.ts
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/queries.ts
  frontend/src/metabase-types/api/metabot.ts
  frontend/src/metabase/query_builder/containers/use-register-metabot-context.tsx
Labels: no-backport, .Team/Querying

#49701 🤖 backported "docs: contact support to change cloud env var"
  docs/dashboards/subscriptions.md
  src/metabase/cmd/resources/env-var-intro.md
Labels: was-backported

#49726 docs - notes on database browser
  docs/exploration-and-organization/exploration.md
  docs/permissions/data.md
Labels: Type:Documentation, backport

#49727 🤖 backported "docs - notes on database browser"
  docs/exploration-and-organization/exploration.md
  docs/permissions/data.md
Labels: was-backported

#49639 metabot v3: provide complete visualization settings to llm
  frontend/src/metabase/metabot-v3/selectors.ts
  frontend/src/metabase/query_builder/containers/use-register-metabot-context.tsx
Labels: .Team/DashViz

#49710 redshift defines "text" as varchar(255) and we want it to be way longer
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  test/metabase/upload_test.clj
Labels: backport, .Team/BackendComponents

#49728 🤖 backported "redshift defines "text" as varchar(255) and we want it to be way longer"
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  test/metabase/upload_test.clj
Labels: was-backported

#49651 metabot v3: y axis range tool
  enterprise/backend/src/metabase_enterprise/metabot_v3/reactions.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change-y-axis-range.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change_y_axis_range.clj
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/index.ts
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/visualizations.ts
  frontend/src/metabase-types/api/metabot.ts
Labels: .Team/DashViz

#49650 metabot v3: add change goal line tool
  enterprise/backend/src/metabase_enterprise/metabot_v3/reactions.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change-goal-line.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change-y-axis-range.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change_goal_line.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change_y_axis_range.clj
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/index.ts
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/visualizations.ts
  frontend/src/metabase-types/api/metabot.ts
Labels: .Team/DashViz

#49649 metabot v3: stacked setting tool
  enterprise/backend/src/metabase_enterprise/metabot_v3/reactions.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change-goal-line.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change-stacking-settings.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change-y-axis-range.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change_goal_line.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change_stacking_settings.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change_y_axis_range.clj
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/index.ts
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/visualizations.ts
  frontend/src/metabase-types/api/metabot.ts
Labels: .Team/DashViz

#49640 metabot v3: change axes names tool
  enterprise/backend/src/metabase_enterprise/metabot_v3/reactions.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change-axes-labels.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change_axes_labels.clj
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/index.ts
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/visualizations.ts
  frontend/src/metabase-types/api/metabot.ts
Labels: .Team/DashViz

#49644 metabot v3: change series settings tool
  enterprise/backend/src/metabase_enterprise/metabot_v3/reactions.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change-column-settings.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change-goal-line.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change-series-settings.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change-stacking-settings.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change-table-visualization-settings.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change-y-axis-range.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change_column_settings.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change_goal_line.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change_series_settings.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change_stacking_settings.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/change_y_axis_range.clj
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/index.ts
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/visualizations.ts
  frontend/src/metabase-types/api/metabot.ts
  frontend/src/metabase/query_builder/containers/use-register-metabot-context.tsx
Labels: .Team/DashViz

#49707 Fix label and link on authentication upsell card
  frontend/src/metabase/admin/upsells/UpsellSSO.tsx
Labels: backport, .Team/AdminWebapp

#49576 [Notification] Send notification options
  src/metabase/api/pulse.clj
  src/metabase/events/notification.clj
  src/metabase/notification/core.clj
  src/metabase/pulse/send.clj
  src/metabase/task/notification.clj
  src/metabase/task/send_pulses.clj
  test/metabase/events/notification_test.clj
  test/metabase/notification/test_util.clj
Labels: no-backport, .Team/BackendComponents

#49465 Handle touch start capture as well as mouse down for popover
  frontend/src/metabase/ui/components/overlays/Menu/MenuItem/MenuItem.tsx
  frontend/src/metabase/ui/components/overlays/Popover/Popover.styled.tsx
Labels: backport, .Team/Querying

#49736 🤖 backported "Handle touch start capture as well as mouse down for popover"
  frontend/src/metabase/ui/components/overlays/Menu/MenuItem/MenuItem.tsx
  frontend/src/metabase/ui/components/overlays/Popover/Popover.styled.tsx
Labels: was-backported

#49441 Support localization in static embeds
  e2e/support/helpers/e2e-embedding-helpers.js
  e2e/test/scenarios/embedding/embedding-linked-filters.cy.spec.js
  e2e/test/scenarios/embedding/embedding-native.cy.spec.js
  e2e/test/scenarios/embedding/embedding-reproductions.cy.spec.js
  enterprise/frontend/src/embedding-sdk/components/public/MetabaseProvider.tsx
  frontend/src/metabase/dashboard/hooks/use-dashboard-url-params.ts
  frontend/src/metabase/dashboard/types/hash-options.ts
  frontend/src/metabase/lib/i18n.js
  frontend/src/metabase/public/LocaleProvider.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboard.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardPage.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion.tsx
  frontend/src/metabase/public/hooks/use-embed-frame-options.ts
  frontend/src/metabase/public/lib/types.ts
  src/metabase/server/middleware/session.clj
  test/metabase/server/middleware/session_test.clj
Labels: backport, .Team/Embedding

#49749 docs(sdk): fix dead link in sdk quickstart
  docs/embedding/sdk/quickstart.md
Labels: backport, .Team/Embedding, Embedding/SDK

#49750 🤖 backported "docs(sdk): fix dead link in sdk quickstart"
  docs/embedding/sdk/quickstart.md
Labels: was-backported

#49656 Remove sandboxes tests from flaky jail
  e2e/test/scenarios/permissions/sandboxes.cy.spec.js
Labels: .CI & Tests, backport, flaky-test-fix, .Team/Querying

#49745 Fix flaky native query drill test
  e2e/test/scenarios/question/native-query-drill.cy.spec.ts
Labels: .CI & Tests, backport, flaky-test-fix, .Team/Querying

#49747 feat(sdk): deprecate the ModifyQuestion component
  docs/embedding/sdk/questions.md
  enterprise/frontend/src/embedding-sdk/components/public/ModifyQuestion/ModifyQuestion.tsx
Labels: backport, .Team/Embedding, Embedding/SDK

#49754 🤖 backported "Remove sandboxes tests from flaky jail"
  e2e/test/scenarios/permissions/sandboxes.cy.spec.js
Labels: was-backported

#49755 🤖 backported "Fix flaky native query drill test"
  e2e/test/scenarios/question/native-query-drill.cy.spec.ts
Labels: was-backported

#49757 🤖 backported "feat(sdk): deprecate the ModifyQuestion component"
  docs/embedding/sdk/questions.md
  enterprise/frontend/src/embedding-sdk/components/public/ModifyQuestion/ModifyQuestion.tsx
Labels: was-backported

#49753 Fix flaky 25885 repro
  e2e/test/scenarios/models/reproductions.cy.spec.ts
Labels: .CI & Tests, backport, flaky-test-fix, .Team/Querying

#49760 🤖 backported "Fix flaky 25885 repro"
  e2e/test/scenarios/models/reproductions.cy.spec.ts
Labels: was-backported

#49761 🤖 backported "Remove @flaky tag from no longer flaking tests"
  e2e/test/scenarios/dashboard-filters/dashboard-filters-sql-text-category.cy.spec.js
  e2e/test/scenarios/metrics/metrics-collection.cy.spec.js
  e2e/test/scenarios/models/models-metadata.cy.spec.js
Labels: was-backported
