Repository metabase/metabase, pull requests merged in 2024-01, with the labels that each got.

#37181 Update readme to 2024
  README.md
Labels: backport

#37059 docs - embed quick start
  docs/README.md
  docs/embedding/images/all-users.png
  docs/embedding/images/jwt-setup.png
  docs/embedding/images/map-user-attribute.png
  docs/embedding/images/sandboxed-invoices-table.png
  docs/embedding/images/sync-groups.png
  docs/embedding/interactive-embedding-quick-start-guide.md
  docs/embedding/interactive-embedding.md
  docs/embedding/start.md
Labels: Type:Documentation, backport

#37094 disable static charts animation
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.tsx
  frontend/src/metabase/static-viz/components/ScatterPlot/ScatterPlot.tsx
  frontend/src/metabase/visualizations/echarts/cartesian/constants/style.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/index.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/CartesianChart.tsx
Labels: visual, .Team/DashViz

#37178 remove `metabase.models.permissions.util`
  enterprise/backend/src/metabase_enterprise/advanced_permissions/driver/impersonation.clj
  src/metabase/models/permissions/util.clj
Labels: no-backport, .Team/AdminWebapp

#37200 Update relative date filter tests for 2024
  e2e/test/scenarios/dashboard-cards/dashboard-drill.cy.spec.js
  e2e/test/scenarios/dashboard-filters/shared/dashboard-filters-date.js
  e2e/test/scenarios/dashboard-filters/shared/dashboard-filters-sql-date.js
Labels: .CI & Tests, backport, .Team/AdminWebapp

#37190 Update copyright year in EE code
  enterprise/backend/src/metabase_enterprise/core.clj
Labels: no-backport, .Team/AdminWebapp

#37051 Add a DELETE endpoint for API Keys
  src/metabase/api/api_key.clj
  src/metabase/events/audit_log.clj
  src/metabase/models/api_key.clj
  src/metabase/server/middleware/session.clj
  test/metabase/api/api_key_test.clj
Labels: no-backport, .Team/AdminWebapp

#37061 Return `group` instead of just `group_name` for ApiKeys
  src/metabase/api/api_key.clj
  src/metabase/models/api_key.clj
  test/metabase/api/api_key_test.clj
Labels: no-backport, .Team/AdminWebapp

#37092 Typo in FormSelect
  frontend/src/metabase/forms/components/FormSelect/FormSelect.tsx
Labels: no-backport, .Team/AdminWebapp

#36830 Automated release status updates in Slack
  .github/workflows/release-status.yml
  release/package.json
  release/src/github.ts
  release/src/index.ts
  release/src/release-status.ts
  release/src/slack.ts
  release/src/types.ts
  release/yarn.lock
Labels: .Building & Releasing, no-backport, .Team/AdminWebapp

#37095 Add CopyTextInput component
  frontend/src/metabase/components/CopyTextInput/CopyTextInput.styled.tsx
  frontend/src/metabase/components/CopyTextInput/CopyTextInput.tsx
  frontend/src/metabase/components/CopyTextInput/index.ts
Labels: no-backport, .Team/AdminWebapp

#37085 Oops - remove API bits from ApiKey model
  src/metabase/models/api_key.clj
Labels: no-backport, .Team/AdminWebapp

#37096 Add FormGroupWidget component
  frontend/src/metabase/forms/components/FormGroupWidget/FormGroupWidget.tsx
  frontend/src/metabase/forms/components/FormGroupWidget/index.ts
  frontend/src/metabase/forms/components/index.ts
Labels: no-backport, .Team/AdminWebapp

#37207 Update enterprise readme to 2024
  enterprise/README.md
Labels: no-backport

#37143 Add dynamic scatter plot
  frontend/src/metabase/lib/objects.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/types.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/scatter/model.ts
  frontend/src/metabase/visualizations/echarts/cartesian/scatter/series.ts
  frontend/src/metabase/visualizations/lib/graph/columns.ts
  frontend/src/metabase/visualizations/register.js
  frontend/src/metabase/visualizations/visualizations/ScatterPlot.jsx
  frontend/src/metabase/visualizations/visualizations/ScatterPlot/ScatterPlot.tsx
  frontend/src/metabase/visualizations/visualizations/ScatterPlot/index.ts
Labels: visual, .Team/DashViz

#36959 [MLv2] Drop redundant :fields clauses from stages and joins
  frontend/src/metabase-lib/queries/utils/dataset.js
  src/metabase/lib/equality.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/remove_replace.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/remove_replace_test.cljc
Labels: .Team/QueryProcessor, no-backport

#37177 Create `metabase.permissions.util` namespace
  enterprise/backend/src/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions.clj
  src/metabase/models/collection.clj
  src/metabase/models/permissions.clj
  src/metabase/models/query/permissions.clj
  src/metabase/permissions/util.clj
  src/metabase/search/config.clj
  test/metabase/api/card_test.clj
  test/metabase/models/permissions_group_test.clj
  test/metabase/models/permissions_test.clj
  test/metabase/permissions/util_test.clj
Labels: no-backport, .Team/AdminWebapp

#37213 Modify type metabase_field.database_required to bit(1) in mysql
  resources/migrations/001_update_migrations.yaml
  test/metabase/db/schema_migrations_test.clj
Labels: no-backport, .Team/BackendComponents

#37199 FilterValuePicker tests
  frontend/src/metabase/querying/components/FilterValuePicker/FilterValuePicker.tsx
  frontend/src/metabase/querying/components/FilterValuePicker/FilterValuePicker.unit.spec.tsx
Labels: .Team/QueryingComponents

#37214 Add Chris Truter to team.json
  .github/team.json
Labels: no-backport, .Team/BackendComponents

#37203 Filter modal tests
  frontend/src/metabase-types/api/mocks/field.ts
  frontend/src/metabase-types/api/mocks/presets/sample_database.ts
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.unit.spec.tsx
  frontend/src/metabase/components/FieldValuesWidget/utils.unit.spec.js
  frontend/src/metabase/querying/components/FilterModal/FilterModal.unit.spec.tsx
  frontend/src/metabase/querying/components/FilterModal/SegmentFilterEditor/SegmentFilterEditor.tsx
Labels: .Team/QueryingComponents

#37217 Fix incorrect time format strings in filters
  frontend/src/metabase-lib/filter.ts
  frontend/src/metabase-lib/filter.unit.spec.ts
Labels: no-backport, .Team/QueryingComponents

#37072 [MLv2] [FE] MultiSelect-based filter fixes
  e2e/support/helpers/e2e-bi-basics-helpers.js
  e2e/test/scenarios/filters/filter-bulk.cy.spec.js
  e2e/test/scenarios/filters/reproductions/16621-create-multiple-filters-with-same-value.cy.spec.js
  e2e/test/scenarios/joins/joins.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
  frontend/src/metabase-types/api/mocks/field.ts
  frontend/src/metabase-types/api/mocks/presets/sample_database.ts
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.unit.spec.tsx
  frontend/src/metabase/components/FieldValuesWidget/utils.unit.spec.js
  frontend/src/metabase/querying/components/FilterModal/BooleanFilterEditor/BooleanFilterEditor.unit.spec.tsx
  frontend/src/metabase/querying/components/FilterModal/CoordinateFilterEditor/CoordinateFilterEditor.tsx
  frontend/src/metabase/querying/components/FilterModal/CoordinateFilterEditor/CoordinateFilterEditor.unit.spec.tsx
  frontend/src/metabase/querying/components/FilterModal/FilterModal.unit.spec.tsx
  frontend/src/metabase/querying/components/FilterModal/NumberFilterEditor/NumberFilterEditor.tsx
  frontend/src/metabase/querying/components/FilterModal/NumberFilterEditor/NumberFilterEditor.unit.spec.tsx
  frontend/src/metabase/querying/components/FilterModal/SegmentFilterEditor/SegmentFilterEditor.tsx
  frontend/src/metabase/querying/components/FilterModal/StringFilterEditor/StringFilterEditor.tsx
  frontend/src/metabase/querying/components/FilterModal/StringFilterEditor/StringFilterEditor.unit.spec.tsx
  frontend/src/metabase/querying/components/FilterModal/TimeFilterEditor/TimeFilterEditor.tsx
  frontend/src/metabase/querying/components/FilterModal/TimeFilterEditor/TimeFilterEditor.unit.spec.tsx
  frontend/src/metabase/querying/components/FilterValuePicker/FilterValuePicker.tsx
  frontend/src/metabase/querying/components/FilterValuePicker/FilterValuePicker.unit.spec.tsx
  frontend/src/metabase/querying/components/FilterValuePicker/ListValuePicker/ListValuePicker.tsx
  frontend/src/metabase/querying/components/FilterValuePicker/ListValuePicker/constants.ts
  frontend/src/metabase/querying/components/FilterValuePicker/ListValuePicker/utils.ts
  frontend/src/metabase/querying/components/FilterValuePicker/SearchValuePicker/SearchValuePicker.tsx
  frontend/src/metabase/querying/components/FilterValuePicker/SearchValuePicker/utils.ts
  frontend/src/metabase/querying/components/FilterValuePicker/StaticValuePicker/StaticValuePicker.tsx
  frontend/src/metabase/querying/components/FilterValuePicker/constants.ts
  frontend/src/metabase/querying/components/FilterValuePicker/types.ts
  frontend/src/metabase/querying/components/FilterValuePicker/utils.ts
  frontend/src/metabase/ui/components/inputs/MultiAutocomplete/MultiAutocomplete.tsx
  frontend/src/metabase/ui/components/inputs/MultiAutocomplete/index.ts
  frontend/src/metabase/ui/components/inputs/Select/Select.styled.tsx
  frontend/src/metabase/ui/components/inputs/Select/index.ts
  frontend/src/metabase/ui/components/inputs/index.ts
  frontend/src/metabase/ui/components/overlays/Popover/use-popover.ts
Labels: no-backport, .Team/QueryingComponents

#37052 CSV appends: Add based_on_upload to GET /api/card endpoint
  enterprise/backend/test/metabase_enterprise/upload_test.clj
  src/metabase/api/card.clj
  src/metabase/upload.clj
  test/metabase/api/card_test.clj
Labels: no-backport, .Team/BackendComponents

#37198 docs - sections on cloud
  README.md
  docs/README.md
  docs/installation-and-operation/installing-metabase.md
Labels: Type:Documentation, backport

#37218 Filter modal date tests
  frontend/src/metabase/querying/components/FilterModal/DateFilterEditor/DateFilterEditor.unit.spec.tsx
Labels: no-backport, .Team/QueryingComponents

#37091 docs - upload privileges
  docs/databases/uploads.md
  docs/databases/users-roles-privileges.md
Labels: Type:Documentation, backport

#37223 upcoming release status
  release/src/slack.ts
Labels: .Building & Releasing, no-backport, .Team/AdminWebapp

#37189 Use counter instead of `gensym` to make mongo field aliases unique
  modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj
  modules/drivers/mongo/test/metabase/driver/mongo/query_processor_test.clj
Labels: Database/Mongo, backport, .Team/QueryProcessor

#37225 Add segment editor tests
  frontend/src/metabase-lib/test-helpers.ts
  frontend/src/metabase/querying/components/FilterModal/SegmentFilterEditor/SegmentFilterEditor.tsx
  frontend/src/metabase/querying/components/FilterModal/SegmentFilterEditor/SegmentFilterEditor.unit.spec.tsx
Labels: no-backport, .Team/QueryingComponents

#37204 Support replacing expression with modified names
  .dir-locals.el
  src/metabase/lib/expression.cljc
  src/metabase/lib/remove_replace.cljc
  test/metabase/lib/remove_replace_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor, no-backport

#37221 Add e2e test for a line chart with axis - number
  e2e/test/scenarios/visualizations-charts/line_chart.cy.spec.js
Labels: no-backport, .Team/QueryingComponents

#37235 Upload only failed Replay e2e recordings
  e2e/support/config.js
Labels: .CI & Tests, no-backport

#37206 [MLv2] Normalize expression-clause
  src/metabase/lib/js.cljs
  src/metabase/lib/normalize.cljc
  test/metabase/lib/js_test.cljs
Labels: .metabase-lib, .Team/QueryProcessor, no-backport

#37242 Add `sloansparger` to `AdminWebapp` team
  .github/team.json
Labels: no-backport, .Team/AdminWebapp

#37210 Implement truncate, add, and unit-diff date util functions for Cljs
  src/metabase/shared/util/internal/time.clj
  src/metabase/shared/util/internal/time.cljs
  src/metabase/shared/util/time.cljc
  src/metabase/util/date_2.clj
  test/metabase/shared/util/time_test.cljc
  test/metabase/util/date_2_test.clj
Labels: .Team/QueryProcessor, no-backport

#36866 When updating an alert, don't also update the question
  e2e/test/scenarios/sharing/alert/email-alert.cy.spec.js
  frontend/src/metabase/query_builder/components/AlertModals.jsx
Labels: no-backport, .Team/AdminWebapp

#37211 Implement brush filter helper functions
  frontend/src/metabase-lib/filter.ts
  src/metabase/lib/core.cljc
  src/metabase/lib/filter/update.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/schema/filter.cljc
  test/metabase/lib/filter/update_test.cljc
Labels: .Team/QueryProcessor, no-backport

#37236 Make e2e tests less flaky
  e2e/test/scenarios/dashboard/reproductions/34382-dashboard-back-navigation-preserve-filters.cy.spec.js
  e2e/test/scenarios/visualizations-charts/line_chart.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/drillthroughs/chart_drill.cy.spec.js
Labels: no-backport, .Team/QueryingComponents

#37241 Finally introduce the `mt/test-helpers-set-global-values!` pattern
  .clj-kondo/config.edn
  .clj-kondo/hooks/clojure/test.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/api/group_manager_test.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/pages/alerts_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/pages/dashboard_subscriptions_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/pages_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/entity_ids_test.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/saml_test.clj
  test/metabase/actions/execution_test.clj
  test/metabase/api/action_test.clj
  test/metabase/api/card_test.clj
  test/metabase/api/collection_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/embed_test.clj
  test/metabase/api/public_test.clj
  test/metabase/api/user_test.clj
  test/metabase/async/streaming_response_test.clj
  test/metabase/integrations/common_test.clj
  test/metabase/models/login_history_test.clj
  test/metabase/models/user_test.clj
  test/metabase/sync/sync_metadata/fields/sync_instances_test.clj
  test/metabase/task/sync_databases_test.clj
  test/metabase/test.clj
  test/metabase/test/redefs.clj
  test/metabase/test/util/thread_local.clj
Labels: no-backport

#37208 Consistent formatting of all columns in Excel exports
  src/metabase/formatter.clj
  src/metabase/formatter/datetime.clj
  src/metabase/query_processor/streaming/common.clj
  src/metabase/query_processor/streaming/csv.clj
  src/metabase/query_processor/streaming/json.clj
  src/metabase/query_processor/streaming/xlsx.clj
  test/metabase/api/card_test.clj
  test/metabase/formatter/datetime_test.clj
  test/metabase/formatter_test.clj
  test/metabase/pulse/pulse_integration_test.clj
  test/metabase/query_processor/streaming/xlsx_test.clj
Labels: no-backport, .Team/DashViz

#37237 Guard against version duplication (#33803)
  bin/build/src/release/version_info.clj
  bin/build/test/release/version_info_test.clj
Labels: no-backport, .Team/BackendComponents

#37005 Redshift support for CSV uploads
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  src/metabase/driver/postgres.clj
Labels: backport, .Team/BackendComponents

#37254 Drop the test which was mistakenly backported
  e2e/test/scenarios/visualizations-charts/maps.cy.spec.js
Labels: .Team/QueryingComponents

#37255 Fix stress-test workflow
  .github/workflows/e2e-stress-test-flake-fix.yml
Labels: Type:Tech Debt, .CI & Tests, no-backport

#37087 Trend charts — Compare to another column
  e2e/test/scenarios/visualizations-tabular/smartscalar-trend.cy.spec.js
  frontend/src/metabase-types/api/visualization-settings.ts
  frontend/src/metabase/ui/components/inputs/Autocomplete/Autocomplete.styled.tsx
  frontend/src/metabase/ui/components/inputs/MultiSelect/MultiSelect.styled.tsx
  frontend/src/metabase/ui/components/inputs/Select/Select.styled.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SettingsComponents/AnotherColumnForm.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SettingsComponents/SmartScalarSettingsWidgets.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.jsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/compute.js
  frontend/src/metabase/visualizations/visualizations/SmartScalar/compute.unit.spec.js
  frontend/src/metabase/visualizations/visualizations/SmartScalar/constants.ts
  frontend/src/metabase/visualizations/visualizations/SmartScalar/types.ts
  frontend/src/metabase/visualizations/visualizations/SmartScalar/utils.ts
  frontend/src/metabase/visualizations/visualizations/SmartScalar/utils.unit.spec.ts
Labels: visual, .Team/DashViz

#37078 CSV uploads: support more date formats
  src/metabase/upload.clj
  src/metabase/upload/parsing.clj
  test/metabase/upload_test.clj
Labels: backport, .Team/BackendComponents

#37256 🍒 Adapt the stress-test workflow to work with `replay-chromium` (#37255)
  .github/workflows/e2e-stress-test-flake-fix.yml
Labels: was-backported

#37229 [MLv2] Removing a final JOIN condition removes the whole join
  dev/src/dev/fe_helpers.cljs
  src/metabase/lib/remove_replace.cljc
  test/metabase/lib/remove_replace_test.cljc
Labels: no-backport

#37176 Trend charts — multiple comparisons
  e2e/test/scenarios/visualizations-tabular/smartscalar-trend.cy.spec.js
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase-types/api/visualization-settings.ts
  frontend/src/metabase/core/components/Sortable/Sortable.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SettingsComponents/AnotherColumnForm.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SettingsComponents/ComparisonPicker.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SettingsComponents/PeriodsAgoMenuOption.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SettingsComponents/SmartScalarSettingsWidgets.styled.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SettingsComponents/SmartScalarSettingsWidgets.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SettingsComponents/StaticNumberForm.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.jsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.unit.spec.js
  frontend/src/metabase/visualizations/visualizations/SmartScalar/compute.js
  frontend/src/metabase/visualizations/visualizations/SmartScalar/compute.unit.spec.js
  frontend/src/metabase/visualizations/visualizations/SmartScalar/constants.ts
  frontend/src/metabase/visualizations/visualizations/SmartScalar/utils.ts
  frontend/src/metabase/visualizations/visualizations/SmartScalar/utils.unit.spec.ts
Labels: visual, .Team/DashViz

#36919 Add shallow and location param to /api/collection/tree
  src/metabase/api/collection.clj
  test/metabase/api/collection_test.clj
Labels: backport, .Team/AdminWebapp

#37267 Create CODEOWNERS with camsaul owning src/metabase
  .github/CODEOWNERS
Labels: no-backport

#37234 Add last_name to ApiKey users
  src/metabase/api/api_key.clj
  src/metabase/models/user.clj
Labels: no-backport, .Team/AdminWebapp

#37238 [MLv2] Fix field-values-search-info returning string ids
  e2e/test/scenarios/joins/joins.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
  src/metabase/lib/field.cljc
  test/metabase/lib/field_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor, no-backport

#37273 Localize text for filter apply button in dashboard filters
  frontend/src/metabase/parameters/components/FilterApplyButton/FilterApplyButton.tsx
Labels: backport, .Team/AdminWebapp

#37246 [MLv2] Support exclude date filter for filter args display name
  frontend/src/metabase/querying/components/FilterModal/DateFilterEditor/DateFilterEditor.unit.spec.tsx
  src/metabase/lib/fe_util.cljc
  test/metabase/lib/fe_util_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor, no-backport

#37239 Error if DB downgrades are required
  src/metabase/db/liquibase.clj
  src/metabase/db/setup.clj
  test/metabase/db/setup_test.clj
Labels: backport, .Team/AdminWebapp

#37279 Fixing case of invalid graph.dimension
  src/metabase/util/ui_logic.clj
  test/metabase/pulse/render/body_test.clj
Labels: no-backport, .Team/DashViz

#37205 Use simple `Secret`s for ApiKeys
  src/metabase/api/api_key.clj
  src/metabase/models/api_key.clj
  src/metabase/util/secret.clj
  test/metabase/api/api_key_test.clj
  test/metabase/server/middleware/session_test.clj
Labels: no-backport, .Team/AdminWebapp

#37274 Number viz render method properly uses :scalar.field name to render value
  src/metabase/pulse/render/body.clj
  test/metabase/pulse/pulse_integration_test.clj
Labels: backport, visual, .Team/DashViz

#36520 `NotebookSteps`, `steps` - migrate modifying queries to MLv2
  e2e/test/scenarios/custom-column/reproductions/19745-cc-nested-query-remove-expressions.cy.spec.js
  e2e/test/scenarios/permissions/sandboxes.cy.spec.js
  frontend/src/metabase-lib/query.ts
  frontend/src/metabase/query_builder/components/notebook/Notebook.tsx
  frontend/src/metabase/query_builder/components/notebook/NotebookStep/NotebookStep.tsx
  frontend/src/metabase/query_builder/components/notebook/NotebookStepPreview.jsx
  frontend/src/metabase/query_builder/components/notebook/NotebookSteps/NotebookSteps.tsx
  frontend/src/metabase/query_builder/components/notebook/lib/steps.ts
  frontend/src/metabase/query_builder/components/notebook/lib/steps.unit.spec.js
  frontend/src/metabase/query_builder/components/notebook/lib/steps.unit.spec.ts
  frontend/src/metabase/query_builder/components/notebook/test-utils.ts
  frontend/src/metabase/query_builder/components/notebook/types.ts
Labels: no-backport, .Team/QueryingComponents

#37297 Add `nemanjaglumac` to the Querying Components team
  .github/team.json
Labels: no-backport, .Team/QueryingComponents

#37269 Trend charts — Misc fixes and polish
  e2e/test/scenarios/visualizations-tabular/smartscalar-trend.cy.spec.js
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SettingsComponents/ComparisonPicker.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SettingsComponents/SmartScalarSettingsWidgets.styled.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SettingsComponents/StaticNumberForm.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.jsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/utils.ts
  frontend/src/metabase/visualizations/visualizations/SmartScalar/utils.unit.spec.ts
Labels: visual, .Team/DashViz

#37290 Rename `_getMLv2Query` Question method to `query`
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/src/metabase/query_builder/actions/query-updates.ts
  frontend/src/metabase/query_builder/components/AggregationPopover/AggregationPopover.jsx
  frontend/src/metabase/query_builder/components/QueryModals.tsx
  frontend/src/metabase/query_builder/components/filters/FilterPopover/FilterPopover.tsx
  frontend/src/metabase/query_builder/components/notebook/Notebook.tsx
  frontend/src/metabase/query_builder/components/notebook/lib/steps.ts
  frontend/src/metabase/query_builder/components/notebook/steps/DataStep/DataStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/test-utils.ts
  frontend/src/metabase/query_builder/components/view/QuestionFilters/FilterHeader.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/QuestionFilters/QuestionFilters.tsx
  frontend/src/metabase/query_builder/components/view/QuestionRowCount/QuestionRowCount.tsx
  frontend/src/metabase/query_builder/components/view/QuestionRowCount/QuestionRowCount.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/View.jsx
  frontend/src/metabase/query_builder/components/view/ViewHeader.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeSidebar.unit.spec.tsx
  frontend/src/metabase/querying/components/TimeseriesChrome/TimeseriesChrome.tsx
  frontend/src/metabase/querying/utils/drills/query-drill.ts
  frontend/src/metabase/visualizations/click-actions/actions/HideColumnAction/HideColumnAction.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingAddRemoveColumns/ChartSettingAddRemoveColumns.unit.spec.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/ChartSettingTableColumns.tsx
Labels: visual, no-backport, .Team/QueryingComponents

#37283 Drop the *empty* and unused security holder dependency
  package.json
  yarn.lock
Labels: dependencies, no-backport, External

#37309 Fix issue with model index search (48 backport)
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  src/metabase/api/search.clj
  test/metabase/api/search_test.clj
  test/metabase/test.clj
  test/metabase/test/util.clj
Labels: .Team/AdminWebapp

#37311 Remove empty stages when modifying the list of query columns in viz settings
  e2e/test/scenarios/custom-column/reproductions/19745-cc-nested-query-remove-expressions.cy.spec.js
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/utils.ts
Labels: visual, no-backport, .Team/QueryingComponents

#37260 Move `FilterPanel` to `metabase/querying`
  e2e/test/scenarios/custom-column/custom-column.cy.spec.js
  e2e/test/scenarios/filters/filter.cy.spec.js
  frontend/src/metabase/query_builder/components/view/QuestionFilters/FilterHeader.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/QuestionFilters/QuestionFilters.styled.tsx
  frontend/src/metabase/query_builder/components/view/QuestionFilters/QuestionFilters.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader.jsx
  frontend/src/metabase/querying/components/FilterPanel/FilterPanel.styled.tsx
  frontend/src/metabase/querying/components/FilterPanel/FilterPanel.tsx
  frontend/src/metabase/querying/components/FilterPanel/FilterPanelButton/FilterPanelButton.styled.tsx
  frontend/src/metabase/querying/components/FilterPanel/FilterPanelButton/FilterPanelButton.tsx
  frontend/src/metabase/querying/components/FilterPanel/FilterPanelButton/index.ts
  frontend/src/metabase/querying/components/FilterPanel/FilterPanelPopover/FilterPanelPopover.tsx
  frontend/src/metabase/querying/components/FilterPanel/FilterPanelPopover/index.ts
  frontend/src/metabase/querying/components/FilterPanel/FilterPill/FilterPill.styled.tsx
  frontend/src/metabase/querying/components/FilterPanel/FilterPill/FilterPill.tsx
  frontend/src/metabase/querying/components/FilterPanel/FilterPill/index.ts
  frontend/src/metabase/querying/components/FilterPanel/index.ts
  frontend/src/metabase/querying/components/FilterPanel/types.ts
  frontend/src/metabase/querying/components/FilterPanel/utils.ts
  frontend/src/metabase/querying/components/FilterPicker/FilterColumnPicker/FilterColumnPicker.tsx
  frontend/src/metabase/querying/index.ts
Labels: no-backport, .Team/QueryingComponents

#36874 show error and disable save button when create metric fails
  e2e/test/scenarios/admin/datamodel/reproductions/36422-show-create-metric-error.cy.spec.js
  frontend/src/metabase/admin/datamodel/components/MetricForm/MetricForm.tsx
  frontend/src/metabase/admin/datamodel/containers/MetricApp.jsx
  frontend/src/metabase/forms/components/FormErrorMessage/FormErrorMessage.tsx
Labels: backport, .Team/AdminWebapp

#37317 🍒 Manual Backport 2024 e2e test fixes
  e2e/test/scenarios/dashboard-cards/dashboard-drill.cy.spec.js
  e2e/test/scenarios/dashboard-filters/shared/dashboard-filters-date.js
  e2e/test/scenarios/dashboard-filters/shared/dashboard-filters-sql-date.js
Labels: was-backported

#37318 Increase Dashboard filters speed by putting field ids into set
  src/metabase/api/dashboard.clj
Labels: no-backport, .Team/AdminWebapp

#37323 docs - update list of releases
  docs/releases.md
Labels: Type:Documentation, backport

#36875 add-implicit-clauses marks refs to ignore coercion
  src/metabase/driver/sql/query_processor.clj
  src/metabase/query_processor/middleware/add_implicit_clauses.clj
  src/metabase/query_processor/util/nest_query.clj
  test/metabase/query_processor/middleware/add_implicit_clauses_test.clj
  test/metabase/query_processor/middleware/fetch_source_query_test.clj
  test/metabase/query_processor/util/nest_query_test.clj
  test/metabase/query_processor_test/alternative_date_test.clj
Labels: backport, .Team/QueryProcessor

#37284 Avoid failing call to /api/model-index
  frontend/src/metabase/entities/model-indexes/model-indexes.ts
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.unit.spec.tsx
Labels: no-backport, .Team/AdminWebapp

#37110 Drop then recreate a column should refingerprint and analyze the field
  src/metabase/sync/sync_metadata/fields/sync_metadata.clj
  test/metabase/sync/sync_metadata/fields/sync_metadata_test.clj
Labels: no-backport, .Team/BackendComponents

#37271 Serdes for DashboardCardSeries
  enterprise/backend/src/metabase_enterprise/serialization/v2/models.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/extract_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj
  src/metabase/models/dashboard.clj
  src/metabase/models/dashboard_card.clj
  src/metabase/models/dashboard_card_series.clj
  test/metabase/models/dashboard_test.clj
  test/metabase/test.clj
Labels: backport, .Team/QueryProcessor, .Team/BackendComponents

#37319 Reduce boilerplate in permissions checks
  src/metabase/api/search.clj
Labels: no-backport, .Team/BackendComponents

#37336 Update browserslist db
  yarn.lock
Labels: no-backport, .Team/QueryingComponents

#37339 Sync should log something before it fetches metadata
  src/metabase/sync/sync_metadata.clj
Labels: no-backport, .Team/BackendComponents

#37340 Migrate topLevelFilters check to MLv2
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/src/metabase/query_builder/components/view/QuestionFilters/QuestionFilters.tsx
  frontend/src/metabase/querying/components/FilterPanel/FilterPanel.tsx
  frontend/src/metabase/querying/components/FilterPanel/FilterPanelButton/FilterPanelButton.tsx
  frontend/test/metabase-lib/lib/queries/StructuredQuery-nesting.unit.spec.js
Labels: no-backport, .Team/QueryingComponents

#37370 Remove unused code from legacy query
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/test/metabase-lib/lib/queries/StructuredQuery-clean.unit.spec.js
  frontend/test/metabase-lib/lib/queries/StructuredQuery-nesting.unit.spec.js
  frontend/test/metabase-lib/lib/queries/StructuredQuery.unit.spec.js
Labels: no-backport, .Team/QueryingComponents

#37346 Use MLv2 to compute columns in parameter mapping
  enterprise/frontend/src/metabase-enterprise/sandboxes/components/EditSandboxingModal/EditSandboxingModal.unit.spec.tsx
  frontend/src/metabase-lib/parameters/utils/filters.js
  frontend/src/metabase-lib/parameters/utils/targets.ts
  frontend/src/metabase/dashboard/actions/cards.unit.spec.ts
  frontend/src/metabase/parameters/utils/mapping-options.js
  frontend/src/metabase/parameters/utils/mapping-options.unit.spec.js
Labels: no-backport, .Team/QueryingComponents

#36723 docs - add max query rows limits
  docs/configuring-metabase/environment-variables.md
Labels: Type:Documentation, backport

#37325 [MLv2] Remove unused legacy MLv2 functions
  src/metabase/lib/core.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/js.cljs
  test/metabase/lib/field_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor, no-backport

#37381 Fix collection/tree giving 500 error when there is only one user
  src/metabase/api/collection.clj
  test/metabase/api/collection_test.clj
Labels: backport, .Team/AdminWebapp

#37416 Add default sql server port to config
  modules/drivers/sqlserver/resources/metabase-plugin.yaml
Labels: backport, .Team/AdminWebapp

#37415 Fix static viz funnel chart rendering by changing row idx values
  src/metabase/pulse/render/body.clj
  test/metabase/pulse/render/body_test.clj
  test/metabase/pulse/render/test_util.clj
Labels: backport, visual, .Team/DashViz

#37298 Add environ based suggestion for db config
  docs/developers-guide/devenv.md
Labels: no-backport, .Team/BackendComponents

#37243 Make the `with-premium-features` test helper thread-safe
  enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/saml_test.clj
  src/metabase/public_settings/premium_features.clj
  test/metabase/public_settings/premium_features_test.clj
Labels: .Team/QueryProcessor, no-backport

#37375 Migrate `ViewTitleHeader` to MLv2
  frontend/src/metabase/query_builder/components/view/ViewHeader.jsx
Labels: no-backport, .Team/QueryingComponents

#37435 Flaky test fix (dashboard-drill.cy.spec)
  e2e/test/scenarios/dashboard-cards/dashboard-drill.cy.spec.js
Labels: .CI & Tests, no-backport

#37401 Remove legacyQuery from DashCardMenu
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.tsx
Labels: no-backport, .Team/QueryingComponents

#37160 Unify type of timestamp columns
  bin/lint-migrations-file/src/lint_migrations_file.clj
  bin/lint-migrations-file/test/lint_migrations_file_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/extract_test.clj
  resources/migrations/001_update_migrations.yaml
  src/metabase/db/custom_migrations.clj
  test/metabase/db/custom_migrations_test.clj
  test/metabase/db/schema_migrations_test.clj
  test/metabase/models/interface_test.clj
  test/metabase/server/middleware/auth_test.clj
  test/metabase/server/middleware/session_test.clj
Labels: no-backport, .Team/BackendComponents

#37427 Set default group perms when new ones are added
  src/metabase/models/permissions_group.clj
  src/metabase/models/permissions_v2.clj
Labels: .Team/AdminWebapp

#37302 Migrate data notebook step to MLv2
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx
  frontend/src/metabase/query_builder/components/DataSelector/data-search/utils.js
  frontend/src/metabase/query_builder/components/notebook/Notebook.tsx
  frontend/src/metabase/query_builder/components/notebook/NotebookStep/NotebookStep.tsx
  frontend/src/metabase/query_builder/components/notebook/NotebookSteps/NotebookSteps.tsx
  frontend/src/metabase/query_builder/components/notebook/lib/steps.ts
  frontend/src/metabase/query_builder/components/notebook/lib/steps.unit.spec.ts
  frontend/src/metabase/query_builder/components/notebook/steps/AggregateStep/AggregateStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/AggregateStep/AggregateStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/BreakoutStep/BreakoutStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/BreakoutStep/BreakoutStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/DataStep/DataStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/DataStep/DataStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/ExpressionStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/ExpressionStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/FilterStep/FilterStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/FilterStep/FilterStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/LimitStep/LimitStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/LimitStep/LimitStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/SortStep/SortStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/SortStep/SortStep.unit.spec.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/SummarizeStep.tsx
  frontend/src/metabase/query_builder/components/notebook/test-utils.ts
  frontend/src/metabase/query_builder/components/notebook/types.ts
Labels: no-backport, .Team/QueryingComponents

#37432 Fix CSV upload size in docs
  docs/databases/uploads.md
Labels: Type:Documentation, backport, .Team/BackendComponents

#37447 docs - fix aka
  docs/embedding/static-embedding.md
Labels: Type:Documentation, backport

#37421 Multiple Cypress Reporters
  e2e/runner/cypress-runner-run-tests.js
  e2e/support/config.js
  package.json
  yarn.lock
Labels: backport, .Team/DashViz

#37252 Migrate `databaseId`, `database` to use `databaseID` from MLv2
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase-lib/metadata/utils/models.ts
  frontend/src/metabase-lib/queries/AtomicQuery.ts
  frontend/src/metabase-lib/queries/NativeQuery.ts
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/src/metabase-lib/queries/utils/native-query-table.ts
  frontend/src/metabase-lib/queries/utils/structured-query-table.ts
  frontend/src/metabase-lib/queries/utils/structured-query-table.unit.spec.ts
  frontend/src/metabase/actions/containers/ActionCreator/ActionContext/QueryActionContextProvider/QueryActionContextProvider.tsx
  frontend/src/metabase/actions/containers/ActionCreator/ActionContext/QueryActionContextProvider/QueryActionEditor.tsx
  frontend/src/metabase/admin/datamodel/components/FilterPopover/FilterPopover.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/DataSourceSelectors/DataSourceSelectors.jsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/__mocks__/NativeQueryEditor.jsx
  frontend/src/metabase/query_builder/components/QuestionActions.tsx
  frontend/src/metabase/query_builder/components/template_tags/TagEditorSidebar.tsx
  frontend/src/metabase/query_builder/components/view/QuestionDataSelector.jsx
  frontend/src/metabase/query_builder/components/view/QuestionDataSource.jsx
  frontend/src/metabase/query_builder/components/view/QuestionDataSource.unit.spec.js
  frontend/src/metabase/query_builder/components/view/QuestionRowCount/QuestionRowCount.tsx
  frontend/src/metabase/query_builder/components/view/View.jsx
  frontend/src/metabase/query_builder/components/view/View/NewQuestionView/NewQuestionView.tsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.tsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/utils.ts
  frontend/test/metabase-lib/lib/queries/NativeQuery.unit.spec.js
  frontend/test/metabase-lib/lib/queries/StructuredQuery.unit.spec.js
Labels: visual, no-backport, .Team/QueryingComponents

#37451 Remove unused method from StructuredQuery
  frontend/src/metabase-lib/queries/StructuredQuery.ts
Labels: no-backport, .Team/QueryingComponents

#37261 Add MB_ATTACHMENT_TABLE_ROW_LIMIT to docs
  docs/configuring-metabase/environment-variables.md
Labels: Type:Documentation, no-backport

#37442 [WIP] Flaky test fix (models-metadata.cy.spec.js)
  e2e/test/scenarios/models/models-metadata.cy.spec.js
Labels: .CI & Tests, no-backport

#37444 Remove unused legacy query in QueryVisualization
  frontend/src/metabase/query_builder/components/QueryVisualization.jsx
Labels: no-backport, .Team/QueryingComponents

#37403 new utm tags for embed settings
  e2e/test/scenarios/embedding/embedding-smoketests.cy.spec.js
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/common.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/enterprise.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/premium.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingOption.tsx
Labels: .Team/Embedding

#37454 Migrate QuestionDataSelector to MLv2
  frontend/src/metabase/query_builder/components/view/QuestionDataSelector.jsx
  frontend/src/metabase/query_builder/components/view/View.jsx
  frontend/src/metabase/query_builder/components/view/View/NewQuestionView/NewQuestionView.tsx
Labels: no-backport, .Team/QueryingComponents

#37457 Migrate QuestionDescription to MLv2
  frontend/src/metabase/query_builder/components/view/QuestionDescription.jsx
Labels: no-backport

#37477 docs - clarify uploads
  docs/databases/images/upload-to-collection.png
  docs/databases/uploads.md
Labels: Type:Documentation, backport

#37471 Adding replay upload logic for crashes and ~1/10 passes
  e2e/support/config.js
Labels: no-backport, .Team/DashViz

#37411 docs - replace questions on dashboards
  docs/dashboards/images/edit.png
  docs/dashboards/images/replace-card.png
  docs/dashboards/images/visualization-settings.png
  docs/dashboards/introduction.md
Labels: Type:Documentation, no-backport

#37413 docs - updates to usage analytics
  docs/usage-and-performance-tools/images/metabase-analytics.png
  docs/usage-and-performance-tools/usage-analytics.md
Labels: Type:Documentation, backport

#37484 Update slack web api version
  release/package.json
  release/yarn.lock
Labels: backport, .Team/AdminWebapp

#37440 Rename `Question.setQuery` to `Question.setLegacyQuery`
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase-lib/queries/Query.ts
  frontend/src/metabase/actions/containers/ActionCreator/ActionContext/QueryActionContextProvider/utils.ts
  frontend/src/metabase/query_builder/actions/core/core.js
  frontend/src/metabase/query_builder/actions/core/initializeQB.ts
  frontend/src/metabase/query_builder/components/notebook/Notebook.tsx
  frontend/src/metabase/query_builder/components/notebook/NotebookStepPreview.jsx
  frontend/src/metabase/query_builder/components/notebook/NotebookSteps/NotebookSteps.tsx
  frontend/src/metabase/query_builder/components/view/QuestionDataSelector.jsx
  frontend/src/metabase/query_builder/components/view/QuestionFilters/QuestionFilters.tsx
  frontend/src/metabase/querying/components/TimeseriesChrome/TimeseriesChrome.tsx
  frontend/src/metabase/querying/utils/drills/filter-drill/filter-drill.tsx
  frontend/src/metabase/querying/utils/drills/query-drill.ts
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/ChartSettingTableColumns.tsx
  frontend/test/metabase-lib/lib/Question.unit.spec.js
Labels: visual, no-backport, .Team/QueryingComponents

#37497 Replace `ML` references with `Lib`
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase-lib/breakout.unit.spec.ts
  frontend/src/metabase-lib/order_by.unit.spec.ts
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/src/metabase-lib/query.unit.spec.ts
  frontend/src/metabase/query_builder/selectors.js
Labels: no-backport, .Team/QueryingComponents

#37522 Updating honeysql alias in dev ns (#36758)
  dev/src/dev.clj
Labels: .Team/DashViz

#37526 Fixing case of invalid graph.dimension (#37279)
  src/metabase/util/ui_logic.clj
  test/metabase/pulse/render/body_test.clj
Labels: .Team/DashViz

#37482 Adds option to skip backfill, and skips it during auditdb loading
  enterprise/backend/src/metabase_enterprise/audit_db.clj
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj
  enterprise/backend/test/metabase_enterprise/audit_db_test.clj
Labels: backport, .Team/AdminWebapp

#37521 Add :link to Lato Font for the Dashboard Subscription Preview endpoint
  src/metabase/api/pulse.clj
Labels: no-backport, .Team/DashViz

#37450 Remove getQuery selector
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetQueryEditor.jsx
  frontend/src/metabase/query_builder/components/VisualizationResult.jsx
  frontend/src/metabase/query_builder/components/view/View.jsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.jsx
  frontend/src/metabase/query_builder/selectors.js
Labels: visual, no-backport, .Team/QueryingComponents

#36621 setup rendering pipeline for echarts static waterfall
  frontend/src/metabase/static-viz/components/WaterfallChart/OldWaterfallChart.jsx
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.stories.tsx
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.tsx
  frontend/src/metabase/static-viz/components/WaterfallChart/index.js
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data.ts
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/index.ts
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/without-total.json
  frontend/src/metabase/static-viz/containers/IsomorphicStaticChart/IsomorphicStaticChart.tsx
  frontend/src/metabase/static-viz/containers/StaticChart/StaticChart.tsx
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/series.ts
  resources/frontend_shared/static_viz_interface.js
  src/metabase/pulse/render.clj
Labels: visual, .Team/DashViz

#36728 render waterfall series
  frontend/src/metabase/lib/types.ts
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.tsx
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/constants.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/option.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/types.ts
  frontend/src/metabase/visualizations/lib/graph/columns.ts
Labels: visual, .Team/DashViz

#36886 waterfall axis options
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.stories.tsx
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/index.ts
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/ordinal-x-scale.json
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/timeseries-data-as-ordinal-x-scale.json
  frontend/src/metabase/visualizations/echarts/cartesian/option/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/option.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/types.ts
Labels: visual, .Team/DashViz

#36888 handle unsorted timeseries data
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.stories.tsx
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/index.ts
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/timeseries-x-scale-unsorted.json
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/index.ts
Labels: visual, .Team/DashViz

#36925 waterfall rename 'dataset' to 'waterfallDataset'
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/option.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/types.ts
Labels: visual, .Team/DashViz

#36926 waterfall handle unaggregated data
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.stories.tsx
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/index.ts
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/unaggregated-ordinal-2.json
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/unaggregated-ordinal.json
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/unaggregated-timeseries.json
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/index.ts
Labels: visual, .Team/DashViz

#36957 waterfall color setting
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase/static-viz/components/ComboChart/settings.ts
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.stories.tsx
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.tsx
  frontend/src/metabase/static-viz/components/WaterfallChart/settings.ts
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/custom-colors.json
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/series.ts
  frontend/src/metabase/visualizations/shared/settings/waterfall.ts
Labels: visual, .Team/DashViz

#37063 waterfall data labels
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.stories.tsx
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/data-labels-column-formatting.json
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/data-labels-mixed.json
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/data-labels-timeseries.json
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/data-labels.json
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/types.ts
Labels: visual, .Team/DashViz

#37247 waterfall power y-axis scale
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.stories.tsx
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/index.ts
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/pow-y-scale-mixed.json
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/pow-y-scale-negative-only.json
  frontend/src/metabase/static-viz/components/WaterfallChart/stories-data/pow-y-scale.json
  frontend/src/metabase/visualizations/echarts/cartesian/option/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/option/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/series.ts
Labels: visual, .Team/DashViz

#37276 waterfall remove unused extent calculation
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/index.ts
Labels: visual, .Team/DashViz

#37277 waterfall use constant for empty val
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/waterfall/types.ts
Labels: visual, .Team/DashViz

#37282 remove old static waterfall code
  frontend/src/metabase/static-viz/components/WaterfallChart/OldWaterfallChart.jsx
  frontend/src/metabase/static-viz/lib/waterfall.js
  frontend/src/metabase/static-viz/lib/waterfall.unit.spec.js
Labels: visual, .Team/DashViz

#37428 Apply selective malli mu.fn enforcement for certain namespaces to improve performance
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/util/malli/defn.clj
  src/metabase/util/malli/fn.clj
  test/metabase/util/malli/defn_test.clj
  test/metabase/util/malli/fn_test.clj
Labels: backport, .Team/AdminWebapp

#37546 Don't send results works at the card level
  src/metabase/pulse.clj
  test/metabase/pulse/pulse_integration_test.clj
Labels: backport, .Team/DashViz

#37191 New permissions table schema and backend API
  enterprise/backend/src/metabase_enterprise/serialization/v2/models.clj
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  resources/migrations/001_update_migrations.yaml
  src/metabase/cmd/copy.clj
  src/metabase/models/permissions_v2.clj
  test/metabase/models/permissions_v2_test.clj
Labels: no-backport, .Team/AdminWebapp

#37518 Add TypeScript wrappers around native CLJS functions
  frontend/src/metabase-lib/native.ts
  frontend/src/metabase-lib/queries/NativeQuery.ts
Labels: no-backport, .Team/QueryingComponents

#37523 Use new docs url for quickstart link
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/common.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/enterprise.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/premium.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingOption.tsx
Labels: .Team/Embedding

#37313 Validate json settings during init (#36182)
  src/metabase/core.clj
  src/metabase/models/permissions.clj
  src/metabase/models/setting.clj
  src/metabase/sync/analyze/classifiers/name.clj
  test/metabase/models/setting_test.clj
Labels: backport, .Team/BackendComponents

#37495 collections in 'analytics' namespace should not be extracted
  enterprise/backend/src/metabase_enterprise/serialization/v2/extract.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/extract_test.clj
Labels: backport, .Team/BackendComponents

#37530 docs - fix link title
  docs/README.md
Labels: Type:Documentation, backport

#37503 fix serialization when there is a slash in click_behavior id
  enterprise/backend/test/metabase_enterprise/serialization/v2/extract_test.clj
  src/metabase/models/serialization.clj
Labels: backport, .Team/BackendComponents

#37550 make fn-name consistent between mu/defn and mu.fn/fn
  src/metabase/util/malli/defn.clj
  test/metabase/util/malli/defn_test.clj
Labels: backport, .Team/AdminWebapp

#37568 Fix segmented control and menu colors
  frontend/src/metabase/ui/components/inputs/SegmentedControl/SegmentedControl.styled.tsx
  frontend/src/metabase/ui/components/overlays/Menu/Menu.styled.tsx
Labels: no-backport, .Team/QueryingComponents

#37481 Unwrap value expressions when converting to legacy expression
  src/metabase/lib/js.cljs
  test/metabase/lib/js_test.cljs
Labels: .metabase-lib, .Team/QueryProcessor, no-backport

#37567 Remove `isEmpty` method in `StructuredQuery`
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx
  frontend/test/metabase-lib/lib/queries/StructuredQuery.unit.spec.js
Labels: no-backport, .Team/QueryingComponents

#37430 Embedding settings cleanup - Milestone 2
  e2e/test/scenarios/embedding/embedding-smoketests.cy.spec.js
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/common.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/enterprise.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/premium.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingOption.tsx
Labels: no-backport

#37582 Increase the request timeout for instance-analytics
  e2e/test/scenarios/collections/instance-analytics.cy.spec.js
Labels: .CI & Tests, flaky-test-fix, no-backport

#37099 API Keys: Handle Groups UI
  e2e/support/helpers/e2e-api-key-helpers.ts
  e2e/support/helpers/index.js
  e2e/test/scenarios/admin-2/api-keys.cy.spec.ts
  e2e/test/scenarios/admin-2/people/group-managers.cy.spec.js
  e2e/test/scenarios/admin-2/people/people.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/group_managers/components/UserTypeCell/UserTypeCell.styled.tsx
  frontend/src/metabase/admin/people/components/GroupMembersTable/GroupMembersTable.tsx
  frontend/src/metabase/admin/people/components/GroupsListing.jsx
  frontend/src/metabase/components/AdminPaneLayout/AdminPaneLayout.jsx
  frontend/src/metabase/components/LeftNavPane/LeftNavPane.jsx
Labels: no-backport, .Team/AdminWebapp

#37445 docs - api update
  docs/api-documentation.md
  docs/api/api-key.md
  docs/api/collection.md
  docs/api/field.md
  docs/api/permissions.md
  docs/api/pulse.md
  docs/api/table.md
  src/metabase/cmd/endpoint_dox.clj
Labels: Type:Documentation, no-backport

#37466 Truncate tooltip content for table items with large descriptions
  frontend/src/metabase/collections/components/BaseTableItem.jsx
  frontend/src/metabase/core/components/Markdown/Markdown.styled.tsx
  frontend/src/metabase/core/components/Markdown/Markdown.tsx
  frontend/src/metabase/core/components/MarkdownPreview/MarkdownPreview.styled.tsx
  frontend/src/metabase/core/components/MarkdownPreview/MarkdownPreview.tsx
  frontend/src/metabase/core/components/Tooltip/index.ts
  frontend/src/metabase/visualizations/components/legend/LegendCaption.jsx
Labels: backport, visual, .Team/QueryingComponents

#37469 Add advanced option for quoting the database name
  modules/drivers/snowflake/resources/metabase-plugin.yaml
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
Labels: Database/Snowflake, .Backend, backport, .Team/QueryProcessor

#37592 Don't send results works at the card level (#37546)
  src/metabase/pulse.clj
  test/metabase/pulse/pulse_integration_test.clj
Labels: .Team/DashViz
