Repository metabase/metabase, pull requests merged in 2024-02, with the labels that each got.

#38306 Upgrade `actions/upload-artifact` and `actions/download-artifact` action to v4
  .github/actions/prepare-uberjar-artifact/action.yml
  .github/workflows/backend.yml
  .github/workflows/build-for-release.yml
  .github/workflows/e2e-cross-version.yml
  .github/workflows/e2e-stress-test-flake-fix.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  .github/workflows/uberjar.yml
Labels: no-backport, .Team/QueryingComponents

#38334 Upgrade `aws-actions/configure-aws-credentials` action to v4
  .github/actions/upload-test-results/action.yml
  .github/workflows/release.yml
  .github/workflows/set-announce-url.yml
Labels: no-backport, .Team/QueryingComponents

#38136 [QC] Clean up `isStructured` (v1) utilities
  frontend/src/metabase-lib/metadata/utils/models.ts
  frontend/src/metabase-lib/queries/utils/card.js
  frontend/src/metabase-lib/queries/utils/index.js
  frontend/src/metabase/services.js
  frontend/src/metabase/visualizations/lib/LineAreaBarRenderer.js
  frontend/src/metabase/visualizations/lib/renderer_utils.js
  frontend/src/metabase/visualizations/visualizations/Table.tsx
Labels: visual, no-backport, .Team/QueryingComponents

#38331 Upgrade `actions/setup-node` action to v4
  .github/actions/prepare-frontend/action.yml
  .github/workflows/build-for-release.yml
  .github/workflows/rerun-workflows.yml
Labels: no-backport, .Team/QueryingComponents

#38335 Upgrade `actions/cache` action to v4
  .github/actions/prepare-backend/action.yml
  .github/actions/prepare-cypress/action.yml
  .github/actions/prepare-frontend/action.yml
Labels: no-backport, .Team/QueryingComponents

#38332 Upgrade `actions/setup-java` action to v4
  .github/actions/prepare-backend/action.yml
  .github/workflows/build-for-release.yml
  .github/workflows/e2e-stress-test-flake-fix.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/pre-release.yml
  .github/workflows/uberjar.yml
Labels: no-backport, .Team/QueryingComponents

#38249 Add repro for handling not saved dashcards with mapped filters and tabs
  e2e/support/helpers/e2e-misc-helpers.js
  e2e/test/scenarios/dashboard-filters/reproductions/38245-negative-dashcard-id-switching-tabs.cy.spec.js
Labels: support/Repro, no-backport, .Team/QueryingComponents

#38257 Speculative fix for migration on multi instances
  src/metabase/db/liquibase.clj
  src/metabase/db/setup.clj
  test/metabase/db/liquibase_test.clj
Labels: backport, .Team/BackendComponents

#38318 Update migrating-from-h2.md so Postgres version is 9.5
  docs/installation-and-operation/migrating-from-h2.md
Labels: backport

#38351 deprecate trackStructEvent to avoid confusion
  frontend/src/metabase/lib/analytics.js
Labels: no-backport, .Team/Embedding

#38321 Fix issue where reverted question does not use parameter values
  e2e/test/scenarios/question/reproductions/38176-revert-to-previous-does-not-honor-parameters.cy.spec.js
  frontend/src/metabase/query_builder/actions/core/core.js
Labels: backport, .Team/QueryingComponents

#37220 CSV appends: Milestone 0, Merge 2 of 2: upload through model page
  e2e/test/scenarios/collections/uploads.cy.spec.js
  enterprise/backend/test/metabase_enterprise/upload_test.clj
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase-types/api/mocks/card.ts
  frontend/src/metabase-types/store/upload.ts
  frontend/src/metabase/collections/components/CollectionHeader/CollectionHeader.tsx
  frontend/src/metabase/collections/components/CollectionHeader/CollectionUpload.tsx
  frontend/src/metabase/collections/containers/CollectionContent.jsx
  frontend/src/metabase/lib/api.js
  frontend/src/metabase/query_builder/components/QuestionActions.tsx
  frontend/src/metabase/query_builder/selectors.js
  frontend/src/metabase/redux/uploads.ts
  frontend/src/metabase/redux/uploads.unit.spec.js
  frontend/src/metabase/services.js
  frontend/src/metabase/status/components/FileUploadStatus/FileUploadStatus.tsx
  frontend/src/metabase/status/components/FileUploadStatus/FileUploadStatus.unit.spec.tsx
  frontend/src/metabase/status/components/FileUploadStatusLarge/FileUploadErrorModal.tsx
  frontend/src/metabase/status/components/FileUploadStatusLarge/FileUploadStatusLarge.stories.tsx
  frontend/src/metabase/status/components/FileUploadStatusLarge/FileUploadStatusLarge.tsx
  frontend/src/metabase/status/components/StatusLarge/StatusLarge.styled.tsx
  frontend/src/metabase/status/components/StatusLarge/StatusLarge.tsx
  frontend/src/metabase/status/components/StatusListing/StatusListing.tsx
  src/metabase/api/card.clj
  src/metabase/upload.clj
  test/metabase/api/card_test.clj
Labels: no-backport, .Team/BackendComponents

#38369 docs - add redshift to impersonation db list
  docs/permissions/data.md
Labels: Type:Documentation, backport

#38247 Fixed width dashboard migration
  resources/migrations/001_update_migrations.yaml
  src/metabase/api/dashboard.clj
  src/metabase/models/revision/diff.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/events/revision_test.clj
  test/metabase/models/dashboard_test.clj
Labels: no-backport, .Team/DashViz

#38375 [MLv2] Cache JS -> CLJS metadata conversion
  src/metabase/lib/cache.cljc
  src/metabase/lib/js/metadata.cljs
Labels: .Team/QueryProcessor, no-backport

#38210 [MLv2] New "canned" queries and clicks for drill-thru testing
  test/metabase/lib/drill_thru/automatic_insights_test.cljc
  test/metabase/lib/drill_thru/column_filter_test.cljc
  test/metabase/lib/drill_thru/distribution_test.cljc
  test/metabase/lib/drill_thru/fk_details_test.cljc
  test/metabase/lib/drill_thru/pivot_test.cljc
  test/metabase/lib/drill_thru/pk_test.cljc
  test/metabase/lib/drill_thru/quick_filter_test.cljc
  test/metabase/lib/drill_thru/sort_test.cljc
  test/metabase/lib/drill_thru/summarize_column_by_time_test.cljc
  test/metabase/lib/drill_thru/summarize_column_test.cljc
  test/metabase/lib/drill_thru/test_util/canned.cljc
  test/metabase/lib/drill_thru/zoom_test.cljc
  test/metabase/lib/test_metadata.cljc
Labels: .Backend, .Team/QueryProcessor, no-backport

#38344 Display full-dates for trend charts backed by native queries
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.unit.spec.js
  frontend/src/metabase/visualizations/visualizations/SmartScalar/compute.js
  frontend/src/metabase/visualizations/visualizations/SmartScalar/compute.unit.spec.js
Labels: backport, visual, .Team/DashViz

#38128 Evaluate all defsetting arguments at runtime
  src/metabase/models/setting.clj
  test/metabase/models/setting_test.clj
Labels: backport, .Team/BackendComponents

#37693 Migrate syncStructuredQueryColumnsAndSettings to MLv2
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/test/metabase/lib/dataset.unit.spec.js
Labels: no-backport, .Team/QueryingComponents

#38267 Usage reason question
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.js
  frontend/src/metabase-types/api/setup.ts
  frontend/src/metabase-types/store/setup.ts
  frontend/src/metabase/setup/actions.ts
  frontend/src/metabase/setup/components/DatabaseStep/DatabaseStep.tsx
  frontend/src/metabase/setup/components/InactiveStep/InactiveStep.styled.tsx
  frontend/src/metabase/setup/components/InactiveStep/InactiveStep.tsx
  frontend/src/metabase/setup/components/InactiveStep/index.ts
  frontend/src/metabase/setup/components/LanguageStep/LanguageStep.tsx
  frontend/src/metabase/setup/components/PreferencesStep/PreferencesStep.tsx
  frontend/src/metabase/setup/components/SettingsPage/SettingsPage.tsx
  frontend/src/metabase/setup/components/UsageQuestionStep/UsageQuestionStep.tsx
  frontend/src/metabase/setup/components/UsageQuestionStep/index.ts
  frontend/src/metabase/setup/components/UserStep/UserStep.tsx
  frontend/src/metabase/setup/constants.ts
  frontend/src/metabase/setup/reducers.ts
Labels: .Team/Embedding

#38382 Revert redshift change to docs
  docs/permissions/data.md
Labels: Type:Documentation, backport

#38317 docs - clarify collection perms
  docs/permissions/collections.md
  docs/permissions/images/dashboard-no-permissions.png
Labels: Type:Documentation, backport

#38366 [CI] Upgrade `actions/github-script` action to v7
  .github/actions/build-e2e-matrix/action.yml
  .github/actions/e2e-download-uberjar/action.yml
  .github/actions/get-latest-release-branch/action.yml
  .github/actions/notify-pull-request/action.yml
  .github/workflows/auto-assign.yml
  .github/workflows/backport.yml
  .github/workflows/bugs-triage-slack-notification.yml
  .github/workflows/build-for-release.yml
  .github/workflows/check-milestone.yml
  .github/workflows/escalation-slack-notification.yml
  .github/workflows/pre-release.yml
  .github/workflows/pull-request-reminders.yml
  .github/workflows/release-status.yml
  .github/workflows/release.yml
  .github/workflows/require-percy-tests.yml
  .github/workflows/rerun-workflows.yml
  .github/workflows/set-announce-url.yml
  .github/workflows/team-issues-slack-notification.yml
Labels: no-backport, .Team/QueryingComponents

#38367 Upgrade `dorny/paths-filter` action to v3.0.0
  .github/workflows/backend.yml
  .github/workflows/chromatic.yml
  .github/workflows/cljs.yml
  .github/workflows/codeql.yml
  .github/workflows/drivers.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/frontend.yml
  .github/workflows/i18n.yml
  .github/workflows/presto-kerberos-integration-test.yml
  .github/workflows/require-percy-tests.yml
  .github/workflows/snowplow.yml
  .github/workflows/yaml.yml
Labels: no-backport

#38387 Repro #38354 - Not able to switch between databases after a question is created
  e2e/test/scenarios/question/reproductions/38354-changing-source-database.cy.spec.js
Labels: support/Repro, no-backport, .Team/QueryingComponents

#38386 Fix - Not able to switch between databases after a question is created
  e2e/test/scenarios/question/reproductions/38454-changing-source-database.cy.spec.js
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx
  frontend/src/metabase/query_builder/components/notebook/steps/DataStep/DataStep.tsx
Labels: no-backport, .Team/QueryingComponents

#38275 [MLv2] Fix some edge cases and add more unit tests for zoom in drills
  src/metabase/lib/drill_thru/zoom.cljc
  test/metabase/lib/drill_thru/test_util/canned.cljc
  test/metabase/lib/drill_thru/zoom_in_bins_test.cljc
  test/metabase/lib/drill_thru/zoom_in_geographic_test.cljc
  test/metabase/lib/drill_thru/zoom_in_timeseries_test.cljc
Labels: .Team/QueryProcessor, no-backport

#38388 Update fieldvalues in a transaction
  src/metabase/api/field.clj
Labels: backport, .Team/BackendComponents

#38295 [MLv2] Drill-thru coverage: Add a structured column and fix that case
  src/metabase/lib/drill_thru/quick_filter.cljc
  test/metabase/lib/drill_thru/automatic_insights_test.cljc
  test/metabase/lib/drill_thru/column_filter_test.cljc
  test/metabase/lib/drill_thru/distribution_test.cljc
  test/metabase/lib/drill_thru/fk_details_test.cljc
  test/metabase/lib/drill_thru/pivot_test.cljc
  test/metabase/lib/drill_thru/pk_test.cljc
  test/metabase/lib/drill_thru/quick_filter_test.cljc
  test/metabase/lib/drill_thru/sort_test.cljc
  test/metabase/lib/drill_thru/summarize_column_by_time_test.cljc
  test/metabase/lib/drill_thru/summarize_column_test.cljc
  test/metabase/lib/drill_thru/test_util/canned.cljc
  test/metabase/lib/drill_thru/underlying_records_test.cljc
  test/metabase/lib/drill_thru/zoom_test.cljc
Labels: .Team/QueryProcessor, no-backport

#38380 Sort drill should remove ALL existing order bys
  src/metabase/lib/drill_thru/sort.cljc
  src/metabase/lib/order_by.cljc
  test/metabase/lib/drill_thru/sort_test.cljc
  test/metabase/lib/order_by_test.cljc
Labels: .Team/QueryProcessor, no-backport

#38088 Allow :base to be a map of inherited options for defsetting
  src/metabase/analytics/snowplow.clj
  src/metabase/models/setting.clj
  src/metabase/public_settings.clj
  test/metabase/cmd/env_var_dox_test.clj
  test/metabase/models/setting_test.clj
Labels: backport, .Team/BackendComponents

#38054 Make the MLv2 display-name include the path of nested fields
  src/metabase/lib/breakout.cljc
  src/metabase/lib/field.cljc
  test/metabase/lib/field_test.cljc
Labels: .Backend, backport, visual, .metabase-lib, .Team/QueryProcessor

#38378 Return card__<id> for non-model cards and FK targets for tables
  src/metabase/lib/fe_util.cljc
  test/metabase/lib/fe_util_test.cljc
Labels: .Team/QueryProcessor, no-backport

#38409 [MLv2] Add caching for the common case of visible-columns w/o options
  src/metabase/lib/metadata/calculation.cljc
Labels: no-backport

#38408 add snowplow event tracking for card and tab duplication
  e2e/test/scenarios/dashboard-cards/duplicate-dashcards-tabs.cy.spec.js
  frontend/src/metabase/dashboard/analytics.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/use-duplicate-dashcard.ts
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeaderView.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/use-dashboard-tabs.ts
  snowplow/iglu-client-embedded/schemas/com.metabase/dashboard/jsonschema/1-1-3
Labels: no-backport, .Team/DashViz

#38194 docs - update api docs script
  docs/api-documentation.md
  docs/api/collection.md
  docs/api/ee/serialization.md
  src/metabase/api/common/internal.clj
  src/metabase/cmd/endpoint_dox.clj
Labels: no-backport

#38411 add dashcard replace event to snowplow schema and e2e test
  e2e/test/scenarios/dashboard-cards/dashcard-replace-question.cy.spec.js
  snowplow/iglu-client-embedded/schemas/com.metabase/dashboard/jsonschema/1-1-3
Labels: no-backport, .Team/DashViz

#38414 Upload random replays from master only
  e2e/support/config.js
Labels: backport, .Team/DashViz

#38379 Fixing static-viz exports of saved x-ray dashboards
  src/metabase/automagic_dashboards/combination.clj
  src/metabase/automagic_dashboards/populate.clj
  src/metabase/lib/convert.cljc
  test/metabase/pulse/pulse_integration_test.clj
Labels: backport, .Team/DashViz

#38328 Move `canExploreResults` out of the Question prototype
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase/query_builder/components/view/ViewHeader.jsx
  frontend/src/metabase/query_builder/components/view/ViewHeaderUtils.js
  frontend/src/metabase/query_builder/components/view/ViewHeaderUtils.unit.spec.js
Labels: no-backport, :broom:, .Team/QueryingComponents

#38421 Organize `ViewHeader` component and its related files
  frontend/src/metabase/query_builder/components/view/ConvertQueryButton/index.ts
  frontend/src/metabase/query_builder/components/view/ViewHeader/ViewHeader.jsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/ViewHeader.styled.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/ViewHeader.unit.spec.js
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/ConvertQueryButton/ConvertQueryButton.styled.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/ConvertQueryButton/ConvertQueryButton.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/ConvertQueryButton/index.ts
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/ExploreResultsLink.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/FilterHeaderButton.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/HeaderBreadcrumbs/HeaderBreadcrumbs.jsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/HeaderBreadcrumbs/HeaderBreadcrumbs.styled.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/HeaderBreadcrumbs/index.js
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionActions/QuestionActions.styled.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionActions/QuestionActions.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionActions/QuestionActions.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionActions/index.ts
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/QuestionDataSource.jsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/QuestionDataSource.styled.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/QuestionDataSource.unit.spec.js
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/index.ts
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDescription/QuestionDescription.jsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDescription/QuestionDescription.styled.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDescription/index.ts
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionFilters/FilterHeader.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionFilters/QuestionFilters.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionFilters/index.ts
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionNotebookButton/QuestionNotebookButton.jsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionNotebookButton/QuestionNotebookButton.styled.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionNotebookButton/index.ts
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionSummarizeWidget.jsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/index.ts
  frontend/src/metabase/query_builder/components/view/ViewHeader/index.ts
  frontend/src/metabase/query_builder/components/view/ViewHeader/utils.ts
  frontend/src/metabase/query_builder/components/view/ViewHeader/utils.unit.spec.ts
Labels: no-backport, .Team/QueryingComponents

#38427 [Dashboard] Drop unused selector
  frontend/src/metabase/dashboard/selectors.ts
Labels: no-backport, .Team/QueryingComponents

#38045 Add Hebrew Language Support
  locales/he.po
  resources/locales.clj
Labels: Customization/i18n, backport, .Team/AdminWebapp

#38322 BE: add `based_on_upload` to `GET /api/collections/:collection/items` response
  enterprise/backend/test/metabase_enterprise/upload_test.clj
  src/metabase/api/collection.clj
  src/metabase/lib/core.cljc
  src/metabase/upload.clj
  test/metabase/api/card_test.clj
  test/metabase/api/collection_test.clj
Labels: no-backport, .Team/BackendComponents

#38368 Hide unmapped filters for public/embedded dashboards
  e2e/support/commands/api/composite/createNativeQuestionAndDashboard.js
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  e2e/test/scenarios/embedding/embedding-dashboard.cy.spec.js
  e2e/test/scenarios/embedding/shared/embedding-dashboard.js
  e2e/test/scenarios/sharing/public-dashboard.cy.spec.js
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.tsx
  frontend/src/metabase/public/containers/PublicDashboard.jsx
Labels: no-backport, .Team/DashViz

#38296 [MLv2] fk-details drill should preserve `:=` filters for other PKs
  src/metabase/lib/drill_thru/fk_details.cljc
  test/metabase/lib/drill_thru/fk_details_test.cljc
Labels: .Team/QueryProcessor, no-backport

#38448 Adding nil-safe code in model-hydrate-based-on-upload
  src/metabase/upload.clj
Labels: no-backport, .Team/DashViz

#38440 Fix hover cursor is always crosshair instead of pointer on brushable charts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/CartesianChart.tsx
Labels: visual, .Team/DashViz

#38438 Fix missing tooltip on line and area charts when the symbol is hidden
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
Labels: visual, .Team/DashViz

#38441 Adding geographic coordinate formatting to exports
  src/metabase/formatter.clj
  src/metabase/query_processor/streaming/xlsx.clj
  test/metabase/formatter_test.clj
  test/metabase/pulse/pulse_integration_test.clj
  test/metabase/pulse/render/body_test.clj
  test/metabase/query_processor/streaming/csv_test.clj
  test/metabase/query_processor/streaming/json_test.clj
  test/metabase/query_processor/streaming/xlsx_test.clj
  test/metabase/query_processor/streaming_test.clj
Labels: no-backport, .Team/DashViz

#38357 FE - Temporarily mock metrics CRUD endpoints
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase/entities/questions.js
Labels: no-backport, .Team/QueryingComponents

#38221 [MLv2] [FE] Migrate `setDefaultDisplay` to MLv2
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase-lib/aggregation.ts
  frontend/src/metabase-lib/breakout.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase-lib/v2.ts
  frontend/src/metabase-lib/viz/display.ts
  frontend/src/metabase-lib/viz/display.unit.spec.ts
  frontend/src/metabase-lib/viz/index.ts
Labels: no-backport, .Team/QueryingComponents

#38390 Hide "Add your data" step for people interested in embedding
  frontend/src/metabase/setup/components/ActiveStep/ActiveStep.tsx
  frontend/src/metabase/setup/components/InactiveStep/InactiveStep.tsx
  frontend/src/metabase/setup/components/SettingsPage/SettingsPage.tsx
  frontend/src/metabase/setup/reducers.ts
  frontend/src/metabase/setup/selectors.ts
  frontend/src/metabase/setup/setup.unit.spec.tsx
Labels: .Team/Embedding

#38459 [QC] Remove unused `newQuestionFlow` function
  frontend/src/metabase/lib/urls/questions.ts
Labels: no-backport, :broom:, .Team/QueryingComponents

#38453 Make upload tests faster with with-uploads-table macro
  .clj-kondo/config.edn
  test/metabase/upload_test.clj
Labels: .Team/BackendComponents

#37505 Fix redshift not supporting uploads
  .clj-kondo/config.edn
  docs/developers-guide/driver-changelog.md
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  src/metabase/driver.clj
  src/metabase/driver/h2.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql_jdbc.clj
  src/metabase/upload.clj
  test/metabase/upload_test.clj
Labels: backport, .Team/BackendComponents

#38442 deserialization should happen inside a transaction
  enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj
Labels: no-backport, .Team/BackendComponents

#38451 docs - duplicate dashboard card
  docs/dashboards/images/duplicate-card.png
  docs/dashboards/images/replace-card.png
  docs/dashboards/introduction.md
Labels: Type:Documentation, no-backport

#38376 docs - update list of releases
  docs/releases.md
Labels: Type:Documentation, backport

#38452 Use constant x-axis dataKey and fix dataset unit specs
  frontend/src/metabase/visualizations/echarts/cartesian/constants/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.unit.spec.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/types.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/trend-line.ts
  frontend/src/metabase/visualizations/echarts/cartesian/scatter/model.ts
  frontend/src/metabase/visualizations/echarts/cartesian/scatter/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/timeline-events/model.ts
  frontend/src/metabase/visualizations/echarts/cartesian/utils/layout.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/events.ts
Labels: visual, .Team/DashViz

#38480 docs - update release list 48.5
  docs/releases.md
Labels: Type:Documentation, backport

#38413 Implement equality for MLv2 MetadataProviders
  src/metabase/lib/metadata/cached_provider.cljc
  src/metabase/lib/metadata/composed_provider.cljc
  src/metabase/lib/metadata/jvm.clj
  test/metabase/lib/metadata/cached_provider_test.cljc
  test/metabase/lib/metadata/composed_provider_test.cljc
  test/metabase/lib/metadata/jvm_test.clj
  test/metabase/lib/test_metadata/graph_provider.cljc
  test/metabase/lib/test_util/metadata_providers/mock.cljc
Labels: .Team/QueryProcessor, no-backport

#38049 docs - update release list header
  bin/release-list/resources/releases-template.md
  docs/releases.md
Labels: Type:Documentation, backport

#38456 Add internal setting for table render row limit (#36996)
  src/metabase/models/setting.clj
  src/metabase/public_settings.clj
  src/metabase/pulse/render/body.clj
  test/metabase/models/setting_test.clj
  test/metabase/pulse/render/body_test.clj
  test/metabase/pulse/render/table_test.clj
  test/metabase/pulse/render/test_util.clj
  test/metabase/pulse_test.clj
Labels: visual, .Team/DashViz

#38361 [Dashboard] Do not update dashboard settings on every keypress in Heading
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.tsx
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.unit.spec.tsx
  frontend/src/metabase/visualizations/visualizations/Text/Text.unit.spec.tsx
Labels: visual, no-backport, .Team/QueryingComponents

#38337 Implement filtering cards by segment or metric ID
  src/metabase/api/card.clj
  src/metabase/lib/core.cljc
  src/metabase/lib/query.cljc
  test/metabase/api/card_test.clj
  test/metabase/lib/metric_test.cljc
  test/metabase/lib/segment_test.cljc
Labels: .Team/QueryProcessor, no-backport

#38458 Fix ESlint rules
  .eslintrc
  e2e/.eslintrc
  e2e/test/scenarios/dashboard/reproductions/12578-prevent-fetching-slow-cards-more-than-one-at-a-time-when-auto-refreshing.cy.spec.js
  e2e/test/scenarios/embedding/embedding-snippets.cy.spec.js
  e2e/test/scenarios/sharing/alert/email-alert.cy.spec.js
  frontend/src/metabase/components/tree/TreeNodeList.tsx
  frontend/src/metabase/core/components/Select/Select.tsx
  frontend/src/metabase/dashboard/components/PublicLinkPopover/PublicLinkCopyPanel.styled.tsx
  frontend/src/metabase/lib/settings.ts
  frontend/src/metabase/query_builder/components/view/ConvertQueryModal/ConvertQueryModal.tsx
  frontend/src/metabase/static-viz/components/XYChart/XYChart.tsx
  frontend/src/metabase/static-viz/components/XYChart/shapes/AreaSeries.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/utils.unit.spec.ts
  frontend/src/metabase/visualizations/visualizations/RowChart/utils/events.ts
  frontend/src/types/emotion.d.ts
  package.json
  yarn.lock
Labels: backport, visual, .Team/Embedding

#38478 Update running-metabase-on-elastic-beanstalk.md
  docs/installation-and-operation/running-metabase-on-elastic-beanstalk.md
Labels: backport

#38504 [QC] Remove unused metabase-lib (v1) utilities
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/src/metabase-lib/queries/utils/aggregation.js
  frontend/src/metabase-lib/queries/utils/expression.js
  frontend/src/metabase-lib/queries/utils/filter.js
  frontend/src/metabase-lib/queries/utils/query.js
  frontend/test/metabase-lib/lib/queries/StructuredQuery.unit.spec.js
  frontend/test/metabase/lib/query/query.unit.spec.js
Labels: no-backport, :broom:, .Team/QueryingComponents

#38444 Clean up dashboard card types
  frontend/src/metabase-lib/parameters/utils/click-behavior.ts
  frontend/src/metabase-types/api/actions.ts
  frontend/src/metabase-types/api/dashboard.ts
  frontend/src/metabase-types/api/mocks/dashboard.ts
  frontend/src/metabase-types/store/dashboard.ts
  frontend/src/metabase/actions/utils.ts
  frontend/src/metabase/dashboard/actions/auto-wire-parameters/actions.ts
  frontend/src/metabase/dashboard/actions/auto-wire-parameters/toasts.ts
  frontend/src/metabase/dashboard/actions/auto-wire-parameters/utils.ts
  frontend/src/metabase/dashboard/actions/cards.unit.spec.ts
  frontend/src/metabase/dashboard/actions/tabs.ts
  frontend/src/metabase/dashboard/actions/utils.ts
  frontend/src/metabase/dashboard/actions/utils.unit.spec.ts
  frontend/src/metabase/dashboard/components/AddSeriesModal/AddSeriesModal.tsx
  frontend/src/metabase/dashboard/components/AddSeriesModal/QuestionList.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/ClickBehaviorSidebar.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/ClickBehaviorSidebarContent.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/ClickBehaviorSidebarHeader/ClickBehaviorSidebarHeader.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/ClickBehaviorSidebarMainView/ClickBehaviorSidebarMainView.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/CrossfilterOptions.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/LinkOptions/CustomURLPicker.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/LinkOptions/LinkOptions.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/LinkOptions/LinkedEntityPicker/LinkedEntityPicker.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/TableClickBehaviorView/TableClickBehaviorView.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/TypeSelector/TypeSelector.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/hooks.ts
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/utils.ts
  frontend/src/metabase/dashboard/components/DashCard/ClickBehaviorSidebarOverlay/ClickBehaviorSidebarOverlay.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/LinkCardEditButton/LinkCardEditButton.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/use-duplicate-dashcard.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/dashboard/components/DashCard/utils.ts
  frontend/src/metabase/dashboard/components/DashboardGrid.tsx
  frontend/src/metabase/dashboard/selectors.ts
  frontend/src/metabase/dashboard/selectors.unit.spec.js
  frontend/src/metabase/dashboard/utils.ts
  frontend/src/metabase/dashboard/utils.unit.spec.ts
  frontend/src/metabase/parameters/utils/dashboards.ts
  frontend/src/metabase/parameters/utils/mapping-options.js
  frontend/src/metabase/visualizations/components/ObjectDetail/types.ts
  frontend/src/metabase/visualizations/index.ts
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.tsx
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.unit.spec.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx
Labels: visual, no-backport, .Team/DashViz

#38508 [QC] Remove unused `clean` method from the `StructuredQuery` prototype
  frontend/src/metabase-lib/queries/NativeQuery.ts
  frontend/src/metabase-lib/queries/Query.ts
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/src/metabase-lib/queries/structured/Aggregation.ts
  frontend/test/metabase-lib/lib/queries/NativeQuery.unit.spec.js
  frontend/test/metabase-lib/lib/queries/StructuredQuery-clean.unit.spec.js
Labels: no-backport, :broom:, .Team/QueryingComponents

#38404 [Metrics v2] Add "Metric" to the new entity menu
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase/components/NewItemMenu/NewItemMenu.tsx
  frontend/src/metabase/lib/urls/questions.ts
  frontend/src/metabase/routes.jsx
Labels: .Team/QueryingComponents

#38514 Auto focus search input in question picker modal
  frontend/src/metabase/dashboard/components/QuestionPicker/QuestionPicker.jsx
Labels: no-backport, .Team/DashViz

#38402 adds minimal embed focused homepage
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.js
  frontend/src/metabase/home/components/EmbedMinimalHomepage/EmbedMinimalHomepage.styled.tsx
  frontend/src/metabase/home/components/EmbedMinimalHomepage/EmbedMinimalHomepage.tsx
  frontend/src/metabase/home/components/EmbedMinimalHomepage/index.ts
  frontend/src/metabase/home/components/HomeContent/HomeContent.tsx
  frontend/src/metabase/home/utils.ts
  frontend/src/metabase/setup/actions.ts
  frontend/src/metabase/setup/setup.unit.spec.tsx
Labels: .Team/Embedding

#38433 Migrate info hover card to mantine
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/visualizations-tabular/table.cy.spec.js
  frontend/src/metabase/components/MetadataInfo/FieldInfo/FieldInfo.tsx
  frontend/src/metabase/components/MetadataInfo/FieldInfoPopover/FieldInfoPopover.styled.tsx
  frontend/src/metabase/components/MetadataInfo/FieldInfoPopover/FieldInfoPopover.tsx
  frontend/src/metabase/query_builder/components/dataref/FieldPane.tsx
  frontend/src/metabase/ui/components/overlays/HoverCard/HoverCard.stories.mdx
  frontend/src/metabase/ui/components/overlays/HoverCard/HoverCard.styled.tsx
  frontend/src/metabase/ui/components/overlays/HoverCard/index.tsx
  frontend/src/metabase/ui/components/overlays/index.ts
  frontend/src/metabase/ui/components/utils/DelayGroup/DelayGroup.tsx
  frontend/src/metabase/ui/components/utils/DelayGroup/DelayGroup.unit.spec.tsx
  frontend/src/metabase/ui/components/utils/DelayGroup/index.tsx
  frontend/src/metabase/ui/components/utils/index.ts
  frontend/src/metabase/ui/theme.ts
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx
Labels: visual, no-backport, .Team/QueryingComponents

#38465 refactor and tests for [meet embedders]
  frontend/src/metabase-types/store/mocks/setup.ts
  frontend/src/metabase-types/store/setup.ts
  frontend/src/metabase/setup/actions.ts
  frontend/src/metabase/setup/analytics.ts
  frontend/src/metabase/setup/components/CloudMigrationHelp/CloudMigrationHelp.tsx
  frontend/src/metabase/setup/components/CompletedStep/CompletedStep.tsx
  frontend/src/metabase/setup/components/CompletedStep/CompletedStep.unit.spec.tsx
  frontend/src/metabase/setup/components/DatabaseHelp/DatabaseHelp.tsx
  frontend/src/metabase/setup/components/DatabaseStep/DatabaseStep.tsx
  frontend/src/metabase/setup/components/DatabaseStep/DatabaseStep.unit.spec.tsx
  frontend/src/metabase/setup/components/LanguageStep/LanguageStep.tsx
  frontend/src/metabase/setup/components/LanguageStep/LanguageStep.unit.spec.tsx
  frontend/src/metabase/setup/components/PreferencesStep/PreferencesStep.tsx
  frontend/src/metabase/setup/components/PreferencesStep/PreferencesStep.unit.spec.tsx
  frontend/src/metabase/setup/components/SettingsPage/SettingsPage.tsx
  frontend/src/metabase/setup/components/Setup/Setup.tsx
  frontend/src/metabase/setup/components/UsageQuestionStep/UsageQuestionStep.tsx
  frontend/src/metabase/setup/components/UserStep/UserStep.tsx
  frontend/src/metabase/setup/components/UserStep/UserStep.unit.spec.tsx
  frontend/src/metabase/setup/components/WelcomePage/WelcomePage.tsx
  frontend/src/metabase/setup/constants.ts
  frontend/src/metabase/setup/reducers.ts
  frontend/src/metabase/setup/selectors.ts
  frontend/src/metabase/setup/setup.unit.spec.tsx
  frontend/src/metabase/setup/types.ts
Labels: .Team/Embedding

#38494 fix trend line zlevel bug
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Combo.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Combo_Log.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Combo_Power.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Area.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Bar.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Line.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Normalized_Stacked_Area.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Normalized_Stacked_Bar.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Stacked_Area.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Stacked_Bar.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Single_Series_Area.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Single_Series_Bar.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Single_Series_Line.png
  frontend/src/metabase/visualizations/echarts/cartesian/constants/style.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/trend-line.ts
Labels: visual, loki-update

#37945 remove generic type from TabButton
  frontend/src/metabase/core/components/TabButton/TabButton.tsx
  frontend/src/metabase/core/components/TabButton/TabButton.unit.spec.tsx
  frontend/src/metabase/core/components/TabButton/TabButtonMenu.tsx
  frontend/src/metabase/core/components/TabRow/TabRow.stories.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/use-dashboard-tabs.ts
Labels: no-backport, .Team/DashViz

#38493 fix goal line out of bounds
  .loki/reference/chrome_laptop_static_viz_ComboChart_Goal_Between_Extent_And_Chart_Bound.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Goal_Line_Disabled.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Goal_Line_Out_Of_Bounds_37848.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Goal_Very_Small.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Line_Custom_Y_Axis_Range_Equals_Extents.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Goal_Line.png
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/goal-between-extent-and-chart-bound.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/goal-line-disabled.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/goal-line-out-of-bounds-37848.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/goal-very-small.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/line-custom-y-axis-range-equals-extents.json
  frontend/src/metabase/visualizations/echarts/cartesian/option/goal-line.ts
  frontend/src/metabase/visualizations/echarts/cartesian/utils/layout.ts
Labels: visual, .Team/DashViz, loki-update

#38447 Convert `cards` dashboard actions to TypeScript
  frontend/src/metabase-types/api/dashboard.ts
  frontend/src/metabase-types/api/mocks/dashboard.ts
  frontend/src/metabase/dashboard/actions/cards-typed.ts
  frontend/src/metabase/dashboard/actions/cards.js
  frontend/src/metabase/dashboard/actions/cards.unit.spec.ts
  frontend/src/metabase/dashboard/actions/index.ts
  frontend/src/metabase/dashboard/actions/tabs.ts
  frontend/src/metabase/dashboard/analytics.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/use-duplicate-dashcard.ts
  frontend/src/metabase/dashboard/components/DashboardTabs/test-utils.ts
  frontend/src/metabase/dashboard/utils.ts
  frontend/src/metabase/visualizations/index.ts
Labels: visual, no-backport, .Team/DashViz

#38495 fix reversed stacking order
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Breakout_With_Line_Series_Stacked_Right_Axis_Only.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Stacked_Normalized_Empty_Space_37880.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Stacked_Total_Formatted_Values.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Two_Axes_Stacked_With_Negative_Values.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Normalized_Stacked_Area.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Normalized_Stacked_Bar.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Stacked_Area.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Stacked_Bar.png
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/trend-line.ts
Labels: visual, .Team/DashViz, loki-update

#38491 Update default Metabot model
  src/metabase/metabot/settings.clj
  test/metabase/metabot/settings_test.clj
Labels: backport, .Team/DashViz

#38377 Milestone 1: Default Dashboard Body to a Fixed Width
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/29304-scalar-first-render-size-change.cy.spec.js
  e2e/test/scenarios/dashboard-cards/reproductions/31628-responsive-scalars.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-auto-apply.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-date.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard-back-navigation.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/dashboard/x-rays.cy.spec.js
  e2e/test/scenarios/sharing/public-dashboard.cy.spec.js
  e2e/test/scenarios/visualizations-charts/bar_chart.cy.spec.js
  frontend/src/metabase-types/api/dashboard.ts
  frontend/src/metabase-types/api/mocks/dashboard.ts
  frontend/src/metabase/css/core/base.css
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx
  frontend/src/metabase/dashboard/components/DashboardButtonTooltip.tsx
  frontend/src/metabase/dashboard/components/DashboardEmbedHeaderButton/DashboardEmbedHeaderButton.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.styled.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/test-utils.ts
  frontend/src/metabase/dashboard/components/ExtraEditButtonsMenu/ExtraEditButtonsMenu.tsx
  frontend/src/metabase/ui/theme.ts
  frontend/src/metabase/visualizations/components/CardRenderer.jsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.styled.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.tsx
  frontend/src/metabase/visualizations/visualizations/Text/Text.styled.tsx
  src/metabase/api/public.clj
  src/metabase/automagic_dashboards/core.clj
  test/metabase/api/embed_test.clj
Labels: visual, no-backport, .Team/DashViz

#38525 [QC] Remove `hasAnyClauses` method from `StructuredQuery` prototype
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/test/metabase-lib/lib/queries/StructuredQuery-filters.unit.spec.js
Labels: no-backport, :broom:, .Team/QueryingComponents

#38481 [MLv2] Migrate `usesMetric` using new question filter from the `GET /api/card` endpoint
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase/reference/metrics/MetricQuestions.jsx
  frontend/src/metabase/reference/selectors.js
Labels: no-backport, .Team/QueryingComponents

#38500 [MLv2] Migrate `usesSegment` using new question filter from the `GET /api/card endpoint`
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase/reference/metrics/MetricQuestions.jsx
  frontend/src/metabase/reference/segments/SegmentQuestions.jsx
  frontend/src/metabase/reference/selectors.js
  frontend/src/metabase/reference/utils.js
Labels: no-backport, .Team/QueryingComponents

#38487 serialization: snowplow events for export/import
  docs/installation-and-operation/commands.md
  docs/installation-and-operation/serialization.md
  enterprise/backend/src/metabase_enterprise/serialization/api.clj
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/storage.clj
  enterprise/backend/test/metabase_enterprise/serialization/api_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj
  snowplow/iglu-client-embedded/schemas/com.metabase/serialization_export/jsonschema/1-0-0
  snowplow/iglu-client-embedded/schemas/com.metabase/serialization_import/jsonschema/1-0-0
  src/metabase/analytics/snowplow.clj
  src/metabase/cmd.clj
  test/metabase/cmd_test.clj
Labels: no-backport, .Team/BackendComponents

#38463 Dashboard sections
  e2e/test/scenarios/dashboard-cards/dashboard-sections.cy.spec.js
  frontend/src/metabase-types/api/dashboard.ts
  frontend/src/metabase-types/api/mocks/dashboard.ts
  frontend/src/metabase/dashboard/actions/cards-typed.ts
  frontend/src/metabase/dashboard/actions/cards.unit.spec.ts
  frontend/src/metabase/dashboard/actions/core.js
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/dashboard/components/DashCard/utils.ts
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/SectionLayoutPreview.tsx
  frontend/src/metabase/dashboard/reducers.js
  frontend/src/metabase/dashboard/sections.ts
  frontend/src/metabase/dashboard/utils.ts
  frontend/src/metabase/visualizations/register.js
  frontend/src/metabase/visualizations/visualizations/DashCardPlaceholder.tsx
  src/metabase/api/pulse.clj
  src/metabase/models/pulse.clj
  src/metabase/pulse.clj
  test/metabase/api/alert_test.clj
  test/metabase/api/pulse_test.clj
  test/metabase/pulse/pulse_integration_test.clj
Labels: visual, no-backport, .Team/DashViz

#38544 Partially migrate is Question.prototype.isDataset
  e2e/test/scenarios/embedding/reproductions/37914-embed-preview-parameter-values-not-working.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/caching/utils.js
  enterprise/frontend/src/metabase-enterprise/caching/utils.unit.spec.ts
  enterprise/frontend/src/metabase-enterprise/moderation/components/QuestionModerationButton/QuestionModerationButton.tsx
  enterprise/frontend/src/metabase-enterprise/moderation/components/QuestionModerationButton/QuestionModerationButton.unit.spec.js
  enterprise/frontend/src/metabase-enterprise/moderation/index.js
  enterprise/frontend/src/metabase-enterprise/moderation/utils.ts
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase-lib/queries/utils/native-query-table.ts
  frontend/src/metabase-types/api/mocks/presets/sample_cards.ts
  frontend/src/metabase/dashboard/actions/navigation.js
  frontend/src/metabase/models/containers/ModelDetailPage/ModelDetailPage.tsx
  frontend/src/metabase/query_builder/actions/core/initializeQB.ts
  frontend/src/metabase/query_builder/components/QueryModals.tsx
  frontend/src/metabase/query_builder/components/SavedQuestionIntroModal.jsx
  frontend/src/metabase/query_builder/components/SavedQuestionIntroModal.tsx
  frontend/src/metabase/query_builder/components/dataref/QuestionPane/QuestionPane.tsx
  frontend/src/metabase/query_builder/components/view/View.jsx
  frontend/src/metabase/query_builder/components/view/ViewFooter.jsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/QuestionInfoSidebar.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/tests/common.unit.spec.tsx
  frontend/src/metabase/query_builder/selectors.unit.spec.js
  frontend/src/metabase/questions/components/QuestionMoveToast/QuestionMoveToast.tsx
  frontend/src/metabase/questions/containers/ArchiveQuestionModal.jsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailView.unit.spec.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
Labels: visual, no-backport, .Team/QueryingComponents

#38527 bump toucan2 dependency
  deps.edn
Labels: no-backport, .Team/AdminWebapp

#38550 [QC] Remove `setDatabase` and `setDatabaseID` methods
  frontend/src/metabase-lib/queries/NativeQuery.ts
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/test/metabase-lib/lib/queries/StructuredQuery.unit.spec.js
Labels: no-backport, :broom:, .Team/QueryingComponents

#38548 Avoid unnecessary re-renderings in because of getQuestions selector
  frontend/src/metabase/dashboard/selectors.ts
  package.json
  yarn.lock
Labels: no-backport, .Team/QueryingComponents

#38280 load analytics only when changed using a checksum
  e2e/runner/cypress-runner-backend.js
  enterprise/backend/src/metabase_enterprise/audit_db.clj
  enterprise/backend/test/metabase_enterprise/audit_db_test.clj
Labels: backport, .Team/AdminWebapp

#38551 [QC] Remove unused methods from the `StructuredQuery` prototype
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/test/metabase-lib/lib/queries/StructuredQuery.unit.spec.js
Labels: no-backport, :broom:, .Team/QueryingComponents

#38521 analytics for meet-embedders
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.js
  frontend/src/metabase/home/components/EmbedMinimalHomepage/EmbedMinimalHomepage.tsx
  frontend/src/metabase/setup/actions.ts
  frontend/src/metabase/setup/analytics.ts
  frontend/src/metabase/setup/components/Setup/Setup.tsx
  snowplow/iglu-client-embedded/schemas/com.metabase/setup/jsonschema/1-0-2
Labels: .Team/Embedding

#38534 fix histogram bar width
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Histogram_Multi_Series.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Histogram_Stacked.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Histogram_Stacked_Normalized.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Histogram_X_Scale.png
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/bar-histogram-multi-series.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/bar-histogram-stacked-normalized.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/bar-histogram-stacked.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
Labels: visual, .Team/DashViz, loki-update

#38520 Meet embedders - minimal version
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.js
  frontend/src/metabase-types/api/setup.ts
  frontend/src/metabase-types/store/mocks/setup.ts
  frontend/src/metabase-types/store/setup.ts
  frontend/src/metabase/home/components/EmbedMinimalHomepage/EmbedMinimalHomepage.styled.tsx
  frontend/src/metabase/home/components/EmbedMinimalHomepage/EmbedMinimalHomepage.tsx
  frontend/src/metabase/home/components/EmbedMinimalHomepage/index.ts
  frontend/src/metabase/home/components/HomeContent/HomeContent.tsx
  frontend/src/metabase/home/utils.ts
  frontend/src/metabase/setup/actions.ts
  frontend/src/metabase/setup/analytics.ts
  frontend/src/metabase/setup/components/ActiveStep/ActiveStep.tsx
  frontend/src/metabase/setup/components/CloudMigrationHelp/CloudMigrationHelp.tsx
  frontend/src/metabase/setup/components/CompletedStep/CompletedStep.tsx
  frontend/src/metabase/setup/components/CompletedStep/CompletedStep.unit.spec.tsx
  frontend/src/metabase/setup/components/DatabaseHelp/DatabaseHelp.tsx
  frontend/src/metabase/setup/components/DatabaseStep/DatabaseStep.tsx
  frontend/src/metabase/setup/components/DatabaseStep/DatabaseStep.unit.spec.tsx
  frontend/src/metabase/setup/components/InactiveStep/InactiveStep.styled.tsx
  frontend/src/metabase/setup/components/InactiveStep/InactiveStep.tsx
  frontend/src/metabase/setup/components/InactiveStep/index.ts
  frontend/src/metabase/setup/components/LanguageStep/LanguageStep.tsx
  frontend/src/metabase/setup/components/LanguageStep/LanguageStep.unit.spec.tsx
  frontend/src/metabase/setup/components/PreferencesStep/PreferencesStep.tsx
  frontend/src/metabase/setup/components/PreferencesStep/PreferencesStep.unit.spec.tsx
  frontend/src/metabase/setup/components/SettingsPage/SettingsPage.tsx
  frontend/src/metabase/setup/components/Setup/Setup.tsx
  frontend/src/metabase/setup/components/UsageQuestionStep/UsageQuestionStep.tsx
  frontend/src/metabase/setup/components/UsageQuestionStep/index.ts
  frontend/src/metabase/setup/components/UserStep/UserStep.tsx
  frontend/src/metabase/setup/components/UserStep/UserStep.unit.spec.tsx
  frontend/src/metabase/setup/components/WelcomePage/WelcomePage.tsx
  frontend/src/metabase/setup/components/types.ts
  frontend/src/metabase/setup/constants.ts
  frontend/src/metabase/setup/reducers.ts
  frontend/src/metabase/setup/selectors.ts
  frontend/src/metabase/setup/setup.unit.spec.tsx
  frontend/src/metabase/setup/types.ts
  snowplow/iglu-client-embedded/schemas/com.metabase/setup/jsonschema/1-0-2
Labels: no-backport, .Team/Embedding

#38518 Improve look of models in Browse data
  frontend/src/metabase/browse/components/BrowseModels.styled.tsx
  frontend/src/metabase/browse/components/BrowseModels.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarView.tsx
Labels: no-backport, .Team/AdminWebapp

#38547 Fix card query endpoint usage on dashboards
  e2e/test/scenarios/dashboard-cards/duplicate-dashcards-tabs.cy.spec.js
  e2e/test/scenarios/dashboard-filters/reproductions/38245-negative-dashcard-id-switching-tabs.cy.spec.js
  frontend/src/metabase/dashboard/actions/cards.unit.spec.ts
  frontend/src/metabase/dashboard/actions/data-fetching.js
Labels: no-backport, .Team/DashViz

#38450 Update default sizes for new dash width
  e2e/support/helpers/e2e-dashboard-helpers.js
  e2e/test/scenarios/dashboard-cards/dashboard-card-resizing.cy.spec.js
  e2e/test/scenarios/dashboard/tabs.cy.spec.js
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.tsx
  frontend/src/metabase/visualizations/shared/utils/sizes.ts
Labels: visual, no-backport

#38575 add section icon and use in dashboard edit mode
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.tsx
  frontend/src/metabase/ui/components/icons/Icon/icons/index.ts
  frontend/src/metabase/ui/components/icons/Icon/icons/section.svg
Labels: no-backport

#38571 add test for scatter plot breakout bubble size
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Custom_Y_Axis_Range.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Default.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Goal_Line.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Histogram_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale_At_One.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Metric_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Ordinal_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale_Multi_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Timeseries_X_Scale.png
  frontend/src/metabase/static-viz/components/ScatterPlot/ScatterPlot.stories.tsx
  frontend/src/metabase/static-viz/components/ScatterPlot/stories-data/index.ts
  frontend/src/metabase/static-viz/components/ScatterPlot/stories-data/multi-dimension-breakout-bubble-size.json
Labels: visual, .Team/DashViz, loki-update

#38576 fix error with fully null series
  .loki/reference/chrome_laptop_static_viz_ComboChart_Area_Fully_Null_Dimension_37902.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Bar_Fully_Null_Dimension_37902.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Line_Fully_Null_Dimension_37902.png
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/area-fully-null-dimension-37902.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/bar-fully-null-dimension-37902.json
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/line-fully-null-dimension-37902.json
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/series.ts
Labels: visual, .Team/DashViz, loki-update

#38580 fix goal line fading
  frontend/src/metabase/visualizations/echarts/cartesian/option/goal-line.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
Labels: visual, .Team/DashViz

#38047 [MLv2] Use the provided `column-ref` for drills
  src/metabase/lib/drill_thru/column_filter.cljc
  src/metabase/lib/drill_thru/fk_filter.cljc
  src/metabase/lib/drill_thru/quick_filter.cljc
  src/metabase/lib/drill_thru/sort.cljc
  test/metabase/lib/drill_thru/column_filter_test.cljc
  test/metabase/lib/test_util.cljc
Labels: backport, .Team/QueryProcessor

#38583 Disable redshift support for uploads
  src/metabase/driver/postgres.clj
Labels: no-backport, .Team/BackendComponents

#38552 Disable table-privileges feature for MySQL
  src/metabase/driver/mysql.clj
Labels: backport, .Team/BackendComponents

#38593 Remove flaky timeout in DelayGroup test
  frontend/src/metabase/ui/components/utils/DelayGroup/DelayGroup.unit.spec.tsx
Labels: no-backport, .Team/QueryingComponents

#38482 Don't instrument any namespaces for mu.fn/fn in production
  src/metabase/util/malli/defn.clj
  src/metabase/util/malli/fn.clj
  test/metabase/util/malli/defn_test.clj
  test/metabase/util/malli/fn_test.clj
Labels: backport, .Team/BackendComponents

#38546 Remove handling MySQL <8 in table privileges test
  test/metabase/driver/mysql_test.clj
Labels: no-backport, .Team/BackendComponents

#38598 Update devcontainer Dockerile
  .devcontainer/Dockerfile
Labels: backport

#38574 Milestone 3B: Fix dashboard tabs and filters order on a public dashboard page
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.tsx
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.styled.tsx
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.tsx
  frontend/src/metabase/public/containers/PublicDashboard.jsx
  frontend/src/metabase/public/containers/PublicDashboard.styled.tsx
Labels: no-backport, .Team/DashViz

#38395 Embedding + required params
  e2e/support/helpers/e2e-dashboard-helpers.js
  e2e/support/helpers/e2e-embedding-helpers.js
  e2e/test/scenarios/embedding/embedding-dashboard.cy.spec.js
  e2e/test/scenarios/embedding/embedding-native.cy.spec.js
  e2e/test/scenarios/embedding/shared/embedding-native.js
  e2e/test/scenarios/native-filters/helpers/e2e-sql-filter-helpers.js
  frontend/src/metabase-lib/parameters/utils/cards.ts
  frontend/src/metabase-lib/parameters/utils/parameter-values.js
  frontend/src/metabase-lib/parameters/utils/parameter-values.unit.spec.js
  frontend/src/metabase-types/api/dashboard.ts
  frontend/src/metabase/core/components/Toggle/Toggle.styled.tsx
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx
  frontend/src/metabase/dashboard/components/DashboardSidebars.jsx
  frontend/src/metabase/dashboard/containers/AutomaticDashboardApp.jsx
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.tsx
  frontend/src/metabase/dashboard/selectors.ts
  frontend/src/metabase/parameters/components/ParameterSettings/ParameterSettings.styled.tsx
  frontend/src/metabase/parameters/components/ParameterSettings/ParameterSettings.tsx
  frontend/src/metabase/parameters/components/ParameterSettings/ParameterSettings.unit.spec.tsx
  frontend/src/metabase/parameters/components/ParameterSidebar/ParameterSidebar.tsx
  frontend/src/metabase/parameters/components/ParameterSidebar/ParameterSidebar.unit.spec.tsx
  frontend/src/metabase/parameters/components/ParameterWidget/ParameterWidget.jsx
  frontend/src/metabase/parameters/components/RequiredParamToggle/RequierParamToggle.styled.tsx
  frontend/src/metabase/parameters/components/RequiredParamToggle/RequiredParamToggle.tsx
  frontend/src/metabase/parameters/components/RequiredParamToggle/index.ts
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/ParametersSettings.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/StaticEmbedSetupPane.tsx
  frontend/src/metabase/public/containers/PublicDashboard.jsx
  frontend/src/metabase/public/containers/PublicQuestion/PublicQuestion.jsx
  frontend/src/metabase/public/lib/types.ts
  frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.styled.tsx
  frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.tsx
  frontend/src/metabase/query_builder/components/template_tags/TagEditorSidebar.tsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.jsx
  frontend/src/metabase/query_builder/selectors.js
Labels: no-backport, .Team/QueryingComponents

#38529 Redshift: drop session schema when test suite finishes
  deps.edn
  modules/drivers/redshift/test/metabase/test/data/redshift.clj
  test/metabase/query_processor/card_test.clj
  test/metabase/test/data/interface.clj
  test_config/log4j2-test.xml
Labels: no-backport

#38584 Fix dispatch error in `with-model-cleanup`
  test/metabase/test/util.clj
Labels: no-backport, .Team/AdminWebapp

#38585 Milestone 3A: Add fixed width behavior to dashboard filters
  e2e/test/scenarios/dashboard-filters/reproductions/17775-filter-custom-column-date.cy.spec.js
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.styled.tsx
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.styled.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.tsx
  frontend/src/metabase/dashboard/containers/AutomaticDashboardApp.jsx
  frontend/src/metabase/parameters/components/ParameterWidget/ParameterWidget.styled.ts
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.styled.tsx
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.tsx
  frontend/src/metabase/public/containers/PublicDashboard.jsx
  frontend/src/metabase/public/containers/PublicDashboard.styled.tsx
Labels: no-backport, .Team/DashViz

#38393 Remove impersonation feature from Redshift driver
  modules/drivers/redshift/src/metabase/driver/redshift.clj
Labels: backport

#38415 docs - note on stopping when importing and exporting
  docs/installation-and-operation/serialization.md
Labels: Type:Documentation, backport

#38371 docs - fix migrate down command
  docs/installation-and-operation/upgrading-metabase.md
Labels: Type:Documentation, backport

#38600 Scope find-root-test-failure! to same ns by default
  dev/src/dev.clj
Labels: no-backport, .Team/BackendComponents

#38609 Default enable-public-sharing to false for existing instances, and true for new ones
  frontend/src/metabase/admin/settings/selectors.js
  resources/migrations/001_update_migrations.yaml
  src/metabase/public_settings.clj
  test/metabase/db/schema_migrations_test.clj
Labels: no-backport, .Team/AdminWebapp

#37617 Add snowplow events for embedding setup flow
  e2e/support/helpers/e2e-snowplow-helpers.js
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/embedding/embedding-downloads-questions.cy.spec.js
  e2e/test/scenarios/embedding/embedding-smoketests.cy.spec.js
  e2e/test/scenarios/sharing/public-sharing-embed-button-behavior.cy.spec.js
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase-types/api/dashboard.ts
  frontend/src/metabase-types/api/mocks/card.ts
  frontend/src/metabase-types/api/mocks/dashboard.ts
  frontend/src/metabase/actions/containers/ActionCreator/ActionContext/QueryActionContextProvider/QueryActionContextProvider.tsx
  frontend/src/metabase/dashboard/actions/sharing.ts
  frontend/src/metabase/dashboard/components/DashboardTabs/test-utils.ts
  frontend/src/metabase/dashboard/components/PublicLinkPopover/DashboardPublicLinkPopover.tsx
  frontend/src/metabase/dashboard/components/PublicLinkPopover/PublicLinkCopyPanel.tsx
  frontend/src/metabase/dashboard/components/PublicLinkPopover/PublicLinkPopover.tsx
  frontend/src/metabase/dashboard/components/PublicLinkPopover/QuestionPublicLinkPopover.tsx
  frontend/src/metabase/dashboard/reducers.js
  frontend/src/metabase/public/components/EmbedModal/SelectEmbedTypePane/SelectEmbedTypePane.tsx
  frontend/src/metabase/public/components/EmbedModal/SelectEmbedTypePane/SharingPaneButton/SharingPaneButton.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/AppearanceSettings.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/ClientEmbedCodePane.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/CodeSample.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/EmbedModalContentStatusBar.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/OverviewSettings.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/ServerEmbedCodePane.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/StaticEmbedSetupPane.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/config.ts
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/tabs.ts
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/tests/common.unit.spec.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/tests/premium.unit.spec.tsx
  frontend/src/metabase/public/lib/analytics.ts
  frontend/src/metabase/public/lib/code-templates.ts
  frontend/src/metabase/public/lib/code.ts
  frontend/src/metabase/public/lib/embed.ts
  frontend/src/metabase/public/lib/types.ts
  frontend/src/metabase/query_builder/actions/sharing.ts
  frontend/src/metabase/query_builder/reducers.js
  frontend/src/metabase/ui/components/overlays/Popover/index.ts
  frontend/src/metabase/ui/components/overlays/Popover/index.tsx
  resources/migrations/001_update_migrations.yaml
  snowplow/iglu-client-embedded/schemas/com.metabase/embed_flow/jsonschema/1-0-0
  src/metabase/models/card.clj
  src/metabase/models/dashboard.clj
  src/metabase/util/embed.clj
  test/metabase/api/card_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/util/embed_test.clj
Labels: visual, no-backport, .Team/Embedding

#38475 Connection Impersonation for Redshift
  enterprise/backend/test/metabase_enterprise/advanced_permissions/driver/impersonation_test.clj
  modules/drivers/redshift/src/metabase/driver/redshift.clj
Labels: no-backport, .Team/AdminWebapp

#38261 Browse models: Add banner
  e2e/test/scenarios/onboarding/home/browse.cy.spec.js
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/browse/components/BrowseModels.styled.tsx
  frontend/src/metabase/browse/components/BrowseModels.tsx
  frontend/src/metabase/browse/selectors.ts
  src/metabase/public_settings.clj
Labels: no-backport, .Team/AdminWebapp

#38578 Browse models: Sort official collections to the top
  .github/workflows/uberjar.yml
  frontend/src/metabase/browse/components/BrowseModels.tsx
  frontend/src/metabase/browse/utils.ts
Labels: no-backport, .Team/AdminWebapp

#38490 Allow appends from collection list
  frontend/src/metabase-types/api/collection.ts
  frontend/src/metabase/collections/components/CollectionHeader/CollectionHeader.tsx
  frontend/src/metabase/collections/components/CollectionHeader/CollectionUpload.tsx
  frontend/src/metabase/collections/components/CollectionHeader/tests/setup.tsx
  frontend/src/metabase/collections/components/ModelUploadModal.tsx
  frontend/src/metabase/collections/containers/CollectionContent.jsx
  frontend/src/metabase/components/ErrorDetails/ErrorDetails.styled.tsx
  frontend/src/metabase/models/components/ModelDetailLink/ModelDetailLink.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionActions/QuestionActions.tsx
  frontend/src/metabase/redux/uploads.ts
  frontend/src/metabase/redux/uploads.unit.spec.js
  frontend/src/metabase/status/components/FileUploadStatus/FileUploadStatus.unit.spec.tsx
  frontend/src/metabase/status/components/FileUploadStatusLarge/FileUploadErrorModal.tsx
  frontend/test/__support__/server-mocks/collection.ts
Labels: no-backport, .Team/AdminWebapp

#38591 Browse models: only show 'Learn about our data' on the databases tab (very small PR)
  .github/workflows/uberjar.yml
  e2e/test/scenarios/onboarding/home/browse.cy.spec.js
  frontend/src/metabase/browse/components/BrowseApp.tsx
Labels: no-backport, .Team/AdminWebapp

#38297 [MLv2] Add tests and fix a special case for fk-filter drills
  src/metabase/lib/drill_thru/fk_filter.cljc
  src/metabase/lib/stage.cljc
  test/metabase/lib/drill_thru/fk_filter_test.cljc
Labels: .Team/QueryProcessor, no-backport

#38622 Analytics should load only when changed, via checksum
  dev/src/dev.clj
  enterprise/backend/src/metabase_enterprise/audit_db.clj
  enterprise/backend/test/metabase_enterprise/sandbox/models/params/field_values_test.clj
  src/metabase/automagic_dashboards/interesting.clj
  src/metabase/models/recent_views.clj
  test/metabase/actions/test_util.clj
  test/metabase/api/search_test.clj
  test/metabase/models/recent_views_test.clj
Labels: backport, .Team/AdminWebapp

#38472 [MLv2] Add drill-thru test coverage for nil-valued bins
  src/metabase/lib/drill_thru/pivot.cljc
  test/metabase/lib/drill_thru/zoom_in_bins_test.cljc
  test/metabase/lib/drill_thru/zoom_in_geographic_test.cljc
Labels: .metabase-lib, .Team/QueryProcessor, no-backport

#38630 docs - remove in-line toc
  docs/installation-and-operation/upgrading-metabase.md
Labels: Type:Documentation, backport

#38626 Force reload in `ensure-audit-db-installed!`
  enterprise/backend/test/metabase_enterprise/audit_app/permissions_test.clj
Labels: backport, .Team/AdminWebapp

#38172 Use mlv2 findColumnIndexForColumnSetting in viz settings
  frontend/src/metabase/visualizations/lib/settings/column.js
Labels: visual, .Team/QueryingComponents

#37827 docs - json unfolding
  docs/README.md
  docs/data-modeling/field-types.md
  docs/data-modeling/images/table-with-json-column.png
  docs/data-modeling/images/unfold-json-setting.png
  docs/data-modeling/images/unfolded-fields.png
  docs/data-modeling/images/unfolded-values.png
  docs/data-modeling/json-unfolding.md
  docs/data-modeling/start.md
Labels: Type:Documentation, backport

#38153 Add BE for routing billing status
  enterprise/backend/src/metabase_enterprise/api/routes.clj
  enterprise/backend/src/metabase_enterprise/billing/api/routes.clj
  enterprise/backend/src/metabase_enterprise/billing/billing.clj
  enterprise/backend/test/metabase_enterprise/billing/billing_test.clj
  src/metabase/api/routes.clj
Labels: no-backport, .Team/AdminWebapp

#38530 Connection Impersonation UI for Redshift
  enterprise/frontend/src/metabase-enterprise/advanced_permissions/components/ImpersonationModal/ImpersonationModal.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/advanced_permissions/components/ImpersonationModal/ImpersonationModalView.styled.tsx
  enterprise/frontend/src/metabase-enterprise/advanced_permissions/components/ImpersonationModal/ImpersonationModalView.tsx
  enterprise/frontend/src/metabase-enterprise/advanced_permissions/components/ImpersonationWarning/ImpersonationWarning.tsx
  enterprise/frontend/src/metabase-enterprise/advanced_permissions/components/ImpersonationWarning/ImpersonationWarning.unit.spec.tsx
  frontend/src/metabase/components/Code/Code.jsx
  frontend/src/metabase/components/Code/index.jsx
Labels: no-backport, .Team/AdminWebapp

#38629 Don't lower dashboard/question title when there is no last edit info
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeaderView.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/ViewHeader.jsx
Labels: no-backport, .Team/AdminWebapp

#38562 Revert breaking change to the `active-tables` driver method
  docs/developers-guide/driver-changelog.md
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  modules/drivers/redshift/test/metabase/driver/redshift_test.clj
  src/metabase/driver.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql_jdbc.clj
  src/metabase/driver/sql_jdbc/sync.clj
  src/metabase/driver/sql_jdbc/sync/describe_database.clj
  src/metabase/driver/sql_jdbc/sync/interface.clj
  test/metabase/driver/mysql_test.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/driver/sql_jdbc/sync/describe_database_test.clj
Labels: no-backport, .Team/BackendComponents

#38647 Fix custom destination to public dashboard not working on static embedding
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  frontend/src/metabase/lib/dom.js
Labels: backport, .Team/Embedding

#38645 Type routing in State
  frontend/src/metabase-types/store/mocks/index.ts
  frontend/src/metabase-types/store/mocks/routing.ts
  frontend/src/metabase-types/store/mocks/state.ts
  frontend/src/metabase-types/store/state.ts
  frontend/src/metabase/query_builder/actions/navigation.js
  frontend/src/metabase/selectors/routing.ts
  frontend/test/__support__/ui.tsx
Labels: no-backport, .Team/QueryingComponents

#38656 backport: should make test pass in release when we have a specific version in the url
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.js
Labels: .Team/BackendComponents

#38655 should make test pass in release when we have a specific version in t…
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.js
Labels: no-backport, .Team/Embedding

#38570 [QC] Remove unused utils and methods on the `Join` prototype
  frontend/src/metabase-lib/queries/StructuredQuery.ts
  frontend/src/metabase-lib/queries/structured/Join.ts
  frontend/src/metabase-lib/queries/utils/join.js
  frontend/src/metabase-lib/queries/utils/query.js
Labels: no-backport, :broom:, .Team/QueryingComponents

#38512 New Metric page (`/metric/query`)
  frontend/src/metabase-lib/Question.ts
  frontend/src/metabase-types/api/mocks/dataset.ts
  frontend/src/metabase/actions/containers/ActionCreatorModal/ActionCreatorModal.unit.spec.tsx
  frontend/src/metabase/components/NewItemMenu/NewItemMenu.tsx
  frontend/src/metabase/containers/SaveQuestionModal.tsx
  frontend/src/metabase/containers/SaveQuestionModal.unit.spec.tsx
  frontend/src/metabase/dashboard/components/Dashboard/DashboardEmptyState/DashboardEmptyState.tsx
  frontend/src/metabase/lib/urls/questions.ts
  frontend/src/metabase/models/containers/NewModelOptions/NewModelOptions.tsx
  frontend/src/metabase/query_builder/actions/core/updateQuestion.ts
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx
  frontend/src/metabase/query_builder/components/QueryModals.tsx
  frontend/src/metabase/query_builder/components/view/View.jsx
  frontend/src/metabase/query_builder/containers/test-utils.tsx
  frontend/src/metabase/query_builder/selectors.js
  frontend/src/metabase/query_builder/typed-utils.ts
  frontend/src/metabase/routes.jsx
  frontend/src/metabase/selectors/app.ts
Labels: no-backport, .Team/QueryingComponents

#38624 source-field populated in aggregates with foreign refs
  src/metabase/automagic_dashboards/interesting.clj
  test/metabase/automagic_dashboards/core_test.clj
  test/metabase/automagic_dashboards/interesting_test.clj
Labels: backport

#38660 Bump Bigquery driver to v2.37.1
  modules/drivers/bigquery-cloud-sdk/deps.edn
Labels: no-backport

#38642 Compare datetimes w/o timezone fields with literals as strings
  modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj
  modules/drivers/sqlserver/test/metabase/driver/sqlserver_test.clj
Labels: backport, .Team/QueryProcessor

#38582 Fix sidebar and home loading indefinitely when database data fails to load
  frontend/src/metabase/home/components/HomeContent/HomeContent.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarContainer.tsx
Labels: backport, .Team/AdminWebapp

#38635 Models In Browse Data Follow Up
  e2e/test/scenarios/onboarding/home/browse.cy.spec.js
  e2e/test/scenarios/onboarding/urls.cy.spec.js
  frontend/src/metabase-types/api/mocks/search.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/browse/components/BrowseApp.tsx
  frontend/src/metabase/browse/components/BrowseDatabases.tsx
  frontend/src/metabase/browse/components/BrowseDatabases.unit.spec.tsx
  frontend/src/metabase/browse/components/BrowseModels.styled.tsx
  frontend/src/metabase/browse/components/BrowseModels.tsx
  frontend/src/metabase/browse/components/BrowseModels.unit.spec.tsx
  frontend/src/metabase/browse/components/BrowseRedirect.tsx
  frontend/src/metabase/browse/components/BrowseRedirect.unit.spec.tsx
  frontend/src/metabase/browse/components/ModelExplanationBanner.tsx
  frontend/src/metabase/browse/utils.ts
  frontend/src/metabase/routes.jsx
  src/metabase/public_settings.clj
Labels: no-backport, .Team/AdminWebapp

#38476 [MLv2] Add description and fingerprint to `displayInfo` for columns
  frontend/src/metabase-lib/types.ts
  src/metabase/lib/field.cljc
  test/metabase/lib/js_test.cljs
Labels: .Team/QueryProcessor, no-backport
