Repository metabase/metabase, pull requests merged in 2024-07, with the labels that each got.

#44908 fix: one of transactions was removed and that causes problems on downgrade
  resources/migrations/001_update_migrations.yaml
  test/metabase/db/schema_migrations_test.clj
Labels: backport, .Team/BackendComponents

#44886 Fix unable to rollback due to dropped not null constraint on 50
  dev/src/dev/migrate.clj
  resources/migrations/001_update_migrations.yaml
Labels: backport, .Team/BackendComponents

#44888 replace html2cavas with html2canvas-pro to support color css functions
  frontend/src/metabase/visualizations/lib/save-chart-image.ts
  frontend/src/metabase/visualizations/lib/save-dashboard-pdf.ts
  package.json
  webpack.config.js
  yarn.lock
Labels: no-backport, .Team/Embedding

#44944 🤖 backported "Wrap non-latin characters in a span specifying working font"
  deps.edn
  resources/frontend_client/app/fonts/Lato/Lato-Regular.ttf
  src/metabase/pulse/render/png.clj
  src/metabase/pulse/render/style.clj
  test/metabase/pulse/render/png_test.clj
Labels: was-backported

#44872 [dev tool] Generate sql statement for a migration
  dev/src/dev.clj
  dev/src/dev/migrate.clj
  dev/test/dev/migrate_test.clj
Labels: no-backport, .Team/BackendComponents

#44954 🤖 backported "Fix unable to rollback due to dropped not null constraint on 50"
  resources/migrations/001_update_migrations.yaml
Labels: was-backported

#44956 Milestone tracing logic update
  release/src/linked-issues.ts
  release/src/linked-issues.unit.spec.ts
Labels: .CI & Tests, no-backport, .Team/DevEx

#44882 Add a reproduction for "Cannot find the new column in pick columns after alter schema and synced"
  e2e/test/scenarios/admin/admin-reproductions.cy.spec.js
Labels: support/Repro, backport, .Team/QueryingComponents

#44953 🤖 backported "fix: one of transactions was removed and that causes problems on downgrade"
  resources/migrations/001_update_migrations.yaml
  test/metabase/db/schema_migrations_test.clj
Labels: .Team/BackendComponents, was-backported

#44775 feat(sdk): Add customizable layout to interactive question
  enterprise/frontend/src/embedding-sdk/README.md
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/Visualization.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/context.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/index.ts
Labels: no-backport, .Team/Embedding

#44964 🤖 backported "Combine actions e2e specs"
  e2e/test/scenarios/actions/actions-reproductions.cy.spec.js
  e2e/test/scenarios/actions/reproductions/31587-bottom-corner-radius-action-buttons.cy.spec.js
  e2e/test/scenarios/actions/reproductions/32974-linked-parameter-via-url-does-not-work.cy.spec.js
Labels: was-backported

#44909 Repro #27521 - Query fails when selecting two fields from nested query, when fields are identical except for their join-alias
  e2e/test/scenarios/joins/joins-reproductions.cy.spec.js
  e2e/test/scenarios/models/reproductions.cy.spec.ts
Labels: backport, .Team/QueryingComponents

#44965 Repro #28106 - Scrolling up on schema list jumps to the top when creating a new question
  e2e/support/test_tables.js
  e2e/test/scenarios/question/notebook-data-source.cy.spec.ts
Labels: backport, .Team/QueryingComponents

#44971 🤖 backported "Repro #28106 - Scrolling up on schema list jumps to the top when creating a new question"
  e2e/support/test_tables.js
  e2e/test/scenarios/question/notebook-data-source.cy.spec.ts
Labels: was-backported

#44968 🤖 backported "Repro #27521 - Query fails when selecting two fields from nested query, when fields are identical except for their join-alias"
  e2e/test/scenarios/joins/joins-reproductions.cy.spec.js
  e2e/test/scenarios/models/reproductions.cy.spec.ts
Labels: was-backported

#44859 Support specific date filters with 00:00 time
  e2e/test/scenarios/dashboard-filters/dashboard-filters-date.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
  frontend/src/metabase-lib/filter.ts
  frontend/src/metabase-lib/filter.unit.spec.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/querying/components/DatePicker/DateOperatorPicker/utils.unit.spec.ts
  frontend/src/metabase/querying/components/DatePicker/DatePicker.unit.spec.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePicker.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePicker.unit.spec.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/DateRangePicker/SimpleDateRangePicker/SimpleDateRangePicker.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/DateRangePicker/SimpleDateRangePicker/SimpleDateRangePicker.unit.spec.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/DateRangePicker/index.ts
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/DateRangePicker/types.ts
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SimpleSpecificDatePicker/SimpleSpecificDatePicker.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SimpleSpecificDatePicker/SimpleSpecificDatePicker.unit.spec.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SingleDatePicker/SimpleSingleDatePicker/SimpleSingleDatePicker.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SingleDatePicker/SimpleSingleDatePicker/SimpleSingleDatePicker.unit.spec.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SingleDatePicker/SingleDatePicker.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SingleDatePicker/SingleDatePicker.unit.spec.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SingleDatePicker/index.ts
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SingleDatePicker/types.ts
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SpecificDatePicker.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SpecificDatePicker.unit.spec.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/TimeToggle/TimeToggle.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/utils.ts
  frontend/src/metabase/querying/components/DatePicker/types.ts
  frontend/src/metabase/querying/components/FilterContent/DateFilterEditor/DateFilterEditor.unit.spec.tsx
  frontend/src/metabase/querying/components/FilterPicker/test-utils.ts
  frontend/src/metabase/querying/components/TimeseriesChrome/TimeseriesFilterPicker/TimeseriesFilterPicker.unit.spec.tsx
  frontend/src/metabase/querying/hooks/use-date-filter/use-date-filter.unit.spec.ts
  frontend/src/metabase/querying/hooks/use-date-filter/utils.ts
Labels: backport, .Team/QueryingComponents

#44938 Memoize driver.u/supports? only in prod
  src/metabase/driver/util.clj
  test/metabase/driver/util_test.clj
Labels: backport, .Team/BackendComponents

#44975 Add reproduction for "Accurate Error Messaging for Cross DB Joins in Notebook Editor"
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
Labels: backport, .Team/QueryingComponents

#44979 🤖 backported "Support specific date filters with 00:00 time"
  e2e/test/scenarios/dashboard-filters/dashboard-filters-date.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
  frontend/src/metabase-lib/filter.ts
  frontend/src/metabase-lib/filter.unit.spec.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/querying/components/DatePicker/DateOperatorPicker/DateOperatorPicker.unit.spec.tsx
  frontend/src/metabase/querying/components/DatePicker/DateOperatorPicker/utils.unit.spec.ts
  frontend/src/metabase/querying/components/DatePicker/DatePicker.unit.spec.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePicker.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/DateRangePicker/DateRangePicker.unit.spec.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/DateRangePicker/SimpleDateRangePicker/SimpleDateRangePicker.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/DateRangePicker/SimpleDateRangePicker/SimpleDateRangePicker.unit.spec.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/DateRangePicker/index.ts
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/DateRangePicker/types.ts
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SimpleSpecificDatePicker/SimpleSpecificDatePicker.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SimpleSpecificDatePicker/SimpleSpecificDatePicker.unit.spec.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SingleDatePicker/SimpleSingleDatePicker/SimpleSingleDatePicker.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SingleDatePicker/SimpleSingleDatePicker/SimpleSingleDatePicker.unit.spec.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SingleDatePicker/SingleDatePicker.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SingleDatePicker/SingleDatePicker.unit.spec.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SingleDatePicker/index.ts
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SingleDatePicker/types.ts
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SpecificDatePicker.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/SpecificDatePicker.unit.spec.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/TimeToggle/TimeToggle.tsx
  frontend/src/metabase/querying/components/DatePicker/SpecificDatePicker/utils.ts
  frontend/src/metabase/querying/components/DatePicker/types.ts
  frontend/src/metabase/querying/components/FilterContent/DateFilterEditor/DateFilterEditor.unit.spec.tsx
  frontend/src/metabase/querying/components/FilterPicker/test-utils.ts
  frontend/src/metabase/querying/components/TimeseriesChrome/TimeseriesFilterPicker/TimeseriesFilterPicker.unit.spec.tsx
  frontend/src/metabase/querying/hooks/use-date-filter/use-date-filter.unit.spec.ts
  frontend/src/metabase/querying/hooks/use-date-filter/utils.ts
Labels: was-backported

#44990 Adds a property to a defsetting
  src/metabase/public_settings/premium_features.clj
  test/metabase/api/session_test.clj
Labels: backport, .Team/AdminWebapp

#44943 support sorting on funnel bar charts
  .loki/reference/chrome_laptop_static_viz_FunnelBarChart_Funnel_Bar_Ordered_Rows.png
  .loki/reference/chrome_laptop_static_viz_FunnelBarChart_Funnel_Bar_Unordered_Rows.png
  frontend/src/metabase/static-viz/components/FunnelBarChart/FunnelBarChart.stories.tsx
  frontend/src/metabase/static-viz/components/FunnelBarChart/stories-data/funnel-bar-ordered-rows.json
  frontend/src/metabase/static-viz/components/FunnelBarChart/stories-data/funnel-bar-unordered-rows.json
  frontend/src/metabase/static-viz/components/FunnelBarChart/stories-data/index.ts
  frontend/src/metabase/visualizations/visualizations/Funnel/funnel-bar-transform.ts
Labels: backport, .Team/DashViz

#44862 Better display names for CSV upload tables
  src/metabase/lib/util.cljc
  src/metabase/sync/sync_metadata/tables.clj
  src/metabase/upload.clj
  src/metabase/util.cljc
  test/metabase/lib/util_test.cljc
  test/metabase/upload_test.clj
  test/metabase/util_test.cljc
Labels: backport, .Team/BackendComponents

#44981 🤖 backported "Memoize driver.u/supports? only in prod"
  src/metabase/driver/util.clj
  test/metabase/driver/util_test.clj
Labels: was-backported

#44993 🤖 backported "support sorting on funnel bar charts"
  .loki/reference/chrome_laptop_static_viz_FunnelBarChart_Funnel_Bar_Ordered_Rows.png
  .loki/reference/chrome_laptop_static_viz_FunnelBarChart_Funnel_Bar_Unordered_Rows.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Auto_Y_Axis_Exclude_Zero_With_Goal.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Custom_Y_Axis_Range.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Custom_Y_Axis_Range_With_Column_Scaling.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Default.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Goal_Line.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Histogram_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Log_X_Scale_At_One.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Dimension_Breakout_Bubble_Size.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Multi_Metric_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Ordinal_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Power_X_Scale_Multi_Series.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Timeseries_X_Scale.png
  frontend/src/metabase/static-viz/components/FunnelBarChart/FunnelBarChart.stories.tsx
  frontend/src/metabase/static-viz/components/FunnelBarChart/stories-data/funnel-bar-ordered-rows.json
  frontend/src/metabase/static-viz/components/FunnelBarChart/stories-data/funnel-bar-unordered-rows.json
  frontend/src/metabase/static-viz/components/FunnelBarChart/stories-data/index.ts
  frontend/src/metabase/visualizations/visualizations/Funnel/funnel-bar-transform.ts
Labels: was-backported

#44996 🤖 backported "Better display names for CSV upload tables"
  src/metabase/lib/util.cljc
  src/metabase/sync/sync_metadata/tables.clj
  src/metabase/upload.clj
  src/metabase/util.cljc
  test/metabase/lib/util_test.cljc
  test/metabase/upload_test.clj
  test/metabase/util_test.cljc
Labels: was-backported

#44855 Return info about the proper billing status on the license page
  enterprise/backend/src/metabase_enterprise/billing/billing.clj
  enterprise/backend/test/metabase_enterprise/billing/billing_test.clj
Labels: backport, .Team/AdminWebapp

#45004 🤖 backported "Return info about the proper billing status on the license page"
  enterprise/backend/src/metabase_enterprise/billing/billing.clj
  enterprise/backend/test/metabase_enterprise/billing/billing_test.clj
Labels: was-backported

#44977 cached metadata provider: lower the log level for metadata retrieval so DEBUG is less busy
  src/metabase/lib/metadata/cached_provider.cljc
Labels: no-backport, .Team/BackendComponents

#44967 Create new release note sections
  release/src/constants.ts
  release/src/release-notes.ts
  release/src/release-notes.unit.spec.ts
Labels: .Building & Releasing, no-backport, .Team/DevEx

#44995 Add a repro for 'Permission error before finishing referencing a question in the native query'
  e2e/test/scenarios/native/native-reproductions.cy.spec.js
Labels: backport, .Team/QueryingComponents

#45011 fix missing release dependency
  release/package.json
  release/yarn.lock
Labels: .Building & Releasing, no-backport, .Team/DevEx

#44980 Allow ad-hoc release-notes generation
  .github/workflows/release-notes-preview.yml
  release/README.md
  release/generate-changelog.ts
  release/package.json
  release/release-offline.ts
  release/src/github.ts
  release/src/release-notes.ts
Labels: .Building & Releasing, no-backport, .Team/DevEx

#44969 Repro #34350 - Unable to switch question to query table in another database
  e2e/test/scenarios/question/notebook-data-source.cy.spec.ts
Labels: backport, .Team/QueryingComponents

#45012 🤖 backported "Repro #34350 - Unable to switch question to query table in another database"
  e2e/test/scenarios/question/notebook-data-source.cy.spec.ts
Labels: was-backported

#44989 fix(sdk): runtime error when font family is not provided
  enterprise/frontend/src/embedding-sdk/components/public/MetabaseProvider.tsx
  frontend/test/__support__/ui.tsx
Labels: no-backport, .Team/Embedding

#45031 Remove incorrect default parameter from release note generation code
  release/src/github.ts
Labels: .Building & Releasing, no-backport, .Team/DevEx

#45033 docs - add 50.9 to list of releases
  docs/releases.md
Labels: Type:Documentation, backport

#45035 🤖 backported "docs - add 50.9 to list of releases"
  docs/releases.md
Labels: was-backported

#45010 🤖 backported "Add a repro for 'Permission error before finishing referencing a question in the native query'"
  e2e/test/scenarios/native/native-reproductions.cy.spec.js
Labels: was-backported

#45037 Hide docs issues in release notes
  release/src/constants.ts
  release/src/release-notes.ts
  release/src/release-notes.unit.spec.ts
Labels: .Building & Releasing, no-backport, .Team/DevEx

#44942 Repro parameter field matching issues for questions based on sql models
  e2e/test/scenarios/filters-reproductions/dashboard-filters-reproductions.cy.spec.js
  frontend/src/metabase-lib/v1/parameters/utils/targets.ts
Labels: backport, .Team/QueryingComponents

#45025 Fix - Invalid join clause does not disappear after changing query source to use a different database
  e2e/test/scenarios/joins/joins-reproductions.cy.spec.js
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinDraft/JoinDraft.tsx
Labels: backport, .Team/QueryingComponents

#45043 🤖 backported "Fix - Invalid join clause does not disappear after changing query source to use a different database"
  e2e/test/scenarios/joins/joins-reproductions.cy.spec.js
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinDraft/JoinDraft.tsx
Labels: was-backported

#45040 🤖 backported "Repro parameter field matching issues for questions based on sql models"
  e2e/test/scenarios/filters-reproductions/dashboard-filters-reproductions.cy.spec.js
  frontend/src/metabase-lib/v1/parameters/utils/targets.ts
Labels: was-backported

#44920 docs: warnings about question marks
  docs/questions/native-editor/writing-sql.md
  docs/questions/query-builder/expressions-list.md
  docs/questions/query-builder/expressions.md
  docs/troubleshooting-guide/sql.md
Labels: Type:Documentation, backport

#45049 🤖 backported "docs: warnings about question marks"
  docs/questions/native-editor/writing-sql.md
  docs/questions/query-builder/expressions-list.md
  docs/questions/query-builder/expressions.md
  docs/troubleshooting-guide/sql.md
Labels: was-backported

#43430 Calculate metadata without running queries [JDBC]
  docs/configuring-metabase/log-configuration.md
  docs/developers-guide/driver-changelog.md
  e2e/test/scenarios/binning/binning-reproductions.cy.spec.js
  src/metabase/analyze.clj
  src/metabase/analyze/classifiers/core.clj
  src/metabase/analyze/classifiers/name.clj
  src/metabase/analyze/fingerprint/fingerprinters.clj
  src/metabase/analyze/query_results.clj
  src/metabase/api/card.clj
  src/metabase/driver.clj
  src/metabase/driver/sql_jdbc.clj
  src/metabase/driver/sql_jdbc/execute.clj
  src/metabase/driver/sql_jdbc/metadata.clj
  src/metabase/lib/schema.cljc
  src/metabase/lib/schema/metadata.cljc
  src/metabase/models/card.clj
  src/metabase/models/card/metadata.clj
  src/metabase/models/dashboard.clj
  src/metabase/query_processor/async.clj
  src/metabase/query_processor/compile.clj
  src/metabase/query_processor/metadata.clj
  src/metabase/query_processor/middleware/annotate.clj
  src/metabase/query_processor/preprocess.clj
  src/metabase/query_processor/store.clj
  src/metabase/query_processor/util.clj
  src/metabase/util/i18n.clj
  test/metabase/analyze/classifiers/name_test.clj
  test/metabase/api/card_test.clj
  test/metabase/api/dataset_test.clj
  test/metabase/driver/h2_test.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/driver/sql_jdbc/connection_test.clj
  test/metabase/driver/sql_jdbc/metadata_test.clj
  test/metabase/models/card_test.clj
  test/metabase/pulse/pulse_integration_test.clj
  test/metabase/query_processor/async_test.clj
  test/metabase/query_processor/metadata_test.clj
  test/metabase/query_processor/middleware/results_metadata_test.clj
  test/metabase/query_processor/persistence_test.clj
  test/metabase/query_processor/test_util.clj
  test/metabase/query_processor_test/aggregation_test.clj
  test/metabase/query_processor_test/native_test.clj
  test/metabase/query_processor_test/nested_queries_test.clj
  test/metabase/test/data/users.clj
  test/metabase/upload_test.clj
  test/metabase/xrays/automagic_dashboards/core_test.clj
  test/metabase/xrays/automagic_dashboards/interesting_test.clj
Labels: .Team/QueryProcessor, no-backport

#44763 prevent collections with special types / non-null namespaces from appearing in recents
  e2e/test/scenarios/native/snippets.cy.spec.js
  src/metabase/models/collection.clj
  src/metabase/models/recent_views.clj
  test/metabase/models/recent_views_test.clj
Labels: no-backport, .Team/AdminWebapp

#44986 Fix typo in trash spec
  e2e/test/scenarios/collections/trash.cy.spec.js
Labels: no-backport, .Team/AdminWebapp

#44795 Performance: partial data-permissions graph refactor
  e2e/test/scenarios/permissions/admin-permissions.cy.spec.js
  enterprise/backend/src/metabase_enterprise/advanced_permissions/models/connection_impersonation.clj
  enterprise/backend/src/metabase_enterprise/sandbox/models/group_table_access_policy.clj
  enterprise/frontend/src/metabase-enterprise/advanced_permissions/index.js
  enterprise/frontend/src/metabase-enterprise/sandboxes/index.js
  frontend/src/metabase-types/api/permissions.ts
  frontend/src/metabase/admin/permissions/permissions.js
  frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts
  frontend/src/metabase/admin/permissions/utils/graph/partial-updates.unit.spec.ts
  frontend/src/metabase/plugins/index.ts
  src/metabase/api/permissions.clj
  src/metabase/models/data_permissions.clj
  src/metabase/models/data_permissions/graph.clj
Labels: backport, .Team/AdminWebapp

#44543 docs - oracle note
  docs/databases/connections/oracle.md
Labels: Type:Documentation, backport

#45057 🤖 backported "docs - oracle note"
  docs/databases/connections/oracle.md
Labels: was-backported

#45056 🤖 backported "Performance: partial data-permissions graph refactor"
  e2e/test/scenarios/permissions/admin-permissions.cy.spec.js
  enterprise/backend/src/metabase_enterprise/advanced_permissions/models/connection_impersonation.clj
  enterprise/backend/src/metabase_enterprise/sandbox/models/group_table_access_policy.clj
  enterprise/frontend/src/metabase-enterprise/advanced_permissions/index.js
  enterprise/frontend/src/metabase-enterprise/sandboxes/index.js
  frontend/src/metabase-types/api/permissions.ts
  frontend/src/metabase/admin/permissions/permissions.js
  frontend/src/metabase/admin/permissions/utils/graph/partial-updates.ts
  frontend/src/metabase/admin/permissions/utils/graph/partial-updates.unit.spec.ts
  frontend/src/metabase/plugins/index.ts
  src/metabase/api/permissions.clj
  src/metabase/models/data_permissions.clj
  src/metabase/models/data_permissions/graph.clj
Labels: was-backported

#44987 Fix #35954: SQL-converted question with field filter breaks filtered dashboard if reverted back to its editor version
  e2e/test/scenarios/filters-reproductions/dashboard-filters-with-question-revert.cy.spec.js
  frontend/src/metabase-lib/v1/parameters/utils/targets.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapperButton.tsx
  frontend/src/metabase/dashboard/components/DashCard/utils.ts
  frontend/src/metabase/dashboard/reducers.js
  frontend/src/metabase/entities/revisions.js
Labels: .CI & Tests, support/Repro, backport

#39804 Debug QP 2.0
  dev/src/dev/debug_qp.clj
  src/metabase/query_processor.clj
  src/metabase/query_processor/debug.clj
  src/metabase/query_processor/middleware/annotate.clj
  src/metabase/query_processor/preprocess.clj
Labels: .Team/QueryProcessor, no-backport

#45055 Add e2e tests for basic field remapping logic
  e2e/test/scenarios/admin/datamodel/datamodel.cy.spec.js
Labels: backport, .Team/QueryingComponents

#45001 Misc unrelated code cleanup from #45000, split into a different PR.
  modules/drivers/mongo/test/metabase/driver/mongo_test.clj
  src/metabase/models/permissions.clj
  src/metabase/query_processor/middleware/permissions.clj
  src/metabase/server/middleware/session.clj
  test/metabase/models/on_demand_test.clj
  test/metabase/query_processor/middleware/parameters/native_test.clj
  test/metabase/query_processor_test/parameters_test.clj
  test/metabase/test/data/users.clj
Labels: .Team/QueryProcessor, no-backport

#45071 🤖 backported "Add e2e tests for basic field remapping logic"
  e2e/test/scenarios/admin/datamodel/datamodel.cy.spec.js
Labels: was-backported

#45072 Test for #40775
  modules/drivers/redshift/test/metabase/driver/redshift_test.clj
  test/metabase/driver/postgres_test.clj
Labels: backport, .Team/QueryProcessor

#45075 🤖 backported "Test for #40775"
  modules/drivers/redshift/test/metabase/driver/redshift_test.clj
  test/metabase/driver/postgres_test.clj
Labels: was-backported

#44972 Repro #43216 - Questions based on a custom SQL query aren't updated
  e2e/support/helpers/e2e-command-palette-helpers.js
  e2e/test/scenarios/question-reproductions/reproductions-2.cy.spec.js
Labels: backport, .Team/QueryingComponents

#45065 🤖 backported "Fix #35954: SQL-converted question with field filter breaks filtered dashboard if reverted back to its editor version"
  e2e/test/scenarios/filters-reproductions/dashboard-filters-with-question-revert.cy.spec.js
  frontend/src/metabase-lib/v1/parameters/utils/targets.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.tsx
  frontend/src/metabase/dashboard/components/DashCard/utils.ts
  frontend/src/metabase/dashboard/reducers.js
  frontend/src/metabase/entities/revisions.js
Labels: was-backported

#45039 fix(sdk): Improve filter/summarize/notebook layouts
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/Filter.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/Notebook.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/components/Summarize.tsx
  frontend/src/metabase/css/core/flex.module.css
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeContent/SummarizeAggregationItemList.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeContent/SummarizeBreakoutColumnList.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeContent/SummarizeContent.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeContent/index.ts
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeSidebar.tsx
  frontend/src/metabase/querying/components/FilterContent/FilterSearchInput/FilterSearchInput.tsx
  frontend/src/metabase/querying/components/FilterModal/FilterModal.tsx
Labels: no-backport, .Team/Embedding

#44978 Add reproduction for "Entity picker surfaces recent questions that are not valid joins"
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
Labels: .CI & Tests, support/Repro, backport, .Team/QueryingComponents

#45083 Repro #42385 - Cover additional draft join scenario
  e2e/test/scenarios/joins/joins-reproductions.cy.spec.js
Labels: backport, .Team/QueryingComponents

#45030 Fix - Ellipsis tooltip cut off/not visible in GUI editor
  e2e/test/scenarios/dashboard-cards/dashboard-card-reproductions.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
  frontend/src/metabase/components/Breadcrumbs/Breadcrumbs.jsx
  frontend/src/metabase/core/components/Ellipsified/Ellipsified.tsx
  frontend/src/metabase/reference/components/EditableReferenceHeader.jsx
  frontend/src/metabase/reference/components/ReferenceHeader.jsx
  frontend/src/metabase/timelines/common/components/ModalHeader/ModalHeader.tsx
  frontend/src/metabase/timelines/questions/components/TimelineCard/TimelineCard.tsx
Labels: backport, .Team/QueryingComponents

#45087 🤖 backported "Add reproduction for "Entity picker surfaces recent questions that are not valid joins""
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
Labels: was-backported

#45088 🤖 backported "Repro #42385 - Cover additional draft join scenario"
  e2e/test/scenarios/joins/joins-reproductions.cy.spec.js
Labels: was-backported

#45080 🤖 backported "Repro #43216 - Questions based on a custom SQL query aren't updated"
  e2e/support/helpers/e2e-command-palette-helpers.js
  e2e/test/scenarios/question-reproductions/reproductions-2.cy.spec.js
Labels: was-backported

#44488 Update light theme style
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_Dark_Theme_Default.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_Dark_Theme_No_Background_Default.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_Dark_Theme_No_Background_Scroll.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_Dark_Theme_Scroll.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_Light_Theme_Default.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_Light_Theme_No_Background_Default.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_Light_Theme_No_Background_Scroll.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_Light_Theme_Scroll.png
  frontend/src/metabase/components/ExplicitSize/ExplicitSize.tsx
  frontend/src/metabase/components/ExplicitSize/__mocks__/ExplicitSize.tsx
  frontend/src/metabase/components/ExplicitSize/__mocks__/index.ts
  frontend/src/metabase/components/ExplicitSize/context.ts
  frontend/src/metabase/components/ExplicitSize/index.ts
  frontend/src/metabase/lib/dom.js
  frontend/src/metabase/parameters/components/ParameterWidget/ParameterWidget.styled.ts
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.module.css
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.styled.tsx
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardView.stories.tsx
  loki.config.js
  package.json
  yarn.lock
Labels: no-backport, .Team/Embedding

#45044 fix(sdk): modify `Custom column` widget in notebook to conform to some styles
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions/ExpressionEditorSuggestions.styled.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx
  frontend/src/metabase/ui/components/inputs/Input/Input.styled.tsx
Labels: no-backport, .Team/Embedding

#44885 Support duplicate prefixes in long column names for CSV uploads
  src/metabase/upload.clj
  test/metabase/upload_test.clj
Labels: backport, .Team/BackendComponents

#45050 [perf] Add caching on `dashboard_load_id`; reusable MetadataProviders
  src/metabase/api/dashboard.clj
  src/metabase/lib/metadata/jvm.clj
  test/metabase/api/dashboard_test.clj
Labels: backport, .Team/QueryProcessor

#45045 Only check create-queries perms when fetching DB/schema metadata
  enterprise/backend/src/metabase_enterprise/advanced_permissions/common.clj
  src/metabase/api/database.clj
  src/metabase/models/database.clj
  test/metabase/api/database_test.clj
Labels: backport, .Team/AdminWebapp

#45094 🤖 backported "[perf] Add caching on `dashboard_load_id`; reusable MetadataProviders"
  src/metabase/api/dashboard.clj
  src/metabase/lib/metadata/jvm.clj
  test/metabase/api/dashboard_test.clj
Labels: was-backported

#45096 🤖 backported "[MBQL lib] Allow a space in datetime literal strings"
  src/metabase/shared/util/internal/time_common.cljc
  test/metabase/legacy_mbql/schema_test.cljc
  test/metabase/lib/expression_test.cljc
Labels: was-backported

#45092 🤖 backported "Support duplicate prefixes in long column names for CSV uploads"
  src/metabase/upload.clj
  test/metabase/upload_test.clj
Labels: .Team/BackendComponents, was-backported

#44332 Auto request review workflow
  .github/auto_request_review.yml
  .github/workflows/auto-request-review.yml
Labels: backport, .Team/BackendComponents

#45099 🤖 backported "Auto request review workflow"
  .github/auto_request_review.yml
  .github/workflows/auto-request-review.yml
Labels: was-backported

#44941 fix night theme png downloads
  frontend/src/metabase/dashboard/components/DashCard/DashCard.styled.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/query_builder/actions/downloading.ts
Labels: backport, .Team/DashViz

#45101 docs - add note about permissions update
  docs/permissions/data.md
  docs/permissions/no-self-service-deprecation.md
Labels: Type:Documentation, backport

#45095 Optimize: compute chart title href only on mouseenter and focus
  e2e/test/scenarios/dashboard/title-drill.cy.spec.js
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/visualizations/components/ChartCaption.tsx
  frontend/src/metabase/visualizations/components/ChartCaption.unit.spec.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
  frontend/src/metabase/visualizations/components/legend/LegendCaption.jsx
  frontend/src/metabase/visualizations/components/legend/LegendLabel.tsx
  frontend/src/metabase/visualizations/types/visualization.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/CartesianChart.tsx
  frontend/src/metabase/visualizations/visualizations/Funnel/Funnel.tsx
  frontend/src/metabase/visualizations/visualizations/Funnel/Funnel.unit.spec.jsx
  frontend/src/metabase/visualizations/visualizations/RowChart/RowChart.tsx
Labels: backport, .Team/QueryingComponents

#45106 Update SDK version to 0.1.16
  enterprise/frontend/src/embedding-sdk/CHANGELOG.md
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: no-backport

#45100 🤖 backported "fix night theme png downloads"
  frontend/src/metabase/dashboard/components/DashCard/DashCard.styled.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/query_builder/actions/downloading.ts
Labels: was-backported

#45051 Adds plan-alias info to premium-embedding-token and exposes it in troubleshooting
  src/metabase/public_settings/premium_features.clj
  src/metabase/troubleshooting.clj
Labels: backport, .Team/AdminWebapp

#45008 Support compiling SQL with inlined parameters directly
  docs/developers-guide/driver-changelog.md
  enterprise/backend/src/metabase_enterprise/llm/tasks/describe_question.clj
  modules/drivers/athena/src/metabase/driver/athena.clj
  modules/drivers/athena/test/metabase/driver/athena_test.clj
  modules/drivers/athena/test/metabase/test/data/athena.clj
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj
  modules/drivers/druid-jdbc/src/metabase/driver/druid_jdbc.clj
  modules/drivers/oracle/src/metabase/driver/oracle.clj
  modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj
  modules/drivers/presto-jdbc/test/metabase/driver/presto_jdbc_test.clj
  modules/drivers/snowflake/test/metabase/test/data/snowflake.clj
  modules/drivers/sparksql/src/metabase/driver/hive_like.clj
  modules/drivers/sparksql/src/metabase/driver/sparksql.clj
  modules/drivers/sparksql/test/metabase/driver/sparksql_test.clj
  modules/drivers/sparksql/test/metabase/test/data/sparksql.clj
  modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj
  modules/drivers/sqlserver/test/metabase/driver/sqlserver_test.clj
  src/metabase/api/dataset.clj
  src/metabase/driver.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql.clj
  src/metabase/driver/sql/query_processor.clj
  src/metabase/driver/sql/util/unprepare.clj
  src/metabase/query_processor/compile.clj
  src/metabase/query_processor/execute.clj
  src/metabase/query_processor/middleware/splice_params_in_response.clj
  src/metabase/query_processor/postprocess.clj
  test/metabase/actions/test_util.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/driver/sql/query_processor_test.clj
  test/metabase/driver/sql/util/unprepare_test.clj
  test/metabase/driver/sql_jdbc_test.clj
  test/metabase/query_processor/execute_test.clj
  test/metabase/query_processor/middleware/splice_params_in_response_test.clj
  test/metabase/query_processor_test/expressions_test.clj
  test/metabase/query_processor_test/filter_test.clj
  test/metabase/query_processor_test/parameters_test.clj
Labels: .Team/QueryProcessor, no-backport

#45064 User Parameter Values Are Unique Per Dashboard
  resources/migrations/001_update_migrations.yaml
  src/metabase/models/user_parameter_value.clj
  src/metabase/query_processor/dashboard.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/models/user_parameter_value_test.clj
Labels: backport, .Team/DashViz

#45067 Ignore unknown columns when reverting cards and dashboards
  src/metabase/api/revision.clj
  src/metabase/models/dashboard.clj
  src/metabase/models/revision.clj
  test/metabase/api/revision_test.clj
  test/metabase/models/revision_test.clj
Labels: backport, .Team/AdminWebapp

#45117 🤖 backported "User Parameter Values Are Unique Per Dashboard"
  resources/migrations/001_update_migrations.yaml
  src/metabase/models/user_parameter_value.clj
  src/metabase/query_processor/dashboard.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/models/user_parameter_value_test.clj
Labels: was-backported

#45038 Reproduce #27643: Field filter linked to Boolean column causes an error when used in Embedding
  e2e/support/helpers/e2e-setup-helpers.js
  e2e/test/scenarios/embedding/embedding-reproductions.cy.spec.js
Labels: .CI & Tests, support/Repro, backport, .Team/Embedding

#45121 🤖 backported "Reproduce #27643: Field filter linked to Boolean column causes an error when used in Embedding"
  e2e/support/helpers/e2e-setup-helpers.js
  e2e/test/scenarios/embedding/embedding-reproductions.cy.spec.js
Labels: was-backported

#45093 [serdes] a bit more descriptive exceptions
  src/metabase/models/serialization.clj
Labels: no-backport, .Team/BackendComponents

#44970 Pass correct redux action name
  frontend/src/metabase/dashboard/actions/parameters.ts
Labels: backport, .Team/QueryingComponents

#45126 🤖 backported "Pass correct redux action name"
  frontend/src/metabase/dashboard/actions/parameters.ts
Labels: was-backported

#45113 E2E repro for "Editing Column description of Model is confusing if it contains aggregations"
  e2e/test/scenarios/models/reproductions.cy.spec.ts
Labels: support/Repro, backport, .Team/QueryingComponents

#45066 [repro] Add e2e repro for Zoom In on pivot tables row headers
  e2e/test/scenarios/visualizations-tabular/pivot_tables.cy.spec.js
Labels: support/Repro, .Team/QueryProcessor, no-backport

#45091 Refine the reproduction for " Entity picker surfaces recent questions that are not valid joins" (#44974)
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
Labels: .CI & Tests, support/Repro, backport, .Team/QueryingComponents

#44931 Fix actions menu permission checks
  frontend/src/metabase-lib/v1/metadata/utils/models.ts
  frontend/src/metabase-lib/v1/metadata/utils/models.unit.spec.js
  frontend/src/metabase/query_builder/actions/models.js
  frontend/src/metabase/query_builder/components/view/ViewHeader/ViewTitleHeader.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionActions/QuestionActions.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionActions/QuestionActions.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/ViewTitleHeaderRightSide/ViewTitleHeaderRightSide.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/DatasetManagementSection/DatasetManagementSection.jsx
Labels: backport

#45139 🤖 backported "Refine the reproduction for " Entity picker surfaces recent questions that are not valid joins" (#44974)"
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
Labels: was-backported

#44851 [49 Backport] Catch exceptions from driver/database-supports? outside driver code and Memoize driver.u/supports? (#44719) (#44804)
  .clj-kondo/config.edn
  enterprise/backend/src/metabase_enterprise/advanced_permissions/driver/impersonation.clj
  enterprise/backend/test/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions_test.clj
  src/metabase/actions.clj
  src/metabase/api/card.clj
  src/metabase/api/database.clj
  src/metabase/api/table.clj
  src/metabase/automagic_dashboards/combination.clj
  src/metabase/db/metadata_queries.clj
  src/metabase/driver/sql_jdbc/sync/describe_database.clj
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
  src/metabase/driver/util.clj
  src/metabase/models/database.clj
  src/metabase/query_processor/middleware/add_implicit_joins.clj
  src/metabase/query_processor/middleware/check_features.clj
  src/metabase/query_processor/middleware/parameters/native.clj
  src/metabase/query_processor/middleware/results_metadata.clj
  src/metabase/query_processor/timezone.clj
  src/metabase/sync/fetch_metadata.clj
  src/metabase/sync/sync_metadata/fields.clj
  src/metabase/sync/sync_metadata/fields/our_metadata.clj
  src/metabase/sync/sync_metadata/fks.clj
  src/metabase/sync/sync_metadata/indexes.clj
  src/metabase/sync/sync_metadata/sync_table_privileges.clj
  src/metabase/upload.clj
  test/metabase/api/database_test.clj
  test/metabase/db/metadata_queries_test.clj
  test/metabase/driver/sql_jdbc/sync/describe_table_test.clj
  test/metabase/driver/util_test.clj
  test/metabase/models/database_test.clj
  test/metabase/models/model_index_test.clj
  test/metabase/query_processor/middleware/parameters/mbql_test.clj
  test/metabase/query_processor/test_util.clj
  test/metabase/query_processor_test/advanced_math_test.clj
  test/metabase/query_processor_test/date_bucketing_test.clj
  test/metabase/query_processor_test/date_time_zone_functions_test.clj
  test/metabase/query_processor_test/timezones_test.clj
  test/metabase/test/data/dataset_definition_test.clj
  test/metabase/upload_test.clj
Labels: .Team/BackendComponents

#45120 Fix Wrong Migration IDs for User Parameter Values Migration
  resources/migrations/001_update_migrations.yaml
Labels: no-backport, .Team/DashViz

#45068 fix: param-fields when native model is aggregated
  e2e/test/scenarios/filters-reproductions/dashboard-filters-reproductions.cy.spec.js
  src/metabase/api/dashboard.clj
  src/metabase/models/params.clj
  test/metabase/models/params_test.clj
Labels: backport, .Team/QueryProcessor

#45143 Repro #39504: Pivot table disappears
  e2e/test/scenarios/visualizations-tabular/pivot_tables.cy.spec.js
Labels: .CI & Tests, support/Repro, no-backport

#45140 🤖 backported "Fix actions menu permission checks"
  frontend/src/metabase-lib/v1/metadata/utils/models.ts
  frontend/src/metabase-lib/v1/metadata/utils/models.unit.spec.js
  frontend/src/metabase/query_builder/actions/models.js
  frontend/src/metabase/query_builder/components/view/ViewHeader/ViewHeader.jsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionActions/QuestionActions.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionActions/QuestionActions.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/DatasetManagementSection/DatasetManagementSection.jsx
Labels: was-backported

#45131 🤖 backported "E2E repro for "Editing Column description of Model is confusing if it contains aggregations""
  e2e/test/scenarios/models/reproductions.cy.spec.ts
Labels: was-backported

#44585 Fix/logs keep pooling after unmount
  frontend/src/metabase/admin/tasks/components/Logs/Logs.unit.spec.tsx
  frontend/src/metabase/admin/tasks/components/Logs/hooks.ts
Labels: External

#45158 🍒 Fix/logs keep pooling after unmount (#44585)
  frontend/src/metabase/admin/tasks/components/Logs/Logs.unit.spec.tsx
  frontend/src/metabase/admin/tasks/components/Logs/hooks.ts
Labels: .Team/QueryingComponents, was-backported

#45152 🍒 Backport pivot tables reproductions
  e2e/test/scenarios/visualizations-tabular/pivot_tables.cy.spec.js
  frontend/src/metabase/visualizations/visualizations/PivotTable/settings.ts
Labels: Type:Tech Debt, .CI & Tests, .Team/QueryingComponents, was-backported

#44363 logic to handle downloads url parameter
  e2e/test/scenarios/embedding/embedding-questions.cy.spec.js
  e2e/test/scenarios/embedding/embedding-snippets.cy.spec.js
  e2e/test/scenarios/embedding/shared/embedding-snippets.js
  e2e/test/scenarios/sharing/public-sharing-embed-button-behavior.cy.spec.js
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.tsx
  enterprise/frontend/src/metabase-enterprise/resource_downloads/resource_downloads_plugin.ts
  enterprise/frontend/src/metabase-enterprise/resource_downloads/tests/common.unit.spec.ts
  enterprise/frontend/src/metabase-enterprise/resource_downloads/tests/enterprise.unit.spec.ts
  enterprise/frontend/src/metabase-enterprise/resource_downloads/tests/premium.unit.spec.ts
  enterprise/frontend/src/metabase-enterprise/resource_downloads/tests/setup.ts
  frontend/src/metabase/dashboard/constants.ts
  frontend/src/metabase/dashboard/hooks/use-dashboard-url-params.ts
  frontend/src/metabase/dashboard/types/display-options.ts
  frontend/src/metabase/dashboard/types/embed-display-options.ts
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/AppearanceSettings.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/ServerEmbedCodePane.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/StaticEmbedSetupPane.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/config.ts
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/tests/premium.unit.spec.tsx
  frontend/src/metabase/public/constants.ts
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboard.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardPage.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardView.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestionView.tsx
  frontend/src/metabase/public/hooks/use-embed-frame-options.ts
  frontend/src/metabase/public/lib/analytics.ts
  frontend/src/metabase/public/lib/types.ts
Labels: .Team/Embedding

#44955 [notification] New method: `channel/can-connect?`
  .clj-kondo/config.edn
  .clj-kondo/src/hooks/clojure/test.clj
  src/metabase/channel/core.clj
  src/metabase/channel/email.clj
  src/metabase/channel/http.clj
  src/metabase/channel/shared.clj
  src/metabase/channel/slack.clj
  src/metabase/pulse.clj
  src/metabase/util/malli/schema.clj
  test/metabase/channel/email_test.clj
  test/metabase/channel/http_test.clj
  test/metabase/pulse/test_util.clj
  test/metabase/pulse_test.clj
Labels: .Team/BackendComponents

#45177 fix serialization errors we get on big old databases
  src/metabase/models/card.clj
  src/metabase/models/interface.clj
  src/metabase/models/serialization.clj
Labels: no-backport, .Team/BackendComponents

#44999 Remove field refs from DatasetEditor
  frontend/src/metabase-lib/v1/Question.ts
  frontend/src/metabase-lib/v1/metadata/utils/models.ts
  frontend/src/metabase-lib/v1/queries/utils/dataset.ts
  frontend/src/metabase-lib/v1/queries/utils/field-ref.js
  frontend/src/metabase/query_builder/actions/models.js
  frontend/src/metabase/query_builder/actions/querying.js
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.unit.spec.tsx
  frontend/src/metabase/query_builder/reducers.js
  frontend/src/metabase/query_builder/selectors.js
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/TableColumnPanel/TableColumnPanel.tsx
  src/metabase/query_processor/middleware/results_metadata.clj
Labels: backport, .Team/QueryingComponents

#45062 Show alert sending time in alert form
  e2e/test/scenarios/sharing/alert/email-alert.cy.spec.js
  frontend/src/metabase/query_builder/components/AlertModals/AlertModals.jsx
Labels: no-backport, .Team/DashViz

#45162 Add INFO log for each table before JSON unfolding during field sync
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
Labels: backport, .Team/BackendComponents

#45160 Skip fingerprinting or scanning field values for fields with base-type=type/Collection
  src/metabase/db/query.clj
  src/metabase/models/field_values.clj
  src/metabase/sync/analyze/fingerprint.clj
  test/metabase/models/field_values_test.clj
  test/metabase/sync/analyze/fingerprint_test.clj
Labels: backport, .Team/BackendComponents

#44863 fix: limit xrays on agg models to source fields
  src/metabase/xrays/automagic_dashboards/combination.clj
  src/metabase/xrays/automagic_dashboards/core.clj
  test/metabase/xrays/automagic_dashboards/core_test.clj
Labels: backport, .Team/QueryProcessor

#45150 🤖 backported "fix: param-fields when native model is aggregated"
  e2e/test/scenarios/filters-reproductions/dashboard-filters-reproductions.cy.spec.js
  src/metabase/api/dashboard.clj
  src/metabase/models/params.clj
  test/metabase/models/params_test.clj
Labels: was-backported

#45180 Remove field ref matching from `table.columns`
  e2e/test/scenarios/models/reproductions.cy.spec.ts
  frontend/src/metabase-lib/v1/queries/utils/dataset.ts
  frontend/src/metabase-lib/v1/queries/utils/dataset.unit.spec.ts
  frontend/src/metabase-lib/v1/queries/utils/get-column-key.ts
  frontend/src/metabase-lib/v1/references.ts
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase-types/api/mocks/card.ts
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/TableColumnPanel/TableColumnPanel.unit.spec.tsx
  frontend/src/metabase/visualizations/lib/settings/column.js
  frontend/src/metabase/visualizations/lib/sync-settings.ts
  frontend/src/metabase/visualizations/lib/sync-settings.unit.spec.ts
Labels: backport, .Team/QueryingComponents

#44866 Allow defective duplicate fields
  enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj
  resources/migrations/001_update_migrations.yaml
  src/metabase/cmd/copy.clj
  src/metabase/models/database.clj
  src/metabase/models/field.clj
  src/metabase/models/table.clj
  test/metabase/cmd/load_from_h2_test.clj
  test/metabase/db/schema_migrations_test.clj
  test/metabase/db/schema_migrations_test/impl.clj
  test/metabase/native_query_analyzer_test.clj
Labels: backport, .Team/BackendComponents

#45119 🤖 backported "Ignore unknown columns when reverting cards and dashboards"
  src/metabase/api/revision.clj
  src/metabase/models/dashboard.clj
  src/metabase/models/revision.clj
  test/metabase/api/revision_test.clj
  test/metabase/models/revision_test.clj
Labels: was-backported

#45184 🤖 backported "Remove field refs from DatasetEditor"
  frontend/src/metabase-lib/v1/Question.ts
  frontend/src/metabase-lib/v1/metadata/utils/models.ts
  frontend/src/metabase-lib/v1/queries/utils/dataset.ts
  frontend/src/metabase-lib/v1/queries/utils/field-ref.js
  frontend/src/metabase-types/api/modelIndexes.ts
  frontend/src/metabase/query_builder/actions/models.js
  frontend/src/metabase/query_builder/actions/querying.js
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.jsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.unit.spec.tsx
  frontend/src/metabase/query_builder/reducers.js
  frontend/src/metabase/query_builder/selectors.js
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/TableColumnPanel/TableColumnPanel.tsx
  src/metabase/query_processor/middleware/results_metadata.clj
Labels: was-backported

#45187 🤖 backported "Add INFO log for each table before JSON unfolding during field sync"
  src/metabase/driver/sql_jdbc/sync/describe_table.clj
Labels: was-backported

#45196 🤖 backported "Allow defective duplicate fields"
  enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj
  resources/migrations/001_update_migrations.yaml
  src/metabase/cmd/copy.clj
  src/metabase/models/database.clj
  src/metabase/models/field.clj
  src/metabase/models/table.clj
  test/metabase/cmd/load_from_h2_test.clj
  test/metabase/db/schema_migrations_test.clj
  test/metabase/db/schema_migrations_test/impl.clj
  test/metabase/native_query_analyzer_test.clj
Labels: was-backported

#45183 refactor: drop unused js file
  frontend/src/metabase/dashboard/actions/ui.js
Labels: backport, .Team/QueryingComponents

#45203 🤖 backported "refactor: drop unused js file"
  frontend/src/metabase/dashboard/actions/ui.js
Labels: was-backported

#45104 Use Mantine Components for `QueryDownloadWidget` and `QueryDownloadPopover`
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/query_builder/components/QueryDownloadPopover/DownloadButton.module.css
  frontend/src/metabase/query_builder/components/QueryDownloadPopover/DownloadButton.tsx
  frontend/src/metabase/query_builder/components/QueryDownloadPopover/QueryDownloadPopover.styled.tsx
  frontend/src/metabase/query_builder/components/QueryDownloadPopover/QueryDownloadPopover.tsx
  frontend/src/metabase/query_builder/components/QueryDownloadPopover/QueryDownloadPopover.unit.spec.tsx
  frontend/src/metabase/query_builder/components/QueryDownloadPopover/index.ts
  frontend/src/metabase/query_builder/components/QueryDownloadPopover/use-download-data.ts
  frontend/src/metabase/query_builder/components/QueryDownloadPopover/utils.ts
  frontend/src/metabase/query_builder/components/QueryDownloadWidget/QueryDownloadWidget.tsx
Labels: no-backport

#45122 ci: pin replayio version
  .github/actions/prepare-cypress/action.yml
Labels: backport, .Team/QueryingComponents

#45194 docs(sdk): Document how to reload Metabase embedding SDK components
  enterprise/frontend/src/embedding-sdk/README.md
Labels: backport, .Team/Embedding

#45212 🤖 backported "docs(sdk): Document how to reload Metabase embedding SDK components"
  enterprise/frontend/src/embedding-sdk/README.md
Labels: was-backported

#45167 Do not collide "no results" with "running the query"
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
  frontend/src/metabase/query_builder/components/VisualizationResult.jsx
Labels: .CI & Tests, support/Repro, backport, .Team/QueryingComponents

#45215 Alphabetize EE routes
  enterprise/backend/src/metabase_enterprise/api/routes.clj
Labels: no-backport, .Team/BackendComponents

#45058 Fix Menu button in admin app on mobile view
  e2e/test/scenarios/admin/admin-reproductions.cy.spec.js
  frontend/src/metabase/nav/components/AdminNavbar/AdminNavbar.module.css
  frontend/src/metabase/nav/components/AdminNavbar/AdminNavbar.tsx
Labels: backport, .Team/AdminWebapp

#45213 🤖 backported "Do not collide "no results" with "running the query""
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
  frontend/src/metabase/query_builder/components/VisualizationResult.jsx
Labels: was-backported

#45190 docs - add 50.10 to list of versions
  docs/releases.md
Labels: Type:Documentation, backport

#45219 add note about MySQL and MariaDB re: offset
  docs/questions/query-builder/expressions-list.md
  docs/questions/query-builder/expressions/offset.md
Labels: Type:Documentation, backport

#45226 🤖 backported "docs - add 50.10 to list of versions"
  docs/releases.md
Labels: was-backported

#45227 🤖 backported "add note about MySQL and MariaDB re: offset"
  docs/questions/query-builder/expressions-list.md
  docs/questions/query-builder/expressions/offset.md
Labels: was-backported

#45218 Use `filled` button variant for the "Duplicate entity" modal
  frontend/src/metabase/forms/components/FormSubmitButton/FormSubmitButton.tsx
Labels: backport, .Team/QueryingComponents

#45228 🤖 backported "Use `filled` button variant for the "Duplicate entity" modal"
  frontend/src/metabase/forms/components/FormSubmitButton/FormSubmitButton.tsx
Labels: was-backported

#45148 Fix #44754: qbnewq modal can't be dismissed with keyboard
  e2e/test/scenarios/onboarding/home/homepage.cy.spec.js
  frontend/src/metabase/query_builder/components/SavedQuestionIntroModal.tsx
Labels: support/Repro, backport, .Team/QueryingComponents

#45189 🤖 backported "Skip fingerprinting or scanning field values for fields with base-type=type/Collection"
  src/metabase/db/query.clj
  src/metabase/models/field_values.clj
  src/metabase/sync/analyze/fingerprint.clj
  test/metabase/models/field_values_test.clj
  test/metabase/sync/analyze/fingerprint_test.clj
Labels: was-backported

#45229 Don't return an archived dashboard as the most recently viewed dashboard
  src/metabase/models/recent_views.clj
  test/metabase/api/activity_test.clj
  test/metabase/models/recent_views_test.clj
Labels: backport, .Team/AdminWebapp

#45239 🤖 backported "Require Card ref permissions to use Card reference template tag in native query "
  modules/drivers/mongo/src/metabase/driver/mongo.clj
  src/metabase/driver.clj
  src/metabase/driver/common/parameters/values.clj
  src/metabase/driver/sql.clj
  src/metabase/lib/schema.cljc
  src/metabase/models/query/permissions.clj
  test/metabase/driver/common/parameters/values_test.clj
  test/metabase/models/query/permissions_test.clj
  test/metabase/query_processor/middleware/parameters/native_test.clj
  test/metabase/query_processor/middleware/parameters_test.clj
  test/metabase/query_processor_test/parameters_test.clj
  test/metabase/test.clj
  test/metabase/test/data/interface.clj
  test/metabase/test/data/sql.clj
Labels: was-backported

#45110 Batch permission updates with many tables
  src/metabase/models/data_permissions.clj
Labels: backport, .Team/AdminWebapp

#45243 🤖 backported "Batch permission updates with many tables"
  src/metabase/models/data_permissions.clj
Labels: was-backported

#45217 🤖 backported "Fix Menu button in admin app on mobile view"
  e2e/test/scenarios/admin/admin-reproductions.cy.spec.js
  frontend/src/metabase/nav/components/AdminNavbar/AdminNavbar.module.css
  frontend/src/metabase/nav/components/AdminNavbar/AdminNavbar.tsx
Labels: was-backported

#45244 docs - note on info schema
  docs/databases/connections/redshift.md
Labels: Type:Documentation, backport

#45211 🤖 backported "ci: pin replayio version"
  .github/actions/prepare-cypress/action.yml
Labels: was-backported

#45250 🤖 backported "docs - note on info schema"
  docs/databases/connections/redshift.md
Labels: was-backported

#44447 Remove enable nested queries
  e2e/test/scenarios/dashboard/dashboard-reproductions.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/onboarding/command-palette.cy.spec.js
  e2e/test/scenarios/onboarding/home/homepage.cy.spec.js
  e2e/test/scenarios/search/recently-viewed.cy.spec.js
  e2e/test/scenarios/search/search.cy.spec.js
  frontend/src/metabase/admin/settings/selectors.js
  frontend/test/__support__/server-mocks/activity.ts
  src/metabase/public_settings.clj
  test/metabase/api/database_test.clj
  test/metabase/query_processor/middleware/fetch_source_query_test.clj
Labels: no-backport, .Team/AdminWebapp
