Repository metabase/metabase, pull requests merged in 2024-05, with the labels that each got.

#41856 Add kondo hook so LSP can jump to driver definition
  .clj-kondo/config.edn
  .clj-kondo/hooks/metabase/driver.clj
Labels: .Team/QueryProcessor, no-backport

#41864 Fix Snowflake/Redshift filtering on date for timestamp with time zone columns
  modules/drivers/presto-jdbc/test/metabase/driver/presto_jdbc_test.clj
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
  modules/drivers/snowflake/test/metabase/test/data/snowflake.clj
  modules/drivers/vertica/src/metabase/driver/vertica.clj
  src/metabase/driver/sql/parameters/substitution.clj
  src/metabase/driver/sql_jdbc/execute/legacy_impl.clj
  test/metabase/driver/sql/parameters/substitute_test.clj
  test/metabase/query_processor/test_util.clj
  test/metabase/query_processor_test/date_bucketing_test.clj
  test/metabase/query_processor_test/date_time_zone_functions_test.clj
  test/metabase/query_processor_test/filter_test.clj
  test/metabase/query_processor_test/parameters_test.clj
  test/metabase/query_processor_test/timezones_test.clj
  test/metabase/test/data/sql/ddl.clj
Labels: backport, .Team/QueryProcessor

#41006 Capture card's last_used_at
  .clj-kondo/hooks/clojure/test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/query_processor/middleware/update_used_cards_test.clj
  resources/migrations/001_update_migrations.yaml
  src/metabase/lib/metadata.cljc
  src/metabase/lib/metadata/cached_provider.cljc
  src/metabase/lib/metadata/composed_provider.cljc
  src/metabase/lib/metadata/invocation_tracker.cljc
  src/metabase/lib/metadata/jvm.clj
  src/metabase/lib/metadata/protocols.cljc
  src/metabase/lib/schema/metadata.cljc
  src/metabase/models/card.clj
  src/metabase/query_processor/execute.clj
  src/metabase/query_processor/middleware/process_userland_query.clj
  src/metabase/query_processor/middleware/update_used_cards.clj
  src/metabase/query_processor/store.clj
  src/metabase/query_processor/util.clj
  test/metabase/api/card_test.clj
  test/metabase/dashboard_subscription_test.clj
  test/metabase/lib/metadata/invocation_tracker_test.clj
  test/metabase/lib/metadata/jvm_test.clj
  test/metabase/models/legacy_metric_test.clj
  test/metabase/query_processor/middleware/process_userland_query_test.clj
  test/metabase/query_processor/middleware/update_used_cards_test.clj
Labels: no-backport, .Team/BackendComponents

#42047 Add cancelation exception for vertica
  src/metabase/driver/sql_jdbc/execute.clj
Labels: Database/Vertica, backport, .Team/QueryProcessor

#41578 Notebook text extraction shortcut
  e2e/test/scenarios/custom-column/cc-shortcuts-combine.cy.spec.js
  e2e/test/scenarios/custom-column/cc-shortcuts-extract.cy.spec.js
  frontend/src/metabase-lib/extractions.ts
  frontend/src/metabase-lib/index.ts
  frontend/src/metabase/common/components/QueryColumnPicker/QueryColumnPicker.tsx
  frontend/src/metabase/core/components/AccordionList/AccordionList.jsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions/ExpressionEditorSuggestions.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx
  frontend/src/metabase/query_builder/components/expressions/ExtractColumn/ExtractColumn.module.css
  frontend/src/metabase/query_builder/components/expressions/ExtractColumn/ExtractColumn.tsx
  frontend/src/metabase/query_builder/components/expressions/ExtractColumn/index.tsx
  frontend/src/metabase/query_builder/components/expressions/ExtractColumn/util.ts
  frontend/src/metabase/query_builder/components/expressions/ExtractColumn/util.unit.spec.ts
  frontend/src/metabase/ui/components/icons/Icon/icons/index.ts
  frontend/src/metabase/ui/components/icons/Icon/icons/split.svg
Labels: no-backport, .Team/QueryingComponents

#42051 Fix flaky dashboard subscription test
  e2e/test/scenarios/sharing/subscriptions.cy.spec.js
Labels: backport, .Team/DashViz

#42046 Fix flaky dashboard repro tests (issue 39863)
  e2e/test/scenarios/dashboard/reproductions/39863-redundant-queries-on-tab-change.cy.spec.js
Labels: backport, .Team/DashViz

#42065 Add string like filtering capabilities to filter widget
  e2e/test/scenarios/question/reproductions/42065-mongo-filter-by-id.cy.spec.js
  frontend/src/metabase-lib/column_types.ts
  frontend/src/metabase-lib/filter.ts
  frontend/src/metabase-lib/v1/parameters/utils/filters.js
  frontend/src/metabase/common/utils/columns.ts
  frontend/src/metabase/querying/components/FilterModal/ColumnFilterSection/ColumnFilterSection.tsx
  frontend/src/metabase/querying/components/FilterModal/utils/sorting.ts
  frontend/src/metabase/querying/components/FilterPicker/FilterPickerBody/FilterPickerBody.tsx
  frontend/src/metabase/querying/utils/drills/quick-filter-drill/quick-filter-drill.tsx
  src/metabase/lib/types/isa.cljc
Labels: Database/Mongo, support/Repro, backport, .Team/QueryProcessor

#42021 Combine columns
  docs/developers-guide/mbql-library-changelog.md
  e2e/test/scenarios/visualizations-tabular/drillthroughs/combine-column.cy.spec.js
  frontend/src/metabase-lib/drills.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/common/components/QueryColumnPicker/QueryColumnPicker.tsx
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/combine-columns-drill.tsx
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/components/ColumnAndSeparatorRow/ColumnAndSeparatorRow.module.css
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/components/ColumnAndSeparatorRow/ColumnAndSeparatorRow.tsx
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/components/ColumnAndSeparatorRow/index.ts
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/components/ColumnPicker/ColumnPicker.module.css
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/components/ColumnPicker/ColumnPicker.tsx
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/components/ColumnPicker/index.ts
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/components/CombineColumnsDrill/CombineColumnsDrill.tsx
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/components/CombineColumnsDrill/index.ts
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/components/Example/Example.module.css
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/components/Example/Example.tsx
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/components/Example/index.ts
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/components/index.ts
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/index.ts
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/types.ts
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/utils.ts
  frontend/src/metabase/querying/utils/drills/constants.ts
  frontend/src/metabase/ui/components/overlays/Popover/index.tsx
  frontend/src/metabase/ui/index.ts
  frontend/src/metabase/visualizations/components/ClickActions/utils.ts
  frontend/src/metabase/visualizations/types/click-actions.ts
Labels: visual, no-backport, .Team/QueryingComponents

#42106 FE metadata changes for metrics
  e2e/test/scenarios/models/models.cy.spec.js
  e2e/test/scenarios/question/nested.cy.spec.js
  frontend/src/metabase-lib/metadata.ts
  frontend/src/metabase/lib/schema/schema.unit.spec.js
  frontend/src/metabase/query_builder/actions/core/updateQuestion.ts
  frontend/src/metabase/query_builder/components/QueryVisualization.jsx
  frontend/src/metabase/query_builder/components/notebook/steps/DataStep/DataStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTablePicker/JoinTablePicker.tsx
  frontend/src/metabase/questions/actions.ts
  frontend/src/metabase/redux/metadata.js
  frontend/src/metabase/redux/metadata.unit.spec.js
  frontend/src/metabase/search/components/InfoText/InfoText.unit.spec.tsx
  src/metabase/lib/core.cljc
  src/metabase/lib/fe_util.cljc
  src/metabase/lib/js.cljs
  src/metabase/upload.clj
  test/metabase/lib/fe_util_test.cljc
Labels: no-backport, .Team/QueryingComponents

#42084 [docs] use SSO for MFA
  docs/people-and-groups/start.md
Labels: Type:Documentation, backport

#42083 [docs] surface dashboard width in toc
  docs/dashboards/introduction.md
Labels: Type:Documentation, backport

#42072 [docs] Add "check table visibility" to troubleshooting guide
  docs/troubleshooting-guide/cant-see-tables.md
Labels: Type:Documentation, backport

#42064 [docs] Clarify casting
  docs/data-modeling/field-types.md
  docs/data-modeling/metadata-editing.md
Labels: Type:Documentation, backport

#42080 [docs] Custom destinations in static embedding
  docs/embedding/static-embedding.md
Labels: Type:Documentation, backport

#42077 [docs] Use SQL questions as sources for other questions
  docs/data-modeling/images/turn-into-a-model.png
  docs/questions/images/explore-results.png
  docs/questions/native-editor/writing-sql.md
Labels: Type:Documentation, backport

#41672 support unpinning line charts from zero, pinning scatter charts to zero
  .loki/reference/chrome_laptop_static_viz_ComboChart_Line_Unpin_From_Zero.png
  .loki/reference/chrome_laptop_static_viz_ScatterPlot_Pin_To_Zero.png
  e2e/test/scenarios/visualizations-charts/line_chart.cy.spec.js
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/settings.ts
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/line-unpin-from-zero.json
  frontend/src/metabase/static-viz/components/ScatterPlot/ScatterPlot.stories.tsx
  frontend/src/metabase/static-viz/components/ScatterPlot/stories-data/index.ts
  frontend/src/metabase/static-viz/components/ScatterPlot/stories-data/pin-to-zero.json
  frontend/src/metabase/visualizations/echarts/cartesian/option/axis.ts
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/src/metabase/visualizations/lib/settings/graph.unit.spec.js
  frontend/src/metabase/visualizations/shared/settings/cartesian-chart.ts
Labels: visual, no-backport, .Team/DashViz

#42050 Expose theme property to metabase provider in embedding SDK
  enterprise/frontend/src/embedding-sdk/components/public/MetabaseProvider.tsx
  enterprise/frontend/src/embedding-sdk/index.ts
  enterprise/frontend/src/embedding-sdk/types/index.ts
  enterprise/frontend/src/embedding-sdk/types/theme.ts
  frontend/src/metabase/ui/components/theme/ThemeProvider/ThemeProvider.tsx
Labels: no-backport, .Team/Embedding

#42112 backported "Faster driver/describe-database for redshift"
  enterprise/backend/test/metabase_enterprise/advanced_permissions/driver/impersonation_test.clj
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  modules/drivers/redshift/test/metabase/driver/redshift_test.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql_jdbc/sync/describe_database.clj
  test/metabase/sync/sync_metadata/comments_test.clj
  test/metabase/sync/sync_metadata/sync_table_privileges_test.clj
Labels: no-backport, .Team/BackendComponents, was-backported

#42102 Fix typo in the file name
  frontend/src/metabase/parameters/components/RequiredParamToggle/RequiredParamToggle.styled.tsx
  frontend/src/metabase/parameters/components/RequiredParamToggle/RequiredParamToggle.tsx
Labels: backport, .Team/QueryingComponents

#42145 Comment out failing snowflake test sync-dynamic-tables-test
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
Labels: backport, .Team/BackendComponents

#42120 Skip flaky test
  e2e/test/scenarios/question/reproductions/42065-mongo-filter-by-id.cy.spec.js
Labels: .Team/QueryProcessor, no-backport

#42140 Fix mongo OOM during sync
  modules/drivers/mongo/src/metabase/driver/mongo/util.clj
  modules/drivers/mongo/test/metabase/driver/mongo/util_test.clj
Labels: backport, .Team/BackendComponents

#42149 Fix/update the hard coded description field in containers action
  .github/actions/e2e-prepare-containers/action.yml
Labels: .CI & Tests, no-backport, :broom:, .Team/QueryingComponents

#42142 Verify Metabase's theme is merged with user-supplied theme overrides
  frontend/src/metabase/ui/components/theme/ThemeProvider/ThemeProvider.unit.spec.tsx
Labels: no-backport, .Team/Embedding

#42162 Enable Mongo tests to run in the stress-test action
  .github/workflows/e2e-stress-test-flake-fix.yml
Labels: .CI & Tests, no-backport, .Team/QueryingComponents

#42117 41994 command pallet search descriptions
  e2e/test/scenarios/onboarding/command-palette.cy.spec.js
  frontend/src/metabase/palette/components/PaletteResultItem.tsx
  frontend/src/metabase/palette/components/PaletteResults.tsx
  frontend/src/metabase/palette/components/PaletteResults.unit.spec.tsx
  frontend/src/metabase/palette/components/PaletteResultsList.tsx
  frontend/src/metabase/palette/hooks/useCommandPalette.tsx
  frontend/src/metabase/palette/types.ts
  frontend/src/metabase/palette/utils.ts
  frontend/src/metabase/palette/utils.unit.spec.ts
  frontend/test/__support__/ui.tsx
Labels: no-backport, .Team/AdminWebapp

#42156 Fix data source E2E test
  e2e/test/scenarios/question/notebook-data-source.cy.spec.ts
Labels: no-backport, .Team/QueryingComponents

#42148 Apply mantine color palette to cartesian chart labels
  enterprise/frontend/src/embedding-sdk/types/theme.ts
  frontend/src/metabase/hooks/use-palette.ts
  frontend/src/metabase/visualizations/components/Visualization/Visualization-themed.unit.spec.tsx
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-models-and-option.ts
  frontend/test/__support__/ui.tsx
Labels: visual, no-backport, .Team/Embedding

#42161 Fix E2E Repro #42065 failure
  e2e/test/scenarios/question/reproductions/42065-mongo-filter-by-id.cy.spec.js
Labels: .CI & Tests, flaky-test-fix, no-backport, .Team/QueryingComponents

#42091 [docs] Add Pathway for Email Settings Configuration
  docs/configuring-metabase/email.md
Labels: Type:Documentation, backport

#42053 [WIP] Aggregation picker changes for metrics
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.styled.tsx
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.tsx
  frontend/src/metabase/core/components/AccordionList/AccordionListCell.jsx
  frontend/src/metabase/ui/utils/colors.ts
Labels: .Team/QueryingComponents

#42174 docs - add 49.8 to list of releases
  docs/releases.md
Labels: Type:Documentation, backport

#42167 42078 palette search links
  frontend/src/metabase/palette/components/PaletteResultItem.tsx
  frontend/src/metabase/palette/components/PaletteResults.tsx
  frontend/src/metabase/palette/components/PaletteResults.unit.spec.tsx
  frontend/src/metabase/palette/hooks/useCommandPalette.tsx
  frontend/src/metabase/palette/types.ts
  frontend/test/__support__/ui.tsx
Labels: no-backport

#42177 [docs] remove trailing slash from SSO docs
  docs/people-and-groups/authenticating-with-jwt.md
  docs/people-and-groups/authenticating-with-saml.md
  docs/people-and-groups/saml-auth0.md
  docs/troubleshooting-guide/saml.md
Labels: Type:Documentation, backport

#41774 Add analytics event for extract column in chill mode
  e2e/test/scenarios/visualizations-tabular/drillthroughs/column_extract_drill.cy.spec.js
  frontend/src/metabase-lib/extractions.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/querying/analytics.ts
  frontend/src/metabase/querying/utils/drills/column-extract-drill/column-extract-drill.tsx
  src/metabase/lib/core.cljc
  src/metabase/lib/drill_thru/column_extract.cljc
  src/metabase/lib/js.cljs
  test/metabase/lib/drill_thru/column_extract_test.cljc
Labels: no-backport, .Team/QueryingComponents

#42181 [docs] Add TOC to a few articles
  docs/configuring-metabase/customizing-jetty-webserver.md
  docs/installation-and-operation/running-metabase-on-debian.md
Labels: Type:Documentation, backport

#42062 Optimize loading of admin permissions pages (add skip_fields flag to database metadata endpoint)
  frontend/src/metabase-types/api/table.ts
  frontend/src/metabase/admin/permissions/pages/DataPermissionsPage/DataPermissionsPage.tsx
  src/metabase/api/database.clj
  test/metabase/api/database_test.clj
Labels: no-backport, .Team/AdminWebapp

#42076 Preserve saved parameter operator type
  e2e/test/scenarios/dashboard-filters/dashboard-filters-management.cy.spec.js
  frontend/src/metabase/dashboard/actions/parameters.ts
  frontend/src/metabase/dashboard/reducers.js
  frontend/src/metabase/dashboard/selectors.ts
Labels: no-backport, .Team/QueryingComponents

#42116 [QP] Support `:temporal-unit` parameters on MBQL queries
  src/metabase/lib/schema/parameter.cljc
  src/metabase/query_processor/middleware/parameters.clj
  src/metabase/query_processor/middleware/parameters/mbql.clj
  test/metabase/native_query_analyzer/parameter_substitution_test.clj
  test/metabase/query_processor_test/date_bucketing_test.clj
Labels: .Team/QueryProcessor, no-backport

#42107 Cleanup parameters popover
  frontend/src/metabase/dashboard/components/ParametersPopover.jsx
  frontend/src/metabase/dashboard/components/ParametersPopover.tsx
  frontend/src/metabase/parameters/utils/dashboard-options.ts
Labels: no-backport, .Team/QueryingComponents

#41802 docs - generate environment variables
  enterprise/backend/src/metabase_enterprise/sso/integrations/sso_settings.clj
  src/metabase/cmd/env_var_dox.clj
  src/metabase/cmd/resources/other-env-vars.md
  src/metabase/driver/sql_jdbc/connection.clj
  src/metabase/public_settings.clj
  src/metabase/public_settings/premium_features.clj
  src/metabase/server/middleware/session.clj
  test/metabase/cmd/env_var_dox_test.clj
Labels: backport

#42087 Fix LegacyMetric/Segment macroexpansion with definitions using ancient MBQL
  src/metabase/lib/convert.cljc
  src/metabase/query_processor/middleware/expand_macros.clj
  test/metabase/query_processor/middleware/expand_macros_test.clj
  test/metabase/query_processor/reducible_test.clj
  test/metabase/query_processor_test/sum_where_test.clj
Labels: .Team/QueryProcessor, no-backport

#42058 fixes replace missing values with zeros on timeseries charts
  .loki/reference/chrome_laptop_static_viz_ComboChart_Line_Replace_Missing_Values_Zero.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Combo.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Combo_Log.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Combo_Power.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Area.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Line.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Normalized_Stacked_Area.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Normalized_Stacked_Bar.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Stacked_Area.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Single_Series_Area.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Single_Series_Line.png
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/line-replace-missing-values-zero.json
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.unit.spec.ts
Labels: visual, no-backport, .Team/DashViz

#42070 MLv2: Simplify MetadataProvider protocols (16 methods/3 protocols => 7 methods/2 protocols)
  modules/drivers/mongo/src/metabase/driver/mongo/parameters.clj
  modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj
  src/metabase/driver/sql/parameters/substitution.clj
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/card.cljc
  src/metabase/lib/column_group.cljc
  src/metabase/lib/drill_thru/pivot.cljc
  src/metabase/lib/drill_thru/quick_filter.cljc
  src/metabase/lib/drill_thru/zoom_in_timeseries.cljc
  src/metabase/lib/expression.cljc
  src/metabase/lib/filter/operator.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/join/util.cljc
  src/metabase/lib/js/metadata.cljs
  src/metabase/lib/legacy_metric.cljc
  src/metabase/lib/metadata.cljc
  src/metabase/lib/metadata/cached_provider.cljc
  src/metabase/lib/metadata/composed_provider.cljc
  src/metabase/lib/metadata/invocation_tracker.cljc
  src/metabase/lib/metadata/jvm.clj
  src/metabase/lib/metadata/protocols.cljc
  src/metabase/lib/order_by.cljc
  src/metabase/lib/query.cljc
  src/metabase/lib/schema/metadata.cljc
  src/metabase/lib/segment.cljc
  src/metabase/models/legacy_metric.clj
  src/metabase/models/segment.clj
  src/metabase/query_processor/middleware/add_dimension_projections.clj
  src/metabase/query_processor/setup.clj
  test/metabase/analyze/query_results_test.clj
  test/metabase/lib/metadata/cached_provider_test.cljc
  test/metabase/lib/metadata/invocation_tracker_test.cljc
  test/metabase/lib/metadata/jvm_test.clj
  test/metabase/lib/table_test.cljc
  test/metabase/lib/test_metadata.cljc
  test/metabase/lib/test_metadata/graph_provider.cljc
  test/metabase/lib/test_util.cljc
  test/metabase/lib/test_util/metadata_providers/merged_mock.cljc
  test/metabase/lib/test_util/metadata_providers/mock.cljc
  test/metabase/lib/test_util/metadata_providers/with_cards_for_queries.cljc
  test/metabase/lib/test_util/mocks_31769.cljc
  test/metabase/models/collection/graph_test.clj
  test/metabase/query_processor/test_util.clj
  test/metabase/test.clj
  test/metabase/test/util.clj
Labels: no-backport

#42144 Add tests for url and email columns
  e2e/test/scenarios/visualizations-tabular/drillthroughs/column_extract_drill.cy.spec.js
  frontend/src/metabase/query_builder/components/expressions/ExtractColumn/util.ts
  frontend/src/metabase/querying/utils/drills/column-extract-drill/column-extract-drill.tsx
Labels: no-backport, .Team/QueryingComponents

#42042 Change utm tags for embedding homepage links
  frontend/src/metabase/home/components/EmbedHomepage/EmbedHomepage.tsx
  frontend/src/metabase/home/components/EmbedHomepage/tests/common.unit.spec.tsx
Labels: .Team/Embedding

#42200 add description to the checklist setup step
  src/metabase/api/setup.clj
Labels: .Team/Embedding

#42095 Snowplow event for extract action via notebook shortcut
  e2e/test/scenarios/custom-column/cc-shortcuts-extract.cy.spec.js
  frontend/src/metabase/query_builder/analytics.js
  frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx
  frontend/src/metabase/query_builder/components/expressions/ExtractColumn/ExtractColumn.tsx
Labels: no-backport, .Team/QueryingComponents

#42119 Add a few tests for time granularity parameters
  test/metabase/api/dashboard_test.clj
Labels: .Team/QueryProcessor, no-backport

#41777 Enable customization of columns in ItemsTable
  e2e/test/scenarios/collections/collections.cy.spec.js
  frontend/src/metabase/collections/components/ActionMenu/ActionMenu.tsx
  frontend/src/metabase/collections/components/ActionMenu/ActionMenu.unit.spec.tsx
  frontend/src/metabase/collections/components/BulkActions.styled.tsx
  frontend/src/metabase/collections/components/BulkActions.tsx
  frontend/src/metabase/collections/components/CollectionContent/CollectionContent.styled.tsx
  frontend/src/metabase/collections/components/CollectionContent/CollectionContent.tsx
  frontend/src/metabase/collections/components/CollectionContent/CollectionContentView.tsx
  frontend/src/metabase/components/EntityItem/EntityItem.styled.tsx
  frontend/src/metabase/components/EntityItem/EntityItem.tsx
  frontend/src/metabase/components/ItemsTable/BaseItemsTable.styled.tsx
  frontend/src/metabase/components/ItemsTable/BaseItemsTable.tsx
  frontend/src/metabase/components/ItemsTable/BaseItemsTable.unit.spec.tsx
  frontend/src/metabase/components/ItemsTable/BaseTableItem.tsx
  frontend/src/metabase/components/ItemsTable/Columns.tsx
  frontend/src/metabase/components/ItemsTable/ItemsTable.tsx
  frontend/src/metabase/components/ItemsTable/utils.ts
  frontend/src/metabase/containers/dnd/ItemDragSource.jsx
  frontend/src/metabase/containers/dnd/ItemsDragLayer.jsx
  frontend/src/metabase/ui/theme.ts
Labels: no-backport, .Team/AdminWebapp

#42208 Fix InteractiveQuestion loader show no question before loaded
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.unit.spec.tsx
Labels: no-backport, .Team/Embedding

#42043 Add viz settings to manage line style and thickness to line/area charts
  .loki/reference/chrome_laptop_static_viz_ComboChart_Line_Settings.png
  e2e/test/scenarios/visualizations-charts/line_chart.cy.spec.js
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/settings.ts
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/index.ts
  frontend/src/metabase/static-viz/components/ComboChart/stories-data/line-settings.json
  frontend/src/metabase/visualizations/components/ChartSettings.unit.spec.tsx
  frontend/src/metabase/visualizations/components/settings/ChartNestedSettingsSeriesMultiple.unit.spec.js
  frontend/src/metabase/visualizations/echarts/cartesian/constants/style.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
  frontend/src/metabase/visualizations/lib/settings/series.js
  frontend/src/metabase/visualizations/shared/settings/series.ts
Labels: visual, no-backport, .Team/DashViz

#42217 Update readme adding more ways to run Metabase
  enterprise/frontend/src/embedding-sdk/README.md
Labels: no-backport, .Team/Embedding

#41990 Embed homepage, MS4
  e2e/test/scenarios/onboarding/embedding-homepage.cy.spec.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/home/components/EmbedHomepage/EmbedHomepage.stories.tsx
  frontend/src/metabase/home/components/EmbedHomepage/EmbedHomepage.tsx
  frontend/src/metabase/home/components/EmbedHomepage/EmbedHomepageView.tsx
  frontend/src/metabase/home/components/EmbedHomepage/InteractiveTabContent.tsx
  frontend/src/metabase/home/components/EmbedHomepage/StaticTabContent.tsx
  frontend/src/metabase/home/components/EmbedHomepage/actions.ts
  frontend/src/metabase/home/components/EmbedHomepage/analytics.ts
  frontend/src/metabase/home/components/EmbedHomepage/tests/common.unit.spec.tsx
  frontend/src/metabase/home/components/EmbedHomepage/tests/setup.tsx
  frontend/src/metabase/home/components/EmbedHomepage/types.ts
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/StaticEmbedSetupPane.tsx
  frontend/src/metabase/public/lib/analytics.ts
  snowplow/iglu-client-embedded/schemas/com.metabase/embed_flow/jsonschema/1-0-1
  snowplow/iglu-client-embedded/schemas/com.metabase/embedding_homepage/jsonschema/1-0-0
  src/metabase/api/setup.clj
  test/metabase/api/setup_test.clj
Labels: no-backport

#42207 Define public metabase theme and Mantine transformer for embedding SDK
  enterprise/frontend/src/embedding-sdk/README.md
  enterprise/frontend/src/embedding-sdk/components/private/AppInitializeController.tsx
  enterprise/frontend/src/embedding-sdk/components/public/MetabaseProvider.tsx
  enterprise/frontend/src/embedding-sdk/index.ts
  enterprise/frontend/src/embedding-sdk/lib/theme/color-tuple.ts
  enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.ts
  enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.unit.spec.ts
  enterprise/frontend/src/embedding-sdk/types/fonts.ts
  enterprise/frontend/src/embedding-sdk/types/index.ts
  enterprise/frontend/src/embedding-sdk/types/theme.ts
Labels: no-backport, .Team/Embedding

#42137 [docs] A bit more details about API
  docs/installation-and-operation/serialization.md
Labels: Type:Documentation, backport

#42169 docs - update filter docs
  docs/data-modeling/metadata-editing.md
Labels: Type:Documentation, backport

#42209 Adjust styles of the single active tab in parameter sidebar
  frontend/src/metabase/parameters/components/ParameterSidebar/ParameterSidebar.tsx
Labels: no-backport, .Team/QueryingComponents

#42232 Update feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: no-backport

#42231 Fix editing an existing metric
  frontend/src/metabase/query_builder/selectors.js
Labels: no-backport, .Team/QueryingComponents

#41955 Remove the tabs from Browse
  frontend/src/metabase/browse/components/BrowseApp.styled.tsx
  frontend/src/metabase/browse/components/BrowseApp.tsx
  frontend/src/metabase/browse/components/BrowseDatabases.tsx
  frontend/src/metabase/browse/components/BrowseDatabases.unit.spec.tsx
  frontend/src/metabase/browse/components/BrowseModels.tsx
  frontend/src/metabase/browse/components/BrowseModels.unit.spec.tsx
  frontend/src/metabase/browse/components/BrowseRedirect.tsx
  frontend/src/metabase/browse/components/BrowseRedirect.unit.spec.tsx
  frontend/src/metabase/browse/components/BrowseSchemas.tsx
  frontend/src/metabase/browse/components/SchemaBrowser.jsx
  frontend/src/metabase/lib/urls/browse.ts
  frontend/src/metabase/routes.jsx
Labels: no-backport, .Team/AdminWebapp

#41543 Move archived items to the trash
  resources/migrations/001_update_migrations.yaml
  src/metabase/api/card.clj
  src/metabase/api/collection.clj
  src/metabase/api/common.clj
  src/metabase/api/dashboard.clj
  src/metabase/api/public.clj
  src/metabase/api/search.clj
  src/metabase/config.clj
  src/metabase/models/card.clj
  src/metabase/models/collection.clj
  src/metabase/models/permissions.clj
  src/metabase/models/revision/diff.clj
  src/metabase/query_processor/card.clj
  src/metabase/search/config.clj
  src/metabase/util/malli/schema.clj
  test/metabase/api/bookmark_test.clj
  test/metabase/api/card_test.clj
  test/metabase/api/collection_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/search_test.clj
  test/metabase/models/card_test.clj
  test/metabase/models/collection_test.clj
Labels: .Team/AdminWebapp

#42184 Add `can_write` to /collection/:id/items
  src/metabase/api/collection.clj
  test/metabase/api/collection_test.clj
Labels: backport, .Team/AdminWebapp

#42221 [MBQL lib] Add `metric-based?` function and `Lib.isMetricBased`
  frontend/src/metabase-lib/metrics.ts
  src/metabase/lib/core.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/metric.cljc
  src/metabase/lib/metric/basics.cljc
Labels: .Team/QueryProcessor, no-backport

#42251 fix a regex validation
  src/metabase/public_settings/premium_features.clj
Labels: no-backport, .Team/AdminWebapp

#40293 Druid jdbc
  .clj-kondo/hooks/clojure/core.clj
  .github/workflows/drivers.yml
  deps.edn
  docs/developers-guide/driver-changelog.md
  modules/drivers/deps.edn
  modules/drivers/druid-jdbc/deps.edn
  modules/drivers/druid-jdbc/resources/metabase-plugin.yaml
  modules/drivers/druid-jdbc/src/metabase/driver/druid_jdbc.clj
  modules/drivers/druid-jdbc/test/metabase/driver/druid_jdbc/nested_field_columns_test.clj
  modules/drivers/druid-jdbc/test/metabase/driver/druid_jdbc_test.clj
  modules/drivers/druid-jdbc/test/metabase/test/data/druid_jdbc.clj
  src/metabase/driver/util.clj
  src/metabase/models/field_values.clj
  src/metabase/types.cljc
  test/metabase/api/field_test.clj
  test/metabase/db/metadata_queries_test.clj
  test/metabase/driver/sql_jdbc/connection_test.clj
  test/metabase/driver/sql_jdbc/execute/diagnostic_test.clj
  test/metabase/driver/sql_jdbc/sync/describe_database_test.clj
  test/metabase/driver/sql_jdbc/sync/describe_table_test.clj
  test/metabase/driver/sql_jdbc/test_util.clj
  test/metabase/driver/sql_jdbc_test.clj
  test/metabase/query_processor/test_util.clj
  test/metabase/query_processor_test/alternative_date_test.clj
  test/metabase/test.clj
  test/metabase/test/data/dataset_definition_test.clj
  test/metabase/test/data/impl.clj
  test/metabase/test/data/interface.clj
  test/metabase/test/data/mbql_query_impl.clj
  test/metabase/timeseries_query_processor_test.clj
  test/metabase/timeseries_query_processor_test/util.clj
Labels: .Team/QueryProcessor, no-backport

#42224 Use database-supports? instead of hard-coded driver in `dataset-with-custom-pk-test`
  test/metabase/test/data/dataset_definition_test.clj
Labels: backport, .Team/BackendComponents

#42206 Added Key Authentication Option to SSH Tunneling Docs
  docs/databases/ssh-tunnel.md
Labels: Type:Documentation, backport

#42246 Fix wrapping in QueryColumnPicker
  e2e/test/scenarios/question/reproductions/42244-column-picker-wrapping.cy.spec.js
  frontend/src/metabase/common/components/QueryColumnPicker/QueryColumnPicker.styled.tsx
  frontend/src/metabase/common/components/QueryColumnPicker/QueryColumnPicker.tsx
Labels: no-backport, .Team/QueryingComponents

#42233 Hide "Basic metrics" when the query is entirely metric-based
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.tsx
Labels: no-backport

#42236 Open the expression editor if all metrics are selected
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/AggregateStep/AggregateStep.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/AggregationItem/AggregationItem.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/SummarizeSidebar/SummarizeSidebar.tsx
Labels: no-backport, .Team/QueryingComponents

#41223 docs - field type metadata
  docs/data-modeling/field-types.md
  docs/data-modeling/formatting.md
  docs/questions/images/world-region-map.png
  docs/questions/sharing/visualizations/map.md
Labels: Type:Documentation, backport

#42276 Add `can_write` to cards/dashboards in Search
  src/metabase/api/search.clj
  test/metabase/api/search_test.clj
Labels: backport, .Team/AdminWebapp

#42059 add percent change to timeseries tooltip
  e2e/test/scenarios/visualizations-charts/line-bar-tooltips.cy.spec.js
  frontend/src/metabase/lib/formatting/numbers.tsx
  frontend/src/metabase/visualizations/components/ChartTooltip/KeyValuePairChartTooltip/KeyValuePairChartTooltip.styled.tsx
  frontend/src/metabase/visualizations/components/ChartTooltip/KeyValuePairChartTooltip/KeyValuePairChartTooltip.tsx
  frontend/src/metabase/visualizations/components/ChartTooltip/StackedDataTooltip/StackedDataTooltip.styled.tsx
  frontend/src/metabase/visualizations/components/FunnelNormal.jsx
  frontend/src/metabase/visualizations/echarts/cartesian/model/guards.ts
  frontend/src/metabase/visualizations/lib/numeric.js
  frontend/src/metabase/visualizations/lib/numeric.unit.spec.js
  frontend/src/metabase/visualizations/types/hover.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/constants.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/events.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-chart-events.ts
  frontend/src/metabase/visualizations/visualizations/SmartScalar/compute.js
  frontend/src/metabase/visualizations/visualizations/SmartScalar/compute.unit.spec.js
Labels: visual, no-backport, .Team/DashViz

#42269 Improve types for ParameterSettings
  frontend/src/metabase-lib/v1/parameters/utils/operators.ts
  frontend/src/metabase/dashboard/components/ParametersPopover.tsx
  frontend/src/metabase/parameters/components/ParameterSettings/ParameterSettings.tsx
  frontend/src/metabase/parameters/utils/dashboard-options.ts
Labels: no-backport, .Team/QueryingComponents

#42283 adds diagnostic info to troubleshooting for air gapping
  src/metabase/public_settings/premium_features.clj
  src/metabase/troubleshooting.clj
Labels: no-backport, .Team/AdminWebapp

#42292 Fix x-axis time series interval computation when x-values include nulls
  frontend/src/metabase/visualizations/echarts/cartesian/utils/timeseries.ts
  frontend/src/metabase/visualizations/echarts/cartesian/utils/timeseries.unit.spec.js
  frontend/src/metabase/visualizations/visualizations/CartesianChart/CartesianChart.tsx
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-chart-debug.ts
Labels: visual, no-backport, .Team/DashViz

#42296 Make bulk action bar reusable
  e2e/test/scenarios/collections/archive.cy.spec.js
  frontend/src/metabase/archive/containers/ArchiveApp.tsx
  frontend/src/metabase/collections/components/BulkActions.styled.tsx
  frontend/src/metabase/collections/components/CollectionBulkActions.tsx
  frontend/src/metabase/collections/components/CollectionContent/CollectionContentView.tsx
  frontend/src/metabase/components/BulkActionBar/BulkActionBar.styled.tsx
  frontend/src/metabase/components/BulkActionBar/BulkActionBar.tsx
  frontend/src/metabase/components/BulkActionBar/index.tsx
Labels: no-backport, .Team/AdminWebapp

#42125 Port metric v1 e2e tests
  e2e/test/scenarios/question/notebook.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/reproductions/6010-metric-filter-drill.cy.spec.js
  frontend/src/metabase/parameters/utils/mapping-options.unit.spec.js
  frontend/src/metabase/query_builder/containers/QueryBuilder.unsaved-changes-warning.unit.spec.tsx
  src/metabase/lib/fe_util.cljc
Labels: .Team/QueryProcessor

#42009 Entity picker/new search item component
  enterprise/frontend/src/metabase-enterprise/collections/index.ts
  enterprise/frontend/src/metabase-enterprise/collections/utils.ts
  enterprise/frontend/src/metabase-enterprise/collections/utils.unit.spec.ts
  frontend/src/metabase-types/api/mocks/search.ts
  frontend/src/metabase-types/api/search.ts
  frontend/src/metabase/common/components/CollectionPicker/components/CollectionPickerModal.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/EntityPickerModal.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/EntityPickerModal.unit.spec.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/TabsView.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerSearch/EntityPickerSearch.styled.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerSearch/EntityPickerSearch.tsx
  frontend/src/metabase/common/components/EntityPicker/components/LoadingSpinner/LoadingSpinner.tsx
  frontend/src/metabase/common/components/EntityPicker/components/ResultItem/ResultItem.styled.tsx
  frontend/src/metabase/common/components/EntityPicker/components/ResultItem/ResultItem.tsx
  frontend/src/metabase/common/components/EntityPicker/components/ResultItem/ResultItem.unit.spec.tsx
  frontend/src/metabase/common/components/EntityPicker/components/ResultItem/index.ts
  frontend/src/metabase/lib/icon.ts
  frontend/src/metabase/plugins/index.ts
Labels: no-backport, .Team/AdminWebapp

#42299 Fix tooltip shows data for different X value
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Combo.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Combo_Log.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Combo_Power.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Area.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Line.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Normalized_Stacked_Area.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Normalized_Stacked_Bar.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Multi_Series_Stacked_Area.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Single_Series_Area.png
  .loki/reference/chrome_laptop_static_viz_ComboChart_Trend_Single_Series_Line.png
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/dataset.unit.spec.ts
Labels: visual, no-backport, .Team/DashViz

#42287 Basic Table Component (+ use it for API Keys)
  e2e/test/scenarios/admin-2/api-keys.cy.spec.ts
  frontend/src/metabase/admin/settings/components/ApiKeys/ManageApiKeys.tsx
  frontend/src/metabase/admin/settings/components/ApiKeys/utils.ts
  frontend/src/metabase/common/components/Table/Table.styled.tsx
  frontend/src/metabase/common/components/Table/Table.tsx
  frontend/src/metabase/common/components/Table/Table.unit.spec.tsx
  frontend/src/metabase/common/components/Table/index.ts
Labels: backport, .Team/AdminWebapp

#42098 Remove unusued code paths for automagic filtering
  src/metabase/api/automagic_dashboards.clj
  src/metabase/automagic_dashboards/core.clj
  src/metabase/automagic_dashboards/filters.clj
  src/metabase/models/dashboard_tab.clj
Labels: no-backport, .Team/BackendComponents

#41772 Send pulses in parallel
  resources/migrations/001_update_migrations.yaml
  src/metabase/api/alert.clj
  src/metabase/api/common.clj
  src/metabase/db/custom_migrations.clj
  src/metabase/models/pulse.clj
  src/metabase/models/pulse_channel.clj
  src/metabase/task/send_pulses.clj
  test/metabase/analytics/stats_test.clj
  test/metabase/models/pulse_channel_test.clj
  test/metabase/models/pulse_test.clj
  test/metabase/task/send_pulses_test.clj
  test/metabase/test/util.clj
Labels: no-backport, .Team/BackendComponents

#42297 Fix combine extract column drill icons
  frontend/src/metabase/querying/utils/drills/column-extract-drill/column-extract-drill.tsx
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/combine-columns-drill.tsx
Labels: no-backport, .Team/QueryingComponents

#42317 Do not require `onConfirm` prop in `EntityPickerModal`
  frontend/src/metabase/common/components/DataPicker/components/DataPickerModal.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/EntityPickerModal.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/EntityPickerModal.unit.spec.tsx
Labels: no-backport, .Team/QueryingComponents

#42312 Snowflake: fix sync dynamic table
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
Labels: backport, .Team/BackendComponents

#42315 Remove snippets from search types
  frontend/src/metabase-types/api/search.ts
  frontend/src/metabase/common/hooks/entity-framework/use-search-list-query/use-search-list-query.unit.spec.tsx
  frontend/src/metabase/lib/icon.ts
Labels: no-backport, .Team/QueryingComponents

#42222 [MBQL lib] Suggest joining metrics on their primary breakout
  src/metabase/lib/join.cljc
  src/metabase/lib/metric.cljc
  src/metabase/lib/metric/basics.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/test_util.cljc
Labels: .Team/QueryProcessor

#42332 Update the README to document some SDK quirks
  enterprise/frontend/src/embedding-sdk/README.md
Labels: no-backport, .Team/Embedding

#42334 add chart logging own env var
  frontend/src/metabase/env.js
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-chart-debug.ts
Labels: visual, no-backport

#42327 Fix Embedding SDK calling admin endpoint
  enterprise/frontend/src/embedding-sdk/hooks/private/use-init-data.ts
Labels: no-backport, .Team/Embedding

#42226 Remove Archive Page + Add `/trash` routing
  e2e/test/scenarios/actions/model-actions.cy.spec.js
  e2e/test/scenarios/collections/permissions.cy.spec.js
  e2e/test/scenarios/collections/trash.cy.spec.js
  frontend/src/metabase/archive/containers/ArchiveApp.styled.tsx
  frontend/src/metabase/archive/containers/ArchiveApp.tsx
  frontend/src/metabase/collections/components/CollectionLanding/CollectionLanding.tsx
  frontend/src/metabase/components/ArchivedItem/ArchivedItem.styled.tsx
  frontend/src/metabase/components/ArchivedItem/ArchivedItem.tsx
  frontend/src/metabase/components/BulkActionBar/BulkActionBar.styled.tsx
  frontend/src/metabase/components/BulkActionBar/BulkActionBar.tsx
  frontend/src/metabase/components/BulkActionBar/index.tsx
  frontend/src/metabase/components/type/PageHeading.jsx
  frontend/src/metabase/lib/urls/collections.ts
  frontend/src/metabase/routes.jsx
Labels: .Team/AdminWebapp

#42311 Silence `abs` warning on startup
  deps.edn
Labels: no-backport

#42179 41901 command palette search view all
  e2e/test/scenarios/onboarding/command-palette.cy.spec.js
  frontend/src/metabase/lib/browser.js
  frontend/src/metabase/nav/components/AppBar/AppBarLarge.tsx
  frontend/src/metabase/nav/components/search/SearchBar/CommandPaletteTrigger.tsx
  frontend/src/metabase/nav/components/search/SearchButton/SearchButton.tsx
  frontend/src/metabase/nav/components/search/SearchButton/index.ts
  frontend/src/metabase/palette/components/PaletteResultItem.tsx
  frontend/src/metabase/palette/components/PaletteResults.tsx
  frontend/src/metabase/palette/components/PaletteResults.unit.spec.tsx
  frontend/src/metabase/palette/hooks/useCommandPalette.tsx
  frontend/src/metabase/palette/types.ts
  frontend/test/__support__/ui.tsx
Labels: no-backport, .Team/AdminWebapp

#42314 Allow duplicate "combine column" columns in chill mode
  e2e/test/scenarios/visualizations-tabular/drillthroughs/combine-column.cy.spec.js
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/components/CombineColumnsDrill/CombineColumnsDrill.tsx
  frontend/src/metabase/querying/utils/drills/combine-columns-drill/utils.ts
Labels: no-backport, .Team/QueryingComponents

#42302 Only nest expressions referenced in breakouts or aggregations
  .clj-kondo/hooks/clojure/test.clj
  modules/drivers/oracle/test/metabase/driver/oracle_test.clj
  src/metabase/models/params/custom_values.clj
  src/metabase/query_processor/util/nest_query.clj
  src/metabase/util/malli/schema.clj
  test/metabase/driver/sql/query_processor_test.clj
  test/metabase/models/params/custom_values_test.clj
  test/metabase/query_processor/util/nest_query_test.clj
  test/metabase/util/malli/schema_test.clj
Labels: .Team/QueryProcessor, no-backport

#42272 Make Z-indexes a bit more sane
  frontend/src/metabase/common/components/CollectionPicker/components/NewCollectionDialog.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/EntityPickerModal.tsx
  frontend/src/metabase/common/components/EntityPicker/components/ResultItem/ResultItem.tsx
  frontend/src/metabase/common/components/EntityPicker/components/ResultItem/ResultItem.unit.spec.tsx
  frontend/src/metabase/components/BulkActionBar/BulkActionBar.styled.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorHelpText/ExpressionEditorHelpText.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions/ExpressionEditorSuggestions.tsx
  frontend/src/metabase/ui/components/overlays/Popover/Popover.styled.tsx
  frontend/src/metabase/ui/components/overlays/Popover/index.tsx
Labels: no-backport, .Team/AdminWebapp

#42132 Support `Offset()` as an expression with no breakouts [backend]
  src/metabase/legacy_mbql/normalize.cljc
  src/metabase/lib/schema.cljc
  src/metabase/lib/schema/expression/window.cljc
  src/metabase/lib/schema/util.cljc
  test/metabase/legacy_mbql/normalize_test.cljc
  test/metabase/lib/schema/expression/window_test.cljc
  test/metabase/lib/schema/expression_test.cljc
  test/metabase/lib/schema_test.cljc
  test/metabase/query_processor/test_util.clj
  test/metabase/query_processor_test/offset_test.clj
  test/metabase/query_processor_test/remapping_test.clj
  test/metabase/test/data/users.clj
Labels: .Team/QueryProcessor, no-backport

#42310 Don't optimize temporal filters with unbucketed exprs against relative datetimes
  src/metabase/driver/h2.clj
  src/metabase/driver/sql/query_processor.clj
  src/metabase/query_processor/middleware/optimize_temporal_filters.clj
  test/metabase/driver/mysql_test.clj
  test/metabase/driver/sql/query_processor_test.clj
  test/metabase/formatter/datetime_test.clj
  test/metabase/query_processor/middleware/optimize_temporal_filters_test.clj
Labels: .Team/QueryProcessor, no-backport

#42279 Backfill QueryField on Metabase startup
  resources/migrations/001_update_migrations.yaml
  src/metabase/api/dashboard.clj
  src/metabase/db/custom_migrations.clj
  src/metabase/lib/util.cljc
  src/metabase/models/card.clj
  src/metabase/models/dashboard.clj
  src/metabase/models/dashboard_tab.clj
  src/metabase/models/field_usage.clj
  src/metabase/models/query_field.clj
  src/metabase/native_query_analyzer.clj
  src/metabase/task/backfill_query_fields.clj
  src/metabase/util.cljc
  test/metabase/db/custom_migrations_test.clj
  test/metabase/models/query_field_test.clj
  test/metabase/native_query_analyzer_test.clj
  test/metabase/pulse/pulse_integration_test.clj
  test/metabase/task/backfill_query_fields_test.clj
  test/metabase/util_test.cljc
Labels: no-backport, .Team/BackendComponents

#42336 Table does not appear selected in single-schema dbs
  frontend/src/metabase/common/components/DataPicker/components/DatabaseList.tsx
  frontend/src/metabase/common/components/DataPicker/components/SchemaList.tsx
  frontend/src/metabase/common/components/DataPicker/hooks/useAutoSelectOnlyItem.ts
Labels: no-backport, .Team/QueryingComponents

#42101 Allow multiple values for string operators in the query builder
  e2e/test/scenarios/filters/filter-types.cy.spec.js
  frontend/src/metabase/querying/components/FilterModal/StringFilterEditor/StringFilterEditor.tsx
  frontend/src/metabase/querying/components/FilterModal/StringFilterEditor/StringFilterEditor.unit.spec.tsx
  frontend/src/metabase/querying/components/FilterPicker/StringFilterPicker/StringFilterPicker.tsx
  frontend/src/metabase/querying/components/FilterPicker/StringFilterPicker/StringFilterPicker.unit.spec.tsx
  frontend/src/metabase/querying/hooks/use-string-filter/constants.ts
  frontend/src/metabase/querying/hooks/use-string-filter/index.ts
  frontend/src/metabase/querying/hooks/use-string-filter/types.ts
  frontend/src/metabase/querying/hooks/use-string-filter/use-string-filter.ts
  frontend/src/metabase/querying/hooks/use-string-filter/use-string-filter.unit.spec.ts
  frontend/src/metabase/querying/hooks/use-string-filter/utils.ts
  frontend/src/metabase/ui/components/inputs/MultiAutocomplete/MultiAutocomplete.tsx
Labels: no-backport, .Team/QueryingComponents

#42340 Bump published SDK version
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: no-backport

#42374 Simplify custom font code
  frontend/src/metabase/styled-components/containers/GlobalStyles/GlobalStyles.tsx
Labels: backport, .Team/Embedding

#41882 Increment view_count on card, dashboard, and table views
  resources/migrations/001_update_migrations.yaml
  src/metabase/events/view_log.clj
  test/metabase/api/activity_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/field_test.clj
  test/metabase/api/table_test.clj
  test/metabase/db/schema_migrations_test.clj
  test/metabase/events/view_log_test.clj
Labels: backport, .Team/BackendComponents

#42320 Remove trailing slash from API route
  enterprise/backend/src/metabase_enterprise/upload_management/api.clj
  enterprise/backend/test/metabase_enterprise/upload_management/api_test.clj
Labels: no-backport, .Team/BackendComponents

#42324 [docs] Updating table settings
  docs/questions/images/column-header-formatting.png
  docs/questions/sharing/visualizations/table.md
Labels: Type:Documentation, backport

#42384 Remove unused `useNativeQuery` util
  frontend/src/metabase/query_builder/components/view/NativeQueryPreview/index.ts
  frontend/src/metabase/query_builder/components/view/NativeQueryPreview/use-native-query.ts
Labels: no-backport, :broom:, .Team/QueryingComponents

#42322 Option to customize base font size in React embedding
  enterprise/frontend/src/embedding-sdk/components/private/AppInitializeController.tsx
  enterprise/frontend/src/embedding-sdk/components/private/SdkContentWrapper.tsx
  enterprise/frontend/src/embedding-sdk/components/public/MetabaseProvider.tsx
  enterprise/frontend/src/embedding-sdk/hooks/private/use-embedding-theme.ts
  enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.ts
  enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.unit.spec.ts
  enterprise/frontend/src/embedding-sdk/types/theme/index.ts
  enterprise/frontend/src/embedding-sdk/types/theme/private.ts
  frontend/src/metabase/css/core/base.styled.ts
  frontend/src/metabase/styled-components/containers/GlobalStyles/GlobalStyles.tsx
Labels: no-backport, .Team/Embedding

#42386 Fix overflow problem in Filter Modal sidebar
  frontend/src/metabase/querying/components/FilterModal/FilterModal.styled.tsx
  frontend/src/metabase/querying/components/FilterModal/FilterModal.tsx
Labels: backport, .Team/QueryingComponents

#42368 Add metric icons in the notebook editor
  e2e/test/scenarios/question/notebook.cy.spec.js
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/query_builder/components/notebook/steps/DataStep/DataStep.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinComplete/JoinComplete.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinDraft/JoinDraft.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTablePicker/JoinTablePicker.styled.tsx
  frontend/src/metabase/query_builder/components/notebook/steps/JoinStep/JoinTablePicker/JoinTablePicker.tsx
Labels: .Team/QueryingComponents

#42391 docs - fix broken link
  docs/developers-guide/clojure.md
Labels: Type:Documentation, backport

#42342 Support custom font in SDK
  enterprise/frontend/src/embedding-sdk/components/private/SdkContentWrapper.tsx
  enterprise/frontend/src/embedding-sdk/types/fonts.ts
Labels: no-backport, .Team/Embedding

#42333 Port CollapseSection to ts
  frontend/src/metabase/components/CollapseSection/CollapseSection.styled.tsx
  frontend/src/metabase/components/CollapseSection/CollapseSection.tsx
  frontend/src/metabase/components/CollapseSection/CollapseSection.unit.spec.tsx
  frontend/src/metabase/components/CollapseSection/index.js
  frontend/src/metabase/components/CollapseSection/index.ts
Labels: no-backport, .Team/AdminWebapp

#42412 Fix flaky frontend question unit test
  frontend/src/metabase/common/components/QuestionPicker/components/QuestionPicker.unit.spec.tsx
Labels: flaky-test-fix, no-backport, .Team/AdminWebapp

#42300 [Metric V2] When joining a metric add its aggregation clause
  src/metabase/lib/join.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/query_processor/middleware/metrics_test.clj
Labels: .Team/QueryProcessor

#42052 Dashboard Param Values Common Impl for Embedding/Preview Embedding
  e2e/test/scenarios/embedding/reproductions/37914-41635-embed-preview-parameter-values.cy.spec.js
  e2e/test/scenarios/embedding/reproductions/37914-embed-preview-parameter-values-not-working.cy.spec.js
  e2e/test/scenarios/embedding/reproductions/40660-overflow-when-embedding-long-dashboards.cy.spec.js
  frontend/src/metabase/dashboard/actions/data-fetching.js
  frontend/src/metabase/services.js
  src/metabase/api/embed.clj
  src/metabase/api/embed/common.clj
  src/metabase/api/preview_embed.clj
  test/metabase/api/embed_test.clj
  test/metabase/api/preview_embed_test.clj
Labels: backport, .Team/DashViz

#42212 Reserve component height with defaults from visualization type in embedded questions
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/public/StaticQuestion/StaticQuestion.tsx
  enterprise/frontend/src/embedding-sdk/lib/default-height.ts
Labels: no-backport, .Team/Embedding

#42357 Allow disabling health check logging via env var
  src/metabase/server/middleware/log.clj
  test/metabase/server/middleware/log_test.clj
Labels: backport, no-backport, .Team/AdminWebapp

#42250 Cam's module linter 5000
  .clj-kondo/config.edn
  .clj-kondo/hooks/clojure/core.clj
  src/metabase/api/collection.clj
  src/metabase/api/database.clj
  src/metabase/api/search.clj
  src/metabase/cmd/copy.clj
  src/metabase/cmd/copy/h2.clj
  src/metabase/cmd/dump_to_h2.clj
  src/metabase/db.clj
  src/metabase/db/query.clj
  src/metabase/driver/h2.clj
  src/metabase/sync/sync_metadata/fks.clj
  src/metabase/task/sync_databases.clj
  test/metabase/cmd/compare_h2_dbs.clj
Labels: .Team/QueryProcessor, no-backport

#42421 Fix another flaky question picker unit test
  frontend/src/metabase/common/components/QuestionPicker/components/QuestionPicker.unit.spec.tsx
Labels: flaky-test-fix, no-backport, .Team/AdminWebapp

#42419 convert `SocketChannelEndpoint` to `SocketChannel`
  src/metabase/async/streaming_response.clj
Labels: backport, .Team/AdminWebapp

#42371 adds the new `watch` alias, which reloads BE on file changes
  deps.edn
  dev/src/watch/watcher.clj
Labels: no-backport

#42431 Remove Extraneous Style Props
  frontend/src/metabase/collections/components/ModelUploadModal.tsx
  frontend/src/metabase/common/components/CollectionPicker/components/NewCollectionDialog.tsx
Labels: no-backport, .Team/AdminWebapp

#42438 allow using urls from other columns in link templates
  frontend/src/metabase/lib/formatting/link.ts
  frontend/src/metabase/lib/formatting/link.unit.spec.tsx
  frontend/src/metabase/lib/formatting/url.tsx
Labels: backport, .Team/DashViz

#42089 fix malli error in defendpoint
  src/metabase/api/common/internal.clj
Labels: no-backport, .Team/BackendComponents

#42433 Add `metabase.actions.core` module API namespace
  .clj-kondo/config.edn
  src/metabase/actions/core.clj
  src/metabase/api/action.clj
  src/metabase/api/dashboard.clj
  src/metabase/api/public.clj
  src/metabase/driver/h2/actions.clj
  src/metabase/driver/mysql/actions.clj
  src/metabase/driver/postgres/actions.clj
  src/metabase/driver/sql_jdbc/actions.clj
Labels: .Team/QueryProcessor, no-backport

#42415 Use the correct icon for the extract column shortcut
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorSuggestions/ExpressionEditorSuggestions.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionWidget.tsx
Labels: no-backport, .Team/QueryingComponents

#42211 Consolidate `engine` utilities
  frontend/src/metabase/admin/app/selectors.ts
  frontend/src/metabase/admin/databases/database.js
  frontend/src/metabase/lib/engine.js
  frontend/src/metabase/lib/engine.ts
  frontend/src/metabase/lib/engine.unit.spec.ts
  frontend/src/metabase/lib/formatting.js
  frontend/src/metabase/lib/formatting/sql.ts
  frontend/src/metabase/query_builder/components/NativeQueryEditor/utils.unit.spec.ts
Labels: no-backport, :broom:, .Team/QueryingComponents

#42359 Allow drivers to not automatically add a PK column for CSV uploads
  docs/developers-guide/driver-changelog.md
  src/metabase/driver.clj
  src/metabase/upload.clj
  test/metabase/upload_test.clj
Labels: .Team/BackendComponents

#42285 Fix mysql with multiple most recent revision
  resources/migrations/001_update_migrations.yaml
  test/metabase/db/schema_migrations_test.clj
Labels: backport, .Team/BackendComponents

#42448 Fix axios security issue by updating the upstream library version
  package.json
  yarn.lock
Labels: no-backport, .Team/Embedding

#41801 Remove Dead Pickers
  e2e/test/scenarios/organization/timelines-collection.cy.spec.js
  e2e/test/scenarios/question/new.cy.spec.js
  frontend/src/metabase/collections/components/CreateCollectionForm/CreateCollectionForm.tsx
  frontend/src/metabase/collections/containers/FormCollectionPicker/FormCollectionPicker.styled.tsx
  frontend/src/metabase/collections/containers/FormCollectionPicker/FormCollectionPicker.tsx
  frontend/src/metabase/common/components/EntityPicker/types.ts
  frontend/src/metabase/common/components/QuestionPicker/components/QuestionPickerModal.tsx
  frontend/src/metabase/containers/AddToDashSelectDashModal/AddToDashSelectDashModal.styled.tsx
  frontend/src/metabase/containers/CollectionPicker.jsx
  frontend/src/metabase/containers/CollectionSelect.jsx
  frontend/src/metabase/containers/CreateCollectionOnTheGo.styled.tsx
  frontend/src/metabase/containers/CreateCollectionOnTheGo.tsx
  frontend/src/metabase/containers/DashboardPicker.tsx
  frontend/src/metabase/containers/ItemPicker/Item.styled.tsx
  frontend/src/metabase/containers/ItemPicker/Item.tsx
  frontend/src/metabase/containers/ItemPicker/ItemPicker.styled.tsx
  frontend/src/metabase/containers/ItemPicker/ItemPicker.tsx
  frontend/src/metabase/containers/ItemPicker/ItemPicker.unit.spec.js
  frontend/src/metabase/containers/ItemPicker/ItemPickerView.tsx
  frontend/src/metabase/containers/ItemPicker/index.ts
  frontend/src/metabase/containers/ItemPicker/test-utils.js
  frontend/src/metabase/containers/ItemPicker/types.ts
  frontend/src/metabase/containers/QuestionPicker.jsx
  frontend/src/metabase/containers/QuestionSelect.tsx
  frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/LinkOptions/LinkedEntityPicker/LinkedEntityPicker.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/LinkOptions/LinkedEntityPicker/LinkedEntityPicker.unit.spec.tsx
  frontend/src/metabase/dashboard/containers/CopyDashboardForm.tsx
  frontend/src/metabase/dashboard/containers/CreateDashboardForm.tsx
  frontend/src/metabase/dashboard/containers/CreateDashboardModal.tsx
  frontend/src/metabase/entities/containers/EntityCopyModal.tsx
  frontend/src/metabase/models/containers/FormModelPicker/FormModelPicker.styled.tsx
  frontend/src/metabase/timelines/collections/routes.tsx
  frontend/src/metabase/timelines/common/components/MoveTimelineModal/MoveTimelineModal.styled.tsx
  frontend/src/metabase/timelines/common/components/MoveTimelineModal/MoveTimelineModal.tsx
Labels: no-backport, .Team/AdminWebapp

#42444 Fix flaky question management e2e test
  e2e/test/scenarios/question/question-management.cy.spec.js
Labels: backport, .Team/QueryingComponents

#42432 [docs] Update environment-variables.md: fix typo re: MB_JETTY_SKIP_SNI
  docs/configuring-metabase/environment-variables.md
Labels: Type:Documentation, backport

#42345 Serialize trash correctly
  enterprise/backend/src/metabase_enterprise/serialization/cmd.clj
  enterprise/backend/test/metabase_enterprise/audit_app/api/collection_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/backfill_ids_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/e2e_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/extract_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/storage_test.clj
  resources/migrations/001_update_migrations.yaml
  src/metabase/api/card.clj
  src/metabase/api/collection.clj
  src/metabase/api/common.clj
  src/metabase/api/dashboard.clj
  src/metabase/config.clj
  src/metabase/core.clj
  src/metabase/models/card.clj
  src/metabase/models/collection.clj
  src/metabase/models/dashboard.clj
  src/metabase/models/revision/diff.clj
  src/metabase/models/serialization.clj
  test/metabase/api/bookmark_test.clj
  test/metabase/api/card_test.clj
  test/metabase/api/collection_test.clj
  test/metabase/api/search_test.clj
Labels: .Team/AdminWebapp

#42418 Remove dead API keys code
  frontend/src/metabase/services.js
Labels: no-backport

#42457 Fix not allow using both react 17 and 18 in the SDK
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: no-backport, .Team/Embedding

#42113 Make Browse models table sortable
  enterprise/frontend/src/metabase-enterprise/content_verification/utils.unit.spec.ts
  frontend/src/metabase-types/api/mocks/search.ts
  frontend/src/metabase-types/api/search.ts
  frontend/src/metabase/browse/components/BrowseModels.tsx
  frontend/src/metabase/browse/components/CollectionBreadcrumbsWithTooltip.tsx
  frontend/src/metabase/browse/components/ModelsTable.tsx
  frontend/src/metabase/browse/components/constants.tsx
  frontend/src/metabase/browse/components/utils.tsx
  frontend/src/metabase/browse/components/utils.unit.spec.tsx
  frontend/src/metabase/browse/constants.ts
  frontend/src/metabase/browse/utils.ts
  frontend/src/metabase/browse/utils.unit.spec.ts
  frontend/src/metabase/collections/components/CollectionContent/CollectionContentView.tsx
  frontend/src/metabase/components/ItemsTable/BaseItemsTable.tsx
  frontend/src/metabase/components/ItemsTable/BaseItemsTable.unit.spec.tsx
  frontend/src/metabase/components/ItemsTable/Columns.tsx
Labels: no-backport, .Team/AdminWebapp

#41972 Convert PublicDashboard to TS
  frontend/src/metabase-types/store/dashboard.ts
  frontend/src/metabase/dashboard/actions/data-fetching-typed.ts
  frontend/src/metabase/dashboard/actions/data-fetching.js
  frontend/src/metabase/dashboard/actions/data-fetching.unit.spec.js
  frontend/src/metabase/dashboard/actions/index.ts
  frontend/src/metabase/dashboard/actions/revisions.js
  frontend/src/metabase/dashboard/actions/save.js
  frontend/src/metabase/dashboard/actions/ui.ts
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx
  frontend/src/metabase/dashboard/components/DashboardActions.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.tsx
  frontend/src/metabase/dashboard/hoc/types.ts
  frontend/src/metabase/dashboard/types.ts
  frontend/src/metabase/parameters/utils/parameter-values.ts
  frontend/src/metabase/public/containers/PublicDashboard/PublicDashboard.jsx
  frontend/src/metabase/public/containers/PublicDashboard/PublicDashboard.tsx
Labels: no-backport, .Team/Embedding

#42204 Use official version of Marginalia
  deps.edn
Labels: Type:Tech Debt, no-backport, .Team/BackendComponents

#42424 [Drills] Only show "Extract" and "Combine" actions on MBQL stages
  src/metabase/lib/drill_thru/column_extract.cljc
  src/metabase/lib/drill_thru/combine_columns.cljc
Labels: .Team/QueryProcessor, no-backport

#42437 Enumerate the current state of the world with regards to module namespaces
  .clj-kondo/config.edn
  .clj-kondo/hooks/clojure/core.clj
  dev/src/dev/deps_graph.clj
  src/metabase/formatter.clj
  src/metabase/pulse/render/body.clj
Labels: .Team/QueryProcessor, no-backport

#41472 Disable cypress log to bypass out of memory issue
  .github/workflows/pre-release.yml
Labels: backport, .Team/QueryingComponents

#42461 [QP] Fix error with `:!=` "Is Not" filter on expression
  src/metabase/driver/sql/query_processor.clj
  test/metabase/driver/sql/query_processor_test.clj
Labels: no-backport

#42481 [docs] add 49.9 to list of releases
  docs/releases.md
Labels: Type:Documentation, backport

#42468 `metabase.metabot` API namespace
  .clj-kondo/config.edn
  .clj-kondo/hooks/clojure/core.clj
  src/metabase/api/metabot.clj
  src/metabase/metabot.clj
  src/metabase/metabot/feedback.clj
Labels: .Team/QueryProcessor, no-backport

#42485 [docs] Fix format in CLI docs
  docs/installation-and-operation/commands.md
Labels: Type:Documentation, backport
