Repository metabase/metabase, pull requests merged in 2025-04, with the labels that each got.

#56031 🤖 backported "Fix compilation of case with clauses that need pre-processing"
  frontend/src/metabase-lib/v1/expressions/compiler.ts
  frontend/src/metabase-lib/v1/expressions/compiler.unit.spec.ts
  frontend/src/metabase-lib/v1/expressions/identifier.ts
  frontend/src/metabase-lib/v1/expressions/passes.ts
Labels: was-backported

#55916 Merge expression tokenizer and lexer
  frontend/src/metabase-lib/v1/expressions/__support__/expressions.ts
  frontend/src/metabase-lib/v1/expressions/compiler.ts
  frontend/src/metabase-lib/v1/expressions/complete/aggregations.ts
  frontend/src/metabase-lib/v1/expressions/complete/functions.ts
  frontend/src/metabase-lib/v1/expressions/complete/literals.ts
  frontend/src/metabase-lib/v1/expressions/complete/util.ts
  frontend/src/metabase-lib/v1/expressions/diagnostics.ts
  frontend/src/metabase-lib/v1/expressions/diagnostics.unit.spec.ts
  frontend/src/metabase-lib/v1/expressions/errors.ts
  frontend/src/metabase-lib/v1/expressions/pratt/compiler.unit.spec.ts
  frontend/src/metabase-lib/v1/expressions/pratt/fuzz.unit.spec.ts
  frontend/src/metabase-lib/v1/expressions/pratt/index.ts
  frontend/src/metabase-lib/v1/expressions/pratt/lexifier.ts
  frontend/src/metabase-lib/v1/expressions/pratt/lexifier.unit.spec.ts
  frontend/src/metabase-lib/v1/expressions/pratt/parser.ts
  frontend/src/metabase-lib/v1/expressions/pratt/parser.unit.spec.ts
  frontend/src/metabase-lib/v1/expressions/pratt/syntax.ts
  frontend/src/metabase-lib/v1/expressions/pratt/types.ts
  frontend/src/metabase-lib/v1/expressions/tokenizer/index.ts
  frontend/src/metabase-lib/v1/expressions/tokenizer/tokenize.ts
  frontend/src/metabase-lib/v1/expressions/tokenizer/tokenize.unit.spec.ts
  frontend/src/metabase-lib/v1/expressions/tokenizer/types.ts
  frontend/src/metabase-lib/v1/expressions/typeinferencer.ts
  frontend/src/metabase-lib/v1/expressions/typeinferencer.unit.spec.ts
  frontend/src/metabase-lib/v1/expressions/types.ts
  frontend/src/metabase/query_builder/components/expressions/Editor/Editor.tsx
Labels: backport, .Team/Querying

#55894 QueryDownloadPopover -> QuestionDownloadWidget + QueryDownloadWidget -> QuestionDownloadPopover
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/DownloadWidget/DownloadWidget.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestionView.tsx
  frontend/src/metabase/query_builder/components/QueryDownloadPopover/index.ts
  frontend/src/metabase/query_builder/components/QuestionDownloadPopover/QuestionDownloadPopover.tsx
  frontend/src/metabase/query_builder/components/QuestionDownloadPopover/QuestionDownloadPopover.unit.spec.tsx
  frontend/src/metabase/query_builder/components/QuestionDownloadPopover/index.ts
  frontend/src/metabase/query_builder/components/QuestionDownloadWidget/QuestionDownloadWidget.tsx
  frontend/src/metabase/query_builder/components/QuestionDownloadWidget/QuestionDownloadWidget.unit.spec.tsx
  frontend/src/metabase/query_builder/components/QuestionDownloadWidget/index.ts
  frontend/src/metabase/query_builder/components/QuestionDownloadWidget/use-download-data.ts
  frontend/src/metabase/query_builder/components/view/ViewFooter/ViewFooterDownloadWidget.tsx
Labels: .Team/Embedding, triple-backport

#56048 🤖 backported "Merge expression tokenizer and lexer"
  frontend/src/metabase-lib/v1/expressions/__support__/expressions.ts
  frontend/src/metabase-lib/v1/expressions/compiler.ts
  frontend/src/metabase-lib/v1/expressions/complete/aggregations.ts
  frontend/src/metabase-lib/v1/expressions/complete/functions.ts
  frontend/src/metabase-lib/v1/expressions/complete/literals.ts
  frontend/src/metabase-lib/v1/expressions/complete/util.ts
  frontend/src/metabase-lib/v1/expressions/diagnostics.ts
  frontend/src/metabase-lib/v1/expressions/diagnostics.unit.spec.ts
  frontend/src/metabase-lib/v1/expressions/errors.ts
  frontend/src/metabase-lib/v1/expressions/pratt/compiler.unit.spec.ts
  frontend/src/metabase-lib/v1/expressions/pratt/fuzz.unit.spec.ts
  frontend/src/metabase-lib/v1/expressions/pratt/index.ts
  frontend/src/metabase-lib/v1/expressions/pratt/lexifier.ts
  frontend/src/metabase-lib/v1/expressions/pratt/lexifier.unit.spec.ts
  frontend/src/metabase-lib/v1/expressions/pratt/parser.ts
  frontend/src/metabase-lib/v1/expressions/pratt/parser.unit.spec.ts
  frontend/src/metabase-lib/v1/expressions/pratt/syntax.ts
  frontend/src/metabase-lib/v1/expressions/pratt/types.ts
  frontend/src/metabase-lib/v1/expressions/tokenizer/index.ts
  frontend/src/metabase-lib/v1/expressions/tokenizer/tokenize.ts
  frontend/src/metabase-lib/v1/expressions/tokenizer/tokenize.unit.spec.ts
  frontend/src/metabase-lib/v1/expressions/tokenizer/types.ts
  frontend/src/metabase-lib/v1/expressions/typeinferencer.ts
  frontend/src/metabase-lib/v1/expressions/typeinferencer.unit.spec.ts
  frontend/src/metabase-lib/v1/expressions/types.ts
  frontend/src/metabase/query_builder/components/expressions/Editor/Editor.tsx
Labels: was-backported

#55987 Respect whitelabeling when showing the instructional video
  frontend/src/metabase/browse/models/BrowseModels.tsx
  frontend/src/metabase/browse/models/ModelExplanationBanner.tsx
Labels: backport

#56050 🤖 backported "QueryDownloadPopover -> QuestionDownloadWidget + QueryDownloadWidget -> QuestionDownloadPopover"
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/DownloadWidget/DownloadWidget.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestionView.tsx
  frontend/src/metabase/query_builder/components/QueryDownloadPopover/index.ts
  frontend/src/metabase/query_builder/components/QuestionDownloadPopover/QuestionDownloadPopover.tsx
  frontend/src/metabase/query_builder/components/QuestionDownloadPopover/QuestionDownloadPopover.unit.spec.tsx
  frontend/src/metabase/query_builder/components/QuestionDownloadPopover/index.ts
  frontend/src/metabase/query_builder/components/QuestionDownloadWidget/QuestionDownloadWidget.tsx
  frontend/src/metabase/query_builder/components/QuestionDownloadWidget/QuestionDownloadWidget.unit.spec.tsx
  frontend/src/metabase/query_builder/components/QuestionDownloadWidget/index.ts
  frontend/src/metabase/query_builder/components/QuestionDownloadWidget/use-download-data.ts
  frontend/src/metabase/query_builder/components/view/ViewFooter/ViewFooterDownloadWidget.tsx
Labels: was-backported

#56049 🤖 backported "QueryDownloadPopover -> QuestionDownloadWidget + QueryDownloadWidget -> QuestionDownloadPopover"
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/DownloadWidget/DownloadWidget.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestionView.tsx
  frontend/src/metabase/query_builder/components/QueryDownloadPopover/index.ts
  frontend/src/metabase/query_builder/components/QuestionDownloadPopover/QuestionDownloadPopover.tsx
  frontend/src/metabase/query_builder/components/QuestionDownloadPopover/QuestionDownloadPopover.unit.spec.tsx
  frontend/src/metabase/query_builder/components/QuestionDownloadPopover/index.ts
  frontend/src/metabase/query_builder/components/QuestionDownloadWidget/QuestionDownloadWidget.tsx
  frontend/src/metabase/query_builder/components/QuestionDownloadWidget/QuestionDownloadWidget.unit.spec.tsx
  frontend/src/metabase/query_builder/components/QuestionDownloadWidget/index.ts
  frontend/src/metabase/query_builder/components/QuestionDownloadWidget/use-download-data.ts
  frontend/src/metabase/query_builder/components/view/ViewFooter/ViewFooterDownloadWidget.tsx
Labels: was-backported

#56052 🤖 backported "Respect whitelabeling when showing the instructional video"
  frontend/src/metabase/browse/models/BrowseModels.tsx
  frontend/src/metabase/browse/models/ModelExplanationBanner.tsx
Labels: was-backported

#55986 Fix overflow in expression editor suggestions
  e2e/test/scenarios/custom-column/custom-column-reproductions.cy.spec.js
  frontend/src/metabase/nav/components/search/SearchBar/SearchBar.styled.tsx
  frontend/src/metabase/query_builder/components/expressions/Editor/Listbox/Listbox.module.css
Labels: backport, .Team/Querying

#56010 Fix row create
  src/metabase/driver/sql_jdbc/actions.clj
  test/metabase/actions/actions_test.clj
Labels: .Team/Workflows

#56004 Fix console warning for end vs flex-end
  frontend/src/metabase/data-grid/components/Footer/Footer.module.css
Labels: backport, .Team/Embedding

#55256 Closes VIZ-289 duplicated cards never ending loading state
  e2e/test/scenarios/dashboard-cards/duplicate-dashcards-tabs.cy.spec.js
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/use-duplicate-dashcard.ts
Labels: backport, .Team/DashViz

#55696 SEM-156 Extract column sorting into a separate control
  e2e/test/scenarios/admin/datamodel/editor.cy.spec.js
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataEditor/MetadataEditor.styled.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataEditor/MetadataEditor.unit.spec.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataHeader/MetadataHeader.module.css
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataHeader/MetadataHeader.styled.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataHeader/MetadataHeader.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataTable/MetadataTable.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataTableColumn/MetadataTableColumn.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataTableColumnList/MetadataTableColumnList.styled.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataTableColumnList/MetadataTableColumnList.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataTableColumnList/index.ts
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataTableSettings/MetadataTableSettings.unit.spec.tsx
  frontend/src/metabase/components/AdminHeader/AdminHeader.jsx
  frontend/src/metabase/metadata/components/FieldOrderSidesheet/FieldOrderPicker.tsx
  frontend/src/metabase/metadata/components/FieldOrderSidesheet/FieldOrderSidesheet.tsx
  frontend/src/metabase/metadata/components/FieldOrderSidesheet/SortableField/SortableField.module.css
  frontend/src/metabase/metadata/components/FieldOrderSidesheet/SortableField/SortableField.tsx
  frontend/src/metabase/metadata/components/FieldOrderSidesheet/SortableField/index.ts
  frontend/src/metabase/metadata/components/FieldOrderSidesheet/index.ts
  frontend/src/metabase/metadata/components/FieldOrderSidesheet/lib.ts
  frontend/src/metabase/ui/components/icons/Icon/icons/sort_arrows.svg
  frontend/src/metabase/ui/index.ts
Labels: no-backport, .Team/SemanticLayer

#55983 Global `scrollIntoView` & `scrollBy` mocks
  enterprise/frontend/src/metabase-enterprise/auth/components/SessionTimeoutSetting/SessionTimeoutSetting.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/sandboxes/components/EditSandboxingModal/EditSandboxingModal.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/FontWidget/FontWidget.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/IllustrationWidget/IllustrationWidget.unit.spec.tsx
  frontend/src/metabase/admin/datamodel/containers/SegmentApp.unit.spec.tsx
  frontend/src/metabase/admin/permissions/components/FilterableTree/FilterableTree.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/ApiKeys/ManageApiKeys.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/AdminSettingInput.unit.spec.tsx
  frontend/src/metabase/common/components/CollectionPicker/components/CollectionPicker.unit.spec.tsx
  frontend/src/metabase/common/components/DashboardPicker/components/DashboardPicker.unit.spec.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/EntityPickerModal.unit.spec.tsx
  frontend/src/metabase/common/components/QuestionPicker/components/QuestionPicker.unit.spec.tsx
  frontend/src/metabase/components/Schedule/Schedule.unit.spec.tsx
  frontend/src/metabase/components/tree/Tree.unit.spec.tsx
  frontend/src/metabase/containers/AddToDashSelectDashModal/AddToDashSelectDashModal.unit.spec.tsx
  frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.unit.spec.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/LinkOptions/LinkedEntityPicker/LinkedEntityPicker.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/ChartSettingsButton/ChartSettingsButton.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardInfoSidebar/DashboardEntityIdCard/tests/premium.unit.spec.tsx
  frontend/src/metabase/dashboard/components/FormDashboardTabSelect/FormDashboardTabSelect.unit.spec.tsx
  frontend/src/metabase/dashboard/containers/CreateDashboardModal.unit.spec.tsx
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.unit.spec.tsx
  frontend/src/metabase/home/components/Onboarding/tests/common.unit.spec.tsx
  frontend/src/metabase/home/components/Onboarding/tests/setup.tsx
  frontend/src/metabase/nav/components/search/SearchResults/SearchResults.unit.spec.tsx
  frontend/src/metabase/notifications/modals/CreateOrEditQuestionAlertModal/CreateOrEditQuestionAlertModal.unit.spec.tsx
  frontend/src/metabase/palette/components/test/PaletteResults/setup.tsx
  frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/DateOperatorPicker/DateOperatorPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateIntervalPicker/DateIntervalPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateIntervalPicker/SimpleDateIntervalPicker/SimpleDateIntervalPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateOffsetIntervalPicker/DateOffsetIntervalPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/SimpleDatePicker/SimpleDatePicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/DateFilterPicker/DateFilterPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/TimeseriesChrome/TimeseriesFilterPicker/TimeseriesFilterPicker.unit.spec.tsx
  frontend/src/metabase/querying/notebook/components/JoinStep/JoinStep.unit.spec.tsx
  frontend/src/metabase/querying/notebook/components/Notebook/Notebook.unit.spec.tsx
  frontend/src/metabase/status/components/FileUploadStatus/FileUploadStatus.unit.spec.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingSelect.unit.spec.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/ChartSettingsTableFormatting.unit.spec.tsx
  frontend/test/__support__/components/mantineSelect.unit.spec.tsx
  frontend/test/__support__/mocks.js
  frontend/test/__support__/ui.tsx
Labels: backport, .Team/SemanticLayer

#55870 Fix coercion for model
  src/metabase/query_processor/middleware/add_implicit_clauses.clj
  test/metabase/query_processor/middleware/add_implicit_clauses_test.clj
Labels: double-backport, .Team/SemanticLayer

#56056 🤖 backported "Fix console warning for end vs flex-end"
  frontend/src/metabase/data-grid/components/Footer/Footer.module.css
Labels: was-backported

#56057 🤖 backported "Closes VIZ-289 duplicated cards never ending loading state"
  e2e/test/scenarios/dashboard-cards/duplicate-dashcards-tabs.cy.spec.js
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/use-duplicate-dashcard.ts
Labels: was-backported

#56062 🤖 backported "Global `scrollIntoView` & `scrollBy` mocks"
  enterprise/frontend/src/metabase-enterprise/auth/components/SessionTimeoutSetting/SessionTimeoutSetting.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/sandboxes/components/EditSandboxingModal/EditSandboxingModal.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/FontWidget/FontWidget.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/IllustrationWidget/IllustrationWidget.unit.spec.tsx
  frontend/src/metabase/admin/datamodel/containers/SegmentApp.unit.spec.tsx
  frontend/src/metabase/admin/permissions/components/FilterableTree/FilterableTree.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/ApiKeys/ManageApiKeys.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/AdminSettingInput.unit.spec.tsx
  frontend/src/metabase/common/components/CollectionPicker/components/CollectionPicker.unit.spec.tsx
  frontend/src/metabase/common/components/DashboardPicker/components/DashboardPicker.unit.spec.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/EntityPickerModal.unit.spec.tsx
  frontend/src/metabase/common/components/QuestionPicker/components/QuestionPicker.unit.spec.tsx
  frontend/src/metabase/components/Schedule/Schedule.unit.spec.tsx
  frontend/src/metabase/components/tree/Tree.unit.spec.tsx
  frontend/src/metabase/containers/AddToDashSelectDashModal/AddToDashSelectDashModal.unit.spec.tsx
  frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.unit.spec.tsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/LinkOptions/LinkedEntityPicker/LinkedEntityPicker.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/ChartSettingsButton/ChartSettingsButton.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardInfoSidebar/DashboardEntityIdCard/tests/premium.unit.spec.tsx
  frontend/src/metabase/dashboard/components/FormDashboardTabSelect/FormDashboardTabSelect.unit.spec.tsx
  frontend/src/metabase/dashboard/containers/CreateDashboardModal.unit.spec.tsx
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.unit.spec.tsx
  frontend/src/metabase/home/components/Onboarding/tests/common.unit.spec.tsx
  frontend/src/metabase/home/components/Onboarding/tests/setup.tsx
  frontend/src/metabase/nav/components/search/SearchResults/SearchResults.unit.spec.tsx
  frontend/src/metabase/notifications/modals/CreateOrEditQuestionAlertModal/CreateOrEditQuestionAlertModal.unit.spec.tsx
  frontend/src/metabase/palette/components/test/PaletteResults/setup.tsx
  frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/DateOperatorPicker/DateOperatorPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateIntervalPicker/DateIntervalPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateIntervalPicker/SimpleDateIntervalPicker/SimpleDateIntervalPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateOffsetIntervalPicker/DateOffsetIntervalPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/SimpleDatePicker/SimpleDatePicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/DateFilterPicker/DateFilterPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/TimeseriesChrome/TimeseriesFilterPicker/TimeseriesFilterPicker.unit.spec.tsx
  frontend/src/metabase/querying/notebook/components/JoinStep/JoinStep.unit.spec.tsx
  frontend/src/metabase/querying/notebook/components/Notebook/Notebook.unit.spec.tsx
  frontend/src/metabase/status/components/FileUploadStatus/FileUploadStatus.unit.spec.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingSelect.unit.spec.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/ChartSettingsTableFormatting.unit.spec.tsx
  frontend/test/__support__/components/mantineSelect.unit.spec.tsx
  frontend/test/__support__/mocks.js
  frontend/test/__support__/ui.tsx
Labels: was-backported

#56063 🤖 backported "Fix coercion for model"
  src/metabase/query_processor/middleware/add_implicit_clauses.clj
  test/metabase/query_processor/middleware/add_implicit_clauses_test.clj
Labels: was-backported

#56064 🤖 backported "Fix coercion for model"
  src/metabase/query_processor/middleware/add_implicit_clauses.clj
  test/metabase/query_processor/middleware/add_implicit_clauses_test.clj
Labels: was-backported

#56047 Spec update add support for reverse PK
  src/metabase/models/util/spec_update.clj
  src/metabase/notification/models.clj
  test/metabase/models/util/spec_update_test.clj
  test/metabase/notification/api/notification_test.clj
Labels: .Team/Workflows

#56039 test: move flaky test to jail
  e2e/test/scenarios/embedding/embedding-questions.cy.spec.js
Labels: backport, .Team/Querying

#55896 [Notification] Improve memory usage for alerts
  src/metabase/channel/email/result_attachment.clj
  src/metabase/channel/impl/email.clj
  src/metabase/channel/impl/http.clj
  src/metabase/channel/impl/slack.clj
  src/metabase/channel/shared.clj
  src/metabase/notification/payload/core.clj
  src/metabase/notification/payload/execute.clj
  src/metabase/notification/payload/impl/card.clj
  src/metabase/notification/payload/impl/dashboard.clj
  src/metabase/notification/payload/temp_storage.clj
  test/metabase/dashboard_subscription_test.clj
  test/metabase/notification/payload/impl/card_test.clj
Labels: backport, .Team/Workflows

#56067 🤖 backported "test: move flaky test to jail"
  e2e/test/scenarios/embedding/embedding-questions.cy.spec.js
Labels: was-backported

#56075 :row/delete also wanted some joins
  src/metabase/driver/sql_jdbc/actions.clj
Labels: .Team/Workflows

#56068 WRK-213: Adjust available intervals for 'by the minute' schedule option
  frontend/src/metabase/components/Schedule/Schedule.tsx
  frontend/src/metabase/components/Schedule/Schedule.unit.spec.tsx
  frontend/src/metabase/components/Schedule/strings.ts
Labels: no-backport, .Team/Workflows

#56065 WRK-198: Custom notifications templates
  enterprise/frontend/src/metabase-enterprise/api/table-data-edit.ts
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/EditTableDataGrid.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/EditTableDataHeader.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/inputs/EditingBodyCellBasicInput.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/inputs/EditingBodyCellCategorySelect.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/modals/EditingBaseRowModal.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/view/BrowseTableData.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/view/BrowseTableDataGrid.tsx
  frontend/src/metabase-types/api/notification-channels.ts
  frontend/src/metabase-types/api/notification.ts
  frontend/src/metabase/dashboard/components/TablePicker/TableList.tsx
  frontend/src/metabase/notifications/modals/AlertsModals/CreateOrEditQuestionAlertModal/CreateOrEditQuestionAlertModal.tsx
  frontend/src/metabase/notifications/modals/AlertsModals/QuestionAlertListModal/QuestionAlertListModal.tsx
  frontend/src/metabase/notifications/modals/TableNotificationsModals/CreateOrEditTableNotificationModal/CreateOrEditTableNotificationModal.tsx
  frontend/src/metabase/notifications/modals/TableNotificationsModals/CreateOrEditTableNotificationModal/CreateOrEditTableNotificationModal.unit.spec.tsx
  frontend/src/metabase/notifications/modals/TableNotificationsModals/TableNotificationsListModal/TableNotificationsListItem.tsx
  frontend/src/metabase/notifications/modals/TableNotificationsModals/TableNotificationsListModal/TableNotificationsListModal.stories.tsx
  frontend/src/metabase/notifications/modals/TableNotificationsModals/TableNotificationsListModal/TableNotificationsListModal.tsx
  frontend/src/metabase/notifications/modals/TableNotificationsModals/TableNotificationsListModal/TableNotificationsListModal.unit.spec.tsx
  frontend/src/metabase/notifications/modals/TableNotificationsModals/TableNotificationsTrigger.tsx
  frontend/src/metabase/notifications/modals/index.ts
  frontend/src/metabase/notifications/modals/shared/components/HandlersInfo.tsx
  frontend/src/metabase/notifications/modals/shared/components/NotificationChannels/NotificationChannelsAddMenu.tsx
  frontend/src/metabase/notifications/modals/shared/components/NotificationChannels/NotificationChannelsPicker/NotificationChannelsPicker.module.css
  frontend/src/metabase/notifications/modals/shared/components/NotificationChannels/NotificationChannelsPicker/NotificationChannelsPicker.tsx
  frontend/src/metabase/notifications/modals/shared/components/NotificationChannels/NotificationChannelsPicker/NotificationChannelsPicker.unit.spec.tsx
  frontend/src/metabase/notifications/modals/shared/components/NotificationChannels/NotificationChannelsPicker/templates/delete.json
  frontend/src/metabase/notifications/modals/shared/components/NotificationChannels/NotificationChannelsPicker/templates/insert.json
  frontend/src/metabase/notifications/modals/shared/components/NotificationChannels/NotificationChannelsPicker/templates/update.json
  frontend/src/metabase/notifications/modals/shared/components/NotificationChannels/NotificationChannelsPicker/test-utils.tsx
  frontend/src/metabase/notifications/modals/shared/components/NotificationChannelsPicker/NotificationChannelsPicker.tsx
Labels: .Team/Workflows

#55864 🤖 backported "support keys in env vars"
  enterprise/backend/src/metabase_enterprise/advanced_config/file/api_keys.clj
  enterprise/backend/test/metabase_enterprise/advanced_config/file/api_keys_test.clj
Labels: was-backported

#56073 Add cloud-ops as codeowners of prometheus.clj
  .github/CODEOWNERS
Labels: no-backport

#56079 fix schedules
  src/metabase/sync/schedules.clj
Labels: .Team/Workflows

#56078 v53: Allow escape square brackets in identifier
  e2e/test/scenarios/custom-column/custom-column-reproductions.cy.spec.js
  frontend/src/metabase-lib/v1/expressions/tokenizer.ts
  frontend/src/metabase-lib/v1/expressions/tokenizer.unit.spec.ts
Labels: no-backport, .Team/Querying

#56082 Fix table alerts delete from Account Settings
  frontend/src/metabase/account/notifications/actions.js
  frontend/src/metabase/notifications/modals/TableNotificationsModals/TableNotificationsListModal/TableNotificationsListModal.unit.spec.tsx
Labels: .Team/Workflows

#56071 test: add a fix for flaky test but move to jail anyway
  e2e/support/helpers/e2e-collection-helpers.ts
  e2e/test/scenarios/metrics/metrics-collection.cy.spec.js
Labels: backport, .Team/Querying

#56016 fix scatter charts freeze page
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/src/metabase/visualizations/lib/timeseries.js
Labels: .Team/DashViz, double-backport

#56086 🤖 backported "test: add a fix for flaky test but move to jail anyway"
  e2e/support/helpers/e2e-collection-helpers.ts
  e2e/test/scenarios/metrics/metrics-collection.cy.spec.js
Labels: was-backported

#56090 🤖 backported "ci: run sample app tests and sdk cross version tests on draft prs"
  .github/workflows/e2e-component-tests-embedding-sdk-cross-version.yml
  .github/workflows/e2e-sample-apps-tests.yml
Labels: was-backported

#56089 🤖 backported "ci: run sample app tests and sdk cross version tests on draft prs"
  .github/workflows/e2e-component-tests-embedding-sdk-cross-version.yml
  .github/workflows/e2e-sample-apps-tests.yml
Labels: was-backported

#56092 🤖 backported "fix scatter charts freeze page"
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/src/metabase/visualizations/lib/timeseries.js
Labels: was-backported

#56091 🤖 backported "fix scatter charts freeze page"
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/src/metabase/visualizations/lib/timeseries.js
Labels: was-backported

#56033 Bigquery handles nested fields in nested queries appropriately
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj
  test/metabase/query_processor_test/nested_field_test.clj
Labels: backport, .Team/Querying

#56034 docs - note on caching and permissions
  docs/configuring-metabase/caching.md
Labels: Type:Documentation, backport

#56097 🤖 backported "docs - note on caching and permissions"
  docs/configuring-metabase/caching.md
Labels: was-backported

#56095 🤖 backported "Bigquery handles nested fields in nested queries appropriately"
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj
  test/metabase/query_processor_test/nested_field_test.clj
Labels: was-backported

#55934 task: update ee-extra to understand noop from registry
  .github/actions/build-ee-extra/action.yml
Labels: backport, .Team/Drivers

#56107 🤖 backported "task: update ee-extra to understand noop from registry"
  .github/actions/build-ee-extra/action.yml
Labels: was-backported

#56074 Add `./bin/mage start-maildev` command
  bb.edn
  mage/mage/start_maildev.clj
Labels: no-backport, .Team/AdminWebapp

#56093 test: add native query test to flaky group
  e2e/test/scenarios/native/native.cy.spec.js
Labels: backport, .Team/Querying

#56108 🤖 backported "test: add native query test to flaky group"
  e2e/test/scenarios/native/native.cy.spec.js
Labels: was-backported

#56111 Revert #56007
  .github/workflows/o401.yml
Labels: .CI & Tests, no-backport, .Team/AdminWebapp

#55889 Add job context for all quartz jobs
  .clj-kondo/config.edn
  enterprise/backend/src/metabase_enterprise/task/cache.clj
  src/metabase/indexed_entities/task/index_values.clj
  src/metabase/lib_be/task/backfill_entity_ids.clj
  src/metabase/model_persistence/task/persist_refresh.clj
  src/metabase/notification/task/send.clj
  src/metabase/pulse/task/email_remove_legacy_pulse.clj
  src/metabase/pulse/task/send_pulses.clj
  src/metabase/query_analysis/task/analyze_queries.clj
  src/metabase/query_analysis/task/sweep_query_analysis.clj
  src/metabase/search/task/search_index.clj
  src/metabase/session/task/session_cleanup.clj
  src/metabase/sync/task/sync_databases.clj
  src/metabase/task.clj
  src/metabase/task/QUARTZ.md
  src/metabase/task/creator_sentiment_emails.clj
  src/metabase/task/follow_up_emails.clj
  src/metabase/task/refresh_slack_channel_user_cache.clj
  src/metabase/task/send_anonymous_stats.clj
  src/metabase/task/task_history_cleanup.clj
  src/metabase/task/truncate_audit_tables.clj
  src/metabase/task/upgrade_checks.clj
  test/metabase/db/custom_migrations_test.clj
  test/metabase/task_test.clj
Labels: backport, .Team/Workflows

#56118 🤖 backported "Add job context for all quartz jobs"
  .clj-kondo/config.edn
  enterprise/backend/src/metabase_enterprise/task/cache.clj
  src/metabase/indexed_entities/task/index_values.clj
  src/metabase/lib_be/task/backfill_entity_ids.clj
  src/metabase/model_persistence/task/persist_refresh.clj
  src/metabase/notification/task/send.clj
  src/metabase/pulse/task/email_remove_legacy_pulse.clj
  src/metabase/pulse/task/send_pulses.clj
  src/metabase/query_analysis/task/analyze_queries.clj
  src/metabase/query_analysis/task/sweep_query_analysis.clj
  src/metabase/search/task/search_index.clj
  src/metabase/session/task/session_cleanup.clj
  src/metabase/sync/task/sync_databases.clj
  src/metabase/task.clj
  src/metabase/task/QUARTZ.md
  src/metabase/task/creator_sentiment_emails.clj
  src/metabase/task/follow_up_emails.clj
  src/metabase/task/refresh_slack_channel_user_cache.clj
  src/metabase/task/send_anonymous_stats.clj
  src/metabase/task/task_history_cleanup.clj
  src/metabase/task/truncate_audit_tables.clj
  src/metabase/task/upgrade_checks.clj
  test/metabase/db/custom_migrations_test.clj
  test/metabase/task_test.clj
Labels: was-backported

#55863 Add String->Float coercion strategy
  modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj
  src/metabase/driver/sql/query_processor.clj
  src/metabase/types.cljc
  test/metabase/query_processor_test/coercion_test.clj
  test/metabase/test/data/dataset_definitions.clj
Labels: no-backport, .Team/SemanticLayer

#56123 Flaky test fix: unsubscribe-receive-email-test
  test/metabase/channel/email_test.clj
  test/metabase/notification/api/notification_test.clj
Labels: backport, .Team/Workflows

#56054 🤖 backported "Fix overflow in expression editor suggestions"
  e2e/test/scenarios/custom-column/custom-column-reproductions.cy.spec.js
  frontend/src/metabase/query_builder/components/expressions/Editor/Listbox/Listbox.module.css
Labels: was-backported

#55982 🤖 backported "[Notification] more 🪵"
  src/metabase/channel/email/result_attachment.clj
  src/metabase/channel/render/card.clj
  src/metabase/notification/payload/execute.clj
  src/metabase/notification/payload/impl/card.clj
  src/metabase/notification/payload/impl/dashboard.clj
  src/metabase/notification/payload/temp_storage.clj
  src/metabase/notification/send.clj
  src/metabase/util/log.clj
  test/metabase/util/log_test.clj
Labels: was-backported

#56126 🤖 backported "Flaky test fix: unsubscribe-receive-email-test"
  test/metabase/channel/email_test.clj
  test/metabase/notification/api/notification_test.clj
Labels: was-backported

#56125 fix testing and CDPATH issues with mage
  .github/workflows/backend.yml
  bb.edn
  bin/mage
  test/mage/core_test.clj
  test/mage/runtests.clj
  test/mage/start_db_test.clj
Labels: backport, .Team/Workflows

#56128 🤖 backported "fix testing and CDPATH issues with mage"
  .github/workflows/backend.yml
  bin/mage
  test/mage/core_test.clj
  test/mage/runtests.clj
  test/mage/start_db_test.clj
Labels: was-backported

#56127 test(sdk): Fix storybook not working properly when a component uses EE plugins
  enterprise/frontend/src/embedding-sdk/test/storybook-themes.ts
Labels: .Team/Embedding, double-backport

#56081 Fix - Visibility explanation copy is the same across all 3 options
  frontend/src/metabase/admin/datamodel/metadata/components/FieldVisibilityPicker/FieldVisibilityPicker.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/FieldVisibilityPicker/FieldVisibilityPicker.unit.spec.tsx
Labels: backport, .Team/SemanticLayer

#56133 🤖 backported "test(sdk): Fix storybook not working properly when a component uses EE plugins"
  enterprise/frontend/src/embedding-sdk/test/storybook-themes.ts
Labels: was-backported

#56135 Make editables models instead of questions
  src/metabase/api/dashboard.clj
  src/metabase/models/card.clj
Labels: .Team/Workflows

#56132 🤖 backported "test(sdk): Fix storybook not working properly when a component uses EE plugins"
  enterprise/frontend/src/embedding-sdk/test/storybook-themes.ts
Labels: was-backported

#56134 🤖 backported "Fix - Visibility explanation copy is the same across all 3 options"
  frontend/src/metabase/admin/datamodel/metadata/components/FieldVisibilityPicker/FieldVisibilityPicker.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/FieldVisibilityPicker/FieldVisibilityPicker.unit.spec.tsx
Labels: was-backported

#56024 Webhook ingestion
  .clj-kondo/config/modules/config.edn
  enterprise/backend/src/metabase_enterprise/api/routes.clj
  enterprise/backend/src/metabase_enterprise/data_editing/api.clj
  enterprise/backend/src/metabase_enterprise/data_editing/data_editing.clj
  enterprise/backend/src/metabase_enterprise/data_editing_public/api.clj
  enterprise/backend/test/metabase_enterprise/data_editing/api_test.clj
  resources/migrations/001_update_migrations.yaml
Labels: .Team/Workflows

#56096 Fix chain filters on public dashboards
  src/metabase/public_sharing/api.clj
  test/metabase/public_sharing/api_test.clj
Labels: backport, .Team/Querying, double-backport

#56136 feat: add editable table dashcard configuration sidebar
  frontend/src/metabase-types/store/dashboard.ts
  frontend/src/metabase/dashboard/actions/ui.ts
  frontend/src/metabase/dashboard/components/ConfigureEditableTableSidebar.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardActionsPanel.tsx
  frontend/src/metabase/dashboard/components/DashboardSidebars.tsx
  frontend/src/metabase/dashboard/constants.ts
  frontend/src/metabase/visualizations/types/visualization.ts
  frontend/src/metabase/visualizations/visualizations/TableEditable.tsx
Labels: .Team/Workflows

#56142 🤖 backported "Fix chain filters on public dashboards"
  src/metabase/api/public.clj
  test/metabase/api/public_test.clj
Labels: was-backported

#56141 🤖 backported "Fix chain filters on public dashboards"
  src/metabase/public_sharing/api.clj
  test/metabase/public_sharing/api_test.clj
Labels: was-backported

#56143 Remove opacity from viz settings gear icon
  frontend/src/metabase/query_builder/components/view/ViewButton.module.css
  frontend/src/metabase/query_builder/components/view/ViewButton.tsx
Labels: backport, .Team/DashViz

#56156 🤖 backported "Remove opacity from viz settings gear icon"
  frontend/src/metabase/query_builder/components/view/ViewButton.module.css
  frontend/src/metabase/query_builder/components/view/ViewButton.tsx
Labels: was-backported

#56087 Make mongo between condition inclusive
  modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj
  test/metabase/query_processor_test/aggregation_test.clj
Labels: backport, .Team/Drivers

#56150 docs - mention config file on api keys page
  docs/people-and-groups/api-keys.md
Labels: Type:Documentation, backport

#56161 🤖 backported "Make mongo between condition inclusive"
  modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj
  test/metabase/query_processor_test/aggregation_test.clj
Labels: was-backported

#56164 🤖 backported "docs - mention config file on api keys page"
  docs/people-and-groups/api-keys.md
Labels: was-backported

#56153 Split :cast into three features
  docs/developers-guide/driver-changelog.md
  frontend/src/metabase-lib/v1/expressions/__support__/shared.ts
  frontend/src/metabase-lib/v1/expressions/config.ts
  frontend/src/metabase-types/api/database.ts
  src/metabase/driver.clj
  src/metabase/driver/postgres.clj
  src/metabase/legacy_mbql/schema.cljc
Labels: backport, .Team/Querying

#56166 fix: ee-build should skip adding jars when there are none
  .github/actions/build-ee-extra/action.yml
Labels: backport, .Team/Drivers

#56167 🤖 backported "fix: ee-build should skip adding jars when there are none"
  .github/actions/build-ee-extra/action.yml
Labels: was-backported

#56145 fix: correct setting name check for static stats
  enterprise/backend/src/metabase_enterprise/internal_stats.clj
  enterprise/backend/test/metabase_enterprise/internal_stats_test.clj
  src/metabase/premium_features/token_check.clj
Labels: .Team/AdminWebapp, double-backport

#56165 🤖 backported "Split :cast into three features"
  docs/developers-guide/driver-changelog.md
  frontend/src/metabase-lib/v1/expressions/__support__/shared.ts
  frontend/src/metabase-lib/v1/expressions/config.ts
  frontend/src/metabase-types/api/database.ts
  src/metabase/driver.clj
  src/metabase/driver/postgres.clj
  src/metabase/legacy_mbql/schema.cljc
Labels: was-backported

#56171 fix: attempt no 2 to skip adding non-existent partner jars
  .github/actions/build-ee-extra/action.yml
Labels: backport, .Team/Drivers

#56172 🤖 backported "fix: attempt no 2 to skip adding non-existent partner jars"
  .github/actions/build-ee-extra/action.yml
Labels: was-backported

#56169 🤖 backported "fix: correct setting name check for static stats"
  enterprise/backend/src/metabase_enterprise/internal_stats.clj
  enterprise/backend/test/metabase_enterprise/internal_stats_test.clj
  src/metabase/premium_features/token_check.clj
Labels: was-backported

#56168 🤖 backported "fix: correct setting name check for static stats"
  enterprise/backend/src/metabase_enterprise/internal_stats.clj
  enterprise/backend/test/metabase_enterprise/internal_stats_test.clj
  src/metabase/premium_features/token_check.clj
Labels: was-backported

#56162 docs - table viz updates
  docs/questions/images/column-header-formatting.png
  docs/questions/images/column-selection.png
  docs/questions/images/conditional-formatting.png
  docs/questions/images/paginate-table-on-dashboard-card.png
  docs/questions/images/pivot.png
  docs/questions/images/show-row-index.png
  docs/questions/visualizations/table.md
Labels: Type:Documentation, backport

#56170 dont skip mage tests when BE job is skipped
  .github/workflows/backend.yml
  .github/workflows/mage.yml
  bb.edn
  test/mage/core_test.clj
  test/mage/runtests.clj
Labels: no-backport

#55969 perf: Optimize settings retrieval
  src/metabase/models/setting.clj
  src/metabase/models/setting/cache.clj
  test/metabase/models/setting/cache_test.clj
Labels: backport

#56112 Change decimal field for Number question to only accept positive integers and update E2E test to cover edge cases
  e2e/test/scenarios/visualizations-tabular/smartscalar-trend.cy.spec.js
  frontend/src/metabase/visualizations/lib/settings/column.js
Labels: backport, .Team/DashViz

#56183 🤖 backported "Change decimal field for Number question to only accept positive integers and update E2E test to cover edge cases"
  e2e/test/scenarios/visualizations-tabular/smartscalar-trend.cy.spec.js
  frontend/src/metabase/visualizations/lib/settings/column.js
Labels: was-backported

#55583 Allow toggling folder/sheet import for gsheets
  enterprise/frontend/src/metabase-enterprise/api/gdrive.ts
  enterprise/frontend/src/metabase-enterprise/google_drive/Gdrive.module.css
  enterprise/frontend/src/metabase-enterprise/google_drive/GdriveConnectionModal.strings.ts
  enterprise/frontend/src/metabase-enterprise/google_drive/GdriveConnectionModal.tsx
  enterprise/frontend/src/metabase-enterprise/google_drive/GdriveConnectionModal.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/google_drive/GdriveSyncStatus.tsx
  frontend/test/__support__/server-mocks/gdrive.ts
Labels: no-backport, .Team/AdminWebapp

#56181 🤖 backported "perf: Optimize settings retrieval"
  src/metabase/models/setting.clj
  src/metabase/models/setting/cache.clj
  test/metabase/models/setting/cache_test.clj
Labels: was-backported

#55941 Unified tests for `splitPart()`
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj
  modules/drivers/redshift/test/metabase/driver/redshift_test.clj
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  src/metabase/legacy_mbql/schema.cljc
  src/metabase/lib/schema/expression.cljc
  src/metabase/lib/schema/expression/string.cljc
  test/metabase/driver/mysql_test.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/query_processor_test/split_part_test.clj
Labels: do not merge, no-backport, .Team/Querying

#56184 docs - remove partner drivers
  docs/databases/connecting.md
  docs/databases/connections/sparksql.md
  docs/databases/sync-scan.md
  docs/databases/uploads.md
  docs/developers-guide/community-drivers.md
  docs/developers-guide/drivers/start.md
  docs/developers-guide/partner-and-community-drivers.md
  docs/developers-guide/start.md
  docs/people-and-groups/api-keys.md
  docs/questions/visualizations/table.md
Labels: Type:Documentation, backport

#56187 🤖 backported "docs - remove partner drivers"
  docs/databases/connecting.md
  docs/databases/connections/sparksql.md
  docs/databases/sync-scan.md
  docs/databases/uploads.md
  docs/developers-guide/community-drivers.md
  docs/developers-guide/drivers/start.md
  docs/developers-guide/partner-and-community-drivers.md
  docs/developers-guide/start.md
  docs/people-and-groups/api-keys.md
  docs/questions/visualizations/table.md
Labels: was-backported

#55067 Fix formatter support for field id or name col settings
  src/metabase/formatter.clj
  src/metabase/formatter/datetime.clj
  src/metabase/query_processor/streaming/common.clj
  test/metabase/formatter/datetime_test.clj
  test/metabase/formatter_test.clj
Labels: .Backend, backport, .Team/DashViz

#56188 🤖 backported "Fix formatter support for field id or name col settings"
  src/metabase/formatter.clj
  src/metabase/formatter/datetime.clj
  src/metabase/query_processor/streaming/common.clj
  test/metabase/formatter/datetime_test.clj
  test/metabase/formatter_test.clj
Labels: was-backported

#56173 fix: deadlock in last used at
  resources/migrations/001_update_migrations.yaml
  src/metabase/query_processor/middleware/update_used_cards.clj
  test/metabase/query_processor/middleware/update_used_cards_test.clj
Labels: .Team/AdminWebapp, double-backport

#56199 Revert search engine default to in-place
  .github/workflows/e2e-test.yml
  src/metabase/public_settings.clj
Labels: backport, .Team/AdminWebapp

#56200 🤖 backported "Revert search engine default to in-place"
  .github/workflows/e2e-test.yml
  src/metabase/public_settings.clj
Labels: was-backported

#56149 Remodel system event notification
  deps.edn
  resources/migrations/001_update_migrations.yaml
  src/metabase/cmd/copy.clj
  src/metabase/notification/api/notification.clj
  src/metabase/notification/models.clj
  src/metabase/notification/seed.clj
  src/metabase/sync/task/sync_databases.clj
  src/metabase/task.clj
  test/metabase/events/notification_test.clj
  test/metabase/notification/api/notification_test.clj
  test/metabase/notification/models_test.clj
  test/metabase/notification/payload/impl/system_event_test.clj
  test/metabase/notification/seed_test.clj
  test/metabase/notification/test_util.clj
Labels: .Team/Workflows

#55526 fix(sdk): Remove 'Unrecognized Props' error from InteractiveDashboard
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.module.css
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.styled.tsx
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.tsx
Labels: .Team/Embedding

#56146 SEM-212 Allow clicking on the Segment's name to navigate to its edit screen
  e2e/test/scenarios/admin/datamodel/datamodel.cy.spec.js
  frontend/src/metabase/admin/datamodel/components/SegmentItem.jsx
Labels: no-backport, .Team/SemanticLayer

#56051 🤖 backported "QueryDownloadPopover -> QuestionDownloadWidget + QueryDownloadWidget -> QuestionDownloadPopover"
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/DownloadWidget/DownloadWidget.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestionView.tsx
  frontend/src/metabase/query_builder/components/QueryDownloadPopover/index.ts
  frontend/src/metabase/query_builder/components/QuestionDownloadPopover/QuestionDownloadPopover.tsx
  frontend/src/metabase/query_builder/components/QuestionDownloadPopover/QuestionDownloadPopover.unit.spec.tsx
  frontend/src/metabase/query_builder/components/QuestionDownloadPopover/index.ts
  frontend/src/metabase/query_builder/components/QuestionDownloadWidget/QuestionDownloadWidget.tsx
  frontend/src/metabase/query_builder/components/QuestionDownloadWidget/QuestionDownloadWidget.unit.spec.tsx
  frontend/src/metabase/query_builder/components/QuestionDownloadWidget/index.ts
  frontend/src/metabase/query_builder/components/QuestionDownloadWidget/use-download-data.ts
  frontend/src/metabase/query_builder/components/view/ViewFooter/ViewFooterDownloadWidget.tsx
Labels: was-backported

#56206 🤖 backported "fix(sdk): Clean up "Unrecognized Prop" errors on CreateDashboardModal"
  enterprise/frontend/src/embedding-sdk/components/public/CreateDashboardModal/CreateDashboardModal.tsx
Labels: was-backported

#56203 Invalidate field values on insert/update
  .clj-kondo/config/modules/config.edn
  enterprise/backend/src/metabase_enterprise/data_editing/api.clj
  enterprise/backend/test/metabase_enterprise/data_editing/api_test.clj
Labels: .Team/Workflows

#56204 refactor: move editable table siderbar into separate folder
  frontend/src/metabase/dashboard/components/ConfigureEditableTableSidebar/ConfigureEditableTableSidebar.tsx
  frontend/src/metabase/dashboard/components/DashboardSidebars.tsx
Labels: .Team/Workflows

#56198 docs: update api and env var docs for master
  docs/api.html
  docs/configuring-metabase/environment-variables.md
Labels: Type:Documentation, no-backport

#56197 docs: update env var docs for 54
  docs/configuring-metabase/environment-variables.md
Labels: Type:Documentation, no-backport

#56099 Add minimal E2E test suite for visualizer
  e2e/test/scenarios/dashboard/dashboard-visualizer.cy.spec.js
  e2e/test/scenarios/visualizations-charts/line_chart.cy.spec.js
  frontend/src/metabase/dashboard/actions/data-fetching.ts
  frontend/src/metabase/dashboard/components/QuestionPicker/QuestionList.tsx
  frontend/src/metabase/visualizations/components/settings/ChartNestedSettingSeriesMultiple.jsx
  frontend/src/metabase/visualizations/components/settings/ChartNestedSettingSeriesMultiple.unit.spec.js
  frontend/src/metabase/visualizations/components/settings/ChartNestedSettingSeriesSingle.tsx
  frontend/src/metabase/visualizer/components/DataManager/DataManager.tsx
  frontend/src/metabase/visualizer/components/DataManager/DatasetList.tsx
  frontend/src/metabase/visualizer/components/VisualizationCanvas/HorizontalWell/FunnelHorizontalWell.tsx
  frontend/src/metabase/visualizer/components/VisualizationCanvas/VerticalWell/PieVerticalWell.tsx
  frontend/src/metabase/visualizer/components/VisualizationCanvas/VerticalWell/WellBox.tsx
  frontend/src/metabase/visualizer/components/VisualizationCanvas/VisualizationCanvas.tsx
  frontend/src/metabase/visualizer/components/VisualizationCanvas/WellItem.tsx
  frontend/src/metabase/visualizer/components/VisualizationPicker/VisualizationPicker.tsx
  frontend/src/metabase/visualizer/components/Visualizer/Visualizer.tsx
  frontend/src/metabase/visualizer/visualizations/funnel.ts
Labels: .Team/DashViz

#56193 🤖 backported "fix: deadlock in last used at"
  resources/migrations/001_update_migrations.yaml
  src/metabase/query_processor/middleware/update_used_cards.clj
  test/metabase/query_processor/middleware/update_used_cards_test.clj
Labels: was-backported

#56155 Multi line help text
  e2e/support/helpers/e2e-custom-column-helpers.ts
  e2e/test/scenarios/custom-column/custom-column-reproductions.cy.spec.js
  frontend/src/metabase-lib/v1/expressions/position.ts
  frontend/src/metabase-lib/v1/expressions/position.unit.spec.ts
Labels: backport, .Team/Querying

#56192 🤖 backported "fix: deadlock in last used at"
  resources/migrations/001_update_migrations.yaml
  src/metabase/query_processor/middleware/update_used_cards.clj
  test/metabase/query_processor/middleware/update_used_cards_test.clj
Labels: was-backported

#56189 Changelog for api/card/:card-id/query/export-format
  docs/developers-guide/api-changelog.md
  src/metabase/api/card.clj
Labels: double-backport

#55995 Fix - When DB is stuck in a Sync Loop, DB List in Native Editor Blinks Constantly
  e2e/test/scenarios/native/native-reproductions.cy.spec.ts
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.module.css
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.unit.spec.js
  frontend/src/metabase/query_builder/components/DataSelector/data-search/SearchResults.jsx
  frontend/src/metabase/query_builder/components/DataSelector/data-search/SearchResults.module.css
  frontend/src/metabase/query_builder/components/DataSelector/data-search/index.js
  frontend/src/metabase/query_builder/components/DataSelector/data-search/utils.js
Labels: double-backport, .Team/SemanticLayer

#56205 feat(sdk): Apply dts rollup to generate a single .d.ts file with types
  bin/embedding-sdk/fixup-types-after-compilation.js
  enterprise/frontend/src/embedding-sdk/bin/generate-nextjs-compat.ts
  enterprise/frontend/src/embedding-sdk/embedding-sdk-api-extractor.json
  enterprise/frontend/src/embedding-sdk/package.template.json
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase-lib/v1/queries/NativeQuery.ts
  package.json
  tsconfig.sdk.json
  yarn.lock
Labels: no-backport, .Team/Embedding

#55796 🤖 backported "Allow Assertion Functions in Jest Tests"
  .eslintrc.js
  enterprise/frontend/src/embedding-sdk/test/sdk-config-errors.unit.spec.tsx
  frontend/src/metabase-lib/v1/expressions/formatter/formatter.unit.spec.ts
  frontend/src/metabase/admin/settings/components/CloudPanel/CloudPanel.unit.spec.tsx
  frontend/src/metabase/components/TokenField/TokenField.unit.spec.js
  frontend/src/metabase/core/components/AccordionList/AccordionList.unit.spec.js
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeaderButtonRow/DashboardHeaderButtonRow.unit.spec.tsx
  frontend/src/metabase/hooks/use-list-keyboard-navigation/use-list-keyboard-navigation.unit.spec.ts
  frontend/src/metabase/lib/formatting/link.unit.spec.tsx
  frontend/src/metabase/nav/containers/Navbar.unit.spec.tsx
  frontend/src/metabase/public/LocaleProvider.unit.spec.ts
  frontend/src/metabase/querying/notebook/components/Notebook/Notebook.unit.spec.tsx
  frontend/src/metabase/querying/notebook/components/NotebookStepList/NotebookStepList.unit.spec.tsx
  frontend/src/metabase/setup/tests/common.unit.spec.tsx
  frontend/src/metabase/setup/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/setup/tests/premium-pro-cloud.unit.spec.tsx
  frontend/src/metabase/setup/tests/premium-pro-selfhosted.unit.spec.tsx
  frontend/src/metabase/setup/tests/premium-starter-cloud.unit.spec.tsx
Labels: was-backported

#56214 🤖 backported "fix(sdk): Add `questionProps` to dashboard components"
  docs/embedding/sdk/dashboards.md
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveAdHocQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionDefaultView/InteractiveQuestionDefaultView.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/EditableDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.tsx
Labels: was-backported

#56219 🤖 backported "Fix - When DB is stuck in a Sync Loop, DB List in Native Editor Blinks Constantly "
  e2e/test/scenarios/native/native-reproductions.cy.spec.ts
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.module.css
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.unit.spec.js
  frontend/src/metabase/query_builder/components/DataSelector/data-search/SearchResults.jsx
  frontend/src/metabase/query_builder/components/DataSelector/data-search/SearchResults.module.css
  frontend/src/metabase/query_builder/components/DataSelector/data-search/index.js
  frontend/src/metabase/query_builder/components/DataSelector/data-search/utils.js
Labels: was-backported

#56217 🤖 backported "Changelog for api/card/:card-id/query/export-format"
  docs/developers-guide/api-changelog.md
  src/metabase/api/card.clj
Labels: was-backported

#56101 Introduce metabot-id
  .clj-kondo/config/modules/config.edn
  enterprise/backend/src/metabase_enterprise/metabot_v3/api.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/repl.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/api.clj
  enterprise/backend/test/metabase_enterprise/api/session_test.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/api_test.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/tools/api_test.clj
Labels: Metabot/Tools

#56154 fix: make saml issuer identity required
  e2e/test/scenarios/admin-2/sso/saml.cy.spec.js
  e2e/test/scenarios/admin-2/sso/shared/helpers.js
  enterprise/frontend/src/metabase-enterprise/auth/components/SettingsSAMLForm/SettingsSAMLForm.jsx
Labels: .Team/AdminWebapp, double-backport

#56222 Revert "🤖 backported "fix(sdk): Clean up "Unrecognized Prop" errors on CreateDashboardModal""
  enterprise/frontend/src/embedding-sdk/components/public/CreateDashboardModal/CreateDashboardModal.tsx
Labels: .Team/Embedding

#56221 (mini-PR) Localize string in sidesheet
  frontend/src/metabase/components/EntityIdCard/EntityIdCard.tsx
Labels: backport, .Team/AdminWebapp, double-backport, triple-backport

#56139 test: use dynamic data for referencing columns and tables instead of static
  e2e/test/scenarios/visualizations-charts/line-bar-tooltips.cy.spec.js
Labels: backport, .Team/Querying

#56226 🤖 backported "(mini-PR) Localize string in sidesheet"
  frontend/src/metabase/components/EntityIdCard/EntityIdCard.tsx
Labels: was-backported

#56228 🤖 backported "(mini-PR) Localize string in sidesheet"
  frontend/src/metabase/components/EntityIdCard/EntityIdCard.tsx
Labels: was-backported

#56229 🤖 backported "test: use dynamic data for referencing columns and tables instead of static"
  e2e/test/scenarios/visualizations-charts/line-bar-tooltips.cy.spec.js
Labels: was-backported

#56030 🤖 backported "Limit tsvector inserts to 1048575 bytes"
  src/metabase/search/appdb/specialization/postgres.clj
  src/metabase/util/string.clj
  test/metabase/util/string_test.clj
Labels: was-backported

#56100 fix(sdk): fix dataset endpoint being called on every re-render
  e2e/test-component/scenarios/embedding-sdk/interactive-dashboard.cy.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveAdHocQuestion.tsx
Labels: .Team/Embedding, Embedding/SDK, double-backport

#56233 🤖 backported "fix(sdk): fix dataset endpoint being called on every re-render"
  e2e/test-component/scenarios/embedding-sdk/interactive-dashboard.cy.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveAdHocQuestion.tsx
Labels: was-backported

#56230 docs - various changes
  docs/configuring-metabase/config-file.md
  docs/configuring-metabase/config-template.md
  docs/developers-guide/community-drivers.md
  docs/questions/visualizations/table.md
  src/metabase/cmd/resources/config-template.yaml
Labels: Type:Documentation, backport

#54938 Support for individual google sheets
  enterprise/backend/src/metabase_enterprise/gsheets/api.clj
  enterprise/backend/test/metabase_enterprise/api/gsheets_test.clj
  enterprise/frontend/src/metabase-enterprise/api/gdrive.ts
  enterprise/frontend/src/metabase-enterprise/google_drive/Gdrive.module.css
  enterprise/frontend/src/metabase-enterprise/google_drive/GdriveConnectionModal.strings.ts
  enterprise/frontend/src/metabase-enterprise/google_drive/GdriveConnectionModal.tsx
  enterprise/frontend/src/metabase-enterprise/google_drive/GdriveConnectionModal.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/google_drive/GdriveSyncStatus.tsx
  frontend/test/__support__/server-mocks/gdrive.ts
  test_resources/gsheets/mock_hm_responses.edn
Labels: backport, .Team/AdminWebapp

#55952 Integration branch for generalizing cast tests
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj
  modules/drivers/redshift/test/metabase/driver/redshift_test.clj
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  test/metabase/driver/mysql_test.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/query_processor_test/cast_test.clj
Labels: no-backport, .Team/Querying

#55920 Add explicit CAST when compiling string literal expressions in H2 driver
  e2e/test/scenarios/custom-column/cc-literals.cy.spec.ts
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
  frontend/src/metabase-lib/v1/expressions/__support__/expressions.ts
  frontend/src/metabase-lib/v1/expressions/compiler.unit.spec.ts
  frontend/src/metabase-lib/v1/expressions/matchers.ts
  frontend/src/metabase-lib/v1/expressions/passes.ts
  frontend/src/metabase-types/api/mocks/database.ts
  src/metabase/driver/h2.clj
  src/metabase/legacy_mbql/normalize.cljc
  test/metabase/legacy_mbql/normalize_test.cljc
  test/metabase/lib/convert_test.cljc
  test/metabase/lib/expression_test.cljc
  test/metabase/lib/js_test.cljs
  test/metabase/lib/test_metadata.cljc
  test/metabase/query_processor_test/expression_aggregations_test.clj
  test/metabase/query_processor_test/expressions_test.clj
  test/metabase/query_processor_test/nested_queries_test.clj
Labels: no-backport, .Team/Querying

#55956 add additional fields to payload for create-release-issues
  .github/workflows/release.yml
Labels: no-backport

#56224 🤖 backported "fix: make saml issuer identity required"
  e2e/test/scenarios/admin-2/sso/saml.cy.spec.js
  e2e/test/scenarios/admin-2/sso/shared/helpers.js
  enterprise/frontend/src/metabase-enterprise/auth/components/SettingsSAMLForm/SettingsSAMLForm.jsx
Labels: was-backported

#56225 🤖 backported "fix: make saml issuer identity required"
  e2e/test/scenarios/admin-2/sso/saml.cy.spec.js
  e2e/test/scenarios/admin-2/sso/shared/helpers.js
  enterprise/frontend/src/metabase-enterprise/auth/components/SettingsSAMLForm/SettingsSAMLForm.jsx
Labels: was-backported

#56250 skip tooltip loki specs
  frontend/src/metabase/visualizations/components/ChartTooltip/EChartsTooltip/EChartsTooltip.stories.tsx
Labels: backport, .Team/DashViz

#56253 🤖 backported "skip tooltip loki specs"
  frontend/src/metabase/visualizations/components/ChartTooltip/EChartsTooltip/EChartsTooltip.stories.tsx
Labels: was-backported

#56262 [Notification] Simplify payload for system event
  deps.edn
  enterprise/backend/test/metabase_enterprise/data_editing/notification_test.clj
  frontend/src/metabase/notifications/modals/shared/components/NotificationChannels/NotificationChannelsPicker/NotificationChannelsPicker.tsx
  src/metabase/channel/email/data_editing_row_create.hbs
  src/metabase/channel/email/data_editing_row_delete.hbs
  src/metabase/channel/email/data_editing_row_update.hbs
  src/metabase/channel/email/new_user_invite.hbs
  src/metabase/channel/email/notification_card_new_confirmation.hbs
  src/metabase/channel/impl/email.clj
  src/metabase/channel/impl/http.clj
  src/metabase/channel/impl/slack.clj
  src/metabase/events.clj
  src/metabase/events/notification.clj
  src/metabase/events/schema.clj
  src/metabase/notification/models.clj
  src/metabase/notification/payload/core.clj
  src/metabase/notification/payload/impl/system_event.clj
  src/metabase/notification/seed.clj
  test/metabase/events/notification_test.clj
  test/metabase/notification/api/notification_test.clj
  test/metabase/notification/payload/core_test.clj
  test/metabase/notification/payload/impl/system_event_test.clj
  test/metabase/notification/send_test.clj
  test/metabase/notification/test_util.clj
  test_resources/notification/channel_template/hello_world.hbs
Labels: .Team/Workflows

#56216 🤖 backported "fix(sdk): Add `questionProps` to dashboard components"
  docs/embedding/sdk/dashboards.md
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveAdHocQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionDefaultView/InteractiveQuestionDefaultView.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/EditableDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.tsx
Labels: was-backported

#56212 🤖 backported "Multi line help text"
  e2e/support/helpers/e2e-custom-column-helpers.ts
  e2e/test/scenarios/custom-column/custom-column-reproductions.cy.spec.js
  frontend/src/metabase-lib/v1/expressions/position.ts
  frontend/src/metabase-lib/v1/expressions/position.unit.spec.ts
Labels: was-backported

#56131 Enable PDF and card result downloads individually in static and public embedding
  e2e/test/scenarios/sharing/public-resource-downloads.cy.spec.ts
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.tsx
  enterprise/frontend/src/metabase-enterprise/resource_downloads/resource_downloads_plugin.ts
  enterprise/frontend/src/metabase-enterprise/resource_downloads/tests/common.unit.spec.ts
  enterprise/frontend/src/metabase-enterprise/resource_downloads/tests/enterprise.unit.spec.ts
  enterprise/frontend/src/metabase-enterprise/resource_downloads/tests/premium.unit.spec.ts
  enterprise/frontend/src/metabase-enterprise/resource_downloads/tests/setup.ts
  frontend/src/metabase/dashboard/constants.ts
  frontend/src/metabase/dashboard/types/embed-display-options.ts
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.tsx
  frontend/src/metabase/public/constants.ts
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboard.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardView-filters.stories.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardView.stories.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardView.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestionView.tsx
  frontend/src/metabase/public/lib/types.ts
Labels: no-backport, .Team/Embedding

#56215 🤖 backported "fix(sdk): Add `questionProps` to dashboard components"
  .loki/reference/chrome_laptop_viz_EChartsTooltip_Default.png
  .loki/reference/chrome_laptop_viz_EChartsTooltip_Light_Theme.png
  docs/embedding/sdk/dashboards.md
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveAdHocQuestion.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionDefaultView/InteractiveQuestionDefaultView.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/EditableDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/InteractiveDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.tsx
Labels: was-backported

#56274 ci(sdk): mark 54 as a stable release version
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: no-backport, .Team/Embedding

#56273 ci(sdk): set the nightly version in master to 55
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: no-backport, .Team/Embedding

#55669 fix(sdk): wrong default cell background color on SDK
  frontend/src/metabase/embedding-sdk/theme/default-component-theme.ts
Labels: backport, .Team/Embedding

#56275 🤖 backported "fix(sdk): wrong default cell background color on SDK"
  frontend/src/metabase/embedding-sdk/theme/default-component-theme.ts
Labels: was-backported

#55257 🤖 backported "Fix object detail view ignores link formatting"
  e2e/test/scenarios/visualizations-tabular/object_detail.cy.spec.js
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailBody.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/ObjectDetailsTable.tsx
  frontend/src/metabase/visualizations/components/ObjectDetail/types.ts
  frontend/src/metabase/visualizations/visualizations/ObjectDetail.jsx
Labels: was-backported

#56220 🤖 backported "Fix - When DB is stuck in a Sync Loop, DB List in Native Editor Blinks Constantly "
  e2e/test/scenarios/native/native-reproductions.cy.spec.ts
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.module.css
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.unit.spec.js
  frontend/src/metabase/query_builder/components/DataSelector/data-search/SearchResults.jsx
  frontend/src/metabase/query_builder/components/DataSelector/data-search/SearchResults.module.css
  frontend/src/metabase/query_builder/components/DataSelector/data-search/index.js
  frontend/src/metabase/query_builder/components/DataSelector/data-search/utils.js
Labels: was-backported
