Repository metabase/metabase, pull requests merged in 2025-07, with the labels that each got.

#60259 Fix failed host apps tests
  .github/file-paths.yaml
  e2e/test-host-app/shared/compatibility.cy.spec.js
Labels: no-backport, .Team/Embedding

#60049 Render `New Question` button and the query builder
  .github/workflows/e2e-component-tests-embedding-sdk.yml
  .github/workflows/e2e-embedding-sdk-compatibility-tests.yml
  .github/workflows/e2e-test.yml
  .storybook-sdk/main.js
  .storybook/main.ts
  e2e/runner/run_cypress_local.ts
  e2e/test-component/scenarios/embedding-sdk/editable-dashboard.cy.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/public/dashboard/EditableDashboard/EditableDashboard.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/public/dashboard/SdkDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/dashboard/tests/setup.tsx
  enterprise/frontend/src/embedding-sdk/jest/setup-env.js
  enterprise/frontend/src/embedding-sdk/test/__support__/ui.tsx
  frontend/src/metabase/dashboard/components/AddCardSidebar/AddCardSidebar.unit.spec.tsx
  frontend/src/metabase/dashboard/components/QuestionPicker/QuestionPicker.tsx
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.tsx
  frontend/src/metabase/dashboard/context/context.tsx
  frontend/src/metabase/env.ts
  frontend/src/metabase/querying/notebook/components/DataStep/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/querying/notebook/components/DataStep/tests/setup.tsx
  frontend/src/metabase/querying/notebook/components/NotebookDataPicker/EmbeddingDataPicker/tests/setup.tsx
  frontend/src/metabase/selectors/embed.ts
  frontend/src/metabase/ui/components/theme/ThemeProvider/ThemeProvider.tsx
  frontend/src/metabase/ui/components/theme/ThemeProvider/context.ts
  frontend/test/__support__/server-mocks/search.ts
  frontend/test/__support__/storybook.tsx
  frontend/test/__support__/ui.tsx
  webpack.embedding-sdk.config.js
Labels: .Team/Embedding

#60044 Prg-26-add-upsells-for-dev-instances-in-admin-settings
  enterprise/frontend/src/metabase-enterprise/embedding/components/InteractiveEmbeddingSettings.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/EmbeddingSdkSettings.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/StaticEmbeddingSettings.tsx
  frontend/src/metabase/admin/settings/components/GeneralSettings/DevInstanceBanner.tsx
  frontend/src/metabase/admin/settings/components/GeneralSettings/DevInstanceBanner.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/SettingsPages/EmbeddingSettingsPage.tsx
  frontend/src/metabase/admin/settings/components/SettingsPages/GeneralSettingsPage.tsx
  frontend/src/metabase/admin/upsells/UpsellDevInstances.tsx
  frontend/src/metabase/admin/upsells/index.ts
  frontend/src/metabase/selectors/settings.ts
Labels: no-backport, .Team/ProductGrowth

#60317 🤖 backported "document the backward-compatibility-tests"
  .github/workflows/e2e-cross-version-for-breaking-changes.yml
  .github/workflows/embedding-sdk.yml
  bin/backward-compatibility-test.js
Labels: was-backported

#60316 🤖 backported "document the backward-compatibility-tests"
  .github/workflows/e2e-cross-version-for-breaking-changes.yml
  .github/workflows/embedding-sdk.yml
  bin/backward-compatibility-test.js
Labels: was-backported

#60095 [Metabot] Thinking + error style iteration
  e2e/test/scenarios/metabot/metabot.cy.spec.ts
  enterprise/frontend/src/embedding-sdk/components/public/MetabotQuestion/MetabotQuestion.tsx
  enterprise/frontend/src/metabase-enterprise/api/ai-streaming/requests.unit.spec.ts
  enterprise/frontend/src/metabase-enterprise/api/ai-streaming/test-utils.ts
  enterprise/frontend/src/metabase-enterprise/metabot/components/MetabotChat/MetabotChat.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/components/MetabotChat/MetabotChatMessage.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/components/MetabotChat/MetabotThinking.module.css
  enterprise/frontend/src/metabase-enterprise/metabot/components/MetabotChat/MetabotThinking.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/components/MetabotChat/utils.ts
  enterprise/frontend/src/metabase-enterprise/metabot/constants.ts
  enterprise/frontend/src/metabase-enterprise/metabot/hooks.ts
  enterprise/frontend/src/metabase-enterprise/metabot/metabot-streaming.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/metabot.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/errors.ts
  enterprise/frontend/src/metabase-enterprise/metabot/reactions/messages.ts
  enterprise/frontend/src/metabase-enterprise/metabot/state/actions.ts
  enterprise/frontend/src/metabase-enterprise/metabot/state/reducer.ts
  enterprise/frontend/src/metabase-enterprise/metabot/state/selectors.ts
  enterprise/frontend/src/metabase-enterprise/metabot/state/selectors.unit.spec.ts
Labels: backport, .Team/Metabot

#60334 Flake Chore: `blocking-queue-concurrency-test`
  test/metabase/notification/send_test.clj
Labels: no-backport, .Team/Querying

#60226 [Metabot] Better text streaming
  e2e/test/scenarios/metabot/metabot.cy.spec.ts
  enterprise/frontend/src/metabase-enterprise/api/ai-streaming/process-stream.ts
  enterprise/frontend/src/metabase-enterprise/metabot/components/AIMarkdown/AIMarkdown.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/components/MetabotChat/MetabotChat.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/components/MetabotChat/MetabotChatMessage.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/components/MetabotChat/MetabotThinking.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/components/MetabotChat/hooks.ts
  enterprise/frontend/src/metabase-enterprise/metabot/metabot-streaming.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/metabot.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/state/actions.ts
  enterprise/frontend/src/metabase-enterprise/metabot/state/reducer.ts
Labels: backport, .Team/Metabot

#60353 🤖 backported "docs - update sync scans"
  docs/databases/sync-scan.md
Labels: was-backported

#60352 🤖 backported "db routing copy edit"
  docs/permissions/database-routing.md
  enterprise/frontend/src/metabase-enterprise/database_routing/index.tsx
Labels: was-backported

#60357 🤖 backported "[Metabot] Make streaming the default"
  e2e/support/helpers/e2e-metabot-helpers.ts
  e2e/test/scenarios/metabot/metabot.cy.spec.ts
  enterprise/frontend/src/metabase-enterprise/metabot/components/MetabotChat/MetabotChat.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/state/reducer.ts
Labels: was-backported

#60294 🤖 backported "docs - update links"
  docs/README.md
  docs/cloud/cloud-vs-self-hosting.md
  docs/cloud/custom-domain.md
  docs/cloud/google-sheets.md
  docs/cloud/how-billing-works.md
  docs/cloud/limitations.md
  docs/cloud/migrate/cloud-to-self-hosted.md
  docs/cloud/migrate/guide.md
  docs/cloud/storage.md
  docs/configuring-metabase/settings.md
  docs/databases/connections/mongodb.md
  docs/databases/users-roles-privileges.md
  docs/embedding/interactive-embedding.md
  docs/embedding/introduction.md
  docs/embedding/sdk/quickstart-with-sample-app.md
  docs/embedding/sdk/quickstart.md
  docs/installation-and-operation/activating-the-enterprise-edition.md
  docs/installation-and-operation/migrating-from-h2.md
  docs/installation-and-operation/serialization.md
  docs/people-and-groups/authenticating-with-jwt.md
  docs/people-and-groups/authenticating-with-saml.md
  docs/people-and-groups/google-sign-in.md
  docs/people-and-groups/managing.md
  docs/people-and-groups/saml-google.md
  docs/people-and-groups/saml-keycloak.md
  docs/permissions/data-sandbox-examples.md
  docs/permissions/data-sandboxes.md
  docs/permissions/embedding.md
  docs/troubleshooting-guide/db-connection.md
  docs/troubleshooting-guide/models.md
Labels: was-backported

#60356 Delete deprecated and unused `FormCheckbox`
  frontend/src/metabase/common/components/FormCheckBox/FormCheckBox.stories.tsx
  frontend/src/metabase/common/components/FormCheckBox/FormCheckBox.tsx
  frontend/src/metabase/common/components/FormCheckBox/FormCheckBox.unit.spec.tsx
  frontend/src/metabase/common/components/FormCheckBox/index.ts
Labels: no-backport, .Team/ProductGrowth

#60370 🤖 backported "wipe remains of java 11"
  docs/developers-guide/build.md
Labels: was-backported

#60162 Filters in dashboards M2 backend
  src/metabase/channel/impl/email.clj
  src/metabase/channel/impl/slack.clj
  src/metabase/channel/impl/util.clj
  src/metabase/channel/render/card.clj
  src/metabase/channel/render/util.clj
  src/metabase/notification/payload/execute.clj
  test/metabase/pulse/dashboard_subscription_test.clj
  test/metabase/pulse/send_test.clj
Labels: .Team/DashViz

#60340 🤖 backported "Render ComparisonPicker for SDK without a portal"
  e2e/test-component/scenarios/embedding-sdk/popover.cy.spec.tsx
  frontend/src/metabase/css/core/layout.module.css
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SettingsComponents/ComparisonPicker.tsx
Labels: was-backported

#60376 ask search bots to not index openapi docs
  resources/openapi/index.html
Labels: backport, .Team/Workflows

#60363 Remove deprecated and unused `WithPublicDashboardEndpoints`
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardPage/PublicOrEmbeddedDashboardPage.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/WithPublicDashboardEndpoints.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/use-public-dashboard-endpoints.tsx
Labels: no-backport, :broom:, .Team/ProductGrowth

#60331 Fix "undo" when removing a heading dashcard with filters
  e2e/test/scenarios/dashboard-filters/parameters.cy.spec.js
  frontend/src/metabase/dashboard/actions/cards-typed.ts
  frontend/src/metabase/dashboard/components/DashboardGrid.tsx
  frontend/src/metabase/dashboard/selectors.ts
Labels: no-backport, .Team/DashViz

#60355 Remove unused `ConfirmContent`
  frontend/src/metabase/common/components/ConfirmContent/ConfirmContent.tsx
  frontend/src/metabase/common/components/ConfirmContent/index.tsx
Labels: no-backport, .Team/ProductGrowth

#60197 Closes VIZ-1235 update top nav filter appearance
  e2e/support/helpers/e2e-dashboard-helpers.ts
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  e2e/test/scenarios/dashboard-cards/dashboard-drill.cy.spec.js
  e2e/test/scenarios/dashboard-filters/dashboard-filters-remapping.cy.spec.ts
  e2e/test/scenarios/dashboard-filters/dashboard-filters-reset-clear.cy.spec.ts
  e2e/test/scenarios/dashboard-filters/dashboard-filters-text-category.cy.spec.js
  e2e/test/scenarios/dashboard-filters/parameters.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/dashboard/title-drill.cy.spec.js
  e2e/test/scenarios/filters-reproductions/dashboard-filters-reproductions.cy.spec.js
  frontend/src/metabase/dashboard/components/DashboardParameterList/DashboardParameterList.tsx
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.tsx
Labels: backport, .Team/DashViz

#60384 🤖 backported "Followup on VIZ-1221 (added translation)"
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
Labels: was-backported

#60387 🤖 backported "Closes VIZ-1216 bubble size well style "
  frontend/src/metabase/visualizer/components/VisualizationCanvas/ScatterFloatingWell/ScatterFloatingWell.tsx
  frontend/src/metabase/visualizer/components/VisualizationCanvas/VisualizationCanvas.module.css
  frontend/src/metabase/visualizer/components/VisualizationCanvas/VisualizationCanvas.tsx
Labels: was-backported

#59206 `datetime()` custom expression function
  e2e/test/scenarios/custom-column/cc-cast-functions.cy.spec.ts
  frontend/src/metabase-lib/v1/expressions/config.ts
  modules/drivers/athena/src/metabase/driver/athena.clj
  modules/drivers/clickhouse/src/metabase/driver/clickhouse_qp.clj
  modules/drivers/databricks/src/metabase/driver/databricks.clj
  modules/drivers/hive-like/src/metabase/driver/hive_like.clj
  modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj
  modules/drivers/oracle/src/metabase/driver/oracle.clj
  modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/sqlite/src/metabase/driver/sqlite.clj
  modules/drivers/starburst/src/metabase/driver/starburst.clj
  modules/drivers/vertica/src/metabase/driver/vertica.clj
  src/metabase/driver/h2.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql/query_processor.clj
  src/metabase/legacy_mbql/normalize.cljc
  src/metabase/legacy_mbql/schema.cljc
  src/metabase/lib/schema/expression/temporal.cljc
  src/metabase/types/core.cljc
  test/metabase/query_processor_test/alternative_date_test.clj
  test/metabase/query_processor_test/cast_test.clj
  test/metabase/types/core_test.cljc
Labels: no-backport, .Team/Querying

#60394 🤖 backported "docs - fix typo"
  docs/installation-and-operation/serialization.md
Labels: was-backported

#60401 Use id not slug in saved action param configuration
  enterprise/backend/src/metabase_enterprise/data_editing/configure.clj
  enterprise/backend/test/metabase_enterprise/data_editing/action_v2_api_test.clj
Labels: .Team/Workflows

#60367 Add QP integration tests for custom expressions in join conditions
  test/metabase/query_processor_test/explicit_joins_test.clj
Labels: no-backport, .Team/Querying

#59859 Removing FK->PK remapping hack
  frontend/src/metabase-lib/v1/metadata/Field.ts
  frontend/src/metabase-lib/v1/metadata/Field.unit.spec.ts
  frontend/src/metabase/parameters/utils/dashboards.ts
  resources/migrations/001_update_migrations.yaml
  src/metabase/parameters/params.clj
  test/metabase/dashboards/api_test.clj
Labels: no-backport, .Team/Querying

#60396 🧹 move AddToDashSelectDashModal
  frontend/src/metabase/query_builder/components/AddToDashSelectDashModal/AddToDashSelectDashModal.tsx
  frontend/src/metabase/query_builder/components/AddToDashSelectDashModal/AddToDashSelectDashModal.unit.spec.tsx
  frontend/src/metabase/query_builder/components/AddToDashSelectDashModal/hooks.ts
  frontend/src/metabase/query_builder/components/AddToDashSelectDashModal/index.ts
  frontend/src/metabase/query_builder/components/AddToDashSelectDashModal/utils.ts
  frontend/src/metabase/query_builder/components/QueryModals/QueryModals.tsx
Labels: Type:Tech Debt, backport, .Team/AdminWebapp

#60406 🤖 backported "Update SDK changelog"
  docs/embedding/sdk/introduction.md
Labels: was-backported

#60405 Add missing step to set JWT SSO URI
  docs/embedding/sdk/authentication.md
Labels: backport

#60413 Update SDK changelog
  docs/embedding/sdk/introduction.md
Labels: no-backport

#60391 Ensure clause is always compiled to honeysql in driver.sql.query-processor/correct-null-behaviour
  src/metabase/driver/sql/query_processor.clj
  test/metabase/query_processor_test/explicit_joins_test.clj
  test/metabase/query_processor_test/filter_test.clj
Labels: no-backport, .Team/Querying

#60224 Add Kondo warning about committing `t2/debug`
  .clj-kondo/config.edn
  test/metabase/permissions/models/data_permissions/sql_test.clj
Labels: no-backport, .Team/DevEx

#60223 fix trend native formatting
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.jsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/compute.js
  frontend/src/metabase/visualizations/visualizations/SmartScalar/compute.unit.spec.js
Labels: backport, .Team/DashViz

#60411 make dashcard menu button always visible
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Card_Visualizations_Dark_Theme.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Card_Visualizations_Light_Theme.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Dark_Theme_Default.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Dark_Theme_No_Background_Default.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Dark_Theme_No_Background_Scroll.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Dark_Theme_Scroll.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Light_Theme_Default.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Light_Theme_No_Background_Default.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Light_Theme_No_Background_Scroll.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Light_Theme_Scroll.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Transparent_Theme_Default.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Transparent_Theme_No_Background_Default.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Transparent_Theme_No_Background_Scroll.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Transparent_Theme_Scroll.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_All_Options.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Month_Year.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Quarter_Year.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Quarter_Year_Dropdown.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Range.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Relative.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Single.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Number.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_List.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_List_Single_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_List_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_Search.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_Search_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Text.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Text_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Unit_Of_Time.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_All_Options.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Month_Year.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Quarter_Year.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Quarter_Year_Dropdown.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Range.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Relative.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Single.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Number.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_List.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_List_Single_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_List_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_Search.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_Search_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Text.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Text_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Unit_Of_Time.png
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.styled.tsx
  frontend/src/metabase/visualizations/components/legend/LegendLabel.module.css
Labels: .Team/DashViz

#59894 set a bin range to between filter in dashboard click behavior
  frontend/src/metabase-lib/v1/parameters/utils/click-behavior.ts
  frontend/src/metabase-lib/v1/parameters/utils/click-behavior.unit.spec.ts
Labels: backport, .Team/DashViz

#60419 🤖 backported "fix trend native formatting"
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.jsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/compute.js
  frontend/src/metabase/visualizations/visualizations/SmartScalar/compute.unit.spec.js
Labels: was-backported

#60421 🤖 backported "Fix permission check for notifications - allow slack"
  e2e/test/scenarios/sharing/alert/alert.cy.spec.js
  frontend/src/metabase/lib/pulse.ts
  frontend/src/metabase/notifications/modals/ChannelSetupModal.tsx
  frontend/src/metabase/notifications/modals/CreateOrEditQuestionAlertModal/CreateOrEditQuestionAlertModal.tsx
  frontend/src/metabase/notifications/pulse/actions.js
Labels: was-backported

#60422 🤖 backported "set a bin range to between filter in dashboard click behavior"
  frontend/src/metabase-lib/v1/parameters/utils/click-behavior.ts
  frontend/src/metabase-lib/v1/parameters/utils/click-behavior.unit.spec.ts
Labels: was-backported

#60341 Split file at \r and \r\n too in Ace editor
  frontend/src/metabase/query_builder/components/NativeQueryEditor/AceEditor/AceEditor.tsx
Labels: .Team/Querying

#60379 SEM-420 Organize e2e tests
  e2e/test/scenarios/admin/datamodel/datamodel.cy.spec.ts
  e2e/test/scenarios/admin/datamodel/segments.cy.spec.ts
Labels: no-backport, .Team/SemanticLayer

#59683 Reduce memory pressure during BigQuery sync
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj
  src/metabase/sync/sync_metadata/fields.clj
Labels: backport, .Team/SemanticLayer

#60388 SEM-420 Organize e2e tests (part 2)
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/admin/datamodel/datamodel.cy.spec.ts
  e2e/test/scenarios/admin/datamodel/editor.cy.spec.ts
Labels: no-backport, .Team/SemanticLayer

#60399 🧹move archiveCollectionModal
  frontend/src/metabase/collections/components/ArchiveCollectionModal/ArchiveCollectionModal.jsx
  frontend/src/metabase/collections/components/ArchiveCollectionModal/index.jsx
  frontend/src/metabase/common/components/ArchiveCollectionModal/index.jsx
  frontend/src/metabase/routes.jsx
Labels: backport, .Team/AdminWebapp

#60443 🤖 backported "🧹move archiveCollectionModal"
  frontend/src/metabase/collections/components/ArchiveCollectionModal/ArchiveCollectionModal.jsx
  frontend/src/metabase/collections/components/ArchiveCollectionModal/index.jsx
  frontend/src/metabase/common/components/ArchiveCollectionModal/index.jsx
  frontend/src/metabase/routes.jsx
Labels: was-backported

#60446 Swap over to mysql's images for 8.0
  .github/workflows/drivers.yml
Labels: no-backport

#60462 🤖 backported "Don't use hyphens in token features 😁"
  e2e/test-component/scenarios/embedding-sdk/interactive-dashboard.cy.spec.tsx
  e2e/test-component/scenarios/embedding-sdk/interactive-question.cy.spec.tsx
  e2e/test/scenarios/question/saved.cy.spec.js
  e2e/test/scenarios/visualizations-charts/bar_chart.cy.spec.js
  e2e/test/scenarios/visualizations-charts/pie_chart.cy.spec.js
  e2e/test/scenarios/visualizations-charts/sankey.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/drillthroughs/table_drills.cy.spec.js
  enterprise/backend/test/metabase_enterprise/api/session_test.clj
  enterprise/frontend/src/embedding-sdk/components/private/SdkUsageProblem/SdkUsageProblemDisplay.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/hooks/private/use-sdk-usage-problem.ts
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/static-viz/containers/LegacyStaticChart/LegacyStaticChart.tsx
  frontend/src/metabase/static-viz/index.js
  frontend/src/metabase/visualizations/components/Visualization/Visualization.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.unit.spec.js
  frontend/src/metabase/visualizations/visualizations/BarChart/BarChart.stories.tsx
  frontend/src/metabase/visualizations/visualizations/Funnel/Funnel.stories.tsx
  frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.stories.tsx
  frontend/src/metabase/visualizations/visualizations/Table/Table.stories.tsx
  src/metabase/premium_features/settings.clj
Labels: was-backported

#60157 Refactor Browse Databases
  frontend/src/metabase/browse/components/BrowseCard.module.css
  frontend/src/metabase/browse/components/BrowseCard.tsx
  frontend/src/metabase/browse/components/BrowseGrid.tsx
  frontend/src/metabase/browse/databases/BrowseDatabases.tsx
  frontend/src/metabase/browse/schemas/BrowseSchemas.styled.tsx
  frontend/src/metabase/browse/schemas/BrowseSchemas.tsx
  frontend/src/metabase/browse/tables/TableBrowser/TableBrowser.jsx
  frontend/src/metabase/browse/tables/TableBrowser/TableBrowser.styled.tsx
  frontend/src/metabase/browse/tables/TableBrowser/TableBrowser.unit.spec.js
  frontend/src/metabase/collections/components/PinnedQuestionCard/PinnedQuestionCard.tsx
Labels: no-backport, .Team/AdminWebapp

#60402 🧹 Remove ButtonWithStatus
  e2e/test/scenarios/admin/datamodel/datamodel.cy.spec.js
  frontend/src/metabase/admin/datamodel/metadata/components/FieldRemappingSettings/FieldRemappingSettings.jsx
  frontend/src/metabase/common/components/ButtonWithStatus/ButtonWithStatus.jsx
  frontend/src/metabase/common/components/ButtonWithStatus/index.jsx
  frontend/src/metabase/notifications/modals/CreateOrEditQuestionAlertModal/CreateOrEditQuestionAlertModal.tsx
Labels: Type:Tech Debt, no-backport, .Team/AdminWebapp

#60409 Fix a couple flaky tests
  test/metabase/notification/send_test.clj
  test/metabase/premium_features/token_check_test.clj
Labels: backport, .Team/AdminWebapp

#60469 mark parameter test flaky
  e2e/test/scenarios/dashboard-filters/parameters.cy.spec.js
Labels: .CI & Tests, no-backport, .Team/AdminWebapp

#60468 🤖 backported "Fix a couple flaky tests"
  test/metabase/notification/send_test.clj
  test/metabase/premium_features/token_check_test.clj
Labels: was-backported

#60473 Add repro test for #12679
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
Labels: no-backport, .Team/Querying

#60375 Cloud >override naming
  e2e/test/scenarios/admin-2/settings.cy.spec.js
  frontend/src/metabase-types/api/email.ts
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/settings/components/Email/CloudSMTPConnectionCard.tsx
  frontend/src/metabase/admin/settings/components/Email/CloudSMTPConnectionCard.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/Email/SMTPConnectionCard.tsx
  frontend/src/metabase/admin/settings/components/Email/SMTPConnectionCard.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/Email/SMTPOverrideConnectionForm.tsx
  frontend/src/metabase/admin/settings/components/Email/SMTPOverrideConnectionForm.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmailFromAddressWidget.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmailFromAddressWidget.unit.spec.tsx
  frontend/src/metabase/api/email.ts
  frontend/test/__support__/server-mocks/email.ts
  src/metabase/channel/api/email.clj
  src/metabase/channel/email.clj
  src/metabase/channel/settings.clj
  test/metabase/channel/api/email_test.clj
  test/metabase/channel/email_test.clj
  test/metabase/channel/settings_test.clj
Labels: .Team/AdminWebapp

#60457 Fix join condition compilation on mongo when rhs is a literal value
  modules/drivers/mongo/src/metabase/driver/mongo/query_processor.clj
  modules/drivers/mongo/test/metabase/driver/mongo/query_processor_test.clj
  test/metabase/query_processor_test/explicit_joins_test.clj
Labels: no-backport, .Team/Querying

#60438 Closes VIZ-1206 some settings are not preserved when changing to funnel
  frontend/src/metabase/visualizer/utils/get-updated-settings-for-display.ts
  frontend/src/metabase/visualizer/utils/get-updated-settings-for-display.unit.spec.ts
Labels: backport, .Team/DashViz

#60385 Closes VIZ-1209 browser stalls when too many series in visualizer
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
Labels: backport, .Team/DashViz

#60480 🤖 backported "Closes VIZ-1209 browser stalls when too many series in visualizer"
  frontend/src/metabase/visualizations/echarts/cartesian/model/index.ts
Labels: was-backported

#60431 fix(sdk): fix popovers can't be rendered inside modals
  enterprise/frontend/src/embedding-sdk/components/private/SdkPortalContainer.tsx
  enterprise/frontend/src/embedding-sdk/components/private/SdkUsageProblem/index.tsx
  enterprise/frontend/src/embedding-sdk/components/public/MetabaseProvider.tsx
  frontend/src/metabase/embedding-sdk/config.ts
  frontend/src/metabase/embedding-sdk/theme/default-component-theme.ts
Labels: backport, .Team/Embedding

#60377 🤖 backported "Improve Sample apps health check logic"
  e2e/runner/sample-apps-shared/constants/sample-app-setup-configs.js
  e2e/runner/sample-apps-shared/helpers/start-containers.ts
  e2e/runner/start-sample-app-containers/startSampleAppContainers.ts
Labels: was-backported

#60453 Unskip repro 40635
  e2e/test/scenarios/models/reproductions.cy.spec.ts
Labels: no-backport, .Team/Querying

#60495 chore(sdk): skip flaky test
  e2e/test-component/scenarios/embedding-sdk/styles-tests.cy.spec.tsx
Labels: backport, .Team/Embedding

#60494 Fix flaky dashcard filter test
  e2e/test/scenarios/dashboard-filters/parameters.cy.spec.js
Labels: no-backport, .Team/DashViz

#60458 [malli] Don't instrument multimethods when instrumentation is disabled
  src/metabase/util/malli.cljc
  src/metabase/util/malli/defn.clj
  test/metabase/util/malli/defn_test.clj
Labels: backport

#60509 🤖 backported "[malli] Don't instrument multimethods when instrumentation is disabled"
  src/metabase/util/malli.cljc
  src/metabase/util/malli/defn.clj
  test/metabase/util/malli/defn_test.clj
Labels: was-backported

#60461 perf: Optimize remove-empty-clauses
  src/metabase/legacy_mbql/normalize.cljc
Labels: backport

#60425 adjust inline filters popover position
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/dashboard/components/DashboardParameterList/DashboardParameterList.tsx
  frontend/src/metabase/parameters/components/ParameterWidget/ParameterWidget.tsx
  frontend/src/metabase/parameters/components/ParametersList/ParametersList.tsx
  frontend/src/metabase/parameters/components/ParametersList/types.ts
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.tsx
Labels: no-backport

#60227 Query processor supports native custom filters
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk/query_processor.clj
  modules/drivers/sparksql/test/metabase/test/data/sparksql.clj
  src/metabase/driver.clj
  src/metabase/driver/common/parameters.clj
  src/metabase/driver/common/parameters/values.clj
  src/metabase/driver/sql.clj
  src/metabase/driver/sql/parameters/substitute.clj
  src/metabase/driver/sql/parameters/substitution.clj
  src/metabase/driver/sql/query_processor.clj
  src/metabase/driver_api/core.clj
  src/metabase/legacy_mbql/normalize.cljc
  src/metabase/legacy_mbql/schema.cljc
  src/metabase/lib/schema/template_tag.cljc
  src/metabase/types/core.cljc
  test/metabase/query_processor_test/parameters_test.clj
  test/metabase/query_processor_test/uuid_test.clj
  test/metabase/test/data/sql.clj
Labels: no-backport, .Team/Querying

#60502 Lib can recognize and validate mb.filter tags
  src/metabase/lib/native.cljc
  test/metabase/lib/native_test.cljc
Labels: no-backport, .Team/Querying

#60515 Add repro test for #33972
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
Labels: no-backport, .Team/Querying

#59421 [cljs] Introduce match-lite to reduce CLJS bundle size
  .clj-kondo/config.edn
  .cljfmt.edn
  src/metabase/legacy_mbql/util.cljc
  src/metabase/lib/expression.cljc
  src/metabase/lib/fe_util.cljc
  src/metabase/lib/filter.cljc
  src/metabase/lib/filter/update.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/remove_replace.cljc
  src/metabase/lib/schema.cljc
  src/metabase/lib/stage.cljc
  src/metabase/lib/util.cljc
  src/metabase/lib/util/match.clj
  src/metabase/lib/util/match/impl.cljc
  test/metabase/lib/util/match_test.cljc
Labels: backport

#60512 🤖 backported "perf: Optimize remove-empty-clauses"
  src/metabase/legacy_mbql/normalize.cljc
Labels: was-backported

#60533 🤖 backported "Fix inconsistent header button styles"
  frontend/src/metabase/query_builder/components/view/ViewHeader/ViewTitleHeader.module.css
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/FilterHeaderButton.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionNotebookButton/QuestionNotebookButton.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/ToggleNativeQueryPreview/ToggleNativeQueryPreview.tsx
Labels: was-backported

#60349 fix(sdk): make isEmbeddingSdk consistent on new iframe embed using singletons
  enterprise/frontend/src/embedding-sdk/index.ts
  enterprise/frontend/src/embedding-sdk/store/index.ts
  enterprise/frontend/src/embedding-sdk/test/environment.unit.spec.ts
  enterprise/frontend/src/embedding-sdk/test/server-mocks/sdk-init.ts
  frontend/src/metabase-types/store/embed.ts
  frontend/src/metabase-types/store/mocks/embed.ts
  frontend/src/metabase/app-embed-sdk.tsx
  frontend/src/metabase/collections/components/CollectionContent/CollectionItemsTable.tsx
  frontend/src/metabase/common/components/ExportSettingsWidget/ExportSettingsWidget.tsx
  frontend/src/metabase/common/components/ItemsTable/Columns.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.tsx
  frontend/src/metabase/dashboard/components/DashboardParameterPanel/DashboardParameterPanel.tsx
  frontend/src/metabase/dashboard/components/QuestionPicker/QuestionList.tsx
  frontend/src/metabase/dashboard/components/QuestionPicker/QuestionPicker.tsx
  frontend/src/metabase/dashboard/selectors.ts
  frontend/src/metabase/embedding-sdk/config.ts
  frontend/src/metabase/embedding-sdk/mocks/config-mock.ts
  frontend/src/metabase/env.ts
  frontend/src/metabase/lib/formatting/url.tsx
  frontend/src/metabase/lib/formatting/value.tsx
  frontend/src/metabase/lib/i18n.js
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.tsx
  frontend/src/metabase/public/components/EmbedFrame/useGlobalTheme.tsx
  frontend/src/metabase/querying/notebook/components/DataStep/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/querying/notebook/components/DataStep/tests/setup.tsx
  frontend/src/metabase/selectors/embed.ts
  frontend/src/metabase/selectors/web-app.ts
  frontend/src/metabase/ui/components/theme/ThemeProvider/ThemeProvider.tsx
  frontend/src/metabase/visualizations/components/ChoroplethMap.jsx
  frontend/src/metabase/visualizations/components/ChoroplethMap.unit.spec.js
  frontend/src/metabase/visualizations/components/Visualization/Visualization.tsx
  frontend/src/metabase/visualizations/components/legend/LegendLabel.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingColorPicker/ChartSettingColorPicker.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingMultiSelect.tsx
  frontend/src/metabase/visualizations/echarts/tooltip/index.tsx
  frontend/src/metabase/visualizations/lib/action.js
  frontend/src/metabase/visualizations/lib/image-exports.ts
  frontend/src/metabase/visualizations/lib/save-chart-image.ts
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SettingsComponents/ComparisonPicker.tsx
Labels: backport, .Team/Embedding

#60378 🤖 backported "ask search bots to not index openapi docs"
  resources/openapi/index.html
Labels: was-backported

#60490 Closes VIZ-967 Click behavior on prefixed columns no longer overflows on next line
  frontend/src/metabase/lib/formatting/value.tsx
Labels: backport, .Team/DashViz

#60338 Closes VIZ-1208: smarter detection of selected columns
  frontend/src/metabase/visualizer/utils/get-initial-state-for-card-data-source.ts
  frontend/src/metabase/visualizer/utils/get-initial-state-for-card-data-source.unit.spec.ts
  frontend/src/metabase/visualizer/visualizations/cartesian.ts
  frontend/src/metabase/visualizer/visualizations/cartesian.unit.spec.ts
Labels: backport, .Team/DashViz

#60540 🤖 backported "Closes VIZ-1208: smarter detection of selected columns"
  frontend/src/metabase/visualizer/utils/get-initial-state-for-card-data-source.ts
  frontend/src/metabase/visualizer/utils/get-initial-state-for-card-data-source.unit.spec.ts
  frontend/src/metabase/visualizer/visualizations/cartesian.ts
  frontend/src/metabase/visualizer/visualizations/cartesian.unit.spec.ts
Labels: was-backported

#60541 🤖 backported "fix(sdk): keep full url with subpath for `/auth/sso` http call"
  enterprise/frontend/src/embedding-sdk/test/auth-flow/jwt.unit.spec.tsx
  enterprise/frontend/src/embedding/auth-common/connect-to-instance-auth-sso.ts
Labels: was-backported

#60542 🤖 backported "Fix PortalContainer to respect SDK styles"
  enterprise/frontend/src/embedding-sdk/components/private/SdkPortalContainer.tsx
Labels: was-backported

#60439 SEM-420 Test new features (e2e)
  e2e/support/helpers/e2e-datamodel-helpers.ts
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/test/scenarios/admin/datamodel/datamodel.cy.spec.ts
  frontend/src/metabase/api/dataset.ts
  frontend/src/metabase/metadata/components/NameDescriptionInput/NameDescriptionInput.tsx
  frontend/src/metabase/metadata/components/RemappingPicker/CustomMappingModal/CustomMappingModal.tsx
  frontend/src/metabase/metadata/components/RemappingPicker/CustomMappingModal/CustomMappingModal.unit.spec.tsx
  frontend/src/metabase/metadata/components/RemappingPicker/RemappingPicker.tsx
  frontend/src/metabase/metadata/components/SortableFieldItem/SortableFieldItem.tsx
  frontend/src/metabase/metadata/components/SortableFieldList/SortableFieldList.tsx
  frontend/src/metabase/metadata/pages/DataModel/DataModel.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/BehaviorSection.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/DataSection/DataSection.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/DataSection/LabeledValue.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/FieldSection.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/FieldValuesModal.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/PreviewSection/ObjectDetailPreview.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/PreviewSection/PreviewSection.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/PreviewSection/TablePreview.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/PreviewSection/utils.ts
  frontend/src/metabase/metadata/pages/DataModel/components/SyncOptionsModal.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/TablePicker/TablePicker.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/TablePicker/utils.ts
  frontend/src/metabase/metadata/pages/DataModel/components/TableSection/FieldList/FieldItem/FieldItem.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/TableSection/FieldList/FieldList.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/TableSection/TableSection.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/index.ts
  frontend/src/metabase/metadata/utils/field.ts
Labels: no-backport, .Team/SemanticLayer

#60491 SEM-419 Increase test coverage (unit tests)
  frontend/src/metabase/metadata/components/CurrencyPicker/CurrencyPicker.unit.spec.tsx
  frontend/src/metabase/metadata/components/FieldOrderPicker/FieldOrderPicker.unit.spec.tsx
  frontend/src/metabase/metadata/components/FkTargetPicker/FkTargetPicker.tsx
  frontend/src/metabase/metadata/components/FkTargetPicker/FkTargetPicker.unit.spec.tsx
  frontend/src/metabase/metadata/components/SemanticTypeAndTargetPicker/SemanticTypeAndTargetPicker.tsx
  frontend/src/metabase/metadata/components/SemanticTypeAndTargetPicker/SemanticTypeAndTargetPicker.unit.spec.tsx
  frontend/src/metabase/metadata/components/index.ts
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/BehaviorSection/BehaviorSection.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/BehaviorSection/RemappingPicker/CustomMappingModal/CustomMappingModal.module.css
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/BehaviorSection/RemappingPicker/CustomMappingModal/CustomMappingModal.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/BehaviorSection/RemappingPicker/CustomMappingModal/CustomMappingModal.unit.spec.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/BehaviorSection/RemappingPicker/CustomMappingModal/index.ts
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/BehaviorSection/RemappingPicker/CustomMappingModal/types.ts
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/BehaviorSection/RemappingPicker/CustomMappingModal/utils.ts
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/BehaviorSection/RemappingPicker/DisplayValuesPicker/DisplayValuesPicker.module.css
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/BehaviorSection/RemappingPicker/DisplayValuesPicker/DisplayValuesPicker.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/BehaviorSection/RemappingPicker/DisplayValuesPicker/DisplayValuesPicker.unit.spec.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/BehaviorSection/RemappingPicker/DisplayValuesPicker/index.ts
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/BehaviorSection/RemappingPicker/DisplayValuesPicker/types.ts
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/BehaviorSection/RemappingPicker/NamingTip.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/BehaviorSection/RemappingPicker/RemappingPicker.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/BehaviorSection/RemappingPicker/illustrations/sub-input.svg
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/BehaviorSection/RemappingPicker/index.ts
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/BehaviorSection/RemappingPicker/utils.ts
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/BehaviorSection/index.ts
Labels: no-backport, .Team/SemanticLayer

#60486 🤖 backported "sdk(fix): Render legacy popover within the proper portal container for the SDK"
  e2e/support/helpers/e2e-dashboard-helpers.ts
  e2e/test-component/scenarios/embedding-sdk/styles-tests.cy.spec.tsx
  frontend/src/metabase/common/components/Popover/Popover.jsx
  frontend/src/metabase/dashboard/components/ClickBehaviorSidebar/ClickBehaviorSidebar.tsx
Labels: was-backported

#60548 Repro for "Query builder SQL references wrong column in outermost WHERE clause"
  e2e/support/helpers/e2e-ad-hoc-question-helpers.js
  e2e/test/scenarios/question-reproductions/reproductions.cy.spec.ts
Labels: no-backport, .Team/Querying

#60558 🤖 backported "fix: optionally add can_run_adhoc_query in items"
  .clj-kondo/config/modules/config.edn
  src/metabase/collections/api.clj
  src/metabase/queries/models/card.clj
  test/metabase/collections/api_test.clj
Labels: was-backported

#60560 docs(sdk): Update SDK version to 0.55.4
  enterprise/frontend/src/embedding-sdk/CHANGELOG.md
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: no-backport

#60448 🤖 backported "Make `mu/fn` safe for cljs (`java` not found)"
  src/metabase/util/malli/fn.clj
  test/metabase/util/malli/fn_java_error_test.cljs
Labels: was-backported

#60568 🤖 backported "Preview native query with snippet"
  e2e/test/scenarios/native/snippets.cy.spec.js
  frontend/src/metabase/query_builder/components/view/PreviewQueryButton/PreviewQueryButton.tsx
Labels: was-backported

#60238 show active y-axis split lines on hover
  e2e/support/helpers/e2e-visual-tests-helpers.js
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/axis.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-chart-events.ts
Labels: backport, .Team/DashViz

#60575 chore: add timestamp columns to tenants
  enterprise/backend/src/metabase_enterprise/tenants/model.clj
  resources/migrations/056_update_migrations.yaml
Labels: .Team/AdminWebapp

#60517 filters in dashcards tracking
  e2e/test/scenarios/dashboard-filters/parameters.cy.spec.js
  e2e/test/scenarios/dashboard/visualizer/snowplow-tracking.cy.spec.ts
  frontend/src/metabase-types/analytics/event.ts
  frontend/src/metabase/dashboard/actions/parameters.ts
  frontend/src/metabase/dashboard/analytics.ts
  frontend/src/metabase/visualizer/components/DataImporter/ColumnsList/ColumnsList.tsx
  frontend/src/metabase/visualizer/components/DataImporter/DatasetsList/DatasetsList.tsx
  frontend/src/metabase/visualizer/components/VisualizationPicker/VisualizationPicker.tsx
Labels: no-backport, .Team/DashViz

#60577 Add repro for "Question Query Builder fails with missing column when joining two models"
  e2e/test/scenarios/models/reproductions.cy.spec.ts
Labels: no-backport, .Team/Querying

#60573 Add repro for "Multiple model fields mapped to same db field have weird bugs"
  e2e/test/scenarios/models/reproductions.cy.spec.ts
Labels: no-backport, .Team/Querying

#60485 Allow users to go back to dashboard from new dashboard question flow
  e2e/test-component/scenarios/embedding-sdk/editable-dashboard.cy.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/BackButton/BackButton.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/InteractiveQuestionProvider.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/context/types.ts
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionDefaultView/InteractiveQuestionDefaultView.tsx
  enterprise/frontend/src/embedding-sdk/components/public/dashboard/EditableDashboard/EditableDashboard.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/public/dashboard/InteractiveDashboard/InteractiveDashboard.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/public/dashboard/SdkDashboard.tsx
  enterprise/frontend/src/embedding-sdk/components/public/dashboard/tests/SdkDashboard.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/public/dashboard/tests/setup.tsx
  frontend/src/metabase/css/core/hide.module.css
  frontend/src/metabase/dashboard/context/context.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/DashboardBackButton/DashboardBackButton.tsx
  frontend/src/metabase/querying/notebook/components/DataStep/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/querying/notebook/components/DataStep/tests/setup.tsx
Labels: .Team/Embedding

#60595 🤖 backported "docs(sdk): Remove beta message from the SDK readme after GA"
  enterprise/frontend/src/embedding-sdk/README.md
Labels: was-backported

#60504 Rename source param name to content
  enterprise/frontend/src/metabase-enterprise/embedding/components/InteractiveEmbeddingSettings.tsx
  enterprise/frontend/src/metabase-enterprise/google_drive/GdriveAddDataPanel.tsx
  frontend/src/metabase/admin/people/components/PeopleNav.tsx
  frontend/src/metabase/admin/performance/components/StrategyEditorForDatabases.tsx
  frontend/src/metabase/admin/permissions/components/PermissionsEditor/PermissionsEditor.jsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/EmbeddingSdkSettings.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/StaticEmbeddingSettings.tsx
  frontend/src/metabase/admin/settings/components/SettingsPages/AuthenticationSettingsPage.tsx
  frontend/src/metabase/admin/settings/components/SettingsPages/EmailSettingsPage.tsx
  frontend/src/metabase/admin/settings/components/SettingsPages/EmbeddingSettingsPage.tsx
  frontend/src/metabase/admin/settings/components/SettingsPages/GeneralSettingsPage.tsx
  frontend/src/metabase/admin/settings/components/SettingsPages/UpdatesSettingsPage.tsx
  frontend/src/metabase/admin/settings/components/SettingsPages/UploadSettingsPage.tsx
  frontend/src/metabase/admin/tools/components/Help/Help.tsx
  frontend/src/metabase/admin/upsells/UpsellBetterSupport.tsx
  frontend/src/metabase/admin/upsells/UpsellCacheConfig.tsx
  frontend/src/metabase/admin/upsells/UpsellDevInstances.tsx
  frontend/src/metabase/admin/upsells/UpsellHosting.tsx
  frontend/src/metabase/admin/upsells/UpsellMetabaseBanner.tsx
  frontend/src/metabase/admin/upsells/UpsellPermissions.tsx
  frontend/src/metabase/admin/upsells/UpsellSSO.tsx
  frontend/src/metabase/admin/upsells/UpsellStorage.tsx
  frontend/src/metabase/admin/upsells/UpsellUploads.tsx
  frontend/src/metabase/admin/upsells/UpsellWhitelabel.tsx
  frontend/src/metabase/admin/upsells/components/UpsellBanner.tsx
  frontend/src/metabase/admin/upsells/components/UpsellBanner.unit.spec.tsx
  frontend/src/metabase/admin/upsells/components/UpsellBigCard.tsx
  frontend/src/metabase/admin/upsells/components/UpsellCard.tsx
  frontend/src/metabase/admin/upsells/components/UpsellPill.tsx
  frontend/src/metabase/admin/upsells/components/analytics.ts
  frontend/src/metabase/admin/upsells/components/use-upsell-link.ts
  frontend/src/metabase/admin/upsells/components/use-upsell-link.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardInfoSidebar/components/InsightsUpsellTab.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/AddDataModal/Panels/CSVPanel.tsx
Labels: no-backport, .Team/ProductGrowth

#60600 SEM-484 Going into segments, you can't go back to any table
  e2e/test/scenarios/admin/datamodel/datamodel.cy.spec.ts
  frontend/src/metabase/metadata/pages/DataModel/components/TablePicker/wrappers.tsx
Labels: no-backport, .Team/SemanticLayer

#60572 Fix drill thru with multi-series dashcards
  e2e/test/scenarios/dashboard/title-drill.cy.spec.js
  frontend/src/metabase/dashboard/actions/getNewCardUrl.ts
  frontend/src/metabase/dashboard/actions/getNewCardUrl.unit.spec.ts
Labels: backport, .Team/Querying

#60621 🤖 backported "Fix MultiStageFilterPicker leaving the query with an empty stage"
  e2e/test/scenarios/models/reproductions.cy.spec.js
  frontend/src/metabase/querying/filters/components/FilterPicker/MultiStageFilterPicker/MultiStageFilterPicker.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/MultiStageFilterPicker/MultiStageFilterPicker.unit.spec.tsx
Labels: was-backported

#60616 Fix hover selector and add menu hover story
  frontend/src/metabase/ui/components/overlays/Menu/Menu.module.css
  frontend/src/metabase/ui/components/overlays/Menu/Menu.stories.tsx
Labels: no-backport, .Team/AdminWebapp

#60610 🤖 backported "Convert edit dashboard buttons to use dashboard context"
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeader.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeaderButtonRow/action-buttons.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/buttons/EditDashboardButton.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/buttons/SaveEditButton.tsx
Labels: was-backported

#60607 🤖 backported "Convert fullscreen dashboard buttons to use dashboard context"
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeaderButtonRow/action-buttons.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/buttons/FullscreenAnalyticsDashboard.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/buttons/FullscreenToggle.tsx
Labels: was-backported

#60571 Auto provision tenants, respect tenants feature
  enterprise/backend/src/metabase_enterprise/sso/integrations/jwt.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj
Labels: .Team/AdminWebapp

#60628 stop asking team workflows to review all migrations
  .github/auto_request_review.yml
  .github/workflows/auto-request-review.yml
Labels: backport, .Team/Workflows

#60631 🤖 backported "stop asking team workflows to review all migrations"
  .github/auto_request_review.yml
  .github/workflows/auto-request-review.yml
Labels: was-backported

#60508 Delete bigquery datasets > 2 hours old
  modules/drivers/bigquery-cloud-sdk/test/metabase/test/data/bigquery_cloud_sdk.clj
Labels: no-backport, .Team/Drivers

#60325 Closes VIZ-1242 visualize another way copy
  e2e/support/helpers/e2e-dashboard-visualizer-helpers.ts
  e2e/test-component/scenarios/embedding-sdk/popover.cy.spec.tsx
  e2e/test/scenarios/dashboard-cards/dashboard-sections.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard-questions.cy.spec.js
  e2e/test/scenarios/dashboard/visualizer/basics.cy.spec.ts
  e2e/test/scenarios/dashboard/visualizer/cartesian.cy.spec.ts
  e2e/test/scenarios/metrics/metrics-dashboard.cy.spec.js
  e2e/test/scenarios/metrics/reproductions/metrics-reproductions.cy.spec.ts
  e2e/test/scenarios/visualizations-charts/legend.cy.spec.js
  e2e/test/scenarios/visualizations-charts/line-bar-tooltips.cy.spec.js
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardActionsPanel.tsx
  frontend/src/metabase/dashboard/components/DashCard/Dashcard.unit.spec.tsx
Labels: backport, .Team/DashViz

#60642 🤖 backported "Closes VIZ-1215 more space for pie wells"
  frontend/src/metabase/visualizer/components/VisualizationCanvas/VisualizationCanvas.tsx
  frontend/src/metabase/visualizer/components/VisualizationCanvas/wells/VerticalWell/PieVerticalWell.tsx
Labels: was-backported

#60635 🤖 backported "Chars composition fix"
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/ButtonBar.tsx
  frontend/src/metabase/components/CollapseSection/CollapseSection.tsx
  frontend/src/metabase/components/ListField/ListField.tsx
  frontend/src/metabase/components/SelectList/BaseSelectListItem.tsx
  frontend/src/metabase/components/SingleSelectListField/SingleSelectListField.tsx
  frontend/src/metabase/components/TextWidget/TextWidget.tsx
  frontend/src/metabase/components/TokenField/TokenField.tsx
  frontend/src/metabase/core/components/AccordionList/AccordionList.jsx
  frontend/src/metabase/core/components/EditableText/EditableText.tsx
  frontend/src/metabase/core/components/TabButton/TabButton.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapperButton.tsx
  frontend/src/metabase/databases/components/DatabaseEngineField/DatabaseEngineWidget.tsx
  frontend/src/metabase/nav/components/search/SearchBar/SearchBar.tsx
  frontend/src/metabase/palette/components/PaletteResultsList.tsx
  frontend/src/metabase/query_builder/components/LimitPopover.jsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/CodeMirrorEditor/completers.unit.spec.tsx
  frontend/src/metabase/query_builder/components/expressions/CombineColumns/ColumnAndSeparatorRow/ColumnInput.tsx
  frontend/src/metabase/query_builder/components/expressions/NameInput/NameInput.tsx
  frontend/src/metabase/ui/components/inputs/MultiAutocomplete/MultiAutocomplete.unit.spec.tsx
  frontend/src/metabase/ui/components/inputs/MultiAutocomplete/use-multi-autocomplete/use-multi-autocomplete.ts
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SettingsComponents/PeriodsAgoMenuOption.tsx
Labels: was-backported

#60634 🤖 backported "Chars composition fix"
  enterprise/frontend/src/embedding-sdk/components/public/MetabotQuestion/MetabotChatEmbedding.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/components/MetabotChat/MetabotChat.tsx
  frontend/src/metabase/common/components/AccordionList/AccordionList.jsx
  frontend/src/metabase/common/components/CollapseSection/CollapseSection.tsx
  frontend/src/metabase/common/components/EditableText/EditableText.tsx
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/ButtonBar.tsx
  frontend/src/metabase/common/components/SelectList/BaseSelectListItem.tsx
  frontend/src/metabase/common/components/TabButton/TabButton.tsx
  frontend/src/metabase/common/components/TokenField/TokenField.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapperButton.tsx
  frontend/src/metabase/databases/components/DatabaseEngineField/DatabaseEngineWidget.tsx
  frontend/src/metabase/nav/components/search/SearchBar/SearchBar.tsx
  frontend/src/metabase/palette/components/PaletteResultsList.tsx
  frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget/FieldValuesWidget/ListField/ListField.tsx
  frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget/FieldValuesWidget/SingleSelectListField/SingleSelectListField.tsx
  frontend/src/metabase/parameters/components/widgets/TextWidget/TextWidget.tsx
  frontend/src/metabase/query_builder/components/LimitPopover.jsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/CodeMirrorEditor/completers.unit.spec.tsx
  frontend/src/metabase/query_builder/components/expressions/CombineColumns/ColumnAndSeparatorRow/ColumnInput.tsx
  frontend/src/metabase/query_builder/components/expressions/NameInput/NameInput.tsx
  frontend/src/metabase/ui/components/inputs/MultiAutocomplete/MultiAutocomplete.unit.spec.tsx
  frontend/src/metabase/ui/components/inputs/MultiAutocomplete/use-multi-autocomplete/use-multi-autocomplete.ts
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SettingsComponents/PeriodsAgoMenuOption.tsx
Labels: was-backported

#60408 Improve usage analytics without first/last name
  resources/migrations/056_update_migrations.yaml
  resources/migrations/instance_analytics_views/users/v3/h2-users.sql
  resources/migrations/instance_analytics_views/users/v3/mysql-users.sql
  resources/migrations/instance_analytics_views/users/v3/postgres-users.sql
Labels: no-backport, .Team/AdminWebapp

#60644 Remove broken `lib/aggregation-column`
  frontend/src/metabase-lib/aggregation.ts
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/js.cljs
  test/metabase/lib/aggregation_test.cljc
Labels: no-backport, .Team/Querying

#60653 Fix Lib.isNumeric check and get rid of the "MySQL hack"
  frontend/src/metabase-lib/column_types.ts
  frontend/src/metabase-lib/v1/types/constants.ts
  frontend/src/metabase/visualizations/visualizations/Funnel/Funnel.unit.spec.jsx
  src/metabase/lib/types/constants.cljc
  test/metabase/lib/types/isa_test.cljc
Labels: no-backport, .Team/Querying

#60215 Closes VIZ-195 - Bar chart data labels jump 1px on hover
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
Labels: backport, .Team/DashViz

#60655 🤖 backported "Closes VIZ-195 - Bar chart data labels jump 1px on hover"
  frontend/src/metabase/visualizations/echarts/cartesian/option/series.ts
Labels: was-backported

#60627 List all supported upload databases in a disclaimer/warning
  frontend/src/metabase/admin/settings/components/UploadSettings/UploadSettingsForm.tsx
Labels: backport, .Team/ProductGrowth

#60666 🤖 backported "List all supported upload databases in a disclaimer/warning"
  frontend/src/metabase/admin/settings/components/UploadSettings/UploadSettingsForm.tsx
Labels: was-backported

#60672 Fix SQL Server connection failure when login and database users differ
  modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj
  modules/drivers/sqlserver/test/metabase/driver/sqlserver_test.clj
Labels: backport, PR-Env

#60676 🤖 backported "Fix SQL Server connection failure when login and database users differ"
  modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj
  modules/drivers/sqlserver/test/metabase/driver/sqlserver_test.clj
Labels: was-backported

#60677 Fix for claude code container issue
  .github/workflows/claude.yml
Labels: no-backport

#60543 Closes VIZ-1204 VIZ-1205 error state when removing columns and switching viz
  frontend/src/metabase/visualizer/utils/get-updated-settings-for-display.ts
  frontend/src/metabase/visualizer/utils/get-updated-settings-for-display.unit.spec.ts
Labels: backport, .Team/DashViz

#60606 🤖 backported "Convert DashboardTabs to context"
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeaderView.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/tests/setup.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardTabs/use-dashboard-tabs.ts
  frontend/src/metabase/dashboard/containers/AutomaticDashboardApp/AutomaticDashboardApp.tsx
  frontend/src/metabase/dashboard/context/context.redux.ts
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardView.tsx
Labels: was-backported

#60608 🤖 backported "Convert basic dashboard buttons to use dashboard context"
  frontend/src/metabase/dashboard/components/DashboardHeader/buttons/AddActionElementButton.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/buttons/AddFilterParameterButton/AddFilterParameterButton.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/buttons/AddFilterParameterButton/AddFilterParameterButton.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/buttons/AddHeadingOrTextButton.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/buttons/AddQuestionButton.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/buttons/AddSectionButton/AddSectionButton.tsx
  frontend/src/metabase/dashboard/components/QuestionPicker/actions.ts
  frontend/src/metabase/dashboard/context/context.redux.ts
Labels: was-backported

#60679 🤖 backported "tests: drop old testing library"
  frontend/src/metabase/actions/hooks/use-action-form/use-action-form.unit.spec.ts
  frontend/src/metabase/common/hooks/use-list-keyboard-navigation/use-list-keyboard-navigation.unit.spec.ts
  frontend/src/metabase/common/hooks/use-list-select.unit.spec.ts
  frontend/src/metabase/common/hooks/use-pagination.unit.spec.ts
  frontend/src/metabase/common/hooks/use-url-state/use-url-state.unit.spec.ts
  frontend/src/metabase/common/hooks/use-user-key-value.unit.spec.tsx
  frontend/src/metabase/querying/filters/hooks/use-boolean-filter/use-boolean-filter.unit.spec.ts
  frontend/src/metabase/querying/filters/hooks/use-coordinate-filter/use-coordinate-filter.unit.spec.ts
  frontend/src/metabase/querying/filters/hooks/use-date-filter/use-date-filter.unit.spec.ts
  frontend/src/metabase/querying/filters/hooks/use-default-filter/use-default-filter.unit.spec.ts
  frontend/src/metabase/querying/filters/hooks/use-number-filter/use-number-filter.unit.spec.ts
  frontend/src/metabase/querying/filters/hooks/use-string-filter/use-string-filter.unit.spec.ts
  frontend/src/metabase/querying/filters/hooks/use-time-filter/use-time-filter.unit.spec.ts
  frontend/src/metabase/visualizations/echarts/tooltip/index.unit.spec.ts
  frontend/test/__support__/ui.tsx
  package.json
  yarn.lock
Labels: was-backported

#60432 🤖 backported "Reduce memory pressure during BigQuery sync"
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj
Labels: was-backported

#60678 use :role on connection details for sqlserver
  enterprise/backend/test/metabase_enterprise/impersonation/driver_test.clj
Labels: backport, .Team/Drivers

#60682 🤖 backported "infer only one column to be entity name"
  src/metabase/analyze/fingerprint/fingerprinters.clj
  src/metabase/sync/analyze/classify.clj
  test/metabase/sync/analyze/classify_test.clj
Labels: was-backported

#60687 Fix typedoc help message typo
  .github/workflows/embedding-sdk.yml
Labels: backport, .Team/Embedding

#60639 Make namespaced components consistent in core and SDK
  enterprise/frontend/src/embedding-sdk/components/public/dashboard/SdkDashboard.stories.tsx
  enterprise/frontend/src/embedding-sdk/components/public/dashboard/SdkDashboard.tsx
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx
  frontend/src/metabase/dashboard/components/Dashboard/components/ParametersList.tsx
  frontend/src/metabase/dashboard/components/Dashboard/components/index.ts
  frontend/src/metabase/dashboard/components/Dashboard/index.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeaderView.tsx
  frontend/src/metabase/dashboard/components/DashboardParameterPanel/DashboardParameterPanel.tsx
  frontend/src/metabase/dashboard/containers/AutomaticDashboardApp/AutomaticDashboardApp.tsx
  frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget/FieldValuesWidget/utils.ts
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardView.tsx
Labels: backport, .Team/Embedding

#60670 Add a repro test for "Lib.visibleColumns are not marked as selected when joining a native query"
  e2e/test/scenarios/question-reproductions/reproductions.cy.spec.ts
Labels: no-backport, .Team/Querying

#60697 [docs] Update ssh-tunnel.md
  docs/databases/ssh-tunnel.md
Labels: Type:Documentation, backport

#60691 Add repro for "Custom Expression can fail query when mixing numeric and string functions"
  e2e/support/helpers/e2e-custom-column-helpers.ts
  e2e/test/scenarios/custom-column/custom-column-reproductions.cy.spec.js
Labels: .Team/Querying, triple-backport

#60711 Fix flaky dashboard filters test
  e2e/test/scenarios/filters-reproductions/dashboard-filters-reproductions.cy.spec.js
Labels: no-backport, .Team/SemanticLayer

#58723 Change 'Inner Ring' label to 'Breakout' for single dimension
  frontend/src/metabase/visualizations/visualizations/PieChart/DimensionsWidget.tsx
  frontend/src/metabase/visualizations/visualizations/PieChart/DimensionsWidget.unit.spec.tsx
Labels: Visualization/Chart Settings, .Frontend, backport, Visualization/Charts/Pie, .Team/DashViz

#60641 🤖 backported "Closes VIZ-1242 visualize another way copy"
  e2e/support/helpers/e2e-dashboard-visualizer-helpers.ts
  e2e/test-component/scenarios/embedding-sdk/popover.cy.spec.tsx
  e2e/test/scenarios/dashboard-cards/dashboard-sections.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard-questions.cy.spec.js
  e2e/test/scenarios/dashboard/visualizer/basics.cy.spec.ts
  e2e/test/scenarios/dashboard/visualizer/cartesian.cy.spec.ts
  e2e/test/scenarios/metrics/metrics-dashboard.cy.spec.js
  e2e/test/scenarios/metrics/reproductions/metrics-reproductions.cy.spec.ts
  e2e/test/scenarios/visualizations-charts/legend.cy.spec.js
  e2e/test/scenarios/visualizations-charts/line-bar-tooltips.cy.spec.js
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardActionsPanel.tsx
  frontend/src/metabase/dashboard/components/DashCard/Dashcard.unit.spec.tsx
Labels: was-backported

#60566 Add filter collapsing logic to question dashboard cards
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_card_filters_Full_Width_Chart_Many_Filters.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_card_filters_Full_Width_Chart_One_Filter.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_card_filters_Medium_Chart_Many_Filters.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_card_filters_Medium_Chart_One_Filter.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_card_filters_Narrow_Chart_Many_Filters.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_card_filters_Narrow_Chart_Many_Filters_Expanded.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_card_filters_Narrow_Chart_One_Filter.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_card_filters_Narrow_Chart_One_Filter_Long_Card_Name.png
  e2e/test/scenarios/dashboard-filters/parameters.cy.spec.js
  frontend/src/metabase-lib/v1/parameters/utils/parameter-values.js
  frontend/src/metabase/dashboard/components/CollapsibleDashboardParameterList/CollapsibleDashboardParameterList.tsx
  frontend/src/metabase/dashboard/components/CollapsibleDashboardParameterList/index.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.module.css
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/dashboard/hooks/use-responsive-parameter-list.ts
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardView-card-filters.stories.tsx
  frontend/src/metabase/visualizations/components/legend/LegendCaption/LegendCaption.styled.tsx
  frontend/src/metabase/visualizations/components/legend/LegendCaption/LegendCaption.tsx
  frontend/src/metabase/visualizations/components/legend/LegendCaption/index.ts
  frontend/src/metabase/visualizations/lib/settings/visualization.js
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.tsx
Labels: no-backport, .Team/DashViz

#60730 docs: clarify export limit
  docs/questions/exporting-results.md
Labels: Type:Documentation, backport

#60701 🤖 backported "Stop unfurling links in Slack notifications"
  src/metabase/channel/impl/slack.clj
  test/metabase/channel/impl/slack_test.clj
  test/metabase/pulse/dashboard_subscription_test.clj
Labels: was-backported

#60674 docs: move embedding auth flow article to docs
  docs/README.md
  docs/embedding/images/full-app-embedding-sso.png
  docs/embedding/images/signed-embedding-jwt.png
  docs/embedding/interactive-embedding.md
  docs/embedding/introduction.md
  docs/embedding/securing-embeds.md
  docs/embedding/start.md
  docs/permissions/data-sandboxes.md
Labels: Type:Documentation, backport

#60739 🤖 backported "docs: move embedding auth flow article to docs"
  docs/README.md
  docs/embedding/images/full-app-embedding-sso.png
  docs/embedding/images/signed-embedding-jwt.png
  docs/embedding/interactive-embedding.md
  docs/embedding/introduction.md
  docs/embedding/securing-embeds.md
  docs/embedding/start.md
  docs/permissions/data-sandboxes.md
Labels: was-backported

#60663 [Lib] Stop passing `:unique-name-fn` as an option
  src/metabase/lib/card.cljc
  src/metabase/lib/drill_thru/common.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/field/resolution.cljc
  src/metabase/lib/field/util.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/metadata/result_metadata.cljc
  src/metabase/lib/remove_replace.cljc
  src/metabase/lib/stage.cljc
  src/metabase/lib/table.cljc
  test/metabase/lib/breakout_test.cljc
  test/metabase/lib/column_group_test.cljc
  test/metabase/lib/expression_test.cljc
  test/metabase/lib/field/resolution_test.cljc
  test/metabase/lib/filter_test.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/js_test.cljs
  test/metabase/lib/metadata/calculation_test.cljc
  test/metabase/lib/metadata/result_metadata_test.cljc
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/remove_replace_test.cljc
  test/metabase/lib/stage_test.cljc
  test/metabase/lib/test_util/matrix.cljc
  test/metabase/lib/test_util/metadata_providers/mock.cljc
  test/metabase/lib/types/isa_test.cljc
  test/metabase/query_processor/api_test.clj
  test/metabase/query_processor/pivot_test.clj
  test/metabase/query_processor/preprocess_test.clj
  test/metabase/query_processor_test/model_test.clj
Labels: no-backport, .Team/DevEx

#60546 Inconsistent formatting
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Dark_Theme_Default.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Dark_Theme_No_Background_Default.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Dark_Theme_No_Background_Scroll.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Dark_Theme_Scroll.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Light_Theme_Default.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Light_Theme_No_Background_Default.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Light_Theme_No_Background_Scroll.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Light_Theme_Scroll.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Transparent_Theme_Default.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Transparent_Theme_No_Background_Default.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Transparent_Theme_No_Background_Scroll.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Transparent_Theme_Scroll.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_All_Options.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Month_Year.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Quarter_Year.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Quarter_Year_Dropdown.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Range.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Relative.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Single.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Number.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_List.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_List_Single_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_List_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_Search.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_Search_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Text.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Text_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Unit_Of_Time.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_All_Options.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Month_Year.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Quarter_Year.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Quarter_Year_Dropdown.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Range.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Relative.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Single.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Number.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_List.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_List_Single_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_List_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_Search.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_Search_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Text.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Text_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Unit_Of_Time.png
  .loki/reference/chrome_laptop_viz_Table_Dashboard_Table.png
  .loki/reference/chrome_laptop_viz_Table_Dashboard_Table_Embedding_Theme.png
  .loki/reference/chrome_laptop_viz_Table_Dashboard_Table_Embedding_Theme_With_Sticky_Background_Color.png
  e2e/test/scenarios/dashboard-filters/dashboard-filters-number-source.cy.spec.js
  e2e/test/scenarios/embedding/sdk-iframe-embedding/sdk-iframe-embedding.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding/theming.cy.spec.ts
  e2e/test/scenarios/visualizations-tabular/table.cy.spec.js
  frontend/src/metabase/common/hooks/use-number-formatter.ts
  frontend/src/metabase/common/hooks/use-number-formatter.unit.spec.ts
  frontend/src/metabase/data-grid/components/DataGrid/DataGrid.stories.tsx
  frontend/src/metabase/data-grid/components/Footer/Footer.tsx
  frontend/src/metabase/lib/formatting/numbers.tsx
  frontend/src/metabase/query_builder/components/view/QuestionRowCount/QuestionRowCount.tsx
  frontend/src/metabase/query_builder/components/view/QuestionRowCount/QuestionRowCount.unit.spec.tsx
  frontend/src/metabase/visualizations/components/PaginationFooter/PaginationFooter.tsx
Labels: backport, .Team/Querying

#60710 sync new-table api for new view sync
  src/metabase/sync/core.clj
  src/metabase/sync/sync_metadata.clj
  test/metabase/transform/transform_test.clj
Labels: .Team/SemanticLayer

#60727 relax test, ordering can be nondeterministic
  test/metabase/sync/analyze/classify_test.clj
Labels: backport, .Team/SemanticLayer

#60725 Fix couldn't click filters in dashboard edit mode with SDK
  e2e/test-component/scenarios/embedding-sdk/editable-dashboard.cy.spec.tsx
  frontend/src/metabase/dashboard/components/CollapsibleDashboardParameterList/CollapsibleDashboardParameterList.tsx
  frontend/src/metabase/parameters/components/ParametersList/ParametersList.tsx
Labels: no-backport, .Team/DashViz

#60709 🤖 backported "Add repro for "Custom Expression can fail query when mixing numeric and string functions""
  e2e/support/helpers/e2e-custom-column-helpers.ts
  e2e/test/scenarios/custom-column/custom-column-reproductions.cy.spec.js
Labels: was-backported

#60750 🤖 backported "Inconsistent formatting"
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Dark_Theme_Default.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Dark_Theme_No_Background_Default.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Dark_Theme_No_Background_Scroll.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Dark_Theme_Scroll.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Light_Theme_Default.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Light_Theme_No_Background_Default.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Light_Theme_No_Background_Scroll.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Light_Theme_Scroll.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Transparent_Theme_Default.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Transparent_Theme_No_Background_Default.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Transparent_Theme_No_Background_Scroll.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Transparent_Theme_Scroll.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_All_Options.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Month_Year.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Quarter_Year.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Quarter_Year_Dropdown.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Range.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Relative.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Single.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Number.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_List.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_List_Single_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_List_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_Search.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Parameter_Search_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Text.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Text_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Unit_Of_Time.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_All_Options.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Month_Year.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Quarter_Year.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Quarter_Year_Dropdown.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Range.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Relative.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Single.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Number.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_List.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_List_Single_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_List_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_Search.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Parameter_Search_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Text.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Text_With_Value.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Unit_Of_Time.png
  .loki/reference/chrome_laptop_viz_Table_Dashboard_Table.png
  .loki/reference/chrome_laptop_viz_Table_Dashboard_Table_Embedding_Theme.png
  .loki/reference/chrome_laptop_viz_Table_Dashboard_Table_Embedding_Theme_With_Sticky_Background_Color.png
  e2e/test/scenarios/dashboard-filters/dashboard-filters-number-source.cy.spec.js
  e2e/test/scenarios/embedding/sdk-iframe-embedding/sdk-iframe-embedding.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding/theming.cy.spec.ts
  e2e/test/scenarios/visualizations-tabular/table.cy.spec.js
  frontend/src/metabase/common/hooks/use-number-formatter.ts
  frontend/src/metabase/common/hooks/use-number-formatter.unit.spec.ts
  frontend/src/metabase/data-grid/components/DataGrid/DataGrid.stories.tsx
  frontend/src/metabase/data-grid/components/Footer/Footer.tsx
  frontend/src/metabase/lib/formatting/numbers.tsx
  frontend/src/metabase/query_builder/components/view/QuestionRowCount/QuestionRowCount.tsx
  frontend/src/metabase/query_builder/components/view/QuestionRowCount/QuestionRowCount.unit.spec.tsx
  frontend/src/metabase/visualizations/components/PaginationFooter/PaginationFooter.tsx
Labels: was-backported

#60738 🤖 backported "deps: fix critical alert re pbkdf2"
  package.json
  yarn.lock
Labels: was-backported

#60696 Add repro for "Validate date/datetime arguments to custom expressions"
  e2e/test/scenarios/custom-column/custom-column-reproductions.cy.spec.js
Labels: backport, .Team/Querying
