Repository metabase/metabase, pull requests merged in 2025-01, with the labels that each got.

#51643 🤖 backported "docs - env vars in config files"
  docs/configuring-metabase/config-file.md
Labels: was-backported

#51709 Workflow: Slack Notification for New Feature Requests
  .github/workflows/main.yml
Labels: .CI & Tests, no-backport

#51720 🍾 🎆 Happy new year e2e test fixes 🎆 🍾
  e2e/test/scenarios/dashboard-filters/shared/dashboard-filters-date.js
  e2e/test/scenarios/embedding/embedding-reproductions.cy.spec.js
  e2e/test/scenarios/sharing/public-question.cy.spec.js
Labels: .CI & Tests, backport, .Team/AdminWebapp

#51722 🤖 backported "🍾 🎆 Happy new year e2e test fixes 🎆 🍾 "
  e2e/test/scenarios/dashboard-filters/shared/dashboard-filters-date.js
  e2e/test/scenarios/sharing/public-question.cy.spec.js
Labels: was-backported

#51723 🤖 backported "🍾 🎆 Happy new year e2e test fixes 🎆 🍾 "
  e2e/test/scenarios/dashboard-filters/shared/dashboard-filters-date.js
  e2e/test/scenarios/embedding/embedding-reproductions.cy.spec.js
  e2e/test/scenarios/sharing/public-question.cy.spec.js
Labels: was-backported

#51661 Fix static embedding missing dark theme on some date widgets
  .loki/reference/chrome_laptop_Inputs_DatePicker_Dates_range.png
  .loki/reference/chrome_laptop_Inputs_DatePicker_Dates_range_SDK.png
  .loki/reference/chrome_laptop_Parameters_DatePicker_All_Options.png
  .loki/reference/chrome_laptop_Parameters_DatePicker_All_Options_Dark_Theme.png
  .loki/reference/chrome_laptop_Parameters_DatePicker_Exclude.png
  .loki/reference/chrome_laptop_Parameters_DatePicker_Exclude_Dark_Theme.png
  .loki/reference/chrome_laptop_Parameters_DatePicker_Exclude_Day_Of_Week.png
  .loki/reference/chrome_laptop_Parameters_DatePicker_Exclude_Day_Of_Week_Dark_Theme.png
  .loki/reference/chrome_laptop_Parameters_DatePicker_Relative_Current.png
  .loki/reference/chrome_laptop_Parameters_DatePicker_Relative_Current_Dark_Theme.png
  .loki/reference/chrome_laptop_Parameters_DatePicker_Relative_Next.png
  .loki/reference/chrome_laptop_Parameters_DatePicker_Relative_Next_Dark_Theme.png
  .loki/reference/chrome_laptop_Parameters_DatePicker_Relative_Previous.png
  .loki/reference/chrome_laptop_Parameters_DatePicker_Relative_Previous_Dark_Theme.png
  .loki/reference/chrome_laptop_Parameters_DatePicker_Specific_Between.png
  .loki/reference/chrome_laptop_Parameters_DatePicker_Specific_Between_Dark_Theme.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_All_Options.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Month_Year.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Quarter_Year.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Quarter_Year_Dropdown.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Range.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Single.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Month_Year.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Quarter_Year_Dropdown.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Range.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Single.png
  frontend/src/metabase/css/core/colors.module.css
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.module.css
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardView-filters.stories.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/DatePicker.stories.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/DateShortcutPicker/DateShortcutPicker.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/ExcludeDatePicker/ExcludeDatePicker.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateIntervalPicker/DateIntervalPicker.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/SpecificDatePicker/TimeToggle/TimeToggle.tsx
  frontend/src/metabase/ui/components/buttons/Button/Button.styled.tsx
  frontend/src/metabase/ui/components/buttons/PopoverBackButton/PopoverBackButton.tsx
  frontend/src/metabase/ui/components/inputs/Calendar/Calendar.styled.tsx
  frontend/src/metabase/ui/components/inputs/DateInput/DateInput.styled.tsx
  frontend/src/metabase/ui/components/inputs/DatePicker/DatePicker.styled.tsx
  frontend/src/metabase/ui/components/inputs/Input/Input.styled.tsx
  frontend/src/metabase/ui/components/inputs/MonthPicker/MonthPicker.styled.tsx
  frontend/src/metabase/ui/components/inputs/Switch/Switch.styled.tsx
  frontend/src/metabase/ui/components/inputs/TextInput/TextInput.styled.tsx
  frontend/src/metabase/ui/components/inputs/TimeInput/TimeInput.styled.tsx
  frontend/src/metabase/ui/components/navigation/Tabs/Tabs.styled.tsx
  frontend/src/metabase/ui/components/utils/Divider/Divider.styled.tsx
  loki.config.js
Labels: no-backport, .Team/Embedding

#51732 Update urls
  README.md
  frontend/src/metabase/admin/datamodel/containers/DataModelApp/ModelEducationalModal.jsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DisabledNativeCardHelpText/DisabledNativeCardHelpText.tsx
  frontend/src/metabase/models/containers/NewModelOptions/NewModelOptions.tsx
  frontend/src/metabase/parameters/components/ValuesSourceModal/ValuesSourceTypeModal.tsx
  frontend/src/metabase/query_builder/components/VisualizationError/VisualizationError.tsx
  frontend/src/metabase/query_builder/components/view/PreviewQueryModal/PreviewQueryModal.tsx
Labels: no-backport, .Team/Querying

#51737 dopcs - add link to support matrix
  docs/databases/connections/sql-server.md
Labels: Type:Documentation, backport

#51739 🤖 backported "dopcs - add link to support matrix"
  docs/databases/connections/sql-server.md
Labels: was-backported

#51433 Enable N-parallelism for e2e tests
  .github/actions/build-e2e-matrix/action.yml
  .github/workflows/e2e-matrix-builder.yml
  .github/workflows/e2e-test.yml
  .github/workflows/e2e-tests.yml
  e2e/test/scenarios/admin/performance/clock.cy.spec.ts
  e2e/test/scenarios/navigation/navbar.cy.spec.js
Labels: .CI & Tests, no-backport, .Team/AdminWebapp

#51705 🤖 backported "split up query stage e2e test file"
  e2e/test/scenarios/dashboard-filters-2/dashboard-filters-1-stage.cy.spec.ts
  e2e/test/scenarios/dashboard-filters-2/dashboard-filters-2-stage.cy.spec.ts
  e2e/test/scenarios/dashboard-filters-2/dashboard-filters-3-stage.cy.spec.ts
  e2e/test/scenarios/dashboard-filters-2/dashboard-filters-misc.cy.spec.ts
  e2e/test/scenarios/dashboard-filters-2/dashboard-filters-query-stages.cy.spec.ts
  e2e/test/scenarios/dashboard-filters-2/shared/dashboard-filters-query-stages.ts
Labels: was-backported

#51746 docs - separate google sign-in and ldap docs
  docs/README.md
  docs/databases/connections/databricks.md
  docs/paid-features/overview.md
  docs/people-and-groups/changing-password-complexity.md
  docs/people-and-groups/google-sign-in.md
  docs/people-and-groups/ldap.md
  docs/people-and-groups/managing.md
  docs/people-and-groups/start.md
  docs/questions/alerts.md
Labels: Type:Documentation, backport

#51489 Fix the zoom-in.binning drill thru for multi-stage queries
  frontend/src/metabase/visualizations/lib/table.js
  src/metabase/lib/drill_thru.cljc
  src/metabase/lib/drill_thru/automatic_insights.cljc
  src/metabase/lib/drill_thru/common.cljc
  src/metabase/lib/drill_thru/underlying_records.cljc
  src/metabase/lib/drill_thru/zoom_in_bins.cljc
  src/metabase/lib/drill_thru/zoom_in_timeseries.cljc
  src/metabase/lib/underlying.cljc
  test/metabase/lib/drill_thru/underlying_records_test.cljc
  test/metabase/lib/drill_thru/zoom_in_bins_test.cljc
  test/metabase/lib/underlying_test.cljc
Labels: backport, .Team/Querying

#51608 Fix compare-aggregations drill for multi-stage queries
  src/metabase/lib/drill_thru/compare_aggregations.cljc
  test/metabase/lib/drill_thru/compare_aggregations_test.cljc
Labels: backport, .Team/Querying

#51754 🤖 backported "Fix compare-aggregations drill for multi-stage queries"
  src/metabase/lib/drill_thru/compare_aggregations.cljc
  test/metabase/lib/drill_thru/compare_aggregations_test.cljc
Labels: was-backported

#51685 [svg] Limit the lifetime of a cached Truffle JS object to sidestep apparent memory leaks
  src/metabase/channel/render/js/svg.clj
  src/metabase/util/delay.clj
  test/metabase/util/delay_test.clj
Labels: backport

#51773 🤖 backported "[svg] Limit the lifetime of a cached Truffle JS object to sidestep apparent memory leaks"
  src/metabase/channel/render/js/svg.clj
  src/metabase/util/delay.clj
  test/metabase/util/delay_test.clj
Labels: was-backported

#51387 🤖 backported "adjusting webhook test response ui"
  e2e/test/scenarios/admin-2/settings.cy.spec.js
  frontend/src/metabase-types/api/notifications.ts
  frontend/src/metabase/admin/settings/notifications/WebhookForm.tsx
  src/metabase/channel/impl/http.clj
  test/metabase/channel/impl/http_test.clj
Labels: was-backported

#51750 🤖 backported "docs - separate google sign-in and ldap docs"
  docs/README.md
  docs/databases/connections/databricks.md
  docs/paid-features/overview.md
  docs/people-and-groups/changing-password-complexity.md
  docs/people-and-groups/google-sign-in.md
  docs/people-and-groups/ldap.md
  docs/people-and-groups/managing.md
  docs/people-and-groups/start.md
  docs/questions/sharing/alerts.md
Labels: was-backported

#51768 Update Loki snapshots for 2025 in release-x.52.x branch
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Month_Year.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Quarter_Year_Dropdown.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Month_Year.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Quarter_Year_Dropdown.png
Labels: no-backport

#51784 docs - links
  docs/databases/connections/databricks.md
  docs/people-and-groups/managing.md
  docs/questions/alerts.md
Labels: Type:Documentation, backport

#51785 🤖 backported "docs - links"
  docs/databases/connections/databricks.md
  docs/people-and-groups/managing.md
  docs/questions/sharing/alerts.md
Labels: was-backported

#51780 Update Loki snapshots for 2025 in release-x.51.x branch
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Month_Year.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Quarter_Year_Dropdown.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Month_Year.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Quarter_Year_Dropdown.png
Labels: no-backport, .Team/Querying, loki-update

#51721 Fix `FormTextInput` styling
  frontend/src/metabase/forms/components/FormTextInput/FormTextInput.tsx
Labels: backport, .Team/AdminWebapp

#51767 🤖 backported "Fix compare-aggregations drill for multi-stage queries"
  src/metabase/lib/drill_thru/compare_aggregations.cljc
  test/metabase/lib/drill_thru/compare_aggregations_test.cljc
Labels: was-backported

#51684 Preemptive caching FE
  e2e/test/scenarios/admin/performance/helpers/constants.ts
  e2e/test/scenarios/admin/performance/helpers/e2e-strategy-form-helpers.ts
  e2e/test/scenarios/admin/performance/strategyForm.cy.spec.ts
  enterprise/backend/src/metabase_enterprise/cache/strategies.clj
  enterprise/frontend/src/metabase-enterprise/caching/components/StrategyEditorForDatabases.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/caching/components/StrategyEditorForQuestionsAndDashboards/utils.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/caching/components/StrategyFormLauncher.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/caching/constants.ts
  frontend/src/metabase-types/api/mocks/performance.ts
  frontend/src/metabase-types/api/performance.ts
  frontend/src/metabase/admin/performance/components/StrategyForm.tsx
  frontend/src/metabase/admin/performance/components/test-utils.tsx
  resources/migrations/001_update_migrations.yaml
  src/metabase/models/cache_config.clj
  src/metabase/plugins/classloader.clj
  test/metabase/test/data.clj
Labels: no-backport, .Team/AdminWebapp

#51795 Update API dox
  docs/api-documentation.md
  docs/api/card.md
  docs/api/cards.md
  docs/api/collection.md
  docs/api/dashboard.md
  docs/api/database.md
  docs/api/search.md
  docs/api/user-key-value.md
Labels: no-backport, .Team/DevEx

#51769 🤖 backported "Fix the zoom-in.binning drill thru for multi-stage queries"
  frontend/src/metabase/visualizations/lib/table.js
  src/metabase/lib/drill_thru.cljc
  src/metabase/lib/drill_thru/automatic_insights.cljc
  src/metabase/lib/drill_thru/common.cljc
  src/metabase/lib/drill_thru/underlying_records.cljc
  src/metabase/lib/drill_thru/zoom_in_bins.cljc
  src/metabase/lib/drill_thru/zoom_in_timeseries.cljc
  src/metabase/lib/underlying.cljc
  test/metabase/lib/drill_thru/underlying_records_test.cljc
  test/metabase/lib/drill_thru/zoom_in_bins_test.cljc
  test/metabase/lib/underlying_test.cljc
Labels: was-backported

#51783 Update setting table name reference to :model/setting
  src/metabase/models/setting/cache.clj
Labels: backport, .Team/AdminWebapp

#51781 🤖 backported "put field usage behind a feature flag and turn it off by default"
  src/metabase/query_processor/middleware/process_userland_query.clj
  test/metabase/query_processor/middleware/process_userland_query_test.clj
Labels: was-backported

#51676 [Notification] Create notification API use current user as creator
  src/metabase/api/notification.clj
  src/metabase/models/notification.clj
  test/metabase/api/notification_test.clj
  test/metabase/models/notification_test.clj
Labels: .Team/Workflows

#51546 Improved encryption management
  docs/installation-and-operation/commands.md
  resources/migrations/001_update_migrations.yaml
  src/metabase/cmd.clj
  src/metabase/cmd/remove_encryption.clj
  src/metabase/cmd/rotate_encryption_key.clj
  src/metabase/db.clj
  src/metabase/db/encryption.clj
  src/metabase/db/setup.clj
  src/metabase/models/setting.clj
  src/metabase/util/string.clj
  test/metabase/api/session_test.clj
  test/metabase/api/setup_test.clj
  test/metabase/api/user_test.clj
  test/metabase/cmd/remove_encryption_test.clj
  test/metabase/cmd_test.clj
  test/metabase/setup_test.clj
  test/metabase/test.clj
  test/metabase/test/util.clj
  test/metabase/util/encryption_test.clj
Labels: no-backport, .Team/AdminWebapp

#51740 🤖 backported "Enable N-parallelism for e2e tests"
  .github/actions/build-e2e-matrix/action.yml
  .github/workflows/e2e-matrix-builder.yml
  .github/workflows/e2e-test.yml
  .github/workflows/e2e-tests.yml
  e2e/test/scenarios/admin/performance/clock.cy.spec.ts
  e2e/test/scenarios/navigation/navbar.cy.spec.js
Labels: was-backported

#51815 docs - add enterprise-only key to SDK blockquote
  docs/embedding/sdk/appearance.md
  docs/embedding/sdk/authentication.md
  docs/embedding/sdk/collections.md
  docs/embedding/sdk/config.md
  docs/embedding/sdk/dashboards.md
  docs/embedding/sdk/introduction.md
  docs/embedding/sdk/next-js.md
  docs/embedding/sdk/plugins.md
  docs/embedding/sdk/questions.md
  docs/embedding/sdk/quickstart-cli.md
  docs/embedding/sdk/quickstart.md
  docs/embedding/sdk/version.md
Labels: Type:Documentation, backport

#51812 docs - mb-disable-scheduler
  docs/configuring-metabase/environment-variables.md
  src/metabase/cmd/resources/other-env-vars.md
Labels: Type:Documentation, backport

#51789 Fix flaky unit test of JoinStep
  frontend/src/metabase/querying/notebook/components/JoinStep/JoinStep.unit.spec.tsx
Labels: no-backport, .Team/AdminWebapp

#51820 🤖 backported "docs - mb-disable-scheduler"
  docs/configuring-metabase/environment-variables.md
  src/metabase/cmd/resources/other-env-vars.md
Labels: was-backported

#51822 docs - note on bigquery structs
  docs/data-modeling/json-unfolding.md
Labels: Type:Documentation, backport

#51577 Small a11y improvements
  frontend/src/metabase/common/components/EntityPicker/components/ResultItem/ResultItem.styled.tsx
  frontend/src/metabase/css/core/base.styled.ts
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbar.styled.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/BookmarkList/BookmarkList.styled.tsx
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/SidebarItems.styled.tsx
  frontend/src/metabase/visualizations/components/legend/LegendLabel.module.css
Labels: backport, .Team/AdminWebapp

#51825 🤖 backported "Small a11y improvements"
  frontend/src/metabase/common/components/EntityPicker/components/ResultItem/ResultItem.styled.tsx
  frontend/src/metabase/css/core/base.styled.ts
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbar.styled.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/BookmarkList/BookmarkList.styled.tsx
  frontend/src/metabase/nav/containers/MainNavbar/SidebarItems/SidebarItems.styled.tsx
  frontend/src/metabase/visualizations/components/legend/LegendLabel.module.css
Labels: was-backported

#51223 Convert ChartSettingFieldsPartition to mantine
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.styled.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.unit.spec.js
  frontend/src/metabase/visualizations/lib/settings.js
  frontend/src/metabase/visualizations/visualizations/PivotTable/partitions.tsx
Labels: backport, .Team/Embedding

#51831 🤖 backported "docs - relocate contributing file"
  docs/CONTRIBUTING.md
  docs/developers-guide/start.md
Labels: was-backported

#51719 docs - in function for custom expressions
  docs/questions/query-builder/expressions-list.md
  docs/questions/query-builder/expressions/in.md
Labels: Type:Documentation, no-backport

#51823 Hide preemptive caching toggle for root config
  e2e/test/scenarios/admin/performance/strategyForm.cy.spec.ts
  frontend/src/metabase/admin/performance/components/StrategyForm.tsx
Labels: no-backport, .Team/AdminWebapp

#51832 Make JWT provider URI optional
  docs/configuring-metabase/environment-variables.md
  e2e/test/scenarios/admin-2/sso/jwt.cy.spec.js
  enterprise/backend/src/metabase_enterprise/sso/integrations/sso_settings.clj
  enterprise/frontend/src/metabase-enterprise/auth/components/SettingsJWTForm/SettingsJWTForm.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/auth/index.js
Labels: backport, .Team/AdminWebapp

#51715 Cache logins in e2e tests
  e2e/snapshot-creators/default.cy.snap.js
  e2e/support/commands/user/authentication.ts
  e2e/support/cypress_sample_instance_data.js
  e2e/support/helpers/e2e-setup-helpers.js
  e2e/test/scenarios/embedding-sdk/static-dashboard-cors.cy.spec.js
Labels: .CI & Tests, backport, .Team/AdminWebapp

#51835 🤖 backported "Cache logins in e2e tests"
  e2e/snapshot-creators/default.cy.snap.js
  e2e/support/commands/user/authentication.ts
  e2e/support/cypress_sample_instance_data.js
  e2e/support/helpers/e2e-setup-helpers.js
  e2e/test/scenarios/embedding-sdk/static-dashboard-cors.cy.spec.js
Labels: was-backported

#51837 Add rileythomp to team files
  .github/team.json
  release/github-slack-map.json
Labels: no-backport, .Team/Drivers

#51827 🤖 backported "Convert ChartSettingFieldsPartition to mantine"
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.styled.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldsPartition.unit.spec.js
  frontend/src/metabase/visualizations/lib/settings.js
  frontend/src/metabase/visualizations/visualizations/PivotTable/partitions.tsx
Labels: was-backported

#51834 🤖 backported "Make JWT provider URI optional"
  docs/configuring-metabase/environment-variables.md
  e2e/test/scenarios/admin-2/sso/jwt.cy.spec.js
  enterprise/backend/src/metabase_enterprise/sso/integrations/sso_settings.clj
  enterprise/frontend/src/metabase-enterprise/auth/components/SettingsJWTForm/SettingsJWTForm.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/auth/index.js
Labels: was-backported

#51800 Convert aggregation order-bys to reference by index instead of uuid before hashing
  src/metabase/lib/schema/util.cljc
  src/metabase/query_processor/util.clj
  test/metabase/query_processor/util_test.clj
Labels: backport, .Team/Querying

#51674 chore(e2e): create helpers for viz settings and viz type buttons
  e2e/support/helpers/e2e-viz-settings-helpers.js
  e2e/test/scenarios/binning/binning-reproductions.cy.spec.js
  e2e/test/scenarios/cross-version/source/03-questions.cy.spec.js
  e2e/test/scenarios/custom-column/custom-column-reproductions.cy.spec.js
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  e2e/test/scenarios/dashboard/x-rays.cy.spec.js
  e2e/test/scenarios/joins/joins-reproductions.cy.spec.js
  e2e/test/scenarios/models/reproductions.cy.spec.js
  e2e/test/scenarios/models/reproductions.cy.spec.ts
  e2e/test/scenarios/native/native-reproductions.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
  e2e/test/scenarios/permissions/sandboxes.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions-1.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions-2.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
  e2e/test/scenarios/question/multiple-column-breakouts.cy.spec.ts
  e2e/test/scenarios/question/settings.cy.spec.js
  e2e/test/scenarios/visualizations-charts/bar_chart.cy.spec.js
  e2e/test/scenarios/visualizations-charts/combo.cy.spec.js
  e2e/test/scenarios/visualizations-charts/funnel.cy.spec.js
  e2e/test/scenarios/visualizations-charts/legend.cy.spec.js
  e2e/test/scenarios/visualizations-charts/line-bar-tooltips.cy.spec.js
  e2e/test/scenarios/visualizations-charts/line_chart.cy.spec.js
  e2e/test/scenarios/visualizations-charts/pie_chart.cy.spec.js
  e2e/test/scenarios/visualizations-charts/sankey.cy.spec.js
  e2e/test/scenarios/visualizations-charts/scatter.cy.spec.js
  e2e/test/scenarios/visualizations-charts/trendline.cy.spec.js
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.js
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.ts
  e2e/test/scenarios/visualizations-charts/waterfall.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/pivot_tables.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/scalar.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/smartscalar-trend.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/table-column-settings.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/table.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/visualizations-tabular-reproductions.cy.spec.js
Labels: backport, .Team/Querying

#51511 Port schemas to use new `EntityListLoaderRtkQuery`
  e2e/test/scenarios/organization/timelines-question.cy.spec.js
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase/api/card.ts
  frontend/src/metabase/api/query.ts
  frontend/src/metabase/entities/containers/rtk-query/EntityListLoaderRtkQuery.tsx
  frontend/src/metabase/entities/containers/rtk-query/EntityObjectLoader.tsx
  frontend/src/metabase/entities/schemas.js
  frontend/src/metabase/redux/uploads.ts
  frontend/src/metabase/redux/uploads.unit.spec.js
  frontend/src/metabase/services.js
Labels: no-backport, .Team/Querying

#51519 Port collections to use new `EntityListLoaderRtkQuery`
  frontend/src/metabase/api/collection.ts
  frontend/src/metabase/entities/collections/collections.ts
Labels: no-backport, .Team/Querying

#51847 Port snippet collections to use new `EntityListLoaderRtkQuery`
  frontend/src/metabase/entities/collections/collections.ts
  frontend/src/metabase/entities/snippet-collections.js
Labels: no-backport, .Team/Querying

#51670 feat(QB): make viz icon stable independently from the viz type
  frontend/src/metabase/query_builder/components/view/QuestionDisplayToggle/QuestionDisplayToggle.tsx
  frontend/src/metabase/query_builder/components/view/QuestionDisplayToggle/index.ts
  frontend/src/metabase/query_builder/components/view/ViewFooter/CenterViewFooterButtonGroup.tsx
Labels: no-backport, .Team/Querying, PR-Env

#51774 perf: Optimize metabase.formatter/strip-trailing-zeroes
  src/metabase/formatter.clj
Labels: backport

#51819 🤖 backported "docs - add enterprise-only key to SDK blockquote"
  docs/embedding/sdk/appearance.md
  docs/embedding/sdk/authentication.md
  docs/embedding/sdk/collections.md
  docs/embedding/sdk/config.md
  docs/embedding/sdk/dashboards.md
  docs/embedding/sdk/introduction.md
  docs/embedding/sdk/next-js.md
  docs/embedding/sdk/plugins.md
  docs/embedding/sdk/questions.md
  docs/embedding/sdk/quickstart-cli.md
  docs/embedding/sdk/quickstart.md
  docs/embedding/sdk/version.md
Labels: was-backported

#51818 fix parameter placeholder encoding on iframe urls
  frontend/src/metabase/visualizations/visualizations/IFrameViz/utils.ts
  frontend/src/metabase/visualizations/visualizations/IFrameViz/utils.unit.spec.ts
Labels: no-backport, .Team/DashViz

#51808 Consolidate numeric type system checks
  frontend/src/metabase-lib/column_types.ts
  frontend/src/metabase-lib/v1/parameters/utils/filters.ts
  frontend/src/metabase/components/MetadataInfo/ColumnFingerprintInfo/ColumnFingerprintInfo.tsx
  frontend/src/metabase/querying/filters/components/FilterModal/FilterModalBody/ColumnFilterList/utils.ts
  src/metabase/lib/types/constants.cljc
  src/metabase/lib/types/isa.cljc
  test/metabase/lib/test_util/generators.cljc
  test/metabase/lib/types/isa_test.cljc
Labels: no-backport, .Team/Querying

#51802 [refs] Clean up backfill warnings on cards at startup
  src/metabase/task/sweep_query_analysis.clj
Labels: no-backport

#51816 Create serialization users as inactive
  enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj
  src/metabase/models/serialization.clj
Labels: backport, .Team/AdminWebapp

#51650 feat(QB): rename last to previous in date filters
  .loki/reference/chrome_laptop_Design_System_Overlays_Mantine_Modal_Can_Launch_Legacy_Select.png
  .loki/reference/chrome_laptop_Design_System_Overlays_Mantine_Popover_Can_Launch_Legacy_Tooltip.png
  .loki/reference/chrome_laptop_Parameters_DatePicker_All_Options.png
  .loki/reference/chrome_laptop_Parameters_DatePicker_All_Options_Dark_Theme.png
  .loki/reference/chrome_laptop_Parameters_DatePicker_Relative_Next.png
  .loki/reference/chrome_laptop_Parameters_DatePicker_Relative_Next_Dark_Theme.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_All_Options.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Single.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Number.png
  .loki/reference/chrome_laptop_embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_All_Options.png
  .loki/reference/chrome_laptop_viz_SankeyChart_Sankey_Node_Align_Right.png
  e2e/test/scenarios/dashboard/dashboard-reproductions.cy.spec.js
  e2e/test/scenarios/filters-reproductions/filters-reproductions.cy.spec.js
  e2e/test/scenarios/filters/filter-bulk.cy.spec.js
  e2e/test/scenarios/filters/filter-types.cy.spec.js
  e2e/test/scenarios/filters/relative-datetime.cy.spec.js
  frontend/src/metabase-lib/v1/parameters/constants.ts
  frontend/src/metabase/parameters/utils/formatting.unit.spec.ts
  frontend/src/metabase/querying/filters/components/DatePicker/DateShortcutPicker/constants.ts
  frontend/src/metabase/querying/filters/components/FilterModal/DateFilterEditor/DateFilterEditor.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/FilterModal/DateFilterEditor/constants.ts
  frontend/src/metabase/querying/filters/components/FilterModal/FilterModal.unit.spec.tsx
  frontend/src/metabase/querying/filters/constants.ts
  frontend/src/metabase/querying/parameters/utils/dates.ts
Labels: no-backport, .Team/Querying, PR-Env

#50158 [refs] Adding `:ident` to columns returned by `MetadataProvider`s
  src/metabase/api/table.clj
  src/metabase/legacy_mbql/util.cljc
  src/metabase/lib/js/metadata.cljs
  src/metabase/lib/metadata.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/metadata/ident.cljc
  src/metabase/lib/metadata/jvm.clj
  src/metabase/lib/stage.cljc
  src/metabase/lib/util.cljc
  src/metabase/query_processor/middleware/annotate.clj
  test/metabase/api/database_test.clj
  test/metabase/api/table_test.clj
  test/metabase/lib/js/metadata_test.cljs
  test/metabase/lib/metadata_test.cljc
  test/metabase/lib/query_test.cljc
  test/metabase/lib/test_metadata/graph_provider.cljc
  test/metabase/lib/test_util/metadata_providers/mock.cljc
  test/metabase/query_processor/middleware/add_implicit_clauses_test.clj
  test/metabase/query_processor/middleware/auto_bucket_datetimes_test.clj
  test/metabase/query_processor/middleware/desugar_test.clj
  test/metabase/query_processor/middleware/expand_macros_test.clj
  test/metabase/query_processor/middleware/metrics_test.clj
  test/metabase/query_processor/middleware/optimize_temporal_filters_test.clj
  test/metabase/query_processor/middleware/pre_alias_aggregations_test.clj
  test/metabase/query_processor_test/nested_queries_test.clj
Labels: no-backport, .Team/Querying

#51861 Backport serialization user fix (#51816) to 51
  enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj
  src/metabase/models/serialization.clj
Labels: .Team/AdminWebapp

#51860 🤖 backported "Create serialization users as inactive"
  enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj
  src/metabase/models/serialization.clj
Labels: was-backported

#51296 fix: Change pool acquireRetryAttemps to 0
  src/metabase/driver/sql_jdbc/connection.clj
  test/metabase/driver/sql_jdbc/connection_test.clj
Labels: backport, .Team/Drivers

#51249 Set key auth as the default auth method, put warning password
  modules/drivers/snowflake/resources/metabase-plugin.yaml
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
  src/metabase/plugins/lazy_loaded_driver.clj
Labels: backport, .Team/Drivers

#51870 docs - link updates
  docs/README.md
  docs/databases/sync-scan.md
  docs/developers-guide/start.md
  docs/embedding/static-embedding.md
  docs/installation-and-operation/installing-metabase.md
  docs/installation-and-operation/migrating-from-h2.md
  docs/people-and-groups/api-keys.md
  docs/troubleshooting-guide/loading-from-h2.md
Labels: Type:Documentation, backport

#51867 🤖 backported "Set key auth as the default auth method, put warning password"
  modules/drivers/snowflake/resources/metabase-plugin.yaml
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
  src/metabase/plugins/lazy_loaded_driver.clj
Labels: was-backported

#51866 🤖 backported "fix: Change pool acquireRetryAttemps to 0"
  src/metabase/driver/sql_jdbc/connection.clj
  test/metabase/driver/sql_jdbc/connection_test.clj
Labels: was-backported

#51869 Send flakes to jail
  e2e/test/scenarios/native/native-reproductions.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
  e2e/test/scenarios/organization/entity-picker.cy.spec.ts
  e2e/test/scenarios/question-reproductions/reproductions-1.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/visualizations-tabular-reproductions.cy.spec.js
Labels: .CI & Tests, no-backport, .Team/AdminWebapp

#51844 🤖 backported "chore(e2e): create helpers for viz settings and viz type buttons"
  e2e/support/helpers/e2e-viz-settings-helpers.js
  e2e/test/scenarios/binning/binning-reproductions.cy.spec.js
  e2e/test/scenarios/cross-version/source/03-questions.cy.spec.js
  e2e/test/scenarios/custom-column/custom-column-reproductions.cy.spec.js
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  e2e/test/scenarios/dashboard/x-rays.cy.spec.js
  e2e/test/scenarios/joins/joins-reproductions.cy.spec.js
  e2e/test/scenarios/models/reproductions.cy.spec.js
  e2e/test/scenarios/models/reproductions.cy.spec.ts
  e2e/test/scenarios/native/native-reproductions.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
  e2e/test/scenarios/permissions/sandboxes.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions-1.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions-2.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
  e2e/test/scenarios/question/multiple-column-breakouts.cy.spec.ts
  e2e/test/scenarios/question/settings.cy.spec.js
  e2e/test/scenarios/visualizations-charts/bar_chart.cy.spec.js
  e2e/test/scenarios/visualizations-charts/combo.cy.spec.js
  e2e/test/scenarios/visualizations-charts/funnel.cy.spec.js
  e2e/test/scenarios/visualizations-charts/legend.cy.spec.js
  e2e/test/scenarios/visualizations-charts/line-bar-tooltips.cy.spec.js
  e2e/test/scenarios/visualizations-charts/line_chart.cy.spec.js
  e2e/test/scenarios/visualizations-charts/pie_chart.cy.spec.js
  e2e/test/scenarios/visualizations-charts/sankey.cy.spec.js
  e2e/test/scenarios/visualizations-charts/scatter.cy.spec.js
  e2e/test/scenarios/visualizations-charts/trendline.cy.spec.js
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.js
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.ts
  e2e/test/scenarios/visualizations-charts/waterfall.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/pivot_tables.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/scalar.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/smartscalar-trend.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/table-column-settings.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/table.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/visualizations-tabular-reproductions.cy.spec.js
Labels: was-backported

#51192 Fix Liquibase CLI alias
  .clj-kondo/config.edn
  dev/src/dev/liquibase.clj
  src/metabase/db/custom_migrations.clj
  src/metabase/task.clj
  src/metabase/task/bootstrap.clj
Labels: no-backport, .Team/DevEx

#51862 Backport serialization user fix (#51816) to 50
  enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj
  src/metabase/models/serialization.clj
Labels: .Team/AdminWebapp

#51257 Dot X Releases
  .github/workflows/release-tag.yml
  .github/workflows/release.yml
  release/src/release-channel-log.ts
  release/src/release-log.ts
  release/src/release-notes.ts
  release/src/release-notes.unit.spec.ts
  release/src/version-helpers.ts
  release/src/version-helpers.unit.spec.ts
Labels: .Building & Releasing, no-backport, .Team/AdminWebapp

#51724 Actions preprocess queries before compiling
  src/metabase/driver/sql_jdbc/actions.clj
  test/metabase/actions_test.clj
Labels: backport, .Team/Querying

#51887 🤖 backported "Actions preprocess queries before compiling"
  src/metabase/driver/sql_jdbc/actions.clj
  test/metabase/actions_test.clj
Labels: was-backported

#51688 [Notification] Transaction emails
  resources/migrations/001_update_migrations.yaml
  src/metabase/api/alert.clj
  src/metabase/api/notification.clj
  src/metabase/api/pulse/unsubscribe.clj
  src/metabase/email.clj
  src/metabase/email/_notification_card_condition.hbs
  src/metabase/email/alert_admin_unsubscribed_you.hbs
  src/metabase/email/alert_unsubscribed.hbs
  src/metabase/email/alert_you_were_added.hbs
  src/metabase/email/messages.clj
  src/metabase/email/notification_card_unsubscribed.hbs
  src/metabase/email/notification_card_you_were_added.hbs
  src/metabase/email/notification_card_you_were_removed.hbs
  test/metabase/api/alert_test.clj
  test/metabase/api/notification_test.clj
  test/metabase/email_test.clj
  test/metabase/events/notification_test.clj
  test/metabase/notification/payload/impl/card_test.clj
  test/metabase/notification/test_util.clj
Labels: .Team/Workflows

#51657 [Notification] module readme
  src/metabase/notification/README.md
Labels: .Team/Workflows

#51655 chore(QB): show small Join and CC icons for aggregation without breakout
  e2e/test/scenarios/custom-column/cc-shortcuts-combine.cy.spec.ts
  e2e/test/scenarios/custom-column/cc-shortcuts.cy.spec.ts
  e2e/test/scenarios/question/offset.cy.spec.ts
  frontend/src/metabase/querying/notebook/components/NotebookStep/NotebookStep.tsx
  frontend/src/metabase/querying/notebook/components/NotebookStep/utils.ts
  frontend/src/metabase/querying/notebook/components/NotebookStepList/NotebookStepList.unit.spec.tsx
  frontend/src/metabase/querying/notebook/utils/steps.ts
  frontend/src/metabase/querying/notebook/utils/steps.unit.spec.ts
Labels: no-backport, .Team/Querying, PR-Env

#51671 feat(QB): combine chart type selector with viz settings sidebar
  e2e/support/helpers/e2e-viz-settings-helpers.js
  e2e/test/scenarios/binning/binning-reproductions.cy.spec.js
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard-reproductions.cy.spec.js
  e2e/test/scenarios/permissions/permissions-reproductions.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions-1.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
  e2e/test/scenarios/question/multiple-column-breakouts.cy.spec.ts
  e2e/test/scenarios/question/settings.cy.spec.js
  e2e/test/scenarios/visualizations-charts/line_chart.cy.spec.js
  e2e/test/scenarios/visualizations-charts/maps.cy.spec.js
  e2e/test/scenarios/visualizations-charts/sankey.cy.spec.js
  e2e/test/scenarios/visualizations-charts/trendline.cy.spec.js
  e2e/test/scenarios/visualizations-charts/waterfall.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/table.cy.spec.js
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeList/ChartTypeList.tsx
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeOption/ChartTypeOption.tsx
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeOption/ChartTypeOption.unit.spec.tsx
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeSettings/ChartTypeSettings.tsx
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeSettings/ChartTypeSettings.unit.spec.tsx
  frontend/src/metabase/query_builder/components/view/View/View/View.jsx
  frontend/src/metabase/query_builder/components/view/View/ViewLeftSidebarContainer/ViewLeftSidebarContainer.jsx
  frontend/src/metabase/query_builder/components/view/View/ViewMainContainer/ViewMainContainer.jsx
  frontend/src/metabase/query_builder/components/view/ViewFooter/LeftViewFooterButtonGroup.tsx
  frontend/src/metabase/query_builder/components/view/ViewFooter/ViewFooter.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/ChartSettingsSidebar.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/ChartTypeSidebar/ChartTypeSidebar.tsx
  frontend/src/metabase/query_builder/containers/QueryBuilder.unsaved-changes-warning.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ChartSettings/BaseChartSettings/BaseChartSettings.styled.tsx
  frontend/src/metabase/visualizations/components/ChartSettings/BaseChartSettings/BaseChartSettings.tsx
  frontend/src/metabase/visualizations/components/ChartSettings/BaseChartSettings/BaseChartSettings.unit.spec.tsx
  frontend/src/metabase/visualizations/components/ChartSettings/BaseChartSettings/hooks.ts
  frontend/src/metabase/visualizations/components/ChartSettings/QuestionChartSettings/QuestionChartSettings.tsx
  frontend/src/metabase/visualizations/visualizations/Map/Map.jsx
Labels: no-backport, .Team/Querying, PR-Env

#51885 CI Failure notice improvements
  .github/workflows/rerun-workflows.yml
Labels: .CI & Tests, no-backport, .Team/AdminWebapp

#51910 Remove `entity.ListLoader` from `ModelCacheRefreshJobs`
  frontend/src/metabase/admin/tasks/containers/ModelCacheRefreshJobs/ModelCacheRefreshJobs.tsx
Labels: no-backport, .Team/Querying

#51914 Remove `entity.ListLoader` from `SavedEntityList`
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityList.tsx
Labels: no-backport, .Team/Querying

#51915 Remove `entity.ListLoader` from `SearchApp`
  frontend/src/metabase/search/containers/SearchApp.jsx
Labels: no-backport, .Team/Querying

#51912 Remove `entity.ListLoader` from `QuestionList`
  frontend/src/metabase/dashboard/components/QuestionPicker/QuestionList.tsx
Labels: no-backport, .Team/Querying

#47895 add entity insertion library
  dev/src/dev/add_load.clj
  dev/src/dev/with_perm.clj
Labels: no-backport, .Team/AdminWebapp

#51923 Update year in the README
  README.md
Labels: no-backport

#51921 Reset login cache when starting cypress locally
  package.json
Labels: .CI & Tests, backport, .Team/AdminWebapp

#51884 Don't build FE for driver tests that don't need it; shave 2 minutes off of driver tests
  .github/actions/test-driver/action.yml
  .github/workflows/drivers.yml
  .github/workflows/drivers_summary.yml
Labels: no-backport, .Team/DevEx

#51927 🤖 backported "Reset login cache when starting cypress locally"
  package.json
Labels: was-backported

#51931 docs - upload title
  docs/databases/uploads.md
Labels: Type:Documentation, backport

#51892 Fix formatting of month-of-year when there are 53 weeks in the year
  frontend/src/metabase/lib/time-dayjs.ts
  frontend/src/metabase/lib/time-dayjs.unit.spec.ts
  frontend/src/metabase/lib/time.ts
  frontend/test/metabase/lib/time.unit.spec.js
Labels: backport, .Team/Querying

#51932 🤖 backported "docs - upload title"
  docs/databases/uploads.md
Labels: was-backported

#51871 🤖 backported "docs - link updates"
  docs/README.md
  docs/databases/sync-scan.md
  docs/developers-guide/start.md
  docs/embedding/static-embedding.md
  docs/installation-and-operation/installing-metabase.md
  docs/installation-and-operation/migrating-from-h2.md
  docs/people-and-groups/api-keys.md
  docs/troubleshooting-guide/loading-from-h2.md
Labels: was-backported

#51933 🤖 backported "Fix formatting of month-of-year when there are 53 weeks in the year"
  frontend/src/metabase/lib/time-dayjs.ts
  frontend/src/metabase/lib/time-dayjs.unit.spec.ts
  frontend/src/metabase/lib/time.ts
  frontend/test/metabase/lib/time.unit.spec.js
Labels: was-backported

#51765 New deactivated_at field on users
  resources/migrations/001_update_migrations.yaml
  src/metabase/models/user.clj
  test/metabase/models/user_test.clj
Labels: no-backport, .Team/AdminWebapp

#51886 Setting alignment to top for icons in subscription and alert emails
  src/metabase/email/alert.hbs
  src/metabase/email/dashboard_subscription.hbs
Labels: backport, .Team/DashViz

#51935 🤖 backported "Setting alignment to top for icons in subscription and alert emails"
  src/metabase/email/alert.hbs
  src/metabase/email/dashboard_subscription.hbs
Labels: was-backported

#51840 Correct docstring for series
  src/metabase/api/card.clj
Labels: backport

#51939 🤖 backported "Correct docstring for series"
  src/metabase/api/card.clj
Labels: was-backported

#51880 Dont escape chars of header dashcards
  src/metabase/notification/payload/execute.clj
Labels: backport, .Team/DashViz

#51947 🤦 Fix re-run ci job
  .github/workflows/rerun-workflows.yml
Labels: .CI & Tests, no-backport, .Team/AdminWebapp

#51913 Remove `entity.ListLoader` from `SearchResults`
  frontend/src/metabase/query_builder/components/DataSelector/data-search/SearchResults.jsx
Labels: no-backport, .Team/Querying

#51903 chore(qb): cleanup unused code
  frontend/src/metabase-types/store/mocks/qb.ts
  frontend/src/metabase-types/store/qb.ts
  frontend/src/metabase/query_builder/actions/ui.ts
  frontend/src/metabase/query_builder/components/view/View/View/View.jsx
  frontend/src/metabase/query_builder/components/view/View/ViewLeftSidebarContainer/ViewLeftSidebarContainer.jsx
  frontend/src/metabase/query_builder/components/view/View/ViewLeftSidebarContainer/index.ts
  frontend/src/metabase/query_builder/defaults.ts
  frontend/src/metabase/query_builder/reducers.js
  frontend/src/metabase/query_builder/selectors.js
Labels: no-backport, .Team/Querying

#51636 🤖 backported "feat(sdk): make editable dashboard grid border color themeable"
  docs/embedding/sdk/appearance.md
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/EditableDashboard.stories.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion-themed.stories.tsx
  enterprise/frontend/src/embedding-sdk/test/storybook-dark-theme.ts
  enterprise/frontend/src/embedding-sdk/types/theme/index.ts
  frontend/src/metabase/dashboard/components/grid/GridLayout.jsx
  frontend/src/metabase/dashboard/components/grid/utils.js
Labels: was-backported

#51958 Remove `entity.ListLoader` from `CollectionItemsTable` - approach v3
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase-types/api/search.ts
  frontend/src/metabase/collections/components/CollectionContent/CollectionItemsTable.tsx
  frontend/src/metabase/collections/components/ModelUploadModal.tsx
  frontend/src/metabase/collections/components/utils.ts
  frontend/src/metabase/entities/containers/rtk-query/EntityListLoaderRtkQuery.tsx
Labels: no-backport, .Team/Querying

#51944 Only push OSS Dot-x git tags
  .github/workflows/release-tag.yml
Labels: .Building & Releasing, no-backport, .Team/AdminWebapp

#51743 [Cards in Dashboards] Fix focus getting lost in nested Save question modals
  e2e/test/scenarios/question/saved.cy.spec.js
  frontend/src/metabase/collections/containers/FormCollectionAndDashboardPicker/FormCollectionAndDashboardPicker.tsx
  frontend/src/metabase/components/SaveQuestionForm/SaveQuestionForm.tsx
Labels: no-backport, .Team/AdminWebapp

#51580 🤖 backported "Show errors from backend in Create API key modal"
  e2e/support/helpers/e2e-api-key-helpers.ts
  e2e/support/helpers/e2e-ui-elements-helpers.js
  e2e/support/helpers/index.ts
  e2e/test/scenarios/admin-2/api-keys.cy.spec.ts
  frontend/src/metabase-types/api/admin.ts
  frontend/src/metabase/admin/settings/components/ApiKeys/CreateApiKeyModal.tsx
  frontend/src/metabase/forms/components/FormGroupWidget/FormGroupWidget.tsx
  frontend/src/metabase/forms/components/FormTextInput/FormTextInput.tsx
Labels: was-backported

#50390 🤖 backported "add capability for sending bug reports"
  frontend/src/metabase-types/api/bug-report.ts
  frontend/src/metabase-types/api/index.ts
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/mocks/slack.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase-types/api/slack.ts
  frontend/src/metabase/admin/settings/slack/components/SlackForm/SlackForm.tsx
  frontend/src/metabase/admin/settings/slack/components/SlackSetupForm/SlackSetupForm.tsx
  frontend/src/metabase/admin/settings/slack/selectors.ts
  frontend/src/metabase/api/bug-report.ts
  frontend/src/metabase/api/index.ts
  frontend/src/metabase/components/ErrorPages/ErrorDiagnosticModal.tsx
  frontend/src/metabase/components/ErrorPages/ErrorDiagnosticModal.unit.spec.tsx
  src/metabase/api/slack.clj
  src/metabase/integrations/slack.clj
  src/metabase/public_settings.clj
Labels: was-backported

#51966 Add Filip to slack map
  release/github-slack-map.json
Labels: .CI & Tests, no-backport, .Team/AdminWebapp

#51965 make flaky job detection case-insensitive
  .github/workflows/rerun-workflows.yml
Labels: .CI & Tests, no-backport, .Team/AdminWebapp

#51325 🤖 backported "fix(sdk): Fix alignment of ColorSelector in SDK Chart Settings"
  e2e/test/scenarios/visualizations-tabular/table.cy.spec.js
  frontend/src/metabase/core/components/ColorPicker/ColorPickerTrigger.tsx
  frontend/src/metabase/core/components/ColorPill/ColorPill.module.css
  frontend/src/metabase/core/components/ColorPill/ColorPill.stories.tsx
  frontend/src/metabase/core/components/ColorPill/ColorPill.styled.tsx
  frontend/src/metabase/core/components/ColorPill/ColorPill.tsx
  frontend/src/metabase/core/components/ColorPill/index.ts
  frontend/src/metabase/core/components/ColorRangeSelector/ColorRangePopover.tsx
  frontend/src/metabase/core/components/ColorSelector/ColorSelector.stories.tsx
  frontend/src/metabase/core/components/ColorSelector/ColorSelector.tsx
  frontend/src/metabase/core/components/ColorSelector/ColorSelector.unit.spec.tsx
  frontend/src/metabase/core/components/ColorSelector/ColorSelectorPopover.tsx
  frontend/src/metabase/core/components/ColorSelector/index.ts
  frontend/src/metabase/visualizations/components/settings/ChartNestedSettingSeriesMultiple.jsx
  frontend/src/metabase/visualizations/components/settings/ChartNestedSettingSeriesSingle.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingColorPicker/ChartSettingColorPicker.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingGaugeSegments.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingSeriesOrder.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting.jsx
Labels: was-backported

#51841 🤖 backported "Convert aggregation order-bys to reference by index instead of uuid before hashing"
  src/metabase/lib/schema/util.cljc
  src/metabase/query_processor/util.clj
  test/metabase/query_processor/util_test.clj
Labels: was-backported

#51940 docs: H1 edits
  docs/configuring-metabase/email.md
  docs/configuring-metabase/slack.md
  docs/dashboards/interactive.md
  docs/databases/ssl-certificates.md
  docs/developers-guide/drivers/driver-tests.md
  docs/developers-guide/internationalization.md
  docs/embedding/sdk/collections.md
  docs/embedding/sdk/dashboards.md
  docs/questions/visualizations/pivot-table.md
  docs/questions/visualizations/visualizing-results.md
  docs/troubleshooting-guide/docker.md
  docs/troubleshooting-guide/ldap.md
  docs/troubleshooting-guide/running.md
Labels: Type:Documentation, backport

#51975 🤖 backported "docs: H1 edits"
  docs/configuring-metabase/email.md
  docs/configuring-metabase/slack.md
  docs/dashboards/interactive.md
  docs/databases/ssl-certificates.md
  docs/developers-guide/drivers/driver-tests.md
  docs/developers-guide/internationalization.md
  docs/embedding/sdk/collections.md
  docs/embedding/sdk/dashboards.md
  docs/questions/sharing/visualizations/pivot-table.md
  docs/questions/sharing/visualizing-results.md
  docs/troubleshooting-guide/docker.md
  docs/troubleshooting-guide/ldap.md
  docs/troubleshooting-guide/running.md
Labels: was-backported

#51807 Fix quick-filter drill thru for multi-stage queries
  src/metabase/lib/drill_thru/quick_filter.cljc
  test/metabase/lib/drill_thru/quick_filter_test.cljc
  test/metabase/lib/drill_thru/test_util.cljc
  test/metabase/lib/drill_thru/test_util/canned.cljc
  test/metabase/lib/drill_thru_test.cljc
Labels: backport, .Team/Querying

#51893 allow disabling table pivot when new columns were added
  frontend/src/metabase/visualizations/visualizations/Table.tsx
  frontend/src/metabase/visualizations/visualizations/Table.unit.spec.js
Labels: backport, .Team/DashViz

#51745 [Cards in Dashboards] Allow creating dashboards from entity picker
  e2e/support/helpers/e2e-collection-helpers.ts
  e2e/test/scenarios/dashboard/dashboard-management.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/native/snippets.cy.spec.js
  e2e/test/scenarios/question/new.cy.spec.js
  e2e/test/scenarios/question/question-management.cy.spec.js
  e2e/test/scenarios/question/saved.cy.spec.js
  frontend/src/metabase/common/components/CollectionPicker/components/CollectionPicker.tsx
  frontend/src/metabase/common/components/CollectionPicker/components/CollectionPickerModal.tsx
  frontend/src/metabase/common/components/DashboardPicker/components/DashboardPicker.tsx
  frontend/src/metabase/common/components/DashboardPicker/components/DashboardPickerModal.tsx
  frontend/src/metabase/common/components/DashboardPicker/components/NewDashboardDialog.tsx
  frontend/src/metabase/common/components/DashboardPicker/utils.ts
  frontend/src/metabase/common/components/EntityPicker/components/EntityPickerModal/ButtonBar.tsx
  frontend/src/metabase/containers/AddToDashSelectDashModal/AddToDashSelectDashModal.unit.spec.tsx
  frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.unit.spec.tsx
Labels: no-backport, .Team/AdminWebapp

#51980 🤖 backported "Fix quick-filter drill thru for multi-stage queries"
  src/metabase/lib/drill_thru/quick_filter.cljc
  test/metabase/lib/drill_thru/quick_filter_test.cljc
  test/metabase/lib/drill_thru/test_util.cljc
  test/metabase/lib/drill_thru/test_util/canned.cljc
  test/metabase/lib/drill_thru_test.cljc
Labels: was-backported

#51964 Remove the custom `--folder` flag when running Cypress
  docs/developers-guide/e2e-tests.md
  e2e/runner/cypress-runner-run-tests.js
  e2e/runner/cypress-runner-utils.js
Labels: no-backport

#51984 🤖 backported "Fix quick-filter drill thru for multi-stage queries"
  src/metabase/lib/drill_thru/quick_filter.cljc
  test/metabase/lib/drill_thru/quick_filter_test.cljc
  test/metabase/lib/drill_thru/test_util.cljc
  test/metabase/lib/drill_thru/test_util/canned.cljc
  test/metabase/lib/drill_thru_test.cljc
Labels: was-backported

#51981 🤖 backported "allow disabling table pivot when new columns were added"
  frontend/src/metabase/visualizations/visualizations/Table.tsx
  frontend/src/metabase/visualizations/visualizations/Table.unit.spec.js
Labels: was-backported

#51951 fix pivot table is not rendered until resized
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.ts
  frontend/src/metabase/components/ExplicitSize/ExplicitSize.tsx
Labels: backport, .Team/DashViz

#51990 🤖 backported "fix pivot table is not rendered until resized"
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.ts
  frontend/src/metabase/components/ExplicitSize/ExplicitSize.tsx
Labels: was-backported

#51993 🤖 backported "Fix zoom-in.geographic drill thru for multi-stage queries"
  src/metabase/lib/drill_thru/zoom_in_geographic.cljc
  src/metabase/lib/drill_thru/zoom_in_timeseries.cljc
  src/metabase/lib/underlying.cljc
  test/metabase/lib/drill_thru/test_util.cljc
  test/metabase/lib/drill_thru/zoom_in_geographic_test.cljc
Labels: was-backported

#51998 🤖 backported "Fix zoom-in.geographic drill thru for multi-stage queries"
  src/metabase/lib/drill_thru/zoom_in_geographic.cljc
  src/metabase/lib/drill_thru/zoom_in_timeseries.cljc
  src/metabase/lib/underlying.cljc
  test/metabase/lib/drill_thru/test_util.cljc
  test/metabase/lib/drill_thru/zoom_in_geographic_test.cljc
Labels: was-backported

#51977 🤖 backported "Fix ChartSettingsPopover style/z-index issues"
  e2e/support/helpers/e2e-viz-settings-helpers.js
  e2e/test/scenarios/visualizations-charts/maps.cy.spec.js
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.js
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.ts
  e2e/test/scenarios/visualizations-charts/waterfall.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/pivot_tables.cy.spec.js
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/QuestionSettings/QuestionSettings.stories.tsx
  frontend/src/metabase/css/core/overflow.module.css
  frontend/src/metabase/visualizations/components/ChartSettings/BaseChartSettings/BaseChartSettings.tsx
  frontend/src/metabase/visualizations/components/ChartSettingsWidget.styled.tsx
  frontend/src/metabase/visualizations/components/ChartSettingsWidget.tsx
  frontend/src/metabase/visualizations/components/ChartSettingsWidgetPopover.styled.tsx
  frontend/src/metabase/visualizations/components/ChartSettingsWidgetPopover.tsx
  frontend/src/metabase/visualizations/components/ChartSettingsWidgetPopover.unit.spec.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldPicker.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldPicker.unit.spec.js
  frontend/src/metabase/visualizations/components/settings/ChartSettingSelect.jsx
Labels: was-backported

#51953 allow changing x-axis column settings
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.ts
  frontend/src/metabase/visualizations/lib/settings/graph.js
Labels: backport, .Team/DashViz

#51978 🤖 backported "Convert ChartsettingOrderedItems to match ChartSettingSelect"
  e2e/support/helpers/e2e-viz-settings-helpers.js
  e2e/test/scenarios/binning/binning-reproductions.cy.spec.js
  e2e/test/scenarios/native/native-reproductions.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
  e2e/test/scenarios/permissions/sandboxes.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions-1.cy.spec.js
  e2e/test/scenarios/question/settings.cy.spec.js
  e2e/test/scenarios/visualizations-charts/bar_chart.cy.spec.js
  e2e/test/scenarios/visualizations-charts/funnel.cy.spec.js
  e2e/test/scenarios/visualizations-charts/pie_chart.cy.spec.js
  e2e/test/scenarios/visualizations-charts/trendline.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/pivot_tables.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/visualizations-tabular-reproductions.cy.spec.js
  frontend/src/metabase/core/components/Sortable/Sortable.tsx
  frontend/src/metabase/css/core/base.module.css
  frontend/src/metabase/visualizations/components/settings/ChartSettingActionIcon.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingOrderedSimple.styled.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingOrderedSimple.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingSeriesOrder.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingTableColumns/TableColumnPanel/TableColumnPanel.tsx
  frontend/src/metabase/visualizations/components/settings/ColumnItem/ColumnItem.module.css
  frontend/src/metabase/visualizations/components/settings/ColumnItem/ColumnItem.styled.tsx
  frontend/src/metabase/visualizations/components/settings/ColumnItem/ColumnItem.tsx
Labels: was-backported

#51872 New command to generate static `index.html` page for OpenAPI/Scalar API documentation
  deps.edn
  docs/api.html
  resources/openapi/index_inline.html.mustache
  src/metabase/api/common/openapi.clj
  src/metabase/api/docs.clj
  src/metabase/cmd.clj
  src/metabase/cmd/endpoint_dox.clj
  test/metabase/cmd/endpoint_dox_test.clj
Labels: no-backport, .Team/DevEx

#52005 🤖 backported "allow changing x-axis column settings"
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.ts
  frontend/src/metabase/visualizations/lib/settings/graph.js
Labels: was-backported

#51973 Fix parameter mappings reset logic
  e2e/test/scenarios/native/native-reproductions.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
  e2e/test/scenarios/native/native_subquery.cy.spec.js
  frontend/src/metabase/dashboard/actions/parameters.ts
  frontend/src/metabase/dashboard/actions/parameters.unit.spec.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.unit.spec.jsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/hooks.ts
Labels: backport, .Team/Querying

#52009 🤖 backported "Fix parameter mappings reset logic"
  e2e/test/scenarios/native/native-reproductions.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
  e2e/test/scenarios/native/native_subquery.cy.spec.js
  frontend/src/metabase/dashboard/actions/parameters.ts
  frontend/src/metabase/dashboard/actions/parameters.unit.spec.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapper.unit.spec.jsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/hooks.ts
Labels: was-backported

#51708 [Notification] reduce memory footprint
  dev/src/dev.clj
  dev/src/dev/memory.clj
  src/metabase/channel/impl/email.clj
  src/metabase/channel/impl/http.clj
  src/metabase/channel/impl/slack.clj
  src/metabase/channel/shared.clj
  src/metabase/email/result_attachment.clj
  src/metabase/notification/payload/execute.clj
  src/metabase/notification/payload/temp_storage.clj
  test/metabase/dashboard_subscription_test.clj
  test/metabase/models/permissions_group_test.clj
  test/metabase/notification/payload/temp_storage_test.clj
  test/metabase/pulse/pulse_integration_test.clj
Labels: backport, .Team/Workflows

#52011 🤖 backported "[Notification] reduce memory footprint"
  dev/src/dev.clj
  dev/src/dev/memory.clj
  src/metabase/channel/impl/email.clj
  src/metabase/channel/impl/http.clj
  src/metabase/channel/impl/slack.clj
  src/metabase/channel/shared.clj
  src/metabase/email/result_attachment.clj
  src/metabase/notification/payload/execute.clj
  src/metabase/notification/payload/temp_storage.clj
  test/metabase/dashboard_subscription_test.clj
  test/metabase/models/permissions_group_test.clj
  test/metabase/notification/payload/temp_storage_test.clj
  test/metabase/pulse/pulse_integration_test.clj
Labels: was-backported

#52016 docs(sdk): Update SDK version to 0.53.1-nightly
  enterprise/frontend/src/embedding-sdk/CHANGELOG.md
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: no-backport

#51899 Ensure with-dynamic-redefs is only used with functions
  enterprise/backend/test/metabase_enterprise/serialization/api_test.clj
  enterprise/backend/test/metabase_enterprise/task/cache_test.clj
  enterprise/backend/test/metabase_enterprise/upload_management/api_test.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/search_test.clj
  test/metabase/cmd/dump_to_h2_test.clj
  test/metabase/events/notification_test.clj
  test/metabase/models/card_test.clj
  test/metabase/models/dashboard_test.clj
  test/metabase/models/database_test.clj
  test/metabase/models/params/chain_filter_test.clj
  test/metabase/models/search_index_metadata_test.clj
  test/metabase/notification/send_test.clj
  test/metabase/query_analysis_test.clj
  test/metabase/search/appdb/index_test.clj
  test/metabase/search/appdb/scoring_test.clj
  test/metabase/test.clj
  test/metabase/test/util/dynamic_redefs.clj
  test/metabase/test/util_test.clj
  test/metabase/upload_test.clj
  test/metabase/util/malli/defn_test.clj
  test/metabase/util/malli/fn_test.clj
Labels: no-backport, .Team/Workflows

#52017 Add trace logging for search index queue, and fix timer
  src/metabase/search/core.clj
  src/metabase/search/ingestion.clj
  src/metabase/task/search_index.clj
Labels: backport, .Team/Workflows

#52021 🤖 backported "Add trace logging for search index queue, and fix timer"
  src/metabase/search/core.clj
  src/metabase/search/ingestion.clj
  src/metabase/task/search_index.clj
Labels: was-backported

#52015 Fix SDK release process failure
  .github/workflows/release-embedding-sdk.yml
Labels: backport, .Team/Embedding

#52022 🤖 backported "Fix SDK release process failure"
  .github/workflows/release-embedding-sdk.yml
Labels: was-backported

#52018 Enable realtime search indexing without experimental flag
  src/metabase/models.clj
Labels: backport, .Team/Workflows

#52025 🤖 backported "Enable realtime search indexing without experimental flag"
  src/metabase/models.clj
Labels: was-backported

#51662 Properly report unknown users from create-dashboard-subscription
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/create_dashboard_subscription.clj
Labels: Metabot/General, no-backport

#52026 Add sanex3339 to team files
  .github/team.json
  release/github-slack-map.json
Labels: .CI & Tests, no-backport, .Team/Embedding

#52024 🤖 backported "Add Code component from Mantine"
  frontend/src/metabase/ui/components/typography/Code/Code.stories.tsx
  frontend/src/metabase/ui/components/typography/Code/Code.styled.tsx
  frontend/src/metabase/ui/components/typography/Code/index.ts
  frontend/src/metabase/ui/components/typography/index.ts
  frontend/src/metabase/ui/theme.ts
Labels: was-backported

#52036 docs: static embedding typo
  docs/embedding/static-embedding.md
Labels: Type:Documentation, backport
