Repository metabase/metabase, pull requests merged in 2025-10, with the labels that each got.

#64082 Do not show error when loading
  frontend/src/metabase/query_builder/components/VisualizationResult.jsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.unit.spec.js
Labels: no-backport, .Team/Querying

#64241 Do not run transform test in postgres mysql
  .github/workflows/drivers.yml
Labels: no-backport, .Team/Workflows

#64077 Add context to Save verb and fix similar translation issues
  frontend/src/metabase/admin/upsells/UpsellUploads.tsx
  frontend/src/metabase/databases/components/DatabaseForm/DatabaseFormFooter.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/AddDataModal/Panels/AddDataModalEmptyStates.tsx
  frontend/src/metabase/setup/components/DatabaseStep/DatabaseStep.tsx
  frontend/src/metabase/visualizations/click-actions/actions/NativeQueryClickFallback.tsx
Labels: backport, .Team/Querying

#64233 Hide the python runner settings for cloud instances
  enterprise/frontend/src/metabase-enterprise/transforms-python/pages/PythonRunnerSettingsPage/PythonRunnerSettingsPage.tsx
  frontend/src/metabase/admin/settings/components/SettingsNav/SettingsNav.tsx
Labels: no-backport, .Team/Workflows

#64273 Update table editing e2e tests to not add or remove rows in Sample Database
  e2e/test/scenarios/table-editing/table-editing.cy.spec.ts
Labels: no-backport, .Team/Workflows, .Team/UXEast

#64261 Auto-update documentation for release-x.56.x
  docs/api.html
Labels: Type:Documentation, no-backport

#64267 tests: wait for data in a flaky test
  e2e/test/scenarios/question/notebook-data-source.cy.spec.ts
Labels: backport, .Team/Workflows

#64278 🤖 backported "tests: wait for data in a flaky test"
  e2e/test/scenarios/question/notebook-data-source.cy.spec.ts
Labels: was-backported

#64284 docs: serializing new entities
  docs/installation-and-operation/serialization.md
Labels: Type:Documentation, no-backport

#63256 Show full timestamp for revision history entries on hover
  frontend/src/metabase/common/components/Timeline/Timeline.tsx
Labels: backport

#64145 🤖 backported "[perf] Optimize metabase.lib.field.resolution/merge-metadata"
  src/metabase/lib/field/resolution.cljc
  src/metabase/util/performance.cljc
  src/metabase/util/snake_hating_map.clj
Labels: was-backported

#64129 🤖 backported "[match] Prevent match-lite from extracting common result that depends on uncommon bindings"
  src/metabase/lib/fe_util.cljc
  src/metabase/lib/filter.cljc
  src/metabase/lib/remove_replace.cljc
  src/metabase/lib/util/match.clj
  test/metabase/lib/util/match_test.cljc
Labels: was-backported

#64298 🤖 backported "docs: uploads to clickhouse cloud"
  docs/databases/uploads.md
Labels: was-backported

#64299 docs: don't overhype interactive embedding
  docs/embedding/embedded-analytics-js.md
  docs/embedding/interactive-embedding.md
Labels: Type:Documentation, backport

#64266 Remove skipped dashboard toast e2e tests
  e2e/test/scenarios/dashboard-filters/dashboard-filters-auto-apply.cy.spec.js
Labels: .CI & Tests, no-backport

#64200 🤖 backported "Fix #63904: Corrects dashcard selector usage"
  frontend/src/metabase/dashboard/actions/cards-typed.ts
  frontend/src/metabase/dashboard/actions/parameters.tsx
  frontend/src/metabase/dashboard/selectors.ts
  frontend/src/metabase/dashboard/selectors.unit.spec.js
  frontend/src/metabase/parameters/components/ParameterSettings/MoveParameterMenu/MoveParameterMenu.tsx
  frontend/src/metabase/parameters/components/ParameterSettings/MoveParameterMenu/MoveParameterMenu.unit.spec.tsx
Labels: was-backported

#64287 Handful of fixes for transforms search
  enterprise/backend/src/metabase_enterprise/metabot_v3/context.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/api.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/search.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/tools/search_test.clj
  enterprise/frontend/src/metabase-enterprise/metabot/components/MetabotChat/hooks.ts
Labels: .Team/Metabot

#64132 Better error handling when sync-tracking-atoms fails
  src/metabase/search/appdb/index.clj
Labels: backport, .Team/UXWest

#64258 Update the list of source tables in Python editor when metabot changes it
  enterprise/frontend/src/metabase-enterprise/transforms-python/components/PythonTransformEditor/PythonDataPicker/PythonDataPicker.tsx
  enterprise/frontend/src/metabase-enterprise/transforms-python/components/PythonTransformEditor/PythonTransformEditor.tsx
Labels: .Team/Metabot

#64310 🤖 backported "Better error handling when sync-tracking-atoms fails"
  src/metabase/search/appdb/index.clj
Labels: was-backported

#64309 Log errors in downgrades
  src/metabase/app_db/liquibase.clj
Labels: backport

#64312 🤖 backported "Log errors in downgrades"
  src/metabase/app_db/liquibase.clj
Labels: was-backported

#64268 🤖 backported "Add context to Save verb and fix similar translation issues"
  frontend/src/metabase/admin/upsells/UpsellUploads.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/AddDataModal/Panels/AddDataModalEmptyStates.tsx
  frontend/src/metabase/setup/components/DatabaseStep/DatabaseStep.tsx
  frontend/src/metabase/visualizations/click-actions/actions/NativeQueryClickFallback.tsx
Labels: was-backported

#64274 Adjust sample apps e2e setup
  e2e/runner/embedding-sdk/sample-apps/constants/sample-app-setup-configs.js
  e2e/runner/embedding-sdk/sample-apps/helpers/copy-shoppy-metabase-app-db-dump.ts
Labels: .CI & Tests, no-backport, .Team/Embedding

#64187 feat(sdk-bundle): Add EditableParameters component for InteractiveQuestion and StaticQuestion
  e2e/test-component/scenarios/embedding-sdk/sdk-question-native.cy.spec.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkQuestion/components/SqlParametersList/SqlParametersList.module.css
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkQuestion/components/SqlParametersList/SqlParametersList.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkQuestion/components/SqlParametersList/index.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkQuestion/components/index.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkQuestion/context/SdkQuestionProvider.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkQuestion/context/types.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/InteractiveQuestion/InteractiveQuestion.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/InteractiveQuestion/InteractiveQuestion.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/public/SdkQuestion/SdkQuestion.stories.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/public/SdkQuestion/SdkQuestion.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/public/SdkQuestion/data/data.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/StaticQuestion/StaticQuestion.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/StaticQuestion/StaticQuestion.tsx
  enterprise/frontend/src/embedding-sdk-bundle/hooks/private/use-load-question.ts
  enterprise/frontend/src/embedding-sdk-bundle/lib/sdk-question/load-question.ts
  enterprise/frontend/src/embedding-sdk-bundle/lib/sdk-question/update-question.ts
  enterprise/frontend/src/embedding-sdk-bundle/types/question.ts
  enterprise/frontend/src/embedding-sdk-package/components/public/InteractiveQuestion/InteractiveQuestion.tsx
  enterprise/frontend/src/embedding-sdk-package/components/public/StaticQuestion/StaticQuestion.tsx
  frontend/src/metabase/parameters/components/ParameterWidget/ParameterWidget.tsx
  frontend/src/metabase/parameters/components/widgets/TextWidget/TextWidget.tsx
  frontend/src/metabase/parameters/components/widgets/TextWidget/TextWidget.unit.spec.tsx
  frontend/src/metabase/public/lib/types.ts
  frontend/src/metabase/query_builder/components/ResponsiveParametersList.tsx
  frontend/src/metabase/query_builder/components/SyncedParametersList.tsx
Labels: no-backport, .Team/Embedding, Embedding/SDK, release-notes

#64039 WRK-903 Update command palette modal
  e2e/support/helpers/e2e-command-palette-helpers.js
  e2e/support/helpers/e2e-metabot-helpers.ts
  e2e/test/scenarios/admin/datamodel/reproductions.cy.spec.ts
  e2e/test/scenarios/dashboard/dashboard-questions.cy.spec.js
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/metabot/metabot.cy.spec.ts
  e2e/test/scenarios/onboarding/command-palette.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/metabot/index.tsx
  frontend/src/metabase-types/api/search.ts
  frontend/src/metabase/palette/components/Palette.module.css
  frontend/src/metabase/palette/components/Palette.styled.tsx
  frontend/src/metabase/palette/components/Palette.tsx
  frontend/src/metabase/palette/components/PaletteFooter.tsx
  frontend/src/metabase/palette/components/PaletteResultItem.tsx
  frontend/src/metabase/palette/components/PaletteResultItem.unit.spec.tsx
  frontend/src/metabase/palette/components/PaletteResults.tsx
  frontend/src/metabase/palette/components/PaletteResultsList.tsx
  frontend/src/metabase/palette/components/test/PaletteResults/PaletteResults-ee.unit.spec.tsx
  frontend/src/metabase/palette/components/test/PaletteResults/PaletteResults-oss.unit.spec.tsx
  frontend/src/metabase/palette/components/test/PaletteResults/setup.tsx
  frontend/src/metabase/palette/hooks/useCommandPalette.tsx
  frontend/src/metabase/palette/utils.ts
  frontend/src/metabase/palette/utils.unit.spec.ts
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/ui/components/icons/Icon/icons/table.svg
Labels: no-backport, .Team/Workflows, PR-Env, .Team/UXEast

#64291 Fix formatting for `mt/native-query`
  .cljfmt.edn
  enterprise/backend/test/metabase_enterprise/advanced_permissions/models/permissions/block_permissions_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/field_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/query_processor/middleware/sandboxing_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/extract_test.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/params_test.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk/query_processor_test.clj
  modules/drivers/clickhouse/test/metabase/driver/clickhouse_test.clj
  modules/drivers/oracle/test/metabase/driver/oracle_test.clj
  test/metabase/actions/actions_test.clj
  test/metabase/dashboards/api_test.clj
  test/metabase/driver/common/parameters/values_test.clj
  test/metabase/driver/mysql_test.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/embedding/api/embed_test.clj
  test/metabase/embedding/api/preview_embed_test.clj
  test/metabase/indexed_entities/models/model_index_test.clj
  test/metabase/pulse/dashboard_subscription_test.clj
  test/metabase/query_processor/dashboard_test.clj
  test/metabase/query_processor/middleware/parameters/native_test.clj
  test/metabase/query_processor/middleware/parameters_test.clj
  test/metabase/query_processor/middleware/permissions_test.clj
  test/metabase/query_processor/parameters/temporal_units_test.clj
  test/metabase/query_processor_test/alternative_date_test.clj
  test/metabase/query_processor_test/native_test.clj
  test/metabase/query_processor_test/nested_queries_test.clj
  test/metabase/query_processor_test/parameters_test.clj
  test/metabase/query_processor_test/persistence_test.clj
  test/metabase/query_processor_test/uuid_test.clj
Labels: no-backport, .Team/DevEx

#64238 fix(sdk): Allow token without`exp`, but raise a warning
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkUsageProblem/SdkUsageProblemBanner.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkUsageProblem/SdkUsageProblemDisplay-simple-embedding.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkUsageProblem/SdkUsageProblemDisplay.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkUsageProblem/index.tsx
  enterprise/frontend/src/embedding-sdk-bundle/hooks/private/use-sdk-usage-problem.ts
  enterprise/frontend/src/embedding-sdk-bundle/lib/usage-problem.ts
  enterprise/frontend/src/embedding-sdk-bundle/store/auth/auth.ts
  enterprise/frontend/src/embedding-sdk-bundle/store/reducer.ts
  enterprise/frontend/src/embedding-sdk-bundle/test/auth-flow/jwt.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk-bundle/test/mocks/state.ts
  enterprise/frontend/src/embedding-sdk-bundle/types/refresh-token.ts
  enterprise/frontend/src/embedding/auth-common/index.ts
  enterprise/frontend/src/embedding/auth-common/validate-session-token.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/embed.ts
Labels: backport, .Team/Embedding

#64063 QP result metadata should always populate `:lib/desired-column-alias`
  src/metabase/lib/field/util.cljc
  src/metabase/lib/metadata/result_metadata.cljc
  src/metabase/lib/schema/metadata.cljc
  src/metabase/lib/table.cljc
  test/metabase/lib/metadata/result_metadata_test.cljc
  test/metabase/lib/remove_replace_test.cljc
  test/metabase/lib/table_test.cljc
  test/metabase/lib/test_util/matrix.cljc
Labels: no-backport, .Team/DevEx

#64314 🤖 backported "fix(modular): links and type/URL columns should be rendered as clickable"
  e2e/test-component/scenarios/embedding-sdk/dashboard-click-behavior.cy.spec.tsx
  frontend/src/metabase/lib/formatting/url.tsx
Labels: was-backported

#64283 Move SmartScalar subcomponents to separate files
  frontend/src/metabase/visualizations/visualizations/SmartScalar/PreviousValueComparison.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/ScalarPeriod.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/Separator.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.tsx
Labels: no-backport, .Team/Workflows, .Team/UXEast

#64236 Mage run tests via nrepl
  CLAUDE.md
  bb.edn
  dev/src/dev/reload.clj
  mage/mage/be_dev.clj
  mage/mage/cli.clj
  mage/mage/util.clj
Labels: no-backport, .Team/Workflows

#64242 Closes EMB-854 escape single quotes in embed code snippets
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/utils/embed-snippet.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/utils/embed-snippet.unit.spec.ts
Labels: backport, .Team/Embedding

#64322 🤖 backported "Closes EMB-854 escape single quotes in embed code snippets"
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/utils/embed-snippet.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/utils/embed-snippet.unit.spec.ts
Labels: was-backported

#64292 Hide the step number circle in the setup flow when we only have one step
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.ts
  frontend/src/metabase/setup/components/ActiveStep/ActiveStep.tsx
  frontend/src/metabase/setup/selectors.ts
Labels: no-backport, .Team/Embedding

#62616 fix: validate ldap server email before save
  .clj-kondo/config/modules/config.edn
  enterprise/backend/src/metabase_enterprise/scim/v2/api.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/ldap.clj
  src/metabase/sso/core.clj
  src/metabase/sso/google.clj
  src/metabase/sso/ldap/default_implementation.clj
  src/metabase/users/api.clj
  src/metabase/users/core.clj
  src/metabase/users/models/user.clj
  src/metabase/users/schema.clj
  test/metabase/sso/ldap/default_implementation_test.clj
  test/metabase/users/models/user_test.clj
Labels: double-backport, .Team/UXWest

#64326 chore: Remove unused column-level middleware
  enterprise/backend/src/metabase_enterprise/sandbox/query_processor/middleware/column_level_perms_check.clj
  src/metabase/permissions/models/permissions.clj
  src/metabase/query_processor/execute.clj
  src/metabase/query_processor/middleware/enterprise.clj
Labels: no-backport, .Team/UXWest

#64331 🤖 backported "fix: validate ldap server email before save"
  .clj-kondo/config/modules/config.edn
  enterprise/backend/src/metabase_enterprise/scim/v2/api.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/ldap.clj
  src/metabase/sso/core.clj
  src/metabase/sso/google.clj
  src/metabase/sso/ldap/default_implementation.clj
  src/metabase/users/api.clj
  src/metabase/users/core.clj
  src/metabase/users/models/user.clj
  src/metabase/users/schema.clj
  test/metabase/sso/ldap/default_implementation_test.clj
  test/metabase/users/models/user_test.clj
Labels: was-backported

#64265 Show 'See it' link next to 'Saved' button after x-ray is saved as dashboard
  e2e/test/scenarios/dashboard/x-rays.cy.spec.js
  frontend/src/metabase/dashboard/containers/AutomaticDashboardApp/AutomaticDashboardApp.tsx
  frontend/src/metabase/dashboard/containers/AutomaticDashboardApp/AutomaticDashboardApp.unit.spec.tsx
  frontend/test/__support__/server-mocks/dashboard.ts
Labels: no-backport, .Team/ProductGrowth

#64336 [METABOT] Use `limit` in final search response
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/search.clj
Labels: backport, .Team/Metabot

#64338 🤖 backported "docs - notes on Metabot feedback"
  docs/ai/metabot.md
  docs/ai/settings.md
Labels: was-backported

#64339 🤖 backported "docs - notes on Metabot feedback"
  docs/ai/metabot.md
  docs/ai/settings.md
Labels: was-backported

#64343 🤖 backported "[METABOT] Use `limit` in final search response"
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/search.clj
Labels: was-backported

#64247 Store transform create/updates in revision table
  enterprise/backend/src/metabase_enterprise/transforms/api.clj
  enterprise/backend/test/metabase_enterprise/transforms/api_test.clj
  enterprise/backend/test/metabase_enterprise/transforms/revision_test.clj
  src/metabase/revisions/events.clj
  src/metabase/revisions/impl/transform.clj
  src/metabase/revisions/init.clj
Labels: no-backport, .Team/Querying, .Team/Drivers, Querying/Transforms

#64342 [METABOT] Fix 404 in `get-table-details` helper
  enterprise/backend/src/metabase_enterprise/metabot_v3/dummy_tools.clj
Labels: backport, .Team/Metabot

#64346 🤖 backported "[METABOT] Fix 404 in `get-table-details` helper"
  enterprise/backend/src/metabase_enterprise/metabot_v3/dummy_tools.clj
Labels: was-backported

#64279 Update alignment and copy for embedding hub
  e2e/test/scenarios/embedding/embedding-hub/embedding-hub.cy.spec.ts
  frontend/src/metabase/admin/components/RelatedSettingsSection/RelatedSettingsSection.tsx
  frontend/src/metabase/embedding/embedding-hub/components/EmbeddingHub.unit.spec.tsx
  frontend/src/metabase/embedding/embedding-hub/components/StepperWithCards/StepperWithCards.module.css
  frontend/src/metabase/embedding/embedding-hub/components/StepperWithCards/StepperWithCards.tsx
  frontend/src/metabase/embedding/embedding-hub/utils/embedding-hub-steps.ts
Labels: no-backport, .Team/Embedding

#63973 Change embed flow tracking to track step completions for funnel analysis
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/embed-parameters.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/get-code.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/select-embed-entity.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/select-embed-experience.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/select-embed-options.cy.spec.ts
  e2e/test/scenarios/sharing/public-sharing-embed-flow.cy.spec.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/analytics.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/GetCodeStep.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/SdkIframeEmbedSetupProvider.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/SelectEmbedExperienceStep.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/SelectEmbedResourceStep.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/context.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/hooks/use-sdk-iframe-embed-navigation.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/utils/default-embed-setting.ts
  frontend/src/metabase-types/analytics/event.ts
Labels: backport, .Team/Embedding

#64288 Closes EMB-411 no more transparent cell background by default
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Dark_Theme_No_Background_Default.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_Dark_Theme_No_Background_Scroll.png
  .loki/reference/chrome_laptop_viz_Table_Dashboard_Table_Embedding_Theme_With_Dark_Background.png
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.tsx
  frontend/src/metabase/visualizations/components/TableInteractive/utils/table-theme-to-data-grid-theme.ts
  frontend/src/metabase/visualizations/components/TableInteractive/utils/table-theme-to-data-grid-theme.unit.spec.ts
  frontend/src/metabase/visualizations/visualizations/Table/Table.stories.tsx
Labels: backport, .Team/Embedding

#64367 🤖 backported "Enable copying of iframe cards"
  src/metabase/dashboards/api.clj
  test/metabase/dashboards/api_test.clj
Labels: was-backported

#63952 🤖 backported "Fix starbust query cancellation with isClosed proxy implementations"
  modules/drivers/sparksql/src/metabase/driver/sparksql.clj
  modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj
  modules/drivers/starburst/src/metabase/driver/starburst.clj
  modules/drivers/starburst/test/metabase/driver/starburst_test.clj
  src/metabase/driver.clj
  src/metabase/driver/sql_jdbc.clj
  src/metabase/driver/sql_jdbc/execute.clj
  test/metabase/driver/sql_jdbc/execute_test.clj
Labels: was-backported

#63334 chore: replace moment-timezone with dayjs for main app
  frontend/src/metabase-types/guards/settings.ts
  frontend/src/metabase/forms/components/FormDateInput/FormDateInput.tsx
  frontend/src/metabase/lib/dayjs-parse-zone-plugin.js
  frontend/src/metabase/lib/dayjs-parse-zone-plugin.unit.spec.js
  frontend/src/metabase/lib/dayjs.ts
  frontend/src/metabase/lib/formatting/date.tsx
  frontend/src/metabase/lib/formatting/link.ts
  frontend/src/metabase/lib/formatting/time.ts
  frontend/src/metabase/lib/formatting/value.tsx
  frontend/src/metabase/lib/i18n.js
  frontend/src/metabase/lib/i18n.unit.spec.ts
  frontend/src/metabase/lib/time-dayjs.ts
  frontend/src/metabase/lib/time-dayjs.unit.spec.ts
  frontend/src/metabase/lib/time.ts
  frontend/src/metabase/query_builder/selectors.js
  frontend/test/metabase/lib/formatting.unit.spec.js
  frontend/test/metabase/lib/time.unit.spec.js
  package.json
  yarn.lock
Labels: no-backport, .Team/Workflows

#64378 Replace and remove the deprecated `space` utility
  frontend/src/metabase/account/app/components/AccountHeader/AccountHeader.styled.tsx
  frontend/src/metabase/account/app/components/AccountLayout/AccountLayout.styled.tsx
  frontend/src/metabase/actions/components/ActionViz/ActionDashcardSettings.styled.tsx
  frontend/src/metabase/actions/components/ActionViz/ActionForm.styled.tsx
  frontend/src/metabase/actions/components/ActionViz/ActionParameterMapping.styled.tsx
  frontend/src/metabase/actions/components/ActionViz/ExplainerText/ExplainerText.styled.tsx
  frontend/src/metabase/actions/containers/ActionCreator/ActionCreator.styled.tsx
  frontend/src/metabase/actions/containers/ActionCreator/ActionCreatorHeader.styled.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/EmptyFormPlaceholder/EmptyFormPlaceholder.styled.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FieldSettingsPopover.styled.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FormCreator.styled.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FormFieldEditor/FormFieldEditor.styled.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/OptionEditor.styled.tsx
  frontend/src/metabase/actions/containers/ActionPicker/ActionPicker.styled.tsx
  frontend/src/metabase/admin/settings/components/widgets/GroupMappingsWidget/DeleteGroupMappingModal/DeleteGroupMappingModal.styled.tsx
  frontend/src/metabase/admin/settings/components/widgets/GroupMappingsWidget/GroupMappingsWidget.styled.tsx
  frontend/src/metabase/common/components/BulkActionBar/BulkActionBar.styled.tsx
  frontend/src/metabase/common/components/Input/Input.styled.tsx
  frontend/src/metabase/common/components/SelectButton/SelectButton.styled.tsx
  frontend/src/metabase/common/components/Tab/Tab.styled.tsx
  frontend/src/metabase/common/components/TokenField/TokenField.styled.tsx
  frontend/src/metabase/common/components/UndoListing.styled.tsx
  frontend/src/metabase/forms/components/FormMessage/FormMessage.styled.tsx
  frontend/src/metabase/nav/components/StoreLink/StoreLink.styled.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbar.styled.tsx
  frontend/src/metabase/questions/components/QuestionMoveToast/QuestionMoveToast.styled.tsx
  frontend/src/metabase/styled-components/theme/constants.ts
  frontend/src/metabase/styled-components/theme/index.ts
  frontend/src/metabase/styled-components/theme/space.ts
  frontend/src/metabase/styled-components/theme/space.unit.spec.ts
  frontend/src/metabase/visualizations/components/LegendItem.styled.tsx
  frontend/src/metabase/visualizations/components/ScalarValue/ScalarValue.styled.tsx
  frontend/src/metabase/visualizations/visualizations/Scalar/Scalar.styled.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.styled.tsx
Labels: no-backport, .Team/ProductGrowth

#61794 feat: card deep links in pulses
  src/metabase/channel/impl/slack.clj
  src/metabase/channel/render/card.clj
  src/metabase/channel/urls.clj
  test/metabase/channel/impl/email_test.clj
  test/metabase/channel/impl/slack_test.clj
  test/metabase/channel/render/card_test.clj
  test/metabase/channel/urls_test.clj
  test/metabase/pulse/dashboard_subscription_test.clj
Labels: backport

#63841 Remove unused EmbeddingSetup components and hooks
  frontend/src/metabase-types/analytics/event.ts
  frontend/src/metabase/App.tsx
  frontend/src/metabase/selectors/app.ts
  frontend/src/metabase/setup/components/EmbeddingSetup/EmbeddingSetup.tsx
  frontend/src/metabase/setup/components/EmbeddingSetup/EmbeddingSetupContext.tsx
  frontend/src/metabase/setup/components/EmbeddingSetup/EmbeddingSetupSidebar.tsx
  frontend/src/metabase/setup/components/EmbeddingSetup/index.ts
  frontend/src/metabase/setup/components/EmbeddingSetup/steps/DataConnectionStep.tsx
  frontend/src/metabase/setup/components/EmbeddingSetup/steps/DoneStep.tsx
  frontend/src/metabase/setup/components/EmbeddingSetup/steps/FinalStep.tsx
  frontend/src/metabase/setup/components/EmbeddingSetup/steps/ProcessingStep.tsx
  frontend/src/metabase/setup/components/EmbeddingSetup/steps/TableSelectionStep.tsx
  frontend/src/metabase/setup/components/EmbeddingSetup/steps/UserCreationStep.tsx
  frontend/src/metabase/setup/components/EmbeddingSetup/steps/WelcomeStep.tsx
  frontend/src/metabase/setup/components/EmbeddingSetup/steps/embeddingSetupSteps.ts
Labels: no-backport, .Team/Embedding

#64328 fix(sdk): Fix SDK TSC errors
  enterprise/frontend/src/.eslintrc.js
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkBreadcrumbs/SdkBreadcrumbs.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkBreadcrumbs/setup.spec.tsx
  frontend/src/metabase/.eslintrc
  frontend/src/metabase/.eslintrc.js
  frontend/src/metabase/common/components/TitleAndDescription/i18n-tests/common.unit.spec.tsx
  frontend/src/metabase/common/components/TitleAndDescription/i18n-tests/premium.unit.spec.tsx
  frontend/src/metabase/common/components/TitleAndDescription/i18n-tests/utils.spec.tsx
  frontend/src/metabase/notifications/modals/CreateOrEditQuestionAlertModal/components/NotificationSchedule/NotificationSchedule.unit.spec.tsx
  frontend/src/metabase/notifications/modals/CreateOrEditQuestionAlertModal/components/NotificationSchedule/setup.spec.tsx
  frontend/src/metabase/parameters/components/ParameterWidget/i18n-tests/common.unit.spec.tsx
  frontend/src/metabase/parameters/components/ParameterWidget/i18n-tests/premium.unit.spec.tsx
  frontend/src/metabase/parameters/components/ParameterWidget/i18n-tests/setup.spec.tsx
  frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget/FieldValuesWidget/testMocks.spec.ts
  frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget/FieldValuesWidget/utils.unit.spec.js
  tsconfig.sdk.json
Labels: backport, .Team/Embedding

#64389 Delete unused string util from metabase lib
  frontend/src/metabase/lib/string.js
  frontend/test/metabase/lib/string.unit.spec.js
Labels: no-backport, .Team/ProductGrowth

#64404 🤖 backported "fix(sdk): Fix SDK TSC errors"
  enterprise/frontend/.eslintrc
  enterprise/frontend/.eslintrc.js
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkBreadcrumbs/SdkBreadcrumbs.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkBreadcrumbs/setup.spec.tsx
  frontend/src/metabase/.eslintrc
  frontend/src/metabase/.eslintrc.js
  frontend/src/metabase/common/components/TitleAndDescription/i18n-tests/common.unit.spec.tsx
  frontend/src/metabase/common/components/TitleAndDescription/i18n-tests/premium.unit.spec.tsx
  frontend/src/metabase/common/components/TitleAndDescription/i18n-tests/utils.spec.tsx
  frontend/src/metabase/notifications/modals/CreateOrEditQuestionAlertModal/components/NotificationSchedule/NotificationSchedule.unit.spec.tsx
  frontend/src/metabase/notifications/modals/CreateOrEditQuestionAlertModal/components/NotificationSchedule/setup.spec.tsx
  frontend/src/metabase/parameters/components/ParameterWidget/i18n-tests/common.unit.spec.tsx
  frontend/src/metabase/parameters/components/ParameterWidget/i18n-tests/premium.unit.spec.tsx
  frontend/src/metabase/parameters/components/ParameterWidget/i18n-tests/setup.spec.tsx
  frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget/FieldValuesWidget/testMocks.spec.ts
  frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget/FieldValuesWidget/utils.unit.spec.js
  tsconfig.sdk.json
Labels: was-backported

#64387 🤖 backported "feat: card deep links in pulses"
  src/metabase/channel/impl/slack.clj
  src/metabase/channel/render/card.clj
  src/metabase/channel/urls.clj
  test/metabase/channel/impl/email_test.clj
  test/metabase/channel/impl/slack_test.clj
  test/metabase/channel/render/card_test.clj
  test/metabase/channel/urls_test.clj
  test/metabase/pulse/dashboard_subscription_test.clj
Labels: was-backported

#64395 Bump io.github.metabase/hawk from 1.0.12 to 1.0.13
  deps.edn
Labels: no-backport

#64290 Fix wrong timezone in "exclude hours" filters
  src/metabase/driver/common/parameters/dates.clj
  src/metabase/query_processor/parameters/dates.clj
  test/metabase/driver/common/parameters/dates_test.clj
  test/metabase/query_processor/parameters/dates_test.clj
Labels: backport

#64014 🤖 backported "Handle trailing spaces appropriately in snippet template tags"
  e2e/test-component/scenarios/embedding-sdk/interactive-question.cy.spec.tsx
  e2e/test/scenarios/native/snippets.cy.spec.js
  src/metabase/lib/native.cljc
  test/metabase/lib/native_test.cljc
Labels: was-backported

#64305 [QP] Push required implicitly joined fields down through stages
  src/metabase/lib/walk.cljc
  src/metabase/query_processor/middleware/add_implicit_joins.clj
  test/metabase/lib/walk_test.cljc
  test/metabase/query_processor/middleware/add_implicit_joins_test.clj
  test/metabase/query_processor_test/field_ref_repro_test.clj
Labels: no-backport, .Team/Querying

#64373 🤖 backported "Fix localization number separators"
  frontend/src/metabase/admin/settings/components/widgets/FormattingWidget.tsx
  frontend/src/metabase/admin/settings/components/widgets/FormattingWidget.unit.spec.tsx
  src/metabase/appearance/settings.clj
  test/metabase/appearance/settings_test.clj
Labels: was-backported

#64427 🤖 backported "docs: price change"
  docs/cloud/how-billing-works.md
Labels: was-backported

#64386 Remove parallel annotation from tests
  test/metabase/models/resolution_test.clj
Labels: no-backport, .Team/UXWest

#64201 Show audit links for non-admins with perms
  enterprise/frontend/src/metabase-enterprise/audit_app/components/InsightsLink.tsx
  enterprise/frontend/src/metabase-enterprise/audit_app/types/state.ts
  frontend/src/metabase/common/components/Sidesheet/components/InsightsTabOrLink/tests/premium.unit.spec.tsx
  frontend/src/metabase/common/components/Sidesheet/components/InsightsTabOrLink/tests/setup.tsx
Labels: backport, .Team/UXWest

#64433 🤖 backported "Show audit links for non-admins with perms"
  enterprise/frontend/src/metabase-enterprise/audit_app/components/InsightsLink.tsx
  enterprise/frontend/src/metabase-enterprise/audit_app/types/state.ts
  frontend/src/metabase/common/components/Sidesheet/components/InsightsTabOrLink/tests/premium.unit.spec.tsx
  frontend/src/metabase/common/components/Sidesheet/components/InsightsTabOrLink/tests/setup.tsx
Labels: was-backported

#64405 Fix merge e2e timings step
  .github/scripts/average-e2e-timings.js
  .github/workflows/e2e-tests.yml
Labels: .CI & Tests, no-backport

#64424 Parameterize cloud-add-on API
  enterprise/frontend/src/metabase-enterprise/metabot/components/MetabotAdmin/MetabotPurchasePage.tsx
  frontend/src/metabase-types/api/cloud-add-ons.ts
  frontend/src/metabase-types/api/index.ts
  frontend/src/metabase-types/api/metabot.ts
  frontend/src/metabase/api/cloud-add-ons.ts
  frontend/src/metabase/api/index.ts
  frontend/src/metabase/api/metabot.ts
Labels: backport, .Team/ProductGrowth

#64349 Unskip working pivot-tables test
  e2e/test/scenarios/visualizations-tabular/pivot_tables.cy.spec.js
Labels: .CI & Tests, no-backport

#64422 🤖 backported "fix(modular): enable external click behavior; fallback to drills for internal click behaviors"
  e2e/test-component/scenarios/embedding-sdk/dashboard-click-behavior.cy.spec.tsx
  frontend/src/metabase/lib/formatting/value.tsx
  frontend/src/metabase/visualizations/lib/action.js
  frontend/src/metabase/visualizations/lib/settings.js
Labels: was-backported

#64413 chore: migrate renderer_utils from moment to dayjs
  frontend/src/metabase/lib/time-dayjs.ts
  frontend/src/metabase/visualizations/lib/renderer_utils.js
  frontend/src/metabase/visualizations/lib/renderer_utils.unit.spec.js
Labels: no-backport, .Team/Workflows

#64446 🤖 backported "Small refactoring of the services.js"
  frontend/src/metabase/services.js
Labels: was-backported

#64360 Add "Local symbol" option in "Currency label style" visualization setting
  e2e/test/scenarios/visualizations-tabular/table.cy.spec.js
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/settings/components/widgets/FormattingWidget.tsx
  frontend/src/metabase/admin/settings/components/widgets/FormattingWidget.unit.spec.tsx
  frontend/src/metabase/lib/formatting/currency.ts
  frontend/src/metabase/lib/formatting/currency.unit.spec.ts
  frontend/src/metabase/visualizations/lib/settings/column.js
Labels: no-backport, .Team/Workflows, .Team/UXEast

#64429 🤖 backported "refactor(embed-js): Refactor EmbedJS wizard to prepare it for No-user embedding"
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/embed-parameters.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/get-code.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/helpers/index.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/select-embed-options.cy.spec.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/constants.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/embed.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/types/embed.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/EmbedPreviewLoadingOverlay.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/GetCodeStep.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/ParameterSettings/ParameterSettings.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/ParameterSettings/ParameterVisibilityToggle.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/ParameterSettings/hooks/use-hide-parameter.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/SdkIframeEmbedPreview.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/SdkIframeEmbedSetup.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/SdkIframeEmbedSetup.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/SdkIframeEmbedSetupProvider.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/SelectEmbedExperienceStep.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/SelectEmbedResourceStep.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/context.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/hooks/index.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/hooks/use-get-current-resource.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/hooks/use-parameters-values.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/hooks/use-parameters.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/hooks/use-sdk-iframe-embed-settings.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/hooks/use-sdk-iframe-embed-snippet.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/types.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/utils/convert-parameter-values-by-slug-to-by-id.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/utils/convert-parameter-values-by-slug-to-by-id.unit.spec.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/utils/embed-snippet.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/utils/get-default-sdk-iframe-embed-setting.ts
Labels: was-backported

#64440 Auto-update documentation for master
  docs/api.html
Labels: Type:Documentation, no-backport

#64385 Split fields returned to metabot for cards/models into core fields and related_tables
  enterprise/backend/src/metabase_enterprise/metabot_v3/dummy_tools.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/api.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/tools/api_test.clj
Labels: no-backport, .Team/Metabot

#64464 Fix local test failure in metabot tool API test by sorting table IDs
  enterprise/backend/test/metabase_enterprise/metabot_v3/tools/api_test.clj
Labels: no-backport

#64467 Temporarily remove tooltip loki tests for embedded questions to unblock ci
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedQuestionView_Smart_Scalar_Dark_Theme_Tooltip.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedQuestionView_Smart_Scalar_Light_Theme_Tooltip.png
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestionView.stories.tsx
Labels: no-backport, .Team/Embedding

#64481 docs - triple braces in config.yml
  docs/configuring-metabase/config-file.md
Labels: Type:Documentation, double-backport

#64483 🤖 backported "docs - triple braces in config.yml"
  docs/configuring-metabase/config-file.md
Labels: was-backported

#64482 🤖 backported "docs - triple braces in config.yml"
  docs/configuring-metabase/config-file.md
Labels: was-backported

#64332 🤖 backported "fix: validate ldap server email before save"
  .clj-kondo/config/modules/config.edn
  enterprise/backend/src/metabase_enterprise/scim/v2/api.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/ldap.clj
  src/metabase/sso/core.clj
  src/metabase/sso/google.clj
  src/metabase/sso/ldap/default_implementation.clj
  src/metabase/users/api.clj
  src/metabase/users/core.clj
  src/metabase/users/models/user.clj
  src/metabase/users/schema.clj
  test/metabase/sso/ldap/default_implementation_test.clj
  test/metabase/users/models/user_test.clj
Labels: was-backported

#64493 🤖 backported "propagate original card title and description to visualizer cards"
  e2e/test/scenarios/dashboard-filters/temporal-unit-parameters.cy.spec.js
  e2e/test/scenarios/dashboard/visualizer/basics.cy.spec.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/visualizations/visualizations/CartesianChart/CartesianChart.tsx
  frontend/src/metabase/visualizer/selectors.ts
  frontend/src/metabase/visualizer/utils/get-initial-state-for-card-data-source.ts
  frontend/src/metabase/visualizer/utils/get-initial-state-for-card-data-source.unit.spec.ts
  frontend/src/metabase/visualizer/utils/get-initial-state-for-multiple-series.ts
  frontend/src/metabase/visualizer/utils/get-initial-state-for-multiple-series.unit.spec.ts
Labels: was-backported

#64366 Make db removal somewhat more efficient
  dev/src/dev/toucan2_monitor.clj
  src/metabase/warehouses/api.clj
  src/metabase/warehouses/models/database.clj
  test/metabase/search/api_test.clj
Labels: backport, .Team/Workflows

#64500 🤖 backported "Make db removal somewhat more efficient"
  dev/src/dev/toucan2_monitor.clj
  src/metabase/warehouses/api.clj
  src/metabase/warehouses/models/database.clj
  test/metabase/search/api_test.clj
Labels: was-backported

#64098 disable comments in an iframe
  .clj-kondo/config/modules/config.edn
  e2e/support/helpers/e2e-document-helpers.ts
  e2e/test/scenarios/documents/comments.cy.spec.ts
  e2e/test/scenarios/embedding/interactive-embedding.cy.spec.js
  enterprise/backend/src/metabase_enterprise/comments/api.clj
  enterprise/backend/test/metabase_enterprise/comments/api_test.clj
  enterprise/frontend/src/metabase-enterprise/documents/components/DocumentHeader.tsx
  enterprise/frontend/src/metabase-enterprise/documents/utils/api.ts
  enterprise/frontend/src/metabase-enterprise/rich_text_editing/tiptap/extensions/Blockquote/Blockquote.tsx
  enterprise/frontend/src/metabase-enterprise/rich_text_editing/tiptap/extensions/BulletList/BulletList.tsx
  enterprise/frontend/src/metabase-enterprise/rich_text_editing/tiptap/extensions/CardEmbed/CardEmbedNode.tsx
  enterprise/frontend/src/metabase-enterprise/rich_text_editing/tiptap/extensions/CodeBlock/CodeBlock.tsx
  enterprise/frontend/src/metabase-enterprise/rich_text_editing/tiptap/extensions/Heading/Heading.tsx
  enterprise/frontend/src/metabase-enterprise/rich_text_editing/tiptap/extensions/OrderedList/OrderedList.tsx
  enterprise/frontend/src/metabase-enterprise/rich_text_editing/tiptap/extensions/Paragraph/Paragraph.tsx
  src/metabase/analytics/core.clj
  src/metabase/analytics/sdk.clj
Labels: no-backport, .Team/Workflows

#64457 refactor(sdk, embed-js): Additional code preparations for Anonymous Embedding
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkAdHocQuestion/SdkAdHocQuestion.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkQuestion/context/SdkQuestionProvider.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/public/SdkQuestion/SdkQuestion.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/public/StaticQuestion/StaticQuestion.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/SdkDashboard.tsx
  enterprise/frontend/src/embedding-sdk-bundle/hooks/private/use-dashboard-load-handlers.ts
  enterprise/frontend/src/embedding-sdk-bundle/store/index.ts
  enterprise/frontend/src/embedding-sdk-bundle/store/reducer.ts
  enterprise/frontend/src/embedding-sdk-bundle/store/selectors.ts
  enterprise/frontend/src/embedding-sdk-bundle/store/types.ts
  enterprise/frontend/src/embedding-sdk-bundle/test/mocks/state.ts
  enterprise/frontend/src/embedding-sdk-bundle/types/collection.ts
  enterprise/frontend/src/embedding-sdk-bundle/types/dashboard.ts
  enterprise/frontend/src/embedding-sdk-bundle/types/entity.ts
  enterprise/frontend/src/embedding-sdk-bundle/types/index.ts
  enterprise/frontend/src/embedding-sdk-bundle/types/question.ts
  enterprise/frontend/src/embedding-sdk-bundle/types/ui.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/hooks/use-sdk-iframe-embed-event-bus.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/ParameterSettings/ParameterSettings.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/SdkIframeEmbedSetupProvider.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/context.ts
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/CodeSample.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/ServerEmbedCodePane.tsx
  frontend/src/metabase/public/components/EmbedModal/StaticEmbedSetupPane/StaticEmbedSetupPane.tsx
  frontend/src/metabase/public/components/EmbedServerSnippetLanguageSelect/EmbedServerSnippetLanguageSelect.tsx
  frontend/src/metabase/public/lib/code-templates.ts
  frontend/src/metabase/public/lib/embed.ts
  frontend/src/metabase/public/lib/types.ts
  frontend/src/metabase/query_builder/components/VisualizationResult.jsx
  frontend/src/metabase/redux/downloads.ts
Labels: backport, .Team/Embedding, Embedding/SDK

#64448 Add column names / ordering to python test-run output
  enterprise/backend/src/metabase_enterprise/transforms_python/api.clj
  enterprise/backend/test/metabase_enterprise/transforms_python/api_test.clj
Labels: no-backport, .Team/Metabot

#64285 DSN-69 Smart Scalar charts in dashboards shouldn't overflow their card
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedQuestionView_Smart_Scalar_Dark_Theme.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedQuestionView_Smart_Scalar_Light_Theme.png
  .loki/reference/chrome_laptop_Viz_Static_Viz_SmartScalar_Big_Numbers.png
  .loki/reference/chrome_laptop_Viz_Static_Viz_SmartScalar_Comparisons.png
  .loki/reference/chrome_laptop_Viz_Static_Viz_SmartScalar_Default.png
  .loki/reference/chrome_laptop_Viz_Static_Viz_SmartScalar_Missing_Interval.png
  .loki/reference/chrome_laptop_Viz_Static_Viz_SmartScalar_Null_Value.png
  .loki/reference/chrome_laptop_viz_SmartScalar_Default.png
  .loki/reference/chrome_laptop_viz_SmartScalar_Embedding_Theme.png
  e2e/test/scenarios/dashboard-cards/dashboard-card-reproductions.cy.spec.js
  e2e/test/scenarios/dashboard-cards/dashboard-card-resizing.cy.spec.js
  frontend/src/metabase/static-viz/components/SmartScalar/SmartScalar.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.styled.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/PreviousValueComparison.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/PreviousValueComparison/DetailCandidate.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/PreviousValueComparison/PreviousValueComparison.styled.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/PreviousValueComparison/PreviousValueComparison.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/PreviousValueComparison/PreviousValueComparisonTooltip.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/PreviousValueComparison/VariationDetails.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/PreviousValueComparison/VariationPercent.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/PreviousValueComparison/index.ts
  frontend/src/metabase/visualizations/visualizations/SmartScalar/Separator.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/constants.ts
  frontend/src/metabase/visualizations/visualizations/SmartScalar/utils.ts
Labels: no-backport, .Team/Workflows, PR-Env, .Team/UXEast

#64506 🤖 backported "refactor(sdk): move transformSdkQuestion"
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkQuestion/context/SdkQuestionProvider.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkQuestion/hooks/use-run-visualization.ts
  enterprise/frontend/src/embedding-sdk-bundle/lib/transform-question.unit.spec.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenuItems.tsx
  frontend/src/metabase/embedding-sdk/lib/transform-question.ts
Labels: was-backported

#64509 🤖 backported "rename tests folder to stories"
  enterprise/frontend/src/embedding-sdk-bundle/stories/sdk-locale-support.stories.tsx
  enterprise/frontend/src/embedding-sdk-bundle/stories/styling-sdk-tests.stories.tsx
Labels: was-backported

#64462 [search] make verified dashboards appear when filtering for "verified"
  src/metabase/dashboards/models/dashboard.clj
  src/metabase/search/appdb/core.clj
  src/metabase/search/in_place/filter.clj
  test/metabase/search/api_test.clj
  test/metabase/search/in_place/filter_test.clj
  test/metabase/test.clj
  test/metabase/test/util.clj
Labels: backport, .Team/Workflows

#64511 🤖 backported "[search] make verified dashboards appear when filtering for "verified""
  src/metabase/dashboards/models/dashboard.clj
  src/metabase/search/appdb/core.clj
  src/metabase/search/in_place/filter.clj
  test/metabase/search/api_test.clj
  test/metabase/search/in_place/filter_test.clj
  test/metabase/test.clj
  test/metabase/test/util.clj
Labels: was-backported

#64513 🤖 backported "Fix Firefox bug where models are not clickable until after selecting/unselecting some text"
  frontend/src/metabase/browse/models/ModelsTable.tsx
Labels: was-backported
