Repository metabase/metabase, pull requests merged in 2025-06, with the labels that each got.

#58284 Move visibility toggles to the table picker
  frontend/src/metabase/metadata/pages/DataModel/components/TablePicker/Results.module.css
  frontend/src/metabase/metadata/pages/DataModel/components/TablePicker/Results.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/TablePicker/TableVisibilityToggle.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/TablePicker/TableVisibilityToggle.unit.spec.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/TablePicker/types.ts
  frontend/src/metabase/metadata/pages/DataModel/components/TablePicker/utils.ts
  frontend/src/metabase/metadata/pages/DataModel/components/TableSection/TableSection.tsx
  frontend/test/__support__/server-mocks/table.ts
Labels: .Team/SemanticLayer

#58612 Improve the `embedding-sdk-no-exposed-internal-types-validate` CI job
  .github/workflows/embedding-sdk.yml
  .typedoc/typedoc.common.config.js
Labels: backport, .Team/Embedding

#58775 🤖 backported "Reproduction for missing hyphen in formatting in joined columns"
  e2e/test/scenarios/custom-column/custom-column-reproductions.cy.spec.js
  frontend/src/metabase-lib/v1/expressions/formatter/formatter.unit.spec.ts
Labels: was-backported

#58635 WRK-340 Improve table selection when adding editable
  frontend/src/metabase/components/SelectList/SelectListItem.tsx
  frontend/src/metabase/dashboard/components/QuestionPicker/QuestionPicker.tsx
  frontend/src/metabase/dashboard/components/TablePicker/TableList.module.css
  frontend/src/metabase/dashboard/components/TablePicker/TableList.tsx
Labels: no-backport, .Team/Workflows

#53159 Fix the code blocks in README.md to facilitate the copy feature
  README.md
Labels: no-backport

#58754 docs: MongoDB supports basic sandboxing
  docs/permissions/data-sandboxes.md
Labels: Type:Documentation, backport

#58707 docs - download button for static embeds
  docs/embedding/images/04-preview.png
  docs/embedding/static-embedding-parameters.md
Labels: Type:Documentation, backport

#58711 🤖 backported "docs - sentence case"
  e2e/test/scenarios/onboarding/command-palette.cy.spec.js
  frontend/src/metabase/nav/components/ProfileLink/ProfileLink.jsx
Labels: was-backported

#58784 Use string literals for i18n context
  enterprise/frontend/src/metabase-enterprise/metabot/components/MetabotAdmin/MetabotAdminPage.tsx
Labels: Customization/i18n, backport, .Team/AdminWebapp

#58791 Share common Host App tests between all Host Apps
  e2e/runner/cypress-runner-run-tests.js
  e2e/test-host-app/next-14-app-router-host-app/compatibility.cy.spec.js
  e2e/test-host-app/next-14-pages-router-host-app/compatibility.cy.spec.js
  e2e/test-host-app/shared/compatibility.cy.spec.js
Labels: no-backport, .Team/Embedding

#58426 add native query validation of time grouping syntax
  e2e/test/scenarios/dashboard-filters/temporal-unit-parameters.cy.spec.js
  e2e/test/scenarios/native/native.cy.spec.js
  frontend/src/metabase-lib/native.ts
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.module.css
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryValidationError/NativeQueryValidationError.module.css
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryValidationError/NativeQueryValidationError.tsx
  src/metabase/driver/sql/parameters/substitution.clj
  src/metabase/lib/core.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/native.cljc
  test/metabase/lib/native_test.cljc
Labels: .Team/Querying, PR-Env

#58684 🤖 backported "Don't create mega queries when deleting databases (#58491)"
  bin/lint-migrations-file/src/change_set/strict.clj
  bin/lint-migrations-file/test/lint_migrations_file_test.clj
  src/metabase/app_db/init.clj
  src/metabase/app_db/setup.clj
  src/metabase/models/interface.clj
  src/metabase/warehouses/models/database.clj
  test/metabase/app_db/setup_test.clj
Labels: was-backported

#58685 🤖 backported "Mega App DB memory usage improvements"
  src/metabase/app_db/connection_pool_setup.clj
  test/metabase/app_db/connection_pool_setup_test.clj
Labels: was-backported

#58242 cljs: Replace clojure.spec leftovers with Malli
  enterprise/backend/test/metabase_enterprise/serialization/load_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/test_util.clj
  src/metabase/models/visualization_settings.cljc
  src/metabase/util/log/capture.cljc
  test/metabase/models/visualization_settings_test.cljc
Labels: backport

#53665 fix(api-openapi): documentation responsivity
  resources/openapi/index.html
Labels: backport

#58582 Respect `is_active` on JWT/SAML logins
  enterprise/backend/src/metabase_enterprise/sso/integrations/jwt.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/saml.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/sso_utils.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/saml_test.clj
Labels: backport, .Team/AdminWebapp

#58660 docs - pivot table exports
  docs/questions/exporting-results.md
  docs/questions/images/pivot-table-in-metabase.png
  docs/questions/images/pivoted-results.png
  docs/questions/images/raw-table.png
  docs/questions/images/unpivoted-results.png
  docs/questions/visualizations/pivot-table.md
Labels: Type:Documentation, backport

#58813 🤖 backported "docs - pivot table exports"
  docs/questions/exporting-results.md
  docs/questions/images/pivot-table-in-metabase.png
  docs/questions/images/pivoted-results.png
  docs/questions/images/raw-table.png
  docs/questions/images/unpivoted-results.png
  docs/questions/visualizations/pivot-table.md
Labels: was-backported

#58822 🤖 backported "Fixing strings for relative date params in subscriptions"
  e2e/test/scenarios/sharing/sharing-reproductions.cy.spec.js
  e2e/test/scenarios/sharing/subscriptions.cy.spec.js
  frontend/src/metabase/notifications/AddEditSidebar/DefaultParametersSection.jsx
  frontend/src/metabase/notifications/AddEditSidebar/DefaultParametersSection.unit.spec.jsx
  frontend/src/metabase/notifications/DashboardSubscriptionsSidebar/tests/setup.tsx
  frontend/src/metabase/notifications/PulsesListSidebar.jsx
  src/metabase/parameters/shared.cljc
  test/metabase/parameters/shared_test.cljc
Labels: was-backported

#58204 Fix zoom drill for clicks on a joined PK column
  src/metabase/lib/drill_thru/common.cljc
  src/metabase/lib/drill_thru/quick_filter.cljc
  src/metabase/lib/drill_thru/zoom.cljc
  test/metabase/lib/drill_thru_test.cljc
Labels: backport

#58745 🤖 backported "Ensure display-info returns correct :long-display-name for aggregations from a previous stage"
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  e2e/test/scenarios/filters/filter-sources.cy.spec.js
  frontend/src/metabase-lib/v1/parameters/utils/targets.unit.spec.ts
  src/metabase/lib/field.cljc
  src/metabase/lib/util.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/util_test.cljc
Labels: was-backported

#58818 Fixup snowflake old dataset check
  modules/drivers/snowflake/test/metabase/test/data/snowflake.clj
Labels: backport

#58814 update native query time grouping tests to be more comprehensive
  test/metabase/driver/common/parameters/temporal_units_test.clj
  test/metabase/test/data/interface.clj
  test/metabase/test/data/sql.clj
Labels: .Team/Querying

#58777 add logging for table filtering during sync
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj
  modules/drivers/databricks/src/metabase/driver/databricks.clj
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  src/metabase/driver/sql_jdbc/sync/describe_database.clj
Labels: backport, .Team/SemanticLayer

#58768 🤖 backported "Handle datetime extracted values in filters for xrays"
  src/metabase/xrays/automagic_dashboards/names.clj
  test/metabase/xrays/automagic_dashboards/names_test.clj
Labels: was-backported

#58832 🤖 backported "Fixup snowflake old dataset check"
  modules/drivers/snowflake/test/metabase/test/data/snowflake.clj
Labels: was-backported

#58831 Optimize delete children
  .clj-kondo/config/modules/config.edn
  enterprise/backend/test/metabase_enterprise/data_editing/api_test.clj
  src/metabase/actions/actions.clj
  src/metabase/actions/core.clj
  src/metabase/actions/error.clj
  src/metabase/actions/foreign_keys.clj
  src/metabase/driver/sql_jdbc/actions.clj
  test/metabase/actions/foreign_keys_test.clj
  test/metabase/driver/sql_jdbc/actions_test.clj
Labels: .Team/Workflows

#58856 Revert "Remove hive-jdbc$standalone dependency"
  deps.edn
  modules/drivers/deps.edn
  modules/drivers/hive-like/deps.edn
Labels: no-backport, .Team/Drivers

#58858 🤖 backported "docs - visualizer updates"
  docs/dashboards/images/add-data.png
  docs/dashboards/images/add_values.png
  docs/dashboards/images/edit-visualization.png
  docs/dashboards/images/edit_modal.png
  docs/dashboards/images/edit_modal_multi-series.png
  docs/dashboards/images/editor-orders-by-product-category.png
  docs/dashboards/images/multi-series_query_builder.png
  docs/dashboards/images/notebook_editor_multi-series.png
  docs/dashboards/images/numbers_to_bar_chart.png
  docs/dashboards/images/set-to-bar-chart.png
  docs/dashboards/images/settings-sidebar.png
  docs/dashboards/images/visualization-settings.png
  docs/dashboards/images/visualize-another-way.png
  docs/dashboards/introduction.md
  docs/dashboards/multiple-series.md
Labels: was-backported

#58781 Remove transient "Getting started" section from the main sidebar in v55 (#58332)
  .clj-kondo/src/hooks/metabase/settings/models/setting.clj
  e2e/test/scenarios/onboarding/onboarding-checklist.cy.spec.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/app/selectors.ts
  frontend/src/metabase/collections/utils.ts
  frontend/src/metabase/home/components/Onboarding/OnboardingDismissedToast.tsx
  frontend/src/metabase/home/components/Onboarding/index.ts
  frontend/src/metabase/nav/components/ProfileLink/ProfileLink.jsx
  frontend/src/metabase/nav/components/ProfileLink/ProfileLink.unit.spec.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbar.styled.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/GettingStartedSection.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/GettingStartedSection.unit.spec.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarView.tsx
  frontend/src/metabase/nav/containers/MainNavbar/tests/common.unit.spec.tsx
  src/metabase/users/settings.clj
Labels: .Team/ProductGrowth

#58771 FE for delete linked records
  enterprise/frontend/src/metabase-enterprise/api/table-data-edit.ts
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/EditTableDashcardVisualization.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/EditTableDataContainer.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/modals/ForeignKeyConstraintModal.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/modals/ForeignKeyConstraintModal.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/modals/use-foreign-key-constraint-handling.ts
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/modals/use-foreign-key-constraint-handling.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/use-table-crud.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/types.ts
  frontend/src/metabase/dashboard/actions/actions.ts
Labels: no-backport, .Team/Workflows

#58360 VIZ-1024 small polish items on visualizer
  e2e/test/scenarios/dashboard/visualizer/funnels.cy.spec.ts
  frontend/src/metabase/visualizer/components/VisualizationPicker/VisualizationPicker.tsx
Labels: backport, .Team/DashViz

#58861 🤖 backported "docs - shortcuts"
  docs/README.md
  docs/exploration-and-organization/keyboard-shortcuts.md
  docs/exploration-and-organization/start.md
  docs/util/README.md
  docs/util/generate-shortcuts-docs.ts
  docs/util/resources/introduction.md
  docs/util/tsconfig.json
  e2e/test/scenarios/onboarding/command-palette.cy.spec.js
  frontend/src/metabase/palette/components/PaletteShortcutsModal/PaletteShortcutsModal.tsx
  frontend/src/metabase/palette/constants.ts
  frontend/src/metabase/palette/shortcuts/dashboard.ts
  frontend/src/metabase/palette/shortcuts/global.ts
  frontend/src/metabase/palette/shortcuts/question.ts
  frontend/src/metabase/palette/types.ts
  util/package.json
Labels: was-backported

#58785 Address review comments from #58408
  e2e/test/scenarios/onboarding/add-initial-data.cy.spec.ts
  frontend/src/metabase/databases/components/DatabaseEngineList/DatabaseEngineList.module.css
  frontend/src/metabase/databases/components/DatabaseEngineList/DatabaseEngineList.tsx
  frontend/src/metabase/databases/components/DatabaseEngineList/DatabaseEngineList.unit.spec.tsx
  frontend/src/metabase/databases/constants.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/AddDataModal/AddDataModal.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/AddDataModal/Panels/PanelsHeader.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/BrowseNavSection.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/BrowseNavSection.unit.spec.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/GettingStartedSection.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/GettingStartedSection.unit.spec.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarView.tsx
Labels: no-backport, .Team/ProductGrowth

#54847 Update case.md
  docs/questions/query-builder/expressions/case.md
Labels: backport

#58819 chore: add galdre to internal team config
  .github/team.json
  release/github-slack-map.json
Labels: backport, .Team/Querying

#58706 Short circuit on sync error
  src/metabase/sync/analyze/fingerprint.clj
  src/metabase/sync/util.clj
  test/metabase/sync/field_values_test.clj
Labels: backport, .Team/SemanticLayer

#58661 Correctly handle nil last-sync-started-at in gsheets response
  enterprise/backend/src/metabase_enterprise/gsheets/api.clj
  enterprise/backend/test/metabase_enterprise/api/gsheets_test.clj
Labels: .Team/AdminWebapp, double-backport

#58828 Remove LLM Autodescription Frontend
  enterprise/frontend/src/metabase-enterprise/llm_autodescription/LLMSuggestQuestionInfo.tsx
  enterprise/frontend/src/metabase-enterprise/llm_autodescription/index.ts
  enterprise/frontend/src/metabase-enterprise/llm_autodescription/loading.css
  enterprise/frontend/src/metabase-enterprise/plugins.js
  enterprise/frontend/src/metabase-enterprise/services.ts
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/settings/selectors/selectors.js
  frontend/src/metabase/components/SaveQuestionForm/LLMSuggestionQuestionInfo.tsx
  frontend/src/metabase/components/SaveQuestionForm/index.ts
  frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.tsx
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/plugins/types.ts
Labels: backport

#58770 🤖 backported "Handle datetime extracted values in filters for xrays"
  src/metabase/xrays/automagic_dashboards/names.clj
  test/metabase/xrays/automagic_dashboards/names_test.clj
Labels: was-backported

#58769 🤖 backported "Handle datetime extracted values in filters for xrays"
  src/metabase/xrays/automagic_dashboards/names.clj
  test/metabase/xrays/automagic_dashboards/names_test.clj
Labels: was-backported

#58718 Make new "appdb" search engine the default starting with v55
  src/metabase/search/api.clj
  src/metabase/search/settings.clj
  test/metabase/search/api_test.clj
Labels: backport, .Team/AdminWebapp

#58876 Improve Editable action init hook
  enterprise/backend/test/metabase_enterprise/data_editing/api_test.clj
  src/metabase/dashboards/api.clj
  test/metabase/dashboards/api_test.clj
Labels: .Team/Workflows

#58880 🤖 backported "Short circuit on sync error"
  src/metabase/sync/analyze/fingerprint.clj
  src/metabase/sync/util.clj
  test/metabase/sync/field_values_test.clj
Labels: was-backported

#58898 🤖 backported "docs - remove export branding"
  docs/exploration-and-organization/uploads.md
  docs/questions/exporting-results.md
  docs/questions/images/question-with-metabase-logo.png
  docs/questions/query-builder/expressions/countif.md
Labels: was-backported

#58726 🤖 backported "Always fully uncollapse pivots in exports"
  src/metabase/pivot/core.cljc
  test/metabase/pivot/core_test.cljc
Labels: was-backported

#58901 docs - multi-catalog support for databricks
  docs/databases/connections/databricks.md
Labels: Type:Documentation, backport

#58903 🤖 backported "docs - multi-catalog support for databricks"
  docs/databases/connections/databricks.md
Labels: was-backported

#58683 [MLv2 × QP] `auto-parse-filter-values` => MLv2
  enterprise/backend/test/metabase_enterprise/sandbox/query_processor/middleware/row_level_restrictions_test.clj
  src/metabase/driver/sql/query_processor.clj
  src/metabase/query_processor/middleware/auto_parse_filter_values.clj
  src/metabase/query_processor/preprocess.clj
  test/metabase/query_processor/middleware/auto_parse_filter_values_test.clj
  test/metabase/query_processor/util/add_alias_info_test.clj
Labels: no-backport, .Team/Querying

#58906 🤖 backported "Don't show prompt to add duplicated model to dashboard"
  e2e/test/scenarios/collections/instance-analytics.cy.spec.js
  e2e/test/scenarios/models/models.cy.spec.js
  e2e/test/scenarios/models/reproductions.cy.spec.js
  frontend/src/metabase/query_builder/components/QueryModals/QueryModals.tsx
Labels: was-backported

#58878 Fix time grouping tests
  test/metabase/driver/common/parameters/temporal_units_test.clj
Labels: .Team/Querying

#58848 chore: replace moment-timezone with dayjs in cypress specs
  e2e/test/scenarios/actions/actions-in-object-detail-view.cy.spec.js
  e2e/test/scenarios/filters-reproductions/dashboard-filters-reproductions.cy.spec.js
  e2e/test/scenarios/filters/relative-datetime.cy.spec.js
Labels: no-backport, .Team/Querying

#58908 Map row action parameters on the server side
  enterprise/backend/src/metabase_enterprise/data_editing/api.clj
  enterprise/backend/src/metabase_enterprise/data_editing/data_editing.clj
  enterprise/backend/test/metabase_enterprise/data_editing/api_test.clj
Labels: .Team/Workflows

#58843 add some snowplow events for semantic layer events
  .clj-kondo/config/modules/config.edn
  src/metabase/warehouse_schema/api/field.clj
  src/metabase/warehouses/api.clj
  test/metabase/warehouse_schema/api/field_test.clj
  test/metabase/warehouses/api_test.clj
Labels: backport, .Team/SemanticLayer

#58884 Extend tmp-modal to existing viz-action mappings
  enterprise/backend/src/metabase_enterprise/data_editing/api.clj
  enterprise/backend/test/metabase_enterprise/data_editing/api_test.clj
Labels: .Team/Workflows

#58917 Fix conditional table notification not sending
  enterprise/backend/test/metabase_enterprise/data_editing/notification_test.clj
  src/metabase/notification/condition.clj
  test/metabase/notification/condition_test.clj
Labels: .Team/Workflows

#58924 ci(sdk): skip broken create question test temporarily
  e2e/test-component/scenarios/embedding-sdk/create-question.cy.spec.tsx
Labels: no-backport, .Team/Embedding

#58693 handle effective_type/coercions in fingerprinters
  src/metabase/analyze/fingerprint/fingerprinters.clj
  test/metabase/analyze/fingerprint/fingerprinters_test.clj
  test/metabase/analyze/fingerprint/insights_test.clj
Labels: backport, .Team/SemanticLayer

#58926 🤖 backported "handle effective_type/coercions in fingerprinters"
  src/metabase/analyze/fingerprint/fingerprinters.clj
  test/metabase/analyze/fingerprint/fingerprinters_test.clj
  test/metabase/analyze/fingerprint/insights_test.clj
Labels: was-backported

#58927 SEM-311 Table preview - no impact when changing time formatting for seconds and ms
  frontend/src/metabase/metadata/pages/DataModel/components/PreviewSection/TablePreview.tsx
Labels: no-backport, .Team/SemanticLayer

#58868 Avoid timeouts during sync with snowflake
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
Labels: backport, .Team/SemanticLayer

#58933 Backport missing visualizer PRs
  e2e/support/helpers/e2e-dashboard-helpers.ts
  e2e/support/helpers/e2e-dashboard-visualizer-helpers.ts
  e2e/support/test-visualizer-data.ts
  e2e/test/scenarios/dashboard/dashboard-questions.cy.spec.js
  e2e/test/scenarios/dashboard/visualizer/basics.cy.spec.ts
  e2e/test/scenarios/dashboard/visualizer/cartesian.cy.spec.ts
  e2e/test/scenarios/dashboard/visualizer/drillthrough.cy.spec.ts
  e2e/test/scenarios/metrics/metrics-dashboard.cy.spec.js
  e2e/test/scenarios/metrics/reproductions/metrics-reproductions.cy.spec.ts
  e2e/test/scenarios/sharing/sharing-reproductions.cy.spec.js
  e2e/test/scenarios/visualizations-charts/line-bar-tooltips.cy.spec.js
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.js
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/static-viz/index.js
  frontend/src/metabase/ui/components/overlays/Menu/MenuItem/MenuItem.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.tsx
  frontend/src/metabase/visualizations/components/legend/LegendCaption.tsx
  frontend/src/metabase/visualizer/components/DataImporter/DataImporter.tsx
  frontend/src/metabase/visualizer/components/DataImporter/DatasetsList/DatasetsList.tsx
  frontend/src/metabase/visualizer/hooks/use-boolean-map.ts
  frontend/src/metabase/visualizer/selectors.ts
  frontend/src/metabase/visualizer/utils/get-visualization-columns.ts
  frontend/src/metabase/visualizer/utils/merge-data.ts
  frontend/src/metabase/visualizer/utils/merge-data.unit.spec.ts
  frontend/src/metabase/visualizer/utils/split-series.ts
  frontend/src/metabase/visualizer/utils/update-viz-settings-with-refs.ts
  frontend/src/metabase/visualizer/utils/update-viz-settings-with-refs.unit.spec.ts
  frontend/src/metabase/visualizer/visualizations/cartesian.ts
  frontend/src/metabase/visualizer/visualizer.slice.ts
  src/metabase/activity_feed/api.clj
  src/metabase/activity_feed/models/recent_views.clj
  src/metabase/search/impl.clj
  test/metabase/activity_feed/models/recent_views_test.clj
Labels: .Team/DashViz

#58936 🤖 backported "Avoid timeouts during sync with snowflake"
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
Labels: was-backported

#58950 [test] Make backports persevere test
  e2e/test/scenarios/filters-reproductions/filters-reproductions.cy.spec.js
  frontend/src/metabase/components/InputBlurChange/InputBlurChange.tsx
Labels: .Team/AdminWebapp, triple-backport

#58944 🤖 backported "Fix disappearing padding on filter"
  e2e/test/scenarios/filters-reproductions/filters-reproductions.cy.spec.js
  frontend/src/metabase/querying/filters/components/FilterPicker/StringFilterPicker/StringFilterPicker.tsx
Labels: was-backported

#58960 docs - 55 generated docs
  docs/api.html
  docs/configuring-metabase/config-template.md
  docs/configuring-metabase/environment-variables.md
Labels: Type:Documentation, no-backport

#58794 Undoable undo
  enterprise/backend/src/metabase_enterprise/data_editing/actions.clj
  enterprise/backend/src/metabase_enterprise/data_editing/data_editing.clj
  enterprise/backend/src/metabase_enterprise/data_editing/models/undo.clj
  enterprise/backend/test/metabase_enterprise/data_editing/api_test.clj
  enterprise/backend/test/metabase_enterprise/data_editing/models/undo_test.clj
  resources/migrations/001_update_migrations.yaml
  src/metabase/driver/sql_jdbc/actions.clj
Labels: .Team/Workflows

#58729 Fix 3 flaky tests
  src/metabase/app_db/cluster_lock.clj
  src/metabase/query_processor/middleware/update_used_cards.clj
  test/metabase/parameters/custom_values_test.clj
  test/metabase/premium_features/token_check_test.clj
  test/metabase/sync/analyze/fingerprint_test.clj
  test/metabase/test/initialize.clj
  test/metabase/test/initialize/row_lock.clj
  test/metabase/warehouses/api_test.clj
Labels: .Team/AdminWebapp, double-backport

#58896 Add test for implicity join columns
  test/metabase/lib/metadata/calculation_test.cljc
Labels: no-backport, .Team/Querying

#58920 respect modularisation effort and use analytics.core
  src/metabase/warehouse_schema/api/field.clj
  src/metabase/warehouses/api.clj
Labels: backport, .Team/SemanticLayer

#58983 🤖 backported "Fix 3 flaky tests"
  src/metabase/app_db/cluster_lock.clj
  src/metabase/query_processor/middleware/update_used_cards.clj
  test/metabase/parameters/custom_values_test.clj
  test/metabase/premium_features/token_check_test.clj
  test/metabase/sync/analyze/fingerprint_test.clj
  test/metabase/test/initialize.clj
  test/metabase/test/initialize/row_lock.clj
  test/metabase/warehouses/api_test.clj
Labels: was-backported

#58755 Update License and Billing Settings
  enterprise/frontend/src/metabase-enterprise/license/actions.ts
  enterprise/frontend/src/metabase-enterprise/license/components/BillingInfo/BillingGoToStore.tsx
  enterprise/frontend/src/metabase-enterprise/license/components/BillingInfo/BillingInfo.tsx
  enterprise/frontend/src/metabase-enterprise/license/components/BillingInfo/BillingInfoError.tsx
  enterprise/frontend/src/metabase-enterprise/license/components/BillingInfo/BillingInfoNotStoreManaged.tsx
  enterprise/frontend/src/metabase-enterprise/license/components/BillingInfo/BillingInfoTable.tsx
  enterprise/frontend/src/metabase-enterprise/license/components/LicenseAndBillingSettings/LicenseAndBillingSettings.tsx
  enterprise/frontend/src/metabase-enterprise/license/components/LicenseAndBillingSettings/LicenseAndBillingSettings.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/license/components/LicenseAndBillingSettings/index.ts
  enterprise/frontend/src/metabase-enterprise/license/index.js
  frontend/src/metabase/admin/settings/components/LicenseInput/LicenseInput.styled.tsx
  frontend/src/metabase/admin/settings/components/LicenseInput/LicenseInput.tsx
  frontend/src/metabase/admin/settings/components/SettingsLicense/SettingsLicense.styled.tsx
  frontend/src/metabase/admin/settings/components/SettingsLicense/SettingsLicense.tsx
  frontend/src/metabase/admin/settings/components/SettingsLicense/SettingsLicense.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/SettingsLicense/index.ts
  frontend/src/metabase/admin/settings/components/SettingsPages/LicenseSettingsPage.tsx
  frontend/src/metabase/admin/settings/selectors/selectors.js
  frontend/src/metabase/plugins/index.ts
  frontend/test/__support__/server-mocks/index.ts
  frontend/test/__support__/server-mocks/premium-features.ts
Labels: no-backport, .Team/AdminWebapp

#58797 Closes VIZ-1051 no title menu for single source cards
  e2e/support/helpers/e2e-dashboard-helpers.ts
  e2e/support/helpers/e2e-dashboard-visualizer-helpers.ts
  e2e/test/scenarios/dashboard/visualizer/basics.cy.spec.ts
  e2e/test/scenarios/dashboard/visualizer/cartesian.cy.spec.ts
  e2e/test/scenarios/dashboard/visualizer/filters.cy.spec.ts
  e2e/test/scenarios/dashboard/visualizer/snowplow-tracking.cy.spec.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/visualizations/components/ChartCaption.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.tsx
  frontend/src/metabase/visualizations/components/legend/LegendCaption.tsx
  frontend/src/metabase/visualizations/types/visualization.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/CartesianChart.tsx
  frontend/src/metabase/visualizations/visualizations/Funnel/Funnel.tsx
Labels: backport, .Team/DashViz

#58942 Test fixes
  enterprise/backend/test/metabase_enterprise/data_editing/api_test.clj
  enterprise/backend/test/metabase_enterprise/data_editing/test_util.clj
Labels: .Team/Workflows

#58986 🤖 backported "respect modularisation effort and use analytics.core"
  src/metabase/warehouse_schema/api/field.clj
  src/metabase/warehouses/api.clj
Labels: was-backported

#58937 Add support for drop downs to tmp-modal
  enterprise/backend/src/metabase_enterprise/data_editing/api.clj
Labels: .Team/Workflows

#58989 🤖 backported "Closes VIZ-1051 no title menu for single source cards"
  e2e/support/helpers/e2e-dashboard-helpers.ts
  e2e/support/helpers/e2e-dashboard-visualizer-helpers.ts
  e2e/test/scenarios/dashboard/visualizer/basics.cy.spec.ts
  e2e/test/scenarios/dashboard/visualizer/cartesian.cy.spec.ts
  e2e/test/scenarios/dashboard/visualizer/filters.cy.spec.ts
  e2e/test/scenarios/dashboard/visualizer/snowplow-tracking.cy.spec.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/visualizations/components/ChartCaption.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.tsx
  frontend/src/metabase/visualizations/components/legend/LegendCaption.tsx
  frontend/src/metabase/visualizations/types/visualization.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/CartesianChart.tsx
  frontend/src/metabase/visualizations/visualizations/Funnel/Funnel.tsx
Labels: was-backported

#58988 🤖 backported "remove ai dashboard analysis"
  enterprise/backend/src/metabase_enterprise/ai_entity_analysis/api.clj
  enterprise/backend/test/metabase_enterprise/ai_entity_analysis/api_test.clj
  enterprise/frontend/src/metabase-enterprise/ai-entity-analysis/components/AIDashboardAnalysisButton.tsx
  enterprise/frontend/src/metabase-enterprise/ai-entity-analysis/components/AIDashboardAnalysisSidebar/AIDashboardAnalysisSidebar.tsx
  enterprise/frontend/src/metabase-enterprise/ai-entity-analysis/components/AIDashboardAnalysisSidebar/AIDashboardAnalysisSidebar.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/ai-entity-analysis/hooks/useDashboardAnalysis.ts
  enterprise/frontend/src/metabase-enterprise/ai-entity-analysis/index.ts
  enterprise/frontend/src/metabase-enterprise/api/ai-entity-analysis.ts
  frontend/src/metabase-types/api/ai-entity-analysis.ts
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeaderButtonRow/DashboardHeaderButtonRow.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeaderButtonRow/action-buttons.tsx
  frontend/src/metabase/dashboard/components/DashboardHeader/DashboardHeaderButtonRow/constants.ts
  frontend/src/metabase/dashboard/components/DashboardSidebars.tsx
  frontend/src/metabase/plugins/index.ts
  frontend/test/__support__/server-mocks/ai-entity-analysis.ts
Labels: was-backported

#58998 docs - add notIn entry
  docs/questions/query-builder/expressions-list.md
Labels: Type:Documentation, backport

#59000 🤖 backported "docs - add notIn entry"
  docs/questions/query-builder/expressions-list.md
Labels: was-backported

#58753 Update Malli to 0.18
  deps.edn
  src/metabase/api/macros/defendpoint/open_api.clj
  src/metabase/api/open_api.clj
  src/metabase/models/visualization_settings.cljc
  src/metabase/util/malli/defn.clj
  src/metabase/util/malli/fn.clj
  test/metabase/api/macros/defendpoint/open_api_test.clj
  test/metabase/api/open_api_test.clj
  test/metabase/test/http_client.clj
  test/metabase/util/malli/defn_test.clj
  test/metabase/util/malli/fn_test.clj
Labels: no-backport

#59001 Add the special empty viz state for native queries
  frontend/src/metabase/visualizations/components/EmptyVizState/EmptyVizState.tsx
  frontend/src/metabase/visualizations/components/EmptyVizState/EmptyVizState.unit.spec.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.tsx
Labels: backport, .Team/ProductGrowth

#58996 test: add repro for a fixed issue
  e2e/test/scenarios/question-reproductions/reproductions.cy.spec.ts
Labels: no-backport, .Team/Querying

#58882 Fix the comment
  src/metabase/query_processor/middleware/resolve_joins.clj
Labels: no-backport, .Team/Querying

#58993 validate time unit parameters and fix bug
  src/metabase/driver/common/parameters/values.clj
  src/metabase/driver/sql/parameters/substitute.clj
  test/metabase/driver/common/parameters/temporal_units_test.clj
Labels: .Team/Querying

#58670 Update Settings SAML Form
  e2e/test/scenarios/admin-2/sso/saml.cy.spec.js
  enterprise/backend/src/metabase_enterprise/sso/settings.clj
  enterprise/backend/test/metabase_enterprise/sso/settings_test.clj
  enterprise/frontend/src/metabase-enterprise/api/index.ts
  enterprise/frontend/src/metabase-enterprise/api/saml.ts
  enterprise/frontend/src/metabase-enterprise/auth/components/SettingsSAMLForm/SettingsSAMLForm.jsx
  enterprise/frontend/src/metabase-enterprise/auth/components/SettingsSAMLForm/SettingsSAMLForm.styled.tsx
  enterprise/frontend/src/metabase-enterprise/auth/components/SettingsSAMLForm/SettingsSAMLForm.tsx
  enterprise/frontend/src/metabase-enterprise/auth/components/SettingsSAMLForm/SettingsSAMLForm.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/auth/components/SettingsSAMLForm/index.js
  enterprise/frontend/src/metabase-enterprise/auth/index.js
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/auth.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/sso-saml-disabled.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/sso-saml.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/SettingsLdapForm.tsx
  frontend/src/metabase/admin/settings/selectors/selectors.js
  frontend/src/metabase/admin/settings/settings.js
  frontend/src/metabase/admin/settings/utils.js
  frontend/src/metabase/common/hooks/use-setting/use-setting.ts
  frontend/src/metabase/plugins/components/PluginPlaceholder/PluginPlaceholder.tsx
  frontend/src/metabase/plugins/components/PluginPlaceholder/index.js
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/services.js
Labels: no-backport, .Team/AdminWebapp

#58620 Ensure we use a different connection per `have-select-privilege?` call
  docs/developers-guide/driver-changelog.md
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql_jdbc.clj
  src/metabase/driver/sql_jdbc/sync/describe_database.clj
  src/metabase/driver/sql_jdbc/sync/interface.clj
  test/metabase/driver/sql_jdbc/sync/describe_database_test.clj
Labels: backport, .Team/SemanticLayer

#58749 Update JWT Settings
  e2e/test/scenarios/admin-2/sso/jwt.cy.spec.js
  e2e/test/scenarios/admin-2/sso/shared/helpers.js
  enterprise/backend/src/metabase_enterprise/sso/settings.clj
  enterprise/frontend/src/metabase-enterprise/auth/components/SettingsJWTForm/SettingsJWTForm.tsx
  enterprise/frontend/src/metabase-enterprise/auth/components/SettingsJWTForm/SettingsJWTForm.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/auth/components/SettingsJWTForm/index.ts
  enterprise/frontend/src/metabase-enterprise/auth/index.js
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/settings/selectors/selectors.js
  frontend/src/metabase/api/utils/settings.ts
  frontend/src/metabase/plugins/index.ts
Labels: no-backport, .Team/AdminWebapp

#59009 Move notification components to new folder structure
  frontend/src/metabase/admin/settings/components/SettingsPages/NotificationSettingsPage.tsx
  frontend/src/metabase/admin/settings/components/widgets/Notifications/CreateWebhookModal.tsx
  frontend/src/metabase/admin/settings/components/widgets/Notifications/EditWebhookModal.tsx
  frontend/src/metabase/admin/settings/components/widgets/Notifications/WebhookForm.tsx
  frontend/src/metabase/admin/settings/components/widgets/Notifications/WebhookForm.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/Notifications/utils.ts
  frontend/src/metabase/admin/settings/components/widgets/Notifications/utils.unit.spec.ts
  frontend/src/metabase/admin/settings/selectors/selectors.js
Labels: no-backport, .Team/AdminWebapp

#58875 Allow resetting a required filter to its default value
  e2e/test/scenarios/dashboard-filters/dashboard-filters-reset-clear.cy.spec.ts
  e2e/test/scenarios/native-filters/sql-field-filter.cy.spec.js
  frontend/src/metabase-lib/v1/parameters/utils/parameter-values.js
  frontend/src/metabase/parameters/components/UpdateFilterButton/getUpdateButtonProps.ts
  frontend/src/metabase/parameters/components/widgets/NumberInputWidget/NumberInputWidget.tsx
  frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget/ParameterFieldWidget.tsx
  frontend/src/metabase/parameters/components/widgets/StringInputWidget/StringInputWidget.tsx
  frontend/src/metabase/query_builder/components/template_tags/TagEditorParamParts/DefaultRequiredValueControl.tsx
Labels: no-backport, .Team/Querying, PR-Env

#58839 Disallow aggregations in filters and custom columns
  e2e/test/scenarios/custom-column/cc-typing-suggestion.cy.spec.js
  e2e/test/scenarios/custom-column/custom-column-reproductions.cy.spec.js
  frontend/src/metabase-lib/v1/expressions/diagnostics/diagnostics.unit.spec.ts
  frontend/src/metabase-lib/v1/expressions/diagnostics/expression/check-functions-for-expression-mode.ts
  frontend/src/metabase-lib/v1/expressions/diagnostics/expression/index.ts
  frontend/src/metabase-lib/v1/expressions/index.ts
  frontend/src/metabase-lib/v1/expressions/mode.ts
  frontend/src/metabase/query_builder/components/expressions/Editor/Editor.tsx
  frontend/src/metabase/query_builder/components/expressions/Editor/HelpText/HelpText.stories.tsx
  frontend/src/metabase/query_builder/components/expressions/Editor/HelpText/HelpText.tsx
  frontend/src/metabase/query_builder/components/expressions/Editor/HelpText/tests/common.unit.spec.tsx
  frontend/src/metabase/query_builder/components/expressions/Editor/HelpText/tests/setup.tsx
  frontend/src/metabase/query_builder/components/expressions/Editor/Tooltip/Tooltip.tsx
Labels: backport, .Team/Querying

#59018 Routes for new picker
  src/metabase/actions/api.clj
  test/metabase/actions/api_test.clj
Labels: .Team/Workflows

#59019 🤖 backported "Disallow aggregations in filters and custom columns"
  e2e/test/scenarios/custom-column/cc-typing-suggestion.cy.spec.js
  e2e/test/scenarios/custom-column/custom-column-reproductions.cy.spec.js
  frontend/src/metabase-lib/v1/expressions/diagnostics/diagnostics.unit.spec.ts
  frontend/src/metabase-lib/v1/expressions/diagnostics/expression/check-functions-for-expression-mode.ts
  frontend/src/metabase-lib/v1/expressions/diagnostics/expression/index.ts
  frontend/src/metabase-lib/v1/expressions/index.ts
  frontend/src/metabase-lib/v1/expressions/mode.ts
  frontend/src/metabase/query_builder/components/expressions/Editor/Editor.tsx
  frontend/src/metabase/query_builder/components/expressions/Editor/HelpText/HelpText.stories.tsx
  frontend/src/metabase/query_builder/components/expressions/Editor/HelpText/HelpText.tsx
  frontend/src/metabase/query_builder/components/expressions/Editor/HelpText/tests/common.unit.spec.tsx
  frontend/src/metabase/query_builder/components/expressions/Editor/HelpText/tests/setup.tsx
  frontend/src/metabase/query_builder/components/expressions/Editor/Tooltip/Tooltip.tsx
Labels: was-backported

#58955 Remove data-editing API
  docs/api.html
  enterprise/backend/src/metabase_enterprise/api/routes.clj
  enterprise/backend/src/metabase_enterprise/data_editing/api.clj
  enterprise/backend/test/metabase_enterprise/data_editing/api_test.clj
  src/metabase/premium_features/core.clj
  src/metabase/premium_features/settings.clj
  test/metabase/analytics/stats_test.clj
Labels: .Team/Workflows, double-backport

#59017 Remove package prerelease identifier after 55 gold
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: .Team/Embedding

#59016 Update SDK release workflow after 55 gold
  .github/workflows/release-embedding-sdk.yml
Labels: backport, .Team/Embedding

#59031 🤖 backported "Update SDK release workflow after 55 gold"
  .github/workflows/release-embedding-sdk.yml
Labels: was-backported

#58922 fix: proper input/param mappings for execution endpoints
  enterprise/frontend/src/metabase-enterprise/api/table-data-edit.ts
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/use-table-crud.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/types.ts
  enterprise/frontend/src/metabase-enterprise/table-actions/execution/TableActionExecuteModalContent.tsx
Labels: .Team/Workflows

#59035 🤖 backported "fix incorrect keyset not exists logging during metabase_metadata sync"
  src/metabase/sync/sync_metadata/metabase_metadata.clj
Labels: was-backported

#58807 🤖 backported "Randomize the timing of upgrade checks"
  src/metabase/version/task/upgrade_checks.clj
Labels: was-backported

#58740 Closes VIZ-181: Negative values overlap with x-axis labels, making them unreadable
  frontend/src/metabase/visualizations/echarts/cartesian/option/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/index.unit.spec.ts
Labels: backport, .Team/DashViz

#58805 Closes VIZ-192: Goal line tooltip formatting does not match ticks formatting
  e2e/test/scenarios/visualizations-charts/bar_chart.cy.spec.js
  e2e/test/scenarios/visualizations-charts/line_chart.cy.spec.js
  frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/model/types.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/events.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-chart-events.ts
Labels: backport, .Team/DashViz

#59003 fix: audit adjust to source handles nil schemas
  enterprise/backend/src/metabase_enterprise/audit_app/audit.clj
  enterprise/backend/test/metabase_enterprise/audit_app/audit_test.clj
Labels: .Team/AdminWebapp, double-backport

#59042 🤖 backported "Closes VIZ-181: Negative values overlap with x-axis labels, making them unreadable"
  frontend/src/metabase/visualizations/echarts/cartesian/option/index.ts
  frontend/src/metabase/visualizations/echarts/cartesian/option/index.unit.spec.ts
Labels: was-backported

#59046 🤖 backported "fix: audit adjust to source handles nil schemas"
  enterprise/backend/src/metabase_enterprise/audit_app/audit.clj
  enterprise/backend/test/metabase_enterprise/audit_app/audit_test.clj
Labels: was-backported

#58891 🤖 backported "Make new "appdb" search engine the default starting with v55"
  .github/workflows/e2e-component-tests-embedding-sdk-cross-version.yml
  e2e/test-component/scenarios/embedding-sdk/create-question.cy.spec.tsx
  src/metabase/search/api.clj
  src/metabase/search/settings.clj
  test/metabase/search/api_test.clj
Labels: was-backported

#59056 docs: update offset limitations
  docs/questions/query-builder/expressions-list.md
  docs/questions/query-builder/expressions/offset.md
Labels: Type:Documentation, backport

#59053 🤖 backported "Fix model sigma icon"
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/common/utils/column-groups.ts
  frontend/src/metabase/common/utils/column-groups.unit.spec.ts
  src/metabase/lib/card.cljc
  src/metabase/lib/metadata/calculation.cljc
  test/metabase/lib/card_test.cljc
Labels: was-backported

#58980 🤖 backported "Fix before-and-after :join generative test"
  test/metabase/lib/test_util/generators.cljc
Labels: was-backported

#59062 Fix and test nil native temporal unit
  src/metabase/driver/common/parameters/values.clj
  test/metabase/driver/common/parameters/temporal_units_test.clj
Labels: .Team/Querying

#58824 🤖 backported "Fix zoom drill for clicks on a joined PK column"
  src/metabase/lib/drill_thru/common.cljc
  src/metabase/lib/drill_thru/quick_filter.cljc
  src/metabase/lib/drill_thru/zoom.cljc
  test/metabase/lib/drill_thru_test.cljc
Labels: was-backported

#58999 Test that self-joined columns are independently editable (metadata)
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
Labels: no-backport, .Team/Querying

#59071 🤖 backported "Stabilize flaky mongo tests"
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.js
Labels: was-backported

#58647 static size for watermark background, changing source url
  frontend/src/metabase/visualizations/components/Visualization/Watermark/Watermark.module.css
  frontend/src/metabase/visualizations/components/Visualization/Watermark/Watermark.tsx
  resources/frontend_client/app/assets/img/watermark-background.svg
Labels: no-backport, .Team/AdminWebapp

#58943 Auto-backport workflow improvements
  .github/actions/create-backport/action.yml
  .github/workflows/auto-backport.yml
Labels: .CI & Tests, no-backport, .Team/AdminWebapp

#59066 fix: move metabot migrations back to 001
  resources/migrations/001_update_migrations.yaml
  resources/migrations/056_update_migrations.yaml
Labels: backport, .Team/AdminWebapp

#59045 add e2e tests for optional usage of time grouping
  e2e/test/scenarios/native/native.cy.spec.js
Labels: .Team/Querying

#58907 Add team names to backend modules config
  .clj-kondo/config/modules/config.edn
  .github/team.json
  test/metabase/core/modules_test.clj
Labels: backport, .Team/DevEx

#59051 SEM-370 Hide/show table button not shown when focused but not hovered
  frontend/src/metabase/metadata/pages/DataModel/components/TablePicker/Results.module.css
Labels: no-backport, .Team/SemanticLayer

#59091 docs(sdk): Update SDK version to 0.56.3-esbuild
  enterprise/frontend/src/embedding-sdk/CHANGELOG.md
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: no-backport

#59089 🤖 backported "Remove debugging code"
  frontend/src/metabase/components/UserHasSeen/UserHasSeen.tsx
  frontend/src/metabase/components/UserHasSeen/UserHasSeenAllContext.tsx
Labels: was-backported

#58946 SEM-359 Toasts shown when nothing changed
  e2e/test/scenarios/admin/datamodel/datamodel.cy.spec.js
  frontend/src/metabase/visualizations/components/settings/ChartSettingInput.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingInput.unit.spec.tsx
Labels: backport, .Team/SemanticLayer

#59087 Mallify actions
  .clj-kondo/config/modules/config.edn
  enterprise/backend/src/metabase_enterprise/data_editing/actions.clj
  src/metabase/actions/actions.clj
  src/metabase/actions/args.clj
  src/metabase/actions/core.clj
  src/metabase/actions/execution.clj
  src/metabase/driver/sql_jdbc/actions.clj
  src/metabase/lib/schema/actions.cljc
  test/metabase/driver/sql_jdbc/actions_test.clj
Labels: .Team/Workflows

#59096 docs(sdk): Update SDK version to 0.55.2
  enterprise/frontend/src/embedding-sdk/CHANGELOG.md
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: no-backport

#59033 Ability to specify auth method in new iframe embedding
  e2e/support/helpers/e2e-embedding-iframe-sdk-helpers.ts
  e2e/support/helpers/embedding-sdk-testing/embedding-sdk-helpers.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding/authentication.cy.spec.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/embed.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/types/embed.ts
Labels: .Team/Embedding

#59078 🤖 backported "fix: move metabot migrations back to 001"
  resources/migrations/001_update_migrations.yaml
Labels: was-backported

#59105 chore: replace moment with dayjs in unit tests
  frontend/src/metabase/components/DateTime/DateTime.unit.spec.tsx
  frontend/src/metabase/components/ItemsTable/BaseItemsTable/BaseItemsTable.unit.spec.tsx
  frontend/src/metabase/components/LastEditInfoLabel/LastEditInfoLabel.unit.spec.js
  frontend/src/metabase/visualizations/echarts/cartesian/utils/timeseries.tz.unit.spec.js
Labels: no-backport, .Team/Querying

#59111 🤖 backported "fix typo in authcard"
  frontend/src/metabase/admin/settings/auth/components/AuthCard/AuthCard.tsx
Labels: was-backported

#58939 End-to-end tests for SSO authentication for new iframe embedding
  e2e/support/helpers/e2e-embedding-iframe-sdk-helpers.ts
  e2e/support/helpers/embedding-sdk-testing/embedding-sdk-helpers.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding/authentication.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding/missing-tokens.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding/sdk-iframe-embedding.cy.spec.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/embed.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/types/embed.ts
Labels: backport, .Team/Embedding

#59108 fix(sdk): omit jwt token response from error messages
  enterprise/frontend/src/embedding/auth-common/jwt.ts
Labels: backport, .Team/Embedding

#59114 🤖 backported "fix(sdk): omit jwt token response from error messages"
  enterprise/frontend/src/embedding/auth-common/jwt.ts
Labels: was-backported

#59094 Remove flash of default title when saving a question
  e2e/test/scenarios/question-reproductions/reproductions.cy.spec.ts
  frontend/src/metabase/components/SaveQuestionForm/context.tsx
  frontend/src/metabase/components/SaveQuestionForm/util.ts
Labels: .Team/Querying, double-backport

#59095 Closes VIZ-187 double scrollbar on viz settings
  frontend/src/metabase/query_builder/components/SidebarContent/SidebarContent.module.css
Labels: .Team/DashViz, double-backport

#59121 🤖 backported "Closes VIZ-187 double scrollbar on viz settings"
  frontend/src/metabase/query_builder/components/SidebarContent/SidebarContent.module.css
Labels: was-backported

#58438 s/mirror database/destination database/g
  docs/api.html
  e2e/test/scenarios/admin/database-routing/database-routing-admin.cy.spec.ts
  e2e/test/scenarios/admin/database-routing/database-routing-usage.cy.spec.ts
  e2e/test/scenarios/admin/database-routing/helpers/e2e-database-routing-helpers.ts
  enterprise/backend/src/metabase_enterprise/database_routing/api.clj
  enterprise/backend/src/metabase_enterprise/database_routing/common.clj
  enterprise/backend/src/metabase_enterprise/database_routing/middleware.clj
  enterprise/backend/src/metabase_enterprise/database_routing/model.clj
  enterprise/backend/test/metabase_enterprise/database_routing/api_test.clj
  enterprise/backend/test/metabase_enterprise/database_routing/e2e_test.clj
  enterprise/frontend/src/metabase-enterprise/api/db-routing.ts
  src/metabase/database_routing/core.clj
  src/metabase/query_processor/execute.clj
  src/metabase/query_processor/middleware/enterprise.clj
  src/metabase/query_processor/middleware/process_userland_query.clj
  src/metabase/query_processor/preprocess.clj
  src/metabase/query_processor/store.clj
  src/metabase/query_processor/util.clj
  src/metabase/query_processor/writeback.clj
  src/metabase/warehouses/api.clj
Labels: backport, .Team/AdminWebapp

#59113 🤖 backported "End-to-end tests for SSO authentication for new iframe embedding"
  e2e/support/helpers/component-testing-sdk/component-embedding-sdk-auth-helpers.tsx
  e2e/support/helpers/component-testing-sdk/component-embedding-sdk-helpers.tsx
  e2e/support/helpers/component-testing-sdk/index.ts
  e2e/support/helpers/e2e-embedding-iframe-sdk-helpers.ts
  e2e/support/helpers/embedding-sdk-testing/embedding-sdk-helpers.ts
  e2e/support/helpers/embedding-sdk-testing/index.ts
  e2e/test-component/scenarios/embedding-sdk/collection-browser.cy.spec.tsx
  e2e/test-component/scenarios/embedding-sdk/create-dashboard.cy.spec.tsx
  e2e/test-component/scenarios/embedding-sdk/requests.cy.spec.tsx
  e2e/test/scenarios/embedding/sdk-iframe-embedding/authentication.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding/missing-tokens.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding/sdk-iframe-embedding.cy.spec.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/embed.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/types/embed.ts
Labels: was-backported

#59130 🤖 backported "Auto Focus save button on the SaveQuestion Modal"
  e2e/test/scenarios/question/new.cy.spec.js
  frontend/src/metabase/components/SaveQuestionForm/SaveQuestionForm.tsx
  frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.unit.spec.tsx
Labels: was-backported

#59103 chore: typo in the function name
  frontend/src/metabase/query_builder/selectors.js
  frontend/src/metabase/visualizations/components/LeafletGridHeatMap.jsx
  frontend/src/metabase/visualizations/echarts/cartesian/model/axis.ts
  frontend/src/metabase/visualizations/echarts/cartesian/utils/timeseries.ts
  frontend/src/metabase/visualizations/echarts/cartesian/utils/timeseries.tz.unit.spec.js
  frontend/src/metabase/visualizations/echarts/cartesian/utils/timeseries.unit.spec.js
  frontend/src/metabase/visualizations/lib/numeric.js
  frontend/src/metabase/visualizations/lib/numeric.unit.spec.js
Labels: no-backport, .Team/Querying

#59129 fix: increase starburst percentile acceptable epsilon
  test/metabase/query_processor/middleware/metrics_test.clj
Labels: .Team/Drivers, double-backport

#59134 🤖 backported "fix: increase starburst percentile acceptable epsilon"
  test/metabase/query_processor/middleware/metrics_test.clj
Labels: was-backported

#59115 fix(sdk): Properly expose `initialParameters` type on dashboard components
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/ConnectedDashboard.tsx
  enterprise/frontend/src/embedding-sdk/hooks/private/use-sdk-dashboard-params.ts
  enterprise/frontend/src/embedding-sdk/index.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/types/embed.ts
  frontend/src/metabase/dashboard/actions/data-fetching.ts
  frontend/src/metabase/embedding-sdk/types/dashboard.ts
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboard.tsx
Labels: .Team/Embedding, double-backport

#59162 🤖 backported "fix(sdk): Properly expose `initialParameters` type on dashboard components"
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/ConnectedDashboard.tsx
  enterprise/frontend/src/embedding-sdk/hooks/private/use-sdk-dashboard-params.ts
  enterprise/frontend/src/embedding-sdk/index.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/types/embed.ts
  frontend/src/metabase/dashboard/actions/data-fetching.ts
  frontend/src/metabase/embedding-sdk/types/dashboard.ts
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboard.tsx
Labels: was-backported

#59012 Skip uploading test results to Trunk.io for draft PRs
  .github/actions/upload-test-results/action.yml
Labels: .CI & Tests, no-backport, .Team/AdminWebapp

#59178 🤖 backported "no archived collections in perm graph"
  src/metabase/models/collection/graph.clj
  test/metabase/api/collection_test.clj
Labels: was-backported

#58405 In the main nav, move 'Browse databases' above 'Browse models'
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/BrowseNavSection.tsx
Labels: no-backport, .Team/AdminWebapp

#59170 chore: deduplicate everything
  frontend/src/metabase/admin/performance/components/StrategyForm.tsx
  frontend/src/metabase/lib/colors/groups.ts
  frontend/src/metabase/lib/formatting/numbers.tsx
  frontend/src/metabase/services.js
  frontend/src/metabase/setup/components/UserForm/UserForm.styled.tsx
  frontend/src/metabase/setup/components/UserForm/UserForm.tsx
  frontend/src/metabase/visualizations/echarts/cartesian/option/axis.ts
  frontend/src/metabase/visualizations/lib/settings/column.js
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SettingsComponents/MenuItem.module.css
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SettingsComponents/MenuItem.styled.tsx
  package.json
  yarn.lock
Labels: .Team/Querying

#59182 🤖 backported "static size for watermark background, changing source url"
  frontend/src/metabase/visualizations/components/Visualization/Watermark/Watermark.module.css
  frontend/src/metabase/visualizations/components/Visualization/Watermark/Watermark.tsx
  resources/frontend_client/app/assets/img/watermark-background.svg
Labels: was-backported

#59102 wip: more field types for described action form
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/EditTableDataContainer.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/inputs_v2/ActionInputSearchableSelect.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/inputs_v2/ParameterActionInput.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/inputs_v2/types.ts
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/inputs_v2/use-action-input-searchable-options.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/modals/ActionFormModalParameter.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/types.ts
Labels: .Team/Workflows

#59080 Don't count dashboard subscriptions as a reason to count a card as recently viewed
  src/metabase/activity_feed/events/recent_views.clj
  test/metabase/events/recent_views_test.clj
Labels: .Team/AdminWebapp, double-backport

#59189 __METABASE_ROUTER__ instead of primary db
  docs/permissions/database-routing.md
Labels: Type:Documentation, backport
