Repository metabase/metabase, pull requests merged in 2025-02, with the labels that each got.

#53096 🤖 backported "docs - fixes link to blog post"
  docs/databases/connecting.md
Labels: was-backported

#52810 [csv-export] Follow-up optimizations to CSV pivotted export
  src/metabase/query_processor/pivot/postprocess.clj
  src/metabase/util/performance.clj
  test/metabase/util/performance_test.clj
Labels: backport

#53101 🤖 backported "[csv-export] Follow-up optimizations to CSV pivotted export"
  src/metabase/query_processor/pivot/postprocess.clj
  src/metabase/util/performance.clj
  test/metabase/util/performance_test.clj
Labels: was-backported

#52680 Proper title for cards when visualization is in error
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.unit.spec.js
Labels: backport, .Team/DashViz

#53103 🤖 backported "Proper title for cards when visualization is in error"
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.unit.spec.js
Labels: was-backported

#53104 update hawk to silence warnings about algo.generic/abs override
  deps.edn
Labels: no-backport

#52896 fix(entity-id): show 404 for entity id that starts with digits
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/question/questions-entity-id.cy.spec.ts
  frontend/src/metabase/routes-stable-id-aware.tsx
  frontend/src/metabase/routes.jsx
Labels: backport, .Team/Embedding

#53106 stabilize flaky browse.cy.spec.ts tests
  e2e/test/scenarios/metrics/browse.cy.spec.ts
Labels: backport

#53109 🤖 backported "stabilize flaky browse.cy.spec.ts tests"
  e2e/test/scenarios/metrics/browse.cy.spec.ts
Labels: was-backported

#53094 Dont run redshift upload tests on PRs
  .github/workflows/drivers.yml
Labels: .CI & Tests, backport, .Team/AdminWebapp

#53113 🤖 backported "Dont run redshift upload tests on PRs"
  .github/workflows/drivers.yml
Labels: was-backported

#52853 [chore] Bump BE deps at the start of Metabase 54
  deps.edn
  modules/drivers/bigquery-cloud-sdk/deps.edn
  modules/drivers/mongo/deps.edn
  modules/drivers/presto-jdbc/deps.edn
  modules/drivers/redshift/deps.edn
  modules/drivers/snowflake/deps.edn
  modules/drivers/sqlite/deps.edn
Labels: no-backport, .Team/Querying

#52929 🤖 backported "Stop drilling down past day in DateType"
  src/metabase/lib/filter/update.cljc
  test/metabase/lib/filter/update_test.cljc
Labels: was-backported

#53047 🤖 backported "ci: find css variables that are used but never defined"
  .github/workflows/frontend.yml
  bin/find-never-defined-css-variables/find-never-defined-css-variables.ts
  bin/find-never-defined-css-variables/find-never-defined-css-variables.unit.spec.ts
  package.json
Labels: was-backported

#53108 🤖 backported "fix(entity-id): show 404 for entity id that starts with digits"
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  e2e/test/scenarios/question/questions-entity-id.cy.spec.ts
  frontend/src/metabase/routes-stable-id-aware.tsx
  frontend/src/metabase/routes.jsx
Labels: was-backported

#52921 Symbol for swedish krona is "kr" not "Skr"
  src/metabase/util/currency.cljc
Labels: backport, .Team/AdminWebapp

#53120 Manual backport "ci: find css variables that are used but never defined (#52910)"
  .github/workflows/frontend.yml
  bin/find-never-defined-css-variables/find-never-defined-css-variables.ts
  bin/find-never-defined-css-variables/find-never-defined-css-variables.unit.spec.ts
  enterprise/frontend/src/embedding-sdk/components/private/EditorViewControl/EditorViewControl.tsx
  frontend/src/metabase/home/components/EmbedHomepage/Badge.ts
  package.json
Labels: .Team/Embedding

#53114 🤖 backported "ci: find css variables that are used but never defined"
  .github/workflows/frontend.yml
  bin/find-never-defined-css-variables/find-never-defined-css-variables.ts
  bin/find-never-defined-css-variables/find-never-defined-css-variables.unit.spec.ts
  enterprise/frontend/src/embedding-sdk/components/private/EditorViewControl/EditorViewControl.tsx
  enterprise/frontend/src/embedding-sdk/test/storybook-themes.ts
  frontend/src/metabase/home/components/EmbedHomepage/Badge.ts
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.module.css
  package.json
Labels: was-backported

#53123 🤖 backported "Symbol for swedish krona is "kr" not "Skr""
  src/metabase/util/currency.cljc
Labels: was-backported

#52880 fix(sdk): fix minWidth console error in dashboard grid
  frontend/src/metabase/dashboard/components/grid/utils.ts
  frontend/src/metabase/dashboard/components/grid/utils.unit.spec.ts
Labels: backport, .Team/Embedding

#52982 Fix enum filtering on postgres
  docs/developers-guide/driver-changelog.md
  src/metabase/driver.clj
  src/metabase/driver/postgres.clj
  src/metabase/driver/sql_jdbc/execute.clj
  src/metabase/driver/sql_jdbc/sync/interface.clj
  src/metabase/query_processor/middleware/results_metadata.clj
  test/metabase/api/table_test.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/query_processor/middleware/results_metadata_test.clj
Labels: no-backport, .Team/Querying, .Team/Drivers

#53069 🤖 backported "Ensure the classloader is in task thread contexts"
  src/metabase/sync/concurrent.clj
Labels: was-backported

#53060 🤖 backported "Don't cast dates when doing a dateadd on h2"
  src/metabase/driver/h2.clj
  test/metabase/driver/h2_test.clj
Labels: was-backported

#53002 Elide data in task_history.details which can get very large
  src/metabase/models/interface.clj
  src/metabase/models/task_history.clj
  src/metabase/util/string.clj
  test/metabase/models/interface_test.clj
  test/metabase/util/string_test.clj
Labels: backport, .Team/AdminWebapp

#53136 🤖 backported "Elide data in task_history.details which can get very large"
  src/metabase/models/interface.clj
  src/metabase/models/task_history.clj
  src/metabase/util/string.clj
  test/metabase/models/interface_test.clj
  test/metabase/util/string_test.clj
Labels: was-backported

#53138 🤖 backported "Symbol for swedish krona is "kr" not "Skr""
  src/metabase/util/currency.cljc
Labels: was-backported

#52934 Check connectivity on startup
  .clj-kondo/config.edn
  enterprise/backend/test/metabase_enterprise/scim/v2/api_test.clj
  src/metabase/analytics/prometheus.clj
  src/metabase/core/core.clj
  src/metabase/models/database.clj
  test/metabase/analytics/prometheus_test.clj
  test/metabase/channel/email_test.clj
  test/metabase/driver_test.clj
  test/metabase/models/database_test.clj
  test/metabase/query_processor/middleware/metrics_test.clj
  test/metabase/server/middleware/sdk_test.clj
  test/metabase/test.clj
  test/metabase/test/data/interface.clj
  test/metabase/test/util.clj
Labels: backport, .Team/Drivers

#51948 Add hostname support to BigQuery
  modules/drivers/bigquery-cloud-sdk/resources/metabase-plugin.yaml
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj
  modules/drivers/bigquery-cloud-sdk/test/metabase/driver/bigquery_cloud_sdk_test.clj
Labels: External

#53074 🤖 backported "Recognize year-of-era"
  src/metabase/legacy_mbql/schema.cljc
  test/metabase/legacy_mbql/schema_test.cljc
Labels: was-backported

#52925 Fix breakout by drill through context menu for multi-stage queries
  e2e/test/scenarios/filters-reproductions/filters-reproductions.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/drillthroughs/table_drills.cy.spec.js
  frontend/src/metabase-lib/drills.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/querying/drills/utils/pivot-drill.tsx
  src/metabase/lib/drill_thru/pivot.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/schema/drill_thru.cljc
  test/metabase/lib/drill_thru/pivot_test.cljc
Labels: backport, .Team/Querying

#53093 Order the query in `expression-using-aggregation-test`
  test/metabase/query_processor_test/expressions_test.clj
Labels: backport, .Team/Querying, .Team/Drivers

#53146 🤖 backported "Order the query in `expression-using-aggregation-test`"
  test/metabase/query_processor_test/expressions_test.clj
Labels: was-backported

#52977 Support not specifying is_group_manager in /api/user calls on Pro
  enterprise/backend/src/metabase_enterprise/advanced_permissions/models/permissions/group_manager.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/api/group_manager_test.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/models/permissions/group_manager_test.clj
Labels: backport, .Team/AdminWebapp

#53147 🤖 backported "Support not specifying is_group_manager in /api/user calls on Pro"
  enterprise/backend/src/metabase_enterprise/advanced_permissions/models/permissions/group_manager.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/api/group_manager_test.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/models/permissions/group_manager_test.clj
Labels: was-backported

#53152 🤖 backported "Support not specifying is_group_manager in /api/user calls on Pro"
  enterprise/backend/src/metabase_enterprise/advanced_permissions/models/permissions/group_manager.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/api/group_manager_test.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/models/permissions/group_manager_test.clj
Labels: was-backported

#53160 ensure that the link abstracted from element is not empty
  e2e/test/scenarios/dashboard/dashboard-questions.cy.spec.js
Labels: .CI & Tests, backport

#53161 🤖 backported "ensure that the link abstracted from element is not empty"
  e2e/test/scenarios/dashboard/dashboard-questions.cy.spec.js
Labels: was-backported

#53105 Update SDK usage wording
  docs/embedding/sdk/authentication.md
  docs/embedding/sdk/dashboards.md
Labels: backport

#53163 🤖 backported "Update SDK usage wording"
  docs/embedding/sdk/authentication.md
  docs/embedding/sdk/dashboards.md
Labels: was-backported

#52964 Simple data picker UI
  frontend/src/metabase/embedding-sdk/components/SimpleDataPicker/SimpleDataPicker.stories.tsx
  frontend/src/metabase/embedding-sdk/components/SimpleDataPicker/SimpleDataPicker.tsx
  frontend/src/metabase/embedding-sdk/components/SimpleDataPicker/index.ts
  loki.config.js
Labels: .Team/Embedding

#53143 Add /api/ee/ai-fix-sql/fix endpoint
  enterprise/backend/src/metabase_enterprise/ai_sql_fixer/api.clj
  enterprise/backend/src/metabase_enterprise/api/routes.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/client.clj
Labels: Metabot/General, .Team/Querying

#53153 Autofix SQL button
  enterprise/backend/src/metabase_enterprise/ai_sql_fixer/api.clj
  enterprise/backend/test/metabase_enterprise/api/session_test.clj
  enterprise/frontend/src/metabase-enterprise/ai-sql-fixer/components/FixNativeQueryButton/FixNativeQueryButton.tsx
  enterprise/frontend/src/metabase-enterprise/ai-sql-fixer/components/FixNativeQueryButton/index.ts
  enterprise/frontend/src/metabase-enterprise/ai-sql-fixer/components/FixNativeQueryButton/utils.ts
  enterprise/frontend/src/metabase-enterprise/ai-sql-fixer/index.ts
  enterprise/frontend/src/metabase-enterprise/api/ai-sql-fixer.ts
  enterprise/frontend/src/metabase-enterprise/api/index.ts
  enterprise/frontend/src/metabase-enterprise/plugins.js
  frontend/src/metabase-types/api/ai-fix-sql.ts
  frontend/src/metabase-types/api/dataset.ts
  frontend/src/metabase-types/api/index.ts
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase-types/store/mocks/qb.ts
  frontend/src/metabase-types/store/qb.ts
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/query_builder/components/QueryVisualization.jsx
  frontend/src/metabase/query_builder/components/VisualizationError/VisualizationError.module.css
  frontend/src/metabase/query_builder/components/VisualizationError/VisualizationError.tsx
  frontend/src/metabase/query_builder/defaults.ts
  frontend/src/metabase/query_builder/reducers.js
  frontend/src/metabase/query_builder/selectors.js
  frontend/src/metabase/ui/components/icons/Icon/icons/index.ts
  frontend/src/metabase/ui/components/icons/Icon/icons/metabot.svg
  frontend/src/metabase/ui/components/icons/Icon/icons/metabot_sad.svg
  src/metabase/analytics/stats.clj
  src/metabase/premium_features/core.clj
  src/metabase/public_settings.clj
Labels: no-backport, .Team/Querying, PR-Env

#53110 convert header breadcrumbs components to typescript
  frontend/src/metabase/lib/urls/collections.ts
  frontend/src/metabase/query_builder/components/SavedQuestionHeaderButton/CollectionIcon.tsx
  frontend/src/metabase/query_builder/components/SavedQuestionHeaderButton/SavedQuestionHeaderButton.tsx
  frontend/src/metabase/query_builder/components/SavedQuestionHeaderButton/SavedQuestionHeaderButton.unit.spec.js
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/HeaderBreadcrumbs/HeaderBreadcrumbs.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/HeaderBreadcrumbs/index.js
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/HeaderCollectionBadge/HeaderCollectionBadge.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/HeaderCollectionBadge/index.ts
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/DataSourceCrumbs.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/QuestionDataSource.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/SourceDatasetBreadcrumbs.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/SourceQuestionBreadcrumbs.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/utils.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/SavedQuestionLeftSide/SavedQuestionLeftSide.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/index.ts
Labels: backport, .Team/Querying, PR-Env

#53150 Add fraserdrops to team lists
  .github/team.json
  release/github-slack-map.json
Labels: no-backport, .Team/AdminWebapp

#53176 Mark browse metrics flakes as flaky
  e2e/test/scenarios/metrics/browse.cy.spec.ts
Labels: backport, .Team/AdminWebapp

#52781 [Cards in Dashboards] Trash UI when removing last dashcard for a dashboard question
  e2e/test/scenarios/dashboard/dashboard-questions.cy.spec.js
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardActionsPanel.tsx
  frontend/src/metabase/dashboard/components/DashCard/Dashcard.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.tsx
Labels: backport, .Team/AdminWebapp, PR-Env

#52916 Fix home page Metabot spacing on large screens
  frontend/src/metabase/home/components/HomeGreeting/HomeGreeting.styled.tsx
  frontend/src/metabase/home/components/HomeGreeting/HomeGreeting.tsx
Labels: backport, .Team/AdminWebapp

#52913 Close CSV upload modal on escape press
  frontend/src/metabase/collections/components/CollectionHeader/CollectionUploadInfoModal.tsx
  frontend/src/metabase/collections/components/CollectionHeader/tests/common.unit.spec.tsx
Labels: backport, .Team/AdminWebapp

#52822 fix(sdk): echarts tooltip is cut off below the viewport height
  e2e/support/helpers/e2e-element-visibility-helpers.ts
  e2e/support/helpers/e2e-visual-tests-helpers.js
  e2e/test-component/scenarios/embedding-sdk/tooltip-reproductions.cy.spec.tsx
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.js
  enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.ts
  enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.unit.spec.ts
  frontend/src/metabase/components/Popover/TippyPopover.tsx
  frontend/src/metabase/components/Popover/TippyPopover.unit.spec.js
  frontend/src/metabase/visualizations/echarts/tooltip/index.tsx
Labels: no-backport, .Team/Embedding

#53187 🤖 backported "[Cards in Dashboards] Trash UI when removing last dashcard for a dashboard question"
  e2e/test/scenarios/dashboard/dashboard-questions.cy.spec.js
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardActionsPanel.tsx
  frontend/src/metabase/dashboard/components/DashCard/Dashcard.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.tsx
Labels: was-backported

#53189 🤖 backported "Close CSV upload modal on escape press"
  frontend/src/metabase/collections/components/CollectionHeader/CollectionUploadInfoModal.tsx
  frontend/src/metabase/collections/components/CollectionHeader/tests/common.unit.spec.tsx
Labels: was-backported

#53191 🤖 backported "fix(sdk): echarts tooltip is cut off below the viewport height"
  e2e/support/helpers/e2e-element-visibility-helpers.ts
  e2e/support/helpers/e2e-visual-tests-helpers.js
  e2e/test-component/scenarios/embedding-sdk/tooltip-reproductions.cy.spec.tsx
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.js
  enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.ts
  enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.unit.spec.ts
  frontend/src/metabase/components/Popover/TippyPopover.tsx
  frontend/src/metabase/components/Popover/TippyPopover.unit.spec.js
  frontend/src/metabase/visualizations/echarts/tooltip/index.tsx
Labels: was-backported

#53167 fixed logo to support opacity and color props. looks correct in admin…
  frontend/src/metabase/components/LogoIcon/LogoIcon.jsx
  resources/frontend_client/app/assets/img/logo.svg
Labels: backport, .Team/AdminWebapp

#53188 🤖 backported "Fix home page Metabot spacing on large screens"
  frontend/src/metabase/home/components/HomeGreeting/HomeGreeting.styled.tsx
  frontend/src/metabase/home/components/HomeGreeting/HomeGreeting.tsx
Labels: was-backported

#52995 🤖 backported "fix(sdk): Remove ExplicitSize findDOMNode console errors"
  enterprise/frontend/src/metabase-enterprise/license/components/BillingInfo/BillingInfoTable.tsx
  frontend/src/metabase/ErrorBoundary.tsx
  frontend/src/metabase/components/DebouncedFrame/DebouncedFrame.jsx
  frontend/src/metabase/components/ErrorPages/ErrorPages.tsx
  frontend/src/metabase/components/ExplicitSize/ExplicitSize.tsx
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.tsx
  frontend/src/metabase/components/LoadingAndErrorWrapper/LoadingAndErrorWrapper.tsx
  frontend/src/metabase/core/components/TabRow/TabRow.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.unit.spec.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditorInner.jsx
  frontend/src/metabase/query_builder/components/DatasetEditor/index.js
  frontend/src/metabase/query_builder/components/DatasetEditor/index.ts
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx
  frontend/src/metabase/query_builder/components/view/View/View/View.jsx
  frontend/src/metabase/querying/metrics/components/MetricEditor/MetricEditor.tsx
  frontend/src/metabase/visualizations/components/CardRenderer.jsx
  frontend/src/metabase/visualizations/components/ChartWithLegend.jsx
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx
  frontend/src/metabase/visualizations/components/TableSimple/TableSimple.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.tsx
Labels: was-backported

#53155 update to latest GraalVM JS version
  bin/build/src/build/licenses.clj
  deps.edn
Labels: no-backport, .Team/Workflows

#53196 🤖 backported "fixed logo to support opacity and color props. looks correct in admin…"
  frontend/src/metabase/components/LogoIcon/LogoIcon.jsx
  resources/frontend_client/app/assets/img/logo.svg
Labels: was-backported

#53182 docs: in clarification
  docs/questions/query-builder/expressions/in.md
Labels: Type:Documentation, backport

#53200 🤖 backported "docs: in clarification"
  docs/questions/query-builder/expressions/in.md
Labels: was-backported

#53072 🤖 backported "Fix `all-indexes->field-ids` generating queries with too many parameters"
  src/metabase/sync/sync_metadata/indexes.clj
  test/metabase/sync/sync_metadata/indexes_test.clj
Labels: was-backported

#53099 Introduce the Upsell Banner component
  frontend/src/metabase/admin/upsells/components/UpsellBanner.mdx
  frontend/src/metabase/admin/upsells/components/UpsellBanner.stories.tsx
  frontend/src/metabase/admin/upsells/components/UpsellBanner.tsx
  frontend/src/metabase/admin/upsells/components/UpsellCard.tsx
  frontend/src/metabase/admin/upsells/components/Upsells.module.css
  frontend/src/metabase/admin/upsells/components/Upsells.styled.tsx
  frontend/src/metabase/admin/upsells/components/index.ts
Labels: no-backport

#52375 [Notification] Card notification archive when send_once = true
  .clj-kondo/config.edn
  src/metabase/models/notification.clj
  src/metabase/notification/payload/impl/card.clj
  src/metabase/task/notification.clj
  test/metabase/models/notification_test.clj
  test/metabase/notification/payload/impl/card_test.clj
  test/metabase/notification/test_util.clj
Labels: .Team/Workflows

#52109 [Notification] unsubscribe notification APIs
  src/metabase/api/notification/unsubscribe.clj
  src/metabase/api/pulse/unsubscribe.clj
  src/metabase/api/routes.clj
  src/metabase/channel/email/messages.clj
  src/metabase/channel/email/notification_card.hbs
  src/metabase/channel/impl/email.clj
  src/metabase/events/audit_log.clj
  test/metabase/api/notification/unsubscribe_test.clj
  test/metabase/notification/payload/impl/card_test.clj
Labels: .Team/Workflows

#53203 Add e2e tests checking high-visibility pages in top locales
  e2e/test/scenarios/i18n/i18n.cy.spec.ts
  frontend/src/metabase/account/profile/components/UserProfileForm/UserProfileForm.tsx
Labels: backport, .Team/AdminWebapp

#53206 🤖 backported "Add e2e tests checking high-visibility pages in top locales"
  e2e/test/scenarios/i18n/i18n.cy.spec.ts
  frontend/src/metabase/account/profile/components/UserProfileForm/UserProfileForm.tsx
Labels: was-backported

#53192 🤖 backported "fix(sdk): echarts tooltip is cut off below the viewport height"
  e2e/support/helpers/e2e-element-visibility-helpers.ts
  e2e/support/helpers/e2e-visual-tests-helpers.js
  e2e/test-component/scenarios/embedding-sdk/tooltip-reproductions.cy.spec.tsx
  e2e/test/scenarios/visualizations-charts/visualizations-charts-reproductions.cy.spec.js
  enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.ts
  enterprise/frontend/src/embedding-sdk/lib/theme/get-embedding-theme.unit.spec.ts
  frontend/src/metabase/components/Popover/TippyPopover.tsx
  frontend/src/metabase/components/Popover/TippyPopover.unit.spec.js
  frontend/src/metabase/embedding-sdk/theme/default-component-theme.ts
  frontend/src/metabase/styled-components/theme/css-variables.ts
  frontend/src/metabase/visualizations/echarts/tooltip/index.tsx
Labels: was-backported

#53081 Don't infer join aliases when replacing a join
  src/metabase/lib/join.cljc
  src/metabase/lib/remove_replace.cljc
  test/metabase/lib/remove_replace_test.cljc
Labels: backport, .Team/Querying

#53164 🤖 backported "feat(sdk): apply theming to interactive question modules"
  .loki/reference/chrome_laptop_Inputs_DatePicker_Dates_range_SDK.png
  .storybook/preview.tsx
  docs/embedding/sdk/appearance.md
  e2e/support/helpers/component-testing-sdk/component-embedding-sdk-question-helpers.tsx
  e2e/test-component/scenarios/embedding-sdk/interactive-question-theming.cy.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/ChartTypeSelectorList/ChartTypeDropdown.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/EditorButton.module.css
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/EditorButton.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/QuestionSettings/QuestionSettingsDropdown/QuestionSettingsDropdown.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/util/BadgeList/BadgeList.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/util/BadgeList/BadgeListItem/BadgeListItem.module.css
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/util/BadgeList/BadgeListItem/BadgeListItem.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/styles/ToolbarButton.module.css
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult/InteractiveQuestionResult.tsx
  enterprise/frontend/src/embedding-sdk/components/private/SdkThemeProvider.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/EditableDashboard.stories.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion-themed.stories.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.stories.tsx
  enterprise/frontend/src/embedding-sdk/test/storybook-dark-theme.ts
  enterprise/frontend/src/embedding-sdk/test/storybook-themes.ts
  frontend/src/metabase/css/core/colors.module.css
  frontend/src/metabase/embedding-sdk/theme/MetabaseTheme.ts
  frontend/src/metabase/embedding-sdk/theme/css-vars-to-sdk-theme.ts
  frontend/src/metabase/embedding-sdk/theme/default-component-theme.ts
  frontend/src/metabase/embedding-sdk/theme/dynamic-css-vars-config.ts
  frontend/src/metabase/embedding-sdk/theme/dynamic-css-vars.ts
  frontend/src/metabase/embedding-sdk/theme/embedding-color-palette.ts
  frontend/src/metabase/embedding-sdk/types/private/css-variables.ts
  frontend/src/metabase/embedding-sdk/types/utils.ts
  frontend/src/metabase/query_builder/components/LimitInput.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.module.css
  frontend/src/metabase/query_builder/components/expressions/ExpressionWidgetInfo/ExpressionWidgetInfo.module.css
  frontend/src/metabase/querying/notebook/components/NotebookStep/NotebookActionButton/NotebookActionButton.module.css
  frontend/src/metabase/styled-components/containers/GlobalStyles/GlobalStyles.tsx
  frontend/src/metabase/styled-components/theme/css-variables.ts
Labels: was-backported

#53165 fix(sdk): remove error about stageIndex prop being passed to dom element
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/Filter/FilterDropdown/FilterDropdown.tsx
Labels: backport, .Team/Embedding

#53212 🤖 backported "fix(sdk): remove error about stageIndex prop being passed to dom element"
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/Filter/FilterDropdown/FilterDropdown.tsx
Labels: was-backported

#52539 Fix Flake: 16559
  e2e/support/helpers/e2e-dashboard-helpers.ts
  e2e/test/scenarios/dashboard/dashboard-reproductions.cy.spec.js
  frontend/src/metabase/dashboard/components/DashboardHeader/buttons/DashboardInfoButton.tsx
Labels: .CI & Tests, backport, flaky-test-fix, .Team/AdminWebapp

#53219 🤖 backported "Fix Flake: 16559"
  e2e/support/helpers/e2e-dashboard-helpers.ts
  e2e/test/scenarios/dashboard/dashboard-reproductions.cy.spec.js
  frontend/src/metabase/dashboard/components/DashboardHeader/buttons/DashboardInfoButton.tsx
Labels: was-backported

#52885 fix(sdk): remove unsafe lifecycle errors from Visualization
  e2e/support/helpers/component-testing-sdk/component-embedding-sdk-console-helpers.tsx
  e2e/support/helpers/component-testing-sdk/component-embedding-sdk-helpers.tsx
  e2e/support/helpers/component-testing-sdk/component-embedding-sdk-question-helpers.tsx
  e2e/support/helpers/component-testing-sdk/index.ts
  e2e/test-component/scenarios/embedding-sdk/interactive-question.cy.spec.tsx
  e2e/test-component/scenarios/embedding-sdk/tooltip-reproductions.cy.spec.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
Labels: backport, .Team/Embedding

#53169 disable video recording on snapshots and delete videos on success
  e2e/support/config.js
Labels: .CI & Tests, backport

#53166 🤖 backported "feat(sdk): apply theming to interactive question modules"
  .loki/reference/chrome_laptop_Inputs_DatePicker_Dates_range_SDK.png
  .storybook/preview.tsx
  docs/embedding/sdk/appearance.md
  e2e/support/helpers/component-testing-sdk/component-embedding-sdk-question-helpers.tsx
  e2e/test-component/scenarios/embedding-sdk/interactive-question-theming.cy.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/ChartTypeSelectorList/ChartTypeDropdown.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/EditorButton.module.css
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/EditorButton.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/QuestionSettings/QuestionSettingsDropdown/QuestionSettingsDropdown.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/util/BadgeList/BadgeList.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/util/BadgeList/BadgeListItem/BadgeListItem.module.css
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/util/BadgeList/BadgeListItem/BadgeListItem.tsx
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/styles/ToolbarButton.module.css
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestionResult/InteractiveQuestionResult.tsx
  enterprise/frontend/src/embedding-sdk/components/private/SdkThemeProvider.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/EditableDashboard.stories.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion-themed.stories.tsx
  enterprise/frontend/src/embedding-sdk/components/public/InteractiveQuestion/InteractiveQuestion.stories.tsx
  enterprise/frontend/src/embedding-sdk/test/storybook-dark-theme.ts
  enterprise/frontend/src/embedding-sdk/test/storybook-themes.ts
  frontend/src/metabase/embedding-sdk/theme/MetabaseTheme.ts
  frontend/src/metabase/embedding-sdk/theme/css-vars-to-sdk-theme.ts
  frontend/src/metabase/embedding-sdk/theme/default-component-theme.ts
  frontend/src/metabase/embedding-sdk/theme/dynamic-css-vars-config.ts
  frontend/src/metabase/embedding-sdk/theme/dynamic-css-vars.ts
  frontend/src/metabase/embedding-sdk/theme/embedding-color-palette.ts
  frontend/src/metabase/embedding-sdk/types/private/css-variables.ts
  frontend/src/metabase/embedding-sdk/types/utils.ts
  frontend/src/metabase/query_builder/components/LimitInput.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.module.css
  frontend/src/metabase/styled-components/containers/GlobalStyles/GlobalStyles.tsx
  frontend/src/metabase/styled-components/theme/css-variables.ts
Labels: was-backported

#53221 🤖 backported "fix(sdk): remove unsafe lifecycle errors from Visualization"
  e2e/support/helpers/component-testing-sdk/component-embedding-sdk-console-helpers.tsx
  e2e/support/helpers/component-testing-sdk/component-embedding-sdk-helpers.tsx
  e2e/support/helpers/component-testing-sdk/component-embedding-sdk-question-helpers.tsx
  e2e/support/helpers/component-testing-sdk/index.ts
  e2e/test-component/scenarios/embedding-sdk/interactive-question.cy.spec.tsx
  e2e/test-component/scenarios/embedding-sdk/tooltip-reproductions.cy.spec.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
Labels: was-backported

#53224 docs(sdk): Update SDK version to 0.53.2
  enterprise/frontend/src/embedding-sdk/CHANGELOG.md
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: no-backport

#53225 docs(sdk): Update SDK version to 0.52.9
  enterprise/frontend/src/embedding-sdk/CHANGELOG.md
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: no-backport

#53107 fix(sdk): fixes `NotFoundError: Failed to execute 'removeChild' on 'Node'` on nextjs app router when a TableInteractive component is rendered
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx
Labels: backport, .Team/Embedding

#53195 Add query-metric tool endpoint
  enterprise/backend/src/metabase_enterprise/metabot_v3/api.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/filters.clj
Labels: Metabot/Tools

#53222 🤖 backported "fix(sdk): remove unsafe lifecycle errors from Visualization"
  e2e/support/helpers/component-testing-sdk/component-embedding-sdk-console-helpers.tsx
  e2e/support/helpers/component-testing-sdk/component-embedding-sdk-helpers.tsx
  e2e/support/helpers/component-testing-sdk/component-embedding-sdk-question-helpers.tsx
  e2e/support/helpers/component-testing-sdk/index.ts
  e2e/test-component/scenarios/embedding-sdk/interactive-question.cy.spec.tsx
  e2e/test-component/scenarios/embedding-sdk/tooltip-reproductions.cy.spec.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
Labels: was-backported

#53217 fix: allow replacing a question with a long name
  frontend/src/metabase/components/SaveQuestionForm/schema.ts
  frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.unit.spec.tsx
Labels: backport, .Team/Querying

#53139 Add legalese modal to present SDK terms
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkLegaleseModal/EmbeddingSdkLegaleseModal.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkLegaleseModal/EmbeddingSdkLegaleseModal.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkLegaleseModal/index.ts
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/EmbeddingSdkSettings.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/index.ts
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/tests/common.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/tests/premium.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/tests/setup.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/tests/util.ts
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSettings.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/index.ts
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingSdkOptionCard/EmbeddingSdkOptionCard.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingSdkOptionCard/tests/common.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingSdkOptionCard/tests/premium.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingSdkOptionCard/tests/setup.tsx
  frontend/src/metabase/admin/settings/components/widgets/SettingTextInput/SettingTextInput.tsx
  src/metabase/util/embed.clj
  test_resources/serialization_baseline/settings.yaml
Labels: backport, .Team/Embedding

#53183 [WIP] Querying generative test
  .github/workflows/generative-query-test.yml
  test/metabase/lib/test_util/generators.cljc
  test/metabase/lib/test_util/generators/filters.cljc
  test/metabase/lib/test_util/generators/util.cljc
  test/metabase/lib/test_util/random.clj
  test/metabase/query_processor_test/generative_test.clj
  test_config/log4j2-test.xml
Labels: no-backport, .Team/Querying

#53228 🤖 backported "fix(sdk): fixes `NotFoundError: Failed to execute 'removeChild' on 'Node'` on nextjs app router when a TableInteractive component is rendered"
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx
Labels: was-backported

#53213 fix(sdk): remove unsafe lifecycle errors from DashboardGrid
  e2e/support/helpers/component-testing-sdk/component-embedding-sdk-console-helpers.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.tsx
  frontend/src/metabase/dashboard/grid-utils.ts
Labels: backport, .Team/Embedding

#53162 Keep old Search Engine for 53 gold release
  .github/workflows/e2e-test.yml
  e2e/runner/cypress-runner-backend.js
  src/metabase/public_settings.clj
Labels: .Team/Workflows

#53229 Fix search index update job restart issue
  src/metabase/task/search_index.clj
Labels: backport, .Team/Workflows

#53230 🤖 backported "fix: allow replacing a question with a long name"
  frontend/src/metabase/components/SaveQuestionForm/schema.ts
  frontend/src/metabase/containers/SaveQuestionModal/SaveQuestionModal.unit.spec.tsx
Labels: was-backported

#53233 🤖 backported "Add legalese modal to present SDK terms"
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkLegaleseModal/EmbeddingSdkLegaleseModal.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkLegaleseModal/EmbeddingSdkLegaleseModal.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkLegaleseModal/index.ts
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/EmbeddingSdkSettings.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/index.ts
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/tests/common.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/tests/premium.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/tests/setup.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/tests/util.ts
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSettings.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/index.ts
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingSdkOptionCard/EmbeddingSdkOptionCard.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingSdkOptionCard/tests/common.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingSdkOptionCard/tests/premium.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingSdkOptionCard/tests/setup.tsx
  frontend/src/metabase/admin/settings/components/widgets/SettingTextInput/SettingTextInput.tsx
  src/metabase/util/embed.clj
  test_resources/serialization_baseline/settings.yaml
Labels: was-backported

#53238 🤖 backported "fix(sdk): remove unsafe lifecycle errors from DashboardGrid"
  e2e/support/helpers/component-testing-sdk/component-embedding-sdk-console-helpers.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.tsx
  frontend/src/metabase/dashboard/grid-utils.ts
Labels: was-backported

#53243 mark additional tests as flaky
  e2e/test/scenarios/organization/content-verification.cy.spec.js
Labels: .CI & Tests, backport

#53237 Use env vars in backend process
  e2e/runner/cypress-runner-backend.js
Labels: no-backport, .Team/Workflows

#53244 🤖 backported "Fix search index update job restart issue"
  src/metabase/task/search_index.clj
Labels: was-backported

#53242 🤖 backported "Fix search index update job restart issue"
  src/metabase/task/search_index.clj
Labels: was-backported

#53185 🤖 backported "Mark browse metrics flakes as flaky"
  e2e/test/scenarios/metrics/browse.cy.spec.ts
Labels: was-backported

#53245 🤖 backported "mark additional tests as flaky"
  e2e/test/scenarios/organization/content-verification.cy.spec.js
Labels: was-backported

#53220 Remove the postcss-presets-env warning about the partially supported `end` value
  frontend/src/metabase/nav/components/AppBar/AppBarLarge.styled.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/CodeMirrorEditor/CodeMirrorEditor.module.css
  frontend/src/metabase/query_builder/components/view/View/View/View.module.css
  frontend/src/metabase/querying/segments/components/SegmentEditor/ClauseStep/ClauseStep.module.css
  frontend/src/metabase/timelines/common/components/EventForm/EventForm.styled.tsx
  frontend/src/metabase/timelines/common/components/TimelineForm/TimelineForm.styled.tsx
  frontend/src/metabase/visualizations/components/ChartSettings/ChartSettingsFooter/ChartSettingsFooter.styled.tsx
Labels: no-backport

#53135 Fix quick filter drill for trend charts
  e2e/test/scenarios/visualizations-tabular/smartscalar-trend.cy.spec.js
  frontend/src/metabase/visualizations/visualizations/SmartScalar/compute.js
Labels: backport, .Team/Querying

#53227 🤖 backported "fix(sdk): fixes `NotFoundError: Failed to execute 'removeChild' on 'Node'` on nextjs app router when a TableInteractive component is rendered"
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx
Labels: was-backported

#53236 🤖 backported "Add legalese modal to present SDK terms"
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkLegaleseModal/EmbeddingSdkLegaleseModal.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkLegaleseModal/EmbeddingSdkLegaleseModal.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkLegaleseModal/index.ts
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/EmbeddingSdkSettings.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/index.ts
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/tests/common.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/tests/premium.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/tests/setup.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/tests/util.ts
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSettings.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/index.ts
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingSdkOptionCard/EmbeddingSdkOptionCard.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingSdkOptionCard/tests/common.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingSdkOptionCard/tests/premium.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingSdkOptionCard/tests/setup.tsx
  frontend/src/metabase/admin/settings/components/widgets/SettingTextInput/SettingTextInput.tsx
  src/metabase/util/embed.clj
  test_resources/serialization_baseline/settings.yaml
Labels: was-backported

#53241 Fix memoization of extensions in CodeMirror
  frontend/src/metabase/query_builder/components/NativeQueryEditor/CodeMirrorEditor/completers.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/CodeMirrorEditor/completers.unit.spec.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/CodeMirrorEditor/extensions.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/CodeMirrorEditor/util.tsx
Labels: no-backport, .Team/Querying

#53204 [Dashboards] Mark dashboard as dirty if tabs are edited
  e2e/support/helpers/e2e-dashboard-helpers.ts
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  frontend/src/metabase/dashboard/actions/tabs.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardActionsPanel.tsx
Labels: backport, .Team/AdminWebapp

#53118 Fix use of offset with external remapping
  src/metabase/driver/sql/query_processor.clj
  src/metabase/query_processor/util/transformations/nest_breakouts.clj
  test/metabase/query_processor_test/offset_test.clj
Labels: backport, .Team/Querying

#53080 Upsell Advanced Permissions
  enterprise/frontend/src/metabase-enterprise/feature_level_permissions/index.ts
  frontend/src/metabase/admin/permissions/components/PermissionsEditor/PermissionsEditor.jsx
  frontend/src/metabase/admin/permissions/components/PermissionsEditor/PermissionsEditorContent.styled.tsx
  frontend/src/metabase/admin/permissions/components/PermissionsPageLayout/PermissionsPageLayout.tsx
  frontend/src/metabase/admin/permissions/components/ToolbarUpsell/ToolbarUpsell.styled.tsx
  frontend/src/metabase/admin/permissions/components/ToolbarUpsell/ToolbarUpsell.tsx
  frontend/src/metabase/admin/permissions/components/ToolbarUpsell/ToolbarUpsell.unit.spec.tsx
  frontend/src/metabase/admin/permissions/components/ToolbarUpsell/index.ts
  frontend/src/metabase/admin/permissions/pages/DataPermissionsPage/DataPermissionsPage.tsx
  frontend/src/metabase/admin/upsells/UpsellPermissions.tsx
  frontend/src/metabase/admin/upsells/index.ts
Labels: no-backport

#53260 🤖 backported "Fix use of offset with external remapping"
  src/metabase/driver/sql/query_processor.clj
  src/metabase/query_processor/util/transformations/nest_breakouts.clj
  test/metabase/query_processor_test/offset_test.clj
Labels: was-backported

#53267 [CI] Fix flaky dashboard test
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
Labels: no-backport, .Team/AdminWebapp

#53249 🤖 backported "Fix quick filter drill for trend charts"
  e2e/test/scenarios/visualizations-tabular/smartscalar-trend.cy.spec.js
  frontend/src/metabase/visualizations/visualizations/SmartScalar/compute.js
Labels: was-backported

#53254 🤖 backported "[Dashboards] Mark dashboard as dirty if tabs are edited"
  e2e/support/helpers/e2e-dashboard-helpers.ts
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  frontend/src/metabase/dashboard/actions/tabs.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardActionsPanel.tsx
Labels: was-backported

#51585 docs - note on upgrading to pro
  docs/installation-and-operation/activating-the-enterprise-edition.md
Labels: Type:Documentation, backport

#53274 🤖 backported "docs - note on upgrading to pro"
  docs/installation-and-operation/activating-the-enterprise-edition.md
Labels: was-backported

#53271 🤖 backported "Update Translations for v53"
  locales/ar-SA.po
  locales/ar.po
  locales/bg.po
  locales/ca.po
  locales/cs.po
  locales/da.po
  locales/de.po
  locales/es.po
  locales/fa.po
  locales/fi.po
  locales/fr.po
  locales/he.po
  locales/hu.po
  locales/id.po
  locales/it.po
  locales/ja.po
  locales/ko.po
  locales/lv.po
  locales/metabase.pot
  locales/ms.po
  locales/nb.po
  locales/nl.po
  locales/pl.po
  locales/pt-BR.po
  locales/ru.po
  locales/sk.po
  locales/sq.po
  locales/sr.po
  locales/sv.po
  locales/tr.po
  locales/uk.po
  locales/vi.po
  locales/zh-CN.po
  locales/zh-HK.po
  locales/zh-TW.po
  locales/zh.po
Labels: was-backported

#53273 🤖 backported "Fix quick filter drill for trend charts"
  e2e/test/scenarios/visualizations-tabular/smartscalar-trend.cy.spec.js
  frontend/src/metabase/visualizations/visualizations/SmartScalar/compute.js
Labels: was-backported

#53181 Add legacy handling for snowflake password
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
Labels: backport, .Team/Drivers

#53235 Remove unused label for be tests
  .github/workflows/backend.yml
Labels: .CI & Tests, backport, .Team/AdminWebapp

#53226 add estimated size to Search Results virtual list in entity picker
  frontend/src/metabase/common/components/EntityPicker/components/SearchTab/SearchResults.tsx
Labels: backport, .Team/AdminWebapp

#53277 🤖 backported "Add legacy handling for snowflake password"
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
Labels: was-backported

#53276 🤖 backported "Add legacy handling for snowflake password"
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
Labels: was-backported

#53279 🤖 backported "add estimated size to Search Results virtual list in entity picker"
  frontend/src/metabase/common/components/EntityPicker/components/SearchTab/SearchResults.tsx
Labels: was-backported

#53272 Add custom linter to make sure requires are on newlines
  .clj-kondo/src/hooks/clojure/core.clj
  .clj-kondo/test/hooks/clojure/core_test.clj
  bin/release-list/src/release_list/main.clj
  bin/release-list/test/release_list/main_test.clj
  enterprise/backend/src/metabase_enterprise/airgap.clj
  enterprise/backend/src/metabase_enterprise/cache/config.clj
  enterprise/backend/src/metabase_enterprise/stale.clj
  enterprise/backend/test/metabase_enterprise/airgap_test.clj
  enterprise/backend/test/metabase_enterprise/stale_test.clj
  modules/drivers/athena/test/metabase/driver/athena/hive_parser_test.clj
  modules/drivers/druid/src/metabase/driver/druid/js.clj
  modules/drivers/druid/test/metabase/driver/druid/execute_test.clj
  modules/drivers/druid/test/metabase/test/data/druid.clj
  src/metabase/analytics/sdk.clj
  src/metabase/core/bootstrap.clj
  src/metabase/lib/dispatch.cljc
  src/metabase/query_processor/context.clj
  src/metabase/server/middleware/request_id.clj
  src/metabase/task/cache.clj
  src/metabase/util/autoplace.clj
  src/metabase/util/connection.clj
  test/metabase/api/cards_test.clj
  test/metabase/api/trash_test.clj
  test/metabase/api/user_key_value_test.clj
  test/metabase/stale_test.clj
  test/metabase/util/autoplace_test.clj
  test/metabase/util/delay_test.clj
  test/metabase/util/performance_test.clj
Labels: backport, .Team/DevEx

#53211 🤖 backported "Don't infer join aliases when replacing a join"
  src/metabase/lib/join.cljc
  src/metabase/lib/remove_replace.cljc
  test/metabase/lib/remove_replace_test.cljc
Labels: was-backported

#52871 🤖 backported "Fix ultra wide tooltips (closes #52199)"
  frontend/src/metabase/ui/components/icons/Icon/Icon.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/EntityDisplay.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkViz.unit.spec.tsx
Labels: was-backported

#53126 🤖 backported "fix(sdk): fix minWidth console error in dashboard grid"
  frontend/src/metabase/dashboard/components/grid/utils.ts
  frontend/src/metabase/dashboard/components/grid/utils.unit.spec.ts
Labels: was-backported

#53177 🤖 backported "convert header breadcrumbs components to typescript"
  frontend/src/metabase/lib/urls/collections.ts
  frontend/src/metabase/query_builder/components/SavedQuestionHeaderButton/CollectionIcon.tsx
  frontend/src/metabase/query_builder/components/SavedQuestionHeaderButton/SavedQuestionHeaderButton.tsx
  frontend/src/metabase/query_builder/components/SavedQuestionHeaderButton/SavedQuestionHeaderButton.unit.spec.js
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/HeaderBreadcrumbs/HeaderBreadcrumbs.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/HeaderBreadcrumbs/index.js
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/HeaderCollectionBadge/HeaderCollectionBadge.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/HeaderCollectionBadge/index.ts
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/DataSourceCrumbs.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/QuestionDataSource.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/SourceDatasetBreadcrumbs.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/SourceQuestionBreadcrumbs.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/QuestionDataSource/utils.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/SavedQuestionLeftSide/SavedQuestionLeftSide.tsx
  frontend/src/metabase/query_builder/components/view/ViewHeader/components/index.ts
Labels: was-backported

#53269 [Backend modularization] More search module cleanup
  .clj-kondo/config.edn
  .clj-kondo/src/hooks/metabase/search/api_test.clj
  .cljfmt.edn
  deps.edn
  enterprise/backend/src/metabase_enterprise/search/scoring.clj
  src/metabase/api/routes.clj
  src/metabase/models/resolution.clj
  src/metabase/search/api.clj
  src/metabase/search/appdb/index.clj
  src/metabase/search/ingestion.clj
  src/metabase/search/init.clj
  src/metabase/search/models/search_index_metadata.clj
  src/metabase/search/task/search_index.clj
  src/metabase/task/init.clj
  test/metabase/search/api_test.clj
  test/metabase/search/appdb/index_test.clj
  test/metabase/search/impl_test.clj
  test/metabase/search/models/search_index_metadata_test.clj
  test/metabase/search/task/search_index_test.clj
Labels: backport, .Team/DevEx

#53287 🤖 backported "Dashcard titles no longer interactive when editing the dashboard"
  frontend/src/metabase/visualizations/components/ChartCaption.styled.tsx
  frontend/src/metabase/visualizations/components/legend/LegendCaption.tsx
  frontend/src/metabase/visualizations/components/legend/LegendLabel.tsx
  frontend/src/metabase/visualizations/components/legend/LegendLabel.unit.spec.tsx
  frontend/src/metabase/visualizations/visualizations/CartesianChart/CartesianChart.tsx
  frontend/src/metabase/visualizations/visualizations/RowChart/RowChart.styled.tsx
Labels: was-backported

#53239 🤖 backported "fix(sdk): remove unsafe lifecycle errors from DashboardGrid"
  e2e/support/helpers/component-testing-sdk/component-embedding-sdk-console-helpers.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.tsx
  frontend/src/metabase/dashboard/grid-utils.ts
Labels: was-backported

#53278 🤖 backported "Remove unused label for be tests"
  .github/workflows/backend.yml
Labels: was-backported

#53298 unmark tests as flaky
  e2e/test/scenarios/models/model-indexes.cy.spec.js
  e2e/test/scenarios/search/search-pagination.cy.spec.js
  e2e/test/scenarios/search/search.cy.spec.js
Labels: .CI & Tests, backport, flaky-test-fix

#53132 [Dashboards] Prevent duplicate edit dashboard calls from breaking dashboard save
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx
  frontend/src/metabase/dashboard/reducers-typed.ts
Labels: backport, .Team/AdminWebapp

#53295 No more super tiny remove button for condition rules with many columns
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting.jsx
Labels: backport, .Team/DashViz

#53013 fix invalid pivot table columns in click behavior
  e2e/test/scenarios/visualizations-tabular/visualizations-tabular-reproductions.cy.spec.js
  frontend/src/metabase/dashboard/components/ClickMappings.jsx
Labels: backport, .Team/DashViz

#53309 Quarantine Flaky Tab Test
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, backport, .Team/AdminWebapp

#53261 Highlight lines changed by SQL autofixing
  enterprise/frontend/src/metabase-enterprise/ai-sql-fixer/components/FixSqlQueryButton/FixSqlQueryButton.tsx
  enterprise/frontend/src/metabase-enterprise/ai-sql-fixer/components/FixSqlQueryButton/FixSqlQueryButton.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/ai-sql-fixer/components/FixSqlQueryButton/utils.ts
  frontend/src/metabase-types/store/mocks/qb.ts
  frontend/src/metabase-types/store/qb.ts
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/query_builder/components/NativeQueryEditor/CodeMirrorEditor/CodeMirrorEditor.module.css
  frontend/src/metabase/query_builder/components/NativeQueryEditor/CodeMirrorEditor/CodeMirrorEditor.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/CodeMirrorEditor/extensions.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx
  frontend/src/metabase/query_builder/components/QueryVisualization.jsx
  frontend/src/metabase/query_builder/components/VisualizationError/VisualizationError.tsx
  frontend/src/metabase/query_builder/components/view/View/ViewNativeQueryEditor/ViewNativeQueryEditor.jsx
  frontend/src/metabase/query_builder/defaults.ts
  frontend/src/metabase/query_builder/reducers.js
  frontend/src/metabase/query_builder/selectors.js
Labels: .Team/Querying

#53128 Allow private slack channels to be returned for alerts/subscriptions
  docs/configuring-metabase/slack.md
  resources/slack-manifest.yaml
  src/metabase/integrations/slack.clj
  test/metabase/integrations/slack_test.clj
Labels: no-backport, .Team/Workflows

#53314 🤖 backported "Quarantine Flaky Tab Test"
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
Labels: was-backported

#53312 fix (ci): Set longer timeout to ensure we get a successful connection attempt
  test/metabase/models/database_test.clj
Labels: backport, .Team/Drivers

#53315 Drop `of our terms` from legalese copy
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkLegaleseModal/EmbeddingSdkLegaleseModal.tsx
Labels: backport, .Team/Embedding

#53145 🤖 backported "Fix breakout by drill through context menu for multi-stage queries"
  e2e/test/scenarios/filters-reproductions/filters-reproductions.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/drillthroughs/table_drills.cy.spec.js
  frontend/src/metabase-lib/drills.ts
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/querying/drills/utils/pivot-drill.tsx
  src/metabase/lib/drill_thru/pivot.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/schema/drill_thru.cljc
  test/metabase/lib/drill_thru/pivot_test.cljc
Labels: was-backported

#53317 🤖 backported "Type mbql required features"
  frontend/src/metabase-lib/v1/expressions/types.ts
  frontend/src/metabase-types/api/database.ts
Labels: was-backported

#53322 🤖 backported "Drop `of our terms` from legalese copy"
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkLegaleseModal/EmbeddingSdkLegaleseModal.tsx
Labels: was-backported

#53323 🤖 backported "Drop `of our terms` from legalese copy"
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkLegaleseModal/EmbeddingSdkLegaleseModal.tsx
Labels: was-backported

#53292 add visibility check before saving dashboard
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
Labels: .CI & Tests, backport, flaky-test-fix

#53137 🤖 backported "Elide data in task_history.details which can get very large"
  src/metabase/models/interface.clj
  src/metabase/models/task_history.clj
  src/metabase/util/string.clj
  test/metabase/models/interface_test.clj
  test/metabase/util/string_test.clj
Labels: was-backported

#53329 🤖 backported "add visibility check before saving dashboard"
  e2e/test/scenarios/dashboard/dashboard.cy.spec.js
Labels: was-backported

#53010 🤖 backported "Add tests for file downloads from the public link sharing popover"
  e2e/test/scenarios/sharing/public-question.cy.spec.js
Labels: was-backported

#52994 🤖 backported "fix(sdk): Remove ExplicitSize findDOMNode console errors"
  enterprise/frontend/src/metabase-enterprise/license/components/BillingInfo/BillingInfoTable.tsx
  frontend/src/metabase/ErrorBoundary.tsx
  frontend/src/metabase/components/DebouncedFrame/DebouncedFrame.jsx
  frontend/src/metabase/components/ErrorPages/ErrorPages.tsx
  frontend/src/metabase/components/ExplicitSize/ExplicitSize.tsx
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.tsx
  frontend/src/metabase/components/LoadingAndErrorWrapper/LoadingAndErrorWrapper.tsx
  frontend/src/metabase/core/components/TabRow/TabRow.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.tsx
  frontend/src/metabase/entities/containers/rtk-query/EntityListLoader.tsx
  frontend/src/metabase/entities/containers/rtk-query/EntityObjectLoader.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditor.unit.spec.tsx
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetEditorInner.jsx
  frontend/src/metabase/query_builder/components/DatasetEditor/index.js
  frontend/src/metabase/query_builder/components/DatasetEditor/index.ts
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx
  frontend/src/metabase/query_builder/components/expressions/ExpressionEditorTextfield/ExpressionEditorTextfield.tsx
  frontend/src/metabase/query_builder/components/view/View/View/View.jsx
  frontend/src/metabase/querying/metrics/components/MetricEditor/MetricEditor.tsx
  frontend/src/metabase/visualizations/components/CardRenderer.jsx
  frontend/src/metabase/visualizations/components/ChartWithLegend.jsx
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.jsx
  frontend/src/metabase/visualizations/components/TableSimple/TableSimple.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.jsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.tsx
Labels: was-backported

#53263 update enable-embedding-sdk based on embedding-app-origins-sdk
  resources/migrations/001_update_migrations.yaml
Labels: backport, .Team/DevEx

#53331 🤖 backported "update enable-embedding-sdk based on embedding-app-origins-sdk"
  resources/migrations/001_update_migrations.yaml
Labels: was-backported

#53330 Allow disabling reading a setting from env vars
  src/metabase/models/setting.clj
  test/metabase/models/setting_test.clj
Labels: no-backport, .Team/AdminWebapp
