Repository metabase/metabase, pull requests merged in 2025-05, with the labels that each got.

#57401 Remove Legacy Metrics code from the backend
  enterprise/backend/src/metabase_enterprise/serialization/v2/entity_ids.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/models.clj
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  src/metabase/analytics/stats.clj
  src/metabase/api/card.clj
  src/metabase/events/audit_log.clj
  src/metabase/events/schema.clj
  src/metabase/legacy_mbql/schema.cljc
  src/metabase/lib/breakout.cljc
  src/metabase/lib/js/metadata.cljs
  src/metabase/lib/metadata.cljc
  src/metabase/lib/metadata/cached_provider.cljc
  src/metabase/lib/metadata/invocation_tracker.cljc
  src/metabase/lib/metric.cljc
  src/metabase/lib/query.cljc
  src/metabase/lib/schema/aggregation.cljc
  src/metabase/lib/schema/id.cljc
  src/metabase/lib/schema/metadata.cljc
  src/metabase/lib/schema/ref.cljc
  src/metabase/models/audit_log.clj
  src/metabase/models/interface.clj
  src/metabase/models/legacy_metric.clj
  src/metabase/models/legacy_metric_important_field.clj
  src/metabase/models/query.clj
  src/metabase/models/resolution.clj
  src/metabase/revisions/events.clj
  src/metabase/revisions/models/revision/diff.clj
  src/metabase/segments/models/segment.clj
  src/metabase/xrays/api/automagic_dashboards.clj
  src/metabase/xrays/automagic_dashboards/core.clj
  src/metabase/xrays/automagic_dashboards/interesting.clj
  src/metabase/xrays/automagic_dashboards/names.clj
  src/metabase/xrays/automagic_dashboards/util.clj
  src/metabase/xrays/domain_entities/specs.clj
  src/metabase/xrays/related.clj
  test/metabase/api/card_test.clj
  test/metabase/cmd/copy_test.clj
  test/metabase/events/audit_log_test.clj
  test/metabase/lib/test_util/metadata_providers/merged_mock.cljc
  test/metabase/lib/test_util/metadata_providers/mock.cljc
  test/metabase/models/interface_test.clj
  test/metabase/models/legacy_metric_test.clj
  test/metabase/segments/models/segment_test.clj
  test/metabase/test/generate.clj
  test/metabase/test/util.clj
  test/metabase/xrays/api/automagic_dashboards_test.clj
  test/metabase/xrays/automagic_dashboards/core_test.clj
Labels: no-backport, .Team/DevEx

#57075 TS Conversion: Automatic Dashboard App
  frontend/src/metabase-types/api/dashboard.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.tsx
  frontend/src/metabase/dashboard/containers/AutomaticDashboardApp/AutomaticDashboardApp.module.css
  frontend/src/metabase/dashboard/containers/AutomaticDashboardApp/AutomaticDashboardApp.tsx
  frontend/src/metabase/dashboard/containers/AutomaticDashboardApp/SuggestionsSidebar.tsx
  frontend/src/metabase/dashboard/containers/AutomaticDashboardApp/index.ts
  frontend/src/metabase/dashboard/containers/Dashboard.jsx
  frontend/src/metabase/dashboard/containers/Dashboard.tsx
Labels: no-backport, .Team/Embedding

#57258 Fix cumulative aggregations legacy transform
  src/metabase/lib/convert.cljc
  test/metabase/lib/convert_test.cljc
Labels: backport, .Team/SemanticLayer

#57475 🤖 backported "Fix cumulative aggregations legacy transform"
  src/metabase/lib/convert.cljc
  test/metabase/lib/convert_test.cljc
Labels: was-backported

#57480 fix: display a header with actions (create) even when there is no data
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/EditTableDashcardVisualization.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.tsx
  frontend/src/metabase/visualizations/types/visualization.ts
  frontend/src/metabase/visualizations/visualizations/TableEditable/TableEditable.tsx
Labels: .Team/Workflows

#57425 feat(enterprise): add distinct editing modal URL for dashboard
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/EditTableDashcardVisualization.tsx
Labels: .Team/Workflows

#57390 Convert AutomaticDashboardApp to a functional component
  frontend/src/metabase/dashboard/containers/AutomaticDashboardApp/AutomaticDashboardApp.tsx
  frontend/src/metabase/dashboard/containers/Dashboard.tsx
Labels: no-backport, .Team/Embedding

#57487 deps: remove simpleclient_jetty and javax.servlet
  deps.edn
Labels: backport, .Team/AdminWebapp

#57268 docs - note on role setting
  docs/databases/connections/snowflake.md
Labels: Type:Documentation, triple-backport

#57492 [Backend modularization] create new `api-routes` module
  .clj-kondo/config/modules/config.edn
  .gitignore
  enterprise/backend/src/metabase_enterprise/sso/api/routes.clj
  src/metabase/api/docs.clj
  src/metabase/api/open_api.clj
  src/metabase/api/routes/common.clj
  src/metabase/api/util.clj
  src/metabase/api_routes/core.clj
  src/metabase/api_routes/routes.clj
  src/metabase/cmd/endpoint_dox.clj
  src/metabase/server/auth_wrapper.clj
  src/metabase/server/core.clj
  src/metabase/server/routes.clj
  test/metabase/api/open_api_test.clj
  test/metabase/api_routes/routes_test.clj
Labels: no-backport, .Team/DevEx

#57500 🤖 backported "docs - note on role setting"
  docs/databases/connections/snowflake.md
Labels: was-backported

#57499 🤖 backported "docs - note on role setting"
  docs/databases/connections/snowflake.md
Labels: was-backported

#57498 🤖 backported "docs - note on role setting"
  docs/databases/connections/snowflake.md
Labels: was-backported

#57494 🤖 backported "deps: remove simpleclient_jetty and javax.servlet"
  deps.edn
Labels: was-backported

#57497 [Backend modularization] create new `api-keys` module
  .clj-kondo/config/modules/config.edn
  enterprise/backend/src/metabase_enterprise/advanced_config/file/api_keys.clj
  enterprise/backend/src/metabase_enterprise/scim/api.clj
  src/metabase/api_keys/api.clj
  src/metabase/api_keys/core.clj
  src/metabase/api_keys/models/api_key.clj
  src/metabase/api_routes/routes.clj
  src/metabase/models/collection.clj
  src/metabase/models/interface.clj
  src/metabase/models/resolution.clj
  src/metabase/server/middleware/session.clj
  test/metabase/api_keys/api_test.clj
  test/metabase/channel/email/messages_test.clj
Labels: no-backport, .Team/DevEx

#57502 [Backend modularization] Move remaining Slack namespaces into `channel`
  .clj-kondo/config/modules/config.edn
  enterprise/backend/src/metabase_enterprise/sso/integrations/sso_utils.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/api/setting_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/pulse_test.clj
  src/metabase/analytics/stats.clj
  src/metabase/api_routes/routes.clj
  src/metabase/channel/api.clj
  src/metabase/channel/api/slack.clj
  src/metabase/channel/events/slack.clj
  src/metabase/channel/impl/slack.clj
  src/metabase/channel/init.clj
  src/metabase/channel/settings.clj
  src/metabase/channel/slack.clj
  src/metabase/channel/task/refresh_slack_channel_user_cache.clj
  src/metabase/events/init.clj
  src/metabase/events/schema.clj
  src/metabase/notification/events/notification.clj
  src/metabase/notification/init.clj
  src/metabase/pulse/api/pulse.clj
  src/metabase/task/init.clj
  test/metabase/analytics/stats_test.clj
  test/metabase/channel/api/slack_test.clj
  test/metabase/channel/impl/slack_test.clj
  test/metabase/channel/settings_test.clj
  test/metabase/channel/slack_test.clj
  test/metabase/notification/events/notification_test.clj
  test/metabase/notification/send_test.clj
  test/metabase/notification/test_util.clj
  test/metabase/pulse/api/pulse_test.clj
Labels: no-backport, .Team/DevEx

#57503 [Backend modularization] `testing-api` module
  .clj-kondo/config/modules/config.edn
  src/metabase/api_routes/routes.clj
  src/metabase/core/init.clj
  src/metabase/db/connection.clj
  src/metabase/testing_api/api.clj
  src/metabase/testing_api/core.clj
  src/metabase/testing_api/init.clj
  src/metabase/testing_api/settings.clj
  test/metabase/testing_api/api_test.clj
Labels: no-backport, .Team/DevEx

#56760 Create EmailSettingsPage
  e2e/test/scenarios/admin-2/settings.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/email_allow_list/index.ts
  enterprise/frontend/src/metabase-enterprise/email_restrict_recipients/index.ts
  enterprise/frontend/src/metabase-enterprise/plugins.js
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/allowed-domains.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/user-visibility.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/Email/BccToggleWidget.tsx
  frontend/src/metabase/admin/settings/components/Email/SMTPConnectionCard.tsx
  frontend/src/metabase/admin/settings/components/Email/SettingsEmailForm.tsx
  frontend/src/metabase/admin/settings/components/SettingsPages/EmailSettingsPage.tsx
  frontend/src/metabase/admin/settings/components/SettingsPages/EmailSettingsPage.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/SettingsPages/UpdatesSettingsPage.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/AdminSettingInput.tsx
  frontend/src/metabase/admin/settings/components/widgets/AdminSettingInput.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmailReplyToWidget.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmailReplyToWidget.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/SettingCommaDelimitedInput.jsx
  frontend/src/metabase/admin/settings/selectors/selectors.js
Labels: no-backport, .Team/AdminWebapp

#57508 Drop param_values
  enterprise/backend/src/metabase_enterprise/llm/tasks/describe_dashboard.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/dashboard_test.clj
  frontend/src/metabase-lib/v1/metadata/Field.ts
  frontend/src/metabase-lib/v1/metadata/Field.unit.spec.ts
  frontend/src/metabase-types/api/dashboard.ts
  frontend/src/metabase/dashboard/actions/data-fetching.ts
  frontend/src/metabase/entities/fields.js
  frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget/FieldValuesWidget/utils.unit.spec.js
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion.tsx
  frontend/src/metabase/redux/metadata.js
  src/metabase/api/dashboard.clj
  src/metabase/embedding/api/common.clj
  src/metabase/public_sharing/api.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/embedding/api/embed_test.clj
  test/metabase/public_sharing/api_test.clj
Labels: backport, .Team/Querying

#57512 🤖 backported "Drop param_values"
  enterprise/backend/src/metabase_enterprise/llm/tasks/describe_dashboard.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/dashboard_test.clj
  frontend/src/metabase-lib/v1/metadata/Field.ts
  frontend/src/metabase-lib/v1/metadata/Field.unit.spec.ts
  frontend/src/metabase-types/api/dashboard.ts
  frontend/src/metabase/components/FieldValuesWidget/FieldValuesWidget.unit.spec.tsx
  frontend/src/metabase/components/FieldValuesWidget/utils.unit.spec.js
  frontend/src/metabase/dashboard/actions/data-fetching.ts
  frontend/src/metabase/entities/fields.js
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion.tsx
  frontend/src/metabase/redux/metadata.js
  src/metabase/api/dashboard.clj
  src/metabase/api/embed/common.clj
  src/metabase/public_sharing/api.clj
  test/metabase/api/dashboard_test.clj
  test/metabase/api/embed_test.clj
  test/metabase/public_sharing/api_test.clj
Labels: was-backported

#57263 Closes VIZ-349 unknown date style warnings
  frontend/src/metabase/lib/formatting/date.tsx
Labels: backport, .Team/DashViz

#57513 🤖 backported "Closes VIZ-349 unknown date style warnings"
  frontend/src/metabase/lib/formatting/date.tsx
Labels: was-backported

#57472 Reverse the order of coercion in notification parsing
  enterprise/backend/src/metabase_enterprise/data_editing/coerce.clj
  enterprise/backend/src/metabase_enterprise/data_editing/data_editing.clj
  enterprise/backend/test/metabase_enterprise/data_editing/coerce_test.clj
  enterprise/backend/test/metabase_enterprise/data_editing/notification_test.clj
  src/metabase/notification/payload/impl/system_event.clj
Labels: .Team/Workflows

#57474 Sample event info with table value
  enterprise/backend/test/metabase_enterprise/data_editing/notification_test.clj
  src/metabase/notification/api/notification.clj
  src/metabase/notification/core.clj
  src/metabase/notification/payload/impl/system_event.clj
  src/metabase/notification/payload/sample.clj
Labels: .Team/Workflows

#57253 closes viz-360 esc key should not add a recipient
  e2e/test/scenarios/sharing/subscriptions.cy.spec.js
  frontend/src/metabase/components/TokenField/TokenField.tsx
Labels: backport, .Team/DashViz

#57515 🤖 backported "closes viz-360 esc key should not add a recipient"
  e2e/test/scenarios/sharing/subscriptions.cy.spec.js
  frontend/src/metabase/components/TokenField/TokenField.tsx
Labels: was-backported

#57510 [VISUALIZER] Fix card duplication spinning
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/use-duplicate-dashcard.ts
Labels: Reporting/Dashboards, no-backport, .Team/DashViz

#57517 fix: display values of FK fields when it is outside of search results
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/inputs/EditingBodyCellCategorySelect.tsx
Labels: .Team/Workflows

#57482 [serdes] break endless loops
  enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/storage.clj
  enterprise/backend/test/metabase_enterprise/serialization/api_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj
  src/metabase/models/serialization.clj
Labels: .Team/Workflows, double-backport

#57521 🤖 backported "[serdes] break endless loops"
  enterprise/backend/src/metabase_enterprise/serialization/v2/load.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/storage.clj
  enterprise/backend/test/metabase_enterprise/serialization/api_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/cmd_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/load_test.clj
  src/metabase/models/serialization.clj
Labels: was-backported

#57389 Do not set card when using browser back button
  e2e/test/scenarios/models/reproductions.cy.spec.ts
  frontend/src/metabase/query_builder/actions/navigation.ts
Labels: backport, .Team/Querying

#57522 🤖 backported "Do not set card when using browser back button"
  e2e/test/scenarios/models/reproductions.cy.spec.ts
  frontend/src/metabase/query_builder/actions/navigation.ts
Labels: was-backported

#57526 Closes VIZ-926: combining existing dashcards causes them to crash
  e2e/support/helpers/e2e-dashboard-visualizer-helpers.ts
  e2e/test/scenarios/dashboard/visualizer/basics.cy.spec.ts
  frontend/src/metabase/dashboard/actions/data-fetching.ts
Labels: .Team/DashViz

#57318 Bump com.clickhouse/clickhouse-jdbc from 0.8.4 to 0.8.5
  modules/drivers/clickhouse/deps.edn
  modules/drivers/clickhouse/test/metabase/driver/clickhouse_data_types_test.clj
Labels: no-backport

#57319 Bump io.trino/trino-jdbc from 431 to 475
  modules/drivers/starburst/deps.edn
Labels: no-backport

#57519 Repurpose Bulk actions as Table actions
  .gitignore
  enterprise/backend/src/metabase_enterprise/data_editing/api.clj
  enterprise/backend/src/metabase_enterprise/data_editing/data_editing.clj
  enterprise/backend/src/metabase_enterprise/data_editing/undo.clj
  enterprise/backend/test/metabase_enterprise/data_editing/api_test.clj
  enterprise/backend/test/metabase_enterprise/data_editing/coerce_test.clj
  src/metabase/actions/actions.clj
  src/metabase/actions/execution.clj
  src/metabase/driver/h2/actions.clj
  src/metabase/driver/mysql/actions.clj
  src/metabase/driver/postgres/actions.clj
  src/metabase/driver/sql_jdbc/actions.clj
  src/metabase/events/notification.clj
  test/metabase/actions/actions_test.clj
  test/metabase/driver/h2_test.clj
  test/metabase/driver/mysql_test.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/driver/sql_jdbc/actions_test.clj
  test/metabase/notification/api/notification_test.clj
Labels: .Team/Workflows

#56659 Bump com.facebook.presto/presto-jdbc from 0.291 to 0.292
  modules/drivers/presto-jdbc/deps.edn
Labels: no-backport

#57484 fix: include system catalog in databricks multicatalog
  modules/drivers/databricks/src/metabase/driver/databricks.clj
  modules/drivers/databricks/test/metabase/driver/databricks_test.clj
Labels: no-backport, .Team/Drivers

#57530 Fix remaining identity hash test flakes
  test/metabase/models/dashboard_test.clj
  test/metabase/models/dimension_test.clj
  test/metabase/native_query_snippets/models/native_query_snippet_test.clj
  test/metabase/segments/models/segment_test.clj
Labels: backport, .Team/Drivers

#57507 Fix druid jdbc parameterized query with date type
  modules/drivers/druid-jdbc/src/metabase/driver/druid_jdbc.clj
  modules/drivers/druid-jdbc/test/metabase/driver/druid_jdbc_test.clj
Labels: backport, .Team/Drivers

#57536 🤖 backported "Fix remaining identity hash test flakes"
  test/metabase/models/dashboard_test.clj
  test/metabase/models/dimension_test.clj
  test/metabase/models/native_query_snippet_test.clj
  test/metabase/segments/models/segment_test.clj
Labels: was-backported

#57514 Further limit tsvector size since it's concatinated
  src/metabase/search/appdb/specialization/postgres.clj
Labels: backport, double-backport, triple-backport

#57511 [Backend modularization] `sample-data` module
  .clj-kondo/config.edn
  .clj-kondo/config/modules/config.edn
  .clj-kondo/config/test-helpers/config.edn
  .cljfmt.edn
  src/metabase/api/database.clj
  src/metabase/cmd/copy.clj
  src/metabase/core/core.clj
  src/metabase/core/init.clj
  src/metabase/sample_data/core.clj
  src/metabase/sample_data/impl.clj
  src/metabase/sample_data/init.clj
  src/metabase/sample_data/settings.clj
  src/metabase/settings/deprecated_grab_bag.clj
  test/metabase/sample_data/impl_test.clj
Labels: no-backport, .Team/DevEx

#57504 Improved handling deleted connections in harbormaster
  enterprise/backend/src/metabase_enterprise/gsheets/api.clj
Labels: no-backport, .Team/AdminWebapp

#57549 🤖 backported "Further limit tsvector size since it's concatinated"
  src/metabase/search/appdb/specialization/postgres.clj
Labels: was-backported

#56648 [svg] Pool static-viz-context objects
  deps.edn
  src/metabase/channel/render/js/svg.clj
  test/metabase/channel/render/js/svg_test.clj
Labels: backport

#56928 Fix for Grey areas around the cards when exporting to PDF
  frontend/src/metabase/visualizations/lib/save-dashboard-pdf.ts
Labels: backport

#57563 🤖 backported "Fix for Grey areas around the cards when exporting to PDF"
  frontend/src/metabase/visualizations/lib/save-dashboard-pdf.ts
Labels: was-backported

#57185 Fix remapping caching
  frontend/src/metabase/hoc/Remapped.jsx
  frontend/src/metabase/redux/metadata.js
Labels: backport, .Team/Querying

#57568 🤖 backported "Fix remapping caching"
  frontend/src/metabase-types/api/field.ts
  frontend/src/metabase/api/field.ts
  frontend/src/metabase/api/tags/utils.ts
  frontend/src/metabase/hoc/Remapped.jsx
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/redux/metadata.js
  frontend/src/metabase/services.js
Labels: was-backported

#57545 remove old static pie chart interface
  resources/frontend_shared/static_viz_interface.js
Labels: backport, .Team/DashViz

#57569 🤖 backported "remove old static pie chart interface"
  resources/frontend_shared/static_viz_interface.js
Labels: was-backported

#57456 🤖 backported "Reindex immediately on start-up if existing table is old"
  .clj-kondo/config/modules/config.edn
  src/metabase/core/core.clj
  src/metabase/search/appdb/core.clj
  src/metabase/search/appdb/index.clj
  src/metabase/search/core.clj
  src/metabase/search/task/search_index.clj
  src/metabase/startup/core.clj
  test/metabase/search/appdb/index_test.clj
Labels: was-backported

#57548 🤖 backported "Further limit tsvector size since it's concatinated"
  src/metabase/search/appdb/specialization/postgres.clj
Labels: was-backported

#56714 🤖 backported "feat(sdk): Automatically set a sensible display to interactive question"
  e2e/test-component/scenarios/embedding-sdk/interactive-question.cy.spec.tsx
  enterprise/frontend/src/embedding-sdk/lib/interactive-question/run-question-query.ts
  enterprise/frontend/src/embedding-sdk/test/auth-flow.unit.spec.tsx
Labels: was-backported

#57589 🤖 backported "fix(sdk): manual fixes for module level ttag calls causing broken translations"
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/ChartTypeSelectorList/ChartTypeDropdown.tsx
  enterprise/frontend/src/metabase-enterprise/audit_app/components/AuditTableVisualization/AuditTableVisualization.jsx
  frontend/src/metabase/actions/components/ActionViz/ActionViz.tsx
  frontend/src/metabase/parameters/components/UpdateFilterButton/getUpdateButtonProps.ts
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeList/ChartTypeList.unit.spec.tsx
  frontend/src/metabase/query_builder/components/chart-type-selector/ChartTypeOption/ChartTypeOption.tsx
  frontend/src/metabase/query_builder/components/view/sidebars/ChartSettingsSidebar.tsx
  frontend/src/metabase/visualizations/components/PinMap.jsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.unit.spec.js
  frontend/src/metabase/visualizations/types/visualization.ts
  frontend/src/metabase/visualizations/visualizations/AreaChart/AreaChart.tsx
  frontend/src/metabase/visualizations/visualizations/BarChart/BarChart.tsx
  frontend/src/metabase/visualizations/visualizations/ComboChart/ComboChart.tsx
  frontend/src/metabase/visualizations/visualizations/DashCardPlaceholder.tsx
  frontend/src/metabase/visualizations/visualizations/Funnel/Funnel.tsx
  frontend/src/metabase/visualizations/visualizations/Gauge/Gauge.jsx
  frontend/src/metabase/visualizations/visualizations/Heading/index.ts
  frontend/src/metabase/visualizations/visualizations/IFrameViz/IFrameVizSettings.ts
  frontend/src/metabase/visualizations/visualizations/LineChart/LineChart.tsx
  frontend/src/metabase/visualizations/visualizations/LinkViz/LinkVizSettings.ts
  frontend/src/metabase/visualizations/visualizations/Map/Map.jsx
  frontend/src/metabase/visualizations/visualizations/ObjectDetail.jsx
  frontend/src/metabase/visualizations/visualizations/PieChart/chart-definition.ts
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.tsx
  frontend/src/metabase/visualizations/visualizations/Progress/Progress.jsx
  frontend/src/metabase/visualizations/visualizations/RowChart/RowChart.tsx
  frontend/src/metabase/visualizations/visualizations/SankeyChart/chart-definition.ts
  frontend/src/metabase/visualizations/visualizations/Scalar/Scalar.jsx
  frontend/src/metabase/visualizations/visualizations/ScatterPlot/ScatterPlot.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.jsx
  frontend/src/metabase/visualizations/visualizations/Table/Table.tsx
  frontend/src/metabase/visualizations/visualizations/Text/index.ts
  frontend/src/metabase/visualizations/visualizations/WaterfallChart/WaterfallChart.tsx
Labels: was-backported

#57496 Add a new metric button to browse metrics page
  e2e/test/scenarios/metrics/browse.cy.spec.ts
  frontend/src/metabase/browse/metrics/BrowseMetrics.tsx
  frontend/src/metabase/browse/metrics/tests/common.unit.spec.tsx
Labels: no-backport, .Team/ProductGrowth

#57524 Add label to `CodeEditor` in `LogLevelsForm`
  frontend/src/metabase/admin/tasks/components/LogLevelsModal/DurationInput.tsx
  frontend/src/metabase/admin/tasks/components/LogLevelsModal/LogLevelsForm.tsx
  frontend/src/metabase/components/CodeEditor/CodeEditor.tsx
Labels: no-backport, .Team/SemanticLayer

#57420 SEM-241 Data model - Field - Data section
  frontend/src/metabase-types/api/field.ts
  frontend/src/metabase/metadata/components/CoercionStrategyPicker/CoercionStrategyPicker.module.css
  frontend/src/metabase/metadata/components/CoercionStrategyPicker/CoercionStrategyPicker.tsx
  frontend/src/metabase/metadata/components/CoercionStrategyPicker/CoercionStrategyPicker.unit.spec.tsx
  frontend/src/metabase/metadata/components/CoercionStrategyPicker/index.ts
  frontend/src/metabase/metadata/components/NameDescriptionInput/Input.tsx
  frontend/src/metabase/metadata/components/NameDescriptionInput/NameDescriptionInput.tsx
  frontend/src/metabase/metadata/components/NameDescriptionInput/TextInputBlurChange.tsx
  frontend/src/metabase/metadata/components/NameDescriptionInput/TextInputBlurChange.unit.spec.tsx
  frontend/src/metabase/metadata/components/SortableField/SortableField.module.css
  frontend/src/metabase/metadata/components/SortableField/SortableField.tsx
  frontend/src/metabase/metadata/components/SortableFieldList/SortableFieldList.tsx
  frontend/src/metabase/metadata/components/SortableFieldList/utils.ts
  frontend/src/metabase/metadata/components/index.ts
  frontend/src/metabase/metadata/pages/DataModel/DataModel.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/FieldDataSection.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/FieldSection.module.css
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/FieldSection.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/illustrations/sub-input-follow.svg
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/illustrations/sub-input.svg
  frontend/src/metabase/metadata/pages/DataModel/components/SectionPill/SectionPill.module.css
  frontend/src/metabase/metadata/pages/DataModel/components/SectionPill/SectionPill.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/SectionPill/index.ts
  frontend/src/metabase/metadata/pages/DataModel/components/TableSection/TableSection.tsx
  frontend/src/metabase/metadata/pages/DataModel/types.ts
  frontend/src/metabase/metadata/pages/DataModel/utils.ts
  frontend/src/metabase/metadata/pages/DataModel/utils.unit.spec.ts
  frontend/src/metabase/metadata/utils/field.ts
  frontend/src/metabase/metadata/utils/field.unit.spec.ts
  frontend/src/metabase/ui/components/inputs/TextInputBlurChange/TextInputBlurChange.tsx
  frontend/src/metabase/ui/components/inputs/TextInputBlurChange/index.tsx
Labels: no-backport, .Team/SemanticLayer

#57495 properly invalidate collections when x-raying a table
  e2e/test/scenarios/dashboard/x-rays.cy.spec.js
  frontend/src/metabase/dashboard/containers/AutomaticDashboardApp/AutomaticDashboardApp.tsx
Labels: no-backport, .Team/AdminWebapp

#56812 Register Dynamic Shortcuts
  e2e/support/helpers/e2e-command-palette-helpers.js
  e2e/test/scenarios/onboarding/command-palette.cy.spec.js
  frontend/src/metabase/dashboard/components/DashboardTabs/DashboardTabs.tsx
  frontend/src/metabase/nav/components/AdminNavbar/AdminNavbar.tsx
  frontend/src/metabase/palette/components/PaletteResultsList.tsx
  frontend/src/metabase/palette/components/PaletteShortcutsModal/PaletteShortcutsModal.tsx
  frontend/src/metabase/palette/constants.ts
  frontend/src/metabase/palette/hooks/useRegisterShortcut.tsx
  frontend/src/metabase/palette/shortcuts/admin.ts
  frontend/src/metabase/palette/shortcuts/collection.ts
  frontend/src/metabase/palette/shortcuts/dashboard.ts
  frontend/src/metabase/palette/shortcuts/global.ts
  frontend/src/metabase/palette/shortcuts/index.ts
  frontend/src/metabase/palette/shortcuts/question.ts
  frontend/src/metabase/palette/types.ts
  patches/kbar+0.1.0-beta.45.patch
Labels: no-backport, .Team/AdminWebapp

#57580 Bump org.eclipse.jetty.ee9/jetty-ee9-servlet from 12.0.19 to 12.0.20
  deps.edn
Labels: no-backport

#57581 Bump org.eclipse.jetty/jetty-server from 12.0.19 to 12.0.20
  deps.edn
Labels: no-backport

#57531 SEM-297 Drop entity framework usage in `SemanticTypePicker`
  frontend/src/metabase/admin/datamodel/metadata/components/FieldGeneralSettings/FieldGeneralSettings.tsx
  frontend/src/metabase/admin/datamodel/metadata/components/MetadataTableColumn/MetadataTableColumn.tsx
  frontend/src/metabase/metadata/.eslintrc
  frontend/src/metabase/metadata/components/FieldOrderSidesheet/FieldOrderSidesheet.tsx
  frontend/src/metabase/metadata/components/FieldOrderSidesheet/lib.ts
  frontend/src/metabase/metadata/components/FkTargetPicker/FkTargetPicker.tsx
  frontend/src/metabase/metadata/components/SemanticTypeAndTargetPicker/SemanticTypeAndTargetPicker.tsx
  frontend/src/metabase/metadata/utils/field.ts
  frontend/src/metabase/metadata/utils/field.unit.spec.ts
  frontend/src/metabase/metadata/utils/schema.ts
  frontend/src/metabase/metadata/utils/schema.unit.spec.ts
  frontend/src/metabase/query_builder/components/DatasetEditor/DatasetFieldMetadataSidebar/DatasetFieldMetadataFkTargetPicker.tsx
  frontend/src/metabase/reference/components/FieldFkTargetPicker.tsx
Labels: no-backport, .Team/SemanticLayer

#57587 Bump net.snowflake/snowflake-jdbc from 3.23.2 to 3.24.0
  modules/drivers/snowflake/deps.edn
Labels: no-backport

#57457 🤖 backported "Reindex immediately on start-up if existing table is old"
  .clj-kondo/config/modules/config.edn
  src/metabase/core/core.clj
  src/metabase/search/appdb/core.clj
  src/metabase/search/appdb/index.clj
  src/metabase/search/core.clj
  src/metabase/search/task/search_index.clj
  src/metabase/startup/core.clj
  test/metabase/search/appdb/index_test.clj
Labels: was-backported

#57601 Remove use modal hook
  enterprise/frontend/src/metabase-enterprise/user_provisioning/components/UserProvisioning.tsx
  frontend/src/metabase/hooks/use-modal.ts
Labels: Type:Tech Debt, no-backport, .Team/AdminWebapp

#57541 fix: add table-level sql based permission query
  src/metabase/models/table.clj
  src/metabase/search/appdb/core.clj
  src/metabase/search/impl.clj
  src/metabase/search/in_place/legacy.clj
  src/metabase/search/permissions.clj
  src/metabase/util/honey_sql_2.clj
  test/metabase/models/table_test.clj
  test/metabase/search/api_test.clj
  test/metabase/search/appdb/index_test.clj
  test/metabase/search/impl_test.clj
Labels: .Team/AdminWebapp, double-backport

#57553 Add watermark to static viz chart renderings
  .loki/reference/chrome_laptop_Viz_Static_Viz_ComboChart_Watermark.png
  .loki/reference/chrome_laptop_Viz_Static_Viz_FunnelChart_Watermark.png
  .loki/reference/chrome_laptop_Viz_Static_Viz_Gauge_Watermark.png
  .loki/reference/chrome_laptop_Viz_Static_Viz_PieChart_Watermark.png
  .loki/reference/chrome_laptop_Viz_Static_Viz_ProgressBar_Watermark.png
  .loki/reference/chrome_laptop_Viz_Static_Viz_RowChart_Watermark.png
  .loki/reference/chrome_laptop_Viz_Static_Viz_SankeyChart_Default_Settings.png
  .loki/reference/chrome_laptop_Viz_Static_Viz_SankeyChart_Watermark.png
  .loki/reference/chrome_laptop_Viz_Static_Viz_ScatterPlot_Watermark.png
  .loki/reference/chrome_laptop_Viz_Static_Viz_WaterfallChart_Watermark.png
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.stories.tsx
  frontend/src/metabase/static-viz/components/ComboChart/ComboChart.tsx
  frontend/src/metabase/static-viz/components/FunnelChart/FunnelChart.stories.tsx
  frontend/src/metabase/static-viz/components/FunnelChart/FunnelChart.tsx
  frontend/src/metabase/static-viz/components/Gauge/Gauge.stories.tsx
  frontend/src/metabase/static-viz/components/Gauge/Gauge.tsx
  frontend/src/metabase/static-viz/components/Gauge/GaugeContainer.tsx
  frontend/src/metabase/static-viz/components/PieChart/PieChart.stories.tsx
  frontend/src/metabase/static-viz/components/PieChart/PieChart.tsx
  frontend/src/metabase/static-viz/components/ProgressBar/ProgressBar.stories.tsx
  frontend/src/metabase/static-viz/components/ProgressBar/ProgressBar.tsx
  frontend/src/metabase/static-viz/components/RowChart/RowChart.stories.tsx
  frontend/src/metabase/static-viz/components/RowChart/RowChart.tsx
  frontend/src/metabase/static-viz/components/SankeyChart/SankeyChart.stories.tsx
  frontend/src/metabase/static-viz/components/SankeyChart/SankeyChart.tsx
  frontend/src/metabase/static-viz/components/SankeyChart/stories-data/default-settings.json
  frontend/src/metabase/static-viz/components/SankeyChart/stories-data/index.ts
  frontend/src/metabase/static-viz/components/ScatterPlot/ScatterPlot.stories.tsx
  frontend/src/metabase/static-viz/components/ScatterPlot/ScatterPlot.tsx
  frontend/src/metabase/static-viz/components/StaticVisualization/StaticVisualization.tsx
  frontend/src/metabase/static-viz/components/StaticVisualization/types.ts
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.stories.tsx
  frontend/src/metabase/static-viz/components/WaterfallChart/WaterfallChart.tsx
  frontend/src/metabase/static-viz/containers/LegacyStaticChart/LegacyStaticChart.tsx
  frontend/src/metabase/static-viz/index.js
  frontend/src/metabase/static-viz/watermark.svg
  frontend/src/metabase/visualizations/types/visualization.ts
  resources/frontend_shared/static_viz_interface.js
  src/metabase/channel/render/js/svg.clj
  test/metabase/channel/render/js/svg_test.clj
Labels: no-backport, .Team/AdminWebapp

#57570 remove add visualization button from empty dashcards
  e2e/test/scenarios/dashboard/visualizer/funnels.cy.spec.ts
  frontend/src/metabase/visualizations/visualizations/DashCardPlaceholder.tsx
Labels: .Team/DashViz

#57610 🤖 backported "fix: add table-level sql based permission query"
  src/metabase/models/table.clj
  src/metabase/search/appdb/core.clj
  src/metabase/search/impl.clj
  src/metabase/search/in_place/legacy.clj
  src/metabase/search/permissions.clj
  src/metabase/util/honey_sql_2.clj
  test/metabase/models/table_test.clj
  test/metabase/search/api_test.clj
  test/metabase/search/appdb/index_test.clj
  test/metabase/search/impl_test.clj
Labels: was-backported

#54750 Update Title component sizes to match Figma
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Relative.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Relative.png
  .loki/reference/chrome_laptop_Design_System_Typography_Title_Default.png
  .loki/reference/chrome_laptop_Design_System_Typography_Title_Sizes.png
  .loki/reference/chrome_laptop_Patterns_Overlays_All_Overlays.png
  .loki/reference/chrome_laptop_Patterns_Overlays_Legacy_Modal_Can_Launch_Mantine_Modal.png
  .loki/reference/chrome_laptop_Patterns_Overlays_Mantine_Modal_Can_Launch_Legacy_Modal.png
  .loki/reference/chrome_laptop_Patterns_Overlays_Mantine_Modal_Can_Launch_Legacy_Select.png
  .loki/reference/chrome_laptop_Patterns_Overlays_Mantine_Modal_Can_Launch_Mantine_Hovercard.png
  .loki/reference/chrome_laptop_Patterns_Overlays_Mantine_Modal_Can_Launch_Mantine_Select.png
  .loki/reference/chrome_laptop_Patterns_Overlays_Mantine_Popover_Can_Launch_Legacy_Modal.png
  .loki/reference/chrome_laptop_Patterns_Overlays_Mantine_Popover_Can_Launch_Legacy_Select.png
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/SdkSaveQuestionForm.tsx
  frontend/src/metabase/admin/databases/components/ExistingDatabaseHeader.tsx
  frontend/src/metabase/admin/permissions/components/ApplicationPermissionsHelp/ApplicationPermissionsHelp.tsx
  frontend/src/metabase/admin/permissions/components/CollectionPermissionsHelp/CollectionPermissionsHelp.tsx
  frontend/src/metabase/admin/permissions/components/DataPermissionsHelp/DataPermissionsHelp.tsx
  frontend/src/metabase/admin/settings/components/ApiKeys/ManageApiKeys.tsx
  frontend/src/metabase/admin/settings/components/Email/SMTPConnectionCard.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkLegaleseModal/EmbeddingSdkLegaleseModal.tsx
  frontend/src/metabase/admin/settings/components/widgets/EmbeddingOption/EmbeddingOption.tsx
  frontend/src/metabase/admin/settings/notifications/NotificationSettings.tsx
  frontend/src/metabase/admin/upsells/components/UpsellBanner.tsx
  frontend/src/metabase/admin/upsells/components/UpsellBigCard.tsx
  frontend/src/metabase/admin/upsells/components/UpsellCard.tsx
  frontend/src/metabase/browse/components/BrowseDataHeader.tsx
  frontend/src/metabase/browse/metrics/BrowseMetrics.tsx
  frontend/src/metabase/browse/models/BrowseModels.tsx
  frontend/src/metabase/browse/models/ModelExplanationBanner.tsx
  frontend/src/metabase/collections/components/CollectionBulkActions/QuestionMoveConfirmModal.tsx
  frontend/src/metabase/common/components/Sidesheet/SidesheetSubPage.tsx
  frontend/src/metabase/components/ModalContent/ModalHeader.tsx
  frontend/src/metabase/dashboard/components/Dashboard/DashboardEmptyState/DashboardEmptyState.tsx
  frontend/src/metabase/home/components/EmbedHomepage/FeedbackModal.tsx
  frontend/src/metabase/home/components/Onboarding/Onboarding.tsx
  frontend/src/metabase/models/components/ModelActions/ModelActions.tsx
  frontend/src/metabase/public/components/EmbedModal/SelectEmbedTypePane/SharingPaneButton/SharingPaneButton.tsx
  frontend/src/metabase/public/components/widgets/LegaleseStep/LegaleseStep.tsx
  frontend/src/metabase/query_builder/components/MoveQuestionModal/MoveQuestionModal.tsx
  frontend/src/metabase/query_builder/components/QueryVisualization.jsx
  frontend/src/metabase/timelines/collections/components/TimelineEmptyState/TimelineEmptyState.tsx
  frontend/src/metabase/ui/components/overlays/Modal/Modal.module.css
  frontend/src/metabase/ui/components/typography/Title/Title.config.tsx
  frontend/src/metabase/ui/components/typography/Title/Title.module.css
  frontend/src/metabase/ui/components/typography/Title/Title.stories.tsx
  frontend/src/metabase/ui/theme.ts
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/RuleListing.tsx
  frontend/src/metabase/visualizations/visualizations/SmartScalar/SmartScalar.jsx
Labels: no-backport, PR-Env

#57611 🤖 backported "fix: add table-level sql based permission query"
  src/metabase/models/table.clj
  src/metabase/search/appdb/core.clj
  src/metabase/search/impl.clj
  src/metabase/search/in_place/legacy.clj
  src/metabase/search/permissions.clj
  src/metabase/util/honey_sql_2.clj
  test/metabase/models/table_test.clj
  test/metabase/search/api_test.clj
  test/metabase/search/appdb/index_test.clj
  test/metabase/search/impl_test.clj
Labels: was-backported

#57618 Fix Kondo failures not causing CI failures
  .clj-kondo/config.edn
  .clj-kondo/config/modules/config.edn
  enterprise/backend/test/metabase_enterprise/api/gsheets_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/dashboard_test.clj
  mage/mage/kondo.clj
  src/metabase/channel/render/js/svg.clj
  src/metabase/pulse/models/pulse_channel.clj
  src/metabase/util.cljc
  test/metabase/api/dashboard_test.clj
  test/metabase/channel/render/js/svg_test.clj
  test/metabase/models/dashboard_card_test.clj
  test/metabase/models/dashboard_test.clj
  test/metabase/models/dimension_test.clj
  test/metabase/native_query_snippets/models/native_query_snippet_test.clj
  test/metabase/public_sharing/api_test.clj
  test/metabase/pulse/api/pulse_test.clj
  test/metabase/search/impl_test.clj
  test/metabase/segments/models/segment_test.clj
Labels: no-backport, .Team/DevEx

#57505 fix: remove version-info from settings list api
  e2e/test/scenarios/admin-2/settings.cy.spec.js
  e2e/test/scenarios/onboarding/navbar/whats-new.cy.spec.js
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/SettingsEditor.jsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/setup.tsx
  frontend/src/metabase/admin/settings/components/SettingsPages/UpdatesSettingsPage.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/VersionUpdateNotice/VersionUpdateNotice.tsx
  frontend/src/metabase/admin/settings/components/widgets/VersionUpdateNotice/VersionUpdateNotice.unit.spec.tsx
  frontend/src/metabase/admin/settings/selectors/selectors.js
  frontend/src/metabase/nav/components/WhatsNewNotification/WhatsNewNotification.tsx
  frontend/src/metabase/nav/components/WhatsNewNotification/WhatsNewNotification.unit.spec.tsx
  frontend/src/metabase/nav/containers/MainNavbar/tests/setup.tsx
  frontend/src/metabase/nav/containers/Navbar.unit.spec.tsx
  frontend/test/__support__/server-mocks/settings.ts
  src/metabase/settings/deprecated_grab_bag.clj
  src/metabase/settings/models/setting.clj
  test/metabase/session/api_test.clj
  test/metabase/settings/api_test.clj
  test/metabase/settings/models/setting_test.clj
Labels: backport, .Team/AdminWebapp

#57625 🤖 backported "docs: link to help page"
  docs/configuring-metabase/config-template.md
  docs/configuring-metabase/environment-variables.md
  docs/dashboards/subscriptions.md
  docs/installation-and-operation/activating-the-enterprise-edition.md
  docs/people-and-groups/user-provisioning.md
  src/metabase/cmd/resources/env-var-intro.md
Labels: was-backported

#57465 Create new PublicSharingSettingsPage component
  e2e/test/scenarios/sharing/public-sharing.cy.spec.js
  frontend/src/metabase/admin/settings/components/SettingsPages/PublicSharingSettingsPage.tsx
  frontend/src/metabase/admin/settings/components/SettingsPages/PublicSharingSettingsPage.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/PublicLinksListing/PublicLinksListing.tsx
  frontend/src/metabase/admin/settings/components/widgets/PublicLinksListing/PublicLinksListing.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/PublicLinksListing/PublicResources.tsx
  frontend/src/metabase/admin/settings/components/widgets/PublicLinksListing/PublicResources.unit.spec.tsx
  frontend/src/metabase/admin/settings/selectors/selectors.js
  frontend/test/__support__/server-mocks/action.ts
  frontend/test/__support__/server-mocks/card.ts
  frontend/test/__support__/server-mocks/dashboard.ts
Labels: no-backport, .Team/AdminWebapp

#57555 Add a new model button to browse models page
  e2e/test/scenarios/models/create.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/browse/models/BrowseModels.unit.spec.tsx
  frontend/src/metabase/browse/models/BrowseModels.tsx
  frontend/src/metabase/browse/models/BrowseModels.unit.spec.tsx
Labels: no-backport, .Team/ProductGrowth

#57605 Add a "new collection" button to the main sidebar
  e2e/test/scenarios/collections/permissions.cy.spec.js
  e2e/test/scenarios/collections/personal-collections.cy.spec.js
  e2e/test/scenarios/onboarding/urls.cy.spec.js
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbar.styled.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarContainer.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarView.tsx
Labels: no-backport

#57588 move context info to after the log message
  resources/log4j2.xml
Labels: backport, .Team/Workflows

#57636 🤖 backported "move context info to after the log message"
  resources/log4j2.xml
Labels: was-backported

#57529 fix(sdk): updating collection's entity id crashes InteractiveQuestion and CollectionBrowser
  e2e/support/cypress_sample_instance_data.js
  e2e/test-component/scenarios/embedding-sdk/collection-browser.cy.spec.tsx
  e2e/test-component/scenarios/embedding-sdk/interactive-question.cy.spec.tsx
  frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts
Labels: .Team/Embedding, double-backport

#57616 Add a "new collection" button to the collection header
  e2e/test/scenarios/collections/collections.cy.spec.js
  frontend/src/metabase/collections/components/CollectionHeader/CollectionHeader.tsx
  frontend/src/metabase/collections/components/CollectionHeader/CollectionNewButton.tsx
  frontend/src/metabase/collections/components/CollectionHeader/tests/common.unit.spec.tsx
  frontend/src/metabase/collections/components/CollectionHeader/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/ui/components/icons/Icon/icons/add_folder.svg
  frontend/src/metabase/ui/components/icons/Icon/icons/index.ts
Labels: no-backport

#57539 fix(sdk): custom GeoJSON maps does not load due to wrong domain
  frontend/src/metabase/visualizations/components/ChoroplethMap.jsx
  frontend/src/metabase/visualizations/components/ChoroplethMap.unit.spec.js
Labels: .Team/Embedding, double-backport

#57642 🤖 backported "fix(sdk): updating collection's entity id crashes InteractiveQuestion and CollectionBrowser"
  e2e/support/cypress_sample_instance_data.js
  e2e/test-component/scenarios/embedding-sdk/collection-browser.cy.spec.tsx
  e2e/test-component/scenarios/embedding-sdk/interactive-question.cy.spec.tsx
  frontend/src/metabase/lib/entity-id/hooks/use-validated-entity-id.ts
Labels: was-backported

#57645 🤖 backported "fix(sdk): custom GeoJSON maps does not load due to wrong domain"
  frontend/src/metabase/visualizations/components/ChoroplethMap.jsx
  frontend/src/metabase/visualizations/components/ChoroplethMap.unit.spec.js
Labels: was-backported

#57382 Clean up helper text utils
  frontend/src/metabase-lib/v1/expressions/clause.ts
  frontend/src/metabase-lib/v1/expressions/complete/aggregations.ts
  frontend/src/metabase-lib/v1/expressions/complete/functions.ts
  frontend/src/metabase-lib/v1/expressions/complete/util.ts
  frontend/src/metabase-lib/v1/expressions/config.ts
  frontend/src/metabase-lib/v1/expressions/define.ts
  frontend/src/metabase-lib/v1/expressions/diagnostics/expression/check-arg-count.ts
  frontend/src/metabase-lib/v1/expressions/help-text.ts
  frontend/src/metabase-lib/v1/expressions/help-text.unit.spec.ts
  frontend/src/metabase-lib/v1/expressions/helper-text-strings.ts
  frontend/src/metabase-lib/v1/expressions/index.ts
  frontend/src/metabase-lib/v1/expressions/position.ts
  frontend/src/metabase-lib/v1/expressions/types.ts
  frontend/src/metabase/query_builder/components/expressions/Editor/HelpText/HelpText.tsx
  frontend/src/metabase/query_builder/components/expressions/Editor/HelpText/tests/common.unit.spec.tsx
  frontend/src/metabase/query_builder/components/expressions/Editor/HelpText/tests/setup.tsx
  frontend/src/metabase/query_builder/components/expressions/FunctionBrowser/FunctionBrowser.tsx
  frontend/src/metabase/query_builder/components/expressions/FunctionBrowser/utils.ts
  frontend/src/metabase/query_builder/components/expressions/FunctionBrowser/utils.unit.spec.ts
Labels: no-backport

#57641 Remove "Metric" option from the "New" button menu
  e2e/test/scenarios/metrics/metrics-editing.cy.spec.js
  frontend/src/metabase/components/NewItemMenu/NewItemMenu.tsx
  frontend/src/metabase/containers/NewItemMenu/NewItemMenu.unit.spec.tsx
Labels: no-backport, .Team/ProductGrowth

#57400 Wrap `EditableDashboard` with context
  frontend/src/metabase/dashboard/context/context.redux.ts
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardView.stories.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/mock-context.tsx
Labels: .Team/Embedding

#57550 🤖 backported "Further limit tsvector size since it's concatinated"
  src/metabase/search/appdb/specialization/postgres.clj
Labels: was-backported

#57594 Closes VIZ-933 a replaced dataset no longer appears as collapsed
  frontend/src/metabase/visualizer/components/DataImporter/ColumnsList/ColumnsList.tsx
  frontend/src/metabase/visualizer/components/DataImporter/DataImporter.tsx
  frontend/src/metabase/visualizer/components/DataImporter/DatasetsList/DatasetsList.tsx
  frontend/src/metabase/visualizer/components/Visualizer/Visualizer.tsx
  frontend/src/metabase/visualizer/components/VisualizerModal/VisualizerModal.tsx
  frontend/src/metabase/visualizer/components/VisualizerUiContext/VisualizerUiContext.tsx
  frontend/src/metabase/visualizer/hooks/use-boolean-map.ts
Labels: .Team/DashViz

#57649 Remove "Collection" option from the "New" button menu
  e2e/support/helpers/e2e-collection-helpers.ts
  e2e/test/scenarios/collections/collections.cy.spec.js
  e2e/test/scenarios/collections/personal-collections.cy.spec.js
  e2e/test/scenarios/onboarding/command-palette.cy.spec.js
  e2e/test/scenarios/onboarding/navbar/new-menu.cy.spec.js
  e2e/test/scenarios/organization/entity-picker.cy.spec.ts
  e2e/test/scenarios/organization/official-collections.cy.spec.js
  e2e/test/scenarios/permissions/permissions-reproductions.cy.spec.js
  frontend/src/metabase/components/NewItemMenu/NewItemMenu.tsx
  frontend/src/metabase/containers/NewItemMenu/NewItemMenu.unit.spec.tsx
Labels: no-backport, .Team/ProductGrowth

#57528 Closes VIZ-638: better type comparison for compatibility check
  frontend/src/metabase/visualizer/components/DataImporter/DatasetsList/getIsCompatible.ts
  frontend/src/metabase/visualizer/components/DataImporter/DatasetsList/getIsCompatible.unit.spec.ts
Labels: .Team/DashViz

#57397 fix: redshift pg_enum error when missing base types
  modules/drivers/redshift/src/metabase/driver/redshift.clj
  modules/drivers/redshift/test/metabase/driver/redshift_test.clj
Labels: backport, .Team/Drivers

#57652 fix: remapped_to_column is not defined when rows are empty
  frontend/src/metabase/visualizations/index.ts
Labels: .Team/Workflows

#57042 Add dashboard context
  enterprise/frontend/src/embedding-sdk/components/public/StaticDashboard/StaticDashboard.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardMenu/DashCardMenu.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/dashboard/components/DashCard/Dashcard.unit.spec.tsx
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.tsx
  frontend/src/metabase/dashboard/constants.ts
  frontend/src/metabase/dashboard/containers/AutomaticDashboardApp/AutomaticDashboardApp.tsx
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.tsx
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.unit.spec.tsx
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardTitle.tsx
  frontend/src/metabase/dashboard/containers/DashboardApp/use-slow-card-notification.ts
  frontend/src/metabase/dashboard/context/context.redux.ts
  frontend/src/metabase/dashboard/context/context.tsx
  frontend/src/metabase/dashboard/context/index.ts
  frontend/src/metabase/dashboard/hooks/use-auto-scroll-to-dashcard.ts
  frontend/src/metabase/dashboard/types/display-options.ts
  frontend/src/metabase/dashboard/types/embed-display-options.ts
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboard.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardPage/PublicOrEmbeddedDashboardPage.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardView-filters.stories.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardView.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestion.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestionView.stories.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestionView.tsx
  frontend/src/metabase/public/lib/types.ts
  frontend/src/metabase/routes.jsx
Labels: .Team/Embedding

#57657 update chart settings types
  frontend/src/metabase/visualizations/components/ChartSettings/DashboardChartSettings/types.ts
  frontend/src/metabase/visualizations/components/ChartSettings/QuestionChartSettings/types.ts
  frontend/src/metabase/visualizations/components/ChartSettings/types.ts
Labels: backport, .Team/DashViz

#57620 Watermarks in development instances - App viz
  .eslintrc.js
  .loki/reference/chrome_laptop_viz_BarChart_Watermark.png
  .loki/reference/chrome_laptop_viz_Funnel_Watermark.png
  .loki/reference/chrome_laptop_viz_PieChart_Watermark.png
  e2e/test-component/scenarios/embedding-sdk/interactive-dashboard.cy.spec.tsx
  e2e/test-component/scenarios/embedding-sdk/interactive-question.cy.spec.tsx
  e2e/test/scenarios/question/saved.cy.spec.js
  e2e/test/scenarios/visualizations-charts/bar_chart.cy.spec.js
  e2e/test/scenarios/visualizations-charts/pie_chart.cy.spec.js
  e2e/test/scenarios/visualizations-charts/sankey.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/drillthroughs/table_drills.cy.spec.js
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/dashboard/utils.ts
  frontend/src/metabase/visualizations/components/Visualization/Visualization.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.unit.spec.js
  frontend/src/metabase/visualizations/components/Visualization/Watermark/Watermark.module.css
  frontend/src/metabase/visualizations/components/Visualization/Watermark/Watermark.tsx
  frontend/src/metabase/visualizations/components/Visualization/Watermark/index.ts
  frontend/src/metabase/visualizations/components/Visualization/Watermark/watermark.svg
  frontend/src/metabase/visualizations/visualizations/BarChart/BarChart.stories.tsx
  frontend/src/metabase/visualizations/visualizations/Funnel/Funnel.stories.tsx
  frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.stories.tsx
  frontend/src/metabase/visualizations/visualizations/Table/Table.stories.tsx
  frontend/test/__support__/storybook.tsx
Labels: no-backport, .Team/AdminWebapp

#57633 Add build-args to uberjar job
  .github/workflows/containerize-jar.yml
  .github/workflows/uberjar.yml
Labels: no-backport, .Team/AdminWebapp, .Team/DevEx

#57664 🤖 backported "update chart settings types"
  frontend/src/metabase/visualizations/components/ChartSettings/DashboardChartSettings/types.ts
  frontend/src/metabase/visualizations/components/ChartSettings/QuestionChartSettings/types.ts
  frontend/src/metabase/visualizations/components/ChartSettings/types.ts
Labels: was-backported

#57662 fix: failing kondos on master
  .clj-kondo/config.edn
  .clj-kondo/macros/metabase/models/user_test.clj
  enterprise/backend/src/metabase_enterprise/advanced_permissions/models/permissions/group_manager.clj
  enterprise/backend/src/metabase_enterprise/scim/v2/api.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/api/group_manager_test.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/models/permissions/block_permissions_test.clj
  enterprise/backend/test/metabase_enterprise/sandbox/api/card_test.clj
  src/metabase/models/user.clj
  src/metabase/permissions/api.clj
  src/metabase/permissions/core.clj
  src/metabase/permissions/models/permissions_group_membership.clj
  src/metabase/sso/common.clj
  test/metabase/actions/api_test.clj
  test/metabase/api/collection_test.clj
  test/metabase/api/user_test.clj
  test/metabase/db/schema_migrations_test.clj
  test/metabase/models/user_test.clj
  test/metabase/permissions/models/permissions_group_membership_test.clj
  test/metabase/permissions/models/permissions_group_test.clj
  test/metabase/sso/common_test.clj
  test/metabase/test.clj
  test/metabase/test/data/users.clj
  test/metabase/test/util.clj
  test/metabase/test/util/misc.clj
Labels: no-backport, .Team/AdminWebapp

#56468 Update Appearance Settings
  .eslintrc.js
  e2e/test/scenarios/admin-2/whitelabel.cy.spec.js
  enterprise/frontend/src/embedding-sdk/components/private/SdkThemeProvider.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/ChartColorSettings/ChartColorSettings.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/ColorResetModal/ColorResetModal.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/ColorResetModal/index.ts
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/ColorSettings/ColorSettings.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/ColorSettingsWidget/ColorSettingsWidget.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/ColorSettingsWidget/index.ts
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/FontFilesWidget/FontFilesWidget.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/FontFilesWidget/index.ts
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/FontFilesWidget/types.ts
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/FontWidget/FontFilesWidget.styled.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/FontWidget/FontFilesWidget.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/FontWidget/FontWidget.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/FontWidget/FontWidget.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/FontWidget/index.ts
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/FontWidget/types.ts
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/FontWidget/utils.ts
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/HelpLinkSettings/HelpLinkSettings.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/HelpLinkSettings/HelpLinkSettings.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/IllustrationTitle.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/IllustrationWidget/IllustrationWidget.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/IllustrationWidget/IllustrationWidget.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/IllustrationWidget/ImageUploadWidget.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/IllustrationWidget/ImageUploadWidget.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/ImageToggle/ImageToggle.styled.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/ImageUpload/ImageUpload.jsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/ImageUpload/ImageUpload.styled.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/ImageUpload/index.ts
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/LighthouseToggleWidget/LighthouseToggleWidget.styled.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/LighthouseToggleWidget/LighthouseToggleWidget.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/LighthouseToggleWidget/LighthouseToggleWidget.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/LighthouseToggleWidget/index.ts
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/LighthouseToggleWidget/types.ts
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/MetabaseLinksToggleDescription.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/MetabaseLinksToggleWidget/MetabaseLinksToggleDescription.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/MetabaseLinksToggleWidget/MetabaseLinksToggleWidget.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/MetabaseLinksToggleWidget/index.ts
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/MetabotToggleWidget/MetabotToggleWidget.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/MetabotToggleWidget/MetabotToggleWidget.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/SwitchWidget/SwitchWidget.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/SwitchWidget/index.ts
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/WhiteLabelSettingsPage.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/WhiteLabelSettingsPage.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/index.js
  enterprise/frontend/src/metabase-enterprise/whitelabel/lib/loading-message.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/settings/components/SettingsPages/AppearanceSettingsPage.tsx
  frontend/src/metabase/admin/settings/components/SettingsSetting.jsx
  frontend/src/metabase/admin/settings/components/widgets/AdminSettingInput.tsx
  frontend/src/metabase/admin/settings/selectors/selectors.js
  frontend/src/metabase/admin/upsells/UpsellWhitelabel.tsx
  frontend/src/metabase/api/utils/settings.ts
  frontend/src/metabase/plugins/index.ts
  frontend/test/__support__/utils.ts
Labels: no-backport, .Team/AdminWebapp

#57634 simplify slack impl
  enterprise/backend/test/metabase_enterprise/data_editing/notification_test.clj
  src/metabase/channel/impl/slack.clj
  src/metabase/integrations/slack.clj
  test/metabase/channel/impl/slack_test.clj
  test/metabase/dashboard_subscription_test.clj
  test/metabase/integrations/slack_test.clj
  test/metabase/notification/api/notification_test.clj
  test/metabase/notification/payload/impl/card_test.clj
  test/metabase/notification/send_test.clj
  test/metabase/notification/test_util.clj
  test/metabase/pulse/send_test.clj
Labels: .Team/Workflows

#57686 🤖 backported "Copy multi-stage components"
  .eslintrc.js
  enterprise/frontend/.eslintrc
  enterprise/frontend/src/embedding-sdk/.eslintrc
  enterprise/frontend/src/embedding/data-picker/DataSelector.jsx
  enterprise/frontend/src/embedding/data-picker/DataSelector.module.css
  enterprise/frontend/src/embedding/data-picker/DataSelector.unit.spec.js
  enterprise/frontend/src/embedding/data-picker/DataSelectorDataBucketPicker/DataSelectorDataBucketPicker.module.css
  enterprise/frontend/src/embedding/data-picker/DataSelectorDataBucketPicker/DataSelectorDataBucketPicker.tsx
  enterprise/frontend/src/embedding/data-picker/DataSelectorDataBucketPicker/DataSelectorDataBucketPicker.unit.spec.tsx
  enterprise/frontend/src/embedding/data-picker/DataSelectorDataBucketPicker/index.ts
  enterprise/frontend/src/embedding/data-picker/DataSelectorDatabasePicker/DataSelectorDatabasePicker.tsx
  enterprise/frontend/src/embedding/data-picker/DataSelectorDatabasePicker/DataSelectorDatabasePicker.unit.spec.tsx
  enterprise/frontend/src/embedding/data-picker/DataSelectorDatabasePicker/index.ts
  enterprise/frontend/src/embedding/data-picker/DataSelectorDatabaseSchemaPicker/DataSelectorDatabaseSchemaPicker.tsx
  enterprise/frontend/src/embedding/data-picker/DataSelectorDatabaseSchemaPicker/DataSelectorDatabaseSchemaPicker.unit.spec.js
  enterprise/frontend/src/embedding/data-picker/DataSelectorDatabaseSchemaPicker/index.ts
  enterprise/frontend/src/embedding/data-picker/DataSelectorFieldPicker/DataSelectorFieldPicker.module.css
  enterprise/frontend/src/embedding/data-picker/DataSelectorFieldPicker/DataSelectorFieldPicker.tsx
  enterprise/frontend/src/embedding/data-picker/DataSelectorFieldPicker/DataSelectorFieldPicker.unit.spec.tsx
  enterprise/frontend/src/embedding/data-picker/DataSelectorFieldPicker/index.ts
  enterprise/frontend/src/embedding/data-picker/DataSelectorLoading/DataSelectorLoading.tsx
  enterprise/frontend/src/embedding/data-picker/DataSelectorLoading/index.ts
  enterprise/frontend/src/embedding/data-picker/DataSelectorSchemaPicker/DataSelectorSchemaPicker.tsx
  enterprise/frontend/src/embedding/data-picker/DataSelectorSchemaPicker/DataSelectorSchemaPicker.unit.spec.js
  enterprise/frontend/src/embedding/data-picker/DataSelectorSchemaPicker/index.ts
  enterprise/frontend/src/embedding/data-picker/DataSelectorSectionHeader/DataSelectorSectionHeader.module.css
  enterprise/frontend/src/embedding/data-picker/DataSelectorSectionHeader/DataSelectorSectionHeader.tsx
  enterprise/frontend/src/embedding/data-picker/DataSelectorSectionHeader/index.ts
  enterprise/frontend/src/embedding/data-picker/DataSelectorTablePicker/DataSelectorTablePicker.tsx
  enterprise/frontend/src/embedding/data-picker/DataSelectorTablePicker/DataSelectorTablePicker.unit.spec.tsx
  enterprise/frontend/src/embedding/data-picker/DataSelectorTablePicker/index.ts
  enterprise/frontend/src/embedding/data-picker/RawDataBackButton.tsx
  enterprise/frontend/src/embedding/data-picker/SimpleDataPicker/SimpleDataPicker.stories.tsx
  enterprise/frontend/src/embedding/data-picker/SimpleDataPicker/SimpleDataPicker.tsx
  enterprise/frontend/src/embedding/data-picker/SimpleDataPicker/SimpleDataPicker.unit.spec.tsx
  enterprise/frontend/src/embedding/data-picker/SimpleDataPicker/SimpleDataPickerView.tsx
  enterprise/frontend/src/embedding/data-picker/SimpleDataPicker/index.ts
  enterprise/frontend/src/embedding/data-picker/TriggerComponents.tsx
  enterprise/frontend/src/embedding/data-picker/constants.ts
  enterprise/frontend/src/embedding/data-picker/saved-entity-picker/SavedEntityList.module.css
  enterprise/frontend/src/embedding/data-picker/saved-entity-picker/SavedEntityList.tsx
  enterprise/frontend/src/embedding/data-picker/saved-entity-picker/SavedEntityPicker.jsx
  enterprise/frontend/src/embedding/data-picker/saved-entity-picker/SavedEntityPicker.module.css
  enterprise/frontend/src/embedding/data-picker/saved-entity-picker/SavedEntityPicker.unit.spec.jsx
  enterprise/frontend/src/embedding/data-picker/saved-entity-picker/constants.ts
  enterprise/frontend/src/embedding/data-picker/saved-entity-picker/utils.js
  enterprise/frontend/src/embedding/data-picker/types.ts
  enterprise/frontend/src/embedding/data-picker/utils.ts
  enterprise/frontend/src/metabase-enterprise/embedding-sdk/index.js
  enterprise/frontend/src/metabase-enterprise/embedding/index.js
  frontend/src/metabase/embedding-sdk/types/components/data-picker.ts
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/querying/notebook/components/NotebookDataPicker/EmbeddingDataPicker/EmbeddingDataPicker.tsx
  frontend/src/metabase/querying/notebook/components/NotebookDataPicker/EmbeddingDataPicker/tests/EmbeddingDataPicker.unit.spec.tsx
  rspack.config.js
  rspack.static-viz.config.js
  webpack.config.js
Labels: was-backported

#57479 Fix missing snippet create button
  e2e/support/helpers/api/createSnippet.ts
  e2e/support/helpers/api/index.ts
  e2e/test/scenarios/native/native-reproductions.cy.spec.ts
  e2e/test/scenarios/native/snippets.cy.spec.js
  frontend/src/metabase/query_builder/components/template_tags/SnippetSidebar/SnippetSidebar.jsx
  frontend/src/metabase/query_builder/components/template_tags/SnippetSidebar/SnippetSidebar.module.css
Labels: backport, .Team/Querying

#57689 🤖 backported "Fix missing snippet create button"
  e2e/support/helpers/api/createSnippet.ts
  e2e/support/helpers/api/index.ts
  e2e/test/scenarios/native/native-reproductions.cy.spec.ts
  e2e/test/scenarios/native/snippets.cy.spec.js
  frontend/src/metabase/query_builder/components/template_tags/SnippetSidebar/SnippetSidebar.jsx
  frontend/src/metabase/query_builder/components/template_tags/SnippetSidebar/SnippetSidebar.module.css
Labels: was-backported

#57691 🤖 backported "make LocaleProvider change the return of useLocale and set the locale used by Mantine"
  frontend/src/metabase/common/hooks/use-locale/use-locale.ts
  frontend/src/metabase/public/LocaleProvider.tsx
  frontend/src/metabase/public/LocaleProvider.unit.spec.tsx
Labels: was-backported

#57682 SEM-269 Data model - Field - Formatting section
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/FieldSection.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/FieldSection/FormattingSection.tsx
  frontend/src/metabase/visualizations/components/ColumnSettings.jsx
Labels: no-backport, .Team/SemanticLayer

#57659 Fix funnel mapping issues
  e2e/test/scenarios/dashboard/visualizer/funnels.cy.spec.ts
  frontend/src/metabase/visualizer/components/VisualizationCanvas/HorizontalWell/FunnelHorizontalWell.tsx
  frontend/src/metabase/visualizer/utils/get-initial-state-for-card-data-source.ts
  frontend/src/metabase/visualizer/utils/get-initial-state-for-card-data-source.unit.spec.ts
  frontend/src/metabase/visualizer/visualizations/funnel.ts
Labels: .Team/DashViz

#57660 Fix columns removed when changing cartesian viz types
  e2e/support/test-visualizer-data.ts
  e2e/test/scenarios/dashboard/visualizer/cartesian.cy.spec.ts
  frontend/src/metabase/visualizer/utils/get-updated-settings-for-display.ts
  frontend/src/metabase/visualizer/utils/get-updated-settings-for-display.unit.spec.ts
Labels: .Team/DashViz

#57688 WRK-264: Initial version of conditional alerts UI
  enterprise/frontend/src/metabase-enterprise/data_editing/alerts/TableNotificationsModals/CreateOrEditTableNotificationModal/CreateOrEditTableNotificationModal.module.css
  enterprise/frontend/src/metabase-enterprise/data_editing/alerts/TableNotificationsModals/CreateOrEditTableNotificationModal/CreateOrEditTableNotificationModal.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/alerts/TableNotificationsModals/CreateOrEditTableNotificationModal/CreateOrEditTableNotificationModal.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/alerts/TableNotificationsModals/CreateOrEditTableNotificationModal/components/AlertConditionBuilder/AlertConditionBuilder.module.css
  enterprise/frontend/src/metabase-enterprise/data_editing/alerts/TableNotificationsModals/CreateOrEditTableNotificationModal/components/AlertConditionBuilder/AlertConditionBuilder.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/alerts/TableNotificationsModals/CreateOrEditTableNotificationModal/components/PreviewTemplatePanel/PreviewTemplatePanel.module.css
  enterprise/frontend/src/metabase-enterprise/data_editing/alerts/TableNotificationsModals/CreateOrEditTableNotificationModal/components/PreviewTemplatePanel/PreviewTemplatePanel.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/alerts/TableNotificationsModals/CreateOrEditTableNotificationModal/index.ts
  enterprise/frontend/src/metabase-enterprise/data_editing/alerts/TableNotificationsModals/CreateOrEditTableNotificationModal/types.ts
  enterprise/frontend/src/metabase-enterprise/data_editing/alerts/TableNotificationsModals/TableNotificationsListModal/TableNotificationsListItem.module.css
  enterprise/frontend/src/metabase-enterprise/data_editing/alerts/TableNotificationsModals/TableNotificationsListModal/TableNotificationsListItem.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/alerts/TableNotificationsModals/TableNotificationsListModal/TableNotificationsListModal.stories.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/alerts/TableNotificationsModals/TableNotificationsListModal/TableNotificationsListModal.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/alerts/TableNotificationsModals/TableNotificationsListModal/TableNotificationsListModal.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/alerts/TableNotificationsModals/TableNotificationsListModal/index.ts
  enterprise/frontend/src/metabase-enterprise/data_editing/alerts/TableNotificationsModals/TableNotificationsListModal/test-utils.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/alerts/TableNotificationsModals/TableNotificationsTrigger/TableNotificationsTrigger.module.css
  enterprise/frontend/src/metabase-enterprise/data_editing/alerts/TableNotificationsModals/TableNotificationsTrigger/TableNotificationsTrigger.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/EditTableDataContainer.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/edit/EditTableDataHeader.tsx
  enterprise/frontend/src/metabase-enterprise/data_editing/tables/view/BrowseTableData.tsx
  frontend/src/metabase-types/api/notification.ts
  frontend/src/metabase/notifications/modals/index.ts
  frontend/src/metabase/notifications/utils.ts
Labels: .Team/Workflows

#57695 docs(sdk): Update SDK version to 0.55.5-metabot
  enterprise/frontend/src/embedding-sdk/CHANGELOG.md
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: no-backport

#57303 [Admin] Remove styled component usages from people and group pages + components
  frontend/src/metabase/admin/people/components/AddMemberRow.styled.tsx
  frontend/src/metabase/admin/people/components/AddMemberRow.tsx
  frontend/src/metabase/admin/people/components/GroupSummary.styled.tsx
  frontend/src/metabase/admin/people/components/GroupSummary.tsx
  frontend/src/metabase/admin/people/components/GroupsListing.styled.tsx
  frontend/src/metabase/admin/people/components/GroupsListing.tsx
  frontend/src/metabase/admin/people/components/MembershipSelect/MembershipSelect.module.css
  frontend/src/metabase/admin/people/components/MembershipSelect/MembershipSelect.styled.tsx
  frontend/src/metabase/admin/people/components/MembershipSelect/MembershipSelect.tsx
  frontend/src/metabase/admin/people/components/NudgeToPro.module.css
  frontend/src/metabase/admin/people/components/NudgeToPro.tsx
  frontend/src/metabase/admin/people/components/PeopleListRow.module.css
  frontend/src/metabase/admin/people/components/PeopleListRow.styled.tsx
  frontend/src/metabase/admin/people/components/PeopleListRow.tsx
  frontend/src/metabase/admin/people/containers/AdminPeopleApp.styled.tsx
  frontend/src/metabase/admin/people/containers/AdminPeopleApp.tsx
  frontend/src/metabase/admin/people/containers/PeopleListingApp.tsx
  frontend/src/metabase/admin/people/containers/UserPasswordResetModal.styled.tsx
  frontend/src/metabase/admin/people/containers/UserPasswordResetModal.tsx
  frontend/src/metabase/admin/people/containers/UserSuccessModal.styled.tsx
  frontend/src/metabase/admin/people/containers/UserSuccessModal.tsx
Labels: no-backport, .Team/AdminWebapp

#57699 Stabilize flaky Font Test
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/FontWidget/FontWidget.unit.spec.tsx
Labels: flaky-test-fix, no-backport, .Team/AdminWebapp

#57675 do not store all computed settings values in viz definitions
  e2e/test/scenarios/dashboard/visualizer/basics.cy.spec.ts
  frontend/src/metabase/visualizer/visualizer.slice.ts
Labels: .Team/DashViz

#57615 Functions with side effects should generally end in `!`
  src/metabase/db/liquibase.clj
  src/metabase/db/setup.clj
  test/metabase/cmd/load_from_h2_test.clj
  test/metabase/db/liquibase_test.clj
Labels: no-backport, .Team/DevEx

#57518 Migrate hacked semantic type fields to use coercion
  resources/migrations/001_update_migrations.yaml
Labels: no-backport, .Team/SemanticLayer

#57606 SEM-229 Hide numerical semantic types on string-based fields
  frontend/src/metabase/metadata/components/SemanticTypePicker/SemanticTypePicker.unit.spec.tsx
  frontend/src/metabase/metadata/components/SemanticTypePicker/utils.ts
Labels: no-backport, .Team/SemanticLayer

#57661 Support bigint model_pks in model_index_value
  resources/migrations/001_update_migrations.yaml
Labels: backport, .Team/AdminWebapp, double-backport

#57551 Remove unused `:model/TablePrivileges`
  enterprise/backend/src/metabase_enterprise/serialization/v2/models.clj
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  src/metabase/cmd/copy.clj
  src/metabase/driver.clj
  src/metabase/driver/sql_jdbc/sync/describe_database.clj
  src/metabase/models/resolution.clj
  src/metabase/models/table_privileges.clj
  src/metabase/sync/sync_metadata.clj
  src/metabase/sync/sync_metadata/sync_table_privileges.clj
  test/metabase/sync/sync_metadata/sync_table_privileges_test.clj
Labels: no-backport, .Team/DevEx

#57556 Remove unused `:model/FieldUsage`
  .clj-kondo/config/modules/config.edn
  docs/configuring-metabase/config-template.md
  docs/configuring-metabase/environment-variables.md
  enterprise/backend/src/metabase_enterprise/serialization/v2/models.clj
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  src/metabase/models/field_usage.clj
  src/metabase/models/resolution.clj
  src/metabase/query_processor/middleware/process_userland_query.clj
  src/metabase/query_processor/util.clj
  test/metabase/cmd/copy_test.clj
  test/metabase/db/general_schema_tests.clj
  test/metabase/models/field_usage_test.clj
  test/metabase/query_processor/middleware/process_userland_query_test.clj
Labels: no-backport, .Team/DevEx

#57672 Remove zh from the list of supported translations
  docs/configuring-metabase/localization.md
Labels: no-backport, .Team/AdminWebapp

#57676 [VISUALIZER] Add fallback to assoc-attachment-booleans
  src/metabase/channel/impl/email.clj
  test/metabase/channel/impl/email_test.clj
Labels: Reporting/Pulses, .Team/DashViz

#57710 Mark setup tests flaky
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.ts
Labels: no-backport, .Team/AdminWebapp

#57677 Fix parameter types!
  frontend/src/metabase-lib/v1/metadata/Field.ts
  frontend/src/metabase-lib/v1/parameters/utils/click-behavior.unit.spec.ts
  frontend/src/metabase-lib/v1/parameters/utils/filters.ts
  frontend/src/metabase-lib/v1/parameters/utils/filters.unit.spec.ts
  frontend/src/metabase-lib/v1/parameters/utils/parameter-parsing.ts
  frontend/src/metabase-lib/v1/parameters/utils/template-tag-options.unit.spec.js
  frontend/src/metabase-lib/v1/types/utils/isa.js
  frontend/src/metabase/querying/parameters/utils/parsing.ts
  frontend/src/metabase/querying/parameters/utils/parsing.unit.spec.ts
  src/metabase/lib/filter/operator.cljc
  src/metabase/lib/types/isa.cljc
  src/metabase/xrays/automagic_dashboards/filters.clj
  test/metabase/lib/fe_util_test.cljc
  test/metabase/lib/filter_test.cljc
  test/metabase/lib/types/isa_test.cljc
  test/metabase/xrays/api/automagic_dashboards_test.clj
  test/metabase/xrays/automagic_dashboards/core_test.clj
Labels: no-backport, .Team/Querying, PR-Env

#57678 [Notification] reduce module apis
  .clj-kondo/config/modules/config.edn
  enterprise/backend/src/metabase_enterprise/sso/integrations/sso_utils.clj
  src/metabase/notification/api.clj
  src/metabase/notification/core.clj
  src/metabase/notification/events/notification.clj
  src/metabase/pulse/api/alert.clj
  src/metabase/pulse/api/pulse.clj
  test/metabase/notification/events/notification_test.clj
Labels: backport, .Team/Workflows

#57679 fix audit log to record external emails when sending notifications
  enterprise/backend/test/metabase_enterprise/sandbox/pulse_test.clj
  src/metabase/notification/payload/impl/card.clj
  src/metabase/notification/payload/impl/dashboard.clj
  test/metabase/notification/payload/impl/card_test.clj
Labels: backport, .Team/Workflows

#57647 Remove "Model" and "Action" from the "New" button menu
  e2e/support/helpers/e2e-action-helpers.js
  e2e/test/scenarios/actions/actions-reproductions.cy.spec.js
  e2e/test/scenarios/actions/model-actions.cy.spec.js
  e2e/test/scenarios/dashboard-cards/dashboard-card-reproductions.cy.spec.js
  e2e/test/scenarios/models/create.cy.spec.js
  e2e/test/scenarios/models/reproductions.cy.spec.js
  e2e/test/scenarios/models/reproductions.cy.spec.ts
  e2e/test/scenarios/native/native-database-source.cy.spec.js
  e2e/test/scenarios/onboarding/command-palette.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions-2.cy.spec.js
  e2e/test/scenarios/question/notebook-native-preview-sidebar.cy.spec.ts
  e2e/test/scenarios/question/notebook.cy.spec.js
  frontend/src/metabase/components/NewItemMenu/NewItemMenu.tsx
  frontend/src/metabase/containers/NewItemMenu/NewItemMenu.tsx
  frontend/src/metabase/containers/NewItemMenu/NewItemMenu.unit.spec.tsx
Labels: no-backport, .Team/ProductGrowth

#57687 feat: add a link to field filter docs from dashboard sidebar with native question
  frontend/src/metabase/common/hooks/use-docs-url/use-docs-url.ts
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx
  frontend/src/metabase/dashboard/components/DashboardSidebars.tsx
  frontend/src/metabase/dashboard/containers/DashboardApp/DashboardApp.tsx
  frontend/src/metabase/parameters/components/ParameterLinkedFilters/ParameterLinkedFilters.tsx
  frontend/src/metabase/parameters/components/ParameterLinkedFilters/ParameterLinkedFilters.unit.spec.tsx
  frontend/src/metabase/parameters/components/ParameterSidebar/ParameterSidebar.tsx
  frontend/src/metabase/parameters/components/ParameterSidebar/ParameterSidebar.unit.spec.tsx
Labels: backport, .Team/Querying, PR-Env

#57733 🤖 backported "Mark setup tests flaky"
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.ts
Labels: was-backported

#57728 a transformation layer for event info before evaluating the condition
  enterprise/backend/test/metabase_enterprise/data_editing/notification_test.clj
  src/metabase/notification/condition.clj
  src/metabase/notification/payload/impl/system_event.clj
  test/metabase/notification/events/notification_test.clj
Labels: .Team/Workflows

#57732 🤖 backported "Mark setup tests flaky"
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.ts
Labels: was-backported

#57731 Patch the metabot-v3 merge
  enterprise/frontend/src/metabase-enterprise/metabot/index.tsx
  frontend/src/metabase/components/NewItemMenu/NewItemMenu.tsx
  frontend/src/metabase/nav/components/NewItemButton/NewItemButton.tsx
  frontend/src/metabase/plugins/index.ts
Labels: no-backport, .Team/ProductGrowth

#57735 Fix flaky e2e test in the onboarding `setup` spec
  e2e/test/scenarios/onboarding/setup/setup.cy.spec.ts
Labels: backport, .Team/ProductGrowth

#57724 Visualizer cleanup
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardView.tsx
  frontend/src/metabase/visualizations/components/ChartSettings/BaseChartSettings/BaseChartSettings.tsx
Labels: .Team/DashViz

#57740 Revert visualizer prototyping leftover code
  frontend/src/metabase/visualizations/components/FunnelNormal.jsx
  frontend/src/metabase/visualizations/echarts/cartesian/chart-measurements/index.ts
  frontend/src/metabase/visualizations/visualizations/Funnel/Funnel.tsx
  frontend/src/metabase/visualizations/visualizations/PieChart/chart-definition.ts
Labels: .Team/DashViz

#57694 Customizable slack template for alerts
  enterprise/frontend/src/metabase-enterprise/data_editing/alerts/TableNotificationsModals/TableNotificationsListModal/TableNotificationsListModal.stories.tsx
  frontend/src/metabase-types/api/notification.ts
  frontend/src/metabase/notifications/modals/AlertsModals/CreateOrEditQuestionAlertModal/CreateOrEditQuestionAlertModal.module.css
  frontend/src/metabase/notifications/modals/AlertsModals/CreateOrEditQuestionAlertModal/CreateOrEditQuestionAlertModal.tsx
  frontend/src/metabase/notifications/modals/AlertsModals/QuestionAlertListModal/AlertListItem.tsx
  frontend/src/metabase/notifications/modals/shared/components/NotificationChannels/NotificationChannelsPicker/DefaultTemplatesPicker.tsx
  frontend/src/metabase/notifications/modals/shared/components/NotificationChannels/NotificationChannelsPicker/NotificationChannelsPicker.tsx
  frontend/src/metabase/notifications/modals/shared/components/NotificationChannels/NotificationChannelsPicker/default_templates.ts
  src/metabase/channel/impl/slack.clj
  src/metabase/channel/template/default.clj
  src/metabase/notification/api/notification.clj
  src/metabase/notification/payload/execute.clj
  src/metabase/notification/payload/impl/card.clj
  test/metabase/channel/impl/slack_test.clj
  test/metabase/dashboard_subscription_test.clj
  test/metabase/notification/api/notification_test.clj
  test/metabase/notification/payload/impl/card_test.clj
  test/metabase/pulse/send_test.clj
Labels: .Team/Workflows

#57365 [Admin] Modernize components for People + Groups pages
  enterprise/frontend/src/metabase-enterprise/audit_app/components/UnsubscribeUserForm/UnsubscribeUserForm.tsx
  enterprise/frontend/src/metabase-enterprise/audit_app/index.js
  enterprise/frontend/src/metabase-enterprise/audit_app/routes.jsx
  frontend/src/metabase/admin/people/colors.ts
  frontend/src/metabase/admin/people/components/AddMemberRow.tsx
  frontend/src/metabase/admin/people/components/AddRow.tsx
  frontend/src/metabase/admin/people/components/GroupDetail.tsx
  frontend/src/metabase/admin/people/components/GroupMembersTable/GroupMembersTable.tsx
  frontend/src/metabase/admin/people/components/GroupMembersTable/index.ts
  frontend/src/metabase/admin/people/components/GroupSummary.tsx
  frontend/src/metabase/admin/people/components/GroupsListing.tsx
  frontend/src/metabase/admin/people/components/MembershipSelect/MembershipSelect.module.css
  frontend/src/metabase/admin/people/components/MembershipSelect/MembershipSelect.tsx
  frontend/src/metabase/admin/people/components/PeopleList.tsx
  frontend/src/metabase/admin/people/components/PeopleListRow.tsx
  frontend/src/metabase/admin/people/containers/EditUserModal/EditUserModal.tsx
  frontend/src/metabase/admin/people/containers/NewUserModal.tsx
  frontend/src/metabase/admin/people/containers/PeopleListingApp.tsx
  frontend/src/metabase/admin/people/containers/UserActivationModal.tsx
  frontend/src/metabase/admin/people/containers/UserPasswordResetModal.tsx
  frontend/src/metabase/admin/people/containers/UserSuccessModal.tsx
  frontend/src/metabase/admin/people/forms/UserForm.tsx
  frontend/src/metabase/admin/routes.jsx
  frontend/src/metabase/admin/settings/components/widgets/GroupMappingsWidget/GroupSelect/GroupSelect.tsx
  frontend/src/metabase/components/ConfirmModal/ConfirmModal.tsx
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/query_builder/components/MoveQuestionModal/MoveQuestionModal.tsx
  frontend/src/metabase/query_builder/components/expressions/Editor/CloseModal/CloseModal.tsx
  frontend/src/metabase/ui/components/inputs/Pill/index.ts
Labels: no-backport, .Team/AdminWebapp

#57738 Add "Visualize another way" action
  e2e/support/helpers/e2e-dashboard-visualizer-helpers.ts
  e2e/test/scenarios/dashboard/visualizer/basics.cy.spec.ts
  frontend/src/metabase/dashboard/components/DashCard/DashCard.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardActionsPanel.tsx
  frontend/src/metabase/dashboard/components/DashCard/Dashcard.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardGrid.tsx
Labels: .Team/DashViz

#57490 [Admin] Convert people / group pages to RTKQuery
  e2e/test/scenarios/admin-2/people.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/audit_app/components/UnsubscribeUserForm/UnsubscribeUserForm.styled.tsx
  enterprise/frontend/src/metabase-enterprise/audit_app/components/UnsubscribeUserForm/UnsubscribeUserForm.tsx
  enterprise/frontend/src/metabase-enterprise/audit_app/components/UnsubscribeUserForm/UnsubscribeUserForm.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/audit_app/components/UnsubscribeUserForm/index.js
  enterprise/frontend/src/metabase-enterprise/audit_app/containers/UnsubscribeUserModal/UnsubscribeUserModal.tsx
  enterprise/frontend/src/metabase-enterprise/audit_app/containers/UnsubscribeUserModal/UnsubscribeUserModal.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/collections/use-get-default-collection-id/use-get-default-collection-id.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/group_managers/actions.js
  enterprise/frontend/src/metabase-enterprise/group_managers/utils.ts
  frontend/src/metabase-types/api/group.ts
  frontend/src/metabase-types/api/schema.ts
  frontend/src/metabase-types/api/user.ts
  frontend/src/metabase-types/store/entities.ts
  frontend/src/metabase-types/store/mocks/entities.ts
  frontend/src/metabase/account/profile/actions.ts
  frontend/src/metabase/admin/people/components/AddMemberRow.tsx
  frontend/src/metabase/admin/people/components/GroupDetail.tsx
  frontend/src/metabase/admin/people/components/GroupMembersTable/GroupMembersTable.tsx
  frontend/src/metabase/admin/people/components/GroupsListing.tsx
  frontend/src/metabase/admin/people/components/PeopleList.tsx
  frontend/src/metabase/admin/people/components/PeopleListRow.tsx
  frontend/src/metabase/admin/people/constants.js
  frontend/src/metabase/admin/people/constants.ts
  frontend/src/metabase/admin/people/containers/GroupDetailApp.tsx
  frontend/src/metabase/admin/people/containers/GroupsListingApp.tsx
  frontend/src/metabase/admin/people/containers/NewUserModal.tsx
  frontend/src/metabase/admin/people/containers/PeopleListingApp.tsx
  frontend/src/metabase/admin/people/containers/UserActivationModal.tsx
  frontend/src/metabase/admin/people/containers/UserPasswordResetModal.tsx
  frontend/src/metabase/admin/people/events.js
  frontend/src/metabase/admin/people/hooks/use-people-query.ts
  frontend/src/metabase/admin/people/people.js
  frontend/src/metabase/admin/people/selectors.js
  frontend/src/metabase/api/permission.ts
  frontend/src/metabase/api/session.ts
  frontend/src/metabase/api/user.ts
  frontend/src/metabase/common/components/Sidesheet/components/InsightsTabOrLink/tests/setup.tsx
  frontend/src/metabase/components/ConfirmModal/ConfirmModal.tsx
  frontend/src/metabase/components/SaveQuestionForm/context.unit.spec.tsx
  frontend/src/metabase/dashboard/components/DashboardInfoSidebar/tests/setup.tsx
  frontend/src/metabase/entities/collections/tests/selectors.unit.spec.js
  frontend/src/metabase/entities/containers/EntityName.unit.spec.tsx
  frontend/src/metabase/entities/groups.js
  frontend/src/metabase/entities/index.js
  frontend/src/metabase/entities/users.js
  frontend/src/metabase/plugins/types.ts
  frontend/src/metabase/query_builder/components/view/sidebars/QuestionInfoSidebar/tests/setup.tsx
  frontend/src/metabase/redux/user.ts
  frontend/src/metabase/schema.js
  frontend/src/metabase/services.js
  frontend/test/__support__/server-mocks/audit.ts
  frontend/test/__support__/store.ts
  src/metabase/permissions/models/permissions_group.clj
Labels: no-backport, .Team/AdminWebapp

#56357 Bump org.apache.poi/poi-ooxml-full from 5.4.0 to 5.4.1
  deps.edn
Labels: no-backport

#57673 Add analytics for new entity creation being initiated
  e2e/test/scenarios/collections/collections.cy.spec.js
  e2e/test/scenarios/onboarding/home/browse.cy.spec.ts
  e2e/test/scenarios/onboarding/home/homepage.cy.spec.js
  frontend/src/metabase-types/analytics/event.ts
  frontend/src/metabase/browse/metrics/BrowseMetrics.tsx
  frontend/src/metabase/browse/metrics/analytics.ts
  frontend/src/metabase/browse/models/BrowseModels.tsx
  frontend/src/metabase/browse/models/analytics.ts
  frontend/src/metabase/collections/components/CollectionEmptyState/CollectionEmptyState.tsx
  frontend/src/metabase/collections/components/CollectionEmptyState/analytics.ts
  frontend/src/metabase/collections/components/CollectionHeader/CollectionNewButton.tsx
  frontend/src/metabase/collections/components/CollectionHeader/analytics.ts
  frontend/src/metabase/components/NewItemMenu/NewItemMenu.tsx
  frontend/src/metabase/components/NewItemMenu/analytics.ts
  frontend/src/metabase/nav/components/NewItemButton/NewItemButton.tsx
  frontend/src/metabase/nav/components/NewItemButton/analytics.ts
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/MainNavbarView.tsx
  frontend/src/metabase/nav/containers/MainNavbar/analytics.ts
Labels: no-backport

#57577 Bump io.github.eerohele/pp from 9598f4c72b528480a85ea41651c45b08d1717428 to 4998a1fdd9d3713d7034d04509e9212204773bf2
  deps.edn
Labels: no-backport

#56654 Bump commons-io/commons-io from 2.18.0 to 2.19.0
  deps.edn
Labels: no-backport

#56885 Shutdown index sync while its results are unused
  modules/drivers/mongo/src/metabase/driver/mongo.clj
  modules/drivers/mongo/test/metabase/driver/mongo_test.clj
  modules/drivers/sqlite/src/metabase/driver/sqlite.clj
  modules/drivers/sqlserver/src/metabase/driver/sqlserver.clj
  src/metabase/driver.clj
  src/metabase/driver/h2.clj
  src/metabase/driver/mysql.clj
  src/metabase/driver/postgres.clj
  test/metabase/api/database_test.clj
  test/metabase/api/field_test.clj
  test/metabase/api/table_test.clj
Labels: no-backport, .Team/SemanticLayer

#56952 Bump com.google.guava/guava from 33.4.6-jre to 33.4.8-jre
  deps.edn
  modules/drivers/mongo/deps.edn
Labels: no-backport

#57578 Bump io.github.tonsky/clj-reload from 0.9.4 to 0.9.5
  deps.edn
Labels: no-backport

#57575 Bump babashka/fs from 0.5.24 to 0.5.25
  deps.edn
Labels: no-backport

#54171 Bump org.apache.calcite.avatica/avatica from 1.25.0 to 1.26.0
  modules/drivers/druid-jdbc/deps.edn
Labels: no-backport

#56694 fix: toolbar button color not changing on hover
  frontend/src/metabase/components/ToolbarButton/ToolbarButton.tsx
Labels: backport
