Repository metabase/metabase, pull requests merged in 2025-09, with the labels that each got.

#62964 Maz Comments styling tweaks
  enterprise/frontend/src/metabase-enterprise/comments/components/CommentEditor/CommentEditor.tsx
  enterprise/frontend/src/metabase-enterprise/comments/components/Discussion/Discussion.stories.tsx
  enterprise/frontend/src/metabase-enterprise/comments/components/Discussions/Discussions.tsx
  enterprise/frontend/src/metabase-enterprise/documents/components/CommentsSidesheet/CommentsSidesheet.module.css
  enterprise/frontend/src/metabase-enterprise/documents/components/CommentsSidesheet/CommentsSidesheet.tsx
  enterprise/frontend/src/metabase-enterprise/documents/components/Editor/CommentsMenu/CommentsMenu.tsx
  enterprise/frontend/src/metabase-enterprise/documents/components/Editor/extensions/Blockquote/Blockquote.tsx
  enterprise/frontend/src/metabase-enterprise/documents/components/Editor/extensions/BulletList/BulletList.tsx
  enterprise/frontend/src/metabase-enterprise/documents/components/Editor/extensions/CardEmbed/CardEmbedNode.tsx
  enterprise/frontend/src/metabase-enterprise/documents/components/Editor/extensions/CodeBlock/CodeBlock.tsx
  enterprise/frontend/src/metabase-enterprise/documents/components/Editor/extensions/Heading/Heading.tsx
  enterprise/frontend/src/metabase-enterprise/documents/components/Editor/extensions/OrderedList/OrderedList.tsx
  enterprise/frontend/src/metabase-enterprise/documents/components/Editor/extensions/Paragraph/Paragraph.tsx
  frontend/src/metabase-types/api/comments.ts
  frontend/src/metabase-types/api/mocks/comment.ts
  frontend/src/metabase-types/api/mocks/document.ts
Labels: no-backport, PR-Env

#62867 🤖 backported "Fix flaky test for metabase-browser custom element"
  e2e/test/scenarios/embedding/sdk-iframe-embedding/view-and-curate-content.cy.spec.ts
Labels: was-backported

#62854 Hide CSV panel with no meaningful uploadable dbs
  e2e/test/scenarios/onboarding/add-initial-data.cy.spec.ts
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/AddDataModal/AddDataModal.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/AddDataModal/tests/common.unit.spec.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/AddDataModal/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/AddDataModal/tests/premium-advanced-permissions.unit.spec.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/AddDataModal/tests/premium-hosting-upload.unit.spec.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/AddDataModal/use-add-data-permission.ts
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/AddDataModal/use-add-data-permission.unit.spec.ts
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/AddDataModal/utils.ts
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/AddDataModal/utils.unit.spec.ts
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/BrowseNavSection.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/BrowseNavSection.unit.spec.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/GettingStartedSection.tsx
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/GettingStartedSection.unit.spec.tsx
Labels: backport, .Team/ProductGrowth

#62992 🤖 backported "Closes EMB-650 move download button to footer for title-less embed tables"
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedQuestionView_Table_Light_Theme.png
  frontend/src/metabase/data-grid/components/DataGrid/DataGrid.tsx
  frontend/src/metabase/data-grid/components/Footer/Footer.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestionView.stories.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestionView.tsx
  frontend/src/metabase/visualizations/components/TableInteractive/TableInteractive.tsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.tsx
  frontend/src/metabase/visualizations/types/visualization.ts
Labels: was-backported

#62990 Closes EMB-716 publicly shared maps in dashboards
  frontend/src/metabase/visualizations/lib/map.ts
  frontend/src/metabase/visualizations/lib/map.unit.spec.ts
Labels: backport, .Team/Embedding

#62812 🤖 backported "[Metabot] Add `available_actions` to metabot context"
  enterprise/backend/src/metabase_enterprise/metabot_v3/context.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/context_test.clj
  enterprise/frontend/src/metabase-enterprise/api/ai-streaming/test-utils.ts
  enterprise/frontend/src/metabase-enterprise/metabot/context.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/metabot.unit.spec.tsx
  frontend/src/metabase/api/database.ts
Labels: was-backported

#62893 Return explicit errors when trying to edit a table without a PK
  enterprise/backend/src/metabase_enterprise/action_v2/data_editing.clj
  src/metabase/driver/sql_jdbc/actions.clj
  test/metabase/actions/actions_test.clj
Labels: no-backport, .Team/Workflows

#62978 Auto-update documentation for master
  docs/api.html
Labels: Type:Documentation, no-backport

#63020 🤖 backported "disable starburst"
  .github/workflows/drivers.yml
Labels: was-backported

#60562 feat(sdk): use entity ids directly in collection picker and browser
  e2e/test-component/scenarios/embedding-sdk/collection-browser.cy.spec.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkQuestion/components/SdkSaveQuestionForm.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkQuestionDefaultView/SdkQuestionDefaultView.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/public/CollectionBrowser/CollectionBrowser.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/public/CreateDashboardModal/CreateDashboardModal.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/public/CreateDashboardModal/CreateDashboardModal.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk-bundle/lib/create-dashboard.ts
  enterprise/frontend/src/embedding-sdk-bundle/store/collections.ts
  enterprise/frontend/src/metabase-enterprise/clean_up/analytics.ts
  frontend/src/metabase-types/api/collection.ts
  frontend/src/metabase/collections/utils.unit.spec.ts
  frontend/src/metabase/common/components/SaveQuestionForm/context.tsx
  frontend/src/metabase/nav/components/CollectionBreadcrumbs/utils.ts
Labels: no-backport, .Team/Embedding

#62954 Embed JS should show "Try it out" before docs in admin panel
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/EmbeddingSdkSettings.tsx
Labels: backport, .Team/Embedding

#63024 🤖 backported "fix(sdk): prevent double scrollbars in sdk dashboards"
  frontend/src/metabase/dashboard/components/Dashboard/Dashboard.tsx
Labels: was-backported

#63022 🤖 backported "Embed JS should show "Try it out" before docs in admin panel"
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/EmbeddingSdkSettings.tsx
Labels: was-backported

#63021 feat: audit for cloud add on purchase
  .clj-kondo/config/modules/config.edn
  enterprise/backend/src/metabase_enterprise/cloud_add_ons/api.clj
  enterprise/backend/test/metabase_enterprise/cloud_add_ons/api_test.clj
  src/metabase/audit_app/events/audit_log.clj
Labels: double-backport, cloud

#61522 Pg Replication Preview modal
  .clj-kondo/config/modules/config.edn
  .github/workflows/uberjar-containerize-labeled.yml
  CLAUDE.md
  enterprise/backend/src/metabase_enterprise/database_replication/api.clj
  enterprise/backend/src/metabase_enterprise/harbormaster/client.clj
  enterprise/backend/test/metabase_enterprise/database_replication/api_test.clj
  enterprise/frontend/src/metabase-enterprise/api/database-replication.ts
  enterprise/frontend/src/metabase-enterprise/database_replication/DatabaseReplicationButton.tsx
  enterprise/frontend/src/metabase-enterprise/database_replication/DatabaseReplicationButton.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/database_replication/DatabaseReplicationError.tsx
  enterprise/frontend/src/metabase-enterprise/database_replication/DatabaseReplicationForm.tsx
  enterprise/frontend/src/metabase-enterprise/database_replication/DatabaseReplicationModal.tsx
  enterprise/frontend/src/metabase-enterprise/database_replication/DatabaseReplicationModal.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/database_replication/DatabaseReplicationPostgresInfo.tsx
  enterprise/frontend/src/metabase-enterprise/database_replication/DatabaseReplicationSection.tsx
  enterprise/frontend/src/metabase-enterprise/database_replication/DatabaseReplicationSettingUp.tsx
  enterprise/frontend/src/metabase-enterprise/database_replication/DatabaseReplicationStatusInfo.tsx
  enterprise/frontend/src/metabase-enterprise/database_replication/DatabaseReplicationStatusInfo.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/database_replication/DatabaseReplicationSuccess.tsx
  frontend/src/metabase/admin/databases/components/DatabaseInfoSection.tsx
  src/metabase/driver/sync.clj
  src/metabase/premium_features/core.clj
  src/metabase/premium_features/token_check.clj
Labels: no-backport, build-docker-uberjar

#62931 🤖 backported "[ClickHouse] Handle SSH tunneling when checking for `:connection-impersonation` support"
  modules/drivers/clickhouse/src/metabase/driver/clickhouse.clj
  modules/drivers/clickhouse/src/metabase/driver/clickhouse_version.clj
  modules/drivers/clickhouse/test/metabase/driver/clickhouse_impersonation_test.clj
  test/metabase/actions/actions_test.clj
  test/metabase/driver/sql_jdbc/connection_test.clj
  test/metabase/driver/test_util.clj
Labels: was-backported

#63029 🤖 backported "feat: audit for cloud add on purchase"
  .clj-kondo/config/modules/config.edn
  enterprise/backend/src/metabase_enterprise/cloud_add_ons/api.clj
  enterprise/backend/test/metabase_enterprise/cloud_add_ons/api_test.clj
  src/metabase/audit_app/events/audit_log.clj
Labels: was-backported

#62883 Use container padding to provide space between items in entity picker
  e2e/test/scenarios/question/notebook-data-source.cy.spec.ts
  frontend/src/metabase/common/components/EntityPicker/components/ItemList/ItemList.tsx
  frontend/src/metabase/common/components/Pickers/DataPicker/components/DatabaseList.tsx
Labels: backport, .Team/UXWest

#62357 Make Usage Analytics work on mysql
  .clj-kondo/config/modules/config.edn
  enterprise/backend/src/metabase_enterprise/audit_app/audit.clj
  enterprise/backend/test/metabase_enterprise/audit_app/audit_test.clj
  enterprise/backend/test/metabase_enterprise/audit_app/permissions_test.clj
  test/metabase/driver/sql_jdbc/execute_test.clj
  test/metabase/session/models/session_test.clj
  test/metabase/settings/api_test.clj
  test/metabase/test/util.clj
Labels: .Team/DevEx, triple-backport

#62989 Show non-aggregation functions in aggregations
  e2e/test/scenarios/custom-column/custom-column-reproductions.cy.spec.js
  frontend/src/metabase/querying/expressions/config.ts
  frontend/src/metabase/querying/expressions/fuzz.compiler.unit.spec.ts
  frontend/src/metabase/querying/expressions/suggestions/aggregations.unit.spec.ts
Labels: backport, .Team/Querying

#63001 Show loading indicator overlay immediately on embed flow preview
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/select-embed-experience.cy.spec.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/EmbedPreviewLoadingOverlay.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/SdkIframeEmbedPreview.tsx
Labels: backport, .Team/Embedding

#63052 🤖 backported "Show non-aggregation functions in aggregations"
  e2e/test/scenarios/custom-column/custom-column-reproductions.cy.spec.js
  frontend/src/metabase/querying/expressions/config.ts
  frontend/src/metabase/querying/expressions/fuzz.compiler.unit.spec.ts
  frontend/src/metabase/querying/expressions/suggestions/aggregations.unit.spec.ts
Labels: was-backported

#63009 WRK-865 Flaky Test: detail view value rendering respects datamodel remapping and viz settings
  e2e/test/scenarios/detail-view/detail-view.cy.spec.ts
Labels: no-backport, .Team/Workflows, .Team/UXEast

#63042 two fixes, compaction and when to run
  .github/actions/test-driver/action.yml
  .github/workflows/backend.yml
  resources/c3p0.properties
  test_config/log4j2-test.xml
Labels: backport

#62892 Fix time-interval filters
  src/metabase/query_processor/parameters/dates.clj
  test/metabase/parameters/dashboard_test.clj
  test/metabase/query_processor/parameters/dates_test.clj
Labels: no-backport

#63076 🤖 backported "Quick ci test disabling"
  .github/actions/prepare-backend/action.yml
  ci-test-config.json
  deps.edn
  test/metabase/test_runner.clj
Labels: was-backported

#63075 🤖 backported "Quick ci test disabling"
  .github/actions/prepare-backend/action.yml
  ci-test-config.json
  deps.edn
  test/metabase/test_runner.clj
Labels: was-backported

#62950 Stop pushing useless version info highlights
  release/src/version-info.ts
  release/src/version-info.unit.spec.ts
Labels: .Building & Releasing, no-backport, .Team/UXWest

#63064 feat(embed-js): throws when setting invalid metabaseConfig keys
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/constants.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/embed.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/embed.unit.spec.ts
Labels: backport, .Team/Embedding

#63062 Apply the new upsell flow to interactive and embed js upsells
  e2e/test/scenarios/embedding/embedding-smoketests.cy.spec.js
  e2e/test/scenarios/embedding/embedding-upsells.cy.spec.ts
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingOption/InteractiveEmbeddingOptionCard/InteractiveEmbeddingOptionCard.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/EmbeddingSdkSettings.tsx
  frontend/src/metabase/admin/upsells/UpsellEmbeddingButton.tsx
Labels: backport, .Team/Embedding

#63080 🤖 backported "feat(embed-js): throws when setting invalid metabaseConfig keys"
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/constants.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/embed.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/embed.unit.spec.ts
Labels: was-backported

#62788 🤖 backported "add yarn storybook-pure command"
  package.json
Labels: was-backported

#61681 block prs coming from master
  .github/workflows/block-master-source-branch-prs.yml
Labels: no-backport, .Team/DevEx

#63046 Set initial timestamp in create event modal
  e2e/test/scenarios/organization/timelines-collection.cy.spec.js
  frontend/src/metabase/forms/components/FormDateInput/FormDateInput.tsx
  frontend/src/metabase/timelines/common/components/EventForm/EventForm.tsx
Labels: backport, .Team/UXWest

#62960 Add repair-index! API with temp table mechanism for detecting lost deletes
  enterprise/backend/src/metabase_enterprise/semantic_search/core.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/init.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/pgvector_api.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/repair.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/settings.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/task/index_cleanup.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/task/index_repair.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/repair_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/task/index_cleanup_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/test_util.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/without_init_test.clj
  src/metabase/search/semantic/core.clj
Labels: no-backport, .Team/Metabot

#63094 🤖 backported "stabilize composed regex schemas"
  src/metabase/util/malli/registry.cljc
  test/metabase/util/malli/registry_test.cljc
  test/metabase/util/malli/registry_test_macro.clj
  test/metabase/util/malli/registry_test_macro.cljs
Labels: was-backported

#62835 Add transform run start/end time and run method filters to the list endpoint
  e2e/test/scenarios/admin/transforms.cy.spec.ts
  enterprise/backend/src/metabase_enterprise/transforms/api.clj
  enterprise/backend/src/metabase_enterprise/transforms/models/transform_run.clj
  enterprise/backend/src/metabase_enterprise/transforms/util.clj
  enterprise/backend/test/metabase_enterprise/transforms/api_test.clj
  enterprise/frontend/src/metabase-enterprise/transforms/pages/JobListPage/JobList/JobList.tsx
  enterprise/frontend/src/metabase-enterprise/transforms/pages/RunListPage/FilterList/FilterFieldSet/FilterFieldSet.tsx
  enterprise/frontend/src/metabase-enterprise/transforms/pages/RunListPage/FilterList/FilterList.tsx
  enterprise/frontend/src/metabase-enterprise/transforms/pages/RunListPage/FilterList/RunMethodFilterWidget/RunMethodFilterWidget.tsx
  enterprise/frontend/src/metabase-enterprise/transforms/pages/RunListPage/FilterList/RunMethodFilterWidget/index.ts
  enterprise/frontend/src/metabase-enterprise/transforms/pages/RunListPage/FilterList/TimeFilterWidget/TimeFilterWidget.tsx
  enterprise/frontend/src/metabase-enterprise/transforms/pages/RunListPage/FilterList/TimeFilterWidget/index.ts
  enterprise/frontend/src/metabase-enterprise/transforms/pages/RunListPage/RunList/RunList.tsx
  enterprise/frontend/src/metabase-enterprise/transforms/pages/RunListPage/RunListPage.tsx
  enterprise/frontend/src/metabase-enterprise/transforms/pages/RunListPage/utils.ts
  enterprise/frontend/src/metabase-enterprise/transforms/pages/TransformListPage/TransformList/TransformList.tsx
  enterprise/frontend/src/metabase-enterprise/transforms/pages/TransformPage/RunSection/RunSection.tsx
  enterprise/frontend/src/metabase-enterprise/transforms/types.ts
  enterprise/frontend/src/metabase-enterprise/transforms/urls.ts
  enterprise/frontend/src/metabase-enterprise/transforms/utils.ts
  frontend/src/metabase-types/api/transform.ts
  src/metabase/search/filter.clj
Labels: no-backport, .Team/Querying

#62966 Fix semantic search tests when running on mysql and enable all appdbs in CI
  .github/workflows/semantic-search.yml
  enterprise/backend/src/metabase_enterprise/semantic_search/scoring.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/core_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/scoring_test.clj
  src/metabase/search/in_place/legacy.clj
Labels: no-backport, .Team/Metabot

#63055 Mark tests as flaky
  e2e/test/scenarios/dashboard/visualizer/basics.cy.spec.ts
  e2e/test/scenarios/dashboard/visualizer/drillthrough.cy.spec.ts
  e2e/test/scenarios/native/native-reproductions.cy.spec.ts
Labels: no-backport

#63078 Ignore some test vars
  ci-test-config.json
Labels: no-backport

#62804 Type parameter value
  e2e/test/scenarios/native-filters/sql-filters-reset-clear.cy.spec.ts
  frontend/src/metabase-lib/v1/parameters/types.ts
  frontend/src/metabase-lib/v1/parameters/utils/cards.ts
  frontend/src/metabase-lib/v1/parameters/utils/click-behavior.ts
  frontend/src/metabase-lib/v1/parameters/utils/parameter-parsing.ts
  frontend/src/metabase-lib/v1/urls.ts
  frontend/src/metabase-types/api/parameters.ts
  frontend/src/metabase-types/store/dashboard.ts
  frontend/src/metabase-types/store/qb.ts
  frontend/src/metabase/actions/components/ActionViz/Action.tsx
  frontend/src/metabase/actions/components/ActionViz/utils.ts
  frontend/src/metabase/dashboard/actions/getNewCardUrl.ts
  frontend/src/metabase/dashboard/actions/parameters.tsx
  frontend/src/metabase/dashboard/reducers-typed.ts
  frontend/src/metabase/dashboard/utils.unit.spec.ts
  frontend/src/metabase/lib/validate.js
  frontend/src/metabase/lib/validate.ts
  frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget/ParameterFieldWidget.tsx
  frontend/src/metabase/parameters/components/widgets/StringInputWidget/StringInputWidget.tsx
  frontend/src/metabase/public/lib/types.ts
  frontend/src/metabase/query_builder/actions/core/core.ts
  frontend/src/metabase/visualizations/visualizations/Heading/Heading.unit.spec.tsx
  frontend/src/metabase/visualizations/visualizations/Text/Text.unit.spec.tsx
  frontend/test/metabase/lib/validate.unit.spec.js
Labels: no-backport, .Team/Querying

#62967 Update pgvector to pg17 in semantic search docker-compose.yml and CI workflow
  .github/workflows/semantic-search.yml
  enterprise/backend/src/metabase_enterprise/semantic_search/docker-compose.yml
Labels: no-backport, .Team/Metabot

#63072 feat: add comment reactions
  enterprise/frontend/src/metabase-enterprise/api/comment.ts
  enterprise/frontend/src/metabase-enterprise/comments/components/Discussion/Discussion.module.css
  enterprise/frontend/src/metabase-enterprise/comments/components/Discussion/Discussion.tsx
  enterprise/frontend/src/metabase-enterprise/comments/components/Discussion/DiscussionActionPanel.tsx
  enterprise/frontend/src/metabase-enterprise/comments/components/Discussion/DiscussionComment.tsx
  enterprise/frontend/src/metabase-enterprise/comments/components/Discussion/DiscussionReactions.tsx
  frontend/src/metabase-types/api/comments.ts
  frontend/src/metabase-types/api/mocks/comment.ts
Labels: .Team/Workflows

#63121 🤖 backported "docs: Typo in Embedded JS"
  docs/embedding/embedded-analytics-js.md
Labels: was-backported

#63092 When navigating with browser back/forward buttons, re-run the query only when the existing query results are dirty
  e2e/test/scenarios/models/reproductions.cy.spec.ts
  frontend/src/metabase/query_builder/actions/core/core.ts
  frontend/src/metabase/query_builder/actions/querying.ts
Labels: no-backport, .Team/Querying

#62776 Add transform dependencies and job transforms endpoints
  e2e/test/scenarios/admin/transforms.cy.spec.ts
  enterprise/backend/src/metabase_enterprise/transforms/api.clj
  enterprise/backend/src/metabase_enterprise/transforms/api/transform_job.clj
  enterprise/backend/src/metabase_enterprise/transforms/jobs.clj
  enterprise/backend/src/metabase_enterprise/transforms/ordering.clj
  enterprise/backend/test/metabase_enterprise/transforms/api/transform_job_test.clj
  enterprise/backend/test/metabase_enterprise/transforms/api_test.clj
  enterprise/backend/test/metabase_enterprise/transforms/jobs_test.clj
  enterprise/frontend/src/metabase-enterprise/api/tags.ts
  enterprise/frontend/src/metabase-enterprise/api/transform-job.ts
  enterprise/frontend/src/metabase-enterprise/api/transform.ts
  enterprise/frontend/src/metabase-enterprise/transforms/components/JobView/DependenciesSection/DependenciesSection.module.css
  enterprise/frontend/src/metabase-enterprise/transforms/components/JobView/DependenciesSection/DependenciesSection.tsx
  enterprise/frontend/src/metabase-enterprise/transforms/components/JobView/DependenciesSection/index.ts
  enterprise/frontend/src/metabase-enterprise/transforms/components/JobView/JobView.tsx
  enterprise/frontend/src/metabase-enterprise/transforms/components/TitleSection/TitleSection.tsx
  enterprise/frontend/src/metabase-enterprise/transforms/pages/TransformPage/DependenciesSection/DependenciesSection.module.css
  enterprise/frontend/src/metabase-enterprise/transforms/pages/TransformPage/DependenciesSection/DependenciesSection.tsx
  enterprise/frontend/src/metabase-enterprise/transforms/pages/TransformPage/DependenciesSection/index.ts
  enterprise/frontend/src/metabase-enterprise/transforms/pages/TransformPage/TransformPage.tsx
Labels: no-backport, .Team/Querying

#63124 🤖 backported "feat(sdk): native questions should hide filter and summarize from toolbar"
  e2e/test-component/scenarios/embedding-sdk/sdk-question-native.cy.spec.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/private/SdkQuestionDefaultView/SdkQuestionDefaultView.tsx
Labels: was-backported

#63106 Auto-update documentation for master
  docs/api.html
Labels: Type:Documentation, no-backport

#63097 docs - metabot notes
  docs/ai/metabot.md
  docs/ai/settings.md
Labels: Type:Documentation, double-backport

#63132 🤖 backported "docs - metabot notes"
  docs/ai/metabot.md
  docs/ai/settings.md
Labels: was-backported

#63126 fix(embed-js): copywriting improvements for embed flow
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/select-embed-options.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding/view-and-curate-content.cy.spec.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/components/MetabaseBrowser.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/types/embed.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/SelectEmbedOptionsStep.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/constants.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/utils/theme-colors.ts
Labels: backport, .Team/Embedding

#63138 docs - clarify data collection for Metabase editions
  docs/usage-and-performance-tools/usage-analytics.md
Labels: Type:Documentation, backport

#63051 inline dashcard parameter can only be mapped to the card
  e2e/test/scenarios/dashboard-filters/parameters.cy.spec.js
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapperContent.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/parameters/utils/mapping-options.ts
  frontend/src/metabase/parameters/utils/mapping-options.unit.spec.js
Labels: backport, .Team/UXWest

#63140 🤖 backported "inline dashcard parameter can only be mapped to the card"
  e2e/test/scenarios/dashboard-filters/parameters.cy.spec.js
  frontend/src/metabase/dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapperContent.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/parameters/utils/mapping-options.ts
  frontend/src/metabase/parameters/utils/mapping-options.unit.spec.js
Labels: was-backported

#63143 Add section about new connection string at top of db settings
  docs/databases/connections/athena.md
  docs/databases/connections/bigquery.md
  docs/databases/connections/clickhouse.md
  docs/databases/connections/databricks.md
  docs/databases/connections/druid.md
  docs/databases/connections/mariadb.md
  docs/databases/connections/mysql.md
  docs/databases/connections/oracle.md
  docs/databases/connections/postgresql.md
  docs/databases/connections/presto.md
  docs/databases/connections/redshift.md
  docs/databases/connections/snowflake.md
  docs/databases/connections/sparksql.md
  docs/databases/connections/sql-server.md
  docs/databases/connections/sqlite.md
  docs/databases/connections/starburst.md
Labels: Type:Documentation, backport

#63144 🤖 backported "Add section about new connection string at top of db settings"
  docs/databases/connections/athena.md
  docs/databases/connections/bigquery.md
  docs/databases/connections/clickhouse.md
  docs/databases/connections/databricks.md
  docs/databases/connections/druid.md
  docs/databases/connections/mariadb.md
  docs/databases/connections/mysql.md
  docs/databases/connections/oracle.md
  docs/databases/connections/postgresql.md
  docs/databases/connections/presto.md
  docs/databases/connections/redshift.md
  docs/databases/connections/snowflake.md
  docs/databases/connections/sparksql.md
  docs/databases/connections/sql-server.md
  docs/databases/connections/sqlite.md
  docs/databases/connections/starburst.md
Labels: was-backported

#63149 🤖 backported "convert mysql booleans to real booleans during semantic indexing"
  enterprise/backend/src/metabase_enterprise/semantic_search/index.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/index_test.clj
Labels: was-backported

#61747 Send CORS headers for localhost regardless of whether SDK is enabled or not
  .clj-kondo/config/modules/config.edn
  docs/configuring-metabase/config-template.md
  docs/configuring-metabase/environment-variables.md
  frontend/src/metabase-types/api/mocks/settings.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/EmbeddingSdkSettings.tsx
  src/metabase/analytics/stats.clj
  src/metabase/embedding/settings.clj
  src/metabase/server/middleware/security.clj
  src/metabase/server/settings.clj
  test/metabase/embedding/settings_test.clj
  test/metabase/server/middleware/security_test.clj
  test_resources/serialization_baseline/settings.yaml
Labels: no-backport, .Team/Embedding

#63014 feat(sdk): Add disc/memory caching for hosted bundle on top of etag caching
  e2e/support/helpers/e2e-browser-helpers.ts
  e2e/test-component/scenarios/embedding-sdk/sdk-bundle.cy.spec.tsx
  src/metabase/server/lib/etag_cache.clj
  src/metabase/server/middleware/embedding_sdk_bundle.clj
  src/metabase/server/middleware/etag_cache.clj
  src/metabase/server/routes.clj
  test/metabase/server/lib/etag_cache_test.clj
  test/metabase/server/middleware/embedding_sdk_bundle_test.clj
  test/metabase/server/middleware/etag_cache_test.clj
Labels: no-backport, .Team/Embedding, Embedding/SDK

#63074 Fix filtering on questions after dashboard drills when there are no perms to create queries
  e2e/test/scenarios/dashboard/title-drill.cy.spec.js
  e2e/test/scenarios/filters-reproductions/dashboard-filters-reproductions.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/sharing/components/MutableParametersSection.tsx
  frontend/src/metabase-lib/v1/Question.ts
  frontend/src/metabase/dashboard/components/DashboardParameterList/DashboardParameterList.tsx
  frontend/src/metabase/metadata/pages/DataModel/DataModel.unit.spec.tsx
  frontend/src/metabase/parameters/components/ParameterDropdownWidget.tsx
  frontend/src/metabase/parameters/components/ParameterValueWidget.tsx
  frontend/src/metabase/parameters/components/ParameterWidget/ParameterWidget.tsx
  frontend/src/metabase/parameters/components/ParametersList/ParametersList.tsx
  frontend/src/metabase/parameters/components/ParametersList/types.ts
  frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget/FieldValuesWidget/FieldValuesWidget.tsx
  frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget/FieldValuesWidget/utils.ts
  frontend/src/metabase/parameters/components/widgets/ParameterFieldWidget/ParameterFieldWidget.tsx
  frontend/src/metabase/public/components/EmbedFrame/EmbedFrame.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditorTopBar/NativeQueryEditorTopBar.tsx
  frontend/src/metabase/query_builder/components/ResponsiveParameterList.unit.spec.tsx
  frontend/src/metabase/query_builder/components/ResponsiveParametersList.tsx
  frontend/src/metabase/query_builder/components/SyncedParametersList.tsx
  frontend/src/metabase/query_builder/components/view/View/ViewMainContainer/ViewMainContainer.tsx
  frontend/src/metabase/services.js
Labels: backport, .Team/Querying

#63161 fix: limit editable functionality and add comment styles
  enterprise/frontend/src/metabase-enterprise/comments/components/CommentEditor/CommentEditor.module.css
  enterprise/frontend/src/metabase-enterprise/comments/components/CommentEditor/CommentEditor.tsx
Labels: .Team/Workflows

#63168 Cache Store OpenAPI description only for 5min
  enterprise/backend/src/metabase_enterprise/harbormaster/client.clj
Labels: double-backport

#62972 Bump net.thisptr/jackson-jq from 1.4.0 to 1.6.0
  deps.edn
Labels: no-backport

#63171 Closes EMB-779 content translation is now case insensitive
  enterprise/frontend/src/metabase-enterprise/content_translation/tests/utils.unit.spec.ts
  enterprise/frontend/src/metabase-enterprise/content_translation/utils.ts
Labels: backport, .Team/Embedding

#63179 🤖 backported "Closes EMB-779 content translation is now case insensitive"
  enterprise/frontend/src/metabase-enterprise/content_translation/tests/utils.unit.spec.ts
  enterprise/frontend/src/metabase-enterprise/content_translation/utils.ts
Labels: was-backported

#62647 Bump org.apache.sshd/sshd-core from 2.15.0 to 2.16.0
  deps.edn
Labels: no-backport

#62975 Bump com.facebook.presto/presto-jdbc from 0.293 to 0.294
  modules/drivers/presto-jdbc/deps.edn
Labels: no-backport

#62643 Bump djblue/portal from 0.60.2 to 0.61.0
  deps.edn
Labels: no-backport

#62654 Bump org.apache.arrow/arrow-memory-core from 17.0.0 to 18.3.0
  modules/drivers/bigquery-cloud-sdk/deps.edn
Labels: no-backport

#62942 🤖 backported "Differentiate different geographic drills and don't show duplicates"
  e2e/test/scenarios/visualizations-tabular/drillthroughs/chart_drill.cy.spec.js
  e2e/test/scenarios/visualizations-tabular/drillthroughs/geographic_drill.cy.spec.ts
  e2e/test/scenarios/visualizations-tabular/pivot_tables.cy.spec.js
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/querying/drills/utils/zoom-in-geographic-drill.ts
  src/metabase/lib/drill_thru/zoom_in_bins.cljc
  src/metabase/lib/drill_thru/zoom_in_geographic.cljc
  test/metabase/lib/drill_thru_test.cljc
Labels: was-backported

#62976 Bump net.snowflake/snowflake-jdbc-thin from 3.26.0 to 3.26.1
  modules/drivers/snowflake/deps.edn
Labels: no-backport

#62974 Bump com.google.cloud/google-cloud-bigquery from 2.54.1 to 2.54.2
  modules/drivers/bigquery-cloud-sdk/deps.edn
Labels: no-backport

#63202 🤖 backported "Update development instance documentation for clarity"
  docs/installation-and-operation/development-instance.md
Labels: was-backported

#62710 [BOT-284] BE for notebook query tool table support
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/api.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/filters.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/config_test.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/tools/filters_test.clj
Labels: no-backport, .Team/Metabot

#63182 fix(embed-js): bar charts no longer change scale when props change
  frontend/src/metabase/visualizations/shared/components/RowChart/utils/scale.ts
  frontend/src/metabase/visualizations/shared/components/RowChart/utils/scale.unit.spec.ts
Labels: backport, .Team/Embedding

#63204 🤖 backported "fix(embed-js): bar charts no longer change scale when props change"
  frontend/src/metabase/visualizations/shared/components/RowChart/utils/scale.ts
  frontend/src/metabase/visualizations/shared/components/RowChart/utils/scale.unit.spec.ts
Labels: was-backported

#62884 Include transform dependencies that have not been run yet
  docs/developers-guide/driver-changelog.md
  enterprise/backend/src/metabase_enterprise/transforms/ordering.clj
  enterprise/backend/test/metabase_enterprise/transforms/ordering_test.clj
  modules/drivers/bigquery-cloud-sdk/src/metabase/driver/bigquery_cloud_sdk.clj
  src/metabase/driver/sql.clj
Labels: no-backport, .Team/Querying, .Team/Drivers

#63120 Fix join step alignment
  frontend/src/metabase/querying/notebook/components/JoinStep/JoinComplete/JoinComplete.module.css
  frontend/src/metabase/querying/notebook/components/JoinStep/JoinComplete/JoinComplete.tsx
  frontend/src/metabase/querying/notebook/components/JoinStep/JoinConditionColumnPicker/JoinColumnButton/JoinColumnButton.module.css
  frontend/src/metabase/querying/notebook/components/JoinStep/JoinConditionDraft/JoinConditionDraft.tsx
  frontend/src/metabase/querying/notebook/components/JoinStep/JoinDraft/JoinDraft.module.css
  frontend/src/metabase/querying/notebook/components/JoinStep/JoinDraft/JoinDraft.tsx
Labels: backport, .Team/Querying

#63203 🤖 backported "BOT-310 lower the weight on the :rrf score for semantic search results"
  enterprise/backend/test/metabase_enterprise/semantic_search/query_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/scoring_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/test_util.clj
  src/metabase/search/config.clj
Labels: was-backported

#63157 Ensure flaky tests are tagged as flaky
  e2e/test/scenarios/admin-2/people.cy.spec.js
  e2e/test/scenarios/admin/transforms.cy.spec.ts
  e2e/test/scenarios/collections/uploads.cy.spec.js
  e2e/test/scenarios/embedding/embedding-reproductions.cy.spec.js
  e2e/test/scenarios/models/reproductions.cy.spec.ts
  e2e/test/scenarios/onboarding/setup/setup-embedding.cy.spec.ts
  e2e/test/scenarios/permissions/admin-permissions.cy.spec.js
  e2e/test/scenarios/permissions/sandboxing/sandboxing-via-ui.cy.spec.ts
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
Labels: .CI & Tests, no-backport, .Team/DevEx

#62476 Dev 780 Provide issue comments by employees to Claude Code
  .github/scripts/get-issue-data.js
  .github/workflows/claude-code-bug-fix.yml
Labels: .CI & Tests, no-backport, .Team/DevEx

#63172 Protect against nil search_vector
  src/metabase/search/appdb/specialization/postgres.clj
Labels: .Team/Workflows, triple-backport

#63238 🤖 backported "Protect against nil search_vector"
  src/metabase/search/appdb/specialization/postgres.clj
Labels: was-backported

#63166 🤖 backported "Remove `driver/set-use-database` in favour of setting the DB in the jdbc spec"
  enterprise/backend/test/metabase_enterprise/impersonation/driver_test.clj
  modules/drivers/snowflake/resources/metabase-plugin.yaml
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
  src/metabase/driver.clj
  src/metabase/driver/sql_jdbc/execute.clj
Labels: was-backported

#63274 🤖 backported "Pass validation errors to create dashboard modal"
  e2e/test/scenarios/dashboard/dashboard-reproductions.cy.spec.js
  frontend/src/metabase/dashboard/containers/CreateDashboardForm.tsx
Labels: was-backported

#63265 Add typedoc annotations for MetabotQuestion
  enterprise/frontend/src/embedding-sdk-bundle/components/public/MetabotQuestion/MetabotQuestion.tsx
Labels: Type:Documentation, no-backport, .Team/Embedding

#63290 fix(table-editing): disable row edit button when rows are selected
  e2e/test/scenarios/table-editing/table-editing.cy.spec.ts
  enterprise/frontend/src/metabase-enterprise/table-editing/table-edit/data-grid/use-table-column-row-select.tsx
Labels: no-backport, .Team/Workflows

#63291 Skip sdk-bundle test suite for backward-compat SDK tests
  .github/workflows/e2e-component-tests-embedding-sdk-backward-compatibility.yml
  e2e/runner/cypress-runner-run-tests.js
  e2e/test-component/scenarios/embedding-sdk/sdk-bundle.cy.spec.tsx
Labels: .CI & Tests, no-backport, .Team/Embedding

#63188 feat(sdk): Use `zod` schemas to validate exposed from SDK bundle Components and their props
  docs/embedding/sdk/next-js.md
  e2e/test-component/scenarios/embedding-sdk/sdk-bundle.cy.spec.tsx
  enterprise/frontend/src/.eslintrc.js
  enterprise/frontend/src/embedding-sdk-bundle/components/public/CollectionBrowser/CollectionBrowser.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/CollectionBrowser/CollectionBrowser.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/public/CreateDashboardModal/CreateDashboardModal.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/CreateDashboardModal/CreateDashboardModal.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/public/InteractiveQuestion/InteractiveQuestion.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/InteractiveQuestion/InteractiveQuestion.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/public/MetabotQuestion/MetabotQuestion.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/MetabotQuestion/MetabotQuestion.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/public/SdkDebugInfo/SdkDebugInfo.module.css
  enterprise/frontend/src/embedding-sdk-bundle/components/public/SdkDebugInfo/SdkDebugInfo.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/SdkDebugInfo/SdkDebugInfo.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/public/SdkDebugInfo/index.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/StaticQuestion/StaticQuestion.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/StaticQuestion/StaticQuestion.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/EditableDashboard/EditableDashboard.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/EditableDashboard/EditableDashboard.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/InteractiveDashboard/InteractiveDashboard.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/InteractiveDashboard/InteractiveDashboard.tsx
  enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/StaticDashboard/StaticDashboard.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/StaticDashboard/StaticDashboard.tsx
  enterprise/frontend/src/embedding-sdk-bundle/index.ts
  enterprise/frontend/src/embedding-sdk-bundle/lib/validate-function-schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/types/schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/types/sdk-bundle.ts
  enterprise/frontend/src/embedding-sdk-package/components/private/ComponentWrapper/ComponentWrapper.tsx
  enterprise/frontend/src/embedding-sdk-package/constants/error-messages.ts
  enterprise/frontend/src/embedding-sdk-package/dev.md
  enterprise/frontend/src/embedding-sdk-shared/types/validation.ts
  package.json
  yarn.lock
Labels: no-backport, .Team/Embedding, Embedding/SDK, no-release-notes

#63277 Adjust clj-kondo linter to allow keyword flags in `require`
  .clj-kondo/src/hooks/clojure/core/require.clj
Labels: no-backport, .Team/Querying

#63193 Don't add remaps from join columns that aren't in join `:fields`
  src/metabase/lib/core.cljc
  src/metabase/lib/join.cljc
  src/metabase/query_processor/middleware/add_remaps.clj
  test/metabase/lib/join_test.cljc
  test/metabase/lib/metadata/calculation_test.cljc
  test/metabase/lib/stage_test.cljc
  test/metabase/query_processor/middleware/add_remaps_test.clj
  test/metabase/query_processor_test/remapping_test.clj
Labels: backport, .Team/Querying, .Team/DevEx

#63254 Ensure results are realized when falling back to in-place results in semantic search
  enterprise/backend/src/metabase_enterprise/semantic_search/core.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/core_test.clj
Labels: backport, .Team/Metabot

#63309 Add tooltip to clear-conversation action in metabot panel
  enterprise/frontend/src/metabase-enterprise/metabot/components/MetabotChat/MetabotChat.tsx
Labels: backport

#63311 update placeholder copy
  enterprise/frontend/src/metabase-enterprise/documents/components/Editor/Editor.tsx
Labels: no-backport

#63294 Separate file / s3 lifetimes / writes / reads from http calls
  enterprise/backend/src/metabase_enterprise/transforms/api.clj
  enterprise/backend/src/metabase_enterprise/transforms/execute.clj
  enterprise/backend/src/metabase_enterprise/transforms/python_runner.clj
  enterprise/backend/test/metabase_enterprise/transforms/python_runner_test.clj
  enterprise/frontend/src/metabase-enterprise/transforms/components/QueryEditor/PythonEditor/PythonEditor.tsx
Labels: .Team/Metabot

#63335 Start python runner with driver tests
  .github/actions/await-port/action.yml
  .github/workflows/backend.yml
  .github/workflows/drivers.yml
  docs/developers-guide/driver-changelog.md
  enterprise/backend/src/metabase_enterprise/transforms/api.clj
  enterprise/backend/src/metabase_enterprise/transforms/execute.clj
  enterprise/backend/test/metabase_enterprise/transforms/python_runner_test.clj
Labels: .Team/Workflows

#63342 Fix stray bracket in version-info
  release/src/version-info.ts
  release/src/version-info.unit.spec.ts
Labels: .Building & Releasing, no-backport, .Team/UXWest

#63343 mark transform test flaky
  e2e/test/scenarios/admin/transforms.cy.spec.ts
Labels: .CI & Tests, flaky-test-fix, no-backport, .Team/UXWest, no-release-notes

#63301 fix: don't ignore db sync/rescan promise
  frontend/src/metabase/admin/databases/components/DatabaseConnectionInfoSection/DatabaseConnectionInfoSection.tsx
  frontend/src/metabase/admin/databases/components/DatabaseConnectionInfoSection/DatabaseConnectionInfoSection.unit.spec.tsx
  frontend/test/__support__/server-mocks/database.ts
Labels: no-backport, cloud

#63359 🤖 backported "Upgrade clickhouse jdbc driver to 0.9.2"
  modules/drivers/clickhouse/deps.edn
  modules/drivers/clickhouse/src/metabase/driver/clickhouse_qp.clj
  modules/drivers/clickhouse/test/metabase/driver/clickhouse_data_types_test.clj
  modules/drivers/clickhouse/test/metabase/driver/clickhouse_test.clj
Labels: was-backported

#63331 Avoid null names in semantic search document
  enterprise/backend/src/metabase_enterprise/semantic_search/index.clj
Labels: backport

#63361 🤖 backported "Disable column number mismatch error in prod"
  src/metabase/lib/metadata/result_metadata.cljc
Labels: was-backported

#63364 🤖 backported "fix table search crash when pressing enter without any table selected"
  frontend/src/metabase/metadata/pages/DataModel/components/TablePicker/TablePicker.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/TablePicker/TablePicker.unit.spec.tsx
Labels: was-backported

#63362 🤖 backported "Avoid null names in semantic search document"
  enterprise/backend/src/metabase_enterprise/semantic_search/index.clj
Labels: was-backported

#63468 Handle legacy viz settings where `base-type` might not be present
  e2e/test/scenarios/visualizations-tabular/visualizations-tabular-reproductions.cy.spec.js
  frontend/src/metabase-lib/v1/queries/utils/column-key.ts
  frontend/src/metabase-lib/v1/queries/utils/column-key.unit.spec.ts
  frontend/src/metabase-lib/v1/references.ts
  frontend/src/metabase/visualizations/visualizations/PivotTable/settings.ts
Labels: no-backport, .Team/Querying

#63418 Remove field filter popover cutoff e2e test
  e2e/test/scenarios/native-filters/native-filters-reproductions.cy.spec.js
Labels: .CI & Tests, no-backport

#63417 Remove skipped Metabase Cloud e2e tests
  e2e/test/scenarios/admin-2/settings.cy.spec.js
  frontend/src/metabase/admin/settings/components/SettingsNav/SettingsNav.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/widgets/SiteUrlWidget.unit.spec.tsx
Labels: .CI & Tests, no-backport, .Team/DevEx

#63492 🤖 backported "Closes EMB-791 custom pivot column title not being translated"
  e2e/test/scenarios/admin/i18n/content-translation/dashboards.cy.spec.ts
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.tsx
Labels: was-backported

#63452 Fall back to DESCRIBE if Athena JDBC reports duplicate column names
  modules/drivers/athena/src/metabase/driver/athena.clj
  modules/drivers/athena/test/metabase/driver/athena_test.clj
Labels: backport, .Team/Querying, double-backport, triple-backport

#63516 Ignore new flaky transform tests until they are fixed
  e2e/test/scenarios/admin/transforms.cy.spec.ts
Labels: no-backport, .Team/Querying

#63511 🤖 backported "Fall back to DESCRIBE if Athena JDBC reports duplicate column names"
  modules/drivers/athena/src/metabase/driver/athena.clj
  modules/drivers/athena/test/metabase/driver/athena_test.clj
Labels: was-backported

#63496 PRG-138 fix mongo and sql server YAML setup
  e2e/test/scenarios/admin/databases.cy.spec.js
  modules/drivers/mongo/resources/metabase-plugin.yaml
  modules/drivers/sqlserver/resources/metabase-plugin.yaml
Labels: backport, .Team/ProductGrowth

#63523 Fix flaky transform tests
  e2e/test/scenarios/admin/transforms.cy.spec.ts
Labels: no-backport, .Team/Querying

#63524 docs - elaborate on privacy
  docs/ai/settings.md
Labels: Type:Documentation, double-backport

#63527 🤖 backported "docs - elaborate on privacy"
  docs/ai/settings.md
Labels: was-backported

#63487 Fix skipped notebook info popoever e2e tests
  e2e/test/scenarios/question/notebook.cy.spec.js
Labels: .CI & Tests, no-backport

#63428 Fix skipped time series binning e2e test
  e2e/test/scenarios/binning/binning-options.cy.spec.js
Labels: .CI & Tests, no-backport

#63486 Enable skipped implicit-join and breakout e2e tests
  e2e/test/scenarios/dashboard-filters-2/dashboard-filters-2-stage-2.cy.spec.ts
  e2e/test/scenarios/dashboard-filters-2/dashboard-filters-2-stage-3.cy.spec.ts
  e2e/test/scenarios/dashboard-filters-2/dashboard-filters-2-stage-4.cy.spec.ts
  e2e/test/scenarios/dashboard-filters-2/dashboard-filters-3-stage.cy.spec.ts
Labels: .CI & Tests, no-backport

#63205 Update :bookmarked and :user_recency scorer to work with mysql and mariadb
  enterprise/backend/src/metabase_enterprise/semantic_search/scoring.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/scoring_test.clj
  src/metabase/search/scoring.clj
Labels: backport, .Team/Metabot

#63543 🤖 backported "Update :bookmarked and :user_recency scorer to work with mysql and mariadb"
  enterprise/backend/src/metabase_enterprise/semantic_search/scoring.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/scoring_test.clj
  src/metabase/search/scoring.clj
Labels: was-backported

#63531 Reindex has to be async on language change callback
  src/metabase/search/appdb/core.clj
  src/metabase/search/appdb/index.clj
Labels: backport, .Team/UXWest

#63544 🤖 backported "Reindex has to be async on language change callback"
  src/metabase/search/appdb/core.clj
  src/metabase/search/appdb/index.clj
Labels: was-backported

#62963 support value and goal column selection in progress visualization
  e2e/support/helpers/e2e-viz-settings-helpers.js
  e2e/test/scenarios/visualizations-charts/progress-bar.cy.spec.js
  frontend/src/metabase/static-viz/components/ProgressBar/ProgressBar.stories.tsx
  frontend/src/metabase/static-viz/components/ProgressBar/ProgressBar.tsx
  frontend/src/metabase/static-viz/components/ProgressBar/index.ts
  frontend/src/metabase/static-viz/components/ProgressBar/stories-data.ts
  frontend/src/metabase/static-viz/components/ProgressBar/utils.ts
  frontend/src/metabase/static-viz/components/StaticVisualization/StaticVisualization.tsx
  frontend/src/metabase/static-viz/containers/LegacyStaticChart/LegacyStaticChart.tsx
  frontend/src/metabase/static-viz/register.js
  frontend/src/metabase/visualizations/components/settings/ChartSettingFieldPicker.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingGoalInput.tsx
  frontend/src/metabase/visualizations/visualizations/Progress/Progress.jsx
  frontend/src/metabase/visualizations/visualizations/Progress/utils.ts
  frontend/src/metabase/visualizations/visualizations/Progress/utils.unit.spec.ts
  frontend/test/metabase/visualizations/visualizations/Progress/utils.unit.spec.ts
  resources/frontend_shared/static_viz_interface.js
  src/metabase/channel/render/body.clj
  src/metabase/channel/render/card.clj
  src/metabase/util/ui_logic.clj
  test/metabase/channel/render/body_test.clj
  test/metabase/channel/render/card_test.clj
  test/metabase/channel/render/js/svg_test.clj
  test/metabase/notification/payload/impl/card_test.clj
  test/metabase/util/ui_logic_test.clj
Labels: no-backport, PR-Env, .Team/UXWest

#63489 refactor(sdk): Replase Zod with Yup for SDK bundle schema validation
  enterprise/frontend/src/.eslintrc.js
  enterprise/frontend/src/embedding-sdk-bundle/components/public/CollectionBrowser/CollectionBrowser.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/CreateDashboardModal/CreateDashboardModal.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/InteractiveQuestion/InteractiveQuestion.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/MetabotQuestion/MetabotQuestion.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/SdkDebugInfo/SdkDebugInfo.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/StaticQuestion/StaticQuestion.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/EditableDashboard/EditableDashboard.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/InteractiveDashboard/InteractiveDashboard.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/components/public/dashboard/StaticDashboard/StaticDashboard.schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/lib/validate-function-schema.ts
  enterprise/frontend/src/embedding-sdk-bundle/types/schema.ts
  package.json
  yarn.lock
Labels: no-backport, .Team/Embedding, Embedding/SDK, no-release-notes

#63547 🤖 backported "Metabot usage"
  enterprise/backend/src/metabase_enterprise/metabot_v3/api.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/client.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/client/schema.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/core.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/dummy_tools.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/models/metabot.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/models/metabot_conversation.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/models/metabot_entity.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/models/metabot_message.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/models/metabot_prompt.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/repl.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/api.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/util.clj
  enterprise/backend/src/metabase_enterprise/serialization/v2/models.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/aisdkstream1.txt
  enterprise/backend/test/metabase_enterprise/metabot_v3/aisdkstream2.txt
  enterprise/backend/test/metabase_enterprise/metabot_v3/api_test.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/client_test.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/util_test.clj
  enterprise/backend/test/metabase_enterprise/models/entity_id_test.clj
  enterprise/frontend/src/metabase-enterprise/api/ai-streaming/__snapshots__/process-stream.unit.spec.ts.snap
  enterprise/frontend/src/metabase-enterprise/api/ai-streaming/process-stream.ts
  enterprise/frontend/src/metabase-enterprise/api/ai-streaming/schemas.ts
  resources/migrations/056_update_migrations.yaml
  src/metabase/cmd/copy.clj
  src/metabase/models/resolution.clj
  src/metabase/premium_features/token_check.clj
  src/metabase/util.cljc
  test/metabase/premium_features/token_check_test.clj
  test/metabase/util_test.cljc
Labels: was-backported

#63442 Add :metabase-search/semantic-fallback-results-usage metric
  enterprise/backend/src/metabase_enterprise/semantic_search/core.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/core_test.clj
  src/metabase/analytics/prometheus.clj
Labels: backport, .Team/Metabot

#63555 🤖 backported "Add :metabase-search/semantic-fallback-results-usage metric"
  enterprise/backend/src/metabase_enterprise/semantic_search/core.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/core_test.clj
  src/metabase/analytics/prometheus.clj
Labels: was-backported

#63552 Factor out python specific api tests
  enterprise/backend/test/metabase_enterprise/transforms/api_test.clj
  enterprise/backend/test/metabase_enterprise/transforms/test_util.clj
  enterprise/backend/test/metabase_enterprise/transforms_python/transforms_api_test.clj
Labels: .Team/Metabot

#63518 Unskip and fix flaky locale test for embedded analytics js
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/select-embed-experience.cy.spec.ts
Labels: backport, .Team/Embedding

#63569 🤖 backported "docs - clarify webhook permissions"
  docs/configuring-metabase/email.md
  docs/configuring-metabase/slack.md
  docs/configuring-metabase/webhooks.md
  docs/permissions/application.md
  docs/questions/alerts.md
Labels: was-backported

#63572 Skip broken about test
  e2e/test/scenarios/onboarding/about.cy.spec.js
Labels: .CI & Tests, flaky-test-fix, no-backport, .Team/UXWest

#63594 docs: transforms draft
  docs/data-modeling/transforms.md
  docs/databases/users-roles-privileges.md
Labels: Type:Documentation, no-backport

#63593 Feat: UXW-717 Reconcile comments with document layout
  enterprise/frontend/src/metabase-enterprise/documents/components/Editor/CommentsMenu/CommentsMenu.tsx
  enterprise/frontend/src/metabase-enterprise/rich_text_editing/tiptap/extensions/CardEmbed/CardEmbedNode.module.css
  enterprise/frontend/src/metabase-enterprise/rich_text_editing/tiptap/extensions/CardEmbed/CardEmbedNode.tsx
  frontend/src/metabase/ui/components/icons/Icon/icons/add_message.svg
  frontend/src/metabase/ui/components/icons/Icon/icons/index.ts
Labels: no-backport, PR-Env, ci skip, .Team/UXWest

#63590 Document password handling for special characters
  docs/databases/connections/mariadb.md
  docs/databases/connections/mysql.md
Labels: Type:Documentation, backport

#63603 🤖 backported "Document password handling for special characters"
  docs/databases/connections/mariadb.md
  docs/databases/connections/mysql.md
Labels: was-backported

#63586 Simplify state management and fix the flicker with the transform run button
  enterprise/frontend/src/metabase-enterprise/api/transform-job.ts
  enterprise/frontend/src/metabase-enterprise/api/transform.ts
  enterprise/frontend/src/metabase-enterprise/transforms/components/JobView/ScheduleSection/ScheduleSection.tsx
  enterprise/frontend/src/metabase-enterprise/transforms/components/RunButton/RunButton.tsx
  enterprise/frontend/src/metabase-enterprise/transforms/pages/TransformPage/RunSection/RunSection.tsx
Labels: no-backport, .Team/Querying

#63588 Fix auto-passing e2e spec changes
  .github/workflows/e2e-test.yml
Labels: backport, .Team/UXWest

#63615 🤖 backported "Handle calls to current-join-alias with unexpected types like Metric metadata."
  src/metabase/lib/join/util.cljc
Labels: was-backported

#63597 viz-settings middleware => Lib
  src/metabase/query_processor/middleware/visualization_settings.clj
  src/metabase/query_processor/postprocess.clj
  test/metabase/query_processor/middleware/visualization_settings_test.clj
Labels: no-backport, .Team/Querying, .Team/DevEx

#63579 [metabot] tool_calls should be a vector
  enterprise/backend/src/metabase_enterprise/metabot_v3/client/schema.clj
Labels: no-backport, .Team/Workflows

#63554 Adjust legacy sql generation button to toggle Metabot chat
  enterprise/frontend/src/metabase-enterprise/ai-sql-generation/components/GenerateSqlQueryButton/GenerateSqlQueryButton.tsx
  enterprise/frontend/src/metabase-enterprise/ai-sql-generation/components/GenerateSqlQueryButton/GenerateSqlQueryButton.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/ai-sql-generation/components/GenerateSqlQueryButton/index.ts
  enterprise/frontend/src/metabase-enterprise/ai-sql-generation/index.ts
  enterprise/frontend/src/metabase-enterprise/ai-sql-generation/utils.ts
  enterprise/frontend/src/metabase-enterprise/api/ai-sql-generation.ts
  enterprise/frontend/src/metabase-enterprise/api/index.ts
  enterprise/frontend/src/metabase-enterprise/metabot/components/MetabotToggleButton.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/index.tsx
  enterprise/frontend/src/metabase-enterprise/plugins.js
  frontend/src/metabase-types/api/ai-sql-generation.ts
  frontend/src/metabase-types/api/index.ts
  frontend/src/metabase-types/api/mocks/ai-sql-generation.ts
  frontend/src/metabase-types/api/mocks/index.ts
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/query_builder/components/NativeQueryEditor/CodeMirrorEditor/util.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/CodeMirrorEditor/util.unit.spec.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditor.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditorActionButtons/NativeQueryEditorActionButtons.tsx
  frontend/src/metabase/query_builder/components/NativeQueryEditor/NativeQueryEditorTopBar/NativeQueryEditorTopBar.tsx
  frontend/test/__support__/server-mocks/ai-sql-generation.ts
  frontend/test/__support__/server-mocks/index.ts
Labels: backport, double-backport

#63564 🤖 backported "Send pulse skip legacy alerts"
  src/metabase/pulse/task/send_pulses.clj
  test/metabase/api/downloads_exports_test.clj
  test/metabase/pulse/send_test.clj
  test/metabase/pulse/task/send_pulses_test.clj
Labels: was-backported

#63563 🤖 backported "Send pulse skip legacy alerts"
  src/metabase/pulse/task/send_pulses.clj
  test/metabase/api/downloads_exports_test.clj
  test/metabase/pulse/send_test.clj
  test/metabase/pulse/task/send_pulses_test.clj
Labels: was-backported

#63520 🤖 backported "PRG-138 fix mongo and sql server YAML setup"
  e2e/test/scenarios/admin/databases.cy.spec.js
  modules/drivers/mongo/resources/metabase-plugin.yaml
  modules/drivers/sqlserver/resources/metabase-plugin.yaml
Labels: was-backported

#63526 Fix flaky "Change target" behavior for transforms
  e2e/test/scenarios/admin/transforms.cy.spec.ts
  enterprise/frontend/src/metabase-enterprise/transforms/pages/JobPage/JobPage.tsx
  enterprise/frontend/src/metabase-enterprise/transforms/pages/TransformPage/TargetSection/UpdateTargetModal/UpdateTargetModal.tsx
  enterprise/frontend/src/metabase-enterprise/transforms/pages/TransformPage/TransformPage.tsx
Labels: no-backport, .Team/Querying

#63613 Auto-update documentation for release-x.56.x
  docs/api.html
Labels: Type:Documentation, no-backport

#63639 Fix for empty input tables with LocalStack
  enterprise/backend/src/metabase_enterprise/transforms_python/python_runner.clj
  enterprise/backend/test/metabase_enterprise/transforms_python/python_runner_test.clj
Labels: .Team/Workflows

#63632 Closes EMB-303 search bar in embedding no longer awfully long
  frontend/src/metabase/nav/components/search/SearchBar/SearchBar.styled.tsx
Labels: backport, .Team/Embedding

#63558 PRG-130 Send parse connection string parsing events only on blur
  e2e/test/scenarios/admin/database-connection-strings.cy.spec.ts
  frontend/src/metabase/databases/components/DatabaseConnectionUri/DatabaseConnectionStringField.tsx
Labels: backport, .Team/ProductGrowth

#63654 Proper CI setup: clone instead of sub modules
  .github/scripts/setup-python-runner.sh
  .github/workflows/drivers.yml
Labels: .Team/Workflows
