Repository metabase/metabase, pull requests merged in 2025-03, with the labels that each got.

#54564 Bump metabase/saml20-clj from 2.2.7.173 to 3.0.0.175
  deps.edn
Labels: no-backport

#54565 Bump org.apache.sshd/sshd-core from 2.14.0 to 2.15.0
  deps.edn
Labels: no-backport

#54562 Bump cider/cider-nrepl from 0.52.0 to 0.52.1
  deps.edn
Labels: no-backport

#54563 Bump io.github.tonsky/clj-reload from 0.8.0 to 0.9.0
  deps.edn
Labels: no-backport

#54561 Bump ch.qos.logback/logback-classic from 1.5.16 to 1.5.17
  deps.edn
Labels: no-backport

#54566 Bump org.slf4j/slf4j-api from 2.0.16 to 2.0.17
  deps.edn
Labels: no-backport

#54349 Auto formatting adapts to currency style if needed
  frontend/src/metabase/visualizations/lib/settings/graph.js
  frontend/src/metabase/visualizations/lib/settings/graph.unit.spec.js
  frontend/src/metabase/visualizations/lib/settings/visualization.js
Labels: backport, .Team/DashViz

#54558 Remove the ACE editor
  frontend/src/metabase/css/vendor.css
  frontend/src/types/ace-builds.d.ts
  frontend/test/__support__/mocks.js
  jest.config.js
  package.json
  rspack.config.js
  webpack.config.js
  yarn.lock
Labels: no-backport, .Team/Querying

#54500 🤖 backported "fix: prevent icon overflow on resize"
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
  frontend/src/metabase/querying/notebook/components/JoinStep/JoinComplete/JoinComplete.tsx
Labels: was-backported

#54069 Recalculate columns for Upload model when updating
  src/metabase/models/card/metadata.clj
  src/metabase/upload.clj
  test/metabase/upload_test.clj
Labels: backport, .Team/Workflows

#54521 Allow impersonated users to hit cache again
  .clj-kondo/config.edn
  .clj-kondo/config/modules/config.edn
  .clj-kondo/macros/metabase_enterprise/impersonation/util_test.clj
  .cljfmt.edn
  enterprise/backend/src/metabase_enterprise/advanced_permissions/api/routes.clj
  enterprise/backend/src/metabase_enterprise/impersonation/api.clj
  enterprise/backend/src/metabase_enterprise/impersonation/core.clj
  enterprise/backend/src/metabase_enterprise/impersonation/driver.clj
  enterprise/backend/src/metabase_enterprise/impersonation/middleware.clj
  enterprise/backend/src/metabase_enterprise/impersonation/model.clj
  enterprise/backend/src/metabase_enterprise/impersonation/util.clj
  enterprise/backend/src/metabase_enterprise/sandbox/models/params/field_values.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/common_test.clj
  enterprise/backend/test/metabase_enterprise/advanced_permissions/models/field_values_test.clj
  enterprise/backend/test/metabase_enterprise/impersonation/api_test.clj
  enterprise/backend/test/metabase_enterprise/impersonation/cache_test.clj
  enterprise/backend/test/metabase_enterprise/impersonation/driver_test.clj
  enterprise/backend/test/metabase_enterprise/impersonation/util_test.clj
  enterprise/backend/test/metabase_enterprise/serialization/v2/models_test.clj
  src/metabase/driver/sql_jdbc/execute.clj
  src/metabase/models/field_values.clj
  src/metabase/models/resolution.clj
  src/metabase/permissions/api.clj
  src/metabase/permissions/models/data_permissions/graph.clj
  src/metabase/permissions/util.clj
  src/metabase/query_processor/middleware/cache.clj
  src/metabase/query_processor/middleware/enterprise.clj
  src/metabase/query_processor/preprocess.clj
  src/metabase/query_processor/util.clj
Labels: no-backport, .Team/AdminWebapp

#54581 Remove unnecessary step that updates GH CLI
  .github/workflows/release-embedding-sdk.yml
Labels: .Team/Embedding, double-backport

#54585 🤖 backported "Remove unnecessary step that updates GH CLI"
  .github/workflows/release-embedding-sdk.yml
Labels: was-backported

#54380 Remove V1 metabot agent endpoint
  enterprise/backend/src/metabase_enterprise/metabot_v3/README.md
  enterprise/backend/src/metabase_enterprise/metabot_v3/api.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/client.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/client/schema.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/context.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/docs/sequence-diagram.png
  enterprise/backend/src/metabase_enterprise/metabot_v3/docs/sequence-diagram.txt
  enterprise/backend/src/metabase_enterprise/metabot_v3/dummy_tools.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/envelope.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/handle_envelope.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/reactions.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/repl.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/create-dashboard-subscription.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/create_dashboard_subscription.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/filter-records.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/filters.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/find-metric.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/find-outliers.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/find_metric.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/find_outliers.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/generate-insights.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/generate_insights.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/interface.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/invite-user.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/invite_user.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/query-metric.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/show-results-to-user.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/show_results_to_user.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/who-is-your-favorite.json
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/who_is_your_favorite.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/api_test.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/client_test.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/handle_envelope_test.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/tools/create_dashboard_subscription_test.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/tools/filters_test.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/tools/find_outliers_test.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/tools/generate_insights_test.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/tools/invite_user_test.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/tools/show_results_to_user_test.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/tools/who_is_your_favorite_test.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/tools_test.clj
Labels: Metabot/General

#54586 docs - note on license
  docs/embedding/sdk/quickstart.md
Labels: Type:Documentation, backport

#54588 🤖 backported "docs - note on license"
  docs/embedding/sdk/quickstart.md
Labels: was-backported

#54250 Run cypress tests against the nodejs sample app
  .gitignore
  e2e/runner/constants/exit-code.js
  e2e/runner/cypress-runner-backend.js
  e2e/runner/cypress-runner-run-tests.js
  e2e/runner/cypress-runner-utils.js
  e2e/runner/run_cypress_ci.js
  e2e/runner/run_cypress_local.ts
  e2e/runner/sample-apps-shared/constants/sample-app-setup-configs.js
  e2e/runner/sample-apps-shared/helpers/fetch-app.ts
  e2e/runner/sample-apps-shared/helpers/prepare-app.ts
  e2e/runner/sample-apps-shared/helpers/start-containers.ts
  e2e/runner/sample-apps-shared/types.ts
  e2e/runner/start-sample-app-containers/start-sample-app-containers.ts
Labels: .CI & Tests, do not merge, no-backport, .Team/Embedding

#54591 🤖 backported "Update sample app ports in documentation"
  docs/embedding/sdk/quickstart-with-sample-app.md
Labels: was-backported

#54590 🤖 backported "Update sample app ports in documentation"
  docs/embedding/sdk/quickstart-with-sample-app.md
Labels: was-backported

#54519 Convert dummy tools to normal tools
  enterprise/backend/src/metabase_enterprise/metabot_v3/dummy_tools.clj
  enterprise/backend/src/metabase_enterprise/metabot_v3/tools/api.clj
  enterprise/backend/test/metabase_enterprise/metabot_v3/tools/api_test.clj
Labels: Metabot/Tools

#54170 Bump thheller/shadow-cljs from 2.28.20 to 2.28.21
  deps.edn
Labels: no-backport

#54441 Adding deep link url support for visualizer cards in dashboard subs
  src/metabase/channel/render/card.clj
  test/metabase/channel/render/card_test.clj
Labels: .Team/DashViz

#54523 Add prometheus info metric
  src/metabase/analytics/prometheus.clj
  src/metabase/core/core.clj
Labels: backport, .Team/Workflows

#54592 docs - clarify cloud
  docs/embedding/sdk/quickstart.md
Labels: Type:Documentation, double-backport

#54596 🤖 backported "docs - clarify cloud"
  docs/embedding/sdk/quickstart.md
Labels: was-backported

#54589 Override some deps licenses
  bin/build/resources/overrides.edn
Labels: no-backport, .Team/AdminWebapp

#54598 updating mantine patch
  patches/@mantine+core+7.17.0.patch
Labels: no-backport, .Team/AdminWebapp

#54525 Make `:time-interval` work with `0` instead of `:current` in the UI
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/querying/filters/components/DatePicker/DateOperatorPicker/DateOperatorPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/DateOperatorPicker/utils.ts
  frontend/src/metabase/querying/filters/components/DatePicker/DateOperatorPicker/utils.unit.spec.ts
  frontend/src/metabase/querying/filters/components/DatePicker/DatePicker.stories.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/DatePicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/DateShortcutPicker/DateShortcutPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/DateShortcutPicker/constants.ts
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/CurrentDatePicker/CurrentDatePicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/CurrentDatePicker/utils.ts
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateIntervalPicker/DateIntervalPicker.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateIntervalPicker/DateIntervalPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateIntervalPicker/SimpleDateIntervalPicker/SimpleDateIntervalPicker.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateIntervalPicker/SimpleDateIntervalPicker/SimpleDateIntervalPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateIntervalPicker/utils.ts
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateOffsetIntervalPicker/DateOffsetIntervalPicker.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateOffsetIntervalPicker/DateOffsetIntervalPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateOffsetIntervalPicker/utils.ts
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/IncludeCurrentSwitch/IncludeCurrentSwitch.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/RelativeDatePicker.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/RelativeDatePicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/types.ts
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/utils.ts
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/utils.unit.spec.ts
  frontend/src/metabase/querying/filters/components/DatePicker/SimpleDatePicker/SimpleDatePicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/FilterModal/DateFilterEditor/DateFilterEditor.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/DateFilterPicker/DateFilterPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/RelativeDateShortcutPicker/RelativeDateShortcutPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/RelativeDateShortcutPicker/utils.ts
  frontend/src/metabase/querying/filters/components/TimeseriesChrome/TimeseriesFilterPicker/TimeseriesFilterPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/types.ts
  frontend/src/metabase/querying/filters/utils/dates.unit.spec.ts
  frontend/src/metabase/querying/parameters/utils/parsing.ts
  frontend/src/metabase/querying/parameters/utils/parsing.unit.spec.ts
  src/metabase/lib/fe_util.cljc
  src/metabase/lib/filter.cljc
  src/metabase/lib/js.cljs
  test/metabase/lib/fe_util_test.cljc
  test/metabase/lib/filter_test.cljc
Labels: backport, .Team/Querying

#54056 Fix invisible close icons on some legacy modals
  frontend/src/metabase/components/Modal/Modal.tsx
  frontend/src/metabase/components/ModalContent/ModalContent.styled.ts
Labels: no-backport, .Team/AdminWebapp

#54529 fix: Cast LocalDateTime to date in oracle
  modules/drivers/oracle/src/metabase/driver/oracle.clj
  modules/drivers/oracle/test/metabase/driver/oracle_test.clj
Labels: .Team/Drivers, double-backport

#52993 Remove extra queries on public & embedded dashboard load
  e2e/test/scenarios/filters-reproductions/dashboard-filters-reproductions.cy.spec.js
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboard.tsx
Labels: backport, .Team/Querying

#54609 🤖 backported "Remove extra queries on public & embedded dashboard load"
  e2e/test/scenarios/filters-reproductions/dashboard-filters-reproductions.cy.spec.js
  frontend/src/metabase/public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboard.tsx
Labels: was-backported

#54607 🤖 backported "fix: Cast LocalDateTime to date in oracle"
  modules/drivers/oracle/src/metabase/driver/oracle.clj
  modules/drivers/oracle/test/metabase/driver/oracle_test.clj
Labels: was-backported

#54446 Healthcheck endpoint for databases
  src/metabase/api/database.clj
  test/metabase/api/database_test.clj
Labels: no-backport, .Team/AdminWebapp

#54533 add ability to style SpecialTagInput, update MultiAutocomplete styles
  frontend/src/metabase/querying/filters/components/FilterValuePicker/SearchValuePicker/SearchValuePicker.tsx
  frontend/src/metabase/ui/components/feedback/Loader/Loader.tsx
  frontend/src/metabase/ui/components/inputs/MultiAutocomplete/MultiAutocomplete.module.css
  frontend/src/metabase/ui/components/inputs/MultiAutocomplete/MultiAutocomplete.tsx
  frontend/src/metabase/ui/components/inputs/SpecialTagsInput/SpecialTagsInput.tsx
Labels: no-backport, .Team/AdminWebapp

#54450 fix(sdk): Fix ColorRangeSelector in Conditional Formatting
  frontend/src/metabase/core/components/ColorRangeSelector/ColorRangeSelector.stories.tsx
  frontend/src/metabase/core/components/ColorRangeSelector/ColorRangeSelector.tsx
  frontend/src/metabase/core/components/ColorRangeSelector/ColorRangeSelector.unit.spec.tsx
  frontend/src/metabase/core/components/ColorRangeSelector/index.ts
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/RuleEditor.tsx
  frontend/src/metabase/visualizations/visualizations/Map/Map.jsx
Labels: .Team/Embedding, double-backport

#54534 Add "for React" to SDK in legalese modal and settings page
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/common.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/enterprise.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/premium.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkLegaleseModal/EmbeddingSdkLegaleseModal.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/EmbeddingSdkSettings.tsx
Labels: .Team/Embedding, double-backport

#54611 Fix duplicates introduced by column sync
  frontend/src/metabase/querying/viz-settings/utils/sync-viz-settings.ts
  frontend/src/metabase/querying/viz-settings/utils/sync-viz-settings.unit.spec.tsx
Labels: backport, .Team/Querying

#54604 🤖 backported "Make `:time-interval` work with `0` instead of `:current` in the UI"
  frontend/src/metabase-lib/types.ts
  frontend/src/metabase/querying/filters/components/DatePicker/DateOperatorPicker/DateOperatorPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/DateOperatorPicker/utils.ts
  frontend/src/metabase/querying/filters/components/DatePicker/DateOperatorPicker/utils.unit.spec.ts
  frontend/src/metabase/querying/filters/components/DatePicker/DatePicker.stories.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/DatePicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/DateShortcutPicker/DateShortcutPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/DateShortcutPicker/constants.ts
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/CurrentDatePicker/CurrentDatePicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/CurrentDatePicker/utils.ts
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateIntervalPicker/DateIntervalPicker.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateIntervalPicker/DateIntervalPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateIntervalPicker/SimpleDateIntervalPicker/SimpleDateIntervalPicker.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateIntervalPicker/SimpleDateIntervalPicker/SimpleDateIntervalPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateIntervalPicker/utils.ts
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateOffsetIntervalPicker/DateOffsetIntervalPicker.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateOffsetIntervalPicker/DateOffsetIntervalPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateOffsetIntervalPicker/utils.ts
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/IncludeCurrentSwitch/IncludeCurrentSwitch.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/RelativeDatePicker.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/RelativeDatePicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/types.ts
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/utils.ts
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/utils.unit.spec.ts
  frontend/src/metabase/querying/filters/components/DatePicker/SimpleDatePicker/SimpleDatePicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/FilterModal/DateFilterEditor/DateFilterEditor.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/FilterPicker/DateFilterPicker/DateFilterPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/RelativeDateShortcutPicker/RelativeDateShortcutPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/components/RelativeDateShortcutPicker/utils.ts
  frontend/src/metabase/querying/filters/components/TimeseriesChrome/TimeseriesFilterPicker/TimeseriesFilterPicker.unit.spec.tsx
  frontend/src/metabase/querying/filters/types.ts
  frontend/src/metabase/querying/filters/utils/dates.unit.spec.ts
  frontend/src/metabase/querying/parameters/utils/dates.ts
  frontend/src/metabase/querying/parameters/utils/dates.unit.spec.ts
  src/metabase/lib/fe_util.cljc
  src/metabase/lib/filter.cljc
  src/metabase/lib/js.cljs
  test/metabase/lib/fe_util_test.cljc
  test/metabase/lib/filter_test.cljc
Labels: was-backported

#54618 🤖 backported "Add "for React" to SDK in legalese modal and settings page"
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/common.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/enterprise.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/premium.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkLegaleseModal/EmbeddingSdkLegaleseModal.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/EmbeddingSdkSettings.tsx
Labels: was-backported

#54620 🤖 backported "Fix duplicates introduced by column sync"
  frontend/src/metabase/querying/viz-settings/utils/sync-viz-settings.ts
  frontend/src/metabase/querying/viz-settings/utils/sync-viz-settings.unit.spec.tsx
Labels: was-backported

#54536 Updating InputWithSelectPrefix to Mantine components
  e2e/test/scenarios/admin-2/settings.cy.spec.js
  frontend/src/metabase/components/InputWithSelectPrefix/InputWithSelectPrefix.jsx
Labels: backport, .Team/AdminWebapp

#54619 Repro for "Date filter translations: Key not being translated"
  e2e/test/scenarios/filters-reproductions/dashboard-filters-reproductions.cy.spec.js
Labels: backport, .Team/Querying

#54617 🤖 backported "Add "for React" to SDK in legalese modal and settings page"
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/common.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/enterprise.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/app/components/SettingsEditor/tests/embedding/premium.embedding.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkLegaleseModal/EmbeddingSdkLegaleseModal.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/EmbeddingSdkSettings.tsx
Labels: was-backported

#54499 fix: close date filter on esc
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_All_Options.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Month_Year.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Relative.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Date_Filter_Single.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Dark_Theme_Unit_Of_Time.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_All_Options.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Month_Year.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Relative.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Date_Filter_Single.png
  .loki/reference/chrome_laptop_App_Embed_PublicOrEmbeddedDashboardView_filters_Light_Theme_Unit_Of_Time.png
  e2e/test/scenarios/dashboard/dashboard-reproductions.cy.spec.js
  frontend/src/metabase/parameters/components/ParameterValueWidget.tsx
Labels: backport, .Team/Querying

#54402 fix(sdk): Fix ColorSelector in Conditional Formatting
  frontend/src/metabase/core/components/ColorSelector/ColorSelector.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/RuleEditor.tsx
Labels: .Team/Embedding, double-backport

#54622 🤖 backported "Repro for "Date filter translations: Key not being translated""
  e2e/test/scenarios/filters-reproductions/dashboard-filters-reproductions.cy.spec.js
Labels: was-backported

#54156 Build multi-arch arm images
  .github/actions/fetch-artifact/action.yml
  .github/workflows/containerize-jar.yml
  .github/workflows/pre-release.yml
  .github/workflows/tag-for-release.yml
  release/src/version-helpers.ts
  release/src/version-helpers.unit.spec.ts
Labels: .Building & Releasing, backport, .Team/AdminWebapp

#54629 🤖 backported "Build multi-arch arm images"
  .github/actions/fetch-artifact/action.yml
  .github/workflows/containerize-jar.yml
  .github/workflows/pre-release.yml
  .github/workflows/tag-for-release.yml
  release/src/version-helpers.ts
  release/src/version-helpers.unit.spec.ts
Labels: was-backported

#54628 🤖 backported "Guard enforced-sandboxes-for-user against nil user-ids"
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  enterprise/backend/src/metabase_enterprise/sandbox/api/util.clj
  test/metabase/api/embed_test.clj
Labels: was-backported

#53776 Increase e2e test coverage for sandboxing
  e2e/support/helpers/api/addQuestionToDashboard.ts
  e2e/support/helpers/api/createCollection.ts
  e2e/support/helpers/api/createDashboard.ts
  e2e/support/helpers/api/index.ts
  e2e/support/helpers/e2e-ad-hoc-question-helpers.js
  e2e/support/helpers/e2e-misc-helpers.js
  e2e/support/helpers/e2e-permissions-helpers.js
  e2e/test/scenarios/onboarding/command-palette.cy.spec.js
  e2e/test/scenarios/permissions/sandboxing/helpers/e2e-sandboxing-helpers.ts
  e2e/test/scenarios/permissions/sandboxing/helpers/types.ts
  e2e/test/scenarios/permissions/sandboxing/sandboxing-via-api.cy.spec.js
  e2e/test/scenarios/permissions/sandboxing/sandboxing-via-ui.cy.spec.ts
  enterprise/frontend/src/metabase-enterprise/sandboxes/components/EditSandboxingModal/EditSandboxingModal.tsx
  frontend/src/metabase-types/api/dataset.ts
Labels: no-backport, .Team/AdminWebapp, run-tests

#54577 Robustly initialize notification triggers
  src/metabase/task/notification.clj
  test/metabase/task/notification_test.clj
Labels: no-backport, .Team/Workflows

#54483 Closes viz-474: conditional formatting polish
  frontend/src/metabase/core/components/ColorSelector/ColorSelector.tsx
  frontend/src/metabase/hooks/use-toggle.ts
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/RuleEditor.tsx
Labels: .Team/DashViz, double-backport

#54574 refactor: "Get embedding code" width too narrow
  e2e/test/scenarios/sharing/public-sharing-embed-button-behavior.cy.spec.js
  frontend/src/metabase/public/components/EmbedModal/SelectEmbedTypePane/PublicEmbedCard.tsx
Labels: backport, .Team/Embedding

#54640 ci: Fix wrong code format failing linter
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
Labels: .Team/Embedding

#54639 Removed GH project urls
  .github/team.json
Labels: .CI & Tests, no-backport

#54637 🤖 backported "refactor: "Get embedding code" width too narrow"
  e2e/test/scenarios/sharing/public-sharing-embed-button-behavior.cy.spec.js
  frontend/src/metabase/public/components/EmbedModal/SelectEmbedTypePane/PublicEmbedCard.tsx
Labels: was-backported

#54489 feat(sdk): Simple data picker
  e2e/test-component/scenarios/embedding-sdk/create-question.cy.spec.tsx
  e2e/test-component/scenarios/embedding-sdk/data-picker.cy.spec.tsx
  e2e/test/scenarios/embedding/interactive-embedding.cy.spec.js
  enterprise/frontend/src/embedding-sdk/components/private/SimpleDataPicker/SimpleDataPicker.stories.tsx
  enterprise/frontend/src/embedding-sdk/components/private/SimpleDataPicker/SimpleDataPicker.tsx
  enterprise/frontend/src/embedding-sdk/components/private/SimpleDataPicker/SimpleDataPicker.unit.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/private/SimpleDataPicker/SimpleDataPickerView.tsx
  enterprise/frontend/src/embedding-sdk/components/private/SimpleDataPicker/index.ts
  enterprise/frontend/src/embedding-sdk/index.ts
  enterprise/frontend/src/metabase-enterprise/embedding-sdk/index.js
  enterprise/frontend/src/metabase-enterprise/settings/index.ts
  frontend/src/metabase/components/EmptyState/EmptyState.module.css
  frontend/src/metabase/components/EmptyState/EmptyState.styled.tsx
  frontend/src/metabase/components/EmptyState/EmptyState.tsx
  frontend/src/metabase/plugins/index.ts
  frontend/src/metabase/query_builder/components/DataSelector/DataSelector.jsx
  frontend/src/metabase/query_builder/components/DataSelector/saved-entity-picker/SavedEntityList.tsx
  frontend/src/metabase/querying/notebook/components/DataStep/tests/common.unit.spec.tsx
  frontend/src/metabase/querying/notebook/components/DataStep/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/querying/notebook/components/DataStep/tests/setup.tsx
  frontend/src/metabase/querying/notebook/components/NotebookDataPicker/NotebookDataPicker.tsx
  frontend/test/__support__/server-mocks/search.ts
  jest.config.js
Labels: no-backport, .Team/Embedding

#54430 Update activating-the-enterprise-edition.md
  docs/installation-and-operation/activating-the-enterprise-edition.md
Labels: Type:Documentation, backport

#54646 🤖 backported "Update activating-the-enterprise-edition.md"
  docs/installation-and-operation/activating-the-enterprise-edition.md
Labels: was-backported

#54643 fix: WRK-120 show set up channels CTA for users with settings access
  frontend/src/metabase/notifications/modals/ChannelSetupModal.tsx
  frontend/src/metabase/notifications/modals/CreateOrEditQuestionAlertModal/CreateOrEditQuestionAlertModal.tsx
  frontend/src/metabase/notifications/modals/CreateOrEditQuestionAlertModal/CreateOrEditQuestionAlertModal.unit.spec.tsx
Labels: .Team/Workflows

#53125 Migrations for database routing
  resources/migrations/001_update_migrations.yaml
  src/metabase/api/table.clj
  src/metabase/models/database.clj
  test/metabase/search/appdb/index_test.clj
  test_resources/serialization_baseline/databases/My Database/My Database.yaml
  test_resources/serialization_baseline/databases/test-data (h2)/test-data (h2).yaml
Labels: .Team/AdminWebapp

#54621 🤖 backported "Updating InputWithSelectPrefix to Mantine components"
  e2e/test/scenarios/admin-2/settings.cy.spec.js
  frontend/src/metabase/components/InputWithSelectPrefix/InputWithSelectPrefix.jsx
Labels: was-backported

#54614 Manual Backport of echarts tooltip and dashcard viz modal adjustments
  e2e/support/helpers/e2e-visual-tests-helpers.js
  e2e/test-component/scenarios/embedding-sdk/tooltip-reproductions.cy.spec.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/ChartSettingsButton/ChartSettingsButton.tsx
  frontend/src/metabase/visualizations/components/ChartSettings/DashboardChartSettings/DashboardChartSettings.tsx
  frontend/src/metabase/visualizations/echarts/tooltip/index.tsx
Labels: no-backport, .Team/AdminWebapp

#54595 🤖 backported "Add prometheus info metric"
  src/metabase/analytics/prometheus.clj
  src/metabase/core/core.clj
Labels: was-backported

#54436 54138 Upgrade node to v22 in Dockerfile & docker-compose
  Dockerfile
  dev/docker-compose.yml
Labels: External

#54645 Bump react-virtualized to 9.22.5 to unblock React 19
  package.json
  yarn.lock
Labels: .Team/Embedding, double-backport

#54587 fix(frontend): update single alert condition style
  e2e/test/scenarios/sharing/alert/alert-types.cy.spec.js
  frontend/src/metabase/notifications/modals/CreateOrEditQuestionAlertModal/CreateOrEditQuestionAlertModal.tsx
Labels: backport, .Team/Workflows

#54672 🤖 backported "docs: Update Usage analytics"
  docs/usage-and-performance-tools/usage-analytics.md
Labels: was-backported

#54579 Integrate Sample Apps e2e tests with CI
  .github/workflows/e2e-sample-apps-tests.yml
  e2e/runner/cypress-runner-run-tests.js
  e2e/runner/run_cypress_ci.js
  e2e/runner/run_cypress_local.ts
  e2e/runner/sample-apps-shared/constants/sample-app-setup-configs.js
  e2e/runner/sample-apps-shared/helpers/start-containers.ts
  e2e/runner/sample-apps-shared/types.ts
  e2e/runner/start-sample-app-containers/start-ci.ts
  e2e/runner/start-sample-app-containers/startSampleAppContainers.ts
  release/src/version-helpers.ts
Labels: .CI & Tests, no-backport, .Team/Embedding

#54518 Smarter cards edition routing (followup on VIZ-470)
  frontend/src/metabase/components/EditBar/EditBar.styled.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardActionsPanel.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/VisualizerButton/VisualizerButton.tsx
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/dashboard/components/QuestionPicker/QuestionList.tsx
  frontend/src/metabase/dashboard/components/QuestionPicker/convert-question-to-initial-state.ts
  frontend/src/metabase/dashboard/components/QuestionPicker/convert-question-to-initial-state.unit.spec.ts
  frontend/src/metabase/visualizer/utils/column.ts
  frontend/src/metabase/visualizer/utils/dashboard-card-supports-visualizer.ts
  frontend/src/metabase/visualizer/utils/is-visualizer-dashboard-card.ts
  frontend/src/metabase/visualizer/utils/merge-data.ts
  frontend/src/metabase/visualizer/utils/misc.ts
  frontend/src/metabase/visualizer/utils/update-settings-for-display.ts
  frontend/src/metabase/visualizer/utils/update-settings-for-display.unit.spec.ts
  frontend/src/metabase/visualizer/visualizer.slice.ts
Labels: no-backport, .Team/DashViz

#54470 Convert RuleDescription to Mantine
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/RuleDescription.tsx
Labels: .Team/Embedding, double-backport

#54471 Convert RuleListing to Mantine
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/RuleListing.tsx
Labels: .Team/Embedding, double-backport

#54675 🤖 backported "Convert RuleDescription to Mantine"
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/RuleDescription.tsx
Labels: was-backported

#54676 🤖 backported "Convert RuleDescription to Mantine"
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/RuleDescription.tsx
Labels: was-backported

#54600 fix: clear dashboard url from undefined when filter is removed
  e2e/test/scenarios/dashboard-cards/click-behavior.cy.spec.js
  frontend/src/metabase-lib/v1/queries/drills/dashboard-click-drill.js
Labels: backport, .Team/Querying

#54668 Do not display the raw data toggle when displaying `table`, even with reordered columns
  frontend/src/metabase-types/api/mocks/card.ts
  frontend/src/metabase/query_builder/containers/QueryBuilder.tsx
  frontend/src/metabase/query_builder/selectors.js
  frontend/src/metabase/query_builder/selectors.unit.spec.js
Labels: backport, .Team/Querying

#54683 🤖 backported "Do not display the raw data toggle when displaying `table`, even with reordered columns"
  frontend/src/metabase-types/api/mocks/card.ts
  frontend/src/metabase/query_builder/containers/QueryBuilder.tsx
  frontend/src/metabase/query_builder/selectors.js
  frontend/src/metabase/query_builder/selectors.unit.spec.js
Labels: was-backported

#54469 Convert ColorRange + RuleBackground to Mantine
  frontend/src/metabase/core/components/ColorRange/ColorRange.stories.tsx
  frontend/src/metabase/core/components/ColorRange/ColorRange.styled.tsx
  frontend/src/metabase/core/components/ColorRange/ColorRange.tsx
  frontend/src/metabase/core/components/ColorRange/index.ts
  frontend/src/metabase/core/components/ColorRangeSelector/ColorRangePopover.styled.tsx
  frontend/src/metabase/core/components/ColorRangeSelector/ColorRangePopover.tsx
  frontend/src/metabase/core/components/ColorRangeSelector/ColorRangeSelector.tsx
  frontend/src/metabase/core/components/ColorRangeSelector/ColorRangeToggle.styled.tsx
  frontend/src/metabase/core/components/ColorRangeSelector/ColorRangeToggle.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/RuleBackground.tsx
Labels: .Team/Embedding, double-backport

#54472 Convert RulePreview to Mantine
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/RulePreview.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/SortableRuleList.tsx
Labels: .Team/Embedding, double-backport

#54610 Show an error message when overwriting a card with a cycle
  e2e/test/scenarios/question-reproductions/reproductions.cy.spec.ts
  frontend/src/metabase/dashboard/reducers-typed.ts
Labels: backport, .Team/Querying

#54476 Convert rest of RuleEditor to Mantine
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/RuleEditor.tsx
Labels: .Team/Embedding, double-backport

#54091 Metabase Automation Genius Engine
  .clj-kondo/config.edn
  .github/workflows/backend.yml
  .gitignore
  README.md
  bb.edn
  bin/cljfmt-updated.sh
  bin/cljfmt_staged.sh
  bin/kondo-updated.sh
  bin/kondo.sh
  bin/mage
  bin/mb-download
  deps.edn
  dev/src/dev/private_things_test.clj
  mage/mage/autotab.clj
  mage/mage/cli.clj
  mage/mage/color.clj
  mage/mage/format.clj
  mage/mage/jar_download.clj
  mage/mage/kondo.clj
  mage/mage/shell.clj
  mage/mage/start_db.clj
  mage/mage/util.clj
  mage/resource.txt
  test/mage/core_test.clj
  test/mage/examples_test.clj
  test/mage/start_db_test.clj
Labels: backport, .Team/DevEx

#54698 🤖 backported "Metabase Automation Genius Engine"
  .clj-kondo/config.edn
  .github/workflows/backend.yml
  .gitignore
  README.md
  bb.edn
  bin/cljfmt-updated.sh
  bin/cljfmt_staged.sh
  bin/kondo-updated.sh
  bin/kondo.sh
  bin/mage
  bin/mb-download
  deps.edn
  dev/src/dev/private_things_test.clj
  mage/mage/autotab.clj
  mage/mage/cli.clj
  mage/mage/color.clj
  mage/mage/format.clj
  mage/mage/jar_download.clj
  mage/mage/kondo.clj
  mage/mage/shell.clj
  mage/mage/start_db.clj
  mage/mage/util.clj
  mage/resource.txt
  test/mage/core_test.clj
  test/mage/examples_test.clj
  test/mage/start_db_test.clj
Labels: was-backported

#54690 🤖 backported "Convert RulePreview to Mantine"
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/RulePreview.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/SortableRuleList.tsx
Labels: was-backported

#54691 🤖 backported "Convert RulePreview to Mantine"
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/RulePreview.tsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/SortableRuleList.tsx
Labels: was-backported

#54426 feat(frontend): allow non admin users to create alerts
  enterprise/frontend/src/metabase-enterprise/application_permissions/types/user.ts
  frontend/src/metabase/notifications/modals/ChannelSetupModal.tsx
  frontend/src/metabase/notifications/modals/CreateOrEditQuestionAlertModal/CreateOrEditQuestionAlertModal.tsx
  frontend/src/metabase/notifications/modals/CreateOrEditQuestionAlertModal/CreateOrEditQuestionAlertModal.unit.spec.tsx
  frontend/src/metabase/notifications/modals/components/NotificationChannelsAddMenu.tsx
  frontend/src/metabase/notifications/modals/components/NotificationChannelsPicker.tsx
  frontend/src/metabase/notifications/utils.ts
  frontend/src/metabase/plugins/index.ts
Labels: .Team/Workflows

#54693 🤖 backported "Show an error message when overwriting a card with a cycle"
  e2e/test/scenarios/question-reproductions/reproductions.cy.spec.ts
  frontend/src/metabase/dashboard/reducers-typed.ts
Labels: was-backported

#54678 🤖 backported "Convert RuleListing to Mantine"
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/ChartSettingsTableFormatting.jsx
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/RuleListing.tsx
Labels: was-backported

#54677 🤖 backported "Convert RuleListing to Mantine"
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/RuleListing.tsx
Labels: was-backported

#54556 Moduralize notification
  .clj-kondo/config.edn
  .clj-kondo/config/modules/config.edn
  deps.edn
  dev/src/dev/render_png.clj
  docs/api.html
  src/metabase/api/routes.clj
  src/metabase/channel/impl/email.clj
  src/metabase/channel/render/preview.clj
  src/metabase/db/custom_migrations.clj
  src/metabase/driver.clj
  src/metabase/events/notification.clj
  src/metabase/models/card.clj
  src/metabase/models/resolution.clj
  src/metabase/notification/api.clj
  src/metabase/notification/api/notification.clj
  src/metabase/notification/api/unsubscribe.clj
  src/metabase/notification/core.clj
  src/metabase/notification/init.clj
  src/metabase/notification/models.clj
  src/metabase/notification/payload/core.clj
  src/metabase/notification/seed.clj
  src/metabase/notification/send.clj
  src/metabase/notification/task/send.clj
  src/metabase/pulse/api/alert.clj
  src/metabase/pulse/api/pulse.clj
  src/metabase/pulse/update_alerts.clj
  src/metabase/task/init.clj
  test/metabase/api/card_test.clj
  test/metabase/api/collection_test.clj
  test/metabase/db/custom_migrations/pulse_to_notification_test.clj
  test/metabase/events/notification_test.clj
  test/metabase/models/field_values_test.clj
  test/metabase/notification/api/notification_test.clj
  test/metabase/notification/api/unsubscribe_test.clj
  test/metabase/notification/models_test.clj
  test/metabase/notification/payload/impl/card_test.clj
  test/metabase/notification/payload/impl/system_event_test.clj
  test/metabase/notification/seed_test.clj
  test/metabase/notification/send_test.clj
  test/metabase/notification/task/send_test.clj
  test/metabase/notification/test_util.clj
  test/metabase/pulse/api/alert_test.clj
Labels: no-backport, .Team/Workflows

#54660 Remove the legacy isModal context from ModalContent
  frontend/src/metabase/components/ModalContent/ModalContent.tsx
Labels: .Team/Embedding, double-backport

#54705 🤖 backported "Remove the legacy isModal context from ModalContent"
  frontend/src/metabase/components/ModalContent/ModalContent.tsx
Labels: was-backported

#54713 Disable merged feature notifications
  .github/workflows/on-epic-close.yml
Labels: .CI & Tests, no-backport

#54710 ci(sdk): Add stable SDK git tags
  .github/workflows/release-embedding-sdk.yml
Labels: .Team/Embedding, double-backport

#54717 🤖 backported "ci(sdk): Add stable SDK git tags"
  .github/workflows/release-embedding-sdk.yml
Labels: was-backported

#54716 🤖 backported "ci(sdk): Add stable SDK git tags"
  .github/workflows/release-embedding-sdk.yml
Labels: was-backported

#54508 WRK-81: Subscriptions can include unwired filters which is confusing
  e2e/test/scenarios/sharing/subscriptions.cy.spec.js
  enterprise/frontend/src/metabase-enterprise/sharing/components/MutableParametersSection.tsx
  frontend/src/metabase/notifications/AddEditSidebar/AddEditEmailSidebar.tsx
  frontend/src/metabase/notifications/AddEditSidebar/AddEditSidebar.jsx
  frontend/src/metabase/notifications/AddEditSidebar/AddEditSlackSidebar.tsx
  frontend/src/metabase/notifications/AddEditSidebar/constants.js
  frontend/src/metabase/notifications/AddEditSidebar/constants.ts
  frontend/src/metabase/notifications/DashboardSubscriptionsSidebar/tests/premium.unit.spec.ts
  frontend/src/metabase/notifications/DashboardSubscriptionsSidebar/tests/setup.tsx
  frontend/src/metabase/plugins/index.ts
Labels: backport, .Team/Workflows

#54531 Prevent from using `millisecond` with `datetime-diff`
  frontend/src/metabase-lib/v1/expressions/helper-text-strings.ts
  frontend/src/metabase-lib/v1/expressions/helper-text-strings.unit.spec.ts
  src/metabase/lib/schema/expression/temporal.cljc
  test/metabase/lib/schema/expression/temporal_test.cljc
Labels: backport, .Team/Querying

#54720 🤖 backported "Prevent from using `millisecond` with `datetime-diff`"
  frontend/src/metabase-lib/v1/expressions/helper-text-strings.ts
  frontend/src/metabase-lib/v1/expressions/helper-text-strings.unit.spec.ts
  src/metabase/lib/schema/expression/temporal.cljc
  test/metabase/lib/schema/expression/temporal_test.cljc
Labels: was-backported

#54509 🤖 backported "Fix - Uncaught TypeError when making native query parameter required"
  e2e/test/scenarios/native/native-reproductions.cy.spec.ts
  frontend/src/metabase/query_builder/actions/native.ts
  frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.tsx
  frontend/src/metabase/query_builder/components/template_tags/TagEditorSidebar.tsx
Labels: was-backported

#54651 Table Data Editing APIs
  .clj-kondo/config/modules/config.edn
  enterprise/backend/src/metabase_enterprise/api/routes.clj
  enterprise/backend/src/metabase_enterprise/data_editing/api.clj
  enterprise/backend/test/metabase_enterprise/data_editing/api_test.clj
  src/metabase/actions/core.clj
  src/metabase/api/database.clj
  src/metabase/lib/schema/info.cljc
  src/metabase/premium_features/core.clj
  src/metabase/query_processor/streaming.clj
  test/metabase/analytics/stats_test.clj
  test/metabase/api/database_test.clj
Labels: no-backport, .Team/Workflows

#53210 Return http channels for admins or users with settings permissions only
  enterprise/backend/test/metabase_enterprise/advanced_permissions/api/channel_test.clj
  enterprise/frontend/src/metabase-enterprise/application_permissions/types/user.ts
  frontend/src/metabase/notifications/modals/ChannelSetupModal.tsx
  frontend/src/metabase/notifications/modals/CreateOrEditQuestionAlertModal/CreateOrEditQuestionAlertModal.tsx
  frontend/src/metabase/notifications/modals/CreateOrEditQuestionAlertModal/CreateOrEditQuestionAlertModal.unit.spec.tsx
  frontend/src/metabase/notifications/modals/components/NotificationChannelsAddMenu.tsx
  frontend/src/metabase/notifications/modals/components/NotificationChannelsPicker.tsx
  frontend/src/metabase/notifications/utils.ts
  frontend/src/metabase/plugins/index.ts
  src/metabase/channel/api/channel.clj
  src/metabase/channel/models/channel.clj
  test/metabase/channel/api/channel_test.clj
  test/metabase/test.clj
Labels: no-backport, .Team/Workflows

#54507 docs - rename SQL snippets to snippets
  docs/README.md
  docs/exploration-and-organization/delete-and-restore.md
  docs/installation-and-operation/serialization.md
  docs/permissions/collections.md
  docs/permissions/data.md
  docs/permissions/introduction.md
  docs/permissions/snippets.md
  docs/permissions/start.md
  docs/questions/native-editor/referencing-saved-questions-in-queries.md
  docs/questions/native-editor/snippets.md
  docs/questions/native-editor/writing-sql.md
  docs/questions/start.md
Labels: Type:Documentation, backport

#54729 🤖 backported "docs - rename SQL snippets to snippets"
  docs/README.md
  docs/exploration-and-organization/delete-and-restore.md
  docs/installation-and-operation/serialization.md
  docs/permissions/collections.md
  docs/permissions/data.md
  docs/permissions/introduction.md
  docs/permissions/snippets.md
  docs/permissions/start.md
  docs/questions/native-editor/referencing-saved-questions-in-queries.md
  docs/questions/native-editor/snippets.md
  docs/questions/native-editor/writing-sql.md
  docs/questions/start.md
Labels: was-backported

#54724 fix(sdk): wrong icon on visualization selector
  enterprise/frontend/src/embedding-sdk/components/private/InteractiveQuestion/components/ChartTypeSelectorList/ChartTypeDropdown.tsx
Labels: no-backport, .Team/Embedding

#54734 docs - images and links
  docs/embedding/images/embedded-example-dashboard.png
  docs/embedding/images/interactive-question-sample-app.png
  docs/embedding/images/interactive-question.png
  docs/embedding/images/public-embed.png
  docs/embedding/images/query-builder.png
  docs/embedding/images/static-question.png
  docs/permissions/introduction.md
  docs/questions/images/build-a-funnel-query.png
  docs/questions/images/funnel-as-sql.png
  docs/questions/images/funnel-settings.png
  docs/questions/images/read-a-funnel.png
Labels: Type:Documentation, backport

#54735 🤖 backported "docs - images and links"
  docs/embedding/images/embedded-example-dashboard.png
  docs/embedding/images/interactive-question-sample-app.png
  docs/embedding/images/interactive-question.png
  docs/embedding/images/public-embed.png
  docs/embedding/images/query-builder.png
  docs/embedding/images/static-question.png
  docs/permissions/introduction.md
  docs/questions/images/build-a-funnel-query.png
  docs/questions/images/funnel-as-sql.png
  docs/questions/images/funnel-settings.png
  docs/questions/images/read-a-funnel.png
Labels: was-backported

#54738 Closes VIZ-469 Better DND experience for Pie in the visualizer
  frontend/src/metabase/dashboard/components/DashCard/DashCardActionsPanel/DashCardActionsPanel.tsx
  frontend/src/metabase/visualizer/utils/update-settings-for-display.ts
  frontend/src/metabase/visualizer/utils/update-settings-for-display.unit.spec.ts
  frontend/src/metabase/visualizer/visualizations/pie.ts
Labels: .Team/DashViz

#54285 fix: update saml20 for full SAML SLO support
  deps.edn
  enterprise/backend/src/metabase_enterprise/sso/api/sso.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/saml.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/sso_settings.clj
  enterprise/backend/test/metabase_enterprise/sso/api/sso_test.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/saml_test.clj
  test_resources/saml-slo-test-response.xml
  test_resources/sso/idp.cert
  test_resources/sso/idp.private.key
Labels: backport, .Team/AdminWebapp

#54475 use new endpoints for tiles in the pin map viz
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestionView.tsx
  frontend/src/metabase/visualizations/components/LeafletTilePinMap.jsx
  frontend/src/metabase/visualizations/components/Visualization/Visualization.tsx
  frontend/src/metabase/visualizations/lib/map.ts
  frontend/src/metabase/visualizations/lib/map.unit.spec.ts
  frontend/src/metabase/visualizations/types/visualization.ts
  src/metabase/public_sharing/api.clj
  test/metabase/public_sharing/api_test.clj
Labels: backport, .Team/DashViz

#54658 Only include actual users in admin recipients
  src/metabase/channel/email/messages.clj
  test/metabase/channel/email/messages_test.clj
Labels: backport, .Team/AdminWebapp, double-backport

#54316 🤖 backported "docs - sdk edits"
  docs/embedding/introduction.md
  docs/embedding/sdk/dashboards.md
  docs/embedding/sdk/introduction.md
  docs/embedding/sdk/plugins.md
  docs/embedding/sdk/questions.md
  docs/embedding/sdk/quickstart-cli.md
  docs/embedding/sdk/quickstart-with-sample-app.md
  docs/embedding/sdk/quickstart.md
  docs/embedding/sdk/version.md
  docs/embedding/start.md
Labels: was-backported

#54747 🤖 backported "Only include actual users in admin recipients"
  src/metabase/channel/email/messages.clj
  test/metabase/channel/email/messages_test.clj
Labels: was-backported

#54754 🤖 backported "docs - check for anchors"
  .github/workflows/links.yml
Labels: was-backported

#54298 🤖 backported "docs - sdk questions edits"
  docs/embedding/images/interactive-question.png
  docs/embedding/images/query-builder.png
  docs/embedding/images/static-question.png
  docs/embedding/sdk/questions.md
Labels: was-backported

#54751 Fix token unescaping in the expression editor
  e2e/support/helpers/e2e-custom-column-helpers.ts
  e2e/test/scenarios/custom-column/custom-column-reproductions.cy.spec.js
  frontend/src/metabase-lib/v1/expressions/recursive-parser.js
  frontend/src/metabase-lib/v1/expressions/recursive-parser.unit.spec.ts
Labels: backport, .Team/Querying

#54674 allow healthchecks for h2 dbs
  src/metabase/api/database.clj
Labels: no-backport, .Team/AdminWebapp

#54745 🤖 backported "Don't allow pulse.updated_at to change when dashboard changes"
  src/metabase/pulse/dashboard_subscription.clj
Labels: was-backported

#54571 Update running-metabase-on-docker.md
  docs/installation-and-operation/running-metabase-on-docker.md
Labels: Type:Documentation, backport

#54424 Add a nitpick for postgres and impersonation
  docs/permissions/impersonation.md
Labels: Type:Documentation, backport

#54764 🤖 backported "Update running-metabase-on-docker.md"
  docs/installation-and-operation/running-metabase-on-docker.md
Labels: was-backported

#54765 🤖 backported "Add a nitpick for postgres and impersonation"
  docs/permissions/impersonation.md
Labels: was-backported

#54671 Support relative-time-interval in the expression editor
  frontend/src/metabase-lib/v1/expressions/__support__/shared.ts
  frontend/src/metabase-lib/v1/expressions/config.ts
  frontend/src/metabase-lib/v1/expressions/helper-text-strings.ts
  frontend/src/metabase-lib/v1/expressions/recursive-parser.unit.spec.ts
Labels: backport, .Team/Querying

#54659 Do no singularize or pluralize table and column names in drills
  e2e/test/scenarios/question-reproductions/reproductions-3.cy.spec.js
  frontend/src/metabase/querying/drills/utils/fk-filter-drill.ts
  frontend/src/metabase/querying/drills/utils/underlying-records-drill.ts
Labels: no-backport, .Team/Querying

#54766 🤖 backported "Support relative-time-interval in the expression editor"
  frontend/src/metabase-lib/v1/expressions/__support__/shared.ts
  frontend/src/metabase-lib/v1/expressions/config.ts
  frontend/src/metabase-lib/v1/expressions/helper-text-strings.ts
  frontend/test/metabase/lib/expressions/recursive-parser.unit.spec.js
Labels: was-backported

#54762 Repro for "Add column popover is cut off"
  e2e/test/scenarios/question-reproductions/reproductions.cy.spec.ts
Labels: no-backport, .Team/Querying

#54748 🤖 backported "Only include actual users in admin recipients"
  src/metabase/email/messages.clj
  test/metabase/email/messages_test.clj
Labels: was-backported

#54769 🤖 backported "Fix large filter pill text wrapping"
  e2e/test/scenarios/filters-reproductions/filters-reproductions.cy.spec.js
  frontend/src/metabase/querying/filters/components/FilterPanel/FilterPill/FilterPill.module.css
Labels: was-backported

#54370 🤖 backported "docs - update sdk dashboard page "
  docs/embedding/sdk/dashboards.md
  docs/embedding/sdk/quickstart-cli.md
Labels: was-backported

#54686 Fix temporal unit interval translations
  e2e/test/scenarios/filters-reproductions/dashboard-filters-reproductions.cy.spec.js
  e2e/test/scenarios/filters/filter-bulk.cy.spec.js
  e2e/test/scenarios/filters/time-series-chrome.cy.spec.ts
  e2e/test/scenarios/question-reproductions/reproductions-1.cy.spec.js
  e2e/test/scenarios/search/search-filters.cy.spec.js
  e2e/test/scenarios/sharing/public-question.cy.spec.js
  frontend/src/metabase/parameters/utils/formatting.unit.spec.ts
  frontend/src/metabase/querying/filters/components/FilterModal/DateFilterEditor/DateFilterEditor.unit.spec.tsx
  frontend/src/metabase/querying/filters/utils/dates.unit.spec.ts
  frontend/src/metabase/search/components/SearchFilterDateDisplay/SearchFilterDateDisplay.unit.spec.tsx
  src/metabase/lib/temporal_bucket.cljc
  src/metabase/lib/temporal_bucket/util.cljc
  src/metabase/models/params/shared.cljc
  test/metabase/lib/fe_util_test.cljc
  test/metabase/lib/temporal_bucket_test.cljc
  test/metabase/models/params/shared_test.cljc
Labels: no-backport, .Team/Querying

#54744 🤖 backported "use new endpoints for tiles in the pin map viz"
  frontend/src/metabase/dashboard/components/DashCard/DashCardVisualization.tsx
  frontend/src/metabase/public/containers/PublicOrEmbeddedQuestion/PublicOrEmbeddedQuestionView.tsx
  frontend/src/metabase/visualizations/components/LeafletTilePinMap.jsx
  frontend/src/metabase/visualizations/lib/map.ts
  frontend/src/metabase/visualizations/lib/map.unit.spec.ts
  src/metabase/api/public.clj
  test/metabase/api/public_test.clj
Labels: was-backported

#54746 🤖 backported "Don't allow pulse.updated_at to change when dashboard changes"
  src/metabase/models/dashboard.clj
Labels: was-backported

#54761 fix: replicate mantine v7 behavior for relative datepicker
  frontend/src/metabase/querying/filters/components/DatePicker/RelativeDatePicker/DateOffsetIntervalPicker/DateOffsetIntervalPicker.tsx
Labels: .Team/Querying

#53693 Update required driver fields and placeholders
  modules/drivers/athena/resources/metabase-plugin.yaml
  modules/drivers/databricks/resources/metabase-plugin.yaml
  modules/drivers/druid-jdbc/resources/metabase-plugin.yaml
  modules/drivers/druid/resources/metabase-plugin.yaml
  modules/drivers/mongo/resources/metabase-plugin.yaml
  modules/drivers/oracle/resources/metabase-plugin.yaml
  modules/drivers/presto-jdbc/resources/metabase-plugin.yaml
  modules/drivers/redshift/resources/metabase-plugin.yaml
  modules/drivers/sparksql/resources/metabase-plugin.yaml
  modules/drivers/sqlite/resources/metabase-plugin.yaml
  modules/drivers/vertica/resources/metabase-plugin.yaml
Labels: backport, .Team/Drivers

#52351 [db-pool] Try again to address the thread deadlock caused by c3p0
  src/metabase/analytics/prometheus.clj
Labels: backport

#54776 🤖 backported "Update required driver fields and placeholders"
  modules/drivers/athena/resources/metabase-plugin.yaml
  modules/drivers/databricks/resources/metabase-plugin.yaml
  modules/drivers/druid-jdbc/resources/metabase-plugin.yaml
  modules/drivers/druid/resources/metabase-plugin.yaml
  modules/drivers/mongo/resources/metabase-plugin.yaml
  modules/drivers/oracle/resources/metabase-plugin.yaml
  modules/drivers/presto-jdbc/resources/metabase-plugin.yaml
  modules/drivers/redshift/resources/metabase-plugin.yaml
  modules/drivers/sparksql/resources/metabase-plugin.yaml
  modules/drivers/sqlite/resources/metabase-plugin.yaml
  modules/drivers/vertica/resources/metabase-plugin.yaml
Labels: was-backported

#54773 fix examples for mage cljfmt-files
  bb.edn
  bin/mage
  test/mage/core_test.clj
Labels: no-backport, .Team/DevEx

#54733 ci(sdk): Send SDK release notification to Slack
  .github/workflows/release-embedding-sdk.yml
  release/src/slack.ts
Labels: .CI & Tests, .Team/Embedding, double-backport

#54781 🤖 backported "ci(sdk): Send SDK release notification to Slack"
  .github/workflows/release-embedding-sdk.yml
  release/src/slack.ts
Labels: was-backported

#54780 🤖 backported "ci(sdk): Send SDK release notification to Slack"
  .github/workflows/release-embedding-sdk.yml
  release/src/slack.ts
Labels: was-backported

#54320 [Notification] Dedup send queue
  src/metabase/notification/send.clj
  test/metabase/notification/send_test.clj
Labels: no-backport, .Team/Workflows

#54709 Fix type logic for datetimeDiff() for days on postgres
  src/metabase/driver/postgres.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/query_processor_test/date_time_zone_functions_test.clj
Labels: backport, .Team/Querying

#54453 Clean template tags when changing databases
  e2e/test/scenarios/native/native-reproductions.cy.spec.js
  src/metabase/lib/native.cljc
  src/metabase/lib/schema/template_tag.cljc
  test/metabase/lib/native_test.cljc
Labels: backport, .Team/Querying

#54635 🤖 backported "Closes viz-474: conditional formatting polish"
  frontend/src/metabase/core/components/ColorSelector/ColorSelector.tsx
  frontend/src/metabase/hooks/use-toggle.ts
  frontend/src/metabase/visualizations/components/settings/ChartSettingsTableFormatting/RuleEditor.tsx
Labels: was-backported

#54753 fix: package.json script should use &&
  package.json
Labels: no-backport

#54786 🤖 backported "Fix type logic for datetimeDiff() for days on postgres"
  src/metabase/driver/postgres.clj
  test/metabase/driver/postgres_test.clj
  test/metabase/query_processor_test/date_time_zone_functions_test.clj
Labels: was-backported

#54789 stabilize flaky test
  e2e/test/scenarios/onboarding/command-palette.cy.spec.js
Labels: .CI & Tests, backport, flaky-test-fix

#54707 Remove findDOMNode from visualization components
  frontend/src/metabase/visualizations/components/CardRenderer.jsx
  frontend/src/metabase/visualizations/components/LegendHorizontal.jsx
  frontend/src/metabase/visualizations/components/LegendItem.jsx
  frontend/src/metabase/visualizations/components/LegendVertical.jsx
  frontend/src/metabase/visualizations/visualizations/Gauge/Gauge.jsx
  frontend/src/metabase/visualizations/visualizations/PivotTable/PivotTable.tsx
  frontend/src/metabase/visualizations/visualizations/Progress/Progress.jsx
Labels: .Team/Embedding, run-tests, double-backport

#54792 🤖 backported "stabilize flaky test"
  e2e/test/scenarios/onboarding/command-palette.cy.spec.js
Labels: was-backported
