Repository metabase/metabase, pull requests merged in 2025-08, with the labels that each got.

#61671 Fix release notes preview action
  .github/workflows/release-notes-preview.yml
Labels: .Building & Releasing, no-backport, .Team/AdminWebapp

#61659 🤖 backported "update snowflake's commons-lang3 to clear out security issue"
  modules/drivers/snowflake/deps.edn
Labels: was-backported

#61707 docs(sdk): Update SDK version to 0.56.1-nightly
  enterprise/frontend/src/embedding-sdk/CHANGELOG.md
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: no-backport

#61711 🤖 backported "remove references to ENTERPRISE_TOKEN"
  docs/developers-guide/e2e-tests.md
  e2e/runner/run_cypress_local.ts
  enterprise/frontend/src/embedding-sdk/dev.md
Labels: was-backported

#61475 feat(sdk): Use Mantine styles with CSS layer for the SDK
  e2e/test-component/scenarios/embedding-sdk/styles-tests.cy.spec.tsx
  enterprise/frontend/src/embedding-sdk/components/private/PublicComponentStylesWrapper.tsx
  enterprise/frontend/src/embedding-sdk/components/public/MetabaseProvider.tsx
  enterprise/frontend/src/embedding-sdk/components/public/dashboard/SdkDashboard.stories.tsx
  enterprise/frontend/src/embedding-sdk/index.ts
  frontend/src/metabase/embedding-sdk/css/index.module.css
  frontend/src/metabase/embedding-sdk/css/layer.module.css
  frontend/src/metabase/embedding-sdk/css/vendor.module.css
  patches/@mantine+core+8.0.2.patch
  webpack.embedding-sdk.config.js
Labels: no-backport, .Team/Embedding

#61717 🤖 backported "fix: issues generating valid urls for map tiles"
  e2e/test/scenarios/visualizations-charts/maps.cy.spec.js
  frontend/src/metabase/visualizations/components/LeafletTilePinMap.jsx
  frontend/src/metabase/visualizations/lib/map.ts
  frontend/src/metabase/visualizations/lib/map.unit.spec.ts
Labels: was-backported

#61563 Always set roles on connections
  enterprise/backend/test/metabase_enterprise/impersonation/driver_test.clj
  modules/drivers/clickhouse/src/metabase/driver/clickhouse.clj
  src/metabase/driver/sql_jdbc/execute.clj
Labels: backport

#61723 🤖 backported "chore(sdk): bump minimum react version to 18"
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: was-backported

#61724 🤖 backported "chore(sdk): bump minimum react version to 18"
  enterprise/frontend/src/embedding-sdk/package.template.json
Labels: was-backported

#61686 keep report cards and collections in sync
  enterprise/backend/src/metabase_enterprise/reports/api/report.clj
  enterprise/backend/src/metabase_enterprise/reports/models/report.clj
  enterprise/backend/test/metabase_enterprise/reports/api/report_test.clj
  enterprise/backend/test/metabase_enterprise/reports/models/report_test.clj
Labels: .Team/AdminWebapp

#61565 Fix zero measure count issue for pivot tables
  src/metabase/query_processor/pivot/postprocess.clj
  test/metabase/query_processor/pivot/postprocess_test.clj
Labels: backport, .Team/AdminWebapp

#61725 🤖 backported "Fix: UXW-382 - Public Links menu item within sharing menu is too large"
  e2e/test/scenarios/sharing/public-sharing-embed-button-behavior.cy.spec.js
  frontend/src/metabase/embedding/components/SharingMenu/MenuItems/PublicLinkMenuItem.tsx
  frontend/src/metabase/embedding/components/SharingMenu/test/DashboardSharingMenu.unit.spec.tsx
  frontend/src/metabase/embedding/components/SharingMenu/test/QuestionSharingMenu.unit.spec.tsx
  frontend/src/metabase/ui/components/overlays/Menu/Menu.module.css
Labels: was-backported

#61615 do not throw on empty query for /search
  src/metabase/search/api.clj
  test/metabase/search/api_test.clj
Labels: backport, .Team/AdminWebapp

#61730 🤖 backported "do not throw on empty query for /search"
  src/metabase/search/api.clj
  test/metabase/search/api_test.clj
Labels: was-backported

#61715 🤖 backported "Enable DB routing for snowflake"
  docs/developers-guide/driver-changelog.md
  enterprise/backend/test/metabase_enterprise/impersonation/driver_test.clj
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
  src/metabase/driver.clj
  src/metabase/driver/sql_jdbc/execute.clj
Labels: was-backported

#61700 [ci run] Fix deprecated input
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FieldSettingsPopover.styled.tsx
  frontend/src/metabase/actions/containers/ActionCreator/FormCreator/FieldSettingsPopover.tsx
Labels: no-backport, .Team/AdminWebapp

#61664 Format scalar currencies correctly in alerts
  src/metabase/channel/render/body.clj
  src/metabase/formatter/core.clj
  src/metabase/formatter/impl.clj
  test/metabase/formatter/impl_test.clj
Labels: backport, .Team/AdminWebapp

#61744 docs - link to intro page
  docs/embedding/sdk/quickstart.md
Labels: Type:Documentation, double-backport

#61754 🤖 backported "docs - update expressions list"
  docs/questions/query-builder/expressions-list.md
Labels: was-backported

#61630 Enable DB routing for Databricks
  .github/workflows/drivers.yml
  enterprise/backend/test/metabase_enterprise/database_routing/e2e_test.clj
  modules/drivers/databricks/src/metabase/driver/databricks.clj
  modules/drivers/databricks/test/metabase/test/data/databricks.clj
Labels: backport

#61022 feat(sdk): hide tables by default in embedding data picker if there are more than 2 models
  enterprise/frontend/src/embedding-sdk/components/public/dashboard/EditableDashboard/EditableDashboard.unit.spec.tsx
  frontend/src/metabase-types/store/embedding-data-picker.ts
  frontend/src/metabase-types/store/mocks/embedding-data-picker.ts
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/BrowseNavSection.tsx
  frontend/src/metabase/querying/notebook/components/NotebookDataPicker/EmbeddingDataPicker/EmbeddingDataPicker.tsx
  frontend/src/metabase/querying/notebook/components/NotebookDataPicker/EmbeddingDataPicker/constants.ts
  frontend/src/metabase/redux/embedding-data-picker.ts
  frontend/src/metabase/selectors/embedding-data-picker.ts
Labels: backport, .Team/Embedding, run-tests

#61758 🤖 backported "Add note on useExistingUserSession's browser compatibility"
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/get-code.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/user-settings-persistence.cy.spec.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/GetCodeStep.tsx
Labels: was-backported

#61760 🤖 backported "feat(sdk): hide tables by default in embedding data picker if there are more than 2 models"
  enterprise/frontend/src/embedding-sdk/components/public/dashboard/EditableDashboard/EditableDashboard.unit.spec.tsx
  frontend/src/metabase-types/store/embedding-data-picker.ts
  frontend/src/metabase-types/store/mocks/embedding-data-picker.ts
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/BrowseNavSection.tsx
  frontend/src/metabase/querying/notebook/components/NotebookDataPicker/EmbeddingDataPicker/EmbeddingDataPicker.tsx
  frontend/src/metabase/querying/notebook/components/NotebookDataPicker/EmbeddingDataPicker/constants.ts
  frontend/src/metabase/redux/embedding-data-picker.ts
  frontend/src/metabase/selectors/embedding-data-picker.ts
Labels: was-backported

#61159 [m.u.performance] Make performance namespace cross-platform
  src/metabase/util/performance.clj
  src/metabase/util/performance.cljc
  test/metabase/util/performance_test.clj
  test/metabase/util/performance_test.cljc
Labels: backport

#61782 Cleanup stacked card background on embed flow preview
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/SdkIframeEmbedSetup.tsx
Labels: backport, .Team/Embedding

#61791 Revert "🤖 backported "feat(sdk): hide tables by default in embedding data picker if there are more than 2 models""
  enterprise/frontend/src/embedding-sdk/components/public/dashboard/EditableDashboard/EditableDashboard.unit.spec.tsx
  frontend/src/metabase-types/store/embedding-data-picker.ts
  frontend/src/metabase-types/store/mocks/embedding-data-picker.ts
  frontend/src/metabase/nav/containers/MainNavbar/MainNavbarContainer/BrowseNavSection.tsx
  frontend/src/metabase/querying/notebook/components/NotebookDataPicker/EmbeddingDataPicker/EmbeddingDataPicker.tsx
  frontend/src/metabase/querying/notebook/components/NotebookDataPicker/EmbeddingDataPicker/constants.ts
  frontend/src/metabase/redux/embedding-data-picker.ts
  frontend/src/metabase/selectors/embedding-data-picker.ts
Labels: no-backport, .Team/Embedding

#61241 [pivot] Implement optimized clj->js and use it when recalculating pivots on frontend
  src/metabase/pivot/core.cljc
  src/metabase/pivot/js.cljs
  src/metabase/util/performance.cljc
Labels: backport

#61768 Adjust semantic search query to favor HNSW index over seq scans
  enterprise/backend/src/metabase_enterprise/semantic_search/index.clj
Labels: .Team/Metabot

#61766 bump hive to 4.1.0
  modules/drivers/hive-like/deps.edn
Labels: backport

#61788 Update copy from new iframe to Embedded Analytics JS in embed flow
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/GetCodeStep.tsx
Labels: backport, .Team/Embedding

#61812 🤖 backported "Update copy from new iframe to Embedded Analytics JS in embed flow"
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/GetCodeStep.tsx
Labels: was-backported

#61796 Migrate webpack.shared.config.js to rspack
  .github/file-paths.yaml
  package.json
  resources/frontend_shared/color_selector.js
  rspack.shared.config.js
Labels: no-backport, .Team/Embedding

#61799 refactor(sdk): Add `x-metabase-version` header to BE responses
  enterprise/frontend/src/embedding-sdk/hooks/private/use-init-data/use-init-data.ts
  enterprise/frontend/src/embedding-sdk/store/reducer.ts
  enterprise/frontend/src/embedding-sdk/store/selectors.ts
  enterprise/frontend/src/embedding-sdk/store/types.ts
  enterprise/frontend/src/embedding-sdk/test/mocks/state.ts
  frontend/src/metabase/lib/api.js
  src/metabase/server/handler.clj
  src/metabase/server/middleware/misc.clj
  src/metabase/server/middleware/security.clj
  test/metabase/server/middleware/misc_test.clj
Labels: no-backport, .Team/Embedding

#61801 refactor(sdk): Prepare `src/metabase` code for Hosted Bundle
  enterprise/frontend/src/embedding-sdk/components/public/MetabaseProvider.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/components/ColorSettings/ColorSettings.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/whitelabel/lib/whitelabel.js
  frontend/src/metabase/api/dashboard.ts
  frontend/src/metabase/common/components/Alert/Alert.stories.tsx
  frontend/src/metabase/common/components/Alert/Alert.styled.tsx
  frontend/src/metabase/common/components/Alert/Alert.tsx
  frontend/src/metabase/common/hooks/use-instance-locale/index.ts
  frontend/src/metabase/common/hooks/use-instance-locale/use-instance-locale.ts
  frontend/src/metabase/common/hooks/use-locale/use-locale.ts
  frontend/src/metabase/css/core/colors.module.css
  frontend/src/metabase/embedding-sdk/theme/define-metabase-theme.ts
  frontend/src/metabase/embedding-sdk/theme/index.ts
  frontend/src/metabase/lib/colors/colors.ts
  frontend/src/metabase/lib/colors/index.ts
  frontend/src/metabase/lib/colors/palette.ts
  frontend/src/metabase/lib/colors/palette.unit.spec.ts
  frontend/src/metabase/lib/colors/types.ts
  frontend/src/metabase/redux/settings.ts
  frontend/src/metabase/static-viz/lib/colors.ts
Labels: no-backport, .Team/Embedding

#61827 [Release blocker] Revert join custom columns changes
  src/metabase/lib/fe_util.cljc
  src/metabase/lib/join.cljc
  test/metabase/lib/fe_util_test.cljc
  test/metabase/lib/join_test.cljc
Labels: backport, .Team/Querying

#61803 Rename embed-iframe route to embed-js
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/auto-enable-embedding.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/helpers/index.ts
  frontend/src/metabase/common/components/NewItemMenu/NewItemMenuView.tsx
  frontend/src/metabase/nav/containers/Navbar.unit.spec.tsx
  frontend/src/metabase/redux/app.ts
  frontend/src/metabase/routes.jsx
Labels: backport, .Team/Embedding

#61837 🤖 backported "[Release blocker] Revert join custom columns changes"
  src/metabase/lib/fe_util.cljc
  src/metabase/lib/join.cljc
  test/metabase/lib/fe_util_test.cljc
  test/metabase/lib/join_test.cljc
Labels: was-backported

#61840 🤖 backported "Rename embed-iframe route to embed-js"
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/auto-enable-embedding.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/helpers/index.ts
  frontend/src/metabase/common/components/NewItemMenu/NewItemMenuView.tsx
  frontend/src/metabase/nav/containers/Navbar.unit.spec.tsx
  frontend/src/metabase/redux/app.ts
  frontend/src/metabase/routes.jsx
Labels: was-backported

#61690 fix: handle arrays in sparksql
  modules/drivers/databricks/test/metabase/driver/databricks_test.clj
  modules/drivers/hive-like/test/metabase/driver/hive_like_test.clj
  modules/drivers/sparksql/src/metabase/driver/sparksql.clj
  modules/drivers/sparksql/test/metabase/driver/sparksql_test.clj
  test/metabase/actions/test_util.clj
Labels: double-backport

#61841 🤖 backported "[Release blocker] Revert fuzzy matching changes"
  e2e/test/scenarios/custom-column/custom-column-reproductions.cy.spec.js
  e2e/test/scenarios/filters/filter.cy.spec.js
  frontend/src/metabase/common/components/AccordionList/AccordionList.tsx
  frontend/src/metabase/common/components/AccordionList/AccordionList.unit.spec.tsx
  frontend/src/metabase/common/components/AccordionList/utils.ts
  frontend/src/metabase/common/components/AggregationPicker/AggregationPicker.tsx
  frontend/src/metabase/common/components/QueryColumnPicker/QueryColumnPicker.tsx
  frontend/src/metabase/querying/expressions/suggestions/aggregations.ts
  frontend/src/metabase/querying/expressions/suggestions/aggregations.unit.spec.ts
  frontend/src/metabase/querying/expressions/suggestions/fields.ts
  frontend/src/metabase/querying/expressions/suggestions/fields.unit.spec.ts
  frontend/src/metabase/querying/expressions/suggestions/functions.ts
  frontend/src/metabase/querying/expressions/suggestions/functions.unit.spec.ts
  frontend/src/metabase/querying/expressions/suggestions/metrics.ts
  frontend/src/metabase/querying/expressions/suggestions/segments.ts
  frontend/src/metabase/querying/expressions/suggestions/util.ts
  frontend/src/metabase/querying/filters/components/FilterPicker/FilterColumnPicker/FilterColumnPicker.tsx
Labels: was-backported

#61818 Persist cards when saving document
  enterprise/backend/src/metabase_enterprise/documents/api.clj
  enterprise/backend/src/metabase_enterprise/documents/api/document.clj
  enterprise/backend/src/metabase_enterprise/documents/models/document.clj
  enterprise/backend/src/metabase_enterprise/documents/models/document_version.clj
  enterprise/backend/src/metabase_enterprise/documents/prose_mirror.clj
  enterprise/backend/test/metabase_enterprise/documents/api/card_test.clj
  enterprise/backend/test/metabase_enterprise/documents/api/collection_test.clj
  enterprise/backend/test/metabase_enterprise/documents/api/document_test.clj
  enterprise/backend/test/metabase_enterprise/documents/models/dashboard_card_test.clj
  enterprise/backend/test/metabase_enterprise/documents/models/document_test.clj
  enterprise/backend/test/metabase_enterprise/documents/prose_mirror_test.clj
  enterprise/backend/test/metabase_enterprise/documents/recent_views_test.clj
  enterprise/backend/test/metabase_enterprise/documents/search_test.clj
  enterprise/frontend/src/metabase-enterprise/api/document.ts
  enterprise/frontend/src/metabase-enterprise/api/tags.ts
  enterprise/frontend/src/metabase-enterprise/documents/components/DocumentPage.tsx
  enterprise/frontend/src/metabase-enterprise/documents/components/Editor/CommandPlugin.tsx
  enterprise/frontend/src/metabase-enterprise/documents/components/Editor/Editor.tsx
  enterprise/frontend/src/metabase-enterprise/documents/components/Editor/extensions/CardEmbed/CardEmbedNode.tsx
  enterprise/frontend/src/metabase-enterprise/documents/components/Editor/extensions/CardEmbed/ModifyQuestionModal.tsx
  enterprise/frontend/src/metabase-enterprise/documents/components/Editor/hooks/useCardEmbedSelection.ts
  enterprise/frontend/src/metabase-enterprise/documents/components/EmbedQuestionSettingsSidebar.tsx
  enterprise/frontend/src/metabase-enterprise/documents/documents.slice.ts
  enterprise/frontend/src/metabase-enterprise/documents/hooks/index.ts
  enterprise/frontend/src/metabase-enterprise/documents/hooks/use-document-card-save.ts
  enterprise/frontend/src/metabase-enterprise/documents/hooks/useCardWithDataset.ts
  enterprise/frontend/src/metabase-enterprise/documents/hooks/useDocumentActions.ts
  enterprise/frontend/src/metabase-enterprise/documents/hooks/useDocumentState.ts
  enterprise/frontend/src/metabase-enterprise/documents/hooks/useDraftCardOperations.ts
  enterprise/frontend/src/metabase-enterprise/documents/selectors.ts
  enterprise/frontend/src/metabase-enterprise/documents/utils/editorNodeUtils.ts
  enterprise/frontend/src/metabase-enterprise/documents/utils/visualizationUtils.ts
  frontend/src/metabase-types/api/card.ts
  frontend/src/metabase-types/api/document.ts
  frontend/src/metabase/api/tags/constants.ts
  frontend/src/metabase/collections/components/CollectionContent/constants.ts
  resources/migrations/056_update_migrations.yaml
  src/metabase/activity_feed/events/recent_views.clj
  src/metabase/collections/api.clj
  src/metabase/dashboards/models/dashboard_card.clj
  src/metabase/lib/schema/metadata.cljc
  src/metabase/models/resolution.clj
  src/metabase/queries/api/card.clj
  src/metabase/queries/models/card.clj
  src/metabase/queries/schema.clj
  src/metabase/util/malli/schema.clj
  test/metabase/collections/api_test.clj
  test/metabase/dashboards/models/dashboard_card_test.clj
  test/metabase/events/recent_views_test.clj
  test/metabase/queries/api/card_test.clj
  test/metabase/queries/models/card_test.clj
  test/metabase/test/util.clj
Labels: .Team/DashViz

#61757 🤖 backported "Enable DB routing for Databricks"
  .github/workflows/drivers.yml
  enterprise/backend/test/metabase_enterprise/database_routing/e2e_test.clj
  modules/drivers/databricks/src/metabase/driver/databricks.clj
  modules/drivers/databricks/test/metabase/test/data/databricks.clj
Labels: was-backported

#61728 🤖 backported "Fix zero measure count issue for pivot tables"
  src/metabase/query_processor/pivot/postprocess.clj
  test/metabase/query_processor/pivot/postprocess_test.clj
Labels: was-backported

#61822 refactor(sdk): Convert webpack.embedding-sdk.config to rspack and prepare for Hosted Bundle
  .eslintrc.js
  .github/file-paths.yaml
  .storybook-sdk/main.js
  .storybook/main.ts
  docs/developers-guide/devenv.md
  e2e/support/component-webpack.config.js
  enterprise/frontend/src/embedding-sdk/.eslintrc.js
  frontend/build/embedding-sdk/rspack/shared.js
  frontend/build/embedding-sdk/rspack/typescript-convert-errors-to-warnings.js
  frontend/build/shared/constants.js
  frontend/build/shared/rspack/babel-config.js
  frontend/build/shared/rspack/css-config.js
  frontend/build/shared/rspack/get-banner-options.js
  frontend/parse-deps.js
  frontend/src/metabase/app.js
  frontend/src/metabase/common/components/dnd/ItemsDragLayer.jsx
  package.json
  rspack.config.js
  rspack.embedding-sdk-bundle.config.js
  rspack.main.config.js
  rspack.shared.config.js
  rspack.static-viz.config.js
  webpack.embedding-sdk.config.js
  yarn.lock
Labels: no-backport, .Team/Embedding

#61802 Fix upsell button and auth links in embedding admin settings
  e2e/test/scenarios/embedding/embedding-smoketests.cy.spec.js
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingOption/InteractiveEmbeddingOptionCard/InteractiveEmbeddingOptionCard.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/EmbeddingSdkSettings.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/tests/common.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/tests/enterprise.unit.spec.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/tests/premium.unit.spec.tsx
  frontend/src/metabase/admin/upsells/UpsellEmbeddingButton.tsx
  frontend/src/metabase/admin/upsells/UpsellSdkLink.tsx
  frontend/src/metabase/admin/upsells/components/Upsells.module.css
Labels: backport, .Team/Embedding

#61448 PR-envs and ci skip should work together
  .github/workflows/e2e-tests.yml
  .github/workflows/pr-env-labeled.yml
  .github/workflows/pr-env.yml
  .github/workflows/run-tests.yml
  .github/workflows/uberjar.yml
Labels: no-backport

#61714 Prg-108-add-gem-icon-and-free-trial-cta-in-interactive-embedding
  e2e/test/scenarios/sharing/public-sharing-embed-button-behavior.cy.spec.js
  frontend/src/metabase/admin/upsells/UpsellEmbeddingButton.tsx
  frontend/src/metabase/admin/upsells/UpsellSdkCta.tsx
  frontend/src/metabase/admin/upsells/components/UpsellBanner.tsx
  frontend/src/metabase/admin/upsells/components/UpsellBigCard.tsx
  frontend/src/metabase/admin/upsells/components/UpsellCard.tsx
  frontend/src/metabase/admin/upsells/components/UpsellCta.module.css
  frontend/src/metabase/admin/upsells/components/UpsellCta.stories.tsx
  frontend/src/metabase/admin/upsells/components/UpsellCta.tsx
  frontend/src/metabase/admin/upsells/components/UpsellCta.unit.spec.tsx
  frontend/src/metabase/admin/upsells/components/Upsells.base.module.css
  frontend/src/metabase/admin/upsells/components/Upsells.module.css
  frontend/src/metabase/admin/upsells/components/index.ts
  frontend/src/metabase/public/components/EmbedModal/EmbedModalContent/tests/EmbedModalContent.enterprise.unit.spec.tsx
  frontend/src/metabase/public/components/EmbedModal/EmbedModalContent/tests/EmbedModalContent.premium.unit.spec.tsx
  frontend/src/metabase/public/components/EmbedModal/EmbedModalContent/tests/setup.tsx
  frontend/src/metabase/public/components/EmbedModal/SelectEmbedTypePane/SelectEmbedTypePane.tsx
  frontend/src/metabase/public/components/EmbedModal/SelectEmbedTypePane/SharingPaneButton/SharingPaneButton.tsx
Labels: no-backport, .Team/ProductGrowth

#61867 🤖 backported "refactor(sdk): Add styles for custom SDK spinner loader"
  enterprise/frontend/src/embedding/sdk-common/lib/get-sdk-loader-css.ts
Labels: was-backported

#61871 🤖 backported "Add color reset button to embed flow"
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/select-embed-options.cy.spec.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/ColorCustomizationSection.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/SdkIframeEmbedPreview.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/SelectEmbedOptionsStep.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/utils/theme-colors.ts
  frontend/src/metabase/common/components/ColorPicker/ColorPillPicker.tsx
Labels: was-backported

#61872 🤖 backported "feat(sdk): add translation context and aria-label to embedding sdk settings"
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/EmbeddingSdkSettings.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/tests/common.unit.spec.tsx
Labels: was-backported

#61869 Always set connection role for Redshift
  enterprise/backend/test/metabase_enterprise/impersonation/driver_test.clj
  modules/drivers/redshift/src/metabase/driver/redshift.clj
Labels: backport, .Team/Querying

#61815 Fallback to appdb search if semantic search doesn't return enough results
  .clj-kondo/config/modules/config.edn
  enterprise/backend/src/metabase_enterprise/semantic_search/core.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/index.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/settings.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/core_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/test_util.clj
  src/metabase/search/engine.clj
  src/metabase/search/impl.clj
  src/metabase/search/semantic/core.clj
Labels: .Team/Metabot

#61876 docs: jwt docs
  docs/embedding/interactive-embedding-quick-start-guide.md
  docs/people-and-groups/authenticating-with-jwt.md
  docs/people-and-groups/images/JWT-auth-form.png
  docs/people-and-groups/images/jwt-groups.png
Labels: Type:Documentation, backport

#61879 🤖 backported "docs: jwt docs "
  docs/embedding/interactive-embedding-quick-start-guide.md
  docs/people-and-groups/authenticating-with-jwt.md
  docs/people-and-groups/images/JWT-auth-form.png
  docs/people-and-groups/images/jwt-groups.png
Labels: was-backported

#61873 🤖 backported "Always set connection role for Redshift"
  enterprise/backend/test/metabase_enterprise/impersonation/driver_test.clj
  modules/drivers/redshift/src/metabase/driver/redshift.clj
Labels: was-backported

#61881 🤖 backported "Include columns that are not specifically excluded"
  src/metabase/query_processor/streaming.clj
  test/metabase/channel/render/table_test.clj
  test/metabase/query_processor/streaming_test.clj
Labels: was-backported

#61764 Add table link to metadata page
  e2e/support/helpers/e2e-datamodel-helpers.ts
  e2e/test/scenarios/admin/datamodel/datamodel.cy.spec.ts
  frontend/src/metabase/metadata/components/NameDescriptionInput/NameDescriptionInput.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/TableSection/TableSection.tsx
  frontend/src/metabase/metadata/pages/DataModel/components/TableSection/TableSection.unit.spec.tsx
Labels: no-backport, PR-Env

#61842 Add MB_SYNC_LEAF_FIELDS_LIMIT setting
  modules/drivers/mongo/src/metabase/driver/mongo.clj
  modules/drivers/mongo/test/metabase/driver/mongo_test.clj
  src/metabase/driver/settings.clj
Labels: backport, .Team/Metabot

#61889 🤖 backported "Check data permissions of result metadata columns"
  enterprise/backend/test/metabase_enterprise/advanced_permissions/models/permissions/block_permissions_test.clj
  src/metabase/queries/api/card.clj
  src/metabase/query_permissions/core.clj
  src/metabase/query_permissions/impl.clj
  src/metabase/query_processor/middleware/permissions.clj
Labels: was-backported

#61890 🤖 backported "Check data permissions of result metadata columns"
  enterprise/backend/test/metabase_enterprise/advanced_permissions/models/permissions/block_permissions_test.clj
  src/metabase/queries/api/card.clj
  src/metabase/query_permissions/core.clj
  src/metabase/query_permissions/impl.clj
  src/metabase/query_processor/middleware/permissions.clj
Labels: was-backported

#61884 Semantic search test fixes
  enterprise/backend/test/metabase_enterprise/semantic_search/core_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/db_test.clj
Labels: .Team/Metabot

#61530 QP Binning middleware => Lib
  src/metabase/lib/binning.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/field/resolution.cljc
  src/metabase/query_processor/middleware/binning.clj
  src/metabase/query_processor/preprocess.clj
  test/metabase/lib/binning_test.cljc
  test/metabase/lib/field/resolution_test.cljc
  test/metabase/query_processor/middleware/binning_test.clj
  test/metabase/query_processor_test/binning_test.clj
  test/metabase/query_processor_test/breakout_test.clj
Labels: backport, .Team/DevEx

#61902 🤖 backported "QP Binning middleware => Lib"
  src/metabase/lib/binning.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/field/resolution.cljc
  src/metabase/query_processor/middleware/binning.clj
  src/metabase/query_processor/preprocess.clj
  test/metabase/lib/binning_test.cljc
  test/metabase/lib/field/resolution_test.cljc
  test/metabase/query_processor/middleware/binning_test.clj
  test/metabase/query_processor_test/binning_test.clj
  test/metabase/query_processor_test/breakout_test.clj
Labels: was-backported

#61323 add connection string form prefill feature
  e2e/support/commands.js
  e2e/support/commands/ui/paste.ts
  e2e/test/scenarios/admin/database-connection-strings.cy.spec.ts
  e2e/test/scenarios/admin/databases.cy.spec.js
  e2e/test/scenarios/admin/helpers/e2e-database-helpers.js
  enterprise/frontend/src/embedding-sdk/cli/steps/add-database-connection.ts
  enterprise/frontend/src/metabase-enterprise/database_routing/DatabaseRoutingSection/DatabaseRoutingSection.tsx
  frontend/src/metabase-types/analytics/event.ts
  frontend/src/metabase-types/api/settings.ts
  frontend/src/metabase-types/guards/index.ts
  frontend/src/metabase-types/guards/settings.ts
  frontend/src/metabase/admin/databases/components/DatabaseEditConnectionForm.tsx
  frontend/src/metabase/admin/databases/components/ExistingDatabaseHeader.tsx
  frontend/src/metabase/databases/components/DatabaseConnectionUri/DatabaseConnectionStringField.tsx
  frontend/src/metabase/databases/components/DatabaseConnectionUri/analytics.ts
  frontend/src/metabase/databases/components/DatabaseConnectionUri/database-field-mapper.ts
  frontend/src/metabase/databases/components/DatabaseConnectionUri/engines-config.ts
  frontend/src/metabase/databases/components/DatabaseConnectionUri/index.ts
  frontend/src/metabase/databases/components/DatabaseConnectionUri/parse-connection-regex.ts
  frontend/src/metabase/databases/components/DatabaseConnectionUri/parse-connection-regex.unit.spec.ts
  frontend/src/metabase/databases/components/DatabaseForm/DatabaseForm.tsx
  frontend/src/metabase/databases/components/DatabaseForm/tests/setup.tsx
  frontend/src/metabase/databases/components/DatabaseNameField/DatabaseNameField.tsx
  frontend/src/metabase/databases/components/DatabaseNameField/index.ts
  frontend/src/metabase/databases/utils/schema.ts
  frontend/src/metabase/setup/components/DatabaseStep/DatabaseStep.tsx
  frontend/src/metabase/setup/components/EmbeddingSetup/steps/DataConnectionStep.tsx
  rspack.embedding-sdk-cli.config.js
  yarn.lock
Labels: no-backport, PR-Env, .Team/ProductGrowth

#61911 🤖 backported "Emb 668 make embed bundles work with cypress locally and hot reload"
  e2e/support/helpers/e2e-embedding-iframe-sdk-helpers.ts
  rspack.iframe-sdk-embed.config.js
Labels: was-backported

#61823 Fix Payload Type Typo for Notifications
  docs/api.html
  src/metabase/notification/api/notification.clj
Labels: backport

#61865 Tag an embed flow test "persists chart embed options" as flaky
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/user-settings-persistence.cy.spec.ts
Labels: backport, .Team/Embedding

#61540 feat: endpoint for retrieve embedding token from jwt
  enterprise/backend/src/metabase_enterprise/sso/api/sso.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/jwt.clj
  enterprise/backend/test/metabase_enterprise/sso/api/sso_test.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj
Labels: backport

#61921 🤖 backported "Tag an embed flow test "persists chart embed options" as flaky"
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/user-settings-persistence.cy.spec.ts
Labels: was-backported

#61866 add snowflake csid as Metabase_Metabase
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
Labels: double-backport

#61922 🤖 backported "feat: endpoint for retrieve embedding token from jwt"
  enterprise/backend/src/metabase_enterprise/sso/api/sso.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/jwt.clj
  enterprise/backend/test/metabase_enterprise/sso/api/sso_test.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj
Labels: was-backported

#61925 🤖 backported "add snowflake csid as Metabase_Metabase"
  modules/drivers/snowflake/src/metabase/driver/snowflake.clj
  modules/drivers/snowflake/test/metabase/driver/snowflake_test.clj
Labels: was-backported

#61917 🤖 backported "Fix Payload Type Typo for Notifications"
  docs/api.html
  src/metabase/notification/api/notification.clj
Labels: was-backported

#61898 Add `mbql-5-query` macro
  .clj-kondo/config.edn
  .cljfmt.edn
  src/metabase/lib/schema.cljc
  src/metabase/lib/schema/join.cljc
  test/metabase/lib/test_util/macros.clj
  test/metabase/test/data/mbql_query_impl.cljc
Labels: backport, .Team/Querying

#61926 Temporarily replace docs and quickstart with "Try it out"
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/EmbeddingSdkSettings.tsx
Labels: backport, .Team/Embedding

#61927 fix: jwt auth doesn't wipe login_attributes
  enterprise/backend/src/metabase_enterprise/sso/integrations/jwt.clj
  enterprise/backend/src/metabase_enterprise/sso/integrations/sso_utils.clj
  enterprise/backend/test/metabase_enterprise/sso/integrations/jwt_test.clj
  enterprise/frontend/src/metabase-enterprise/auth/components/SettingsJWTForm/SettingsJWTForm.tsx
Labels: backport, .Team/UXWest

#61929 🤖 backported "fix(sdk): targetCollection should take precedence over recent dashboard"
  e2e/test-component/scenarios/embedding-sdk/reproductions/sdk-question-reproductions.cy.spec.tsx
  frontend/src/metabase/common/components/SaveQuestionForm/context.tsx
Labels: was-backported

#61932 🤖 backported "Remove Beta badge from Embedded Analytics JS"
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/EmbeddingSdkSettings.tsx
  frontend/src/metabase/admin/settings/components/EmbeddingSettings/EmbeddingSdkSettings/tests/simple-embedding.unit.spec.tsx
  frontend/src/metabase/common/components/NewItemMenu/NewItemMenu.premium.unit.spec.tsx
  frontend/src/metabase/common/components/NewItemMenu/NewItemMenuView.tsx
Labels: was-backported

#61935 🤖 backported "Improve tests from #53373"
  test/metabase/queries/api/card_test.clj
Labels: was-backported

#61808 fix(sdk): send CORS headers for error messages when embedding is disabled
  e2e/test/scenarios/embedding-sdk/static-dashboard-cors.cy.spec.js
  e2e/test/scenarios/embedding/sdk-iframe-embedding/authentication.cy.spec.ts
  enterprise/backend/src/metabase_enterprise/sso/integrations/jwt.clj
  enterprise/frontend/src/embedding-sdk/errors/generic.ts
  enterprise/frontend/src/embedding-sdk/errors/jwt.ts
  enterprise/frontend/src/embedding/auth-common/connect-to-instance-auth-sso.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/embed.ts
  src/metabase/server/middleware/security.clj
  src/metabase/server/routes.clj
  test/metabase/server/middleware/security_test.clj
Labels: backport, .Team/Embedding

#61918 Only fetch embeddings when needed
  enterprise/backend/src/metabase_enterprise/semantic_search/index.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/pgvector_api.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/index_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/test_util.clj
Labels: .Team/Metabot

#61937 🤖 backported "fix(sdk): send CORS headers for error messages when embedding is disabled"
  e2e/test/scenarios/embedding-sdk/static-dashboard-cors.cy.spec.js
  e2e/test/scenarios/embedding/sdk-iframe-embedding/authentication.cy.spec.ts
  enterprise/backend/src/metabase_enterprise/sso/integrations/jwt.clj
  enterprise/frontend/src/embedding-sdk/errors/generic.ts
  enterprise/frontend/src/embedding-sdk/errors/jwt.ts
  enterprise/frontend/src/embedding/auth-common/connect-to-instance-auth-sso.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/embed.ts
  src/metabase/server/middleware/security.clj
  src/metabase/server/routes.clj
  test/metabase/server/middleware/security_test.clj
Labels: was-backported

#61767 Finish untangling the metadata knot
  modules/drivers/mongo/test/metabase/test/data/mongo.clj
  src/metabase/legacy_mbql/schema.cljc
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/breakout.cljc
  src/metabase/lib/card.cljc
  src/metabase/lib/column_group.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/equality.cljc
  src/metabase/lib/expression.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/field/resolution.cljc
  src/metabase/lib/field/util.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/join/util.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/metadata/result_metadata.cljc
  src/metabase/lib/metric.cljc
  src/metabase/lib/query.cljc
  src/metabase/lib/remove_replace.cljc
  src/metabase/lib/schema.cljc
  src/metabase/lib/schema/aggregation.cljc
  src/metabase/lib/schema/metadata.cljc
  src/metabase/lib/stage.cljc
  src/metabase/lib/table.cljc
  src/metabase/query_processor/middleware/add_implicit_joins.clj
  src/metabase/query_processor/preprocess.clj
  src/metabase/query_processor/store.clj
  src/metabase/query_processor/util/add_alias_info.clj
  src/metabase/query_processor/util/transformations/nest_breakouts.clj
  test/metabase/lib/aggregation_test.cljc
  test/metabase/lib/breakout_test.cljc
  test/metabase/lib/card_test.cljc
  test/metabase/lib/drill_thru/column_filter_test.cljc
  test/metabase/lib/drill_thru/underlying_records_test.cljc
  test/metabase/lib/drill_thru_test.cljc
  test/metabase/lib/equality_test.cljc
  test/metabase/lib/field/resolution_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/filter_test.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/metadata/calculation_test.cljc
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/remove_replace_test.cljc
  test/metabase/lib/schema/join_test.cljc
  test/metabase/lib/schema_test.cljc
  test/metabase/lib/stage_test.cljc
  test/metabase/lib/swap_test.cljc
  test/metabase/query_processor/middleware/remove_inactive_field_refs_test.clj
  test/metabase/query_processor/pivot_test.clj
  test/metabase/query_processor/preprocess_test.clj
  test/metabase/query_processor/util/transformations/nest_breakouts_test.clj
  test/metabase/query_processor_test/breakout_test.clj
  test/metabase/query_processor_test/count_where_test.clj
  test/metabase/query_processor_test/cumulative_aggregation_test.clj
  test/metabase/query_processor_test/explicit_joins_test.clj
  test/metabase/query_processor_test/field_ref_repro_test.clj
  test/metabase/query_processor_test/remapping_test.clj
Labels: backport, .Team/Querying

#61883 fix annoying tooltip on cartesian charts, pie, sankey
  frontend/src/metabase/visualizations/echarts/tooltip/index.tsx
  frontend/src/metabase/visualizations/visualizations/CartesianChart/CartesianChart.tsx
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-chart-events.ts
  frontend/src/metabase/visualizations/visualizations/CartesianChart/use-tooltip-mouse-leave.ts
  frontend/src/metabase/visualizations/visualizations/PieChart/PieChart.tsx
  frontend/src/metabase/visualizations/visualizations/SankeyChart/SankeyChart.tsx
Labels: backport, .Team/UXWest

#59324 Fix QP preprocessing middleware disabling Malli checks
  src/metabase/lib/schema/expression/temporal.cljc
  src/metabase/query_processor/preprocess.clj
Labels: no-backport, .Team/Querying

#61880 🤖 backported "Include columns that are not specifically excluded"
  src/metabase/query_processor/streaming.clj
  test/metabase/channel/render/table_test.clj
  test/metabase/query_processor/streaming_test.clj
Labels: was-backported

#61951 🤖 backported "Fix navigate forwards to a Details modal for QB"
  e2e/test/scenarios/models/models-metadata.cy.spec.js
  e2e/test/scenarios/question-reproductions/reproductions.cy.spec.ts
  frontend/src/metabase/query_builder/actions/core/core.ts
  frontend/src/metabase/query_builder/actions/navigation.ts
  frontend/src/metabase/query_builder/actions/object-detail.ts
Labels: was-backported

#61755 Fix revision history for old cards
  .clj-kondo/config/modules/config.edn
  src/metabase/queries/core.clj
  src/metabase/queries/models/card.clj
  src/metabase/revisions/impl/card.clj
  src/metabase/revisions/models/revision.clj
  test/metabase/queries/api/card_test.clj
  test/metabase/revisions/impl/card_test.clj
  test/metabase/revisions/models/revision_test.clj
Labels: backport, .Team/Querying, double-backport

#61940 fix: login_attrs -> jwt_attrs for jwt users
  resources/migrations/056_update_migrations.yaml
Labels: backport, .Team/UXWest

#61930 🤖 backported "fix(sdk): targetCollection should take precedence over recent dashboard"
  e2e/test-component/scenarios/embedding-sdk/reproductions/sdk-question-reproductions.cy.spec.tsx
  frontend/src/metabase/common/components/SaveQuestionForm/context.tsx
Labels: was-backported

#61966 🤖 backported "Add tests for custom elements attributes "
  e2e/test/scenarios/embedding/sdk-iframe-embedding/custom-elements-api.cy.spec.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/embed.ts
Labels: was-backported

#61939 Fix pivot tables in static embedding having white cell backgrounds in dark mode
  e2e/test/scenarios/embedding/embedding-dashboard.cy.spec.js
  frontend/src/metabase/dashboard/context/context.redux.ts
  frontend/src/metabase/dashboard/context/context.tsx
Labels: .Team/Embedding, double-backport

#61970 🤖 backported "test(embed-js): migrate tests to use custom element api"
  e2e/support/helpers/e2e-embedding-iframe-sdk-helpers.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding/authentication.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding/embed-options.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding/missing-tokens.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding/sdk-iframe-embedding.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding/theming.cy.spec.ts
Labels: was-backported

#61804 🤖 backported "[pivot] Implement optimized clj->js and use it when recalculating pivots on frontend"
  src/metabase/pivot/core.cljc
  src/metabase/pivot/js.cljs
  src/metabase/util/performance.cljc
Labels: was-backported

#61975 🤖 backported "[perf] Fix metabase.util.performance cljc-related issues"
  src/metabase/util/performance.cljc
  src/metabase/util/performance/jvm.clj
Labels: was-backported

#61979 Docs: fix examples in timezone docs
  docs/questions/query-builder/expressions/converttimezone.md
Labels: Type:Documentation, double-backport

#61981 🤖 backported "Docs: fix examples in timezone docs"
  docs/questions/query-builder/expressions/converttimezone.md
Labels: was-backported

#61850 [Semantic Search] Add AI Service as an embeddings providers
  .clj-kondo/config/modules/config.edn
  enterprise/backend/src/metabase_enterprise/metabot_v3/client.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/embedding.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/index.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/settings.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/embedding_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/index_embedding_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/test_util.clj
Labels: .Team/Metabot

#61943 [Lib] make `visible-columns` only work on stages
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/breakout.cljc
  src/metabase/lib/card.cljc
  src/metabase/lib/column_group.cljc
  src/metabase/lib/drill_thru/common.cljc
  src/metabase/lib/drill_thru/zoom_in_geographic.cljc
  src/metabase/lib/expression.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/filter.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/js.cljs
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/order_by.cljc
  src/metabase/lib/remove_replace.cljc
  src/metabase/lib/stage.cljc
  src/metabase/query_processor/middleware/add_implicit_joins.clj
  src/metabase/query_processor/middleware/annotate.clj
  src/metabase/query_processor/middleware/expand_macros.clj
  src/metabase/query_processor/middleware/metrics.clj
  src/metabase/query_processor/parameters/values.clj
  src/metabase/util/malli.cljc
  test/metabase/lib/card_test.cljc
  test/metabase/lib/field_ref_repro_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/metadata/calculation_test.cljc
  test/metabase/lib/metric_test.cljc
  test/metabase/query_processor_test/field_ref_repro_test.clj
Labels: backport, .Team/DevEx

#61645 fix(formatting): round compact numbers with Intl; preserve legacy k casing (closes #59454)
  frontend/src/metabase/lib/formatting/numbers.tsx
  frontend/src/metabase/lib/formatting/numbers.unit.spec.ts
Labels: no-backport

#61968 Update parameters section subtitle for questions in embed flow
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/SelectEmbedOptionsStep.tsx
Labels: backport, .Team/Embedding

#61991 🤖 backported "Update parameters section subtitle for questions in embed flow"
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/SelectEmbedOptionsStep.tsx
Labels: was-backported

#61602 [BOT-260] sem search consistency, gating and indexer loops
  .clj-kondo/config/modules/config.edn
  enterprise/backend/src/metabase_enterprise/semantic_search/core.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/db.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/env.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/gate.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/index.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/index_metadata.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/indexer.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/init.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/pgvector_api.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/task/indexer.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/db_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/gate_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/index_metadata_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/indexer_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/pgvector_api_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/test_util.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/without_init_test.clj
Labels: .Team/Metabot

#62014 🤖 backported "docs - add page title"
  docs/embedding/embedded-analytics-js.md
Labels: was-backported

#62013 🤖 backported "Archive deleted tables"
  resources/migrations/056_update_migrations.yaml
  src/metabase/sync/sync_metadata/tables.clj
  src/metabase/warehouse_schema/models/table.clj
  test/metabase/sync/sync_metadata/tables_test.clj
  test/metabase/sync/sync_test.clj
  test_resources/serialization_baseline/databases/My Database/tables/Schemaless Table/Schemaless Table.yaml
  test_resources/serialization_baseline/databases/test-data (h2)/schemas/PUBLIC/tables/CATEGORIES/CATEGORIES.yaml
  test_resources/serialization_baseline/databases/test-data (h2)/schemas/PUBLIC/tables/CHECKINS/CHECKINS.yaml
  test_resources/serialization_baseline/databases/test-data (h2)/schemas/PUBLIC/tables/ORDERS/ORDERS.yaml
  test_resources/serialization_baseline/databases/test-data (h2)/schemas/PUBLIC/tables/PEOPLE/PEOPLE.yaml
  test_resources/serialization_baseline/databases/test-data (h2)/schemas/PUBLIC/tables/PRODUCTS/PRODUCTS.yaml
  test_resources/serialization_baseline/databases/test-data (h2)/schemas/PUBLIC/tables/REVIEWS/REVIEWS.yaml
  test_resources/serialization_baseline/databases/test-data (h2)/schemas/PUBLIC/tables/USERS/USERS.yaml
  test_resources/serialization_baseline/databases/test-data (h2)/schemas/PUBLIC/tables/VENUES/VENUES.yaml
Labels: was-backported

#61954 🤖 backported "Fix revision history for old cards"
  .clj-kondo/config/modules/config.edn
  src/metabase/queries/core.clj
  src/metabase/queries/models/card.clj
  src/metabase/revisions/impl/card.clj
  src/metabase/revisions/models/revision.clj
  test/metabase/queries/api/card_test.clj
  test/metabase/revisions/impl/card_test.clj
  test/metabase/revisions/models/revision_test.clj
Labels: was-backported

#62017 🤖 backported "Enable DB routing for Athena"
  .github/workflows/drivers.yml
  enterprise/backend/test/metabase_enterprise/database_routing/e2e_test.clj
  modules/drivers/athena/src/metabase/driver/athena.clj
  modules/drivers/athena/test/metabase/test/data/athena.clj
Labels: was-backported

#61949 Enable DB routing for Starburst and Presto
  enterprise/backend/test/metabase_enterprise/database_routing/e2e_test.clj
  modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj
  modules/drivers/presto-jdbc/test/metabase/test/data/presto_jdbc.clj
  modules/drivers/starburst/src/metabase/driver/starburst.clj
Labels: backport, .Team/Querying, .Team/Drivers

#61947 Thread pool for semantic search index batch updates
  .clj-kondo/config.edn
  enterprise/backend/src/metabase_enterprise/semantic_search/index.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/settings.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/index_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/pgvector_api_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/test_util.clj
  src/metabase/permissions/models/collection/graph.clj
Labels: .Team/Metabot

#62023 Docs: Remove call to promo banner
  docs/embedding/securing-embeds.md
Labels: Type:Documentation, backport

#62027 🤖 backported "Docs: Remove call to promo banner"
  docs/embedding/securing-embeds.md
Labels: was-backported

#62030 🤖 backported "docs - fix typos"
  docs/dashboards/filters.md
Labels: was-backported

#61484 Bump thheller/shadow-cljs from 3.1.4 to 3.1.8
  deps.edn
Labels: no-backport

#60245 Bump cider/cider-nrepl from 0.55.7 to 0.57.0
  deps.edn
Labels: no-backport

#62004 Bump com.amazon.redshift/redshift-jdbc42 from 2.1.0.32 to 2.1.0.34
  modules/drivers/redshift/deps.edn
Labels: no-backport

#61780 Bump com.oracle.database.jdbc/ojdbc17 from 23.8.0.25.04 to 23.9.0.25.07
  modules/drivers/oracle/deps.edn
Labels: no-backport

#62025 🤖 backported "[Metabot] Remove non-streaming metabot code"
  enterprise/frontend/src/metabase-enterprise/api/metabot.ts
  enterprise/frontend/src/metabase-enterprise/metabot/components/MetabotChat/MetabotChat.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/hooks.ts
  enterprise/frontend/src/metabase-enterprise/metabot/metabot-streaming.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/metabot.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/state/actions.ts
  enterprise/frontend/src/metabase-enterprise/metabot/state/getPrevAgentResponse.ts
  enterprise/frontend/src/metabase-enterprise/metabot/state/reducer.ts
  enterprise/frontend/src/metabase-enterprise/metabot/state/selectors.ts
Labels: was-backported

#62026 🤖 backported "[Metabot] Remove non-streaming metabot code"
  enterprise/frontend/src/metabase-enterprise/api/metabot.ts
  enterprise/frontend/src/metabase-enterprise/metabot/components/MetabotChat/MetabotChat.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/hooks.ts
  enterprise/frontend/src/metabase-enterprise/metabot/metabot-streaming.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/metabot.unit.spec.tsx
  enterprise/frontend/src/metabase-enterprise/metabot/state/actions.ts
  enterprise/frontend/src/metabase-enterprise/metabot/state/getPrevAgentResponse.ts
  enterprise/frontend/src/metabase-enterprise/metabot/state/reducer.ts
  enterprise/frontend/src/metabase-enterprise/metabot/state/selectors.ts
Labels: was-backported

#61952 Collapse indexed-entity ids in semantic search results
  enterprise/backend/src/metabase_enterprise/semantic_search/index.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/index_metadata_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/index_test.clj
  src/metabase/search/appdb/core.clj
  src/metabase/search/core.clj
  src/metabase/search/util.clj
Labels: no-backport, .Team/Metabot

#59146 Bump babashka/fs from 0.5.25 to 0.5.26
  deps.edn
Labels: no-backport

#61941 🤖 backported "Finish untangling the metadata knot"
  modules/drivers/mongo/test/metabase/test/data/mongo.clj
  src/metabase/legacy_mbql/schema.cljc
  src/metabase/lib/aggregation.cljc
  src/metabase/lib/breakout.cljc
  src/metabase/lib/card.cljc
  src/metabase/lib/column_group.cljc
  src/metabase/lib/core.cljc
  src/metabase/lib/equality.cljc
  src/metabase/lib/expression.cljc
  src/metabase/lib/field.cljc
  src/metabase/lib/field/resolution.cljc
  src/metabase/lib/field/util.cljc
  src/metabase/lib/join.cljc
  src/metabase/lib/join/util.cljc
  src/metabase/lib/metadata/calculation.cljc
  src/metabase/lib/metadata/result_metadata.cljc
  src/metabase/lib/metric.cljc
  src/metabase/lib/query.cljc
  src/metabase/lib/remove_replace.cljc
  src/metabase/lib/schema.cljc
  src/metabase/lib/schema/aggregation.cljc
  src/metabase/lib/schema/metadata.cljc
  src/metabase/lib/stage.cljc
  src/metabase/lib/table.cljc
  src/metabase/query_processor/middleware/add_implicit_joins.clj
  src/metabase/query_processor/preprocess.clj
  src/metabase/query_processor/store.clj
  src/metabase/query_processor/util/add_alias_info.clj
  src/metabase/query_processor/util/transformations/nest_breakouts.clj
  test/metabase/lib/aggregation_test.cljc
  test/metabase/lib/breakout_test.cljc
  test/metabase/lib/card_test.cljc
  test/metabase/lib/drill_thru/column_filter_test.cljc
  test/metabase/lib/drill_thru/underlying_records_test.cljc
  test/metabase/lib/drill_thru_test.cljc
  test/metabase/lib/equality_test.cljc
  test/metabase/lib/field/resolution_test.cljc
  test/metabase/lib/field_test.cljc
  test/metabase/lib/filter_test.cljc
  test/metabase/lib/join_test.cljc
  test/metabase/lib/metadata/calculation_test.cljc
  test/metabase/lib/order_by_test.cljc
  test/metabase/lib/remove_replace_test.cljc
  test/metabase/lib/schema/join_test.cljc
  test/metabase/lib/schema_test.cljc
  test/metabase/lib/stage_test.cljc
  test/metabase/lib/swap_test.cljc
  test/metabase/query_processor/middleware/remove_inactive_field_refs_test.clj
  test/metabase/query_processor/pivot_test.clj
  test/metabase/query_processor/preprocess_test.clj
  test/metabase/query_processor/util/transformations/nest_breakouts_test.clj
  test/metabase/query_processor_test/breakout_test.clj
  test/metabase/query_processor_test/count_where_test.clj
  test/metabase/query_processor_test/cumulative_aggregation_test.clj
  test/metabase/query_processor_test/explicit_joins_test.clj
  test/metabase/query_processor_test/field_ref_repro_test.clj
  test/metabase/query_processor_test/remapping_test.clj
Labels: was-backported

#61250 Bump io.netty/netty-buffer from 4.2.1.Final to 4.2.3.Final
  modules/drivers/bigquery-cloud-sdk/deps.edn
Labels: no-backport

#60900 Bump io.github.seancorfield/build-uber-log4j2-handler from v2.24.0 to v2.25.1
  deps.edn
Labels: no-backport

#60246 Bump clj-http/clj-http from 3.13.0 to 3.13.1
  deps.edn
Labels: no-backport

#61776 Bump net.clojars.wkok/openai-clojure from 0.22.0 to 0.23.0
  deps.edn
Labels: no-backport

#59521 Bump com.facebook.presto/presto-jdbc from 0.292 to 0.293
  modules/drivers/presto-jdbc/deps.edn
Labels: no-backport

#61771 Bump clj-kondo/clj-kondo from 2025.04.07 to 2025.07.28
  deps.edn
  enterprise/backend/src/metabase_enterprise/audit_app/query_processor/middleware/handle_audit_queries.clj
  enterprise/backend/src/metabase_enterprise/sandbox/models/group_table_access_policy.clj
  enterprise/backend/src/metabase_enterprise/scim/v2/api.clj
  src/metabase/app_db/update_h2.clj
  src/metabase/lib/util.cljc
  src/metabase/queries/api/card.clj
  src/metabase/warehouse_schema/api/field.clj
  src/metabase/warehouse_schema/models/field.clj
  test/metabase/driver/impl_test.clj
  test/metabase/driver/sql_jdbc/connection_test.clj
  test/metabase/lib/util/match_test.cljc
Labels: no-backport

#62001 Bump org.eclipse.jetty/jetty-server from 12.0.22 to 12.0.24
  deps.edn
Labels: no-backport

#62061 🤖 backported "docs - field filter intro"
  docs/questions/native-editor/field-filters.md
Labels: was-backported

#61772 Bump com.github.seancorfield/honeysql from 2.7.1310 to 2.7.1340
  deps.edn
Labels: no-backport

#62024 Improved fallback logic & prometheus metrics for semantic search
  enterprise/backend/src/metabase_enterprise/semantic_search/core.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/index.clj
  enterprise/backend/src/metabase_enterprise/semantic_search/pgvector_api.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/core_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/pgvector_api_test.clj
  enterprise/backend/test/metabase_enterprise/semantic_search/test_util.clj
  src/metabase/analytics/core.clj
  src/metabase/analytics/prometheus.clj
Labels: .Team/Metabot

#62022 🤖 backported "Enable DB routing for Starburst and Presto"
  enterprise/backend/test/metabase_enterprise/database_routing/e2e_test.clj
  modules/drivers/presto-jdbc/src/metabase/driver/presto_jdbc.clj
  modules/drivers/presto-jdbc/test/metabase/test/data/presto_jdbc.clj
  modules/drivers/starburst/src/metabase/driver/starburst.clj
Labels: was-backported

#62072 Update menu items
  enterprise/frontend/src/metabase-enterprise/documents/components/Editor/extensions/Command/CommandSuggestion.tsx
Labels: .Team/AdminWebapp

#62074 docs: add saml to embed JS
  docs/embedding/embedded-analytics-js.md
Labels: Type:Documentation, backport

#61919 Fix CI workflows nesting and artifact download
  .github/actions/fetch-artifact/action.yml
  .github/actions/get-docker-info/action.yml
  .github/workflows/containerize-uberjar.yml
  .github/workflows/e2e-test.yml
  .github/workflows/perf-test.yml
  .github/workflows/pr-env.yml
  .github/workflows/run-tests.yml
  .github/workflows/uberjar-containerize-labeled.yml
  .github/workflows/uberjar.yml
Labels: no-backport, PR-Env, build-docker-uberjar

#62081 docs: DB routing new DBs
  docs/databases/connections/athena.md
  docs/databases/connections/bigquery.md
  docs/databases/connections/databricks.md
  docs/databases/connections/druid.md
  docs/databases/connections/mariadb.md
  docs/databases/connections/mongodb.md
  docs/databases/connections/mysql.md
  docs/databases/connections/postgresql.md
  docs/databases/connections/presto.md
  docs/databases/connections/redshift.md
  docs/databases/connections/snowflake.md
  docs/databases/connections/sql-server.md
  docs/databases/connections/sqlite.md
  docs/databases/connections/starburst.md
  docs/permissions/database-routing.md
Labels: Type:Documentation, backport

#62083 🤖 backported "docs: DB routing new DBs"
  docs/databases/connections/athena.md
  docs/databases/connections/bigquery.md
  docs/databases/connections/databricks.md
  docs/databases/connections/druid.md
  docs/databases/connections/mariadb.md
  docs/databases/connections/mongodb.md
  docs/databases/connections/mysql.md
  docs/databases/connections/postgresql.md
  docs/databases/connections/presto.md
  docs/databases/connections/redshift.md
  docs/databases/connections/snowflake.md
  docs/databases/connections/sql-server.md
  docs/databases/connections/sqlite.md
  docs/databases/connections/starburst.md
  docs/permissions/database-routing.md
Labels: was-backported

#62085 🤖 backported "docs - images and edits"
  docs/dashboards/filters.md
  docs/dashboards/images/add-section.png
  docs/dashboards/images/add_series.png
  docs/dashboards/images/apply-button.png
  docs/dashboards/images/wiring-cards.png
  docs/questions/query-builder/summarizing-and-grouping.md
Labels: was-backported

#61969 Show the allow download option for static questions on embed flow
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/select-embed-options.cy.spec.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/components/SelectEmbedOptionsStep.tsx
Labels: backport, .Team/Embedding

#62094 Default is-save-enabled to false on Embed JS and embed flow
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/select-embed-options.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/user-settings-persistence.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding/embed-options.cy.spec.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/components/SdkIframeEmbedRoute.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/constants.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/utils/default-embed-setting.ts
Labels: backport, .Team/Embedding

#62112 🤖 backported "Replace Asia/Saigon with Asia/Ho_Chi_Minh"
  test/metabase/driver/postgres_test.clj
  test/metabase/query_processor_test/date_time_zone_functions_test.clj
Labels: was-backported

#62015 Update channel test permission model
  e2e/runner/cypress-runner-backend.js
  enterprise/backend/test/metabase_enterprise/advanced_permissions/api/channel_test.clj
  src/metabase/channel/api/channel.clj
  src/metabase/channel/impl/http.clj
  src/metabase/channel/settings.clj
  src/metabase/util.cljc
  src/metabase/util/http.clj
  test/metabase/channel/api/channel_test.clj
  test/metabase/channel/impl/http_test.clj
  test/metabase/pulse/api/pulse_test.clj
  test/metabase/pulse/send_test.clj
  test/metabase/util/http_test.clj
Labels: backport, .Team/Workflows, double-backport

#62114 🤖 backported "Default is-save-enabled to false on Embed JS and embed flow"
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/select-embed-options.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding-setup/user-settings-persistence.cy.spec.ts
  e2e/test/scenarios/embedding/sdk-iframe-embedding/embed-options.cy.spec.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/components/SdkIframeEmbedRoute.tsx
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk/constants.ts
  enterprise/frontend/src/metabase-enterprise/embedding_iframe_sdk_setup/utils/default-embed-setting.ts
Labels: was-backported

#62110 fix: handle special cased migration
  src/metabase/app_db/liquibase.clj
  test/metabase/app_db/liquibase_test.clj
Labels: double-backport, .Team/UXWest

#62127 docs: clarify translations
  docs/embedding/translations.md
Labels: Type:Documentation, backport

#62129 docs: JSON unfolding
  docs/data-modeling/json-unfolding.md
Labels: Type:Documentation, backport

#61406 refactor(sdk): Adjust SDK CLI to work with Hosted Bundle
  enterprise/frontend/src/embedding-sdk/cli/snippets/analytics-dashboard-snippet.ts
  enterprise/frontend/src/embedding-sdk/cli/snippets/embedding-provider-snippet.ts
  enterprise/frontend/src/embedding-sdk/cli/utils/snippets-helpers.ts
Labels: no-backport, .Team/Embedding

#62132 data sandboxing -> row and column security
  docs/permissions/row-and-column-security.md
Labels: Type:Documentation, backport

#62130 🤖 backported "docs: clarify translations"
  docs/embedding/translations.md
Labels: was-backported

#62133 🤖 backported "data sandboxing -> row and column security"
  docs/permissions/row-and-column-security.md
Labels: was-backported
